### ISSUE TITLE
Unnamed imports in Ractive components (built to es6) don't get added

### ISSUE THREAD

**Issue by timshannon** [rollup/rollup#100]
I've thrown together a quick repository to show the issue I'm seeing:
[https://github.com/timshannon/rollup-ractive-issue](https://github.com/timshannon/rollup-ractive-issue)

As you can see from the repository, I'm using gobble to first build a ractive component into an es6 module, which I can then import into my main application file, and use Rollup to pull it all together into one JS file.

For the most part this works great until I try to take advantage of the import side effects as described in #13.  I can't seem to get Rollup to include any libraries imported in a Ractive component.

In the repository example above the component looks like this:
```
<div>
	component
</div>
<script>
import "../lib/standalone";

component.exports = {
};

</script>
```

with the `../lib/standalone` simply being an `alert("test");`

So if the entirety of my unnamed import is loaded with the component, then you should get an alert pop up when running `gobble`.  But if you check the built source, the alert is nowhere to be found.

Looking at the post ractive-component source, it looks correct to me.  And if I import the `standalone.js` in the main application file `index.js` the alert shows up / is imported fine.

I'm probably missing something obvious, so this may be more of a question than an issue.

Thanks,

**Comment by timshannon** [comment]
Oh, also, I'm converting from esperanto and it worked fine there.

**Comment by Victorystick** [comment]
That seems like a bug. @Rich-Harris, you're intimately familiar with both rollup and ractive, what's your take on this?

**Comment by timshannon** [comment]
So I took some time to try to figure this out, and I think I understand what's happening.  Not sure what the fix is though.

The component imports the entire standalone library which contains `alert("test");`
```
<div>
	component
</div>
<script>
import "../lib/standalone";
component.exports = {
};
</script>
```

So when the es6 module is built from this component it looks roughly like this
```
import Ractive from 'ractive';
var __options__ = {
  template: {v:3,t:[{p:[1,1,0],t:7,e:"div",f:["component"]}]},
},
component={},
__prop__,
__export__;

import "../lib/standalone";
component.exports = {
};


if ( typeof component.exports === "object" ) {
  for ( __prop__ in component.exports ) {
	  if ( component.exports.hasOwnProperty(__prop__) ) {
		  __options__[__prop__] = component.exports[__prop__];
	  }
  }
}

__export__ = Ractive.extend( __options__ );

export default __export__;

```

which rollup will replace with
```
import Ractive from 'ractive';
var __options__ = {
  template: {v:3,t:[{p:[1,1,0],t:7,e:"div",f:["component"]}]},
},
component={},
__prop__,
__export__;

alert("test");
component.exports = {
};


if ( typeof component.exports === "object" ) {
  for ( __prop__ in component.exports ) {
	  if ( component.exports.hasOwnProperty(__prop__) ) {
		  __options__[__prop__] = component.exports[__prop__];
	  }
  }
}

__export__ = Ractive.extend( __options__ );

export default __export__;

```

The issue being that the alert call is inserted properly, but it's not actually exported from the component, so rollup properly doesn't include it with anything that imports the component.
```
alert("test");
component.exports = {
};
```

The problem is now there is no way for me to include an unnamed import into a component.  Ractive will only include anything part of the component.exports section of the component, but imports have to be at the top.  It's not an issue with rollup necessarily, and I've been getting by with esperanto because it included everything regardless of it being exported or not.

**Comment by timshannon** [comment]
So I guess to put it another way, you can only import a module for it's side effects at the root of your build.

If
Root *-imports->* libA *-imports->* libB

libB can't be an unnamed import with side effects, because those side effects won't be exported up the chain to Root.  You can do it at libA though.

**Comment by timshannon** [comment]
After pulling the latest rollout, it looks like my issue in my main repository is fixed.  It appears the recent changes to tracking global mutations has allowed me to import my standalone libraries without issue now (as they all mutate global variables as their side effects).  I assume it's the closing of issue #112 that fixed my issue as well.

Thanks,

**Comment by Rich-Harris** [comment]
This issue totally flew under my radar – sorry @timshannon! Glad that it's behaving now.
