### ISSUE TITLE
Rollup is removing unused function from the entry file

### ISSUE THREAD

**Issue by alexcorvi** [rollup/rollup#1003]
My entry file has some unused function that should be called from inline HTML `onclick=""`. However when enabling tree-shaking, rollup is removing those function!

Is there a possible way to disable removing unused function with treeshaking enabled?

I'm using the Nodejs API btw.

[reproduction link](http://rollupjs.org/?version=0.36.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJmdW5jdGlvbiUyME5vdFVzZWRGdW5jdGlvbk5hbWUoKSU3QiU1Q24lMjAlMjByZXR1cm4lMjAlNUMlMjJhYmMlNUMlMjIlM0IlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q24lN0QlMjIlN0QlNUQlN0Q=)

**Comment by Victorystick** [comment]
When using ES6 modules, any unexported functions are not accessible outside the module they're defined in, so your onclick handler won't work unless you export the function. You can disable treeshaking with the `treeshake: false` option (see [the Wiki](https://github.com/rollup/rollup/wiki/JavaScript-API#treeshake)), but that doesn't really help you.

If you write something like,
```html
<button onclick='bundle.clickHandler()'>Click me!</button>
```
make sure to export the click handler.
```js
export function clickHandler(e) {
  ...
}
```
