### ISSUE TITLE
Allow importing of modules that don't use semicolons

### ISSUE THREAD

**Issue by matthieusieben** [rollup/rollup#1004]
There is a trend in the JS community to [abandon](http://standardjs.com/rules.html#semicolons) [semi](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding)-[colons](http://inimino.org/~inimino/blog/javascript_semicolons).

When appending a file that starts with an opening bracket (basically most external dependencies) after a file that relies on not using semi colons, the code breaks:
```js
// included from node_mobule/baz/no_semi_colons.js
const someString = "bla"
export default someString

// included from node_mobule/foo/bar.js
(function (global) {
  // blabla
})(typeof window === 'object' ? window : global);
```
The previous example will result in the following error: `Uncaught TypeError: someString is not a function`

Is there a way to avoid this?

**Comment by richarddewit** [comment]
> Is there a way to avoid this?

Write proper JS with semi-colons?

**Comment by matthieusieben** [comment]
Thank you for your comment. Sarcasm really helped me there.

Rollup recommends including the es2015 from external projects, some of which are written without semi colons. Maybe I should post your comment on all their repos so that I can start using your (otherwise quite nice) tool.

**Comment by TheBosZ** [comment]
From the subject, it sounds like you would want the generated bundle to not have semi-colons, is that correct? But the issue you're talking about looks more like the ability to import code that doesn't have semi-colons.

For the issue reported, it's possibly related to a bug mentioned in #1009

For generating a bundle with optional semi-colons, that's not a trivial thing to do and would probably have to include a large amount of rewriting to support it.

**Comment by matthieusieben** [comment]
My subject was poorly chosen indeed (I am not a native English speaker). 

The problem is not only with rollup not adding semi colons at the end of functions. The same runtime TpyeError also occurs when a file that starts with `(` or `[` is concatenated after a file that does not uses semi colons.

A workaround could be to write a plugin that checks the first char of each file, and if it is a (square) bracket, adds a semi colon before. Or apply a strategy that always adds a semicolon between files (since empty instructions are allowed in js), even though the generated code would be less elegant.

Whatever the solution, I believe it would be better to solve it in Rollup's core instead of a plugin.

Note that I am not trying to argue whether not using semicolons is a bad thing. JavaScript was so poorly designed that it allows several syntaxes, all of which we now have to support...

**Comment by TheBosZ** [comment]
Ah, yes! Maybe you could change the title of the issue to "Allow importing of modules that don't use semicolons". I think that would make it more clear.

Some other bundlers do as you suggest and always insert a semicolon between modules for just this reason. It does lead to empty statements but the minification step should remove them.

**Comment by matthieusieben** [comment]
Nice thanks!!

**Comment by Rich-Harris** [comment]
Released 0.36.2 with the fix

**Comment by lygstate** [comment]
Add leading semicolon before (function (global) {
for iife output.

**Comment by lygstate** [comment]
Give a option to output leading semicolon instead trailing semicolon.
Trailing semicolon not compitable with Standard JS.

**Comment by snuggs** [comment]
What about `void` @lygstate ? That's been my preference. Makes it up front and in your face that something is "different".

```javascript
void function () {} ()
```

**Comment by lygstate** [comment]
seems OK
