### ISSUE TITLE
renamed default exported function is still referred as original name 

### ISSUE THREAD

**Issue by ymzt** [rollup/rollup#1011]
Is this correct?  
I define constructor function named "Table", which is referred in argument of immediate function invocation ("Table.prototype").
In generated code, this function gets to be referred as "MyTable"
but argument is still refereed as original name "Table".
This results in run-time error.

source:

<pre>
import MyTable from './table.js'

var tbl = new MyTable();
console.log(tbl.name);
</pre>

<pre>
// "table" module file
export default function Table () {
  this.name = "aaa";
}
(function (proto) {
  proto.execute = function () {
    console.log("aa");
  }
})(Table.prototype);
</pre>

generated code:

<pre>
'use strict';

var MyTable = function Table () {
  this.name = "aaa";
}

(function (proto) {
  proto.execute = function () {
    console.log("aa");
  }
})(Table.prototype);

var tbl = new MyTable();
console.log(tbl.name);
</pre>

http://rollupjs.org/?version=0.36.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwTXlUYWJsZSUyMGZyb20lMjAnLiUyRm1hdGhzLmpzJyU1Q24lNUNudmFyJTIwdGJsJTIwJTNEJTIwbmV3JTIwTXlUYWJsZSgpJTNCJTVDbmNvbnNvbGUubG9nKHRibC5uYW1lKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBUYWJsZSUyMCgpJTIwJTdCJTVDbiUyMCUyMHRoaXMubmFtZSUyMCUzRCUyMCU1QyUyMmFhYSU1QyUyMiUzQiU1Q24lN0QlNUNuJTVDbihmdW5jdGlvbiUyMChwcm90byklMjAlN0IlNUNuJTIwJTIwcHJvdG8uZXhlY3V0ZSUyMCUzRCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJTVDJTIyYWElNUMlMjIpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QpKFRhYmxlLnByb3RvdHlwZSklM0IlNUNuJTVDbiUyMiU3RCU1RCU3RA==

**Comment by bfred-it** [comment]
I think that's what babel does too. `tbl.name` refers to the original name, not the name of the variable to which it's assigned. Same as

```js
const foo = function bar()  {}
foo.name === 'bar'
```

**Comment by Rich-Harris** [comment]
Released 0.38.2, which prints a warning in this situation
