### ISSUE TITLE
bundle.generate() produces sourcemap with absolute paths in sources

### ISSUE THREAD

**Issue by asapach** [rollup/rollup#1015]
See systemjs/builder#705

Starting with rollup@0.34 sourcemaps produced by `bundle.generate()` contain absolute paths in `sources` instead of relative URLs when input source maps are provided. Repro case: https://github.com/asapach/rollup-sourcemaps
Here's the example in it's entirety:

``` js
var rollup = require( 'rollup' );

rollup.rollup({
  entry: 'test.js',
  plugins: [{
    resolveId: function(id) {
      return id;
    },
    load: function(id) {
      return {
        code: 'export var foo = "bar";',
        map: {"version":3,"sources":["test.js"],"names":["foo"],"mappings":"AAAA,OAAO,IAAMA,MAAM,KAAZ","file":"test.js","sourcesContent":["export const foo = \"bar\";"]}
      };
    }
  }]
}).then(function (bundle) {
  var result = bundle.generate({
    sourceMap: true,
    moduleName: 'test',
    format: 'iife'
  });
  console.log(result.map.sources);
});
```

On my machine this outputs `[ 'C:/tmp/rollup-sourcemaps/test.js' ]`

It looks like this commit (5b4f70725dbee1a78063415adff3aaf70af1f03d) has introduced native `path.resolve()` instead of custom `resolve()` implementation. And now source path is resolved relative to `cwd`: https://github.com/rollup/rollup/blob/c5d9d347721ad3d168b2ca6df27894be69815d1c/src/utils/collapseSourcemaps.js#L121

This issue manifests itself differently when passing the `dest` option: the source path becomes relative, but still **relative to `cwd`**. Is this behavior intentional? How would you recommend handling this in tools that use `rollup` as a library?

**Comment by Rich-Harris** [comment]
Without a `sourceMapFile` or `dest` option (`dest` is used as `sourceMapFile` if the latter is missing), Rollup doesn't have much choice other than to use an absolute path (which isn't as useless as it sounds – subsequent tooling might manipulate the sourcemap further – though perhaps it should have a `file://` protocol prefix, and perhaps it should cause a warning to be emitted).

If you *do* have a `sourceMapFile` or `dest` option, the resulting sources are relative to that destination. So in your example, if we add this line...

```diff
}).then(function (bundle) {
  var result = bundle.generate({
    sourceMap: true,
+   sourceMapFile: 'bundle.js',
    moduleName: 'test',
    format: 'iife'
  });
  console.log(result.map.sources);
});
```

...then the result is `['test.js']`. If we do this instead...

```diff
-   sourceMapFile: 'bundle.js',
+   sourceMapFile: 'build/bundle.js',
```

...the result is `['../test.js']`. The CWD is irrelevant except insofar as that's what the `sourceMapFile` is resolved against.

This seems correct to me. How would you expect the behaviour to differ? (Genuine question – sourcemaps are a world of confusion, with subtle differences of opinion everywhere you look.)

**Comment by asapach** [comment]
@Rich-Harris, thanks, `sourceMapFile` explanation makes perfect sense. As for `file://` protocol, I'm afraid it's not as widely supported as relative paths, so I'd rather emit a warning.
The problem with using `path.resolve()`, is that it assumes that source files actually exist on disk under CWD, which is not necessarily true. For example this breaks down when sources use deep relative paths with backtracking, e.g. `../../../../foo.js` - if my CWD is `/home/johndoe/`, the resulting sourcemap will reference `../../foo.js`, since it will be normalized against the current path.
My expected behavior actually matches the previous implementation of `resolve()` util.

**Comment by Rich-Harris** [comment]
@asapach I think I understand the point about the `path.resolve` difference, but I'm struggling to come up with a test case — can you help? Thanks

**Comment by asapach** [comment]
The following test case comes to mind:
* Transform a file with existing source map
* One of the sources in the source map should have a relative path
* The relative path should be deep enough to hit a limit (say 20 levels up the tree) so that it would run into the CWD issue mentioned above on any/most systems
* The resulting source map after the transformation should have the same source with the same nesting level to verify the issue is fixed

I'll try to create the test case as a PR when I have the time.

**Comment by asapach** [comment]
@Rich-Harris, as promised here's the repro case: #1259.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
