### ISSUE TITLE
IIFE uses top-level this

### ISSUE THREAD

**Issue by deckar01** [rollup/rollup#1024]
The IIFE format ([src/finalisers/iife.js#L34](https://github.com/rollup/rollup/blob/152afb9732975188c7f4bf716c143da549afd432/src/finalisers/iife.js#L34)) uses `this` to reference the global context, which evaluates to `undefined` according to the spec. Some transpilers will replace top-level `this` with `undefined` and break the build. See #851 for a similar discussion.

#858 fixed #851 by adding a config variable specify how `this` should be replaced, but it does not seem to replace `this` usage introduced during finalization.

I skimmed over [Ben Alman's post about IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/), but his module pattern returns a single module instead of injecting the global context.

---

Current:

```js
(function (exports) {
  ...
}(this.Module = this.Module || {}));
```

---

Proposed:

```js
Module = (function (exports) {
  ...
  return exports;
}(typeof(Module) === 'undefined' ? {} : Module));
```

**Comment by bfred-it** [comment]
Also discussed in #827

**Comment by deckar01** [comment]
@bfred-it It doesn't look like `this` usage was discussed in #827. The proposed solution is very similar, but I am not trying to change the "extend module" behavior.

Here is an alternate solution to clarify:

```js
(function (exports) {
  ...
}(Module = typeof(Module) === 'undefined' ? {} : Module));
```

**Comment by Rich-Harris** [comment]
`this` only evaluates to `undefined` at the top level of an ES module. In scripts and CommonJS modules it evaluates to whatever the global object is. Are there situations where this is causing problems?

**Comment by deckar01** [comment]
I am currently targeting a single es6 file to be bundled in a rails pipeline using sprockets and transpiled by babel. It does seem odd that babel is configured to transpile the bundles in "module" mode even though sprockets doesn't support the es6 import/export syntax. I will open an issue in the sprockets repo to dig a little deeper.

Is there any benefit to using `this` for IIFE?

**Comment by deckar01** [comment]
It looks like the issue is that the project I am contributing to uses sprockets-es6, which didn't include a module loading framework, but when it got ported into sprockets 4 they baked in SystemJS.

Since IIFE isn't meant to be used in an es6 module, I will fork it for now and push them towards sprockets 4.

Thanks for your feedback @Rich-Harris.
