### ISSUE TITLE
Exported variables pollute global namespace

### ISSUE THREAD

**Issue by ntilwalli** [rollup/rollup#1027]
This is related to: https://github.com/rollup/rollup-plugin-commonjs/issues/127

The namespace pollution is caused by this line: https://github.com/rollup/rollup/blob/master/src/ast/nodes/ExportNamedDeclaration.js#L72

The link below demonstrates two issues:
1) The commonjs plugin can generate improper exports of vars which locally shadow global methods
2) Exported vars pollute the global namespace in the generated bundle

Demonstration: http://rollupjs.org/?version=0.36.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjByZXF1ZXN0QmFzZSU3RCUyMGZyb20lMjAnLiUyRm1vZHVsZV8xJyU1Q24lNUNuZnVuY3Rpb24lMjBCYXIoKSUyMCU3QiU1Q24lMjAlMjB0aGlzLl90aW1lb3V0JTIwJTNEJTIwMCUzQiU1Q24lN0QlNUNuJTVDbkJhci5wcm90b3R5cGUuY2xlYXJUaW1lb3V0JTIwJTNEJTIwcmVxdWVzdEJhc2UuY2xlYXJUaW1lb3V0JTVDbiU1Q25jb25zdCUyMHglMjAlM0QlMjBuZXclMjBCYXIoKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYqJTVDbkFjdHVhbCUyMHNuaXBwZXQlMjBvZiUyMGNvbW1vbmpzJTIwY29kZSUyMGZyb20lMjBzdXBlcmFnZW50LiU1Q24lNUNuJTIwJTIwZXhwb3J0cy5jbGVhclRpbWVvdXQlMjAlM0QlMjBmdW5jdGlvbiUyMF9jbGVhclRpbWVvdXQoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZyglNjBDYWxsaW5nJTIwbG9jYWwlMjBjbGVhclRpbWVvdXQlNjApJTNCJTVDbiUyMCUyMCUyMCUyMGNsZWFyVGltZW91dCh0aGlzLl90aW1lb3V0KSUzQiU1Q24lMjAlMjAlN0QlNUNuJTVDbkltcHJvcGVybHklMjBnZW5lcmF0ZWQlMjBjb2RlJTIwaXMlMjBiZWxvdy4uLiU1Q24lNUNuVHdvJTIwaXNzdWVzJTNBJTIwJTVDbjEpJTIwQ29tbW9uanMlMjBwbHVnaW4lMjBnZW5lcmF0ZXMlMjBhJTIwJTYwY2xlYXJUaW1lb3V0JTYwJTIwZXhwb3J0JTIwd2hpY2glMjBzaGFkb3dzJTIwdGhlJTIwZ2xvYmFsJTJGd2luZG93JTIwJTYwY2xlYXJUaW1lb3V0JTYwJTIwd2hpY2glMjBpcyUyMHdyb25nJTVDbiUyMCUyMCU1Q24yKSUyMFJvbGx1cCUyMGl0c2VsZiUyMGNvbnZlcnRzJTIwdGhlJTIwdGhlJTIwbW9kdWxlJ3MlMjBleHBvcnRlZCUyMChsb2NhbGx5JTIwc2hhZG93aW5nKSUyMCU2MGNsZWFyVGltZW91dCU2MCUyMGluJTIwYSUyMHdheSUyMHRoYXQncyUyMG5vdCUyMG1hbmdsZWQlMkZuYW1lc3BhY2VkJTIwaW4lMjB0aGUlMjBnZW5lcmF0ZWQlMjBidW5kbGUlMjBzbyUyMGl0JTIwc2hhZG93cyUyMHRoZSUyMGdsb2JhbCUyMCU2MGNsZWFyVGltZW91dCU2MCUyMGZvciUyMGFsbCUyMGNvbnN1bWVycyUyMG9mJTIwdGhlJTIwYnVuZGxlJTIwKHNlZSUyMHJpZ2h0JTIwcGFuZSklNUNuKiUyRiU1Q25mdW5jdGlvbiUyMGNyZWF0ZUNvbW1vbmpzTW9kdWxlKGZuJTJDJTIwbW9kdWxlKSUyMCU3QiU1Q24lNUN0bW9kdWxlJTIwJTNEJTIwJTdCJTIwZXhwb3J0cyUzQSUyMCU3QiU3RCUyMCU3RCUzQiU1Q24lMjAlMjAlMjAlMjBmbihtb2R1bGUlMkMlMjBtb2R1bGUuZXhwb3J0cyklM0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwbW9kdWxlLmV4cG9ydHMlM0IlNUNuJTdEJTVDbiU1Q252YXIlMjByZXF1ZXN0QmFzZSUyMCUzRCUyMGNyZWF0ZUNvbW1vbmpzTW9kdWxlKGZ1bmN0aW9uJTIwKG1vZHVsZSUyQyUyMGV4cG9ydHMpJTIwJTdCJTVDbiUyMCUyMGV4cG9ydHMuY2xlYXJUaW1lb3V0JTIwJTNEJTIwZnVuY3Rpb24lMjBfY2xlYXJUaW1lb3V0KCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY2xlYXJUaW1lb3V0KHRoaXMuX3RpbWVvdXQpJTNCJTIwJTJGJTJGJTIwaW1wcm9wZXJseSUyMHJlZmVycyUyMHRvJTIwaXRzZWxmJTVDbiUyMCUyMCU3RCU1Q24lN0QpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1Q25leHBvcnQlMjBkZWZhdWx0JTIwcmVxdWVzdEJhc2UlM0IlNUNuZXhwb3J0JTIwJTdCcmVxdWVzdEJhc2UlMjBhcyUyMF9fbW9kdWxlRXhwb3J0cyU3RCUzQiU1Q25leHBvcnQlMjB2YXIlMjBjbGVhclRpbWVvdXQlMjAlM0QlMjByZXF1ZXN0QmFzZS5jbGVhclRpbWVvdXQlMjAlMjAlMkYlMkYlMjBzaGFkb3dzJTIwJTVDbiUyMiU3RCU1RCU3RA==

**Comment by NeekSandhu** [comment]
How about bundling with IIFE? Or is it something else?

**Comment by Rich-Harris** [comment]
This is fixed with rollup-plugin-commonjs 6.0.1 – thanks
