### ISSUE TITLE
Default exports being included with "export *"

### ISSUE THREAD

**Issue by mairatma** [rollup/rollup#1028]
I started getting this `Conflicting namespaces` error after changing a file (let's say **file2.js**) to re-export everything from another file (**file1.js**), by using two export declarations:

``` js
import def from './file1';

export default def;      // Re-exports the default export.
export * from './file1'; // Re-exports all named exports.
```

Rollup then started complaining that there were `Conflicting namespaces` for the default export, as if **file1.js** was exporting it twice. I researched how `export *` should behave, and everwhere I looked it was treated as if it should only export named files, including transpilers like babel (see how they ignore default exports on purpose when converting ExportAllDeclaration [here](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-modules-commonjs/src/index.js#L36)).

Rollup seems to always include the default export with `export *` though. I used the demo page to build an example [here](http://rollupjs.org/?version=0.36.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGMlMjBmcm9tJTIwJy4lMkZmaWxlMiclM0IlNUNuaW1wb3J0JTIwJTdCYSUyQyUyMGIlN0QlMjBmcm9tJTIwJy4lMkZmaWxlMiclM0IlNUNuY29uc29sZS5sb2coJTIwYyUyQyUyMGElMkMlMjBiJTIwKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmaWxlMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGZmlsZTEnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZpbGUxLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMGElMjAlM0QlMjAxJTNCJTVDbnZhciUyMGIlMjAlM0QlMjAyJTNCJTVDbmV4cG9ydCUyMCU3QmElMkMlMjBiJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAzJTNCJTIyJTdEJTVEJTdE). Note how there's no build error, even though **file2.js** has no default export. If you remove the default export from **file1.js** you'll see the build fail though.

I think it's important that Rollup behave in the expected way regarding these exports. If I keep the `export default` line in my file I get these annoying warnings on Rollup, and if I remove it the code may not work on other transpilers anymore.

**Comment by Rich-Harris** [comment]
Finally fixed in 0.37. Thanks!
