### ISSUE TITLE
Caching Enhancement thoughts

### ISSUE THREAD

**Issue by stefanpenner** [rollup/rollup#1031]
The `cache` feature of rollup is great, but I believe it could be expanded further.
Right now, the cache is merely used to avoid the `transform` phase [here](https://github.com/rollup/rollup/blob/f43d63dc97b858b1604b2e99a52a5bd89757f6ff/src/Bundle.js#L255);

[But a later phase](https://github.com/rollup/rollup/blob/f43d63dc97b858b1604b2e99a52a5bd89757f6ff/src/Bundle.js#L273-L292) is also quite costly, but could very likely also be cached (or at-least partially cached).

This should really help let rollup scale to larger bundles, while maintaining a nice quick development feedback loop  for users of rollup.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
