### ISSUE TITLE
Firebase ionic2 and rollup - “rollup: Use of `eval` is strongly discouraged

### ISSUE THREAD

**Issue by adirzoari** [rollup/rollup#1034]
i have configured AngularFire2 according to this blog post: https://javebratt.com/ionic-2-firebase-3-facebook/
i'm getting this error

rollup: Use ofeval(in c:\XXX\node_modules\angularfire2\node_modules\firebase\firebase.js) is strongly discouraged, as it poses security risks and may cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details

this is my source code
```

`console.log("I'm the Hulk");// for test

var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');

// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: 'src/app/main.dev.ts',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',

  useStrict: false,
  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    builtins(),
    commonjs({
      include: [
        'node_modules/rxjs/**', // firebase needs rxjs to avoid build errors
        'node_modules/firebase/**', // here we're calling firebase.
        'node_modules/angularfire2/**' // here we're calling angularfire2.
      ],
      namedExports: {
        'node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
        'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database']
      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};


if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
  rollupConfig.sourceMap = false;
}


module.exports = rollupConfig;`

```

**Comment by marvinhagemeister** [comment]
This is not an issue with [rollup](https://github.com/rollup/rollup) but with `firebase`. As the message states: The use of `eval` is **strongly** discouraged and in pretty much all cases a security risk. Note that this is a warning generated by rollup when it receives such code, not an error. Your code will compile successfully.

**Comment by Rich-Harris** [comment]
[Here's a possible workaround](http://stackoverflow.com/a/39851383/2742396). Firebase really should change that code, since it's entirely unnecessary.

One possible action Rollup could take: we could add a `forceIndirectEval` (or something) option, which rewrote `eval(str)` as `[eval][0](str)`, or as `indirectEval(str)` with a `var indirectEval = eval` declaration at the top of the bundle. That would break any modules that are using `eval` dangerously (i.e. accessing current scope), while allowing cases like Firebase to continue working without the warning. Not sure if it's worth the effort though... thoughts welcome

**Comment by marvinhagemeister** [comment]
I'm happy with the current behaviour. It seems wrong to my put logic into rollup that tries to fix peoples code. If one hack gets added, more will surely follow for other libraries.

**Comment by Rich-Harris** [comment]
Yeah, I kind of agree. Will close this issue as there isn't anything for Rollup to do (FYI I've spoken with someone on the Firebase core team, they're going to look into this soon)

**Comment by Shyam-Chen** [comment]
```js
[...]
replace({  // 'rollup-plugin-replace'
  eval: '[eval][0]'
}),
[...]
```
