### ISSUE TITLE
try catch block is dropped

### ISSUE THREAD

**Issue by hbrls** [rollup/rollup#1039]
I have a repo illustrate this: [https://github.com/hbrls/rollup-try-catch-dropped](https://github.com/hbrls/rollup-try-catch-dropped)

Steps:
1. A plain require`var each = require('component-each');` [code](https://github.com/hbrls/rollup-try-catch-dropped/blob/master/lib/index.js#L7)
2. The `component-each` package I depend on uses a `try catch` block [code](https://github.com/component/each/blob/master/index.js#L6)
   
   ```
   try {
     var type = require('type');
   } catch (err) {
     var type = require('component-type');
   }
   ```
3. Run `npm run build` and check the result `dist/integration.js`. The `try catch` block is dropped. [code](https://github.com/hbrls/rollup-try-catch-dropped/blob/master/dist/integration.js#L274)

**Comment by thisconnect** [comment]
I suppose it is rollup-plugin-commonjs that drops the try catch.
Not 100% sure, but esmodules can not have conditional imports at runtime (afaik)

```js
// this can NOT be converted to es modules
var module = require(condition ? 'something' : 'otherlib')

// this can NOT be converted to es modules
if (condition){
  var lib = require('lib1')
} else {
  var lib = require('lib2')
}
```

Should this be documented on https://github.com/rollup/rollup/wiki/Troubleshooting ?

**Comment by Rich-Harris** [comment]
This is fixed in recent versions – closing. Thanks
