### ISSUE TITLE
Error building a cycle.js app

### ISSUE THREAD

**Issue by mindrones** [rollup/rollup#1040]
Hi, I'm getting an error when trying to build a cycle app with rollup.

Here's a super minimal repro: https://gist.github.com/mindrones/3894a4329ec15ac0c79c55da7a4a0cc7
To reproduce, in the gist dir: `npm install`, `npm run build`.

It reports a problem at line 78 of `node_modules/es5-ext/object/set-prototype-of/shim.js` which has only 73 lines of code, hence I'm assuming the error is happening in some wrapped code within rollup but I'm not sure. Can you shed some light on this?

Thanks!

**Comment by Victorystick** [comment]
This is an error caused by the CommonJS plugin; moving the issue there.

**Comment by Victorystick** [comment]
Just published version `5.0.5` of the CommonJS plugin. Please reopen this issue if the problem is not solved.

**Comment by mindrones** [comment]
Super! It works now, thanks a lot for the release!
