### ISSUE TITLE
Rollup can not resolve relative .d.ts

### ISSUE THREAD

**Issue by lygstate** [rollup/rollup#1049]
Error: Could not resolve 'math-lib' from C:\CI-Cor\acrop\acrop-client\src\pages\devicelist\devicelist.ts
    at Error (native)
    at C:\CI-Cor\acrop\acrop-client\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21

devicelist.ts

```
import { isPrime } from "math-lib";
```

`math-lib.d.ts` in the same folder as `devicelist.ts`

```
export function isPrime (x: number): boolean;
export as namespace mathLib;

```

**Comment by marvinhagemeister** [comment]
This has nothing to do with Rollup. For usage questions of typescript you should have a look at the official typescript documentation. If you're stuck with something, a great place to ask usage questions is stackoverflow. 

In your case the problem is that you try to import a `*.d.ts` file which makes no sense. Types are included via the `files` property in your `tsconfig.json`.

**Comment by PaulBGD** [comment]
This should be closed or moved to rollup-plugin-typescript if you INSIST this is a problem with rollup. More than likely it's an issue with your version of TypeScript.

**Comment by snuggs** [comment]
Agreed @PaulBGD

**Comment by Avnerus** [comment]
Hi! I ran into a similar issue and I was wondering about @marvinhagemeister's comment. I think when a .`d.ts` file is a module that uses `export` ([see documentation here](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html)) it should be valid to import from it? It seems rollup partially allow this. The typescript2 plugin successfully transpiles the importing module, and rollup accepts the import *unless* there is an attempt to call a declared function or class. For example, when using a `WebXR.d.ts` definitions file (there is only a .d.ts, no .ts):
The following works:
```
// WebXR.d.ts
export interface XRReferenceSpace extends XRSpace { 
...
}
```
```
// index.ts
import { XRReferenceSpace } from 'three/src/renderers/webxr/WebXR'

const baseReferenceSpace: XRReferenceSpace = this.xrManager.getReferenceSpace()
```
But this doesn't work:
```
// WebXR.d.ts
export declare class XRRigidTransform {
...
}
```
```
// index.ts
import { XRRigidTransform } from 'three/src/renderers/webxr/WebXR'

const xform = new XRRigidTransform(
...
);
```
Results in : `[!] Error: Could not load .three.js/src/renderers/webxr/WebXR (imported by index.ts): ENOENT: no such file or directory, open 'three.js/src/renderers/webxr/WebXR'`

I was even able to circumvent this problem by 'fooling' rollup to think that I'm not really using that declaration like so:
```
import { XRRigidTransform as XRRigidTransformDef } from 'three/src/renderers/webxr/WebXR
declare class XRRigidTransform extends XRRigidTransformDef {}

const xform = new XRRigidTransform(
...
);

```
I am quite new to typescript so might be missing something here, but any thoughts?
Thank you!
