### ISSUE TITLE
No name was provided for external module 'util' in options.globals – guessing 'util'

### ISSUE THREAD

**Issue by georgeedwards** [rollup/rollup#1051]
I am trying to introduce rollup into my angular2 build chain. However, I get the following issues:

```
No name was provided for external module 'events' in options.globals – guessing 'events'
No name was provided for external module 'util' in options.globals – guessing 'util'
```

Which seem to be breaking my bundle. The messages aren't particulalry helpful, I don;t know what util and events are, so don't know how to fix them. Is there any common wisdom to help me solve this, or could the error message be made more helpful?

**Comment by thisconnect** [comment]
Hi, those are node builtins 
https://nodejs.org/api/events.html
https://nodejs.org/api/util.html

Can you try https://www.npmjs.com/package/rollup-plugin-node-builtins ?

**Comment by thisconnect** [comment]
> Is there any common wisdom to help me solve this, or could the error message be made more helpful?

Not sure, maybe rollup could check for events, stream, path, querystring, url and so on and promote rollup-plugin-node-builtins in the warning.

**Comment by georgeedwards** [comment]
@thisconnect I think that would be really helpful. When using this I get:

```
Could not resolve 'process' from C:\Users\George\Source\Repos\docs\node_modules\rollup-plugin-node-builtins\src\es6\util.js
Error: Could not resolve 'process' from C:\Users\George\Source\Repos\docs\node_modules\rollup-plugin-node-builtins\src\es6\util.js
    at Error (native)
    at C:\Users\George\Source\Repos\docs\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21
    at C:\Users\George\Source\Repos\docs\node_modules\resolve\lib\async.js:46:14
    at process (C:\Users\George\Source\Repos\docs\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\George\Source\Repos\docs\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\George\Source\Repos\docs\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\George\Source\Repos\docs\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\George\Source\Repos\docs\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

**Comment by georgeedwards** [comment]
> maybe rollup could check for events, stream, path, querystring, url and so on and promote rollup-plugin-node-builtins in the warning.

@thisconnect I think that would be really useful.

**Comment by georgeedwards** [comment]
@thisconnect I am now getting issues with message:

>Uncaught ReferenceError: exports is not defined

The code it's referring to (below) seems to be part of Angular? Why is exports left in the bundle, and why does it look like the angular2 bit is being treated as a commonJS module, even though the AOT compiler compiled it as a es2015 module?

```
function createCommonjsModule(fn, module) {
	return module = { exports: {} }, fn(module, module.exports), module.exports;
}

var objectTypes = {
    'boolean': false,
    'function': true,
    'object': true,
    'number': false,
    'string': false,
    'undefined': false
};
exports.root = (objectTypes[typeof self] && self) || (objectTypes[typeof window] && window);
```

Here is my **rollup.config.js** file:

```
import rollup from 'rollup';
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify'
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';

export default {
  entry: 'client/main.js',
  dest: 'public/assets/js/build.es2015.js',
  sourceMap: false,
  format: 'iife',
  plugins: [
    globals(),
    builtins(),
    nodeResolve({ jsnext: true, module: true }),
    commonjs({
      include: [
        'node_modules/angular2-jwt/**',
        'node_modules/rxjs/**',
        'node_modules/auth0-lock/**',
        'node_modules/auth0-js/**',
      ]
    }),
    //uglify(),
  ]
}
```

**Comment by thisconnect** [comment]
I am unfamiliar with the `Uncaught ReferenceError: exports is not defined
 ` error. Is that in the browser console or does rollup throw that warning?

Not sure, my guess is that it's something found by nodeResolve, but not going through commonjs. Could you try to include the whole node_modules dir with 
 ```js
commonjs({
        include: 'node_modules/**'
})
```
?

`jsnext: true` should find the jsnext property in package.json and take the es modules defined there. If you use `jsnext: true` you would get es6 modules and eventually need to transpile to es5 with babel or buble. 

As far as I could see the modules angular2-jwt, rxjs, auth0-lock or auth0-js all distribute commonjs and non of them has a jsnext field.

**Comment by JulianGarciaCastillo** [comment]
I added to the problem, in my case I'm trying to use **sockJS**.
I'm on typescript 2. When I try to build I get this error:
```
[15:22:32]  rollup: Treating 'net' as external dependency 
[15:22:32]  rollup: Treating 'tls' as external dependency 
[15:22:46]  rollup: No name was provided for external module 'net' in options.globals – guessing 'net' 
[15:22:46]  rollup: No name was provided for external module 'tls' in options.globals – guessing 'tls' 
```
This is my **rollup.config.js**

```
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');


// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  entry: '{{SRC}}/app/main.dev.ts',
  sourceMap: true,
  format: 'iife',
  dest: 'main.js',

  plugins: [
    builtins(),
    commonjs({
      namedExports: {
        'node_modules/three/build/three.js':
        [
          'PerspectiveCamera',
          'Face3'
        ]
      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};

module.exports = rollupConfig;
```
I tried several configurations but I can't make it work.

**Comment by arjan674** [comment]
@JulianGarciaCastillo 
I have the same problem. Did you find the solution?

**Comment by JulianGarciaCastillo** [comment]
@arjan674 Nop. In the meantime I ended up placing the sockjs.js file directly in my project, but not a good solution for production.
 Including in my index.html: 
`<script src="assets/lib/js/sockjs.js"></script>`
Using it like this:
` let sockLocal = new SockJS(url, undefined, options);`

**Comment by Rich-Harris** [comment]
@georgeedwards @JulianGarciaCastillo can either of you [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

@thisconnect this is a great idea

> Not sure, maybe rollup could check for events, stream, path, querystring, url and so on and promote rollup-plugin-node-builtins in the warning

**Comment by Rich-Harris** [comment]
Warnings have been improved in 0.38.3, and will be improved further by #1194
