### ISSUE TITLE
Allow imports to resolve against certain file extensions

### ISSUE THREAD

**Issue by bretkikehara** [rollup/rollup#1052]
### issue

A user should be allowed to implicitly import files. In [utils/defaults.js](https://github.com/rollup/rollup/blob/152afb9732975188c7f4bf716c143da549afd432/src/utils/defaults.js#L9-L21), it seems that only files with `*.js` extension will correctly resolve. Thus, rollup doesn't work well with projects with JSX files even if the rollup babel plugin has been enabled to execute the JSX transpile to JS.

While renaming `foo.jsx` to `foo.js` ensures rollup plays well with JSX files and babel can do its job, this is in directly violation with eslint react default rule of [throwing errors for JSX files with the wrong extensions](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md).

Tries to solve:
https://github.com/rollup/rollup/issues/115
https://github.com/rollup/rollup-plugin-babel/issues/44,
### proposal

With PR #1053, module resolution should be user-configurable with fallback of `.js`. 

``` js
rollup.rollup({
  entry: 'main.js',
  extensions: [ '.js', '.jsx' ],
  plugins: [
    babel({ ... }),
  ],
})
```

**Comment by McPo** [comment]
Whats the status on this, running into this issue myself?

**Comment by Victorystick** [comment]
@bretkikehara If you specify the extension in the import, you can use whatever extension you please. @Rich-Harris has given several reasons ([here](https://github.com/rollup/rollup/issues/480#issuecomment-177520954) and further down in the thread) why extensionless imports are bad.

It's very unlikely that we'd add support for specifying extensions to Rollup core, especially since it's so easily solved with a plugin such as [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve). In fact, it's more likely that we'd remove the special-case of handling `.js` extensions altogether.

**Comment by McPo** [comment]
@victorystick if that's the case then I'd be for removing the special case of handling *.js, for consistency.

**Comment by Victorystick** [comment]
If what you want is to resolve certain file-extensions and want to avoid `node-resolve`, you can use a custom plugin.

```js
import extensions from './extensions.js';

export default {
  ...
  plugins: [
    extensions({
      extensions: [ '.jsx', '.foobar', '.etc' ],
    })
  ]
};
```

An implementation could look something like this. See [the Wiki](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins) for more info.

```js
import { basename, dirname, isAbsolute, resolve } from 'path';
import * as fs from 'fs';

function isFile ( file ) {
	try {
		return fs.statSync( file ).isFile();
	} catch ( err ) {
		return false;
	}
}

function addExtensionIfNecessary ( file, extensions ) {
	try {
		const name = basename( file );
		const files = fs.readdirSync( dirname( file ) );

		if ( ~files.indexOf( name ) && isFile( file ) ) return file;
		for ( const ext of extensions ) {
			if ( ~files.indexOf( `${name}${ext}` ) && isFile( `${file}${ext}` ) ) {
				return `${file}${ext}`;
			}
		}
	} catch ( err ) {
		// noop
	}

	return null;
}

export default function extensions ({extensions}) {
	if (!extensions || !extensions.length) {
		throw new Error( `Must specify { extensions: [..] } as non-empty array!` );
	}

	return {
		name: 'extensions',

		resolveId ( importee, importer ) {
			// absolute paths are left untouched
			if ( isAbsolute( importee ) ) {
				return addExtensionIfNecessary( resolve( importee ), extensions );
			}

			// if this is the entry point, resolve against cwd
			if ( importer === undefined ) {
				return addExtensionIfNecessary( resolve( process.cwd(), importee ), extensions );
			}

			// external modules are skipped at this stage
			if ( importee[0] !== '.' ) return null;

			return addExtensionIfNecessary( resolve( dirname( importer ), importee ), extensions );
		}
	};
}
```

**Comment by PierBover** [comment]
In case anyone stumbles upon this from Google (as I did) the solution is simply to use this official plugin:

https://github.com/rollup/plugins/tree/master/packages/node-resolve

```
resolve({
  extensions: ['.js', '.svelte', '.jsx', '.whatever']
})
```

**Comment by mayuratbillme** [comment]
Any update on this issue by using `rollup-plugin-babel` and not by using `node-resolve`?

**Comment by matthew-dean** [comment]
The problem with `@rollup/plugin-node-resolve` is that it resolves _both_ extensions AND `node_modules`-relative modules, and you may (such as in my case) want to exclude the latter. Ideally this would be a first-class concern of rollup.

**Comment by matthew-dean** [comment]
@Victorystick Any chance you would package your solution as a plugin on NPM?
