### ISSUE TITLE
[Bug] Ng2-charts breaks with Rollup

### ISSUE THREAD

**Issue by Luchillo** [rollup/rollup#1054]
Rollup is a pain in the ass, however Ionic 2 now wants it, seriously i have been fixing issues about Chart.js, comparev, signature_pad, intl and web-animations-js pollyfils, seems now is the time for this repo.

The error states like this:

![image](https://cloud.githubusercontent.com/assets/9698639/19369615/19ca3df8-916c-11e6-869f-63e839a10e76.png)

I'll be linking the issue from their repo:
https://github.com/valor-software/ng2-charts/issues/463

**Comment by sholladay** [comment]
> Rollup is a pain in the ass

That's not a good way to ask for help.

The "_x_ does not export _y_" category of error indicates there is almost certainly a problem with your code. Please post your code. Specifically your `app.module.ts`.

It looks like you are using TypeScript, which I'm not very familiar with. But I did `npm install ng2-charts` and took a look at `node_modules/ng2-charts/ng2-charts.js` and this is what I see.

```js
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
__export(require('./components/charts/charts'));
```

Clearly this is using Node.js / CommonJS modules, not ES2015 modules. Rollup is meant for ES2015 modules. Without being able to see your config, I'm guessing you are not using [`rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs) which is necessary to translate legacy modules into the new format.

If I am wrong and you are already using it, then maybe `exclude` is accidentally matching that file. Or maybe you are `import`ing it wrong. Are you doing `import { ChartsModules }` or `import ChartsModule`?

**Comment by snuggs** [comment]
Seems to work by using commonjs @sholladay /cc @Luchillo

**Comment by Luchillo** [comment]
@sholladay Sorry about that, after dealing with issues with 5 libs 1 by 1 i'm in a bit of a rage (almost rage quit), i'm dealing with something else so tomorrow i'll post the code.

**Comment by Luchillo** [comment]
Arrggg i have to learn to read, it is ChartModule**s**, in plural, that's really unexpected, almost all modules are exported as a single module that uses other modules.

**Comment by Luchillo** [comment]
@sholladay I'm importing as this:
```ts
import { ChartsModule } from 'ng2-charts/ng2-charts';
```
And the VSCode tslint is telling me that it is ok like that, also i'm putting that in the `declarations` part of the app module.

**Comment by sholladay** [comment]
Okay and you did take a look at [`rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs)? I'm pretty sure that is your missing piece. Or it is not configured correctly.

My understanding is that because `ng2-charts` is using this dynamic export pattern...

```js
exports[p] = m[p];
```

... you won't be able to use named imports (`import { ChartsModule }`...} by default.

I am basing that assertion on the limitations mentioned in the [Custom Named Exports](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports) section of the plugin docs. I believe you will have to do `import ng2Charts` instead (no curly braces). Try logging the object you get by importing it that way.

**Comment by nikrhes** [comment]
@sholladay hi,  I am already using the rollup-plugin-commonjs. but the error still occured.
this is my rollup name export:

`namedExports: {
          'node_modules/ng2-charts/ng2-charts.js': [ 'ChartsModule' ]
        }`

but still get the following error when run the rollup command

`Export 'ChartsModule' is not defined by '/Users/nikrhes/Documents/digi-aot/app/aot/app/app.module.ngfactory.js'
Export 'ChartsModule' is not defined by '/Users/nikrhes/Documents/digi-aot/app/aot/app/app.module.ngfactory.js'
'ChartsModule' is not exported by node_modules/ng2-charts/ng2-charts.js (imported by app/app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module`

Note: I am already import the ChartModule in app.module.ts

**Comment by sholladay** [comment]
Modify the `for` loop I mentioned above to log the values of `p`.

```js
function __export(m) {
    for (var p in m) {
        console.log('p:', p);
        if (!exports.hasOwnProperty(p)) exports[p] = m[p];
    }
}
```

Anything that prints can be used in the `namedExports` option. Anything it does not print won't work. Does it print "ChartsModule"?

**Comment by nikrhes** [comment]
@sholladay how is actually I am run the code to see the console.log?
