### ISSUE TITLE
Mixing imports and requires with Rollup.js best approach

### ISSUE THREAD

**Issue by fabm22** [rollup/rollup#1058]
Dumb question maybe, but just to be very clear:

It is possible to use (ie. = Rollup.js doesn't go against), at same time, in a file, ES6's ```import```s and common-js style ```require```s right ? 
I think of cases where you would require non-js ressources like html/css particularly (yet one can use imports for that too, https://www.npmjs.com/package/rollup-plugin-postcss) or is migrating code partially.  

For what I have quickly tested, by default Rollup.js simply doesn't care about what appears to him as a global "require" and simply does it thing, great.

So what would be the best, recommended, approach supported by Rollup.js to handle the require statements:

- NOT to use them at all and not mixing both, which would mean to systematically use a rollup-plugin like the one mentioned above.
- What seems logical, to use another non-Rollup.js plugin/dependency/bundler to handle those require *but then* what is the best way to still leverage as much as possible the tree-shaking of Rollup.js ? To pass the other bundler **before** of **after** Rollup ??

Thanks.

**Comment by Rich-Harris** [comment]
Mixing `import` and `require` is definitely discouraged. The only way for Rollup to handle `require` statements is with rollup-plugin-commonjs, but that plugin will skip any files with `import` or `export` statements.

Using two bundlers is totally sensible, if you have specific needs that aren't met by an ES module bundler. Just use `format: 'cjs'` and hand the result off to Browserify or Webpack, and you'll get the benefits of both (smaller, faster-to-execute bundle, but support for all the weird edge cases CommonJS presents). https://github.com/nolanlawson/rollupify might be worth a look too.

**Comment by fabm22** [comment]
Thanks for clarification. Closing.
