### ISSUE TITLE
Unused exports from other files not removed

### ISSUE THREAD

**Issue by DVLP** [rollup/rollup#1059]
For example I'll show THREE.JS which is using a file to pass exports from other files 

https://github.com/mrdoob/three.js/blob/dev/src/Three.js

Importing anything from this file causes all other exported modules to be included in final bundle. This should be prevented.

**Comment by Rich-Harris** [comment]
See https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working
