### ISSUE TITLE
Error parsing about double colon(bind operator)

### ISSUE THREAD

**Issue by lixinliang** [rollup/rollup#1060]
Hello,

I wrote a double colon(bind operator) syntax demo, [@see](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGxvZyUyMGZyb20lMjAnLiUyRmxvZy5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGxvZyklM0IlNUNuJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsb2cuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKHRoaXMpJTVDbiU3RCUyMiU3RCU1RCU3RA==)

Actually, it's not a part of ES6 standard. But it's work in babel es2015 stage-0, [@see](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0&code=let%20log%20%3D%20console.log%3B%0Aconsole%3A%3Alog%28123%29%3B)

In my case, I use the rollup to bundle js first, and transform es6 next by babel.
Is there anyway to ignore this error or skip it?

Like spread operator, [@see](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjB0ZXN0JTIwZnJvbSUyMCcuJTJGdGVzdC5qcyclM0IlNUNudGVzdCglMjAxJTJDMiUyQzMlMjApJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRlc3QuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKCUyMC4uLmFyZ3MlMjApJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZyhhcmdzKSU1Q24lN0QlMjIlN0QlNUQlN0Q=)
Keep the same look as before.

**Comment by Rich-Harris** [comment]
Rollup is a JavaScript bundler – you would need to transform the source code first, e.g. using rollup-plugin-babel
