### ISSUE TITLE
Static analysis to eliminate dead code

### ISSUE THREAD

**Issue by jknight12882** [rollup/rollup#1061]
`webpack` is able to do static analysis on the following UMD code to remove it while `rollup` leaves it behind. 

```
  // UMD wrapper.
  /*global define:false*/
  if (typeof exports === "object" && typeof module === "object") {
    // CommonJS
    module.exports = _lload;

  } else if (typeof define === "function" && define.amd) {
    // AMD
    define([], function () { return _lload; });

  } else {
    // VanillaJS
    window._lload = _lload;
  }
```

this should be replace by 

```
if (true) {
    // CommonJS
    module.exports = _lload;
    ...
```

which can then be eliminated

**Comment by Rich-Harris** [comment]
This is a two-parter – first, the commonjs plugin would need to rewrite the `typeof` expressions. Just opened https://github.com/rollup/rollup-plugin-commonjs/issues/151 for that.

Second, Rollup's dead code elimination would need to handle logical expressions in `if` block conditions. I thought it did, but apparently not – [this works](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaWYlMjAoJ29iamVjdCclMjAlM0QlM0QlM0QlMjAlNUMlMjJvYmplY3QlNUMlMjIpJTIwJTdCJTVDbiUyMCUyMG1vZHVsZS5leHBvcnRzJTIwJTNEJTIwZm9vJTNCJTVDbiU3RCUyMGVsc2UlMjBpZiUyMCh0eXBlb2YlMjBkZWZpbmUlMjAlM0QlM0QlM0QlMjAlNUMlMjJmdW5jdGlvbiU1QyUyMiUyMCUyNiUyNiUyMGRlZmluZS5hbWQpJTIwJTdCJTVDbiUyMCUyMGRlZmluZSglNUIlNUQlMkMlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTIwcmV0dXJuJTIwZm9vJTNCJTIwJTdEKSUzQiU1Q24lN0QlMjBlbHNlJTIwJTdCJTVDbiUyMCUyMHdpbmRvdy5mb28lMjAlM0QlMjBmb28lM0IlNUNuJTdEJTIyJTdEJTVEJTdE), but [this doesn't](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaWYlMjAoJ29iamVjdCclMjAlM0QlM0QlM0QlMjAlNUMlMjJvYmplY3QlNUMlMjIlMjAlMjYlMjYlMjAnb2JqZWN0JyUyMCUzRCUzRCUzRCUyMCU1QyUyMm9iamVjdCU1QyUyMiklMjAlN0IlNUNuJTIwJTIwbW9kdWxlLmV4cG9ydHMlMjAlM0QlMjBmb28lM0IlNUNuJTdEJTIwZWxzZSUyMGlmJTIwKHR5cGVvZiUyMGRlZmluZSUyMCUzRCUzRCUzRCUyMCU1QyUyMmZ1bmN0aW9uJTVDJTIyJTIwJTI2JTI2JTIwZGVmaW5lLmFtZCklMjAlN0IlNUNuJTIwJTIwZGVmaW5lKCU1QiU1RCUyQyUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlMjByZXR1cm4lMjBmb28lM0IlMjAlN0QpJTNCJTVDbiU3RCUyMGVsc2UlMjAlN0IlNUNuJTIwJTIwd2luZG93LmZvbyUyMCUzRCUyMGZvbyUzQiU1Q24lN0QlMjIlN0QlNUQlN0Q=).

**Comment by Rich-Harris** [comment]
Fixed in 0.38.3 and rollup-plugin-commonjs@7.0.0

**Comment by kzc** [comment]
Great stuff.

I guess the next logical step would be to add another bit of functionality to remove curly braces around blocks without `let` and `const`:
```js
{
	console.log( 'true' );
}
```
Or perhaps just leave that to the downstream minifier to deal with.

**Comment by Rich-Harris** [comment]
Yeah, I think Rollup should ideally remove the braces. Minifiers *will* remove them, so it's not a super high priority, but it does look weird if they're not removed. Not just `let` and `const`, I'm fairly sure `class` and `function` declarations are also block-scoped.

**Comment by Rich-Harris** [comment]
Think so yeah. Wouldn't even need to walk the BlockStatement since any declarations would have to be direct descendants of it, I think, so off the top of my head:

```js
const blockScopedDeclarations = block.children.filter( node =>
  /Declaration/.test( node.type ) && node.kind !== 'var' );

if ( blockScopedDeclarations.length === 0 ) {
  // remove curlies. for extra credit, deindent...
}
```
