### ISSUE TITLE
jQuery being included twice

### ISSUE THREAD

**Issue by moose56** [rollup/rollup#1063]
Hi,

I have an application where a number of my modules include jQuery and it is being included in the final bundle correctly:

``` javascript
var jquery_slim$1 = createCommonjsModule(function (module) {...})
```

I also include a 3rd party node module that has the following code at the start of it:

``` javascript
(function(factory){
    if (typeof define === "function" && define.amd) {
        define(["jquery"], factory);
    } else if (typeof exports === 'object') {
        factory(require('jquery'));
    } else {
        factory(jQuery);
    }
}
```

This causes a second copy of jQuery to be included in the final bundle:

``` javascript
var jquery_slim$2 = createCommonjsModule(function (module) {...})
```

Is there any way I can prevent the second copy from being imported?

**Comment by moose56** [comment]
I am using the includepaths plugin to set which jQuery file to use as I want the jquery.slim.js version.

Looking at the bundled file I can see that the slim version has been included twice.

The dependencies for the 3rd party node module are:

```javascript
"dependencies": {
    "jquery": ">=1.7.1"
}
```

and my project:

```javascript
"dependencies": {
    "jquery": "^3.1.0"
}
```

Is that the problem?

**Comment by PaulBGD** [comment]
Looking at NPM semvar it seems like the 3rd party should work with yours, but maybe rollup is still detecting it as 2 different ones. I'm not a rollup maintainer, these are just educated guesses.

**Comment by moose56** [comment]
Messed around with the version numbers and still no change unfortunately.

**Comment by Rich-Harris** [comment]
Deduping modules is npm's responsibility rather than Rollup's. As far as Rollup is concerned, if two dependencies resolve to different filenames, they're different things. You could forcibly resolve one instance to the other's filename, but it's quite possible that doing so would introduce bugs!

**Comment by moose56** [comment]
Thanks Rich.
