### ISSUE TITLE
Allow output as an Angular (1) module

### ISSUE THREAD

**Issue by dsample** [rollup/rollup#1064]
For compatibility reasons, we currently still use Angular 1. I've made my own simple compiler using EJS and Babel that can create CommonJS, AMD, ES6 and IIFE versions of my code, which can be easily achieved using Rollup instead. The problem stopping my adoption of Rollup though, is that my simple compiler also creates an Angular module.

Having taken a look at the finalisers, I can't work out what I'd need to do to create an Angular 1 output format, and even past that hurdle, I couldn't find a plugin that adds a finaliser, so that I could use it as an example to create my own plugin for it.

The output wrapper I'm looking for is something like:

``` javascript
(function () {
    <%- include('./lib/main.js') %>

    angular
        .module(angular._MODULE_)
        .service('moduleName', module);
})();
```

_Of course, with the relevant replacements, such as the EJS include being the real code, the module name (similar to UMD) and referencing the main export function from within the main code_

Any suggestions as to how this could be done would be appreciated.

**Comment by Victorystick** [comment]
@dsample Can you give a minimal example of a compilation? A before and after?

**Comment by Rich-Harris** [comment]
Related: #269

**Comment by bfred-it** [comment]
This can also be achieved with `--banner` and `--footer`:

```js
// index.js
export default 1;
```

```
$ rollup index.js --format iife --name module --banner '(function () {' --footer 'angular
.module(angular._MODULE_)
.service("moduleName", module);
})();' 
```

```js
// output
(function () {
var module = (function () {
'use strict';

var a = 1;

return a;

}());
angular
.module(angular._MODULE_)
.service("moduleName", module);
})();
```

**Comment by bfred-it** [comment]
... but only if it only exports `default`, because of #827:

```js
// index.js
export const a = 1;
export const b = 1;
```

```js
// output
(function () {
(function (exports) {
'use strict';

const a = 1;
const b = 1;

exports.a = a;
exports.b = b;

}((this.module = this.module || {}))); // `this` is wrong
angular
.module(angular._MODULE_)
.service("moduleName", module);
})();
```

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
