### ISSUE TITLE
export default something wrong

### ISSUE THREAD

**Issue by stephenkingsley** [rollup/rollup#1065]
I used rollup to build my project. 

in `rollup.js`

``` js
export default {
  entry: 'src/index.js',
  moduleName: 'awesomeRollup',
  external: ['react'],
  exports: 'named',
  globals: { react: 'React' },
}
```

in `src/index.js`

``` js
const func = () => {};
const awesomeRollup = (arg) => func();
awesomeRollup.a = (a) => func();
awesomeRollup.b = (b) => func();
awesomeRollup.c = (c) => func();
awesomeRollup.d = (d) => func();

export default awesomeRollup
export { func1, func2, func3 }
```

when I `console.log(awesomeRollup)` in chrome

``` js
object: {
    default: awesomeRollup,
    func1: function(){}
    func2: function(){}
    func3: function(){}
}
```

that is not my want, I want the export like

``` js
object: {
    a: function(){},
    b: function(){},
    c: function(){}, 
    func1: function(){}
    func2: function(){}
    func3: function(){}
}
```

**Comment by thisconnect** [comment]
then don't `export default` (which is commonjs equivalent to module.exports )

just do 
```js
export const a = 1
export const b = 1
export const c = 1

export const func1 = () => {}
export const func2 = () => {}
export const func3 = () => {}
```

http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGElMjAlM0QlMjAxJTVDbmV4cG9ydCUyMGNvbnN0JTIwYiUyMCUzRCUyMDElNUNuZXhwb3J0JTIwY29uc3QlMjBjJTIwJTNEJTIwMSU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBmdW5jMSUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTdEJTVDbmV4cG9ydCUyMGNvbnN0JTIwZnVuYzIlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU3RCU1Q25leHBvcnQlMjBjb25zdCUyMGZ1bmMzJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlNUNuJTIyJTdEJTVEJTdE

**Comment by yaycmyk** [comment]
This should be closed - OP is not understanding the module spec.

**Comment by thisconnect** [comment]
> not understanding the module spec.

yes, but many, including me, have never used es modules before rollup. In fact when I first visited http://rollupjs.org/ I felt it's time to start learning rollup+esmodules. So where else should newbies ask about es modules?

if you have any questions about es modules please ask tc39 ?  :)

**Comment by yaycmyk** [comment]
Stackoverflow
