### ISSUE TITLE
Sourcemap-aware transform sequence

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#107]
Via https://github.com/rollup/rollup-babel/issues/1:

> the `transform` sequence should always supply a string to the transformer and accept either a string or a `{ code, map }` object in return, and Rollup should take care of combining sourcemaps

At the moment it's a [dumb reduce](https://github.com/rollup/rollup/blob/b8894dd9014c2a6d54a66673f321b3acfb9821d2/src/utils/load.js#L7-L9), which leaves individual transformers at the mercy of whatever came before them. It's also tied to the `load` function, meaning that custom loaders (e.g. in-browser, from cache, whatever) have to reimplement `transform` (rollup-babel [suffers from this](https://github.com/rollup/rollup-babel/blob/2e0d91567aff40ce17eb76c472c670004fe72e12/index.js#L63-L82)).

Couple of other idle thoughts while I'm on the subject:

* it'd be nice if transformers were configurable. E.g. we might want to use an off-the-shelf transformer (not that such things currently exist) but only on files that match a certain minimatch pattern
* Long-term it'd be nice to be able to specify transforms via the CLI, a la Browserify transforms

**Comment by callumlocke** [comment]
Is this issue only about combining sourcemaps coming from 'transforms'?

What about when I'm not using rollup's transforms feature, but I'm using rollup as part of a sequence of build steps:

```
$ babel original.js | rollup | browserify > bundle.js
```

(I haven't bothered to write all the flags in but you get the point...) I've tried a variation of the above, and the final sourcemap seemed to take me back to the *output* of Babel, but not all the way back to the original file (when I debug in a browser, the code looks like Babel output). So it seems like browserify correctly notices the incoming sourcemap from rollup and combines it, but rollup doesn't do this.

Am I correct this hasn't been implemented or am I doing something wrong? If it's not implemented, should there be a separate issue for it?

**Comment by Rich-Harris** [comment]
I'm strongly of the opinion that transpilers and bundlers shouldn't attempt to account for incoming sourcemaps – it's a tricky thing to do (I've encountered some hairy bugs in the past with tools that attempt to do it), and it's senseless for everyone to reimplement the necessary logic. Instead, I think each tool should just worry about their own transformation step, and the entire chain of sourcemaps should be flattened at the end in a single step that goes all the way from `src` to `dist`. I wrote [sorcery](https://github.com/rich-harris/sorcery) to try and tackle this problem – you could try using it on `bundle.js` (`sorcery -i bundle.js`) to see if it can find the original sources. (YMMV!)

So yes, this issue is purely about ensuring that the sourcemap accompanying Rollup's output correctly points to its immediate input, without worrying about prior steps (such as Babel, though if we get this right you wouldn't have a separate step with Babel, rollup-babel would handle that for you – which is better because it means you can deduplicate helpers etc).

**Comment by callumlocke** [comment]
> I'm strongly of the opinion that transpilers and bundlers shouldn't attempt to account for incoming sourcemaps

Cool that makes sense now, I agree. But I still need to flatten sourcemaps myself, so I'm glad to hear about sorcery, it looks perfect! You've written several modules that have come to my rescue recently :+1:

**Comment by Rich-Harris** [comment]
This is implemented as of 0.19.0 – closing. @callumlocke hope sorcery works for you!

**Comment by creationix** [comment]
Works great using typescript (outputting ES6 + sourcemaps) + rollup (IIFE + sourcemap) + sorcery for me.   Now if only I can find a good minifier that handles ES6 code properly.
