### ISSUE TITLE
Option to throw on conflicting namespaces

### ISSUE THREAD

**Issue by chrbala** [rollup/rollup#1071]
I'm using rollup-plugin-multi-entry, and would like the build to fail if there are conflicting namespaces. Right now it just logs the error.

Is there an option to make rollup throw in this situation?

**Comment by Rich-Harris** [comment]
There isn't an option for this, no. The best bet would probably be to use a custom [`onwarn`](https://github.com/rollup/rollup/wiki/JavaScript-API#onwarn) option that intercepts the warning and throws if necessary. This will become a better option after https://github.com/rollup/rollup/issues/1194.

**Comment by Rich-Harris** [comment]
#1194 is implemented, which means the easiest way to handle this now is to have a custom `onwarn` handler that looks something like this:

```js
onwarn ( warning ) {
  if ( warning.code === 'NAMESPACE_CONFLICT' ) {
    throw new Error( warning.message );
  }
}
```
