### ISSUE TITLE
test karma rollup tape setup

### ISSUE THREAD

**Issue by thisconnect** [rollup/rollup#1072]
small repo (`karma` + `rollup` + `karma-rollup-plugin` + `tape`) https://github.com/thisconnect/test-karma-rollup-tape

<details>
  <summary>'default' is not exported by node_modules/tape/index.js (imported by test.js)</summary>

21 10 2016 14:13:52.097:DEBUG [plugin]: Loading inlined plugin (defining preprocessor:rollup).
21 10 2016 14:13:52.101:DEBUG [plugin]: Loading inlined plugin (defining launcher:Chrome, launcher:ChromeCanary, launcher:Chromium, launcher:Dartium, test).
21 10 2016 14:13:52.112:DEBUG [web-server]: Instantiating middleware
21 10 2016 14:13:52.141:DEBUG [preprocessor.rollup]: Processing "test-karma-rollup-tape/test.js".
21 10 2016 14:13:52.389:ERROR [preprocessor.rollup]: 'default' is not exported by node_modules/tape/index.js (imported by test.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

</details>

I tried using commonjs namedExports as described in the Troubleshooting#name-is-not-exported-by-module section of the wiki with no effect.

Should `rollup` + `rollup-plugin-commonjs` be able to understand `tape`'s exports
```js
exports = module.exports = (function () {
```
?
(see https://github.com/substack/tape/blob/092344b906cd3774ba1812d2db431e77916c9f19/index.js#L19 )

**Comment by thisconnect** [comment]
Going to use browserify tape first, and only use rollup for the actual test, as it seems rollup can not bundle tape.

**Comment by snuggs** [comment]
I"m confused. I use rollup and tape and test in memory. Am I missing something? @thisconnect

**Comment by thisconnect** [comment]
@snuggs could you paste your rollup config?

**Comment by thisconnect** [comment]
The nice thing about `tape` is that it doesn't magically add a global and can be bundled to run in the browser. Tape unfortunately does some lazy require stuff. This is why you use 
`const tape = require('tape')` instead of `import tape from 'tape'` in bubbletape [here](https://github.com/snuggs/buble-tape/blob/master/tape.es#L1) and [here](https://github.com/snuggs/buble-tape/blob/336b792c05fb7b89c3f0c717878e5320a20fe7dd/test.es#L7) and don't import [here](https://github.com/snuggs/buble-tape/blob/0da53d747635b35b67efc813621ec17700af453d/buble-tape.es#L31).

**Comment by thisconnect** [comment]
updated description
