### ISSUE TITLE
importing react-redux produces require() calls in IIFE output

### ISSUE THREAD

**Issue by dyakovlev** [rollup/rollup#1073]
I'm setting up a new project using Babel, React, Redux, and their associated helpers. When compiling an IIFE-type bundle, I'm seeing require() calls produced in the output. As I understand it, those should be expanded, aliased, or otherwise processed out when making bundles for browser consumption.

repo here: https://github.com/dyakovlev/redux-include-badness

bad lines:

```
    $ grep "require(" out.js
    <snip>
    var     getPrototype$1 = require('./_getPrototype');
    var     isObjectLike$1 = require('./isObjectLike');
```

These appear only when I import react-redux into my project, but I haven't been able to find anything more specific. Unclear if this should be here or in rollup-plugin-commonjs, also..

**Comment by kzc** [comment]
It's because `react-redux/src/components/connect.js` uses:

```
import isPlainObject from 'lodash/isPlainObject'
```
https://github.com/reactjs/react-redux/blob/68a4f2b78671329e10bfca87f8f1c82cc8690459/src/components/connect.js#L6

In turn `node_modules/lodash/isPlainObject.js` has:
```
var getPrototype = require('./_getPrototype'),
    isObjectLike = require('./isObjectLike');
```

`require()`s are being mixed with `import`s.

If `react-redux` were to use `lodash-es` instead of `lodash`:

https://github.com/reactjs/react-redux/search?utf8=✓&q=lodash

then it would work as expected:
```
import isPlainObject from 'lodash-es/isPlainObject'
```

Consider opening an issue on `react-redux`.

**Comment by dyakovlev** [comment]
Thanks! I will bounce this over there.

**Comment by dyakovlev** [comment]
actually, shouldn't `rollup-plugin-commonjs` and/or `babel` be transpiling the `require`s into es2015 imports? or am I misunderstanding the functionality of this toolchain?

**Comment by kzc** [comment]
Possibly. But require()s may include more code than necessary.

I don't see lodash in the commonjs section of your rollup config. Adding it might work.

**Comment by dyakovlev** [comment]
just tried that, now I'm getting this in the bundle:

```
module.exports = function hoistNonReactStatics(targetComponent, sourceComponent, customStatics) {
        if (typeof sourceComponent !== 'string') { // don't hoist over string (html) components
            var keys = Object.getOwnPropertyNames(sourceComponent);

            /* istanbul ignore else */
            if (isGetOwnPropertySymbolsAvailable) {
                keys = keys.concat(Object.getOwnPropertySymbols(sourceComponent));
            }

            for (var i = 0; i < keys.length; ++i) {
                if (!REACT_STATICS[keys[i]] && !KNOWN_STATICS[keys[i]] && (!customStatics || !customStatics[keys[i]])) {
                    try {
                        targetComponent[keys[i]] = sourceComponent[keys[i]];
                    } catch (error) {

                    }
                }
            }
        }

        return targetComponent;
    };
```

which breaks the bundle due to `module.exports` usage.

**Comment by kzc** [comment]
Which is why it is probably better to open an issue on `react-redux` to use `lodash-es` instead of `lodash`.

**Comment by kzc** [comment]
`redux` has the same lodash import:

https://github.com/reactjs/redux/blob/0139a9601dae810db533762c2bc4a745a37d4cf6/src/combineReducers.js#L2

This is how `redux` handles it:

https://github.com/reactjs/redux/blob/85e2368ea9ff9b308fc873921ddf41929638f130/build/use-lodash-es.js

https://github.com/reactjs/redux/blob/85e2368ea9ff9b308fc873921ddf41929638f130/.babelrc#L32

Ultimately they're doing the same thing as I suggested above - replacing `lodash` with `lodash-es`, albeit in a more circuitous fashion involving a babel plugin.

**Comment by kzc** [comment]
@dyakovlev Please try this:
```patch
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -32,7 +32,10 @@ export default {
          namedExports: {
          }
        }),
-       replace({ 'process.env.NODE_ENV': JSON.stringify('development') }),
+       replace({
+         'process.env.NODE_ENV': JSON.stringify('development'),
+         "lodash/": "lodash-es/",
+       }),
        resolve({ jsnext: true, browser: true, main: true })
   ]
 }
```

**Comment by btd** [comment]
Maybe it will help. I did PR for react-redux to include modules export to npm (it will be published to next version). For myself i created react-redux-es, while waiting for next version where it will be available.

**Comment by kzc** [comment]
FWIW, the `replace({"lodash/": "lodash-es/"})` hack above works.

Thanks @btd I saw react-redux-es after the fact. It appears to be doing more or less the same thing at the module level.

I marvel at the lengths ES6 devs go to combine different libraries - each with their own build quirks.

**Comment by dyakovlev** [comment]
thanks for the help, everyone. I've gotten it to work a slightly different way - updating to `next` version of react-redux (which uses lodash-es internally) and adding `react-dom`, `hoist-non-react-statics`, and `invariant` to the cjs loader's include list.

FWIW I tried replacing lodash with lodash-es as kzc suggested, and ended up with a bunch of `module.exports` assignments. 

kzc - ES6 packaging is definitely a very young, scary place. thanks for the help!

I'm closing this issue as there is nothing really actionable to rollup from it.

**Comment by kzc** [comment]
Glad you got it working through another means.

> adding react-dom, hoist-non-react-statics, and invariant to the cjs loader's include list.

Your exports fix seems to be equally applicable to make the way above work as well:
```patch
diff --git a/rollup.config.js b/rollup.config.js
index 7c104fb..b7612dc 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -28,11 +28,14 @@ export default {
            'node_modules/react/**',
            'node_modules/react-dom/**',
            'node_modules/react-redux/**',
+           'node_modules/hoist-non-react-statics/**',
+           'node_modules/invariant/**',
          ],
          namedExports: {
          }
        }),
        replace({ 'process.env.NODE_ENV': JSON.stringify('development') }),
+       replace({ "lodash/": "lodash-es/" }),
        resolve({ jsnext: true, browser: true, main: true })
   ]
 }
```
Before patch above:
```
$ grep module.exports out.js
	return module = { exports: {} }, fn(module, module.exports), module.exports;
module.exports = function hoistNonReactStatics(targetComponent, sourceComponent, customStatics) {
module.exports = invariant$39;
```
After patch:
```
$ grep module.exports out.js
	return module = { exports: {} }, fn(module, module.exports), module.exports;
```
I never actually ran it though.

**Comment by dyakovlev** [comment]
interesting. when I tried it, s/lodash/lodash-es/g caused rollup to quietly bundle up untranspiled stuff, but updating react-redux to the beta version produced import complaints that actually allowed me to find the missing cjs includes.

**Comment by kzc** [comment]
Seems to have transpiled from ES6 to ES5. `uglifyjs out.js -c -m` ran without error indicating it's ES5 clean. I can appreciate that debugging the build errors is not an exact science.
