### ISSUE TITLE
Babel plugin's options are sticking

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#1080]
I'm not sure if this is an issue with Rollup Core, or the Babel plugin.  Rich Harris said core would be the place to open the issue, so here I am.

The code below should be what I was running at the time: whichever plugin state was generated by the first call to getRollup, via the extHelpers flag "stuck" and applied to subsequent calls, even if extHelpers changed.  This issue persisted even if I ran these calls sequentially.

If this is insufficient to repro the issue, I'd be happy to put together a repo doing so.  Just let me know.  (I've already worked around this, but I'm happy to help however I can)

``` javascript
const getRollup = (entry, extHelpers) =>
    rollup.rollup({
        entry,
        plugins: [
            babel({
                presets: ['react', ['es2015', { modules: false }], 'stage-2'],
                plugins: extHelpers ? ['external-helpers'] : []
            }),
            alias({
                resolve: ['.es6'],
                './buttonDropdown.js': './buttonDropdown'
            })
        ]
    });
```

**Comment by Rich-Harris** [comment]
Sorry for non-response – if you could provide a repro that'd be great, because I'm not sure what's going on here. It looks like it should work.
