### ISSUE TITLE
Rollup-watch could not be found (installed globally)

### ISSUE THREAD

**Issue by joe223** [rollup/rollup#1082]
> rollup --watch depends on the rollup-watch package, which could not be found. You can install it globally (recommended) with npm install -g rollup-watch

But, actually I did. This is infomation

```
➜  lib git:(ec2f450) ✗ pwd
/home/joe/.nvm/versions/node/v6.2.2/lib
➜  lib git:(ec2f450) ✗ npm ls | grep rollup
├─┬ rollup-watch@2.5.0
➜  lib git:(ec2f450) ✗ ls
node_modules
➜  lib git:(ec2f450) ✗ npm -v
3.9.5
```

**Comment by thisconnect** [comment]
> > rollup --watch depends on the rollup-watch package

Are you sure this is correct?

see rollup cli options https://github.com/rollup/rollup/wiki/Command-Line-Interface

**Comment by joe223** [comment]
@thisconnect 
>➜  blade git:(master) ✗ rollup -w -i ./src/blade.js -o ./dist/blade.js
rollup --watch depends on the rollup-watch package, which could not be found. You can install it globally (recommended) with npm install -g rollup-watch
Is there something incorrect? I have already installed rollup-watch globally

**Comment by joe223** [comment]
It's solved. Use  install `rollup-watch` locally。

**Comment by jonataswalker** [comment]
Locally is the way to go, I can confirm, globally is not been found by rollup. Maybe we should change the **recommended message**?

**Comment by joe223** [comment]
Accurate recommended message would be better.

**Comment by Rich-Harris** [comment]
Closing in favour of https://github.com/rollup/rollup-watch/issues/34. Agree, local installation probably makes more sense.
