### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by Immortalin** [rollup/rollup#1093]
I am getting a `buffer is undefined` error in the browser when loading [Github.js](https://github.com/michael/github). This issue was resolved by turning off preferbuiltins in the config. However, now I am facing issues regarding Base64 encoding with the following error:
<details>
<summary> Browser Console Stacktrace</summary>
Uncaught TypeError: Cannot read property 'encode' of undefined
</details>

Here's the repo:
https://github.com/Immortalin/Orwell (App can be started with [live-server](https://github.com/tapio/live-server))

**Comment by thisconnect** [comment]
AFAIK as you disable builtins you would need
- https://github.com/calvinmetcalf/rollup-plugin-node-globals
- https://www.npmjs.com/package/rollup-plugin-node-builtins

seems that you already have the globals but you don't use them in plugins
https://github.com/Immortalin/Orwell/blob/master/rollup.config.js

**Comment by Rich-Harris** [comment]
The repro appears to have vanished?
