### ISSUE TITLE
Separate vendor bundle

### ISSUE THREAD

**Issue by m0onspell** [rollup/rollup#1094]
Can we have [that](https://github.com/sogko/gulp-recipes/tree/master/browserify-separating-app-and-vendor-bundles) with `rollup`?
We have an `external` option, but it will just add `require` calls for external bundles.
How can we build a vendor bundle and link it to the main one?

**Comment by bfred-it** [comment]
Sounds like #372

**Comment by m0onspell** [comment]
Exactly.

**Comment by caub** [comment]
I've put an example here https://github.com/caub/color-wheel/tree/master/demo, 

It's not so practical because I make this useless https://github.com/caub/color-wheel/tree/master/demo/vendor.js file as entry, they'll end up in chunk1:
```
 921K mars  28 01:15 chunk1.js
 5,3K mars  28 01:15 index.js
  101 mars  28 01:15 vendor.js
```

**Comment by lukastaegert** [comment]
#2084 will provide an even better way of doing this.

**Comment by aharpervc** [comment]
> It's not so practical because I make this useless https://github.com/caub/color-wheel/blob/0b1f61457ad805ad6f8d04d81ad37fc678c06c2d/demo/vendor.js file as entry, vendor deps end up in chunk1:

Is this still the best way to put node_modules vendor dependencies in a separate bundle? I reviewed #2084 but I could not figure out how to get rollup to do this automatically

**Comment by bfred-it** [comment]
People wanting to extract _vendors_ into a separate file should re-consider why they're doing it.

The original reasoning was that vendors rarely change and so they can be cached for longer, but generated bundles are not always the same, even if the vendors haven't changed.

If this was the only reason you're blindly extracting _vendors_ you're shooting yourself in the foot (now the browser has to load 2 files to do one thing).

Look into per-feature lazy loading instead.

**Comment by aharpervc** [comment]
> generated bundles are not always the same, even if the vendors haven't changed

Whoa, that's concerning, I had no idea that rollup wouldn't produce the same output every time for the same input. Why would this be happening?

> If this was the only reason you're blindly extracting vendors you're shooting yourself in the foot (now the browser has to load 2 files to do one thing).

It's not the only reason, but even if it were, that wouldn't necessarily be a bad thing. And believe me there's a more than 2 files being loaded in my case anyway.

There's several reasons to want 3rd party code separated out from app code into at least one bundle. Overall file bundle size, debuggability, minimizing bundle changes when compiling (as you said), etc. I'm not really interested in refactoring my whole app for dynamic imports right now. I basically just want what webpack does.

**Comment by bfred-it** [comment]
> rollup wouldn't produce the same output every time for the same input. Why would this be happening?

I don’t know for certain that it happens in rollup, but that’s what I experienced in webpack and browserify due to changing module IDs, for example (the 1, 2, 3, ... numbers that appear in the bundle). Rollup _might_ just happen to have a different variable name to avoid conflict, for example, just because you used the same variable name in a separate module.

**Comment by lukastaegert** [comment]
As Rollup does not add any runtime environment code, module id issues do not apply here. I’m not 100% sure about variable renaming issues. The code can still change, though, due to tree-shaking. I.e. depending on what your own code uses from your vendor bundle, different parts can be removed.

**Comment by aharpervc** [comment]
> The code can still change, though, due to tree-shaking

Oh, that makes sense. And it's kind of different input anyway. I was thinking that like back to back executions of `rollup -c` would have different outputs.

**Comment by aharpervc** [comment]
I should also have clarified that my situation is generating application bundles. I can totally understand why you only need/want a single bundle for a library.

**Comment by TheDirigible** [comment]
A different output for tree-shaken vendor files would still be nice, as it could then be blacklisted during debugging.  There doesn't seem to be a way to specify manual code splitting in rollup.

**Comment by lukastaegert** [comment]
`manualChunks` have been added to achieve just that: https://rollupjs.org/guide/en/#manualchunks

**Comment by TheDirigible** [comment]
I tried to use the basic example of
`manualChunks: {
  lodash: ['lodash']
}`
but I got the error "parserError: SyntaxError: 'import' and 'export' may only appear at the top level"

**Comment by shellscape** [comment]
@TheDirigible an error message without a reproduction isn't of much use. Since that error message doesn't appear in Rollup core, you probably have a plugin issue. This would not be the right place to report that error.

**Comment by TheDirigible** [comment]
I'll just report the issue of a general lack of working examples making this much harder to use.  After a couple hours trying to get this working I started with a simplified build, and now I see this: "Error: UMD and IIFE output formats are not supported for code-splitting builds."  So this won't even work for me.  I don't know why that didn't show up before, would have been nice to see it in the docs 2 hours ago.
