### ISSUE TITLE
Rollup on node 0.10

### ISSUE THREAD

**Issue by ichernev** [rollup/rollup#1095]
Hello, I'm the maintainer of https://github.com/moment, and we're migrating to rollup (+babel).

Apparently rollup is not compatible with node 0.10 (https://travis-ci.org/moment/moment/jobs/172510860)

```
/home/travis/build/moment/moment/node_modules/rollup/dist/rollup.js:62
	for ( var item of map.entries() ) {
	               ^^
Loading "transpile.js" tasks...ERROR
>> SyntaxError: Unexpected identifier
```

I know the version is old, but that means no other project using `rollup` can be properly tested on it, which means eventually it will stop working.

I don't want to stop support for 0.10, just because we rewrote our build (which is completely irrelevant for our users).

Can you pass the whole thing through babel and add another `dist` file for compatibility?

**Comment by kzc** [comment]
See #1036

You could change the target to 0.10 here: 

https://github.com/rollup/rollup/blob/master/rollup.config.js#L24-L29

But not sure if you'd need to fork rollup to accomplish that.

**Comment by ichernev** [comment]
Thank you!

**Comment by kzc** [comment]
You may want to upgrade `buble` to the latest version as it's pretty out of date:

https://github.com/rollup/rollup/blob/master/package.json#L51
