### ISSUE TITLE
Error: SyntaxError: Unexpected strict mode reserved word.

### ISSUE THREAD

**Issue by sumitknoldus** [rollup/rollup#1096]
Hi guyz , 

**Below is the link for full description of the error occurence:** 
http://stackoverflow.com/questions/40374911/error-syntaxerror-unexpected-strict-mode-reserved-word

**For building the angular2 app for production I'm following below link:**
http://blog.mgechev.com/2016/06/26/tree-shaking-angular2-production-build-rollup-javascript/

warm regards

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)
