### ISSUE TITLE
Bundle error with node-iconv

### ISSUE THREAD

**Issue by larssn** [rollup/rollup#1097]
I'm trying to bundle iconv from a typescript project (Ionic 2), and I get the error:
`bundle failed: Unexpected character '�' (1:0) in /node_modules/iconv/build/Release/iconv.node `

iconv.node seems to be a binary file.

Reproduce:
```
npm install iconv
npm install @types/iconv
```

In a ts file:
```
import Iconv from 'iconv';

export class test {
   constructor() {
      let iv = Iconv('UTF-8', 'CP1252');
   }
}
```

**Comment by Rich-Harris** [comment]
`.node` files can't be bundled, you would need to use the `external: [ 'iconv' ]` option ([docs](https://github.com/rollup/rollup/wiki/JavaScript-API#external)).

**Comment by larssn** [comment]
Thanks.

Ended up using iconv-lite, but if I for any reason need to go back, I'll consider it.
Gonna lose this.
