### ISSUE TITLE
How to bundle Node packages for Browser?

### ISSUE THREAD

**Issue by corysimmons** [rollup/rollup#1098]
Please add Wiki page for this...

Use case:
I'm trying to make an interactive playground for a Node package I made. Basically I want to be able to edit css in a textbox, and have it run through a postcss plugin, and apply those styles to the page.

I can do the last half (DOM interaction) and got this working pretty quickly with Browserify, but Browserify bundles 500megs so I figured I'd try Rollup and Webpack 2 for shaky trees.

Been fighting with this for days. Would really just appreciate a hand-holding tutorial at this point... @jlengstorf save me?

I want to use Node in the browser so hard it's not funny.

**Comment by jlengstorf** [comment]
Hey, @corysimmons — this sounds cool. I'm not sure I can help you, but I'm happy to take a look at your repo. Maybe open an issue on your repo explaining the errors you're running into and mention me?

If you want to open an issue on jlengstorf/code.lengstorf.com with a post idea, I will take a look at it for a future video/article.

In the meantime, I'd recommend closing this issue since it's not really an issue with Rollup itself. Thanks!

**Comment by corysimmons** [comment]
I opened [an issue](https://github.com/jlengstorf/code.lengstorf.com/issues/12) over there, but after uglifying/gzipping, the Browserify bundle is a usable size so I'm probably just going to go with Browserify from now on instead of fighting with all these tools and their layers-upon-layers of microconfiguration.

I don't understand how Rich wrote [a blog post](https://medium.com/@Rich_Harris/small-modules-it-s-not-quite-that-simple-3ca532d65de4) on systems being too modular, then let Rollup become [so modular](https://github.com/rollup/rollup/wiki/Plugins#list-of-plugins).

I can't wait for the next generation of JS monoliths that end this era.

Yeah yeah I'm an entitled jerk causing open-source burnout.

**Comment by jlengstorf** [comment]
I think the main problem is that (as far as I understand) Rollup wasn't really intended to replace Browserify or Webpack. Rollup is meant to bundle ES modules efficiently; if you need the advanced bundling features from Browserify/Webpack, trying to do it with Rollup is _kind of_ trying to fit a square peg in a round hole.

Webpack 2 actually implements the same tree-shaking — I think it was planning to include Rollup at one point, though I'm not sure that happened — so you may be able to have your cake and eat it, too.

Good luck!

**Comment by corysimmons** [comment]
> I think the main problem is that (as far as I understand) Rollup wasn't really intended to replace Browserify or Webpack. Rollup is meant to bundle ES modules efficiently; if you need the advanced bundling features from Browserify/Webpack, trying to do it with Rollup is kind of trying to fit a square peg in a round hole.

That's what I was afraid of.

Webpack 2 is coming along slowly though. I think it's done-ish, but it has a lot of the same problems I'm having trying to wrangle Rollup into this. I was hoping to support Rollup but if it's going to go out without a fight then I guess I'll just use Browserify and then switch to Webpack 2 in a few months.

Thanks for the replies and I <3 your YouTube channel so keep up the good work!
