### ISSUE TITLE
Dublicate rxjs classes when using RollupNG2

### ISSUE THREAD

**Issue by PFight** [rollup/rollup#1099]
**Minimal example:** [https://github.com/PFight/rollup-dublicate-bug](https://github.com/PFight/rollup-dublicate-bug)

If you install and run this example, in output file [test-rollup.js](https://github.com/PFight/rollup-dublicate-bug/blob/master/test-roolup.js) two classes will appear:

    class Observable {
    ....
    class Observable$1 {

The first class imported by `test.js`:

    import { Observable } from "rxjs/Observable";

The second class imported by [rxjs-es/add/operator/delay](https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/delay.ts):

    import { Observable } from '../../Observable';

### Reason

The bug disappears, if I remove RollupNG2 plugin from [rollup-config.js](https://github.com/PFight/rollup-dublicate-bug/blob/master/rollup-config.js), and replace all references `rxjs` to `rxjs-es` by hand. 

### Issue

How to write RollupNG2 plugin correctly, to remove dublicating?

**Comment by PFight** [comment]
Solution found!

It is there: [commit](https://github.com/PFight/rollup-dublicate-bug/commit/423844b72f9fac976619ef4269e2278b8b922a8b)

Looks like, buggy version of RollupNG2 generated not resolved paths (with `..`), but nodeResolve plugin generates absolute resolved paths. Rollup compares these paths symbol-by-symbol, and determines, that they are different. That's why, one module threated as two different modules. I just wrapped RollupNG2  into path.resolve, and problem disappeared.

### Conclusion

Rollup should perform [path.resolve](https://nodejs.org/api/path.html#path_path_resolve_paths) before comparing paths.

**Comment by aluanhaddad** [comment]
rxjs-es is now deprecated

**Comment by PFight** [comment]
It's not rxjs-es specific, it's rollup extensibility issue. If plugin generates relative path, then rollup do not identifies library as the same and makes dublication.

Checkined [simpified version](https://github.com/PFight/rollup-dublicate-bug) of minimal reproducing example. There no rxjs, @angular, only test files and custom plugin.

**Comment by Rich-Harris** [comment]
What OS are you on? The minimal example works for me on Node 7/OS X, `SomeDep.js` is only included once

**Comment by PFight** [comment]
@Rich-Harris, interesting, I tried on work machine with node v6.9.2, rollup v0.38.0, Windows10 and it does not reproduced. I will try later at home, where it had reproduced earlier. May be it was fixed in latest releases.

**Comment by Rich-Harris** [comment]
Closing. Let me know if this issue is still live.

**Comment by PFight** [comment]
Was reporducing on rollup 0.36.3. Now on 0.39.2 all ok.
