### ISSUE TITLE
Importing dependencies from existing vendor bundle

### ISSUE THREAD

**Issue by ericontilt** [rollup/rollup#1105]
I have an application which acts as a plugin container. It's bundeled using Webpack and it outputs a vendor bundle.

Now I'm bundling my plugin with rollup (FYI the plugin exposes some React components), and I would like to use React from my existing vendor bundle. I've set the external prop in the rollup config to contain all peerDependencies, but plugin it can't import anything from the vendor bundle. I'm guessing because it doesn't know how to interop with webpack imports.

Can anybody tell me if this scenario is at all possible?

**Comment by Rich-Harris** [comment]
Not a Webpack user so not exactly sure how vendor bundles work, but could you `export` React from your vendor bundle, then import it in your app?

```js
import { React } from './my-vendor-bundle.js';
```

Webpack would need to generate a JS module for this to work, or you'd need to use the `commonjs` plugin.

**Comment by ericontilt** [comment]
Thanks for the response, and sorry for my late one.. Since this is more of a webpack code splitting related issue, I think I need to ask the question over there.

**Comment by luispuig** [comment]
Did you solve the problem? I got the same one :)
