### ISSUE TITLE
conditional statements mess up tree shaking, resulting in huge bundles

### ISSUE THREAD

**Issue by epiloque** [rollup/rollup#1109]
### How to reproduce ?

On [rollupjs.org](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBjdWJlJTIwJTdEJTIwZnJvbSUyMCdzb21lLWJpZy1tb2R1bGUnJTNCJTVDbiU1Q25pZiUyMChmYWxzZSklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKGN1YmUoMSkpJTVDbiU3RCU1Q24lMjIlN0QlNUQlN0Q=) try 

```js
import { cube } from 'some-big-module';

if (false) {
  console.log(cube(1))
}
```

Which would result in the following:

```js
import 'some-big-module';
```

Most minifiers won't remove the above like, assuming that it has side-effects.

**Comment by Victorystick** [comment]
This is intended behavior. Rollup will not remove the import statement since removing any potential side-effects will change the runtime semantics of the bundle.

**Comment by epiloque** [comment]
I agree, on the assumption that there are side effects, what if there are none ? This is an extreme case of #551
