### ISSUE TITLE
Allow bundling of npm modules

### ISSUE THREAD

**Issue by nojvek** [rollup/rollup#1110]
rollup src/client/app.js --format es 

```
Treating 'preact' as external dependency
```

What if I don't want to treat as external component, but bundle as single file ?

**Comment by eisisig** [comment]
There is a plugin for that... If I remember correctly it is this one https://github.com/rollup/rollup-plugin-node-resolve

**Comment by btd** [comment]
@eisisig yes, but also need [rollup-plugin-commonjs](https://www.npmjs.com/package/rollup-plugin-commonjs).

@nojvek check example in readme for `rollup-plugin-commonjs`

**Comment by nojvek** [comment]
soooo many plugins. Its really confusing.

Is there a place where I can added common use cases documentation?

**Comment by Victorystick** [comment]
@nojvek You shouldn't need the commonjs plugin to bundle preact. They support the `jsnext:main` property in package.json, see the documentation for the node-resolve plugin.
