### ISSUE TITLE
How to keep third party libs out of bundle?

### ISSUE THREAD

**Issue by donnieflorence** [rollup/rollup#1111]
Hello, I'm using rollup for my library build. I'm not sure how to keep 3rd party dependencies out of my build. As an example:
```js
import someFunc from 'someLib';

function myLibraryFunction (someParam) {
  var someBox = someFunc(someParam);
  return someBox;
}

export default myLibraryFunction;

//or say with react example

import React from 'react';

export default function someComponent (props) {
  return <div>someText</div>;
}
```
This is very contrived example and the only one I could think of at the moment.

I don't want to include any of the code from `someFunc` or anything at all from `someLib` or `React` in my library. Because The person using my library will 100% have that `someLib` or `React` in their application code. How can I 100% with certainty guarantee that any of the code from those doesn't get added to my library?

**Comment by NicolasParada** [comment]
Mark they as [extenal](https://github.com/rollup/rollup/wiki/JavaScript-API#external).

**Comment by donnieflorence** [comment]
@NicolasParada I don't think that works well. Because I have a tiny file 15 lines of code. The library output comes out to 8kb. Theres no reason why 15LOC is 8kb. I think the module is finding its way into the output not sure why tho.

**Comment by Victorystick** [comment]
Non-relative imports (usually external dependencies) are [not bundled by default](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20You%20can%20import%20external%20modules%20into%20your%20bundle%20%E2%80%93%5Cn%2F%2F%20it%20doesn't%20matter%20if%20they're%20ES2015%20or%20legacy%5Cnimport%20%24%20from%20'jquery'%3B%5Cn%5Cn%24(%20'body'%20).html(%20'%3Ch1%3EHello%20world!%3C%2Fh1%3E'%20)%3B%22%7D%5D%7D). You must be using some plugin that includes them. I'm guessing node-resolve?

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)
