### ISSUE TITLE
With --watch, ignore first rollup run?

### ISSUE THREAD

**Issue by arxpoetica** [rollup/rollup#1112]
With the cli argument `-w`/`--watch` is there a config or cli option to *not* rollup on first run? Something like `--ignoreinit` or `ignoreInit: true`? Sometimes I fire rollup in a development environment, and the js libraries have already been packaged/rolled up, and I only want it to rollup when a change is made to one of the watched files.

**Comment by Rich-Harris** [comment]
Rollup doesn't know *which* files to run until it's built the bundle. The only way around that would be to write a JSON file that serialized information about the bundle, but at that point you may as well just use the caching/incremental build mechanism. (There might already be an issue for that somewhere, not sure...)

**Comment by arxpoetica** [comment]
Yeah, that makes sense. Chalk this up as a feature request? It's not hugely urgent at this point, though it was cumbersome for a bit until I changed my technique. (Can't remember exactly how it was burdensome; sorry I don't have a clearer immediate example.)

**Comment by Rich-Harris** [comment]
Makes sense. Have opened https://github.com/rollup/rollup-watch/issues/31 – will close this in favour of that
