### ISSUE TITLE
Unrolled up/ungrouped/uncompiled files for development purposes?

### ISSUE THREAD

**Issue by arxpoetica** [rollup/rollup#1114]
When bundling a large amount of files, it's helpful to know which file a bug came from. Sourcemaps are only so useful, as well they can be tedious and large.

Is it currently possible to keep files separate, and load them individually (in order) via separate scripts. Rollup seems to do a lot of global namespace handling, so maybe this isn't an easy thing?

**Comment by arxpoetica** [comment]
It appears this is already being addressed in the looooong standing ticket #372? Is this correct? If so, please close this ticket (or tell me to, and I will).

Otherwise, question stands. :)

Note: related: #1115

**Comment by Victorystick** [comment]
If you want to load modules individually during development I suggest you take a look at SystemJS.
