### ISSUE TITLE
How can I extract the common bundle?

### ISSUE THREAD

**Issue by lsycxyj** [rollup/rollup#1115]
There is such a plugin called factor-bundle for browserify. But how can I achieve this by rollup? And how can I output multiple bundles (eg. asynchronous loaded Components of React)?

**Comment by tivac** [comment]
The short answer is you can't right now.

The longer answer is contained within #372

**Comment by lsycxyj** [comment]
#372 It has been a long time. :(

**Comment by Victorystick** [comment]
Closing as duplicate of #372.
