### ISSUE TITLE
Plugin.outro didn't work

### ISSUE THREAD

**Issue by Elric-pp** [rollup/rollup#1116]
I have find the plugin outro api in [here](https://github.com/rollup/rollup/wiki/Plugins).
But it seems to be useless when i dive into the source code.
Is it a deprecated api or just a bug ?

**Comment by Victorystick** [comment]
It looks like a documentation error.

**Comment by Rich-Harris** [comment]
Can you clarify what the difference is between the expected and actual behaviour?

**Comment by Elric-pp** [comment]
I was writing a plugin, when i goes to this code 
```
    intro() {
      return 'hello'
    },
    outro() {
      return 'world'
    }
```
the intro is goes right, but there is no outro string. 
It seems to rollup didn't call the outro function or insert the outro string

**Comment by Rich-Harris** [comment]
Weird! Will be fixed by https://github.com/rollup/rollup/pull/1162 – thanks
