### ISSUE TITLE
<stdin> closing and parent process closing do not close `rollup --watch`

### ISSUE THREAD

**Issue by OvermindDL1** [rollup/rollup#1117]
As per usual process connections when a connection is closed a process should close unless it is designed to remain open as a daemon or persistent process, however right now when `rollup --watch` is called, the hosting server/ide manages its processes by closing the stdin file descriptor (and in this case also dying right after), but rollup keeps on running, disconnected from anything but init itself, I have to find the (many over multiple runs of) running instances of rollup and kill it(/them) as I dev. If the current functionality is wanted, where it stays running even when its parent process and input file descriptors die, any chance of a parameter that makes it act like a normal process then so it can be properly launched/killed by IDE's and build servers?

**Comment by Rich-Harris** [comment]
Closing in favour of https://github.com/rollup/rollup-watch/issues/30

**Comment by LostKobrakai** [comment]
This is still an issue with rollup 1.0 (probably reintroducted).
