### ISSUE TITLE
Unused code included in output - part 2

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#1120]
Reported by @bclinkinbeard in https://github.com/rollup/rollup/issues/977#issuecomment-262545870

Simplified test case using rollup version 0.36.4

$ cat a.js
```
function bar(umm) {
    umm = hmm();
    console.log("bar");
}
function hmm() {
    return true;
}
function baz() {
    console.log("baz");
}
baz();
```
$ node bin/rollup a.js 
```
function hmm() {
    return true;
}
function baz() {
    console.log("baz");
}
baz();
```
`function hmm` should have been dropped.

**Comment by kzc** [comment]
Another variation for rollup version 0.36.4:

$ cat b.js
```
function bar() {
    var t;
    t = hmm();
    console.log("bar");
}
function hmm() {
    return true;
}
function baz() {
    console.log("baz");
}
baz();
```
$ node bin/rollup b.js 
```
function hmm() {
    return true;
}
function baz() {
    console.log("baz");
}
baz();
```
Strangely, if `bar` is defined as follows then rollup 0.36.4 will produce the correct result:
```
function bar() {
    var t = hmm();    // instead of:   var t; t = hmm();
    console.log("bar");
}
```

**Comment by kzc** [comment]
If the #1106 [patch](https://github.com/rollup/rollup/commit/3da03c64b77d011672481f4da4ed54a4bb817b55) to CallExpression is applied to AssignmentExpression, the two tests above have the desired output with no regressions.
```patch
--- a/src/ast/nodes/AssignmentExpression.js
+++ b/src/ast/nodes/AssignmentExpression.js
@@ -37,7 +37,10 @@ export default class AssignmentExpression extends Node {
        initialise ( scope ) {
                this.scope = scope;
 
-               this.module.bundle.dependentExpressions.push( this );
+               if ( isProgramLevel( this ) ) {
+                       this.module.bundle.dependentExpressions.push( this );
+               }
+
                super.initialise( scope );
        }
 
@@ -45,3 +48,14 @@ export default class AssignmentExpression extends Node {
                return isUsedByBundle( this.scope, this.subject );
        }
 }
+
+function isProgramLevel ( node ) {
+       do {
+               if ( node.type === 'Program' ) {
+                       return true;
+               }
+               node = node.parent;
+       } while ( node && !/Function/.test( node.type ) );
+
+       return false;
+}
```
Aside from the repeated function isProgramLevel, are there any obvious problems with the same approach here?

UpdateExpression also calls `this.module.bundle.dependentExpressions.push( this );`. This might present the same issue although I can't craft a failing test case with `++` or `--`.

/cc @bclinkinbeard

**Comment by kzc** [comment]
@Rich-Harris I think the proposed patch in https://github.com/rollup/rollup/issues/1120#issuecomment-262889664 is reasonably sound.
`isProgramLevel` copied from https://github.com/rollup/rollup/commit/3da03c64b77d011672481f4da4ed54a4bb817b55 could be DRYed out.

**Comment by danez** [comment]
Yes I can confirm, that this also fixes #1142.
I can keep #1143 open for the test cases, or you can also pick them here.

Nice job. 👍

**Comment by kzc** [comment]
Was just following the pattern of the fix in #1106. 

@danez Would you mind rolling this fix into your PR and adding the two test cases above? 

`function isProgramLevel`, also used by #1106, probably should be moved to src/utils/.

**Comment by joaovieira** [comment]
Thanks for the great work on fixing these related issues!

I still believe there's a follow up on this though. The following:

```javascript
function foo (bar) {
  return bar
}

const baz = foo('b')
```

Results in empty bundle - `baz` is never used 👍 

However, if there is any sort of external function invocation within `foo` (external = not part of the bundle), even though `baz` is never used, both are added to the bundle:

```javascript
function foo (bar) {
  return bar.trim() //.slice(), Object.assign(), console.log(), etc.
}

const baz = foo('b')
```

Results in:
```javascript
function foo (bar) {
  return bar.trim()
}

const baz = foo('b')
```

If I were then to export `baz`, it would always be included regardless of being imported or not:

```javascript
// baz.js
function foo (bar) {
  return bar.trim();
}

export const baz = foo('b');
export const test = 1;

// main.js
import { test } from './baz'
console.log(test);
```

Results in:
```javascript
function foo (bar) {
  return bar.trim();
}

const baz = foo('b');
const test = 1;

console.log(test);
```

-----

Other inputs:

1.
```javascript
function qux () {
  return 1
  // return () => 1
  // return new Promise((res, rej) => setTimeout(res, 50))
}

function foo (bar) {
  return qux();
}

const baz = foo('b');
```
```javascript
(empty bundle)
```

2.
```javascript
function foo (bar) {
  return undef();
}

const baz = foo('b');
```
```javascript
function foo (bar) {
  return undef();
}

const baz = foo('b');
```

----

I would expect the bundle to never include `baz` and therefore `foo`. Is this a known issue?

**Comment by kzc** [comment]
```
function foo (bar) {
  return undef();
}
const baz = foo('b');
```
> I would expect the bundle to never include baz and therefore foo. 

That would result in incorrect code. If an unconditionally executed statement makes a call with a side effect it will always be included - regardless of whether it is exported or not. 

Note: tailgating on a closed issue is generally a bad idea as followups are less likely.

**Comment by joaovieira** [comment]
Yeah, I'm following up on the discussions around annotating pure functions/modules and noticing it's related. Makes sense. Cheers for that.

**Comment by joaovieira** [comment]
I guess this is where [prepack](https://prepack.io/) would come in :)

![screen shot 2017-05-04 at 14 28 41](https://cloud.githubusercontent.com/assets/474603/25705695/1a3e0080-30d6-11e7-84f5-23046e4cf57d.png)
