### ISSUE TITLE
transformBundle/ongenerate aren't async

### ISSUE THREAD

**Issue by tivac** [rollup/rollup#1122]
I realize that `transformBundle`/`ongenerate` are synchronous because `bundle.generate()` is synchronous, but I'm starting to run into cases where that's pretty limiting. Given that `rollup.rollup()` and `bundle.write()` already return a promise would it be weird for `bundle.generate()` and the associated hooks to be changed?

I'd be happy to do that work and send a PR for it for what it's worth!

I realize this is a pretty big breaking change but I'd be happy to further explain why that hook/fn being sync is a problem for me if it'd help. I did some explaining already in [gitter](https://gitter.im/rollup/rollup?at=5835e3e416ee9e640479df46)

**Comment by Rich-Harris** [comment]
As of 0.45, `bundle.generate` returns a promise, so `transformBundle` hooks can too — will close this issue
