### ISSUE TITLE
Importing Object fails on second build with activated cache

### ISSUE THREAD

**Issue by MikaFima** [rollup/rollup#1124]
Hi rollup,

I'm experiencing a weird behaviour importing this library: https://github.com/airbnb/react-dates.
But only when i'm using cache, on a second build.

When I try to import the library from this file https://github.com/airbnb/react-dates/blob/master/index.js, I found a complete object, but at the second time, this object has got `undefined` values.

You can experiment this in my reproduction repository 
https://github.com/MikaFima/rollup-react-dates-issue, all instructions included.

I keep in touch if you want more details.
Thanks.

**Comment by Rich-Harris** [comment]
Ok, I've done some digging. It turns out that the issue here is that the `commonjs` plugin is being reinstantiated each time the bundle is created. If you modify your Bundler.js like so...

```diff
var rollup = require('rollup').rollup;
var commonjs = require('rollup-plugin-commonjs');
var nodeResolve = require('rollup-plugin-node-resolve');
var replace = require('rollup-plugin-replace');

+ const plugins = [
+     nodeResolve({
+         extensions: ['.js', '.jsx'],
+     }),
+     commonjs({
+         extensions: ['.js', '.jsx'],
+     }),
+     replace({
+         values: {
+             'process.env.NODE_ENV': '"env"',
+         },
+     }),
+ ];

const Bundler = function() {
    this.cache;

    this.bundle = (entry, outro, useCache) => {
        const rollupOptions = {
            entry: entry,
            cache: useCache ? this.cache : null,
            indent: true,

-            plugins: [
-                nodeResolve({
-                    extensions: ['.js', '.jsx'],
-                }),
-                commonjs({
-                    extensions: ['.js', '.jsx'],
-                }),
-                replace({
-                    values: {
-                        'process.env.NODE_ENV': '"env"',
-                    },
-                }),
-            ],
+            plugins
        };

        return rollup(rollupOptions).then((bundle) => {
            this.cache = bundle;

            return bundle.write({
                useStrict: true,
                format: 'umd',
                dest: outro,
                moduleName: 'Reproduction'
            });
        }).catch((e) => {
            console.log(e);
        });
    }
}

module.exports = Bundler;
```

...it works as expected. The reason is that the `commonjs` plugin isn't entirely stateless, so reinstantiating it each time interacts badly with incremental rebuilds.

Hope this helps!
