### ISSUE TITLE
undefined reserved word.

### ISSUE THREAD

**Issue by snuggs** [rollup/rollup#1129]
Using Wayfarer router. How do we handle these situations with undefined? PR with Wayfarer seems a bit excessive as this will occur again. Please advise.

![capture d ecran 2016-11-30 a 17 16 05](https://cloud.githubusercontent.com/assets/38223/20775116/5b85fed6-b727-11e6-9cfa-f6de3b62684b.png)

**Comment by snuggs** [comment]
whoops lol. Please advise.

**Comment by Victorystick** [comment]
@snuggs Can you create a repro of the issue on rollupjs.org?

**Comment by Rich-Harris** [comment]
Yeah, am confused by this – would need a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff). `undefined` shouldn't be a reserved word anywhere

**Comment by snuggs** [comment]
Thanks @bfred-it i didn't even notice there was a response. Will clean up after myself next time. Now have notifications for rollup on ;-) 

That said I did a test from an old rollup dependency from that time frame. Same issue. Could be fixed now but i haven't updated rollup for that repo. Please advise...

![capture d ecran 2017-06-21 a 19 41 28](https://user-images.githubusercontent.com/38223/27411113-c524ee74-56b9-11e7-9ee8-2704c6effeb3.png)
/cc @Rich-Harris @Victorystick

**Comment by bfred-it** [comment]
That's not rollup. Your example works

```sh
❯ cat a.js
if ('foo' === undefined) console.log(`baz.es${'foo'}`)

~/delme 
❯ rollup a.js --format iife
(function () {
'use strict';

if ('foo' === undefined) console.log(`baz.es${'foo'}`);

}());
```

**Comment by snuggs** [comment]
Thanks @bfred-it will check some things out and get back to you if i need to.

Curious though could it be any one of these plugins from your experience? Ascii hand shrug is a fine response as well. Thanks in advance! 🙏
