### ISSUE TITLE
Treeshaking is defeated by Object.defineProperty

### ISSUE THREAD

**Issue by mhevery** [rollup/rollup#1130]
main.js:
```
import './core.js';
```

core.js:
```
export var ViewContainer = (function () {
    function ViewContainer() {
    }
    Object.defineProperty(ViewContainer.prototype, 'elementRef', {});
    return ViewContainer;
}());
```

One would expect that the resulting file would be empty as  `ViewContainer` is not used anywhere. Turns out that if `Object.defineProperty(ViewContainer.prototype)` is removed then the resulting code file is empty. This means that the call to `Object.defineProperty` defeats the tree shaker.

This is a common output when writing code in ES6 such as:
```
class ViewContainer{
  get elementRef() { return null; }
}

```

**Comment by kzc** [comment]
You have to consider side effects from any use of Object.defineProperty() that could happen with pathological code.

I guess Rollup would have to treat
```
Object.defineProperty(o, 'prop', {
  value: some_object_reference, ...
});
```
as 
```
o.prop = some_object_reference;
```
And it could only make that inference if the prop name argument was a literal, among other assumptions.

Things can get really complicated quickly in simulating the program flow.

**Comment by mhevery** [comment]
This use case is extremely common. Consider [this example](https://www.typescriptlang.org/play/#src=class%20ViewContainer%7B%0D%0A%20%20get%20elementRef()%20%7B%20return%20null%3B%20%7D%0D%0A%7D)

```
class ViewContainer{
  get elementRef() { return null; }
}
```

produces

```
var ViewContainer = (function () {
    function ViewContainer() {
    }
    Object.defineProperty(ViewContainer.prototype, "elementRef", {
        get: function () { return null; },
        enumerable: true,
        configurable: true
    });
    return ViewContainer;
}());
```

This is very common, and it causes retention of a lot of code in a project.

Could Rollup be smart and realize that the `Object.defineProperty` got called on local variable, hence there will be no side effects?

**Comment by kzc** [comment]
Whether it's common or not doesn't make it simple to solve. :-)

I was just trying to demonstrate some potential pitfalls to consider.

What if Object.defineProperty() is called via indirection as is common for Babel generated code?
```
$ echo 'class Foo { bar(x){return x * x;} }' | babel

"use strict";

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _createClass(Foo, [{
    key: "bar",
    value: function bar(x) {
      return x * x;
    }
  }]);

  return Foo;
})();
```

**Comment by kzc** [comment]
Related issue: #349

**Comment by mhevery** [comment]
Hi @kzc I have put together my thoughts on how this can be achieved in [this design doc](https://docs.google.com/document/d/16eAFx2ZzZcU9VthcbrpxAELe-vwXEsQowxsaZlSx4WA). Please have a look and give me back some comments. I am willing to do the work, if I can have some support from you.

**Comment by kzc** [comment]
@mhevery If you take a step back and look at a similar problem:
```
var Person = (function(){
    var Person = function(){};
    Person.prototype.run = function run() { console.log("run"); }
    Person.prototype.jump = function jump() { console.log("jump"); }
    return Person;
}());
var p = new Person();
p.jump();
```
and run this code through rollup version 0.36.4 you'll see that it does not drop the unused function `Person.prototype.run`. 

Although the simple program above can be statically analyzed, in a more complex program any object property can be accessed in a dynamic fashion that cannot always be statically deduced:
```
var Person = (function(){
    var Person = function(){};
    Person.prototype.run = function run() { console.log("run"); }
    Person.prototype.jump = function jump() { console.log("jump"); }
    return Person;
}());
var p = new Person();
p.jump();

p[ Math.random() > 0.5 ? "run" : "jump" ]();
```
which is why rollup [errs on the side of caution](https://github.com/rollup/rollup/issues/349#issuecomment-162573654) and retains all methods. 

Of course one could make some assumptions that methods will not be called in such a dynamic fashion, but I personally wouldn't want it to be the default behavior.  It is not uncommon in javascript to add or monkey patch functions at runtime.

Perhaps specific classes or IIFEs could be annotated with a comment directive to assume it will be statically accessed.

**Comment by mhevery** [comment]
I understand what you are saying, but I am not proposing that we drop methods from the class. I am proposing that we drop a whole class, when we know that no one is referring to the class. This operation is safe even in face of reflection.

**Comment by kzc** [comment]
Ah, okay, we weren't on the same page.

Rollup already can drop unreferenced IIFEs - aside from some problems with parens: #1101

I assumed that it could also drop unused ES6 classes. Let's check:

$ cat classes.js 
```
class Base {
    base() { console.log("base"); }
}

class Derived extends Base {
    derived() { console.log("derived"); }
}

new Base().base();
```
$ node bin/rollup classes.js 
```
class Base {
    base() { console.log("base"); }
}

new Base().base();
```
It appears to drop unused ES6 classes.

Rather than teaching rollup about the idiosyncrasies ES5 code generated from Typescript including `__extends`, I would recommend unused classes be dropped at the higher level of Typescript.

**Comment by kzc** [comment]
@mhevery Please don't let me discourage you from creating a PR for Rollup. I'm not a maintainer of Rollup. But since you asked, I just would approach the problem a different way. 

> The __extends function call is same problem as Object.defineProperty, but with an added complication that we can't tell Rollup ahead of time that __extends function is well-behaved-encapsulated-functions and which arguments are mutating and which are read-only. The rollup will have to figure this out on its own. 

That's a non-trivial task.

Barring transforming the code at the higher Typescript level, perhaps you could create some sort of comment directive or runtime flag to tell rollup which functions mutate which arguments.

**Comment by kzc** [comment]
@mhevery Any reason why you're not using the Typescript compiler to target ES6 and then running Rollup on that?

$ cat classes.ts
```
class Animal {
    constructor(public name: string) { }
    move(distanceInMeters: number = 0) {
        console.log(`${this.name} moved ${distanceInMeters}m.`);
    }
}

class Snake extends Animal {
    constructor(name: string) { super(name); }
    move(distanceInMeters = 5) {
        console.log("Slithering...");
        super.move(distanceInMeters);
    }
}

class Horse extends Animal {
    constructor(name: string) { super(name); }
    move(distanceInMeters = 45) {
        console.log("Galloping...");
        super.move(distanceInMeters);
    }
}

let sam = new Snake("Sammy the Python");
sam.move();
```
$ tsc --version
```
Version 2.0.10
```
$ tsc classes.ts --target ES6 --outFile classes.js

$ cat classes.js
```
class Animal {
    constructor(name) {
        this.name = name;
    }
    move(distanceInMeters = 0) {
        console.log(`${this.name} moved ${distanceInMeters}m.`);
    }
}
class Snake extends Animal {
    constructor(name) {
        super(name);
    }
    move(distanceInMeters = 5) {
        console.log("Slithering...");
        super.move(distanceInMeters);
    }
}
class Horse extends Animal {
    constructor(name) {
        super(name);
    }
    move(distanceInMeters = 45) {
        console.log("Galloping...");
        super.move(distanceInMeters);
    }
}
let sam = new Snake("Sammy the Python");
sam.move();
```
$ rollup classes.js
```
class Animal {
    constructor(name) {
        this.name = name;
    }
    move(distanceInMeters = 0) {
        console.log(`${this.name} moved ${distanceInMeters}m.`);
    }
}
class Snake extends Animal {
    constructor(name) {
        super(name);
    }
    move(distanceInMeters = 5) {
        console.log("Slithering...");
        super.move(distanceInMeters);
    }
}
let sam = new Snake("Sammy the Python");
sam.move();
```
Notice that the unused class `Horse` has been dropped.

**Comment by mhevery** [comment]
> @mhevery Any reason why you're not using the Typescript compiler to target ES6 and then running Rollup on that?

That is an excellent point! @robwormald do you have an opinion?

So Angular is distributed on NPM in two forms. 
1) As a umd bundle (which must be in ES5 so that browsers can execute it directly) and as 
2) ES5 code with modules syntax. This form is needed for two reasons.
   1) so that unit tests can run in browser with something like System.js (ie must be ES5)
   2) and so that Angular AoT compiler can do deep imports. 

I see how shipping the code in both ES5 and ES2015 format would be beneficial for tree shaking for Rollup but it would complicate user deployment. Also it would complicate how third part components need to be packaged in NPM.

**Comment by IgorMinar** [comment]
Sigh. Yeah. This is so that our npm packages are compatible with webpack. According to @robwormald, Webpack 2 currently can't downlevel code from 3rd party npm packages from es6 to es5 - @seanlarkin can you please confirm?

**Comment by TheLarkInn** [comment]
webpack only down levels import statements. For other syntactical features you need babel to transpile. In terms of tree shaking there are issues with UglifyJs not removing side effects from transpiled classes which may be what is being mentioned above.

**Comment by TheLarkInn** [comment]
However if rollup is already being run against the es6 modules that should help with some of the opt before webpack bundles it.

**Comment by kzc** [comment]
Similar discussion took place a few month back: https://github.com/mishoo/UglifyJS2/issues/1261

Same recommendations as I made above. Either perform these optimizations at a higher level in ES6 with rollup or equivalent or come up with some sort of annotation to mark the transpiled ES5 IIFE as being pure.

**Comment by manfredsteyer** [comment]
I'm curious: What is the current status on this?

**Comment by emilio-martinez** [comment]
@mhevery I think you "own" this ticket.

Reading down the conversation it seems like this is somewhat taken care of by Rollup, at least as far as it seems it can be taken for the time being?

**Comment by mhevery** [comment]
While the issue still holds, Angular is no longer blocked on this as we have changed our pipeline to not run into this.  So while it would be nice to fix, it is not needed by Angular. (Close at will)

**Comment by backspaces** [comment]
I am using three.js for visualizing agent based models .. [here is an example](http://backspaces.github.io/as-app3d/models/?water).

I used Three because of its popularity, and I assumed a rollup of the modeling software (57K minified) with three would be quite small, I use only their buffer geometries which are designed to be minimalistic. Amazingly, using rollup with a one-liner drags in ALL of three.js. Bummer.

I'm wondering what I would have to do to use just the parts of three.js that I use? Would using the src/*.js files be better than using `import * as THREE from 'three.module.js'`? Or is this a deep problem that requires modifying all of three, a project like @Rich-Harris's initial modularization of three.js?

**Comment by kzc** [comment]
> what I would have to do to use just the parts of three.js that I use?

Use deep imports in your code or assist that project land the class conversion PR https://github.com/mrdoob/three.js/pull/14654

> Or is this a deep problem that requires modifying all of three, a project like @Rich-Harris's initial modularization of three.js?

[That PR](https://github.com/mrdoob/three.js/pull/9310) got them to use ES6 import/export but the modules are still comprised of [ES5 code](https://github.com/mrdoob/three.js/blob/dev/src/lights/SpotLight.js) whose side effects are difficult to determine for dead code elimination.

**Comment by taoeffect** [comment]
Is there any reason to ever use `Object.defineProperty()`? I have never personally encountered a use case.

If the code can work just fine without it, then perhaps it's better to recommend that such code be rewritten?

**Comment by timdp** [comment]
How else would you define a getter and setter in ES5?

**Comment by kzc** [comment]
http://2ality.com/2015/08/object-literals-es5.html#ecmascript_5_has_getters_and_setters

**Comment by asyncLiz** [comment]
You need `Object.defineProperty()` when creating getters and setters on function-style classes. Typescript also makes use of this. Consider this class in ES6:

```js
class Example {
  get prop() { return true; }
}
```

It will transpile to 

```js
function Example() {
}
Object.defineProperty(Example.prototype, "prop", {
  get: function () { return true; },
  enumerable: true,
  configurable: true
});
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
