### ISSUE TITLE
Stop rollupjs from rewriting variable and function names

### ISSUE THREAD

**Issue by Veqt0r** [rollup/rollup#1131]
Rollup is renaming "protected" function/variable names, but it's not renaming the calls to those functions/variables, so scripts are simply failing with "function/variable not defined".

For example it's renaming animate() to animate$1(), as well as var renderer to var renderer$1. And yet it leaves all instances of it throughout the script as they were.

Is there a way to turn this off? Or am I possibly loading modules incorrectly, causing the renaming to fail?

**Comment by Veqt0r** [comment]
I've also found a user on stackoverflow with the same issue:

[http://stackoverflow.com/questions/40568580/rollup-js-how-import-a-js-file-not-es6-module-without-any-change-myvarextras](http://stackoverflow.com/questions/40568580/rollup-js-how-import-a-js-file-not-es6-module-without-any-change-myvarextras)

**Comment by tunnckoCore** [comment]
@Veqt0r can you give some code? Cuz user that posted at SO is doing it wrong and it's totally expected to not work for him.

But maybe I understand what you mean. I just playing with Rollup this night and found couple of strange things.

1. Outputs empty file if there's no `console.log()` ([see at REPL](http://rollupjs.org/?version=0.36.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwaGVsbG8lMjAlN0QlMjBmcm9tJTIwJy4lMkZmb28uanMnJTNCJTVDbiU1Q25oZWxsbygpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGhlbGxvJTIwKCklMjAlN0IlNUNuJTVDdHJldHVybiUyMCdoZWxsbzEnJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB3b3JsZCUyMCgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjAnd29sciclM0IlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhci5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGhlbGxvJTIwKCklMjAlN0IlNUNuJTVDdHJldHVybiUyMCdoZWxsbzEnJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB3b3JsZCUyMCgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjAnd29sciclM0IlNUNuJTdEJTIyJTdEJTVEJTdE))
2. It may be strange why this `name$1` or `name$23` is needed. But it is logical, don't how correct it is. See [the example, again in REPL](http://rollupjs.org/?version=0.36.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBoZWxsbyUyMCU3RCUyMGZyb20lMjAnLiUyRmZvby5qcyclM0IlNUNuaW1wb3J0JTIwJTdCJTIwd29ybGQlMjAlN0QlMjBmcm9tJTIwJy4lMkZiYXIuanMnJTNCJTVDbmltcG9ydCUyMCU3QiUyMHdvcmxkJTIwYXMlMjBxdXhpZSUyMCU3RCUyMGZyb20lMjAnLiUyRnF1eC5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGhlbGxvKCklMkMlMjB3b3JsZCgpJTJDJTIwcXV4aWUoKSklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwaGVsbG8lMjAoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwJ2hlbGxvMSclM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHdvcmxkJTIwKCklMjAlN0IlNUNuJTVDdHJldHVybiUyMCd3b2xyJyUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmFyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwaGVsbG8lMjAoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwJ2hlbGxvMSclM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHdvcmxkJTIwKCklMjAlN0IlNUNuJTVDdHJldHVybiUyMCd3b2xyJyUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIycXV4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwaGVsbG8lMjAoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwJ2hlbGxvMSclM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHdvcmxkJTIwKCklMjAlN0IlNUNuJTVDdHJldHVybiUyMCd3b2xyJyUzQiU1Q24lN0QlMjIlN0QlNUQlN0Q=). If you move `import { hello } from './foo.js';` from top to bottom, you'll see interesting thing - you'll see `world`, `world$1` and `hello$2`

**Comment by Permutatrix** [comment]
@Veqt0r Yeah, if you're doing it the same way as that user, Rollup is behaving correctly. Rollup doesn't concatenate JavaScript files; it transpiles ES2015 modules. I'm going to write an answer to that SO question. (I'm surprised it doesn't have one yet, since it's so simple...) You can read that answer for more details to see if it solves your problem as well.

@tunnckoCore
1. That's Rollup's fairly advanced tree-shaking in action. It omits things that have no side effects. Your example does nothing, so Rollup outputs a script that does nothing.
2. That _is_ interesting. I wonder what's going on there. It probably won't be "fixed" any time soon, though, since it doesn't cause any problems.

**Comment by tunnckoCore** [comment]
@Veqt0r Nope.

1. It does something (think that the/this "bundle/main/index/app/cli" is the user, it calls the needed thing). It has `hello()` which is really "called action" and `hello` can do something like request APIs and etc.
2. Yea, it is not a problem any way.

edit: 1) or you mean that if i have `cli.js` that calls the api of some lib, and i want to transpile that cli file, then Rollup will output me such "empty" (here, empty, means that won't insert me the api in the bundle) file? (ironic question) That's not okey, really. 

What I was thinking last days is that _"if there has `foobarName(` **and** prev token is not `function` we should import the wanted module to the bundle, if not we won't"_

**Comment by tunnckoCore** [comment]
Take [this REPL](http://rollupjs.org/?version=0.36.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwaGVsbG8lMjAlN0QlMjBmcm9tJTIwJy4lMkZmb28uanMnJTNCJTVDbmltcG9ydCUyMG1pbmltaXN0JTIwZnJvbSUyMCdtaW5pbWlzdCclM0IlNUNuJTVDbmNvbnN0JTIwYXJndiUyMCUzRCUyMG1pbmltaXN0KHByb2Nlc3MuYXJndi5zbGljZSgyKSklNUNuJTVDbmhlbGxvKGFyZ3YlMkMlMjAoZXJyJTJDJTIwcmVzKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBpZiUyMChlcnIpJTIwcmV0dXJuJTIwcHJvY2Vzcy5leGl0KDEpJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdTdWNjZXNzJyklNUNuJTdEKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBoZWxsbyUyMCgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjAnaGVsbG8xJyUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwd29ybGQlMjAoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwJ3dvbHInJTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBoZWxsbyUyMCgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjAnaGVsbG8xJyUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwd29ybGQlMjAoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwJ3dvbHInJTNCJTVDbiU3RCUyMiU3RCU1RCU3RA==) for example.

**Comment by Permutatrix** [comment]
@tunnckoCore I don't understand what you're saying. A call to a function with no side effects has no side effects. The input and output are therefore functionally equivalent, in both cases, regardless of how complicated the arguments you pass in are.

**Comment by tunnckoCore** [comment]
Only saying that consideration: only if the module is `console.log`ed then import it; is wrong.

**Comment by Permutatrix** [comment]
It has nothing to do with `console.log`. `console.log` just happens to have side effects, which means Rollup considers calls to it to be significant. Omitting code with no side effects isn't wrong because it doesn't change the behavior of the output.

**Comment by tunnckoCore** [comment]
Okey, i know it is not `console.log` only, but anyway.

This snippet is not just snippet. It is real world thing. Anyone can think to do CLI package of some other API package, like Sindre does for example. And like what i thinking to do for one of my packages, but I won't be able to do it because of this. And really, such CLI package can be that small and delegates CLI args to the API directly like in that repl snippet. Only different thing will be that it wont `import from ./foo` but `import from my-package`

**Comment by Permutatrix** [comment]
@tunnckoCore If you're importing from an external module, Rollup will assume that functions have side effects, so the code will be included even if you don't use `console.log` or anything.

This is tree-shaking, one of Rollup's core features and possibly its main reason for existing. One of the keys of tree-shaking is that it doesn't prevent you from doing anything&mdash;aside from the smaller file size of your bundles, you have no way of even knowing it's happening.

**Comment by Permutatrix** [comment]
@tunnckoCore (Here's an example of an external module's function not being tree-shaken.](http://rollupjs.org/?version=0.36.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwaGVsbG8lMjAlN0QlMjBmcm9tJTIwJ2ZvbyclM0IlNUNuJTVDbmhlbGxvKGFyZ3YlMkMlMjAoZXJyJTJDJTIwcmVzKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBpZiUyMChlcnIpJTIwcmV0dXJuJTIwcHJvY2Vzcy5leGl0KDEpJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdTdWNjZXNzJyklNUNuJTdEKSUyMiU3RCU1RCU3RA==)

**Comment by designbyadrian** [comment]
> @tunnckoCore [Here's an example of an external module's function not being tree-shaken.](http://rollupjs.org/?version=0.36.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwaGVsbG8lMjAlN0QlMjBmcm9tJTIwJ2ZvbyclM0IlNUNuJTVDbmhlbGxvKGFyZ3YlMkMlMjAoZXJyJTJDJTIwcmVzKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBpZiUyMChlcnIpJTIwcmV0dXJuJTIwcHJvY2Vzcy5leGl0KDEpJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdTdWNjZXNzJyklNUNuJTdEKSUyMiU3RCU1RCU3RA==)

This link is now dead.

**Comment by tunnckoCore** [comment]
Of course, thread is 6 years old.

**Comment by aigan** [comment]
But I still need it to keep all variable names

**Comment by rvanbaalen** [comment]
Hello from the future. What's the consensus on this? How to prevent rollup from renaming my functions?
