### ISSUE TITLE
Removing sourcemapping comment also removes newline character

### ISSUE THREAD

**Issue by Archomeda** [rollup/rollup#1132]
I've found a node package called `node-source-map-support` that inconveniently uses a `////# sourceMapURL=foo.js.map` [in their file](https://github.com/evanw/node-source-map-support/blob/313c03883ec48dd99cdf43fc9457d40d9599c142/source-map-support.js#L113). On its own, this is not an issue, but when using rollup it produces an invalid file because the next line is being commented out.

**main.js**
```javascript
////# sourceMappingURL=foo
var val = 42;
console.log(val);
```

**output**
```javascript
'use strict';

//var val = 42;
console.log(val);
```

[Take a look.](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTJGJTJGJTIzJTIwc291cmNlTWFwcGluZ1VSTCUzRGZvbyU1Q252YXIlMjB2YWwlMjAlM0QlMjA0MiUzQiU1Q25jb25zb2xlLmxvZyh2YWwpJTNCJTIyJTdEJTVEJTdE)

Interestingly enough, when using CRLF as newline character, it doesn't remove the newline. Whereas only using LF as newline character, it does get removed. I assume that there's a regex being too greedy?

**Comment by Rich-Harris** [comment]
Thanks – fixed in 0.37.2
