### ISSUE TITLE
Accept config from package.json (i don't like X-awesome-tool custom config files)

### ISSUE THREAD

**Issue by tunnckoCore** [rollup/rollup#1133]
I just hate my repos to be full of config files. And think that every self-loving tool and developer of "awesome" tools should allow multiple config lookups. I have [an idea](https://github.com/tunnckoCore/ideas/issues/46) for such thing.

**Comment by tunnckoCore** [comment]
@Rich-Harris thoughts?

**Comment by kzc** [comment]
> Accept config from package.json

https://github.com/rollup/rollup/blob/master/rollup.config.js is not JSON.

**Comment by tunnckoCore** [comment]
But can be.

**Comment by tivac** [comment]
That would be a very, very simple config. Completely devoid of any plugins. I have a hard time seeing a lot of benefit to that.

**Comment by tunnckoCore** [comment]
> Completely devoid of any plugins.

Mm nope, why? How babel, eslint and others do it? Come on, it's not serious saying such thing.

**Comment by Rich-Harris** [comment]
I don't see any benefit to this, sorry. Much better if there's a standard way for all Rollup projects to store their configuration, and – like Webpack, which has similar needs and has reached the same conclusion – a JavaScript config file is the correct solution. A lot of options (both for Rollup core and its plugins) can be functions, because you need precise control over certain aspects of your configuration, and if you restrict yourself to JSON you end up with a nightmarish DSL. It's not worth it.

**Comment by tunnckoCore** [comment]
Allowing one more config entry point not means that users won't be able to use such config files as currently. I really don't see the problem - in my specific case I just want to use `*-buble and `*-node-resolve` plugins. I'm sure I'm not the only one that need few simple things with defaults and hate dozen config files. Every self-respecting tool should support few ways of configuration. Babel and ESLint does it great - both can accept pretty complex configs through JSON. And there are few plugins even in this org, that has pretty simple config file including only the buble plugin.

I don't see value to force users do some tricks and make them headaches.

> because you need precise control over certain aspects of your configuration, and if you restrict yourself to JSON you end up with a nightmarish DSL.

Mm nope. The nightmares comes when we start using such tools. Dozen of tools that not does their job correctly. I hate to have 50+ devDependencies (so I don't have such `package.json`s), because I'm forced (sort of, because the needs) to use couple of tools that partially does some job. That's why I still trying to not use such tooling as much as possible.

I'm not hating you or your projects. Rollup is amazing and gave us the tree-shaking idea, Buble is cool too. I just feel uncomfortable and believe me I'm not the only one.

Sorry for the tone or something,
cheers, Charlike.

edit: It seems that I'll create wrapper thing, again. Such "issues" are the reason that we are in era of "wrappers of wrappers of wrappers".

**Comment by tunnckoCore** [comment]
Why i still think configs could be loaded from package.json

```json
  "browserify": {
    "transform": [
      ["rollupify", {
        "plugins": [
          ["foobar", {
            "qux": true
          }]
          ["buble", {
            "target": "0.12"
          }]
        ]
      }],
      ["uglifyify", {
        "compress": true
      }]
    ]
  },
```

And the most minimal change for this is to create `options.plugins` to work as babel/eslint/browserify.
