### ISSUE TITLE
Rollup throwing Error: TODO with ASI confused code

### ISSUE THREAD

**Issue by bjornharrtell** [rollup/rollup#1134]
This example code:

```
export default {}

(function() {
})()
```

Results with Rollup saying:
```
Error: TODO
      at callHasEffects (src/ast/nodes/shared/callHasEffects.js:64:5)
```

Of course the code does not make much sense and is a demonstration of when forgetting to separate statements that becomes intermingled because of ASI. Adding a semi-colon before the self-executing function is the appropriate action, but I think it would be good if Rollup would not fail with such a non-informative error.

**Comment by guybedford** [comment]
As far as I can tell this is resolved now.
