### ISSUE TITLE
Ability to access importee or id during transform plugin?

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#1136]
While performing a `transform()` in a plugin, is there any way to know what the original `importee` or `id` of this module was? Or was rollup specifically designed to not provide this information, and if I'm trying to access it then I'm doing something wrong? If I do need the `id`/filename for part of the transformation, I suppose I can always just do that part during a `load()`, but that seems kinda hacky.

(Backstory: I'm experimenting with different ways of combining multi-file components for [svelte](/sveltejs/svelte) into one file, and getting rollup to do this for me sounds fun.)

**Comment by tivac** [comment]
The module `id` is passed as the second arg to `transform`. I'm making use of it in [`modular-css`](https://github.com/tivac/modular-css/blob/master/src/rollup.js#L34).

Hopefully just a documentation issue.

**Comment by Conduitry** [comment]
Ah interesting, thanks! Yep I had been only looking at the API docs, which you just updated. Closing this issue.
