### ISSUE TITLE
Rollup should warn if the user is shadowing an imported variable

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#1137]
```js
import { foo } from 'foo';
//       ^ warn about shadowed/unused import?

export const foo = foo;
```

See [live example](http://rollupjs.org/?version=0.36.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAnZm9vJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjBmb28lM0IlMjIlN0QlNUQlN0Q=) of v0.36.4.

**Comment by Rich-Harris** [comment]
Isn't this a linter's job? ESLint prints the following if it sees that:

```bash
3:14  error  'foo' is already defined                no-redeclare
```

**Comment by Rich-Harris** [comment]
Going to close this in the interests of one day getting on top of the backlog
