### ISSUE TITLE
Instruction for setting up babel polyfill

### ISSUE THREAD

**Issue by tresdin** [rollup/rollup#1139]
I unfortunately got a trouble with using `babel-polyfill` with `rollup`. I've been searching for hours but I still can not find a detailed instruction for this issue. I think this expected instruction is not included in the official documentation.

**Comment by Rich-Harris** [comment]
Not a Babel user, but I assume you'd just need to import `babel-polyfill` at the top of your entry module, per the [documentation](https://babeljs.io/docs/usage/polyfill/). Be aware that it contains a lot of stuff you might not need – consider importing only the specific polyfills you need.

Closing as this isn't a Rollup issue.

**Comment by tresdin** [comment]
@Rich-Harris `rollup` treats `babel-polyfill` as external dependencies. If I'm not mistaken, that means `rollup` will not include those modules in the bundled files. If this is the case, then how can I config `rollup` for including external modules into bundled files?

**Comment by Rich-Harris** [comment]
You would need to use rollup-plugin-node-resolve (and possibly rollup-plugin-commonjs)

**Comment by tresdin** [comment]
@Rich-Harris Thank you for pointing it out. It does help me a lot.

By the way, I still got another trouble with using `rollup` for  bundling es6 modules. This issue is specified at #1161 . Hope you can help me with this.
