### ISSUE TITLE
`this.warn(...)` (and others) for plugins

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1140]
Via https://github.com/rollup/rollup-plugin-babel/pull/85 – would be good to have a standardised way for plugins to provide logging info, warnings, and errors. Mutating the `options` object is a bit mad, but currently the only way.

**Comment by tivac** [comment]
> is a bit mad

https://github.com/tivac/modular-css/blob/master/src/rollup.js#L27-L29

...

😅

**Comment by Rich-Harris** [comment]
Released this in 0.41
