### ISSUE TITLE
Recursive function uses itself and not gets removed by tree-shaking

### ISSUE THREAD

**Issue by danez** [rollup/rollup#1142]
When having a function that calls itself, it is not removed by tree-shaking. Seems this happens because the Node gets `activated`, at least that's were I ended debugging.

## Input
```js
var set = function set(object) {
   object.value = value;

   set(Object.getPrototypeOf(object));
};
```

## Expected output
```js
'use strict';

```

## Current output
```js
'use strict';

var set = function set(object) {
   object.value = value;

   set(Object.getPrototypeOf(object));
};
```

## Example

http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwc2V0JTIwJTNEJTIwZnVuY3Rpb24lMjBzZXQob2JqZWN0KSUyMCU3QiU1Q24lMjAlMjAlMjBvYmplY3QudmFsdWUlMjAlM0QlMjB2YWx1ZSUzQiU1Q24lNUNuJTIwJTIwJTIwc2V0KE9iamVjdC5nZXRQcm90b3R5cGVPZihvYmplY3QpKSUzQiU1Q24lN0QlM0IlMjIlN0QlNUQlN0Q=

## Environment

rollup: 0.37
node: 6.9.1
os: macOS 10.11

 I can help to fix it, but I'm not sure where to start. I debugged a testcase with this input-code, but I'm not sure where the whole activation happens, and how the Node could detect that it got activated by itself.

**Comment by kzc** [comment]
Does this patch help?

https://github.com/rollup/rollup/issues/1120#issuecomment-262889664
