### ISSUE TITLE
Plugin order

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1148]
A couple of recent issues (https://github.com/rollup/rollup-plugin-commonjs/issues/145 and https://github.com/rollup/rollup-plugin-babel/issues/58) have been caused by the order in which plugins run. It's not obvious that, for example, the `commonjs` plugin needs to run before the `babel` plugin, or that `node-resolve` has to come before `commonjs`.

I'm not sure what the best solution is. Perhaps plugins could export an `order` property that allows Rollup to warn if it looks like plugins are in the wrong order?

```js
function myPlugin ( options ) {
  return {
    name: 'my-plugin',

    order: {
      commonjs: -1,
      babel: 1
    },

    transform ( code, id ) {
      // ...
    }
  };
}
```

Or something more intuitive, like `mustFollow: [ 'commonjs' ]` and `mustPrecede: [ 'babel' ]`.

This wouldn't catch every case, but it would allow us to warn on the common cases. Thoughts?

**Comment by kzc** [comment]
> mustFollow: [ 'commonjs' ] and mustPrecede: [ 'babel' ]

That's probably the simplest solution.

Might there be a valid use case to repeat plugins within a rollup config? If so, that might present a complication. But even then a warning would be emitted and execution could continue.

**Comment by Rich-Harris** [comment]
> Might there be a valid use case to repeat plugins within a rollup config?

Conceivably, yes – you might want to transpile some files with these Babel options and some with those Babel options, for example. Typically though you would probably want to have those plugin instances next to each other, I think. And yeah, it's just a warning rather than an error.

**Comment by kzc** [comment]
Are there rollup options to disable warnings and/or error out upon warning?

**Comment by Rich-Harris** [comment]
You can supply an `options.onwarn` handler, which you can use to suppress or throw. It will default to `console.warn`ing message. Right now warnings are just strings, I'd like to make them a bit more structured eventually

**Comment by Rich-Harris** [comment]
> Right now warnings are just strings, I'd like to make them a bit more structured eventually

https://github.com/rollup/rollup/issues/1194

**Comment by btd** [comment]
I do not think adding additional keys to show plugin run after is right idea. 
Plugins will just start work in any order - no body will know what is going on. 
We completly loose obviosity.

PostCSS has similar problem, but they wrote specific order steps if required in readme. So all problems are comming from users that did not read readme.

**Comment by Rich-Harris** [comment]
The proposal isn't that plugins would *control* the order in which they run, just that they'd provide hints that would allow Rollup to say 'by the way, this config probably isn't going to work, you should probably make sure that the commonjs plugin goes before the babel plugin. But YMMV'.

**Comment by jharris4** [comment]
I'm confused by the statement above `It's not obvious that, for example, the commonjs plugin needs to run before the babel plugin`.

I just tried converting a project to use rollup that's using babel-plugin-transform-object-rest-spread.

If I use the following rollup plugin ordering:

```
plugins: [
  replace({
    'process.env.NODE_ENV': JSON.stringify('production')
  }),
  node(),
  commonjs(),
  babel(babelConfig)
]
```

I get an error from the commonjs plugin:

```
🚨   (commonjs plugin) Unexpected token (<line>:<col>) in <filename.js>
```

Where the corresponding source looks like:

```
let myVar = functionCall({...objectToSpread, otherArg});
```

The only way I can fix the error is to change the order of the plugins such that babel is *before* commonjs, like so:

```
plugins: [
  replace({
    'process.env.NODE_ENV': JSON.stringify('production')
  }),
  node(),
  babel(babelConfig),
  commonjs()
]
```

Am I missing something here? I don't quite understand why commonjs is supposed to be before babel, or how to workaround the above issue.

**Comment by btd** [comment]
@jharris4  I think this is because you use object spread, which is not in any es standard yet. But commonjs plugin uses acorn which supports only stage-4 items (which is in standard actually).

**Comment by mortargrind** [comment]
@btd Shouldn't Rollup let the rollup-user to use additional acorn plugins (for things like JSX or Object spread) if needed in order to avoid syntax errors during parsing stage? Because it seems that current Rollup plugin order requires us to use Babel at the very end of the flow. But if the rollup-user uses anything that adds special syntax to the ES itself, Acorn can not parse it in the first place so we are forced to use Babel first in the plugin order: Most of the examples about React+Rollup are like this and they're actually wrong. It literally took more than 1 day for me to figure out it's about the plugin order and Acorn :(

I know that the decision was to wait for the community to grow and develop Rollup transform plugins, but at this stage if the Acorn plugin ecosystem is more rich and stable i think it should be an option to use Acron plugins directly.

**Comment by btd** [comment]
@mortargrind i do not think so. Each plugin distinct from rollup itself, and it is literally your responsobility currently to provide plugin source it could work with (that is why this issue raised - to make this process more simple).
If we are trying to go this road (allow acorn plugins) - each plugin should have tons of additional options.
That is why babel should be first to convert source to es5 (but actually most plugins allow es6+ stage-4 things) and pass it further.
For example one of the projects uses react and rollup has such config:
```js
function scripts(entry, cache) {

  return rollup({
    entry: entry,
    sourceMap: sourceMap,
    format: 'iife',
    cache: cache,
    plugins: [
      rollupJson(),
      rollupBabel({
        plugins: [
          "external-helpers",
        ],
        presets: [
          ['es2015', { loose: true, modules: false }],
          'react'
        ],
        exclude: 'node_modules/**'
      }),
      rollupReplace({
        'process.env.NODE_ENV': JSON.stringify(isDev ? 'development': 'production'),
        'process.env.VERSION': JSON.stringify(pkg.version),
        'process.env.SITE_URL': JSON.stringify(config.SITE_URL),
        'process.env.CDN': JSON.stringify(config.CDN),
        'process.env.PATH': JSON.stringify(config.PATH)
      }),
      rollupNodeResolve({
        extensions: ['.js', '.jsx'],
        jsnext: true,
        main: true
      }),
      rollupCommonJs({
        ignoreGlobal: true,
        include: 'node_modules/**',
        namedExports: {
          'node_modules/react/react.js': ['Children', 'Component', 'PropTypes', 'createElement']
        }
      }),
      rollupVisualizer({
        filename: './stats.html'
      })
    ]
  });
}
```
(it is part of gulpfile so additional options)
I do not see anything wrong with plugin order at all.

**Comment by mortargrind** [comment]
@btd So according to this, No need to run babel at the end (after common-js) at all?

**Comment by btd** [comment]
@mortargrind yes there is no any reason to run babel after commonjs. commonjs plugin do not add anything to source file that other plugins could not consume (it added in most situations imports and exports, which rollup handle itself).
I could be wrong there (i do not use globals and builtins feature), but commonjs only could handle global var usage and wrap file in iife. Builtins i am not sure how handled, there is [empty repo](https://github.com/rollup/rollup-plugin-node-builtins).

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by vladshcherbin** [comment]
@shellscape still need some kind of resolution for this one, it's useful in plugins.

**Comment by shellscape** [comment]
@vladshcherbin would you be willing to lead the effort? This issue hasn't seen much life since 2017.
