### ISSUE TITLE
Uncommon project structure - how to enable import?

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#1149]
Issue:

We do have a library which works perfectly when bundled by Webpack, but our users cant use Rollup as a non-breaking replacement for it.

Its caused because we have allowed a quite custom import for the part of the library.
1. we have 2 main entry points to the things exported by the lib - `redux-saga` and `redux-saga/effects` which are used with normal `import` syntax like `import { call } from 'redux-saga/effects'`
2. our library is transpiled by Webpack to umd and es builds to `lib/` and `es/` directories accordingly
3. we have in our package.json correct entries
```
"main": "lib/index.js",
"jsnext:main": "es/index.js",
```
which works fine for `import { delay } from 'redux-saga'` in both cases but its unfortunately not working for the second one - `import { call } from 'redux-saga/effect'`.
4. We got it working within Webpack environment by creating a file at the root (acting as a proxy to the bundled file):
```javascript
// ./effects.js
module.exports = require('./lib/effects')
```
but as you can see its dependant on the `lib` directory and Rollup needs to be directed to the other one - `es`

Do you have any idea how to support both build systems at the same time?

Example repo demonstrating the issue:
https://github.com/zech/rollup-redux-saga

More details here:
https://github.com/yelouafi/redux-saga/issues/689

**Comment by Rich-Harris** [comment]
I thought Webpack supported `import` and `export` natively – isn't it possible for `redux-saga/effect.js` to be an ES module? Unfortunately there isn't really a way for a package to expose different modules for CommonJS and ES consumers *other* than with `main` and `jsnext:main` (aka `module`).

**Comment by Andarist** [comment]
Hm, I think webpack 2 supports `import`/`export` natively, but its predecessor does not unfortunately.

I thought about making an `if` statement here based on some env var
```javascript
// ./effects.js
module.exports = process.env.JSNEXT ? require('./es/effects') : require('./lib/effects')
```

but that would impose on the user to make this env var accessible, so the solution is rather clunky

**Comment by Rich-Harris** [comment]
Yeah, I think this issue can only be solved with documentation in that case :(

**Comment by Andarist** [comment]
@Rich-Harris I forgot to post here, but fortunately I've resolved the issue after few months - or rather somebody did it for me ;)

You can look on the solution [here](https://github.com/redux-saga/redux-saga/commit/d3139efd5ffeeef901a8cb8c0f186b0efd234387) - it's quite nifty.
