### ISSUE TITLE
jsx support

### ISSUE THREAD

**Issue by aeosynth** [rollup/rollup#115]
is it possible to use rollup on a project which uses jsx (through babel)? do i have to somehow process it first with babel to remove the jsx syntax?

**Comment by eventualbuddha** [comment]
If I were going to try this I'd investigate using rollup-babel or making rollup capable of using a custom parser (here I'm assuming rollup's parser doesn't support jsx).

**Comment by aeosynth** [comment]
thanks for the link. for now i'll stick with the systemjs bundler.
