### ISSUE TITLE
External dependency "is not defined"

### ISSUE THREAD

**Issue by FezVrasta** [rollup/rollup#1155]
I'm trying to understand how the external dependencies are treated by Rollup.

My library imports a dependency with:

```
import Popper from 'popper.js;
```

And later it uses it.

In the tests I'm writing, when I try to use it:

```
import Tooltip from '../../src/tooltip/index.js';

describe('[tooltip.js]', () => {
    it('should show a tooltip when hovered', () => {
        new Tooltip(reference, {
            trigger: 'hover',
        });
    });
});
```

I get:

```
Uncaught ReferenceError: Popper is not defined
  at tests/functional/tooltip.js:2296
```

I don't understand what I'm doing wrong. I would expect Rollup to import `Popper` along with `Tooltip` when I compile a file that `import`s `tooltip.js`.

Note that I'm already defining `popper.js` inside the `globals` option of Rollup.

**Comment by jonataswalker** [comment]
Is there any relation between `Tooltip` and `Popper`? Rollup doesn't import unused code.

**Comment by FezVrasta** [comment]
I use `Popper` inside `Tooltip`

```
        this.popperInstance = new Popper(reference, tooltipNode, popperOptions);
```

**Comment by jonataswalker** [comment]
I can see Popper library inside the generated bundle with a config like:

```javascript
// rollup.config.js
var commonjs = require('rollup-plugin-commonjs'),
      resolve = require('rollup-plugin-node-resolve');

export default {
  format: 'umd',
  entry: 'test.js',
  dest: 'bundle.js',
  moduleName: 'test',
  plugins: [
    resolve({ browser: true }),
    commonjs({ namedExports: { 'poper.js': ['Popper'] }})
  ]
}
```

```javascript
// test.js
import Popper from 'popper.js';
console.log(new Popper());
```

**Comment by FezVrasta** [comment]
Why do I need `commonjs`? Both the libraries are compiled with Rollup.

**Comment by FezVrasta** [comment]
I tried to follow your advices but I get:


```
17 12 2016 09:18:43.911:ERROR [preprocessor.rollup]: Failed to process /Users/federicozivolo/Progetti/popper-js/tests/functional/tooltip.js

Error transforming /Users/federicozivolo/Progetti/popper-js/src/tooltip/node_modules/popper.js/build/popper.js with 'babel' plugin: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
```

I doubt it's actually a babel's fault...

This is the branch with the changes:
https://github.com/FezVrasta/popper.js/tree/v1-dev-tooltip-tests

**Comment by FezVrasta** [comment]
I just noticed that if I import `popper.js` source inside `tooltip.js` (instead of the UMD module) everything works.

```
import Popper from '../popper/index.js';
```

**Comment by FezVrasta** [comment]
Update, to fix the problem in my specific case I did the following:

inside the Rollup configuration of Karma, I kept just these options:

```
plugins: [babel()],
format: 'iife',
 sourceMap: 'inline',
```

in my test, I require just `tooltip.js`:
```
import Tooltip from '../../src/tooltip/index.js';
```

in my `tooltip.js` source, I import `popper.js` from its source (not the npm package):
```
import Popper from '../popper/index.js';
```

then, in the Rollup config used to create the `tooltip.js` bundle (the one I put on npm), I added this option:
```
external: [path.resolve(root, 'src/popper/index.js')]
```

Doing so, the bundle refers to a generic `Popper` dependency, but when Karma compiles the files, it includes the actual source code of `popper.js`.

I don't think this is a real solution since my initial idea was to import directly from the `node_modules` folder, there's something wrong with Rollup or any of its plugins probably.

**Comment by Rich-Harris** [comment]
This should work fine without having to muck around with stuff like `'../popper/index.js'` (which is brittle because it depends on npm installing things in a particular way), but we'd need a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) in order to investigate.

**Comment by FezVrasta** [comment]
I have provided the repo with the problem. I'll try to prepare a minimal repro when I find a minute

**Comment by FezVrasta** [comment]
```
git clone https://github.com/FezVrasta/rollup-bug-repro
cd rollup-bug-repo
yarn
yarn run build
yarn run start
```

**Comment by Rich-Harris** [comment]
Your import is in the wrong place. You're importing `Popper` in test.js, where it's not used, instead of in tooltip.js where it is

**Comment by FezVrasta** [comment]
Sorry it was a typo, btw fixing it the problem is still there.

**Comment by Rich-Harris** [comment]
I see two more problems with your config:

1. You're transpiling `node_modules/popper.js/src/popper.js`. For whatever reason, it doesn't like to be transpiled. Excluding it with `babel({ exclude: 'node_modules/**' })` allows the test to build
2. Your `index.html` file is broken – the `<script>` tag needs to come *after* the DOM elements the test references.

Once those are fixed, it seems to work just fine. What behaviour are you expecting?

**Comment by FezVrasta** [comment]
`popper.js/src/popper.js` is an ES2015+ file, so it needs to be transpiled by Babel actually.

**Comment by Rich-Harris** [comment]
In which case you might want to [remove this line](https://github.com/FezVrasta/rollup-bug-repro/blob/master/.babelrc#L10). Also, your Babel config appears to be breaking CommonJS detection – it works if you use the `externalHelpers: true` option in your config.

**Comment by FezVrasta** [comment]
Thanks, I'll look at it and in case I'll post here what I found. Thank you for your time!

**Comment by FezVrasta** [comment]
I fixed the problem with this PR:
https://github.com/FezVrasta/popper.js/pull/147/files
