### ISSUE TITLE
Print code frame for syntax errors

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1158]
This might be a dupe but I can't find the original right now if it is... when an error has location info attached to it we should include a code frame with the error object (and print it, when using the CLI)

**Comment by piotr-cz** [comment]
Indeed.
I'm trying to use a _rollup-plugin-string_ to import svg files and all I see on the console is generic error 
`Error parsing xxx icons.svg: Unexpected token (1:0)`.

It took me some some time to realize that the problem may be in rollup itself but I have no idea which line in it's source code is throwing an error

**Comment by Rich-Harris** [comment]
Found the original – this is a dupe of #296. Closing
