### ISSUE TITLE
Variable and function rename can be optimization

### ISSUE THREAD

**Issue by nuintun** [rollup/rollup#1159]
See examples: 

[DEMO](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwZWZmZWN0cyUyMCU3RCUyMGZyb20lMjAnLiUyRmVmZmVjdHMuanMnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhlZmZlY3RzKGRvY3VtZW50LmJvZHkpKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJpcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJ2YXIlMjBPUCUyMCUzRCUyME9iamVjdC5wcm90b3R5cGUlM0IlNUNudmFyJTIwdG9TdHJpbmclMjAlM0QlMjBPUC50b1N0cmluZyUzQiU1Q24lNUNuJTJGKiolNUNuJTIwKiUyMHR5cGUlNUNuJTIwKiU1Q24lMjAqJTIwJTQwZXhwb3J0JTVDbiUyMColMjAlNDBwYXJhbSUyMCU3QkFueSU3RCUyMHZhbHVlJTVDbiUyMColMjAlNDByZXR1cm5zJTVDbiUyMColMkYlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB0eXBlKHZhbHVlKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjB0b1N0cmluZy5jYWxsKHZhbHVlKSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZWZmZWN0cy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjB0eXBlJTIwJTdEJTIwZnJvbSUyMCcuJTJGaXMuanMnJTNCJTVDbiU1Q24lMkYlMkYlMjBhbmltYXRpb24lNUNudmFyJTIwQU5JTUFUSU9OJTIwJTNEJTIwJ2FuaW1hdGlvbiclM0IlNUNuJTJGJTJGJTIwdHJhbnNpdGlvbiU1Q252YXIlMjBUUkFOU0lUSU9OJTIwJTNEJTIwJ3RyYW5zaXRpb24nJTNCJTVDbiU1Q24lMkYqKiU1Q24lMjAqJTIwdG9BcnJheSU1Q24lMjAqJTVDbiUyMColMjAlNDBwYXJhbSUyMCU3QkFueSU3RCUyMHZhbHVlJTVDbiUyMColMjAlNDByZXR1cm5zJTIwJTdCQXJyYXklN0QlNUNuJTIwKiUyRiU1Q25mdW5jdGlvbiUyMHRvQXJyYXkodmFsdWUpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHR5cGUodmFsdWUpJTIwJTNEJTNEJTNEJTIwJyU1Qm9iamVjdCUyMFN0cmluZyU1RCclMjAlM0YlMjB2YWx1ZS5zcGxpdCgnJTJDJTIwJyklMjAlM0ElMjAlNUIlNUQlM0IlNUNuJTdEJTVDbiU1Q24lMkYqKiU1Q24lMjAqJTIwZWZmZWN0cyU1Q24lMjAqJTVDbiUyMColMjAlNDBwYXJhbSUyMCU3QkhUTUxFbGVtZW50JTdEJTIwZWxlbWVudCU1Q24lMjAqJTIwJTQwcmV0dXJucyU1Q24lMjAqJTJGJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwZWZmZWN0cyhlbGVtZW50KSUyMCU3QiU1Q24lMjAlMjB2YXIlMjB0eXBlJTNCJTVDbiUyMCUyMHZhciUyMHN0eWxlcyUyMCUzRCUyMHdpbmRvdy5nZXRDb21wdXRlZFN0eWxlKGVsZW1lbnQlMkMlMjBudWxsKSUzQiU1Q24lMjAlMjB2YXIlMjB0cmFuc2l0aW9uRHVyYXRpb25zJTIwJTNEJTIwdG9BcnJheShzdHlsZXMuZ2V0UHJvcGVydHlWYWx1ZShUUkFOU0lUSU9OJTIwJTJCJTIwJy1kdXJhdGlvbicpKSUzQiU1Q24lMjAlMjB2YXIlMjBhbmltYXRpb25EdXJhdGlvbnMlMjAlM0QlMjB0b0FycmF5KHN0eWxlcy5nZXRQcm9wZXJ0eVZhbHVlKEFOSU1BVElPTiUyMCUyQiUyMCctZHVyYXRpb24nKSklM0IlNUNuJTIwJTIwdmFyJTIwdGltZW91dCUyMCUzRCUyME1hdGgubWF4KHRyYW5zaXRpb25EdXJhdGlvbnMlMkMlMjBhbmltYXRpb25EdXJhdGlvbnMpJTNCJTVDbiUyMCUyMCU1Q24lMjAlMjB0eXBlJTIwJTNEJTIwdGltZW91dCUyMCUzRSUyMDAlMjAlNUNuJTIwJTIwJTIwJTIwJTNGJTIwKHRyYW5zaXRpb25EdXJhdGlvbnMlMjAlM0UlMjBhbmltYXRpb25EdXJhdGlvbnMlMjAlM0YlMjBUUkFOU0lUSU9OJTIwJTNBJTIwQU5JTUFUSU9OKSUyMCU1Q24lMjAlMjAlNUN0JTNBJTIwbnVsbCUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTdCJTVDbiUyMCUyMCU1Q3R0eXBlJTNBJTIwdHlwZSUyQyU1Q24lMjAlMjAlMjAlMjB0aW1lb3V0JTNBJTIwdGltZW91dCU1Q24lMjAlMjAlN0QlM0IlNUNuJTdEJTIyJTdEJTVEJTdE) and #992 

source:
>is.js
```js
var OP = Object.prototype;
var toString = OP.toString;

/**
 * type
 *
 * @export
 * @param {Any} value
 * @returns
 */
export function type(value) {
  return toString.call(value);
}
```

>effects.js
```js
import { type } from './is.js';

// animation
var ANIMATION = 'animation';
// transition
var TRANSITION = 'transition';

/**
 * toArray
 *
 * @param {Any} value
 * @returns {Array}
 */
function toArray(value) {
  return type(value) === '[object String]' ? value.split(', ') : [];
}

/**
 * effects
 *
 * @param {HTMLElement} element
 * @returns
 */
export function effects(element) {
  var type;
  var styles = window.getComputedStyle(element, null);
  var transitionDurations = toArray(styles.getPropertyValue(TRANSITION + '-duration'));
  var animationDurations = toArray(styles.getPropertyValue(ANIMATION + '-duration'));
  var timeout = Math.max(transitionDurations, animationDurations);
  
  type = timeout > 0 
    ? (transitionDurations > animationDurations ? TRANSITION : ANIMATION) 
  	: null;

  return {
  	type: type,
    timeout: timeout
  };
}
```

>main.js
```js
import { effects } from './effects.js';

console.log(effects(document.body));
```
output:
>bundle.js
```js
(function() {
  'use strict';

  var OP = Object.prototype;
  var toString = OP.toString;

  /**
   * type
   *
   * @export
   * @param {Any} value
   * @returns
   */
  function type(value) {
    return toString.call(value);
  }

  // animation
  var ANIMATION = 'animation';
  // transition
  var TRANSITION = 'transition';

  /**
   * toArray
   *
   * @param {Any} value
   * @returns {Array}
   */
  function toArray(value) {
    return type(value) === '[object String]' ? value.split(', ') : [];
  }

  /**
   * effects
   *
   * @param {HTMLElement} element
   * @returns
   */
  function effects(element) {
    var type$$1;
    var styles = window.getComputedStyle(element, null);
    var transitionDurations = toArray(styles.getPropertyValue(TRANSITION + '-duration'));
    var animationDurations = toArray(styles.getPropertyValue(ANIMATION + '-duration'));
    var timeout = Math.max(transitionDurations, animationDurations);

    type$$1 = timeout > 0 ?
      (transitionDurations > animationDurations ? TRANSITION : ANIMATION) :
      null;

    return {
      type: type$$1,
      timeout: timeout
    };
  }

  console.log(effects(document.body));
}());
```

The block scope local variable ```type``` in method ```effects``` of  ```bundle.js```  be renamed!

But a block scope local variable no necessary be renamed.

**Comment by Rich-Harris** [comment]
It's renamed because the shadowed name *could* be used in a way that would cause bugs. Walking the AST to find out whether or not that's the case would be extra work, so Rollup doesn't bother – the resulting behaviour is the same, and after minification the code is identical.
