### ISSUE TITLE
Default Export in non-ES6 formats

### ISSUE THREAD

**Issue by snuggles08** [rollup/rollup#116]
`export default MyDefaultExport; export {MyNonDefaultExport};` should normally create this structure:
```js
// MyDefaultExport
{
  export: 'Default'
}
// MyNonDefaultExport
{
  otherexport: 'NonDefault'
}
// What consumers see
{
  export: 'Default',
  MyNonDefaultExport: {
    otherexport: 'NonDefault'
  }
}
// Currently
{
  default: {
    export: 'Default'
  },
  MyNonDefaultExport: {
    otherexport: 'NonDefault'
  }
}
```

**Comment by snuggles08** [comment]
Just noticed this was documented. Maybe add a new export setting using Object.assign?

**Comment by Rich-Harris** [comment]
I'd argue that mixing everything into a single object is a bit confusing and likely to cause interoperability problems – could you outline the scenario in a bit more detail?

**Comment by snuggles08** [comment]
Not by default, but maybe `exports: merge` should `Object.assign` with a `named` export without the default export as a source and the default export as the target.

**Comment by Rich-Harris** [comment]
I'm still not sure I understand what the rationale is?

**Comment by snuggles08** [comment]
Having to use `mylibrary['default']` isn't exactly the most intuitive...

**Comment by Rich-Harris** [comment]
But if it's your library, you have a choice to *not use the default export*. If you only use the default export, or only use named exports, there's no problem at all with interoperability. It sounds like in this case you'd be better off just using named exports, rather than trying to go against the grain (and spec!) of ES6 modules.

**Comment by snuggles08** [comment]
For my library, the default export is the library and the `Module` named export is for extensions.

**Comment by Rich-Harris** [comment]
I've taken a look at https://github.com/PkmnLib/pkmnlib-core, which I assume is the library you're referring to? As far as I can see, since you can't do anything without `Module`, there's no real value to having it as a separate export rather than doing the ES5 `pkmnLib.Module = PkmnLibModule` thing.

That way, someone could still use the library like so:

```js
import pkmnLib, { Module } from 'pkmblib-core';

// or like this
import pkmnLib from 'pkmnlib-core';
const { Module } = pkmnLib;
```

But equally, there doesn't seem to be any reason that you *have* to use the default export:

```js
// why not this?
import { pkmnLib, Module } from 'pkmnlib-core';
```

**Comment by Victorystick** [comment]
For clarification. Some ES6 module like
```js
export default { export: 'Default' };
var MyNonDefaultExport = { otherexport: 'NonDefault' };
export { MyNonDefaultExport };
```
when imported using a non-ES6 module format, etc. CommonJS. looks like:
```js
var lib = require( './main.js' );

assert.equal( lib, {
  default: {
    export: 'Default'
  },
  MyNonDefaultExport: {
    otherexport: 'NonDefault'
  }
});
```
while you'd like it to be more inline with how its done in CommonJS and the like, where the non-default exports are made properties on the "default"?

It isn't always possible to do so. The following example, if 
```js
function a () {}
a.important = 1;
export default a; // module.exports = a;

var important = 2;
export { important }; // Object.assign( a, { important } );
```
would result in the `a` function's `important` property being overwritten.

**Comment by snuggles08** [comment]
@Victorystick Yes. About the second example, I was thinking just cause an error.

**Comment by snuggles08** [comment]
@Rich-Harris Usually, the `Module`, when combined with a proper `config.js` file, is never used from a user standpoint. So, if you `npm install` a module, (which in turn `npm install`s a blank config), rollup will use `js:next` to load that module in `config.js`, allowing it to be used in a final build.

**Comment by Rich-Harris** [comment]
@snuggles08 Your requirements are very niche! There are a few solutions outlined here that would work (I would do `pkmnLib.Module = PkmnLibModule` personally), so I'm going to close this issue for now.

**Comment by tbranyen** [comment]
Just wanted to note that this is a problem with function exports as well. I have the API:

``` js
export default function MyMiddleware() {

}
```

And would like to be able to export this function under the global `MyMiddleware`, so it can be invoked like `use(MyMiddleware())`. Haven't found a solution yet. Sorry for pinging a 2yr old thread.
