### ISSUE TITLE
Prevent rollup from changing variable names

### ISSUE THREAD

**Issue by tresdin** [rollup/rollup#1161]
I've found that `rollup` automatically assigns `$1`, `$2`, etc at the end of some global variable names in the bundled files. This single behaviour is seriously breaking my application. 

How can I config `rollup` for preventing this unexpected action?

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by tresdin** [comment]
@Rich-Harris As required, I've made a repro for this issue.
https://github.com/tresdin/rollup_issue_changing_variable_names
Please inform me if you need any further information.

**Comment by Rich-Harris** [comment]
@tresdin you're trying to run a CommonJS module in a browser. You need to use `format: 'iife'` (or `umd`), not `cjs`.

**Comment by tresdin** [comment]
@Rich-Harris I feel so dumb right now. Thank you for poiting it out @Rich-Harris
