### ISSUE TITLE
Split up bundle to parts

### ISSUE THREAD

**Issue by PFight** [rollup/rollup#1170]
### Now

Rollup allow to build one tree-shaked bundle, and it is great. Also, rollup allow to exclude some dependencies from that bundle, making it "external". But, if dependencies made external, they are can't be tree-shaked and should be included as is.

### Suggestion

It would be great to make middle case: we are making full tree-shake as in first case (single bundle), and then extracting from this bundle some parts as separate bundles. It will allow split up app bundle to parts, and load them "on-demand". Thats more, we will able to reuse common parts (common dependencies) by loading them once.

### Example

There is Angular2  - it is big. There is my app, that uses Angular2 - it is big too. I want to split up my app to 3 parts and load specific part only for specific routes to minimize loading overhead. Now I can create 3 bundles with rollup, but every part will contain Angular2. Or I can mark Angular2 as external dependency, but in that case it would be not tree-shaked, and become ~1Mb size (instead of 60-200Kb tree-shaked). 

Preffered way - create tree-shaked Angluar2 bundle (that contains only code, that used by whole application), and create 3 app bundles (without Angular2). Then I will load once that Angular2 bundle, and dynamicly load every app bundle only when it is needed for specific route.

**Comment by tivac** [comment]
See #372 for the current state of this feature.

Such as it is 😞

**Comment by Rich-Harris** [comment]
Yep, will close this in favour of #372. Unfortunately we need to get on top of the issue list before we can make a start on ambitious new features, but it *is* something we want to do.
