### ISSUE TITLE
Variable not postfixed correctly with 0.38

### ISSUE THREAD

**Issue by danez** [rollup/rollup#1176]
When updating rollup in babylon to 0.38 the bundle that gets created is invalid and leads to endless loops. It workes fine with 0.37.2

The difference in the bundles is appended.

The difference in parse() might be okay, as there is not other parse function in the same scope. But for isKeyword() it does not work, as you can see it is now simply calling itself.

Here is the link to the PR: https://github.com/babel/babylon/pull/265 and in there you also find the results from the CI.

```diff
--- 	2016-12-22 21:58:56 +0000
+++ 	2016-12-22 21:58:56 +0000
@@ -30,7 +30,7 @@
 
 // And the keywords
 
-var isKeyword$1 = makePredicate("break case catch continue debugger default do else finally for function if return switch throw try var while with null true false instanceof typeof void delete new in this let const class extends export import yield super");
+var isKeyword = makePredicate("break case catch continue debugger default do else finally for function if return switch throw try var while with null true false instanceof typeof void delete new in this let const class extends export import yield super");
 
 // ## Character categories
 
@@ -629,7 +629,7 @@
   // TODO
 
   Tokenizer.prototype.isKeyword = function isKeyword(word) {
-    return isKeyword$1(word);
+    return isKeyword(word);
   };
 
   // TODO
@@ -6468,9 +6468,9 @@
 plugins.flow = flowPlugin;
 plugins.jsx = jsxPlugin;
 
-function parse$1(input, options) {
+function parse(input, options) {
   return new Parser(options, input).parse();
 }
 
-exports.parse = parse$1;
+exports.parse = parse;
 exports.tokTypes = types;

```

**Comment by Rich-Harris** [comment]
Thanks – [reduced test case here](http://rollupjs.org/?version=0.38.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwaXNLZXl3b3JkJTIwYXMlMjBfaXNLZXl3b3JkJTIwJTdEJTIwZnJvbSUyMCcuJTJGZm9vLmpzJyUzQiU1Q24lNUNuZnVuY3Rpb24lMjBUb2tlbml6ZXIlMjAoKSUyMCU3QiU3RCUzQiU1Q24lNUNuVG9rZW5pemVyLnByb3RvdHlwZS5pc0tleXdvcmQlMjAlM0QlMjBmdW5jdGlvbiUyMGlzS2V5d29yZCUyMCglMjB3b3JkJTIwKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBpc0tleXdvcmQoJTIwd29yZCUyMCklM0IlNUNuJTdEJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBUb2tlbml6ZXIlMjAlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwaXNLZXl3b3JkJTIwKCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJyUzRiUzRiUzRiclM0IlNUNuJTdEJTIyJTdEJTVEJTdE)

**Comment by danez** [comment]
I fixed the reduced testcase and run git bisect

Reduced testcase: [here](http://rollupjs.org/?version=0.38.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwaXNLZXl3b3JkJTIwYXMlMjBfaXNLZXl3b3JkJTIwJTdEJTIwZnJvbSUyMCcuJTJGZm9vLmpzJyUzQiU1Q24lNUNuZnVuY3Rpb24lMjBUb2tlbml6ZXIlMjAoKSUyMCU3QiU3RCUzQiU1Q24lNUNuVG9rZW5pemVyLnByb3RvdHlwZS5pc0tleXdvcmQlMjAlM0QlMjBmdW5jdGlvbiUyMGlzS2V5d29yZCUyMCglMjB3b3JkJTIwKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBfaXNLZXl3b3JkKCUyMHdvcmQlMjApJTNCJTVDbiU3RCUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwVG9rZW5pemVyJTIwJTdEJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGlzS2V5d29yZCUyMCgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCclM0YlM0YlM0YnJTNCJTVDbiU3RCUyMiU3RCU1RCU3RA==)


Commit that introduced the regression: 553abd9873ffb100818614f7d9db1cac27acb0ac

**Comment by kzc** [comment]
```
function Tokenizer () {};

Tokenizer.prototype.isKeyword = function isKeyword ( word ) {
  return isKeyword( word );
};
```
This is very similar to the Bublé regression: https://gitlab.com/Rich-Harris/buble/issues/166 which was recently fixed/merged and waiting for a release. Might Buble be the culprit?
