### ISSUE TITLE
Skip warning about named exports when `exports = 'none'`

### ISSUE THREAD

**Issue by legomind** [rollup/rollup#1181]
The following warning is useless when `exports = 'none'`

```
Using named and default exports together. Consumers of your bundle will have to use 
bundle['default'] to access the default export, which may not be what you want.
Use `exports: 'named'` to disable this warning. 
See https://github.com/rollup/rollup/wiki/JavaScript-API#exports for more information
```

**Comment by bfred-it** [comment]
It sounds like you're not actually assigning `exports = 'none'` because that warning only appears when `exports = 'auto'` or `exports = undefined`

https://github.com/rollup/rollup/blob/a9f342cb26d14ae8ee93a8f8f39f35dc968e3461/src/utils/getExportMode.js#L20

What's your code?

**Comment by Rich-Harris** [comment]
Moreover, Rollup would throw an error if `exports` was set to `none` and your entry module was exporting anything. [Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff), thanks
