### ISSUE TITLE
Provide option for listing each file in the dependency graph

### ISSUE THREAD

**Issue by kasbah** [rollup/rollup#1184]
Browserify does this and I need it for properly working with Make and [Ninja Build](http://ninja-build.org/). From `browserify --help advanced`:

```
  --list
 
    Print each file in the dependency graph. Useful for makefiles.
```

Ways that this could be improved from how Browserify works: 

1. Have the option to emit the list while also emitting the bundle. With Broswerify you have to run it twice instead which takes a lot of time. 
1. Output in a makefile format, like C/C++ compilers do. Both Make and Ninja expect this behaviour.

**Comment by bfred-it** [comment]
Also mentioned here: https://github.com/rollup/rollup/issues/1369

**Comment by lukastaegert** [comment]
Note that at this point, the plugin API should provide all necessary information to create a plugin that does that.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by kasbah** [comment]
I'd still find it useful, but if it's a plugin that would be fine too.
