### ISSUE TITLE
class static properties

### ISSUE THREAD

**Issue by liangxingchen** [rollup/rollup#1185]
```js
class Foo{
  static baz = 1;
  static bar() {
    return Foo.baz;
  }
}
```

 SyntaxError: Unexpected token (2:13) in main.js

**Comment by bfred-it** [comment]
That's not valid Javascript. It's only a proposal: https://github.com/tc39/proposal-class-public-fields

You might need to use `rollup-plugin-babel` and [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/)

**Comment by Rich-Harris** [comment]
Closing – as @bfred-it says, you need to convert the input to JavaScript first

**Comment by andrevenancio** [comment]
so I'm using rollup for a library I'm building and I want to export my app both in ES5 and ES6.

ES5 is sorted, I'm using babel and the transform-class-properties as suggested.
But to export it as a module (pure ES6) isn't there a way of adding static classes to rollup itself? sucks to have to re-write a bunch of classes. static classes are very handy.

**Comment by guybedford** [comment]
@andrevenancio you can add the acorn plugin for handling this via `npm install acorn-static-class-property-initializer` and then using the rollup configuration option - `acornInjectPlugins: [require('acorn-static-class-property-initializer/inject')]`.

**Comment by piotr-cz** [comment]
Seems that above https://github.com/rollup/rollup/issues/1185#issuecomment-384631306 doesn't work anymore, may be because _acorn-static-class-property-initializer_ depends on acorn 5, while rollup now uses acorn 6 (`TypeError: plugins[i] is not a function`)

**Comment by trusktr** [comment]
I ran into this unexpected token error today on class fields using Rollup ^2.47 and plugin-buble ^0.21.0.

The defaults in Buble seems to be a bit outdated. Every browser supports the syntax nowadays, and there should be no need to fuss with having to customize acorn plugins. The fix was easy though: all syntax is supported nowadays, so I simply removed buble from my rollup config.
