### ISSUE TITLE
Importing PostCSS in rollup bundle not working

### ISSUE THREAD

**Issue by sadiqevani** [rollup/rollup#1190]
Hello,

I am trying to import PostCSS as a dependency inside a project of mine, but i am having some issues doing that.

Somehow the "import" functionality does not work i suppose.

I recreieve the following error when i try to run it:

```
function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) { Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; } }
```

```
TypeError: Super expression must either be null or a function, not undefined
    at _inherits (/Users/sadiqevani/Laboratory/qurate-engine/main/index.js:6549:113)
    at /Users/sadiqevani/Laboratory/qurate-engine/main/index.js:6562:5
    at /Users/sadiqevani/Laboratory/qurate-engine/main/index.js:6669:2
    at createCommonjsModule (/Users/sadiqevani/Laboratory/qurate-engine/main/index.js:49:35)
    at /Users/sadiqevani/Laboratory/qurate-engine/main/index.js:6530:14
    at buffer (/Users/sadiqevani/Laboratory/qurate-engine/main/index.js:2:82)
    at Object.<anonymous> (/Users/sadiqevani/Laboratory/qurate-engine/main/index.js:5:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

I assume this is because of some "import conversion", anyone had this problem?

**Comment by marvinhagemeister** [comment]
How do you import PostCSS? Can you post some of your code?

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by sadiqevani** [comment]
Couldn't fix, probably there's something wrong i am doing!

**Comment by marvinhagemeister** [comment]
@sadiqevani We can't help you further without seeing your config :)

**Comment by tivac** [comment]
I just ran into this and made a repro.

https://gist.github.com/tivac/5e392a94903989cdc5fc786c2bc585eb

Seems like the inclusion of `container.js` is failing for some reason. Since PostCSS is using ES2015 Modules anyways it's too bad they don't ship that via npm.

**Comment by tivac** [comment]
@sadiqevani Would you re-open this please?

**Comment by sadiqevani** [comment]
@tivac Done, i haven't managed to get through that issue yet, its still pending on my issue list, but right now i have some other priorities. But would be awesome if it could be fixed.
