### ISSUE TITLE
Built-in symbols like valueOf don’t play nice.

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#12]
For example, consider test.js:

```js
import foo from "./foo";

export {
  foo
};
```

And foo.js:

```js
function valueOf() {
  return 42;
}

export default function() {
  return valueOf();
};
```

The output from `rollup -b -- test.js` lacks the valueOf function:

```js
var foo = function() {
  return valueOf();
}

export { foo };
```

Renaming the function to valueOf_ works around the issue. I suspect there is code somewhere that is using an Object as a map when it should be using a Map.

**Comment by Rich-Harris** [comment]
Yep, there was a missing hasOwnProperty check - have replaced all `{}` instances with a helper that returns `Object.create(null)`, which has the desired effect

**Comment by mbostock** [comment]
Thanks for fixing this.
