### ISSUE TITLE
generated bin/rollup not chmod +x

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#1209]
```
$ bin/rollup
bash: bin/rollup: Permission denied
```
```
$ node bin/rollup 

rollup version 0.39.2
=====================================

Usage: rollup [options] <entry file>
```

**Comment by Rich-Harris** [comment]
That's weird, how did this not surface before? What changed?

Hopefully #1210 fixes is

**Comment by kzc** [comment]
It's always been that way. I just got tired of typing in the `node` prefix today and made a ticket. ;-)

Maybe `npm install rollup` does the `chmod +x` automatically?

**Comment by mutech** [comment]
It would be nice if you could specify an optional output parameter `mode` for the primary output. That's more portable than assuming that there is a chmod or having to use shx just for that purpose. (rollup is creating the file and would just need to add the mode parameter to its write/open call.
