### ISSUE TITLE
Source Map 'inline' documented but not implemented

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#121]

**Comment by Rich-Harris** [comment]
Oops. Right you are. It *is* implemented, but not in the way the docs said – basically it only works (and only really makes sense) in the context of [bundle.write](https://github.com/rollup/rollup/wiki/JavaScript-API#bundlewrite-options-):

```js
bundle.write({
  dest: 'bundle.js',
  format: 'cjs',
  sourceMap: 'inline'
}).then(...);
```

To do it with `bundle.generate` you'd manually append it:

```js
let { code, map } = bundle.generate({
  format: 'cjs',
  sourceMap: true,
  sourceMapFile: 'bundle.js'
});

code += '\n//# sourceMappingURL=' + map.toUrl();
require( 'fs' ).writeFile( 'bundle.js', code );
```

I've updated the docs.
