### ISSUE TITLE
Warning "Creating a browser bundle that depends on Node.js built-in module" is always displayed

### ISSUE THREAD

**Issue by danielbayerlein** [rollup/rollup#1211]
I'm trying to update rollup.js and get the following warning:

```
⚠   Creating a browser bundle that depends on Node.js built-in module ('events'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
```

I've already added `import builtins from 'rollup-plugin-node-builtins'` and `plugins: [ builtins() ]`. The output file works with and without `rollup-plugin-node-builtins` . 

What am I doing wrong? 😕 Thanks for your support!

* Repository
  * https://github.com/developit/precharts/tree/update-dependencies
* `rollup.config.js`
  * https://github.com/developit/precharts/blob/update-dependencies/rollup.config.js
* `package.json`
  * https://github.com/developit/precharts/blob/update-dependencies/package.json

**Comment by danielbayerlein** [comment]
@developit Do you have an idea what is wrong?

**Comment by developit** [comment]
Never seen that before @danielbayerlein. It looks like Recharts [does now use `events`](https://github.com/recharts/recharts/blob/580ac55e4374ef2ef9ebeaf0adda8bc35f1ca36d/src/util/Events.js#L1) though, which I guess requires injecting a [browserify-compatible version](https://github.com/Gozala/events)

**Comment by danielbayerlein** [comment]
@developit You're right! It's not a rollup issue - sorry!

**Comment by fab1o** [comment]
@danielbayerlein I'm having the exact same issue. What is the fix for this?
