### ISSUE TITLE
Allow hiding warnings and etc output

### ISSUE THREAD

**Issue by tunnckoCore** [rollup/rollup#1213]
I believe we can move showing the warnings behind `--verbose` flag (and `config.verbose`) for example?

The code is here https://github.com/rollup/rollup/blob/master/bin/src/runRollup.js#L67-L70

**Comment by Rich-Harris** [comment]
Added a `--silent` flag, which suppresses warnings, in the next release. Will probably add `--verbose` in the future when we add extra info (dependency graph, bundle size etc) to the output per  #651
