### ISSUE TITLE
Allow passing source code instead of filepath entry

### ISSUE THREAD

**Issue by tunnckoCore** [rollup/rollup#1214]
As it seems I'm building a wrapper around Rollup, because some needs, but anyway.

I believe it would be useful not only in my case.

It would be good to be able to pass source code directly, instead of passing path to `options.entry` which must point to real file to be read.

Maybe `options.code` or `options.source`?

**Comment by tunnckoCore** [comment]
My workaround is just with native `os.tmpdir` and `uuid` then i'm passing path to that generated temp file.

**Comment by Rich-Harris** [comment]
Modules need to have IDs (otherwise their import statements don't have anything to be resolved against) – usually a file, but not necessarily (e.g. plugins create 'virtual modules'). For that reason, you *have* to have an entry module ID.

This is a problem that's probably best solved with a plugin:

```js
// rollup.config.js
import source from 'rollup-plugin-source'; // doesn't exist yet!

export default {
  entry: 'x',
  dest: 'bundle.js',
  format: 'cjs',
  plugins: [
    source({
      // normal resolution logic would apply, i.e. entry is `path.resolve('x')`
      x: `import y from './y.js'; console.log( y );`,

      // could also take code/map combo maybe
      y: {
        code: '...',
        map: {...}
      }
    })
  ]
};
```

```js
// rollup-plugin-source
import { resolve } from 'path';

export default function source ( options ) {
  const modules = {};
  Object.keys( options ).forEach( id => {
    modules[ resolve( id ) ] = options[ id ];
  });

  return {
    name: 'source',

    load ( id ) {
      return modules[ id ];
    }
  };
}
```

**Comment by tunnckoCore** [comment]
Hm. This plugin looks interesting, pretty better than writing to disk. But how rollup will understand.. actually, how will find that `entry: 'x'`?

**Comment by Rich-Harris** [comment]
The `entry` option is always resolved against the CWD, so `x` becomes `path/to/x`. So if the `source` plugin resolves all the option keys the same way (using `path.resolve`), `x: '...'` will get picked up by it. The advantage of doing it that way is you can mix and match files in disk with things that are passed in as an option to `source`, plus things in `node_modules` etc.
