### ISSUE TITLE
How to deal with Object.entries?

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#1216]
What is the proper course of action if one wishes to run process a Javascript file containing `Object.entries()` and have the output run on ES2015?

I tried processing files with Babel, followed by rollup. Because Babel's output does not contain ES6 modules, rollup doesn't know to bundle the modules.

So it looks like I can get unbundled ES2015 files, or bundled ES6 files. Any ideas?

**Comment by cowwoc** [comment]
Nevermind. I found https://github.com/rollup/rollup-plugin-babel

Sorry for the false alarm.

**Comment by HiroAgustin** [comment]
@cowwoc may I ask how did you manage to setup babel/rollup to include `Object.entries`? I'm getting the following error:

```
[!] Error: 'default' is not exported by node_modules/babel-runtime/core-js/object/entries.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/index.js (2:7)
1: import _Object$entries from 'babel-runtime/core-js/object/entries';
          ^
```

Notice that I had to change my config (replace `"external-helpers"` plugin with `"transform-runtime"` as indicated in this response: https://stackoverflow.com/questions/35090153/babel-support-for-object-entries/35382020

**Comment by cowwoc** [comment]
@HiroAgustin Did you try https://stackoverflow.com/a/35382020/14731?

**Comment by cowwoc** [comment]
@HiroAgustin I honestly don't remember and I am not actively working on any code that needs this fix so I can't easily double-check either. Sorry.
