### ISSUE TITLE
Importing functions from ramda.js throws error

### ISSUE THREAD

**Issue by tencircles** [rollup/rollup#1220]
Hey, 

Just trying to use ramda with rollup and I'm getting the following error. 

🚨   'compose' is not exported by node_modules/ramda/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

The code that produces the error is simply 

````javascript
import {compose} from "ramda";
````

The rollup.config.js looks like this

````javascript
// Rollup plugins
import babel from "rollup-plugin-babel";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";

export default {
    entry     : "src/test.js",
    dest      : "dist/test.js",
    format    : "iife",
    sourceMap : "inline",
    plugins   : [
        resolve({
            jsnext  : true,
            main    : true,
            browser : true
        }),
        commonjs(),
        babel({
            exclude : "node_modules/**"
        })
    ]
};
````
Here's a stack trace, any help is greatly appreciated. Was really looking forward to using rollup in this project, but it seems like it's back to webpack. compose, as well as every other ramda function is pretty clearly exported by the file: node_modules/ramda/index.js

<details>
  <summary>Stack trace</summary>
Error: 'compose' is not exported by node_modules/ramda/index.js
    at error (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:7979:2)
    at Module.trace (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:8074:9)
    at ModuleScope.findDeclaration (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:7663:22)
    at Identifier.bind (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:6726:29)
    at /Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:5291:50
    at UnaryExpression.eachChild (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:5308:5)
    at UnaryExpression.bind (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:5291:7)
    at UnaryExpression.bind (/Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:7189:53)
    at /Users/chris/Projects/web/dinahmoe/dmafjs/dmafjs-core/node_modules/rollup/dist/rollup.js:5291:50
</details>
-->

**Comment by kzc** [comment]
Try adding a `namedExports` block in `commonjs()` for `ramda`:

https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

**Comment by tencircles** [comment]
Seems to work, but is this the only solution? I don't think maintaining a named list of every function ramda exports as a part of my build config is a very tenable solution.

**Comment by tencircles** [comment]
ok came up with a decent solution. 


```javascript
commonjs({
            namedExports : {
                "node_modules/ramda/index.js" : Object.keys(require("ramda"))
            }
        }),
````

thanks for the help

**Comment by kzc** [comment]
If there was a native ES distro of `ramda` using `import` and `export` instead of `require()` you wouldn't have to do this. But since it's in cjs format you have to jump through some hoops.

Looking at the way ramda exports its symbols in cjs format:
```
module.exports = {
  F: require('./src/F'),
  T: require('./src/T'),
  __: require('./src/__'),
  add: require('./src/add'),
  addIndex: require('./src/addIndex'),
  adjust: require('./src/adjust'),
...
```
I suspect that rollup will include every unused ramda symbol in the final bundle. 

To reduce the final bundle size, you could code in this manner:
```
import {default as compose} from "ramda/src/compose.js";
```
and you wouldn't need to have namedExports in commonjs().

**Comment by kzc** [comment]
@tencircles This plugin will give you the import syntax you want (`import {compose} from "ramda";`) without bundling unused ramda functions:

https://github.com/idmitriev/rollup-plugin-ramda

Not sure whether rollup bundling times will be improved though.
