### ISSUE TITLE
Turning treeshake off breaks app if you import rxjs

### ISSUE THREAD

**Issue by robianmcd** [rollup/rollup#1221]
Using the following config

```js
let commonjs = require('rollup-plugin-commonjs');
let nodeResolve = require('rollup-plugin-node-resolve');

export default {
    entry: 'main.js',
    dest: 'bundle.js',
    format: 'iife',
    treeshake: false,
    plugins: [
        nodeResolve({jsnext: true, module: true}),
        commonjs({include: 'node_modules/rxjs/**'})
    ]
};
```

and the following main.js

```
import {Observable} from "rxjs/Observable";

console.log('imported observable', Observable);
```

My app will throw the following exception `Uncaught ReferenceError: __moduleExports is not defined`.

If I set `treeshake` to true everything works as expected.

My use case is that I am trying to speed up the build for an angular 2 app by disabling treeshaking in development (and leaving it on in the prod build).

Here is a minimal app that reproduces the issue
[rollup-app.zip](https://github.com/rollup/rollup/files/686068/rollup-app.zip)

Any idea what could be causing this?

**Comment by lukastaegert** [comment]
Seems this is already fixed in rollup@0.50.1 (possibly together with fixes in rollup-plugin-commonjs), closing it now.
