### ISSUE TITLE
Issue with using rollup with Parse-JS-SDK

### ISSUE THREAD

**Issue by caoer** [rollup/rollup#1228]
![1__tmux__tmux_](https://cloud.githubusercontent.com/assets/225856/21708542/d63cbbd2-d3a7-11e6-8638-de73852a7618.png)

I'm having issue with compiling Parse js SDK. it shows that I should use named exports, but I dont' understand how to specify 'default' named exports. It seems fine to use webpack to compile it (but the code webpack compiled seems having issue running..still working on that). I want to compile the Parse library to use in iOS 'JavascriptCore' environment. It's not a React Native environment, but I'm trying to make it compatible with RN. Any help will be much appreciated. 😺 

Here is the demo repo: 
https://github.com/caoer/Parse-SDK-JS/
commit: 
https://github.com/caoer/Parse-SDK-JS/commit/bad30292b40dd6eb3675e50e37353b934098d23a

**Comment by Rich-Harris** [comment]
The error message says that `CoreManager` doesn't export `default`. [Sure enough, it doesn't](https://github.com/caoer/Parse-SDK-JS/blob/bad30292b40dd6eb3675e50e37353b934098d23a/src/CoreManager.js#L166) — it uses `module.exports = ...` instead. Replace that with `export default ...` and see if it fixes the issue.

**Comment by jhabdas** [comment]
Stale
