### ISSUE TITLE
`new Class` with side effects erroneously removed

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#1233]
**Input**

$ cat new.js 
```js
class Foo {
    constructor() {
        console.log("Foo");
    }
}
new Foo;
```
**Expected output**

$ node new.js
```
Foo
```
**rollup@0.41.0 output**

$ bin/rollup new.js -f es | node
```
⚠️   Generated an empty bundle
```

**Suggested fix**

```patch
--- a/src/ast/nodes/NewExpression.js
+++ b/src/ast/nodes/NewExpression.js
@@ -2,7 +2,7 @@ import Node from '../Node.js';
 import callHasEffects from './shared/callHasEffects.js';
 
 export default class NewExpression extends Node {
-       hasEffects ( scope ) {
-               return callHasEffects( scope, this.callee, true );
+       hasEffects () {
+               return true;
        }
 }
```

**Rollup output with fix**

$ bin/rollup new.js -f es
```js
class Foo {
    constructor() {
        console.log("Foo");
    }
}
new Foo;
```
$ bin/rollup new.js -f es | node
```
Foo
```
A few existing rollup tests with incorrect results would have to be updated.

**Comment by kzc** [comment]
Related bug: #980

**Comment by Rich-Harris** [comment]
Ideally we'd be able to determine that the function to test for side-effects is the `constructor`. In the shorter term, what if we just include all new expressions where the callee is a class? https://github.com/rollup/rollup/pull/1234

**Comment by kzc** [comment]
The fix I suggested was a bit drastic because of the seriousness of the error. But if you want to refine it for side effects, by all means. The related bug #980 had a side effect in the super constructor.

**Comment by kzc** [comment]
> what if we just include all new expressions where the callee is a class?

Even if the callee is a function we still want the `new Func` included if it has a side effect.

**Comment by Rich-Harris** [comment]
[That already happens](http://rollupjs.org/?version=0.41.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBBJTIwKCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTIwJ3NpZGUtZWZmZWN0JyUyMCklM0IlMjAlNUNuJTdEJTVDbiU1Q25jbGFzcyUyMEIlMjAlN0IlNUNuJTIwJTIwY29uc3RydWN0b3IlMjAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZyglMjAnc2lkZS1lZmZlY3QnJTIwKSUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25uZXclMjBBKCklM0IlNUNubmV3JTIwQigpJTNCJTIyJTdEJTVEJTdE), it's only classes that were behaving badly.

About to leave my desk so will cut a release with the fix and we can address the false positives another time
