### ISSUE TITLE
`new Class` without side-effects erroneously included

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1235]
Flip-side of https://github.com/rollup/rollup/issues/1233 — now that all `new` expressions involving classes are included, we [include some stuff without side-effects](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY2xhc3MlMjBBJTIwJTdCJTVDbiUyMCUyMGNvbnN0cnVjdG9yJTIwKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHVtYmxld2VlZCU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25uZXclMjBBKCklM0IlMjIlN0QlNUQlN0Q=).

For simple cases (class without a superclass, with either no constructor or a side-effect-free constructor) that's easy enough; the fun will start when superclasses are involved. The more forward-looking fix (than simply locating the `constructor` function) is probably to embed some understanding of how classes and their instances work, since that's what we'll eventually need to do in order to tree-shake unused methods.

**Comment by imcotton** [comment]
Got bitten by `export const instance = new class {}`, searched around with this finding:

https://github.com/eslint/eslint/blob/master/lib/rules/no-useless-constructor.js
