### ISSUE TITLE
export ES6 classes from all files

### ISSUE THREAD

**Issue by 2beers** [rollup/rollup#1236]
Hello. I'm new to rollup. I'm trying to bundle a js library that is split in multiple files
this is my config file
```
export default {
  entry: 'src/a.js',
  dest: 'build/bundle.js',
  format: 'es',
  exports:"named"
};
```

I'm using 

> exports: "named" – suitable if you're exporting more than one thing 
based on what the official doc is saying.

My problem is that not all classes are exported. For example
```
//a.js
import {B} from "./b";
export class A{
//....
}

//b.js
export class B{
//...
}


//bundle.js is built like this
class B{
}
class A{
}
export {A};
```

Is there a way to declare in config so I can have `export class B` as well?
I'm using version 0.40.2

**Comment by Rich-Harris** [comment]
Anything exported from your *entry file* gets exported from the bundle, so you just need to add an `export` declaration to a.js:

```js
//a.js
export {B} from "./b";
export class A{
//....
}
```

That only works if you're not using `B` in a.js — if you are, then you need to import and re-export it:

```js
//a.js
import {B} from "./b";
export class A{
//....
}
export {B};
```

[Demo](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkZhLmpzJTVDbmV4cG9ydCUyMCU3QkIlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmIlNUMlMjIlM0IlNUNuZXhwb3J0JTIwY2xhc3MlMjBBJTdCJTVDbiUyRiUyRi4uLi4lNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY2xhc3MlMjBCJTdCJTVDbiUyRiUyRi4uLiU1Q24lN0QlMjIlN0QlNUQlN0Q=).
