### ISSUE TITLE
[question] Why register e.g. $ as a global vs. referencing like window.$?

### ISSUE THREAD

**Issue by wearhere** [rollup/rollup#1237]
I have a project that loads jQuery from a CDN. The project currently references jQuery without engaging Rollup at all:

```js
// index.js (simplified)
var $ = window.$;
$(...);
```

But it occurred to me that I could use `external: [ 'jquery' ]` and `globals: { jquery: '$' }` option to let me write `import $ from 'jquery';` instead.

This would have the advantage of consistency within my project, I suppose, at the cost of a more complicated Rollup configuration and obscuring that the global is a global. What other advantages are there? Footnote [1] of https://github.com/rollup/rollup/issues/556 seems to add

> * Since [using the `globals` option causes the global to be] just a name inside the IIFE, uglifiers can minify it.
> * Shorter scope depth is slightly faster.

are those indeed advantages of using the `globals` option? Any others?

**Comment by Rich-Harris** [comment]
Both are valid. It depends on your preference. The main difference is that if you have multiple modules that use `$`, it needs to be redeclared within each module, and Rollup will create a new variable each time ([demo](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGZm9vLmpzJyUzQiU1Q25pbXBvcnQlMjAnLiUyRmJhci5qcyclM0IlNUNuJTVDbnZhciUyMCUyNCUyMCUzRCUyMHdpbmRvdy4lMjQlM0IlNUNudmFyJTIweCUyMCUzRCUyMCUyNCgneCcpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJ2YXIlMjAlMjQlMjAlM0QlMjB3aW5kb3cuJTI0JTNCJTVDbnZhciUyMHklMjAlM0QlMjAlMjQoJ3knKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwJTI0JTIwJTNEJTIwd2luZG93LiUyNCUzQiU1Q252YXIlMjB6JTIwJTNEJTIwJTI0KCd6JyklM0IlMjIlN0QlNUQlN0Q=)). On the other hand, if you use `import` statements, then you pay the interop cost ([demo](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTIyanF1ZXJ5JTIyJTNBJTIyalF1ZXJ5JTIyJTdEJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCUyNCUyMGZyb20lMjAnanF1ZXJ5JyUzQiU1Q25pbXBvcnQlMjAnLiUyRmZvby5qcyclM0IlNUNuaW1wb3J0JTIwJy4lMkZiYXIuanMnJTNCJTVDbiU1Q252YXIlMjB4JTIwJTNEJTIwJTI0KCd4JyklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCUyNCUyMGZyb20lMjAnanF1ZXJ5JyUzQiU1Q24lNUNudmFyJTIweSUyMCUzRCUyMCUyNCgneScpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhci5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlMjQlMjBmcm9tJTIwJ2pxdWVyeSclM0IlNUNuJTVDbnZhciUyMHolMjAlM0QlMjAlMjQoJ3onKSUzQiUyMiU3RCU1RCU3RA==)).

**Comment by wearhere** [comment]
Cool thanks!
