### ISSUE TITLE
Buble 0.15.2?

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#1242]
Rich, apologies for the off-topic use of the [Bat Signal](https://en.wikipedia.org/wiki/Bat-Signal), but would you mind publishing buble@0.15.2 to fix a regression affecting a few projects?

buble master already has the [fix](https://gitlab.com/Rich-Harris/buble/issues/166#note_20228354), just need to publish.

**Comment by Rich-Harris** [comment]
Done, sorry — am bad at handling multiple backlogs at once, been trying to get Rollup under control before immersing myself in anything else, which I realise is a nuisance.

**Comment by kzc** [comment]
Thanks!

Your work is appreciated.

**Comment by Rich-Harris** [comment]
As is yours! Rollup and Bublé users, including me, owe you a huge amount
