### ISSUE TITLE
[question] Recommended way to dedupe dependencies yet make modules self-sufficient

### ISSUE THREAD

**Issue by wearhere** [rollup/rollup#1243]
I'm developing a module A to be consumed by modules B and C. I'm outputting module A in CJS format (fwiw) because C's build process can't handle ES6 modules.

A depends on jQuery and Backbone. So does B. I wish to dedupe these imports. I know that I can do this by marking them as [`external`](https://github.com/rollup/rollup/wiki/JavaScript-API#external) to A and thus excluding them from A's bundle. B can then supply them when B is bundled, as globals, or from npm, or what-not.

However, now A is not self-sufficient—its bundle cannot be used standalone. And when it is installed into another project, it requires that project's developer to install its dependencies on its behalf.

An alternative, to illustrate what I'm looking for, is the npm ecosystem. If both A and B were npm modules being run by Node, npm would dedupe A and B's dependencies on install, and properly locate the deduped dependency at runtime—but if A were installed standalone, it would fulfill its own dependency.

Is there a way to dedupe dependencies, yet make modules self-sufficient, with Rollup?

**Comment by Rich-Harris** [comment]
A module can either have external dependencies or be standalone, it can't be both. But a package can contain both kinds of module. See [magic-string](https://github.com/rich-harris/magic-string) for an example — it exposes a [CommonJS version](https://unpkg.com/magic-string@0.19.0/dist/magic-string.cjs.js) and an [ES module version](https://unpkg.com/magic-string@0.19.0/dist/magic-string.es.js) with external dependencies (which a consumer can bundle, if it wants to), but also ships a [UMD build](https://unpkg.com/magic-string@0.19.0/dist/magic-string.umd.js) with its only external dependency included.

**Comment by wearhere** [comment]
Thanks @Rich-Harris! Seeing that configuration also clarifies for me that a CommonJS module is effectively standalone so long as the external dependencies can be fulfilled from npm.

Btw I found that magic-string's README was out of date with respect to the UMD build, fixed here: https://github.com/Rich-Harris/magic-string/pull/117 Cheers!
