### ISSUE TITLE
Rollup and Sinon not playing nice together. Referencing the incorrect function.

### ISSUE THREAD

**Issue by scripter-co** [rollup/rollup#1247]
I'm trying to use Sinon and Rollup to test some function calls. The problem is that the sinon spy that i'm creating:

    const spy = sinon.spy(method, 'function');

that I'm using, when generated by rollup, doesn't reference the correct thing. I have listed both my code and the rolled up code:

Mine:

    import assert from 'assert';
    import sinon from 'sinon';
    import * as playbackModule from '../components/playback';
    
    describe('App', () => {
      it('initialises the app', () => {
        const spy = sinon.spy(playbackModule, 'playback');
        playbackModule.playback();
        assert.equal(spy.called,  true);
      });
    });

Generated:

    function playback() {
      console.log('called');
    }
    
    var playbackModule = {
      playback: playback
    };
    
    describe('App', function () {
      it('initialises the app', function () {
        var spy = sinon_1.spy(playbackModule, 'playback');
        playback();
        assert_1.equal(spy.called,  true);
      });
    });

As you can see, the reference for `playback()` is not the one in the object, therefore the spy will never say that it was called.

Is there any way, using this setup (sinon and rollup) that I can get the spy's correctly referencing the right thing? Interestingly, in my code, if I replace `playbackModule.playback();` with `playbackModule['playback']();` it correctly gives me `called = true`;

**Comment by Rich-Harris** [comment]
Am curious about what version you're using and your configuration? I'd expect it to look like this instead...

```js
var playbackModule = Object.freeze({
  playback: playback
});
```

...in which case attempting to spy on the method would fail. (This is correct before AFAICT, because `playbackModule` is a namespace and not an object, in the traditional sense.)

I think you have two options — spy on the function itself...

```js
var playbackSpy = sinon.spy(playbackModule.playback);
playbackSpy();
assert.equal(playbackSpy.called, true);
```

...or create a new object:

```js
var functions = {
  playback: playbackModule.playback
};

// later
var spy = sinon.spy( functions, 'playback' );
functions.playback();
assert.equal( spy.called, true );
```

**Comment by scripter-co** [comment]
@Rich-Harris Apologies, we're using a plugin that strips out `Object.freeze`. You are right, by default it does look like you expected.

The first option doesn't work as the `sinon.spy(playbackModule.playback)` will return the spy that then you pass in to be called. What we actually want to do is check down the line that when calling `app()` it then calls `playback()`. Essentially, we want to know that calling X, calls Y.

The second suggestion still doesn't reference the correct thing in the following example which is closer to our usecase: [rollup example](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYXBwJTIwZnJvbSUyMCcuLiUyRmFwcCclM0IlNUNuaW1wb3J0JTIwKiUyMGFzJTIwcGxheWJhY2tNb2QlMjBmcm9tJTIwJy4uJTJGY29tcG9uZW50cyUyRnBsYXliYWNrJyUzQiU1Q24lNUNuZGVzY3JpYmUoJ0FwcCclMkMlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBpdCgnaW5pdGlhbGlzZXMlMjB0aGUlMjBhcHAnJTJDJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBmdW5jdGlvbnMlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcGxheWJhY2slM0ElMjBwbGF5YmFja01vZC5wbGF5YmFjayU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBzcHklMjAlM0QlMjBzaW5vbi5zcHkoZnVuY3Rpb25zJTJDJTIwJ3BsYXliYWNrJyklM0IlNUNuJTIwJTIwJTIwJTIwYXBwKCklM0IlMjAlMkYlMkYlMjBpbnNpZGUlMjBhcHAoKSUyMHdlJTIwY2FsbCUyMHBsYXliYWNrTW9kLnBsYXliYWNrJTVDbiUyMCUyMCUyMCUyMGFzc2VydC5lcXVhbChzcHkuY2FsbENvdW50JTJDJTIwMSklM0IlMjAlMkYlMkYlMjBhY3R1YWwlM0ElMjBjYWxsQ291bnQlMjAlM0QlMjAwJTVDbiUyMCUyMCU3RCklM0IlNUNuJTdEKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb21wb25lbnRzJTJGcGxheWJhY2suanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBwbGF5YmFjaygpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdjYWxsZWQnKSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYXBwLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25pbXBvcnQlMjAlN0IlMjBwbGF5YmFjayUyMCU3RCUyMGZyb20lMjAnLiUyRmNvbXBvbmVudHMlMkZwbGF5YmFjayclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGluaXQoKSUyMCU3QiU1Q24lMjAlMjBwbGF5YmFjaygpJTNCJTVDbiU3RCUyMiU3RCU1RCU3RA==)

**Comment by Rich-Harris** [comment]
app.js is just referencing the function, so it doesn't really matter what you do to the namespace object. The only way you could spy on the `playback` function is if components/playback.js [exported a writable object](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYXBwJTIwZnJvbSUyMCcuLiUyRmFwcCclM0IlNUNuaW1wb3J0JTIwcGxheWJhY2tNb2QlMjBmcm9tJTIwJy4uJTJGY29tcG9uZW50cyUyRnBsYXliYWNrJyUzQiU1Q24lNUNuZGVzY3JpYmUoJ0FwcCclMkMlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBpdCgnaW5pdGlhbGlzZXMlMjB0aGUlMjBhcHAnJTJDJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBzcHklMjAlM0QlMjBzaW5vbi5zcHkocGxheWJhY2tNb2QlMkMlMjAncGxheWJhY2snKSUzQiU1Q24lMjAlMjAlMjAlMjBhcHAoKSUzQiUyMCUyRiUyRiUyMGluc2lkZSUyMGFwcCgpJTIwd2UlMjBjYWxsJTIwcGxheWJhY2tNb2QucGxheWJhY2slNUNuJTIwJTIwJTIwJTIwYXNzZXJ0LmVxdWFsKHNweS5jYWxsQ291bnQlMkMlMjAxKSUzQiUyMCUyRiUyRiUyMGFjdHVhbCUzQSUyMGNhbGxDb3VudCUyMCUzRCUyMDAlNUNuJTIwJTIwJTdEKSUzQiU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmNvbXBvbmVudHMlMkZwbGF5YmFjay5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwJTdCJTVDbiUyMCUyMHBsYXliYWNrJTIwKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ2NhbGxlZCcpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYXBwLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25pbXBvcnQlMjBwbGF5YmFja01vZCUyMGZyb20lMjAnLiUyRmNvbXBvbmVudHMlMkZwbGF5YmFjayclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGluaXQoKSUyMCU3QiU1Q24lMjAlMjBwbGF5YmFja01vZC5wbGF5YmFjaygpJTNCJTVDbiU3RCUyMiU3RCU1RCU3RA==). But then the tail is wagging the dog.

**Comment by scripter-co** [comment]
That's exactly why this issue was raised, and I was hoping there was another way other than exporting an object on the default, as you obviously lose the benefits of tree shaking.

The only other solution I have thought about is using DI, which wont work in all scenarios; especially if you have a `util` that's imported in multiple places (and therefore cannot possibly stub/spy at all) - so is not a viable options.

I'm assuming there are no other ways around this. I'm also surprised at the lack of information around this (not here, just in general) - I'd of assumed this was a common use case - but perhaps not?

**Comment by Rich-Harris** [comment]
It does seem a bit unsolvable. I think this is one of those cases where CommonJS tricked us into thinking (and building software) a certain way, because the limitations of the language pre-modules meant things had to be done in a more hackable way (dynamic requires, `module.exports` is an object, etc) which created opportunities for things like `sinon.spy`.

Personally I haven't found this to be a limitation because I only really test the public API — I don't care about the implementation details as long as the observed outputs and effects are correct for a given set of inputs. So I'm not practiced at thinking about these problems. Would be interested to hear from anyone else who has dealt with these issues though!

**Comment by alexchao** [comment]
FWIW, I ran into the scenario that @Rich-Harris alluded to with the object being frozen preventing me from performing `sinon` mocking, stubbing, etc. on its methods. I generally agree with the idea of only testing the public API, or using DI to inject test objects in testing scenarios, but it's not always feasible or reasonable to expect an entire codebase to be structured this way.

In my case, I'm working on small enough of a project that I should be able to restructure with DI in mind. I'm curious to know how this pans out though. Interesting point you make about CommonJS et al. trickery leading us to this point.

**Comment by guybedford** [comment]
I think it's safe to mark this as a wontfix as this isn't supported for ES modules in Node or browsers.

**Comment by scripter-co** [comment]
I agree.

**Comment by Izhaki** [comment]
It seems that rollup exports with `configurable: true` in the descriptor (@guybedford ?). 

If so, you can stub like so:
```javascript
    Object.defineProperty(logger, 'createLogger', {
      writable: true,
      value: sinon.stub().returns(loggerStub)
    });
```
See [this](https://github.com/webpack/webpack/issues/6979#issuecomment-389220417) for more.

I also think Sinon could [support this in the future](https://github.com/sinonjs/sinon/issues/1762#issuecomment-389332862) without any extra workarounds.
