### ISSUE TITLE
How can a plugin use external files to invalidate the cache

### ISSUE THREAD

**Issue by robianmcd** [rollup/rollup#1248]
I opened this issue on the `rollup-plugin-angular` https://github.com/cebor/rollup-plugin-angular/issues/34 because it is not working with the rollup cache. The plugin takes html and css files and inlines them in an angular component however changes to the html and css files will not invalidate the rollup cache. 

I took a look at the rollup source code:

https://github.com/rollup/rollup/blob/master/src/Bundle.js#L292-L296
**Bundle.js**
```javascript
...
if ( this.cachedModules.has( id ) && this.cachedModules.get( id ).originalCode === source.code ) {
    return this.cachedModules.get( id );
}

return transform( this, source, id, this.plugins );
...
```

And it looks like the cache is checked before the plugins get a chance to do anything. So do you have any ideas on the best way to go about solving this?

**Comment by Rich-Harris** [comment]
See https://github.com/rollup/rollup/issues/1203. Basically we need a way for plugins to declare dependencies other than with an `import` declaration. (The stopgap would be for the plugin to generate empty imports...

```js
import './app.component.html'
```

...then generate an empty module for that ID.)

**Comment by robianmcd** [comment]
Thanks. That looks like it would solve the issue. I'll keep an eye on that ticket. 

Would there still be an issue with checking the cache before `transform()` is called though?

**Comment by Rich-Harris** [comment]
I see your point. The cache would have to be invalidated for the modules in question. That could be handled inside rollup-watch, I think

**Comment by robianmcd** [comment]
I'm using gulp and rollup's JS API for my build. So would I need to manually remove modules from the rollup cache when the watcher triggers for an external file?

**Comment by Rich-Harris** [comment]
Hmm, would have to have a think about that. I generally recommend that people use the CLI, or a dedicated plugin that takes care of these sorts of issues rather than using the JS API directly.

**Comment by robianmcd** [comment]
Not sure if they CLI is flexible enough for my needs. e.g. I want to be able to cache bust the bundle that rollup outputs which I do with:

```javascript
...
return bundle.write({
    format: 'iife',
    dest: `dist/app-${Date.now().toString(36)}.js`,
    sourceMap: !prodMode
});
...
```

This means that rollup generates a file with a new name each time it runs so I need to clean the old one which I do with

```javascript
let rollupApp = gulp.series(
    function cleanRollupJs() {return del('dist/app*.js')},
    function buildRollupApp() {
        //...
    }
);
```

It also means that I need to dynamically inject the bundle into index.html and regenerate it any time the bundle changes. And I want to live reload the browser when the bundle changes so I do

```javascript
//...
gulp.watch(['src/**/*.ts', ...componentStylePaths, ...componentTemplatePaths], gulp.series(appJs, index, browserSync.reload));
//...

function index() {
    let srcStream = gulp.src(['dist/global*.js', 'dist/app*.js', 'dist/global*.css'], {read: false});

    return gulp.src('src/index.html')
        .pipe(inject(srcStream, {addRootSlash: false, ignorePath: 'dist'}))
        .pipe(gulp.dest('dist'));
}
```

I'm trying to build a simple build for an Angular 2 app but it's still requires a lot of things that are fairly easy to do with gulp but would be hard to do with rollup plugins.

Anyway if there was a way for a rollup plugin to declare dependencies before the cache is checked instead of in the `transform` hook I think that could solve this issue without requiring rollup-watch. But I'm new to rollup so not sure if that's the best approach

**Comment by guybedford** [comment]
I'm currently working on the approach outlined in #1203, with that invalidating the transform cache. Tracking in that issue.
