### ISSUE TITLE
replace absolute URL's in the sourcemap with relative ones

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#125]
Any sourcemaps produced have absolute URL's, which for instance if you were bundling a library, you would not want.

It would be better if they were relative and always used the `/` path seperator.

**Comment by Rich-Harris** [comment]
If you specify `sourceMapFile` (or `dest` if using `bundle.write`, in which case `sourceMapFile` defaults to the same thing), and it's an absolute filepath, then the sources will be relative to that filepath:

```js
let { code, map } = bundle.generate({
  format: 'cjs',
  sourceMap: true,
  sourceMapFile: path.resolve( 'dist/bundle.js' )
});

map.sources; // [ '../src/main.js', '../src/foo.js', ... ]
map.file; // bundle.js
```

If you don't specify `sourceMapFile`, the sources will be absolute. I don't remember explicitly choosing this behaviour but I think it's what makes most sense!

**Comment by lukeapage** [comment]
Looks good, thanks. I've added a sentence to SourceMapFile in https://github.com/rollup/rollup/wiki/JavaScript-API
