### ISSUE TITLE
get dependency tree [question]

### ISSUE THREAD

**Issue by chpio** [rollup/rollup#1250]
Hi,

is there a way to get the dependency tree inside of rollup? Im forking rollup (because there is no [plugin-api for output formats](https://github.com/rollup/rollup/issues/269)) to add support for the emscripten js format (https://github.com/evanw/emscripten-library-generator/issues/1#issuecomment-56837241 ; [example](https://github.com/kripken/emscripten/blob/master/src/library_async.js))?

Im referring to the local dependencies:

```js

const myVar = 42;

function asdf() {
  return myVar;
}

export function foo() {
  return asdf();
}
```

would result in:

```js
LibraryManager.library.myVar = 42;

LibraryManager.library.asdf = function() {
  return myVar;
};
LibraryManager.library.asdf__deps = ['myVar'];

LibraryManager.library.foo = function() {
  return asdf();
};
LibraryManager.library.foo__deps = ['asdf'];
```

Nice-to-have: prefix all local symbols:
 
```js
LibraryManager.library._my_module_myVar = 42;

LibraryManager.library._my_module_asdf = function() {
  return _my_module_myVar;
};
LibraryManager.library._my_module_asdf__deps = ['_my_module_myVar'];

LibraryManager.library.foo = function() {
  return _my_module_asdf();
};
LibraryManager.library.foo__deps = ['_my_module_asdf'];
```

If there is no way to get it, i would try to plug the code from [emscripten-library-generator](https://github.com/evanw/emscripten-library-generator) (discovered that while writing this issue) into the finalizer by maybe `bundle.ast`...

Thank you

**Comment by Rich-Harris** [comment]
Yes — if you're using the JavaScript API, you can get a list of modules contained in the bundle, with a list of their dependencies, like so:

```js
rollup.rollup( options ).then( bundle => {
  bundle.modules.forEach( module => {
    console.log( module.id, module.dependencies ); // dependencies is a list of IDs
  });

  return bundle.write( options );
});
```
