### ISSUE TITLE
Version 0.41: Error in created imports in mjs file

### ISSUE THREAD

**Issue by ArthurClemens** [rollup/rollup#1252]
I have this index file to import all sub packages in a lerna project: https://github.com/ArthurClemens/polythene/blob/rewrite/packages/polythene/index.js

In rollup v. 0.41 this creates an entry:
```
import { * as polytheneFastclick, * as polytheneFastclick, * as polytheneFastclick } from 'polythene-fastclick';
```
instead of v.0.39 that creates:
```
import 'polythene-fastclick';
```

It seems to happen with all the imports with pattern
```
export * from "some-module";
```
either at the start of the file or when directly following an import with pattern 
```
export { some } from "some-module";
```
(the other imports are handled fine)

**Comment by Rich-Harris** [comment]
Thanks — fixed in 0.41.4
