### ISSUE TITLE
Subfolders in external modules

### ISSUE THREAD

**Issue by trbrc** [rollup/rollup#126]
*(I suppose this is more of a question about `jsnext:main` rather than Rollup)*

Is there a recommended way to deal with subfolders/namespaces when writing reusable modules? I noticed that in [d3-jsnext](https://github.com/rollup/d3-jsnext), the module structure has been flattened out to a single level to work with ES6/Rollup, causing very surprising module names such as `geo_transform` among otherwise camel-cased names.

Is there no better way to deal with nested or namespaced modules? Would it be possible to author a module that uses subfolders, and is used something like this instead?

```
import {transform} from 'd3-jsnext/geo';
```

Or would the only option be to include the namespace in the export name, something like this?

```
import {geoTransform as transform} from 'd3-jsnext';
```

The solution used by [d3-bundler](https://github.com/d3/d3-bundler) seems to be to have a separate npm module for each submodule.

```
import {transform} from 'd3-geo';
```

But this seems to betray the philosophy outlined by [Rich on Medium](https://medium.com/@Rich_Harris/small-modules-it-s-not-quite-that-simple-3ca532d65de4).

**Comment by Rich-Harris** [comment]
I think the decision to split d3 into multiple separate packages is mostly about ease of authoring (though it does mean that non-ES6 users can still get leaner D3 apps) – there could still be a 'master' D3 package that re-exported from individual packages like `d3-geo`, though I don't know what the ultimate plan is for the next version.

In the general case, I *don't* think relying on folder structure is a good idea:

1. It means you're treating the folder structure as an undocumented, untested API which is likely to change
2. It couples your code to the filesystem – you would have to change everything if (say) you decided to unbundle third party libraries and use a CDN for them (unless they replicated the folder structure, which would be unusual)

So for that reason I would generally suggest that it's okay to put everything in a single namespace and just give everything different names – I think it's good to clearly disambiguate between different functions (e.g. `d3.geo.transform` and `d3.transform` do very different things, so in a situation where you don't have the `d3.geo.` bit, it's much better for code readability if it's obvious which of those two things you're using. Though I do take the point that the snake_case is a bit weird).

That aside, clearly there are situations where it's helpful to do...

```js
import mod from 'foo/sub/mod';
```

...where only `foo` goes through the external module resolver as opposed to the whole thing. In fact there's a PR, #95, which implements that – I forgot it wasn't merged, I'll tidy it up and include it in the next release.

**Comment by Rich-Harris** [comment]
Just released 0.16.2 – by default, the resolution algorithm now works as follows:

* `import foo from 'foo'` – as before, `foo` is sought in parent `node_modules` folders, and the `jsnext:main` property in that package's `package.json` is used to find the entry module
* `import mod from 'foo/sub/mod'` – once `foo` is found, `sub/mod` is appended to the resolved path (e.g. `/path/to/project/node_modules/foo/sub/mod.js'`)

**Comment by trbrc** [comment]
:+1: Fantastic!
> 1. It means you're treating the folder structure as an undocumented, untested API which is likely to change

I don't see why it couldn't be documented and tested? It could be like any other part of the API. If d3 explicitly said that you should import all geo stuff with `import {x} from 'd3/geo'`, I don't see why that would be a problem. I guess it wouldn't be possible to restrict access from non-api folders, but you're never really restricted from doing undocumented things, so it's really just a question of documentation I think.

> import mod from 'foo/sub/mod' – once foo is found, sub/mod is appended to the resolved path (e.g. /path/to/project/node_modules/foo/sub/mod.js')

Just so I understand correctly - this means folder paths do not depend on `jsnext:main`?

**Comment by Rich-Harris** [comment]
> I don't see why it couldn't be documented and tested?

Oh, it definitely *could* be, I just think it's a bad convention because in many cases it *won't* be, so it sets a bad precedent that importing individual files from external modules is a totally cool thing to do when in most cases it isn't – the interface between packages (or apps and packages) should be defined via the API. 

Another concern is that this is a Node.js thing – I'm not quite sure what the conventions will be (or should be) with native ES6 module loaders, when they eventually arrive.

> Just so I understand correctly - this means folder paths do not depend on `jsnext:main`?

Yep, exactly :+1:

**Comment by FunkMonkey** [comment]
> > Just so I understand correctly - this means folder paths do not depend on jsnext:main?

> Yep, exactly :+1: 

And just so that I understand correctly - this means we cannot create es5-compatible and esnext modules in subfolders like `foo/sub/mod` at the same time? After all there can only be one `foo/sub/mod.js` - either with es5  compatible module syntax (`require`) or es6 syntax (`import`, `export`)... Am I correct?

Thanks! :)

**Comment by Rich-Harris** [comment]
@FunkMonkey I'm afraid so – there was a proposal a while back to have sibling `.js` (legacy) and `.jsm` (module) files, where the legacy files would typically be generated at publish time from the modules, but it got kiboshed.

Only real solution if you need to put modules in subfolders and have them work everywhere is probably to publish two separate packages from the same repo (which isn't as bad as it sounds, it's what Lodash does for example).
