### ISSUE TITLE
Remove unused pure curried functions where possible

### ISSUE THREAD

**Issue by hdgarrood** [rollup/rollup#1263]
With Rollup v0.41.4, using the following input:

```javascript
function foo(a) {
  return function(b) {
    return a+b;
  }
}

function bar(a, b) {
  return a+b;
}

foo(1)(2);
bar(1,2);
```

Note that `foo` and `bar` are the same function except that `foo` is curried.

When bundling this as ES2015, I hoped to see an empty module, but got this:

```javascript
function foo(a) {
  return function(b) {
    return a+b;
  }
}

foo(1)(2);
```

[Here's a repro on rollupjs.org](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJmdW5jdGlvbiUyMGZvbyhhKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBmdW5jdGlvbihiKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBhJTJCYiUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGJhcihhJTJDJTIwYiklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwYSUyQmIlM0IlNUNuJTdEJTVDbiU1Q25mb28oMSkoMiklM0IlNUNuYmFyKDElMkMyKSUzQiUyMiU3RCU1RCU3RA==).

If this is something you'd like Rollup to be able to do, I'd be interested in working on this.

**Comment by Rich-Harris** [comment]
Coincidentally, I've spent much of the last week working on a new approach to tree-shaking that will hopefully enable Rollup to be smarter about cases like these (and many others — unused methods of objects and classes, etc). But it's *hard*, and there are no guarantees that it's possible. Even [Closure Compiler in advanced mode](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A(function%2520()%2520%257B%250Afunction%2520foo(a)%2520%257B%250A%2520%2520return%2520function(b)%2520%257B%250A%2520%2520%2520%2520return%2520a%252Bb%253B%250A%2520%2520%257D%250A%257D%250A%250Afunction%2520bar(a%252C%2520b)%2520%257B%250A%2520%2520return%2520a%252Bb%253B%250A%257D%250A%250Afoo(1)(2)%253B%250Abar(1%252C2)%253B%250A%257D())%253B%250A%250A) can't remove that code.

Essentially, you have to simulate running the entire bundle, tracking the value of every expression (which quickly gets hairy, especially when closures are involved) as you do so, then determine which statements are guaranteed not to have side-effects. Without implementing an entire JavaScript interpreter, you can only get to an approximate result — one that is hopefully good enough to handle a lot of common patterns, but that will never be 100% accurate. 

Hopefully I'll be in a position to share some results soon. If you have ideas about how you'd go about handling cases like these, I'm definitely interested to hear them.

**Comment by hdgarrood** [comment]
Ha, I may have underestimated the difficulty of this then, I didn't realise that Closure Compiler doesn't handle it :)

I haven't thought a huge amount about what the implementation might look like so I don't know how workable this is, but I was imagining a special case for curried functions like this, so that e.g on encountering a function declaration whose body is just `return <function expression>` where the function in the function expression has exactly 1 parameter, we temporarily transform the function declaration to an uncurried form by adding the parameter of the inner function expression to the end of the outer function's parameter list, and then checking whether the resulting uncurried function is pure; if so, the curried function we started with can also be assumed to be pure. This procedure could then be extended to curried functions of 3 or more arguments by 'uncurrying' one argument at a time and checking whether we still have a pure function, I think.

I suppose you'd have to disallow any reassignment to function parameters and any use of `arguments` and maybe a couple other things for this to be safe, though?

**Comment by Pauan** [comment]
@Rich-Harris Indeed, dead code elimination is incredibly hard in an impure language like JavaScript.

But the reason @hdgarrood created this issue is because PureScript currently uses its own custom program for bundling, and [we want to switch to Rollup instead](https://github.com/purescript/purescript/issues/2545).

That's why I created [this pull request](https://github.com/rollup/rollup/pull/1017), because it has a huge impact when bundling PureScript code.

So although dead code elimination is hard in general, it shouldn't be that hard to add in some code which specifically handles curried functions. It won't help much with regular JavaScript code, but it will have a huge impact on PureScript code, because all functions in PureScript are curried.

If I have some time, I plan to create a pull request which specifically handles curried functions. Is there anything I should be aware of? For example, a new branch where you are working on the new algorithm?

**Comment by hdgarrood** [comment]
Ok @Pauan if you're interested in working on this too, I'll leave it to you :)

**Comment by Rich-Harris** [comment]
The work is happening in a branch called [value-tracking](https://github.com/rollup/rollup/tree/value-tracking). I won't lie — it's currently a complete mess, I'm groping blindly through the problem space.

I'm always wary of adding code that covers special cases. They can be useful stopgap measures until a more comprehensive solution comes along, but they have a habit of multiplying, and it can severely hamper your ability to refactor and maintain the codebase in my experience. So for now I'd prefer to see if the work in value-tracking pans out. I'm cautiously optimistic that we'll be able to determine that the return value of `foo` is pure and mark it as removable.

I definitely appreciate the offer of help though! Once the branch is in a less chaotic state, some extra pairs of eyes would certainly be valuable.

**Comment by Pauan** [comment]
@Rich-Harris I absolutely agree, a more general solution would be preferable.

I also don't mind special-casing curried functions in [my PureScript plugin](https://github.com/Pauan/rollup-plugin-purs), but currently it seems that plugins don't have much control over the tree-shaking process.

Actually, I've run into a lot of various issues with the plugin system when writing `rollup-plugin-purs`, but fixing those issues is probably a backwards-incompatible change in Rollup.

**Comment by Rich-Harris** [comment]
> but fixing those issues is probably a backwards-incompatible change in Rollup

Backwards-incompatibility isn't necessarily a reason not to do them — it might be stuff that other plugins could benefit from too

**Comment by Pauan** [comment]
@Rich-Harris Okay then, I'll create some issues about the various problems I've had when developing `rollup-plugin-purs`, and you can decide on a case-by-case basis whether to fix them or not.

**Comment by olsonpm** [comment]
I'm trying to learn more about the rollup process in general.  That said, what's preventing your tree-shaking to be implemented in transformBundle?

**Comment by Pauan** [comment]
@olsonpm It can be done in `transformBundle`, but it's more work (for me) compared to a nice general solution in Rollup (which benefits all code, rather than just my plugin).

The reason it's more work is because Rollup plugins have no way of controlling/changing/triggering Rollup's tree shaking process, so I essentially would need to implement my own custom tree shaking from scratch.
