### ISSUE TITLE
external doesn't allow function returning true

### ISSUE THREAD

**Issue by StreetStrider** [rollup/rollup#1264]
It seemes that I can't use function for `external` option if that function just returns `true`. My intent is to mark everything (even local imports) as external. So, I use `external: () => true`. I got `[Error: Could not load false: path must be a string]`. The documentations still clear says it is possible to use a boolean returning function here.

The repro is to only use function returning `true` for `external` with no plugins.

Looks like that issue has something with entry file. I can workaround it by passing
`external: (id) => id !== entry`.

**Comment by yaycmyk** [comment]
The error coming back is `Could not load false: str.slice is not a function` @Rich-Harris

**Comment by Rich-Harris** [comment]
Rollup now prints a more useful error, saying that the entry module can't be external

**Comment by StreetStrider** [comment]
@Rich-Harris are you against `() => false` or are there any drawbacks for such form?

**Comment by Rich-Harris** [comment]
Do you mean `() => true`? Just that it doesn't work with the entry module. I guess we could change the behaviour so that `isExternal` is never called for the entry module in the first place — that might be more logical.

**Comment by StreetStrider** [comment]
Yes. I would like it to treat `() => true` as «everything is external». Since entry cannot be external it can be ignored in check. The issue with my workaround above `(id) => id !== entry` is that I need to store `entry` in local variable (to prevent duplicating in config) when in usual case I could just pass literal in config in the single place.

**Comment by StreetStrider** [comment]
Seemes this working already as I expect it. Awesome :+1: 
If someone can confirm that is expected and not an unintended effect, I will close the issue.

**Comment by lukastaegert** [comment]
Yes, this case is expected and tested. Returning true will just leave you with the entry modules and every import is external.

**Comment by StreetStrider** [comment]
Thank you.
