### ISSUE TITLE
this.warn and this.error should accept a loc rather than a pos

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup#1265]
Plugins can use `this.warn` and `this.error` to emit warnings/errors. These functions accept a second `pos` argument, which must be an integer. This integer is the *character index* within the code.

My plugin uses [`recast`](https://github.com/benjamn/recast) to parse the source code, which gives me back an AST. This AST contains `loc` objects, like `{ line: 0, column: 10 }`, but it does **not** contain the *character index*.

Therefore, I cannot use the second argument to `this.warn` or `this.error`, but I would like to. So I would prefer if I could pass in a `{ line, column }` object instead of a character index.

**Comment by bfred-it** [comment]
This was fixed by #1446, correct?

**Comment by Pauan** [comment]
@bfred-it Yes, it seems that way, thanks!
