### ISSUE TITLE
IE8 instanceof is failed

### ISSUE THREAD

**Issue by musicode** [rollup/rollup#1266]
```js
class ClassName() {

}
```

source version

```js
var ClassName = function ClassName() {

}
```

compressd version

```js
var a = function b() {
    // this instanceof a is true
   //  this instanceof b is false
}
```

**Comment by bfred-it** [comment]
I don't think is is due to rollup because rollup won't change `class` to `function`.

Perhaps it's babel or buble.

**Comment by elasim** [comment]
@musicode 
Use this, https://babeljs.io/docs/plugins/transform-jscript/
this plugin will prevent some jscript issues.

**Comment by VIGDXX** [comment]
@musicode  thanks
