### ISSUE TITLE
rollup-plugin-rev

### ISSUE THREAD

**Issue by ezekielchentnik** [rollup/rollup#1269]
I'm contemplating writing a rollup plugin that will magically generate a hash for the contents of a bundle, but looking for feedback before i do.

- is this of interest?
- if so, what is the API you'd prefer?

**Comment by thisconnect** [comment]
> is this of interest?

yes for me

How would I know what the filename is?

Could the user have control over the format?
i.e. `[filename].[hash].[ext]`

I personally use rollup js api most of the times. That is `rollup.rollup.then(bundle => bundle.write())`. Is it possible to expose the checksum or filename in the bundle?

**Comment by Rich-Harris** [comment]
There's a plugin that's just been released call [rollup-plugin-hash](https://github.com/phamann/rollup-plugin-hash) — does that meet your needs?
