### ISSUE TITLE
transformBundle should receive the pre-formatted source code

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup#1271]
Here is an example Rollup configuration:

```js
export default {
  entry: "foo.js",
  format: "es",
  plugins: [
    {
      transformBundle: function (source) {
        console.log(source);
      }
    }
  ]
};
```

And here is `foo.js`:

```js
console.log(1);
```

If you run `rollup --config` it correctly prints `console.log(1);`

But if you change the `format` to `"iife"` it prints this instead:

```js
(function () {
'use strict';

console.log(1);

}());
```

What's happening is that Rollup is first applying the `format` option and then passing the result to `transformBundle`, but I think it would be better if Rollup first passed the result to `transformBundle` and afterwards applied the `format` option.

**Comment by Pauan** [comment]
The reason I think it's bad for `format` to be applied before `transformBundle` is because it makes `transformBundle` a lot more complicated.

If you want to do some simple transformations (like adding functions) in the `transformBundle` stage, you have to take into account what the `format` is, which means things like this don't work:

```js
export default {
  entry: "foo.js",
  format: "iife",
  plugins: [
    {
      transformBundle: function (source) {
        return source + "; function foo() {}";
      }
    }
  ]
};
```

So perhaps `transformBundle` should receive the format function as an argument, which it can then apply whenever it wants:

```js
export default {
  entry: "foo.js",
  format: "iife",
  plugins: [
    {

      transformBundle: function (source, format) {
        return "// header\n" + format(source + "; function foo() {}") + "// footer";
      }
    }
  ]
};
```

The result of the above plugin would be this:

```js
// header
(function () {
'use strict';

console.log(1);

; function foo() {}

}());
// footer
```

This allows `transformBundle` to manipulate the code before or after formatting (or even both).

**Comment by Pauan** [comment]
Alternatively, rather than receiving `format` as a function argument, it can instead be a method `this.format`, similar to `this.warn` and `this.error`:

```js
export default {
  entry: "foo.js",
  format: "iife",
  plugins: [
    {

      transformBundle: function (source) {
        return "// header\n" + this.format(source + "; function foo() {}").code + "// footer";
      }
    }
  ]
};
```

**Comment by guybedford** [comment]
This kind of injection can be handled through the `intro` and `outro` options which allow customm source injection within the wrapper.
