### ISSUE TITLE
output with es6 syntax for default exports and format iife

### ISSUE THREAD

**Issue by hugomrdias** [rollup/rollup#1280]
this is especially problematic with lodash-es cause they do this kind of exports for categories (array, number, etc..) 

[link to reproduce](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYW5zd2VyJTIwZnJvbSUyMCcuJTJGYW5zd2VyLmpzJyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCUyMCd0aGUlMjBhbnN3ZXIlMjBpcyUyMCclMjAlMkIlMjBhbnN3ZXIudGV4dCgndGVzdCcpJTIwKSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYW5zd2VyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwdGV4dCh0KSU3QiU1Q24lMjAlMjByZXR1cm4lMjB0JTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMCU3QiU1Q24lMjAlMjB0ZXh0JTVDbiU3RCUyMiU3RCU1RCU3RA==)

**Comment by olsonpm** [comment]
What's the es6 syntax you're referring to?  Or am I blind?

I see the following:
```js
var myBundle = (function () {
'use strict';

function text(t){
  return t;
}

var answer = {
  text
};

var main = function () {
	console.log( 'the answer is ' + answer.text('test') );
};

return main;

}());
```

**Comment by hugomrdias** [comment]
```
var answer = {
  text
};
```

**Comment by olsonpm** [comment]
Ha - iife just doesn't output es5.  If you add an explicit line with es6 such as:

```js
// main.js
import answer from './answer.js';

const testing = () => 'just es6'; // <---- this line persists as-is
global.keepTestingAlive = testing;

export default function () {
	console.log( 'the answer is ' + answer.text('test') );
}
```

so the solution is to use rollup-plugin-buble

```js
import pBuble from 'rollup-plugin-buble';

export default {
  entry: 'index.es6.js'
  , moduleName: 'myBundle'
  , plugins: [pBuble()]
  , format: 'iife'
};
```

outputting your desired
```js
var myBundle = (function () {
'use strict';

function text(t){
  return t;
}

var answer = {
  text: text
};

var testing = function () { return 'just es6'; };
global.keepTestingAlive = testing;

var index_es6 = function () {
	console.log( 'the answer is ' + answer.text('test') );
};

return index_es6;

}());
```

**Comment by hugomrdias** [comment]
yes i know i can buble/babel this stuff but for my code
i can't transpile all my deps (Ex. lodash-es) to solve this.
and i'm not inputting anything but 

```
export default {
  text
}
``` 

rollup should handle imports and exports to es5, plus if i change format to commonjs all is good in the world.

**Comment by olsonpm** [comment]
that's the thing, rich decided iife shouldn't transpile but es6 should.  It's a conscious decision and I can't find any documentation saying iifes should transpile so there's no bug here.  Also, because iife's don't transpile, I don't think there should be any edge-case specifically for exports.

And why can't you transpile all your deps?

**Comment by hugomrdias** [comment]
sorry when you say iife doesnt transpile 

```js
export default {
  text
}

// to this isnt transpiling ?
var answer = {
  text
};
```

can you imagine the build times for that ? im talking about a big corporate web app. 
Besides everyone publishes transpiled versions ( and some even transpiled but with es6 modules all because rollup is awesome )

**Comment by olsonpm** [comment]
see #653

**Comment by olsonpm** [comment]
To address your build time concern, there are plenty of ways to mitigate the re-bundling speed - [caching](https://github.com/rollup/rollup/wiki/JavaScript-API) (see the 'cache' option) being the most important.

**Comment by olsonpm** [comment]
Wow - I no clue why I thought `--format cjs` was transpiling.  I swear I tested that behavior but can't figure out why I thought that.  Anyway, I was super wrong with that as any simple repro shows.
