### ISSUE TITLE
options.external is not working as expected and no good workaround?

### ISSUE THREAD

**Issue by cmawhorter** [rollup/rollup#1281]
Created [this repo](https://github.com/cmawhorter/rollup-external-weirdness)

I'm trying to `external: [ 'aws-sdk' ]` but it's not completely working.

Changing external to a function and it becomes obvious why.

The ID being passed to the function is inconsistent:

- `external? aws-sdk yes`
- absolute `external? /Users/...snip.../node_modules/aws-sdk/lib/aws.js no`
- plugin `external? commonjs-proxy:aws-sdk no`

It's possible to do `[ 'aws-sdk', module.resolve('aws-sdk') ]`, but that's a poor workaround that doesn't catch the plugin-prefixed variation.  _(Why is the plugin even getting that entry if I've marked it as external?)_

I also worry about deps of deps.  Depending on a variety of situations, sometimes there might be node_modules/some-dep/node_modules/aws-sdk.

**Comment by cmawhorter** [comment]
I'm still coming up empty on a workaround.  Here's some some attempts at getting aws-sdk external along with the result:

`var isExternal = [ 'aws-sdk' ].indexOf(id) > -1;`

```
external? /Users/.../node_modules/aws-sdk/lib/region_config.json false
{ Error: Unexpected token
code: 'PARSE_ERROR',
```

`var isExternal = [ 'aws-sdk', require.resolve('aws-sdk') ].indexOf(id) > -1;`

```js
var awsSdk = _interopDefault(require('aws-sdk'));
var aws = require('../node_modules/aws-sdk/lib/aws.js');
var aws__default = aws['default'];
```

`var isExternal = id.indexOf('aws-sdk') > -1;`

```js
var awsSdk = _interopDefault(require('aws-sdk'));
var require$$2$1 = _interopDefault(require('***NUL***commonjs-proxy:aws-sdk'));
```


`var isExternal = id.indexOf('aws-sdk') > -1 && id[0] !== String.fromCharCode(0);`

```js
var awsSdk = _interopDefault(require('aws-sdk'));
var aws = require('../node_modules/aws-sdk/lib/aws.js');
var aws__default = aws['default'];
```


`var isExternal = id.indexOf('aws-sdk') > -1 && (id[0] !== String.fromCharCode(0) || id.indexOf('node_modules') > -1); `

```js
var awsSdk = _interopDefault(require('aws-sdk'));
var require$$2$1 = _interopDefault(require('***NUL***commonjs-proxy:/Users/.../node_modules/aws-sdk/lib/aws.js'));
```

**Comment by olsonpm** [comment]
your example repo is confusing.  I get a ton of output as well as a parse error.

If you make it so the error is obvious when I run node build, I'll take a look.  I'm almost finished with my own rollup plugin so I feel confident in solving the issue.

**Comment by cmawhorter** [comment]
happy to clear it up.   tl;dr; I'm trying to use config.external as it's documented, but it's not behaving.

at this point, i'm fairly confident it's related to child dependencies of deps.  

## steps to repro

1. create a project that depends on aws-sdk and mark it external.  build works. no aws-sdk.

1. now, add dynogels (which depends on the same version of aws-sdk i.e. my project aws-sdk === dynogels aws-sdk).  build fails.

1. install json parser = build succeeds with aws-sdk included.  

alternatively, you can exclude `node_modules/aws-sdk/**` with all the plugins, but this still doesn't work.  you have to a) add that exclude option and b) add a second value to external: `require.resolve('aws-sdk')`, which returns the absolute path

## core problem

Deps of deps.  That example repo uses a function for external to show all the various IDs possible for any one module. (4-5 unique IDs for aws-sdk in this situation).  

My followup post documents my attempts at working around the issue.

## compounding scenario

In my repo, dynogels and my project share the same version of aws-sdk.  However, this becomes even more of a problem in npm3 if a dep requires a different version.  

Joi is particularly bad here.  I have a (small) project for aws lambda that has no less than 3 versions of Joi installed into node_modules:

- node_modules/joi
- node_modules/enjoi/node_modules/joi
- node_modules/dynogels/node_modules/joi

I was able to find a workaround to aws-sdk by hand-patching the bundle, but I dead-ended here with joi.  

No matter what I did Joi code ended up in the bundle.  I gave up.

**Comment by olsonpm** [comment]
Ha, thanks for the clarification.  I'll take a look

**Comment by olsonpm** [comment]
Your issue is actually very simple - took me a bit to find it

```js
plugins: [
  nodeResolve({     jsnext: true
    , main: true
    , skip: ['aws-sdk'] // <--- this right hurr
  })
  ...
```

**Comment by cmawhorter** [comment]
Niceee!  I misunderstood what the plugins were doing and mistakingly thought everything was happening in the commonjs plugin.  I went back and reread each readme and now what you say makes sense.

Though, I'm a little confused why external exists.  It looks like I need to add ['aws-sdk'] to both `nodeResolve.skip` and `options.external` to avoid warnings about missing dependencies that are being marked external.  Redundant, but livable.

**Comment by olsonpm** [comment]
Good point about the externals.  The only thing I can think of is that multiple imports are made, some using a commonjs scheme and others not.  I honestly just don't care enough to look into it further haha.

Glad it's working though!
