### ISSUE TITLE
Explain why `format` option is important

### ISSUE THREAD

**Issue by danieldiekmeier** [rollup/rollup#1283]
First of: Thank you for working on Rollup! :) it's really useful, and I appreciate it a lot.

Currently, the [Wiki](https://github.com/rollup/rollup/wiki/JavaScript-API#bundlegenerate-options-) states that "format is highly recommended", but it doesn't really explain why.

I recently followed some discussion about `format` on Twitter, and now tested what adding `format: 'iife` would do to my application bundle: It shrank from 180826 to 162605 bytes, losing 18221 bytes, or more than *10 percent*.

I actually wanted to fork the Wiki, but wasn't aware that any changes would go live immediately. So this issue is mainly to inform you about the change (https://github.com/rollup/rollup/wiki/JavaScript-API#format), and asking if it is okay, or if there is anything else I can help with.

**Comment by jhabdas** [comment]
@danieldiekmeier Mind closing this?

**Comment by jhabdas** [comment]
Thank you from your friendly community Green keeper bot (just kidding, I'm human).

**Comment by danieldiekmeier** [comment]
Sure, no problem! <3
