### ISSUE TITLE
Problem with the external option

### ISSUE THREAD

**Issue by domachine** [rollup/rollup#1290]
Hey,

first of all, thank you for this awesome tool!

I've got a problem with the `external` option. As I read in the wiki (https://github.com/rollup/rollup/wiki/JavaScript-API) I passed in a function that returns a boolean to indicate if an `id` is an external module. But then I get the stacktrace below, which seems that rollup uses the returned boolean as a path. Is the documentation still up to date or do I miss something?

<details>
  <summary>Stack trace</summary>
<pre>
  Error: Could not load false: path must be a string or Buffer while parsing file: ...
    at .../node_modules/rollup/dist/rollup.js:9447:10
</pre>
</details>

**Comment by olsonpm** [comment]
Please reproduce your issue either via [this site](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY3ViZSUyMCU3RCUyMGZyb20lMjAnLiUyRm1hdGhzLmpzJyUzQiU1Q25jb25zb2xlLmxvZyglMjBjdWJlKCUyMDUlMjApJTIwKSUzQiUyMCUyRiUyRiUyMDEyNSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBnZXRzJTIwaW5jbHVkZWQlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3QlMkYlMkYlMjByZXdyaXRlJTIwdGhpcyUyMGFzJTIwJTYwc3F1YXJlKCUyMHglMjApJTIwKiUyMHglNjAlNUNuJTVDdCUyRiUyRiUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zISU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTVEJTdE) or a github repo and respond with a link.

**Comment by domachine** [comment]
Hey, thanks for the quick answer. I quickly threw together a failing sample in the following repo: https://github.com/domachine/rollup-1290.
Just `npm i` and `npm run build`. As you can see I use the `external` option in the `rollup.config.js`. It returns a boolean as described in the wiki. But i errors.

**Comment by olsonpm** [comment]
I'll definitely take a look tomorrow.  Thanks for putting the repo together.

**Comment by olsonpm** [comment]
**Short term fix:**
Make it so your function ignores the entry module name. e.g.

```js
'use strict';

module.exports = {
  entry: 'src/module.js'
  , external: function(id) {
    return id !== 'src/module.js'
      && !id.startsWith('./');
  }
  , format: 'cjs'
};
```

**Explanation:**
if you put a console.log statement like:

```js
// rollup.config.js
  , external: function(id) {
    console.log('id: ' + id);
    return !id.startsWith('./');
  }
```

it spits out

> id: src/module.js
&nbsp;&nbsp;&nbsp;&nbsp;**Could not load false: path must be a string or Buffer**

showing that your issue is that rollup thinks your entry module is external, which makes sense why the error is odd.  The correct fix for a PR would probably be to skip the entry module from the external check.

**Comment by domachine** [comment]
Ah, awesome! Thank you so much, for taking your time. Just tested it and it works like a charm.
