### ISSUE TITLE
Rollup following symlinks breaks imports in Gobble transforms

### ISSUE THREAD

**Issue by fskreuz** [rollup/rollup#1291]
## Summary

Rollup follows symlinks to resolve file paths. However, Gobble uses symlinks to do transforms on *nix systems. This results in Rollup picking up the wrong relative paths from which to import dependencies on certain occasions.

## Reproduction

I could have created a repo or an archive. But the former might be taken down in the future by accident, losing historical value, and the latter is not an option for paranoid people. A step-by-step reproduction is the way to go to address both problems. 😄 

1. Create a directory and run `npm init` on it.
2. `npm install` the following as dependencies:
    - `gobble`
    - `gobble-cli`
    - `gobble-rollup`
    - `fs-plus`
4. Create a file called `gobblefile.js` and use the following as its contents:

    ```js
    const path = require('path');
    const fs = require('fs');
    const gobble = require('gobble');
    const fsPlus = require('fs-plus');

    // Get src
    const src = gobble('src');

    // Create an entrypoint, importing every JS in src and calling their default exports
    const entrypoint = src.transform(generateEntryPoint, { dir: '.', filename: 'main.js' });

    // Merge src with the entrypoint and bundle them up
    module.exports = gobble([ src, entrypoint ]).transform('rollup', {
      format: 'iife',
      moduleName: 'RollupGobbleBug',
      entry: 'main.js',
      dest: 'main-bundle.js'
    }); 

    // Just generates an entrypoint file that imports the default export of every
    // JS file found in the directory and calls the default export as a function.
    function generateEntryPoint(inDir, outDir, options){
      const _options = Object.assign({ dir: '', filename: 'main.js' }, options);
      const testPaths = fsPlus.listTreeSync(path.join(inDir, _options.dir)).filter(testPath => fsPlus.isFileSync(testPath) && path.extname(testPath) === '.js');
      const testImports = testPaths.map((testPath, index) => `import test${index} from './${path.relative(inDir, testPath).replace(/\\/g, '/')}';`).join('\n');
      const testCalls = testPaths.map((testPath, index) => `test${index}();`).join('\n');
      fs.writeFileSync(path.join(outDir, options.filename), `${testImports}\n${testCalls}`, 'utf8');
      return Promise.resolve();
    }
    ```

3. Create a directory called `src` and add the following files inside:

    foo.js
    ```
    export default function(){ console.log('foo') };
    ```

    bar.js
    ```
    export default function(){ console.log('bar') };
    ```

4. Add the following to `package.json`'s `scripts` section:

    ```
    "start": "gobble build build",
    ```

5. Run `npm start`

## Expected result

Expected result should be a `build` directory containing a file named `main-bundle.js` which is a bundled up version of `main.js`, `foo.js` and `bar.js`.

## Actual result

Since Rollup sees `main.js` as a symlink, it follows it all the way back to the `entrypoint` node where the file was created. It uses that node's path as the relative path from which it imports `main.js`'s dependencies. However, `foo.js` and `bar.js` do not exist on the `entrypoint` node. They only exist after the `merge` node.

So when Rollup tries to import `foo.js` and `bar.js` on `main.js`, it's importing it from the wrong directory (it's importing from `01-generateEntryPoint` instead of `02-merge`), resulting in the following error:

```
user@user-VirtualBox:~/Projects/rollup-gobble-bug$ npm start

> rollup-gobble-bug@1.0.0 start /home/user/Projects/rollup-gobble-bug
> gobble build build

gobble: build started
gobble: 01-generateEntryPoint done in 2ms
gobble: 02-merge done in 3ms
∙∙∙∙∙∙∙ 03-rollup running...
gobble: 03-rollup transformation failed

input:  /home/user/Projects/rollup-gobble-bug/.gobble-build/02-merge/1
output: /home/user/Projects/rollup-gobble-bug/.gobble-build/03-rollup/1
>>>
Could not resolve './bar.js' from .gobble-build/01-generateEntryPoint/1/main.js
Error: Could not resolve './bar.js' from .gobble-build/01-generateEntryPoint/1/main.js
    at error (/home/user/Projects/rollup-gobble-bug/node_modules/rollup/dist/rollup.js:170:12)
    at /home/user/Projects/rollup-gobble-bug/node_modules/rollup/dist/rollup.js:9438:7
<<<
```

Verified on both Linux, macOS and GitLab's CI. But this works fine on Windows since Gobble doesn't use symlinks there but actually copies files across transforms.

**Comment by IvanSanchez** [comment]
See https://github.com/gobblejs/gobble-hardlink, https://github.com/paulmillr/chokidar/issues/570 and https://github.com/gobblejs/gobble/issues/129, closely related. Personally I think that Rollup is behaving properly by following symlinks.

**Comment by guybedford** [comment]
The `preserveSymlinks` option can now be used here.
