### ISSUE TITLE
Let loader,resolver plugins have a reference to the Bundle instance

### ISSUE THREAD

**Issue by IvanSanchez** [rollup/rollup#1294]
So I've been creating a bunch of rollup plugins lately (`git-rev`, `unassert` and `grapher`), and then my attention turned to https://github.com/rollup/rollup/issues/1029.

I *think* that the solution is let plugins have a reference to the `Bundle` instance while in their `load`, `resolveId` and `transform` callbacks. Right now only the `ongenerate` and `onwrite` callbacks receive a reference to the `Bundle` instance.

I also propose that function context of *all* plugin callbacks should be the `Bundle` instance. In other words, `this` should be a reference to the bundle, even when it hasn't finished building. e.g.:

```js
function rollupPlugin(opts){
  return {
    load: function load(id) {
      if (condition) {
        // Silently inject a module dep
        this.fetchModule('polyfill', id);
      }
    }
  }
}
```
or
```js
var done = [];
function rollupPlugin(opts){
  return {
    transform: function transform(src, id) {
      if (!done[id]) {
        done[id] = true;  // Prevents infinite recursion
        
        var code = this.transform(source, id);  // Get code after going through other plugins

        // Wrap a code comment around the module with all the module deps
        var module = this.moduleById[id];
        return this.fetchAllDependencies(module).map(mod=>mod.id).then(ids=>{
          var banner = '// ' + ids.join('\n// ') + '\n';
          return banner + code;
        })
      }
    }
  }
}
```

Being able to call `this.fetchAllDependencies(module)`, `this.moduleById`, `fetchModule(id, importer)` *should* cover a few of the tricky edge cases of plugins that need to peek at the resolved modules, or get refs to module dependencies.

Case in point: #1029. By decorating the module ID and delegating to `fetchModule()`, and by fetching the module dependencies, a plugin should be able to get a list of exported identifiers to iterate through and build some worker code with. Kinda like webworkify and the implicit `Function.prototype.toString()` calls, but generating a static list.

This would also cover https://github.com/rollup/rollup/issues/1203 by allowing plugins to call `fetchModule(id, importer)` as they need.

**Comment by olsonpm** [comment]
`this` already gets abused enough these days in javascript in the name of convenience.  Please propose another parameter in the function containing the bundle instance.

**Comment by IvanSanchez** [comment]
I just noticed this is a duplicate of #803 :-)

Also chatted with Rich, got some insight, gonna reword the needs / motivation for this request.
