### ISSUE TITLE
How to create a bundle from two or more modules without an intermediary module?

### ISSUE THREAD

**Issue by jbucaran** [rollup/rollup#1297]
I have a library like so:

```js
// a.js
module.exports = function () {/* ... */}
```

```js
// b.js
module.exports = function () {/* ... */}
```

```js
// c.js
module.exports = function () {/* ... */}
```

```js
// index.js
module.exports = {
  a: require("./a"),
  b: require("./b"),
  c: require("./c")
}
```

So far so good. I also have a module `dummy.js` like so:

```js
// dummy.js
module.exports = {
  a: require("./a"),
  b: require("./b")
}
```

That's it. Notice `dummy.js` does not include `c.js`.

Now, is it possible, using rollup, to create a bundle out of `a` and `b` without having to create `dummy.js`? In other words, I want my project to not have a `dummy.js` file, but be able to create such bundle from `a.js` and `b.js` as if `dummy.js` existed.

Cheers and thanks for the awesome work you're doing here.

**Comment by yairEO** [comment]
I don't understand.  first, why do you use `module.exports` and not ES2015 `import` & `export` and second.

What you are asking is how to import several things at once without creating a file which imports them all and then import that file?

**Comment by jbucaran** [comment]
> why do you use module.exports and not ES2015 import & export and second.

Hi @yairEO. You're right, but that's not relevant to the question. I am using rollup, but not using ES6 export syntax for a reason.

> What you are asking is how to import several things at once without creating a file which imports them all and then import that file?

Maybe? I already have an index.js, the idea is not having to create dummy.js. 

I managed to overcome this issue in my project by removing the dependency for which I needed the dummy.js, so I'm going to close this.
