### ISSUE TITLE
No name was provided for external module 'vue' in options.globals – guessing 'Vue'

### ISSUE THREAD

**Issue by g8up** [rollup/rollup#1299]
run ` rollup -c rollup.config.option.js` got an issue:
> No name was provided for external module 'vue' in options.globals – guessing 'Vue'

```javascript
// rollup.config.option.js
import babel       from 'rollup-plugin-babel';
import babelrc     from 'babelrc-rollup';
import vue         from 'rollup-plugin-vue2';
import css         from 'rollup-plugin-css-only';
import less        from 'rollup-plugin-less';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs    from 'rollup-plugin-commonjs';

let pkg = require('./package.json');
let external = Object.keys(pkg.dependencies);

export default {
	entry: 'src/option.js',
	dest: 'dev/dist/option.js',
	format:'iife',
	moduleName: 'option',
	external,
	plugins: [
		vue(),
		less(),
		css(),
		babel(babelrc()),
		nodeResolve({ jsnext: true}),
		commonjs()
	]
};
```
[my repo](http://git.oschina.net/g8up/auto-fetch/tree/compileVue2/)

**Comment by jonataswalker** [comment]
So set `globals` and you have no issue.

```javascript
    globals: {
      vue: 'Vue'
    }
```

**Comment by andrewmclagan** [comment]
Just to clarify there are ALLOT of github issues around the "No name was provided for external module ..." warning. 

I assumed that `externals` is intended for library authors to not package a dependancy.

So therefore if i'm writing a library compiled with Rollup externals will be all my dependancies i do not want to bundle, although I don't understand the warning above? Its not very clear?

**Comment by netgusto** [comment]
Why is it important to name globals ?

**Comment by netgusto** [comment]
oh, I see; actually it's not just a name, it's the name of the variable where this package is bound; correct ?

**Comment by bennypowers** [comment]
Hi there google!

I got that warm and fuzzy feeling by adding a `globals` property to the default export in rollup.config.js, whose value was an object of type `packageName: global variable`, for example:

```js
export default {

  external: ['aws-sdk'],

  globals: {
    'aws-sdk': 'AWS',
  },
  // etc etc
}
```

in this case, imports of the type `import {S3} from 'aws-sdk'` are now associated with the window property `AWS`

Have fun out there.
