### ISSUE TITLE
Fetch dependencies by import rather than source to allow for different id resolutions via plugin.

### ISSUE THREAD

**Issue by tehvgg** [rollup/rollup#1301]
EDIT: Proposal update in next comment.

The `resolveId()` method of the plugin model exposes the `importee` and `importer` path strings.
If an `importNames` variable was also exposed, it would expand the possibilities of plugins using the method.

```js
// importNames examples
resolveId (importee, importer, importNames) {
  // Default import
  // import SomeModule from "SomeModule";
  importNames === "SomeModule";
  // Named imports
  // import { SubModuleA, SubModuleB } from "SomeModule";
  importNames === [ "SubModuleA", "SubModuleB" ];
}
```

I wrote a [plugin](https://github.com/tehvgg/rollup-plugin-force-binding) that specifically needs access to the import names to dedupe imports by forcing them to come from a single source. The plugin sits in between multi-entry and node-resolve. There is more info in the README of the plugin I linked.

**Comment by tehvgg** [comment]
I've been looking through the code and have some updates on what I think would need to happen for this to be possible.

Named imports have individual Nodes inside the `module.imports` property, but share a source in `module.sources`. Since that is what is passed to the plugin, I cannot change the binding of the named imports individually, and my initial proposal of being given `importNames` would not help.

Instead, dependency resolution would have to be based on imports rather than sources, which should be fine since all imports contain all sources. `importNames` would become `importName`.

```js
resolveId (importee, importer, importName) {
  // default import
  // import SomeModule from "SomeModule";
  importName === "SomeModule";

  // named imports
  // import { SubModuleA, SubModuleB } from "SomeModule";
  // first resolution call
  importName === "SubModuleA";
  // second resolution call
  importName === "SubModuleB";
}
```

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
