### ISSUE TITLE
Core Infrastructure Initiative (CII) Best Practices

### ISSUE THREAD

**Issue by ypid** [rollup/rollup#1302]
I would like to point you to the [CII Best Practices Badge Program](https://bestpractices.coreinfrastructure.org). Could you go thought the [criteria](https://bestpractices.coreinfrastructure.org/criteria), [add the project](https://bestpractices.coreinfrastructure.org/projects/new) and keep it up-to-date there?

Refs:
- https://bestpractices.coreinfrastructure.org
- https://twit.tv/shows/floss-weekly/episodes/389

**Comment by Rich-Harris** [comment]
To be honest this seems like a *lot* of work for no real benefit — I'm going to close this issue. Thanks

**Comment by ypid** [comment]
They are commonly accepted best practices which have real benefits in my eyes. But ok, maybe later.
