### ISSUE TITLE
Babel compatibility, require versus import in rollem.config.js

### ISSUE THREAD

**Issue by mariusk** [rollup/rollup#1303]
I'm using rollup with rollem. In my `rollem.config.js`, when running `rollem --watch` as an npm script, if I import modules like this:

```
const nodeResolve = require('rollup-plugin-node-resolve');
const babel = require('rollup-plugin-babel');
const uglify = require('rollup-plugin-uglify');
```

everything works fine. If I do this instead however:

```
import babel from 'rollup-plugin-babel';
import nodeResolve from 'rollup-plugin-node-resolve';
import uglify from 'rollup-plugin-uglify';
```

everything still works, but now I get the following warnings:

```
'rollup-plugin-babel' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
'rollup-plugin-node-resolve' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
'rollup-plugin-uglify' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
```

As stated, everything works just fine (things get built), but it's still an annoying (and seemingly unecessary) warning.

**Comment by thisconnect** [comment]
Isn't this an issue for https://github.com/bahmutov/rollem/issues ?

**Comment by mariusk** [comment]
You may be right; rollup/rollem is fairly new to me yet so I really can't say. I'll try posting there as well. Thanks.

**Comment by mariusk** [comment]
According to the rollem people, the warning is coming from rollup, see https://github.com/bahmutov/rollem/issues/27 .

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! For the record I'll add a note here, that the message is coming from here, not from Rollem:
https://github.com/rollup/rollup/blob/v0.41.6/src/Bundle.js#L363

**Comment by jhabdas** [comment]
@mariusk can this be closed Re: https://github.com/bahmutov/rollem/issues/27#issuecomment-288054061 it sounds like you're no longer experiencing this issue.

**Comment by mariusk** [comment]
I'm no longer experiencing the issue because I had to migrate off rollup. I don't believe it is really solved either, despite the comments claiming it is documented. I believe the docs referred to describe what is needed for making stuff appear in the bundle, not for running rollup itself (which I had an issue with). But considering the activity here it doesn't seem like much of an issue to others, so I'll close it now anyway. Thanks.

**Comment by jhabdas** [comment]
Thank you for closing, @mariusk. Doing so will help keep the repo cleaner so there's more signal. This issue remains searchable and can be reopened at anytime.
