### ISSUE TITLE
Pass plugin via the CLI

### ISSUE THREAD

**Issue by jorgebucaran** [rollup/rollup#1304]
@Rich-Harris 

Is it possible to specify plugins using the CLI (without a rollup.config.js file)?

Here is my rollup.config.js:
```js
import uglify from "rollup-plugin-uglify"
export default {
    plugins: [
        uglify()
    ]
}
```

And the CLI commands:
```
rollup -cmf umd -n hello -i src/index.js -o dist/hello.js
```

It would be nicer if I could get rid of the configuration and do this instead:

```
rollup -p uglify -cmf umd -n hello -i src/index.js -o dist/hello.js
```

**Comment by stevenvachon** [comment]
Webpack has `--plugin` and `--module-bind`. Would be great if this had something similar.

**Comment by bfred-it** [comment]
Honestly I'd love this, at least to use plugins that don't need special configuration (even though browserify handles that too via [`subarg`](https://github.com/substack/subarg)

**Comment by frank-dspeed** [comment]
@bfred-it this should add a -j option for inline json!
```
roolup -j { "input": "src/main.js",  "output": {  "file": "bundle.js",  "format": "cjs"  } "plugins": [........]}
```

**Comment by franciscop** [comment]
For this specific case you can get away with it in *nix systems by using pipe `|` [as seen here](https://github.com/franciscop/ola/blob/master/package.json#L7):

```js
"build": "rollup ola.js --name Ola --output.format umd | uglifyjs -o ola.min.js"
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by fregante** [comment]
Honestly this would still be nice to have. Many plugins don't need configuration so it's great to just use `rollup` without creating further config files.

**Comment by frank-dspeed** [comment]
@fregante we came to a consens if you want to use rollup without config you can use linux pipe or your own wrapper in general no one else can say what you want or need to do and how. i think it adds zero value to put that into rollup it self it would be more great if the plugins would accept piped input.

**Comment by fregante** [comment]
I wouldn't say it adds _zero_ value. The value is that I can use rollup anywhere on my system without having to create a file first.

**Comment by lukastaegert** [comment]
I somewhat agree with @fregante. A `--plugin` option would be a Rollup CLI-only feature, i.e. all added code would be in the CLI part of Rollup. At the moment, Rollup CLI is already adding a stdin piping plugin, it would not be a big step to also add other plugins. Common useful scenarios would be `rollup main.js --format cjs --plugin commonjs --plugin node-resolve`.

I must add however that at the moment, it does not have a high priority for me, so if you want progress on this, taking the initiative with a PR would go a long way.

I can assist with some guidance if there is interest.
