### ISSUE TITLE
Resolve modules from an other repository.

### ISSUE THREAD

**Issue by chocolord** [rollup/rollup#1305]
Hello,

I want to use one rollup configuration to bundle all applications of my project so I made a `rollup` directory at the root of my project.
I need rollup to search dependencies in `/rollup/node_modules/` to regroup my application's dependencies but it try to resolve them in `/src/sampleApp/node_modules/` instead.

I currently use Webpack2 to bundle my apps in my project and I managed this issue in webpack with the [resolve](https://webpack.github.io/docs/configuration.html#resolve) and [resolve-loaders](https://webpack.github.io/docs/configuration.html#resolveloader) options of the configuration file.
```javascript
  resolve: {
    modules: [ path.resolve('node_modules') ]
  },
  resolveLoader: {
    modules: [ path.resolve('node_modules') ]
  },
```

I created a small repository to illustrate the problem: [rollup-compiler](https://github.com/chocolord/rollup-compiler).

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
