### ISSUE TITLE
ES6 Imports: using different browser and Node.js implementations

### ISSUE THREAD

**Issue by bitjson** [rollup/rollup#1308]
I’ve been trying to understand the best way to define a method in an ES6 library which has a different implementation in Node.js than in the browser. ([Issue #12 in typescript-starter](https://github.com/bitjson/typescript-starter/issues/12))

Both implementations should expose the same API and functionality, but in Node.js, a faster native implementation is preferred. Consumers wanting the Node.js implementation can use the `main` or `module` field in `package.json`, and consumers needing a pure JS implementation can use the `browser` field.

For example: I’d like to create a library which can be imported and used like so:

```
import { sha256 } from ‘my-es6-crypto-lib’
let digest = sha256('abc')
console.log(digest)
```

**What is the best way to do this with Rollup?**

It would be great if we could document a sort of canonical example.

I'd love to figure out how to do this without duplicating code, providing separate functions for each implementation, or performing any kind of runtime checks on which environment is active.

Thanks!

**Comment by bitjson** [comment]
## Option 1

`package.json`
```json
{
   "name": "my-es6-crypto-lib",
   "main": "transpiled-to-commonjs/node.js",
   "module": "lib/node.js",
   "browser": "lib/browser.js"
}
```

(Assume I'm somehow transpiling everything in `lib` to CommonJS in the `transpiled-to-commonjs` directory, and I'm validating with unit tests in all environments.)

`lib/browser.js`:
```js
export { browser_sha256 as sha256 } from './crypto'
```

`lib/node.js`:
```js
export { node_sha256 as sha256 } from './crypto'
```

`lib/crypto.js`
```js
import { createHash } from 'crypto' // Node.js
import { sha256 } from 'hypothetical-pure-js-implementation'

export function node_sha256 (message) {
  return createHash('sha256').update(message).digest('hex')
}

export function browser_sha256 (message) {
  return sha256(message, 'hex')
}
```

I'm not a huge fan of this solution since it requires a lot of similar methods and careful exporting for each implementation. It also means that JSDoc/typedoc wouldn't be able to generate clean documentation for just the `sha256` method.

**Comment by Rich-Harris** [comment]
Rollup itself has this problem — in Node it uses the built-in `fs` and `path` modules, which obviously aren't available in the browser. So the [browser config](https://github.com/rollup/rollup/blob/master/rollup.config.browser.js) adds a plugin that resolves [fs.js](https://github.com/rollup/rollup/blob/master/src/utils/fs.js) and [path.js](https://github.com/rollup/rollup/blob/master/src/utils/path.js) (which wrap/augment the built-in modules) to [browser-specific equivalents](https://github.com/rollup/rollup/tree/master/browser). This technique involves no runtime environment checks.

With judicious use of `export * from ...` declarations I think it's possible to get to where you need with a minimum of code repetition.
