### ISSUE TITLE
Some modules are not included to a bundle when the treeshake is off

### ISSUE THREAD

**Issue by FinesseRus** [rollup/rollup#1315]
Rollup doesn't include variables, function and classes to a result bundle in some cases when the treeshake parameter is off. Try the following example.

The entry file `main.js`:
```js
import Foo from './foo.js';
new Foo();
```

The imported file `foo.js`:
```js
class Foo {
    constructor() {
        console.log('foo');
    }
}

export default Foo;
```

The result of bundling using Rollup (with treeshake off and output format `iife`) is:
```js
(function () {
'use strict';

var Foo = Foo;

new Foo();

}());
```

As you can see Rollup doesn't include the `Foo` class to the bundle. When the threeshake is on, the bug doesn't appear.

**Comment by Victorystick** [comment]
@FinesseRus Is this still an issue now that #1375 is merged?

**Comment by FinesseRus** [comment]
@Victorystick, it is fixed. Thanks! 👍
