### ISSUE TITLE
Incorrect module order

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#132]
Modules are ending up in a funny order following some recent changes – [this test](https://github.com/rollup/rollup/tree/module-order/test/function/module-sort-order) has the details. Essentially it looks as though modules are claiming a dependency on other modules that mutate their values, which is technically accurate but which breaks the module sorting algorithm.

The offending code is [here](https://github.com/rollup/rollup/blob/c903bb2e4e7f7b4fc0378945f4478b58020e29ff/src/Module.js#L414-L417), but it can't removed without re-introducing a bug that was previously handled [here](https://github.com/rollup/rollup/blob/0df5d9b1775d617512f59238b7e26841a3b119c4/src/Bundle.js#L228-L268) – this method included all the necessary code but without impacting module order. @Victorystick any idea how to fix?

**Comment by Victorystick** [comment]
I'll look in to it. :+1:

**Comment by Rich-Harris** [comment]
@Victorystick have you had any thoughts about how to solve this? I've tried to come at it a few different ways, to no avail (I don't think I quite grok all the new stuff around the `Scope` and `Identifier` classes yet!). At the moment we're shipping a broken library, so hopefully we can figure it out between us... :grimacing:

**Comment by Victorystick** [comment]
Hmm. In `bundle.sort`, when I log the `strongDeps` structure I get the same structure no matter if I include [this](https://github.com/rollup/rollup/blob/c903bb2e4e7f7b4fc0378945f4478b58020e29ff/src/Module.js#L414-L417) or not.

```
main.js
  needs -> z.js
z.js

c.js
 
b.js
 
a.js
  needs -> z.js
```
The sort order shouldn't be effected by `weakDependencies` anyway, right?

**Comment by Victorystick** [comment]
The `weakDependencies` helps to decide what modules _are_ included, and not _the order_ they're included, right?

The issue seems to be related to the `ordered` array.
> unordered is actually semi-ordered, as [ fewer dependencies ... more dependencies ]

This used to hold before, but the previous step doesn't seem to preserve the invariant anymore. The module order is `[ 'a', 'b', 'c', 'z', 'main' ]` after the first step, compared to `[ 'b', 'c', 'z', 'a', 'main' ]`.

But as you can see, `a` actually _has_ a strong dependency on `z`, unlike `c`, `b` and `z`. But it gets sorted first despite of this.

**Comment by Victorystick** [comment]
What exactly qualifies a `weakDependency`? They seriously affect the initial state of `ordered`, which of itself determines how well the final sort works if there are cycles.

**Comment by Rich-Harris** [comment]
> The `weakDependencies` helps to decide what modules *are* included, and not *the order* they're included, right?

Not quite – if a bundle had no cyclical dependencies, we could ignore `strongDependencies` and do a straightforward toposort, in which case the order would be entirely determined by `weakDependencies`. As it is, we *do* of course have to account for cycles, but `weakDependencies` still affects the ordering – if `a` depends (weakly or strongly, directly or transitively) on `b` but not vice versa, `b` is guaranteed to be placed before `a`.

I'll try and articulate the distinction between strong and weak dependencies:

If module `a` has a dependency on module `b`, it means that `a` doesn't work without `b`:

```js
// a.js - won't work without b.js
import b from './b';

export default function a () {
  return b() * 2;
}

// b.js
export default function b () {
  return 21;
}
```

If `a` has a strong dependency on `b`, it means something more – not just that it doesn't *work* without `b`, but that it won't even *execute* without throwing an error:

```js
// a.js - won't **execute** without b.js, so b.js **must** go first
import b from './b';

export default b() * 2;

// b.js
var b = () => 21;
export default b; // is a var, so can't rely on function hoisting
```

Since we occasionally encounter cyclical dependencies, we draw this distinction to ensure that if `x` weakly depends on `y`, but `y` strongly depends on `x`, there's no ambiguity about which goes first. (Because of transitive dependencies, we do this in two passes – we collect the transitive dependencies [during the first pass](https://github.com/rollup/rollup/blob/c903bb2e4e7f7b4fc0378945f4478b58020e29ff/src/Bundle.js#L322-L328).)

The reason I highlighted [this chunk of code](https://github.com/rollup/rollup/blob/c903bb2e4e7f7b4fc0378945f4478b58020e29ff/src/Module.js#L414-L417) earlier is that this algorithm fails if we use `weakDependencies` to suggest that `b` depends on `a` in cases like this:

```js
// a.js
import b from './b';
b.foo = 'bar';

// b.js
export default {};
```

Here, `b` **does not** have a dependency on `a` – the bundle as a whole has a dependency on `a` because it affects the value of `b`, which we're using, but that doesn't affect the relationship between `a` and `b` directly.

Hope this clarifies things! Reading it back, I'm not sure whether it does or not...

**Comment by Victorystick** [comment]
It does. I'll give it another go. :+1:
