### ISSUE TITLE
BUG: Unexpected token (please upgrade to the latest version of Acorn)

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup#1321]
[Here is some test code.](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwdmFyJTIwYXMlMjBmb28lMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmZvbyU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2coZm9vKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwKiUyMGZyb20lMjAlNUMlMjIuJTJGYmFyJTVDJTIyJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhci5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJ2YXIlMjBmb28lMjAlM0QlMjAxJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMjBhcyUyMHZhciUyMCU3RCUzQiUyMiU3RCU1RCU3RA==) Replace `export * from "./bar";` with `export { var } from "./bar";` and you will see the `Unexpected token` error.

This bug is [causing problems for people trying to compile PureScript using Rollup](https://github.com/Pauan/rollup-plugin-purs/issues/6).

This is a [bug in Acorn](https://github.com/ternjs/acorn/issues/490), and it was fixed in Acorn version 4.0.5.

However, Rollup is still using Acorn version 4.0.4.

So all that is necessary is for Rollup to upgrade to the latest version of Acorn, and then this bug will be fixed.

**Comment by Pauan** [comment]
@Rich-Harris [Here is the new link to the code.](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHZhciUyMGFzJTIwZm9vJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28lNUMlMjIlM0IlNUNuJTVDbmNvbnNvbGUubG9nKGZvbyklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMHZhciUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGYmFyJTVDJTIyJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhci5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJ2YXIlMjBmb28lMjAlM0QlMjAxJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMjBhcyUyMHZhciUyMCU3RCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) This is still a problem with Rollup version 0.41.6

**Comment by olsonpm** [comment]
Why not create a PR?

**Comment by bfred-it** [comment]
I see `"acorn": "^5.0.3"` now
