### ISSUE TITLE
UMD re-export incorrect after re-exporting an external module

### ISSUE THREAD

**Issue by christopherthielen** [rollup/rollup#1322]
Re-export an external module. Then re-export an internal module.    Generate a UMD bundle.  The internal module symbols are exported as if they came from the external module.

Minimal reproduction: https://github.com/christopherthielen/rollup-bug

```
git clone https://github.com/christopherthielen/rollup-bug
cd rollup-bug
yarn install
yarn build
cat _bundles/rollup-bug.js
```

---

localmodule.js
```
export const FOO = "foo";
```

index.js
```js
export * from "ui-router-core";
export * from "./localmodule";
```

UMD bundle
```
Object.keys(uiRouterCore).forEach(function (key) { exports[key] = uiRouterCore[key]; });
exports.FOO = uiRouterCore.FOO; // FOO is not on uiRouterCore, it's an internal module.
Object.defineProperty(exports, '__esModule', { value: true });
```

---

Interestingly, swapping the order of re-exports seems to work (re-export external modules last)

index.js
```js
export * from "./localmodule";
export * from "ui-router-core";
```

**Comment by guybedford** [comment]
This is an interesting bug and unfortunately there's nothing that can really be done here as we don't know if UI-Router-Core does export a `FOO` or not, so we have to assume it does.

Changing the export order sounds like the right fix here to me.

Marking as a wontfix.
