### ISSUE TITLE
README.md "user guide" link is broken

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#1324]
https://github.com/rollup/rollup contains a link to the "user guide" which points to http://rollupjs.org/guide/ but this returns HTTP 404.

**Comment by Rich-Harris** [comment]
Ah, whoops — the site was updated yesterday so that the guide is the root rather than the REPL, ahead of some wider improvements to the docs. Have fixed the link, and added a redirect to the site. Thanks
