### ISSUE TITLE
Rollup throws syntax error for new style dynamic `import()`

### ISSUE THREAD

**Issue by swernerx** [rollup/rollup#1325]
We are publishing our application with Webpack and bundle our libraries with Rollup. Nowadays we are preparing for dynamic localization. Therefor we are using the new dynamic `import()` syntax to load language files. 

This is working fine in Webpack once we add the `babel-plugin-syntax-dynamic-import` (https://www.npmjs.com/package/babel-plugin-syntax-dynamic-import), but breaks compilation for our libraries with Rollup. We would like that Rollup just keeps these imports as is without touching them. We are bundling for ES module environments.

For publishing our libraries we are using the [Prepublish](https://github.com/sebastian-software/prepublish) tool which now contains a test for the expected support. That's kind of trivial:

```js
console.log("Dynamic Import returns Promise", import("./logo.svg"))
```

Rollup version is: 0.41.4.

Rollup currently fails with the following stack trace:

<details>
  <summary>Stack trace</summary>

```
{ Error: Unexpected token
    at error (/Users/sebastian/Workspace/sebastian-software/prepublish/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/Users/sebastian/Workspace/sebastian-software/prepublish/node_modules/rollup/dist/rollup.js:7997:2)
    at tryParse (/Users/sebastian/Workspace/sebastian-software/prepublish/node_modules/rollup/dist/rollup.js:7700:10)
    at new Module (/Users/sebastian/Workspace/sebastian-software/prepublish/node_modules/rollup/dist/rollup.js:7735:14)
    at /Users/sebastian/Workspace/sebastian-software/prepublish/node_modules/rollup/dist/rollup.js:9481:17
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
  code: 'PARSE_ERROR',
  pos: 9873,
  loc: 
   { file: '/Users/sebastian/Workspace/sebastian-software/prepublish/test/src/index.js',
     line: 389,
     column: 46 },
  frame: '387: ) instanceof ReactTest);\n388: \n389: console.log("Dynamic Import returns Promise", import("./logo.svg"));
 ```
</details>

**Comment by swernerx** [comment]
I am not sure whether this issue is actually a problem with rollup or with the underlying JS parser Acorn. See also: https://github.com/ternjs/acorn/issues/477

**Comment by swernerx** [comment]
It is now in stage3... not stage4 yet unfortunately.
https://github.com/tc39/proposal-dynamic-import#import

**Comment by Victorystick** [comment]
This issue should be resolved once stage 4 is reached, Acorn implements support for it and Rollup updates it's bundled version of Acorn.
