### ISSUE TITLE
Add support for custom finalizers

### ISSUE THREAD

**Issue by steelbrain** [rollup/rollup#1326]
## Current Behavior

There's no external way known to me to specify finalizers or change their output

## Request Behavior

If `options.format` is a function, treat it as a finalizer, should be a 5 mins change [here](https://github.com/rollup/rollup/blob/e955ea76b1c4296c4f58f456642836489f00a176/src/Bundle.js#L476-L486)

**Comment by shellscape** [comment]
Closing, as the accompanying PR was closed as "no longer needed" by the author.
