### ISSUE TITLE
ability for plugins to modify, enhance or utilise bundle tree-shaking details

### ISSUE THREAD

**Issue by hoistedvar** [rollup/rollup#1334]
Tree-shaking is one of the core principles of rollup (probably second only to the actual code bundling) but at present with the current plugin architecture does not expose any way to either customise how this is carried out or to utilise the result of the tree shaking information in the generation process.

There are numerous issues raised against rollup regarding tree shaking that would be better suited to external plugins, for instance in cases where a large amount of static analysis would need to be carried out to perform more rigorous tree shaking, or tree shaking hints. The core tree shaking algorithm within rollup at present is great for handling 95% of all situations, and I think this should be the goal of the core algorithm, specialisations beyond that within the core would only complicate the code base.

Unfortunately currently it is not possible to consume or modify the tree shaking data either from within a plugin or using a wrapped execution approach - calling rollup directly and manipulating the resultant bundle object. This is because the bundle that is produced it neutered in that the AST that contains the tree shaken markup for a module is replaced with the clone of the original AST without this markup.

We currently have a custom build of rollup that allows manipulation of the bundle before processing, one of our key uses is to allow 'weak' includes where only exports that are used elsewhere are imported into a particular location, which is great for tree shaking code where included code might need to be 'processed', that processing in normal circumstances would cause the tree shaking to include everything, the 'weak' inclusion allows use to break the application down automatically. Something like this should not be incorporated into the core rollup tree shaking but is incredibly useful as a plugin.

I've put together a minimal change that would allow for tree-shaking / bundle manipulating plugins to be integrated, it can be found here:

hoistedvar/rollup@c181da7619de97aff5b8cf197157e51bcbbc397a

I'm happy to discuss it, or submit it as a pull request.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
