### ISSUE TITLE
Tree shaking doesn't work when exporting via another file.

### ISSUE THREAD

**Issue by motnik** [rollup/rollup#1335]
Consider [this example](http://rollupjs.org/?version=0.41.5&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JhJTdEJTIwZnJvbSUyMCcuJTJGYWJjJTJGaW5kZXguanMnJTVDbmltcG9ydCUyMCU3QmIlN0QlMjBmcm9tJTIwJy4lMkZhYmMlMkZpbmRleC5qcyclNUNuaW1wb3J0JTIwJTdCeCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGeHl6JTJGaW5kZXguanMlNUMlMjIlNUNueCgpJTNCJTVDbmEoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhYmMlMkZhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMHZhciUyMGElMjAlM0QlMjAlMjAoZnVuY3Rpb24lMjAoKSU3QiU1Q24lMjAlMjByZXR1cm4lMjBmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCdhJyklM0IlNUNuJTIwJTIwJTdEJTNCJTVDbiU3RCkoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhYmMlMkZiLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMHZhciUyMGIlMjAlM0QlMjAlMjAoZnVuY3Rpb24lMjAoKSU3QiU1Q24lMjAlMjByZXR1cm4lMjBmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCdiJyklM0IlNUNuJTIwJTIwJTdEJTNCJTVDbiU3RCkoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhYmMlMkZjLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmIlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmluZGV4LmpzJTVDJTIyJTVDbmV4cG9ydCUyMHZhciUyMGMlMjAlM0QlMjAoZnVuY3Rpb24lMjAoKSU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygnYycpJTNCJTVDbiUyMCUyMGIoKSUzQiU1Q24lN0QpKCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYWJjJTJGaW5kZXguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCYSU3RCUyMGZyb20lMjAlNUMlMjIuJTJGYS5qcyU1QyUyMiU1Q25leHBvcnQlMjAlN0JiJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZiLmpzJTVDJTIyJTVDbmV4cG9ydCUyMCU3QmMlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmMuanMlNUMlMjIlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyeHl6JTJGeC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JiJTdEJTIwZnJvbSUyMCU1QyUyMi4uJTJGYWJjJTJGaW5kZXguanMlNUMlMjIlNUNuZXhwb3J0JTIwdmFyJTIweCUyMCUzRCUyMCUyMChmdW5jdGlvbiUyMCgpJTdCJTVDbiUyMCUyMHJldHVybiUyMGZ1bmN0aW9uKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ3gnKSUzQiU1Q24lMjAlMjAlMjAlMjBiKCklM0IlNUNuJTIwJTIwJTdEJTNCJTVDbiU3RCkoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ4eXolMkZ5LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmElN0QlMjBmcm9tJTIwJTVDJTIyLi4lMkZhYmMlMkZpbmRleC5qcyU1QyUyMiU1Q25leHBvcnQlMjB2YXIlMjB5JTIwJTNEJTIwJTIwKGZ1bmN0aW9uJTIwKCklN0IlNUNuJTIwJTIwcmV0dXJuJTIwZnVuY3Rpb24oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZygneScpJTNCJTVDbiUyMCUyMCUyMCUyMGEoKSUzQiU1Q24lMjAlMjAlN0QlM0IlNUNuJTdEKSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnh5eiUyRnouanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCeSU3RCUyMGZyb20lMjAlNUMlMjIuJTJGaW5kZXguanMlNUMlMjIlNUNuZXhwb3J0JTIwdmFyJTIweiUyMCUzRCUyMChmdW5jdGlvbiUyMCgpJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCd6JyklM0IlNUNuJTIwJTIwJTJGJTJGJTIweSgpJTNCJTVDbiU3RCkoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ4eXolMkZpbmRleC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0J4JTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZ4LmpzJTVDJTIyJTVDbmV4cG9ydCUyMCU3QnklN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnkuanMlNUMlMjIlNUNuZXhwb3J0JTIwJTdCeiU3RCUyMGZyb20lMjAlNUMlMjIuJTJGei5qcyU1QyUyMiUyMiU3RCU1RCU3RA==) where, I am trying to use index.js (via plugin [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) ) to export the files in a folder as a module. 
The issue is that when importing from a folder's index.js, rollup considers the `export` statements as a usage of the module. You can see `z$$1` getting created in the bundle, which is not being used anywhere. Ideally, tree-shaking should take care of such scenarios. 

> P.S. -> Tree shaking for a module in the same folder is working as expected. You can see it by un-commenting the `y()` in `xyz/z.js` file. 

> P.P.S  -> Rollup REPL isn't giving the bundle output directly, you might have to choose some output format, to reflect the changes in output bundle.

**Comment by Rich-Harris** [comment]
The issue here is that you're importing z.js (via index.js), and it has side-effects (the `console.log`) — the fact that you're 'using' `z` is neither here nor there, if Rollup removes that code the program is incorrect.

I'll close this issue as Rollup is behaving as expected. If you need to exclude a module's side-effects, you can't import it, even transitively.
