### ISSUE TITLE
module.originalSourceMap is missing on rebuild.

### ISSUE THREAD

**Issue by krisselden** [rollup/rollup#1336]
If options.cache is set with the last bundle and a plugin load returns a `{ code, map }` then module.originalSourceMap is missing even though the load hooks rerun and still return a `{ code, map }`

I tracked this down to `Module.prototype.toJSON` doesn't output the `originalSourceMap` which is a simple fix but I need to write a test and can't get to it right this moment.

**Comment by Rich-Harris** [comment]
Thanks! Released 0.41.6 with the fix
