### ISSUE TITLE
Scoped variable name conflict with star import

### ISSUE THREAD

**Issue by btpoe** [rollup/rollup#1338]
I've found this bug to be tied to when the following is true:

- module export passes through another module's default export as a named export
- wrapping module's named export does not equal the file name of the imported module
- consuming module uses a variable (inside a scope) of the same name as the file name of the module with the default export.

This is happening in Rollup v0.41.5

Source modules:

`main.js`
```javascript
import * as wrap from './wrap';

function scope() {
  const group = wrap.Group();
}

scope();
```

`group.js`
```javascript
export default function() {
  return true;
}
```

`wrap.js`
```javascript
export { default as Group } from './group';
```

Rollup Output:

```javascript
'use strict';

function group() {
  return true;
}

function scope() {
  const group = group();
}

scope();
```

**Comment by pspeter3** [comment]
Is there a suggested work around or way to fix this?

**Comment by btpoe** [comment]
To be honest, I haven't dug to deep for an actual fix in rollup.

As far as work arounds, I think if you name the default variable the same as the file name imported, you shouldn't run into the problem.

**Comment by emilos** [comment]
repro in repl https://rollupjs.org/repl?version=0.52.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHdyYXAlMjBmcm9tJTIwJy4lMkZ3cmFwJyUzQiU1Q24lNUNuZnVuY3Rpb24lMjBzY29wZSgpJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwZ3JvdXAlMjAlM0QlMjB3cmFwLkdyb3VwKCklM0IlNUNuJTVDdHJldHVybiUyMGdyb3VwJTNCJTVDbiU3RCU1Q24lNUNuJTVDbnZhciUyMHglMjAlM0QlMjBzY29wZSgpJTNCJTVDbmNvbnNvbGUubG9nKHgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMndyYXAuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwZGVmYXVsdCUyMGFzJTIwR3JvdXAlMjAlN0QlMjBmcm9tJTIwJy4lMkZncm91cCclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZ3JvdXAuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uKCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwdHJ1ZSUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==
