### ISSUE TITLE
Allow undefined imports in getInteropBlock

### ISSUE THREAD

**Issue by paulfalgout** [rollup/rollup#1341]
Most interopts I've seen, babel, webpack, and rollup's [cjs interop](https://github.com/rollup/rollup/blob/master/src/finalisers/cjs.js#L42) check for the existence of the imported value prior to checking for `default`.

I tried to read the ecma specs but they're pretty confusing.  If an import statement isn't relative, is this expected to throw an error?

```js
import foo from 'foo-does-not-exist';

// or would it just be undefined?
foo === undefined;
```

Even _if_ it would throw an error in ES2015 modules, if I know my target is UMD anyways, and it is an external dependency, why not allow it to import without an error?

FWIW.. the exact same src will work if you're exporting the commonjs, but it will fail for UMD which seems less than ideal.

The solution is also very simple.

Instead of
```js
foo = 'default' in foo ? foo['default'] : foo;
```
 
it'd be
```
foo = foo && 'default' in foo ? foo['default'] : foo;
```

I have a PR ready to go if this is reasonable.

**Comment by Rich-Harris** [comment]
Released 0.43 with the fix
