### ISSUE TITLE
External option value to ignore all node like importee

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#1343]
Would be good to ignore all node like packages via one option in cli.
Now I need to specify all packages comma-separated.

```
rollup -i src/index.js -o dist/compose.js -f cjs -e inferno,inferno-create-element,inferno-component
```

**Comment by Rich-Harris** [comment]
Isn't this just a case where you're better off using a config file, where you can just use `Object.keys(pkg.dependencies)`? I think that's preferable to adding all kinds of extra options (that have to be documented and maintained in perpetuity).

**Comment by guybedford** [comment]
Agreed the above function sounds like a nice one to include. Perhaps make this a `--excludeBareImports` flag or similar?

Also we can special case the exclude function such that if the module resolves to an entry point it shouldn't be treated as external. This does require running the resolver on what might be treated as externals, but that seems worth the cost of deduping entrypoints to me.

**Comment by guybedford** [comment]
Note we should probably also detect full URLs via a `try { new URL(x); exclude(x); } catch (e) { include(x); } ideally here.

Since URLs are being covered too, maybe `--excludeExternal` is all we need.

**Comment by TrySound** [comment]
So how `external` function will behave alongside with `excludeExternal` flag? Should we warn? Maybe it will be better to extend `external` union with some identifiers to omit impossible case. Maybe even symbols?
```js
{
  external: Symbol.for('excludeExternal')
}
```

**Comment by guybedford** [comment]
I'd imagined them being mutually exclusive with `--excludeExternal` as effectively an alias for a default `external` function. Trying to work out the custom inclusions / exclusions over and above exclude external gets tricky, but perhaps we can just treat it as the fallback external function like all other hooks work when both are applied together?

**Comment by guybedford** [comment]
(where an explicit true / false return takes precedence)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
