### ISSUE TITLE
Temporary lazy loading / multi-module workaround

### ISSUE THREAD

**Issue by PRR24** [rollup/rollup#1347]
I hope Rollup will have a functionality or plugin to support Angular lazy loading at some point.

But while the functionality is not yet available, is there some easy trick to combine lazy loaded modules into one bundle without removing lazy loading from the source code?

I mean that, if one has
- Router mapping: ... { path: 'lazy', loadChildren: 'src/lazy/module#LazyModule' }
- AOT compiled code for the app and for the lazy module
it could be combined/optimized into one bundle.js.

Thanks.

**Comment by bfred-it** [comment]
Can you be more specific? I'm not familiar with Angular's lazy loading code. I think this is the closest rollup will get: #372

**Comment by TakanashiOuken** [comment]
Same question here seems like rollup doesn't work with lazy loading but we pack does

**Comment by guybedford** [comment]
These sorts of lazy loading workflows should be possible now through dynamic import support in Rollup. If there is more that we can do to facilitate, let's track new suggestions in their own issues.
