### ISSUE TITLE
UMD without  requirejs seajs, rollup  it don't work

### ISSUE THREAD

**Issue by heavenhian** [rollup/rollup#1348]
rolleup.js part of config^

 format:'umd',
external: [ 'd3' ],
  paths: {
    d3: 'https://d3js.org/d3.v4.min.js'
}

then rollup translate

typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('https://d3js.org/d3.v4.min.js')) :
	typeof define === 'function' && define.amd ? define(['https://d3js.org/d3.v4.min.js'], factory) :
	(global.aModule = factory(global.d3));

 not load https://d3js.org/d3.v4.min.js, and it can't work

**Comment by Ashot-KR** [comment]
try to remove `.js`
```js
paths: {
  d3: 'https://d3js.org/d3.v4.min'
}
```
that should work.
it looks like error in wiki

**Comment by cool-Blue** [comment]
@heavenhian, not sure what you are doing but I certainly don't get the same output as you in the bundle.

I get 
```js
typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('https://d3js.org/d3.v4.min.js')) :
typeof define === 'function' && define.amd ? define(['https://d3js.org/d3.v4.min.js'], factory) :
factory(global.https___d3js_org_d3_v4_min_js));

But, anyway, this can't work without requirejs or whatever because `rollup` doesn't provide a `define` function on the `window` object.

**Comment by Rich-Harris** [comment]
This is expected behaviour. If you're using a module loader, it will fetch dependencies from wherever you specify. If you're not, you need to put them on the page as `<script>` tags.
