### ISSUE TITLE
Leave async/await untouched

### ISSUE THREAD

**Issue by matthiasg** [rollup/rollup#1349]
We use rollup in some cases to compile server side modules. With node 7 it is now possible to use async/await. 

Therefore it seems necessary to allow async/await as is without touching it basically.

**Comment by jonataswalker** [comment]
In this case you'll use `format: 'cjs'`, right?

**Comment by matthiasg** [comment]
I have experimented some more , it was not a rollup issue to begin with. Sorry for not investigating more properly earlier. 

I had buble and uglify in the pipeline which messed it up.

It works perfectly in my current setup, from modern JS and even with TS
