### ISSUE TITLE
webpack-dev-server  run rollup-loader tips error

### ISSUE THREAD

**Issue by memoryza** [rollup/rollup#1350]
ERROR in (webpack)-dev-server/client?http://0.0.0.0:8081
Module build failed: Error: Could not load false: path must be a string or Buffer
    at /Users/memoryza/nuomi/channel/node_modules/rollup-loader/node_modules/rollup/dist/rollup.js:8913:10
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 webpack/hot/dev-server ./src/test/page/common/common.js

i find  webpack-dev-server  inject "/Users/memoryza/nuomi/channel/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8081 " to entry.

and rollup can't analysis it, and return this entry is false

**Comment by Rich-Harris** [comment]
I'm afraid this issue is incomprehensible. It sounds like you need to raise it with rollup-loader!
