### ISSUE TITLE
"Error not exported" while importing protobuf.js generated static-module?

### ISSUE THREAD

**Issue by fightingcat** [rollup/rollup#1353]
Here is a [demonstration](https://github.com/fightingcat/fightingcat.github.io/blob/master/test.zip)(somehow I can't upload zip file in this issue).

Here is the stack trace:
<details>
  <summary>
    Error: 'test' is not exported by src\test.js
  </summary>
  at error (E:\workspace2\test\node_modules\rollup\dist\rollup.js:170:12)
  at Module.error$1 [as error] (E:\workspace2\test\node_modules\rollup\dist\rollup.js:8007:2)
  at Module.trace (E:\workspace2\test\node_modules\rollup\dist\rollup.js:8106:9)
  at ModuleScope.findDeclaration (E:\workspace2\test\node_modules\rollup\dist\rollup.js:7691:22)
  at Node.bind (E:\workspace2\test\node_modules\rollup\dist\rollup.js:6743:29)
  at E:\workspace2\test\node_modules\rollup\dist\rollup.js:5291:50
  at Node.eachChild (E:\workspace2\test\node_modules\rollup\dist\rollup.js:5305:19)
  at Node.bind (E:\workspace2\test\node_modules\rollup\dist\rollup.js:5291:7)
  at Node.bind (E:\workspace2\test\node_modules\rollup\dist\rollup.js:6040:23)
  at E:\workspace2\test\node_modules\rollup\dist\rollup.js:5291:50
</details><br />

These plugins or packages are used:
    "gulp": "^3.9.1",
    "rollup": "^0.41.6",
    "rollup-plugin-commonjs": "^8.0.2",
    "rollup-plugin-node-resolve": "^2.1.1",
    "rollup-plugin-typescript": "^0.8.1"
    "protobufjs": "^6.6.5"

These options are used with pbjs for generating static code: "-t static-module -w commonjs"
Even "-w es6" doesn't work neither. 

Since "-w es6" implies "--es6" option, and I don't want other transpiler than typescript, I'd rather like to make it work with rollup-plugin-commonjs. There will be a lot of messages exported, so "namedExports" is not my option.

Thanks.

**Comment by fightingcat** [comment]
I tried to import 'protobuf/minimal' as the generated code did, and got
`
node_modules\@protobufjs\inquire\index.js (12:18) Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
`

I didn't see that minimal version had required such file but still affected bundling, maybe this is what caused this issue?

If there are anything I was doing wrong?

**Comment by fightingcat** [comment]
I have figured out what I was doing wrong, I have the generated js file and d.ts file in same path, it seems that I must import the generated file with .js extension explicitly, otherwise it won't work. Somehow the d.ts file involved bundling, I thought everything is happening in transpiled javascript code, now I doubt that.
Anyway, I have solved my problem, close now. Still I hope there is a wiki explain how this work, feel kind of fuzzy about this now.

**Comment by fightingcat** [comment]
Sorry I made a mistake, it didn't work, please help.

**Comment by Shyam-Chen** [comment]
https://github.com/Shyam-Chen/Frontend-Starter-Kit/blob/master/tools/config/rollup.js#L63

**Comment by fightingcat** [comment]
it's not working, the "use of eval" warning only exists when I try to import "protobufjs/minial" directly, but not when I import the generated code which also required that.

**Comment by fightingcat** [comment]
https://github.com/Shyam-Chen/Frontend-Starter-Kit/blob/master/tools/config/rollup.js#L40
I read your config file again and found a solution, I didn't expect using namedExports this way. Thank you very much!
I'm not closing this issue right now, expecting an explanation.

**Comment by Shyam-Chen** [comment]
If module is not ES Modules, you must set `namedExports`.

**Comment by fightingcat** [comment]
Thanks, now I get it, since it's not main purpose to support CommonJS，I should close this issue now.
