### ISSUE TITLE
Any way to express that a default export (as a transitive dependency) is side-effect free?

### ISSUE THREAD

**Issue by teehemkay** [rollup/rollup#1354]
Say we have  a `module A` that imports a named dependency, let's call it `b`, of `module B`. From B, A only imports `b` but `module B` also contains other dependencies other modules. 

When using rollup with `module A` as the `entry` for `rollup`, I would have expected that only `b` (and things it references in `module B`) would be included in the generated bundle.

Instead, any function in `module B` or anything that references a dependency of `module B` ** that is a `default` export of another module is also included** in the bundle as if no tree-shaking is being performed in `module B` for things referencing `default` exports . I'm guessing this because `rollup` by default assumes that  default export may have side effects?

This is really problematic when one is using a functional programming library such as `Ramda` which provides pure functions and each function is contained in it's own module with a single export which is a *default* export.

Those functions are typically higher-order functions that are used to create other functions.  So it's very easy to encounter the use case mentioned above.

[sscce](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZ1YmFyJTIwJTdEJTIwZnJvbSUyMCcuJTJGY29tcHV0ZSclNUNuJTVDbmNvbnNvbGUubG9nKCUyMGZ1YmFyJTIwKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb21wdXRlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGFkZCUyMGZyb20lMjAnLiUyRmFkZCclNUNuaW1wb3J0JTIwdGltZXMlMjBmcm9tJTIwJy4lMkZ0aW1lcyclNUNuaW1wb3J0JTIwJTdCJTIwZm9vJTIwJTdEJTIwZnJvbSUyMCcuJTJGZm9vJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBhZGQxJTIwJTNEJTIwYWRkKDEpJTVDbmNvbnN0JTIwYWRkMTAlMjAlM0QlMjBhZGQoMTApJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGhlbGxvJTIwJTNEJTIwbmFtZSUyMCUzRCUzRSUyMCdoZWxsbyUyMCclMjAlMkIlMjBuYW1lJTVDbmV4cG9ydCUyMGNvbnN0JTIwZnViYXIlMjAlM0QlMjBmb28lMjAlMkIlMjAnYmFyJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjB0aW1lczIlMjAlM0QlMjB0aW1lcygyKSU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYWRkLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAlMkIlMjBiJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRpbWVzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAqJTIwYiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAnZm9vJyU1Q25leHBvcnQlMjBjb25zdCUyMGJhciUyMCUzRCUyMCdiYXInJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

OTOH, when `c` is instead a *named* export (as opposed to a *default*) export of `module C`, then rollup only include `b` in the bundle.

[sscce](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGFkZDElMjAlN0QlMjBmcm9tJTIwJy4lMkZjb21wdXRlJyUzQiU1Q24lNUNuY29uc29sZS5sb2coJTIwYWRkMSglMjAxJTIwKSUyMCklM0IlMjAlMkYlMkYlMjAyJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmNvbXB1dGUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCYWRkJTJDJTIwdGltZXMlN0QlMjBmcm9tJTIwJy4lMkZvcGVyYXRpb25zJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBhZGQxJTIwJTNEJTIwYWRkKDEpJTVDbmV4cG9ydCUyMGNvbnN0JTIwYWRkMTAlMjAlM0QlMjBhZGQoMTApJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMHRpbWVzMiUyMCUzRCUyMHRpbWVzKDIpJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJvcGVyYXRpb25zLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmFkZCU3RCUyMGZyb20lMjAnLiUyRmFkZCclNUNuaW1wb3J0JTIwJTdCdGltZXMlN0QlMjBmcm9tJTIwJy4lMkZ0aW1lcyclNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGFkZCUyQyUyMHRpbWVzJTIwJTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhZGQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBhZGQlMjAlM0QlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAlMkIlMjBiJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRpbWVzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwdGltZXMlMjAlM0QlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAqJTIwYiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

**Comment by olsonpm** [comment]
This can now be handled via `/* #__PURE__ */` annotations supported by [uglifyjs2](https://github.com/mishoo/UglifyJS2#compressor-options) (see compressor option 'side_effects')

[I created a repo](https://github.com/olsonpm/ramda-with-rollup-example) showing this functionality with ramda specifically.  I don't think rollup supports that annotation directly, nor do I think it should given uglifyjs2 is so ubiquitous.

**Comment by teehemkay** [comment]
@olsonpm thank you so much for pointing this out and for the creating a repo to illustrate the point.

This looks exactly like what I was looking for.

**Comment by olsonpm** [comment]
Just realized my example repo might be confusing without [context](https://github.com/ramda/ramda/issues/1968#issuecomment-301207158)

**Comment by Andarist** [comment]
Updated working links:
[`named exports example`](https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGFkZDElMjAlN0QlMjBmcm9tJTIwJy4lMkZjb21wdXRlJyUzQiU1Q24lNUNuY29uc29sZS5sb2coJTIwYWRkMSglMjAxJTIwKSUyMCklM0IlMjAlMkYlMkYlMjAyJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmNvbXB1dGUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCYWRkJTJDJTIwdGltZXMlN0QlMjBmcm9tJTIwJy4lMkZvcGVyYXRpb25zJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBhZGQxJTIwJTNEJTIwYWRkKDEpJTVDbmV4cG9ydCUyMGNvbnN0JTIwYWRkMTAlMjAlM0QlMjBhZGQoMTApJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMHRpbWVzMiUyMCUzRCUyMHRpbWVzKDIpJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJvcGVyYXRpb25zLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmFkZCU3RCUyMGZyb20lMjAnLiUyRmFkZCclNUNuaW1wb3J0JTIwJTdCdGltZXMlN0QlMjBmcm9tJTIwJy4lMkZ0aW1lcyclNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGFkZCUyQyUyMHRpbWVzJTIwJTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhZGQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBhZGQlMjAlM0QlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAlMkIlMjBiJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRpbWVzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwdGltZXMlMjAlM0QlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAqJTIwYiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)
[`default exports example`](https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZ1YmFyJTIwJTdEJTIwZnJvbSUyMCcuJTJGY29tcHV0ZSclNUNuJTVDbmNvbnNvbGUubG9nKCUyMGZ1YmFyJTIwKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb21wdXRlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGFkZCUyMGZyb20lMjAnLiUyRmFkZCclNUNuaW1wb3J0JTIwdGltZXMlMjBmcm9tJTIwJy4lMkZ0aW1lcyclNUNuaW1wb3J0JTIwJTdCJTIwZm9vJTIwJTdEJTIwZnJvbSUyMCcuJTJGZm9vJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBhZGQxJTIwJTNEJTIwYWRkKDEpJTVDbmNvbnN0JTIwYWRkMTAlMjAlM0QlMjBhZGQoMTApJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGhlbGxvJTIwJTNEJTIwbmFtZSUyMCUzRCUzRSUyMCdoZWxsbyUyMCclMjAlMkIlMjBuYW1lJTVDbmV4cG9ydCUyMGNvbnN0JTIwZnViYXIlMjAlM0QlMjBmb28lMjAlMkIlMjAnYmFyJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjB0aW1lczIlMjAlM0QlMjB0aW1lcygyKSU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYWRkLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAlMkIlMjBiJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRpbWVzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMGElMjAqJTIwYiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAnZm9vJyU1Q25leHBvcnQlMjBjb25zdCUyMGJhciUyMCUzRCUyMCdiYXInJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

I believe this is some inconsistency in rollup's implementation of tree-shaking. I dont see why named vs default exports should differ in their tree-shakeability - they are only different in how they can be consumed by other modules.

**Comment by olsonpm** [comment]
@Andarist - you consider the named exports example as working?  Most developers would be surprised to see `const add10 = add(10);` in there.  Also the issue with the default seems to be due to the lack of function names.  If you [name them](https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZ1YmFyJTIwJTdEJTIwZnJvbSUyMCcuJTJGY29tcHV0ZSclNUNuJTVDbmNvbnNvbGUubG9nKCUyMGZ1YmFyJTIwKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb21wdXRlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGFkZCUyMGZyb20lMjAnLiUyRmFkZCclNUNuaW1wb3J0JTIwdGltZXMlMjBmcm9tJTIwJy4lMkZ0aW1lcyclNUNuaW1wb3J0JTIwJTdCJTIwZm9vJTIwJTdEJTIwZnJvbSUyMCcuJTJGZm9vJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBhZGQxJTIwJTNEJTIwYWRkKDEpJTVDbmNvbnN0JTIwYWRkMTAlMjAlM0QlMjBhZGQoMTApJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGhlbGxvJTIwJTNEJTIwbmFtZSUyMCUzRCUzRSUyMCdoZWxsbyUyMCclMjAlMkIlMjBuYW1lJTVDbmV4cG9ydCUyMGNvbnN0JTIwZnViYXIlMjAlM0QlMjBmb28lMjAlMkIlMjAnYmFyJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjB0aW1lczIlMjAlM0QlMjB0aW1lcygyKSU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYWRkLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGFkZChhKSUyMCU3QiUyMHJldHVybiUyMGIlMjAlM0QlM0UlMjBhJTIwJTJCJTIwYiUzQiUyMCU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0aW1lcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjB0aW1lcyhhKSUyMCU3QiUyMHJldHVybiUyMGIlMjAlM0QlM0UlMjBhJTIwKiUyMGIlM0IlMjAlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwZm9vJTIwJTNEJTIwJ2ZvbyclNUNuZXhwb3J0JTIwY29uc3QlMjBiYXIlMjAlM0QlMjAnYmFyJyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) then the code is removed.  I'm not going to look into why because I don't think fiddling with rollup's tree-shaking is a good use of time.

**Comment by Andarist** [comment]
I dont really consider any of them working properly :D Im not familiar that much with rollup's exact algorithm for tree-shaking, but from what I understand about uglifyjs' DCE both examples are 'wrong' in some way. 

I dont say rollup should behave like uglifyjs, but looking at both those examples I see a serious (dangerous for the users) inconsistency. Both examples should behave the same in regards for tree-shaking, same rules should apply and I see their results as unexpected.

Maybe @Rich-Harris or @lukastaegert could shed some light on this matter.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
