### ISSUE TITLE
rollupjs.org -> better sidebar width [suggestion]

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#1355]
New page sidebar would look much better with `width: 17em;` which will eliminate line drops of nav items.

# Now:
![as-is](https://cloud.githubusercontent.com/assets/845031/24605916/7ff08e8c-1873-11e7-8efd-50119f01d856.png)

# Better (single-line items):
![wider](https://cloud.githubusercontent.com/assets/845031/24605959/b74b5e70-1873-11e7-9277-3fd2ff193309.png)

**Comment by Rich-Harris** [comment]
Agree! I've updated it, thanks
