### ISSUE TITLE
Chain plugins `resolveId` functions

### ISSUE THREAD

**Issue by mjeanroy** [rollup/rollup#1356]
Hi @Rich-Harris,

I think it could be great to be able to chain plugins `resolveId` functions. Currently, this limitation make impossible to use two plugins that uses this function.

See this example:
- I would like to use `rollup-plugin-alias` to replace `underscore` dependency with `lodash`
- Then, I would like to use `rollup-plugin-node-resolve` to load `lodash` from the `node_modules` directory.

Here is a configuration that could work if the `resolveId` functions are chained:

```javascript
module.exports = {
  entry: 'src/index.js',
  dest: 'dist/bundle.js',
  format: 'es',
  plugins: [
    // Replace underscore with lodash...
    alias({
      'underscore': 'lodash',
    }),

    // Then, load lodash from `node_modules`...
    nodeResolve(),

    // Then, use the commonjs transformation.
    commonjs(),
  ],
};
```

You can see a test-project with this configuration [here](https://github.com/mjeanroy/test-rollup-alias).

Maybe I don't use these plugins in a correct way, what do you think?

**Comment by mjeanroy** [comment]
@Rich-Harris I solved my problem here by using `require.resolve` in the `rollup-plugin-alias` configuration to point to the absolute path of `lodash`:

```javascript
module.exports = {
  entry: 'src/index.js',
  dest: 'dist/bundle.js',
  format: 'es',
  plugins: [
    // Replace underscore with lodash...
    alias({
      'underscore': require.resolve('lodash'),
    }),

    nodeResolve(),
    commonjs(),
  ],
};
```
I'm not sure if I should close this issue, as we did not discuss about the main point (chain plugins `resolveId` function). I think, it would be better to use the node resolve plugin here as it can do interesting things (use the `module` field of `package.json` if it is defined for example). The downside is that, depending of the solution, it may break some existing plugins.

What do you think?

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.

**Comment by philipwalton** [comment]
I'd like to vote to re-open this.

I'm writing a plugin to work with [Import Maps](https://github.com/WICG/import-maps) and [built-in modules](https://github.com/tc39/proposal-javascript-standard-library/), but I imagine in most cases you'd want a standard module identifier (e.g. `std:kv-storage`) to map to a node module rather than a file in your application.

It seems wrong for my plugin to have to re-implement the node-resolve logic or even use it under the hood (since that ignores other plugins). I think the right thing to do would be to rename the identifier and let the remaining plugins resolve it.

**Comment by lukastaegert** [comment]
The current recommended approach is to use `this.resolveId` from the plugin context: https://rollupjs.org/guide/en#this-resolveid-importee-string-importer-string-string

Would this work for you?

**Comment by philipwalton** [comment]
Oh, nice. I didn't see that in the docs.

It seems to work for my use case. One concern I had though is it doesn't seem to ignore the current plugin, so if called from with a hook by the same name without changing the arguments, it'll lead to an infinite loop. (Not sure if there's a reason to ever do that though...)

**Comment by lukastaegert** [comment]
Actually that is something I plan on finding a solution for at some point as rollup-plugin-commonjs is suffering from the same problem. Maybe a parameter or a second context function
