### ISSUE TITLE
Could not resolve 'module/path/to/file'

### ISSUE THREAD

**Issue by jpablom** [rollup/rollup#1357]
Probably dumb question, but how can i import a specific file from modules? something like:
```js
import bar from 'bar';
import foo from 'bar/baz/foo.es6';

// do something with these
const b = new bar();
const f = b(foo);
```

when i  run rollup throws me:
`Could not resolve 'bar/baz/foo.es6' from 'path/to/main.js'`

**Update**
I use [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) but not sure how resolve this

**Update 2**
bar module
```
// file structure
node_modules
|-- bar
|   |-- package.json
|   |-- src
|       |-- baz
|           |-- foo.es6.js
|       |-- index.js
```
and the `package.json`
```js
{
  "name": "bar",
  "main": "src/index.js",
  ...
}
```
the next works on rollup: 
```js
import foo from 'bar/src/baz/foo.es6'
```
but with browserify works as:
```js
import foo from 'bar/baz/foo.es6'
```

maybe i missing something

**Comment by bfred-it** [comment]
I'm not sure of why browserify would work, the file `./baz/foo.es6.js` does not exist. How would it get to the `src` folder?

**Comment by Rich-Harris** [comment]
You might try using the `browser` option with node-resolve, and in theory it should use the same resolution logic as Browserify. But as @bfred-it says, there's no real reason to expect this to work. I'll close this but feel free to open a fresh issue with a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) if you think there's a bug here.

**Comment by taufik-nurrohman** [comment]
Just in case someone searching this issue on how to make this extension work with relative path. I just found [the solution](https://github.com/taufik-nurrohman/factory/blob/v1.0.7/index.mjs#L116-L132):

~~~ js
function resolve(file, origin) {
    // Your way to resolve local include path
}

function pathResolve(options) {
    return {
        resolveId: function(file, origin) {
            // Your local include path must either starts with `./` or `../`
            if (file.startsWith('./') || file.startsWith('../')) {
                // Return an absolute include path
                return resolve(file, origin);
            }
            return null; // Continue to the next plugins!
        }
    };
}
~~~

Here is how to combine it with `@rollup/plugin-node-resolve`:

~~~ js
import {nodeResolve} from '@rollup/plugin-node-resolve';

function pathResolve(options) { /* ... */ }

export default {
  // ...
  plugins: [pathResolve(), nodeResolve()]
};
~~~
