### ISSUE TITLE
 "warning.indexOf is not a function” rollup.js

### ISSUE THREAD

**Issue by AbinayaSubbiah** [rollup/rollup#1359]
Am getting below error message with rollup.config.js file

> � warning.indexOf is not a 

**rollup.config.js**

       import nodeResolve from 'rollup-plugin-node-resolve'
       import commonjs from 'rollup-plugin-commonjs';
      import uglify from 'rollup-plugin-uglify'

       //paths are relative to the execution path
     export default {
             entry: 'src/main-aot.js',
                 dest: 'aot/dist/build.js', // output a single application bundle
                 sourceMap: true,
                sourceMapFile: 'aot/dist/build.js.map',
             format: 'iife',
               onwarn: function (warning) {
                // Skip certain warnings

            // should intercept ... but doesn't in some rollup versions
           if (warning.code === 'THIS_IS_UNDEFINED') { return; }
            // intercepts in some rollup versions
                if (warning.indexOf("The 'this' keyword is equivalent to 'undefined'") > -1) { return; }
                if (warning.indexOf("Use of `eval` ") > -1) {
                return;
                      }
          // console.warn everything else
                   console.warn(warning.message);
               },
                 plugins: [
             nodeResolve({ jsnext: true, module: true }),
               commonjs({
              include: 'node_modules/rxjs/**',
          }),
            uglify()
                ]
              }
pacakge.json

> "rollup": "^0.41.6", "rollup-plugin-commonjs": "^8.0.2", "rollup-plugin-node-resolve": "^3.0.0", "rollup-plugin-uglify": "^1.0.1",

**Comment by Rich-Harris** [comment]
`warning` is not a string, therefore it does not have an `indexOf` method. The code you pasted into your config file pertains to an old version of Rollup. Replace it with this:

```diff
if (warning.code === 'THIS_IS_UNDEFINED') { return; }
+if (warning.code === 'EVAL') { return; }
-if (warning.indexOf("The 'this' keyword is equivalent to 'undefined'") > -1) { return; }
-if (warning.indexOf("Use of `eval` ") > -1) {
-            return;
-                  }
```

Really though, you'd be better off trying to remove the `eval`. Is it in your code, or a dependency's?
