### ISSUE TITLE
Taking too much time to build `build.js` file

### ISSUE THREAD

**Issue by AbinayaSubbiah** [rollup/rollup#1360]
am using rollup.config.js file for AOT build. am using .js file that used **eval** function. When i build its taking too much time to build dist file.

My config files are in below issue 

https://github.com/rollup/rollup/issues/1359
How to resolve this issue ?

**Comment by Rich-Harris** [comment]
Define 'too much time'? The presence or absence of `eval` shouldn't have an impact, beyond adding console output that can be suppressed by following the instructions in #1359. It sounds like you're just making a really big bundle?

**Comment by yairEO** [comment]
you can buy a better computer?

what is your computer model? Also, you think of a strategy to split the code to few small bundles and then concatenate them at the end, so when you are changing any file, rollup won't bundle EVERYTHING but only the section which includes that file. 

it takes time to setup some a split though...
