### ISSUE TITLE
Can dynamically referenced functions be manually excluded from tree shaking?

### ISSUE THREAD

**Issue by cool-Blue** [rollup/rollup#1361]
Thanks for the great tool, is there a way to explicitly exclude functions from tree shaking to allow for dynamic referencing?
For example, I'm using rollup-plugin-bundle-worker with this:

in webworker.js
```js
// how to exclude this from tree shaking so it can be referenced dynamically?
function route(message){
  self.postMessage(`${message} received in worker`)
}

export default function (e) {
  self[e.data.method](e.data.message);  // dynamic reference to route
}
```
The bundle does not include the route function so the webworker blob does not include it.

I can force it like this...
```js
function route(message){
  self.postMessage(`${message} received in worker`)
}

self.onmessage = function (e) {
  let r = route;
  self[e.data.method](e.data.message);
};
```
But I'm wondering if there is a more elegant way.

**Comment by olsonpm** [comment]
Please create a github or [repl](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuY29uc29sZS5sb2coJTIwY3ViZSglMjA1JTIwKSUyMCklM0IlMjAlMkYlMkYlMjAxMjUlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwaXNuJ3QlMjB1c2VkJTIwYW55d2hlcmUlMkMlMjBzbyU1Q24lMkYlMkYlMjBSb2xsdXAlMjBleGNsdWRlcyUyMGl0JTIwZnJvbSUyMHRoZSUyMGJ1bmRsZS4uLiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTNCJTVDbiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwZ2V0cyUyMGluY2x1ZGVkJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwcmV3cml0ZSUyMHRoaXMlMjBhcyUyMCU2MHNxdWFyZSglMjB4JTIwKSUyMColMjB4JTYwJTVDbiU1Q3QlMkYlMkYlMjBhbmQlMjBzZWUlMjB3aGF0JTIwaGFwcGVucyElNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) reproducing your issue.

**Comment by Rich-Harris** [comment]
What about doing this?

```js
export function route(message){
  self.postMessage(`${message} received in worker`)
}
```

That's how you'd 'tell' Rollup that `route` isn't supposed to be treeshaken. Or, even simpler and more self-explanatory:

```js
self.route = function route(message){
  self.postMessage(`${message} received in worker`)
}
```

**Comment by cool-Blue** [comment]
Ok, thanks for that.
1.  So the `export` statement will prevent tree shaking even if it's not consumed?
2.  Yes, the second method is perfect. It explains that it will be consumed inside the worker.  The first method is cool but semantically "incorrect" coz the function is consumed locally.

This is excellent. I knew ther must have been an elegant way to do it 😎

**Comment by Rich-Harris** [comment]
> So the `export` statement will prevent tree shaking even if it's not consumed?

If it's in the entry module, yes, because that's what defines the interface to the 'outside world'. It doesn't apply to non-entry modules though. The `self.route = ...` approach is better from that perspective.
