### ISSUE TITLE
Way to tell Rollup that certain functions on the global scope are pure?

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#1368]
Is there some way to influence what functions Rollup thinks are pure for the purposes of tree shaking? It looks like it considers all functions not declared in the scope of a module to be potentially impure, which is a good default, but sometimes we could do a bit better than that.

Backstory to try to stave off a potential XY problem - I have a wacky homemade build process for a personal project, and in it I'm turning ES6 `import`s for external dependencies into CommonJS `require`s. (I.e., I'm bundling my own code, but not any of the third-party code.) For different builds, I'm also replacing some strings by `true` or `false` so that certain operations can be skipped in different builds. The code that is inside `if (false)` is nicely shaken out, but the `require()` that the import turned into is not. I happen to not be using any modules where merely requiring them has any side-effects I care about. I'd like to take matters into my own hands here and tell Rollup that, no, the global `require` function has no side effects. Is this possible?

If the answer here ends up being "use the dang plugins that other people wrote and stop trying to do everything yourself", well, so be it.

Thanks!

**Comment by Conduitry** [comment]
I poked around at Rollup's source briefly, and there is indeed a big built in list of functions that are pure, but no apparent way to get at this at runtime. If I were to look into how to go about giving `callHasEffects` its own plugin hook, would that be something you'd be interested in, or is that too niche?

**Comment by Conduitry** [comment]
I've worked around this another way, so my immediate need for this is gone. This may or may not still be a useful thing to expose.

**Comment by kzc** [comment]
> I've worked around this another way

Could you describe your workaround?

**Comment by Conduitry** [comment]
It's really ugly :) Roughly, it involves:

- prepending an `import` statement to each file using a `transform()`
- creating a virtual module (using `resolveId()` and `load()`) that exports this function as a no-op, so it can be shaken out where possible
- doing a `transformBundle()` to tidy up and make the code actually use the proper external function, rather than the no-op

**Comment by nathancahill** [comment]
Also see #1293

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
