### ISSUE TITLE
Website-specific tree-shaking without bundling

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#1369]
I'd like to propose an alternative to code-splitting as discussed at https://github.com/rollup/rollup/issues/372

With HTTP2 adoption increasing quickly, there will be a reduced emphasis on download times and an increased emphasis on reducing parser times.

One of the main drivers behind tree-shaking is that websites typically use a small subset of frameworks such as JQuery or Semantic-UI. Instead of focusing on reducing the download time, however, I'd like to focus on reducing the parsing time of these resources.

The cost of downloading JS/CSS files happens once, but the cost of parsing them occurs on every page load.

I'd like to provide rollup with a list of entry points (e.g. `page1.js`, `page2.js`) for my website, and a list of dependencies used by the website (e.g. `jquery.js`, `semantic-ui.js`) and have rollup output a new version of each dependency after tree-shaking has taken place.

Meaning, for each module, strip out any code not referenced by any entry point. Output a separate module file for each dependency (don't bundle them).

Users can later bundle all dependencies together, if they so wish, but they can also skip this step and load these minimized dependencies directly (I plan to do the latter).

**Comment by bfred-it** [comment]
This can work if you have a handful of modules, but it cripples gzip. While HTTP/2 improves the download of multiple files, its still faster to download one file over the 100-modules an average project is made of (one file = one module)

This would be interesting to investigate, but it's almost the opposite of *rollup* since the core feature of rollup is to join modules; its output is always *one file*

Webpack would probably be a better place to suggest this.

**Comment by cowwoc** [comment]
@bfred-it 

I totally agree that it's faster to download one file than 100 different modules, but to reiterate my point: clients only download modules files once, but they parse them thousands of times (once per page load). If you bundle 100 modules into one, you're forcing clients to parse 100 modules on every page load even though most of them are never used.

I don't think this feature is far from code-splitting being requested over at https://github.com/rollup/rollup/issues/372

At minimum, code-splitting produces one shared module and one private module per page. I am taking it a step further and saying: if you're already producing multiple outputs, let's support multiple shared modules.

Imagine pages 1, 2, 3 depend on modules a, b, c. So let's bundle those into one shared module.
Now imagine pages 4, 5, 6 depend on modules d, e, f. So let's bundle those into a separate shared module.

Now, when users hit pages 1, 2, 3 they have to parse the smaller shared module as opposed to having to deal with an uber shared module that spans the entire website.

The industry trend is that download times are decreasing all the time. Either by way of algorithms (HTTP/2) or newer/faster hardware.

Unfortunately, there seems to be an opposite trend for parsing times. Modules are getting bigger at a faster rate than hardware is improving, and none of the client support any form of cached parsing.

I regret describing this issue as an alternative to code-splitting. It is more of a mutually-exclusive issue that can/should be implemented alongside it.

**Comment by bfred-it** [comment]
But again this doesn't seem to fit rollup's purpose: bundling files. You're asking for a tool to tree-shake existing modules/files and output them essentially _as is._ At most you could extract rollup's side-effect detection code and use it in a tool that does what you want, because that's the only part that would be used.

**Comment by ithinkihaveacat** [comment]
> none of the client support any form of cached parsing.

@cowwoc I think it's fairly minimal, and isn't always used, but [Chrome has supported caching parsed JS since 2015](https://blog.chromium.org/2015/03/new-javascript-techniques-for-rapid.html).

**Comment by Rich-Harris** [comment]
If Rollup reported which exports were used/unused in modules...

```js
rollup.rollup(opts).then(bundle => {
  assert.deepEqual(bundle.modules, [
    {
      id: '/path/to/main.js',
      dependencies: ['/path/to/foo.js'],
      exports: {}
    },
    {
      id: '/path/to/foo.js',
      dependencies: [],
      exports: {
        bar: { used: true },
        baz: { used: false }
      }
    }
  ]);
});
```

...would that enable you to build tooling that does what you propose?

**Comment by cowwoc** [comment]
Sorry but I don't have the know-how to build such tooling so I can't say one way or another.

**Comment by bfred-it** [comment]
@Rich-Harris would it make sense to extract the tree-shake parser to a separate module at that point? Or even share it with webpack. Why didn't webpack 2 use rollup's shaker? I remember reading about that.

**Comment by bfred-it** [comment]
I hope to see the tool you're proposing in the future, something that not only treeshakes but also brings all the files out of node_modules into a flat `dist` directory, but this is out scope for rollup. 

This really sounds like a job for webpack. I'm confident that it could already spit out multiple bundles with a little _(heh)_ configuration/plugin work.

https://github.com/rollup/rollup/issues/1184 will be open as the option Rich suggested.

**Comment by frank-dspeed** [comment]
@bfred-it @cowwoc https://github.com/stealjs/steal-tools

https://stealjs.com
- SystemJS forked Loader
- using rollup treeshaking
- does code splitting and speration into bundels

**Comment by fregante** [comment]
> I hope to see the tool you're proposing in the future, something that not only treeshakes but also brings all the files out of node_modules into a flat `dist` directory

Somebody made it 🎉  https://twitter.com/pikapkg/status/1214693540938145792

**Comment by lukastaegert** [comment]
Isn't this like Rollup's `preserveModules` option, which does exactly that–tree-shaking but keeping the original module structure?

**Comment by lukastaegert** [comment]
Ah then again I see it is Rollup under the hood 😉

**Comment by fregante** [comment]
> Isn't this like Rollup's `preserveModules` option,

You tell me, I didn't see `preserveModules` before 😅

**Comment by lukastaegert** [comment]
This issue has been closed too long, otherwise `preserveModules` would probably have been its resolution: https://rollupjs.org/guide/en/#preservemodules

This came after we introduced code-splitting and was actually driven forward by the Ember CLI team. Unfortunately, development there seems to have stalled since then.
