### ISSUE TITLE
Workaround for Chrome+sourcemap bug

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#1370]
Version 0.41.6

https://github.com/webpack/webpack/issues/2145#issuecomment-294361203 details problems mixing Webpack, sourcemaps and Chrome. I am seeing a similar behavior on rollup when attempting to use rollup-plugin-uglify with sourcemaps enabled. I am unable to set breakpoints on some lines that are getting executed (some of them contain `console.log()` which is how I know they are running).

**UPDATE**: If I disable uglify, breakpoints are still screwed up. If I disable sourcemaps, I am able to set breakpoints on these lines just fine.

**Comment by Rich-Harris** [comment]
Thanks. Any chance you can [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?
