### ISSUE TITLE
Possible to access existing AST of a module?

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#1371]
Is there a way to access the AST that Rollup is already producing with Acorn for each module? Or is my best bet to parse the code myself with my own copy of Acorn and return `{ code, ast }` from a `load` plugin?

I'm trying to implement a non-standard build process, and I'd like to be able to cache the parsed versions of modules as well as their code, to speed up builds. I don't think I can use the built-in `cache` mechanism for incremental builds, because I want to be able to cache certain modules even if the overall bundling fails.

**Comment by kzc** [comment]
Although Rollup uses Acorn to parse and can consume ESTree AST from plugins, it does not maintain an AST of its output. Instead it uses `magic-string` to produce the code in text form. If you wish to process Rollup output you'd have to parse it again.

See: https://github.com/rollup/rollup/issues/782 
and https://gitlab.com/Rich-Harris/buble/issues/68

**Comment by Conduitry** [comment]
I don't think I need an AST of the output for my purposes though. I just want an AST of each input module in its initially parsed form. I'm fine with re-`magic-string`-ing each module each build - that's going to be unavoidable anyway, as different identifiers might need to be deconflicted between modules on different builds.

What I'm trying to do seems similar to the `cache` mechanism, but you're only able to get the list of modules to pass to the next invocation of Rollup if this invocation succeeded. So my idea was to have a `load()` plugin that returns `{ code, ast }` if this module is in a cache, but there does not seem to be a way to access Rollup's initial AST for a module. It's generated in https://github.com/rollup/rollup/blob/master/src/Module.js but the only way it looks like it's exposed is through a successful bundle.

**Comment by Rich-Harris** [comment]
You'd need to create an AST with Acorn (or anything compatible) — I believe returning a `{code, ast}` object from a `load` plugin should Just Work™.

**Comment by guybedford** [comment]
This workflow should be helped by https://github.com/rollup/rollup/pull/1945.

**Comment by adrianheine** [comment]
Passing the AST could potentially improve performance, though :)

**Comment by guybedford** [comment]
@adrianheine do you mean across cached builds here? If the plugin did the parsing then returned the ast that seems pretty optimal?
