### ISSUE TITLE
Bundle differs when created with and without cache

### ISSUE THREAD

**Issue by Finesse** [rollup/rollup#1372]
There is a bug in the [Rollup](https://github.com/rollup/rollup) or the [Rollup CommonJS plugin](https://github.com/rollup/rollup-plugin-commonjs). A bundled code semantically differs when created without cache and with cache from the previous bundling. The bug appears in this case:

* The ES5-style module is imported in ES5-style, i.e. file with `module.exports = ...` is imported by `require ...`.

Here is the demo repository with more information: https://github.com/FinesseRus/rollup-bug-demo

This bug make no harm in most cases. It makes troubles when a false value is exported using `module.exports = false;` inside a ES5 node package because the exported value turns to `Object`.

I faced this bug when tried to import the `Array#iterator` polyfill from [core-js](https://github.com/zloirock/core-js/). The polyfill worked if the app was bundled for the first time and didn't work when the app was rebundled. It took a lot of time to locate the reason.

P.S. I am not sure where to post this issue, here or to the [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) repository, because it affects both repositories. Sorry if I made a mistake.

**Comment by FinesseRus** [comment]
Still actual for Rollup 0.50.0 and rollup-plugin-commonjs 8.2.1

**Comment by FinesseRus** [comment]
A bug demo from @StreetStrider: [on GitHub](https://github.com/StreetStrider/rollup-cache-issue), [archive](https://github.com/rollup/rollup/files/1294281/rollup-cache-issue-master.zip).

**Comment by StreetStrider** [comment]
@Rich-Harris, hello. I review this issue with newest versions of rollup's packages and issue is still present. If you have time, could you look at this or at least give some tips or directions to solve that? I was forced to turn off cache for this months and my dev process slows when I deal with big bundles. It would be awesome if the issue clears up and I can turn cache on again.

**Comment by osaton** [comment]
I might have this same problem with `chai` library becoming `undefined` on subsequent builds.

This is how this can be reproduced:

### Source files

Build task:
``` js 
const rollup = require('rollup'); // v0.50
const node = require('rollup-plugin-node-resolve'); // 3.0.0
const commonjs = require('rollup-plugin-commonjs'); // v8.2.6
let bundle;

/* ... */

bundle = await rollup.rollup({
    input: './test/api.js',
    cache: bundle,
    plugins: [
      node({
        module: true,
        main: true,
        browser: true
      }),
      commonjs({
        include: 'node_modules/**'
      })
    ]
  });

/* ... */

```
api.js:
``` js
import chai from 'chai'; // v4.1.2
import axios from 'axios';
console.log(chai, axios);
```

`chai` works correctly for the first bundling and then becomes `undefined` on subsequent bundles. `axios` works as expected in subsequent builds too.

### Bundled file
Interesting parts from bundled js

First bundle:
``` js
// Line 10626
var chai$2 = createCommonjsModule(function (module, exports) {

// Line 10721
var chai = chai$2;
```

Subsequent bundle:
``` js
// Line 2182
var chai$5 = ( chai$4 && chai$2 ) || chai$4; // chai$4 & chai$2 still undefined

// Line 10524
var chai$2 = createCommonjsModule(function (module, exports) { ... }

// Line 10636
var chai = chai$5; // assigning undefined
```

**Comment by osaton** [comment]
@FinesseRus @StreetStrider I might have figured this one out.

In `index.js` try moving the config outside of `makeBundle` function, so that plugins only initiate once.

``` js
const rollup = require('rollup');
const rollupCommonJS = require('rollup-plugin-commonjs');

let cache = null;

let rollupConfig = {
	input: 'src/app.js',
	context: 'window',
	plugins: [rollupCommonJS()]
}

function makeBundle(outputName)
{
	return rollup.rollup(rollupConfig)
		.then(bundle => {
			rollupConfig.cache = bundle;

			return bundle.write({
				format: 'iife',
				file: 'dist/' + outputName + '.js',
				name: 'test'
			});
		})
		.then(() => {
			console.log(outputName + '.js is ready');
		});
}

makeBundle('bundle-first')
	.then(() => makeBundle('bundle-from-cache'))
	.catch(error => console.error(error));
```

I was having cache problems too and it turns out this was the reason for me as well.

**Comment by StreetStrider** [comment]
@osaton thanks, I'll check that. The bug is still bug though.

**Comment by StreetStrider** [comment]
@osaton's workaround do the trick. The only difference now is sourcemap comment: `//# sourceMappingURL=thunk.js.map`. All code's names are good.

**Comment by adrianheine** [comment]
I used a somewhat simpler test case and found that `rollup-plugin-commonjs` has a set called `commonjsModules` as internal state that stores which module ids refer to commonjs modules that were successfully handled by the plugin. That is obviously empty for a fresh instance, and thus the plugin generates different code if a fresh instance is ran on a cache.

**Comment by FinesseRus** [comment]
@osaton It works, thank you!

It is enough to move just the plugin instance:

```javascript
const rollup = require('rollup');
const rollupCommonJS = require('rollup-plugin-commonjs');

let cache = null;
const rollupCommonJSPlugin = rollupCommonJS();

function makeBundle(outputName)
{
	return rollup.rollup({
			input: 'src/app.js',
			cache: cache,
			context: 'window',
			plugins: [rollupCommonJSPlugin]
		})
		.then(bundle => {
			cache = bundle;

			return bundle.write({
				format: 'iife',
				file: 'dist/' + outputName + '.js',
				name: 'test'
			});
		})
		.then(() => {
			console.log(outputName + '.js is ready');
		});
}

makeBundle('bundle-first')
	.then(() => makeBundle('bundle-from-cache'))
	.catch(error => console.error(error));
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
