### ISSUE TITLE
Rollup mangles class names, breaking IDE code-complete

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#1378]
Version 0.41.6
Webstorm 2017.1.1 (IDE)

1. Every time a module imports a class and re-exports it, rollup mangles the name of the exported class. I am expecting the name to remain unchanged.
2. [Testcase](https://rollupjs.org/repl?version=0.41.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMFBhcmVudCUyMGZyb20lMjAlNUMlMjIuJTJGUGFyZW50JTVDJTIyJTNCJTVDbiU1Q24lMkYqKiU1Q24lMjAqJTIwJTQwcmV0dXJuJTIwJTdCUGFyZW50JTdEJTIwYSUyMFBhcmVudCUyMGluc3RhbmNlJTVDbiUyMColMkYlNUNuZnVuY3Rpb24lMjBjcmVhdGVQYXJlbnQoKSU1Q24lN0IlNUNuJTIwJTIwcmV0dXJuJTIwbmV3JTIwUGFyZW50KCklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY3JlYXRlUGFyZW50JTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMlBhcmVudC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBQYXJlbnQlMjBmcm9tJTIwJTVDJTIyLiUyRmludGVybmFsJTJGUGFyZW50JTVDJTIyJTNCJTVDbmltcG9ydCUyMENoaWxkJTIwZnJvbSUyMCU1QyUyMi4lMkZDaGlsZCU1QyUyMiUzQiU1Q24lNUNuUGFyZW50LnByb3RvdHlwZS5jaGlsZE1ldGhvZCUyMCUzRCUyMGZ1bmN0aW9uKCklNUNuJTdCJTVDbiU1Q3RyZXR1cm4lMjBuZXclMjBDaGlsZCgpJTNCJTVDbiU3RCUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMFBhcmVudCUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJpbnRlcm5hbCUyRlBhcmVudC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYqKiU1Q24lMjAqJTIwJTQwY2xhc3MlNUNuJTIwKiUyRiU1Q25jbGFzcyUyMFBhcmVudCU1Q24lN0IlNUNuJTVDdCUyRioqJTVDbiU1Q3QlMjAqJTIwJTQwY29uc3RydWN0b3IlNUNuJTVDdCUyMColMkYlNUNuJTVDdGNvbnN0cnVjdG9yKCklNUNuJTVDdCU3QiU1Q24lNUN0JTdEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMFBhcmVudCUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJDaGlsZC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJjbGFzcyUyMENoaWxkJTVDbiU3QiU1Q24lMjAlMjAlMjAlMjBjaGlsZE1ldGhvZCgpJTVDbiUyMCUyMCUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZyglNUMlMjJjaGlsZE1ldGhvZCU1QyUyMiklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMENoaWxkJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
3. The main entry point is supposed to return a function `createParent()` that returns an instance of type `Parent`.
4. Unfortunately, rollup mangles the class name of `Parent` into `Parent$1` so when the IDE parses jsdoc it sees that `createParent()` returns `Parent` but it cannot find `class Parent` anywhere. As a result, code-complete does not show `Parent.childMethod()`.
5. I am not aware of any workaround for this issue. I am forced to use this design to deal with circular dependencies between modules and these cannot be removed.

**Comment by kzc** [comment]
Workaround - instead of 
```
export default Parent;
```
use
```
export { Parent as default };
```

**Comment by cowwoc** [comment]
Thanks for the workaround! I really appreciate it.

1. So is this a confirmed bug?
2. Out of curiosity, what is the difference between the two syntaxes? Is this a rollup implementation detail, or are they conceptually different according to the ES6 specification?

**Comment by kzc** [comment]
I don't know if it's a bug, nor am I very well versed on what the ES6 spec says on the matter.

**Comment by kzc** [comment]
It appears to be ES2015 spec compliant. 

Your example is re-exporting a live binding which is why it requires the `export { Parent as default }` syntax.

See:

* http://stackoverflow.com/questions/39276608/is-there-a-difference-between-export-default-x-and-export-x-as-default/39277065#39277065

* Default import/export is not treated as live binding #1078

* [BREAKING] fix behaviour of export { foo as default } #1166

**Comment by cowwoc** [comment]
FYI, I published a related bug report for Babel: https://github.com/babel/babel/issues/5660

**Comment by cowwoc** [comment]
@kzc Thanks for the references. Rollup's behavior makes a lot more sense now.

**Comment by bfred-it** [comment]
Was this also solved by https://youtrack.jetbrains.com/issue/WEB-26724?

**Comment by cowwoc** [comment]
@bfred-it yes
