### ISSUE TITLE
How do I figure out the file that caused a parsing error?

### ISSUE THREAD

**Issue by matthew-dean** [rollup/rollup#1380]
I'm getting an error like this:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected token (1:451)
    at error ([...]/node_modules/rollup/dist/rollup.js:170:12)
    at [...]/node_modules/rollup/dist/rollup.js:8936:6

```
Presumably, Rollup (or a plugin) is choking on a file, but it doesn't tell me what file it was processing. Is there a way to turn on logging for each file processed?

**Comment by matthew-dean** [comment]
I finally found it by using the Rollup eslint plugin, but might be nice to have a logger.

**Comment by gsouf** [comment]
Hi @matthew-dean 

I'm running into the same issue. Can you give an example of how you could get the file that failled to parse, please.

**Comment by Rich-Harris** [comment]
@matthew-dean sorry for non-response — how are you using Rollup? If you're using it via the CLI (e.g. with a config file) then it will print the filename (and location/frame if possible). If you're using it programmatically then the error object should have the plugin name, filename and location info as properties of the error object.

**Comment by matthew-dean** [comment]
> If you're using it programmatically then the error object should have the plugin name, filename and location info as properties of the error object.

It took me a while; I didn't realize such an error object was available. I had to google a bit before inserting something like:
```
.on('error', function(e){ console.log(e)})
```
...after the initial Rollup call. Rollup may assume that users will know that Rollup is a particular type of object (a Node.js stream?) that emits this error event, but it wasn't automatically intuitive to me. Maybe you can add this to documentation? Seems like it should also be part of even simple examples.

The error output outputs all the reference lines on one line (do they need to be further formatted for the console?), but at least it was more useful. Thanks!

**Comment by matthew-dean** [comment]
Nuts, I realized that I was actually using "rollup-stream" in my gulpfile, not "rollup". DERP.
