### ISSUE TITLE
Cant load amd module?

### ISSUE THREAD

**Issue by AbinayaSubbiah** [rollup/rollup#1382]
i am using ej.button.min.js from below link when am using this file i cant able to get core.min.js file which is imported in button.min.js file
https://github.com/syncfusion/JavaScript-Widgets/tree/master/Scripts/ej/web
m creating sample angular 2 AOT using ejbutton

`(function(n){typeof define=="function"&&define.amd?define(["./../common/ej.core.min"],n):n()`

**Comment by olsonpm** [comment]
Please create a reproduction of your issue either using rollup's [repl](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuY29uc29sZS5sb2coJTIwY3ViZSglMjA1JTIwKSUyMCklM0IlMjAlMkYlMkYlMjAxMjUlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwaXNuJ3QlMjB1c2VkJTIwYW55d2hlcmUlMkMlMjBzbyU1Q24lMkYlMkYlMjBSb2xsdXAlMjBleGNsdWRlcyUyMGl0JTIwZnJvbSUyMHRoZSUyMGJ1bmRsZS4uLiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTNCJTVDbiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwZ2V0cyUyMGluY2x1ZGVkJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwcmV3cml0ZSUyMHRoaXMlMjBhcyUyMCU2MHNxdWFyZSglMjB4JTIwKSUyMColMjB4JTYwJTVDbiU1Q3QlMkYlMkYlMjBhbmQlMjBzZWUlMjB3aGF0JTIwaGFwcGVucyElNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) or an example github repo.

**Comment by Rich-Harris** [comment]
AMD is a dog of a format when it comes to static analysis unfortunately — simple AMD modules work via rollup-plugin-amd, but files that check for the existence of `define` and the truthiness of `define.amd` are rather more difficult. 

I don't know if we're going to be able to get this to work, to be honest — Rollup is designed to work with JavaScript modules, and can only handle legacy formats if certain conditions are met. It would be possible *in theory* for a plugin like rollup-plugin-amd to transform files like these ones, but someone would have to build it.

**Comment by emilos** [comment]
I think that the format described at top is a variation of the umd format, so maybe it should be rather converted by something like `rollup-plugin-umd` that is capable of dropping few variations. I believe that this might be out of scope for an amd converter as it would need to not only drop the amd definition, but the whole umd, which contains cjs etc.
