### ISSUE TITLE
`export default async function name(){}` not working

### ISSUE THREAD

**Issue by nickschot** [rollup/rollup#1383]
Rollup does not currently seem to support named async function exports like `export default async function myFunction(){}`. MDN is not fully clear on the issue as it names named functions, function* and classes as possible exports, but I *think* it should also work when the async keyword is used.

The problem (of course) only occurs when using native async/await in node v7.6.0+ (or v7.x.x w/ harmony flag). Async/await exports transpiled to generators as created by babel's async-to-generator transform work fine (as expected).

Example repository w/ simple async function in `lib/util`: https://github.com/nickschot/rollup-named-async-func-example

Relevant MDN: https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export

**Comment by Conduitry** [comment]
Your example repo is using Rollup 0.37. As of that version, Acorn was being told to parse as ES7/ES2016 (which does not support async/await). In [Rollup 0.38.1](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0381), this changed to ES8/ES2017 (which does include async/await). Either upgrade your version of Rollup, or pass a config override of `acorn: { ecmaVersion: 8 }` to Rollup to have it tell Acorn to parse as ES2017.

**Comment by nickschot** [comment]
@Conduitry Oops! That's a mistake on my part in the example repo. I first encountered the error w/ Rollup 0.41.4. Will update the example repo and test if it still occurs there too.

**Comment by Rich-Harris** [comment]
Yep, this works out of the box in more recent versions so I'll close this issue. Holler if you still have problems with it.
