### ISSUE TITLE
Import optional dependency?

### ISSUE THREAD

**Issue by FezVrasta** [rollup/rollup#1385]
Hi, I'm trying to use Rollup to import a dependency that could, or could not, be available.

```
import Dependency from 'dependency';

// 'dependency' is marked as `external` in the Rollup config.
```

When I bundle this code to UMD I get this code:

```
Dependency = 'default' in Dependency ? Dependency['default'] : Dependency;
```

That will fail on `'default' in Dependency` if the dependency isn't available in the global scope.

How can I tell Rollup to not fail if the dependency isn't available?

**Comment by olsonpm** [comment]
Because imports are static, [this doesn't seem to be possible](http://stackoverflow.com/questions/36367532/how-can-i-conditionally-import-an-es6-module)

**Comment by marvinhagemeister** [comment]
The [dynamic imports spec](https://github.com/tc39/proposal-dynamic-import) is still at `stage 3` and not yet supported by rollup. If you're writing a node app you could fall back to conditional `require` statements.

**Comment by FezVrasta** [comment]
I'm not actually want to dynamically import a module, I'd simply like to don't crash the app if the modules isn't available.

**Comment by olsonpm** [comment]
which would be dynamically importing it.

**Comment by FezVrasta** [comment]
Dynamic import is more like calling import on runtime AFAIK

**Comment by olsonpm** [comment]
What we're saying, is it's impossible to turn the below into an optional dependency without first translating it into a non-es format.

```js
import optionalDependency from 'optional-dependency';
```

The feature you're asking for would be something like an option `optional-external-non-es-format-dependencies`, which doesn't seem like it fits the rollup use-case.

**Comment by olsonpm** [comment]
So one assumption I was making is that you were the one writing the code.  If that's the case then my response would be to use another tool such as webpack or browserify.  They are not married to import/export statements and will likely better fit your use-case moving forward.  However I just came across a library with an optional dependency

```js
var optionalDep;
try { optionalDep = require('some-optional-dep'); }
catch(e) {}
```

I don't control this library and so this prevents me from bundling.  If I want to stick to rollup my only two options are to create a workaround in rollup or to fork the library containing the optional dependency and rewrite the logic (btw, according to [this issue](https://github.com/rollup/rollup-plugin-commonjs/issues/89) a workaround isn't known yet).  Neither are good options.  I'm only using rollup for learning purposes atm, but it still strikes me as a use-case that should be addressed considering it causes a potential hardstop.

**Comment by olsonpm** [comment]
I'm looking into the module evaluation process and found this [relevant portion of the spec](https://tc39.github.io/ecma262/#sec-hostresolveimportedmodule):

> If a Module Record corresponding to the pair referencingModule, specifier does not exist or cannot be created, an exception must be thrown.

which, if I'm understanding the spec correctly, is what happens with `require` calls as well.  This behavior is why require calls must be placed in a try/catch in order for them to be optional.

**Comment by marvinhagemeister** [comment]
@olsonpm That's a great find! Kudos to you, didn't know about the try/catch thing 👍

**Comment by sloria** [comment]
@olsonpm Thanks for looking into a workaround. I am trying to do the `try/catch` with a `require()` call, but `require` doesn't seem to be supported out of the box in rollup. Has anybody got this working?

**Comment by olsonpm** [comment]
I'm actually not looking into a workaround - was just trying to understand the issue better.  Unfortunately the issue you're hitting is [this rollup-plugin-commonjs issue](https://github.com/rollup/rollup-plugin-commonjs/issues/89), and there's no workaround atm.

In short, Rich's comment is where the issue stands

>  because imports have to be at the top level – there's no way to turn a require inside a try-catch into an equivalent import. I think this is just a fundamental difference between CJS and ES. Even if there were some way to keep the final require call in the same place as the original in the case of CJS bundles, it doesn't work for AMD, UMD etc.<br><br>I don't really have any good ideas for this off the top of my head.

**Comment by sloria** [comment]
Ah, ok, thanks for the clarification. I also recall optional requires being handled in webpack.  Would love to see support for this in rollup.

**Comment by olsonpm** [comment]
Just found the time to learn webpack's approach.  They handle it in a sensible way:

```js
let optionalDep = "default value for optional dep";

try {
  optionalDep = require("./doesn't exist");
} catch(e) {
  console.error(e);
}

console.log(optionalDep);
```

Which bundles to
```js
let optionalDep = "default value for optional dep";

try {
  optionalDep = __webpack_require__(!(function webpackMissingModule() {
    var e = new Error("Cannot find module \"./doesn't exist\"");
    e.code = 'MODULE_NOT_FOUND';
    throw e;
  }()));
  console.error(e);
}

console.log(optionalDep);
```

And when executed in a browser, prints:
```js
bundle.js:89 Error: Cannot find module "./doesn't exist"
    at webpackMissingModule (bundle.js:87)
    at Object.<anonymous> (bundle.js:87)
    at __webpack_require__ (bundle.js:20)
    at module.exports (bundle.js:66)
    at bundle.js:69

default value for optional dep
```

Rollup could adopt this approach, they just have to give up adherence to import/export equivalence.

**Comment by Rich-Harris** [comment]
Webpack isn't really solving the issue by doing that — there's still no way to actually require the optional dependency.

For a CommonJS bundle you could use the `ignore` option in rollup-plugin-commonjs. For UMD bundles, I suspect the best solution would be to make the interop check more forgiving:

```diff
-Dependency = 'default' in Dependency ? Dependency['default'] : Dependency;
+Dependency = (Dependency && 'default' in Dependency) ? Dependency['default'] : Dependency;
```

**Comment by FezVrasta** [comment]
This change is what I'd need

**Comment by olsonpm** [comment]
@Rich-Harris

> there's still no way to actually require the optional dependency

At runtime you mean?  Of course not, but there is a way to include it in the bundle when rollup can find it, and cause the code to throw an error when it doesn't (like webpack).  This is how require behaves, and how the specs say 'import' should behave.

**Comment by bfred-it** [comment]
@Rich-Harris that'd still fail when `Dependency` is undefined. Did you mean this?

```patch
-Dependency = 'default' in Dependency ? Dependency['default'] : Dependency;
+Dependency = (typeof Dependency !== 'undefined' && 'default' in Dependency) ? Dependency['default'] : Dependency;
```

**Comment by paulfalgout** [comment]
I think this is resolved in 0.43

**Comment by bfred-it** [comment]
@FezVrasta can you confirm that 0.43 works?

**Comment by FezVrasta** [comment]
Going to try this ASAP

**Comment by FezVrasta** [comment]
Can confirm it works! Cool

**Comment by bfred-it** [comment]
Thanks fot eh report, @FezVrasta

**Comment by FezVrasta** [comment]
I didn't actually realized that this would have worked only for UMD bundles...

Now I'm not that sure it's a good idea 😓

**Comment by bepvte** [comment]
This bug still affects me with CJS modules, e.g.
```js
try {
  nonexistant = require('nonexistant')
} catch {}
```
