### ISSUE TITLE
Bad generated code (missing import * as x)

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#139]
This is a reproduction case from a real failing...

entry.js
```
import a from './foo';

a();
```

foo.js
```
import * as a from './bar';

function b() {
  console.log(a.foo, a.bar);
}

export default b;
```

bar.js
```
function foo() {

}
function bar() {

}
export { foo, bar };
```

**Comment by lukeapage** [comment]
Hrmm I cannot reproduce it but I've just found that in my original source, the following kind of output

```
var a = {
    get foo () { return foo; },
    get bar() { return bar; }
  }

function x() {
   a.foo(); // correct
}

function y() {
  b.foo(); // incorrect! because import * as __ is a different name in two files it has not aliased them to be the same name
}
```

**Comment by Victorystick** [comment]
Hmm... When I bundle your first example I get:
```js
function foo () {}

function bar () {}

function b () {
	console.log( a.foo, a.bar );
}

b();
```
which is obviously wrong. It'll ReferenceError with `a` undefined. I'm working on a fix for it.

**Comment by lukeapage** [comment]
yes that's the problem with my example.. I just can't reproduce the exact problem I'm getting with my original source. But I am hoping that fixing the above will fix my original source problem too...
