### ISSUE TITLE
Trouble building with htmlparser2

### ISSUE THREAD

**Issue by adampash** [rollup/rollup#1390]
I'm trying to build a web version of a library that uses [`htmlparser2`](https://www.npmjs.com/package/htmlparser2). `htmlparser2` should work in the browser as well as in node (I've verified this in webpack), but I'm having a lot of trouble getting a build to work with rollup. I've reproduced the problem in [this repo](https://github.com/adampash/rollup-htmlparser2/tree/master). 

When I build, the build succeeds, but with this output in the console:

```bash
⚠️   'default' is not exported by 'node_modules/buffer-es6/index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/Users/aop/code/tmp/rollup-htmlparser2/node_modules/buffer-es6/index.js (1:130)
1: import * as index from "/Users/aop/code/tmp/rollup-htmlparser2/node_modules/buffer-es6/index.js"; export default ( index && index['default'] ) || index;
```

If I try using the generated bundle on a web page, I get the following error:

```javascript
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at inherits (inherits_browser.js:5)
    at Parser.js:123
    at index.js:5
```

(If you clone [the repo](https://github.com/adampash/rollup-htmlparser2/tree/master), you can reproduce this by opening `index.html`.)

Any clue what I'm doing wrong here?

Thanks!

**Comment by olsonpm** [comment]
As for the warning, seems you are encountering [this issue](https://github.com/rollup/rollup-plugin-commonjs/issues/198).

The error in your browser is unrelated to the warning, and after glancing at the error seems to suggest an issue related to native node modules and the node version.

Not sure when the 'events' api changed, but older node versions expected EventEmitter to be retrieved via `var EventEmitter = require('events').EventEmitter`.  Newer versions just return the EventEmitter from the module directly - e.g. `var EventEmitter = require('events')`.  The error in the browser shows the former code, even though the property EventEmitter is undefined.

Not sure why it works with webpack, but I'm uninterested in looking further.

**Comment by thisconnect** [comment]
`htmlparser2` does funny module exports i.e. `module.exports[name] = value;` https://github.com/fb55/htmlparser2/blob/2e6c0e0f3f79cc268efc59e73b25d917c07d8493/lib/index.js#L6

have you considered https://www.npmjs.com/package/parse5? That's the one used by jsdom

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
