### ISSUE TITLE
Import shadowed within a function effects invalid code

### ISSUE THREAD

**Issue by cartant** [rollup/rollup#1391]
There is a http://rollupjs.org reproduction [here](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGUlMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmUlNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc29tZXRoaW5nKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdHJ5JTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKGUpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyMGNhdGNoJTIwKGUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbnNvbGUuZXJyb3IoZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGUlMjAlM0QlMjAyLjcxODI4MTgyODQlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIydW1kJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=). Essentially, this code:

```js
import { e } from "./e";

export function something() {
    try {
        console.log(e);
    } catch (e) { // the catch identifier shadows the import
        console.error(e);
    }
}
```

results in a bundle that contains:

```js
export function something() {
    try {
        console.log(e);
    } catch (e) {
        console.error(e$$1);
    }
}
```

Where `e$$1` is not defined.

My quick search through the repo for issues found [this](https://github.com/rollup/rollup/pull/155) PR that included a test for a shadowed import that used a wildcard. I would have expected that named imports could be similarly shadowed.

**Comment by olsonpm** [comment]
Funny, if you change

```js
// from
import { e } from 'e';

// to
import * as e from 'e';
```

The result shows the bug more clearly
```js
const e = 2.7182818284;

var e$1 = Object.freeze({
	e: e
});

function something() {
    try {
        console.log(e$1);
    } catch (e$1) {
        console.error(e$$1);
    }
}
```

Worthy of a PR.
