### ISSUE TITLE
Export module to two global properties (umd format)

### ISSUE THREAD

**Issue by blikblum** [rollup/rollup#1393]
MarionetteJS (https://github.com/marionettejs/backbone.marionette) uses umd format and exports to two global variables: `Marionette` and `Mn`.

To accomplish this it sets the rollup moduleName option to `'Marionette = global[\'Mn\']'` ( https://github.com/marionettejs/backbone.marionette/blob/master/gulp/build.js#L23 ).

But with recent rollup version this hack does not work probably due to https://github.com/rollup/rollup/pull/1144

Is there another way to set two global properties using umd format?

Is doable to implement an option to never use array notation to access global properties?

The rollup version used by MarionetteJS is 0.36.3

**Comment by olsonpm** [comment]
The correct solution would be to allow an array to be passed to [moduleName](https://github.com/rollup/rollup/wiki/JavaScript-API#modulename).  A hack would be to add a [footer](https://github.com/rollup/rollup/wiki/JavaScript-API#bannerfooter) to your rollup.config.js

```js
footer: 'global.mn = global.marionette'
```

**Comment by olsonpm** [comment]
Ha - thanks to @thisconnect for showing me that [Rich recommends](https://github.com/rollup/rollup/issues/553#issuecomment-202166713) the footer hack

**Comment by blikblum** [comment]
The footer will not work for umd format, the one used by Marionette, see output below:
```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('backbone'), require('underscore'), require('backbone.radio')) :
	typeof define === 'function' && define.amd ? define(['backbone', 'underscore', 'backbone.radio'], factory) :
	(global.Marionette = factory(global.Backbone,global._,global.Backbone.Radio));
}(this, (function (Backbone,_,Radio) { 

'use strict';
[..]
return Marionette;
})));
window.Mn = window.Marionette;
```

When using AMD or CommonJS `window.Marionette` will not be defined

**Comment by olsonpm** [comment]
Which is expected.  If you're trying to replicate the umd output of the [marionette dist code](https://marionettejs.com/downloads/backbone.marionette.js), amd and cjs will continue to work as expected.  The global object is the only one you have to make modifications for.

**Comment by blikblum** [comment]
Thanks for the insight. Closing
