### ISSUE TITLE
Run from JS file

### ISSUE THREAD

**Issue by XtremePlayzCODE** [rollup/rollup#1394]
I'm making a project that uses Rollup as a build script and I was wondering if I could run Rollup from within the script instead of in the shell to make everything much easier.  Is this possible and how would you do it?

**Comment by tivac** [comment]
https://github.com/rollup/rollup/wiki/JavaScript-API describes the JS API. It's definitely possible, I use the JS API directly in https://github.com/tivac/crucible

**Comment by XtremePlayzCODE** [comment]
Oh, thank you very much!
