### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by droooney** [rollup/rollup#1398]
I have a question: what ES6 features do I need to provide a polyfill for in order to use Rollup in browser? I've found `Promise` and `Map` so far.

**Comment by olsonpm** [comment]
I would start by looking at how rollup does it:

https://github.com/rollup/rollupjs.org

**Comment by Rich-Harris** [comment]
You'll need `Set` as well. I can't *think* of anything else off the top of my head.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
