### ISSUE TITLE
Comments missing leading newlines

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#14]
See https://github.com/rollup/rollup/pull/9#issuecomment-106994895. On a similar note, consecutive statements from different modules should perhaps be separated with an extra newline for readability's sake

**Comment by mbostock** [comment]
FYI, this is still causing malformed output on my end. I’ll see if I can make a simple example to demonstrate.

**Comment by mbostock** [comment]
(Edit: I’m dumb.)
