### ISSUE TITLE
UMD builds with externals expect $1-appended globals

### ISSUE THREAD

**Issue by mattdsteele** [rollup/rollup#1400]
Rollup config:
```javascript
export default {
  entry: './app.js',
  format: 'umd',
  moduleName: 'app',
  external: ['globalModule'],
  globals: {
    globalModule: 'globalModule',
  }
}
```

app.js:
```javascript
import './foo';
import globalModule from 'globalModule';
globalModule.doSomething();
```

foo.js:
```javascript
globalModule.doSomethingElse();
export default 42;
```

Outputs:
```javascript
(function (global, factory) {
        typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('globalModule')) :
        typeof define === 'function' && define.amd ? define(['globalModule'], factory) :
        (factory(global.globalModule));
}(this, (function (globalModule$1) { 'use strict';

globalModule$1 = 'default' in globalModule$1 ? globalModule$1['default'] : globalModule$1;

globalModule.doSomethingElse();

globalModule$1.doSomething();

})));
```

This fails when loading in a browser, as it expects `globalModule$1` to be defined. I would have expected it to use `globalModule` instead.

This only seems to occur with `umd` and `amd` builds. Other formats import from `globalModule` properly.

*My use case*: I'm bundling a project and am calling `import angular from 'angular'`, but I don't want to include angular in the bundle; it should be available as a global. I also import `angular-messages`, and *do* want to include it in the bundle. `angular-messages` references `angular` as a global, which causes the scenario as reproduced above.

I can workaround this by removing all `import angular from 'angular'` in my code and only referencing it as a global, but I'd prefer to use import statements.

Seems *maybe* related to #343 but I'm not sure it's the exact same scenario.

**Comment by droooney** [comment]
Perhaps you might be interested in [this plugin](https://github.com/rollup/rollup-plugin-inject).

Create somewhere a file `angular.js` with

```js
export default window.angular;
```

and reference it as a global angular variable.

**Comment by olsonpm** [comment]
Why does foo.js not import globalModule?  Works fine when I make that modification.

**Comment by mattdsteele** [comment]
@olsonpm That'd be ideal, but in my particular case `foo.js` is actually the `angular-messages` module, which is a UMD module that references `angular` as a global variable.

@droooney I'll give the plugin a shot and report back.

**Comment by olsonpm** [comment]
Yeah this would be the job of a plugin then.  Ramda treats it as an undefined variable - as external only considers imports of "external" (i.e. not bundled) modules.

**Comment by Rich-Harris** [comment]
rollup-plugin-inject is what you need here, as @droooney says — I'll close this issue as Rollup is behaving as expected.
