### ISSUE TITLE
Add argument to watch

### ISSUE THREAD

**Issue by matthieusieben** [rollup/rollup#1405]
Add a command to execute as argument to the `--watch` option.

eg.

 ```sh
rollup -c -w 'scp dist/ap.js root@my-server:/www'
```

**Comment by bfred-it** [comment]
I believe this can be added with [`outpipe`](https://www.npmjs.com/package/outpipe)

**Comment by matthieusieben** [comment]
Indeed, thanks

**Comment by bfred-it** [comment]
No, I mean it can be added by implementing it into rollup itself, not as an external tool.

**Comment by shellscape** [comment]
@matthieusieben I'd be happy to help with this, but I'd like to know more about your use case. If you could explain in detail why one might need this feature, I can look into adding it.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
