### ISSUE TITLE
prevent unnecessary warn as a result of commonjs plugin

### ISSUE THREAD

**Issue by olsonpm** [rollup/rollup#1408]
Error:
```sh
Warning: 'default' is not exported by 'src/server/index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
^@commonjs-proxy:.../src/server/index.js (1:123)
1: import * as index from ".../src/server/index.js"; export default ( index && index['default'] ) || index;
```

[This rollup-plugin-commonjs issue](https://github.com/rollup/rollup-plugin-commonjs/issues/186) contains a github repo [reproduction](https://github.com/mjw56/inferno-redux-rollup):

I can think of a few solutions, but would like direction as to one that would get merged so I can create a&nbsp;PR.

1. (leaning heavily toward this one) - add a rollup configuration to prevent this warning from certain modules.  In the above case, `@commonjs-proxy:.../src/server/index.js`.

2. add a function `actuallyMissingAnExport` which would get called after [`!declaration`](https://github.com/rollup/rollup/blob/master/src/ast/nodes/MemberExpression.js?ts=2#L45).  It would take the scope and determine whether an export is actually missing.  This would be kind of a hacky solution, but it would work if we want to run it through a regex, or analyse the ast for a quick check and allows for the function to grow in the case more conditions are needed later.

I'm open to other solutions, I just really want to squash this warning.

**Comment by olsonpm** [comment]
So I somehow missed the [onwarn](https://github.com/rollup/rollup/wiki/JavaScript-API#onwarn) option which gives us the configurability.  The only question then is whether the common cases such as is caused by rollup-plugin-commonjs should be handled in rollup.  I think we should implement the option 2 I have above, or modify `rollup-plugin-commonjs` to create the following output:

```js
// from
export default ( aModule && aModule['default'] ) || aModule;

// to
export default ( React && React['def' + 'ault'] ) || React
```
I tested, and by splitting 'default', rollup doesn't complain.

**Comment by binarykitchen** [comment]
hmmm, what's happening with this issue and how to fix it? a patch underway?

**Comment by vardius** [comment]
any updates here ?

**Comment by trusktr** [comment]
But what is the problem? Following the suggested link leads me to the README on `namedExports`, and obviously how can we name the "default" export if CommonJS packages generally don't actually export an actual "default" property, so `namedExports` simply wouldn't work.

In my case, I'm getting this error on a fairly critical import:

```
⚠️   'default' is not exported by 'node_modules/core-js/library/modules/es6.object.to-string.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/trusktr/src/trusktr+infamous/node_modules/core-js/library/modules/es6.object.to-string.js (1:196)
1: import * as es6_object_toString from "/home/trusktr/src/trusktr+infamous/node_modules/core-js/library/modules/es6.object.to-string.js"; export default ( es6_object_toString && es6_object_toString['default'] ) || es6_object_toString;
```

@olsonpm Simply splitting the string may not help? How do we ensure that we actually import the correct thing from the file shown in the error?

In my case, the file `core-js/library/modules/es6.object.to-string.js` appears to be [simply empty](https://github.com/zloirock/core-js/blob/master/library/modules/es6.object.is-sealed.js). What should even happen here?

**Comment by olsonpm** [comment]
it's a warning.  splitting the string prevents rhe warning per my local test.

**Comment by trusktr** [comment]
Why is it a warning though? It points to the `namedExports` documentation, and that doesn't work with "default" (because how can it?), and that leads me to believe that this "warning" will cause error at runtime depending on what is in the problem file.

**Comment by sumeet610** [comment]
I am seeing this error after upgrading the rollup plugin version to 0.58.1
(!) Missing exports
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module commonjs-proxy:C:\project\node_modules\core-js\library\modules\es6.object.to-string.js default is not exported by node_modules\core-js\library\modules\es6.object.to-string.js1: import * as es6_object_toString from "C:\\project\\node_modules\\core-js\\library\\modules\\es6.object.to-string.js"; export default ( es6_object_toString && es6_object_toString['default'] ) || es6_object_toString;

**Comment by zerkalica** [comment]
+1

es6.object.to-string.js is empty file, may be ignore zero length files?

**Comment by guybedford** [comment]
The actual issue here is that a namespace object is being accessed on a missing export value (`import * as X; X.exportDoesNotExist`).

This does seem a useful warning like a circular reference warning in that it can help catch bugs, but there are certainly valid cases of testing existence on namespace objects this way.

Perhaps we should exclude `default` explicitly from this check specifically for these sorts of interop scenarios? It does seem a bit of a rare exception though.

**Comment by darthrellimnad** [comment]
appears to be expected on core-js side?

https://github.com/zloirock/core-js/issues/98

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
