### ISSUE TITLE
Question: how do you load configs as es6 modules

### ISSUE THREAD

**Issue by ngryman** [rollup/rollup#1409]
Hey,

I'm just curious, how do you load configs as es6 modules? I may probably be tired, but the only thing that seems to load configs is here: https://github.com/rollup/rollup/blob/master/bin/src/runRollup.js#L43. And from what I see, `require-relative` does not handle es6 modules. I'm lost 👻 

Thanks!

**Comment by olsonpm** [comment]
[rollup is a dependency of rollup](https://github.com/rollup/rollup/blob/master/package.json#L62).

the file you linked uses rollup to [compile the config into es5 then execute it](https://github.com/rollup/rollup/blob/master/bin/src/runRollup.js?ts=2#L67-L97)

**Comment by ngryman** [comment]
Oh ok I just had to scroll a down a little more 🤣 
I'm getting a lot of inspiration on your configuration system for the next release of [Speed Racer](https://github.com/ngryman/speedracer).
Thanks alot!

**Comment by olsonpm** [comment]
It happens :)

And you can thank the author Rich - I've contributed almost nothing.  Glad to hear open source is working for the better in your case though.
