### ISSUE TITLE
Importing Object results in erroneous output

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#1412]
import foo from './maths.js';

# maths.js

````
export default {
   templateData : {
        mock : [
            {
                title           : "Some Title",
                protectionLevel : _.random(100),
                trend           : _.random(-10,10),
            }
        ],
        a:1
    }
}
````

### [DEMO PAGE](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRm1hdGhzLmpzJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwJTdCJTVDbiUyMCUyMCUyMHRlbXBsYXRlRGF0YSUyMCUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBtb2NrJTIwJTNBJTIwJTVCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0aXRsZSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQSUyMCU1QyUyMlNvbWUlMjBUaXRsZSU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBwcm90ZWN0aW9uTGV2ZWwlMjAlM0ElMjBfLnJhbmRvbSgxMDApJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRyZW5kJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNBJTIwXy5yYW5kb20oLTEwJTJDMTApJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUQlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYSUzQTElNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJ1bWQlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

# Outputs (UMD):

````
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(factory());
}(this, (function () { 'use strict';

{
   templateData : {
        mock : [
            {
                title           : "Some Title",
                protectionLevel : _.random(100),
                trend           : _.random(-10,10),
            }
        ],
        a:1
    }
}

})));
````

which results in an error when compiled:

    SyntaxError: missing ; before statement
    a:1

	

I also find it annoying that the output is even shown as an object is simply because the lodash `random` method is used as property value... the existence of the whole thing relies of that method?

I would expect the above output only when I import without explicit naming:

    import './maths.js';

and not when doing this:
    
    import foo from './maths.js';

Because I am expecting `foo` variable to itself be the very thing I am important (the object)
and so, if I am not using (referencing) `foo` in my code in any way, I would expect the output to be empty.

I hope that I was clear in my explanation of the problem. 
Thank you very much. I'm a long-time user.

**Comment by olsonpm** [comment]
Sorry, but I'm not sure I understand your issue.  When you say `results in an error when compiled` do you mean `results in an error when ran`?  It does seem rollup has a bug by removing the variable assignment but keeping the object - as the resulting syntax is obviously incorrect.

As for the object persisting, the reason the object doesn't get tree shaken is that Rollup is unable to determine `_.random` as a pure function.  This is [very common](https://github.com/rollup/rollup#tree-shaking), especially [with lodash](https://github.com/rollup/rollup/issues/45#issuecomment-167381283).  So because `_.random` may cause side-effects, the whole object must be left alone.

**Comment by Rich-Harris** [comment]
Simple repro [here](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRmZvby5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTVDdGElM0ElMjBmb28oKSU1Q24lN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

Simple answer, as noted, is to preserve the `var` declaration. If we wanted to get really fancy we'd just keep the function call and discard the object expression:

```js
// main.js
import foo from './foo.js';

// foo.js
export default {
  a: foo()
};

// output:
foo();
```

**Comment by yairEO** [comment]
but what about the bug where the variable assignment is being removed?

**Comment by guybedford** [comment]
Well this is already half fixed... we now get one paren at least :)

Tracking at newer issue - https://github.com/rollup/rollup/issues/2091.
