### ISSUE TITLE
Babel don't work correctly with world 'global'

### ISSUE THREAD

**Issue by alwaysonlinetxm** [rollup/rollup#1415]
I found a strange thing in my rollup project. rollup-plugin-babel can't compile '...' operator corrently when there is a string or annotation with word 'global'.  

Here's my config:

```JavaScript
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';
import json from 'rollup-plugin-json';
// import globals from "rollup-plugin-node-globals";
import babel from "rollup-plugin-babel";

export default {
  entry: 'index.js',
  dest: 'dist/bundle.js',
  format: 'cjs',
  plugins: [
    nodeResolve(), // for support external module in node_modules
    commonjs(),
    // globals(),
    json(),
    babel({
      exclude: "node_modules/**",
      // plugins appears to be ignored. use .babelrc
    })
  ]
};
```

and here's index.js:

```JavaScript
// global
const a = { ...b };
```
The `// global` can be a string or annotation,   just with word 'global' in it, it can be before or after the '...' operator.

and there will be a error when babel try to compile these code:

```JavaScript
$ NODE_ENV=development rollup -c -w 
bundling...
🚨   (commonjs plugin) Unexpected token (2:12) in /Users/alwaysonlinetxm/txm/rollup_issue/index.js
undefined (2:12)
```

Is this a bug of rollup or rollup-plugin-babel ?

there is the example repo to reproduce this problem:
https://github.com/alwaysonlinetxm/rollup_issue

**Comment by olsonpm** [comment]
your babel plugin needs to run prior to commonjs.

Once I switched the order, `rollup -c` worked.

Thanks for creating the example repo :)

**Comment by Rich-Harris** [comment]
thanks @olsonpm! closing this issue.

(Incidentally there is an issue open to try and deal with these cases better: #1148. We'll get to it eventually...)

**Comment by alwaysonlinetxm** [comment]
@olsonpm Thank you! It worked! But I wonder if  the commonjs plugin should be put in after all other plugin?
