### ISSUE TITLE
foo:  - (2 ** 23) causes a operators[this.operator] is not a function

### ISSUE THREAD

**Issue by backspaces** [rollup/rollup#1416]
TL;DR: This construct causes a `operators[this.operator] is not a function`: minInt24x: - (2 ** 23)

Details: Place this in the main.js in the repl:
```
const foo = {
  minInt24: 0 - (2 ** 23),
  // minInt24x: - (2 ** 23) // rollup bug operators[this.operator] is not a function
}
export default foo
```
Then remove the comment.

**Comment by olsonpm** [comment]
Thanks for raising that issue.  Definitely a bug in rollup - hopefully the next release will merge my PR
