### ISSUE TITLE
Recipe without the need a destination (keep in memory)

### ISSUE THREAD

**Issue by binarykitchen** [rollup/rollup#1417]
I have an use case here where I want to rollup tape based tests before letting them go through the tape-runner (https://github.com/substack/tape and https://www.npmjs.com/package/tape-run)

Unfortunately rollup requires a destination to be configured. But in my case I don't need one and would prefer to let it run in memory. Is there a recipe for that?

In other words, instead of something like

$ rollup -c test.js && cat test/dist/index.js | tape-run

could we have this in memory and just pipe to tape-run like

$ rollup -c test.js | tape-run

that would be more elegant I think.

**Comment by olsonpm** [comment]
The following worked for me
```js
// rollup.config.js
export default {
  entry: 'index.js',
  format: 'cjs'
};
```

```js
// index.js
console.log('heyo');
```

```sh
$ rollup -c
'use strict';

console.log('heyo');
```

So please create a github repo reproducing your issue.

**Comment by binarykitchen** [comment]
ok, here is a public branch to reproduce:
https://github.com/binarykitchen/videomail-client/tree/feature/rollupjs

do the following:
```bash
$ git clone git@github.com:binarykitchen/videomail-client.git
$ git checkout feature/rollupjs
$ yarn
$ yarn test // <-- booom, it fails
```

that test command in package json is this:
`"test": "rollup -c env/test/rollup.config.js | tape-run"`

now, let's put back in the destination like this in the env/test/rollup.config.js

```js
config.dest = './tmp/test.js'
```

and change that test command in package.json to
```bash
rollup -c env/test/rollup.config.js && cat tmp/test.js | tape-run
```

then tests are actually run (ignore any failed tests further down)

**Comment by olsonpm** [comment]
your issue is related to the progress plugin - which makes sense as it intercepts stdout.

I made a quick attempt to debug further and get tape-run working, but the example is too large.  You would need to narrow your problem down to a small example.

**Comment by binarykitchen** [comment]
@olsonpm ok, should i report the stdout issue to the progress plugin makers? or do you have a solution to circumvent this?

and what changes did you make to get tape-run working?

**Comment by olsonpm** [comment]
Sorry for not being more clear - I didn't get tape-run working as I ran into other issues after removing the progress plugin.  I didn't want to keep digging because the example was too large.

As for raising an issue to the progress plugin, that wouldn't make sense because there's no other way for it to show progress than to intercept stdout.  That's its purpose.  The simplest solution would be to remove the plugin from your test rollup.config.js and figure out how to get the resulting output in tape-run'able shape.

If you slim your example down I can definitely help - but you should close this issue as it's not a bug in rollup.

**Comment by binarykitchen** [comment]
@olsonpm good points, i ll definitely do all your suggestions and come back here later. thanks again!

**Comment by bfred-it** [comment]
Is this still needed? `rollup` automatically outputs to **stdout** if no `--output` parameter is specified, so this is likely to be a configuration issue.

**Comment by binarykitchen** [comment]
yep, not needed, using an useful zora recipe here
https://github.com/lorenzofox3/zora-recipes#continuous-integration-mode

**Comment by bfred-it** [comment]
Excellent :)
