### ISSUE TITLE
Hide require in order to do bundle splitting

### ISSUE THREAD

**Issue by vjeux** [rollup/rollup#1418]
Bundle splitting is not handled by rollup but I want to use rollup so here's my attempt:

I have two files `a.js` and `b.js` that I want to bundle separately and `a.js` requires `b.js`:

```js
// a.js
const b = require("./b");
```

What I want is to hide the fact that a requires b so that rollup leaves `require("b")` there.

## Attempt 1: externals

```js
externals: ['b.js']
```

Using the absolute file path doesn't do anything.

```js
externals: ['./b']
```

Using the path the same way I put it inside of require seems to be doing something but now it won't compile my file.

```js
Could not resolve './b' from a.js
```

## Attempt 2: use another variable

```js
const b = (0, require)("./b");
```

If you try to use a different AST than `require(x)` it doesn't include it in the bundle (yay!) but it still replaces require by a local function that throws:

```js
throw new Error('Dynamic requires are not currently supported by rollup-plugin-commonjs');
```

Sad panda :(

## Attempt 3: using eval

```js
const b = eval("require")("./b");
```

This works: it doesn't include `b` in the bundle and works at runtime! Yay! But, yeahh... there's a but: you've got a huge warning when building:

```js
⚠️   Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval
parser.js (14:20)
12:     parseFunction = eval("require")("./src/parser-typescript");
13:   } else if (opts.parser === "postcss") {
14:     parseFunction = eval("require")("./src/parser-postcss");
                        ^
15:   } else {
16:     parseFunction = eval("require")("./src/parser-babylon");
```

I haven't found a way to mute this warning unfortunately.

Am I missing something?

**Comment by rossipedia** [comment]
Wouldn't the right approach here be not using `require` but rather `import()` seeing as rollup focuses so much on es modules?

**Comment by vjeux** [comment]
@rossipedia I'm happy to change it to import if you can find a way to make it work.

**Comment by Rich-Harris** [comment]
I think you were close with option a — the trick is to resolve the path, like so:

```js
// rollup.config.js
import path from 'path';

export default {
  entry: 'src/a.js',
  dest: 'dist/bundle.js',
  format: 'cjs',
  externals: [
    path.resolve('src/b.js')
  ],
  // ...
};
```

Then, an `import b from './b.js'` declaration would be turned into a `require` statement. You can also use the `paths` option to control the path of the import in the bundle:

```js
// rollup.config.js
import path from 'path';

const b = path.resolve('src/b.js');

export default {
  entry: 'src/a.js',
  dest: 'dist/bundle.js',
  format: 'cjs',
  externals: [b],
  paths: {
    [b]: '../src/b.js' // would result in `b = require('../src/b.js')`
  }
  // ...
};
```

**Comment by vjeux** [comment]
Omg it works, thanks :)

**Comment by vjeux** [comment]
Arg, actually it doesn't quite work :( It puts all those require at the top of the file, defeating their usecase: they should only be required when you go in that part of the code.

**Comment by thisconnect** [comment]
Just a thought, could a plugin:
- detect `import('./b.js').then(b => { /*  b(); // can be used here */ })` in a.js 
- set the correct `externals` and `paths`
- re-run rollup with the same configs for `b.js`
- end up with `bundle/a.js` and `bundle/b.js`
