### ISSUE TITLE
"Cannot call a namespace" and and IIFE `globals` default

### ISSUE THREAD

**Issue by phuvo** [rollup/rollup#1420]
I just want to use `moment`:
```js
import * as moment from 'moment';
moment.locale('en-au'); // this works fine
moment('2017-05-30'); // `rollup` failed with error "Cannot call a namespace"
```

So I changed the `import` statement to this:
```js
import moment from 'moment';
moment('2017-05-30');
```

With the following `rollup` options:
```js
{
    format: 'iife',
    external: ['moment'],
    globals: { moment: 'moment' },
}
```

But the code generated by `rollup` looked like this:
```js
(function(moment) {
    var moment__default = moment['default'];
    moment__default('2017-05-30'); // `moment__default` is undefined
})(moment);
```

I thought of suppressing the namespace error, but currently `rollup` only support `onwarn`. Does anyone know a workaround or a way to resolve this?

**Comment by olsonpm** [comment]
with your configuration, my bundle looks like this:

```js
(function (moment) {
'use strict';

moment = 'default' in moment ? moment['default'] : moment;

moment('2017-05-30');

}(moment));
```

Which works as expected.  Please create a repo which reproduces your issue.

**Comment by phuvo** [comment]
I just checked and the `moment__default` issue only happens if I use both `import moment from 'moment'` and `import * as moment from 'moment'` in my code.

Since I'm using TypeScript, I'll just use some TypeScript magic to make only `import moment from 'moment'` as valid code.
