### ISSUE TITLE
No name was provided for external module 'babel-runtime/core-js/promise' in options.globals – guessing '_Promise'

### ISSUE THREAD

**Issue by xgz123** [rollup/rollup#1421]
~~~js
// rollup.config.js
...
  external: ['babel-runtime/core-js/promise'],
  globals: {
    promise: 'babel-runtime/core-js/promise'
  }
~~~

I have set options.gobals but still got this warning.

> ⚠️  No name was provided for external module 'babel-runtime/core-js/promise' in options.globals – guessing '_Promise'

**Comment by olsonpm** [comment]
See the [globals documentation](https://github.com/rollup/rollup/wiki/JavaScript-API#globals) in the wiki

> Object of id: name pairs (e.g. with `import Backbone from 'backbone'`, `backbone` is the id, `Backbone` is the global name

```
// rollup.config.js
...
  external: ['babel-runtime/core-js/promise'],
  globals: {
    'babel-runtime/core-js/promise': promise // <-- switch these
  }
```

**Comment by Rich-Harris** [comment]
@olsonpm is correct (thanks!), closing this issue

**Comment by xgz123** [comment]
@olsonpm thanks!

**Comment by cecilpeng** [comment]
globals is an option of output!
