### ISSUE TITLE
RFC: options.imports

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1425]
A frequent source of confusion is the relationship between `options.externals` and `options.globals`:

```js
{
  externals: ['jquery'],
  globals: {
    jquery: '$'
  }
}
```

`globals` is only needed for UMD and IIFE bundles (because it determines what global variable corresponds to a given module). But if it's there, it's redundant.

We could simplify it by dropping `externals` altogether...

```js
{
  globals: {
    jquery: '$'
  }
}
```

...though I'd propose renaming it to reflect its changed purpose:

```js
{
  imports: {
    jquery: '$'
  }
}
```

The keys would determine which modules are external, and the values would determine their names *if* the bundle is UMD or IIFE — in other words, if you're generating an ES module or a CommonJS bundle, you could equally do this, because the values are ignored:

```js
{
  imports: {
    jquery: true
  }
}
```

A nice thing about this is that in many cases you could use `pkg.dependencies`:

```js
const pkg = require('./package.json');

export default {
  ...
  imports: pkg.dependencies
};

// or if you needed to augment it...
export default {
  ...
  imports: Object.assign({
    fs: true,
    path: true
  }, pkg.dependencies)
};
```

We'd keep the function form:

```js
export default {
  ...
  imports: id => {
    if (id === 'underscore') return '_';
    if (id.startsWith('d3-')) return 'd3';
    return null;
  }
}
```

Any thoughts? Is this a step forward or backward?

cc @vijithassar

**Comment by olsonpm** [comment]
Without `external`, you will no longer be able to leave in import/require statements explicitly.

```js
// rollup.config.js
export default {
  entry: 'main.js'
  , external: ['moment']
  , format: 'es'
}
```

```js
// inline-dependency.js
export default 'this dependency will be bundled';
```

from
```js
// main.js
import moment from 'moment';
import inlineDependency from './inline-dependency';

global.doSomethingWith(moment);
global.doSomethingWith(inlineDependency);
```
to
```js
import moment from 'moment';

var inlineDependency = 'this dependency will be bundled';

global.doSomethingWith(moment);
global.doSomethingWith(inlineDependency);
```

**Comment by vijithassar** [comment]
This functionality is specifically about how to *exclude* something from the build (jQuery, in the example above), but in ES6 module syntax, "import" is used to indicate *inclusion*. The word "import" is already very important in the Rollup world, so in the interest of clarity I don't think it's a great idea to give it an additional meaning in this context, let alone one that's opposed to the syntax Rollup exists to compile.

**Comment by shellscape** [comment]
@Rich-Harris is this RFC still relevant?

**Comment by lukastaegert** [comment]
Personally I would not go through with this. External handling is difficult as it is and a lot has happened in this area. To me this seems to have the potential to cause more confusino than it solves. Also "imports" might become more confusing now that we have code-splitting.

**Comment by shellscape** [comment]
OK I'll close for now. We can always re-open.
