### ISSUE TITLE
Support multiple input files: **/*.js

### ISSUE THREAD

**Issue by bfred-it** [rollup/rollup#1435]
Multiple specific files (#863) are now supported via config file as of v0.42 (#1389).

# Feature request

How about any number of JS files via cli? E.g.:

```sh
$ cd src && rollup --output ../dist --watch entry1.js entry2.js entry3.js
dist/entry1.js
dist/entry2.js
dist/entry3.js
```

This would also work with shell-expanded globs:

```sh
$ cd src && rollup --output ../dist --watch *.js
# automatically expanded to:
# cd src && rollup --output ../dist --watch entry1.js entry2.js
```

# Workarounds

Currently, globbing is sort of possible via config file, I think:

```js
// rollup.config.js
const globby = require('globby');
const configs = globby.sync('**/*.js').map(inputFile => ({
  entry: inputFile
  dest: inputFile.replace('src', 'dist'),
  format: 'umd'
}));
module.exports = configs
```

Via CLI you can use [`cli-foreachfile`](https://github.com/hash-bang/cli-foreachfile):

```sh
cd src && each '**/*.js' -- rollup --output $PWD/../dist/%p $PWD/%p
# --watch supported, but you'll need the `--concurrent` flag on `each`
# cd src && each --concurrent 100 '**/*.js' -- rollup --watch --output $PWD/../dist/%p $PWD/%p
```

**Comment by isidrok** [comment]
Have a look at this plugin: https://github.com/rollup/rollup-plugin-multi-entry

**Comment by bfred-it** [comment]
@isidrok the output is one file with that, they need to be separate files.

**Comment by isidrok** [comment]
I see, for that I have used the above mentioned plugin and the rollup capability to export multiple configs , not sure if that's what you are looking for though, it looks something like this:
```javascript
const BUNDLE_1= {
    entry: 'entry1.js',
    dest: 'dist/bundle1.js',
    moduleName: 'BUNDLE1',
    sourceMapFile: 'dist/entry1.js.map'
}
const BUNDLE_2 = {
    entry: [
        'entry2.js',
        'entry3.js'
    ],
    dest: 'dist/bundle2.js',
    moduleName: 'BUNDLE2',
    sourceMapFile: 'dist/bundle1.js.map'
}

const COMMON = {
    format,
    plugins: [
        multiEntry(),
        babel({
            exclude: [
                'node_modules/**'
            ]
        }),
        uglify()
       // ...
    ],
    sourceMap: true
    // ...
}
export default [
    Object.assign({},BUNDLE_1, COMMON),
    Object.assign({}, BUNDLE_2, COMMON)
]
```

**Comment by bfred-it** [comment]
Yeah, it is possible, I mentioned a shorter plugin-less glob-based usage in my first post.

**Comment by isidrok** [comment]
Yeah, just commented in case someone prefered to use the other workaround while the feature is not implemented.

**Comment by Rich-Harris** [comment]
Since there are already multiple ways to do this, I'm going to close this issue — it's not a good idea to keep adding features to the CLI unless there's no alternative, otherwise it will become an unmaintainable mess!

**Comment by zanona** [comment]
Hey, @Rich-Harris I'm afraid I must disagree on this one.
This would be a convenience the CLI offers and if you have to use the API to achieve this, the CLI loses its purpose a little bit since we are not controlling the application through the command line anymore.

Being able to run `rollup **.js -o dist` is a functionality users would expect, I believe.
Hopefully, this can be reconsidered based on how often this is needed/used by developers.

**Comment by mvasilkov** [comment]
As a (beginning) user, I second this very much: I found this issue due to a failed attempt at `$ rollup a.js b.js -o ...`

**Comment by danielo515** [comment]
So, at the end this is not possible right ? I can't take several files as input.

**Comment by lukastaegert** [comment]
Not via the CLI and it is very unlikely we add this as this will easily conflict with the code-splitting CLI interface (which DOES take several input files but will extract shared dependencies into common chunks) or at least become very confusing.

From a performance side at least at the moment, just running rollup several times will not be much slower.

Beyond that, I see potential for a simple CLI app that resolves globs in the way described and will gladly feature it on the website if someone wrote it.

**Comment by lukastaegert** [comment]
> will gladly feature it on the website

Or rather in the tools section of the wiki: https://github.com/rollup/rollup/wiki/Tools

There could really be more tools listed here!

**Comment by danielo515** [comment]
I was not talking about cli, sorry for not being 100% clear. I am using broccoli, and I like how broccoli maps the files 1-1. I am using the rollup-broccoli plugin, and I would like to be able to maintain that interface.

Regards

**Comment by zanona** [comment]
> From a performance side at least at the moment, just running rollup several times will not be much slower.
@lukastaegert I believe that is actually what I would expect from the CLI where running `rollup **/*.js -o dist` would generate every single file separately inside the dist directory and not be trying to compile them in a single one. So really a convenience method to not have to write your own program to run rollup multiple times.

**Comment by lukastaegert** [comment]
@zanona There is actually some discussion about the topic here: https://github.com/rollup/rollup/issues/2092#issuecomment-385756578

Considering code-splitting is a somewhat advanced topic, the discussion is whether to not overload `input` as an array for code-splitting. If we separate these two concerns, input as an array to create multiple bundles might actually be an option again.

@danielo515 If you want a 1-1 mapping, the `experimentalPreserveModules` option may be related to what you achieve. Otherwise if you are using a config file, you can already generate multiple bundles from multiple inputs by returning an array of configurations, cf. the workaround described in the initial configuration for how to combine this with glob patterns. The current issue was mainly about the CLI interface.

**Comment by danielo515** [comment]
Ok, I'll check the workarounds. Do you have any concrete link?

**Comment by alfredosalzillo** [comment]
Hi, check this plugin [rollup-plugin-multi-input](https://github.com/alfredosalzillo/rollup-plugin-multi-input)

**Comment by DominicTobias** [comment]
> I see, for that I have used the above mentioned plugin and the rollup capability to export multiple configs , not sure if that's what you are looking for though, it looks something like this:
> 
> ```js
> const BUNDLE_1= {
>     entry: 'entry1.js',
>     dest: 'dist/bundle1.js',
>     moduleName: 'BUNDLE1',
>     sourceMapFile: 'dist/entry1.js.map'
> }
> const BUNDLE_2 = {
>     entry: [
>         'entry2.js',
>         'entry3.js'
>     ],
>     dest: 'dist/bundle2.js',
>     moduleName: 'BUNDLE2',
>     sourceMapFile: 'dist/bundle1.js.map'
> }
> 
> const COMMON = {
>     format,
>     plugins: [
>         multiEntry(),
>         babel({
>             exclude: [
>                 'node_modules/**'
>             ]
>         }),
>         uglify()
>        // ...
>     ],
>     sourceMap: true
>     // ...
> }
> export default [
>     Object.assign({},BUNDLE_1, COMMON),
>     Object.assign({}, BUNDLE_2, COMMON)
> ]
> ```

Out of curiosity does anyone know how optimized rollup is at handling multiple bundles like that (since it isn't built for it our the box)?

**Comment by EaseRider** [comment]
A workaround, defining every In/Export in the config can be found here:
https://github.com/jaebradley/example-rollup-library/blob/master/rollup.config.js

**Comment by rondonjon** [comment]
> A workaround, defining every In/Export in the config can be found here:
> https://github.com/jaebradley/example-rollup-library/blob/master/rollup.config.js

AIUI this would create multiple bundles with potentially a lot of duplicated code, i.e. these should only be used one at a time and not for library code. Just saying.

**Comment by trusktr** [comment]
> AIUI this would create multiple bundles with potentially a lot of duplicated code, i.e. these should only be used one at a time, and the approach should be avoided for library organization. Just saying.

Well, there's always Webpack for that. Rollup is designed for simple bundles.

**Comment by reothues** [comment]
--entryFileNames entries/*.js
