### ISSUE TITLE
How to use globals

### ISSUE THREAD

**Issue by kopax** [rollup/rollup#1437]
Hi everyone and first of all thanks for the amazing work done.

I have read the documentation [here](https://github.com/rollup/rollup/wiki/JavaScript-API#globals).

I have configured the following rollup:

```jsx
export default {
  entry: 'src/index.js',
  moduleName: pkg.name,
  external: ['react', 'react-router', 'react-transition-group', 'bootstrap-styled', 'styled-component', 'classnames'],
  exports: 'named',
  targets,
  plugins,
  globals: {
    react: 'React',
    'react-router': 'ReactRouter',
    'react-transition-group': 'ReactTransitionGroup',
    'bootstrap-styled': 'BootstrapStyled',
    'styled-component': 'styled',
    classnames: 'cn',
  },
};
```
I never import the default of  `react-router`, `react-transition-group`, `bootstrap-styled`. 

Is it possible to safely write this ?

```jsx
export default {
  entry: 'src/index.js',
  moduleName: pkg.name,
  external: ['react', 'react-router', 'react-transition-group', 'bootstrap-styled', 'styled-component', 'classnames'],
  exports: 'named',
  targets,
  plugins,
  globals: {
    react: 'React',
    'styled-component': 'styled',
    classnames: 'cn',
  },
};
```

It doesn't clearly says how rollup will behave with this `globals` configuration, is it a requirement ? what does this configure ?

**Comment by jonataswalker** [comment]
It doesn't hurt if you let all the globals configured. No performance difference and no warnings from Rollup.

**Comment by L3ARNING2B** [comment]
So as the example above, we could do:

    import React from 'react';

and

    import { Link } from 'react-router';

Does that mean `globals` are use mainly for external dependencies we need to access globally ? Does it could be kind of peer dependency ?

And `external` would be external dependencies  that we do not need to acces globaly ? Does it could be kind of development dependencies` ?

Many thanks for answering, its not clear for me too.

**Comment by L3ARNING2B** [comment]
So as the example above, we could do:

    import React from 'react';

and

    import { Link } from 'react-router';

Does that mean `globals` are use mainly for external dependencies we need to access globally ? Does it could be kind of peer dependency ?

And `external` would be external dependencies that we do not need to access globally ? Does it could be  kind of development dependencies` ?

Many thanks for answering, its not clear for me too.

**Comment by L3ARNING2B** [comment]
@jonataswalker  maybe you recommand to do:

**Comment by L3ARNING2B** [comment]
@jonataswalker maybe you advice us to do this :

````
export default {
  entry: 'src/index.js',
  moduleName: pkg.name,
  external: ['react', 'react-router', 'react-transition-group', 'bootstrap-styled', 'styled-component', 'classnames'],
  exports: 'named',
  targets,
  plugins,
  globals: {
    react: 'React',
    'react-router': 'Link',
    'react-transition-group': 'ReactTransitionGroup',
    'styled-component': 'styled',
    'bootstrap-styled': 'Jumbotron',
    classnames: 'cn',
  },
};
````

So what's happen for importing multiple element as `Link`, `Route`, `Router` from `react-router` ?

can we write that like this ? : 

````
  globals: {
    'react-router': 'Link Route Router',
  },
````

or like that ?:

````
  globals: {
    'react-router': [
      'Link',
      ' Route',
      ' Router',
    ]
  },
````

**Comment by jonataswalker** [comment]
@L3ARNING2B in a browser environment `globals` is a `window.SomeModule`, so Rollup assumes that you are loading the external file that exposes this variable.

Take a look at the `react-router/umd/react-router.js`, there you are: `root["ReactRouter"]`.

This is the way to go:
```javascript
import { Link, Whatever } from 'react-router';
```
```javascript
  globals: {
    react: 'React',
    'react-router': 'ReactRouter'
  }
```

**Comment by L3ARNING2B** [comment]
@jonataswalker this is exactly the explanation I needed, thank you so much. Rollup rocks !

**Comment by L3ARNING2B** [comment]
And if one of these module have only dist folder (no umd folder) I guess it will be the same principle ?

**Comment by jonataswalker** [comment]
Yep. Same thing.

**Comment by calummackervoy** [comment]
I'm new to bundling applications, I've just been getting to grips with rollup (I found this article useful: https://www.mixmax.com/engineering/rollup-externals

I wanted to ask, how can I externalise dependencies with organizations in the module name?

```javascript
external: [
    '@inrupt/solid-client',
    '@multi-user-domain/mud-lib',
    '@inrupt/solid-client-authn-core',
  ],
  output: {
    globals: {
      '@inrupt/solid-client': ???,
      '@multi-user-domain/mud-lib': ???,
      '@inrupt/solid-client-authn-core': ???
    },
```

Am I understanding that Rollup won't expose these to `window` automatically in my browser application? I had a look at the compiled code from unpkg, but I couldn't find an explicit line where it was set, so perhaps that means that it isn't and therefore I can't use it as an external module?

**Comment by calummackervoy** [comment]
Also, it seems like making the dependencies external is a good idea to save on bandwidth, but by doing that I have to explain where to fetch them from e.g.

```javascript
paths: {
    "react": "https://unpkg.com/react@17/umd/react.development.js",
    "react-dom": "https://unpkg.com/react-dom@17/umd/react-dom.development.js",
    "@inrupt/solid-client": "https://unpkg.com/@inrupt/solid-client@1.13.3/dist/index.js",
  },
```

and in doing so I'm duplicating the version information being maintained by my `package.json`?

**Comment by ThisIsMissEm** [comment]
> 



> I'm new to bundling applications, I've just been getting to grips with rollup (I found this article useful: https://www.mixmax.com/engineering/rollup-externals
> 
> I wanted to ask, how can I externalise dependencies with organizations in the module name?
> 
> ```js
> external: [
>     '@inrupt/solid-client',
>     '@multi-user-domain/mud-lib',
>     '@inrupt/solid-client-authn-core',
>   ],
>   output: {
>     globals: {
>       '@inrupt/solid-client': ???,
>       '@multi-user-domain/mud-lib': ???,
>       '@inrupt/solid-client-authn-core': ???
>     },
> ```
> 
> Am I understanding that Rollup won't expose these to `window` automatically in my browser application? I had a look at the compiled code from unpkg, but I couldn't find an explicit line where it was set, so perhaps that means that it isn't and therefore I can't use it as an external module?

Hi @calummackervoy!

I'm a developer on the Solid SDK from Inrupt, I happened to come across your comment whilst researching something relating to rollup. The global name for `@inrupt/solid-client` is `SolidClient` (see: https://github.com/inrupt/solid-client-js/blob/main/rollup.config.js#L46).

For `@inrupt/solid-client-authn-core` and `@inrupt/solid-client-authn-browser`, they are currently built with webpack instead of rollup, so do not expose the UMD modules you're expecting (we do have a backlog ticket to migrate to rollup though). You might be able to find what you want as `solidClientAuthentication`, which is a library name in the [webpack build](https://github.com/inrupt/solid-client-authn-js/blob/main/packages/browser/webpack.browser.js#L12), but I'm not sure it works the same or as expected. Maybe the rollup [commonjs plugin](https://github.com/rollup/plugins/tree/master/packages/commonjs) would help in the meantime too?

For now, I'd probably recommend just bundling the Solid SDK into your application, rather than treating it as an external dependency.

**Comment by calummackervoy** [comment]
Hi @ThisIsMissEm ! Thanks for the extra info it helped a lot, e.g. for seeing how I can find out the global name of a package

Took your advice regarding bundling with the SDK, we were using the commonjs plugin already but in the end we realised that we could drop support for CJS output and this solved our issue
