### ISSUE TITLE
Trouble with isomorphic react app, auth0-js and rollup/babel

### ISSUE THREAD

**Issue by kurtmilam** [rollup/rollup#1439]
I'm cross-posting this from [here](https://github.com/auth0/auth0.js/issues/452).

auth0-js depends on superagent, so I've run into a couple of known compatibility issues between rollup and superagent ( #1086 , #166 ). While I have cleared those issues up, I'm still stuck with an application that isn't working. The current problem is `ReferenceError: process is not defined` in the browser.

Please see [this repository](https://github.com/kurtmilam/karet-express-boilerplate/tree/auth0), which should contain the minimum elements needed to reproduce the problems, including my rollup config.

**Comment by olsonpm** [comment]
Based on the error you mentioned, [rollup-plugin-node-globals](https://github.com/calvinmetcalf/rollup-plugin-node-globals) is what you're looking for.

**Comment by kurtmilam** [comment]
Thanks for the tip. While this gets rid of the `process` error on the browser, it also kills superagent (a dependency of auth0-js) on the browser.

**Comment by olsonpm** [comment]
sorry, i naively thought that would get you going.  i'll take a look tomorrow and get back.  tomorrow is internet installation day at my new apartment. woo woo

**Comment by kurtmilam** [comment]
Please don't apologize! I appreciate any help I can get to figure this out. I was excited when adding node globals seemed to fix the issue, and indeed, it allowed me to add a few new auth-related features to my application before I ran into the latest issue. Would it be helpful for me to update the sample repository, adding node globals added and additional code that triggers errors?

Good luck with your new internet connection - here's to hoping it's lightning fast!

Also, here are quick instructions on how to get the correct repository and branch and then start the application:
```
git clone https://github.com/kurtmilam/karet-express-boilerplate.git
cd karet-express-boilerplate
git checkout auth0
npm install
nmp run watch
```

**Comment by kurtmilam** [comment]
I updated the repo to include rollup-plugin-node-globals as well as a call to a superagent method that causes the error I'm currently getting.

**Comment by olsonpm** [comment]
I sent a PR with the fix.  The issue was you were pulling the server version of superagent.  The fix was just to use the `browser: true` option in rollup-plugin-node-resolve.

**Comment by kurtmilam** [comment]
Thanks for looking into this, but I'm afraid the proposed fixes are not appropriate to my case.

As I mentioned in the opener:
* This is an isomorphic application that will be run on the server and the browser.
* superagent is a dependency of the auth0-js package in my project, so I can't change how it's imported in auth0-js files.

auth0 says their auth0-js package works on the browser and server using their [react examples](https://github.com/auth0-samples/auth0-react-samples) (based on create-react-app and relying on Webpack).

**Comment by olsonpm** [comment]
> This is an isomorphic application

I read their repo and can't find any statement of it being isomorphic.  In fact when I browsed I saw they have a complementary 'node-autho' lib.  Can you point me to where they say they are isomorphic compatible?

**Comment by kurtmilam** [comment]
I'm mostly going off of [this Jan 31, 2017 comment](https://github.com/auth0/lock/issues/592#issuecomment-276452084) from an auth0 developer:

> Some changes were made in lock.js and auth0.js to avoid relying on window object and breaking server side rendering but lock is not there yet (auth0.js v8 can be used without issues)

I'm using auth0.js v8.

'Lock', which apparently still causes problems on the server, refers to a different auth0 package that I am not using.  Based on the comment, I was under the impression that the auth0.js v8 package could be used without issue on the server. I'll double check with the auth0 team and let you know.

Thanks for your help, so far.

**Comment by olsonpm** [comment]
well given auth0 depends on superagent, and superagent has both server and browser specific builds, i would say my fix is appropriate.  you could try the browser specific build in the server to see if it fails, but i don't see how auth0 could be isomorphic given the superagent constraint

**Comment by kurtmilam** [comment]
Thanks so much for helping me out here. The solution ended up being a combination of things:

1. Remove unnecessary built-ins and node-globals rollup plugins.
2. Pass `{ browser: true }` to node-resolve plugin.
3. Place `isBrowser` ( `typeof window !== 'undefined'` ) guards before all invocations of auth0 to make sure it's never invoked on the server.

I appreciate your patience and dedication in helping me determine the solution!
