### ISSUE TITLE
Help needed with a module I cannot rollup (and is there no discussion forum?)

### ISSUE THREAD

**Issue by binarykitchen** [rollup/rollup#1441]
This is not a bug report. It is more a call for help since there is NO discussion forum where I can ask for assistance. And no Slack channel. And on Stackoverflow help doesn't always arrive.

I've been stuck with a feature branch of a module I am trying to port from gulp to rollups:
https://github.com/binarykitchen/videomail-client/tree/feature/rollupjs

Config is https://github.com/binarykitchen/videomail-client/blob/feature/rollupjs/env/dev/rollup.config.js

Current output / problem is:

```
~/c/videomail-client ❯❯❯ npm run build:dev                                                ⏎ feature/rollupjs ✭ ✱

> videomail-client@1.28.11 prebuild:dev /home/michael-heuberger/code/videomail-client
> npm run std --silent


> videomail-client@1.28.11 build:dev /home/michael-heuberger/code/videomail-client
> rollup -c env/dev/rollup.config.js -w

bundling...
(700): src/wrappers/optionsWrapper.js⚠️   'default' is not exported by 'node_modules/global/window.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/michael-heuberger/code/videomail-client/node_modules/global/window.js (1:137)
1: import * as window from "/home/michael-heuberger/code/videomail-client/node_modules/global/window.js"; export default ( window && window['default'] ) || window;
                                                                                                                                            ^

⚠️   'default' is not exported by 'node_modules/global/document.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/michael-heuberger/code/videomail-client/node_modules/global/document.js (1:145)
1: import * as document from "/home/michael-heuberger/code/videomail-client/node_modules/global/document.js"; export default ( document && document['default'] ) || document;
                                                                                                                                                    ^

🚨   'default' is not exported by node_modules/websocket-stream/stream.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/wrappers/visuals/recorder.js (3:7)
1: import { Buffer } from "/home/michael-heuberger/code/videomail-client/node_modules/buffer-es6/index.js";
2: 
3: import websocket from 'websocket-stream';
          ^
4: import Frame from 'canvas-to-buffer';
5: import util from 'util';
```

I think this is the wrong place to report but where else can I be successful? Or can change this ticket into a request for a discussion forum elsewhere. Up to you :)

**Comment by jchook** [comment]
If you want help on github, you better have a repo we can clone to immediately reproduce the problem.

**Comment by binarykitchen** [comment]
sure it is this one https://github.com/binarykitchen/videomail-client/tree/feature/rollupjs

**Comment by jchook** [comment]
Okay, cloning, but... you should try to reproduce the problem as simply as possible.

**Comment by jchook** [comment]
Solved my moving `globals()` plugin down below `commonjs()`.

There is still a warning but that could be a [bug](https://github.com/rollup/rollup/issues/1408).

**Comment by jchook** [comment]
Here is a paste of my `rollup.config.js`:
https://pastebin.com/raw/rGJXAt0q

Also I want to point out that there is an open issue (#1148) about plugin order.

**Comment by binarykitchen** [comment]
thanks man

but weird, after those changes you recommended, I am seeing this new error upon `npm run build:dev`:

```
~/c/videomail-client ❯❯❯ npm run build:dev                                              feature/rollupjs ✭ ✖ ✱ ◼

> videomail-client@1.28.11 prebuild:dev /home/michael-heuberger/code/videomail-client
> npm run std --silent


> videomail-client@1.28.11 build:dev /home/michael-heuberger/code/videomail-client
> rollup -c env/dev/rollup.config.js -w

🚨   Cannot find module 'micromatch'
```

why does it complain about micromatch? i dont have it in my package.json?

**Comment by Rich-Harris** [comment]
Unfortunately it's not really possible to investigate without a simpler [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff). It sounds like *something* depends on `micromatch` — maybe a transitive dependency that's unaccounted for.

Re discussion forum — there's https://gitter.im/rollup/rollup. I've updated https://rollupjs.org so that it's easier to find via a 'chat' option in the nav:

<img width="777" alt="screen shot 2017-06-18 at 6 10 19 pm" src="https://user-images.githubusercontent.com/1162160/27264673-72931a9c-5451-11e7-9d97-5cb9ae502802.png">

**Comment by binarykitchen** [comment]
@Rich-Harris would it be possible to see which transitive dependency is wanting micromatch? And since I really want to fix this, how? Any suggestions would be very welcome.

(good for adding that forum link)

**Comment by jchook** [comment]
@binarykitchen, you can do this easily with yarn:

```
$ yarn why micromatch
yarn why v0.24.6
[1/4] 🤔  Why do we have the module "micromatch"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Reasons this module exists
   - "rollup-plugin-commonjs#rollup-pluginutils" depends on it
   - "rollup-watch#chokidar#anymatch" depends on it
info Disk size without dependencies: "48kB"
info Disk size with unique dependencies: "208kB"
info Disk size with transitive dependencies: "552kB"
info Number of shared dependencies: 17
✨  Done in 0.73s.
```

Not sure how to do it with npm other than manually tracing the tree via `npm list`.

Also, I am not getting the error you are with `npm run build:dev`. Seems to work fine. Maybe try nuking node_modules and re-installing.

**Comment by binarykitchen** [comment]
@jchook ah, the micromatch problem does not happen when you install with yarn but with npm.

this is bad. yarn and npm should behave the same when it comes to npm modules :(

**Comment by binarykitchen** [comment]
Think I better raise this in a separate ticket https://github.com/rollup/rollup/issues/1455
