### ISSUE TITLE
Do not exit when first build fails with watch option

### ISSUE THREAD

**Issue by matthieusieben** [rollup/rollup#1442]
When running rollup cli with the `--watch` option and the build fails (e.g. because of a syntax error), rollup will die directly.

If a first successful build was created, syntax errors appearing during following builds will not cause rollup to exit.

Could the behaviour of all the builds be the same ?

**Comment by Rich-Harris** [comment]
The issue here is that Rollup *can't know which files to watch* until there's been a successful build, because that information exists in the generated bundle. I don't think there's a good way around that unfortunately, so I'll close this as wontfix. Sorry!
