### ISSUE TITLE
Using function param named "async" as object shorthand throws

### ISSUE THREAD

**Issue by shlomiassaf** [rollup/rollup#1447]
```js
const value = 15;

function myValue(async, value) {
	console.log({async, value});
}

myValue(true, value);
```

![image](https://user-images.githubusercontent.com/5377501/27207105-c6cd7846-5244-11e7-8d44-4b2e2fcdcc47.png)

When the function parameter is called **async** and that parameter is later used as an object literal shorthand member, rollup will throw a general error.

I'm not the spec guy so testing in console, Chrome  58.0.3029.110 (64-bit) which support **async await**
 
![image](https://user-images.githubusercontent.com/5377501/27207144-fe881d90-5244-11e7-9515-f1952e0bd85b.png)

Looks like it's valid.

**Comment by Rich-Harris** [comment]
This is disallowed by Acorn — see http://astexplorer.net/#/gist/025356fabb6cabf6ca56d3b5e628278c/1ca8976c4821583dcc4af5fb974c4056f5bfca7c. I think it might be a bug — [this PR](https://github.com/ternjs/acorn/pull/562) looks like it fixes it. Hopefully we'll get a new release soon that fixes this.

**Comment by Rich-Harris** [comment]
This is [fixed](https://rollupjs.org/repl?version=0.47.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwdmFsdWUlMjAlM0QlMjAxNSUzQiU1Q24lNUNuZnVuY3Rpb24lMjBteVZhbHVlKGFzeW5jJTJDJTIwdmFsdWUpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZyglN0Jhc3luYyUyQyUyMHZhbHVlJTdEKSUzQiU1Q24lN0QlNUNuJTVDbm15VmFsdWUodHJ1ZSUyQyUyMHZhbHVlKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) in recent versions of Acorn, and hence Rollup
