### ISSUE TITLE
Arrow functions in es6 class

### ISSUE THREAD

**Issue by figachit** [rollup/rollup#1448]
I want to make pure es6 bundle without transformations but can't use arrow functions as class methods.
Is there any way to handle this?

Code
`class Lani {
  arrow = e => console.log(e);
}`

Error
`Unexpected token =`
`arrow = e => console.log(e);`

My `rollup.config.js` is pretty simple

`export default {
  entry: 'src/main.js',
  dest: 'app/bundle.js',
  format: 'es'
}`

**Comment by kilpatty** [comment]
Hey mind posting your solution here?

**Comment by lukastaegert** [comment]
To my knowledge, this is not part of ES2017 and thus not supported by our parser. You will need a transpiler like Babel to make this work

**Comment by guybedford** [comment]
This is currently a Stage3 feature. Personally I think it would be beneficial to support stage3 features through the appropriate Acorn plugins via a --stage3 flag or similar with that indicating that it implies unstable parsing to some degree.

**Comment by lukastaegert** [comment]
Maybe you are right. You know I am a little wary of these things but of course being able to test features early would probably not hurt.

Somewhat relatedly, I am still hoping for a good solution to be able to handle JSX natively. Maybe this could be a flag as well at some point, I'm sure this could be a killer feature for some library developers.

**Comment by guybedford** [comment]
https://github.com/rollup/rollup/pull/1857 would enable this at least.

Stage 3 can be quite a maintenance process so if there was a generic stage 3 Acorn plugin (wasn't @adrianheine working on that?), then that could either be documented directly or provided through a convenience flag. But at least having plugin injections gets us on the path.

**Comment by adrianheine** [comment]
Yeah, [I'm working on that](https://www.npmjs.com/package/acorn-stage3), but class fields are still missing. Allowing to inject acorn is a good thing to do anyway.

**Comment by TrySound** [comment]
Shouldn't all node types be traversed and considered?
https://github.com/rollup/rollup/tree/master/src/ast/nodes

**Comment by lukastaegert** [comment]
The current logic is that nodes missing from the above list will be internally represented as `UnknownNode`: https://github.com/rollup/rollup/blob/master/src/ast/nodes/UnknownNode.ts

These have the most conservative tree-shaking behaviour, i.e. they will always be kept. Additionally, all child nodes will be initialised properly via the defaults in https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/Node.ts

I think thus if new node types are injected, they should work although the result probably contains a little more dead code.

**Comment by guybedford** [comment]
@adrianheine it's a great project... I look forward to using it.
