### ISSUE TITLE
Clear definition of the difference between the plugin definition in `.babelrc` and `rollup.config.js`

### ISSUE THREAD

**Issue by kopax** [rollup/rollup#1449]
Hi everyone!

I know this is a documented topic and I've read the documentation with my people quite a few time and I am still misunderstanding the definition and how should be use the duplicate babel configuration.

I have for example in my `.babelrc` the following for bundling a `react` and `bootstrap-styled` application:

`.babelrc`:

    {
      "presets": [
        [
          "env",
          {
            "es2015": {
              "modules": false
            }
          }
        ],
        "react",
        "stage-0"
      ],
      "plugins": [
        "transform-es2015-modules-commonjs",
        "styled-components"
      ]
    }

`rollup.config.js`:

```js
babel({
    babelrc: false,
    exclude: 'node_modules/**',
    presets: [['es2015', { modules: false, loose: true }], 'stage-0', 'react'],
    plugins: [
      'external-helpers',
      'array-includes',
      'add-module-exports',
      'transform-object-rest-spread',
      'transform-class-properties',
      'styled-components',
      'transform-react-remove-prop-types',
      'transform-react-constant-elements',
      'transform-react-inline-elements',
    ].filter(Boolean),
```

Is there any logical explanation that could explain when **plugins** should be in `rollup.config.js` / `.babelrc` ?

Thanks in advance and thanks for sharing it's a very good tool.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
