### ISSUE TITLE
appveyor / windows testing

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#145]
so its not forgotten, appveyor was got working and discussed on this thread: https://github.com/rollup/rollup/pull/117#issuecomment-141782191

Rich created a appveyor project but was unable to create one for rollup/rollup - https://ci.appveyor.com/project/Rich-Harris/rollup-starter-project

 - [x] contact appveyor support to get a appveyor project created for rollup/rollup (or work out how to do it in the UI)
 - [x] add to github so it runs on pull requests
 - [x] fix the tests added since I last fixed them - `rollup function has-modules-array` is broken in windows again

**Comment by Victorystick** [comment]
It's building PRs. :+1:

**Comment by Rich-Harris** [comment]
The fine people at AppVeyor helped me figure out how to create a project for rollup/rollup (it was an authentication thing on GitHub's end), so the URL is now https://ci.appveyor.com/project/Rich-Harris/rollup. 3 for 3, so I'll close this – thanks @lukeapage

**Comment by lukeapage** [comment]
I've been puzzling why you get so many failures and I can't work it out. I've looked at other projects and I can't see them suffering as much. On my own projects I occasionally get failures, but nothing like what you are seeing.

If I were you I'd consider running only on one version of node if it doesn't improve.

Also have seen appveyor support node 4. I'll make a PR for discussion.
