### ISSUE TITLE
Have you considered releasing 1.0?

### ISSUE THREAD

**Issue by dariocravero** [rollup/rollup#1452]
Hi everyone,

I'm wondering if you've considered releasing rollup as `1.0.0` at some point. The reason why I'm asking this is because it is in major 0, dependencies are loosing automatic minor updates, like [rollupify](https://github.com/nolanlawson/rollupify/pull/59).

Rollup seems fairly stable and minor releases aren't breaking anything backwards by the looks of it. I wonder, are there any other reasons to keep at 0 or would you be happy to bump it to 1?

Thanks! :)

**Comment by bfred-it** [comment]
Duplicate of #769
