### ISSUE TITLE
I get "but could not be resolved – treating it as an external dependency"  - I use rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by PaulDevI** [rollup/rollup#1458]
Hi

I want to use roll-up with gulp, but I always get "but could not be resolved – treating it as an external dependency" and in the IIFE the import is treated as external variable.
I'm using gulp, because I want to apply roll-up to multiple entries.

What I'm doing wrong ?

```js
const rollup = require('gulp-rollup');
const resolve = require('rollup-plugin-node-resolve');

gulp.task('rollup', function () {
    return gulp.src('_01_src/js/form/*.js')
        .pipe(rollup({
                entry: '_01_src/js/form/controller.js',
                format: 'iife',
                plugins: [
                    resolve({
                        jsnext: true,
                        main: true,
                        browser: true
                    })
                ]
            })
        )

        .pipe(gulp.dest('_02_build/js/'));
});
```

**Comment by PaulDevI** [comment]
Hi

I want to use roll-up with gulp, but I always get "but could not be resolved – treating it as an external dependency" and in the IIFE the import is treated as external variable.
I'm using gulp, because I want to apply roll-up to multiple entries.

What I'm doing wrong ?

const rollup = require('gulp-rollup');
const resolve = require('rollup-plugin-node-resolve');

gulp.task('rollup', function () {
    return gulp.src('_01_src/js/form/*.js')
        .pipe(rollup({
                entry: '_01_src/js/form/controller.js',
                format: 'iife',
                plugins: [
                    resolve({
                        jsnext: true,
                        main: true,
                        browser: true
                    })
                ]
            })
        )

        .pipe(gulp.dest('_02_build/js/'));
});

**Comment by FelixRilling** [comment]
Hello,

Can you post the part of your code where you import the dependency, as well as your package.json?

**Comment by PaulDevI** [comment]
Hello,

I changed to rollup-stream(a wrapper around rollup) and the problem was fixed but now I'm trying to figure it out how to work with babel:

```
throw er; // Unhandled 'error' event
      ^
TypeError: file.isNull is not a function
```
```
gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/app.js',
        format: 'iife'
    }).pipe(babel({
            presets: ['es2015']
        }))
        .pipe(source('form.js'))
        // and output to ./dist/app.js as normal.
        .pipe(gulp.dest('_02_build/js'));
});
```

```
{
  "name": "buildingframework",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "devDependencies": {
    "babel-preset-es2015": "^6.24.1",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^4.0.0",
    "gulp-babel": "^6.1.2",
    "gulp-cli": "^1.3.0",
    "gulp-sass": "^3.1.0",
    "gulp-uglify": "^3.0.0",
    "gulp-watch": "^4.3.11",
    "rollup": "^0.43.0",
    "rollup-stream": "^1.21.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
I' just doing tests now so very simple:
```

model
export function ambor() {
    console.log('alpha');
}
```
controller

```
import {ambor} from './model';

export class Cat {
    constructor(name) {
        this.name = name;
    }
}

ap = new Cat();
let c = ambor();

```
```
app.js

import {ambor} from './model';
import {Cat} from './controller';
```

I'm trying to solve [this problem.](https://stackoverflow.com/questions/44625377/gulp-rollup-babel-transpile-model-view-controler-in-javascript)

**Comment by FelixRilling** [comment]
Hey,

In your new code, you seem to use babel like a gulp-plugin, not a rollup plugin (even though it is one).
Can you try changing
```js
gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/app.js',
        format: 'iife'
    }).pipe(babel({
            presets: ['es2015']
        }))
        .pipe(source('form.js'))
        // and output to ./dist/app.js as normal.
        .pipe(gulp.dest('_02_build/js'));
});
```

to

```js
gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/app.js',
        format: 'iife',
        plugins:[babel({
            presets: ['es2015']
        })]
     })
     .pipe(source('form.js'))
     // and output to ./dist/app.js as normal.
     .pipe(gulp.dest('_02_build/js'));
});
```

**Comment by PaulDevI** [comment]
I get:
```
Error: It looks like your Babel configuration specifies a module transformer. Please disable it. 
```
even if I setted .babelrc: 

```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

**Comment by PaulDevI** [comment]
I can use a different approach/solution that what I'm trying to use now if it can solve my problem. See the github link in my first post.

**Comment by CodingMeUp** [comment]
I get same problem

**Comment by CodingMeUp** [comment]
Hi.

https://github.com/jlengstorf/learn-rollup/issues/38

**Comment by CodingMeUp** [comment]
ok . I make i funny mistake .  import path error ..  but why show the message  " is imported by src\main.js, but could not be resolved" use "not found" much nice

**Comment by Rich-Harris** [comment]
We'll need a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) to have any chance of looking into this. When you create the repro, please don't include any Gulp stuff (it's not necessary anyway if you're only using it to create multiple bundles — as of 0.43 your rollup.config.js file can export an array of configuration objects).
