### ISSUE TITLE
Expose Config Arrays Through Programmatic API

### ISSUE THREAD

**Issue by destroyerofbuilds** [rollup/rollup#1460]
With pull request #1389 Rollup now supports a `rollup.config.js` file that exports an array of Rollup configuration objects. That support, though, is only available through Rollup's CLI.

In my particular use case I call Rollup programmatically using `rollem` so that I can call Rollup with an array of configuration objects.

I would like to transition to using Rollup directly, but can't because the array functionality, which is contained in [runRollup](https://github.com/rollup/rollup/pull/1389/files#diff-1f180723eb4efc40f86013ba982ec550R11) is not exposed when require'ing `rollup`.

Benefits of using Rollup's approach over Rollem (which are in addition to `rollem`'s support for arrays):
* Support for ES6 modules.
* Support for the `targets` option.

**Comment by bfred-it** [comment]
The cli only runs the array in a loop. Would this work for you?

```js
for (const config of configsArray) {
  rollup(config); ///
}
```

**Comment by destroyerofbuilds** [comment]
@bfred-it in your example, are you still using the default npm package entry point?

In that case a slightly more extensive example would be:

```javascript
var rollup = require( 'rollup' );
var configArray = require('./rollup.config.js');

for (const config in configArray) {
  rollup
    .rollup(config)
    .then(...)
}
```

**Comment by bfred-it** [comment]
That wouldn't work. `rollup.rollup()` does not accept a rollup config, the API is different. Also `for...in` is not for arrays.

But yeah, that's the idea: `for config of array, rollup.rollup(config)`

**Comment by bfred-it** [comment]
Related discussion: https://github.com/bahmutov/rollem/issues/44

**Comment by destroyerofbuilds** [comment]
> rollup.rollup() does not accept a rollup config

It should accept a rollup config. It will just ignore those configuration options not supported by the `rollup` function itself.

> Also for...in is not for arrays.

That was a typo on my part. Corrected in my example.

> But yeah, that's the idea: for config of array, rollup.rollup(config)

In that case I would need to do the following:
* Implement lines 68 through 92 for ES6 module support - https://github.com/rollup/rollup/blob/master/bin/src/runRollup.js#L68-L92
* Implement lines 256 through 264 for `target` support - https://github.com/rollup/rollup/blob/master/bin/src/runRollup.js#L68-L92
* Implement all the error handling setup within the CLI code.

**Comment by destroyerofbuilds** [comment]
Basically the Rollup CLI is fantastic, and I would love a way to call `rollup` programmatically.

```javascript
import rollup from 'rollup';

rollup.doWhatCliDoes({ config: true });
// or rollup.doWhatCliDoes({ config: true, watch: true });
```

**Comment by bfred-it** [comment]
> It should accept a rollup config. It will just ignore those configuration options not supported by the `rollup` function itself.

>In that case I would need to do the following:

Yeah, we're talking about the same thing, essentially. You put emphasis on the arrays, but I hope that the two APIs will converge: #1461 (also mentioned a while ago in https://github.com/rollup/rollup/issues/863#issuecomment-269304600)

**Comment by destroyerofbuilds** [comment]
Closing in favor of #1461, because really it's the entire packaging that makes the CLI such a great experience.

Your comment in #863 about _aggrevating_ is pretty much spot on in this case.

**Comment by bfred-it** [comment]
I re-read my comment and found the issue I was looking for: https://github.com/rollup/rollup/issues/761

Its resolution is not reassuring.
