### ISSUE TITLE
Extension-less external import should stay unchanged in amd/umd output

### ISSUE THREAD

**Issue by gunins** [rollup/rollup#1466]
Hi. not sure, if that's the bug, or there is some explained reason for that. In configuration I treat `./container/Container` as external dependency.

Issue is, in es6 import 
```javascript
import Container from './container/Container'
//....
```

Expected output for `amd` should be 

```javascript

define(['widget/App', './container/Container'], ...

```
but rollup generates

```javascript
define(['widget/App', './container/Container.js'],...

```
Problem requirejs not treat this path as relative any more.

There is reason by adding `.js` extension, in moduleId, or is a bug?

**Comment by bfred-it** [comment]
I think this is due to node-resolve mistakenly rewriting Container/index.js to Container.js

Is the file index.js?

**Comment by gunins** [comment]
No. problem is rollup adding extension `.js` module names in amd or cmjs are without `.js` and if in amd has extension `.js` like.

```javascript 
    define(['./container/Container.js'],...// .js is the problem
```

requirejs will not use as module name any more.

expected output in amd should be

```javascript
   define([ './container/Container'],... //you see no .js at the end
``` 

Because rollup generating module names with `.js` at the end, "amd" not resolving modules.

**Comment by bfred-it** [comment]
Is the file named `Container` without an extension?

**Comment by gunins** [comment]
File is named with extension, but "amd" (requirejs) use it without. 

There is problem explained https://github.com/requirejs/requirejs/issues/230

**Comment by gunins** [comment]
in "amd" (requirejs) modules with '.js' are not treated as modules.

**Comment by bfred-it** [comment]
Yeah, it's not `rollup` but `rollup-plugin-node-resolve`. Rollup does not map extension-less imports to `.js` like AMD and CJS resolvers.

`rollup-plugin-node-resolve` is probably resolving the `./container/Container` to `./container/Container.js` and passing it back to rollup, which in turn uses it to locate the external dependency.

**Comment by gunins** [comment]
I not use node resolve plugin. I not use any plugins. And issue is in file `src/finalisers/amd.js`

In line 21
```javascript
		( deps.length ? `[${deps.join( ', ' )}], ` : `` );
```
quick fix is 

```javascript
( deps.length ? `[${deps.map(_=>_.replace('.js','')).join( ', ' )}], ` : `` );
```
The reason I not added pull request is because in tests there is already is expected with `.js` extension. `relative-external-with-global` file `_expected/amd.js`

```javascript
define(['./lib/throttle.js']...
```

I can change this test and make pull request, just thought there was a reason.

**Comment by lukastaegert** [comment]
I know this is an old issue but I think it has been fixed now some time ago in that `.js` extensions are always suppressed for AMD imports, inparticular because I stumbled upon similar resolution issues with AMD for code-splitting. Can this issue be closed?
