### ISSUE TITLE
amd extension issue

### ISSUE THREAD

**Issue by gunins** [rollup/rollup#1467]
I create new issue, because cant reopen this one #1466

I not use node resolve plugin. I not use any plugins. And issue is in file `src/finalisers/amd.js`

In line 21
```javascript
		( deps.length ? `[${deps.join( ', ' )}], ` : `` );
```
quick fix is 

```javascript
( deps.length ? `[${deps.map(_=>_.replace('.js','')).join( ', ' )}], ` : `` );
```
The reason I not added pull request is because in tests there is already is expected with `.js` extension. `relative-external-with-global` file `_expected/amd.js`

```javascript
define(['./lib/throttle.js']...
```

I can change this test and make pull request, just thought there was a reason. 

but "amd"(requirejs)  will fail with `.js` at the end, because not treat it as a module.

**Comment by bfred-it** [comment]
Don't open identical PRs. If it's meant to be reopened it will be reopened.
