### ISSUE TITLE
Feature request : Add function for plugins to allow flag a module as external after resolution

### ISSUE THREAD

**Issue by CodeTroopers** [rollup/rollup#1469]
## Need
Flag all modules from a directory as external module. By example, i want that all modules under "node_modules" be imported as external.

## Proposal
A simple solution could be to allow glob path in external option.
A complex solution could be to add a function to allow to a plugin to flag the module as external after resolution by other plugin like noderesolve

**Comment by Rich-Harris** [comment]
You can pass a function as `options.external` instead of an array:

```js
// rollup.config.js
export default {
  entry: 'src/main.js',
  dest: 'bundle.js',
  format: 'iife',
  external: id => /node_modules/.test(id)
};
```

I *think* that would work, off the top of my head. A slightly more idiomatic way is to treat all the dependencies listed in package.json as external:

```js
// rollup.config.js
import pkg from './package.json;'

export default {
  entry: 'src/main.js',
  dest: 'bundle.js',
  format: 'iife',
  external: Object.keys(pkg.dependencies)
};
```

**Comment by CodeTroopers** [comment]
` external: id => /node_modules/.test(id)`
This doesn't work because id doesn't contain the path with "node_module"

**Comment by Rich-Harris** [comment]
Ah, I see. Well, you could do `id => id[0] !== '.'` maybe? Though for that matter, if you want all `node_modules` folders to be external, why not just omit the node-resolve plugin?

**Comment by CodeTroopers** [comment]
well with this `id => id[0] !== '.'`  i have no warn on resolution problem. I want to ensure that import are correctly resolved but flag modules as external

**Comment by Rich-Harris** [comment]
Afraid I don't understand at all what you're trying to do here! If a module is external, it doesn't get resolved. If you just want to check that an external module exists relative to the generated bundle, you could do it like this:

```js
// rollup.config.js
export default {
  ...,
  external: ['some-external-library'],
  plugins: [
    {
      resolveId(id) {
        if (id[0] === '.') return;
        require.resolve(id); // will throw if `id` can't be resolved
        // we don't need to return anything, it will just continue as normal
      }
    }
  ]
}
```

**Comment by CodeTroopers** [comment]
I want to build a bundle without including the dependencies (mark them as external) but check that the dependencies can be resolved in an environment which can be different depending on the developer or the context of the project (dependance installed in node_modules or in one or several directories depending of developper preferences or build server environment).
Overall I don't understand why rollup uses plugins to resolve path of dependencies and uses another mechanism to flag dependencies as external. I think rollup would must resolve the dependencies with plugins and then pass the resolved path to other plugins which can decide if the dependency is external or not.

**Comment by Rich-Harris** [comment]
Can you give a *concrete example* of what you mean — i.e., the API you envisage, some sample input code, and a sample output bundle? I'm completely failing to follow you!

It's definitely not a plugin's job to decide what should be bundled and what should be external (they could disagree!) — that's project-level configuration.

**Comment by CodeTroopers** [comment]
Well after thought, I think you are right and your argument is perfectly valid

> It's definitely not a plugin's job to decide what should be bundled and what should be external (they could disagree!) — that's project-level configuration.

So i decide to set explicitly the dependencies as external with an array. so my feature request can be closed
