### ISSUE TITLE
wrong bundle ordering when index.js is required by other files

### ISSUE THREAD

**Issue by xiechao06** [rollup/rollup#1471]
the problem is:
htmlparser2/lib/Freehandler.js depends on htmlparser2/lib/index.js ( contrary to most cases!!! ), but index is defined after FreeHandler.js. _(I guess "index.js" always put to the last)._

```javascript
var index$2 = DomHandler;

var DomHandler$1 = index.DomHandler; // index not defined
var DomUtils = index.DomUtils;
``` 
I have created a repository, please check: https://github.com/xiechao06/rollup-htmlparser2-failed
to recreate the problem: 
```
$ npm install
$ gulp
$ node dist/index.js 
```

**Comment by Rich-Harris** [comment]
Unfortunately htmlparser2 is written in a style that is impossible to use with Rollup. Your best bet, if there isn't an alternative package available, might be to bundle htmlparser2 with something like Browserify before importing it.
