### ISSUE TITLE
umd + moduleName: Maybe use '[' ']' is better than .split( '.' ) ?!

### ISSUE THREAD

**Issue by atlastorm** [rollup/rollup#1473]
When Im trying to rollup my package into "umd", I set the options like this:
```
    const packageJSON = require('../package.json');
    ...
    entry: './src/index.js',
    format: 'umd',
    exports: 'named',
    moduleName: `${packageInfo.scope}.${packageInfo.name}.${packageJSON.version}`,
    dest: `./standalone/${packageJSON.version}/index.js`,
    ...
```
What I expected is : 
```
root["NAMESPACE"] = root["NAMESPACE"] || {}, root["NAMESPACE"]["MODULENAME"] = root["NAMESPACE"]["MODULENAME"] || {}, root["NAMESPACE"]["MODULENAME"]["0.0.1"] = factory(root["React"]);
```
(this is the result when I use Webpack2)
BUT, in rollup, because the  **packageJSON.version = 0.0.1** , the result I get is:
```
(factory((global.NAMESPACE = global.NAMESPACE || {}, global.NAMESPACE.MODULENAME = global.NAMESPACE.MODULENAME || {}, global.NAMESPACE.MODULENAME['0'] = global.NAMESPACE.MODULENAME['0'] || {}, global.NAMESPACE.MODULENAME['0']['0'] = global.NAMESPACE.MODULENAME['0']['0'] || {}, global.NAMESPACE.MODULENAME['0']['0']['1'] = global.NAMESPACE.MODULENAME['0']['0']['1'] || {}),global.React));
```
['0']['0']['1'] is absolutely not what I want. When I read the code of rollup.js, I found this: 
```
var parts = name.split( '.' );
var last = property( parts.pop() );
var acc = 'global';
return parts
	.map( function (part) { return ( acc += property( part ), (acc + " = " + acc + " || {}") ); } )
	.concat( ("" + acc + last) )
	.join( ', ' );
```
Because of the **split( '.' )**, it seems there is no way I can get a result like : `root["NAMESPACE"]["MODULENAME"]["0.0.1"] = factory(root["React"])`

**What's the solution here? Thanks for any tips!**

**Comment by bfred-it** [comment]
`0.0.1` is a poor name for a variable. I'm curious, why are you doing that? To avoid collisions among multiple-loaded versions?

**Comment by atlastorm** [comment]
Yes, Im working on a large platform, which can create H5 pages by non-developers，severial co-workers develop their own components for the same platform. 
**Each component has to be maintained**, in this way, we need 'namespace', 'name' and 'version' to  define a component.
    Im thinking about use 'hash' instead of version, but, there are already dozens of components outside, replace the 'version' of all the components cost too much.

**Comment by bfred-it** [comment]
#1472 is introducing changes to this part of the code. Let's see how that develops. Perhaps give it a go, it might solve your issue.

**Comment by Andarist** [comment]
@bfred-it it wont help, `rollup` is treating this one as a namespaced name and will split it by `.` to subproperties.

What can be done here (I think):
- possibility to glue a string by putting it in `""`, i.e. by providing `moduleName: '"0.0.1"'` instead of `moduleName: "0.0.1"`. This would only need better namespacing logic than simple `.split('.')` as `""` would have to be detected
- possibility to pass `moduleName` as function which would allow people to provide whatever they really want, would need to establish what should be returned from such a function so iife/umd finalisers could properly unpack it

**Comment by bfred-it** [comment]
`moduleName: '"0.0.1"'` feels like a better+shorter option, also because while the function is a clever workaround, people might end up using the function to make it dynamic (unnecessarily) like  `moduleName: () => 'lib.method'` and wonder why the function doesn't support splitting the same way as the string does.

**Comment by Andarist** [comment]
I might find some time to implement this. What formats should be supported though?

The most hardcore atm is `foo.@scoped/npm-package.bar.why-would-you-do-this` which gets autowrapped with brackets where neccessary so it becomes `global.foo['@scoped/npm-package'].bar['why-would-you-do-this']`

Should we support parts of the `moduleName` to be somehow glued with `""` (which would look weird - imagine `foo.@scoped/npm-package."bar.why"-would-you-do-this`) or just a simple glue whole or nothing?

**Comment by bfred-it** [comment]
Up to you. What you're suggesting might be _as easy as_ `name.split('"')` and then: `.split('.')` the strings at odd positions and do nothing for the ones in even positions.

e.g.

```js
'foo.@scoped/npm-package."bar.why"-would-you-do-this'.split("")
// becomes
[
'foo.@scoped/npm-package.', // .split('.') this
'bar.why', // leave as is
'-would-you-do-this' // .split('.') this
]

**Comment by bfred-it** [comment]
Or it could support real JS syntax as a string:

```js
foo['@scoped/npm-package']['bar.why']['-would-you-do-this']
// as a string:
moduleName: "foo['@scoped/npm-package']['bar.why']['-would-you-do-this']"
```

**Comment by atlastorm** [comment]
In my opinion, use ' . ' or ' " ' to split a STRING looks a bit weird. ARRAY may be a better choise:
```
moduleName: ['foo', '@scoped/npm-package', 'bar.why', '-would-you-do-this', '0.0.1'],
```
Does not it looks pleasant? 

Or, from another perspective, a string, ' , ' is better than ' . ' and ' " '. I think no one will use ' , ' to name their package ( maybe? ), so the moduleName may look like:
```
moduleName:  `foo,@scoped/npm-package,bar.why,-would-you-do-this,0.0.1`,
```

**Comment by bfred-it** [comment]
`.` is a perfectly fair separator given that it's the javascript object property separator. 

The array sounds good too but that doesn't work from CLI. 

The comma makes less sense than a period. I think that the best solution is to make it something people already know: actual javascript dot/bracket notations. 

Rollup already naively supports the dot notation, so it only makes sense to extend that with bracked notation. 

The code I suggested in my last is exactly your intended result, for you it would be:

```
moduleName: 'NAMESPACE.MODULENAME["0.0.1"]'
```

It's a real, valid javascript expression. We don't need to introduce custom syntax that people have to learn when there's something perfectly valid for it already.

**Comment by Andarist** [comment]
After a thought it might take more time to implement this for me than I initially thought. If somebody wants to do it faster - that's fine, take it :) Just let me know cause I'm planning to do it eventually, just aint sure when.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
