### ISSUE TITLE
options external not work in node_modules dir

### ISSUE THREAD

**Issue by limerickgds** [rollup/rollup#1481]
rollup.config.js:
```js
let nodeResolve = require('rollup-plugin-node-resolve');
let commonjs = require('rollup-plugin-commonjs');
let babel = require('rollup-plugin-babel');

const externals = {
    'react': 'React',
    'react-dom': 'ReactDOM'
};

module.exports = {
    entry: 'src/index.js',
    format: 'umd',
    dest: 'dist/tarot-ext.js',
    moduleName: 'tarot-ext',
    plugins: [
        nodeResolve({
            jsnext: true,
            main: true
        }),
        commonjs({
            include: 'node_modules/**'
        }),
        babel({
            exclude: 'node_modules/**',
            plugins: [
                "transform-react-jsx",
                "external-helpers"
            ],
            presets: [
                "react", [
                    "es2015",
                    {
                        modules: false
                    }
                ],
                "stage-0"
            ],
            babelrc: false
        })
    ],
    globals: externals,
    external: Object.keys(externals)
};
```
npm lib react-redux import react ,so external: ['react'] not work。
it only ignore my source file `import React from 'react'`。

when i change commonjs exclude './node_modules/react';it also has error。
how to config external ?

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by chyzwar** [comment]
Have similar issue, reproduction can be done, I am trying to ignore some modules in node_modules but I still get warnings/

**Comment by Rich-Harris** [comment]
@chyzwar I think your repro uses private packages?

**Comment by chyzwar** [comment]
Yes, these packages are not published, These are scoped packages that I pull from Github?
I would assume that external would ignore them regardless? they are still installed in node_modules.

**Comment by Rich-Harris** [comment]
It means I can't install your repro's dependencies, which is a prerequisite to debugging it. Please create a *minimal* repro - nothing that isn't necessary to demonstrate the issue

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
