### ISSUE TITLE
Nested functions aren't renamed to avoid clashing with the exports of re-exported namespaces

### ISSUE THREAD

**Issue by isiahmeadows** [rollup/rollup#1488]
Apologies for the lengthy title. [Here's a minimal repro](https://rollupjs.org/repl?version=0.45.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3Qm5zJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28uanMlNUMlMjIlNUNuJTVDbmVmZmVjdCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0ZnVuY3Rpb24lMjBjcmVhdGUoKSUyMCU3QiU1Q24lNUN0JTVDdG5zLmNyZWF0ZSgpJTVDbiU1Q3QlN0QlNUNuJTVDbiU1Q3RjcmVhdGUoKSU1Q24lN0QpJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJucy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGNyZWF0ZSgpJTIwJTdCJTIwZWZmZWN0KCklMjAlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG5zJTIwZnJvbSUyMCU1QyUyMi4lMkZucy5qcyU1QyUyMiU1Q25leHBvcnQlMjAlN0JucyU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==). Ran into it while creating a local wrapper for an export inside of a test's suite callback.

Note the fact the inner `create` was made infintely recursive because of this, and the named export is no longer used.

**Comment by Rich-Harris** [comment]
Thanks — is fixed in the upcoming release
