### ISSUE TITLE
Throw on Warning

### ISSUE THREAD

**Issue by gauntface** [rollup/rollup#1493]
I've been using Rollup in a project that is using Lerna to manage package dependencies.

The flow of this set up is:

1. Call `lerna bootstrap`
1. Lerna will run `npm run prepublish` in each package as well as `npm link`
1. In the `npm run prepublish` step I have a rollup call: `"prepublish": "rollup -c"`

What I noticed is that warnings are swallowed by Lerna and actually resulted in a bad build, is there anyway to throw on a warning with the CLI?

**Comment by Rich-Harris** [comment]
yep — you can use a custom `onwarn` handler for that:

```js
// rollup.config.js
export default {
  // ...
  onwarn: warning => {
    throw new Error(warning.message);
  }
};
```
