### ISSUE TITLE
"process.hrtime is not a function" in browser rollup 0.45.2

### ISSUE THREAD

**Issue by sijakret** [rollup/rollup#1495]
when i try to use rollup in the browser i get:

> Uncaught (in promise) TypeError: process.hrtime is not a function
>     at timeStartHelper (rollup.browser.js:33)
>     at timeStart (rollup.browser.js:48)
>     at rollup (rollup.browser.js:10484)
>     ...

after installing browser-process-hrtime and "shiming" process.hrtime something like the following it works

process.hrtime = require('browser-process-hrtime');
import { rollup } from 'rollup/dist/rollup.browser.js';

is this intentional or is some handling missing for the client/browser scenario?

**Comment by Rich-Harris** [comment]
It sounds like `process` is being defined somewhere? Normally `timeStartHelper` uses `window.performance.now` in the browser, but it does that because `process` is normally undefined: https://github.com/rollup/rollup/blob/master/src/utils/flushTime.js
