### ISSUE TITLE
Support for globals in cjs or amd modules

### ISSUE THREAD

**Issue by isidrok** [rollup/rollup#1499]
Hello, I have been using rollup to bundle an Angular 2 application. I have a vendor that exposes the different dependencies and two modules: App and Bill. My bundles are in umd format and I came across with the following problem:

When I tried to lazyload Bill from App using SystemJS I noticed that SystemJS is not compatible with iife format, so it defaults to amd, but since globals are not supported in this format it tries to get all the dependencies again. ( This is just an example to illustrate why could we need globals option in other module formats).

I bundled the modules again using cjs and manually changed the lines:
```javascript
var _angular_core = require("@angular/core");
var _angular_router = require("@angular/router");
// ...
```
By:
```javascript
var _angular_core = vendor._angular_core;
var _angular_router = vendor._angular_router;
// ...
```
And the problem was solved.

I was wondering why is there only globlas support for iife modules and if it is planned to add it in the future.

**Comment by Rich-Harris** [comment]
I've just published a plugin called [rollup-plugin-virtual](https://github.com/rollup/rollup-plugin-virtual) which might be able to solve this without making AMD/CJS output more complex — try using it like so:

```js
// rollup.config.js
import virtual from 'rollup-plugin-virtual';

export default {
  // ...
  plugins: [
    virtual({
      '@angular/core': 'export default vendor._angular_core;',
      '@angular/router': 'export default vendor._angular_router;',
    })
  ]
};
```

**Comment by isidrok** [comment]
Hello, I'm actually trying to make it work with this simple example:

```javascript
import {Component} from '@angular/core';
console.log(Component);
```
Using this config:

```javascript
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import virtual from 'rollup-plugin-virtual';

export default {
    entry: 'index.js',
    dest: 'dist/index.js',
    format: 'umd',
    moduleName: 'index',
    external: [
         '@angular/core'
    ],
    plugins: [
        resolve(),
        commonjs({
            include: 'node_modules/**'
        }),
        virtual({
            '@angular/core': 'export default vendor._angular_core'
        }),
        babel({
            exclude: [
                'node_modules/**'
            ]
        })
    ]
};
```
The thing is when I use the external option the output is the same as if I was not using the plugin, it will try to fetch the module without using the vendor, and if I don't use external then it will put everything into the bundle. 

Now without using external and calling virtual plugin before the resolve and commonjs ones (which I think is the way to go) I get the following error: __Error: 'Component' is not exported by ```virtual:@angular/core```__

Finally I have tried to make it work like in the readme example, importing default from ```@angular/core```
and this time I got the following error: __Error: 'default' is not exported by ```node_modules/@angular/core/@angular/core.es5.js```__ which seems quite estrange to me since it is no longer looking inside ```virtual:@angular/core```.

So don't know why is it not working like in the example, which works just fine, any idea?

Btw I would like to know why are not globals supported by default in cjs/amd modules, is it because of the complexity, to follow an specification or is it just that there is not need at all? 
Thanks!

**Comment by Rich-Harris** [comment]
Try putting the `virtual` plugin before the `node-resolve` one, so that it doesn't get 'intercepted'

**Comment by isidrok** [comment]
Yeah already did that, and tried without using any other plugin but the result was the same error, ```Component``` is not exported by ```virtual:@angular/core```.

I just got it to work by using virtual as the first plugin and then importing default from the package:
```javascript
// works
import core from '@angular/core';
console.log(core.Component);
// doesn't work
import {Component} from '@angular/core';
console.log(Component);
```
So it seems like the problem is with the member imports.

**Comment by Rich-Harris** [comment]
Ah, sorry — missed the part where you said you'd tried that.

Yeah, if there are named imports then you'd presumably need to do something like this:

```js
virtual({
  '@angular/core': `
    export const Component = vendor._angular_core.Component;
    // and so on...
  `
})
```

**Comment by isidrok** [comment]
Oh, I understand the plugin now, will try it out later and edit with the results.

Thank you!

**Comment by Rich-Harris** [comment]
Great — will close this issue, thanks
