### ISSUE TITLE
Console colour not reset after error message

### ISSUE THREAD

**Issue by ilmiont** [rollup/rollup#1500]
Running on Bash on Ubuntu on Windows.

When a syntax error is found during rollup, the console colour is changed to bright white to highlight this in the source.

Rollup does not then revert the console colour to the usual dimmer shade of white after the output.

Expected behaviour: The Rollup error output should be highlighted in bright white. The following console output - from Rollup or other programs - should then revert to the regular dim white console colour. I always think it best if you leave the console "as you found it."

**Comment by Rich-Harris** [comment]
The CLI is just using [chalk](https://github.com/chalk/chalk) — it sounds like this *might* be a bug in chalk?

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
