### ISSUE TITLE
Return promise from config file

### ISSUE THREAD

**Issue by amatiasq** [rollup/rollup#1503]
My config is using async operations to read the file system and exports a promise to be fulfilled with the config instead of the config itself but looks like rollup is not prepared for that:

> 🚨   Config file must export an options object
> https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file

Would it be hard to support promises on config file output?

**Comment by Rich-Harris** [comment]
It should actually be fairly straightforward — [this is the relevant block of code](https://github.com/rollup/rollup/blob/e8da9f54a11679b91b1bc9c913db857a616aa6e8/bin/src/run/index.js#L89-L114), which I think just needs to be more like this:

```diff
.then( ({ code }) => {
  // temporarily override require
  const defaultLoader = require.extensions[ '.js' ];
  require.extensions[ '.js' ] = ( m, filename ) => {
    if ( filename === config ) {
      m._compile( code, filename );
    } else {
      defaultLoader( m, filename );
    }
  };

-  const configs = require( config );
+  return require( config );
+})
+.then( configs => {
  if ( Object.keys( configs ).length === 0 ) {
    handleError({
      code: 'MISSING_CONFIG',
      message: 'Config file must export an options object, or an array of options objects',
      url: 'https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file'
    });
  }

  require.extensions[ '.js' ] = defaultLoader;

  const normalized = Array.isArray( configs ) ? configs : [configs];
  return execute( normalized, command );
})
.catch( handleError );
```

Would you be up for submitting a PR? (With a test 😀 )
