### ISSUE TITLE
UMD Module replaces global d3 instead of updating it.

### ISSUE THREAD

**Issue by lukekentwell** [rollup/rollup#1504]
Hi everyone, 

I am working on a d3.js plugin following the old plugin template provided by Mike. Today I decided to update my rollup-js to get the latest improvements and found that it broke my build :D.

I went from 0.34.8 to 0.45.2, and found that in the header of module it no longer checks for the existence of the d3 global but instead replaces it. you can see the difference in the two version outputs below (ive tried to highlight). 

I'm not sure if this is intended and there is a new setting/config I should be using or if this is a bug?

any help would be much appreciated.

## Command
<details>
rollup -c -m inline -g d3-selection:d3,d3-collection:d3,d3-dispatch:d3,d3-scale:d3,d3-array:d3,d3-transition:d3,d3-shape:d3,is_js:is,lodash:_
</details>

## rollup.config.js
<details>
import node from "rollup-plugin-node-resolve";

export default {
    entry: "index.js",
    format: "umd",
    dest: "build/d3-charts.js",
    moduleName: "d3",
    plugins: [
        node()
    ]
};
</details>

## Output
<details>
  <summary>v0.34.8</summary>
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('lodash'), require('is_js'), require('d3-dispatch'), require('d3-selection'), require('d3-transition'), require('d3-scale'), require('d3-collection'), require('d3-array')) :
    typeof define === 'function' && define.amd ? define(['exports', 'lodash', 'is_js', 'd3-dispatch', 'd3-selection', 'd3-transition', 'd3-scale', 'd3-collection', 'd3-array'], factory) :
    (factory((<b>global.d3 = global.d3 || {}</b>) ,global._,global.is,global.d3,global.d3,global.d3,global.d3,global.d3,global.d3));
}(this, (function (exports,_,is,d3Dispatch,d3Selection,d3Transition,d3Scale,d3Collection,d3Array)
</details>

<details>
  <summary>v0.45.2</summary>
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('lodash'), require('is_js'), require('d3-dispatch'), require('d3-selection'), require('d3-transition'), require('d3-scale'), require('d3-collection'), require('d3-array')) :
	typeof define === 'function' && define.amd ? define(['exports', 'lodash', 'is_js', 'd3-dispatch', 'd3-selection', 'd3-transition', 'd3-scale', 'd3-collection', 'd3-array'], factory) :
	(factory((<b>global.d3 = {}</b>), global._,global.is,global.d3,global.d3,global.d3,global.d3,global.d3,global.d3));
}(this, (function (exports,_,is,d3Dispatch,d3Selection,d3Transition,d3Scale,d3Collection,d3Array)
</details>

**Comment by Rich-Harris** [comment]
There is a new setting — it's called `extend`, it was designed for just this scenario. [Here's](https://github.com/rollup/rollup/issues/827) the discussion that led to it, and [here's](https://github.com/rollup/rollup/pull/1472) the PR. Looks like we haven't got round to documenting it yet, sorry 😬

**Comment by lukekentwell** [comment]
Hi @Rich-Harris, 

Thankyou so much for the speedy reply, I will see if I can get it working now :D.
