### ISSUE TITLE
Cannot import noty

### ISSUE THREAD

**Issue by desfero** [rollup/rollup#1506]
Hello @Rich-Harris , 
cannot get rid of error while importing noty library: `'noty' is imported by src\main.js, but could not be resolved – treating it as an external dependency`

Example can be found here: https://github.com/desfero/rollup-noty-error (based on rollup-starter-app)

Thanks a lot for help :)

**Comment by pshrmn** [comment]
@desfero Your `cjs`/`es` configuration needs to either include `noty` in the `external` array (if you do not want to include Noty in the bundle) or add a `plugins` array with the the `resolve` and `commonjs` plugins (if you want to include Noty in the bundle).

**Comment by desfero** [comment]
@pshrmn i want to include noty in the bundle. `resolve` and `commonjs` is already in `plugins` section.

**Comment by pshrmn** [comment]
@desfero You have two configs:
```js
{
  entry: 'src/main.js',
  dest: pkg.browser,
  format: 'umd',
  moduleName: 'howLongUntilLunch',
  plugins: [
    resolve(), // so Rollup can find `ms`
    commonjs() // so Rollup can convert `ms` to an ES module
  ]
},
```
and
```js
{
  entry: 'src/main.js',
  external: ['ms'],
  targets: [
    { dest: pkg.main, format: 'cjs' },
    { dest: pkg.module, format: 'es' }
  ]
}
```
Only the first one has the plugins. Add them to the second one and it should work as you expect it to.

**Comment by desfero** [comment]
@pshrmn Thanks a lot :) Works
