### ISSUE TITLE
Stale JSDocs

### ISSUE THREAD

**Issue by thysultan** [rollup/rollup#1509]
Ran into a problem affecting closure-compiler comments where Rollup would change function/variable/parameter names but not update related JSdocs.

For example:

```js
/**
 * @constructor
 */
function Foo () {}
/**
 * @param {Foo} element
 */
function Bar () {}
```

Might produce

```js
/**
 * @constructor
 */
function Foo$1 () {}
/**
 * @param {Foo} element
 */
function Bar () {}
```

But `Foo` in`@param {Foo} element` remains un-changed unlike `Foo$1`

**Comment by Announcement** [comment]
Actually this raises an issue of how do we want to go about handling this, do we want to
- integrate jsdoc support through a plugin, so you can add the jsdoc alias tag...
- make rollup handle the renaming process differently so that the final function maintains the original name for exposure...

The second is much more elegant but that might be a breaking change and a bit more complicated to implement.

**Comment by olivbau** [comment]
Any news about this ?

**Comment by guybedford** [comment]
This does sound like a feature best handled through a plugin transform, at least initially. Did anyone attempt this?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
