### ISSUE TITLE
Unused imports when using Import As statement

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup#1511]
When I choose output format to `es`, I am getting an unused import when ever I use the `* as` in my import statement.

example
```js
import * as _ from 'lodash';

_.isEmpty([]);
```

will output to 
```js
import { isEmpty } from 'lodash';
import * as _ from 'lodash';

isEmpty([]);

```

Demo: https://rollupjs.org/repl?version=0.45.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMF8lMjBmcm9tJTIwJ2xvZGFzaCclM0IlNUNuXy5pc0VtcHR5KCU1QiU1RCklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by Rich-Harris** [comment]
fixed in 0.46.3 — thanks
