### ISSUE TITLE
Request: Supporting Acorn JSX

### ISSUE THREAD

**Issue by trueadm** [rollup/rollup#1512]
This is a feature request for adding JSX support to Rollup by potentially having some form of option to enable the Acorn JSX plugin or something similar.

I'm working on a project where it would be ideal to bundle modules that contain JSX, keeping the JSX intact so the resulting bundle still contains the original JSX. For this experiment, I do not want to transform the JSX via Babel etc before making a bundle.

Is this something that could be possible without too much hassle? I looked through the codebase but didn't see any obvious places this could be done without potentially breaking the existing logic.

**Comment by kzc** [comment]
@trueadm Should be fairly straight-forward. JSX from an AST point of view is analogous to ES6 template literals with embedded subexpressions.

To add JSX support to Rollup you'd have to:
* Register the `acorn-jsx` plugin similar to [how Bublé does it](https://gitlab.com/Rich-Harris/buble/blob/master/src/index.js).
* [Make](https://github.com/rollup/rollup/blob/master/src/ast/nodes/TemplateLiteral.js) and [register](https://github.com/rollup/rollup/blob/master/src/ast/nodes/index.js#L71) JSX class(es) - just the ones where you'd want indentation exclusion zones.

Symbol references within JSX `{ }` blocks ought to be recognized by Rollup out of the box as part of the AST.

You may want to add support for `acorn-object-spread` at the same time. Again, use Bublé as a guide.

**Comment by trueadm** [comment]
@kzc Thanks for the help. I've run into an issue doing this though. I get the following error:

```sh
/Users/domgan/Projects/rollup/node_modules/acorn-jsx/inject.js:10
  var tc = acorn.tokContexts;
                ^
TypeError: Cannot read property 'tokTypes' of undefined
```
Any ideas what might fix this particular error?

**Comment by kzc** [comment]
The following patch passes all Rollup tests. By default `acorn-jsx` includes `acorn`. Ignore the Rollup build warnings which appear to be known issues. 
```patch
diff --git a/package.json b/package.json
index f2a44f3..f78e231 100644
--- a/package.json
+++ b/package.json
@@ -46,6 +46,7 @@
   "homepage": "https://github.com/rollup/rollup",
   "devDependencies": {
     "acorn": "^5.1.1",
+    "acorn-jsx": "^4.0.1",
     "buble": "^0.15.1",
     "chalk": "^1.1.3",
     "codecov.io": "^0.1.6",
diff --git a/rollup.config.js b/rollup.config.js
index cc0b9ba..71ccd79 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -1,5 +1,6 @@
 import { readFileSync } from 'fs';
 import buble from 'rollup-plugin-buble';
+import commonjs from 'rollup-plugin-commonjs';
 import nodeResolve from 'rollup-plugin-node-resolve';
 import replace from 'rollup-plugin-replace';
 
@@ -21,8 +22,9 @@ var banner = readFileSync( 'src/banner.js', 'utf-8' )
 export default {
        entry: 'src/rollup.js',
        plugins: [
+               commonjs(),
                buble({
-                       include: [ 'src/**', 'node_modules/acorn/**' ],
+                       include: [ 'src/**', 'node_modules/acorn-jsx/**', ],
                        target: {
                                node: '0.12'
                        }
diff --git a/src/Module.js b/src/Module.js
index bb86854..502160e 100644
--- a/src/Module.js
+++ b/src/Module.js
@@ -1,4 +1,4 @@
-import { parse } from 'acorn';
+import acorn from 'acorn-jsx';
 import MagicString from 'magic-string';
 import { locate } from 'locate-character';
 import { timeStart, timeEnd } from './utils/flushTime.js';
@@ -17,11 +17,12 @@ import ModuleScope from './ast/scopes/ModuleScope.js';
 
 function tryParse ( module, acornOptions ) {
        try {
-               return parse( module.code, assign({
+               return acorn.parse( module.code, assign({
                        ecmaVersion: 8,
                        sourceType: 'module',
                        onComment: ( block, text, start, end ) => module.comments.push({ block, text, start, end }),
-                       preserveParens: false
+                       preserveParens: false,
+                       plugins: { jsx: true, },
                }, acornOptions ));
        } catch ( err ) {
                module.error({
```
```
var a = <Hello>{side() + effect()}</Hello>;
function bar(x) {
    return <Bar>{ x * x }</Bar>;
}
function foo(x) {
    return <Foo>{ side_effect(x) }</Foo>;
}
var b = <World>no side effects</World>;
console.log(bar(7));
```
```
$ bin/rollup j.js -f es
var a = <Hello>{side() + effect()}</Hello>;
function bar(x) {
    return <Bar>{ x * x }</Bar>;
}
console.log(bar(7));
```
This patch does not incorporate any new JSX classes. You'll have to decide which one(s) are required (if any) for indentation exclusion zones.

I'll leave adding `acorn-object-spread` as an exercise for the reader.

**Comment by trueadm** [comment]
@kzc Thank you so much :)

**Comment by kzc** [comment]
@trueadm It just occurred to me that you'll need to bind references of JSX tags (and possible other values) against regular JS classes/functions/variables. Otherwise if `class Bar {}` were added to the example above it'd be dropped by rollup since it was not referenced. Take a look at https://github.com/rollup/rollup/blob/master/src/ast/nodes/Identifier.js as an implementation guide. 

JSX `{` subexpression `}` identifiers are already bound since they are normal JS expression nodes.

**Comment by kzc** [comment]
This may not be 100% correct, but will give you a start:
```js
$ cat src/ast/nodes/JSXIdentifier.js

import Node from '../Node.js';

export default class JSXIdentifier extends Node {
    bind ( scope ) {
        this.declaration = scope.findDeclaration( this.name );
        this.declaration.addReference( this );
    }

    gatherPossibleValues ( values ) {
        values.add( this );
    }

    run () {
        if ( this.declaration ) this.declaration.activate();
    }
}
```
Register the class in `src/ast/nodes/index.js`.
```js
$ cat jref.js 

function Foo() {}
class Bar {}
class Unused {}
var a = <Foo><Bar/></Foo>;
var b = <Bar/>;
console.log(a);
```
```js
$ bin/rollup jref.js -f es

function Foo() {}
class Bar {}
var a = <Foo><Bar/></Foo>;
console.log(a);
```

**Comment by kzc** [comment]
The `acorn-jsx` approach [above](https://github.com/rollup/rollup/issues/1512#issuecomment-320690514) (after rebasing) no longer works as of [`rollup@0.46.0`](https://github.com/rollup/rollup/commit/b159c46048eb250326af683b84d8d4a0a62fcecd) - the rollup build goes into an infinite loop in `rollup -c` consuming 100% CPU. Not sure what recent commit broke it.

@Rich-Harris Any ideas?

**Comment by lukastaegert** [comment]
The way .bind() works has changed as of this release. Basically, scope is no longer passed as a variable to .bind(). Instead, you should now be able to access this.scope in your nodes instead for the same effect. That is, if you did not override .initialise(). I hope this helps a little, unfortunately I do not have a computer here right now to check.

**Comment by kzc** [comment]
@lukastaegert Thanks, but even the first patch goes into an infinite loop without any JSX classes when just trying to import `acorn-jsx`. What you're suggesting would apply to the second patch to resolve JSXIdentifiers, but it doesn't get that far.

**Comment by lukastaegert** [comment]
Oh, I see. I would like to take a deeper look but unfortunately I am on vacation and only have a phone and limited time :P but I will take a look in a few days if your issue does not resolve until then. In the meantime it would be really interesting if you could sprinkle some logs in Rollup' code to narrow down where this loop might be happening :)

**Comment by kzc** [comment]
I found the problem - `commonjs()` was repeated twice in `rollup.config.js`. It was introduced into `master` sometime after my patch was made and there was no merge conflict when rebased. Repeating `commonjs()` will cause an infinite loop apparently.

Hmm - I see the CLI has changed. The following `rollup` command used to warn and default to `-f es`, but now it errors out:
```
$ cat test.js
var unused = 1, hello = "Hello", world = "Earth";;
console.log(`${hello} ${world}`);
```
```
$ bin/rollup test.js 

test.js → stdout...
[!] Error: You must supply an output format
https://github.com/rollup/rollup/wiki/JavaScript-API#format
Error: You must supply an output format
```
I think `es` was a reasonable default. Oh well.
```
$ bin/rollup test.js -f es

test.js → stdout...
var hello = "Hello";
var world = "Earth";
console.log(`${hello} ${world}`);
created stdout in 28ms
```
Is there any way to disable the verbose info messages sent to stderr?

* `test.js → stdout...`
* `created stdout in 28ms`

In my opinion it should only be emitted with a `--verbose` flag.

**Comment by kzc** [comment]
FWIW, here's the rebased combined JSX patch against `v0.46.1` (8969272c93e9cd285db6e9f4443216630193a5f0):
```patch
diff --git a/package.json b/package.json
index 66944a0..ec33755 100644
--- a/package.json
+++ b/package.json
@@ -46,6 +46,7 @@
   "homepage": "https://github.com/rollup/rollup",
   "devDependencies": {
     "acorn": "^5.1.1",
+    "acorn-jsx": "^4.0.1",
     "buble": "^0.15.1",
     "chalk": "^1.1.3",
     "codecov.io": "^0.1.6",
diff --git a/rollup.config.js b/rollup.config.js
index 396e71e..bdf7698 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -23,7 +23,11 @@ export default {
        entry: 'src/node-entry.js',
        plugins: [
                buble({
-                       include: [ 'src/**', 'node_modules/acorn/**' ],
+                       include: [
+                               'src/**',
+                               'node_modules/acorn/**',
+                               'node_modules/acorn-jsx/**',
+                       ],
                        target: {
                                node: '0.12'
                        }
diff --git a/src/Module.js b/src/Module.js
index 4a1cf1f..63dc816 100644
--- a/src/Module.js
+++ b/src/Module.js
@@ -1,4 +1,4 @@
-import { parse } from 'acorn';
+import acorn from 'acorn-jsx';
 import MagicString from 'magic-string';
 import { locate } from 'locate-character';
 import { timeStart, timeEnd } from './utils/flushTime.js';
@@ -17,10 +17,11 @@ import ModuleScope from './ast/scopes/ModuleScope.js';
 
 function tryParse ( module, acornOptions ) {
        try {
-               return parse( module.code, assign( {
+               return acorn.parse( module.code, assign( {
                        ecmaVersion: 8,
                        sourceType: 'module',
                        onComment: ( block, text, start, end ) => module.comments.push( { block, text, start, end } ),
+                       plugins: { jsx: true },
                        preserveParens: false
                }, acornOptions ) );
        } catch ( err ) {
diff --git a/src/ast/nodes/JSXIdentifier.js b/src/ast/nodes/JSXIdentifier.js
new file mode 100644
index 0000000..438fee7
--- /dev/null
+++ b/src/ast/nodes/JSXIdentifier.js
@@ -0,0 +1,16 @@
+import Node from '../Node.js';
+
+export default class JSXIdentifier extends Node {
+       bind () {
+               this.declaration = this.scope.findDeclaration( this.name );
+               this.declaration.addReference( this );
+       }
+
+       gatherPossibleValues ( values ) {
+               values.add( this );
+       }
+
+       run () {
+               if ( this.declaration ) this.declaration.activate();
+       }
+}
diff --git a/src/ast/nodes/index.js b/src/ast/nodes/index.js
index eaccdbe..bfc35a2 100644
--- a/src/ast/nodes/index.js
+++ b/src/ast/nodes/index.js
@@ -19,6 +19,7 @@ import ForOfStatement from './ForOfStatement.js';
 import FunctionDeclaration from './FunctionDeclaration.js';
 import FunctionExpression from './FunctionExpression.js';
 import Identifier from './Identifier.js';
+import JSXIdentifier from './JSXIdentifier.js';
 import IfStatement from './IfStatement.js';
 import ImportDeclaration from './ImportDeclaration.js';
 import Literal from './Literal.js';
@@ -60,6 +61,7 @@ export default {
        FunctionDeclaration,
        FunctionExpression,
        Identifier,
+       JSXIdentifier,
        IfStatement,
        ImportDeclaration,
        Literal,
```
```
$ bin/rollup jref.js -f es

jref.js → stdout...
function Foo() {}
class Bar {}
var a = <Foo><Bar/></Foo>;
console.log(a);
created stdout in 31ms
```

**Comment by kzc** [comment]
> Is there any way to disable the verbose info messages sent to stderr?

`--silent`
```
$ bin/rollup test.js -f es --silent
var hello = "Hello";
var world = "Earth";
console.log(`${hello} ${world}`);
```

**Comment by trueadm** [comment]
@kzc Thank you so much for your help :)

As a side question: could JSX support be adding to Rollup core? It saves us having to maintain a fork of Rollup :/

**Comment by kzc** [comment]
> could JSX support be adding to Rollup core? It saves us having to maintain a fork of Rollup :/

That's up to @Rich-Harris. 

Since object spread/rest is also not presently supported perhaps a Babel-esque grammar plugin system could be devised to inject acorn plugins and Rollup AST classes. That way others could independently extend ES syntax without forking Rollup.

**Comment by trueadm** [comment]
@kzc That would be a good idea. Although, how would that work with existing Rollup plugins? Currently, for example, `babel-plugin-commonjs` also needs to change to use `acorn-jsx` to support JSX (which I'm currently trying to get working).

**Comment by kzc** [comment]
> Currently, for example, `babel-plugin-commonjs` also needs to change to use acorn-jsx to support JSX

Did you mean `rollup-plugin-commonjs`?

I suppose all existing Rollup plugins would have to adopt the same proposed parsing subsystem rather than loading acorn directly?

Rather than pursuing a blind alley I think it'd best to get @Rich-Harris' thoughts on this.

**Comment by trueadm** [comment]
@kzc Sorry, I did – edited my post to reflect the typo. Cool, I'll wait for @Rich-Harris's thoughts on this.

**Comment by trueadm** [comment]
@kzc Going back to an earlier point on using `acorn-object-rest-spread`. I can't seem to get it working via the inject method, could you possibly point me in the right direction? Thank you so much – you've been a great help! )

**Comment by kzc** [comment]
@trueadm It took over an hour to figure out that `acorn-object-spread@1.0.0` is incompatible with `acorn@5`. Tested against 224e192856699d9b67e0626fd6b4e0c3432158f4. Enjoy:
```patch
diff --git a/package.json b/package.json
index f1cf1b7..a3a6183 100644
--- a/package.json
+++ b/package.json
@@ -42,6 +42,8 @@
   "homepage": "https://github.com/rollup/rollup",
   "devDependencies": {
     "acorn": "^5.1.1",
+    "acorn-jsx": "^4.0.1",
+    "@jbboehr/acorn-object-spread": "^3.0.0",
     "buble": "^0.15.1",
     "chalk": "^2.1.0",
     "codecov.io": "^0.1.6",
diff --git a/src/Module.js b/src/Module.js
index 7ba6a4e..4c8f4b4 100644
--- a/src/Module.js
+++ b/src/Module.js
@@ -1,4 +1,5 @@
-import { parse } from 'acorn';
+import acorn from 'acorn-jsx';
+import acornObjectSpread from '@jbboehr/acorn-object-spread/inject.js';
 import MagicString from 'magic-string';
 import { locate } from 'locate-character';
 import { timeStart, timeEnd } from './utils/flushTime.js';
@@ -15,12 +16,18 @@ import enhance from './ast/enhance.js';
 import clone from './ast/clone.js';
 import ModuleScope from './ast/scopes/ModuleScope.js';
 
+acornObjectSpread(acorn);
+
 function tryParse ( module, acornOptions ) {
        try {
-               return parse( module.code, assign( {
+               return acorn.parse( module.code, assign( {
                        ecmaVersion: 8,
                        sourceType: 'module',
                        onComment: ( block, text, start, end ) => module.comments.push( { block, text, start, end } ),
+                       plugins: {
+                               jsx: true,
+                               objectSpread: true,
+                       },
                        preserveParens: false
                }, acornOptions ) );
        } catch ( err ) {
diff --git a/src/ast/nodes/JSXIdentifier.js b/src/ast/nodes/JSXIdentifier.js
new file mode 100644
index 0000000..438fee7
--- /dev/null
+++ b/src/ast/nodes/JSXIdentifier.js
@@ -0,0 +1,16 @@
+import Node from '../Node.js';
+
+export default class JSXIdentifier extends Node {
+       bind () {
+               this.declaration = this.scope.findDeclaration( this.name );
+               this.declaration.addReference( this );
+       }
+
+       gatherPossibleValues ( values ) {
+               values.add( this );
+       }
+
+       run () {
+               if ( this.declaration ) this.declaration.activate();
+       }
+}
diff --git a/src/ast/nodes/index.js b/src/ast/nodes/index.js
index eaccdbe..bfc35a2 100644
--- a/src/ast/nodes/index.js
+++ b/src/ast/nodes/index.js
@@ -19,6 +19,7 @@ import ForOfStatement from './ForOfStatement.js';
 import FunctionDeclaration from './FunctionDeclaration.js';
 import FunctionExpression from './FunctionExpression.js';
 import Identifier from './Identifier.js';
+import JSXIdentifier from './JSXIdentifier.js';
 import IfStatement from './IfStatement.js';
 import ImportDeclaration from './ImportDeclaration.js';
 import Literal from './Literal.js';
@@ -60,6 +61,7 @@ export default {
        FunctionDeclaration,
        FunctionExpression,
        Identifier,
+       JSXIdentifier,
        IfStatement,
        ImportDeclaration,
        Literal,
```
```
$ cat nonsense.js 
function Foo() {}
class Bar {}
class Unused {}
var obj = { fiz: 1, baz: 2 };
var o2 = { qux: 3, ...obj };
var a = <Foo attr={ { ...o2 } }><Bar/></Foo>;
var b = <Bar/>;
console.log(a);
```
```
$ bin/rollup nonsense.js -f es --silent
function Foo() {}
class Bar {}
var obj = { fiz: 1, baz: 2 };
var o2 = { qux: 3, ...obj };
var a = <Foo attr={ { ...o2 } }><Bar/></Foo>;
console.log(a);
```

**Comment by trueadm** [comment]
@kzc Awesome work, thank you again!

**Comment by trueadm** [comment]
@kzc It looks like `acorn-object-spread` doesn't have object rest. However, `acorn-object-rest-spread` seems to have this from the looks of it – I'll look into the level of effort to patch it over your fork.

```js
var obj = { fiz: 1, baz: 2 };
var { fiz, o2 } = obj;
var a = <Foo attr={ { ...o2 } }><Bar/></Foo>;
console.log(a);
```

**Comment by kzc** [comment]
>  It looks like acorn-object-spread doesn't have object rest. However, acorn-object-rest-spread seems to have this from the looks of it

I see. Even `acorn-object-rest-spread` has at least one [issue](https://github.com/victor-homyakov/acorn-object-rest-spread/issues) apparently.  Might have to wait for official `acorn` support once the object rest/spread proposal reaches stage 4. 

Despite suggesting to wait for Rich's thoughts on AST plugins for `rollup`, it might be better to submit a `rollup` PR to start the design discussion.

**Comment by kzc** [comment]
As of rollup version 0.49.0 (specifically commit https://github.com/rollup/rollup/commit/4b4a74fe1a7b8a52e9142ec144c56024f4a35edf) `JSXIdentifier` needs this new implementation to work:

```js
$ cat src/ast/nodes/JSXIdentifier.js 
import Node from '../Node.js';

export default class JSXIdentifier extends Node {
	bind () {
		this.declaration = this.scope.findDeclaration( this.name );
		this.declaration.addReference( this );
	}

	gatherPossibleValues ( values ) {
		values.add( this );
	}

	includeInBundle () {
		if ( this.included ) return false;
		this.included = true;
		this.declaration && this.declaration.includeDeclaration();
		return true;
	}
}
```
The class above is patterned after:

https://github.com/rollup/rollup/blob/master/src/ast/nodes/Identifier.js

**Comment by kzc** [comment]
Rollup version 0.49.1 would likely require more changes to handle unused `JSXElement`s.

@trueadm You can take over from here. :-)

**Comment by guybedford** [comment]
This should now be supported through the custom plugins feature in #1857. Feedback welcome.
