### ISSUE TITLE
"No name was provided for external module" when external is a function

### ISSUE THREAD

**Issue by svpace** [rollup/rollup#1514]
Hi, 

Given the following config:
```javascript
export default {
    entry: 'src/bundle.js',
    dest: 'dist/bundle.js',
    format: 'umd',
    plugins: [
        resolve()
    ],
    external: id => id.includes('node_modules'),
    globals: { jquery: '$' },
};
```
Rollup shows a warning like "No name was provided for external module '<absolute_path>/node_modules/jquery/dist/jquery.js' in options.globals – guessing '$'"

On the other hand, If I change the "external" option to explicitly list the dependencies everything works as intended 
```javascript
export default {
    entry: 'src/bundle.js',
    dest: 'dist/bundle.js',
    format: 'umd',
    plugins: [
        resolve()
    ],
    external: [ 'jquery'],
    globals: { jquery: '$' },
};
```
But then I would be required to explicitly list all my node_modules, which is not ideal. I believe that both configurations should be, roughly, equivalent.

Regards

**Comment by houli** [comment]
You can use the dependency information from your `package.json` file to achieve this without listing out each separately
```javascript
import resolve from 'rollup-plugin-node-resolve';
import { dependencies } from './package.json';

export default {
    entry: 'src/bundle.js',
    dest: 'dist/bundle.js',
    format: 'umd',
    plugins: [
        resolve()
    ],
    external: Object.keys(dependencies),
    globals: { jquery: '$' },
};
```

**Comment by svpace** [comment]
Indeed. In fact, my actual situation is a little more complex (dependencies and some directories within src) and I've been using a small piece of code to build an id list for me. Nonetheless, I was surprised by the fact that using a function in 'external' did not played well with 'globals'.

**Comment by Rich-Harris** [comment]
This is a little bit confusing, but the `external` function will run before *and* after the module is resolved. If it returns `true` for `jquery`, then the module's ID will be `jquery` — Rollup won't try to resolve it.

If it returns anything else (which it will in this case, if it's testing for `node_modules`), then Rollup will resolve it, and then pass the resolved ID back to the function at which point it returns `true`. But by then, the module's ID is `<absolute_path>/blah`.

I can't pretend this is a particularly good design, but it's that way for historical reasons... if you can modify the function accordingly, it should work!

**Comment by svpace** [comment]
Thank you for the great explanation

**Comment by Binote** [comment]
## No name was provided for external module 'vue-runtime-helpers' in output.globals – guessing 'vueRuntimeHelpers'
I developed a set of vue component packaging configuration tools based on rollup that excluded all NPM packages.
I want this configuration to be used to develop all the NPM packages we need, but I can't dynamically get the global export name of the NPM package when packaging the umd package, and it's hard to make sure the export name of the third-party package is standard.
Do you have any good ideas?
