### ISSUE TITLE
Can websocket module be bundled?

### ISSUE THREAD

**Issue by cwilling** [rollup/rollup#1516]
I've already managed to use rollup to bundle the browser side of a project and I'm now trying to do same for the server side (using node.js). The server side uses the npm websocket module to communicate with the browser. I've so far managed to successfully bundle all my own code but not the websocket module  - rollup complains with:

     🚨   Error: Could not resolve '../build/Release/bufferutil' from node_modules/websocket/lib/BufferUtil.js

That file exists in the websocket module - it seems to be code generated when the websocket module was installed.

I have a [trivial example to demonstrate the problem here](https://github.com/cwilling/rollup-websocket). Any ideas? Am I doing something dopey?

**Comment by pshrmn** [comment]
**Note** I had to switch your trivial example to es6 imports in order to get the error to happen.

The file for `build/Release/bufferutil` is `.node`, so I had to add `extensions: ['.js', '.node']` to the `resolve` plugin in order for that file to resolve. That gets rid of the resolving error, but that file cannot be read since it is not JavaScript, so you just end up with an `Unexpected character` error instead. I imagine that you would want to just bundle the fallback file, but I'm not sure how to (or if you can) get Rollup to skip files.

Sorry that I cannot be more help here, but at least that's a step towards figuring this out?

**Comment by cwilling** [comment]
Thanks for looking at it Paul.

Your mention of the fallback file gave me an idea for a workaround, namely to require the fallback file instead of the `.node` file in lib/BufferUtil.js. The fallback file is ordinary javascript so bundling then works as expected. It means hacking inside the websocket module but that's OK in this case because the overall aim is to bundle everything needed so that the node_modules directory is never needed by an end user. I had to do the same thing in lib/Validation.js for a validation.node file that was also required. I've now tried this in the real project and it seems to be running fine - the server/browser interaction is pretty intermittent and I can't spot any difference in speed due to using pure javascript rather than compiled code.

Since the workaround is a bit hackish, I'll leave the issue open for a while in case someone has a better idea.

**Comment by cwilling** [comment]
For completeness: 

although in my previous comment I reported the server was running well after patching BufferUtil.js & Validation.js, it turned out it was not running with a bundled websocket module (no module content in the bundle, so the server must have been accessing node_modules/websocket at run time). My own code still had a require of websocket rather than an import. When I instead imported websocket, the websocket module was bundled but I had a new runtime error about 'new index'  not being a function. Inspection of the bundle showed index was indeed just a dictionary of exported functions, not actual functions. I suspected that might have been be due to the multiple levels of exports/requires in the websocket module i.e. websocket/index.js requires websocket/lib/websocket.js which exports a dictionary of exports each element of which requires something else. To eliminate that confusion, I changed websocket/index.js to directly require lib/WebsocketServer.js (the only thing I'm interested in for my server code). Since then the websocket stuff is correctly bundled and the server itself is running fine.

**Comment by cwilling** [comment]
Also, while looking for something else, I just found that the problem of [dealing with `.node` files has been discussed here](https://github.com/rollup/rollup-plugin-commonjs/issues/101). I haven't seen the new plugin that is mentioned there though.

**Comment by Rich-Harris** [comment]
> I'm not sure how to (or if you can) get Rollup to skip files.

Use `options.external`:

```js
// rollup.config.js
export default {
  // ...
  external: ['websocket']
};
```

If it has a `.node` dependency, it can't be bundled — you'll have to just exclude it.
