### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by mic3ael** [rollup/rollup#1519]
When I tried to build project I got the Error:
  
> Error: Unexpected token
> node_modules/react-redux-toastr/src/ReduxToastr.js (13:21)
> 11:
> 12: export class ReduxToastr extends React.Component {
> 13:   static displayName = 'ReduxToastr';
>                          ^
> 14:
> 15:   static propTypes = {

I use

> react-redux-toastr version "~7.1.3"

 for toast messages

> "rollup": "~0.45.2"
> "rollup-plugin-alias": "^1.3.1",
> "rollup-plugin-babel": "~2.7.1",
> "rollup-plugin-commonjs": "~8.1.0",
> "rollup-plugin-eslint": "~4.0.0",
> "rollup-plugin-node-resolve": "~3.0.0",
> "rollup-plugin-postcss": "~0.5.4",
> "rollup-plugin-replace": "~1.1.1",
> "rollup-plugin-uglify": "~2.0.1",
> "rollup-watch": "~4.3.1"

My conf file is:

 ```
import babel from 'rollup-plugin-babel';
 import commonjs from 'rollup-plugin-commonjs'
 import nodeResolve from 'rollup-plugin-node-resolve'
 import uglify from 'rollup-plugin-uglify'
 import replace from 'rollup-plugin-replace'
 import alias from 'rollup-plugin-alias';
 
 export default {
   entry : 'public/src/index.js',
   dest : 'public/build/js/bundle.min.js',
   format : 'iife',
   plugins : [
     babel({exclude: 'node_modules/**'}),
     nodeResolve({jsnext: true, modulesOnly: true}),
     commonjs({include: 'node_modules/**'}),
     replace({'process.env.NODE_ENV': JSON.stringify('production')}),
     uglify({
       compress: {
         screw_ie8: true,
         warnings: false
       },
       output: {
         comments: false
       },
       sourceMap: false
     }),
     alias({.....})
 ]};


```

I searched on the internet but I didn't find a solution.

Thanks, Michael.

**Comment by kzc** [comment]
> 12: export class ReduxToastr extends React.Component {
> 13: static displayName = 'ReduxToastr';
> ^

Class properties are not in the ECMAScript standard, nor are they supported by `rollup`'s parser `acorn` or Chrome for that matter.

You'd have to run the appropriate `babel` plugin on the code first to translate it to ECMAScript.

**Comment by mic3ael** [comment]
Do you know the appropriate Babel plugin?

**Comment by kzc** [comment]
google for "babel class properties"

**Comment by mic3ael** [comment]
Thanks.

**Comment by Mansourawy** [comment]
Hello , did you find a proper babel plugin for that issue , i have the same issue

**Comment by lstaniszewski** [comment]
@Mansourawy 

Just add `rollup-plugin-babel` to your plugins in rollup config:

```
plugins: [
    babel({
      plugins: ['transform-class-properties'],
      include: ['node_modules/react-redux-toastr/**'],
    }),
   // ...more settings
]
```

Of course you need to install `babel-plugin-transform-class-properties` first
