### ISSUE TITLE
Q: better optimization by running Uglify twice?

### ISSUE THREAD

**Issue by MaxMotovilov** [rollup/rollup#1520]
I have been exploring the possibility of conditional builds in Rollup using the combination of static evaluation, DCE and tree shaking and made a somewhat startling discovery which is best described by this short gist: https://gist.github.com/MaxMotovilov/de9090d3197d2ff75df9b25c9086e6d4. To wit, I can achieve "perfect" optimization (removal of unneeded dependencies and calls) by running the uglify plugin twice; a single run doesn't do it. Apparently this happens because tree shaking is performed between the two minification passes as simply running the output of the first step through Uglify via command line doesn't do the trick!

My questions:

- Is this known/intended behavior? I wasn't able to find it described anywhere and stumbled upon it blindly.
- Are more complex use cases likely to require multiple, potentially unlimited number of passes?
- If not, wouldn't it make sense to include it as a documented, standard approach: a configuration-modifying plugin should be able to do this trick.
- Alternatively, are there better, more efficient ways of achieving the same result?

**Comment by kzc** [comment]
Use the uglify `compress` [option](https://github.com/mishoo/UglifyJS2#minify-options) `passes` to save an unnecessary output/reparse of the code:
```
$ cat rollup.config.js 
import uglify from 'rollup-plugin-uglify';
import buble from 'rollup-plugin-buble';

export default {
	entry: 'main.js',
	format: 'iife',
	exports: "none",
	interop: false,
	plugins: [
		buble(),
		uglify({
			compress: {
				passes: 3,
			},
		}),
	],
	dest: 'bundle.once.js'
};
```
```
$ rollup -c rollup.config.js 
```
```
$ cat bundle.once.js 
!function(){"use strict";for(var o=0;o<2;++o)console.log("B")}();
```

**Comment by MaxMotovilov** [comment]
Indeed - does the same thing! Thanx! I am a bit surprised that a 2nd pass from command line didn't do the same, but perhaps the defaults are different.
