### ISSUE TITLE
breaking changes that occurred at 0.45.0 are not currently reflected in wiki.

### ISSUE THREAD

**Issue by segayuu** [rollup/rollup#1521]
It is always helpful to wiki information.
So I was able to notice the old document.
I appreciate the appropriate error message.

https://github.com/rollup/rollup/wiki/JavaScript-API#bundlegenerate-options-

---

## bundle.generate( options )

**Returns a { code, map } object**, where map is a sourcemap, assuming the sourceMap: true option is set. The following options are supported (none are required, but format is highly recommended):

---

current return value is Promise<{code, map}>...
could you fix document?

**Comment by Rich-Harris** [comment]
It's a wiki, so anyone could have edited it, but sure 😉 The information is correct now
