### ISSUE TITLE
Allow removing interop from CLI

### ISSUE THREAD

**Issue by charlike** [rollup/rollup#1524]
hi! :wave:

Just thinking can you allow removing the interop from the CLI, like `--no-interop`? It seems it's not possible now. I don't know to use rollup config file, since i have dozen of other dot and config files in each repo, don't won't one more for absolutely nothing so serious, also i just not using any plugins, that's why i want to use just the cli.

I prefer to not removing the interop, if i could prepend `/* istanbul-ignore-next */` to it, but using intro doesn't help because adds new line after it. And really, that's the only thing that i need make two bundles - cjs and es, no plugins and things, my packages require node 6.

Of course i can create a plugin that do that, but i don't want config file. All that is related to what i said before some months in another discussion - we don't need config file for some simple things and the tools should force you to do that. That's one of the reasons why i started building a wrapper around Rollup - [@rolldown](https://github.com/charlike/rolldown).

edit: fixed link, forgot that i deleted the org.

**Comment by Rich-Harris** [comment]
Yep, seems sensible. Can you open a PR with a test please? I think you'd just need to add `interop: 'interop'` to [this block](https://github.com/rollup/rollup/blob/f4d9765c381b5d5c20d1336bd9724112459defe6/bin/src/run/mergeOptions.js#L3-L19), and update the [help.md](https://github.com/rollup/rollup/blob/f4d9765c381b5d5c20d1336bd9724112459defe6/bin/src/help.md) file.

**Comment by charlike** [comment]
Okey, i'll try :)

**Comment by charlike** [comment]
https://github.com/rollup/rollup/pull/1534, but i'm not sure :laughing:
