### ISSUE TITLE
Preserve import * as xxx from xxx

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup#1526]
Hi,

the following import statement
```js
import * as Raven from "raven-js";
```

will be outputted to this when passed to rollup
```js
import { captureException, captureMessage, config } from 'raven-js';
```

Is there any way to preserve the original import statement ie with the `import * as`  from some modules or all?

thanks.

**Comment by Rich-Harris** [comment]
Can you explain why you need the `import *` preserved in the generated code?

**Comment by alan-agius4** [comment]
Because how raven-js is written, it requires a 'this' context in the
methods now this works when I have 'import * as raven from "raven-js"'.
Cause in this instance 'raven' is actually the prototype instance.

However, when its is rolled up, this instance is lost and the methods are
called directly.

**Comment by Rich-Harris** [comment]
It sounds like you want to do this instead:

```js
import Raven from 'raven-js';
```

**Comment by alan-agius4** [comment]
Isn't that only valid if the library has a default export?

**Comment by Rich-Harris** [comment]
That's what Raven has — or at least, the CommonJS equivalent (`module.exports`).

**Comment by alan-agius4** [comment]
I need to check a bit cause if i remember correctly I had some problems in the past when doing that and exporting to umd modules, because it was adding .default in the output. But right now i dont have the code handy. 

Thanks for your help

**Comment by alan-agius4** [comment]
I gave it a quick shot, and it seems that it does work cause rollup does set the `.default` when it's not available.

```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('raven-js')) :
	typeof define === 'function' && define.amd ? define(['raven-js'], factory) :
	(factory(global.raven));
}(this, (function (raven) { 'use strict';

raven = raven && raven.hasOwnProperty('default') ? raven['default'] : raven;

raven.config(undefined);

})));
```

However, I apart from rollup I am using TypeScript, and if I transpile it to UMD the output will be invalid because it will be (note the .default)
```
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "raven-js"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var raven_js_1 = require("raven-js");
    raven_js_1.default.config(undefined);
});
```

Which means that for unit tests I will need to use either rollup as well which is not really desired.

**Comment by Rich-Harris** [comment]
Yeah, unfortunately this is what happens when you try and make JavaScript modules, TypeScript modules and CommonJS modules work together 😨

**Comment by Rich-Harris** [comment]
will close this as I'm not sure there's anything that Rollup can realistically do here

**Comment by alan-agius4** [comment]
For anyone seeing the post, I think I might have found a workaround

```
import * as raven from "raven-js"
const ravenJs = raven; 
ravenJs.config();
```

With the 2nd line rollup won't change the import statement.

**Comment by peterbakonyi05** [comment]
Some other solutions/ideas:
**First**
https://rollupjs.org/repl?version=0.47.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMFJhdmVuJTIwZnJvbSUyMCU1QyUyMnJhdmVuLWpzJTVDJTIyJTVDblJhdmVuLmNvbmZpZy5jYWxsKFJhdmVuKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Second**
Use Raven as a global dependency and load it when creating the application bundle using `rollup-plugin-inject` or webpack's `ProvidePlugin`

**Third idea**
I don't know if that is possible but using `rollup-commonjs-plugin` only for `raven-js` and somehow trying to bundle it and not have as an external dependency might work as well. Though I did not manage to make this idea work yet. It seems that you cannot generate an `es` format bundle but still include some of your dependencies in the bundle (not that surprising though).

**Comment by alan-agius4** [comment]
Probably the first would be the simplest although need to be careful that
you do the '.call' on every raven method that is being invoked and not
forget any.

Regarding the second, it is also an option though then one needs to include
rollup and webpack in karma. Which in this case might as well enable
synthetic imports instead.
