### ISSUE TITLE
Module source-map-support not found

### ISSUE THREAD

**Issue by charlike** [rollup/rollup#1528]
hi, just happened to install the latest version v0.46.0 and it throws that error, which is absolutely strange, because it seems it is included here.

proof at travis: https://travis-ci.org/tunnckoCore/parse-function/jobs/263561674, locally fails too (even `rollup --help` fails) and was working with the previous version.

**Comment by charlike** [comment]
Damn, okey, it seems it is excluded intentionally in the [cli's config](https://github.com/rollup/rollup/blob/master/rollup.config.cli.js)?

**Comment by Rich-Harris** [comment]
Seems `source-map-support` is erroneously listed in `devDependencies` rather than `dependencies`. Not sure how that happened. Will fix — in the meantime, just doing `npm install source-map-support` should fix it

**Comment by charlike** [comment]
Yea, but why not bundle it with `source-map-support` as like the other deps?

**Comment by Rich-Harris** [comment]
Honestly can't remember. There must have been some reason. In #1529 I've just removed it altogether, I don't think it's doing anything particularly useful.

**Comment by Rich-Harris** [comment]
released 0.46.1
