### ISSUE TITLE
Variable collision after export *

### ISSUE THREAD

**Issue by tony-g** [rollup/rollup#1550]
I'm running into a variable not getting renamed and colliding with an import.  I'm not sure if I'm missing a plugin or setting (or otherwise doing something I shouldn't be), or if it might be a bug.

Here's a repo with a full example. https://github.com/tony-g/rollup-export-star-question

...

I have a react/redux project and have folders for actions, reducers, selectors, etc.

`selectors/index.js` looks like this:

```js
export * from './a'
export * from './b'
export * from './calculation'
```

I import them in another file (`src/doesnt-work.js` in the example)

```js
import { calculation as doCalculation } from './selectors/index'
...
function mapStateCulprit(state) {
  const calculation = doCalculation(...)
  ...
}
```

### Expected
`calculation` is renamed (which is what happens if I import it directly from `./selectors/calculation`)
```js
function mapState(state) {
  const calculation$$1 = calculation();
```

### Actual
It's not renamed and I get this: (which breaks)
```js
...
function mapStateCulprit(state, ownProps) {
  const calculation = calculation(state);
...
```

Thanks for your help!

**Comment by Rich-Harris** [comment]
Fixed in 0.47.3, thanks!
