### ISSUE TITLE
The use of "undefined" breaks JS-builds

### ISSUE THREAD

**Issue by DonGissel** [rollup/rollup#1552]
Using `undefined` in any context seems to break Rollup entirely. This can be circumvented in one's own code, but editing NPM-packages locally to fix the problems is another matter entirely. Using RollUp 0.47.4, this is what I get:

`SyntaxError: The keyword 'undefined' is reserved (306:12) in D:\Frontend\node_modules\packery\js\packery.js
    at error (D:\Frontend\node_modules\rollup\dist\rollup.js:181:12)
    at D:\Frontend\node_modules\rollup\dist\rollup.js:9460:6
    at <anonymous>`

And the line in question inside Packery (imported using rollup-plugin-commonjs 8.1.0 and rollup-plugin-node-resolve 3.0.0) is:

`x = x === undefined ? item.rect.x: x;`

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined), this is a perfectly valid way of checking if a variable is undefined or not, so this seems like a bug on Rollup's part. Or am I missing something?

**Comment by kzc** [comment]
I too had this error until I blew away `node_modules` and did another `npm install`. Maybe a bug in `package.json`, some `rollup` config file or `npm`.

**Comment by Rich-Harris** [comment]
@DonGissel are you still experiencing this issue after trashing/reinstalling node_modules? If so [please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff), otherwise let us know if we can close this. Thanks

**Comment by DonGissel** [comment]
Yeah, sorry about the wait and the inconvenience. It was indeed something screwy in my `node_modules` – apparently the `npm update` didn't run as smoothly as expected. Nuking the folder and reinstalling from scratch seems to have alleviated the problem. Thanks!
