### ISSUE TITLE
Sourcemap true/'inline' significantly increases bundle time

### ISSUE THREAD

**Issue by houli** [rollup/rollup#1553]
Reproduction repository: https://github.com/houli/rollup-sourcemap-repro

Steps to reproduce:
1. Clone the reproduction repository
2. Run `yarn/npm install`
3. Run `rollup -c` and note short bundle time
4. Change `sourceMap` in `rollup.config.js`
5. Run `rollup -c` again and note long bundle time
<img width="914" alt="screen shot 2017-08-15 at 22 59 39" src="https://user-images.githubusercontent.com/143868/29338775-c1c25c00-820e-11e7-9697-a9a254b59d24.png">

The above demonstrates the time taken when using an inline sourcemap and with sourcemaps then disabled.
I initially noticed this issue when using https://github.com/jlmakes/karma-rollup-preprocessor as a way to use rollup with Karma tests. Inline sourcemaps are important for Karma tests as each test file will be transformed into one iife bundle that can be executed in the browser.

**Comment by Rich-Harris** [comment]
Looks like the vast majority of the time is being spent in [collapseSourcemaps](https://github.com/rollup/rollup/blob/master/src/utils/collapseSourcemaps.js):

<img width="488" alt="screen shot 2017-08-20 at 6 20 00 pm" src="https://user-images.githubusercontent.com/1162160/29498945-3e369224-85d4-11e7-997e-55ea934fce8a.png">

Hopefully there's some low-hanging fruit there...

**Comment by houli** [comment]
Looking at the profile information, 90% of the time is spent in this `forEach` https://github.com/rollup/rollup/blob/master/src/utils/collapseSourcemaps.js#L32
with the function calls in that anonymous function being minuscule (0.1ms of a 200ms iteration). I don't see anything in there that particularly stands out right now

**Comment by pmdartus** [comment]
As @houli mentioned above, most of the time is spent into processing in `collapseSourcemaps.js`, see profile below.

<img width="937" alt="screen shot 2018-02-03 at 8 43 03 pm" src="https://user-images.githubusercontent.com/2567083/35774397-e709db82-0922-11e8-84ae-ce7ff703a75d.png">

When digging further, the real bottleneck resides in the [`traceMappings`](https://github.com/rollup/rollup/blob/089c9e06190b894d766fc44571752fa91dc1eaa5/src/utils/collapseSourcemaps.ts#L52-L101) loop. For most of the files, the processing is (~30 iterations), however this number skyrocket for some specific files (~40k iterations).  The [`encoding-indexes.js`](https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding-indexes.js) which is bundled into the [`nise`](https://unpkg.com/nise@1.2.2/nise.js) module is, in this case, the main offender.

After commenting the section related to `encoding-indexes`, the build time drops back to 2.3 sec. For comparison, the same build without sourcemap takes 2 sec.

<img width="925" alt="screen shot 2018-02-04 at 8 52 14 am" src="https://user-images.githubusercontent.com/2567083/35779862-c316e65a-0988-11e8-8810-8e193a0b443b.png">

**Comment by mourner** [comment]
Let's try upgrading Rollup to use `source-map` v0.7.2 — it should be around 5-6x faster (see  https://github.com/mozilla/source-map/blob/master/CHANGELOG.md)

**Comment by anandthakker** [comment]
@mourner looking at https://github.com/rollup/rollup/blob/451ac5f30ddf07b053d65489b7fa9ab00d6d859e/src/utils/collapseSourcemaps.ts#L52-L101, it seems the `source-map` package isn't being used here: the source mapping segments are being traced 'manually'

**Comment by mourner** [comment]
Heads up that there's a fix coming for this in #2228.
