### ISSUE TITLE
[bug] tree shaking should not happen with circular dependencies.

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#1554]
ES6 module load order is dependent on the order in which `import` statements are found. `import` statements can also be used to cause side effects without something actually being exported or without an export being used.

I have a use case where a simple side-effect `import` fixes a circular dependency, but Rollup removes this import from the output which makes it not possible to solve the circular dependency issue in a way that is easy.

Here's the input file:

..............

and here's the output with the missing `Transformable` import:

...............

If I edit the code manually to add back the import in the format that Rollup would have done, as in

..............

then the problem is fixed as expected.

To reproduce, try this example:

.........................

Then fix the problem by modifying the Rollup output like so:

.....................

For reference, this works in Webpack.

I think it is important to honor this aspect of ES6 modules by not tree shaking away modules if

1. the side-effect module executes any code besides defining functions or variables
2. the side-effect module does not execute anything explicitly but it is part of a circular dependency where it would otherwise be shaken from a module as in the example.
3. other cases?

A simple solution, rather than trying to detect all this stuff, might be to allow authors at the very least the ability to write an inline comment telling Rollup to not tree-shake an import away. I don't like this solution, but it would be easy, and I could live with it.

--- 

I will fill the examples soon, but at least this opens awareness of what I'm experiencing.

**Comment by guybedford** [comment]
Circular reference warnings are now included. If you can post an exact example of invalid tree shaking further, happy to take a look.
