### ISSUE TITLE
--silent versus --verbose

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#1557]
rollup version 0.47.4

Should stderr info messages be an opt-in with `--verbose` rather than an opt-out with `--silent`?

For quick tests without `--silent` the info messages are a bit distracting:
```
$ bin/rollup test.js -f es

test.js → stdout...
var hello = "Hello";
var world = "Earth";
console.log(`${hello} ${world}`);
created stdout in 32ms
```
They also show up in tests:
```
      no-treeshake

main.js → stdout...
created stdout in 27ms

        ✓ no-treeshake (249ms)
      node-config

main.js → stdout...
created stdout in 8ms

        ✓ node-config (260ms)
      node-config-auto-prefix

main.js → stdout...
created stdout in 8ms

        ✓ node-config-auto-prefix (256ms)
```
Maybe it's my exposure to terse UNIX commands with minimal output. But if the node ecosystem prefers verbose output by default, feel free to close issue.

**Comment by Rich-Harris** [comment]
Be interested to know what other people think. Personally I find the output useful (especially in a terminal with colours/bold text) but I could be in a minority.

**Comment by feross** [comment]
Unless there's a really good reason, I usually err on the side of silence. This is actually part of the unix philosophy:

> The rule of silence, also referred to as the silence is golden rule, is an important part of the Unix philosophy that states that when a program has nothing surprising, interesting or useful to say, it should say nothing. It means that well-behaved programs should treat their users' attention and concentration as being valuable and thus perform their tasks as unobtrusively as possible. That is, silence in itself is a virtue.

http://www.linfo.org/rule_of_silence.html

Hope this is a useful perspective! 😄

**Comment by kzc** [comment]
Although I'd prefer silent by default, I'm not terribly invested in this issue.

I'll leave it to the Rollup maintainers to decide.

**Comment by feross** [comment]
@kzc Can you re-open this issue until we hear from the maintainers? If you don't want notifications, there's a handy "Unsubscribe" button in the sidebar.

**Comment by kzc** [comment]
I think 4 months was sufficient time to debate this. @lukastaegert Please feel free to close the ticket if you agree with Rich.

**Comment by kzc** [comment]
Having silent by default would be useful if this Rollup were to implement:

**Feature: accept stdin #1440**

**Comment by lukastaegert** [comment]
I'm not sure I can make a decision here. But maybe a case-by-case solution would actually be better?
1. When using rollup via `rollup -c` or `rollup -w` and rollup is actually creating an output bundle on disk, I personally like the output very much as it is giving me a feeling  that "everything worked nicely" and that I can now use my bundled file as I please
2. I also think that inexperienced users will probably like the output for the reasons given above
3. When bundling to stdout, on the other hand, I agree that the output is problematic at best. Most notably, I do not need the output to see that something happened.

So if we wanted to make a minimal change, switching the output off when no file is written could be one approach. It would also help with piping and #1440. Other thoughts?

If someone were to make a PR for this I would certainly consider merging it.

**Comment by kzc** [comment]
Conditionally silent is worse than not being silent by default.

It's clear you also favor verbose output. Closing issue.
