### ISSUE TITLE
Watch process doesn't exit

### ISSUE THREAD

**Issue by andrejcremoznik** [rollup/rollup#1561]
I just updated `rollup` from `0.45.2` to `0.47.6` and noticed that `watch` is now part of the main package so I also removed `rollup-watch`. Everything works fine except that the watch process doesn't exit. 

Pressing `Ctrl+C` gets me back to shell but the node process remains running in background and I need to manually kill it.

Also, `Ctrl+C`-ing out of the process is kinda wonky. I need to press it once to get from the newly created watcher's shell back to my shell and then another 2 times to get out of the process back to prompt. Anyway, I made a recording: https://drive.google.com/open?id=0BykEiop1kvZaNWIwRy0tNDJQUFE

```
node v8.3.0
npm 5.3.0
linux Arch 4.12.6-1 x86_64
```

Am I missing something?

**Comment by jonataswalker** [comment]
Not here.

```
node v8.4.0
npm 5.3.0
linux 4.12.8-1-ARCH
```
No `node` process after `Ctrl + C`.

**Comment by andrejcremoznik** [comment]
Thanks for your input.

I started disabling plugins and `rollup-plugins-serve` seems to be the culprit.
