### ISSUE TITLE
Not watching multiple config

### ISSUE THREAD

**Issue by jonataswalker** [rollup/rollup#1562]
Rollup `0.47.6`.

Rollup is only watching main `rollup.config.js`.

Repro: https://github.com/jonataswalker/rollup-watch-repro

**Comment by Rich-Harris** [comment]
Yeah, I guess [loadConfigFile](https://github.com/rollup/rollup/blob/master/bin/src/run/loadConfigFile.js) would need to return `bundle.modules` as well as the result of executing the generated bundle, and [this code](https://github.com/rollup/rollup/blob/38e2fca9f337a9300f9890692fbef13c44a9f59d/bin/src/run/watch.js#L101-L132) would need to be updated to use it.

**Comment by ankeetmaini** [comment]
I can try my ✋ at this!

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
