### ISSUE TITLE
Plugin exceptions cause `rollup -w` to exit process

### ISSUE THREAD

**Issue by mitranim** [rollup/rollup#1563]
How to reproduce: run `rollup -cw` with `rollup-plugin-uglify` on a non-ES5 file

Expected: compilation breaks, Rollup continues watching and retrying

Actual: compilation breaks, Rollup exits and has to be restarted manually

Pretty inconvenient IMO.

**Comment by Rich-Harris** [comment]
Rollup can't know which files it needs to watch until a bundle has successfully been generated. If there's an error the first time round, it has no choice but to exit.

(If I've misunderstood and you're saying it exits if the error is introduced *after* a successful initial build, please reopen with a repro.)

**Comment by Mitranim** [comment]
Hmm. Turns out this only happens when modifying the _Rollup config_. When editing source files, Rollup successfully survives plugin exceptions.

Here's a repro:

```js
module.exports = [
  {
    entry: 'src/index.js',
    dest: 'dist/index.js',
    format: 'cjs',
    plugins: [
      require('rollup-plugin-babel')({exclude: 'node_modules/**'}),
      require('rollup-plugin-uglify')(),
    ],
  },
]
```

Make sure the source file uses some ES2015 features, toggle the Babel plugin, watch the whole thing die.

I feel like Rollup should continue watching the config and retry instead of croaking. It's very disruptive when fiddling with the config.

**Comment by Rich-Harris** [comment]
Ah, I see. Yes, I think it'd be feasible to pass the `bundle.modules` from a previous config to the new watcher, so that errors aren't fatal. Wouldn't be bulletproof (if the config changed the shape of the bundle, the old `bundle.modules` would be incorrect), but it should fix this scenario.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
