### ISSUE TITLE
Tree shaking sometimes fails in presence of plusplus expressions

### ISSUE THREAD

**Issue by Mitranim** [rollup/rollup#1564]
`main.js`:

```js
import './lib'
```

`lib.js` version 1 ([playground link](https://rollupjs.org/repl?version=0.47.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbGliJyUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsaWIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBmaXJzdCgpJTIwJTdCJTVDbiUyMCUyMGZvciUyMChsZXQlMjBpJTIwJTNEJTIwLTElM0IlM0IlMkIlMkJpKSUyMCU3QiU3RCU1Q24lMjAlMjBzZWNvbmQlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMHNlY29uZCgpJTIwJTdCJTdEJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)):

```js
function first() {
  for (let i = -1;;++i) {}
  second
}

function second() {}
```

`lib.js` version 2 ([playground link](https://rollupjs.org/repl?version=0.47.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbGliJyUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsaWIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBmaXJzdCgpJTIwJTdCJTVDbiUyMCUyMCUyQiUyQmklNUNuJTIwJTIwc2Vjb25kJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjBzZWNvbmQoKSUyMCU3QiU3RCU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)):

```js
function first() {
  ++i
  second
}

function second() {}
```

In both cases, the `main` output is:

```js
function second() {}
```

Expected output: empty. Removing the `++` or replacing it with `i += 1` bizarrely solves the problem.

**Comment by kzc** [comment]
Apparently the `i += 1` [AssignmentExpression](https://github.com/rollup/rollup/blob/master/src/ast/nodes/AssignmentExpression.js) is behaving differently than the `++i` [UpdateExpression](https://github.com/rollup/rollup/blob/master/src/ast/nodes/UpdateExpression.js). Should be easy enough to experimentally find the differences. Pull request is welcome.

Although Rollup ought to handle it, any rollup minifier plugin can drop unused functions:
```
$ bin/uglifyjs -V
uglify-es 3.0.28

$ echo 'function first(){++i; second} function second(){}' | bin/uglifyjs --toplevel -mc

$ 
```

**Comment by kzc** [comment]
Possible fix:
```patch
diff --git a/src/ast/nodes/UpdateExpression.js b/src/ast/nodes/UpdateExpression.js
index 2b77db9..f792b01 100644
--- a/src/ast/nodes/UpdateExpression.js
+++ b/src/ast/nodes/UpdateExpression.js
@@ -1,6 +1,7 @@
 import Node from '../Node.js';
 import disallowIllegalReassignment from './shared/disallowIllegalReassignment.js';
 import isUsedByBundle from './shared/isUsedByBundle.js';
+import isProgramLevel from '../utils/isProgramLevel.js';
 import { NUMBER } from '../values.js';
 
 export default class UpdateExpression extends Node {
@@ -27,7 +28,9 @@ export default class UpdateExpression extends Node {
        }
 
        initialiseNode () {
-               this.module.bundle.dependentExpressions.push( this );
+               if ( isProgramLevel( this ) ) {
+                       this.module.bundle.dependentExpressions.push( this );
+               }
        }
 
        isUsedByBundle () {
```
```
$ bin/rollup lib.js -f es

lib.js → stdout...
(!) Generated an empty bundle

created stdout in 26ms
```

**Comment by kzc** [comment]
Fixed by PR:

Rework treeshaking algorithm #1582

**Comment by lukastaegert** [comment]
Just added it as a test
