### ISSUE TITLE
Can't locate peerDependency

### ISSUE THREAD

**Issue by timburgess** [rollup/rollup#1567]
I'm using rollup to split out a component from a large React project that builds with webpack. I've seen Rollup used in various libraries and it was pretty straightforward to build a little package - see [here]( https://github.com/timburgess/rollup-peer)

As it's a React component, I've added react as a peer dependency in `package.json`

When building with it in the app, the package is found ok, but I get a
` Error: Can't resolve 'react' in '/home/tim/work/rollup-peer/lib`

Looking at the package code, there is:
`var React = _interopDefault(require('react'));`

That `require` seems pretty similar to the other dependencies that the app uses so puzzled as to why react is not being found.

**Comment by timburgess** [comment]
Resolved. `react` was required in both `peerDependencies` and `devDependencies`.

**Comment by Rich-Harris** [comment]
If it's a peerDependency, consumers of your component will need to have React installed separately. It sounds like that's not the case?

**Comment by Rich-Harris** [comment]
Gah, ignore me — I replied to an open tab that didn't have your last comment!

**Comment by theawless** [comment]
@timburgess hey by any chance do you remember why React was required in the devDependency? Why doesn't rollup pickup the React dependency from the app itself?
