### ISSUE TITLE
export * from 'external'

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#157]
Eventually, we'll have to manage `export * from 'external'`, but how we should do it, I'm not sure.

**Comment by yairEO** [comment]
Can I do something like this? `import * from './modules';` ? seems not to work

if in my `modules` file I have multiple exports to many things (functions / variables)

**Comment by Rich-Harris** [comment]
@yairEO You need to give the import a name:

```js
import * as foo from './modules';

foo.doSomething();
foo.doSomethingElse();
```

Otherwise you have no way to refer to the imported bindings.

**Comment by yairEO** [comment]
seems like export from external works, but only if I have 1 export :

I have 2 files in `/utils/`, one with `export function foo(){ ... }` second same with `bar` (instead of `foo`)

I have another file which combines all those files, called `utils.js` :
    
    export * from './utils/foo';
    export * from './utils/bar';

and in my main js file I have

    import * as utils from './utils';

This only works in the `utils` file has just one export and not multiple..

**Comment by nicolo-ribaudo** [comment]
@yairEO If you export an object as default, you can access its properties in this way:

```js
import utils from "./utils";

utils.foo;
utils.bar;
utils.baz;
```

**Comment by Victorystick** [comment]
@yairEO Your first example with
```js
export * from './utils/foo';
export * from './utils/bar';
```
and
```js
import * as utils from './utils';

utils.foo();
utils.bar();
```
should work as of Rollup [0.20.3](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0203). (There was a bug that prevented your example for working.) If you're only exporting a single function per utility module, I'd recommend you to write `export { default as foo } from '.utils/foo';` and similar in `/utils.js` instead of `export * from './utils/foo'`.

---

I don't recommend the following pattern
```js
import foo from './utils/foo';
import bar from './utils/bar';
import baz from './utils/baz';

export default { foo, bar, baz };
```
as Rollup can't optimise it as well as the earlier example. The `export default` is given an object literal that _uses_ `foo`, `bar` and `baz`, thereby preventing their removal from the bundle should they be unused.

**Comment by Rich-Harris** [comment]
`export * from 'external'` is now implemented, so I'll close this
