### ISSUE TITLE
-o from CLI breaks output.format in rollup.config.js with rollup 0.48.2

### ISSUE THREAD

**Issue by jharris4** [rollup/rollup#1573]
After upgrading to rollup 0.48.2 I tried to migrate my rollup.config.js following the instructions from the gist (https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32).

Despite following the example from the gist, I'm getting the error `[!] Error: You must specify options.format, which can be one of 'amd', 'cjs', 'es', 'iife' or 'umd'`

Basically, my rollup config looks like this:

```
let config = {
  input: 'src/index.js',
  output: {
    format: 'umd',
    name: 'Test123',
    sourcemap: true
  }
};

export default config;
```

And I'm using a package.json script like this:

```
"scripts": {
  "deploy": "rollup -c -o dist/bundle.js"
}
```

Repro repo here: https://github.com/jharris4/rollup-048-config-bug

**Comment by sunnylost** [comment]
The reason is both command line and config file set output config, and they haven't been merged correctly, command's output override config file.

Right now, you should add "file" option in rollup.config.js.

```javascript
let config = {
  input: 'src/index.js',
  output: {
    file: 'dist/bundle.js',
    format: 'umd',
    name: 'Test123',
    sourcemap: true
  }
};
```

and remove "-o dist/bundle.js"

**Comment by jharris4** [comment]
@sunnylost Thanks for the tip, I can confirm that adding `output.file` in `rollup.config.js` instead of specifying `-o <output.file>` from the command line does work around the bug.
