### ISSUE TITLE
@team, could you please showcase rollup and firebase bundle demo?

### ISSUE THREAD

**Issue by anlexN** [rollup/rollup#1577]

**Comment by anlexN** [comment]
google firebase

**Comment by anlexN** [comment]
@stefanpenner @eventualbuddha @evocateur @ericf @tivac 
*Can you help me?*

**Comment by evocateur** [comment]
This issue is spam. It is extremely rude to tag a bunch of recent contributors like this.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
