### ISSUE TITLE
UMD 

### ISSUE THREAD

**Issue by jialj** [rollup/rollup#1578]
When I binding some js files, format UMD. 

```json
 entry: 'src/graph.ts',
    targets: [
      { dest: 'out/umd/graph.min.js', format: 'umd' }
    ],
    moduleName: 'Graph'
```

I got a file like below. 

```javascript
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
	typeof define === 'function' && define.amd ? define(['exports'], factory) :
	(factory(( global.Graph = {})));//I want use  'global' replace  'global.Graph = {}' 
}(this, (function (exports) { 'use strict';
.....
```
How can I got file like below.
Change config? or other things should I do.
```javascript
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
	typeof define === 'function' && define.amd ? define(['exports'], factory) :
	(factory(( global)));//I want use  'global' replace  'global.Graph = {}' 
}(this, (function (exports) { 'use strict';
.....
```

**Comment by isidrok** [comment]
That last call_(factory(( global)));_ is the iife part of umd, which will be executed in the browser environment, thus using window as global and storing your module (Graph) in it, beign accessible from window.Graph.

If you replaced global.Graph by global, everything inside your module would be stored directly at window, why do you want to do that?

**Comment by jialj** [comment]
Yeah, I know that, that's just what I want. My situation is as follows, taking an example:
I want the code works like this `var graph = new Graph()` instead of `var graph = new Graph.Graph()`

**Comment by isidrok** [comment]
Try using moduleName:'self' 

```js
window.self.foo = 1;
window.foo; // 1
```
For anyone reading that doesn't know about modules they are like namespaces used to avoid naming collisions between other modules and window properties so keep in mind writting directly into window is not a good practice at all.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
