### ISSUE TITLE
How to remove global generated functions make them accessable from outside through a class

### ISSUE THREAD

**Issue by BennyAlex** [rollup/rollup#1579]
I want something specific and it isnt easy to expain...
So I want to build a script which will be used with <script> tag. But I cant use the iife formate, because I want to have the functions available from outside(=e.g. another script tag on the page) because there are for example some helper functions. No problem I can use es format. 

But I dont want that the functions are accessable**directly** from outside(=e.g. another script tag on the page). They should be all available through a single class/function (to avoid conflicts and it is nicer :D ). So e.g. myClass.function1() works but not function1().

So the problem is that I have different files and exports/imports. 
Is there any way to make them only accessable through a class?

little example: [example](https://rollupjs.org/repl?version=0.48.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMG15Y2xhc3MlMjBmcm9tJTIwJy4lMkZteWNsYXNzJyU1Q24lNUNubXljbGFzcy5mdW5jMSgpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZ1bmMxLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMHRoaXMlMjBmdW5jdGlvbiUyMHNob3VsZCUyMG9ubHklMjBiZSUyMGF2YWlsYWJsZSUyMGZyb20lMjBvdXRzaWRlJTIwdGhyb3VnaCUyMG15Y2xhc3MuZnVuYzElMjAlNUNudmFyJTIwZnVuYzElMjAlM0QlMjBmdW5jdGlvbigpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnZnVuYzEnKSU1Q24lN0QlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmMxJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmdW5jMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjB0aGlzJTIwZnVuY3Rpb24lMjBzaG91bGQlMjBvbmx5JTIwYmUlMjBhdmFpbGFibGUlMjBmcm9tJTIwb3V0c2lkZSUyMHRocm91Z2glMjBteWNsYXNzLmZ1bmMyJTVDbnZhciUyMGZ1bmMyJTIwJTNEJTIwZnVuY3Rpb24oKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ2Z1bmMyJyklNUNuJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jMiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybXljbGFzcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBmdW5jMSUyMGZyb20lMjAnLiUyRmZ1bmMxLmpzJyUzQiU1Q25pbXBvcnQlMjBmdW5jMiUyMGZyb20lMjAnLiUyRmZ1bmMyLmpzJyUzQiU1Q24lNUNuJTJGJTJGJTIwb25seSUyMHRoaXMlMjBjbGFzcyUyMHNob3VsZCUyMGJlJTIwYWNjZXNzYWJsZSUyMGZyb20lMjBvdXRzaWRlJTIwdG8lMjBhdm9pZCUyMGNvbmZsaWN0cyU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBteWNsYXNzJTIwJTdCJTVDbiU1Q3Rjb25zdHJ1Y3RvcigpJTIwJTdCJTVDbiU1Q3R0aGlzLmZ1bmMxJTIwJTNEJTIwZnVuYzElM0IlNUNuJTVDdHRoaXMuZnVuYzIlMjAlM0QlMjBmdW5jMiU1Q24lNUN0JTdEJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJ1bWQlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjJ0ZXN0JTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=
)

**Comment by Rich-Harris** [comment]
There's a couple of things going on here. First of all, `func1` is currently a property of the *instance*, not the *class* — if you want to be able to do `myclass.func1` then it needs to look like this instead:

```js
// myclass.js
import func1 from './func1.js';
import func2 from './func2.js';

// only this class should be accessable from outside to avoid conflicts
export default class myclass {
  constructor() {}
}

myclass.func1 = func1;
myclass.func2 = func2;
```

Secondly, if you want to use something as a `<script>` tag, *always* use `format: 'iife'` (unless you also want it to work as AMD and CommonJS, in which case `umd`). To make something accessible from outside, just `export` it from your entry module.

[Here's a demo](https://rollupjs.org/repl?version=0.48.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMG15Y2xhc3MlMjBmcm9tJTIwJy4lMkZteWNsYXNzJyU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMG15Y2xhc3MlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZnVuYzEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwdGhpcyUyMGZ1bmN0aW9uJTIwc2hvdWxkJTIwb25seSUyMGJlJTIwYXZhaWxhYmxlJTIwZnJvbSUyMG91dHNpZGUlMjB0aHJvdWdoJTIwbXljbGFzcy5mdW5jMSUyMCU1Q252YXIlMjBmdW5jMSUyMCUzRCUyMGZ1bmN0aW9uKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdmdW5jMScpJTVDbiU3RCU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuYzElNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZ1bmMyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMHRoaXMlMjBmdW5jdGlvbiUyMHNob3VsZCUyMG9ubHklMjBiZSUyMGF2YWlsYWJsZSUyMGZyb20lMjBvdXRzaWRlJTIwdGhyb3VnaCUyMG15Y2xhc3MuZnVuYzIlNUNudmFyJTIwZnVuYzIlMjAlM0QlMjBmdW5jdGlvbigpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnZnVuYzInKSU1Q24lN0QlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmMyJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJteWNsYXNzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZ1bmMxJTIwZnJvbSUyMCcuJTJGZnVuYzEuanMnJTNCJTVDbmltcG9ydCUyMGZ1bmMyJTIwZnJvbSUyMCcuJTJGZnVuYzIuanMnJTNCJTVDbiU1Q24lMkYlMkYlMjBvbmx5JTIwdGhpcyUyMGNsYXNzJTIwc2hvdWxkJTIwYmUlMjBhY2Nlc3NhYmxlJTIwZnJvbSUyMG91dHNpZGUlMjB0byUyMGF2b2lkJTIwY29uZmxpY3RzJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMG15Y2xhc3MlMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKCklMjAlN0IlN0QlNUNuJTdEJTVDbiU1Q25teWNsYXNzLmZ1bmMxJTIwJTNEJTIwZnVuYzElM0IlNUNubXljbGFzcy5mdW5jMiUyMCUzRCUyMGZ1bmMyJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15Y2xhc3MlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMnRlc3QlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==). 

Please note that this is an issue tracker, not a support forum — questions like these are better directed somewhere like [StackOverflow](https://stackoverflow.com/questions/tagged/rollupjs) or [Gitter](https://gitter.im/rollup/rollup).
