### ISSUE TITLE
Mention SystemJS in the README, docs, etc.

### ISSUE THREAD

**Issue by kylecordes** [rollup/rollup#158]
The docs mention how rollup compares to Webpack and Require. How about mentioning SystemJS/JSPM also? It is tough to get a handle on how all these tools compare, every cross-mention with context helps!

**Comment by Rich-Harris** [comment]
I considered this, but I was worried it would generate more heat than light – JSPM is a much broader project, combining a registry and a package manager with a client-side module loader, and the bundler is only one small part (in fact there's a possibility that the JSPM bundler will [use Rollup internally](https://github.com/systemjs/builder/pull/205) in a future version). Whereas Browserify and Webpack are both module bundlers first and foremost, and my sense is that developers are more familiar with them.

Having said that I take your point, it is weird to omit any mention of JSPM when discussing ES6 module bundlers. Any ideas about the least confusing way to include it?

**Comment by kylecordes** [comment]
Roughly speaking, explaining it how you did in your message above would be very helpful in the README!

**Comment by Rich-Harris** [comment]
Cool – have added [this section](https://github.com/rollup/rollup#how-does-this-compare-to-jspmsystemjs)
