### ISSUE TITLE
[v0.49.1] TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by cedx** [rollup/rollup#1589]
Installed the latest version 0.49.1. This release fixed #1587 but a new error raises now:

```shell
$ gulp js:build
[14:41:22] Using gulpfile C:\repo\belin\gulpfile.js
[14:41:22] Starting 'js:build'...
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
[14:41:30] 'js:build' errored after 8.37 s
[14:41:30] TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at Node.hasEffectsWhenMutated (C:\repo\belin\node_modules\rollup\dist\rollup.js:6885:10)
    at Node.hasEffectsWhenAssigned (C:\repo\belin\node_modules\rollup\dist\rollup.js:7148:22)
    at Node.hasEffects (C:\repo\belin\node_modules\rollup\dist\rollup.js:5979:51)
    at included.someChild.child (C:\repo\belin\node_modules\rollup\dist\rollup.js:5699:58)
    at keys.some.key (C:\repo\belin\node_modules\rollup\dist\rollup.js:5786:11)
    at Array.some (<anonymous>)
    at Node.someChild (C:\repo\belin\node_modules\rollup\dist\rollup.js:5779:20)
    at Node.hasEffects (C:\repo\belin\node_modules\rollup\dist\rollup.js:5699:32)
    at Node.shouldBeIncluded (C:\repo\belin\node_modules\rollup\dist\rollup.js:5775:15)
```

The Rollup plugins used:
- `rollup-plugin-node-resolve`: 3.0.0
- `rollup-plugin-commonjs`: 8.2.0

The Gulp task involved:

```javascript
gulp.task('js:build', async () => {
  let plugins = [
    nodeResolve(),
    commonjs()
  ];

  global._bundle = await rollup({
    cache: global._bundle,
    context: 'window',
    input: 'lib/client/index.js',
    plugins
  });

  return global._bundle.write({
    file: 'web/js/main.js',
    format: 'iife',
    sourcemap: true
  });
});
```

Even with the `magic-string` warning, this build task worked fine using Rollup v0.48.2.

**Comment by HitomiTenshi** [comment]
I am getting the same error. I also get the `magic-string` warning. I have no idea why I get the `magic-string` warning though, as the warning itself is pretty vague.

`rollup 0.48.2` seems to work fine even with the `magic-string` warning.

**Comment by lukastaegert** [comment]
I opened a new pull request #1591  that might fix this. Could you please check this by installing rollup via
"rollup": "rollup/rollup#pull/1591/head"
?

**Comment by lukastaegert** [comment]
As for the warning, maybe it is no coincidence. I assume you both got the warning already with 0.48.2?
I further suspect you are using namespace imports, e.g. import * as foo from ...?
If so, are you doing any mutations on these imports (e.g. "foo" in the example) like changing properties etc.?
Does commenting out any of this remove the magic string warning?
Or am I totally wrong here?

**Comment by cedx** [comment]
@lukastaegert Yes, the `magic-string` warning was already with v0.48.2, and there was no issue with it (e.g. the resulting bundle is working fine).

I'm not using namespace imports (e.g. `import * as ...`) but one of my dependencies could (the concerned projects were Angular ones). I'm not doing any transformation as far I know but one of my dependencies could.

Concerning this issue... I could not install the PR code using `"rollup": "rollup/rollup#pull/1591/head"`: every time I try to install it, I get an error (e.g. `error: pathspec 'pull/1591/head' did not match any file(s) known to git.`).

Not luck using the commit SHA either (e.g. `rollup/rollup#d011c0397e6a0914887e314ae8afb7d05a1f7c1b` => `fatal: reference is not a tree: d011c0397e6a0914887e314ae8afb7d05a1f7c1b`).

Is `npm` broken (I'm using version 5.3.0)? I ended up by replicating your patch to the `rollup.js` files in the `node_modules/rollup/dist` folder... and it fixed the current issue! 🙌

**Comment by cedx** [comment]
@lukastaegert I think that the `magic-string` warning comes from the `rollup-plugin-commonjs` package:
- [MagicString#overwrite()](https://github.com/Rich-Harris/magic-string/blob/master/src/MagicString.js#L321) expects an options object as last argument.
- [transform.js](https://github.com/rollup/rollup-plugin-commonjs/blob/60846f50ecc2cd8fcd6508cebbccde5ece9f79cc/src/transform.js) still uses the previous API and uses boolean values as last argument.

**Comment by lukastaegert** [comment]
Glad this fixes your issue and sorry installation did not work 😕. Hope it will get merged soon.
As for the magic string, maybe you could open an issue for rollup-plugin-commonjs?

**Comment by HitomiTenshi** [comment]
There's a pending PR already that fixes the `magic-string` warning.
https://github.com/rollup/rollup-plugin-commonjs/pull/222

Hope it gets merged soon 😄
