### ISSUE TITLE
There are some different args between local rollup and global rollup

### ISSUE THREAD

**Issue by fengxinming** [rollup/rollup#1598]
const config = {
    input: opts.input,
    output: opts.output,
    dest: opts.output,
    external: opts.external,
    format: opts.format,
    banner: opts.banner,
    legacy: opts.legacy,
    name: opts.name || 'DF',
    plugins: [
      replace({
        __VERSION__: version
      }),
      flow(),
      buble(),
      alias(Object.assign({}, aliases, opts.alias))
    ].concat(opts.plugins || [])

arg "dest" can be supported by global rollup, but arg "output" can be supported by local rollup, that will mess up with developers.

here is my project: https://github.com/fengxinming/dom-flyer, you would try it between "npm run dev" and "npm run build"

Error: Unexpected key 'dest' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch

**Comment by krozola** [comment]
WHAT DID YOU SEE???
