### ISSUE TITLE
New config API must specify output file and ignores -o

### ISSUE THREAD

**Issue by bjornharrtell** [rollup/rollup#1600]
Before the new config API I used a config without specifying dest, instead specifying it with the -o flag when running rollup with the config. When trying the same with a newer version that has the new config API it complains with unrelated `Error: You must specify options.format, which can be one of 'amd', 'cjs', 'es', 'iife' or 'umd'`.

**Comment by shellscape** [comment]
Looks like this was fixed by #1606. If this behavior is still observed, please let us know and we'll reopen the issue.
