### ISSUE TITLE
Corrupting ArrayBuffer code

### ISSUE THREAD

**Issue by modulesio** [rollup/rollup#1603]
```
const b = new ArrayBuffer(8);
new Uint32Array(b, 0, 1)[0] = 1234; // deleted, wat?
console.log(new Uint32Array(b, 0, 1)[0]);
```

Seems like a dead code elimination failure.

**Comment by modulesio** [comment]
Clickable https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwYiUyMCUzRCUyMG5ldyUyMEFycmF5QnVmZmVyKDgpJTNCJTVDbm5ldyUyMFVpbnQzMkFycmF5KGIlMkMlMjAwJTJDJTIwMSklNUIwJTVEJTIwJTNEJTIwMTIzNCUzQiUyMCUyRiUyRiUyMGRlbGV0ZWQlMkMlMjB3YXQlM0YlNUNuY29uc29sZS5sb2cobmV3JTIwVWludDMyQXJyYXkoYiUyQyUyMDAlMkMlMjAxKSU1QjAlNUQpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by modulesio** [comment]
Possibly same thing as https://github.com/rollup/rollup/issues/1599.

**Comment by lukastaegert** [comment]
Hi, this is certainly related, I am just checking on it.

**Comment by lukastaegert** [comment]
Fix should be in the next release, thanks for pointing this out, this one is really easy to overlook! We now have a test for this specific issue so that we hopefully do not break this again in the future.

**Comment by lukastaegert** [comment]
[Looks better now](https://rollupjs.org/repl?version=0.49.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwYiUyMCUzRCUyMG5ldyUyMEFycmF5QnVmZmVyKDgpJTNCJTVDbm5ldyUyMFVpbnQzMkFycmF5KGIlMkMlMjAwJTJDJTIwMSklNUIwJTVEJTIwJTNEJTIwMTIzNCUzQiUyMCUyRiUyRiUyMGRlbGV0ZWQlMkMlMjB3YXQlM0YlNUNuY29uc29sZS5sb2cobmV3JTIwVWludDMyQXJyYXkoYiUyQyUyMDAlMkMlMjAxKSU1QjAlNUQpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) 🎉
