### ISSUE TITLE
import/export/require issue

### ISSUE THREAD

**Issue by willin** [rollup/rollup#1608]
## 1. when use require 

https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwdGVzdCUyMCUzRCUyMHJlcXVpcmUoJy4lMkZ0ZXN0LmpzJyklM0IlMjAlMkYlMkYlMjBub3QlMjBpbmNsdWRlZCUyMGluJTVDbiU1Q25jb25zb2xlLmxvZyglMjB0ZXN0JTIwKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydC5hJTIwJTNEJTIwMTIzJTNCJTVDbmV4cG9ydC5iJTIwJTNEJTIwMzIxJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

source:

```js
const test = require('./test.js'); // not included in

console.log( test );
```

output:

```js
const test = require('./test.js'); // not included in

console.log( test );
```

## 2. import / export 

https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHRlc3QlMjBmcm9tJTIwJy4lMkZ0ZXN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coJTIwdGVzdCUyMCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydGVzdC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQuYSUyMCUzRCUyMDEyMyUzQiU1Q25leHBvcnQuYiUyMCUzRCUyMDMyMSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

input:

```js
import * as test from './test.js';

console.log( test );
```

```js
export.a = 123;
export.b = 321;
```

cannot output

--- 

only this can work:

https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHRlc3QlMjBmcm9tJTIwJy4lMkZ0ZXN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coJTIwdGVzdCUyMCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydGVzdC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGElMjAlM0QlMjAxMjMlM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBiJTIwJTNEJTIwMzIxJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

input 

```js
import * as test from './test.js';

console.log( test );
```

```js
export const a = 123;
export const b = 321;
```

**Comment by kzc** [comment]
https://github.com/rollup/rollup-plugin-node-resolve

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
