### ISSUE TITLE
plugin init or reset hook

### ISSUE THREAD

**Issue by akvadrako** [rollup/rollup#1611]
Some rollup plugins keep state that needs to be reset after each run. For example, CSS extractors will collect styles on each call to `transform()` and dump a merged CSS file beside `bundle.js` on the final call to `onwrite()`. I'm writing one now for stylis.

When running `rollup watch`, I cannot find a reliable and documented way to detect when a new run starts. It would be nice if a `plugin.init/reset()` hook was added.

**Comment by guybedford** [comment]
A `buildStart` and `buildEnd` hook have now been added in https://github.com/rollup/rollup/pull/2208.
