### ISSUE TITLE
Error on object spread syntax.

### ISSUE THREAD

**Issue by GrosSacASac** [rollup/rollup#1613]
I tried rollup on a file that use the new object spread syntax and got this error:

Error Unexpected token
274:     const registerWorker = function (options, workerStore = workers) {
275:         const worker = {
276:             ...WORKER_DEFAULT_OPTIONS,
                 ^
277:             ...options,
278:             ...WORKER_INITIAL_SETTINGS

To reproduce go to [https://github.com/GrosSacASac/worka/archive/1.0.0.zip](https://github.com/GrosSacASac/worka/archive/1.0.0.zip) and dowload the zip. (fixed version for reproduction)
then go inside the folder and use
`npm run buildBrowser`

**Comment by kzc** [comment]
Rollup uses the `acorn` parser. Object spread/rest is not yet in the ES standard and is not supported by the `acorn` parser without a plugin.

related: 

https://github.com/rollup/rollup/issues/1584#issuecomment-325375880
https://github.com/rollup/rollup/issues/1512#issuecomment-324626855

**Comment by GrosSacASac** [comment]
I see, I'll close this issue when it is ready. Good job rollup team.

**Comment by pinkhominid** [comment]
Object rest/spread support landed in Acorn 5.4.0 💥 
https://github.com/acornjs/acorn/pull/658
