### ISSUE TITLE
Why only rebuild if file contents have changed in rollup watch?

### ISSUE THREAD

**Issue by mhkeller** [rollup/rollup#1619]
When using rollup in watch mode, I'm curious what the reason is for checking the contents of the changed file against the cached version as found [here](https://github.com/rollup/rollup/blob/9e481d890d333210de3364379b0b1004ee2169f7/src/watch/fileWatchers.js#L69-L70). The current behavior is: if you save `main.js` without any new code, rollup watch won't recompile, which I could see as a small fanciness against unnecessary rebuilds.

What I've found is sometimes those rebuilds *can* be helpful (more on that below) and in my investigation into how to trigger those builds when they *are* desirable (usually after an error), I'm taking a step back to understand better why this behavior was created and wondering if would be easier to remove this `fs.readFileSync` and conditional, which would solve my workflow issue and make build slightly faster by cutting out a file read. But perhaps there's a really good reason for why it works this way and that will be interesting to learn as well.

#### What led me on this path

The original issue I've had with the current behavior is like so: let's say you are importing a module with something like `import test from './test'` but you've misspelled your test module and it's `tets.js` or something. Your rollup build will send a module not found error so you go and rename the file. That module is not watched because it hasn't been imported ever so renaming it won't trigger a build. You also can't trigger a rebuild because your `main.js` file has not changed. I end up introducing a small text change and then undoing it, which is annoying.

I could see this being an issue for loading a csv file or any file that might impact your page that isn't a part of this watched group (unless it's watched by some other process). I'm [exploring some fixes](https://github.com/mhkeller/rollup/tree/recompile-on-error) but maybe there's an alternative before I go deeper.

**Comment by aubergene** [comment]
@mhkeller is this a test of this issue? https://github.com/rollup/rollup/pull/1749/commits/3cd50dc30e690d4f3f3dda799e555413d7369e9b

I'm having issues getting it to work/fail correctly

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by mhkeller** [comment]
Hi @shellscape. I think this issue would be great to fix. Please consider re-opening.

**Comment by shellscape** [comment]
@mhkeller We're three months from the 2 year mark since it was last discussed, so I'm not sure there's a large demand here. If you're willing to lead this effort I'd be happy to reopen.
