### ISSUE TITLE
break inside look which refers to containing block erroneously dropped

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#1622]
[REPL](https://rollupjs.org/repl?version=0.49.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmxhYmVsJTNBJTIwJTdCJTVDbiU1Q3R3aGlsZSUyMChmb28pJTIwJTdCJTVDbiU1Q3QlNUN0aWYlMjAoYmFyKSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3RicmVhayUyMGxhYmVsJTNCJTVDbiU1Q3QlNUN0JTdEJTVDbiU1Q3QlN0QlNUNuJTVDdGJheiUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

```javascript
label: {
	while (foo) {
		if (bar) {
			break label;
		}
	}
	baz;
}
```

bundles to

```
'use strict';

label: {
	baz;
}
```

This also occurs with a for loop instead of a while loop. It does not seem to occur when the if and break appear directly inside of the block.

**Comment by Conduitry** [comment]
I'm realizing that's not quite a helpful example. This is only happening when a few different things are all determined to have no side-effects. Here's some code closer to what I actually ran into: [REPL](https://rollupjs.org/repl?version=0.49.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmxhYmVsJTNBJTIwJTdCJTVDbiU1Q3Rmb3IlMjAobGV0JTIwaSUyMCUzRCUyMDAlM0IlMjBpJTIwJTNDJTIwYXJyYXkubGVuZ3RoJTIwLSUyMDElM0IlMjBpJTJCJTJCKSUyMCU3QiU1Q24lNUN0JTVDdGlmJTIwKGFycmF5JTVCaSU1RCUyMCUzQyUyMGFycmF5JTVCaSUyMCUyQiUyMDElNUQpJTIwJTdCJTVDbiU1Q3QlNUN0JTVDdGJyZWFrJTIwbGFiZWwlM0IlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCU1Q24lNUN0ZG9Tb21ldGhpbmcoKSUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

```javascript
label: {
	for (let i = 0; i < array.length - 1; i++) {
		if (array[i] < array[i + 1]) {
			break label;
		}
	}
	doSomething();
}
```

bundles to

```javascript
'use strict';

label: {
	doSomething();
}
```

I wanted to call `doSomething()` only when the array is non-increasing. I'm not really sure by what mechanism the loop is being incorrectly dropped, but this issue did appear in 0.49.

**Comment by kzc** [comment]
Fix:
```diff
--- a/src/ast/nodes/BreakStatement.js
+++ b/src/ast/nodes/BreakStatement.js
@@ -3,6 +3,7 @@ import Node from '../Node.js';
 export default class BreakStatement extends Node {
        hasEffects ( options ) {
                return super.hasEffects( options )
+                       || this.label
                        || !options.inNestedBreakableStatement;
        }
 
```

**Comment by lukastaegert** [comment]
Nice catch! I will include the fix in the next PR!
