### ISSUE TITLE
Getting "Cannot read property 'magicString' of undefined" when using spread operator

### ISSUE THREAD

**Issue by RomainLanz** [rollup/rollup#1623]
Hey guys! 👋 

So after reading the issue https://github.com/rollup/rollup/issues/1613, it seems that Rollup doesn't support spread operator yet.

In my build, I'm using `buble` to transpile my code from ES6+ to ES5 and `buble` support the spread operator (you can try it there https://buble.surge.sh). When I bundle my code with Rollup it gives me the error `Cannot read property 'magicString' of undefined` and if I remove the line using the spread operator by using the old way `Object.assign({}, ...)` it works fine.

So my question is, shouldn't Rollup transpile the code first then use the transpiled code to bundle the code? Doing this will let us use the spread operator in our code base.

To reproduce this error, you can directly use the code in this repository : https://github.com/RomainLanz/rollup-test-case

Have a nice day ! ☀️

**Comment by marijnh** [comment]
I ran into this today too. The problem appears to be in the [`error` function](https://github.com/rollup/rollup/blob/master/src/utils/error.js#L7), which, while trying to re-wrap an error object, calls the object's constructor with a single string argument when it is an instance of `Error`. There is, however, no guarantee that all subclasses of `Error` have a single-string-argument constructor. In fact, Bublé's `CompileError` doesn't, which is leading to this bug.

I have no idea how to generally solve the problem of error wrapping, but I think the current approach is broken enough that it's preferable to remove it (i.e. don't try to call constructors that we don't know anything about).

**Comment by kenberkeley** [comment]
Same issue

**Comment by kzc** [comment]
There are two issues in this ticket:

1. A Rollup error reporting bug discovered by @marijnh:
```patch
--- a/src/utils/error.js
+++ b/src/utils/error.js
@@ -1,11 +1,5 @@
 export default function error ( props ) {
-       // use the same constructor as props (if it's an error object)
-       // so that err.name is preserved etc
-       // (Object.keys below does not update these values because they
-       // are properties on the prototype chain)
-       // basically if props is a SyntaxError it will not be overriden as a generic Error
-       const constructor = (props instanceof Error) ? props.constructor : Error;
-       const err = new constructor( props.message );
+       const err = new Error( props.message );
 
        Object.keys( props ).forEach( key => {
                err[ key ] = props[ key ];
```
2. A `rollup-plugin-buble` configuration issue highlighted by the rollup fix above:
```
$ rollup -c

index.js → dist/test.cjs.js, dist/test.esm.js, dist/test.umd.js...
[!] (buble plugin) CompileError: Object spread operator requires specified objectAssign option with 'Object.assign' or polyfill helper. (7:20)
index.js (7:20)
```
Patch to [user test case](https://github.com/RomainLanz/rollup-test-case) to get Bublé object spread working:
```patch
diff --git a/index.js b/index.js
index 6b80681..844d6aa 100644
--- a/index.js
+++ b/index.js
@@ -10,4 +10,5 @@ class TestCase {
       evenMoreKey: 'testing',
     }
   }
-}
\ No newline at end of file
+}
+console.log({ foo: "bar", ...{ hello: "world" }});
diff --git a/rollup.config.js b/rollup.config.js
index 0b4058d..f9bb6fa 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -10,7 +10,10 @@ export default [
       { file: pkg.browser, format: 'umd', name: 'Fivb' }
     ],
     plugins: [
-      buble({ exclude: ['node_modules/**'] })
+      buble({
+        objectAssign: 'Object.assign',
+        exclude: ['node_modules/**'],
+      })
     ]
   },
 ]
```
```
$ rollup -c && cat dist/test.esm.js | node

index.js → dist/test.cjs.js, dist/test.esm.js, dist/test.umd.js...
created dist/test.cjs.js, dist/test.esm.js, dist/test.umd.js in 41ms
{ foo: 'bar', hello: 'world' }
```

**Comment by brettz9** [comment]
So can someone pull this if prepared as a PR?

**Comment by brettz9** [comment]
Actually, I was copying a boilerplate and not updating. Now that I updated from an older version of Rollup and rollup-plugin-buble, I'm not getting this problem with Rollup and buble anymore...

**Comment by trusktr** [comment]
I'm getting this error with Buble, and I don't have Rollup installed. And for me, it has nothing to do with spread. I've narrowed it down, it happens in a file with this content:

```js
    const B = A.subclass({
        foo(n) {
            if (n > 100) return -1;
            return super.foo(n+1); // RIGHT HERE
        }
    })
```

If I delete that line, it works.

**Comment by trusktr** [comment]
Hmmm, in fact, the website [throws a different (yet incorrect) error](https://buble.surge.sh/#%20%20%20%20const%20B%20%3D%20A.subclass(%7B%0A%20%20%20%20%20%20%20%20foo(n)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(n%20%3E%20100)%20return%20-1%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20super.foo(n%2B1)%3B%20%2F%2F%20RIGHT%20HERE%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)):

```
use of super outside class method (4:19)
```

It is completely okay to use `super` inside of concise methods outside of a class. I'll open an issue on Buble.

**Comment by trusktr** [comment]
New issue at https://github.com/Rich-Harris/buble/issues/124

**Comment by guybedford** [comment]
I believe this should have been fixed by https://github.com/rollup/rollup/pull/2100. But please reopen if it is still happening.

**Comment by RomainLanz** [comment]
Cool, I'll let you know if I still have this issue!

Thanks for the fix ❤️
