### ISSUE TITLE
Catch and print info when plugin throws an error

### ISSUE THREAD

**Issue by gauntface** [rollup/rollup#1625]
I just got the following problem from Rollup:

```
TypeError: Cannot read property 'names' of undefined
```

The problem was using async and await in my code while `rollup-plugin-uglify-es` is using an old version of uglify-es such that it can't handle this syntax.

It would have been incredibly useful is Rollup could call out that the error originated from the plugin since uglify-es / rollup-plugin-uglify-es didn't catch and report the error either.

**Comment by mhkeller** [comment]
A simple fix would be to add something like this in the catch block of `transformBundle` function

```js
        var buf = 5
        var section = code.split('\n').slice(err.line - buf, err.line + buf).join('\n')
        
        error({
          code: 'BAD_BUNDLE_TRANSFORMER',
          message: `Error transforming bundle${plugin.name ? ` with '${plugin.name}' plugin` : ''}: ${err.message}\n\n${section}`,
          plugin: plugin.name
        });
```

Adding some code highlighting maybe through [cardinal](https://www.npmjs.com/package/cardinal) could be nice as well. I'm not sure how to grab the name of the file that's throwing the error, though. Any thoughts? I can put in a PR if this sounds like a good solution.

**Comment by guybedford** [comment]
Better contextual information in plugin hooks is being tracked in https://github.com/rollup/rollup/issues/2250.
