### ISSUE TITLE
Rollup generates different bundles when cache is on and off

### ISSUE THREAD

**Issue by StreetStrider** [rollup/rollup#1626]
I'm using cache feature for watch builds in my build infrastructure. One day, my bundle start to throw an error in browser when I'm using cache and works ok if cache is off. I had checked the builds and it turned out that name mangling worked differently. Turned cache off to fix this.

[Here's the repo](https://github.com/StreetStrider/rollup-cache-issue). Install deps and do `npm test` to generate two bundles.

In case I delete test case repository, here's the archive:
[rollup-cache-issue-master.zip](https://github.com/rollup/rollup/files/1294281/rollup-cache-issue-master.zip)

**Comment by FinesseRus** [comment]
Duplicate for this issue: https://github.com/rollup/rollup/issues/1372

**Comment by StreetStrider** [comment]
Closing it prior to #1372 
Got a pretty simple repro here, though.

**Comment by FinesseRus** [comment]
@StreetStrider The repo is great. Please post it to https://github.com/rollup/rollup/issues/1372. And could you please leave a 👍 to show to the contributor that people care about the bug.
