### ISSUE TITLE
RangeError: Maximum call stack size exceeded with react-dom on 0.49.3

### ISSUE THREAD

**Issue by perrin4869** [rollup/rollup#1628]
Repro: https://github.com/perrin4869/rollup-react-dom-bug

Explanations are in the repro. This bug was introduced in `0.49.3`

**Comment by lukastaegert** [comment]
Duplicate of #1627 but thanks for the effort nonetheless it was just a few minutes ago 😉

**Comment by perrin4869** [comment]
lol cool!
