### ISSUE TITLE
Getting Error: A module cannot import itself 

### ISSUE THREAD

**Issue by adampotocki** [rollup/rollup#1630]
Getting this error with rollup, any suggestions on fixing this? 

Error: A module cannot import itself
node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/connect/tls.js (1:0)

**Comment by guybedford** [comment]
Duplicate of #1055.

**Comment by lukastaegert** [comment]
Thanks for checking this @guybedford, closing this in favour of the original issue.
