### ISSUE TITLE
[Documentation] reporting a wooly sentence

### ISSUE THREAD

**Issue by revelt** [rollup/rollup#1632]
https://github.com/rollup/rollup/wiki/pkg.module

"pkg.module will point to a module that has ES2015 module syntax but otherwise only syntax features that the target environments support."

Let's reword this because I can't comprehend this sentence.

Maybe splitting into two sentences would do?

1. (FIRST PART IS GOOD) - pkg.module will point to a module that has ES2015 module syntax.
2. (SECOND PART NEEDS REWORDING) - something along the lines (if I interpreted its intended meaning right) - "Make sure that your target environments support the new ECMAScript features used in your code."

**Comment by revelt** [comment]
no worries

**Comment by guybedford** [comment]
Sure, and please continue to post these things, it's useful - I just think the whole page will need a revamp at some point, but it is difficult to advise re workflows here currently while Node modules are still in flux. There are quite a few issues tracking this wiki page.

**Comment by revelt** [comment]
btw, will Rollup repo stay in GitHub or move out?

**Comment by lukastaegert** [comment]
Only speaking for myself here but unless there is a specific reason for leaving other than ideology, I would prefer we stay with Github for the time being.
