### ISSUE TITLE
Can a plugin trigger a new build when watch is enabled?

### ISSUE THREAD

**Issue by tkambler** [rollup/rollup#1634]
When rollup has been started with the `watch` option enabled, is it possible for a plugin to - after the initial build - arbitrarily decide that it would like to trigger / emit an `update` event that would cause rollup to regenerate the bundle?

My use case:

I've created a plugin - [rollup-plugin-import-globs](https://github.com/tkambler/rollup-plugin-import-globs) - that allows me to do this:

```
import './components/*';
```

This works great. There's only one hiccup - if I create a *new* file within this folder or delete an existing one, the watch doesn't seem to want to notice it. I had thought that it would be nice to be able to put my *own* watch in place within my plugin (based on the glob pattern passed) and then trigger my own "change" event later on.

Is this doable?

**Comment by guybedford** [comment]
I've implemented an approach for this in #2259.
