### ISSUE TITLE
WebAssembly 

### ISSUE THREAD

**Issue by jamen** [rollup/rollup#1636]
Hey!  I recently made [`rollup-plugin-wasm`](https://github.com/jamen/rollup-plugin-wasm) to try and support WebAssembly in Rollup.  I wanted to share the results so far.

Firstly, the base plugin (`wasm()`) allows you to import plain `.wasm` files:

```js
import createExample from './example.wasm'

// Initialize module
var example = createExample()

// Call WASM export
var foo = example.main()
```

This is fine if the compiler supports standalone binaries which you can import easily.

But, this plugin also allows you to require source files which have more complex conditions by using:

 - A `compile` method which turns source code into WebAssembly.
 - A `load` method for preparing WebAssembly exports (setting memory, tables, etc.)

By default, there is two configs implementing these that you can use:

 - `wasm.emscripten` for using C/C++ with [Emscripten](https://github.com/kripken/emscripten)
 - `wasm.wabt` for using WAT with [WebAssembly Binary Toolkit](https://github.com/kripken/emscripten)

Here is an example of `rollup.config.js` using Emscripten for C/C++ imports:

```js
import wasm, { emscripten } from 'rollup-plugin-wasm'

export default {
  plugins: [ wasm(emscripten) ]
}
```

And an example of how you would write code:

```cc
int main (int a) {
  return a * 3
}
```

```js
import { _main } from './example.cc'

// Calling C/C++ function
var foo = _main(3)
```

A good start!  But it is still limited in terms of the libraries you can use, because the loader is simple.

Ideas for the future include:

 - Testing a bit more complex C/C++ code.
 - Support for [Rust](https://github.com/linclark/rust-wasm-example), [Go](https://github.com/golang/go/issues/18892), [Elixir](https://github.com/jamen/elixir-wasm).
 - Support multiple lsource types.  Like using JS, C++, and Rust together.
 - Build something cool with it

**Comment by Rich-Harris** [comment]
Thanks, this is awesome! Have added it to the [list of plugins](https://github.com/rollup/rollup/wiki/Plugins). I'll close this issue as there isn't any action required for Rollup, but I'm excited to see where this goes.

**Comment by skandonkumar** [comment]
Hi, I was trying to build a JavaScript SDK over my C library. I converted my C library to WASM using EMScripten, which also provided me a wrapper JS code to call the C functions in JavaScript. I wrote my JavaScript SDK by making multiple calls to WASM and everything seemed to work. Now when I tried to build a bundle for production, I am encountering read errors. Can someone help me with my situation? Any suggestions would be appreciated. Thank You

**Comment by jamen** [comment]
@skandonkumar WebAssembly support in Rollup is not perfect. The only option right now is [`@rollup/plugin-wasm`](https://github.com/rollup/plugins/tree/master/packages/wasm), but its [not perfect](https://github.com/rollup/rollup/issues/2099). There's an effort to [support WebAssembly in Rollup core](https://github.com/rollup/rollup/pull/2113), though it hasn't been championed yet. Alternatively, you could try `fetch('program.wasm')` + [`WebAssembly.instantiateStreaming`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) instead using WebAssembly through Rollup.
