### ISSUE TITLE
Better support shared rollup.config.js

### ISSUE THREAD

**Issue by haraldrudell** [rollup/rollup#1639]
With lerna, most configuration is in a directory two levels up
rollup could better support this with the following enhancement.
If this is implemented, each package will not need to have a package.rollup.js

rollup.input can be provided using --input

Allow a rollup field in package.json:
```javascript
"rollup" : {
  "output": true, // will assemble rollup.output from package.json fields main and module
  "external": {
    "node": true, // will add all Node.js standard library imports to rollup.external
    "modules": ["react"], // will add these to rollup.external
    "dependencies": true, // will add all modules from dependencies to rollup.external
  },
  "clean": ["lib", "build"], // will add a cleanPlugin and
    // a node_modules/.bin/clean command for npm run clean
```

The clean plugin can be based on fs-extra.remove

Here’s a working plugin implementation:
```javascript
export default function cleanPlugin(dirs) {
  let didClean
  return {
    name: 'cleanPlugin',
    async load() {
      if (!didClean) {
        didClean = true
        await clean(dirs)
      }
    },
  }
}
```
And here’s the clean implementation using fs-extra:
```javascript
import fs from 'fs-extra'
import path from 'path'

export default list => clean(list).catch(errorHandler)

async function clean(args) {
  if (typeof args === 'string') args = [args]
  else if (!Array.isArray(args)) throw new Error('clean: package.json cleans field not non-empty string or array')
  args.forEach((s, index) => {
    const st = typeof s
    if (st !== 'string' || !s) throw new Error(`clean: index ${index}: not non-empty string: ${st}`)
  })
  console.log(`clean: ${args.join(' ')}…`)

  const projectDir = process.cwd()
  await Promise.all(args.map(s => removeIfExist(path.join(projectDir, s))))
  console.log('clean completed successfully.')
}

async function removeIfExist(p) {
  if (await fs.exists(p)) await fs.remove(p)
}

function errorHandler(e) {
  console.error(e instanceof Error ? e.message : e)
  process.exit(1)
}
```
and here ’s an example of fishing out main:
```javascript
const m = pkg.main
if (!m || typeof m !== 'string') throw new Error('package.json main field not non-empty string')
const slashIndex = m.lastIndexOf('/')
const hasExtension = !!~m.indexOf('.', ~slashIndex ? slashIndex : 0)
const main = `${m}${hasExtension ? '' : '.js'}`
```

The clean command is built using rollup-plugin-shebang and:
```javascript
export default function chmodPlugin(mode) {
  return {
    name: 'chmodPlugin',
    onwrite(bundle, data) {
      const filename = bundle && (bundle.file || bundle.dest)
      if (filename) fs.chmodSync(filename, mode >= 0 ? Number(mode) : 0o755) // rwxr-xr-x
    },
  }
}
```

**Comment by haraldrudell** [comment]
And rollup.input may be an object so that the rollup config becomes array outputting multiple ranspiled files: 
```
  "main": "lib/cleanlib",
  "bin": {
    "clean": "build/clean"
  },
  "rollup": {
    "input": {
      "src/cleanlib": true,
      "src/cleanbin": {
        "main": "build/clean",
        "shebang": true
      }
    }
  },
  "clean": [
    "build",
    "lib"
  ]
```

**Comment by evocateur** [comment]
I've built a private package to facilitate running rollup on a lerna tree, bailing early if nothing has changed since the last build (facilitating very quick incremental `lerna bootstrap`). It emphasizes convention over configuration, with a few overrides available via the `rollup` field in package.json. I should get around to open-sourcing it soon.

In other words, I don't think rollup core is the appropriate place for adapting to lerna semantics. rollup is perfectly capable of being configured to support those semantics, however.

**Comment by haraldrudell** [comment]
I did, too, come up with an ECMAScript 2015 module for this purpose to have no-configuration npm modules. However, this isn’t Lerna specific

The core issue is Rollup’s requirement that rollup.config.js be a file.
If rollup.config.js could be a package, the world would be a better place #1640 

Since Rollup’s introduction into a project is as an npm script, it would be a good idea for Rollup to fetch rudimentary configuration from that file, in particular fields main, module and dependencies, then extend to it for input value and other things.

**Comment by evocateur** [comment]
`rollup -c node:my-rollup-config-package` doesn't work for you?

(`my-rollup-config-package`'s default export needs to be the config object, same as a `rollup.config.js`)

**Comment by haraldrudell** [comment]
lerna run test and lerna run build are really good with Rollup, since improperly transpiled dependencies fails the final Rollup output with mysterious errors, and it is hard to determine which code came from where. Lerna’s ability to immediately test dependencies outs the culprit immediately, and brings troubleshooting to a much smaller chunk of code.

**Comment by haraldrudell** [comment]
Once can provide plugins in package.json by listing their names and have rollup.config.js try to execute whatever plugin function name it gets. Would look really cool

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
