### ISSUE TITLE
[Question] does this bundle latest Es2018?

### ISSUE THREAD

**Issue by nowindowsowrking** [rollup/rollup#1644]
Is there any build in support for bundling async generatirs, dynamic import etc? I noticed Acorn was used, but it lack support for it.

**Comment by Conduitry** [comment]
Unfortunately not - as you noticed, Rollup uses Acorn for parsing, and Acorn does not support ES2018 features yet. Acorn's policy is to not support feature proposals until they reach stage 4 ('accepted').

**Comment by KFlash** [comment]
@Conduitry You could look at [this one](https://github.com/cherow/cherow) if you need latest ES2018. Still working on this, but should parse everything after the ECMA specs.
