### ISSUE TITLE
Windows10: Error... but it works on Linux/Mac

### ISSUE THREAD

**Issue by BorderCloud** [rollup/rollup#1654]
Hello

My students have a problem with [the same code](https://github.com/BorderCloud/sgvizler2).

On linux, the code of rollup works :
```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('jquery')) :
	typeof define === 'function' && define.amd ? define(['exports', 'jquery'], factory) :
	(factory((global.sgvizler2 = {}),global.jQuery));
}(this, (function (exports,jqueryProxy) { 'use strict';
```
But on windows10, there is an error with a double simple quote...
```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('jquery')) :
	typeof define === 'function' && define.amd ? define(['exports', 'jquery'], factory) :
	(factory((global[''sgvizler2''] = {}),global.jQuery));
}(this, (function (exports,jqueryProxy) { 'use strict';
```
=> the fix is simple : (global['sgvizler2'] 

How can I fix this problem on Windows10 ? 

Thanks

**Comment by kzc** [comment]
I don't run Windows but my guess is that it's probably a Windows shell quoting issue.

Try removing the single quotes on [these two lines](https://github.com/BorderCloud/sgvizler2/blob/bcdf4ff523db8f91b05e570c9c6ceb8dcaed11f5/package.json#L22-L23):
```
    "build:browser": "rollup -c config/exports/rollup.config.ts -f umd --name 'sgvizler2' -o build/browser/sgvizler2.js",
    "build:browser-minify": "rollup -c config/exports/minify.config.ts -f umd --name 'sgvizler2' -o build/browser/sgvizler2.min.js",
```
The `bash` shell drops those quotes automatically. Windows retains them.

**Comment by kzc** [comment]
Recommendation above should be sufficient to solve the issue, but this issue brings to light a Rollup bug:

```js
	return shouldUseDot.test( prop ) ? `.${prop}` : `['${prop}']`;
```
https://github.com/rollup/rollup/blob/v0.50.0/src/finalisers/shared/sanitize.js#L6

The single quote character should be escaped.

**Comment by BorderCloud** [comment]
Thanks @kzc ! it's a shell quoting issue. 
I will fix this problem in my script.

Bye

**Comment by kzc** [comment]
Thanks for confirmation.

Please leave ticket open to fix bug mentioned in https://github.com/rollup/rollup/issues/1654#issuecomment-332112556

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
