### ISSUE TITLE
globals: option does not add module ID to externals

### ISSUE THREAD

**Issue by tmcw** [rollup/rollup#1656]
From the command line flags:

```
-e, --external              Comma-separate list of module IDs to exclude
-g, --globals               Comma-separate list of `module ID:Global` pairs
                              Any module IDs defined here are added to external
```

However, this doesn't seem to be the case, at least judging by the configuration file strategy.

Testcase repo here: https://github.com/tmcw/rollup-globals-testcase

external:

```
import node from "rollup-plugin-node-resolve";

export default {
  sourcemap: "inline",
  input: "in.js",
  output: {
    file: "out.js",
    format: "iife",
    name: "Out"
  },
  external: ['acorn'],
  plugins: [
    node({jsnext: true}),
  ]
};
```

globals:

```
export default {
  sourcemap: "inline",
  input: "in.js",
  output: {
    file: "out.js",
    format: "iife",
    name: "Out"
  },
  globals: {
    'acorn': 'Acorn'
  },
  plugins: [
    node({jsnext: true}),
  ]
};
```

- With `external`, acorn is not included in the bundle
- With `globals`, it is

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
