### ISSUE TITLE
Feature Request: friendly handling of `--output path/`

### ISSUE THREAD

**Issue by jasonkarns** [rollup/rollup#1657]
In the interest of sane defaults, (and not specifying more than is absolutely necessary), it would be nice if I could pass a directory name to `--output`.

Expectation: if `--output` ends with `/`, then the file is written to that directory as `index.js`. (Or alternatively, could mimic babel's `-d` behavior and use the same filename as the entrypoint. I would consider either approach to be sane defaults.)

`rollup foo.js -o dist/` -> `dist/index.js` or `dist/foo.js`

This would make package.json configurations much cleaner. Assuming one is leveraging `pkg.directories` and `$npm_package_*` env vars to DRY up configuration, it would allow a build script to be `"build": "rollup $npm_package_main -o $npm_package_directories_dist"`, which is super nice, especially considering the `dist/` path in this example is frequently referenced in a `clean` npm script.

**Comment by guybedford** [comment]
There is now a `--dir` option in builds which should roughly provide this.
