### ISSUE TITLE
Modifying Error.code may become a problem!?

### ISSUE THREAD

**Issue by clintwood** [rollup/rollup#1658]
I encountered [this issue](https://github.com/standard-things/esm/issues/113) when using Rollup with  `@std/esm`.  @jdalton pointed me to [`makeNodeError`](https://github.com/nodejs/node/blob/28a0af358ac998f94052199dc62a8140e8a11ac5/lib/internal/errors.js#L17-L32) where it looks like node is making `Error.code` readonly.

I do not know what the correct standard on the above use of `code` property on an `Error` object is so just giving a heads up in case this becomes an issue.

**Comment by jdalton** [comment]
Related rollup code [here](https://github.com/rollup/rollup/blob/b949eb08169115ff66648838cbc4833379bf9440/src/utils/transform.js#L30).

**Comment by jdalton** [comment]
I opened a [Node issue](https://github.com/nodejs/node/issues/15658) too.

**Comment by jdalton** [comment]
This has been fixed in Node https://github.com/nodejs/node/commit/42a2a9badb6974e47b98aaee052e9710f34b93e8 :tada:

**Comment by clintwood** [comment]
@jdalton I guess I'll just close this then as it no longer applies here.
Thanks for pushing the issue through to Node.
