### ISSUE TITLE
Customize IIFE export destination

### ISSUE THREAD

**Issue by amatiasq** [rollup/rollup#1659]
Right now using `iife` format I get 

```javascript
var <moduleName> = (function() { ... }());
```

But I'm building multiple modules and I want them all to share a namespace so I'm trying to do something like this:

```javascript
window.myNamespace = window.myNamespace || {};
window.myNamespace.<moduleName> = (function() { ... }());
```

I can add code before and after the module, and I can add code inside the module but what I really need is to remove the  `var` keyword so generated module is `<moduleName> = (function() { ... }());`. Then I can have 

```javascript
window.myNamespace = window.myNamespace || {};
window.myNamespace.
```

As banner and it will work but I can't find a way to customize IIFE header. Is there a way?

**Comment by ondras** [comment]
@amatiasq this is apparently possible by using a "myNamespace.moduleName" syntax for the module name. I added an example to Rollup's docs: https://github.com/rollup/rollupjs.org/pull/88

**Comment by amatiasq** [comment]
OMG I spend so much time on this and the solution was always there. Thanks @ondras
