### ISSUE TITLE
include UMD bundle in my final builded bundle

### ISSUE THREAD

**Issue by sebastienminne** [rollup/rollup#1661]
Hi, 

I was wondering if this could be done : 

I'd like to include an UMD bundle (angular2-markdown in my case) which is a dependency of the angular module I want to bundle.

is there a way to include this UMD module in my builded bundle  ?

**Comment by amenadiel** [comment]
Provided your entry point references that bundle, you can use [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) to handle that bundle as an ES6 module.

Said plugin will let you define named exports besides the default one, if you need to.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
