### ISSUE TITLE
[feature request] passthrough CLI args

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#1662]
I would like to be able to pass arguments, , which are not rollup specific, through the CLI to my script. At the moment rollup thinks I'm trying to pass him a file to bundle and therefore fails loudly on [those lines](https://github.com/rollup/rollup/blob/b949eb08169115ff66648838cbc4833379bf9440/bin/src/run/index.js#L12-L28). 

I would propose rollup to handle only `-i` flag as input. If this is something you'd like I can send a PR.

**Comment by kzc** [comment]
Could you give an example? I don't follow what it means to pass the Rollup CLI arguments it doesn't use or what program those arguments would be passed to exactly.

**Comment by Andarist** [comment]
I have wanted to do something like
`npm run partial-build -- arg1 arg2`
where 
`"partial-build": "cross-env NODE_ENV=development PARTIAL_BUILD=true rollup -c",`

and use my passed args in `rollup.config.js` by accessing `process.argv`.

I must admit though that after a thought this might not make much sense ;) finally i've just used rollup's JS API instead of the CLI, downside of this though was knowing how to process rollup's config
```js
var rollupConfig = require('../rollup.config.js');

rollup.rollup(rollupConfig).then(function(bundle) {
  return bundle.generate(rollupConfig.output);
}).then(function(result) {
  process.stdout.write(result.code);
});
```

Imho the fact that I need to pass `rollupConfig.output` to the `bundle.generate` call is quite a leaking implementation detail.

**Comment by guybedford** [comment]
CLI arguments starting with `--config-[anything]` are supported as of https://github.com/rollup/rollup/pull/1926, which I believe resolves this issue.

**Comment by aleclarson** [comment]
@guybedford I don't see it mentioned in the docs

**Comment by lukastaegert** [comment]
It is mentioned briefly at the end of the https://rollupjs.org/guide/en#configuration-files configuration files section
