### ISSUE TITLE
Support for watching new entry points upon creation

### ISSUE THREAD

**Issue by mhkeller** [rollup/rollup#1663]
Similar to https://github.com/rollup/rollup/issues/863 with added difference that if, say, your glob is `src/*.js` and you create a new file `src/foo.js`, a watch will be initialized on that path and it will be bundled separately.

**Comment by aubergene** [comment]
You need one config per input file, a glob isn't supported

**Comment by mhkeller** [comment]
Thanks @aubergene. That issue didn't end up in a place that is as relevant to this. Here it is rephrased:

Allow to watch a glob such as`src/*.js`. When you create a new file `src/foo.js`, a watch will be initialized on that path and it will be bundled separately according to a config template. You will need `output` to be a function to handle a dynamic file path.

**Comment by TrySound** [comment]
@mhkeller watch works for all files in bundle. Why watch not bundled files which are matched to glob?

**Comment by lukastaegert** [comment]
Even though I can imagine valid use cases for this, I do not think this should be part of core-rollup as it is a rather complicated feature with IMO very limited demand. Couldn't you solve this with an external tool/script?
* You implement your own watcher for new files in the relevant places
* When a file is added (or removed), rollup's watch mode is cancelled, then the (array-based) config is rewritten (extended/shortened), then rollup watch mode is started again
* For config templates, you might e.g. take a look at [ejs-templates](https://www.npmjs.com/package/ejs)

Depending on your solution, this might at some point become an OSS tool that others could benefit from as well.

**Comment by mhkeller** [comment]
@TrySound The use case is you are working on a project where you want to create a new javascript file during a watch and have that be bundled also. Say, in an app that might have multiple IIFE files.
@lukastaegert ya that seems fine. I currently have this implemented with a separate watch tool but thought maybe there would be a way to roll it in https://github.com/bloomberg/wsk.example/blob/master/build/tasks/rollup/watch-for-new.js

Thanks for taking a look.
