### ISSUE TITLE
How to handle global when format is 'es'?

### ISSUE THREAD

**Issue by robhicks** [rollup/rollup#1665]
I have identified an Javascript library (incremental-dom) as both a global and external. I'm loading the library in a script tag. 

When the rollup format is 'iife' the library in injected into the iife and everything works.  

However when I use the 'es' format, the global is never referenced and the browser throws a type error: 

```Uncaught TypeError: Failed to resolve module specifier 'incremental-dom'```

Here's my rollup.config.js file:

```JavaScript
const path = require('path');
const root = process.cwd();
const string = require('rollup-plugin-string');
const superviews = require('rollup-plugin-superviews');

export default [
  {
    input: path.resolve(root, 'src', 'idx-admin-tab', 'component.js'),
    plugins: [
      superviews({include: 'src/**/*.html'}),
      string({include: ['src/**/*.css', 'src/**/*.svg']})
    ],
    globals: {'incremental-dom': 'IncrementalDOM'},
    external: ['incremental-dom'],
    output: {
      file: path.resolve(root, 'dist', 'idx-admin-tab.es.js'),
      format: 'es'
    }
  }
];

**Comment by guybedford** [comment]
Typically when loading globals from ES modules a custom adapter module containing eg `export { globalName }` is necessary to handle this.
