### ISSUE TITLE
Rollup importing unused exports into codebase from shared NPM libraries

### ISSUE THREAD

**Issue by davidrhyswhite** [rollup/rollup#1668]
A common practice in shared libraries seems to be using an index similar to this in an NPM module:

```javascript
export {default as Button} from '/components/Button';
export {default as Blips} from './components/Blips';
```

So then in my app I could write:

```javascript
import { Blips } from 'shared-npm-lib';
Blips();
```
Rollup doesn't seem to tree shake this and instead pulls in both `Button` and `Blips` even though Button is not actually used beyond being imported?

Could this be a bug with tree-shaking in rollup?

I've got a REPL example here:

https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEJsaXBzJTIwJTdEJTIwZnJvbSUyMCcuJTJGaW5kZXgnJTNCJTVDbiU1Q25CbGlwcygpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmluZGV4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMEJ1dHRvbiU3RCUyMGZyb20lMjAnQnV0dG9uJyUzQiU1Q25leHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBCbGlwcyU3RCUyMGZyb20lMjAnQmxpcHMnJTNCJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJCdXR0b24uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBCdXR0b24oKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ0J1dHRvbicpJTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJCbGlwcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMEJsaXBzKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdCbGlwcycpJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment]
Hi @davidrhyswhite, thanks for reporting this. Looking at your example, several things strike me as odd:
* You use a relative path "./index" for index.js but non-relative paths for Button and Blips. If you do not use a plugin such as rollup-plugin-node-resolve, you always need to use relative paths.
* Button and Blibs do not have default exports, just named exports, so `export {default as Button} from './Button'` should not work anyway

If I change both of these things, the output looks quite right to me:

https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEJsaXBzJTIwJTdEJTIwZnJvbSUyMCcuJTJGaW5kZXgnJTNCJTVDbiU1Q25CbGlwcygpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmluZGV4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMEJ1dHRvbiU3RCUyMGZyb20lMjAnLiUyRkJ1dHRvbiclM0IlNUNuZXhwb3J0JTIwJTdCZGVmYXVsdCUyMGFzJTIwQmxpcHMlN0QlMjBmcm9tJTIwJy4lMkZCbGlwcyclM0IlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMkJ1dHRvbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBCdXR0b24oKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ0J1dHRvbicpJTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJCbGlwcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBCbGlwcygpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnQmxpcHMnKSUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by davidrhyswhite** [comment]
Hi @lukastaegert, ah I see, sorry I attempted to type that from memory of how our app works.

I've changed it to match more closely what I was trying to achieve.

I can actually see why it's not quite working now and it looks like it may be an issue with one of our rollup-plugins. I'll create a little sample app over the weekend that does something similar with our plugins.

https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEJsaXBzJTIwJTdEJTIwZnJvbSUyMCdhbi1ucG0tbW9kdWxlJyUzQiU1Q24lNUNuQmxpcHMoJ2JsaXBzLi4uJyklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYW4tbnBtLW1vZHVsZSUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBCdXR0b24lN0QlMjBmcm9tJTIwJy4lMkZCdXR0b24nJTNCJTVDbmV4cG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMEJsaXBzJTdEJTIwZnJvbSUyMCcuJTJGQmxpcHMnJTNCJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJCdXR0b24uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMChzdHIpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnQnV0dG9uJyUyQyUyMHN0ciklM0IlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMkJsaXBzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAoc3RyKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ0JsaXBzJyUyQyUyMHN0ciklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by guybedford** [comment]
The reason this scenario can't be tree-shaken is because we don't know that the external module is pure necessarily.

I believe this should work with the `treeshake.pureExternalModules = true` option though.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
