### ISSUE TITLE
Rebuilds don't happen in watch mode after the first rebuild.

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#1669]
Seems to be happening here too (it was [previously happening to me with rollup-watch](https://github.com/rollup/rollup-watch/issues/61))

**Comment by talmobi** [comment]
You could try `npm install --save-dev chokidar`. If I remember correctly `rollup` will use `chokidar` by default if it finds it in your `node_modules` ( instead of its own custom cocktail wrapper around `fs.watch` )

It's been some time since I used `rollup` ( using `browserify` again ) - but I did have pre v0.50.0 forked/private packages with working `--watch` that may work temporarily if the `chokidar` installation doesn't work out.

https://www.npmjs.com/package/@talmobi/rollup
https://www.npmjs.com/package/@talmobi/rollup-watch

**Comment by trusktr** [comment]
No luck with chokidar.

**Comment by giovanniRodighiero** [comment]
Same problem here. 
I got it working using the `rollup.watch` programmatically though, here's a simplified version of my watch script in case you interested:
```
const rollup = require('rollup');

const config = {
input: 'src/assets/index.js',
output: {
    file: './public/bundle.js',
    format: 'iife',
    sourcemap: true,
  },
watch: {
    chokidar: true,
    include: 'src/assets/**'
},
plugins: [...]
}

const watcher = rollup.watch(config);

watcher.on('event', event => {
  console.log(event.code)
  // event.code can be one of:
  //   START        — the watcher is (re)starting
  //   BUNDLE_START — building an individual bundle
  //   BUNDLE_END   — finished building a bundle
  //   END          — finished building all bundles
  //   ERROR        — encountered an error while bundling
  //   FATAL        — encountered an unrecoverable error
});
```

You'll have to run it "by hand" with node, like `$ node rollup-watch-script.js`

**Comment by aubergene** [comment]
Can you post an example repo to recreate the issue please

**Comment by ezze** [comment]
I faced the same issue and created [a repo to reproduce it](https://github.com/ezze/rollup-watch-issue-demo). It uses both `watch` CLI flag and `chokidar` option in JavaScript API (based on @giovanniRodighiero's sample code). Further digging led me to stating the fact that the problem occurs only when files are changed in IDE. I use PhpStorm, and it creates temporary files on source files' change. When I disable `safe write` option in IDE settings everything works fine, at least for this small repo.

**Comment by aubergene** [comment]
Ah, yes it looks like "safe write" writes to a temporary file and then unlinks and links the file, which isn't triggering the change. Seems to occur for other [projects too](https://www.jetbrains.com/help/phpstorm/system-settings.html). @trusktr please can you confirm what editor you're using when this occurs.

**Comment by trusktr** [comment]
I'm using NeoVim, and have it set **_not_** to write any temporary files anywhere in my project, as far as I know. All temporary files are written to `~/.vim`, and AFAIK it only writes directly to files in the project.

Here's my repo: http://github.com/trusktr/infamous.

You can clone it, then `npm install && npm run build-global -- -w` which runs `rollup -c` with the `-w` option.

Then you can try editing a file multiple times and see if it starts failing.

**Comment by Meshu** [comment]
Hi there, I am facing the exact same issue, the watcher stops picking up changes after a seemingly arbitrary amount of time.

In my case I am watching on the output of the bucklescript compiler, which afaik writes directly to the disk too.

**Comment by trusktr** [comment]
What I do to save time now, is to keep working on code while it is compiling, then my terminal makes a sound when a process finishes so I know when it finishes then I go test it, so I try to save time by either working on other code, or ☕️ . 😃

**Comment by trusktr** [comment]
I just upgraded to Rollup `0.53.0` and the behavior is now worse. When I run `rollup -c -w`, the program exits after the first build and doesn't even try to watch anything. However, it does enter into the temporary buffer during the build, so when we return to the command line all the output is gone. It's just that Rollup exits and doesn't watch anything. 😕

**Comment by shellscape** [comment]
@trusktr if you have a spare moment, could you confirm that the latest version exhibits the same behavior?

(looks like this is similar to #1666)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
