### ISSUE TITLE
Rollup export code is not compatible with IE 11.

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#1671]
I'm exporting things like this:

```js
export {
    DeclarativeBase,
    HTMLNode,
    HTMLPushPaneLayout,
    HTMLScene,
    WebComponent,
    useDefaultNames,
}
```

and rollup converts it to:

```js
var index$16 = Object.freeze({
	get DeclarativeBase () { return DeclarativeBase; },
	HTMLNode: HTMLNode,
	HTMLPushPaneLayout: HTMLPushPaneLayout,
	HTMLScene: HTMLScene,
	WebComponent: WebComponentMixin,
	useDefaultNames: useDefaultNames
});
```

This causes IE 11 to crash, because IE 11 (and below) doesn't understand the `get foo() {}` Object initializer shorthand syntax. It throws the infamous `Object expected` error.

Even with Buble set to `target: { ie: 10 }` Rollup ignores this and make breaking code.

Looking forward to a fix! There doesn't seem to be a way to configure Rollup's bundle output target like we can with Buble.

**Comment by trusktr** [comment]
As a workaround, I can run the output code through a Babel step to fix just the object initializer shorthand.

**Comment by looeee** [comment]
I just opened up the console in IE 11.15.16299.0IC and entered 

```js
var DeclarativeBase = 3;

 var index$16 = Object.freeze( {
	get DeclarativeBase () { return DeclarativeBase; },
	HTMLNode: 2,
	HTMLPushPaneLayout: 3,
	HTMLScene: 4,
	WebComponent: 5,
	useDefaultNames: 6
} );
```

And I don't get any error messages. Perhaps this is fixed in the latest version?

**Comment by trusktr** [comment]
Oops, sorry, I read [this MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) which says "No" for everything in IE. It works actually.

I am getting an `Object expected` error, but it wasn't because of that, so when I saw that MDN page I thought IE 11 didn't support anything (because that page mentions get/set accessors).
