### ISSUE TITLE
Accessing re-exported class breaks output

### ISSUE THREAD

**Issue by NaridaL** [rollup/rollup#1672]
```ts
// index.js
export * from './B2'
// B2.js
export class B2 {
}
(function (B2) {
    B2.asldk = 0;
})(B2 || (B2 = {}));
```
 results in:
```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

class exports.B2 { // ERROR: "unexpected symbol '.'"
}
(function (B2) {
    B2.asldk = 0;
})(exports.B2 || (exports.B2 = {}));

```

the input is what TypeScript generates for 
```
export class B2 {}
export namespace B2 {
	export const asldk = 0
}
```

See https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY2xhc3MlMjBCMiUyMCU3QiU1Q24lN0QlNUNuKGZ1bmN0aW9uJTIwKEIyKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBCMi5hc2xkayUyMCUzRCUyMDAlM0IlNUNuJTdEKShCMiUyMCU3QyU3QyUyMChCMiUyMCUzRCUyMCU3QiU3RCkpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by ceymard** [comment]
This bug is currently preventing me from using rollup to build my library. This is really unfortunate :(

**Comment by guybedford** [comment]
This is fixed as of 0.56.0.

**Comment by NaridaL** [comment]
@guybedford That got unfixed, see #2048, we should probably leave this open.

**Comment by guybedford** [comment]
@NaridaL as far as I can tell that is a different issue? `exports.B2` being written into the name of the class position is definitely fixed. Perhaps you're thinking of https://github.com/rollup/rollup/issues/1914.

**Comment by ceymard** [comment]
From what I've seen I'm not affected anymore by that problem.
