### ISSUE TITLE
Add rollup-plugin-wasm to the rollup organisation

### ISSUE THREAD

**Issue by ColinEberhardt** [rollup/rollup#1673]
Hi,

You may have already noticed that @jamen has created a WebAssembly plugin:

https://github.com/jamen/rollup-plugin-wasm/

I also independently created a similar plugin:

https://github.com/ColinEberhardt/rollup-plugin-webassembly

We've decided [the best thing to do is team up](https://github.com/ColinEberhardt/rollup-plugin-webassembly/issues/1), the community doesn't need two plugins that do the same thing!

Anyhow, it would be great if we could collaborate within the rollup organisation, rather than within one of our own 'user repositories'. Would you be open to having this plugin moved to the organisation?

**Comment by lukastaegert** [comment]
Hi @ColinEberhardt @jamen,

this sounds great and I would really support this! Unfortunately I am not sure this is in my power to do or even to decide. However if there is no other communication/objections from someone else until the end of the week, I will take a look what needs to be done and if I can do it.

**Comment by lukastaegert** [comment]
Hi, I have just added you to the organization! You should be able to transfer the repo yourself now, see
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by jamen** [comment]
@lukastaegert Thanks!  Transferred.  :)

**Comment by ColinEberhardt** [comment]
Thanks @lukastaegert / @jamen - I'll deprecate my plugin and start working on the one in the rollup organisation :-)
