### ISSUE TITLE
Can multi-bundle projects share code?

### ISSUE THREAD

**Issue by bdwain** [rollup/rollup#1679]
I'm trying to create a library (let's call it foo-bar), and i'd like my exports to be organized such that you can do

```js
import blah from 'foo-bar'
import whatever from 'foo-bar/thing1';
import hello from 'foo-bar/thing2';
//etc...
```

Each one has a separate entry point. I'm able to compile all of them since the ability to export an array of configs was added, but one issue is that the shared code is still duplicated. if thing1 and thing2 both depend on a shared file, its contents will be in both generated files.

Is it possible to extract shared code between multi-bundle projects to its own shared file that is imported from each file that uses it? 

It looks like the config array thing just runs the bundler in parallel with no communication between instances, so I imagine this would be a large undertaking. But I was just curious if this was even possible or something that would be on the road map at some point.

Thanks!

**Comment by guybedford** [comment]
Multiple entry points are now supported in Rollup to do exactly this sort of thing. See the documentation at https://rollupjs.org/guide/en#experimental-code-splitting.

**Comment by JomoPipi** [comment]
> Multiple entry points are now supported in Rollup to do exactly this sort of thing. See the documentation at https://rollupjs.org/guide/en#experimental-code-splitting.

it doesn't show up on the website anymore. What did it get replaced with?

**Comment by lukastaegert** [comment]
It is always enabled.

**Comment by chase-moskal** [comment]
@JomoPipi i found information about it here: https://rollupjs.org/guide/en/#code-splitting
