### ISSUE TITLE
importing with * and setting member result to variable gives error

### ISSUE THREAD

**Issue by martikaljuve** [rollup/rollup#168]
Importing a module with `*` works, but setting its member to a variable fails for me. Using **v0.18.4**.

```js
// b.js
export function foo() {
	return 10;
}

export var bar = 20;
```

```js
// index.js
import * as bb from './b';

var val = bb.foo();
var val2 = bb.bar;
```

```bash
$ rollup --input index.js --output rollup.js
```

gives error:
```bash
TypeError: Cannot read property 'node' of undefined
    at /../npm\node_modules\rollup\src\Module.js:279:18
    /../
```

This works:
```js
// index.js
import { foo, bar } from './b';

var val = foo();
var val2 = bar;
```

This works also, as I don't set the results to variables:
```js
// index.js
import * as bb from './b';

bb.foo();
console.log(bb.bar);
```

Sorry if this has been asked before, didn't find a similar case.

**Comment by Victorystick** [comment]
@martikaljuve Thank you for reporting this bug! We haven't encountered this issue before. This definitely isn't expected behavior.

**Comment by Rich-Harris** [comment]
This turned out to be a nice simple fix (one-liner) so I've pushed out a new release, 0.18.5. Thanks for the test case
