### ISSUE TITLE
--watch fails when output.file is stdout

### ISSUE THREAD

**Issue by nwpappas** [rollup/rollup#1680]
Asking Rollup to `--watch` a configuration that outputs to `stdout` is failing.

My config exports an array with 2 outputs. The first build _does_ output a file and works just fine. The second build _does not_ have an output:

```js
  {
    input: 'src/scss/build.js',
    output: {
      format: 'es'
    },
    plugins: [
      sass({
        output: './dist/fleet.css',
        options: {
          outputStyle: ( process.env.NODE_ENV === 'production' ? 'compressed' : 'nested' )
        }
      })
    ]
  }
```

My NPM scripts are super simple:

```json
  "scripts": {
    "dev": "cross-env NODE_ENV=development rollup -c -w",
    "build": "cross-env NODE_ENV=production rollup -c"
  },
```

The `build` script works as expected. Removing `-w` from the `dev` script compiles everything as it should but, obviously, doesn't watch.

**Use Case**

The use case for this is a framework that has a JS and SCSS portion, which are related but not dependent on each other. The JS framework is written in Vue, but we may also duplicate it for React (or other) which will compile into its own bundle. The same SCSS applies to both JS bundles, so it isn't built as part of one.

In the SCSS directory, a simple `build.js` file imports the SCSS file:

```js
import './fleet.scss';
```

Because there is no JS deal with, the output is empty. I don't want to have to clean up an empty bundle either, so I leave the output blank.

**Comment by shellscape** [comment]
@nwpappas what would your desired behavior here be? I can see a few options:

1. Watch mode ignores and/or warns for configurations which are set to `stdout`
1. The CLI is improved to exclude a config by index or name
1. The CLI is improved to choose a config to run by index or name

It would be difficult to output a build to stdout during watch mode, as it's a long-running process.

**Comment by nwpappas** [comment]
In my use case, the first option is a perfectly reasonable behavior.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
