### ISSUE TITLE
rollupjs.org is down - no docs!

### ISSUE THREAD

**Issue by geoctrl** [rollup/rollup#1681]
Steps to reproduce: visite [rollupjs.org](https://rollupjs.org/)

**Comment by zulaica** [comment]
➕ 1️⃣ 
![screen shot 2017-10-20 at 2 05 27 pm](https://user-images.githubusercontent.com/4645082/31841758-c5922a26-b59f-11e7-8733-71df0839f69b.png)

**Comment by Rich-Harris** [comment]
Unfortunately https://zeit.co/now appears to be having some major problems — I can't access any sites I run on Now, nor can I redeploy them etc. I'm hoping that it'll get resolved soon (watching https://twitter.com/zeit_status), but in the medium term we may need to migrate to another provider.

In the meantime, if you're sufficiently motivated you can run the site locally like so:

```bash
git clone https://github.com/rollup/rollupjs.org.git
cd rollupjs.org
yarn
yarn run dev
```

It should then be accessible at http://localhost:3001. Or you can read the [raw markdown](https://github.com/rollup/rollupjs.org/tree/master/guide/en)!

**Comment by bdwain** [comment]
looks like it's back up

**Comment by geoctrl** [comment]
🎉
