### ISSUE TITLE
Supporting `import window from 'window'` in unit tests

### ISSUE THREAD

**Issue by alexchao** [rollup/rollup#1683]
Hello, this is more of a question than a bug or feature request, so sorry if this is the wrong place for this.

I'm using rollup in a project where I'd like to import globals `window` and `document` via the IIFE argument list, so I've got the `globals` option set in my config:

```js
    ...
    globals: {
      window: 'window',
      document: 'document'
    },
    ...
```

... and I've got the following sprinkled about in a few modules where the globals get used:

```js
import * as window from 'window' // or just `import window from 'window'`
import * as document from 'document'

const doesThingsWithWindow = function () {
  const foo = window.navigator.someProperty
  // ...
}
```

As a follow up to the question in #556, I'm wondering if there's a nice way to make this work in my unit tests. I have unit tests (Mocha) for each module, and each test module imports the module being tested. As one might expect though, the imports for `'window'` and `'document'` can't be resolved by Node (`Cannot find module 'window'`) when the test runs.

I was thinking I could just `import * as window from 'window'` in my entry point module (which doesn't really need a unit test) and pass `window` and `document` around within my app via dependency injection, so that none of the other modules would need the imports. Beyond this, is there another way to keep these imported globals as "globals" within the context of the IIFE and still support my unit test setup?

Thanks!

**Comment by TrySound** [comment]
@alexchao Do you think `import * as window from 'window'` make sense over `import window from 'window';`? Semantically it's not correct.

**Comment by alexchao** [comment]
@TrySound Oh, I was mostly just following @Victorystick 's suggestion in #556, but am not partial to using it. In any case, I think `import window from 'window'` is still subject to the issue I raised above.

**Comment by DavidBabel** [comment]
Hey, i got the same issue, did you found a workaround ?

**Comment by alexchao** [comment]
I haven't yet. In my particular case, I've just refactored my code to inject `window` and `document` at the app entrypoint, and then internally, the app just passes them around to all the functions and components that need them (so that no module except the entrypoint module actually has an `import window from 'window'` statement). Sort of works...

**Comment by DavidBabel** [comment]
Did the same, thanks for your answer.

I actually think the issue is test unit side. It should be able to ignore or complete imports.

**Comment by David-Else** [comment]
Could someone help me? This is the exact topic I have been struggling with for days!

I have found out how to use jsdom-global and jsdom to recreate the browser global `window` and `document` AND a fake HTML file for your JS to act on in tests. This lets Mocha test actual web apps. Can't believe it took me so long to get this basic information! Everyone online is a node hipster who thinks this is all obvious :)

Just NPM install jsdom-global and jsdom and add this to the test file:

```
**test.js**

require("jsdom-global")();
document.body.innerHTML = '<!DOCTYPE html><html><head></head><body><div id="js-gender-box"><input id="demo" placeholder="Select date" data-alt-input=true data-alt-format="F j, Y"><div id="results"></div></div></body></html>'
```

I want to now import the rollup bundle.js file and run mocha tests on it, but everything is going wrong. I have no idea about Node importing, I wish I could just use the normal ES6 modules I am used to.

Rollup is creating my bundle as an IIFE, how can I import it into the test file so I can run Mocha tests in it? I add the following, but the code does not seem accessible:

`var codeToTest = require("../dist/bundle");`

I want it to be an IIFE as it is all working great in the browser, but I assume that is restricting the scope of my app so I can't access the functions and objects in it... what do people advise? I don't want to make some special version that has exports, I would like to just load the final bundle and run all my tests... or is this just a dream :)

**Comment by mxcoder** [comment]
Hi @David-Else , maybe you can file this plugin helpful: https://github.com/rollup/rollup-plugin-inject

Basically what I'm testing right now is to have my iife like
```
(function (doc,win$1) {
...
})(document, window)
```
All over my modules I use `win.screen` (for example)

Then for use with other libs, like jest, I might need to add a setup script (pre-tests) to bind win to window, and let jest and jsdom do their thing.

My current rollup code (I'm using the node api) looks like this:
```
const rollupConfig = {
  input: inputFile,
  format: 'iife',
  sourcemap: false,
  external: ['window', 'document'],
  globals: {
    'window': 'window',
    'document': 'document'
  },
  plugins: [
    rollupPluginNodeResolve(),
    rollupPluginCommonjs(),
    rollupPluginInject({
      modules: {
        'win': 'window',
        'doc': 'document'
      }
    })
  ]
}
```

Hope you find this helpful, I'm also using rollup for a browser-only code :)

**Comment by David-Else** [comment]
@mxcoder Thanks! After much struggling I abandoned using jsdom and node and instead found out how to use the browser for unit tests in Mocha. I export the Rollup bundle as ES format and load it into the browser in a separate HTML file. This article explains it : https://www.sitepoint.com/unit-test-javascript-mocha-chai/

I have book marked your post and will come back to it in the future I am sure, I just can't face any more fighting Node's legacy module format... please let it go away forever :)

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
