### ISSUE TITLE
Sourcemaps in DevTools

### ISSUE THREAD

**Issue by frandiox** [rollup/rollup#1685]
Hi! First of all, thanks for all the job done here, rollup is a wonderful tool :)

I'm experiencing some issues in Chrome DevTools related to the sourcemaps generated by rollup. I've made a small [reproduction with instructions here](https://frandiox.github.io/rollup-sourcemaps-issue/). The source code is [here](https://github.com/frandiox/rollup-sourcemaps-issue).

As mentioned in that example, I think the sourcemaps are somehow not pointing to the beginning of the line as they should. As a result, lines run before the code is paused by breakpoints and the debugger gets buggy sometimes when setting and unsetting multiple breakpoints.

There is much more information about this issue here: https://github.com/OnsenUI/OnsenUI/issues/1958
That is our open source project where you can also see the same issue in [bundle-size branch](https://github.com/OnsenUI/OnsenUI/tree/bundle-size) (`yarn install && yarn run dev`).

Related: https://github.com/rollup/rollup/issues/1370 , https://github.com/webpack/webpack/issues/2145#issuecomment-294361203

Thanks!

**Comment by lzqyydy** [comment]
I came across this issue a lot. The sourcemap in Chrome always shift one line and it's hard to place a break at some position and removing breakpoint could make devtool very buggy.

Anyone has idea? Is this a bug?

**Comment by frandiox** [comment]
@lzqyydy Yes, the example I provided is only using `rollup-plugin-babel`, nothing else. Unfortunately, I cannot use Buble because I think it does not support rest properties yet.

**Comment by kzc** [comment]
https://github.com/Rich-Harris/buble/commit/97b79213a77beccb55d606df6bf39972ec1d7f67

**Comment by frandiox** [comment]
@kzc Wow, released yesterday, thanks a lot for the info! I'll give it a try :)

**Comment by kzc** [comment]
That's unfortunate. Maybe you could hack in support. ;-)

https://gitlab.com/Rich-Harris/buble/issues/137

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
