### ISSUE TITLE
Add option so that watch doesn't eat the console output on every change

### ISSUE THREAD

**Issue by tcoopman** [rollup/rollup#1687]
#1491 introduced that in watch mode, rollup eats the terminal output. I'm running rollup in combination with other processes with npm-run-all and I would like that all the output remains on the screen because now I'm often missing errors/warnings because they have been removed by rollup.

A flag to turn this of would be great.

**Comment by feross** [comment]
I too have run into this issue. I run rollup with several other watch commands, like this:

```bash
npm run watch-css & npm run watch-js & npm run watch-server
```

This is also related to https://github.com/rollup/rollup/issues/1557

**Comment by feross** [comment]
Just noticed several comments from other users sharing similar feedback starting from this comment: https://github.com/rollup/rollup/pull/1491#issuecomment-322285075
