### ISSUE TITLE
Changed in 0.48: onwrite bundle does not contain modules

### ISSUE THREAD

**Issue by ondras** [rollup/rollup#1689]
My rollup plugin uses the `onwrite` listener to visualize dependencies:

```js
onwrite(data) {
  let ids = data.bundle.modules.map(m => m.id);
}
```

This is no longer working as of 0.48:
```
[!] TypeError: Cannot read property 'map' of undefined
```

Turns out that the `data.bundle` contains only `code` and `map`. Why? :-)

**Comment by cptroot** [comment]
Any chance we can get a clarification here?

**Comment by guybedford** [comment]
It is advisable to use the `generateBundle` hook to get dependency graph information at this point.
