### ISSUE TITLE
Ability to use a custom parser

### ISSUE THREAD

**Issue by iamale** [rollup/rollup#1690]
First of all, thanks for such an amazing tool! It's really amazing and easy to use, so I'm using it instead of Webpack in practically every my project now.

I've ran across a problem though: sometimes I'm using features not yet supported by Acorn, i. e. Object rest spread:

```js
const { foo, ...rest } = {foo: 4, bar: 42, baz: 420};
```

Babylon / Babel parses it [just fine][repl-babel], but acorn fails and [so does Rollup][repl-rollup]. I'm already using Babel to transpile my code (via rollup-plugin-babel), so it should make sense to use the same Babylon parser for Rollup as well?

[repl-babel]: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBA2sANgQwhAphANDA3jZHAcxwDpyAnTWAXwF0YBeGAIwFcBLRAEwGEU0mABQAibhRAAHbiADuYAPoKOUdAFsIInHDo5JEyRACUAbiA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=stage-2&targets=&version=6.26.0

[repl-rollup]: https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwJTdCLi4ucmVzdCU3RCUyMCUzRCUyMCU3QmZvbyUzQSUyMDUlN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by kzc** [comment]
Related issue: #1512 

It's not just Rollup itself. For a comprehensive parser solution all of the rollup plugins and [Bublé](https://github.com/Rich-Harris/buble) would require a similar change. Basically a shim package is needed to mimic the Acorn API which all the aforementioned tools would make use of instead of Acorn directly, and parser plugins could be registered with it at runtime.

**Comment by lukastaegert** [comment]
This is already resolved in the latest rollup version with the ability to use custom acorn plugins.

**Comment by olstenlarck** [comment]
@lukastaegert that's great, yea. But still, Acorn does not have plugin for Flow for example.

**Comment by adrianheine** [comment]
How about just writing a flow plugin for acorn?

**Comment by olstenlarck** [comment]
The whole thing is to just finish the https://github.com/babel/babel/issues/7369 which code will come from [babel-eslint](https://github.com/babel/babel-eslint/tree/master/lib/babylon-to-espree) source.

So then you surely will be able to switch to pure Babylon with `plugins: ['espree']` forced by default.
