### ISSUE TITLE
Rollup unable to tree-shake classes

### ISSUE THREAD

**Issue by scripter-co** [rollup/rollup#1691]
When using React, for example, and defining [defaultProps](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) will not allow rollup to tree-shake the class from the outputted bundle.

[The rollup/repl can be found here.](https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEluY2x1ZGVNZSUyMCU3RCUyMGZyb20lMjAnLiUyRm1hdGhzLmpzJyUzQiU1Q24lNUNuSW5jbHVkZU1lKCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY2xhc3MlMjBBblVudXNlZENsYXNzJTIwJTdCJTVDbiU3RCU1Q24lNUNuQW5VbnVzZWRDbGFzcy5kZWZhdWx0UHJvcHMlMjAlM0QlMjAlN0IlN0QlNUNuJTVDbmZ1bmN0aW9uJTIwSW5jbHVkZU1lKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdibGEnKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMEFuVW51c2VkQ2xhc3MlMjAlN0QlM0IlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMEluY2x1ZGVNZSUyMCU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**main.js**

```
import { IncludeMe } from './maths.js';

IncludeMe();
```

**maths.js**

```
class AnUnusedClass {
}

AnUnusedClass.defaultProps = {}

function IncludeMe() {
	console.log('bla');
}

export { AnUnusedClass };

export { IncludeMe }
```

**output:**

```
(function () {
'use strict';

class AnUnusedClass {
}

AnUnusedClass.defaultProps = {};

function IncludeMe() {
	console.log('bla');
}

IncludeMe();

}());
```

**Comment by lukastaegert** [comment]
This will be fixed once #1667 is merged.

**Comment by scripter-co** [comment]
I can confirm that your PR does indeed resolve this issue. In my current use case though, it's not correctly tree-shaking the class as we have externals defined, so it looks something like:

```
class Something extends Component {
}
```

The iife is called with `Component` so you end up with a bundle that looks something like

```
function(Component){

  var Something = (function (Component$$1) {
  	function Something () {
  		Component$$1.apply(this, arguments);
  	}if ( Component$$1 ) Something.__proto__ = Component$$1;
  	Something.prototype = Object.create( Component$$1 && Component$$1.prototype );
  	Something.prototype.constructor = Something;

  	

  	return Something;
  }(Component));

}(Component)
```

I'm assuming that's because rollup doesn't know what `Component` does?

**Comment by lukastaegert** [comment]
Yes, more specifically it is the call to `Component.apply`. Currently, Rollup does not understand how to handle `.apply()` (or `.call()`) at all, so it always assumes this has side-effects. But even if it did (which I intend to improve), it would still not know what `Component` does.

Should we solve this `apply` problem eventually, then at least end users of your library how use Rollup will get proper tree-shaking when they actually bundle the external dependencies.

**Comment by scripter-co** [comment]
@lukastaegert so I've been looking into this a little more. I'm currently using version 0.41.6. In this version, if I remove the default props (exact same example being used in the above example), then the component is not included in the package. If I upgrade to. This behaviour persists up to version [0.49.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0490) - this release included:

 - Completely update the treeshaking algorithm (#1582)

So it looks like prior to 0.49.0, it was correctly handling this class tree-shaking when removing the `exampleClass.defaultProps = {}` declaration. Something seems strange about that.

**Comment by scripter-co** [comment]
@lukastaegert So it looks like it is indeed Buble that's causing the larger filesize. I've created an example repo in case you're interested here: https://github.com/scripter-co/rollup-babel-buble-treeshaking.

Anyway, I will close this issue as #1667 does indeed resolve class tree shaking.

**Comment by scripter-co** [comment]
@lukastaegert I set up a repo that highlights the difference between the two version outputs: https://github.com/scripter-co/rollup-babel-buble-treeshaking in case you wanted to take a look.

**Comment by lukastaegert** [comment]
Ok, thanks for the repo!
So I think the main problem is that Rollup does not yet fully understand Object.create (which comes from Bublé). Therefore it must assume that the return value of Object.create could for instance be a global variable. Since the return value is then mutated, this assumption forces Rollup to keep all mutations and therefore the whole class as these mutations could be observable side-effects.

Apparently, previous versions of Rollup just ignored this which lead to hard to fix bugs in other situations. Since Object.create is a standard JS feature I think we will be able to tree-shake this properly at some point again (and with more certainty) but it will take some time.

**Comment by lukastaegert** [comment]
Unfortunately, these issues have been stalled a little. Once 1.0 is finally released, there will be more progress on this.

**Comment by laurentpayot** [comment]
Don't want to be pushy, but version 1.0 is out for a while now :wink:

**Comment by laurentpayot** [comment]
@lukastaegert is this the same as #2759 ?

**Comment by lukastaegert** [comment]
Not really with regard to `Object.create`.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
