### ISSUE TITLE
Rollup empties inner function 

### ISSUE THREAD

**Issue by jrsanchezalcala** [rollup/rollup#1692]
This is the code to rollup.

```
"use strict";

var PlayerComponent = /** @class */ (function () {
    function PlayerComponent(rest, router, usuarioS, t, gl, alert, device) {
     
    }

    PlayerComponent.prototype.downloadFromAndroid = function () {
        var percentD = this.percentDownload;
        var progressfunc = function (result) {
            var percent = result.loaded / result.total * 100;
            percent = Math.round(percent);
            percentD = percent;
        };
        return this.device.download(this.fichero, this.podcast.id.toString() + "." + this.podcast.extension, function (result) {
            var percent = result.loaded / result.total * 100;
            percent = Math.round(percent);
            percentD = percent;
        });
    };
 
}());
exports.PlayerComponent = PlayerComponent;
```

And this is the result

```
`"use strict";

var PlayerComponent = /** @class */ (function () {
    function PlayerComponent(rest, router, usuarioS, t, gl, alert, device) {
     
    }

    PlayerComponent.prototype.downloadFromAndroid = function () {
        return this.device.download(this.fichero, this.podcast.id.toString() + "." + this.podcast.extension, function (result) {
            
        });
    };
 
}());
exports.PlayerComponent = PlayerComponent;
`
```
As you can see function on var progressfunc is not display and the function wich is in the last parameter is an empty function.

Why is this happening ? 

The only way to avoid this is writing this code in this way.

```
"use strict";

var PlayerComponent = /** @class */ (function () {
    function PlayerComponent(rest, router, usuarioS, t, gl, alert, device) {
     
    }

	 PlayerComponent.prototype.progressfunc = function (result) {
            var percent = result.loaded / result.total * 100;
            percent = Math.round(percent);
            percentD = percent;
        };
	
    PlayerComponent.prototype.downloadFromAndroid = function () {
        var percentD = this.percentDownload;
        
        return this.device.download(this.fichero, this.podcast.id.toString() + "." + this.podcast.extension, PlayerComponent.prototype.progressfunc);
    };
 
}());
exports.PlayerComponent = PlayerComponent;
```

**Comment by lukastaegert** [comment]
Hi @jrsanchezalcala,

I have looked at your code and I think rollup behaves correctly here. This is what I found:
1. `progressFunc` is defined but not actually called by your code. Therefore, rollup is correct in removing it as dead code.
2. Similarly, `percentD` is only assigned values but never actually read. Assignments to a variable which is not read are again correctly considered to be dead code.
3. The outer variable `PlayerComponent` is actually `undefined` as you do not return any value from your IIFE. In Rollup 0.50.0, this does not actually change the result a lot, but in the next version it will quite probably be removed nearly completely as it basically does not have any observable effect. This is what I think your example should look like (Using ES6 exports which you should use as well if there is nothing preventing you from doing so. I assume you are using rollup-plugin-commonjs?): [REPL-Link](https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMFBsYXllckNvbXBvbmVudCUyMCUzRCUyMChmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGZ1bmN0aW9uJTIwUGxheWVyQ29tcG9uZW50KHJlc3QlMkMlMjByb3V0ZXIlMkMlMjB1c3VhcmlvUyUyQyUyMHQlMkMlMjBnbCUyQyUyMGFsZXJ0JTJDJTIwZGV2aWNlKSUyMCU3QiU3RCU1Q24lNUNuJTIwJTIwJTIwJTIwUGxheWVyQ29tcG9uZW50LnByb3RvdHlwZS5kb3dubG9hZEZyb21BbmRyb2lkJTIwJTNEJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBwZXJjZW50RCUyMCUzRCUyMHRoaXMucGVyY2VudERvd25sb2FkJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHRoaXMuZGV2aWNlLmRvd25sb2FkKHRoaXMuZmljaGVybyUyQyUyMHRoaXMucG9kY2FzdC5pZC50b1N0cmluZygpJTIwJTJCJTIwJTVDJTIyLiU1QyUyMiUyMCUyQiUyMHRoaXMucG9kY2FzdC5leHRlbnNpb24lMkMlMjBmdW5jdGlvbiUyMChyZXN1bHQpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMHBlcmNlbnQlMjAlM0QlMjByZXN1bHQubG9hZGVkJTIwJTJGJTIwcmVzdWx0LnRvdGFsJTIwKiUyMDEwMCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBwZXJjZW50JTIwJTNEJTIwTWF0aC5yb3VuZChwZXJjZW50KSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBwZXJjZW50RCUyMCUzRCUyMHBlcmNlbnQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwUGxheWVyQ29tcG9uZW50JTNCJTVDbiU3RCgpKSUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCUGxheWVyQ29tcG9uZW50JTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
3. Lastly, the callback you pass to `this.device.download()` is emptied completely as calling it does not have any observable side-effects. The only external effect is modifying the variable `percentD` which is only written to but never actually read, see above.

**Comment by lukastaegert** [comment]
I will close this now, feel free to reopen it if you think rollup needs to behave differently because this behaviour breaks functionality for you.
