### ISSUE TITLE
Rollup favors "main" property in package

### ISSUE THREAD

**Issue by jagi** [rollup/rollup#1694]
Hi, here is a [reproduction](https://github.com/jagi/rollup-reproduction) of the problem.

I add a [package](https://github.com/jagi/rollup-reproduction/tree/master/node_modules/some-test-package) to my project that has both ES and CJS version of the code to support more module formats. In the [package.json](https://github.com/jagi/rollup-reproduction/blob/master/node_modules/some-test-package/package.json) file of this package I have main files defined as follow:

```json
{
  "name": "some-test-package",
  "version": "1.0.0",
  "jsnext:main": "es.js",
  "module": "es.js",
  "main": "cjs.js"
}
```

Documentation says:

> To make sure your ES6 modules are immediately usable by tools that work with CommonJS such as Node.js and webpack, you can use Rollup to compile to UMD or CommonJS format, and then point to that compiled version with the main property in your package.json file. If your package.json file also has a module field, ES6-aware tools like Rollup and webpack 2 will import the ES6 module version directly.

Now I bundle my app using `npm run build` and run the bundle using `npm run start`. And the method call in the bundle comes from the CJS version of package. Rollup also didn't do any tree-shaking for this package. Am I missing something? On the other had it worked well with local modules but not so well with modules coming from the `node_packages` directory.

I'm new to Rollup. I just want to create an NPM package that will take advantage of ES modules but also support CJS so that it can be used with for example Meteor.js. I've heard that Rollup is a great tool and I would like to support it too but I can't make it use code with ES modules and to do tree-shaking.

**Comment by TrySound** [comment]
To resolve node modules you should use [plugin](https://github.com/rollup/rollup-plugin-node-resolve).

**Comment by jagi** [comment]
@TrySound ah I see, thanks! I think you should fix documentation because an example provided on the first page suggests that it works out of the box:

```js
// import the ajax function with an ES6 import statement
import { ajax } from 'utils';
var query = 'Rollup';
// call the ajax function
ajax( 'https://api.example.com?search=' + query ).then( handleResponse );
```

It looks like this code is importing some npm module called `utils`. I would change that to: `import { ajax } from './utils';`

**Comment by TrySound** [comment]
@jagi PR welcome

**Comment by jagi** [comment]
PR created https://github.com/rollup/rollupjs.org/pull/92
