### ISSUE TITLE
Duplicate export for enums error

### ISSUE THREAD

**Issue by artonio** [rollup/rollup#1699]
Hi, I have the following format for enums in my code:

```
export enum UserRolesEnum {
    ADMIN,
    OTHER
}
```

```
export namespace UserRolesEnum {
    export function toString(v: UserRolesEnum): string {
		return UserRolesEnum[v];
    }

    export function stringToEnum(input: string): UserRolesEnum {
		let enumString: UserRolesEnum = UserRolesEnum[input];
		return enumString;
    }
}
```

> I'm getting the following error:
> Error: Duplicate export 'UserRolesEnum'
>     at error (...node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:185:14)
>     at Module.error (...node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:8170:3)
>     at tryParse (...node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:7888:10)
>     at new Module (...node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:7924:15)
>     at load.catch.then.then.then.source (...node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:9749:20)
>     at process._tickCallback (internal/process/next_tick.js:109:7)

Is there a way to fix this without renaming my enums and namespaces?

**Comment by lukastaegert** [comment]
Hi @artonio,
it is difficult to help you here without a little more information. Since you are obviously not writing JavaScript code and Rollup is solely a JavaScript bundler, you are surely using some plugins. Without being able to check this further it looks to me like this is quite possibly issue in the plugin that translates your namespace exports to JavaScript exports and you should probably file the issue there first (and have a higher chance of receiving a helpful answer).

**Comment by artonio** [comment]
Thanks, @lukastaegert 

I am using the following library: https://github.com/jvandemo/generator-angular2-library which uses _rollup.js_ to generate JavaScript from Typescript code. I have also submitted an issue at the above mentioned repo. I have also tried other library generators that use rollup, all produce the same error.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
