### ISSUE TITLE
Build takes about 2-3 minutes

### ISSUE THREAD

**Issue by Durisvk** [rollup/rollup#1700]
Rollup version: "^0.50.0"
OS: macOS Sierra 10.12.3

I was using Rollup on my previous project on this (the same as I have now) computer and with almost the same configuration.  Back then the build used to take about **1-2 seconds**.

Now on my new project the build takes on my computer **2-3 minutes**. On my friends Windows 10 it takes **25-60 seconds** (and I am not talking about the initial build, it does the same every build).

Is it possible to somehow build it faster? Because right now it's **unusable**...

Here is my `rollup.config.js`:

```javascript
import alias from 'rollup-plugin-alias';
import vue from 'rollup-plugin-vue2';
import buble from 'rollup-plugin-buble';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';

const plugins = [
  alias({
    'vue': './../node_modules/vue/dist/vue.min.js',
  }),
  vue(),
  buble({ exclude: 'node_modules/**' }),
  nodeResolve({ browser: true, jsnext: true }),
  commonjs(),
];

if (process.env.NODE_ENV === 'production') {
  plugins.push(uglify());
}

if (process.env.NODE_ENV === 'development') {
}

export default {
  input: 'src/main.js',
  sourcemap: true,
  plugins,
  output: {
    file: 'dist/app.min.js',
    format: 'iife'
  }
};
```

And the file it generates looks like this (it's not even that big as the file in my last project):
https://pastebin.com/pDELSAZR

(btw it's just a beginning of the project, so it's totally incomplete and small)

**Comment by lukastaegert** [comment]
Hi @Durisvk, that sounds really bad.

Ideally if that is not a problem for you, if you could provide a repo with your source files (or a at least a zip file), we could do some profiling as to which part of rollup makes it slow for you.

For a quick check, does adding `treeshake: false` to your rollup configuration yield any noticeable performance improvement? How about `souercemap: false`?

**Comment by Durisvk** [comment]
Hi @lukastaegert,

As I was thinking about that problem and applying logic to what's happening, I came up with an idea. I don't know if it's right, but let me propose it. The project I was working on was using elder version of rollup (it was half a year ago). How did I notice that it was elder version? I was running `rollup -c` and no warnings was shown. As I configured this new project the same way I had configured the old project, it shown the warnings like: `Don't use "entry" use "input" instead`, the same was for `"dest"` => `"output"` and so on. So I deduced that it has to be a newer rollup than I used before. So maybe one of the solution would be to go back to the version I had in that elder project. But that's just an idea...

So I tried your suggestion and came up with this output:

with this config:

```javascript
export default {
  input: 'src/main.js',
  sourcemap: true,
  treeshake: false,
  plugins,
  output: {
    file: 'dist/app.min.js',
    format: 'iife'
  }
};
```
it takes: 2m 4.4s (which is terrible)

and with this:

```javascript
export default {
  input: 'src/main.js',
  sourcemap: false,
  treeshake: false,
  plugins,
  output: {
    file: 'dist/app.min.js',
    format: 'iife'
  }
};
```

it takes: 3.3s (which is great!)

so to try the last combination of those two options you've recommended:

```javascript
export default {
  input: 'src/main.js',
  sourcemap: false,
  treeshake: true,
  plugins,
  output: {
    file: 'dist/app.min.js',
    format: 'iife'
  }
};
```

it takes: 3.4s (which is great!)

So it seems like sourcemap is the problematic (bottleneck) part.

Do I understand correctly, that sourcemap makes the debugging easier, so that in browser console I don't get error like `There's an error in app.min.js:5031`, but I get the error which points directly to the file it was compiled from, like `There's an error in ajax.js:32` or `There's an error in Login.vue:53`? Because that would be useful in the process of development and I wouldn't like to give up this feature.

I also attach the .zip file because we are using a private repo which I can't share. The .zip file doesn't contain `node_modules`, so the `npm install` should be run.

[client.zip](https://github.com/rollup/rollup/files/1450449/client.zip)

Thank you in advance for help.

**Comment by lukastaegert** [comment]
Thanks for checking, @Durisvk , this was really helpful! I was actually considering to postpone releasing the updated tree-shaking algorithm in light of this issue.

So it seems this is probably the same issue as #1553. We will need to look into this further but it will probably take some time.

**Comment by w8r** [comment]
I totally can confirm this one. Even worse, in my case with quite a big external minified library included, it just loads up CPU to 100% and never builds anything.

**Comment by w8r** [comment]
Without sourcemaps the build time is reasonable
