### ISSUE TITLE
Rollup 0.50.1 breaks imports when babel transform decorators is used

### ISSUE THREAD

**Issue by jharris4** [rollup/rollup#1703]
I just upgraded to rollup 0.51.0 from 0.50.0 and started getting errors that `PureComponent is not defined` whereas everything was fine previously.

The code base I'm working on is rather large so it took me a while, but I managed to repro by adding babel plugins one by one, and eventually I traced the issue to our use of 'decorators' and more specifically the https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy plugin.

The repro repository is here:
https://github.com/jharris4/rollup-0-51-0-bug

You can see in `/dist/output.js` that `PureComponent` should be `react.PureComponent` (and it is if you revert back to rollup 0.50.0).

Let me know if there's anything else I can do to help track down or test a fix.

**Comment by lukastaegert** [comment]
Hi @jharris4 ,
thanks for filing this issue, I think your repo will be very useful! I'll take a look tomorrow. Until then, please stick with 0.50.1.

**Comment by lukastaegert** [comment]
Ok, no immediate conclusions yet but it seems this was already broken by some changes from 0.49 to 0.50.0. Can you confirm this?

It will take some more time digging deeper into this as I fear this has to do with code I am not as familiar with yet and I want to look at a few other issues first. In the meantime, if you have some idea/suspicion which changes in 0.50.0 might be responsible for this, this could be really useful in understanding this better.

**Comment by jharris4** [comment]
@lukastaegert I just checked and this is broken in 0.50.1 but works fine in 0.50.0, so I've updated the title accordingly.

**Comment by jharris4** [comment]
I suspect that https://github.com/rollup/rollup/commit/8365bb1a1ddcf63ea564fb2b25d897a155ac9d72 might be the cause of this being broken...

This might also be the same bug that was reported in #1708

**Comment by lukastaegert** [comment]
Thanks. I see, I really need to look at this more closely. Another thing to check (I'll not have time before tomorrow to investigate further): If you add `treeshaking: false` to your rollup options, does this help in any way?

**Comment by jharris4** [comment]
I added `treeshake: false` to the rollup config and it does fix the issue.

**Comment by lukastaegert** [comment]
Ok, it seems I really messed something up here 😳 Thanks for checking!

**Comment by jharris4** [comment]
No worries, it happens! We appreciate your hard work on rollup :-)

I'll have some more time as of Tuesday of next week if there's anything I can do to help.

**Comment by lukastaegert** [comment]
Just checked your repo, `0.51.3` seems to fix your issue but please check again yourself. Thanks again for your contribution! Closing this now.

**Comment by jharris4** [comment]
Awesome! Just checked `0.51.3` against my large code base, and can confirm that rollup is now working there as well.

Thanks for the quick turnaround on this!
