### ISSUE TITLE
Invalid keyPath

### ISSUE THREAD

**Issue by HitomiTenshi** [rollup/rollup#1706]
Thanks for fixing #1702, but now I get a different error when I use the new version `0.51.1`:

```
app/main-aot.js → dist-app/app.bundle.js...

Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\pie-chart\index.js re-exports 'PieChartComponent' from both node_modules\@swimlane\ngx-charts\release\pie-chart\pie-chart.module.js and node_modules\@swimlane\ngx-charts\release\pie-chart\pie-chart.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\pie-chart\index.js re-exports 'PieArcComponent' from both node_modules\@swimlane\ngx-charts\release\pie-chart\pie-chart.module.js and node_modules\@swimlane\ngx-charts\release\pie-chart\pie-arc.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\pie-chart\index.js re-exports 'PieGridComponent' from both node_modules\@swimlane\ngx-charts\release\pie-chart\pie-chart.module.js and node_modules\@swimlane\ngx-charts\release\pie-chart\pie-grid.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\pie-chart\index.js re-exports 'PieSeriesComponent' from both node_modules\@swimlane\ngx-charts\release\pie-chart\pie-chart.module.js and node_modules\@swimlane\ngx-charts\release\pie-chart\pie-series.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\pie-chart\index.js re-exports 'PieLabelComponent' from both node_modules\@swimlane\ngx-charts\release\pie-chart\pie-chart.module.js and node_modules\@swimlane\ngx-charts\release\pie-chart\pie-label.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\pie-chart\index.js re-exports 'PieSeriesComponent' from both node_modules\@swimlane\ngx-charts\release\pie-chart\pie-chart.module.js and node_modules\@swimlane\ngx-charts\release\pie-chart\pie-series.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\line-chart\index.js re-exports 'LineChartComponent' from both node_modules\@swimlane\ngx-charts\release\line-chart\line-chart.module.js and node_modules\@swimlane\ngx-charts\release\line-chart\line-chart.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\line-chart\index.js re-exports 'LineComponent' from both node_modules\@swimlane\ngx-charts\release\line-chart\line-chart.module.js and node_modules\@swimlane\ngx-charts\release\line-chart\line.component.js (will be ignored)
Conflicting namespaces: node_modules\@swimlane\ngx-charts\release\line-chart\index.js re-exports 'LineSeriesComponent' from both node_modules\@swimlane\ngx-charts\release\line-chart\line-chart.module.js and node_modules\@swimlane\ngx-charts\release\line-chart\line-series.component.js (will be ignored)

[!] Error: invalid keyPath
Error: invalid keyPath
    at invariant (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:6585:27)
    at updateInDeepMap (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:7689:5)
    at updateInDeepMap (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:7695:23)
    at Map.updateIn (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:6993:26)
    at Map.setIn (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:6971:19)
    at ExecutionPathOptions.setIn (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:10742:51)
    at ExecutionPathOptions.setIgnoreLabel (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:10935:15)
    at Node.hasEffects (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:12827:6)
    at body.some.child (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\rollup\dist\rollup.js:11830:41)
    at Array.some (<anonymous>)
```

**Comment by lukastaegert** [comment]
Thanks, I'll look into it tomorrow!

**Comment by lukastaegert** [comment]
Should be fixed now. You got quite a knack for stumbling upon obscure issues. Please have a go with 0.51.2 and see what you find next 😜

**Comment by HitomiTenshi** [comment]
@lukastaegert Well now it doesn't crash anymore. Although it seems to remove used code now, since my app doesn't start up anymore and throws `ERROR ReferenceError: i0 is not defined`.

I can't really say what it removed, since I rollup the AOT output of my Angular 4 app and I also can't provide a test repo 😞

I guess I'll keep sticking to version `0.48.2` since this is the one that performs the best and produces the smallest bundle size. `0.51.2` is the first version to produce smaller bundle sizes than `0.48.2` (at least on my project) but it seems to have removed used code and some google closure annotations, since google closure seems to perform worse with the new output.

**Comment by lukastaegert** [comment]
If you use google closure anyways which is doing very good dead code elimination on its own, maybe treeshake: false might be an option? On the other hand, there are some other issues that I plan to iron out in the next days, maybe yours is among them.

**Comment by lukastaegert** [comment]
@HitomiTenshi  does `rollup@0.51.3` by chance fix your reference error?

**Comment by HitomiTenshi** [comment]
@lukastaegert Yes it works now! No more reference errors. If I minify the bundle with google closure though it still is bigger than a bundle made with version `0.48.2`. The new treeshaking seems to remove closure annotations generated by the angular 4 compiler.

I'll try the `treeshake: false` option and see if that gives better results. Issues resolved, thanks! 👍

**Comment by HitomiTenshi** [comment]
@lukastaegert Ok I tested `treeshake: false` on both `0.48.2` and `0.51.3` and it just creates bigger minified bundles. I guess I'll keep sticking to `0.48.2` until I get smaller minified bundles with any future version 😄

**Comment by lukastaegert** [comment]
It would be interesting to know if it is actually removed GCC annotations. If so, what do these annotations look like? Rollup actually goes to great lengths to preserve comments around statements so that these things are not impacted.

Another thing that can increase bundle size is the new "unknown potential getter" side effect detection logic. I plan on releasing some flag to control this logic once more pressing issues have been resolved. The relevant issue to watch here is #1705.

**Comment by HitomiTenshi** [comment]
@lukastaegert I went through the `0.48.2` and `0.51.5` generated bundle and I must say I was wrong, I assumed GCC annotations were removed but that is not the case.

It's still strange why the `0.51.5` minified bundle is bigger than the `0.48.2` minified bundle, even though the non-minified `0.51.5` bundle is smaller than the `0.48.2` non-minified bundle.

![explorer_2017-11-13_09-56-07](https://user-images.githubusercontent.com/7304212/32717154-e5d1e88c-c858-11e7-9f05-14b83a941be9.png)

**Comment by lukastaegert** [comment]
It is but I plan on adding some flags to fine-tune some parts of the algorithm so stay tuned. Might take 1-2 weeks, though.

**Comment by HitomiTenshi** [comment]
@lukastaegert No pressure. I'll continue to use `0.48.2`. 😄
