### ISSUE TITLE
Import namespace is not removed in generated bundle

### ISSUE THREAD

**Issue by rolandjitsu** [rollup/rollup#1715]
After upgrading to `0.50.1` I've noticed that Rollup incorrectly replaces imports in some of the fns. I've created a small [repl](https://rollupjs.org/repl?version=0.51.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZpbmRleCclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyaW5kZXguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwYXBwcGx5SW50ZXJjZXB0b3JzJTdEJTIwZnJvbSUyMCcuJTJGZGVjb3JhdG9ycyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGVjb3JhdG9ycy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAqJTIwYXMlMjB0c2xpYl8xJTIwZnJvbSUyMCU1QyUyMnRzbGliJTVDJTIyJTNCJTVDbiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBhcHBwbHlJbnRlcmNlcHRvcnMoaW50ZXJjZXB0b3JzJTJDJTIwcmVxdWVzdCUyQyUyMGN0eCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwdHNsaWJfMS5fX2F3YWl0ZXIodGhpcyUyQyUyMHZvaWQlMjAwJTJDJTIwdm9pZCUyMDAlMkMlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMGludGVyY2VwdG9yc18xJTJDJTIwaW50ZXJjZXB0b3JzXzFfMSUyQyUyMGludGVyY2VwdG9yJTJDJTIwcmVzdWx0JTJDJTIwZV8yXzElMkMlMjBlXzIlMkMlMjBfYSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjB0c2xpYl8xLl9fZ2VuZXJhdG9yKHRoaXMlMkMlMjBmdW5jdGlvbiUyMChfYiklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwc3dpdGNoJTIwKF9iLmxhYmVsKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjYXNlJTIwMCUzQSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCghQXJyYXkuaXNBcnJheShpbnRlcmNlcHRvcnMpKSUyMHJldHVybiUyMCU1QjMlMjAlMkYqYnJlYWsqJTJGJTJDJTIwOSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBfYi5sYWJlbCUyMCUzRCUyMDElM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDElM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwX2IudHJ5cy5wdXNoKCU1QjElMkMlMjA3JTJDJTIwOCUyQyUyMDklNUQpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGludGVyY2VwdG9yc18xJTIwJTNEJTIwdHNsaWJfMS5fX3ZhbHVlcyhpbnRlcmNlcHRvcnMpJTJDJTIwaW50ZXJjZXB0b3JzXzFfMSUyMCUzRCUyMGludGVyY2VwdG9yc18xLm5leHQoKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBfYi5sYWJlbCUyMCUzRCUyMDIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDIlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoISFpbnRlcmNlcHRvcnNfMV8xLmRvbmUpJTIwcmV0dXJuJTIwJTVCMyUyMCUyRipicmVhayolMkYlMkMlMjA2JTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGludGVyY2VwdG9yJTIwJTNEJTIwaW50ZXJjZXB0b3JzXzFfMS52YWx1ZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXN1bHQlMjAlM0QlMjBpbnRlcmNlcHRvcihyZXF1ZXN0JTJDJTIwY3R4KSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCghKHJlc3VsdCUyMGluc3RhbmNlb2YlMjBQcm9taXNlKSklMjByZXR1cm4lMjAlNUIzJTIwJTJGKmJyZWFrKiUyRiUyQyUyMDQlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVCNCUyMCUyRip5aWVsZColMkYlMkMlMjByZXN1bHQlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDMlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmVxdWVzdCUyMCUzRCUyMF9iLnNlbnQoKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUIzJTIwJTJGKmJyZWFrKiUyRiUyQyUyMDUlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmVxdWVzdCUyMCUzRCUyMHJlc3VsdCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBfYi5sYWJlbCUyMCUzRCUyMDUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDUlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaW50ZXJjZXB0b3JzXzFfMSUyMCUzRCUyMGludGVyY2VwdG9yc18xLm5leHQoKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUIzJTIwJTJGKmJyZWFrKiUyRiUyQyUyMDIlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDYlM0ElMjByZXR1cm4lMjAlNUIzJTIwJTJGKmJyZWFrKiUyRiUyQyUyMDklNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDclM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZV8yXzElMjAlM0QlMjBfYi5zZW50KCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZV8yJTIwJTNEJTIwJTdCJTIwZXJyb3IlM0ElMjBlXzJfMSUyMCU3RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUIzJTIwJTJGKmJyZWFrKiUyRiUyQyUyMDklNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDglM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdHJ5JTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGludGVyY2VwdG9yc18xXzElMjAlMjYlMjYlMjAhaW50ZXJjZXB0b3JzXzFfMS5kb25lJTIwJTI2JTI2JTIwKF9hJTIwJTNEJTIwaW50ZXJjZXB0b3JzXzEucmV0dXJuKSklMjBfYS5jYWxsKGludGVyY2VwdG9yc18xKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZmluYWxseSUyMCU3QiUyMGlmJTIwKGVfMiklMjB0aHJvdyUyMGVfMi5lcnJvciUzQiUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUI3JTIwJTJGKmVuZGZpbmFsbHkqJTJGJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNhc2UlMjA5JTNBJTIwcmV0dXJuJTIwJTVCMiUyMCUyRipyZXR1cm4qJTJGJTJDJTIwcmVxdWVzdCU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) to illustrate the issue.

Please see `__values` import. Instead of using it, it uses `tslib_1.__values` as in the original file.

**Comment by lukastaegert** [comment]
Please have another look but I think this is now fixed by `0.51.3`. Closing this for now.

**Comment by lukastaegert** [comment]
And thanks for the REPL link, those are always really useful!

**Comment by rolandjitsu** [comment]
Seems to work fine, thanks.
