### ISSUE TITLE
Considering plugin transform parallelization

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#1718]
One of the ways I was thinking of improving performance would be to have plugins run their `transform` hook in parallel workers, passing their results to Rollup through IPC (this would be string source only I expect, not asts).

One naive way to implement this might be to have plugins provide a flag export `"parallelTransform: true"` which informs Rollup that the transform method will be safe to run on a separate thread without needing shared state from other hooks.

We could then have a pool workers that run against the sources to maximise CPU usage. While this wouldn't solve the optimization bottleneck, it would get us there faster at least during the transform phase.

I'd be interested to hear thoughts here, as I'd be tempted to prototype something if there is interest (rather than implementing this all within my own plugin, it seems more sensible for it to be a core feature).

Otherwise happy to prototype in a plugin for consideration first.

**Comment by guybedford** [comment]
Because I need to do tree analysis anyway it makes more sense to do this in a wrapper around Rollup. Keep up the great work all!

**Comment by Globegitter** [comment]
@guybedford Has any work been done on this? Sounds like a worthy optimisation.

**Comment by guybedford** [comment]
@Globegitter there are no current plans for direct core integration currently. I'm actually currently working on an autocompiler plugin for Rollup that would offer this by default on all compilers (effectively a plugin of plugins).
