### ISSUE TITLE
Maintain this context in sequence expressions

### ISSUE THREAD

**Issue by nathancahill** [rollup/rollup#1722]
When calling a sequence as a function, the `this` context is maintained. The pattern (especially used by Babel for module functions) is:

```js
var a = (0, module.f)()  // basically f.call(this)
```

Currently in 0.51.3, this becomes:

```js
var a = (module.f)()  // basically f.call(module)
```

When the sequence is called as a function, the first items should not be discarded.

#1721 is submitted as a PR with a broken test.

**Comment by lukastaegert** [comment]
Nice one! It took me a moment to understand what is really going on here and yes you are right, we should absolutely fix this! Will take a look at your PR later today, thanks already for the work you put in.
