### ISSUE TITLE
Complete code string as input in RollupJS JavaScript API

### ISSUE THREAD

**Issue by paulocoghi** [rollup/rollup#1723]
I am using Rollup to generate bundles programmatically.

Is there a way to pass a complete source code string instead of a file name to the "input"?

**Comment by tivac** [comment]
[`rollup-plugin-memory`](https://github.com/TrySound/rollup-plugin-memory) sounds like it does what you want.

**Comment by paulocoghi** [comment]
Thanks, @tivac. That's it.

**Comment by paulocoghi** [comment]
**Update:**

[`rollup-plugin-memory`](https://github.com/TrySound/rollup-plugin-memory) was deprecated in favor of [`rollup-plugin-virtual`](https://github.com/rollup/rollup-plugin-virtual).

**Comment by PierBover** [comment]
Unfortunately `@rollup/plugin-virtual` doesn't allow to pass a string for contents of the input but rather create modules from strings to be imported from the source code.

Does anyone have a better solution?

Right now I'm creating files on a temp folder which is not ideal...

**Comment by paulocoghi** [comment]
Something like the original `rollup-plugin-memory` would be great.

**Comment by PierBover** [comment]
I figured it out.

You can actually specify string code as input with `@rollup/plugin-virtual` like this:

```
import virtual from '@rollup/plugin-virtual';

export default {
  input: 'hello',
  // ...
  plugins: [
    virtual({
      hello: `console.log("hello!");`,
    })
  ]
};
```

**Comment by paulocoghi** [comment]
Thanks for the feedback!
