### ISSUE TITLE
Unicode string property must be enclosed by [], otherwise rollup fails

### ISSUE THREAD

**Issue by borota** [rollup/rollup#1727]
"rollup": "^0.51.5",
    "rollup-plugin-buble": "^0.17.0",

```
export const map = Object.freeze(
  Object.create(null, {
    '\u0591': { value: '', enumerable: true },
    '\u0592': { value: '', enumerable: true }
  })
);
```

`rollup -c` fails with: [!] Error: Line 347: Unexpected string

this works though:
```
export const map = Object.freeze(
  Object.create(null, {
    ['\u0591']: { value: '', enumerable: true },
    ['\u0592']: { value: '', enumerable: true }
  })
);
```

Low priority issue, but still, it doesn't make any sense to have to put string property inside []. Or is this by design?

**Comment by guybedford** [comment]
Is this a problem with Rollup or the Buble plugin in particular? The main case seems to work fine in the repl.

**Comment by peshitta** [comment]
Didn't investigate but my guess is Buble.

**Comment by adrianheine** [comment]
Works fine with current bublé, could you retry with 0.19.1?

**Comment by peshitta** [comment]
"rollup-plugin-buble": "^0.18.0", issue doesn't happen anylonger, must have been fixed somewhere along the way.

**Comment by guybedford** [comment]
@peshitta thanks for the update here.
