### ISSUE TITLE
CANNOT_IMPORT_SELF with rollup+commonjs+babel

### ISSUE THREAD

**Issue by digitalkaoz** [rollup/rollup#1730]
Hey,

im getting the Error when Babel polyfills my code:

**error** 

```js
{ Error: A module cannot import itself
    at error (app/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (app/node_modules/rollup/dist/rollup.js:14293:3)
    at then.resolvedId (app/node_modules/rollup/dist/rollup.js:16054:15)
    at <anonymous>
  code: 'CANNOT_IMPORT_SELF',
  pos: 45,
  loc: 
   { file: '/app/node_modules/core-js/modules/es6.regexp.split.js',
     line: 2,
     column: 0 },
  frame: '1: import "core-js/modules/es6.regexp.replace";\n2: import "core-js/modules/es6.regexp.split";\n   ^\n3: import \'./_fix-re-wks\';\n4: import \'./_is-regexp\';' }
```

here the readable part:

```
[!] Error: A module cannot import itself
node_modules/core-js/modules/es6.regexp.split.js (2:0)
1: import "core-js/modules/es6.regexp.replace";
2: import "core-js/modules/es6.regexp.split";
   ^
3: import './_fix-re-wks';
4: import './_is-regexp';
```

**here is a simple reproducable case**:

```js
//entry.js
'a-b-c'.split(/-/);
```

```js
//.babelrc.js
module.exports = {
  plugins: ["@babel/plugin-external-helpers"],
  presets: [
    [
      "@babel/preset-env",
      {
        debug: true,
        modules: false,
        useBuiltIns: "usage",
        targets: {
          browsers: ["last 2 major versions"]
        }
      }
    ]
  ]
};
```

```js
//rollup.config.js
import uglify from "rollup-plugin-uglify";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import babel from "rollup-plugin-babel";

export default {
  input: "index.js",
  treeshake: false,
  plugins: [resolve(), commonjs(), babel(), uglify()],
  output: {
    file: "output.js",
    format: "iife",
    name: "example",
    sourcemap: true
  }
};
```

i've seen this error was raised by [angular2](https://github.com/angular/angular/issues/17389) and a few other projects, they solved it themselves (in userland code), but why is rollup complaining and not simply taking the module it already have?

**Comment by digitalkaoz** [comment]
maybe @zloirock from core-js has an idea how to fix that? is the self-import fixable in corejs?

**Comment by digitalkaoz** [comment]
if i monkeypatch the `if-condition` the bundling works again...so what is it good for?

**Comment by zloirock** [comment]
No ideas. `core-js` modules should not have circular dependencies.

**Comment by digitalkaoz** [comment]
I tried to figure out what might be the circular ref, but the corejs
structure is bit confusing to me. The same Code with es6 modules works fine
btw...

Denis Pushkarev <notifications@github.com> schrieb am Di., 14. Nov. 2017,
19:31:

**Comment by digitalkaoz** [comment]
@zloirock im a bit confused since `core-js` is CJS, but the error states that its ESM somehow (i guess its some CJS->ESM transpiling step from rollup itself)...

can we make sure there are no cyclic deps in `core-js` especially `es6.regexp.split.js`?!

maybe @Rich-Harris or @TrySound can bring in some light here?! would love to fix, tried some monkey-patching but it seems not so easy

**Comment by TrySound** [comment]
@digitalkaoz es modules error because with commonjs plugin cjs is converted to esm. Possibly bug in commonjs plugin

**Comment by digitalkaoz** [comment]
closing as duplicate of https://github.com/rollup/rollup-plugin-commonjs/issues/257
