### ISSUE TITLE
rollup  with version higher than 0.50.0 hangs while building angular app

### ISSUE THREAD

**Issue by kemsky** [rollup/rollup#1733]
Sample repo:
https://github.com/kemsky/angular-rollbar-hang

**Comment by lukastaegert** [comment]
Thanks for the repo! I am currently preparing a new PR that will hopefully resolve these kinds of problems for good but it will probably take another few days. Having your repo to test against is great (especially as my angular 5 knowledge is somewhat limited 🙄)!

**Comment by lukastaegert** [comment]
Hi @kemsky, can you please confirm this is fixed when you install rollup via
```
npm install rollup/rollup#refactor-assignment-handling
```
?

**Comment by kemsky** [comment]
Hi @lukastaegert , yes it works now, thank you.
