### ISSUE TITLE
Minimal build question

### ISSUE THREAD

**Issue by codepunkt** [rollup/rollup#1734]
Hello everyone!

I'm trying to build a library in UMD, CJS and ES format.
The library needs a `throttle` method, with was imported from `lodash` like this:

```javascript
import throttle from 'lodash/throttle'
```

Because this adds 1.3k gzipped to the bundle and the library itself is only ~1k gzipped, i thought about people that already have their own throttle, which is not necessarily the one provided by lodash (could be underscore, lodash-es, ramda or whatever).

This is why i removed the import and changed the code using throttle to this:

```javascript
export const myMethod = ({ customThrottle, ...moreOptions }) => {
  const throttle = customThrottle || require('lodash/throttle')
  // use throttle below
}
```

To be honest, i'm not too sure if what i'm thinking will work in practice. What it boils down to is that i'd like to bundle the `throttle` provided by lodash into the UMD build, whilst leaving it out in both CJS and ES.

When users of my library don't provide their own throttle, both CJS and ES should be fine with requiring the lodash one on the fly.

Is this basic assumption correct? How would i do this with rollup?

I can think of a very convoulted CLI command or three configs, possibly deriving from a base one and only changing the output format and adding the multiEntry plugin to the UMD one with lodash/throttle as an additional entrypoint.

**Comment by nathancahill** [comment]
To answer your config question, Rollup now accepts an array of config objects since #1389.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
