### ISSUE TITLE
TypeError: Cannot read property 'suggestName' of undefined

### ISSUE THREAD

**Issue by Gozala** [rollup/rollup#1735]
### 🖊 [Reproducible example](https://rollupjs.org/repl?version=0.51.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyME51bWJlciUyMGZyb20lMjAlNUMlMjIuJTJGTnVtYmVyJTVDJTIyJTVDbmV4cG9ydCUyMGNvbnN0JTIwaXNOYU4lMjAlM0QlMjBOdW1iZXIuaXNOYU4lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyTnVtYmVyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjAlNDBmbG93JTIwKiUyRiU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwaXNOYU4lMkMlMjBpc0Zpbml0ZSUyQyUyMHBhcnNlRmxvYXQlMkMlMjBOdW1iZXIlMjAlN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIydW1kJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJtYWluJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

I'm running into this issue ~~for which I don't yet have a reproducible test case as I'm not successful in isolating the cause as it seems to be more than 5 levels deep in the of import chain. I will update this issue one I'm able to isolate it but I thought I'd post this now in case there are some clues what this error message mean.~~

I run into issue when trying to create a bundle as follows:

```sh
rollup -c --verbose
loaded rollup.config.js with warnings
(!) Unused external imports
default imported from external module 'rollup-plugin-flow' but never used

./src/DOM.js → ./js/DOM.js...
[!] TypeError: Cannot read property 'suggestName' of undefined
TypeError: Cannot read property 'suggestName' of undefined
    at Node.bind (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:13021:20)
    at eachChild.child (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:11010:34)
    at keys.forEach.key (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:11027:5)
    at Array.forEach (<anonymous>)
    at Node.eachChild (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:11020:13)
    at Node.bindChildren (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:11010:8)
    at Node.bind (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:10990:8)
    at eachChild.child (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:11010:34)
    at value.forEach.child (/Users/gozala/.config/yarn/global/node_modules/rollup/dist/rollup.js:11025:38)
    at Array.forEach (<anonymous>)
```

with a following configuration:

```js
// @flow

import json from "rollup-plugin-json"
import resolve from "rollup-plugin-node-resolve"
import commonjs from "rollup-plugin-commonjs"
import babel from "rollup-plugin-babel"
import flow from "rollup-plugin-flow"
import flowSyntax from "babel-preset-flow-syntax"

const config = file => ({
  input: `./src/${file}.js`,
  output: {
    file: `./js/${file}.js`,
    format: "iife",
    // intro: "window.global = window;",
    moduleName: `${file}`,
    sourceMap: true
  },
  plugins: [
    babel({
      babelrc: false,
      presets: [flowSyntax]
    }),
    json({ preferConst: true }),
    commonjs(),
    resolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: [".js", ".json"]
    })
  ]
})
export default [config("DOM")]
```

**Comment by Gozala** [comment]
Also please note that changing code to [destruct imports](https://rollupjs.org/repl?version=0.51.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmlzTmFOJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZOdW1iZXIlNUMlMjIlNUNuZXhwb3J0JTIwJTdCaXNOYU4lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyTnVtYmVyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjAlNDBmbG93JTIwKiUyRiU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwaXNOYU4lMkMlMjBpc0Zpbml0ZSUyQyUyMHBhcnNlRmxvYXQlMkMlMjBOdW1iZXIlMjAlN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIydW1kJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJtYWluJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) seems to work fine.

**Comment by guybedford** [comment]
This should be resolved in the latest versions.
