### ISSUE TITLE
Output the same directory structure as the src

### ISSUE THREAD

**Issue by kamleshchandnani** [rollup/rollup#1736]
directory structure
```
├── /es/                  # Temp folder for compiled output
│   ├── /main.js            # The main entry point
│   ├── /a.js    # A module referenced in main.js
│    ├── /dir1
│      └── /c.js # A module referenced in main.js
│   └── /b.js    # A module referenced in main.js
├── /src/                   # ES2015+ source code
│   ├── /main.js            # The main entry point
│   ├── /a.js    # A module referenced in main.js
│   ├── /dir1
│      └── /c.js # A module referenced in main.js
│   └── /b.js    # A module referenced in main.js
└── package.json            # Project settings
```

```npm NODE_ENV=es rollup -c -o es/redux.js```

I want to get the output in es/* to be same as src/* when building for es module system. What changes I have to do? In current setup it just outputs es/main.js bundled with a,b,c.js in single file

**Comment by lukastaegert** [comment]
Rollup's sole purpose is to do just that, bundle multiple files into a single file. If you want your files to just be transpiled from ES6 to CJS modules, directly using something like [Babel](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) via [babel-cli](http://babeljs.io/docs/usage/cli/) might be a better setup.

**Comment by lukastaegert** [comment]
I closed this as I do not see an issue or feature request with rollup here but rather a support question for which a forum like [stackoverflow](https://stackoverflow.com/) might be a better place.

**Comment by adrianheine** [comment]
If you don't want to create a bundle, have a look at https://github.com/marijnh/tariff or https://github.com/standard-things/esm for example.

**Comment by JonathanILevi** [comment]
Should this be reopened?  With the code splitting being a thing now this really is relative to rollup.

**Comment by miraage** [comment]
Rollup is for libraries. Libraries do not make decisions whether code split or not.

**Comment by lukastaegert** [comment]
This is now actually resolved via https://rollupjs.org/guide/en/#preservemodules

> Libraries do not make decisions whether code split or not

I beg to differ and actually wrote an article why a library would do that: https://levelup.gitconnected.com/code-splitting-for-libraries-bundling-for-npm-with-rollup-1-0-2522c7437697

As a matter of fact, Rollup itself is currently using code-splitting to separate the CLI code from the core code and Rollup@2 will go further to also separate the watch code that way.
