### ISSUE TITLE
rollup >= 0.51.4 hangs

### ISSUE THREAD

**Issue by nicolashenry** [rollup/rollup#1737]
Rollup >= 0.51.4 hangs if this file is included : https://raw.githubusercontent.com/bestiejs/platform.js/master/platform.js

**Comment by lukastaegert** [comment]
Hi @nicolashenry, can you please confirm this is fixed when you install rollup via
```
npm install rollup/rollup#refactor-assignment-handling
```
?

**Comment by nicolashenry** [comment]
@lukastaegert It seems to be fixed with this :+1:

**Comment by lukastaegert** [comment]
Thx! Just released a new version.
