### ISSUE TITLE
Rollup watch crashes in cmd/PowerShell on windows

### ISSUE THREAD

**Issue by csvn** [rollup/rollup#1739]
Hello,

Almost every time when I run `rollup -c -w` with minimum configuration, the terminal crashes. I created a reproduction here: https://github.com/csvn/rollup-watch-error.

Windows 10
Node: v8.9.0 / v8.9.1
terminals: cmd/PowerShell
rollup: "^0.51.7"

![Terminal errors](https://raw.githubusercontent.com/csvn/rollup-watch-error/master/rollup-watch-error.gif)

**Comment by csvn** [comment]
Seems it might be something off with my work computer. I tried doing the same steps from home, but many tries later and the terminal has not crashed. I run Windows 10 at home too, and I tried with both Node v8.1.0 and node v8.9.1.

I'm kinda lost as to how I will reproduce this on another machine.

**Comment by csvn** [comment]
I tried today to uninstall and install node to see if it would help, with no success.

When looking through the code I tried some things out. Ifound that if I change the following in `node_modules/rollup/bin/rollup`, the watch command no longer crashes:

```
// const SHOW_ALTERNATE_SCREEN = '\u001B[?1049h';
// const HIDE_ALTERNATE_SCREEN = '\u001B[?1049l';
const SHOW_ALTERNATE_SCREEN = '';
const HIDE_ALTERNATE_SCREEN = '';
```

With the garbled text that sometimes came out (see gif), it might be something weird in my computer about the error stream. I don't know much about the "Alternate Screen" functionality in command lines. I can't find much related to this feature or why it might crash on windows.

I don't know if there might be more similar issues like mine, but if there is it might make sense to have a flag (e.g. `--no-alt-screen`) to disable it.

**Comment by csvn** [comment]
Just a small update: I have a co-worker with the same issue when running `rollup -w` on Windows. A couple of others run Windows but has no issues. Still haven't found a reliable way to reproduce this on other machines, sadly.

**Comment by fedesigner** [comment]
same problem ☹

**Comment by jfcha** [comment]
Same. A simple workaround in cmd that I've found is to redirect stderr, i.e.  `rollup -w 2>NUL`

**Comment by Mourdraug** [comment]
I can confirm same problem on both my windows 10 PCs, command line crashes as well. Most convinient workaround for me is to use Git bash.

**Comment by goriunov** [comment]
The same thing on my machine too

**Comment by goriunov** [comment]
For people whose problem in this: 
``
// const SHOW_ALTERNATE_SCREEN = '\u001B[?1049h';
// const HIDE_ALTERNATE_SCREEN = '\u001B[?1049l';
const SHOW_ALTERNATE_SCREEN = '';
const HIDE_ALTERNATE_SCREEN = '';
``

I have written simple npm script which automatically will replace it just install it with 

```
npm install rollup-watch-fix 
```

and add in package.json
```
"scripts": {
     "postinstall": "rollup-watch-fix"
}
```

this will automatically replace `SHOW_ALTERNATE_SCREEN` and `HIDE_ALTERNATE_SCREEN`

**Comment by pushqrdx** [comment]
same problem here too..
