### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by nickngqs** [rollup/rollup#1743]
I'm trying to import axios to work with rollup.

I'm kept getting `Uncaught ReferenceError: require is not defined`.

I've tried almost everything. Axios is using require in their code, and since I'm using it for browser, it won't work since require is node thing. But how do I make it work using rollup, is there any plugins to resolve the issue?

If not, how do I just require the minified file in rollup, like a concat without the parsing?

If i just put in a script tag of the axios minified file, it works. But I'm looking for an alternative without doing that. Any help will be appreciated.

Repo: https://github.com/nickngqs/axios-issue

You can just npm run dev (it will serve the files)

**Comment by fskreuz** [comment]
Use https://github.com/rollup/rollup-plugin-node-resolve together with https://github.com/rollup/rollup-plugin-commonjs to allow rollup to budle cjs modules.

**Comment by nickngqs** [comment]
As you see my repo, I've already used both of this plugins

**Comment by adrianheine** [comment]
This is actually not a rollup bug.

The first issue is that `rollup-plugin-node-globals` is used before `rollup-plugin-commonjs`, which injects `import` declarations into commonjs files which makes `rollup-plugin-commonjs` think they are actually ES6 modules. Just put `globals()` after `commonjs()`.

The second issue is that `axios/lib/adapters/http.js` is `require`ing `axios/package.json`, for which you need `rollup-plugin-json`.

These plugins could probably be a bit more ergonomic by either better working together or warning in bad situations, but there's no immediate bug in `rollup` at work here.

**Comment by lukastaegert** [comment]
Good job looking into this @adrianheine!

**Comment by lukastaegert** [comment]
Maybe it is more of a documentation issue?

Also, isn't requiring JSON files a core feature of node? I.e. if not done so already, maybe rollup-plugin-node-resolve should actually include/use rollup-plugin-json? Or even better, maybe we should create a meta-plugin that combines rollup-plugin-node-resolve, rollup-plugin-commonjs, rollup-plugin-json and possibly others to give you basically full node/npm compatibility in one preconfigured package? This could prevent quite a few of these configuration issues.

**Comment by adrianheine** [comment]
I think creating such a meta-package is a viable option, especially since loading JSON files is not part of the ES6 modules spec and thus will hopefully mostly be limited to dependencies.

Slightly related: We could also consider moving `addJsExtensionIfNecessary` to a plugin as well, since it is not part of the spec.

Put together, it would be nice to have a package that implements Nodejs' implementation of Commonjs, which means implementing `require` with loading from `node_modules`, supporting `.json` files and automatically adding extensions, but everything except the module resolving is only active in `node_modules/`.

**Comment by lukastaegert** [comment]
> We could also consider moving addJsExtensionIfNecessary to a plugin as well, since it is not part of the spec.

I like that. I always thought that handling extensions should be the sole responsibility of e.g. the node-resolve plugin but your idea is probably even better. Then when an extension is missing we could handle it similarly how it is done for imports that cannot be found: Display a warning that this is happening and we are assuming the extension to be .js and they should either add an extension or use plugin xy.

Also in the meta-plugin, we could do things like only run *.js files through the CJS plugin while using *.mjs files directly and other node subtleties and finally close #1364 .

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
