### ISSUE TITLE
[0.51.x] output unused argument property alias-vars.

### ISSUE THREAD

**Issue by UncleBill** [rollup/rollup#1744]
# source
```js
export default function (ref) {
	let foo = ref.foo;
	let bar = ref.bar;
	console.log('Hello rollup!')
}

```
# output
```js
var main = function (ref) {
	let foo = ref.foo;
	let bar = ref.bar;
	console.log('Hello rollup!');
};
module.exports = main;
```
# expect output
```js
var main = function () {
	console.log('Hello rollup!');
};
module.exports = main;
```

# repl
- [0.51.8](https://rollupjs.org/repl?version=0.51.8&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChyZWYpJTIwJTdCJTVDbiU1Q3RsZXQlMjBmb28lMjAlM0QlMjByZWYuZm9vJTNCJTVDbiU1Q3RsZXQlMjBiYXIlMjAlM0QlMjByZWYuYmFyJTNCJTVDbiU1Q3Rjb25zb2xlLmxvZygnSGVsbG8lMjByb2xsdXAhJyklNUNuJTdEJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
- [0.50.0](https://rollupjs.org/repl?version=0.50.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChyZWYpJTIwJTdCJTVDbiU1Q3RsZXQlMjBmb28lMjAlM0QlMjByZWYuZm9vJTNCJTVDbiU1Q3RsZXQlMjBiYXIlMjAlM0QlMjByZWYuYmFyJTNCJTVDbiU1Q3Rjb25zb2xlLmxvZygnSGVsbG8lMjByb2xsdXAhJyklNUNuJTdEJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

**Comment by lukastaegert** [comment]
Hi @UncleBill,

when evaluating function side effects, rollup assumes all parameters to be "unknown". This is because rollup cannot be sure it knows all parameters a function is called with. You could for instance attach a function to a prototype and call it on an instance or pass it to an external function that calls it.

In your case, your function would throw an error if `ref` were undefined or it could trigger getters. I plan on adding an option to remove these particular checks in the next feature release.

However, I do not expect this to be ever resolved completely.

**Comment by UncleBill** [comment]
Thanks for reply!
It is not a big issue. You can handle others firstly!

**Comment by lukastaegert** [comment]
BTW if you use destructuring parameters, this check is not done:
```javascript
export default function ({foo, bar}) {
	let someFoo = foo;
	let someBar = bar;
	console.log('Hello rollup!')
}
```
will keep only the console statement.

**Comment by lukastaegert** [comment]
Rollup v0.52 now has an option `treeshake.propertyReadSideEffects` that should fix this issue. Please reopen this issue if this does not work for you or you feel this problem should be solved differently.

**Comment by UncleBill** [comment]
`treeshake.propertyReadSideEffects: false` really fix it, thanks! 👍
