### ISSUE TITLE
globals/external not working as expected

### ISSUE THREAD

**Issue by caub** [rollup/rollup#1746]
In this repo: https://github.com/caub/Leaflet.Terminator/blob/npm/rollup.config.js

```js
  name: 'leaflet.terminator',
  external: ['leaflet'],
  globals: {
    'leaflet': 'L'
  },
```
output generated: (`format :'umd'`)
```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('leaflet')) :
	typeof define === 'function' && define.amd ? define(['leaflet'], factory) :
	(global.leaflet = global.leaflet || {}, global.leaflet.terminator = factory(global.L));
}(this, (function (L) { 'use strict';

L = L && L.hasOwnProperty('default') ? L['default'] : L;
// ........
```

I expect that `L` is used in the output, but `global.leaflet` is still there, so I made this hacky plugin, in the hope rollup has a better way

As you can see, only the UMD header has this issue

I've read the docs, and issues on external/globals, yet I can't figure this

rollup: "^0.51.7"

**Comment by caub** [comment]
Hmm it'd work if I set `name: 'L.terminator'`

**Comment by lukastaegert** [comment]
Hi @caub, did you try @adrianheine 's PR by installing rollup via
```bash
npm install adrianheine/rollup#master
```
? Does it work for you? If so I would put this into the next release.
