### ISSUE TITLE
why change UMD `global` structure

### ISSUE THREAD

**Issue by jasonChen1982** [rollup/rollup#1750]
i upgrade `rollup` from `0.36.4` to `0.51.2`, and my library can't work as before.
when i use this `umd-bundle` , the new bundle had cover the `XXX` object which i defined before.

i want this UMD structure for `global`
```js
(factory((global.XXX = global.XXX || {})));
```

but got following in new `rollup`, and it overwrite my `window.XXX = {...}` or `same-series lib` export the same name `XXX`.
```js
(factory((global.XXX = {})));
```

**Comment by lukastaegert** [comment]
Maybe Rollup’s `extend` option is what you are looking for? We just updated the documentation with a little more information.

**Comment by jasonChen1982** [comment]
which `extend` option ? i can't find this config ~

my problem is, how to do the `UMD` bundle work with same `name-space`. not include an `external-lib`.

i suggest to keep following compatibility writing
```js
(factory((global.XXX = global.XXX || {})));
```

**Comment by lukastaegert** [comment]
This one:
![extend-option](https://user-images.githubusercontent.com/12949268/33264240-ff534bec-d36c-11e7-8a13-db270960d469.png)

**Comment by jasonChen1982** [comment]
bravo

**Comment by adrianheine** [comment]
Can this be closed?
