### ISSUE TITLE
sourcemaps missing

### ISSUE THREAD

**Issue by DrYSG** [rollup/rollup#1756]
The documentation is for 0.51.8 at https://rollupjs.org/ is a little out of date (it does not mention that sourceMaps is now in options) (at least that is the warnings I am given.

But even so, I am not seeing any sourcemaps with this rollup.config.js. I realize it must be a novice error on my part, but perhaps someone can clue me and other novices in: ( also tried all lowercase for sourcemap: 'inline'

```
export default {
    input: 'scripts/Main.js',
    output: {
        file: 'dist/bundle.js',
        format: 'es',
    },
    "options": {
        sourceMap: 'inline',
        output: {
            format: 'es'
        }
    }
}
```

**Comment by lukastaegert** [comment]
@DrYSG I think it should look like this:
```
export default {
    input: 'scripts/Main.js',
    output: {
        file: 'dist/bundle.js',
        format: 'es',
        sourcemap: 'inline'
    }
}
```
cf. the sample file at https://rollupjs.org/#configuration-files

**Comment by lukastaegert** [comment]
I assume the core issue was the wrong use of upper and lower case in `sourcemaps`. Please reopen the issue if you still think rollup’s behaviour is wrong. If you think the documentation could be improved, consider opening an issue for [rollupjs.org](https://github.com/rollup/rollupjs.org/issues).

**Comment by DrYSG** [comment]
As mentioned above tried both sourceMap: and sourcemap: but I had it in options, since that is what I recall seeing in the warning messages. (I am out of town a conference and don't have access to my work machine).

Anyway, the documentation at https://rollupjs.org/#big-list-of-options probably could be updated to indicated that the location for the sourcemap field as changed.

**Comment by lukastaegert** [comment]
Yes, I think the depreciation warning is actually deprecated. And we should add `output. …` to the options that belong into `output` on the website. Thanks for the feedback!

**Comment by DrYSG** [comment]
@lukastaegert , It is working fine for me, and I am following your suggestions. Yea, it was the biglist that was confusing me, since it does not say what section the sourcemap should be.

I was having issues with the uglify plug-in for es6, but it is in beta, it is not your issue!, and I really don't need that just minify, so here is my working rollup.config.

```
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import minify from 'rollup-plugin-minify-es'

export default {
    input: 'scripts/Main.js',
    output: {
        file: 'dist/bundle.js',
        format: 'es',
        sourcemap: 'inline'
    },
    plugins: [
        resolve({
            jsnext: true,
            main: true,
            browser: true,
        }),
        commonjs(),
        minify()
    ]
}
```
