### ISSUE TITLE
bundle.write(outputOptions)

### ISSUE THREAD

**Issue by jialj** [rollup/rollup#1766]
```js
const bundle = await rollup.rollup(inputOptions);

  const { code, map } = await bundle.generate(outputOptions);

  bundle.write(outputOptions);
```

This is my code, but sometime I want to write file sync. Can rollup suppot this speciality?
I wish ,I can use like this ,below,or other userful ways.

```js
const outputOptions = {
	async:false,
	......
};

const bundle = await rollup.rollup(inputOptions);

const { code, map } = await bundle.generate(outputOptions);

bundle.write(outputOptions);
```

**Comment by TrySound** [comment]
@jialj Rollup works asynchronously not because it nice. You can't just enable sync mode. Which task are you trying to solve?

**Comment by jialj** [comment]
Thanks for your answer. 
I want to  pause  javascript execute，when rollup is wirting file.  Because I start a prorcess to watch my file.   And I can resolve my issue by code like below.

```javascript
const bundle = await rollup.rollup(inputOptions);
const { code, map } = await bundle.generate(outputOptions);
fs.writeFileSync( outputOptions.file,code );

```

I think, if rollup support this speciality, I can do this  easier.

**Comment by TrySound** [comment]
```js
const bundle = await rollup.rollup(inputOptions);
const { code, map } = await bundle.generate(outputOptions);
```
This lines are still asynchronous. Isn't it a problem? Can't you watch after awaiting `bundle.write`?

**Comment by jialj** [comment]
It is ok!  I  am watching which file has change.   I can not watch after `bundle.write`, because I am using pm2 watch my file, when I start my app.

**Comment by TrySound** [comment]
Okay, how asynchronous breaks watching? OS shouldn't fire an event if writing is not end

**Comment by jialj** [comment]
Asynchronous dont breaks watching, but it trigger `pm2` restart many times, until the files are write finish.

**Comment by TrySound** [comment]
I'm not experienced with pm2, but there should be another solution. Rewriting all the stuff you use with pm2 is bad one. I'll keep this issue open.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
