### ISSUE TITLE
eliminating development-only code paths

### ISSUE THREAD

**Issue by ianstormtaylor** [rollup/rollup#1770]
Hey! Thanks for Rollup, it's awesome 😄 

I was wondering if there was already support for eliminating dev-only code paths, for things like `invariant/warning` or just plain `if (process.env.NODE_ENV != 'production')`. I was previously using Babel for this, but in the interest of the smallest possible builds I was thinking of switching to Bublé.

But I wasn't sure if this should be a Bublé thing, or a Rollup thing. Really it seems like it could be a Rollup plugin.

Has someone already worked on this?

**Comment by TrySound** [comment]
@ianstormtaylor It's `rollup-plugin-replace` thing similar to webpack DefinePlugin. Just replace process.env.NODE_ENV with necessary value. Rollup is able to tree shake falsy branches for a long time. 

See https://rollupjs.org/repl?version=0.52.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuJTVDbmlmJTIwKCdwcm9kdWN0aW9uJyUyMCElM0QlM0QlMjAncHJvZHVjdGlvbicpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZyglMjBjdWJlKCUyMDUlMjApJTIwKSUzQiUyMCUyRiUyRiUyMDEyNSU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwaXNuJ3QlMjB1c2VkJTIwYW55d2hlcmUlMkMlMjBzbyU1Q24lMkYlMkYlMjBSb2xsdXAlMjBleGNsdWRlcyUyMGl0JTIwZnJvbSUyMHRoZSUyMGJ1bmRsZS4uLiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTNCJTVDbiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwZ2V0cyUyMGluY2x1ZGVkJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwcmV3cml0ZSUyMHRoaXMlMjBhcyUyMCU2MHNxdWFyZSglMjB4JTIwKSUyMColMjB4JTYwJTVDbiU1Q3QlMkYlMkYlMjBhbmQlMjBzZWUlMjB3aGF0JTIwaGFwcGVucyElNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by ianstormtaylor** [comment]
Ahhh okay, thank you! (I'm a Rollup noob 😄 )

**Comment by ianstormtaylor** [comment]
Just realized, this won't help with `invariant/warning`, since they aren't dead by default. We'd need something like [`babel-plugin-dev-expression`](https://github.com/4Catalyzer/babel-plugin-dev-expression) for those to be auto-pruned.

**Comment by TrySound** [comment]
It's specific to convention. There's nothing to do with rollup. It doesn't care. Add Babel, add replace plugin after. You will get the same treeshaked result.

**Comment by ianstormtaylor** [comment]
@TrySound thanks! Yeah, I realize that, I just think that it might be a nice idea for a rollup plugin that does the common things like `invariant` automatically.
