### ISSUE TITLE
Rollup watch has a fatal error on first run if encounters error

### ISSUE THREAD

**Issue by mhkeller** [rollup/rollup#1773]
Repro here: https://github.com/mhkeller/rollup-fatal-watch

If I **introduce** a syntax error on a file, rollup will give me a nice error and once I've fixed it, rebuild.

If I try to run `rollup -w` on a file that **has** that same syntax error, the watch exits. I have to fix the error and then run `npm run build` again. 

It would be nicer if the behavior were the same between first run and during a build. 

Perhaps related to https://github.com/rollup/rollup/issues/1563

**Comment by aubergene** [comment]
It looks like this is the same as #1442 which is marked as wontfix. I guess it would possible to have a list of files such as the config and input file(s) and to always watch them, and only add dependencies when a build is succesful. I had a quick brose of the code but couldn't work out where this might be added.

**Comment by mhkeller** [comment]
Good searching @aubergene. ya it seems that there is enough information gathered in the first run to try *up to that point of failure*. But there is certainly much I don't understand about what would make that possible or not ideal.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by mhkeller** [comment]
Hi @shellscape. I think this issue would be great to fix. Please consider re-opening.

**Comment by shellscape** [comment]
@mhkeller We're fast approaching the 2 year mark since it was last discussed, so I'm not sure there's a large demand here. Would you be willing to lead the effort? We're spread pretty thin so we would appreciate the help.

**Comment by mhkeller** [comment]
@shellscape I made a PR for this including a test. If you can take a look, that would be great https://github.com/rollup/rollup/pull/3081
