### ISSUE TITLE
Proposal: Dynamic import remapping plugin hook

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#1779]
I'd like to make the following simple proposal for initial handling of dynamic import in rollup, and that is to:

1. Provide a new plugin hook `resolveDynamicImport (name: string, parent: string, partial: boolean) => string`.
2. When detecting any `import('x')` statement, Rollup would convert literal forms `import('x')`, `import("x")` and `import(``x``)` (double backtick because I don't know how not to in markdown) into a string name, and provide the `partial` argument as `false` since full string literal processing has been possible. The resolved string provided back is then inlined into the dynamic import statement.
3. When handling any expression form of `import(x)` Rollup would then make a best-effort to determine the _leading_ prefix string of the import, for partial resolution, with `partial: true` set. For example `import(``x/${name}``)` would call `resolveDynamicImport('x/', parent, true)`, and `import('x/' + name)` would result in the same call. The resolved value would then be substituted back into its component of the expression.
4. In cases where a partial prefix cannot be determined at all, these could simply be skipped entirely.

This would allow the plugin ecosystem to experiment with dynamic import handling (I have some really interesting work happening here, watch this space! 😀), while abstracting away the problems of AST parsing and analysis that Rollup handles so well.

Let me know your thoughts!

**Comment by lukastaegert** [comment]
I agree that having such a hook would really make sense! Just some thoughts:
1. Dynamic import is currently [at stage 3](https://github.com/tc39/proposal-dynamic-import) and as such unsupported by vanilla acorn. We could of course add an appropriate plugin but this might cause incompatibilities with other plugins that do not use the plugin etc. and would deviate from our current approach of only supporting stage 4 features. Once dynamic import is at stage 4, there is nothing preventing us from adding this.
2. I do not like the guess-work involved in the `partial` flag which would mean plugins could start depending on how the heuristics of rollup interpret an expression. My suggestion would be the following:
   * If the argument is a string literal, we provide the string
   * Otherwise, we just provide the plain AST nodes of the embedded expression and let the plugins sort this out. Then, a plugin can freely decide to do any of the following:
      * Ignore dynamic names and throw an error
      * Do its own guess-work, which can then be plugin-specific and part of the API of this plugin
  
      This is a freedom that rollup should not have IMO.
3. I would call the first parameters `source` similar to the corresponding parameter of the AST node
4. I would suggest to follow the pattern: Parameters that are essential first, then all other parameters as part of a parameter object. In this case one could argue that the only "essential" parameter is `source` as in the default case, it is the only one we need. So I would suggest a signature like
   
   ```javascript
   resolveDynamicImport (source: string | Node, {parent: string, hasDynamicSource: boolean}) => string
   ```

**Comment by lukastaegert** [comment]
Just a question as you seem to have put some thought into this and I could not find a clear answer to this question yet: Do dynamic imports always resolve to the same instance of a module or to a new instance? I.e. if we have

```javascript
// lib.js
export default {};

// main.js
import lib1 from './lib.js';
Promise
  .all([import('./lib.js'), import('./lib.js')])
  .then(([lib2, lib3]) => console.log(lib1 === lib2, lib1 === lib3, lib2 === lib3));
```

should the output be `false false false` or something else? This does not necessarily have a direct bearing on this issue but can have important implications for rollup handling (or not handling) dynamic imports in general.

**Comment by guybedford** [comment]
1. I understand Acorn has a strict policy of features, but dynamic import is guaranteed at this point and a crucial feature to support, so I would strongly encourage bundling the necessary plugin automatically in Rollup. Perhaps such a feature could be enabled when using this "resolveDynamicImport" hook only if that makes things better. But I don't think it would be wise to allow Rollup to be held back on a crucial feature for these reasons.

2. The reasoning behind the partial extraction is to consider scenarios like:

```js
import { basePath } from './constants.js';
export async function dynamic () {
  const { thing } = await import(`${basePath}/dynamic.js`);
  return thing;
}
```

Rollup does the static analysis so may have a good idea what `basePath` is, and could tell the hook that we're resolving `/path/to/dynamic.js` directly, which would be far more useful. Once re-substituted, tree shaking could potentially remove the basePath dependency as well. So that's why I'm suggesting a deeper level of analysis on the Rollup side here. Of course it doesn't have to start that way, but having a path underneath would be nice I think and could be quite powerful.

3. Yes dynamic imports always resolve to the same instance of a module - the module namespace object is a unique object in the loader registry in the browser. This also brings up another point of inlining dynamic import. Consider for example if the module being dynamically imported was also being inlined by another static import, then we could replace the entire dynamic import expression with a `Promise.resolve(moduleObject)`. Perhaps doing this when `resolveDynamicImport` resolves to a string module name that matches a string module name that is already otherwise statically imported.

**Comment by lukastaegert** [comment]
I feared as much, (3) is really bad. There is no such thing as a `moduleObject` now, this is one of the reasons why rollup produces such efficient code. Maybe these need to be implemented if a module is accessed dynamically. However, the whole concept of code splitting revolves around the idea that dynamic imports pull in new code. We need solutions for the case where two asynchronously loaded modules have the same dependency. If this dependency is compiled and scope-hoisted into both bundles, it will be really hard to untangle it and use the SAME instance.

As for the rest, I would rather find ways to enable plugins to add parser plugins and inject new AST node definitions. This would not only solve this issue but also enable many other REALLY cool things like a plugin for native JSX support, maybe even a plugin for native TypeScript support, you name it! Of course we should define what is considered to be "stable" for the AST node interface. Currently, a lot of things are still in flux here.

Particularly for (2), no, currently rollup does not have any idea what `basePath` is. This *could* be implemented but as stated above, I do not see this as rollup's responsibility as there is no clear, natural answer. IMO, putting this responsibility on the plugins makes much more sense and gives them far greater freedom.

**Comment by guybedford** [comment]
@lukastaegert the naive implementation of dynamic import is basically the assumption that the module being imported is an _entry point_. As such, just like building a top-level module in Rollup, all exports are expected to be present.

That said, there may be ways to optimize this - for example, `import('x').then({ destructuredValue } => ...)` could be detected by Rollup and tree-shaken in the same way as usual. Module instance checks are rarely performed in code, but when done would be an effective deoptimization of this technique then yes.

Ah, I disagree about opening up ASTs as you run into all the Babel problems of ordering. And Rollup, tracking scope and analysis being the primary priority, it might be difficult to maintain a consistent picture of all that while tracking plugin hooks into the AST.

I'd strongly advocate Rollup moving to a place where it does partial execution analysis personally, as that would take it to automatic side effect detection.

**Comment by guybedford** [comment]
@lukastaegert would you be open to a PR for the hook here exactly along the lines of your previous suggestion in https://github.com/rollup/rollup/issues/1779#issuecomment-350186471? Let me know if you've had any further thoughts on this.

**Comment by lukastaegert** [comment]
(For other readers following this thread, further comments are at #1790)
