### ISSUE TITLE
Officially support rollup-stream

### ISSUE THREAD

**Issue by KayakinKoder** [rollup/rollup#1780]
I've been evaluating rollup for our project and am loving it. My only concern is that we use gulp for our build processes, and really want to stay that route. I'm wondering if you'd consider "officially" bringing in [rollup-stream](https://www.npmjs.com/package/rollup-stream) as an optional way to use rollup with gulp.

I completely understand the rational behind using rollup plugins, and for a majority of folks that's the best way to go. But for those of us already heavily invested in gulp for builds, knowing that `rollup-stream` capability isn't going to go vanish in 6 months would be really comforting. I can definitely see us switching things over to rollup plugins in the future, but being able to stick rollup right into our gulp build system right away is a big selling point. This is also the only "con" on the side of rollup in my rollup vs. browserify pros/cons list.

(On a side note, the setup docs are really well done. Took me less than an hour to get things up and going from scratch)

**Comment by TrySound** [comment]
@KayakinKoder Gulp officially support promises in tasks which are used in rollup api. So you don't need to do hacky conversion to streams.

**Comment by KayakinKoder** [comment]
Thanks, I've done some reading about that but don't know how that would help. This is more a question for stackoverflow but if anyone has an example hanging around, that would be appreciated.

A simplified example of what we're looking at; instead of using the rollup plugin uglify, we want (need actually, for some use cases) to uglify in our gulp flow:

const uglify = require('uglify');

```
gulp.task('build', function(){
    return gulp.src(['src/main.js'])

        // rollup here

        .pipe(uglify())
        .pipe(gulp.dest('dist'))
});
```

**Comment by KayakinKoder** [comment]
TrySound's heralded answer here seems relevant: https://github.com/gulpjs/gulp/issues/1181

You guys can close this if you'd like, I'll comment here in the near future once I hopefully get the syntax figured out. Thanks

**Comment by TrySound** [comment]
@KayakinKoder The nice thing about rollup is own ecosystem. It has own input/output stuff and a lot of plugins which do not need to be replaced with any wrappers.
Hope this can help https://rollupjs.org/#gulp

**Comment by KayakinKoder** [comment]
Thanks, yes I've seen the example there (note to anyone trying to get that to work -- you may need to update to at least Node v8 for `await` functionality).

Eventually we may hopefully migrate to using many of rollup's plugins, but our build process with gulp does a lot of things that we currently need which rollup plugins wouldn't be able to handle. For example, after bundling but before minifying we output bundle.js to a /build folder, then minify and output to /dist. I don't see a way we could get this post-bundled but pre-minified file output with rollup's ecosystem.

Gulp is obviously a really powerful task runner that I think quite a few orgs are invested in, plug-and-play with gulp is a really attractive draw I would imagine for folks evaluating rollup.

**Comment by TrySound** [comment]
@KayakinKoder async/await feature is just syntax for promises. So you don't need. Well, yeah, output minified and non-minified files requires one more rebuild, but this is the only problem.

**Comment by KayakinKoder** [comment]
@TrySound any chance there's an example that uses regular promises? :) My es8 knowledge is minimal at best.

**Comment by TrySound** [comment]
Sure https://github.com/rollup/rollupjs.org/blob/master/guide/en/05-tools.md#gulp

**Comment by aaronkahlhamer** [comment]
@KayakinKoder If it helps any, I was able to combine Rollup, rollup-stream, and Gulp. 

- [Dev Diary: Gulp + rollup.js](https://medium.com/@networkaaron/dev-diary-gulp-rollup-js-fd2d22e58596)
- [Gulp + rollup.js + ordered-read-streams](https://medium.com/@networkaaron/dev-diary-gulp-rollup-js-ordered-read-streams-cb2e973f9057)

How I figured it out, I don't know.
