### ISSUE TITLE
What's the matter !!!!

### ISSUE THREAD

**Issue by wbbhacker** [rollup/rollup#1781]
I'll follow the official website for a step-by-step study rollup ,but it is wrong...
![image](https://user-images.githubusercontent.com/11323741/33700330-8ade2b4e-db53-11e7-8a34-ae2c5a8e9ca2.png)
![image](https://user-images.githubusercontent.com/11323741/33700342-a4a5d8b0-db53-11e7-8050-1481d2c8c4a8.png)

**Comment by TrySound** [comment]
@wbbhacker Show the output of `rollup -v` command

**Comment by wbbhacker** [comment]
@TrySound it show `rollup version 0.47.6 `

**Comment by TrySound** [comment]
@wbbhacker Too old. Current v0.52.1. Try to update `npm i rollup -g`

**Comment by wbbhacker** [comment]
@TrySound  Work It Out,Thank you very much for your reply
