### ISSUE TITLE
Regression with NodeJS 9

### ISSUE THREAD

**Issue by alippai** [rollup/rollup#1782]
I'm having problem using rollup with nodejs 9.2.0, but 8.9.2 works fine. The error message:
```
Error [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string without null bytes. Received type string
    at nullCheck (fs.js:173:16)
    at Object.fs.readFile (fs.js:359:8)
    at next (/mnt/c/Repositories/proj1/app/admin/node_modules/browser-resolve/index.js:98:12)
    at load_shims (/mnt/c/Repositories/proj1/app/admin/node_modules/browser-resolve/index.js:116:7)
    at resolve (/mnt/c/Repositories/proj1/app/admin/node_modules/browser-resolve/index.js:236:5)
    at /mnt/c/Repositories/proj1/app/admin/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:58:5
    at new Promise (<anonymous>)
    at resolveId$1 (/mnt/c/Repositories/proj1/app/admin/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:57:11)
    at promise.then.result (/mnt/c/Repositories/proj1/app/admin/node_modules/rollup/dist/rollup.js:1750:32)
    at <anonymous>
Could not resolve '/mnt/c/Repositories/proj1/app/admin/node_modules/rxjs/util/errorObject.js' from commonjs-proxy:/mnt/c/Repositories/proj1/app/admin/node_modules/rxjs/util/errorObject.js
```
and there is a `\0` char before the `commonjs-proxy`

This is an Angular 4 project built with ngc + rollup. The used modules are node resolve and commonjs.

**Comment by kzc** [comment]
If memory serves there was a hack to encode plugin information in the path after the null character:

https://github.com/rollup/rollup-plugin-node-resolve/blob/v3.0.0/src/index.js#L36

**Comment by alippai** [comment]
This is the importer case, not the importee, if I'm right.

**Comment by kzc** [comment]
Just pointing out some similar hack likely going on.

**Comment by alippai** [comment]
<3

**Comment by alippai** [comment]
Disabling the rollup-plugin-commonjs solves the issue (we had only 1 or 2 modules with no ESM option available)

**Comment by guybedford** [comment]
I take it this issue is no longer happening? Will close if that is the case.

**Comment by alippai** [comment]
Well, I'm using ES6 modules in most cases (for Angular 6 + 3rd party modules), so I don't face this problem anymore.

**Comment by anurse** [comment]
I'm still seeing this issue, and can't easily change to ES6 modules. But at this point we're probably just going to switch off of rollup to avoid this issue.

**Comment by bfulop** [comment]
I had the same error and it was resolved by moving the `commonjs({...})` block to be the first in the `plugins` list. 

As explained here: https://rollupjs.org/guide/en#npm-packages

> Note that rollup-plugin-commonjs should go before other plugins that transform your modules — this is to prevent other plugins from making changes that break the CommonJS detection.

**Comment by stephenmathieson** [comment]
Thanks @bfulop, that worked for me.
