### ISSUE TITLE
Documentation: ‘globals’ options can be a function

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup#1789]
‘globals’ option seems that it can be a function, however I cannot find any documentation stating this.

Should be added to the documentation

**Comment by goncharovnikita** [comment]
Yes, you need to make is self calling function, e.g:
```
globals: (() => { return { test: 'value' } })()
```

**Comment by alan-agius4** [comment]
I belive you dont need to make it self calling seeing the rollup code. 

Would be great if some one adds it to the documentation

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
