### ISSUE TITLE
Weird issues importing modules at build time

### ISSUE THREAD

**Issue by jasonkarns** [rollup/rollup#1791]
At first I thought this was another manifestation of https://github.com/rollup/rollup-plugin-commonjs/issues/262. However, after doing more digging, I think there are some other weird things going on.

(All repro examples are from [jasonkarns/rollup-repro](https://github.com/jasonkarns/rollup-repro) with simple `npm i && npm run build`)

Starting at the beginning: I'm migrating from browserify + commonjs -> rollup + ESM. As such there are some modules in the repo that are CJS that are imported by code that has been updated to use ESM.

First issue (on master branch): 
```
[!] Error: Cannot find module './logger.js'
Error: Cannot find module './logger.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/tmp/repro/rollup.config.js:8:1)
    at Module._compile (module.js:635:30)
    at Object.require.extensions..js (/private/tmp/repro/node_modules/rollup/bin/rollup:20371:8)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

The entrypoint (/index.js) is ESM which imports from a CJS module (`src/analyticsListener.js`) which itself requires another local CJS module `src/logger.js`.

Another thing of note: this all happens because the ESM entrypoint is itself imported into the rollup config so as to derive the UMD "name" by the exported function name. (further explained below)

## weird thing no. 1
(see [subdir branch](https://github.com/jasonkarns/rollup-repro/tree/subdir)): Simply moving `src/analyticsListener.js` to root makes it work. That is: ESM entry `index.js` -> importing CJS `analyticsListener.js` -> requiring CJS `src/logger.js`. Why on earth the directory location of `analyticsListener.js` matters really confuses me.

## weird thing no. 2
(see [default-export branch](https://github.com/jasonkarns/rollup-repro/tree/default-export)): Uncommenting the _usage_ of the imported CJS module (oldLister) as opposed to it being just an unused import, yields a different error:

```
[!] Error: 'default' is not exported by src/analyticsListener.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
index.js (1:7)
1: import oldListener from './src/analyticsListener'
          ^
2: 
3: export default class AnalyticsListener {
```

## weird thing no. 3
(see [static-umd-name](https://github.com/jasonkarns/rollup-repro/tree/static-umd-name)): Removing the import from the rollup config (and just using a string literal) eliminates the errors. Which is an acceptable workaround to be sure, but the root cause for this behavior eludes me.

**Comment by kuraga** [comment]
Any ideas?

**Comment by jasonkarns** [comment]
I went with the workaround of not importing the entrypoint into the rollup config. (Since I was only importing it so as to make the UMD name automatic based on the default export.) I haven't done any further investigation beyond what's already documented above.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
