### ISSUE TITLE
Bug of compile (1, eval)

### ISSUE THREAD

**Issue by rwu823** [rollup/rollup#1793]
input:

```js
(1, eval)('this')
```

output:
```js
(eval)('this')
```

**Comment by rwu823** [comment]
Any updates?

**Comment by adrianheine** [comment]
Could you explain the issue a bit further? Since the comma operator only returns the last item and `1` is side-effect free, it seems correct to me to drop that part of the expression?

**Comment by rwu823** [comment]
@adrianheine you can create one JS file and then try both look what is difference

**Comment by lukastaegert** [comment]
This looks like a transformation used by a transpiler like Babel. We had similar issues with `(0, x.y)()` having the wrong `this` context for which we added a very specific fix. We could solve this by making the fix more general but it would be really interesting to know what library/framework produces such code. If it is handwritten code you could work around it by writing something like `(1 && eval)('this')` instead

**Comment by adrianheine** [comment]
@rwu823 Now I understand. I only checked in the nodejs REPL where both behave the same.

**Comment by guybedford** [comment]
I wonder if this case could be added as a special exception, as it is a known pattern?

**Comment by guybedford** [comment]
Indirect call cases are all properly handled now thanks to some careful work by @lukastaegert.
