### ISSUE TITLE
Issues with default anonymous exports in 0.52.2

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#1798]
Some issues look to be caused by the regular expression [here](https://github.com/rollup/rollup/pull/1787/files#diff-6db9cc4c7dda84e33ed4bb1d66cb4587R49) being too narrow. It's possible to have anonymous default function/class definitions that do not match that pattern, and so `.match` returns null, and subscripting that throws an exception.

This can be reproduced with a default anonymous export of an async function, or by inserting a comment between two of the keywords in the definition.

Async functions would probably be able to be handled by extending the regular expression - but that doesn't sound like a good idea for dealing with comments. My feeling is that it would be better to be looking at the AST here rather than the string, but I haven't looked into this much.

**Comment by Conduitry** [comment]
cc @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
I will fix this bug this evening
