### ISSUE TITLE
[question] globals option not considered when creating an esm bundle ?

### ISSUE THREAD

**Issue by louisantoinem** [rollup/rollup#1803]
Is it normal that the following import

    import $ from 'jQuery'

with following options in the main config

    external: ['jQuery'],
    globals: {'jQuery': '$'},

still generates a

    import $ from 'jQuery'

in the esm bundle ? (causing an error in browser "Failed to resolve module specifier 'jQuery'")

I was expecting that specifying the "globals" options would prevent this.

When generating an umd bundle, this works as expected (bundle is using the global $).

I got around this with:

    let $ = window.jQuery

instead of 

    import $ from 'jQuery'

But I'd prefer to consistently use ES6 imports in my code.

**Comment by guybedford** [comment]
This seems to be a surprisingly common catch, typically adapter modules exporting globals are the recommended route here.

**Comment by chiefcll** [comment]
@guybedford - Can you provide a link / example to what you mean?

**Comment by guybedford** [comment]
@chiefcll you can create a custom module like - 

jquery.js
```js
export default window.jQuery
```

and then import from that. `globals` is only for when using the UMD or IIFE output format.

**Comment by chiefcll** [comment]
OK - then ideally we should be doing the following

```javascript
import $ from './jquery.js'
```

and jquery.js is as you described.
