### ISSUE TITLE
Dynamic import support?

### ISSUE THREAD

**Issue by DrYSG** [rollup/rollup#1807]
My issue is that sometimes I want to run my HTML file with from the bundle,
```
  <script type="module" src="bundle.js"></script>
```
but for VSCODE debug I also sometimes just include the src, before it is bundled.
 
```
  var DYNAMIC = true;
  <script type="module" src="scripts/Main.js"></script>
```
where inside Main.js I have
```
if (DYNAMIC) {
   var pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8')); }
else
   {import pkg from './package.json';}
```

The import statement of JSON is going to cause an error because dynamic import (doing an import inside of a condition) is not  going to work.

There is a stage 3 proposal for dynamic import:

http://2ality.com/2017/01/import-operator.html
https://github.com/tc39/proposal-dynamic-import

Is this possible with the current rollup? If not, what is going to happen when this is accepted?

**Comment by lukastaegert** [comment]
This has just (=today!) been released as 0.53.0:
https://github.com/rollup/rollup/pull/1790

It's just not properly labeled as "merged". My fault.

**Comment by nicolo-ribaudo** [comment]
@DrYSG
Please note that `import pkg from './package.json';` is not dynamic import. It should be something like 
```js
import('./package.json').then(pkg => /* ... */)
```

**Comment by geoffdavis92** [comment]
@lukastaegert I found this issue after searching the docs in the [import section](https://rollupjs.org/guide/en#importing) for dynamic imports support info.

Can I update the site docs to reflect the new support for dynamic imports?

**Comment by lukastaegert** [comment]
Yes please! I've been meaning to do this for some time now but as you can see...
Note that we currently have dynamic imports behind the `experimentalDynamicImport` feature flag due to some issues with `rollup-plugin-commonjs`.

**Comment by geoffdavis92** [comment]
Sounds good @lukastaegert. I also will note that dynamic imports are not available when targeting ECMAScript 2015 modules, which was the error message that led to me searching for documentation.

**Comment by geoffdavis92** [comment]
@lukastaegert I've got this section added, but I am not seeing the changes I made in `/guide` show up when running `$ npm run dev`, or any other build script.

Do you have any insight?

**Comment by lukastaegert** [comment]
Seems that live updates have been broken by the switch to sapper. But if I kill the server and run `npm run dev` again, updates show up all right.
Would be cool if you could submit your PR soon, otherwise others might accidentally beat you to it, which would be a waste of effort 😉

**Comment by arackaf** [comment]
@lukastaegert hi - sorry to bother you here.  Do you happen to know if there's an issue currently open tracking the commonjs plugin's problem with dynamic import? I looked but didn't find anything.  

I'd love to position ourselves to use Rollup at work, but integrating with CommonJS and AMD are unfortunate requirements.

**Comment by guybedford** [comment]
@arackaf I haven't tracked this problem but could look into it. Do you have a link or further info to share on this?

**Comment by arackaf** [comment]
@guybedford not on my account!  It's clear Rollup works best in an all ESM environment, and it's clear to me converting all our CJS and AMD work to ESM will be a sine qua non for using this in production, and I'm 100% fine with that.

But if you're curious, you can clone this branch. 

https://github.com/arackaf/booklist/tree/special/guybedford-rollup1 

Drop to react-redux folder, and run `npm run rollup`.  No ts needed.  You'll see it error.  You can fix the error by **either** comment out the call to `let p = import(x);` in the root module this is building (`tempRollupEntry.js` which is different than what you saw before), or you can switch off the commonJS plugin in the rollup config file.
