### ISSUE TITLE
The `banner` option is not working in Rollup 0.53.0

### ISSUE THREAD

**Issue by fengyuanchen** [rollup/rollup#1809]
The `banner` option works fine in v0.52.3, but **not** in v0.53.0.

For reproduction: 
1. `git clone https://github.com/fengyuanchen/viewerjs.git`
1. `npm install && npm run build`
1. Checkout `dist/viewer.js` file, you can see the banner is **existing**.
1. `npm install rollup@0.53.0`
1. `npm run build`
1. Checkout `dist/viewer.js` file, you can see the banner is **not existing**.

BTW: https://rollupjs.org/repl has errors and thus is not working.

**Comment by ankeetmaini** [comment]
Hi @fengyuanchen as part of a recent clean-up the options were moved to a unifying config. Now the `banner` option goes in `output` instead of root.

I'll add a deprecation in Rollup and can raise a PR to your repository to fix this. Sorry about that!

**Comment by ankeetmaini** [comment]
[https://github.com/fengyuanchen/viewerjs/pull/127/](This) fixes the issue, though I've not bumped Rollup's version. (Changes are forward compatible).

**Comment by ankeetmaini** [comment]
Looking into REPL error.

**Comment by fengyuanchen** [comment]
OK, I see. Suggest to update the docs at https://rollupjs.org/#banner-footer:

from:

```js
// rollup.config.js
export default {
  ...,
  banner: '/* my-library version ' + version + ' */',
  footer: '/* follow me on Twitter! @rich_harris */'
};
```

to: 

```js
// rollup.config.js
export default {
  ...,
  output: {
    banner: '/* my-library version ' + version + ' */',
    footer: '/* follow me on Twitter! @rich_harris */'
  }
};
```
