### ISSUE TITLE
Minify-es

### ISSUE THREAD

**Issue by DrYSG** [rollup/rollup#1815]
You might want to add this to the plugins page, I found it useful in cases where I have no need (and don't need the complexity to uglify). 

Just plain minify:

https://www.npmjs.com/package/rollup-plugin-minify-es

**Comment by adrianheine** [comment]
The [plugins page](https://github.com/rollup/rollup/wiki/Plugins) is a wiki page, so you should be able to edit it yourself. Also, in case you didn't know, rollup-plugin-minify-es uses uglify internally.
