### ISSUE TITLE
[BUG] Rollup failing to interpolate some variables, causes ReferenceErrors

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#1821]
Rollup takes dependencies and names them something like `foo$1`, and generally replaces all references to the import with that new name (f.e. replaces `foo` with `foo$1` in relevant parts).

However, it is failing to rename some variables (i.e. leaving `foo` instead of placing `foo$1` there) which causes some `ReferenceError`s at runtime.

Here's a reproduction: https://github.com/trusktr/infamous/tree/rollup-rollup-issue-1821

package-lock.json is included so that the version numbers causing the problem are apparent.

Note that in package.json I am using SemVer `^` to keep the packages updated to the latest, and I personally don't use package-lock.json for this project because it is a library. I noticed the problem when I deleted `node_modules` and reinstalled everything (without package-lock.json) and so this installed newer version of rollup and plugins within the semver range, but it appears that one of the version bumps introduced a breaking change. If I remove the `^` symbols from package.json in order to lock the version manually, the problem goes away. So, it seems that either a minor or a patch bump introduced a bug.

To reproduce the error:

```sh
npm i
npm run build-global

# statically serve the root of the project somehow, f.e.:
npm i -g http-server
http-server . # port 8080 by default
```

then open http://localhost:8080/test.html in your browser and you'll see the errors in your console when test.html runs the `global.js` script:

```
Uncaught ReferenceError: _utils is not defined
```

You can find examples of problematic output in `global.js` on lines 7919 through 7953, which looks like this:

```js
  function Rule(selector, style, options) {
    _classCallCheck(this, Rule);

    this.id = utils$1.uid.get();
    this.type = 'font-face';
    this.options = options;
    this.selector = selector;
    this.style = style;
  }

  /**
   * Generates a CSS string.
   *
   * @see toCSS
   * @api public
   */


  _createClass(Rule, [{
    key: 'toString',
    value: function toString(options) {
      var this$1 = this;

      if (Array.isArray(this.style)) {
        var str = '';
        for (var index = 0; index < this.style.length; index++) {
          str += (_utils.toCSS)(this$1.selector, this$1.style[index], options);
          if (this$1.style[index + 1]) { str += '\n'; }
        }
        return str;
      }

      return (_utils.toCSS)(this.selector, this.style, options);
    }
  }]);
```

In that snippet you see a variable `utils$1` is being used. Further down, you'll see the variable `_utils` being used which should actually have been converted to `utils$1`, which is what causes the `ReferenceError`s.

**Comment by trusktr** [comment]
Here's a reproduction: https://github.com/trusktr/infamous/tree/rollup-rollup-issue-1821

package-lock.json is included so that the version numbers causing the problem are apparent.

Note that in package.json I am using SemVer `^` to keep the packages updated to the latest, and I personally don't use package-lock.json for this project because it is a library. I noticed the problem when I deleted `node_modules` and reinstalled everything (without package-lock.json) and so this installed newer version of rollup and plugins within the semver range, but it appears that one of the version bumps introduced a breaking change. If I remove the `^` symbols from package.json in order to lock the version manually, the problem goes away. So, it seems that either a minor or a patch bump introduced a bug.

To reproduce the error:

```sh
npm i
npm run build-global

# statically serve the root of the project somehow, f.e.:
npm i -g http-server
http-server . # port 8080 by default
```

then open http://localhost:8080/test.html in your browser and you'll see the errors in your console when test.html runs the `global.js` script:

```
Uncaught ReferenceError: _utils is not defined
```

You can find examples of problematic output in `global.js` on lines 7919 through 7953, which looks like this:

```js
  function Rule(selector, style, options) {
    _classCallCheck(this, Rule);

    this.id = utils$1.uid.get();
    this.type = 'font-face';
    this.options = options;
    this.selector = selector;
    this.style = style;
  }

  /**
   * Generates a CSS string.
   *
   * @see toCSS
   * @api public
   */


  _createClass(Rule, [{
    key: 'toString',
    value: function toString(options) {
      var this$1 = this;

      if (Array.isArray(this.style)) {
        var str = '';
        for (var index = 0; index < this.style.length; index++) {
          str += (_utils.toCSS)(this$1.selector, this$1.style[index], options);
          if (this$1.style[index + 1]) { str += '\n'; }
        }
        return str;
      }

      return (_utils.toCSS)(this.selector, this.style, options);
    }
  }]);
```

In that snippet you see a variable `utils$1` is being used. Further down, you'll see the variable `_utils` being used which should actually have been converted to `utils$1`, which is what causes the `ReferenceError`s.

**Comment by trusktr** [comment]
For reference, here's a branch that shows the error is gone when I remove the `^` symbols from package.json to manually lock the versions so they aren't updated to newer minor/patch versions: https://github.com/trusktr/infamous/tree/rollup-rollup-issue-1821-2

The steps are the same (perhaps remove `node_modules` and start from scratch), and when you open it in your browser those errors will be gone (but ignore the new error about `threeJsCounterRotation` that shows up, that's unrelated).

**Comment by trusktr** [comment]
In case it helps, I'm using `node v8.5.0` and `npm v5.6.0`

**Comment by guybedford** [comment]
There have been a number of changes in this scope handling code, would be interesting to hear if these issues are still happening?

The more the test case can be isolated the better, and a Rollup repl link is always the ideal here.

**Comment by guybedford** [comment]
This should have been resolved by the latest updates, but let me know if you're still seeing this.
