### ISSUE TITLE
Rollup treats linked modules as external dependencies.

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#1822]
I'm trying to use `npm link <package-name>` to link packages into my project so I can try changes as I dev the linked package. But Rollup tells me the package is external:

```
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
regexr (imported by src/core/LightBase.js)
(!) Missing global variable name
Use options.globals to specify browser global variable names corresponding to external modules
regexr (guessing 'r')
```

Repro coming up.

**Comment by trusktr** [comment]
Hmmm, I can't reproduce the problem, however while having the linked module I've been able to cause two other errors while running Buble, yet I get no errors if I simply install the module rather than linking it.

Suffice it to say, using linked modules isn't working, and I've gotten so far three different errors. I'm not sure why I got two other errors when trying to reproduce the first error.

So, I can't yet reproduce the first error that I got (the one reported here).

What I can do, for now, is to just push my changes to remote, then rather than linking the package just install from the remote git repo. It's less ideal, but at least it'll work.

I'll close this and reopen if I can reproduce.

**Comment by sprajagopal** [comment]
Can confirm the above on 0.53.3.
I have a bunch of 
`import x from 'x'` 
type dependencies all of which are available in the node_modules as symlinks ( I can see from a simple ls). But rollup tells me it treats them as external dependencies.

**Comment by kzc** [comment]
Might be related to this: #1819

**Comment by Filip-Rogalski** [comment]
I got the same problem. But in rollup-stream package used with gulp:

This is one of my js modules where I import jQuery module:
```import jQuery from 'jquery';

const display = () => {
    return jQuery(document);
}
export default display```

This is the gulp task:

```import gulp from 'gulp';
import sourcemaps from 'gulp-sourcemaps';
import rollup from 'rollup-stream';
import source from 'vinyl-source-stream';
import buffer from 'vinyl-buffer';
import babel from 'gulp-babel';

const rollupJS = (inputFile, options) => {
    return () => {
        return rollup({
            input: options.basePath + inputFile,
            format: options.format,
            sourcemap: options.sourcemap
        })
        .pipe(source(inputFile, options.basePath))
        .pipe(buffer())
        .pipe(babel())
        .pipe(gulp.dest(options.distPath));
    }
}

gulp.task('rollupBuild', rollupJS('main.js', {
    basePath: './scripts/',
    format: 'cjs', //useless for the moment - need plugin for transform es6
    distPath: './rollupBundle',
    sourcemap: true,
}));```

running 'gulp rollupBuild' gives error: 
`'jquery' is imported by scripts\components\display.js, but could not be resolved – treating it as an external dependency`

**Comment by Filip-Rogalski** [comment]
Resolved it myself: 
for rollup to locate node_modules we need to install plugin:
    rollup-plugin-node-resolve
It's good also to add 
    rollup-plugin-commonjs
So I modified my gulp task:


    import resolve from 'rollup-plugin-node-resolve';
    import commonjs from 'rollup-plugin-commonjs';
    /// [...]
    const rollupJS = (inputFile, options) => {
    return () => {
        return rollup({
            input: options.basePath + inputFile,
            format: options.format,
            sourcemap: options.sourcemap,
            plugins: [ resolve(), commonjs() ]
          })
          .pipe(source(inputFile, options.basePath))
          .pipe(buffer())
          .pipe(babel())
          .pipe(gulp.dest(options.distPath));
        }
    }

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
