### ISSUE TITLE
problem tree shaking with latest (@babel/babel-helpers@7.0.0-beta.36)

### ISSUE THREAD

**Issue by tswaters** [rollup/rollup#1823]
There's a problem with one of the helpers introduced in https://github.com/babel/babel/commit/0c885b3200ce1e5104f43714fa149f504295d2c9.

The code there is not tree shaking properly so a piece of the polyfill is left in any bundles that are using `rollup-plugin-babel`.  This injects everything and relies on tree shaking to cut out what is unused.

The helper in question is `wrapNativeSuper`.  I played around with it a bit and I found that if I commented out `typeof Reflect === "object" && Reflect.construct` is properly trims it out.

Reproduction is here:  https://github.com/tswaters/rollup-issue-1823

[Reduced REPL repro](https://rollupjs.org/repl?version=0.52.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMlJlZmxlY3QuY29uc3RydWN0JTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)... expecting an empty bundle there.

**Comment by lukastaegert** [comment]
Thanks for the info! Not sure when I find again time to work on the tree-shaking but I guess this should be solvable, albeit with a little work with the global handling.

**Comment by christianhaller** [comment]
same here, a bit annoying. any chance to fix this soon?

**Comment by lukastaegert** [comment]
I have started working on a PR to rework handling of global functions and builtin prototype methods which should be able to do this once it is finished. Might take more than a week, though, as I do not have a lot of time on my hands right now. But I'll take a look tomorrow if we could just add a quick fix for now until the proper fix is complete.

**Comment by christianhaller** [comment]
Thank you @lukastaegert 
It's working like a charm.
