### ISSUE TITLE
Rollup does not strip anything with a chained function

### ISSUE THREAD

**Issue by fskreuz** [rollup/rollup#1824]
[REPL repro here](https://rollupjs.org/repl?version=0.53.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuY29uc29sZS5sb2coJTIwY3ViZSglMjA1JTIwKSUyMCklM0IlMjAlMkYlMkYlMjAxMjUlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwRXllcyUyMGhlcmUhJTVDbiUyRiUyRiUyMFRoaXMlMjBwaWVjZSUyMG9mJTIwY29kZSUyMGlzbid0JTIwdXNlZCUyMGFueXdoZXJlJTJDJTIwYnV0JTIwc3RpbGwlMjBhcHBlYXJzJTIwb24lMjB0aGUlMjBidW5kbGUuJTVDbmNvbnN0JTIwVUlEJTIwJTNEJTIwTWF0aC5mbG9vcihNYXRoLnJhbmRvbSgpJTIwKiUyMDB4MTAwMDAwMDAwMDApLnRvU3RyaW5nKDE2KSU1Q25jb25zdCUyMGZvbyUyMCUzRCUyMCU1QjAlMkMxJTVELmZpbHRlcihCb29sZWFuKSU1Q25jb25zdCUyMGJhciUyMCUzRCUyMCg0MikudG9TdHJpbmcoKSU1Q25jb25zdCUyMGJheiUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJ3F1eCclNUNuY29uc3QlMjBpV29udEFwcGVhckluVGhlQnVuZGxlJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAnJTVFLSU1RSliJyU1Q25jb25zdCUyMHF1eFNwbGl0JTIwJTNEJTIwYmF6KCkuc3BsaXQoJycpJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBnZXRzJTIwaW5jbHVkZWQlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3QlMkYlMkYlMjByZXdyaXRlJTIwdGhpcyUyMGFzJTIwJTYwc3F1YXJlKCUyMHglMjApJTIwKiUyMHglNjAlNUNuJTVDdCUyRiUyRiUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zISU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE). Not sure if this is a feature or limitation, but anything with a chained function call, Rollup doesn't seem to strip away.

main.js
```js
import { cube } from './maths.js';
console.log( cube( 5 ) ); // 125
```

maths.js
```js
// Eyes here!
// This piece of code isn't used anywhere, but still appears on the bundle.
const UID = Math.floor(Math.random() * 0x10000000000).toString(16)
const foo = [0,1].filter(Boolean)
const bar = (42).toString()
const baz = () => 'qux'
const iWontAppearInTheBundle = () => '^-^)b'
const quxSplit = baz().split('')

// This function isn't used anywhere, so
// Rollup excludes it from the bundle...
export function square ( x ) {
	return x * x;
}

// This function gets included
export function cube ( x ) {
	// rewrite this as `square( x ) * x`
	// and see what happens!
	return x * x * x;
}
```

bundle
```js
'use strict';

// Eyes here!
// This piece of code isn't used anywhere, but still appears on the bundle.
const UID = Math.floor(Math.random() * 0x10000000000).toString(16);
const foo = [0,1].filter(Boolean);
const bar = (42).toString();
const baz = () => 'qux';
const quxSplit = baz().split('');

// This function isn't used anywhere, so
// Rollup excludes it from the bundle...


// This function gets included
function cube ( x ) {
	// rewrite this as `square( x ) * x`
	// and see what happens!
	return x * x * x;
}

console.log( cube( 5 ) ); // 125
```

**Comment by lukastaegert** [comment]
The problem is that this requires a serious improvement of the global variable handling as well as implementing handlers for known (String, Array, etc.) prototype methods. This is a known problem and actively worked on.

**Comment by guybedford** [comment]
All of these cases now work, only except for:

```js
const UID = Math.floor(Math.random() * 0x10000000000).toString(16)
```

I believe that is pending builtin global handling, which is being tracked.
