### ISSUE TITLE
treeshake build bug for not used empty function

### ISSUE THREAD

**Issue by soulcm** [rollup/rollup#1831]
follow my code below
```
class Test {
  constructor() {
      var testFn = function test(){}, //not used
          a = 'test';

      // testFn();
      console.log(a)
  }
}
export default Test
```
when I use rollup to build，I get this code
<img width="634" alt="dingtalk20180103195332" src="https://user-images.githubusercontent.com/5706155/34519616-cc125c44-f0bf-11e7-95e1-b717111b4eb6.png">

the function syntax is error, lack "{}" symbol, so will get error when run and uglify

below is my babel and rollup config

```
{
  "presets": [
    ["env", {
      "modules": false
    }]
  ],
  "plugins": [
    "external-helpers"
  ]
}

```

```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import replace from 'rollup-plugin-replace';

export default {
  input: 'src/index.js',
  output: {
    file: 'dist/dist.js',
    format: 'iife',
    name: 'Root'
  },
  plugins: [
    babel({
      exclude: 'node_modules/**',
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify('production'),
    }),
    resolve({
      jsnext: true,
      main: true,
      browser: true,
    }),
    commonjs()
  ]
};

```

**Comment by lukastaegert** [comment]
Thanks! This seems to be a bug with sequence expression rendering. Normally, functions with empty bodies will be removed but with sequence expressions, we sometimes do not remove some expressions to prevent other issues. The empty block statement, however, is removed.
I already plan on refactoring the sequence expression handling, this just stresses how important it is. It also lays open another issue with the rendering that I plan on working on soon.

**Comment by soulcm** [comment]
thanks, I want to konw when can fix this bug

**Comment by lukastaegert** [comment]
Unfortunately it will still take a little longer as it is coupled to reworking some core concepts of the rendering logic. Hope to be able to start working on it next week. Sorry to keep you waiting!

**Comment by ankeetmaini** [comment]
Can I help here? I've no context on the affected code path, so might take a
while to figure it out!

**Comment by lukastaegert** [comment]
There are several sides to this problem.
First of all, we need to figure out, why the declaration of `test` is not removed entirely. This is the smallest possible fix. This can probably found somewhere in the `VariableDeclaration`/`Declarator` nodes.

The larger side of things is that the entire rendering logic should be restructured to move the responsibility of not rendering a child from the child to the parent. But maybe you do not want to go for this yet. I have some ideas what should be done here. If you want, we can discuss this at some point.

**Comment by ankeetmaini** [comment]
Thanks, I'll go and try option #1. :)

**Comment by lukastaegert** [comment]
I have recently started refactoring the general rendering logic (i.e. option 2 above). There is no PR yet but it's happening on [refactor-treeshake-rendering](https://github.com/rollup/rollup/tree/refactor-treeshake-rendering) branch if you want to keep track.

There is a good chance I will get to this issue some time next week.
