### ISSUE TITLE
Code in module scope after code in exported function?

### ISSUE THREAD

**Issue by veltman** [rollup/rollup#1832]
This is more of a clarification question as I try to create a minimal reproduction of an issue I'm encountering. My understanding is that with a module like:

```js
console.log("A");

export function blah() {
  console.log("B");
}
```

"A" should always be logged once before "B" is ever logged, regardless of where else `blah()` is imported/called. Is this true? Or are there valid situations where the function would execute before the module-scope code? (I'm seeing this behavior in my bundle, depending on the order and location of imports)

**Comment by lukastaegert** [comment]
In fact this can happen if you have circular dependencies. To better understand this, note that `function` declarations are hoisted. Look at the following example:

https://rollupjs.org/repl?version=0.53.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGYS5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JiJTdEJTIwZnJvbSUyMCcuJTJGYi5qcyclNUNuJTVDbmNvbnNvbGUubG9nKCU1QyUyMkExJTVDJTIyKSUzQiU1Q25iKCklM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwYSgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMkEyJTVDJTIyKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCYSU3RCUyMGZyb20lMjAnLiUyRmEuanMnJTVDbiU1Q25jb25zb2xlLmxvZyglNUMlMjJCMSU1QyUyMiklM0IlNUNuYSgpJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGIoKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJCMiU1QyUyMiklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

As far as I know, the output is entirely correct. And to my knowledge in the case of circular dependencies, there is no guarantee in which order modules are run. For rollup's solution, the output will be `B1`, `A2`, `A1`, `B2`, i.e. `A1` and `A2` are flipped.

**Comment by veltman** [comment]
Got it - I can probably find the affecting circular dependency and eliminate it, or at least fold the module-scope statements into a function that will only execute once. Thank you for taking the time to explain!
