### ISSUE TITLE
Allowing options.format to be a function

### ISSUE THREAD

**Issue by keithamus** [rollup/rollup#1835]
Im trying to use Rollup in a project which includes a specific vendor bundle - this bundle needs to not do any treeshaking or rolling up, but it needs to do the transforms and resolving that the rest of the codebase does. Treeshaking is easy enough to disable - but sadly the existing finalisers arent quite right for this file. Right now rollup is restricted to only using the built in finalisers.

I propose allowing `format` option to be a function, which allows users to define their own finaliser. This way users (like me) can experiment with writing their own finalisers which fit needs not quite aligned to Rollup's core.

**Comment by lukastaegert** [comment]
Sounds interesting. Do you have suggestions for a specific API? For the existing (plugin) hooks, we always make sure to expose as little as possible of rollup's internals so that should be taken into account.

**Comment by keithamus** [comment]
The existing signature seems to work well - maybe with some bits omitted
```js
(Bundle, MagicStringBundle, { exportMode: string, indentString: string, intro: string, outro: string }, OutputOptions) => Promise<MagicStringBundle>
```

This itself is quite a low level hook - but the really foreign part is `MagicStringBundle` which has to be manipulated to maintain sourcemap compat, this seems like a reasonable tradeoff.

**Comment by guybedford** [comment]
I'd actually be against opening up the finalizer API.... rather if there are new module formats or finalizer options that we should support, that these should be merged into core. The API surface of finalizers is just not something that is versioned right now or that we'd want to version.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
