### ISSUE TITLE
bundling strips `if (true)` conditions (but not the statement)

### ISSUE THREAD

**Issue by sndrs** [rollup/rollup#1839]
this came up using the `replace` plugin to write code like:

```js
if (IS_DEV) {
    performance.mark('a thing happened')
}
```
during bundling, the plugin replaces `IS_DEV` with `true`, which rollup then converts to 

```js
{
    performance.mark('a thing happened')
}
```
maybe this is the wrong way to use the replace plugin and is expected? it caught me out though.

you can see a simple example [here on the repl](https://rollupjs.org/repl?version=0.53.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmlmJTIwKHRydWUpJTIwJTdCJTVDbiU1Q3RwZXJmb3JtYW5jZS5tYXJrKCdhJTIwdGhpbmclMjBoYXBwZW5lZCcpJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE).

**Comment by lukastaegert** [comment]
As far as I can see, this transformation is entirely correct. As the if-statement can be resolved, it is inlined. However to not have issues with variables that might be introduced inside the if statement (we do not check this explicitly), we leave the braces `{}` to introduce a block statement (yes, this is valid JavaScript!)

**Comment by sndrs** [comment]
i had no idea that

```js
{
    performance.mark('a thing happened')
}
```
is valid! rollup is much cleverer than me. closing

**Comment by lukastaegert** [comment]
😜

**Comment by sndrs** [comment]
oop - @lukastaegert just missed you comment, yeah just twigged that, sorry for the noise!
