### ISSUE TITLE
Bundling duplicate dependencies?

### ISSUE THREAD

**Issue by jlmakes** [rollup/rollup#1847]
Sorry if I'm missing something. I've got a project with dependency a graph like this:

```
├── is-dom-node@1.0.1
├─┬ is-dom-node-list@1.0.1
│ └── is-dom-node@1.0.1 (deduped)
```

Instead of `isDomNode` being bundled once, I'm getting both `isDomNode` and `isDomNode$2`.

https://github.com/jlmakes/rollup-repro

Am I doing something wrong?

**Comment by Andarist** [comment]
I **guess** it might be by design, your npm client has installed 2 copies of `is-dom-node` package and rollup just have resolved them both (like it should). It doesnt have power to know that those 2 are the same code.

**Comment by jlmakes** [comment]
> So the real question is - why do you have 2 copies of the same package in your node_modules?

Well `is-dom-node-list` currently depends on `is-dom-node` to function, but this particular project also had reason to use `is-dom-node` directly.

I can think of a few more examples where a project and/or its dependencies would call on the same module more than once... I wouldn't ever expect each instance of a module in a dependency graph to result in duplicate code (unless conflicting versions were imported).

> It doesnt have power to know that those 2 are the same code.

If that is true, this issue can be closed—and I'd love to know why that's the case.

**Comment by jlmakes** [comment]
> So the real question is - why do you have 2 copies of the same package in your node_modules?

Well `is-dom-node-list` currently depends on `is-dom-node` to function, but this particular project also had reason to use `is-dom-node` directly.

I can think of a few more examples where a project and/or its dependencies would call on the same module more than once... I wouldn't ever expect each instance of a module in a dependency graph to result in duplicate code (unless conflicting versions were imported).

> It doesnt have power to know that those 2 are the same code.

If this truly the case, I'd love to know why.

**Comment by Andarist** [comment]
> Well is-dom-node-list currently depends on is-dom-node to function, but this particular project also had reason to use is-dom-node directly.

Which version of npm do you use? Starting from npm3 it should produce a flat dep tree and those directories should be deduped to a single `node_modules/is-dom-node` if only they are compatible (by a semver rules)

> It doesnt have power to know that those 2 are the same code.

It would have to compare 2 files ASTs, which would be rather costly and unnecessary. It's a package manager's job to dedupe those files.

**Comment by jlmakes** [comment]
I use the latest, and the package has been deduped. Maybe it's that `rollup-plugin-node-resolve` is simply importing the code twice?

**Comment by jlmakes** [comment]
I use the latest, and the package has been deduped.
Maybe it's that `rollup-plugin-node-resolve` is simply importing the code twice?

**Comment by jlmakes** [comment]
I think I'm starting to understand the problem...

The `is-dom-node-list` package has already been bundled, so the `is-dom-node` dependency is wrapped up inside; consuming the `is-dom-node-list` package implies consuming its bundled dependency.

And so, if I independently choose to use the same dependency, it will have no awareness of the version inside `is-dom-node-list` and I get duplicate imports.

What about a generic package like `is-plain-obj`? Something like that could duplicated a dozen times within a code base...

Seems totes clunky, what am I missing?

**Comment by Andarist** [comment]
That's a reason to not use a bundled dependencies in your libraries. I **always** explicitly specify
```js
import pkg from './package.json'
// ....
external: [
  ...Object.keys(pkg.dependencies || {}),
  ...Object.keys(pkg.peerDependencies || {}),
]
```
for my cjs and es targets. For umd target I use a simpler
```js
external: [
  ...Object.keys(pkg.peerDependencies || {}),
]
```
and ofc have to specify `globals` then.

**Comment by jlmakes** [comment]
Hmm, so if I understand right, you're saying don't bundle dependencies—instead use peer dependencies, declare them with `rollup.config.external` and `rollup.config.globals`?

**Comment by Andarist** [comment]
Kinda, you can take a look at [example config](https://github.com/Andarist/react-flip-move/blob/08713c55019dfc395c23a837ec757a10de21f0dc/rollup.config.js) that I've prepared just recently - it's based on my personal "template" which i copy & paste (& tweak when necessary) at the moment in various projects.

**Comment by jlmakes** [comment]
I don't understand what I missed, that I'm supposed to gather from the example config, but I appreciate you trying to help.

I'm sure there are good reasons why, but it blows me away that you can't simply declare a module's dependencies and have them resolved with something akin to dependency injection to avoid duplication within the graph.

The irony is that I wanted to take the DOM code I tend to use across projects, and publish them as packages to avoid duplication when those projects are used together... and I've ended up with _more_ duplication than before.

I see now that until a dynamic `import` lands (and is used in published modules), there isn't a way to resolve duplicate dependencies throughout the entire dependency graph. Considering most modules are still CommonJS and dynamic import remains stage 3, I assume it'll be a long road until ES modules with dynamic imports are standard.

The answer appears to be: use peer dependencies and lean on the global namespace, or simply don't use dependencies that themselves have dependencies.

**Comment by Andarist** [comment]
> I see now that until dynamic import lands (and is used in published modules), there isn't a way to resolve duplication throughout the entire dependency graph.

I dont see how dynamic import could help for your case. The problems shows because you have bundled a library A into a library B and when rollup requests later a library C which in turn requests library A it cannot now, that it is actually already included, because you have already included library B. By bundling it into B you've lost its identity.

> The answer appears to be: use peer dependencies and lean on the global namespace, or simply don't use dependencies that themselves have dependencies.

From my point of view the answer is: do not bundle libraries into libraries, put your dependencies under dependencies key in package.json and let bundlers etc resolve them from your node_modules.

**Comment by jlmakes** [comment]
I've been messing around with more bundler settings, and I understand now:

When bundling an ES module, define dependencies as external in order to leave the `import` statement intact. (This is essentially what I had in mind when talking about dynamic imports, but without the need for a bundler.)

I think using `opts.external` on the ES build is what I'm looking for. Cheers!
