### ISSUE TITLE
Multiple Empty Lines in Combination with Babel

### ISSUE THREAD

**Issue by julmot** [rollup/rollup#1848]
Follow up of this ticket:

https://github.com/babel/babel/issues/7167

According to [this comment](https://github.com/babel/babel/issues/7167#issuecomment-355827524) it's an issue of rollup and not Babel. However, it only seems to appear when using rollup in combination with Babel.

Reproducable in [this branch](https://github.com/julmot/mark.js/tree/rollup) (can't say how long it'll be available), the output can be viewed here: https://github.com/julmot/mark.js/blob/67cabf70f6dda91d334fe1332c1512e20a5f7d61/dist/mark.js

Without digging into the code I can't say much about the background. However, non-minifed versions of compiled code is often provided as alternative to minified code, for better readability. Many empty lines are therefore not quite helpful.

**Comment by lukastaegert** [comment]
Hi @julmot , unfortunately this is a short-coming of the current way tree-shaking removes code. In short in its current iteration if a statement is removed, it is responsible for removing itself. This can leave unwanted whitespace between removed statements.
I hope to find some time soon to start reworking this to a state where the parent node is responsible for removing its children which should resolve this issue and make a lot of code a lot nicer.

**Comment by julmot** [comment]
Alright, thanks for the fast response and the explanation. Going to live with that and hope there'll be a solution if you have time. By the way: The whitespace also remains when you use the compact mode of babel. Using uglify for now.

Best,
Julian
