### ISSUE TITLE
Reassigning to another module exports causes "Cannot split a chunk" error

### ISSUE THREAD

**Issue by kirbysayshi** [rollup/rollup#1859]
This may not be the right repo to report this in, but I wanted to share in case someone else comes across this slightly weird situation / error.

Reproducible case: gist / repo: https://gist.github.com/kirbysayshi/6dad0368e4dde7ecac937f68e9a4b8bd

I'm using protobufjs, which generates an ESModule from a protobuf schema file. In the generated code, Protobufjs puts this: `const $root = $protobuf.roots["default"] || ($protobuf.roots["default"] = {});`

When that code is present, rollup throws the following error:

```
[!] Error: Cannot split a chunk that has already been edited (15:60 – "$protobuf.roots["default"]")
Error: Cannot split a chunk that has already been edited (15:60 – "$protobuf.roots["default"]")
    at MagicString$1._splitChunk (/private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:5250:10)
    at MagicString$1._split (/private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:5239:51)
    at MagicString$1.overwrite (/private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:5052:8)
    at Node.MemberExpression.render (/private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:13334:18)
    at /private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:11347:56
    at /private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:11215:17
    at Array.forEach (<anonymous>)
    at Node.eachChild (/private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:11207:19)
    at Node.render (/private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:11347:14)
    at Node.MemberExpression.render (/private/tmp/rollup-protobuf-testcase/node_modules/rollup/dist/rollup.js:13339:33)
```

If you remove the `|| ($protobuf.roots["default"] = {});`, rollup successfully bundles the code.

Protobufjs is doing something weird here, where within `protobufjs/src/roots.js` it's assigning `module.exports = {}`, and then in `protobufjs/src/index-minimal.js` re-exporting roots as a named export: `var protobuf = exports; protobuf.roots        = require("./roots");`.

While I know it's not allowed within ESModules to reassign or modify exports, I believe rollup should print an error that is _somewhat_ close to that, rather than the very mysterious  (at least to me) "Cannot split a chunk that has already been edited". It took me several hours to figure out where the problem actually was!

I'm hoping I can get around this using https://github.com/rollup/rollup-plugin-replace, as luckily I'm not using that `roots.default` functionality.

I guess I'm also reporting this because while protobufjs is probably at fault here for modifying exports after the fact, this is a pretty common thing in commonjs land. Maybe this helps someone else in the future.

Thanks for rollup!

**Comment by erickj** [comment]
@kirbysayshi did you resolve this? I'm having the same issue with protobufjs

**Comment by kirbysayshi** [comment]
@erickj Yes, I used the rollup-plugin-replace plugin ! I believe there were still some issues (rollup requires you to be very explicit with how it treats each dependency), but that plugin worked in general.

I think I configured it with `" || ($protobuf.roots["default"] = {})": ""`, which replaces the assignment with nothingness.

**Comment by LennyPenny** [comment]
@kirbysayshi @erickj can you give me a hint as to how to find code that triggers this error? 
I'm getting `[!] Error: Cannot split a chunk that has already been edited (0:120 – "graphql['default']")`, but searching my node_modules for `graphql['default']` doesn't yield any results :/

**Comment by erickj** [comment]
@LennyPenny sorry, I ended up giving up on this. After trying @kirbysayshi suggestion to use the replace plugin, I became stuck on a deeper error. After an hour or so of trying to figure it out I gave up.

Fortunately for me there was another option, albeit a bit backwards. protobufjs can produce cjs code, so I just reverted to that and used rollup to transpile it back to es modules. I lost some modularity, but I didn't really need it to begin with.

**Comment by kirbysayshi** [comment]
@LennyPenny maybe it's not the literal `graphql['default']`, maybe it's something like graphql reassigning the exports object, or assigning it twice. It could also be the transpiled code, if graphql ships as a transpiled bundle (looks like it does, maybe try importing the module version?). I don't know how rollup works internally, and so I don't really know what the error even means.

**Comment by guybedford** [comment]
@kirbysayshi does your replication still work here? If so, let's reopen and investigate further.

**Comment by kirbysayshi** [comment]
Yes. The original gist, even when updated with latest dependencies, still produces the error!

**Comment by gaberudy** [comment]
I traced this back to the code generated in rollup-plugin-commonjs in this issue:

https://github.com/rollup/rollup-plugin-commonjs/issues/308

It's not clear to me where the bug is, as the code generated there seems perfectly valid, but fails to be rendered in the rollup engine. Also, my "work-around" is to manually patch rollup-plugin-commonjs:

node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:765 change to:
```
					{ return ("import * as " + name$1 + " from " + (JSON.stringify( actualId$1 )) + "; export default " + name$1 + ";"); }
```
(i.e. the same as the else if...)

**Comment by gaberudy** [comment]
I actually now believe this may be a bug in magicstring, from doing a node inspect deep dive into the error

![image](https://user-images.githubusercontent.com/872263/38041990-61b7fdca-3270-11e8-8167-bd12fc3f224b.png)

Essentially, the MagicString sets the content to `"undefined"` but it's _splitChunk function is checking its length as a sentinal that things have gone wrong. Somewhere magicstring (or rollup?) assigning `content` accidentally (javascript coercion). Rollup may be able to update it's guard (here is the rollup code that calls into magicstring before the error):

![image](https://user-images.githubusercontent.com/872263/38042647-275a74bc-3272-11e8-9270-2c46e5318b6d.png)

But it seems like the real fix should be in magicstring (maybe revert to older magicstring dependency?)

**Comment by guybedford** [comment]
I just tried the replication in https://github.com/rollup/rollup/issues/1859#issue-287263963 against master and it seems to be working for me actually.

**Comment by guybedford** [comment]
Given I couldn't reproduce, can we get a confirmation again if this is still an issue?

**Comment by acoreyj** [comment]
I used to have to apply the workaround @gaberudy gave but it doesn't seem I need to anymore so I think it is fixed

**Comment by guybedford** [comment]
@acoreyj thanks for the update. Will close for now, but if this comes up again please do reopen.
