### ISSUE TITLE
Warn about potential minification issues?

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#186]
An interesting case with UglifyJS – if you use `eval` or `with`, the containing scope's variable names can't be mangled. Since Rollup puts every module in a single scope, it's much more likely that mangling will fail for the top level of an entire bundle, meaning that a minified Rollup bundle ends up *larger* than the equivalent Browserify bundle, despite there being less code. (Gzipping goes some way to alleviating this, but not all the way.)

Do we try and catch and deal with those cases somehow? E.g. warn, or wrap everything (except declarations) in an IIFE if a module contains a top-level `eval` or `with`? My thinking is that most people wouldn't investigate too deeply before concluding that Rollup was just less efficient than Browserify or Webpack.

Via https://github.com/mishoo/UglifyJS2/issues/830#issuecomment-147870241

**Comment by kzc** [comment]
It would be pretty straightforward to add such a warning in `uglifyjs` when `eval()` or `with` is encountered when mangling is enabled.

I think the Rollup project should be made aware of this issue as it could be fairly common. Perhaps they can perform some code transforms on their end to avoid this situation in some cases. i.e., don't hoist a function from a module in certain cases.

**Comment by kzc** [comment]
Sorry - I mistakenly thought this was a post to the UglifyJS2 project.

**Comment by Rich-Harris** [comment]
@kzc not at all! thank you for clarifying the issue.

I actually misunderstood the problem before – wrapping the `eval`-containing module in an IIFE wouldn't help, because the `eval` 'infects' all the parent scopes – instead, we'd need to wrap all the *other* modules to make them minifiable. Which makes that approach less appealing.

So, warning the user is probably a better solution.
