### ISSUE TITLE
TypeScript compilation errors

### ISSUE THREAD

**Issue by KingHenne** [rollup/rollup#1862]
First of all, thanks a lot for the effort that went into #1806! ❤️

Unfortunately this broke integration of Rollup into other TypeScript projects. These are the compiler errors I'm seeing in a [minimal example project](https://github.com/KingHenne/rollup-ts-example):

```
node_modules/rollup/dist/typings/Module.d.ts(1,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/Module.d.ts(5,30): error TS2307: Cannot find module 'source-map'.
node_modules/rollup/dist/typings/Module.d.ts(84,9): error TS2411: Property ''*'' of type 'NamespaceVariable | undefined' is not assignable to string index type 'Variable'.
node_modules/rollup/dist/typings/ast/nodes/BlockStatement.d.ts(3,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/ClassDeclaration.d.ts(4,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/ExportDefaultDeclaration.d.ts(5,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/FunctionDeclaration.d.ts(3,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/Identifier.d.ts(6,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/Property.d.ts(5,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/TemplateLiteral.d.ts(2,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/shared/Node.d.ts(4,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/shared/Statement.d.ts(2,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/node-entry.d.ts(5,36): error TS2307: Cannot find module 'package.json'.
node_modules/rollup/dist/typings/rollup/index.d.ts(3,30): error TS2307: Cannot find module 'source-map'.
node_modules/rollup/dist/typings/rollup/index.d.ts(5,27): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/rollup/index.d.ts(18,69): error TS2304: Cannot find name 'Node'.
node_modules/rollup/dist/typings/utils/mergeOptions.d.ts(1,32): error TS2307: Cannot find module '../../src/rollup/index'.
node_modules/rollup/dist/typings/watch/index.d.ts(2,30): error TS2307: Cannot find module 'chokidar'.
```

**Comment by KingHenne** [comment]
Obviously the `Cannot find module` errors could be prevented by a consuming project by installing typings from `@types`. They are only available for `source-map` and `chokidar` though, not for `magic-string`. Also, `Cannot find name 'Node'` can be resolved by adding the `dom` lib in the compiler options. So the remaining issues are:

```
node_modules/rollup/dist/typings/Module.d.ts(1,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/Module.d.ts(84,9): error TS2411: Property ''*'' of type 'NamespaceVariable | undefined' is not assignable to string index type 'Variable'.
node_modules/rollup/dist/typings/ast/nodes/BlockStatement.d.ts(3,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/ClassDeclaration.d.ts(4,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/ExportDefaultDeclaration.d.ts(5,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/FunctionDeclaration.d.ts(3,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/Identifier.d.ts(6,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/Property.d.ts(5,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/TemplateLiteral.d.ts(2,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/shared/Node.d.ts(4,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/ast/nodes/shared/Statement.d.ts(2,25): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/node-entry.d.ts(5,36): error TS2307: Cannot find module 'package.json'.
node_modules/rollup/dist/typings/rollup/index.d.ts(5,27): error TS2307: Cannot find module 'magic-string'.
node_modules/rollup/dist/typings/utils/mergeOptions.d.ts(1,32): error TS2307: Cannot find module '../../src/rollup/index'.
```

**Comment by KingHenne** [comment]
I'm wondering wether `@types/source-map` and `@types/chokidar` should be listed as dependencies?

**Comment by guybedford** [comment]
This is why I think it would be better just to create a custom Rollup.d.ts
and ship that (potentially then using this in the internal type imports)

The interface is pretty trivial to describe... it’s not a large surface
area. And exposing all this internal typing seems plain wrong.

**Comment by KingHenne** [comment]
I disagree, that is not common at all in TS projects that are libraries. 

—
mobil

**Comment by lukastaegert** [comment]
> Also, Cannot find name 'Node' can be resolved by adding the dom lib in the compiler options

Unfortunately this is most probably the wrong `Node`; the right one is https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/Node.ts.

Will take a look at #1864 later. As for @guybedford's comment: When we did the conversion earlier, we never considered the types to be used publicly as this was not the problem we were trying to solve. Thus the few types that actually make sense to be used publicly are far too generic. See my comment here: https://github.com/rollup/rollup/pull/1837#issuecomment-356523806

But I see the advantages of maintaining these option types in rollup itself as for TypeScript users, deprecations etc. will always be up to date with the rollup version they actually use.

Unfortunately I do not see I will find the time to wrap my head around improving this any time soon but if someone from the community feels up to this, please let me know! I will certainly try to support you with this!

also cc @alan-agius4

**Comment by alan-agius4** [comment]
I think those who are having error might not have `skipLibCheck: true` flag in `tsconfig.json`

I'll try to look at this soon. And will also review #1864

**Comment by alan-agius4** [comment]
The main problem with `magic-string` and `source-map` is that `rollup` inlines the libraries and are not marked as dependencies.

**Comment by KingHenne** [comment]
> The main problem with magic-string and source-map is that rollup inlines the libraries and are not marked as dependencies.

Yes, that is unfortunate (for this scenario) and means you have to manually install `@types/source-map`, `magic-string` and also `@types/chokidar` as devDependency as mentioned in #1864. At least I'm not aware of another fix.

**Comment by alan-agius4** [comment]
@KingHenne just a small correction you don't need to install `@types/source-map` this is a stub and one should install the actual `source-map` library.

So for TS users without `skipLibCheck`  you'd need to install
```
@types/chokidar
source-map
magic-string
```
