### ISSUE TITLE
Submit Rollup to Open Collective

### ISSUE THREAD

**Issue by spencer-brown** [rollup/rollup#1865]
It would be great to see Rollup on opencollective.com so people can financially support this great project! [We](https://github.com/mixmaxhq/) use Rollup in all of our projects and would love to support y'all. You could add a section to the readme like https://github.com/webpack/webpack#premium-partners that invites people/companies to help fund development.

**Comment by Rich-Harris** [comment]
Wow, this is timely! I actually set up https://opencollective.com/rollup earlier this week, and am planning to write a blog post in the next couple of days with a proper announcement and an explanation of our plans.

Thank you so much for your support!

**Comment by spencer-brown** [comment]
Whoo! Awesome.

**Comment by spencer-brown** [comment]
@Rich-Harris check https://opencollective.com/rollup#organizations :)

**Comment by bradvogel** [comment]
Thanks! Would love a re-tweet on https://twitter.com/BradVogel/status/951627647452246016 from @RollupJS :)

**Comment by Rich-Harris** [comment]
Most certainly! You guys rock! 🤘
