### ISSUE TITLE
Changed export names after 0.54.0 update

### ISSUE THREAD

**Issue by julmot** [rollup/rollup#1870]
Previous to 0.54.0, when there were name conflicts, a `$` sign was added to the first conflicting thing. Now it's added to the last conflicting thing.

So, after updating to 0.54.0 these are the changes in [mark.js](https://github.com/julmot/mark.js):
![topic](https://user-images.githubusercontent.com/8310677/34864862-889098a6-f776-11e7-898d-88d0accf4ef0.png)

Since I couldn't find an information in the CHANGELOG about this, I was thinking maybe this isn't as intended? Actually I liked the naming before 0.54.0 much more, since now an ugly name is exported.

[REPL](https://rollupjs.org/repl?version=0.54.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyME1hcmtKUyUyMGZyb20lMjAnLiUyRm1hcmsuanMnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyME1hcmsoY3R4KSU3QiU1Q24lMjAlMjBjb25zdCUyMGluc3RhbmNlJTIwJTNEJTIwbmV3JTIwTWFya0pTKGN0eCklM0IlNUNuJTIwJTIwdGhpcy5tYXJrJTIwJTNEJTIwKHN2JTJDJTIwb3B0KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpbnN0YW5jZS5tYXJrKHN2JTJDJTIwb3B0KSUzQiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjB0aGlzJTNCJTVDbiUyMCUyMCU3RCUzQiU1Q24lMjAlMjByZXR1cm4lMjB0aGlzJTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXJrLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyME1hcmslN0IlNUNuJTIwJTIwY29uc3RydWN0b3IoY3R4KSU3QiU1Q24lNUN0JTIwJTIwJTJGJTJGJTIwZG8lMjBzb21ldGhpbmcuLi4lNUNuJTVDdCU3RCU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by lukastaegert** [comment]
I think the nicest way would probably to lock the names of (default or not) exported variables first before deconflicting the remaining variables. This could also solve #1682 and certainly make our output nicer for the casual user. What do you think, @guybedford?

**Comment by guybedford** [comment]
@lukastaegert definitely agree with your proposed fix, that sounds like a reliable way to get this feature regardless of orderings.

**Comment by bdwain** [comment]
Are there any plans to implement this? I'd be happy to help, though I don't know much about rollup's source yet so I may need some guidance. 

I'm mostly just looking to solve #1682, because I'm still using the hacky plugin I wrote a year and a half ago and I'm worried it's going to break one day.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
