### ISSUE TITLE
rollup 0.52.1 cannot parse tagged template strings in 'rollup.config.js'

### ISSUE THREAD

**Issue by feross** [rollup/rollup#1875]
It looks like rollup 0.52.1 started parsing the `rollup.config.js` file with buble (in this PR https://github.com/rollup/rollup/pull/1759). This breaks my config which is using a tagged template string. Apparently buble does not support these.

```
[!] (buble plugin) CompileError: Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip transformation and disable this error, or `transforms: { dangerousTaggedTemplateString: true }` if you know what you're doing (40:10)
rollup.config.js (40:10)
36 :       externalHelpers: true
37 :     }),
38 :     commonjs()
39 :   ],
40 :   banner: stripIndent`
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The PR where this was introduced is https://github.com/rollup/rollup/pull/1759 which was adding support for object rest/spread. Is it possible to support object rest/spread without breaking other features already supported by modern Node runtimes? Or am I doing something wrong?

**Comment by lukastaegert** [comment]
Should be fixed now

**Comment by feross** [comment]
👏
