### ISSUE TITLE
Can I generate two files in one time that one is compiled with babel and another not?

### ISSUE THREAD

**Issue by LvChengbin** [rollup/rollup#1877]
I don't know if I can ask questions here. I want to compile my code to two different versions, one of them is compiled with the plugin `rullup-plugin-babel` and another one should not use this plugin. Can I can implement this in a simple way and what shall I do with the `rollup.config.js`?

**Comment by Rich-Harris** [comment]
You can export an array of configs from rollup.config.js:

```js
// rollup.config.js
import babel from 'rollup-plugin-babel';

export default [
  {
    input: 'src/main.js',
    output: { file: 'dist/untranspiled.js', format: 'cjs' }
  },
  {
    input: 'src/main.js',
    output: { file: 'dist/transpiled.js', format: 'cjs' },
    plugins: [
      babel()
    ]
  }
];
```

It's better if you can ask questions on StackOverflow rather than here, since more people will see it that way, and the answer will be easier to find for other people.

**Comment by LvChengbin** [comment]
@Rich-Harris Thank you so much.
