### ISSUE TITLE
No console output when using rollup.rollup (JS API)

### ISSUE THREAD

**Issue by nikolay-borzov** [rollup/rollup#1885]
Is it intentional? I'd expect the same output as CLI produces.

Repo to reproduce https://github.com/nikolay-borzov/rollup-js-api-test

JavaScript API:
```bash
npm run build 
```
CLI:
```bash
npm run build-cli
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by balthild** [comment]
Hello! Could you please reopen this issue? I'm still encountering same problem on rollup v4.35.0. The `logLevel` option is set to `info` but it doesn't work.
