### ISSUE TITLE
Tree-Shaking not work for ts with extends class

### ISSUE THREAD

**Issue by xsbchen** [rollup/rollup#1890]
Repo to reproduce https://github.com/xsbchen/rollup-tree-shaking

```js
function __extends(d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
}

var A = (function () {
    function A() {
    }
    return A;
}());
var B = (function () {
    function B() {
    }
    return B;
}());
var C = (function (_super) {
    __extends(C, _super);
    function C() {
        _super.apply(this, arguments);
    }
    return C;
}(A));

var a = new B();
console.log(a);
```

Class A and C should be removed?

**Comment by lukastaegert** [comment]
At first glance there are two things that rollup will struggle with for now: `Object.create`, which does not yet have a defined return type in rollup, and the use of `.apply() `. Between other things I am actually kind of working on this so there might be an update soon.

**Comment by kzc** [comment]
dup of #1763

**Comment by lukastaegert** [comment]
Agreed. But the example given here makes for a very nice test case. 👍

**Comment by csvn** [comment]
This specific case seems to be part of the reason why the code below becomes ~230 KB when using `rxjs` (6.0.0-alpha.2). 

```typescript
import { from } from 'rxjs/create';

from([1, 2, 3]).subscribe(v => console.log(v));
```

Most of their operators looks like this:
```typescript
import { Subscriber } from '...';

// can be tree-shaken
export function debounceTime<T>(...) { ... }

// can be tree-shaken
class DebounceTimeOperator<T> implements Operator<T, T> { ... }

// used only by `debounceTime`, though cannot be tree-shaken
class DebounceTimeSubscriber<T> extends Subscriber<T> { ... }
```

The compiled code looks something like this:
```javascript
var DebounceTimeSubscriber = /*@__PURE__*/ (/*@__PURE__*/ function (_super) {
    __extends(C, _super);
    function DebounceTimeSubscriber() {
        _super.apply(this, arguments);
    }
    return DebounceTimeSubscriber;
}(Subscriber ));
```

Not sure if `@__PURE__` is some kind of standard, but in some cases it might be used to remove code marked with it as in the tree-shaking.

**Comment by kzc** [comment]
> Not sure if `/*@__PURE__*/` is some kind of standard, but in some cases it might be used to remove code marked with it as in the tree-shaking.

Uglify removes such pure annotated calls if not referenced.

https://github.com/rollup/rollup/issues/1763#issuecomment-347272579

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
