### ISSUE TITLE
Is there a way to create a bundle without any export at the end

### ISSUE THREAD

**Issue by GrosSacASac** [rollup/rollup#1893]
Feature request:
I would like to create a self contained es bundle without export at the end. Using es modules as bundle target (es).

Repro (I tried to share URL from repl but it seems to not keep changes)
```
// main.js
/* main is entry module 
x, y are exported because many other modules need read access 
they are a bit like global variables but explicit */

import { printState } from './maths.js';
export {x,y};

let x = 0;
let y = 1;
console.log( printState() );
// sometimes x, y changes only here
x = 25;
y = 30;
console.log( printState() );  
```
```
// maths.js
import { x,y } from './main.js';
export {printState};

const printState = function  (  ) {
	return "x: " + x + "y: " + y;
};
```

Result 
```

const printState = function  (  ) {
	return "x: " + x + "y: " + y;
};

/* main is entry module 
x, y are exported because many other modules need read access 
they are a bit like global variables but explicit */

let x = 0;
let y = 1;
console.log( printState() );
// sometimes x, y changes only here
x = 25;
y = 30;
console.log( printState() );

export { x, y };
```

Expected: So what I would like is an option to omit `export { x, y };` at the end
Option could be called `independent `or `no-export` or `self-sufficient` ...

Thanks for awesome rollup !

**Comment by TrySound** [comment]
@GrosSacASac Just don't export anything. You don't need an option for that.

**Comment by lukastaegert** [comment]
I agree with @TrySound here. @GrosSacASac Could you explain what you expect to gain from this? From an executional perspective, an ES module with exports is very much self-contained. You can try it out in e.g. latest Node, an ES module with exports is perfectly executable on its own. It's the unresolved and external imports that break the self-contained-ness. And this cannot be solved by a simple flag. Still, rollup already provides you with various means (warnings, plugin interface, ...) to detect and fix this.

**Comment by GrosSacASac** [comment]
I know it works, I would like to make file size smaller. What is the plugin interface to use ?

**Comment by guybedford** [comment]
@GrosSacASac you could always create a custom entry point here that has no exports that simply imports the existing entry point. Would be simpler than a new option for this sort of thing I think.

Closing, but happy to continue discussion.

**Comment by jpsilva** [comment]
> you could always create a custom entry point here that has no exports that simply imports the existing entry point.

I tried that, but it doesn't work. Without an export, rollup just ignores the code completely, as it should with tree shaking. I'm trying to export my JS in a way that iOS's JavaScriptCore can easily consume, and it doesn't seem to like exports in the code.

**Comment by lukastaegert** [comment]
But if it does not have side-effects, what is the point of running the code except heating the processor? If the side-effect is e.g. setting some globals, then all relevant code for this will be retained as modifying globals is a side-effect. However if you are exporting as ES modules, you need to make sure that your globals are directly declared on the global object and not via `var`, as this does not create global variables. If you want to avoid this, the IIFE format is your friend.

**Comment by jpsilva** [comment]
Thanks, @lukastaegert. IIFE worked for me. I'm not used that format, coming from a browserify/webpack world where globals are considered bad. But in this case, that's just what I needed, and probably what the OP needs as well.

**Comment by OpenA** [comment]
just another useless js bundler

**Comment by mtone** [comment]
I've had the same need to run code for use on the MS Dynamics 365 SAAS platform.

In this use case, various JS files can be hosted and must expose plain functions that the platform calls in contexts it manages. So it is not intended to be executable on its own and it doesn't like exports. Otherwise the Rollup output is perfect for that use case: clean, simple, tree-shaken JS developed in modular TS. 

My solution was to add a small rollup plugin that comments out the export line. Stupid but has been working great for >1 year.

Here's my rollup config [gist](https://gist.github.com/mtone/c7cb55aaaa2c2702d7b1861d7e2fdbd8).

**Comment by TrySound** [comment]
@mtone What's wrong with using iife instead?

**Comment by mtone** [comment]
@TrySound Actually, that does work: by changing outputOptions format "cjs" to "iife" & setting an outputName.

I think I didn't realize back then that we could configure the app to execute outputName.functionName vs only functionName.

Thanks for making me re-look into it!
