### ISSUE TITLE
[Question] why not node resolve as default ?

### ISSUE THREAD

**Issue by lorenzofox3** [rollup/rollup#1895]
Hi, I was just wondering why rollup does not use rollup-plugin-node-resolve as default ?

Most of the time, dependencies are npm modules. By allowing node resolve by default, one could directly use the command line interface. I end up on every single project adding a config file simply to call the plugin. 
This behaviour could be discarded of course when providing a configuration file.
I am probably missing something though, but I have not figured it out what at the light of the others issues.

**Comment by Rich-Harris** [comment]
See my response to this question here! https://github.com/rollup/rollup/issues/1555#issuecomment-322862209

**Comment by lorenzofox3** [comment]
thanks and sorry for the duplicate.

**Comment by lorenzofox3** [comment]
quick question though. Would you have this behavior included as a command line flag. I don't think it would cause any trouble to the points you have mentioned in your comment. 
On the other hand I realize that adding more and more option flags make the cli more complex...

**Comment by lukastaegert** [comment]
I think this is also related to #1894.

Personally, I am not totally against e.g. an `--npm` option that basically pulls in ALL necessary plugins to gain full npm compatibility, e.g. `node-resolve`, `common-js`, `json`, .... It's all plugins that are part of the rollup organisation anyway. Would be a tremendous help for newcomers.

Just a little afraid of the maintenance 😳

**Comment by lorenzofox3** [comment]
I don't think you have to go that far. 
Here is my use case (pretty common ?)

my code source is a library which requires a dependency:
1. This dependency is hosted on npm and is a good citizen: the `package.json` file includes a `module` property which points to a `my-dep.mjs` (ES export), a `main` property which points to a CJS version of it and even a `js:next` which points directly to the entry point of the source code (in ES module format)

2. For testing purpose I import my lib
src/index.js
```Javascript
import {square} from 'my-dep';

export default (input) => square(square(input)); 
```
test/index.js
```Javascript
import superSquare from '../src/index.js';

//do something related to test
```
I can easily test in nodejs by running the command:

`rollup -f cjs ./test/index.js | node`

No problem rollup produces a module whose dependencies are called with `require` so node  is able to resolve everything.

Now however I want to create a file from the test to drop in the browser

`rollup -f iife ./test/index.js > debug.js`

The problem is debug.js will treat my-dep as an external dependency comming from a global and won't be present in debug.js.

So I end up with the config file 
```Javascript
import node from 'rollup-plugin-node-resolve';

export default {
    input:'./test/index.js',
    plugins:[node()],
    output:{
       format:'iife',
       name:'test'
    }
}
```

And `rollup -c ./rollup/test.js > debug.js` works as expected. 

All I needed was not something fancy. Just a call to node resolve with its default params so I can create a bundle including its dependencies

I understand that might be more complicated if the dependencies has its own tree etc. But this can be covered it the plugin as it is now.

**Comment by kzc** [comment]
There are some node resolve-isms in Rollup core already - "realpath" symlinking - brought to light by #1819.

**Comment by guybedford** [comment]
+1 to a "resolver": "npm" or similar option acting like a default plugin "preset" in Babel terms.

**Comment by kzc** [comment]
+1 to the idea of a built in node resolve option in Rollup core. Whether it would be enabled by default is a matter of discussion.

-1 on the flag name `--npm`. 

`--node-resolve` perhaps?

**Comment by lorenzofox3** [comment]
Actually an another approach (which would help on other fronts) could be as the babel cli do, to pass plugins as a command line parameters (or presets). Then if you need to pass parameters to these plugins you could simply go back to the config file

`rollup -f iife -n whaterver --plugins=node-resolve ./entrypoint.js`

**Comment by lukastaegert** [comment]
@kzc You are right, `--node` is much better, not sure what I had in my mind...

@lorenzofox3 Your suggestion could be useful as well and could work along a `--node` option just nicely. Only thing to note is that it will either be impossible to pass options to plugins via the CLI or will require some serious work on the CLI interface which I would dread a little. Not sure if this is an important issue, though.

The longer I think about it, the more I like the preset (e.g. `--preset node`) approach. Besides the obvious case discussed above this would enable others to post presets for more complicated cases, e.g. a react or angular preset or similar ones. Now we just need to find a good API.

**Comment by lorenzofox3** [comment]
Yes that was the idea. I see more ``--plugins=foo,bar,bim`` as a convenience. If one needs to pass params to the plugins it should rather use the config files way

**Comment by David-Else** [comment]
@lukastaegert I would love to see a `--node` option to include all necessary plugins to gain full npm compatibility!

**Comment by shellscape** [comment]
Adding ESLint-style `extends` functionality to the configs would also solve this, similar to @guybedford 's comment above.

```js
{
  extends: 'node'
  ...
}
```

Which would then look for and apply `rollup-config-node` or some such, with plugins needed for npm compat. This has been on my list of things to do for the project, but there are nuances that I'm still investigating.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
