### ISSUE TITLE
external function

### ISSUE THREAD

**Issue by sakitam-fdd** [rollup/rollup#1901]
Hi, I was just wondering why rollup does not use external function same as webpack?
```javascript
externals: [
  function(context, request, callback) {
    if (/^yourregex$/.test(request)){
      return callback(null, 'commonjs ' + request);
    }
    callback();
  }
]
```

**Comment by gewentao** [comment]
also need something like external function in webpack, have you figured out how to resolve this issue (maybe some plugins) ?  @sakitam-fdd

**Comment by sakitam-fdd** [comment]
@gewentao Hi, No solution has been found yet, Because of my relatively rare needs ~ I want to go compatible `ES6` moudle and `commonjs` moudle.
``` javascript
function (context, request, callback) {
  if (/^(ol\/|openlayers\/)\S*$/.test(request)) {
    if (/^(ol\/map|openlayers\/map)$/.test(request)) {
      return callback(null, 'root ' + 'ol.Map')
    }
  }
  callback();
}
```

**Comment by guybedford** [comment]
`options.external` is supported as a function fine in Rollup. Feel free to discuss further if this isn't working for you.
