### ISSUE TITLE
Imports in different files not being deconflicted

### ISSUE THREAD

**Issue by bdwain** [rollup/rollup#1913]
This issue may be the same issue as #1910, but I'm not sure because the example there seemed fixed in the REPL, and my example is not.

I can't seem to generate a url in the REPL that has my buggy code in it, but here is the example

main.js
```js
import foo from 'foo.json';
import './stuff';

console.log(foo);
```

stuff.js
```js
import foo from 'foo';
console.log(foo);
```

generated output:
```js
import foo from 'foo';
import foo from 'foo.json';

console.log(foo);

console.log(foo);
```

**Comment by guybedford** [comment]
Thanks, I've just checked and this is fixed in 0.55.1.
