### ISSUE TITLE
Prefer esm over es format name

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#1917]
es6 is confusing name which can be considered as just non transpilled code. We leave from it in rollup, however its es did not became better IMO. Currently there're a tool like esm-loader and webpack beta uses esm name.

Also I saw node consider it /cc @guybedford 

It could be an alias, but I'd like to replace it with "deprecation" major and then "removing" major.

**Comment by guybedford** [comment]
+1 to supporting `esm` as an alias for `es`.

As opposed to making it preferred or default, I wouldn't rush into that.
