### ISSUE TITLE
code splitting rollup first try, PropTypes doesn't import 

### ISSUE THREAD

**Issue by MichaelRando** [rollup/rollup#1918]
My repro repo is: https://github.com/MichaelRando/rollup-codesplitting-demo

I observe that the PropTypes work as React.PropTypes, but my existing codebase expects the symbols available on PropTypes. Is this a commonjs issue?

If you run the demo, it works but you get 
```
Uncaught (in promise) Error: Cannot read property 'oneOfType' of undefined
  Evaluating http://127.0.0.1:1080/App.js
  Loading App.js
    at Object.execute (App.js:21)
    at j (system-production.js:4)
    at R (system-production.js:4)
    at E (system-production.js:4)
    at system-production.js:4
    at <anonymous>
```
on the console.

**Comment by guybedford** [comment]
Thanks for trying it out and posting a report.

Just to note, you'll get a much faster response and fix if you can try to isolate exactly what is being output, and where you think the problem might be - eg removing parts of the example that are superfluous to the bug is a start. The other thing is that as a maintainer, cloning a repo can be both a security hazard and much more work than looking at either a REPL replication, or a simplified explanation of the exact issue if you're able to trace it down.

Will aim to investigate when I can, but thought I'd mention the points above if you're looking to move faster here.

**Comment by MichaelRando** [comment]
I don’t think that REPL env is set up for this test. And it’s a good repo, I trimmed it well. re more information: the PropTypes symbol lofts into chunk1, gets named propTypes, but is undefined in scope where proptypes are instantiated. I also had trouble getting react/preact symbols into scope; couldn’t use the es module version for some reason...

**Comment by guybedford** [comment]
@MichaelRando I can confirm there is a bug here of some sort, as the ES ouput works with this binding while the system output doesn't. So there may be something in the sytem module format going on here.

I wasn't able to trace it further than that though within 15 mins so have to call it a day here. Will get back to this in two weeks.

**Comment by MichaelRando** [comment]
@guybedford Thank you

**Comment by lukeed** [comment]
I've had similar issues. Essentially, I can take a working, single-bundle Preact app that is built with Rollup, then add additional `inputs` and/or turn on the new `experiement*` flags and the build fails to compile.

1. JSX parsing is lost

    The Bable/Buble config doesn't carry over & so I think Acorn is trying to parse `<Foobar/>` directly

2. Any `import()`s inside the components will throw.

    This is only solved by adding the appropriate Babel/Buble `dynamic-import-syntax` add-on so that _it_ can understand the syntax. Though, unfortunately, this means that Babel/Buble is handling & transforming the `import()` rather than letting Rollup do it.

**Comment by guybedford** [comment]
@lukeed you may benefit from following the example in this issue to see how to combine plugins with these workflows. Please do try to create clear separate issues for the isolated issues you are having.

@MichaelRando I managed to track this down to a bug in the commonjs rollup plugin, and have created an issue for this at https://github.com/rollup/rollup-plugin-commonjs/issues/286.

**Comment by guybedford** [comment]
Sorry, I did close this prematurely - tracking duplicate in https://github.com/rollup/rollup/issues/1968, should hopefully have a fix soon.
