### ISSUE TITLE
Executing rollup -w in parallel via lerna does not watch

### ISSUE THREAD

**Issue by schneidmaster** [rollup/rollup#1919]
I've got a project that uses lerna with a `rollup.config.js` in each of the package directories. Each package has a `watch` script with `rollup -c -w`. If I cd to the package directory and directly run `npm run watch` it works as expected.

However, if I run `lerna run --parallel --stream watch` from the root (thus running `npm run watch` in parallel in each package directory), rollup will build the source code once and then the process will exit, rather than staying alive and waiting for source code changes.

I believe this is a problem with rollup (rather than lerna) because babel's watch mode works perfectly under the same conditions (so it's not like lerna is killing the processes or something).

I've hunted through existing issues and documentation and I'm out of things to try. Am I missing something or is there a bug here?

Thanks!

[Simplified reproduction repo, including babel counterexample](https://github.com/schneidmaster/lerna-rollup-watch)

**Comment by trescenzi** [comment]
This has to do with the fact that the watcher is closed when `stdin` ends the first time. The call that's ending the watch is [here](https://github.com/rollup/rollup/blob/master/bin/src/run/watch.ts#L123). Because it's being run by a lerna, and not within a terminal, it's not waiting around. It's seemingly intentional because code was written to handle this case and close the watcher but I don't know the reasoning behind it. Commenting it out however doesn't seem to cause issues but that's only after playing around with it for a few min so it might.

This might be applicable for this to be a feature request. Something like `Allow execution of rollup -w outside of a TTY`?

**Comment by icedream** [comment]
I just got bitten by this and was surprised to see the behavior of `-w` is dependent on whether Rollup is running inside a TTY.

**Comment by Alxandr** [comment]
As a workaround, I've set up a single rollup so I can watch everything (instead of running rollup in parallel). It can be seen here: https://github.com/YoloDev/aspnet-node-utils/blob/master/rollup.config.js

I'm working on a script where the names don't have to be listed (mostly finished).

**Comment by schneidmaster** [comment]
I implemented a similar workaround for Slate, for what it's worth. Can be seen [here](https://github.com/ianstormtaylor/slate/tree/master/support/rollup) -- `factory.js` produces a rollup config for a package, `config.js` uses the factory to create a single array of configs for all the packages.

**Comment by rbalicki2** [comment]
🙌  I had this problem too, and it was driving me nuts.

I implemented a similar solution. gist here: https://gist.github.com/rbalicki2/60dbecaddb14f7a3625c118f28158c86

Unfortunately, even though I am concatenating the rollup config's, they roll up out of order, and I get many false alarms (this or that file cannot be found, and the like).

Is there a fork of rollup that does not require watch to be run in a TTY?

**Comment by bennypowers** [comment]
I only have one package that uses rollup. Do I need to instruct my collaborators to run `rollup -w` separately from `lerna run watch`?

**Comment by kirill-konshin** [comment]
@bennypowers Use `rollup-no-tty-check` package by @rbalicki2 as replacement. Worked for me.

**Comment by bennypowers** [comment]
Instead of or in addition to a whole separate package, I wonder if @rbalicki2 would be willing to publish a patch file that works with https://www.npmjs.com/package/patch-package

**Comment by kirill-konshin** [comment]
Any updates?

**Comment by Alxandr** [comment]
I found a really nice workaround. I have a `rollup.config.js` in the root dir as well as one in each of the package dirs. The one in the root-dir uses lerna API to find all the lerna packages, then finds the `rollup.config.js` in each of them, and simply returns an array of them all. That way, if you run rollup in the root dir, it will get all of the configs, and you can watch all of the modules at once :)

**Comment by kirill-konshin** [comment]
Ouch... I have found a better workaround ))) I returned to Webpack )))

**Comment by larshisken** [comment]
Using `lerna exec --parralel -- yarn watch` works for me. The output won't be pretty, but I can live with that.

**Comment by shanshanzhu** [comment]
Found a not-working example online https://github.com/schneidmaster/lerna-rollup-watch

**Comment by shellscape** [comment]
Why not simply override `isTTY`?

```console
→ node
> process.stderr.isTTY
true
> process.stderr.isTTY = false
false
> process.stderr.isTTY
false
```

**Comment by lukastaegert** [comment]
Reading a little through the Node docs it seems to me that we in fact *do* need the `.resume()` to cover exactly the edge case described here: https://nodejs.org/api/stream.html#stream_compatibility_with_older_node_js_versions

Which is a pity as I know this Lerna issue is a long-running one and it would be nice to finally fix it. How does Webpack handle this?

**Comment by kvet** [comment]
@lukastaegert, please see the following reply: https://github.com/rollup/rollup/pull/2410#issuecomment-413492131

**Comment by asakusuma** [comment]
Not sure if root cause is the same, but `rollup -w` doesn't seem to work with `concurrently` or `npm-run-all` either.

**Comment by evocateur** [comment]
This isn't a Lerna bug. I don't even know why Rollup cares about `stdin` when watching.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by schneidmaster** [comment]
I re-tested with my repository in the issue description and the latest versions of lerna/rollup, and the issue no longer reproduces 🎉

**Comment by GongT** [comment]
I still have this issue, `rollup -c xxx -w` works but `rollup -c xxx -w </dev/null` not. @shellscape

**Comment by ryanwinchester** [comment]
> How does Webpack handle this?
> -- @lukastaegert 

Webpack has a separate `--watch-stdin` option

**Comment by fschade** [comment]
any news on that, we tried to use rollup together with [rushstack](https://github.com/microsoft/rushstack).

Same problems as above
