### ISSUE TITLE
Is there a way to exclude test.js files in the bundle and also remove a certain folders from being bundled

### ISSUE THREAD

**Issue by jelaxshan** [rollup/rollup#1920]
This is a question, not an issue.
Is there a way to exclude test.js files in the bundle and also remove a certain folders from being bundled in rollup?

**Comment by guybedford** [comment]
Are you using Rollup directly or alongside another tool / workflow that wraps multiple file builds?

Rollup only bundles the module tree that you provide, so this would be about working out how those files got imported in the first place, and to remove their importing definitions.

If you do need those imports for other reasons there may be different approaches you can use to hide / disable the imports though.
