### ISSUE TITLE
RFC: input option accept globs

### ISSUE THREAD

**Issue by kellyselden** [rollup/rollup#1923]
Now that rollup accepts multiple entry points, It would be a nice convenience to handle globs so someone doesn't have to walk dirs themselves. This is also a convenience in rollup-plugin-multi-entry https://github.com/rollup/rollup-plugin-multi-entry/blob/master/src/index.js#L55

**Comment by guybedford** [comment]
Have you got a use case that you'd like to see this supported with?

I'd be really interested to the example project structure here exactly before rushing into this.

I worry that users not understanding what an entry point is might end up with a huge number of chunks as the number of entry points greatly affects the code splitting algorithm.

**Comment by guybedford** [comment]
Is this something you're still looking to support?

**Comment by QingLeiLi** [comment]
I hava use case about this. I hava a project, which export a lot of class, we use rollup to pack it, It`s big !
I`m foward to pack it to two part, one contain everything, the other is the split classes. It`s good for the user to reduce the package size.

**Comment by TrySound** [comment]
@QingLeiLi You can test treeshakablility with [size-snapshot](https://github.com/TrySound/rollup-plugin-size-snapshot) plugin. You probably don't need to split your library with chunks. If there will still untreeshaked stuff ping me I will help to fix it.

**Comment by QingLeiLi** [comment]
@TrySound thank you for your quick reply,
I think I did not make it clear, rollup is fine, I get a bundle as small as possible. 
but the people who use my library may use a bulid tool without treeshakeing, they can not shake the dead code. so I need split it out.
Maybe the best solution is let them turn to rollup.🙂

**Comment by TrySound** [comment]
Both rollup and webpack are fine with treeshaking (actually with classes it's uglify work). Parcel also added support for treeshaking in the last version.

**Comment by QingLeiLi** [comment]
Alright，I will take a look at it, but,  It will be nice if rollup could add the globs support. Change build tool is not a easy work.

**Comment by TrySound** [comment]
Actually its quite easy when format like esm is the same. My team changed rollup to webpack which has faster development mode in a couple of hours.

**Comment by QingLeiLi** [comment]
OK, I will try it out, thanks for the help~

**Comment by shellscape** [comment]
@QingLeiLi is this feature still needed?

**Comment by QingLeiLi** [comment]
I use glob to create array option to resolve this.

```
const config = [];
glob.sync('src/**/*.js').map((p, index) => {
    const name = path.basename(p, path.extname(p));
    config.push(Object.assign({}, commonConfig, {
        input: p,
        output: {
            file: p.replace(/^src\//, 'lib/'),
            name: name,
            format: 'umd'
        },
    }));
});
```

**Comment by shellscape** [comment]
@TrySound @guybedford that solution above looks like an acceptable workaround. thoughts on usefulness of globs for `input` at this stage?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
