### ISSUE TITLE
Optionally pass CLI command arguments to config

### ISSUE THREAD

**Issue by borilla** [rollup/rollup#1925]
It would be a useful for some plugins if they could access the arguments supplied in the original CLI call to `rollup`

An obvious example would be suppressing plugin output if rollup was triggered with `rollup -c --silent`

After looking at the codebase, it seems a clean way to do this would be to (optionally) inject the `command` object into a factory function exported by the config file. This would then allow options to be programatically propagated to plugins, eg

**rollup.config.js**
```js
export default function makeConfig(commandOptions) {
    return {
        /* ... */
        plugins: [
            myPlugin({
                silent: commandOptions.silent ? true : false
            })
        ]
    };
}
```

Please see related pull request #1926

**Comment by guybedford** [comment]
The approach here has been merged.
