### ISSUE TITLE
Bundle UMD name gets passed to the globals function

### ISSUE THREAD

**Issue by MaximKudriavtsev** [rollup/rollup#1929]
Hi,

After updating rollup in [our project](https://github.com/DevExpress/devextreme-reactive) from version 0.50.0 to 0.55.1, we are facing an issue with the `globals` function. Previously, it was called with IDs of the modules that should be added to the bundle. Now, for some reason, it is also called with the bundle `umd` name, but only with its first component.

For example, if the `umd` name is `XX.YY`, then the `globals` function is called with `XX`. Looks like a bug.

[Here is an example](https://github.com/MaximKudriavtsev/rollup-bugs/tree/master) demonstrating this issue.

Thanks.

**Comment by guybedford** [comment]
It seems this feature was added in https://github.com/rollup/rollup/pull/1747 to allow `globals` to define the export name itself.

Personally I'm not sure I follow the logic behind that change over using `name` directly.

//cc @adrianheine @caub.

**Comment by caub** [comment]
@MaximKudriavtsev I'm don't know much rollup but shouldn't globals and name be at the config top level? https://github.com/MaximKudriavtsev/rollup-bugs/blob/master/rollup.config.js#L10

**Comment by MaximKudriavtsev** [comment]
@caub 
If globals and name are put into the config top level, this problem won't be fixed and a warning will be shown.
![image](https://user-images.githubusercontent.com/15093892/35805419-d8b3ff0c-0a8c-11e8-8df8-f73820b8f493.png)

**Comment by guybedford** [comment]
Root issue at https://github.com/rollup/rollup/issues/1746#issue-275344492.

**Comment by guybedford** [comment]
It seems like the use case here is checking the imports of a global build.

If looking to check dependencies this way, I'd suggest rather reading the `bundle.imports` value.

Let me know if that can't work for you here though.
