### ISSUE TITLE
Failing AppVeyor builds marks good PRs as failing 

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#193]
Cause:
````
> export COMMIT_HASH=`git rev-parse HEAD` && gobble build -f dist`

'export' is not recognized as an internal or external command,
operable program or batch file.
```

I propose that we exclude the `AppVeyor` builds until this issue has been addressed.

**Comment by Rich-Harris** [comment]
I've fixed this particular issue ('fixed' perhaps a little generous – 'worked around' more accurate), and builds seem to be passing again, so I'm going to merge a few greenkeeper PRs. I think there's still a bug with Gobble on Windows (to do with file changes) but we can cross that bridge when we come to it...
