### ISSUE TITLE
Module name conflicts are no longer resolved when bundling code

### ISSUE THREAD

**Issue by MaximKudriavtsev** [rollup/rollup#1930]
Hi,

We've updated rollup in [our project](https://github.com/DevExpress/devextreme-reactive) from version 0.50.0 to 0.55.1, and now different modules with the same name have a name conflict although they are imported from different places.

Here is an [example](https://github.com/MaximKudriavtsev/rollup-bugs/tree/double-imports) demonstrating the issue.

Thanks.

**Comment by guybedford** [comment]
Fixed in https://github.com/rollup/rollup/pull/1944.

**Comment by guybedford** [comment]
This is working correctly now.
