### ISSUE TITLE
error in error message

### ISSUE THREAD

**Issue by timbell** [rollup/rollup#1932]
I think the error message [here](https://github.com/rollup/rollup/blob/089c9e06190b894d766fc44571752fa91dc1eaa5/src/utils/collapseSourcemaps.ts#L82) should actually be changed to:
```
error({
    message: `Multiple conflicting contents for sourcemap source ${
        traced.source.filename
    }`
});
```
I say this as I encountered the error with the output `Multiple conflicting contents for sourcemap source undefined`. I made the change to `traced.source.filename` and the message then gave me the file causing the problem.

**Comment by guybedford** [comment]
@timbell thank you for posting this bug. Do you think you could you create a PR for this?

**Comment by guybedford** [comment]
This has been merged.
