### ISSUE TITLE
opencollective.org image issue

### ISSUE THREAD

**Issue by danwdart** [rollup/rollup#1933]
There's mistakenly two buttons called "become a backer" in the readme file - the one underneath the list of contributors should probably say "become a contributor".

https://opencollective.com/rollup/contributors.svg?width=890

Cheers

**Comment by guybedford** [comment]
If you're referring to the exact graphic you've linked here, this is something on opencollective.org I don't believe we have control over.

**Comment by guybedford** [comment]
Finally fixed this, completely misunderstood in my initial comment it seems.
