### ISSUE TITLE
internal: issue running npm test

### ISSUE THREAD

**Issue by kellyselden** [rollup/rollup#1934]
The output at the end is 

```
> rollup@0.55.3 test:typescript C:\code\rollup
> mv src src_tmp; tsc -p test/typescript; mv src_tmp src


  Invalid option: 'p'. Showing Help:

  Usage: mv [options] [args...]

  Options:

    --help                  output usage information
    -f, --force             do not prompt before overwriting
    -n, --no-clobber        do not overwrite an existing file
    --striptrailingslashes  remove any trailing slashes from each source
    -v, --verbose           explain what is being done
```

I'm on Windows BTW.

**Comment by lukastaegert** [comment]
Funny as there is not even a "p" option used. Looks like an issue with "cash-mv" which is responsible for polyfilling the `mv` command on windows. Maybe it does not recognise your console environment properly? As I do not have a windows environment, any help here is certainly appreciated.

**Comment by kzc** [comment]
I don't run Windows, but the semicolons separating commands are likely the problem:

https://stackoverflow.com/questions/8922224/multiple-commands-on-a-single-line-in-a-windows-batch-file

**Comment by lukastaegert** [comment]
Thanks @kzc 👍
@kellyselden Could you check if changing the script in this way fixes the issue?

**Comment by kzc** [comment]
`&&` is already used in `package.json` instead of semicolons.

https://github.com/rollup/rollup/blob/027d6733e5a7b51e52751ba0a6f0ab0e81c7bd59/package.json#L24

It's actually better practice on UNIX because the command will fail as soon as left side of `&&` fails, whereas with a semicolon the rest of the command will erroneously continue.

**Comment by KingHenne** [comment]
Be aware that this won't rename `src_tmp` back to `src` if the `tsc` command fails! That is the reason why I used semicolons here. We need that at least for the second `mv`. Would `mv src src_tmp && tsc -p test/typescript; mv src_tmp src` solve the issue as well?

**Comment by kzc** [comment]
> Would `mv src src_tmp && tsc -p test/typescript; mv src_tmp src` solve the issue as well?

No. Windows would gack on the semicolon and assume the words following the semicolon are arguments of the previous command.

> Be aware that this won't rename src_tmp back to src if the tsc command fails! 

The solution is brittle anyway if the process is killed mid transaction leaving the source tree in a bad state.
