### ISSUE TITLE
CJS and ESM bundle of library returns empty object

### ISSUE THREAD

**Issue by wking-io** [rollup/rollup#1936]
The bundle for the CJS and ESM output that is being generated when imported in another file returns an empty object.

Can see the issue by installing package `saladbar`

npm install `saladbar` or yarn add `saladbar`

then import and log

```js
import saladbar from 'saladbar';

console.log(saladbar);
//> {}
```

The bundle and config can be seen in this repo: https://github.com/wking-io/salad-bar

**Comment by guybedford** [comment]
Can you try and isolate the issue down to a minimal example over a full repo case?

The best type of replication is a link in the Rollup repl - https://rollupjs.org/repl.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
