### ISSUE TITLE
Watch mode fails when run in parallel

### ISSUE THREAD

**Issue by jhildenbiddle** [rollup/rollup#1938]
I ran into issues running rollup in watch mode as a parallel task via npm scripts. I was able to narrow the issue down to the order in which the rollup script was executed.

This works:
```
npm run othertask & rollup -c -w
```

While this fails:
```
rollup -c -w & npm run othertask
```

The order of the scripts shouldn't matter because they are run in parallel, yet rollup's watch mode breaks when it is "interrupted" by other parallel tasks. Moving it to the last position fixes the problem so long the other task(s) complete their work before rollup starts.

I've created a simplified repo where the bug can be reproduced:

- https://github.com/jhildenbiddle/rollup-watch-bug

Here are a few things I tried to address the issue before posting here:

- Tested on node 8.9.3
- Tested on node 9.5.0
- Tested rollup 0.55.3
- Tested rollup 0.54.1
- Tested rollup 0.53.4

Other issues related to watch have been mentioned that are likely related. For example: #1666, #1669, #1828 and #1919.

FWIW, I've addressed this issue in my project by using [npm-run-all](https://github.com/mysticatea/npm-run-all) to run tasks in parallel.  I'd prefer to not add another dependency *just* for rollup, as all other tasks run in parallel without issue using a single `&` symbol: `npm run task1 & npm run task2 & npm run task3` ... etc.

Thanks!

**Comment by lewispham** [comment]
Confirm this bug. I'm having the same issue. I can not start nodejs server after running rollup in watch mode.

**Comment by jhildenbiddle** [comment]
Any chance we get this marked as a bug, @guybedford or @lukastaegert ?

**Comment by lukastaegert** [comment]
Done 😉

**Comment by Blackskyliner** [comment]
This seems to be a problem based on the CLI reset the watch mode does. I guess it can't be done if its running in a subshell which will then subsequently result in not watching anything.

There should be a option to the watcher or a cli parameter to run in like --no-ansi mode or something like that. Where it does not play with the output buffer of the terminal but just prints messages to the console.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
