### ISSUE TITLE
[bug] Redefining live function & class bindings

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#1943]
[REPL url](https://rollupjs.org/repl?version=0.55.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlMjAlN0QlNUNuZm9vJTIwJTNEJTIwJ2JhciclNUNuJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Input**
```js
export function foo() { }
foo = 'bar'
```

**expected output**
```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function foo() { }
exports.foo = foo;
exports.foo = 'bar';
```

**actual output**
```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function exports.foo() { }
exports.foo = 'bar';
```

From what I see rollup@0.49 hadnt this bug, it had different one though - wrong value was preserved on the exports.

I've found this when experimenting with `experimentalCodeSplitting` which caused `babelHelpers.extends` to be put in `chunk1.js` and it is implemented in this "redefining" style (to support uglifyjs DCE) which broke my build.

**Comment by lukastaegert** [comment]
As I'm currently reworking larger parts of the rendering logic I'll have a look at this one as well.
