### ISSUE TITLE
Watcher for experimentalCodeSplitting with several inputs and output dir 

### ISSUE THREAD

**Issue by DmitroPustovit** [rollup/rollup#1950]
Hi, 
I'm very exited with new code splitting feature and want use in my project but one thing is stoping me - absents of support for watching code with several inputs and output to dir. 

Do you have any plans to implement this feature?

**Comment by guybedford** [comment]
Yes the watcher isn't currently supported with the code splitting multi-input workflow.

This should be added definitely, it's just going to be a little work to update the watching system to handle this.

**Comment by philipahlberg** [comment]
Could Rollup expose the names/paths of the modules included in the build somehow? That'd make things like this an inconvenience rather than a show-stopper.

**Comment by guybedford** [comment]
@philipahlberg the `bundle` object returned by Rollup's JavaScript API returns an object with a `chunks` property containing this information.

**Comment by guybedford** [comment]
It includes a list of `modules` of included files per chunk.

**Comment by philipahlberg** [comment]
My bad, sorry for cluttering the issue.

**Comment by anandthakker** [comment]
> This should be added definitely, it's just going to be a little work to update the watching system to handle this.

@guybedford how deep does this go?  Is it pretty much just a matter of adding a layer of iteration over `chunks` in the watcher for the code splitting case, or does it go deeper?

**Comment by guybedford** [comment]
@anandthakker yes this should simply be wiring to watch all the files listed in the various chunks.

**Comment by guybedford** [comment]
(so in theory not very deep)
