### ISSUE TITLE
Named Imports Incorrectly removed if import * is also used

### ISSUE THREAD

**Issue by bdwain** [rollup/rollup#1951]
If I `import * as whatever from 'foo'` and reference `foo` itself, rather than `foo.bar`, any named imports from 'foo' are removed but do not get transformed to use the whatever variable. 

```js
import * as foo from 'foo';
import {blah, bar} from 'foo'; //removed in the final build without changing the console.logs below

console.log(foo)
console.log(blah);
console.log(bar);

```

[Here is the reproduction on the REPL](https://rollupjs.org/repl?version=0.55.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnZm9vJyUzQiU1Q25pbXBvcnQlMjAlN0JibGFoJTJDJTIwYmFyJTdEJTIwZnJvbSUyMCdmb28nJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhmb28pJTVDbmNvbnNvbGUubG9nKGJsYWgpJTNCJTVDbmNvbnNvbGUubG9nKGJhciklM0IlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by guybedford** [comment]
Thanks for the test case here, I've added the test and fix into the reexport refinements in https://github.com/rollup/rollup/pull/1947.

**Comment by bdwain** [comment]
thanks!
