### ISSUE TITLE
[docs] Section heading is un-clickable after scrolling away from the section

### ISSUE THREAD

**Issue by JCCR** [rollup/rollup#1952]
When I jump to a section in the doc sidebar then I scroll down to reach a different heading I can't  jump to go back to the initial section.

It seems this has to do with the fragment in the URL not changing and staying the same when you scroll around.

![rollup-docs-heading-bug](https://user-images.githubusercontent.com/5132652/35945191-24cb8b0c-0c14-11e8-80ed-9f01d0e9acf4.gif)

**Comment by guybedford** [comment]
Thanks, it seems like this is working now, but let us know if you're still seeing this.
