### ISSUE TITLE
Update acorn to 5.4.1 to get async iteration support 

### ISSUE THREAD

**Issue by zbraniecki** [rollup/rollup#1956]
Acorn released 5.4.0 with added support for async iteration: https://github.com/acornjs/acorn/commit/4d1230699be387e31250735cf43f0723ac747007

Could we get a rollup release with this dependency updated? That would make rollup work with async iteration as well.

**Comment by adrianheine** [comment]
See #1953 :)

**Comment by zbraniecki** [comment]
ah, so a dupe. Thanks!
