### ISSUE TITLE
Windows build fails while Mac/Linux succeed. Apparent '\' vs '/' path issue?

### ISSUE THREAD

**Issue by backspaces** [rollup/rollup#1967]
This repo: https://github.com/backspaces/asx has an Issue/bug submitted that a windows build fails in the rollup step while it succeeds with both mac & linux.

To reproduce: On mac/linux run
```
git clone https://github.com/backspaces/asx
cd asx
yarn
yarn build
```

To see failure, run on windows:
```
git clone https://github.com/backspaces/asx
dir asx
yarn
yarn build
```

The error is: 
> Error: Could not resolve '../dist/three.wrapper.js' from src\ThreeMeshes.js

This suggests a path format issue with `\` vs `/`.

On a test system built in our labs, simply changing the paths in two files to windows \ paths resolved the problem:
> I get a successful build if I change the slashes in `ThreeMeshes.js` and `ThreeView.js` for the dist imports from `/` to `\`

Versions:
```
git 2.15.0
node v8.9.3
npm 5.5.1
yarn 1.3.2
rollup 0.53.1
```

**Comment by backspaces** [comment]
![snap 02 13 18-15 39 54](https://user-images.githubusercontent.com/124366/36178918-b50d861c-10d7-11e8-8a1c-d850e1327658.jpg)

**Comment by backspaces** [comment]
Could someone make sure this fails on windows, even tho ok on *nix systems?

I don't have a windows environment, but _do_ have windows PRs!

**Comment by guybedford** [comment]
@backspaces are you still getting this issue? I regularly run builds in Windows here and haven't seen pathing problems, but would help to know.

**Comment by backspaces** [comment]
AFAIK this is no longer a problem. Lets close this.

I did convert the build to use node cross platform scripts, and in particular shelljs which is designed to be a cross system "bash".
