### ISSUE TITLE
Duplicate ESM import alias

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#1968]
Repo for reproduction: https://github.com/arackaf/booklist/tree/feature/rollup2 (that branch specifically).

Drop down into the react-redux folder.  

npm i (from there!)
npm run rollup

If you go into `public/module/chunk5.js` you should see this

```javascript
import { rootReducer, thunkMiddleware, store, getNewReducer } from './chunk4.js';
import { applyMiddleware, createStore, combineReducers, connect, Provider } from './chunk2.js';
import { SET_IS_TOUCH, SET_DESKTOP, SET_MOBILE, REQUEST_DESKTOP, REQUEST_MOBILE, SET_MODULE, SET_LOGGED_IN, SET_PUBLIC_INFO, LOAD_SUBJECTS, LOAD_SUBJECTS_RESULTS, LOAD_COLORS, SAVE_SUBJECT_RESULTS, SUBJECT_DELETED, _propTypes as propTypes } from './chunk3.js';
import { ajaxUtil, React as react, react_3, react_4, require$$4 as objectAssign, commonjsGlobal, commonjsRequire, unwrapExports, createCommonjsModule } from './chunk1.js';
import { reactDom_2, reactDom_1 } from './chunk6.js';
import { _react as react } from './chunk7.js';
```

note the duplicate import aliases named "react." (lines 4 and 6)  Needless to say this errors out at runtime.

This is using Rollup `0.55.5`, though of course everything is listed in the package.json file in THIS directory, (react-redux)

**Comment by guybedford** [comment]
@arackaf I just tried this replication but it seems there are a few `ts` files where `js` files are expected to be in that branch.

Perhaps also try again now that Rollup 0.56.0 has just been released as it had some deshadowing work.

Otherwise let me know when you've got the replication fixed up and I'll take another look.

**Comment by guybedford** [comment]
(To be clear `npm run rollup` is giving an error that `reactStartup.js` is not found)

**Comment by arackaf** [comment]
@guybedford sorry about that - I forgot to tell you to run `npm run ts` before running rollup.

I've upgraded to Rollup 0.56, but sadly the same problem persists.

**Comment by guybedford** [comment]
The above wasn't quite the right classification, eventually tracked this down and posted the fix in https://github.com/rollup/rollup/pull/1975. Should be released soon.

**Comment by arackaf** [comment]
@guybedford oh man, thank you SO much.  I guess I should have known React was published as CJS, and so that would be the cause of the bug.  Sorry about that!
