### ISSUE TITLE
Causing Error with Aurelia.JS

### ISSUE THREAD

**Issue by Rutulpatel7077** [rollup/rollup#1969]
```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

export class AbstractEvent {

    static inject = [EventAggregator] . ===> Giving error here on  " = "?

    constructor (ea,type) {
        
        this.ea = ea;
        this.type = type;
        this.target = null;

    }

    dispatch() {
        this.ea.dispatchEvent(this);
    }

}
```

What could be the reason ?

```
4: export class AbstractEvent {
5: 
6:     static inject = [EventAggregator]
                     ^
7: 
8:     constructor (ea,type) {
```

**Comment by TrySound** [comment]
@Rutulpatel7077 class properties is not part of js standard yet. Rollup supports only standard. You should use babel with class-properties plugin to achieve this.

**Comment by Rutulpatel7077** [comment]
@TrySound  Thanks a lot. is it possible to give me any reference for that?

**Comment by TrySound** [comment]
https://github.com/tc39/proposals#stage-3
https://github.com/rollup/rollup-plugin-babel
https://github.com/babel/babel/tree/master/packages/babel-preset-stage-3
