### ISSUE TITLE
Regarding multiple entry points unlike webpack

### ISSUE THREAD

**Issue by akanshgulati** [rollup/rollup#1972]
I am currently using webpack for build purposes and tried rollup. I am not able to figure out a way to provide multiple entry points unlike webpack. I am building parallel for firefox and chrome and this is a code snippet of webpack config. 

```
 entry: {
        'chrome/build': ['./src/main.js'],
        'chrome/subtle': ['./src/bg.js'],
        'firefox/build': ['./src/main.js'],
        'firefox/subtle': ['./src/bg.js']
    },
    output: {
        path: path.resolve(__dirname),
        publicPath: '/',
        filename: '[name].js',
    }
```
There are currently three directories at same level, 
-src
-firefox
-chrome

What I am achieving by above config is that when any change is made in `main.js` file, it is build into firefox and chrome directories with name `build.js` and same for `bg.js`. How can I achieve same with Rollup.

I found `dir` option for output but not able to figure out `[name].js` syntax which can name file properly. Please help.

**Comment by guybedford** [comment]
This feature has just been merged, so that in the next release, the following pattern should work here in Rollup:

```js
input: {
  'chrome/build': './src/main.js',
  'chrome/subtle': './src/bg.js',
  'firefox/build': './src/main.js',
  'firefox/subtle': './src/bg.js'
},
output: {
  dir: '.'
}
```

Do try it out when the release lands and report back if you have any queries.

**Comment by yanhaijing** [comment]
If I want to customize the name of the output?

```
    entry: {
        'chrome/build': ['./src/main.js'],
        'chrome/subtle': ['./src/bg.js'],
        'firefox/build': ['./src/main.js'],
        'firefox/subtle': ['./src/bg.js']
    },
    output: {
        path: path.resolve(__dirname),
        publicPath: '/',
        filename: '[name].customname.js',
    }
```
