### ISSUE TITLE
Code splitting erroneously implementing renamed exports

### ISSUE THREAD

**Issue by jthoms1** [rollup/rollup#1976]
Reproducible in the following repo: https://github.com/jthoms1/rollup-issues

If you have multiple entry points with `experimentalCodeSplitting` flag and an entry point file contains an `export { A as ItemA} ` this carried into the common chunk file and is also kept in the original entry point. This causes an error at runtime.

I would expect the `export as` naming to only exist in the entry point file and not carried into the common chunk file.

Apologies for not explaining this well but the repo is very straight forward the the issue is easily reproducible.

**Comment by guybedford** [comment]
This should be fixed in 0.56.3.
