### ISSUE TITLE
Dynamic import with dynamic path emitted incorrectly for SystemJS mode

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#1982]
Repro: https://github.com/arackaf/booklist/tree/special/guybedford-rollup2 

That branch in particular.  Change directory into react-redux, `npm i` then `npm run rollup`

The entry point contains 

`let p = import(x);`

the SystemJS bundle that's produced does not modify this at all, producing the following

```javascript
System.register([], function (exports, module) {
'use strict';
return {
execute: function () {

function junk() {}

//import React, { Component } from "react";

//const F2 = require("./junk2");
//import F2 from "./junk2";

let p = import(x);
//let F2 = 12;

class Foo {
  blah() {
    return junk + F2 + p;
    //return this;
  }
} exports('default', Foo);

}
};
});
```

I believe the import should be transformed in some way to interop with SystemJS, rather than leaving a bare import() call that will error at runtime for older browsers.

**Comment by guybedford** [comment]
Thanks, I've created a fix here in https://github.com/rollup/rollup/pull/1985.

**Comment by arackaf** [comment]
@guybedford - thanks SO much.  Can't wait to give this a try once out.
