### ISSUE TITLE
[feature request] Mangle export names in chunked files

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#1983]
While rollup is not a minifier it has necessary knowledge to do this. Non-input chunks are "internal", not really exposed to other consumers than other output files, so you could shorten names of their exports. 

Without files being scope hoisted later when/if bundled minifiers such as uglifyJS won't have necessary info to mangle this.

**Comment by guybedford** [comment]
This is definitely a feature that can be added.

Further I do actually think it could be nice to add a `minify` output option in general to Rollup as it would speed up builds in not needing to reparse since we already have all the analysis for this.

**Comment by Andarist** [comment]
The only pain point for me with adding full-blown minify option is that it's kinda a duplicated effort, there are tools for this already and while you can "easily" implement working minifying, there are many smaller rules/optimizations that you won't be able to do (at first), catching up with everything to other tools sounds a little like a waster effort.

Utopian goal would be to share results of static analysis between tools, so subsequent tools could use previous analysis results and just do some more on top of that, or use the results to achieve even better results with that extra knowledge. This would be a hardcore endeavour though 😄

**Comment by guybedford** [comment]
@Andarist at the end of the day JS needs a general purpose compiler. All tools should aim for this, and the whole ecosystem will win if we have at least two good ones eventually. For Rollup I'd say these aims are good, and could potentially help improve the architecture in more general directions. But certainly if these features create an internal architecture that is more convoluted instead of less then it is wasted effort completely that would be better gained through specialization. Whether we have the right architecture to head towards a general purpose compiler is yet to be seen too certainly.

**Comment by guybedford** [comment]
(Probably worth noting this is my opinion only, and not that of the project, and I may well be wrong in what constitutes the best direction for Rollup!)

**Comment by Andarist** [comment]
> @Andarist at the end of the day JS needs a general purpose compiler.

Yeah, my thoughts exactly. I hope to see such in the future :) Love how rollup is evolving lately, so good luck in anything you'd like to explore next.

**Comment by guybedford** [comment]
Mainly mentioning, because I was thinking the following might be quite straightforward:

* Add `experimentalMinify`
* Do this for all identifiers and not just export boundaries
* Strip all whitespaces as well

**Comment by Andarist** [comment]
Actually mangling export boundaries would be great as separate feature (or builtin of `experimentalCodeSplitting`). I use this feature to ship multi-entry, but fully deduped, libraries to npm and I do not want to minify them because it makes it harder to just dive into node_modules, debug etc.

**Comment by guybedford** [comment]
@Andarist good point, that definitely makes sense and I agree this shouldn't be combined with any minification effort.

Since the imported name will be unmanged, I think it should be more than descriptive enough for debugging to make this the default behaviour.

**Comment by guybedford** [comment]
PR at https://github.com/rollup/rollup/pull/1988.

**Comment by Andarist** [comment]
That was quick! Cool ❤️

**Comment by guybedford** [comment]
The latest PR for this is now at https://github.com/rollup/rollup/pull/2087.
