### ISSUE TITLE
JavaScript API no longer provides names of imports

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#1992]
When debugging an issue with a test in `rollup-plugin-node-resolve` (cf. rollup/rollup-plugin-node-resolve#141), it turned out that as of v0.55.0, rollup always returns an empty array for `imports` in its JavaScript API here: https://github.com/rollup/rollup/blob/5eb2e2e5984fef0e3dae3bd3d863f062597df80f/src/rollup/index.ts#L307

I did not find the time yet to investigate further but obviously there seems to be something wrong with `Chunk.getImportIds()`. `exports` and `modules`, on the other hand, seem to be working to specification.

**Comment by guybedford** [comment]
@lukastaegert do you perhaps have a test case? Note that imports are only present for externals and other chunks. I've definitely got it working in my code splitting workflows here.

**Comment by lukastaegert** [comment]
I do not have a test case other than the original test in rollup/rollup-plugin-node-resolve#141 but I see you already started looking into that. Thanks!

**Comment by lukastaegert** [comment]
Might also be an incompatibility with that plugin.

**Comment by guybedford** [comment]
I've tracked down a fix, will post a PR very soon.
