### ISSUE TITLE
ASI automatically inserts lots of semicolons since 0.56.0

### ISSUE THREAD

**Issue by adrianheine** [rollup/rollup#1993]
[Sample](https://rollupjs.org/repl?version=0.56.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwc2VsZWN0aW9uUG9zaXRpb24odmlldyklMjAlN0IlNUNuJTIwJTIwbGV0JTIwbGVmdCUyQyUyMHJpZ2h0JTJDJTIwdG9wJTJDJTIwYm90dG9tJTVDbiU1Q3RyZXR1cm4lMjBsZWZ0JTIwJTJCJTIwcmlnaHQlMjAlMkIlMjB0b3AlMjAlMkIlMjBib3R0b20lNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE):
```js
export function selectionPosition(view) {
  let left, right, top, bottom
  return left + right + top + bottom
}
```

```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function selectionPosition(view) {
  let left, right, top, bottom;;;;
  return left + right + top + bottom
}

exports.selectionPosition = selectionPosition;
```

This used to work in 0.55.5.

**Comment by lukastaegert** [comment]
Thanks! I guess I messed something up here. BTW if you add a single semicolon, no superfluous one s will be inserted 😜. I will have a look tomorrow.
