### ISSUE TITLE
Code splitting with 'amd' output with default export from common chunk causes incorrect import from dependent chunks

### ISSUE THREAD

**Issue by anandthakker** [rollup/rollup#1996]
If a common module has the form:

```js
const identifier = /* some value */;
export default identifier;
```

and is used from multiple entry points like:

```js
import x from './shared';
/* do stuff with x */
```

then, when bundled using `format: 'amd'`, the output in the dependent modules seems to contain free references to `x` (rather than something like `__chunk1_js.identifier`).

Minimal reproduction here: https://gist.github.com/anandthakker/f2bc16bed7335e8cccb21f257bdf6529 

If you change the common module to simply `export default /* value */`, the error does _not_ occur.

**Comment by guybedford** [comment]
Thanks, this is definitely a bug. I'm looking into it.

**Comment by anandthakker** [comment]
A temporary workaround that seems to be working for me is to export some expression that isn't just an identifier: e.g., `export default identifier || identifier`.

**Comment by anandthakker** [comment]
As best I can tell, it seems like the issue is that `ExportDefaultVariable.getName()` returns the `_original` variable's name: https://github.com/rollup/rollup/blob/5eb2e2e5984fef0e3dae3bd3d863f062597df80f/src/ast/variables/ExportDefaultVariable.ts#L27-L29

... even if this export is at a chunk boundary.  Thus, when an identifier in one chunk refers to a default export from a another chunk, `ExportDefaultVariable.getName()` -- used by `Identifier.render()` -- returns a name from the exporting chunk's scope.

I was hoping I might be able to submit a patch, but I'm not sure what the ideal fix is here -- would it suffice to do a check like so in `ExportDefaultVariable.getName()`?
```js
// If this.safeName is set and differs from this.name, this implies (?) that this variable reference crosses a chunk boundary
if (this.safeName && this.safeName !== this.name)
    return this.safeName
```

Or is the right fix to add some kind of more explicit scope awareness to this part of the object model somehow?

**Comment by anandthakker** [comment]
(@guybedford I know you said you were looking into it!  Just wanted to share what I learned from a bit of digging this afternoon.)

**Comment by guybedford** [comment]
@anandthakker you got the right diagnosis exactly - we're doing some funky things with safeName as it in fact varies across chunks as the "rendered layer"... hopefully we can come up with a better model for this at some point that is a little more intuitive to understand.

Fix at https://github.com/rollup/rollup/pull/2001.

**Comment by anandthakker** [comment]
🙏 thank you for the quick fix, @guybedford !
