### ISSUE TITLE
rollup.config.js in a folder that is not a subfolder of the current folder does not work.

### ISSUE THREAD

**Issue by johanneswilm** [rollup/rollup#1997]
Hey,
please bear with me if this is a known issue. I didn't find anything about it.

Do:

1. CD to the dir where your node_modules and package.json are but where your rollup.config.js file is not. Make sure that the rollup.config.js is in a folder that is NOT a subfolder of the current folder. 

2. Run:

```
node_modules/.bin/rollup -c PATH/OF/CONFIG/rollup.config.js 
```

The path can be relative or absolute. Symbolic links to a different folder seem to be treated as if the absolute path to the linked to folder had been used.

Result:  `[!] Error: Cannot find module 'rollup-plugin-babel'`

**Comment by shellscape** [comment]
@johanneswilm are you still experiencing the same behavior with the latest version? If so, any chance you could put together a minimal repo that reproduces that behavior?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
