### ISSUE TITLE
Add documentation for `resolveDynamicImport` plugin hook to wiki

### ISSUE THREAD

**Issue by anandthakker** [rollup/rollup#2002]
The [Plugins](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins) wiki page documents the hooks available for Rollup plugins, but is missing the `resolveDynamicImport` hook that was added in https://github.com/rollup/rollup/pull/1790.

**Comment by shellscape** [comment]
The wiki page has since been shuttered and this hook does appear on the main documentation now.
