### ISSUE TITLE
[feature request] Tree shaking for short-circuited boolean operations

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#2004]
Rollup already has optimizations for things like `if (true) { ... code ... }` and `if (false) { ... code ... }`, which is great, but I've run into a situation where it would be nice (although certainly not necessary) to also handle `true && ...`, `false && ...`, `true || ...`, `false || ...`.

If someone could point me to the approximate area in the code this should be handled, I'd be happy to take a shot at a PR for this.

**Comment by Conduitry** [comment]
Perhaps a little closer to my feature request, it looks like `true ? ... : ...` and `false ? ... : ...` are also already optimized.

**Comment by lukastaegert** [comment]
This should actually not be that difficult. If your goal is to just suppress the statement if it has no effects (as opposed to also trying to simplify things like `true && myExpression` -> `myExpression`—there are some strings attached if you want this), then all you have to do is add a proper `hasEffects` method to https://github.com/rollup/rollup/blob/master/src/ast/nodes/BinaryExpression.ts.

You could take a look at how logical expressions work for inspiration. No idea why we did not fix binary expressions yet.

**Comment by guybedford** [comment]
@lukastaegert how much do we cache these analysis checks? I'm just wondering how often the same analysis could be reevaluted by different paths?

**Comment by lukastaegert** [comment]
If something has a side-effect, this is cached immediately via the `included` flag and the next time the algorithm short-circuits here. For side-effect free statements there is no caching yet as in most cases, the results can change when new variables are included. Some statements also do some internal caching (i.e. in this example, binary expressions could cache if they are always falsy).

**Comment by guybedford** [comment]
It sounds like we might want methods like "evaluateIfTruthy" for this binary analysis though?

**Comment by lukastaegert** [comment]
There already is a `getValue` that is meant to serve such a purpose (it is used like this e.g. by logical expressions)

**Comment by Conduitry** [comment]
I'm taking a peek at this now, and just judging by the code so far it looks like the class in question might be `LogicalExpression`, not `BinaryExpression`. It also looks like `LogicalExpression` already has `hasEffects` and `getValue` methods that take shortciruiting into account. And it looks like rollup already does remove things like `false && whatever()` and `true || whatever()` if that's the whole statement - but I guess what I was asking about was in fact doing `false && whatever()` -> `false` and `true && whatever()` -> `whatever()` simplifications when those appear in larger expressions. I'm thinking that `LogicalExpression#render` is actually more likely to be what I want to implement, using `ConditionalExpression#render` as a guide. I'll keep digging!

**Comment by lukastaegert** [comment]
Ah, you're right. Logical.

**Comment by lukastaegert** [comment]
The problem with simplification is preservation of the context. I was planning on implementing a more general solution for this problem at some point that would also work for sequence expressions and combinations of them all but it will take some time until I get there.
Until then you should make sure that this is not simplified:
```
// input
(true && x.y)()

// this is not equivalent
(x.y)()
```

because only in the second case, `this` would be `x`. At least sequence expressions already detect these things if you want some inspiration.

**Comment by lukastaegert** [comment]
Otherwise what you need to do is implement a `render` method.
