### ISSUE TITLE
npm module only works on own dependencies. can it be depend on user dependencies?

### ISSUE THREAD

**Issue by hardy12994** [rollup/rollup#2010]
I have made NPM angular module (directive) but when it is install,it is only working on particular angular version on which that module is made.

**if npm module is made on angular v5 then it will only works on angular v5 not on angular v2 or angular v4.**

My question is how can make that module dependencies(like `@angular/core`, `@angular/forms`) depend on that modules which uses has currently in that repositry. or their are any settings which can perform this on Rollup/tsconfig file.

Or i have to make multiple modules for multiple version ?

what i am using is --

- ROLLUP as bundler
- tsconfig for TS

**Comment by lukastaegert** [comment]
This does not seem to be an issue with rollup. You may want to look into using [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) in your package.json file.

**Comment by lukastaegert** [comment]
Also, you need to make sure `angular` is configured as external in your rollup configuration for this to work.

**Comment by hardy12994** [comment]
@lukastaegert peer dependencies are some thing like one module is dependent on other. so when we say `npm install` it will install all the peer dependencies are install which are dependent on dependencies.

So, is their any way in ROLLUP i can say to rollup that use version of required module which user had installed for own purpose (which is kept in node_modules of user REPO)?

**Comment by lukastaegert** [comment]
Peer dependencies are not installed automatically but they are expected to be present on a users system. So if you specify angular as a peer dependency but NOT as an actual dependency (except maybe a devDependency) in your directive's package.json, it is not installed on a user's system but the user will be prompted that they need to have a compatible version of angular installed if it is missing.
If you then `import('angular')` in your directive, it will use the version the user has installed. I do not see how rollup has anything to do with that.

**Comment by hardy12994** [comment]
@lukastaegert  appreciate your reply !!. So is their any way that i want hide ( or stop that ) **promt** when any user use my module ( on setting the require module in **Peer dependencies**) ?

**Comment by lukastaegert** [comment]
Not sure I can follow you. The user would only see a prompt that they need to install angular when they do `npm install` and
* they do not have angular in their own dependencies, or
* they do not have a version inside the version range of your peerDependency

But since your library will not work without angular, I guess this prompt is necessary. Or do you mean something else?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
