### ISSUE TITLE
problem with source map

### ISSUE THREAD

**Issue by MHA15** [rollup/rollup#2011]
I am using rollup v0.56.2 and typescript2 module of that and set `output.sourcemap = true` but it doesnt work and content of sourcemap file is
`
{"version":3,"file":"Menu.js","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"}
`

why it is not set my typescript files?

**Comment by marvinhagemeister** [comment]
Just a wild guess: Do you have sourcemaps enabled in your `tsconfig.json`?

**Comment by bhousel** [comment]
I'm running into this issue as well (see https://github.com/openstreetmap/iD/issues/4874) and definitely not using typescript.

**Comment by taoeffect** [comment]
Hi, similar to this issue and #2615 I also have sourcemaps being generated with nothing but semi-colons.

Here is the rollup config I'm using:

```
  const watchOpts = {
    clearScreen: false,
    input: 'frontend/simple/main.js',
    output: {
      format: 'system',
      dir: 'dist/simple',
      sourcemap: true
    },
    external: ['crypto'],
    moduleContext: {
      'frontend/simple/controller/utils/primus.js': 'window'
    },
    plugins: [
      alias({
        vue: path.resolve('./node_modules/vue/dist/vue.common.js')
      }),
      resolve({
        preferBuiltins: false
      }),
      VuePlugin(),
      flow({ all: true }),
      commonjs({
        namedExports: {
          'node_modules/vuelidate/lib/validators/index.js': [ 'required', 'between', 'email', 'minLength', 'requiredIf' ],
          'node_modules/vue-circle-slider/dist/vue-circle-slider.common.js': [ 'CircleSlider' ]
        },
        ignore: ['crypto']
      }),
      babel({
        runtimeHelpers: true,
        exclude: 'node_modules/**'
      }),
      globals()
    ]
  }
  const watcher = rollup.watch(watchOpts)
```

I tried to eliminate the possibility (perhaps unsuccessfully) that this were an issue with `rollup-plugin-vue` by import a dynamic import on a pure javascript file, generating a chunk and corresponding sourcemap.

This shows the original file:

```js
System.register([], function (exports, module) {
  'use strict';
  return {
    execute: function () {

      exports({
        read: read,
        write: write
      });

      function read(buffer, offset, isLE, mLen, nBytes) {
        var e, m;
        var eLen = nBytes * 8 - mLen - 1;
        var eMax = (1 << eLen) - 1;
        var eBias = eMax >> 1;
        var nBits = -7;
        var i = isLE ? nBytes - 1 : 0;
        var d = isLE ? -1 : 1;
        var s = buffer[offset + i];
        i += d;
        e = s & (1 << -nBits) - 1;
        s >>= -nBits;
        nBits += eLen;

        for (; nBits > 0; e = e * 256 + buffer[offset + i], i += d, nBits -= 8) {}

        m = e & (1 << -nBits) - 1;
        e >>= -nBits;
        nBits += mLen;

        for (; nBits > 0; m = m * 256 + buffer[offset + i], i += d, nBits -= 8) {}

        if (e === 0) {
          e = 1 - eBias;
        } else if (e === eMax) {
          return m ? NaN : (s ? -1 : 1) * Infinity;
        } else {
          m = m + Math.pow(2, mLen);
          e = e - eBias;
        }

        return (s ? -1 : 1) * m * Math.pow(2, e - mLen);
      }
   [... snip a bunch of lines that look similar for brevity's sake ...]
  };
});
//# sourceMappingURL=chunk-7630b9f3.js.map
```

And here's the corresponding chunk sourcemap produced:

```
{"version":3,"file":"chunk-7630b9f3.js","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"}
```

This also happens with my main bundle, which makes debugging a Vue.js app annoying. :-\

Note that unlike the OP I am not using TypeScript (but am using the `rollup-plugin-flow` plugin).

**Comment by taoeffect** [comment]
Another related issue: #2657 (might be others).

Is there a way to debug this and figure out if it's a problem with rollup or a plugin?

**Comment by taoeffect** [comment]
I figured it out!

In our case the problem was because of the [rollup-plugin-flow](https://github.com/leebyron/rollup-plugin-flow/issues/5#issuecomment-367559650) plugin.

This [pull request](https://github.com/openstreetmap/iD/pull/4885/files) shows how to fix it by using [flow-remove-types](https://www.npmjs.com/package/flow-remove-types) directly. 😄

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
