### ISSUE TITLE
Raw, top-level domain import causing error in chunking code

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#2013]
Repo: https://github.com/arackaf/booklist/tree/special/rollup-snapshot-feb-25  (that branch in particular)

Switch to the react-redux folder.  `npm i` `npm run ts` then finally `npm run rollup`

In `public/module/subjects.js` note the following line:

`import domain from 'domain';`

which of course causes errors.  I've tracked this down to the `react-dnd` library. If you go into `react-redux/modules/subjects/components/subjectsList.js` (NOT the typescript companion) and remove

`import { DragSource, DragDropContext, DropTarget, DragLayer } from "react-dnd";`

and then re-run rollup (but NOT TypeScript) the import vanishes. 

I peaked down into the react-dnd source, and the only mention of the word `domain` was in a code comment.

**Comment by guybedford** [comment]
I just had a look at this case and `import domain from 'domain'` seems to appear so long as one is running the CommonJS Rollup plugin against `node_modules/react-dnd/lib/index.js` with any normal Rollup operation.

So basically:

```
import commonjs from "rollup-plugin-commonjs";
import resolve from "rollup-plugin-node-resolve";

export default {
    input: "./node_modules/react-dnd/lib/index.js",
    output: {
      file: "public/module/out.js",
      format: "es",
      sourcemap: false
    },
    plugins: [commonjs(), resolve()]
  }
}
```

is the minimal replication I was able to get here.

It should be possible to further isolate if it is react-dnd itself or a dependency of react-dnd bringing in domain.

I don't have a deep knowledge of how these Rollup plugins work so it may be worth posting an issue there further. I tend to use my own NodeJS Rollup plugin for this stuff which I'm hoping to make available publicly soon.

**Comment by arackaf** [comment]
Posted it here: https://github.com/rollup/rollup-plugin-commonjs/issues/297

Anyone feel free to close this if not needed here anymore

**Comment by guybedford** [comment]
Sure will close this as it doesn't seem to be a Rollup core issue. Note that `domain` does seem to be used so it's not a treeshaking issue either. I do recall builtins needing some custom configuration to work at times, perhaps a custom mapping and resolution for the browser builtin for domain needs to be provided.

**Comment by arackaf** [comment]
Interesting - I already have `browser: true` for that plugin, and this works with webpack, so I'd be curious to hear what might be missing here.
