### ISSUE TITLE
SystemJS confused by missing semicolon after default export

### ISSUE THREAD

**Issue by aphitiel** [rollup/rollup#2018]
while trying to replicate http://rollup-starter-code-splitting.surge.sh, I stumbled upon this issue. Sorry about the missing REPL (rollup/rollupjs.org#124).

test.js:
```
export default { x: 0 }
```
When compiled with ```rollup -f system test.js```, it contains
```
var test = exports('default', { x: 0 )}
```
Note the parenthesis and curly brace in wrong order.

After adding a semicolon the output is correct:
```export default { x: 0 };``` -> ```var main = exports('default', { x: 0 });```

**Comment by guybedford** [comment]
Thanks, I've posted a fix at https://github.com/rollup/rollup/pull/2019.
