### ISSUE TITLE
Cannot name system.register module

### ISSUE THREAD

**Issue by joeldenning** [rollup/rollup#2027]
First off, thanks @guybedford for implementing System.register format, and thanks rollup maintainers for merging it in. We are experimenting with switching off of `jspm bundle` to `rollup -f system` and are excited about some of the possibilities with it!

The System.register() function has [an optional first argument string for naming the module](https://github.com/ModuleLoader/es-module-loader/blob/master/docs/system-register.md#bundled-vs-on-demand), but that is not currently supported by rollup. The string module name seems to correspond nicely with rollups `output.name` concept, since this is similar to a UMD or iife bundle name.

I propose that when rollup's `output.name` option is present, that it should be the name of the System.register module. I've got a pr coming soon that will do exactly that.

**Comment by guybedford** [comment]
This is merged now.

**Comment by CoskunSunali** [comment]
@guybedford Thanks for the update! Would you be so kind to share an example how are we going to define the module names and how the TS compiler will resolve the dependency names?
