### ISSUE TITLE
Function parameters that are the same as imported class names are renamed

### ISSUE THREAD

**Issue by Narretz** [rollup/rollup#2030]
See this reproduction: I would expect that the parameter `MyClass` is not renamed to `MyClass$$1`. This works as expected if the class is not imported but declared in the same file.

[REPRODUCTION](https://rollupjs.org/repl?version=0.55.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyME15Q2xhc3MlMjAlN0QlMjBmcm9tJTIwJy4lMkZNeUNsYXNzLmpzJyUzQiU1Q24lNUNuJTVDbiU1Q25mdW5jdGlvbiUyMG5hbWUoTXlDbGFzcyklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKE15Q2xhc3MuYSklNUNuJTdEJTVDbiU1Q25jb25zb2xlLmxvZyhNeUNsYXNzLmEpJTNCJTVDbmNvbnNvbGUubG9nKG5hbWUoJTdCYSUzQSd3aGF0ZXZlciclN0QpKSU1Q24lNUN0JTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJNeUNsYXNzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNsYXNzJTIwTXlDbGFzcyUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU1Q24lNUN0JTVDdGElMjAlM0QlMjAlNUMlMjJleHRlcm5hbCU1QyUyMiU1Q24lNUN0JTdEJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

@Naridal pointed out a possible reason for this: (https://github.com/rollup/rollup/issues/1914#issuecomment-370078036).

I'd still consider it a bug, though.

**Comment by guybedford** [comment]
It seems Rollup doesn't track inner scopes when doing deshadowing. I'm sure there would be a way to surface bottom-up scope checks over top-down with a modified deshadowing algorithm, but yes wouldn't be a simple change I think without greatly affecting performance.

**Comment by Narretz** [comment]
I found this issue where the same thing (with the same use case) was reported, and closed as "won't fix": https://github.com/rollup/rollup/issues/968. So, your call if this should stay open or not.

**Comment by lukastaegert** [comment]
Interesting, thanks! Marking this as an improvement as this is not breaking anything but just does not look as nice as it could. I would leave this open as the repro of the other issue is broken and your example is something we CAN fix.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
