### ISSUE TITLE
Importing external package as namespace creates duplicate imports

### ISSUE THREAD

**Issue by bigtimebuddy** [rollup/rollup#2033]
I'm trying to upgrade to the latest release (v0.56.4) from v0.52.0 but getting this issue when importing external namespaces. When I try to use this output with Rollup, CommonJS plugin complains and fails `[!] (commonjs plugin) SyntaxError: Identifier 'externalPackage' has already been declared`

input:
```js
import * as ext from 'external-package';
export { ext };
```

output:
```js
import * as externalPackage from 'external-package';
import * as externalPackage from 'external-package';
export { externalPackage as ext };
```

[Repl example](https://rollupjs.org/repl?version=0.56.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGV4dCUyMGZyb20lMjAnZXh0ZXJuYWwtcGFja2FnZSclM0IlNUNuZXhwb3J0JTIwJTdCJTIwZXh0JTIwJTdEJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by guybedford** [comment]
Thanks for posting, PR created at https://github.com/rollup/rollup/pull/2034.
