### ISSUE TITLE
System format should (maybe?) set __esModule to be true

### ISSUE THREAD

**Issue by joeldenning** [rollup/rollup#2037]
Rollup defines an `__esModule` property on many module formats, including amd and cjs (see example [here](https://github.com/rollup/rollup/blob/aa2b54b031dc10b2e08bda433f06b9fa21db5544/test/form/samples/module-name-scoped-package/_expected/amd.js#L7)), but it does not do so for system format bundles.

I do not have a full understanding of what rollup/webpack/jspm/etc have agreed upon for conventions with requiring the default export and how to interop with cjs `module.exports`. But my understanding is that, at least in webpack, `import foo from 'foo'` will return either `foo` or `foo.default`, depending on if `foo.__esModule` is set to true.

Back to rollup's implementation of the system format, my understanding is that the System.register format always represents an es module (since System.register is meant to emulate es6 behavior in the browser) and so I believe that rollup's outputted bundles should set `__esModule` for them. To implement this would be simple -- one way would be to add `"exports('__esModule', true)"` to https://github.com/rollup/rollup/blob/master/src/finalisers/system.ts#L105.

But before submitting a pr for it, I thought I'd check to see if I'm misunderstanding when __esModule should be present.

**Comment by joeldenning** [comment]
cc @guybedford

**Comment by guybedford** [comment]
It would help to focus on an exact use case here ideally. Note that if using the Rollup CommonJS plugin, it will set the default export correctly so that this isn't strictly necessary.

The main reason to support ES module is when writing a library that will be used in other ecosystems that might use an __esModule convention. System.register bundles aren't quite as portable as other formats so I was hoping we could make the output in Rollup more spec compliant than needing to opt into these legacy hacks.

**Comment by guybedford** [comment]
Perhaps if you can share a scenario that isn't working without this, so we can discuss the exact use case?

**Comment by joeldenning** [comment]
The `rx` library is one example where, for better or for worse, the `__esModule` convention is making some of my code work that otherwise would not.

See https://github.com/joeldenning/rollup-2037 for a repo that illustrates some of it. Particularly, take note of [this import statement](https://github.com/joeldenning/rollup-2037/blob/master/index.js#L1). This works with wepback just fine, since webpack converts [rx's `module.exports = Rx`](https://github.com/Reactive-Extensions/RxJS/blob/master/dist/rx.all.js#L12376-L12380) into the default export. However, this **would not** work if rollup creates a system bundle for Rx, which then is injected into a webpack bundle that has declared rx to be an external.

The reason why it doesn't work in that case is that [on this line](https://github.com/joeldenning/rollup-2037/blob/master/dist/main.js#L82), webpack does `var rx__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(rx__WEBPACK_IMPORTED_MODULE_0__)`, which does the [__esModule checks](https://github.com/joeldenning/rollup-2037/blob/master/dist/main.js#L53-L59) to determine whether to return `module` or `module['default']`. This will fail because the registered system module [exports the rx library as the default export](https://github.com/joeldenning/rollup-2037/blob/master/dist/rx.rollup.js#L12373) but does not indicate that it is an __esModule.

Phewf hopefully that explanation isn't unintelligible. The main point is just that modules put into SystemJS registry might not work properly if injected into webpack bundles dynamically in the browser. I'm not sure if the `__esModule` convention is the right thing to do or not, still, but since rollup adds __esModule for other module types, I am thinking that it is probably the right thing to do for System bundles, too

**Comment by guybedford** [comment]
It may be better to build `rx` as a global in this case if used as an external boundary. Rollup has the `exports: 'default'` configuration option for handling this. Basically, SystemJS interprets System.register modules as __esModule modules by default, as the format is designed to exactly match the ES module named semantics. If wanting to build a module as an external, for consumption elsewhere it is probably better to use a format like AMD / UMD or global to get the right interop, as the features of the System format (exact semantics) may not be needed.
