### ISSUE TITLE
[bug] Namespaces are not correctly exported from a common chunk

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#2039]
repl doesn't support `experimentalCodeSplitting` and unfortunately I don't have time to prepare whole repository illustrating the problem - can provide it later, if needed, but the issue is pretty straight-forward so I think a brief description should be enough.

Relevant parts of `rollup.config.js`:
```js
{
  experimentalCodeSplitting: true,
  input: ['src/index.js', 'src/selectors.js'],
  output: [{ dir: 'es', format: 'es' }, { dir: 'lib', format: 'cjs' }],
}
```

My internal files are using `selectors` as this:
```js
import * as selectors from './selectors'
// ...
bindSelectors(selectors, store.getState)
```

I want to expose my selectors file to consumers so in other packages that do not use my main entry point (index.js, the one that using nasty bindSelectors) only used selectors should end up in the bundle.

When using `experimentalCodeSplitting` to achieve this goal my `chunk.js` looks now like this:
```js
// ... some babel helpers

// selectors declarations

var selectors = Object.freeze({
  // ... listed selectors
});

export {
  // babel helpers, listed selectors
}
```

**Note** that `selectors` object is not exported from the common chunk

Importing `index.js` has import declaration WITHOUT `selectors` namespace object (which is consistent with exporting site), but `selectors` namespace object is still present as argument in the function call in the file.

EDIT:// Also what I've spotted now, on the importing site in my index.js I can see unused imports being imported (I think basically all selectors are specified there, even if they are unused, I guess `selectors` namespace should be used here throughout the file? or maybe it would be possible to use namespace object only in the function call that needs it as a whole, but in other places a direct specifier could be used to allow for better minification later)

**Comment by kzc** [comment]
An example repo with output checked in for `es` and `lib` directories would be helpful in demonstrating the problem. Bonus points if the output is runnable from the command line with `console.log` statements. Making a reproducible test case often takes more time than the fix.

**Comment by guybedford** [comment]
This should be fixed in https://github.com/rollup/rollup/pull/2041.

**Comment by Andarist** [comment]
Cool ❤️

**Comment by guybedford** [comment]
Closing as fixed, but please let me know if you still see any issues here at all.
