### ISSUE TITLE
Annotate frozen namespaces with #__PURE__

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#2042]
Would be super cool to have frozen namespaces annotated with `#__PURE__`. By adding #__PURE__ to the call to `Object.freeze()` it could get removed by UglifyJS when the namespace object is not used. I don't think there is any downside of adding those annotations.

This issue is also not about handling `#__PURE__` just like UglifyJS does - it's purely about adding this annotation to the generated code. 

I don't think rollup generates any extra runtime calls than this one, but if it does others could get considered for this too.

Reference [here](https://github.com/rollup/rollup/pull/2041#issuecomment-371906992)

cc @lukastaegert @kzc

**Comment by kzc** [comment]
Not sure if the Rollup output needs such an annotation. You could just have uglify treat all `Object.freeze()` calls as pure with the `pure_funcs` compress option. But if there are desired side effects within the call and the result is not used then all bets are off.

**Comment by kzc** [comment]
Regarding potential side effects in an used `Object.freeze` call, it may work out after all...
```
$ echo '/*@__PURE__*/Object.freeze({a: side_effect()});' | bin/uglifyjs -c "pure_funcs=[Object.freeze]"
side_effect();
```

**Comment by kzc** [comment]
Oops - I meant to exclude the annotation:
```
$ echo 'Object.freeze({a: side_effect()});' | bin/uglifyjs -c "pure_funcs=[Object.freeze]"
side_effect();
```

**Comment by Andarist** [comment]
That certainly works for me, I'd like to provide the best possible setup for unaware of this consumers of my library. I can work around this and add `#__PURE__` on my own in the output bundles, but it seems to me that this could be built-in feature of rollup

**Comment by lukastaegert** [comment]
Just to keep in mind since `Object.freeze` modifies it’s argument, it cannot be safely treated as pure by default. I.e. if it is called on a variable instead of a literal without assigning the return value, the above suggestion would strip the call. If this happens in a library that uses `Object.freeze` as part of its test assertions, the tests may become worthless. That being said, I‘m all in favor of adding the annotation.

**Comment by kzc** [comment]
I agree that adding the pure annotation for this use case provides more fine-grained control and is otherwise harmless. But would it save any bytes in minification for cases other than an unused side effect free import?

BTW, typo in issue title: Annotare
