### ISSUE TITLE
transformChunk hook

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2043]
Thinking about things like having CSS imports work with Code Splitting (again, totally not inspired by other project work), the standard thing a plugin needs is the ability to "reduce" or optimize the CSS for that specific chunk. So it needs a list of ids of what is in the chunk, the chunk source, and then to output some kind of reduction, or to write its own css file etc.

Currently we have the `transformBundle` hook called for each chunk, so that it is effectively a `transformChunk` hook now, but it is missing the following information:

* The list of modules in the chunk
* The output file name of the current chunk

So what I'd like to suggest is:

a) Create a new `transformChunk` interface designed specifically for this purpose. Something like `transformChunk (chunkFileName: string, ids: string[], source, sourceMapChain, outputOptions)`.
b) Consider deprecating `transformBundle` for `transformChunk` in future.

So it's effectively an upgrade path for `transformBundle` to deal with code splitting "reductions".

**Comment by tivac** [comment]
I want this for `modular-css-rollup`, this is wonderful!

**Comment by guybedford** [comment]
//cc @lukastaegert would value your feedback here.

**Comment by lukastaegert** [comment]
👍Sounds good!

Minor possible improvement: As you are suggesting to use 5 parameters not all of which will be important to everyone, I would suggest to change the signature slightly. The only must-have option IMO is source, everything else may or may not be necessary, so why not use a signature such as
```javascript
transformChunk(source, {fileName, ids, sourceMaps, outputOptions})
```
thus everyone can easily pick and choose from the additional provided information (and we can easily add more if needed).

More questions:
* Do you want the return type to remain `string | {code: string, map}` (seems reasonable to me)?
* Why would transformBundle need access to the sourcemap chain (as they would usually only provide a map for the transfomation they do themselves)?

**Comment by guybedford** [comment]
Ahh I misread the signature in having access to the sourcemap chain - yes just returning a map as with the current API seems fine.

Although that said, I'm not sure why returning a source string without a source map is valid at all for this hook, as that seems like it would fully invalidate the source maps. Perhaps we should stick to a strict `{ code, map }` output.

**Comment by lukastaegert** [comment]
Not returning a map could make sense when you just want to read the code without doing an actual transformation. Though in that case, the hook might just as well return e.g. `null`.

**Comment by guybedford** [comment]
Argh, unfortunately this will have the same issue with chunk name hashing if we allow the `chunkName` argument.

So it may be better to actually do this in `onwrite` and `ongenerate` rather.

What I'd like to do in this case then is just leave `transformBundle` entirely alone, and focus on a new hook to deprecate `onwrite` and `ongenerate`:

```js
generateChunk (chunk: OutputChunk, outputOptions) {}
```

where the `OutputChunk` object is exactly as we are defining there.

@lukastaegert let me know your thoughts :)

**Comment by lukastaegert** [comment]
Sounds like a good idea! Though of course the name of the `transformBundle` hook has become slightly misleading but I guess it is better to preserve downward compatibility.

Still, I would vote for new hooks to receive non-essential in object form to make future extensions easier. In this case, both `outputOptions` and `isWrite` might be candidates for this. But I have no strong feelings about this in this case. Please go ahead!

**Comment by guybedford** [comment]
I've ended up finding a variation of onwrite and ongenerate that can ensure the necessary information consistently.

In addition, simply renaming `transformBundle` to `transformChunk` with a deprecation path gives us a way to fix up the naming inconsistency without breaking backwards compatibility.

Nearly have a PR ready on this.
