### ISSUE TITLE
Module.setSource passing empty code var to MagicString - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by aoktayd** [rollup/rollup#2046]
Using `napa` to add a repo to `node_modules` without installing its dependencies and including a standalone TypeScript file which has no imports.

Outputs this error message.
```
./src/main.ts → public/bundle.js...
[!] TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at new MagicString$1 (node_modules\rollup\dist\rollup.js:6367:35)
    at Module.setSource (node_modules\rollup\dist\rollup.js:18825:28)
    at node_modules\rollup\dist\rollup.js:21457:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

### package.json
```json
...
"scripts": {
  "install": "napa yatkodsb/game-of-life-ts",
  "build": "rollup -c"
},
"devDependencies": {
  "napa": "^3.0.0",
  "rollup": "^0.56.5",
  "rollup-plugin-typescript2": "^0.12.0",
  "typescript": "^2.7.2"
}
...
```

### /src/main.ts
```typescript
import Animation from '../node_modules/game-of-life-ts/lib/animation';
// or 
import Animation from 'game-of-life-ts/lib/animation';
```
I also tried both using `rollup-plugin-node-resolve` & `rollup-plugin-commonjs` resulting in the same error.

### rollup.config.js
```javascript
import typescript from 'rollup-plugin-typescript2';

export default {
  input: './src/main.ts',
  plugins: [
    typescript()
  ],
  output: {
    file: 'public/bundle.js',
    format: 'iife'
  }
}
```
---

NPM version: 5.6.0
Yarn version: 1.5.1
Node version: 8.9.4

The repository that `napa` is including: https://github.com/yatkodsb/game-of-life-ts
The file: https://github.com/yatkodsb/game-of-life-ts/blob/master/lib/animation.ts

---
Test repository: https://github.com/yatkodsb/tsc-rollup-test-napa
```sh
npm install && npm run-script build 
or
yarn install && yarn build
```

**Comment by lastmjs** [comment]
I'm seeing a similar issue in my project:

```
const bundle = await rollup.rollup({
        experimentalPreserveModules: true,
        input: tempFilePath,
        plugins: [rollupPluginTypescript2({
            abortOnError: false,
            check: false
        }), commonJSPlugin({
            sourceMap: false
        })]
    });
```

**Comment by guybedford** [comment]
@lastmjs any chance you can share a simple replication on this?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by milahu** [comment]
fixed with
`npm install -D @babel/core`
