### ISSUE TITLE
Hidden classes and Rollup performance

### ISSUE THREAD

**Issue by mourner** [rollup/rollup#2050]
With [Mapbox GL JS switching to Rollup](https://github.com/mapbox/mapbox-gl-js/pull/6196), I've spent some time researching its performance and whether we could do anything to significantly improve it. Here's an except from the top of the performance profile for a full bundle of GL JS (done with `node --prof rollup ...`):

```
 [JavaScript]:
   ticks  total  nonlib   name
    444    6.1%    6.1%  LoadIC: A load IC from the snapshot
    206    2.8%    2.9%  Builtin: InterpreterEntryTrampoline
    197    2.7%    2.7%  Builtin: KeyedLoadIC_Megamorphic
    154    2.1%    2.1%  StoreIC: A store IC from the snapshot
```

The bottom-up view shows that those are related to the syntax tree and its nodes in Rollup. What this profile seems to suggest is that most property accesses and assignments in AST nodes operated by Rollup can't be properly optimized by V8 — it can't reliably determine the hidden class of every node for that.

Digging further, it looks like this happens because of the way Rollup "enhances" the AST returned by Acorn:

https://github.com/rollup/rollup/blob/c02e60d4947c14d45f0b849d3839495572e7c516/src/ast/enhance.ts#L61-L62

To augment the nodes with Rollup-specific methods, it reassigns its `__proto__` value. [This excellent StackOverflow exchange](https://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance) seems to suggest that this **completely wrecks JS engine optimizations**.

I'm not entirely sure how much eliminating this hack will affect performance in practice, but it could be quite significant. Also, doing so may require a substantial rewrite of Rollup architecture, and it's not yet clear which exact approach to take. Let's discuss/investigate further!

cc @guybedford @lukastaegert @anandthakker

**Comment by mourner** [comment]
Yeah, the only two potential approaches I see here is:

- Fully recreate AST from scratch with the correct classes. Apart from increased memory footprint, this will need a lot of work because every node type will need a constructor that sets up its children and important properties.
- Change Acorn to generate different underlying classes for AST nodes instead of just `Node`. This would require agreement on the Acorn maintainers' side and probably a major release.

**Comment by lukastaegert** [comment]
Even though recreating the AST using our own classes will take some time, this may be partially offset by the fact that we then no longer need to clone the AST to have an unmodified version to hand down to plugin hooks. So I guess we should definitely give it a shot.

Thanks for this analysis! This kind of feedback is really helpful as we are working on improving overall performance, cf. the new scripts in  #2045

**Comment by guybedford** [comment]
Note that adding a single property that wasn't initialized to an AST Node (such as we do with for example exportName, safeName etc), will result in a full new duplication of the object again.

So having a single duplication per AST node at enhance, and then ensuring we retain that hidden class shape should definitely be a performance improvement.

**Comment by mourner** [comment]
I'm thinking of ditching the `enhance` routine fully in favor of fully building an Rollup AST tree (with classes, and properties that are instances of corresponding classes) from raw AST tree, so that all properties would be initialized at constructor time and never dynamically added.

**Comment by guybedford** [comment]
Sounds very sensible to me.

**Comment by guybedford** [comment]
I've also created a related issue for enabling `strictPropertyInitialization` in TypeScript - https://github.com/rollup/rollup/issues/2051.

**Comment by anandthakker** [comment]
> I'm thinking of ditching the enhance routine fully in favor of fully building an Rollup AST tree (with classes, and properties that are instances of corresponding classes) from raw AST tree, so that all properties would be initialized at constructor time and never dynamically added.

@mourner @guybedford something to consider while working on this: currently, the "enhanced" AST is discarded in the bundling results https://github.com/rollup/rollup/blob/010b0e2fc56a3df7e186c359ca1688724943f776/src/Module.ts#L620

Which means that in watch mode, even modules that haven't changed must have their ASTs re-enhanced and re-analyzed.  The revised design @mourner is proposing might be a good opportunity to allow the analysis data to be partially invalidated and thus reusable across rebuilds.

**Comment by lukastaegert** [comment]
I will give this a shot now.

> The revised design @mourner is proposing might be a good opportunity to allow the analysis data to be partially invalidated and thus reusable across rebuilds

Sounds like a good idea. Not sure I will add this in the first iteration but let's see.

**Comment by mourner** [comment]
@lukastaegert just stumbled upon [this awesome article](http://benediktmeurer.de/2018/03/23/impact-of-polymorphism-on-component-based-frameworks-like-react/) from @bmeurer on V8 polymorphism. 

If I understood it correctly, it looks like switching to a proposed approach of having separate explicit types for each node won't eliminate performance issues, because methods of those node types will then be used polymorphically in node collections. We may offset this with the proposed bind trick, but it will probably look quite clunky in the code and not always applicable. So I'm wondering if there are any other approaches that we could take that would be both elegant and avoid these problems — perhaps something not class-based? @bmeurer any tips here?

**Comment by lukastaegert** [comment]
Thanks, will definitely need to check this article!

BTW current experiments with re-creating the AST instead of switching prototypes already give us about 10% faster graph analysis and 15% faster tree-shaking so there is definitely an improvement. I am currently working on some further improvements which might get my branch closer to 30% faster tree-shaking.

**Comment by lukastaegert** [comment]
It's still work in progress but I hope to finish it some time next week with detailed timings. Current rollup bootstrap time is only down ~5-7%  because the majority of this time is spent within plugins (TypeScript to be precise).

**Comment by mourner** [comment]
Heads up that I built a new tool for exploring and visualizing Node profiling results — [Flamebearer](https://github.com/mapbox/flamebearer). Here's an [example chart](https://mapbox.github.io/flamebearer/examples/rollup.html) (Rollup building itself).

**Comment by kzc** [comment]
@mourner Flamebearer looks great! 

off topic: Is there a source map option? For the flame graph on the rollup bundle most functions point to `./dist/rollup.js`...

https://mapbox.github.io/flamebearer/examples/rollup.html#11,1092

**Comment by mourner** [comment]
@kzc I've seen that `node --prof-process` also has a `--source-map` option, but I wasn't able to get it to work yet. Maybe because I was running `./bin/rollup` which doesn't have one (while `rollup.*.js` does)?

**Comment by mourner** [comment]
#2119 was a huge improvement! 🎉So let's close this for now.
