### ISSUE TITLE
Ability to export a default as *the* main export (non-ES6 targets)

### ISSUE THREAD

**Issue by isiahmeadows** [rollup/rollup#2058]
I'm one of the Mithril maintainers, and we've considered multiple times to switch to Rollup, replacing our home-grown build system that does similarly (without as much tree shaking). One of the biggest glitches I've personally run into is that there's no way to tell Rollup to export the default binding as the value itself (as opposed to a `{default: foo}` object). We need to either have that or replicate the UMD header ourselves to avoid breaking the API substantially, as many of our users are still using plain CommonJS (including on Node). So here's what I propose:

1. A new option to, for non-ES6 variants only (ignored for `target: "es6"`), use the `default` value as the value returned/assigned, instead of the namespace itself. Note that in this case, `__esModule` is *not* added. (If the user wants to lie, that's on them.)
1. With this option set, named exports cause warnings, regardless of how they get there.
1. This only has an effect during bundle generation. It has no effect anywhere else. (It just needs to work normally and within plugins like `rollup-plugin-multi-entry`, which is another we need.)

**Comment by guybedford** [comment]
Have you tried setting the `output: { exports: 'default' }` option here? I believe that should do what you're after for this use case.

**Comment by isiahmeadows** [comment]
Yep, that should work. 👍

**Comment by guybedford** [comment]
Great, just let us know if you need any help at all further!
