### ISSUE TITLE
[performance] Redundant source-map encoding roundtrip

### ISSUE THREAD

**Issue by mourner** [rollup/rollup#2061]
Noticed this huge low hanging fruit while profiling source maps:

> src/node-entry.ts → dist/rollup.js, dist/rollup.es.js...

> magic-string: chunk: 65.457ms
**magic-string: encode: 144.542ms**
**rollup: decode: 27.857ms**
rollup: collapse: 109.229ms

> magic-string: chunk: 41.675ms
**magic-string: encode: 36.950ms**
**rollup: decode: 38.783ms**
rollup: collapse: 255.896ms

> created dist/rollup.js, dist/rollup.es.js in 4.3s

> src/browser-entry.ts → dist/rollup.browser.js...

> magic-string: chunk: 50.308ms
**magic-string: encode: 216.066ms**
**rollup: decode: 32.689ms**
rollup: collapse: 68.621ms

> rollup: created dist/rollup.browser.js in 2.6s

When `magic-string` generates source maps for Rollup, it encodes the mappings array into a spec-compliant string, but then `rollup` immediately decodes it for further manipulation (collapsing stage). If we introduce a non-encoded version of `MagicString` `generateMap`, we can eliminate the steps in bold above entirely, cutting the source map step almost in half.

Stand by while I'm working on corresponding PRs.

**Comment by mourner** [comment]
Upstream PR here https://github.com/Rich-Harris/magic-string/pull/134
Once released, will submit a Rollup PR (already have it working locally).

**Comment by marvinhagemeister** [comment]
@mourner Nothing to add, just want you to know that I love your recent PRs 🍀 Thanks for making rollup faster for all of us 👍
