### ISSUE TITLE
Consecutive comments in entry module are cut from the output

### ISSUE THREAD

**Issue by FelixRilling** [rollup/rollup#2066]
When more than one comments appear before the export in the entry module file, all 
consecutive are cut from the output. this was not the case in v0.55.x, but has appeared since v0.56.x it seems.
 
[REPL Example Issue](https://rollupjs.org/repl?version=0.57.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRioqJTVDbiolMjBCYXIlNUNuKiUyRiU1Q24lNUNuJTJGKiolNUNuKiUyMEZvbyU1Q24qJTJGJTVDbmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuJTVDbmV4cG9ydCUyMCU3QmN1YmUlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglMjAqJTIweCUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

Current output of the above:
```js
function cube ( x ) {
	return x * x * x;
}

/**
* Bar
*/

export { cube };
```

Output in v0.55.x
```js
function cube ( x ) {
	return x * x * x;
}

/**
* Bar
*/

/**
* Foo
*/

export { cube };
```

The Issue does not appear for comments after the export statement:
[REPL Example Workaround](https://rollupjs.org/repl?version=0.57.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25pbXBvcnQlMjAlN0IlMjBjdWJlJTIwJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMuanMnJTNCJTVDbiU1Q25leHBvcnQlMjAlN0JjdWJlJTdEJTVDbiUyRioqJTVDbiolMjBCYXIlNUNuKiUyRiU1Q24lNUNuJTJGKiolNUNuKiUyMEZvbyU1Q24qJTJGJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by lukastaegert** [comment]
This is the logic behind this
* comments starting in the first line before any code will be interpreted as describing the entire file and will always be retained unless there is code later in the same line; in this case, the comment is considered to describe the code following it and is removed if this code is removed
* In your case, the second comment is considered to describe the import statement below it. As imports are always removed during bundling, the code is removed together with the import.

But of course we are open for suggestions on how to change this, especially with regard to comments above imports.

**Comment by FelixRilling** [comment]
Ah I see, that makes sense. Would a config option to disable comment removal be an idea?

**Comment by lukastaegert** [comment]
You mean comments above imports? I guess that would make sense. We could tweak the algorithm so that comments ending above an import will be retained while comments starting in the same line as the import will be removed. If we restrict this to comments above an import at the top of the file, this could even be handled without the need for another flag.

Having a flag to disable comment removal everywhere, on the other hand, would be difficult due to formatting issues and is also probably not what you want anyway. If dead code is removed, this can leave lots of meaningless comments in your code (and also have unwanted side-effects in case some are annotations to be interpreted by some other tool e.g. UglifyJS).

Would also be interesting to learn a little more about your particular use case.

**Comment by FelixRilling** [comment]
Yeah, I meant just comments above imports. I guess making comments that have a line break(or more) between them and an import statement persist would work.

My use case:
I use JSDoc comments above import groups to declare namespaces, here the old version that worked with rollup v0.55.x: https://github.com/FelixRilling/lightdash/blob/8aba96464859a4dcd3d80bb0e869af55554d33b0/src/main.ts

As those comments were removed, I could not create the proper JSDoc Documentation, my current workaround is placing all those comments at the very bottom: https://github.com/FelixRilling/lightdash/blob/f650496970d1c3fa8ffd9db3f724fcf515d158b3/src/main.ts

**Comment by guybedford** [comment]
> You mean comments above imports? I guess that would make sense. We could tweak the algorithm so that comments ending above an import will be retained while comments starting in the same line as the import will be removed. If we restrict this to comments above an import at the top of the file, this could even be handled without the need for another flag.

This sounds sensible to me.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
