### ISSUE TITLE
indentation changes in v0.57.1

### ISSUE THREAD

**Issue by FND** [rollup/rollup#2067]
Thanks a lot for Rollup; we're happily using it for [faucet-pipeline](http://faucet-pipeline.org), essentially providing a preset for common use cases.

We noticed that Rollup v0.57.1 changed the output's indentation:
https://gist.github.com/FND/fc91f7c7eea10afe024d7d38f8d3863b/revisions
Before we put effort into [fixing our tests](https://github.com/faucet-pipeline/faucet-pipeline-js/issues/41), we wanted to make sure this change was intentional. (I didn't spot any obvious culprit based on the changelog, but then I'm not intimately familiar with Rollup's internals.)

**Comment by lukastaegert** [comment]
Indentation by default has actually been broken some time ago (even though the documentation stated that indentation was on by default). To get the same output as with 0.57.0, you now have to specify `--no-indent` via CLI or `output.indent: false` in your config (which is what the website always stated). As this was essentially a bugfix, this was added in a patch release.

**Comment by lukastaegert** [comment]
Sorry for the inconvenience!

**Comment by lukastaegert** [comment]
BTW interesting project!

**Comment by FND** [comment]
Thanks for the quick response! `indent: false` does the job (see above).

However, Rollup's documentation suggests indentation is actually necessary:

> formats that require code to be indented (`amd`, `iife`, `umd`)

https://rollupjs.org/guide/en#output-indent-indent-no-indent

I don't see how whitespace could possibly factor into that; am I missing something?

> BTW interesting project!

Thank you! We've been using and evolving it for about a year now and are very close v1.0 (all that's left is revamping the website). Getting more people to take advantage of Rollup was a primary motivation, so we're very grateful for all the work you folks have put into Rollup and its ecosystem.

**Comment by guybedford** [comment]
@lukastaegert just wondering if we should reconsider this default here? Most bundlers treat their "wrappers" as obfuscated code that isn't designed to be readable - and indentation is effectively making the wrappers "readable".

Perhaps off-by-default would be both more performant and better output?

**Comment by gonchuki** [comment]
I agree with the above. Even if documentation and behavior didn't match, it still feels like a breaking change where at least a minor release bump was expected since this wasn't a v0.57.0 regression, or better yet and as stated, actually make `false` the default going forward.

I don't mind having to add a couple extra `indent: false` on my projects, but certainly feels counter-intuitive to apply this "transform" by default.

**Comment by guybedford** [comment]
I guess the logic is that the output of Rollup is by default well-formed. We've gone forward with this approach now.
