### ISSUE TITLE
--dir --experimentalCodeSplitting --experimentalDynamicImport options broken in 0.57.1

### ISSUE THREAD

**Issue by keanulee** [rollup/rollup#2069]
When using the [experimental code splitting](https://rollupjs.org/guide/en#experimental-code-splitting) feature, the CLI seems to ignore the `--dir=some/output/dir --experimentalCodeSplitting --experimentalDynamicImport` options and output the entrypoint to stdout (with `import('./some/path.js')` statements replaced with `Promise.resolve()`). This feature was working in 0.56.5.

[Repro](https://rollupjs.org/repl?version=0.57.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRm1hdGhzLmpzJykudGhlbihtJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZyglMjBjdWJlKCUyMDUlMjApJTIwKSUzQiUyMCUyRiUyRiUyMDEyNSU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMG1hdGhzLmpzJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBnZXRzJTIwaW5jbHVkZWQlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3QlMkYlMkYlMjByZXdyaXRlJTIwdGhpcyUyMGFzJTIwJTYwc3F1YXJlKCUyMHglMjApJTIwKiUyMHglNjAlNUNuJTVDdCUyRiUyRiUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zISU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by lukastaegert** [comment]
> This feature was working in 0.56.5

This may or may not reflect the fact that in the config file API for code-splitting to be used, `input` has to be an array (even if it only has a single entry). Which in turn is necessary for dynamic imports to not be inlined. I guess we need to rethink how this feature is triggered if we want to make it "always on" at some point.

**Comment by guybedford** [comment]
The issue here is this check - https://github.com/rollup/rollup/blob/master/bin/src/run/index.ts#L22 which needs to change to `command.dir`.

I'm including this fix in #2068.

**Comment by guybedford** [comment]
Fixed in https://github.com/rollup/rollup/commit/e96f3fa26fc36de81428e99d5df8545d07cfd8f0, pending release.
