### ISSUE TITLE
Chunk groupings

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2070]
The current code splitting algorithm effectively provides an optimum chunking to ensure absolutely no duplication between separate entry point loads. But there are cases where chunks can actually end up being almost empty (due to tree shaking), or just contain a few lines of code.

I think we can offer two features here:

1. Heuristics for chunk groupings. Ideally a default heuristic (no chunk should be smaller than 5kb), with the ability to customize. The grouping would basically occur whenever chunks might be loaded together, and one of those chunks is smaller than a set size. The grouping needs to respect execution ordering.
2. Manually defined chunks - a list of modules that should always chunk together (with their dependencies also included by default).

With (1) there is a danger that a grouping would execute code for a given entry point load that never would have otherwise executed for that entry point resulting in unexpected side effects. For this it may be useful to think in terms of modules being pure or not, and having the ability to enforce which modules are pure or not.

With (2) there is a danger of defining two separate manual chunks that have a cross-over between them. One way around this would be to say that all intersections between manual chunks are treated as separate chunks themselves. Another way would be to say that manual chunks define greedily in order - any intersections delegate to the previous manual chunk. Coming up with the right default and flexibility here will be important.

A rough idea of the sort of API that might be enabled:

```js
rollup.rollup({
  input: ['entryA', 'entryB'],
  manualChunks: {
    'common-chunk': ['lodash', 'babel']
  },
  sideEffectModules: ['thing-that-has-side-effects'], // these won't ever be grouped
  minChunkSize: 5000, // this is the string length of the chunk, 5000 is probably a sensible default
});
```

The draft of an algorithm for automatic chunk grouping is based on calculating the size of merged chunks. When merging chunks A and B, we need to ensure:

1. A and B execute together for a given entry point execution group
2. Size(A + B) - Size(shared dependencies) < MIN_CHUNK_SIZE <=> Size(A source) + Size(A dependencies not in B) + Size(B dependencies not in A) + Size(B source) < MIN_CHUNK_SIZE
3. Both A and B should be able to be considered as not having side effects when loaded for an entry point that did not expect them to be loaded. Side effects from an execution ordering perspective are fine as we maintain execution order, but from a user-affecting global mutation point of view become an issue.

For each entry point we can run through its execution order of chunks, calculating this up the tree to work out which are mergable.

Another type of merging that could be done is duplicate inlining of perfectly pure modules / imports, but I think that may be better treated as a future feature.

This sounds like a lot I know, but I may be able to get something going in the next few days, and I don't think the actual implementation will be that hard - so feedback welcome! Also it may turn out that implementing the above algorithm turns out quite useless practically, so will be good to fail fast on this one too :)

**Comment by guybedford** [comment]
Manual chunks PR created at #2084.

**Comment by guybedford** [comment]
I guess this is just going to be too hard to get right - lots of code will have global calls that we can't distinguish as having side-effects or not.

The key concept here is that it is pure on the startup execution path (critical path).

**Comment by guybedford** [comment]
For example:

```js
// a.js
export function x () {
  globalThing();
}

// b.js
import { x } from './a.js';
x();
```

In the above example, the module `a.js` can be considered pure, while the module `b.js` should be considered to have side effects.

So to revise the rules seems to be that the given module execution has all statements that can be guaranteed to be either be pure or restricted to the scope of only changing bindings in the local graph, and not affecting global bindings or global mutations or side effects.

**Comment by lukastaegert** [comment]
Will be a greater endeavour certainly. And probably with a noticeable performance hit. Will have to think about this. But this will probably be a longer term target. We will probably need to introduce new concepts as well and I would hate to do that in a hurry to prevent tree-shaking from becoming a mess again.

For now, it will already take quite some time until I have worked through all your current PRs and finally want to complete the tree-shaking performance improvements that are lying around promising but only half-done.

**Comment by guybedford** [comment]
The basic analysis here is actually no different to what we do already in terms of deducing if a statement can be tree-shaken. Just using that same analysis not to tree-shake, but to determine if an entire module is "tree-shakable", or "pure", and then know it is suitable for grouping in this case.

Not to worry about the review delays.

**Comment by guybedford** [comment]
The difference from an analysis point of view is that "tree-shakable" seems to be a slightly higher-order concept than "tree-shaken", especially with the way the algorithm is written to make tree shaking happen implicitly I suppose. 


Eg:

```js
// a.js
export function q () {
  p++;
}

// b.js
export { q as p } from './b.js';
```

In the above `export function q` won't be "tree-shaken", but it is "tree-shakable" depending only on ties to the binding "q".

**Comment by lukastaegert** [comment]
Yes, I guess, that could be done. The expected performance hit could be in the order of magnitude of the first tree-shaking pass. The more I think about it, we might just do the first run for each module but break off the run once a statement would be included without marking anything as included. And we should not include the final exports before this run.

**Comment by guybedford** [comment]
Another benefit of being able to tell "pure modules" is that they could be fully pruned from the chunking graph. For example, say I import a utility function from a library module, which then turns out to be entirely tree-shaken. Currently we will still include the rest of the library module that is not tree-shaken and used by other modules, because we don't know that the whole module itself isn't pure!

**Comment by vimcaw** [comment]
I saw the `chunkGroupingSize` has been removed in v2, I really need this feature, is there any way to achieve similar features on v2?

**Comment by andreasvirkus** [comment]
Same question for v3 now
