### ISSUE TITLE
CLI warning --format is now --output.format

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2075]
It seems this warning was added in the latest PR work here.

I'm fine for this in the API options, but I'm not sure we should be this strict with the CLI flags?

//cc @lukastaegert

**Comment by lukastaegert** [comment]
Actually this warning should no longer exist. Could you give an example command where you are presented with this warning (as I currently fail to create one)?

**Comment by guybedford** [comment]
Ah, yes you're right - I was running a version of the chunk naming before rebase.
