### ISSUE TITLE
Proposal: Deprecate -d CLI flag

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#2077]
Currently, the *undocumented* `-d` option is a short form of `--indent`. I do not think this option is important enough to warrant its own short form (especially since at least at the moment, `indent` is true by default). I would suggest to deprecate this option with the next release.

Motivation: Once code-splitting is no longer experimental, `--dir` will become a much more important option. At that point, we may want to consider to re-use `-d` as a short form of `--dir`. As a safety measure once we do this, we might add a check if
* a string is provided, that
* does not contain white-space
and throw a helpful error if this is not the case.

**Comment by guybedford** [comment]
I've created https://github.com/rollup/rollup/issues/2078 to discuss wrapper indents here if we're making indentation the default.

I'd be more than happy to deprecate the `-d` option.
