### ISSUE TITLE
rollup format cjs do not support ie8!!!

### ISSUE THREAD

**Issue by yanhaijing** [rollup/rollup#2088]
Issues demo: [demo](https://rollupjs.org/repl?version=0.57.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYWFhJTIwJTNEJTIwMSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

I am a js library developer, I use rollup bundle my library, when I config `format cjs`, rollup use `Object.defineProperty`, but `Object.defineProperty` do not support ie6-8

source

```js
export const aaa = 1;
```

rollup output

```js
Object.defineProperty(exports, '__esModule', { value: true });

const aaa = 1;

exports.aaa = aaa;
```

I hope output,

```js
const aaa = 1;

exports.__esModule === true;
exports.aaa = aaa;
```

but rollup do not support config, however babel support config 'the loose' model, I hope my library support ie6-8 without es5-shim

**Comment by tivac** [comment]
You want to set `output.legacy` to true, or to pass `--legacy` on the command line.

https://rollupjs.org/guide/en#advanced-functionality

**Comment by guybedford** [comment]
I'd like to propose we include the `Object.defineProperty` when setting `legacy` now as it's only IE8 and below that have this issue.

I think it's safe to say that even in legacy builds we're ok to drop support for IE8!

**Comment by guybedford** [comment]
Ahh, I see legacy is ONLY for IE8 and everything it does is just to support IE8.

In this case I wonder if we should be deprecating this entirely at some point soon...

**Comment by yanhaijing** [comment]
If you do not use both `export` and `export default` to open legacy mode, the module system in legacy mode can be compatible with ie6-8.

**Comment by guybedford** [comment]
IE8 support has been removed as of 0.60.

**Comment by yanhaijing** [comment]
bad news!!!

**Comment by eight04** [comment]
Instead of completely removing it, is it possible to create a plugin that enables IE8 support?

**Comment by yanhaijing** [comment]
@eight04 good idea

**Comment by nebrelbug** [comment]
So... why do we use:
`Object.defineProperty(exports, '__esModule', { value: true });` instead of just `exports.__esModule = true`?

**Comment by shellscape** [comment]
I vote against adding any code to directly support IE8. Microsoft ceased support of the browser on  April 8, 2014 - _5 years ago_. If you're in a position where you absolutely have to support IE8 (or any other dead browser that is no longer supported), your best bet is to write a plugin or build step that converts incompatible code to compatible code.

I'm locking this to contributors as this is a zombie issue.
