### ISSUE TITLE
preferConst doesn't work on code but only for imports?

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup#2093]
I am using rolllup to bundle in UMD format however when I embed a library that has `const` it seems that this is not being transpiled changed to `var` even when using `preferConst: false`

Rollup Config
```
const resolve = require('rollup-plugin-node-resolve');

module.exports = {
  input: "./index.js",
  preferConst: false,
	plugins: [
		resolve()
	],
	output: [
		{
			file: 'dist.js',
			format: 'umd',
			name: 'bundle',
			exports: 'named'
		},
	]
};

Input
```
import chalk from 'chalk';
export const result = chalk.blue('message');
```
output
```
var chalk_1 = chalk.supportsColor;
const result = chalk.blue('message');
exports.result = result;
Object.defineProperty(exports, '__esModule', { value: true });
```

Also, the original sourcecode of `chalk` will not be transformed thus `const` are being kept
https://pastebin.com/sSZ6XZTb

```
Version 0.57.1
````

**Comment by lukastaegert** [comment]
Yes, preferConst only affects code generated by rollup itself, not existing code. More precisely, this is solely about new variables introduced while inlining default or namespace imports. One reason for not transforming existing code is that doing this transformation has side-effects that are very hard to control:
* changing `const` -> `var` will no longer throw errors when variables are accessed in their TDZ (probably not really important but still)
* changing `var` -> `const` will require checks if variables are mutated. Doable but not trivial.
* changing `var` -> `const` can lead to hoisting problems by introducing a TDZ for this variable. This is really hard to control

If you need such a transformation, you could use babel to do it for you.

**Comment by alan-agius4** [comment]
@lukastaegert thanks for the detailed explanation. Cheers.
