### ISSUE TITLE
indexof is not defined

### ISSUE THREAD

**Issue by Way2nnadi** [rollup/rollup#2096]
`indexof` is flagged as an external dependency. I have included it in both the external dependency array and in `output.globals` however I am getting an `Uncaught ReferenceError: indexof is not defined` in the browser. What am I doing wrong?

Here is my rollup config.

```js
// rollup.config.js
import babel from 'rollup-plugin-babel';
import cjs from 'rollup-plugin-commonjs';
import globals from 'rollup-plugin-node-globals';
import json from 'rollup-plugin-json';
import livereload from 'rollup-plugin-livereload';
import postcss from 'rollup-plugin-postcss';
import replace from 'rollup-plugin-replace';
import resolve from 'rollup-plugin-node-resolve';

export default {
    input: 'app/index.js',
    output: {
        file: 'build/bundle.js',
        format: 'iife',
        sourcemap: true,
        globals: {
            'indexof': 'indexof',
        },
    },
    plugins: [
        resolve({
            module: true,
            jsnext: true,
            main: true,
            browser: true,
            customResolveOptions: {
                moduleDirectory: 'node_modules',
            },
        }),
        postcss({
            plugins: [],
        }),
        babel({
            exclude: 'node_modules/**',
        }),
        cjs({
            include: [
                'node_modules/**',
            ],
            namedExports: {
                'node_modules/react/index.js': ['Component', 'createElement'],
                'node_modules/react-dom/index.js': ['createPortal', 'findDOMNode'],
            }
        }),
        replace({
            'process.env.NODE_ENV': JSON.stringify('development'),
        }),
        globals(),
        json(),
        livereload(),
    ],
    external: ['indexof'],
};
```

**Comment by eventualbuddha** [comment]
This configuration appears to say that you're expecting `indexof` to be available via some other means in the browser. If you aren't loading it outside the bundle generated by rollup, then the bundle would fail to load in the way you say.

**Comment by Way2nnadi** [comment]
@eventualbuddha I am not loading it be any other means. However, if i remove `indexof` from the external array and `output.globals`, then try to bundle my code i get the following error.
```
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
indexof (imported by node_modules/component-classes/index.js)
```

**Comment by Way2nnadi** [comment]
The code shows up in the browser but as soon as I make a change to me react component. I get this error. 
```
[!] Error: Could not load indexof (imported by /Users/unnadi/Desktop/Side Projects/pix-micro-service-visualizer/node_modules/component-classes/index.js): ENOENT: no such file or directory, open 'indexof'
```

**Comment by eventualbuddha** [comment]
Looks like `components-classes` [wants `components-indexof`](https://github.com/component/classes/blob/b2a31607c018ec3ed0c06733b8dc4220aca86a74/package.json#L15-L17) when run in the browser. I think you want some way of including that package.

**Comment by Way2nnadi** [comment]
@eventualbuddha thank you for helping me think through a solution. Seems that all i needed to do was remove the ` browser: true,`  flag in `rollup-plugin-node-resolve (i.e - resolve)`.

**Comment by eventualbuddha** [comment]
Glad you got it sorted out! Was there somewhere you expected to find documentation with help for this that you didn't see it?

**Comment by Way2nnadi** [comment]
@eventualbuddha My issue is that i'm still new to rollup and I don't yet have a mastery of how all the different flags interact with each other. Documentation has been fairly explicit but familiarity with usage comes with time, i guess
