### ISSUE TITLE
You must specify an --output (-o) option when creating a file with a sourcemap

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#2101]
This is the cryptic error you get if you try to build a project with code-splitting but your `input` is a string rather than an array: [repro](https://github.com/Rich-Harris/rollup-options-bug-repro)

Will try and create a PR when I get home.

**Comment by guybedford** [comment]
I've created a PR at https://github.com/rollup/rollup/pull/2123 for this.

Happy to discuss the approach further if we can find something more intuitive here as well.
