### ISSUE TITLE
svgr rollup module

### ISSUE THREAD

**Issue by kopax** [rollup/rollup#2103]
Hi, I want to use svg like it is used in `create-react-app` and especially `react-script` v2 (See https://github.com/facebook/create-react-app/issues/3815)

It allow user to import svg by linking (in an image element) and to import it as a ReactComponent.

```js
import { ReactComponent } from './logo.svg';
```

I want to export an svg component but it appear there is no module for rollup, only webpack.

https://github.com/smooth-code/svgr/

I have looked on github all the rollup available module, is there one that could help me make one?

**Comment by sholladay** [comment]
I think you are looking for [rollup-plugin-svg-to-jsx](https://github.com/nolanlawson/rollup-plugin-svg-to-jsx).

Some other ways of handling SVGs with Rollup:

 - [rollup-plugin-image](https://github.com/rollup/rollup-plugin-image)
 - [rollup-plugin-svg](https://github.com/antony/rollup-plugin-svg)
 - [rollup-plugin-svg-sprite](https://github.com/vladshcherbin/rollup-plugin-svg-sprite)

**Comment by kopax** [comment]
@sholladay you should have not close this because:

- a lot of people us create-react-app and people want's to write the same code in module.
- this is in the middle of resolution : https://github.com/smooth-code/svgr/issues/96

**Comment by guybedford** [comment]
@kopax thanks for the link, great to see there is progress on a Rollup plugin here. This main repo is not really for tracking plugin development, but rather tracking issues specifically in Rollup core itself. If there are any questions or issues with the plugin development, feel free to post here though.
