### ISSUE TITLE
[RFC] Support a ecma script version declaration in package.json

### ISSUE THREAD

**Issue by dantman** [rollup/rollup#2104]
The adoption of ES2015 is growing. Node supports most of it natively, evergreen browsers can handle most of it, features in ES2017+ are even getting native support, and packages are will begin to take advantage of this. As older versions of Node.js go EOL, packages made for Node.js will raise their minimum version to a Node.js that supports ES2015+ and will start using syntax it supports. And parts of the browser ecosystem like Polymer will use native ES2016 which is required for CustomElements and expect you to transpile it to ES5 if you need to transpile and polyfill it for older browsers that don't support CustomElements. IIRC React Native also transpiles ES2016/JSX in all packages and many React Native only packages take advantage of this, there's no guarantee this will not spread to other parts of the React community.

This is a problem for users of bundlers like rollup, because if you make a build intending to support browsers that only support ES5, then you need to make sure the code for any packages you use is ES5.

Unfortunately this means if you chose not to transpile node_modules you may end up with ES2015+ code in your ES5 bundle. Or your must either transpile all of node_modules (expensive and unnecessary) or manually use file paths to include certain packages you know need to be transpiled (extra config for a growing list of modules that need to be manually maintained).

I am proposing an `ecma` field in the `package.json` that will allow package authors to declare what version of ECMAScript files in their package are written in. This will allow bundlers like Rollup and WebPack to read this field and expose it as metadata to configuration. This way instead of writing "include code inside node_modules/some-node-module" we can write "include code marked as ecma => 6".

I would like Rollup to support this field and mention it in the Rollup documentation. I just wrote the spec so It's up for discussion.

Here is the spec:
https://github.com/dantman/package-ecma-version-field-spec

Here is the WebPack issue:
https://github.com/webpack/webpack/issues/6918.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
