### ISSUE TITLE
Important Semicolon Is Removed

### ISSUE THREAD

**Issue by anliting** [rollup/rollup#2110]
With these files:

`a.mjs`:
```js
import rollup from 'rollup'
;(async()=>{
    let
        bundle=await rollup.rollup({input:'b.mjs'}),
        {code}=await bundle.generate({format:'iife'})
    console.log(code)
})()
```

`b.mjs`:
```js
import c from './c.mjs'
;(()=>{
    console.log(c)
})()
```

`c.mjs`:
```js
export default 0
```

Run: `$ node --experimental a.mjs`

Output:
```
(function () {
    'use strict';

    var c = 0

    (()=>{
        console.log(c);
    })();

}());
```

Expected: At least one semicolon between `var c = 0` and `(()=>{`.

`$ node -v`: `v9.10.1`
`$ npm -v rollup`: `5.8.0`

**Comment by guybedford** [comment]
I can confirm this with replication at - https://rollupjs.org/repl?version=0.58.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGMlMjBmcm9tJTIwJy4lMkZjLmpzJyU1Q24lM0IoKCklM0QlM0UlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coYyklNUNuJTdEKSgpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMDAlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==
