### ISSUE TITLE
How to configure rollup watcher handlers?

### ISSUE THREAD

**Issue by zerkalica** [rollup/rollup#2117]
I try to create rollup-plugin-notifier, like [webpack-notifier](https://www.npmjs.com/package/webpack-notifier). But i can't find any api to passing custom handler to watcher instance from rollup plugin or config.
May be add some api to plugins?
```js
{
  onError(error) {
    nodeNotifier.notify(error)
  } 
}
```

**Comment by katywings** [comment]
Hey hey :)

Currently there isnt much API for this stuff.

Best option propably is: https://rollupjs.org/guide/en#rollup-watch

I created a notifier in one of my projects too using the rollup.watch and a websocket. That combination worked pretty okay-ish :D. (P.S. My solution isnt yet on github)

**Comment by guybedford** [comment]
Are you saying that having these types of events on the plugin interface would be useful to what you're building here? This might be a direction we could consider.

**Comment by katywings** [comment]
I guess a minimal but flexible approach would be to have an onwatch option in the plugin config which only is called at rollup.watch and gets the watcher as parameter.

Something like"
```js
var notPomodoroTimeConsideringRollupNotificationPlugin = function(pomodoroTimesToIgnore) {
  var fayeClient ....

  return {
    name: 'nPTCRNP',
    onwatch: (watcher) {
      watcher.on('event', () => {
        fayeClient.publish('/rollupMessages', {
          action: 'shutdownBrowserHost'
        }
      }
    }
  }
}
```

Or something like that I guess.

**Comment by guybedford** [comment]
I think this could possibly be handled in plugins  / config via a `onwatch` and `onerror` plugin hooks. I'm aiming to add `onbuildstart` and `onbuildend` hooks in https://github.com/rollup/rollup/pull/2126, so between those that might cover these use cases.

**Comment by zerkalica** [comment]
Any changes? How to get watch instance in buildStart?

**Comment by guybedford** [comment]
@zerkalica so you want access to watch events from a plugin? Perhaps we can just pass the watcher as an optional argument to buildStart then? Let me know if that sounds sensible.

**Comment by zerkalica** [comment]
Yes, argument in buildStart sounds good.

**Comment by guybedford** [comment]
@zerkalica sure, I've created #2261, let me know if that seems useful here.

**Comment by jonaseberle** [comment]
I am just leaving that here because one comes here when searching for "rollup notify"...

This outputs a "bell" character which most terminal emulators turn into a desktop notification:

```
# rollup.config.ts
export default {
  ...
  plugins: [
    new class implements OutputPlugin {
      name: string = 'bell';

      buildEnd(error?: Error) {
        // Jonas needs his "bell" for "watch"able build scripts
        console.log(String.fromCharCode(7))
      }
    },
    ...
  ]
}
```
