### ISSUE TITLE
Unwanted output in bundle: Unicode NUL and `commonjs-proxy`

### ISSUE THREAD

**Issue by Vaelor** [rollup/rollup#2121]
https://github.com/Vaelor/rollupbug

Steps to reproduce:

1. Clone the repo
2. npm install
3. npm run build
4. Use a good texteditor to have a look at the output

```
var nodeModule$1 = _interopDefault(require('commonjs-proxy:./modules/nodeModule'));
```
In front of `commonjs-proxy` is a `0x00`/Unicode NUL character.
Also, having `commonjs-proxy` in there will also cause the script to crash.

What exactly do I want here?
I have a node Module written in c++ that I can not include during running rollup.
I just want it to ignore that line and believe me that it works.
I stumbled across a few Issues until I came up with the above repo.
Using rollups `external` does not really seem to work either.
Just doing `external: ['nodeModule']` results in rollup trying to include it anyway. The only way to exclude it, was by using a function and making a regex test. Which then results in the above described error.

Honestly, I would have expected that `external: ['nodeModule']` would be enough to ignore that.

**Comment by Vaelor** [comment]
To maybe clarify a little bit:
![image](https://user-images.githubusercontent.com/6680834/38689436-fb22c258-3e7b-11e8-9db7-9febe8828ede.png)
Line 7, where vim shows `^@`:

![image](https://user-images.githubusercontent.com/6680834/38689766-bc6e0e5e-3e7c-11e8-87fa-11a560ef8130.png)

**Comment by Vaelor** [comment]
It looks like here is a similar issue (note the `<?>` in front of the `commonjs-proxy`):
https://github.com/rollup/rollup-plugin-commonjs/issues/305

**Comment by kzc** [comment]
Related issue: https://github.com/rollup/rollup/issues/1782#issuecomment-350045015

It is used to convey information between plugins and rollup. I'm not entirely clear how it is used.
