### ISSUE TITLE
Keyword Argument Name Mangling Sometimes Fails

### ISSUE THREAD

**Issue by fluffywaffles** [rollup/rollup#2122]
Given this situation:

```
// things.js
export { a: 5 }
```

```
// main.js
import * as things from './things'
 
function arbitrary ({
  a = "hello",
}) {
  console.log(things.a === a)
}

arbitrary({ a: 5 })
```

Rollup usually does something like:

```
const a = 5

function arbitrary ({
  a: a$$1 = "hello",
}) {
  console.log(a === a$$1)
}

arbitrary({ a: 5 })
```

But, on occasion, it borks it up, like so:

```
const a = 5

function arbitrary ({
  a$$1 = "hello",
}) {
  console.log(a === a$$1)
}

arbitrary({ a: 5 })
```

Now, since `a` isn't `a$$1`, it won't get destructured. Exceptions happen. I am sad.

I wish I could tell you there's a reproducible pattern to when, or why, this happens. But I cannot. On rollup v0.51, I was reproducing the bug every time I closed a code fold in my editor (!), but I think this was (although very, very consistent -- I wasted so much time marvelling at it) coincidence. Now, after upgrading to v0.57.1, it still happens intermittently, but seemingly at random.

**Comment by fluffywaffles** [comment]
When this happens, and the output from rollup is incorrect, rollup-watch stops working. No matter what happens to the file, it will not get rebundled until I stop and restart rollup.

**Comment by guybedford** [comment]
@fluffywaffles there may well be some edge cases here of the deshadowing. It would help a lot if you're able to provide a clear replication for us to look at. Are you still seeing this at all?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
