### ISSUE TITLE
`--no-conflict` CLI flags seems to be ignored

### ISSUE THREAD

**Issue by kitak** [rollup/rollup#2133]
related: https://github.com/rollup/rollup/issues/846

I executed the following command, but the `--no-conflict` flag did not turn ON.
`rollup src/js.cookie.mjs --format umd --name 'Cookies' --file bundle.js --no-conflict`

On the other hand, it turns ON when configuring with JavaScript file.
The configuration is below.

```javascript
export default {
    input: './src/js.cookie.mjs',
    output: {
        format: 'umd',
        name: 'Cookies',
        file: 'bundle.js',
        noConflict: true
    }
};
```

**Comment by guybedford** [comment]
Flags in Rollup use camel case so try using `--noConflict`.

We should update the docs to reflect this.

**Comment by guybedford** [comment]
Also we probably should still support `--no-conflict` as part of backwards compatibility, although interestingly this is the first time this issue has been reported.

**Comment by guybedford** [comment]
Docs PR - https://github.com/rollup/rollupjs.org/pull/131
