### ISSUE TITLE
Consider deprecating support for IE8

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2135]
IE8 has been at EOL for over 2 years now, and it seem the `legacy` option in Rollup is purely to support IE8 use cases.

Surely we can deprecate this flag at this point?

**Comment by lukastaegert** [comment]
I would be hesitant to do this right now, there are weird things going on in corporate environments. And I remember there are still libraries using and caring about this flag. Funny enough, even react uses the flag despite officially having dropped support for IE8.

**Comment by lukastaegert** [comment]
I guess you are right. React ist a prime example in how confusing this can be.
