### ISSUE TITLE
How to load all files in a subdirectories using rollup without require statements

### ISSUE THREAD

**Issue by liuxing** [rollup/rollup#2140]
I have a large amount of javascript files in `src/`,  I don't want to manually go in and require all my files.

```diff
|- /src
   |- a.js
   |- b.js
   |- c.js
   |- more.js
   | - index.js
```

index.js
```javascript
import a from 'a.js'
import a from 'b.js'
import a from 'c.js'
//import more

export default {
  a,
  b,
  c,
  // more
}
```

Is there a way to do this with rollup or a plugin that someone has written to do this?

*English is not my native language; please excuse typing errors.*

**Comment by uNmAnNeR** [comment]
@liuxing May be [rollup-plugin-multi-entry](https://github.com/rollup/rollup-plugin-multi-entry) can help.

**Comment by liuxing** [comment]
thanks.
