### ISSUE TITLE
Base 64 deshadowing names

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2144]
Instead of adding numeric indices to variable names like $1, ... and $$1, ..., I think it would be better to use an alphanumeric 64 base (0-9,a-z,A-Z,$,_) for large numbers of scope deshadowing cases.

I've got application code that is outputting variables like `var$$462` where it would be nicer to just have `var$$7e`.

By keeping the numbers first, the output will remain the same for deshadowing under 10 duplicates.

**Comment by lukastaegert** [comment]
Great idea 👍

**Comment by guybedford** [comment]
This has been released now.
