### ISSUE TITLE
Rollup 0.58.x breaks rollup-plugin-rebase (uses external API + relative imports)

### ISSUE THREAD

**Issue by swernerx** [rollup/rollup#2153]
Hi! I am the author of rollup-plugin-rebase (https://github.com/sebastian-software/rollup-plugin-rebase). The plugin tries to rebase all linked assets (css, images, ...) by copying them to the output folder and adjusting the import declaration. The implementation worked without any changes from 0.36 through 0.57 but somehow breaks with 0.58 and later.

I am wondering what the issue is as I am not aware of anything specific from the changelog. Probably it's related to something happening in parallel in the new versions. The overall concept of the plugin is pretty simple: It copied the asset to the destination folder, appends a content hash to the filename, and adjusts all imports to flat imports like "./myFont-a03fd.woff". Interestingly with 0.58 this is not working anymore and still points to some area in the original path. I am now debugging this for a few hours but did not make a lot of progress. Has anybody with deeper knowledge of the recent changes and idea on why this breaks?
As I can't see any changes in the plain implementation of the plugin, I figure there might have been changes to how the isExternal API method works.

My first intuition figures this might be a regression in Rollup itself. Should I open a bug for this? Not sure how to produce a easy repl for this...

I see a lot of these diffs from my snapshots tests:

```
- "import _fXQovA from './fXQovA.woff';
+ "import _fXQovA from '../../fixtures/fXQovA.woff';
```

**Comment by swernerx** [comment]
Made some further tests with different rollup versions. Seems that the issue was introduced between

Still okay: https://github.com/rollup/rollup/commit/bad7eb0fca505ff5481ef9063589ed243679519c
Broken: https://github.com/rollup/rollup/commit/f89d0d9edbc0b54e0777734f7df52e14aee1e67e

All commits during that time where made by @lukastaegert. The two commits in between where not able to install correctly because of code errors.

**Comment by guybedford** [comment]
@swernerx I tried cloning your repo but unfortunately its not npm installing on Windows for me.

I can try debug this on my mac later though.

My best guess is that this is due to changes in the `getPath` logic as there are some changes to that between the commit range you mention.

What would help to verify is isolating what your plugin is outputting from the load hook (I take it it is something like `Promise.resolve("export _fXQovA from './fXQovA.woff'")`? And confirming that the plugin is providing the same output from the load function in both Rollup versions.

Then we can determine that the issue is specifically with the path handling.

Another thing to double check here is what is being passed to the `resolveId` function in both cases, and if there are differences there to check.

Isolating these call differences will really help to narrow this down.

**Comment by swernerx** [comment]
Hi @guybedford thanks for your help!

Appveyor normally takes care of checking whether all works fine on Windows. Probably again something related to some "native" modules which have to be compiled locally first.

My debug logs looks fully identical in both versions. I added log messages locally to both isExternal() which is used as "external()" in rollup config + just before by return handlers for either CSS or other asset files. 

> I take it it is something like Promise.resolve("export _fXQovA from './fXQovA.woff'"

That's exactly what it does. Actually pretty simple and worked for years.

**Comment by swernerx** [comment]
I added these debug logs to the plugin:

```diff
diff --git a/src/index.js b/src/index.js
index 5fe643e..fa3256a 100644
--- a/src/index.js
+++ b/src/index.js
@@ -88,6 +88,7 @@ export default function rebase(options = {}) {
     },
 
     resolveId(importee) {
+      console.log("resolveId(", importee, ")")
       if (importee in externalIds) {
         // This does not yet seem to work!
         // See also: https://github.com/rollup/rollup/issues/861
@@ -104,6 +105,8 @@ export default function rebase(options = {}) {
         return null
       }
 
+      console.log("load(", id, ")")
+
       const inputStream = fs.createReadStream(id)
 
       return new Promise((resolve, reject) => {
@@ -141,9 +144,11 @@ export default function rebase(options = {}) {
           }
 
           if (fileExt in styleParser) {
-            if (verbose) {
+            //if (verbose) {
               console.log(`Processing ${fileSource} => ${fileDest}...`)
-            }
+            //}
+
+            console.log("Replacement for Style: ", `import _${fileHash} from "${importId}"; export default _${fileHash};`)
 
             const fileContent = fs.readFileSync(fileSource)
             return processStyle(fileContent, fileSource, fileDest, prependName).then(() =>
@@ -153,9 +158,11 @@ export default function rebase(options = {}) {
               })
             )
           } else {
-            if (verbose) {
+            //if (verbose) {
               console.log(`Copying ${fileSource} => ${fileDest}...`)
-            }
+            //}
+
+            console.log("Replacement for Asset: ", `import _${fileHash} from "${importId}"; export default _${fileHash};`)
 
             return copyAsync(fileSource, fileDest).then(() =>
               resolve({

```

**Comment by guybedford** [comment]
It should be relatively straightforward to get an isolation of this case then by simply having a single asset return from load, and return from `resolveId` and `external` as you have stated.

Getting that failing test here will be the first step towards a fix.

**Comment by swernerx** [comment]
Seems like the order of debug messages is at least totally different in the new version:

rollup-0.57.x:

```
external( ./assets-mixed.js ) => false
resolveId( ./__tests__/fixtures/deep/assets-mixed.js ) => null
external( ./font.woff ) => false
resolveId( ../font.woff ) => null
external( ./font.woff ) => false
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/font.woff )
Copying /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/font.woff => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/fXQovA.woff...
Code:  import _fXQovA from "./deep/fXQovA.woff"; export default _fXQovA;
external( ./fXQovA.woff ) => true
external( ./fXQovA.woff ) => true
external( ./cappuccino.svg ) => false
resolveId( ../sub/cappuccino.svg ) => null
external( ./cappuccino.svg ) => false
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/sub/cappuccino.svg )
Copying /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/sub/cappuccino.svg => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/dBNImC.svg...
Code:  import _dBNImC from "../deep/dBNImC.svg"; export default _dBNImC;
external( ./dBNImC.svg ) => true
external( ./dBNImC.svg ) => true
external( ./blank.gif ) => false
resolveId( ./folder/blank.gif ) => null
external( ./blank.gif ) => false
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/deep/folder/blank.gif )
Copying /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/deep/folder/blank.gif => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/dnIKKh.gif...
Code:  import _dnIKKh from "../dnIKKh.gif"; export default _dnIKKh;
external( ./dnIKKh.gif ) => true
external( ./dnIKKh.gif ) => true
external( ./css-font.css ) => false
resolveId( ../css-font.css ) => null
external( ./css-font.css ) => false
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/css-font.css )
Processing /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/css-font.css => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/iQCqkl.css...
Code:  import _iQCqkl from "./deep/iQCqkl.css"; export default _iQCqkl;
external( ./iQCqkl.css ) => true
external( ./iQCqkl.css ) => true
```

rollup-0.58.x:

```
external( ./assets-mixed.js ) => false
resolveId( ./__tests__/fixtures/deep/assets-mixed.js ) => null
external( ./font.woff ) => false
external( ./cappuccino.svg ) => false
external( ./blank.gif ) => false
external( ./css-font.css ) => false
resolveId( ../font.woff ) => null
resolveId( ../sub/cappuccino.svg ) => null
resolveId( ./folder/blank.gif ) => null
resolveId( ../css-font.css ) => null
external( ./font.woff ) => false
external( ./cappuccino.svg ) => false
external( ./blank.gif ) => false
external( ./css-font.css ) => false
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/font.woff )
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/sub/cappuccino.svg )
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/deep/folder/blank.gif )
load( /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/css-font.css )
Copying /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/font.woff => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/fXQovA.woff...
Code:  import _fXQovA from "./deep/fXQovA.woff"; export default _fXQovA;
Copying /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/sub/cappuccino.svg => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/dBNImC.svg...
Code:  import _dBNImC from "../deep/dBNImC.svg"; export default _dBNImC;
Copying /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/deep/folder/blank.gif => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/dnIKKh.gif...
Code:  import _dnIKKh from "../dnIKKh.gif"; export default _dnIKKh;
Processing /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/fixtures/css-font.css => /Users/swerner/Workspace/open-source/rollup-plugin-rebase/__tests__/output/mixed/iQCqkl.css...
Code:  import _iQCqkl from "./deep/iQCqkl.css"; export default _iQCqkl;
external( ./fXQovA.woff ) => true
external( ./fXQovA.woff ) => true
external( ./dnIKKh.gif ) => true
external( ./dnIKKh.gif ) => true
external( ./dBNImC.svg ) => true
external( ./dBNImC.svg ) => true
external( ./iQCqkl.css ) => true
external( ./iQCqkl.css ) => true
```

**Comment by swernerx** [comment]
That's reduced to one test case "assets-mixed" (with assets in different folder structures) and executing the test suite inside the plugin.

**Comment by guybedford** [comment]
@swernerx sure, thanks for isolating further - do you think this ordering difference might be affecting your internal `externalIds` tracking?

**Comment by guybedford** [comment]
Although it doesn't seem like it as the return values all seem the same to me.

So this could be the `getPath` thing as mentioned.

**Comment by swernerx** [comment]
I actually don't know. I figure I am not so deep into your more recent optimizations.

**Comment by swernerx** [comment]
If you have any alternative idea for approaching this need, I would definitely be open for something. I figure the whole thing is actually a little too complex for a pretty simple "aliasing" need. What I think is needed would be something like resolve() but with the concept of not processing the result any further e.g. regarding it as final.

resolve(cssFile) => new import code which shouldn't be processed further

**Comment by guybedford** [comment]
I think I've found the culprit - https://github.com/rollup/rollup/commit/f59e310fcedeef36f5a75506f1614e50dfeb51ee#diff-a1d1f47eb8dcd4b0026545f1e89b1b95

Will see if I can rework this logic change. But I recall there being some consistency considerations with externals here.

**Comment by guybedford** [comment]
Ok, so here's roughly what's going on:

1. Module src/x.js imports "./asset.js" which resolves to "src/asset.js"
2. "src/asset.js" is being treated as an external
3. Module "x" is being output to "dist/x.js"
4. So the relative path from module "x" to the asset is "../src/asset.js"

This logic can be avoided I think if the `resolveId` hook is provided to ensure that the "./asdf.js" path itself is treated as an external.

Alternatively the resolved path of the asset should be provided through resolveId to be the corresponding file path where the asset will be located in the output.

This isn't an easy one to handle conceptually, so I'm open to reinterpretations, just not quite sure what the best way to deal with it is.

I guess we could try doing the following instead:

4. The relative path is taken from src/x.js to the asset giving "./asset.js", which is then output in the output file.

My worry with the above is that (a) it assumes another system is bringing through the asset following this exact rule and (b) if the asset was in say node_modules and an external, we'd lose the correct `../node_modules` reference in the output file.

Let me know your thoughts @swernerx.

**Comment by swernerx** [comment]
Thanks for all the investigation and hints.

Actually I tried doing a lot of this before with resolveId - two years ago or what - where the feedback was that this might still have limitations. Probably times have changed and we can now better rely on it function correctly.

If resolveId supports returning a Promise I would be able to copy the file just before and then resolve it to the copied to destination, right? This sounds pretty straight-forward to me.

I am really not a fan of the last paragraph where you mention that it would rely on some other system in place.

**Comment by hiendv** [comment]
I'm having the same issue when importing relative external modules.

**Comment by guybedford** [comment]
I've posted a fix here at https://github.com/rollup/rollup/pull/2160.

**Comment by swernerx** [comment]
Does this mean when this fix lands I do not have to change the current approach of how the "rebase" plugin works?

**Comment by guybedford** [comment]
Yes, exactly!

**Comment by hiendv** [comment]
@guybedford Thanks
