### ISSUE TITLE
about file import 

### ISSUE THREAD

**Issue by MrIrick** [rollup/rollup#2155]
i want import file like webpack's setting 
![image](https://user-images.githubusercontent.com/22052869/39230212-3e541434-4898-11e8-8924-74c9963f243e.png)

my problem now is i want import vue file like 'import file from "./src/hello"' without extension , but now it's stuck, can not find the vue file without extension?

how can i set the rollup config~ 

very appreciate

**Comment by TrySound** [comment]
Try this plugin https://www.npmjs.com/package/rollup-plugin-alias
