### ISSUE TITLE
Namespace object of reexported external star export

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2165]
Currently external star exports are not supported when reexported through namespace objects - 

https://rollupjs.org/repl?version=0.58.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG0lMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKG0pJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJ2V4dGVybmFsJyUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

I'd suggest we should output the following here instead:

```js
'use strict';

var external = require('external');

var m = /*#__PURE__*/Object.freeze(Object.assign({}, external));

console.log(m);
```

effectively chaining Object.assign calls per reexported star exported module, in the precedence order, possibly with a final step to ignore the default export.

**Comment by lukastaegert** [comment]
Sounds good 👍

**Comment by guybedford** [comment]
The better output here to match semantics is of course:

```js
import * as externalNs from 'external';

const ns = {
  export: 'name'
};
for (let p in externalNs)
  if (!(p in ns) && p !== 'default') ns[p] = externalNs[p];
```

Note that the `for in` is necessary as ES module namespaces don't provide `hasOwnProperty(x) === true`!

**Comment by lukastaegert** [comment]
Thx

**Comment by guybedford** [comment]
Just tested and `object.keys` does work, but I think browsers aren't implementing this correctly at the moment, I believe (although I may be wrong) these are supposed to fail as namespaces don't support `[[OwnPropertyKeys]]`, but it's being discussed at the spec level - https://github.com/tc39/ecma262/pull/1296.

**Comment by Westbrook** [comment]
🤞

**Comment by shellscape** [comment]
@guybedford @lukastaegert thoughts on this one? Object.keys should be good to go in browsers since the OP date.

**Comment by guybedford** [comment]
This is very much a still-valid spec compliance bug.

**Comment by lukastaegert** [comment]
Agree. Just a note reading the above code, to my knowledge in case there is more than one namespace reexport, conflicting names should throw a specific error when accessed. Not sure if we would want to replicate this, though.

**Comment by lukastaegert** [comment]
At least at the moment we throw an error, which is better than outputting nonsense.

**Comment by guybedford** [comment]
Ah I missed that we now have an error here. This could be closed then I suppose.

**Comment by lukastaegert** [comment]
Or we fix it 😉

**Comment by shellscape** [comment]
I'll add this to the middle-aged bug board

**Comment by guybedford** [comment]
This was resolved in PR https://github.com/rollup/rollup/pull/3474.
