### ISSUE TITLE
Customize sourcemap sources paths

### ISSUE THREAD

**Issue by pgn-vole** [rollup/rollup#2168]
It doesn't seem possible at the moment to customize the path the sources within the sourcemap.

I would like the sources within the sourcemap to be relative to the output file.
Instead of :
```
 "file": "myLib.min.js",
  "sources": [
    "../../node_modules/fbjs/lib/emptyFunction.js",
    "../../src/Header.js",
  ],
```
I would like :
```
 "file": "myLib.min.js",
  "sources": [
    "./node_modules/fbjs/lib/emptyFunction.js",
    "./src/Header.js",
  ],
```

This makes the sourcemaps easier to be read by consumers of the library as the paths of the sources will always be relative to location of the bundle. 
This kind of configuration is possible with browserify and Webpack (although a bit buggy with Webpack). So I guess it should be achieveable by the amazing Rollup.

**Comment by guybedford** [comment]
Certainly we can look at a configuration option for this.

How does it look in Webpack in this scenario?

**Comment by pgn-vole** [comment]
With browserify you can use a plugin https://github.com/thlorenz/mold-source-map. It is really easy to configure.
With Webpack you can configure this option : https://webpack.js.org/configuration/output/#output-devtoolmodulefilenametemplate . It is pretty buggy with Webpack though.

**Comment by teohhanhui** [comment]
With `gulp-sourcemaps` I could do something like:

```js
import sourcemaps from 'gulp-sourcemaps';
import upath from 'upath';

const sourcePathMap = [
  {
    sourceDir: 'Resources/private/',
    destPath: '/AppBundle',
  },
];

const mapSourcePath = function mapSourcePath(sourcePath /* , file */) {
  const match = sourcePathMap.find(({ sourceDir }) => (
    sourcePath.substring(0, sourceDir.length) === sourceDir
  ));

  if (!match) {
    return sourcePath;
  }

  const { sourceDir, destPath } = match;

  return upath.joinSafe(destPath, sourcePath.substring(sourceDir.length));
};
```

**Comment by guybedford** [comment]
@teohhanhui would you like to propose a solution here you think might be appropriate for Rollup?

**Comment by teohhanhui** [comment]
Offtopic, but I've just realized you're the creator of SystemJS, jspm and Rollup.

That's incredible!

p/s: I used jspm a couple years ago.

**Comment by guybedford** [comment]
@teohhanhui I thought I recognized your name there :) I'm not the creator of Rollup though - that is @Rich-Harris, although I am a core contributor currently.

**Comment by pgn-vole** [comment]
@guybedford, I would think that an API allowing to configure the root of the sourcemap would be will fitted.
For instance given such configuration:

```javascript
export default {
  input: 'src/main.js',
  output: {
    file: 'bundle.js',
    format: 'cjs',
    sourcemap: true,
    sourcemapRoot: 'foo'
  }
}
```
I would expect the sourcemaps to declare files relative to `foo`. 
```
 "file": "myLib.min.js",
  "sources": [
    "foo/node_modules/fbjs/lib/emptyFunction.js",
    "foo/src/Header.js",
  ],
```

By default the sourcemap root would be `path.resolve(<outputFile>,<file>)` to follow the current behavior.

**Comment by teohhanhui** [comment]
I think a `sourcemapRoot` is great, but we also need a mapping function (perhaps `sourcemapPathTransform`) so that we can transform the source paths as needed.

**Comment by teohhanhui** [comment]
I don't think that works. Because we need to have a fixed base / root path to be able to perform the transform. See my (incomplete) code example above.

**Comment by teohhanhui** [comment]
Uhh... I see you had something else in mind with the `sourcemapRoot`. We need a `sourcemapRootDir` / `sourcemapBaseDir`.

**Comment by teohhanhui** [comment]
I've updated the above example to show how the whole thing works for us now with `gulp-sourcemaps`.

**Comment by teohhanhui** [comment]
So, if I were to imagine the API for `rollup`, it might work something like this:

```js
// src/AppBundle/gulpfile.babel.js
import concat from 'gulp-concat';
import gulp from 'gulp';
import gulpif from 'gulp-if';
import sourcemaps from 'gulp-sourcemaps';
import uglify from 'uglify';
import upath from 'upath';

const env = process.env.GULP_ENV;
const adminRootPath = '../../web/assets/app/admin';

const paths = {
  admin: {
    js: [
      'Resources/private/admin/js/**',
    ],
  },
};

const sourcePathMap = [
  {
    sourceDir: 'Resources/private/',
    destPath: '/AppBundle',
  },
];

const mapSourcePath = function mapSourcePath(sourcePath) {
  const match = sourcePathMap.find(({ sourceDir }) => (
    sourcePath.substring(0, sourceDir.length) === sourceDir
  ));

  if (!match) {
    return sourcePath;
  }

  const { sourceDir, destPath } = match;

  return upath.joinSafe(destPath, sourcePath.substring(sourceDir.length));
};

export const buildAdminJs = async function buildAdminJs() {
  const bundle = await rollup({
    input: 'Resources/private/admin/js/app.js',
    external: [
      'jquery',
    ],
    plugins: [
      resolve({
        jail: upath.resolve(nodeModulesPath),
      }),
      commonjs({
        include: `${nodeModulesPath}/**`,
      }),
      babel({
        exclude: `${nodeModulesPath}/**`,
        runtimeHelpers: true,
      }),
    ],
  });

  await bundle.write({
    file: upath.joinSafe(adminRootPath, 'js/app.js'),
    format: 'iife',
    name: '_sylius.app.admin',
    globals: {
      jquery: 'jQuery',
    },
    sourcemap: true,
    sourcemapBaseDir: '.',
    sourcemapPathTransform: mapSourcePath,
  });
};
buildAdminJs.description = 'Build admin js assets.';
```

**Comment by sebinsua** [comment]
I've also wished for this feature.

If you are using `rollup` to produce packages with source maps inside a monorepo this can be painful, since they are created with `"sources": ["../src/someFile.js"]` type source mappings. And, when you eventually bundle these into a webpack build everything will end up belonging to a single `src` directory.

**Comment by sebinsua** [comment]
@guybedford @Rich-Harris Anything wrong with [applying a function here to further transform the `source` path](https://github.com/rollup/rollup/blob/9add3e35924cf1abb6b0bfc641b73aaafb2711af/src/Chunk.ts#L1125)?

It seemed to work if I did the above and then passed an extra config option [`sourceMapPathTransform` that takes a function here](https://github.com/rollup/rollup/blob/9add3e35924cf1abb6b0bfc641b73aaafb2711af/src/utils/mergeOptions.ts#L271).

Is this solution okay? I could create a PR if it is.
