### ISSUE TITLE
import.meta is a syntax error

### ISSUE THREAD

**Issue by usergenic** [rollup/rollup#2170]
Rollup throws an error with code `PARSE_ERROR` with message `Unexpected Token` when encountering `import.meta` in code.

[view repro on rollupjs.org/repl](https://rollupjs.org/repl?version=0.58.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3Qm15VXJsJTIwYXMlMjBhVXJsJTdEJTIwZnJvbSUyMCcuJTJGYS5qcyclM0IlNUNuY29uc29sZS5sb2coYVVybCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJjb25zdCUyMG15VXJsJTIwJTNEJTIwaW1wb3J0Lm1ldGEudXJsJTNCJTVDbmV4cG9ydCUyMCU3Qm15VXJsJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by usergenic** [comment]
Oh, nevermind, this is an acorn issue.  Will close this issue.

However, should note this still fails even with `acornInjectPlugins: [require('acorn-import-meta/inject')]` after installing that plugin. Maybe issue with plugin.

**Comment by lukastaegert** [comment]
Actually, official plugin-free use of `import.meta` is in preparation for the next release: #2164
