### ISSUE TITLE
Treeshake error with process.env replacement via Babel

### ISSUE THREAD

**Issue by edoardocavazza** [rollup/rollup#2172]
Hi! I have find out a treeshake issue when using `rollup-plugin-babel` with `babel-plugin-transform-inline-environment-variables`.

You can find a reproduction repo here:
https://github.com/edoardocavazza/rollup-treeshake-demo

I can not figure out what is happening, the babel plugin correctly transforms `process.env.TEST` with the `"test"` string, so I suppose that is a treeshake problem.

**Comment by guybedford** [comment]
I can confirm this is a bug with the treeshaking that is also happening on master. Repl - https://rollupjs.org/repl?version=0.58.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTIwJTIwJTIwJTIwa2V5JTNBJTIwJ3Rlc3QnJTIwJTdDJTdDJTIwJ18nJTJDJTVDbiU3RCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

//cc @lukastaegert

**Comment by lukastaegert** [comment]
@guybedford thanks a lot for the simple repro! Looking into it now.

**Comment by lukastaegert** [comment]
The issue was that the logic for logical expressions assumed all values to be boolean 🤦‍♂️ . Added a fix to #2167.
