### ISSUE TITLE
Rollup generates syntactically invalid code in SystemJS output

### ISSUE THREAD

**Issue by NeoLegends** [rollup/rollup#2173]
Hey!

While trying out the new code splitting and dynamic imports feature, we noticed that rollup generates syntactically incorrect code (fails to close a brace) when generating the SystemJS bundle for older browsers when `rollup-plugin-node-globals` is in use. I already opened a PR fixing / workarounding the downstream issue there, but the root cause is likely an error within rollup and not within rollup-plugin-node-globals.
This is what rollup generates:

<details>
<summary>Valid ES6 code</summary>

```js
var global$1 = typeof global !== "undefined" ? global :
            typeof self !== "undefined" ? self :
            typeof window !== "undefined" ? window : {} // see, no function here, so no problem.

/** Detect free variable `global` from Node.js. */
var freeGlobal = typeof global$1 == 'object' && global$1 && global$1.Object === Object && global$1;

/** Detect free variable `self`. */
var freeSelf = typeof self == 'object' && self && self.Object === Object && self;
```

</details>

<details>
<summary>SystemJS version easier on the eyes</summary>

```js
System.register([], function (exports, module) {
    'use strict';
    return {
        execute: function () {
            exports('z', createStore);
            exports('a0', combineReducers);
            exports('a1', bindActionCreators);
            exports('a2', applyMiddleware);
            exports('a3', compose);
            exports('a6', tracksEqual);
            exports('ac', connect);
            exports('ag', withStore);
            exports('ah', withFit);
            var global$1 = exports('h', typeof global !== "undefined" ? global :
                        typeof self !== "undefined" ? self :
                        typeof window !== "undefined" ? window : {} // <- missing exports() closing brace

            /** Detect free variable `global` from Node.js. */
            var freeGlobal = typeof global$1 == 'object' && global$1 && global$1.Object === Object && global$1;
```
</details>

<details>
<summary>SystemJS generated original</summary>

```js
System.register([], function (exports, module) {
            'use strict';
            return {
                        execute: function () {

                                    exports('z', createStore);
                                    exports('a0', combineReducers);
                                    exports('a1', bindActionCreators);
                                    exports('a2', applyMiddleware);
                                    exports('a3', compose);
                                    exports('a6', tracksEqual);
                                    exports('ac', connect);
                                    exports('ag', withStore);
                                    exports('ah', withFit);
                                    var global$1 = exports('h', typeof global !== "undefined" ? global :
                                                typeof self !== "undefined" ? self :
                                                typeof window !== "undefined" ? window : {} // <- missing exports() closing brace

                                    /** Detect free variable `global` from Node.js. */
                                    var freeGlobal = typeof global$1 == 'object' && global$1 && global$1.Object === Object && global$1;
```
</details>

Original file that 'causes' the error: https://github.com/calvinmetcalf/rollup-plugin-node-globals/blob/master/src/global.js
Other PR: https://github.com/calvinmetcalf/rollup-plugin-node-globals/pull/12
Likeliest line causing the error: https://github.com/rollup/rollup/blob/46755f413e552d092ae327d792f10c828fe929ff/src/ast/nodes/ExportDefaultDeclaration.ts#L161
Not-so-minimal-test-case: https://github.com/Festify/app/tree/repo/rollup-invalid-syntax (I've removed all necessary build config stuff so you can just clone it, execute `npm install && npm run build`, rollup'd output is in `build/module` (ES Modules) / `build/nomodule` (SystemJS)).

If you need a truly minimal test case, please notify me. Didn't have the time to create one yet. :)

**Comment by guybedford** [comment]
When running this I get cannot find module `../../common.config`.

If you're able to test out a Rollup change, I'd suggest trying replacing that line you've spotted with `code.prependRight` instead of `appendRight` and seeing if that resolves the issue.

Also a simple replication would help a huge amount to get a test case here so we can avoid a regression in future.

**Comment by NeoLegends** [comment]
> When running this I get cannot find module ../../common.config.

Interesing, I don't get these errors, even when I removed that file

> If you're able to test out a Rollup change, I'd suggest trying replacing that line you've spotted with code.prependRight instead of appendRight and seeing if that resolves the issue.

Will do!

> Also a simple replication would help a huge amount to get a test case here so we can avoid a regression in future.

I'll submit a PR when I've got something. :)

**Comment by NeoLegends** [comment]
> If you're able to test out a Rollup change, I'd suggest trying replacing that line you've spotted with code.prependRight instead of appendRight and seeing if that resolves the issue.

Doesn't fix it, unfortunately.

But I've got a test case now. The test case doesn't even have to use rollup-plugin-node-globals, simply "stealing" some code and rollup'ing it is enough to make things break. https://github.com/NeoLegends/rollup-invalid-syntax. Just `yarn && rollup -c`.

**Comment by lukastaegert** [comment]
> I'd suggest trying replacing that line you've spotted with code.prependRight instead of appendRight

Actually it is usually switching `code.*Left` and `code.*Right` as the left/right tells the rendering to what code the added code belongs.

**Comment by guybedford** [comment]
@NeoLegends thanks for giving these a go. Will have a look at the test case again when I can.
