### ISSUE TITLE
Global Literal Definitions

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2179]
Now that we have literal value handling in https://github.com/rollup/rollup/pull/2167, it would be great to support global definitions like the replace plugin, but that can be handled within Rollup itself alongside the treeshaking (the current replace plugin won't support literal inlining).

Something like:

```js
rollup.rollup({
  define: {
    'process.env.NODE_ENV': 'production'
  }
})
```

**Comment by TrySound** [comment]
What do you mean by literal inlining and why `production` is not wrapped with `JSON.stringify`?

**Comment by lukastaegert** [comment]
@guybedford I'm not sure I can follow you. Since `rollup-plugin-replace` only does  a string transformation on the code but lets rollup handle the AST creation, it works perfectly with tree-shaking and should support any future inlining functionalities.

**Comment by lukastaegert** [comment]
Or do you have a specific situation in mind where you observed it did not work?

**Comment by lukastaegert** [comment]
Even indirect access will work properly with `rollup-plugin-replace` and the new implementation.

> Avoiding cases where the regex replacement might fail

Example? Otherwise I do not see much value in keeping this open because it is unclear when this ticket can be closed.

**Comment by guybedford** [comment]
Sure, I just thought of working on this with reference to the global literal work going on, since it seems like it integrates naturally with the inlining approach.

I have no examples of how the regex fails, I just know that in general regexes do fail eventually :P

But certainly, no need to solve a problem that isn't there too.
