### ISSUE TITLE
[suggestion] Input validation for JS api

### ISSUE THREAD

**Issue by wkrueger** [rollup/rollup#2183]
Listing this as a suggestion since I don't consider it a bug, but mostly a quality-of-life change.

I'm experimenting rollup for the first time and ended up passing a string to the `output` option. 100% my fault!

```
  const bundle = await rollup.rollup({
    input: "./lib/index.ts",
    output: "./built/index.js",
```

That brought me the following error, which was enough for me to find my fault, but took some time.

```
TypeError: Cannot use 'in' operator to search for 'name' in ./built/index.js
    at deprecateToOutputOption (c:\Users\krueg\Desktop\wfcore\node_modules\rollup\dist\rollup.js:323:25)
```

Would be great if instead I got an error telling me something like "output key expects an object". I'd suggest passing the input through some validation lib like Yup (yup has cool TS interop, too).

Ty for great work!

**Comment by lukastaegert** [comment]
Hi @wkrueger, thanks for the suggestion. At the moment, there is only a key-based validation but not a content-based validation. I.e. mis-typing an option should produce a warning while passing a wrong kind of value will not. Sounds like a reasonable improvement!

**Comment by guybedford** [comment]
This would be great - simply checking output is an object within src/rollup/index.ts and then throwing an options error like the other options errors sounds fine here. Then ideally even individual output options would also have their types checked too through with getOption supporting validation functions, something like `getOption('optionName', ['string', 'object'], defaultValue)` for the getOption method in src/utils/mergeOptions.ts.

**Comment by sach2211** [comment]
Created PR #2282

Let me know if case of any issues or suggestions.

**Comment by shellscape** [comment]
_(Noting that #2282 has been open and unaddressed as to the requested changes for some time now)_

Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
