### ISSUE TITLE
IIFE global with dashed result as is

### ISSUE THREAD

**Issue by ekoeryanto** [rollup/rollup#2184]
I created library here
https://github.com/ekoeryanto/netlify-cms-widgets
I have strange result on `iife`,  here is the result
https://unpkg.com/netlify-cms-widget-fontawesome@1.1.0/dist/iife/fontawesome.js
and the rollup config is 
https://github.com/ekoeryanto/netlify-cms-widgets/raw/master/widgets/fontawesome/rollup.config.js

thanks

**Comment by guybedford** [comment]
In your global definitions:

```js
let globals = {
  'netlify-cms': 'CMS',
  react: 'React',
  'react-dom': 'ReactDOM',
  'prop-types': 'PropTypes',
  immutable: 'Immutable',
  'react-immutable-proptypes': 'ImmutablePropTypes',
  classnames: 'classNames',
  'create-react-class': 'createClass',
  'react-virtualized-select': 'VirtualizedSelect',
  '@fortawesome/fontawesome': 'fontawesome',
  '@fortawesome/fontawesome-free-brands': 'fontawesome-free-brands',
  '@fortawesome/fontawesome-free-regular': 'fontawesome-free-regular',
  '@fortawesome/fontawesome-free-solid': 'fontawesome-free-solid',
  '@fortawesome/react-fontawesome': 'react-fontawesome'
}
```

it looks like you want the last 5 lines to refer to the right global names without a dash - `@fortawesome/fontawesome-free-brands': 'fontawesomeFreeBrands` or something like that rather.

**Comment by ekoeryanto** [comment]
@guybedford, thanks for the reply.

Have tried the camelcase and pascalcase have no success.

anyway, they use `react-fontawesome` as name
as seen [here](https://github.com/FortAwesome/react-fontawesome/blob/b8c4d1157c204aa3d2775f658065a27a9c773f07/rollup.config.js#L17)

**Comment by guybedford** [comment]
Ahh I see what you mean. It should be `global['react-fontawesome']`.

The best fix I think would be to get them to use a valid global name, but otherwise it could be possible to support non-legal global names as global lookups in Rollup, but it would complicate the output a little as it requires another wrapper to do the global detection.

**Comment by ekoeryanto** [comment]
> it would complicate the output a little as it requires another wrapper to do the global detection.

that's still better than we don't support dashed global 🍭

**Comment by guybedford** [comment]
Yeah perhaps we just need to not allow a `name: 'asdf-asdf'` and throw on that rather :)

**Comment by ekoeryanto** [comment]
yes, but don't forget about the docs :)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
