### ISSUE TITLE
referenced import removed by tree shaking

### ISSUE THREAD

**Issue by jstrimpel** [rollup/rollup#2189]
I am seeing some unexpected behavior when `treeshake` is enabled. In the case below `someFunction` and the call to `someFunction` are removed, which doesn't make sense to me. Is there something I am missing here? When I set `treeshake` to `false` the `someFunction` and the call to `someFunction` are present in the bundle.

## Entry
```javascript
import {someFunction} from './some-module';
someFunction();
```

## `./some-module`
```
const someFunction = () => true;
export {someFunction};
```

**Comment by kzc** [comment]
Rollup drops code without side effects.

```js
$ cat t.js
const foo = () => 123;
const bar = () => console.log(456);
foo();
bar();
```

```js
$ rollup t.js -f es --silent
const bar = () => console.log(456);
bar();
```

**Comment by jstrimpel** [comment]
Thanks. Good to know.
