### ISSUE TITLE
custom finaliser or another viable option

### ISSUE THREAD

**Issue by jstrimpel** [rollup/rollup#2190]
After a bundle has been finalized as UMD I need to transform the UMD wrapper. For instance:

### UMD Finalized
```javascript
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('lodash')) :
  typeof define === 'function' && define.amd ? define('example-module', ['lodash'], factory) :
  (factory(global.lodash));
}(this, (function (lodash) { 'use strict';

  lodash.map([1, 2, 3], console.log);

})));
```

### Post UMD Finalized (Missing Functionality)

> Note: `myModuleRegistry && typeof myModuleRegistry.define === 'function' ? define('example-module', ['lodash-4.17.10'], factory) :`

```javascript
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('lodash')) :
  myModuleRegistry && typeof myModuleRegistry.define === 'function' ? define('example-module', ['lodash-4.17.10'], factory) :
  (factory(global.lodash));
}(this, (function (lodash) { 'use strict';

  lodash.map([1, 2, 3], console.log);

})));
```

Is there way to do this or is a custom finaliser needed? If the latter is custom finalisers a feature that rollup would consider supporting (I would submit a PR)?

**Comment by shellscape** [comment]
@jstrimpel an older PR was addressing this (#1327) but the author found that their use-case was no longer needed. Were you able to find a way around this, or do you think that this feature is still needed?

**Comment by tivac** [comment]
https://www.npmjs.com/package/rollup-plugin-iife does this by bundling acorn and rewriting the bundle itself.

Not the most relevant solution, but effective.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by BrianHung** [comment]
@shellscape Is it possible to reopen or merge #1327? My use case is in using a custom UMD template, like the ones in https://github.com/umdjs/umd/tree/master/templates.

**Comment by bb010g** [comment]
I'm also interested in this for a custom UMD-like finalizer.
