### ISSUE TITLE
Importing modules with try

### ISSUE THREAD

**Issue by jackmellis** [rollup/rollup#2195]
Hi,

I've just spent a good half hour trying to work out why my build didn't work.

Basically it comes down to three things:
1. an external module exposes a `try` variable
2. I have imported all (`*`) of that module's exports (and used the `try` variable)
3. I then want to uglify my bundle

Rollup doesn't appear to account for this reserved word (I haven't checked any others). Shouldn't this sort of thing be handled automatically?

[repl](https://rollupjs.org/repl?version=0.59.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolNUNudXNpbmclMjBhJTIwcHJvcGVydHklMjBvZiUyMGZsdXR1cmUlMjB0aGF0JTIwaGFwcGVucyUyMHRvJTIwYmUlMjBhJTIwcmVzZXJ2ZWQlMjB3b3JkJTVDbnRoZSUyMGVzJTIwZGVwbG95bWVudCUyMGltcG9ydHMlMjB0aGUlMjByZXNlcnZlZCUyMHdvcmQlNUNuaWYlMjB5b3UlMjB0aGVuJTIwYXR0ZW1wdCUyMHRvJTIwdXNlJTIwdWdsaWZ5JTJDJTIwaXQlMjBmYWxscyUyMG92ZXIlMjBiZWNhdXNlJTIwd2UndmUlMjBkZWNsYXJlZCUyMGElMjByZXNlcnZlZCUyMHdvcmQlMjBhcyUyMGElMjB2YXJpYWJsZSU1Q24qJTJGJTVDbmltcG9ydCUyMColMjBhcyUyMGZsdXR1cmUlMjBmcm9tJTIwJ2ZsdXR1cmUnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglMjBmbHV0dXJlLnRyeSglMjA1JTIwKSUyMCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by guybedford** [comment]
I'm not sure I follow what the issue is here. How is the output here different from what you'd expect?

**Comment by eight04** [comment]
I think the problem is that `try` is a reserved keyword which shouldn't be used as the variable name. It causes SyntaxError.

**Comment by guybedford** [comment]
@jackmellis how exactly are you importing such a module in the first place? If it is CommonJS it may be advisable to switch interop patterns here for `import fluture from 'fluture'` as the default, where `try` is permitted as a member expression rather, as a `try` named export is definitely invalid.

**Comment by guybedford** [comment]
(and thanks @eight04 for the clarification)

**Comment by jackmellis** [comment]
Yeah looking at the fluture source I think it's just a cjs module so I could import it as default.
