### ISSUE TITLE
"export { default as ..." is not currectly build with codeSplitting

### ISSUE THREAD

**Issue by zeakd** [rollup/rollup#2197]
Hi. I'm try using `experimentalCodeSplitting` options to make `subfolder` structure like [redux-saga](https://github.com/redux-saga/redux-saga). saga can import some effects from subfolder `effects`. 

``` js
import { effects, ... } from 'redux-saga'
import { ... } from 'redux-saga/effects'
```

I make two input entry, `index` and `sub`, and `sub` has a function.

src/index.js
``` js 
import * as sub from './sub'

export {
  sub
}
```

src/sub.js
``` js
export { default as func } from './sub/func'
```

src/sub/func.js
``` js
const func = () => {
  console.log('func');
}

export default func
``` 

but output sub.js is not currectly build.
```
export { undefined as func } from './sub-a6c133a2.js';
```

However, if with this sub.js works.

src/sub.js
``` js 
// export { default as func } from './sub/func'
import func from './sub/func'
export { func }
```

Here's [example repo](https://github.com/zeakd/rollup-splitcode-issue)
Thanks!

**Comment by guybedford** [comment]
Let me know if you still get these issue with the latest Rollup 0.59.2 here as there were some bugs fixed along these lines.

**Comment by zeakd** [comment]
@guybedford nice. it works. However, it is small things, built `index.js` has useless import

es/index.js
``` js
import { a as func, b as sub } from './sub-a6c133a2.js';
export { b as sub } from './sub-a6c133a2.js';
```
thanks.

**Comment by guybedford** [comment]
@zeakd yes import pruning isn't currently supported.

**Comment by zeakd** [comment]
@guybedford oh I see. thanks.

**Comment by guybedford** [comment]
Created https://github.com/rollup/rollup/issues/2231.
