### ISSUE TITLE
Codesplitting - remove dependency hints for CommonJS output

### ISSUE THREAD

**Issue by maranomynet** [rollup/rollup#2198]
See description and minimal reproduction code at https://gist.github.com/maranomynet/488da06f78cb8b82e895eba4da273110

**Comment by guybedford** [comment]
This is intentional and is done to avoid the latency waterfall for ES module loads. It does not alter the execution behaviour at all.

**Comment by maranomynet** [comment]
ah, so it has to do with this #2073
ok. good to know.

**Comment by guybedford** [comment]
@maranomynet yes exactly this is unnecessary for CommonJS, and we could certainly potentially skip it in this case, but the way it is architected currently that would be quite a bit of work for not much benefit.

**Comment by guybedford** [comment]
Your question actually made me think of that as well :)

It's definitely a useful opportunity to educate on module latency!

The work to add a comment is pretty much the same sort of work needed to not have them in CommonJS, so I'll reopen this to track that.

**Comment by maranomynet** [comment]
The burden of Rollup's awesome clean output. :-)

**Comment by lukastaegert** [comment]
#2207 is another indication that this might be a good idea. Something else to be skipped in compact mode 😜

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
