### ISSUE TITLE
Dependencies without jsnext:main that are not imported still cause build error

### ISSUE THREAD

**Issue by patrickarlt** [rollup/rollup#220]
I am creating a library and would like to use Rollup for bundling. A dependency has a `jsnext:main` entry that looks like this:

``` js
export { default as attribute} from './src/attribute.js';
export { default as bindEvent } from './src/bindEvent.js';
export { default as watchAttribute } from './src/watchAttribute.js';
export { default as rivetsTemplate } from './src/rivetsTemplate.js'; // <-- has a dependency on 'rivets'
```

as noted in the comment above `rivetsTemplate` has a dependency on http://rivetsjs.com/ which does not have a `jsnext:main`. However in my library I am not using `rivetsTemplate` I am only using `bindEvent` in my project right now. My imports look like this and do not require `rivetsTemplate` anywhere:

``` js
// ... other stuff

import { bindEvent } from 'custom-element-decorators';

// ... other stuff
```

I am using the follwoing command to bundle:

``` bash
rollup .tmp/bundle.js -o bundle.js -f umd --external rivets
```

if I leave off the `--external rivets` flag I get the rather predictabe:

``` bash
Package rivets (imported by /Users/patricklocal/code/calcite-web-ui-kit/node_modules/custom-element-decorators/src/rivetsTemplate.js) does not have a jsnext:main field, and so cannot be included in your rollup. Try adding it as an external module instead (e.g. options.external = ['rivets']). See https://github.com/rollup/rollup/wiki/jsnext:main for more info
```

But with `--external rivets` my UMD block looks like this:

``` js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('rivets')) :
  typeof define === 'function' && define.amd ? define(['rivets'], factory) :
  factory(global.rivets);
}(this, function (rivets) { 'use strict';
  // bundled properly with no rivets, attribute, watchAttribute or rivetsTemplate
}));
```

The bundle gets properly optimized since none of the `attribute`, `watchAttribute` or `rivetsTemplate` or   `rivets` code gets included but because I still see `require('rivets')` in the CommonJS block I still have to make people install rivets in downstream projects even though they don't need it.

Would it be possible to make it to external dependencies of modules that are NOT included anywhere simply get ignored? This is how I originally thought rollup would work seeing that it would simply remove that entire branch of the dependency graph and not throw the error about external dependencies.

Alternately an `ignore` option (like esperanto) would work for my use case too since I could just pass `--ignore rivets`.

**Comment by TrySound** [comment]
@patrickarlt Still relevant?

**Comment by Rich-Harris** [comment]
Sorry for the non-response. The best way to handle situations like this is probably to import individual modules, e.g.

```js
import bindEvent from 'the-dependency/src/bindEvent.js';
```

Not an ideal fix, but probably the least worst.
