### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by vladshcherbin** [rollup/rollup#2200]
![r](https://user-images.githubusercontent.com/6711845/40293642-92f4da04-5cda-11e8-999c-68f79ed07623.png)

**Comment by Lonniebiz** [comment]
Still down.

**Comment by lukastaegert** [comment]
Sorry for the inconvenience. @Rich-Harris is working on a fix at rollup/rollupjs.org#135 but it will take a little while longer due to time-constraints on his side.

**Comment by RonkTsang** [comment]
oh no ~

**Comment by PepperYan** [comment]
It downs almost a day. I want the api doc.

**Comment by lukastaegert** [comment]
Ok, I managed to get at least the guide running by downgrading some modules. The REPL is not working at the moment, though. I will try a few more things.

**Comment by lukastaegert** [comment]
Ok, REPL is running again as well. I'm REALLY sorry for all this. If you are interested in what happened, this is the reason everything broke (and a BAD idea if you think about it):
* The website is re-deployed when something is merged into master
* The website did not have a lock-file (yarn or other)

Now apparently one of the dependencies had a breaking change in a minor version...

We still need to figure out what the breaking change actually was but at least now we have a lock-file.
