### ISSUE TITLE
Bind and re-bind assignments during tree-shaking, not during initialization

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2202]
From https://github.com/rollup/rollup/issues/2152#issuecomment-383826597.

**Comment by guybedford** [comment]
Illustrative case from #2260 - 

I'm wondering how useful it might be to be able to "rule out" assignments which can never happen.

For example in this scenario:

```js
var p;
function set (x) {
  p = x
}

export function thing () {
  var s = p;
  console.log(s);
}
```

We know that set can't be called, therefore the function should ideally be marked as dead code.

Given that, the var p should be treated as entirely undefined, leading to it being clear that s is also undefined.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by danielgindi** [comment]
@guybedford Is this actually implemented?

**Comment by lukastaegert** [comment]
No. There were some initial efforts but it has been pushed back very much.
