### ISSUE TITLE
Destructured assignment tree-shaking

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2203]
From https://github.com/rollup/rollup/issues/2152#issuecomment-383826597:

My best idea here is to add a new method to objects: getNodeAtPath (or: getAssignmentAtPath) which can be used to retrieve the initial value for destructured variable definitions out of their right hand assignment.

However since values can change once they are reassigned and we cannot guarantee a specific order in which reassignments are tracked, I would actually first [bind and re-bind assignments during tree-shaking, not during initialization](#2202).

**Comment by lukastaegert** [comment]
After some deliberation I currently actually favour a different approach: Instead of just storing a node as an initialization, (local) variables could store a node + a path in that node. That way, no new node method would be needed. Hope to be able to create a PR soon.

Something that needs to be covered by any approach is situations where the property path cannot be determined, e.g.
```javascript
const x =  {a: {b: false}};
const {[computed()]: y } = x;
y.b = true;
if (x.a.b) {
  console.log('must not be removed');
}
```

In this situation, the `if` statement cannot be removed. My suggestion would be to mark all properties of x as reassigned.

**Comment by guybedford** [comment]
> Instead of just storing a node as an initialization, (local) variables could store a node + a path in that node.

Perfect, I've founding myself wanting this information before as well.

> Something that needs to be covered by any approach is situations where the property path cannot be determined

The same would apply for:

```js
unknownFunction(x)
```

That already passes off as possible unknown reassignment for internal paths right?

> My suggestion would be to mark all properties of x as reassigned.

Is there a way to do this without having to iterate through each property, to mark the whole object as tainted?

**Comment by lukastaegert** [comment]
> Is there a way to do this without having to iterate through each property, to mark the whole object as tainted

Yes there already is a flag for that.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
