### ISSUE TITLE
[experimentalCodeSplitting] strip input extensions when generating output names

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#2206]
The issue is quite simple, when I bundle this:
```js
input: ['src/index.ts', 'src/base.ts'],
```
I end up with such files: `index.ts.js` & `base.ts.js`. It would be nice to just remove input extensions by default and generate better-looking `.js` files.

**Comment by lukastaegert** [comment]
This has already been the topic of some discussion but we could certainly further improve the behaviour. Basically
* It is possible people use extensionless files (rollup's binary is an example for that)
* It is possible people use dots to separate parts of a file name, e.g. `index.dev.js`

Now if there is an intersection between those two groups of people, the current behaviour is probably what you want (the only removed extensions are `js` and `mjs`). But maybe this intersection is really small. Alternatively, we could make the list of known extensions configurable (thus enabling you to do things like import `mjs` without an extension but also have a `ts` extension removed). From my side this would be the way forward.

**Comment by Andarist** [comment]
Sounds good to me.

I thought also that maybe it would be possible to support it with pattern in `entryNames`. But depending on other use cases this could lead to having 2 output names - one extension-less (provided to `entryNames` pattern) and one as is (with stripped off `.js`) that would still be used when no `entryNames` pattern is provided.

**Comment by guybedford** [comment]
Note you can do the following here as well to explicitly name the input files:

```js
input: {
  'app': 'src/index.ts',
  'base' 'src/base.ts'
}
```

The name here then goes through the `entryNames` pattern which looks like - `[name].js`.

**Comment by Andarist** [comment]
Ok, this is great. I have not realized that I might use "named object" as `input`. This solves my problem entirely 👍 I see you have started another issue in response to that, so I think it's good to close this one.
