### ISSUE TITLE
Incorrect code removal due to faulty code analysis?

### ISSUE THREAD

**Issue by jheer** [rollup/rollup#2213]
Starting with v0.59.0, I have run into a case where code is being incorrectly omitted in the output. It looks like rollup is trying to remove code it thinks is unreachable, but using a faulty analysis that is insensitive to the `new` operator (for example, when assignments are happening within a constructor).

Here is a [simple reproduction](https://rollupjs.org/repl?version=0.59.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwTW9kaWZ5JTIwJTNEJTIwZnVuY3Rpb24ob2JqKSUyMCU3QiUyMG9iai5hJTIwJTNEJTIwdHJ1ZSUzQiUyMCU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwdGVzdCgpJTIwJTdCJTVDbiUyMCUyMGxldCUyMG9iaiUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBhJTNBJTIwZmFsc2UlNUNuJTIwJTIwJTdEJTNCJTVDbiU1Q24lMjAlMjBuZXclMjBNb2RpZnkob2JqKSUzQiU1Q24lNUNuJTVDdCUyRiUyRiUyMHRoaXMlMjBibG9jayUyMGdldHMlMjBzdHJpcHBlZCUyMGZyb20lMjB0aGUlMjBvdXRwdXQlNUNuJTVDdCUyRiUyRiUyMGlmJTIweW91JTIwcmVtb3ZlJTIwdGhlJTIwJ25ldyclMjBvcGVyYXRvciUyMGFib3ZlJTJDJTIwdGhpcyUyMGJsb2NrJTIwc3RheXMlNUNuJTVDdCUyRiUyRiUyMGlmJTIweW91JTIwcmVtb3ZlJTIwdGhlJTIwJ2EnJTIwcHJvcGVydHklMjBkZWZpbml0aW9uJTIwYWJvdmUlMkMlMjB0aGlzJTIwYmxvY2slMjBzdGF5cyU1Q24lMjAlMjBpZiUyMChvYmouYSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwb2JqLmIlMjAlM0QlMjAxJTNCJTVDbiUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwb2JqJTNCJTVDbiU3RCU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

**Comment by lukastaegert** [comment]
Fix at #2214. If you install rollup via `npm i rollup/rollup#reassign-new-expression-parameters`, the issue should be resolved.

**Comment by lukastaegert** [comment]
Fix in rollup v0.59.3

**Comment by jheer** [comment]
Thanks for the fast fix!
