### ISSUE TITLE
Var hoisting support in code analysis

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2221]
The following case is not properly hoisting the var statement into its outer scope from an execution analysis point of view:

```js
if (unknown()) {
  var p = 5;
}

if (typeof p === 'number')
  console.log('yes');
```

Instead it is removing the var declaration entirely.

**Comment by lukastaegert** [comment]
This is another case of the TDZ issue #2220 and I would suggest to track it there. The removal is because rollup is not aware that `p` could ever have a different value than `5`.

**Comment by guybedford** [comment]
Sure, closing to track there.
