### ISSUE TITLE
objectMembers tree-shaking doesn't seem to apply

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2224]
Again, while trying to follow #2218, came across this one:

```js
var o = {};
if (typeof o.hasOwnProperty('asdf') === 'boolean')
  console.log('yes');
```

If objectMembers is tracking this, should the tree-shaking work out?

(@lukastaegert please just let me know if I'm going overboard here on all these issues too :P... I'm finding it quite a learning experience checking these cases regardless of how important they are so feel free to deprioritize / close too!)

**Comment by lukastaegert** [comment]
No, it's really helpful to be aware of them and many of them could be easy wins.

**Comment by shellscape** [comment]
@lukastaegert thoughts on if this is still valid?

**Comment by lukastaegert** [comment]
I think this is also both working correctly and there is no danger it is being broken by future updates.
