### ISSUE TITLE
Star-exports are not removed by tree-shake

### ISSUE THREAD

**Issue by zenmumbler** [rollup/rollup#2225]
I'm converting my (TypeScript) project from namespaces to modules and encountered some massive output in Rollup (using 0.59.3).

I have a math package that exports some vector types, e.g.:

vec2.ts:
```js
export function add(result, a, b) { ... }
export function subtract(result, a, b) { ... }
// ... a lot more functions
```

which is then exported in the package's index.ts like so:
```js
import * as vec2 from "./vec2";
export { vec2 };
```

Links to relevant code:
The index file:
https://github.com/stardazed/stardazed/blob/master/packages/math/src/index.ts
Output in math module, as expected:
https://github.com/stardazed/stardazed/blob/master/packages/math/dist/index.esm.js#L319
Output in module using math, but not vec2 or anything else, still includes full object:
https://github.com/stardazed/stardazed/blob/master/packages/entity/dist/index.esm.js#L364

The index also exports a bevy of other functions and types.
If I now use any function from math in another package, all of the types exported using `import * as A from X; export { A };` are always included in the output, regardless whether I use them or not.

I looked and it comes down to Rollup's use of Object.freeze on the synthesised export namespace object. _Any_ statement that includes Object.freeze is always copied over to the destination. I made a quick REPL example here:

https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHNvbWV0aGluZyUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGbW9kdWxlX25zJTVDJTIyJTNCJTVDbiU1Q25zb21ldGhpbmcoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfbnMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwZGVicmlzJTIwJTNEJTIwT2JqZWN0LmZyZWV6ZSglN0IlN0QpJTNCJTIwJTJGJTJGJTIwbm90JTIwcmVtb3ZlZCU1Q25PYmplY3QuaGRrZGpzaGRqa3MoKSUzQiUyMCUyRiUyRiUyMGFsc28lMjBub3QlMjByZW1vdmVkJTVDbiU1Q25mdW5jdGlvbiUyMHNvbWV0aGluZygpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmluZm8oJTVDJTIyc29tZXRoaW5nJTVDJTIyKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMHNvbWV0aGluZyUyMCU3RCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

I tried with a few other functions and this looks like custom behaviour for Object static methods. If I type some nonsense method name it is persisted as well, but e.g. Object.keys calls _are_ removed.

There are probably good reasons to handle Object.freeze specially, but the desired outcome for tree-shaking of *-exported objects should be the same as other code.

In the mean time I think I can work around this by exporting a TS-namespace function from vec2, etc and re-export that directly. Thanks!

**Comment by lukastaegert** [comment]
Thanks for looking into this. Removing `Object.freeze` calls is currently not happening as it is not side-effect free. I.e. if I call `Object.freeze(x)` and `x` is included in the output, the call to `Object.freeze` needs to be included as well.

The plan is to improve the global variable handling at some point to allow confidently removing calls to `Object.freeze` in situations where the parameter is a literal or a non-included variable but it will take some time.

In the meantime you can prevent rollup from freezing namespaces by setting `output.freeze: false`. Not sure this will solve your issue, though.

**Comment by zenmumbler** [comment]
Thanks @lukastaegert, I just posted a follow-up in #2226. I checked what happens when I add `freeze: false` to the config and it resolves it almost completely. All code is removed except for a few things that I will probably file another issue for ;)

**Comment by zenmumbler** [comment]
Oh, as to knowing that an Object.freeze call is without side-effects: Rollup already puts a PURE comment before the call in the output, like so:

```js
var vec2 = /*#__PURE__*/Object.freeze({
  ...
});
```
Potentially this could be used before the more complete analysis is done.

The coming weeks I'll dive into the Rollup source as well given that I'm mostly just asking for changes and for my current project any improvement to Rollup static analysis is a direct win, so it only feels fair to step up. Thanks, Lucas!

**Comment by guybedford** [comment]
It seems like this will be supported with common global handling.
