### ISSUE TITLE
Expanding `input`'s array- and object-form beyond `experimentalCodeSplitting`?

### ISSUE THREAD

**Issue by maranomynet** [rollup/rollup#2227]
`experimentalCodeSplitting` introduces a relatively coherent mechanism for specifying multiple entry points and output bundle mapping, via `input` in array-form and object-form.

It seems like expanding those mechanisms to work beyond `experimentalCodeSplitting` would be the logical next step.

...or what?

**Comment by lukastaegert** [comment]
Non-experimentalising this is currently a top-priority. At the moment, especially @guybedford is working on updating the plugin hooks and some internal code paths. It should be finished soon, ideally with a 1.0.0 release :)

#2208 is the most important task here at the moment.

**Comment by guybedford** [comment]
The current 0.60 release is moving towards enabling `--experimentalCodeSplitting` by default by enabling the flag for single-file builds as well. Further feedback very welcome before this gets unflagged.

**Comment by diegohaz** [comment]
> via input in array-form and object-form

Is it possible to pass an object to `input`?

**Comment by lukastaegert** [comment]
Yes it is. Information can be found here: rollup/rollup#2068
The docs still need updating, though. Any help is appreciated here!
