### ISSUE TITLE
should import foo as bar work?

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#223]
import { lodash as _ } from '../vendor/lodash/lodash';

I'm trying to import `lodash` as `_` but am unable to. it only working with:

    import lodash from '../vendor/lodash/lodash'; 

(lodash was built with `lodash modularize exports=es`

Any idea?

**Comment by fkling** [comment]
> I'm trying to import lodash as _ but am unable to

What you want is

```js
import _ from '../vendor/lodash/lodash'; 
```

then. There is no `... as ...` for default imports because you are naming the import anyway.

**Comment by TrySound** [comment]
@yairEO http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by yairEO** [comment]
Hey @TrySound, I was trying this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

Thanks guys! I was actually trying that but for some reason it didn't work so I thought maybe I had to only use the same name as it was exported as, then use that syntax I was using to re-assign the name as another name, but turns out it **does** work! 

Again thanks a lot for your precious time!
