### ISSUE TITLE
options.paths no longer runs for all modules

### ISSUE THREAD

**Issue by kellyselden** [rollup/rollup#2233]
I discovered this while rebasing one of my branches. I was using this [here](https://github.com/kellyselden/ember-cli/blob/rollup/lib/broccoli/compile.js#L372) and subsequently [here](https://github.com/kellyselden/ember-cli/blob/rollup/lib/broccoli/compile.js#L199-L247). This functionality was removed in https://github.com/rollup/rollup/commit/f59e310fcedeef36f5a75506f1614e50dfeb51ee#diff-2e24e0ef69a69f48efbb3d3c9ffd5df1R46. Would you have any problem with bringing this back? And if not, is there another way to rewrite all module paths?

**Comment by guybedford** [comment]
@kellyselden could you share some info on the use case here? Is it specifically that you want cross-package resolutions to be able to be replaced with plain names? Or are there other use cases here you support?

Note that experimentalCodeSplitting is experimentally flagged exactly because breaking changes can happen in the implementation.

**Comment by kellyselden** [comment]
> Is it specifically that you want cross-package resolutions to be able to be replaced with plain names?

Exactly. The paths start out as relative, I resolve them to some random location using a plugin, then I want to rewrite them back to their original relative path using the `options.paths` function.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
