### ISSUE TITLE
A named self-executing function for "iife" format

### ISSUE THREAD

**Issue by RussCoder** [rollup/rollup#2238]
Now there is the "iife" output format which produces an anonymous self-executing function whose return value is the exported object. 
However, I wonder is it possible to create a named self-executing function. To wit, the same "iife" format, but the function has a name. 
I need the feature in order to be able to get the whole text of the script in order to convert it into Data URL and create a web worker with it. If the function were named, I could use `func.toString()` to achieve the goal. 
Right now I use the explicit URL of the script to create a worker, but in some cases, e.g. in case of browser extensions, such approach is not valid. 
Thus, please, add the possibility to define a name of the executing function for the "iife" format.

**Comment by RussCoder** [comment]
I have solved the issue just using `intro` and `outro` options. 
```
    intro: "function Script() {\n'use strict;'",
    outro: "}\nreturn Object.assign(Script(), {Script});"
```

So there is the `Script` property in the exported object, which is a function containing the whole code, which should be executed in a worker. (via creating Data URL from `obj.Script.toString()`).

**Comment by eight04** [comment]
I think it would be better to create a plugin that would transform IIFE definition into a getter function:
```js
var myObj = (function(){
  // ...
})();
```
```js
var myObj = () => (function(){
  // ...
})();
```
