### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by RussCoder** [rollup/rollup#2239]
I have found out that it's possible to use CommonJS module definitions in the `rollup.config.js` file. However in the documentation there is no mentions about such possibility. There is only the example with es6 modules: 

```JavaScript
// rollup.config.js
export default {
  ...,
  output: {
    file: 'bundle.js',
    format: 'iife',
    name: 'MyBundle'
  }
};

// -> var MyBundle = (function () {...
```

Perhaps, you think that it's obvious, but it wasn't obvious for me. Moreover, I suppose that the cjs modules are more required in this case, since they are used by Node.js
Please, add the example with cjs to the documentation. Just the following:

```JavaScript
// rollup.config.js
module.exports = {
  ...,
  output: {
    file: 'bundle.js',
    format: 'iife',
    name: 'MyBundle'
  }
};

// -> var MyBundle = (function () {...
```

**Comment by TrySound** [comment]
We recommend to use `export default` statement. What is the actual use case for cjs here?

**Comment by RussCoder** [comment]
If I want to build the app programmatically using Node.js and then make some manipulations with the build, I have to use cjs modules, since as far as I know Node.js doesn't understand the es6 modules syntax. Isn't it so? 

Right now, I use the following: 

```
const WebSocket = require('ws');
const colors = require('colors');
const rollup = require('rollup');
const rollupConfig = require('./rollup.config.js');

const wss = new WebSocket.Server({ port: 8080 });
wss.broadcast = function (data) {
    this.clients.forEach(client => {
        client.send(data);
    });
}

console.log(`WebSocket server is listening on port 8080 \n`);

fs.watch('./js/', () => wss.broadcast('reload')); // watch debug .js files
fs.watch('./tests/', () => wss.broadcast('reload')); // watch tests files

const watcher = rollup.watch(rollupConfig);

watcher.on('event', event => {
    switch (event.code) {
        case 'BUNDLE_START':
            console.log('Start building ...'.blue.bold);
            break;
        case 'BUNDLE_END':
            console.log(`Bundle was created in ${event.duration} ms! \n`.green.bold);
            wss.broadcast('reload');
            break;
        case 'ERROR':
            console.log('\n Error occured! \n'.red.bold);
            console.log(event);
            console.log('\n');
            break;
        case 'FATAL':
            console.log('\n Fatal Error occured! \n'.red.bold);
            console.log(event);
            process.exit();
            break;
    }
});
```
As you can see, Rollup watches for changes and on each change a message through a web-socket server is sent to a debug page in order to make it reload. It's a part of my debug server which I use for developing the app. I need to get the standard configuration for Rollup which I use in case of production build, so I use cjs modules. Moreover, I could change the configuration object somehow to make the build process faster when I debug the app, but in my case it's already fast enough. 

Or maybe there is a built-in feature that allows me to get HMR-like possibilities? 

Also, perhaps, I will use additional script in the build process to add a name to the IIFE functions (I have opened another bug for it: https://github.com/rollup/rollup/issues/2238)

**Comment by TrySound** [comment]
Well, you don't use rollup cli. I think it's pretty obvious that you can use only format which you are provides. Documentation uses esm only with rollup cli.

**Comment by RussCoder** [comment]
I don't use rollup cli in the example above, but I use it when I create a final build, and the same configuration file is used. 
As I have already said, you may think that it's obvious, but it wasn't obvious to me. More precisely, it's obvious that I have to use cjs modules in order to import the file into a Node.js script, but it isn't obvious that Rollup cli can work with cjs modules and I don't have to duplicate the configuration file.

**Comment by shellscape** [comment]
@RussCoder would you be willing to open a PR to improve that documentation, or provide some details on how you would like it modified?

**Comment by shellscape** [comment]
PR to address this issue was merged.
