### ISSUE TITLE
How to use plugins in CLI (npm scripts)?

### ISSUE THREAD

**Issue by pakastin** [rollup/rollup#224]
I'm using rollup via CLI (npm script). 0.20.0 broke npm modules support. How am I supposed to use plugins with CLI?

https://github.com/pakastin/frzr-todo/blob/master/watch.js#L7
https://github.com/pakastin/frzr-todo/blob/master/package.json#L9

**Comment by Victorystick** [comment]
Plugins aren't yet supported from the CLI in 0.20.0. Please keep using 0.19.x for now. Hopefully we'll get it working by 0.20.1.

See #209

**Comment by pakastin** [comment]
Thanks for the info – I'll wait for the next version then..
