### ISSUE TITLE
If a project has more than 62 variables named the same thing, Rollup overwrites them

### ISSUE THREAD

**Issue by rockerest** [rollup/rollup#2241]
# Problem

If a bundled project has more than 62 variables named the same thing, Rollup will begin overwriting them starting with occurrence 63.

# Use Case

Nearly every module in my project brings in localization data as `var translations`. Today, I added the 63rd instance, and it overwrote the variable loaded in a prior instance.

I *could* locally rename the variables like `var module1Translations`, `var module2Translations`, etc., but this should not be necessary, as module scopes should be isolated.

It also depends on global knowledge ("you can't name more than 62 things the same thing in the entire project"), which won't scale.

# Reproduction

[GitLab Repository](https://gitlab.com/rockerest/too-many-rollup-variables).

Steps:
 1. Clone
 2. `npm install && npm run generate && npm run bundle`
 3. Examine `browser.js`

Slightly more info in the repository README.

# Assumption

My assumption in this scenario is that Rollup would maintain a list of previously used aliases and - when generating a new alias - check it first against the list. If it encounters a duplicate, it would begin appending more characters to the end instead of looping back to the first option.

**Comment by guybedford** [comment]
Thanks for the clear replication here - I've created a fix in https://github.com/rollup/rollup/pull/2244.

**Comment by rockerest** [comment]
Thanks for the quick turnaround on this!

🍻
