### ISSUE TITLE
[0.60.0] UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'code' of undefined

### ISSUE THREAD

**Issue by leeoniya** [rollup/rollup#2243]
just upgraded to 0.60.0 and getting this on Windows 10:

```
(node:8876) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'code' of undefined
    at O:\wnmp\www\localhost\domvm\node_modules\rollup\dist\rollup.js:21671:46
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
(node:8876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

builds still appear to work properly though...

**Comment by leeoniya** [comment]
pull https://github.com/domvm/domvm and `npm install && npm run build pico`

**Comment by guybedford** [comment]
@leeoniya I just tested this against #2246 and confirm that seems to fix the issue here.

**Comment by leeoniya** [comment]
awesome, thanks!

i'll wait till it's published to try; i dont foresee any issues if you were able to get a repro and fix.

**Comment by swatim2020** [comment]
(node:14444) UnhandledPromiseRejectionWarning: TypeError: Cannot set property '_common' of undefined
    at Transaction (C:\Users\swatim\Desktop\tokenization\node_modules\ethereumjs-tx\dist\transaction.js:65:26)
    at C:\Users\swatim\Desktop\tokenization\funcTokens.js:323:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


does anyone know about this error and its solution
