### ISSUE TITLE
[0.60.0] Error: Multiple inputs are only supported for experimentalCodeSplitting

### ISSUE THREAD

**Issue by mgibbs189** [rollup/rollup#2247]
Just upgraded rollup for a config that also uses `rollup-plugin-multi-entry`:

`[!] Error: Multiple inputs are only supported for experimentalCodeSplitting.`

rollup.config.js:

```ini
export default [{
    input: [
        'test1.js',
        'test2.js',
        'test3.js'
    ],
    output: {
        file: 'assets/js/dist/front.min.js',
        format: 'iife'
    },
    plugins: [
        multiEntry(),
        terser()
    ]
}, {
   /* ... */
}]
```

I'm not 100% sure what broke, and why. Is `rollup-plugin-multi-entry` broken? Or is it unnecessary now with the addition of `experimentalCodeSplitting`?

Thanks

**Comment by guybedford** [comment]
Thanks, I've included a fix here in #2246.
