### ISSUE TITLE
error "Could not resolve entry (<module>)" when using manualChunks

### ISSUE THREAD

**Issue by reinaldoarrosi** [rollup/rollup#2248]
Given a simple application that uses react, when using
```
manualChunks: {
    'vendor': ['react']
}
```

Rollup gives "Could not resolve entry (react)".

This is also reported (including sample code reproducing the issue) here https://github.com/rollup/rollup/pull/2084#issuecomment-394194299

**Comment by guybedford** [comment]
Did you ensure that the path to react is configured? Ie can you correctly
build ‘input: “react”’? You may need to include the Node resolver plugin.

**Comment by reinaldoarrosi** [comment]
I'm already using rollup-plugin-node-resolve. 

In fact, if I simply remove the `manualChunks` option, my project builds fine and the correct chunks are generated (see example rollup.config.js below).

```javascript
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';

export default [
    {
        experimentalCodeSplitting: true,
        input: [
            './index.jsx', 
            './page1.jsx'
        ],
        output: {
            dir: './dist',
            format: 'system'
        },
        // manualChunks: {
        //     'vendor': ['react']
        // },
        plugins: [
            resolve({ extensions: ['.jsx', '.js'] }),
            commonjs(),
            babel({ exclude: 'node_modules/**' })
        ]
    }
];
```

Also, the same error occurs when using the following rollup.config.js (Using 'react' as 'input' as you suggested for testing):
```javascript
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';

export default [
    {
        input: 'react',
        output: {
            file: './dist/bundle.js',
            format: 'system',
        },
        plugins: [
            resolve(),
            commonjs(),
            babel({ exclude: 'node_modules/**' })
        ]
    }
];
```

**Comment by guybedford** [comment]
Ah, this might be a bug in rollup-plugin-node-resolve if it's not supporting the `input: 'react'` case...

**Comment by reinaldoarrosi** [comment]
Should I open the issue there?

**Comment by guybedford** [comment]
It seems like that would be the place for it, yes.
