### ISSUE TITLE
Rollup JavaScript slice/push does not appear to work

### ISSUE THREAD

**Issue by hanginwithdaddo** [rollup/rollup#2253]
Rollup's rollup.config.js processing fails to process the following JavaScript correctly.
--------------------------------------
NodeJS example:
$ cat example.js
var someArray = [ 'a' ];
var copyOfArray = someArray.slice();

someArray.push('b');
console.log('someArray = ' + someArray);

copyOfArray.push('b');
console.log('copyOfArfay = ' + copyOfArray);

$ node example.js
someArray = a,b
copyOfArfay = a,b

--------------------------------------
Rollup example:
If place the same code in a rollup.config.js file, I see incorrect results:
$ cat rollup.config.js
var someArray = [ 'a' ];
var copyOfArray = someArray.slice();

someArray.push('b');
console.log('someArray = ' + someArray);

copyOfArray.push('b');
console.log('copyOfArray = ' + copyOfArray);

$ node_modules/rollup/bin/rollup -c rollup.config.js
someArray = a,b
copyOfArray = a

copyOfArray should report a,b, not just a.

**Comment by kzc** [comment]
in repl:

https://rollupjs.org/repl?version=0.60.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHNvbWVBcnJheSUyMCUzRCUyMCU1QiUyMCdhJyUyMCU1RCUzQiU1Q252YXIlMjBjb3B5T2ZBcnJheSUyMCUzRCUyMHNvbWVBcnJheS5zbGljZSgpJTNCJTVDbiU1Q25zb21lQXJyYXkucHVzaCgnYicpJTNCJTVDbmNvbnNvbGUubG9nKCdzb21lQXJyYXklMjAlM0QlMjAnJTIwJTJCJTIwc29tZUFycmF5KSUzQiU1Q24lNUNuY29weU9mQXJyYXkucHVzaCgnYicpJTNCJTVDbmNvbnNvbGUubG9nKCdjb3B5T2ZBcnJheSUyMCUzRCUyMCclMjAlMkIlMjBjb3B5T2ZBcnJheSklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by hanginwithdaddo** [comment]
The issue I reported is NOT with what rollup generates, but with rollup's JS engine as it reads and processes JavaScript in its JavaScript-based configuration file (i.e., the file that is passed via the -c command line option).

**Comment by kzc** [comment]
But Rollup does generate incorrect code for the repl link above.

The config file is a different matter, although probably related.

**Comment by hanginwithdaddo** [comment]
Sorry, I missed that in the example you posted. Thanks!!

**Comment by lukastaegert** [comment]
Thanks a lot for bringing up this issue. This is most probably an unintended side-effect of extending the literal value tracking in 0.59 where we made some deoptimizations more specific.

The issue at hand here is that e.g. arrays that are not generated as a literal but rather as a return value of a prototype method do not have a separate backing data structure to track if they are included in the bundle.

Of course this needs to change. After some deliberations I think I have a plan for making this work. This will however require some deeper refactorings (basically I want the call expressions to be responsible for tracking their return value) so it might require a few days. Nevertheless I hope we can release this as an 0.60 patch release soon.

**Comment by kzc** [comment]
Until this ticket was filed I didn't realize that the Rollup config was run through Rollup itself. It makes sense. However, shouldn't it be run on the config with `treeshake` disabled in light of this issue?

**Comment by lukastaegert** [comment]
> shouldn't it be run on the config with treeshake disabled in light of this issue?

We are really lucky this serious issue was discovered via the config parsing. It would have been much harder to find this in a full application. So why should we disable tree-shaking? With the latest versions, the speed improvement of switching off tree-shaking becomes more and more negligible. If tree-shaking works correctly, it should be able to handle config files just as well.

**Comment by kzc** [comment]
Why disable tree shaking for the config parse? Reducing risk in an area that cannot benefit from tree shaking in the best case, and can cause difficult debugging situations in the worst case with future tree shaking bugs. A bug in a config parse is the last thing a user would expect.

**Comment by guybedford** [comment]
I tend to agree treeshaking should be disabled for the configuration file in the name of well-defined behaviour. Especially while treeshaking analysis is under heavy development and likely to have edge case bugs.

**Comment by lukastaegert** [comment]
Still not convinced but that may be just me. The bug has been present since 0.59.0 but no-one noticed until @hanginwithdaddo decided to get fancy with the config. If the config breaks, then the production code will break most definitely but in sinister and hard to track ways.

That does not mean I want to abuse users to find bugs. We only release code we expect to be bug free because we think we wrote all the relevant tests. Just sometimes we did not.

BTW fix is underway, at my current rate it should be finished tomorrow or Wednesday.

**Comment by hanginwithdaddo** [comment]
All, I tend to concur with @lukastaegert. Using the same process by default when processing rollup.config.jsas is used when rolling up source would help isolate some errors that otherwise might not get detected until rolled up results are put into production, which would be certainly worse than catching them while trying to build. We realize you are doing the best to catch issues before we get them. None of us is perfect, therefore neither is the hardware or software that we create perfect, which includes automated testing. We just do our best.

**Comment by guybedford** [comment]
If our goal is to catch shallow bugs fast, yes having this on is useful.

But if our goal is to ensure users have the best possible experience using Rollup, then disabling this is better.

The argument that the shallow-bug catching will help catch build bugs therefore making the project better is a second-order argument, which doesn't hold to justify a greater overall user experience of predictable failure in my opinion.

**Comment by hanginwithdaddo** [comment]
@lukastaegert, thank you for correcting this so quickly!! I pulled down the latest version of rollup and things work fine now.
