### ISSUE TITLE
System module format undefined init expressions

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2257]
It would help if `LocalVariable.init` were set to `UNDEFINED_EXPRESSION` instead of `UNKNOWN_EXPRESSION` so that it would be possibly to reliably know which variables lack an initializer given their variable reference only.

The example for the System module format would be:

```js
export var p;
export function q () {
  p = 5;
}
```

which currently outputs:

```js
System.register([], function (exports, module) {
  'use strict';
  return {
    execute: function () {

      exports('q', q);
      var p;
      function q () {
        p = exports('p', 5);
      }

    }
  };
});
```

But should rather output a line like `exports(p, 'undefined')` at the top so that namespaces have the right shape from the start.

@lukastaegert let me know if this sounds sensible and I can do this refactoring, but just wanted to mention first as it falls into your area here.

**Comment by lukastaegert** [comment]
I am totally OK with that! As I think I already stated at some point, the reason `UNDEFINED_EXPRESSION` does not exist was that initially, it was indistinguishable from the `UNKNOWN_EXPRESSION`. Now with the literal value tracking, there already is a reason to change that. So please go ahead! It would even make many checks whether `.init` exists in LocalVariable obsolete if `.init` is always set to `UNDEFINED_EXPRESSION` until it receives a value.

If you just want to solve the issue described here for now, you could just make `UNDEFINED_EXPRESSION` a copy of `UNKNOWN_EXPRESSION` and we extend the value tracking later (at that point, it would also make sense to check how missing object members are handled etc.).

**Comment by guybedford** [comment]
Ok, I'm very unfamiliar with this stuff but let me give it a go!
