### ISSUE TITLE
CLI support for plugins

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#226]
As discussed [here](https://github.com/rollup/rollup/pull/209#issuecomment-150964362) and [here](https://github.com/rollup/rollup/issues/224).

Main question is what the appropriate mechanism is for passing options to plugins – does this make sense?

```bash
rollup --input src/main.js\
       --output dist/bundle.js\
       --format umd\
       --name myBundle\
       --sourcemap\
       --plugin babel {"sourceMap": true }\
       --plugin commonjs {"include": "node_modules/**" }
```

Or should that configuration live in a `.rolluprc` file (something we've managed without up till now)?

How do other tools handle similar problems?

**Comment by Rich-Harris** [comment]
The JSON option syntax, as well as being unwieldy and awkward to parse, wouldn't cover all possible options (e.g. if a plugin had an option that was a regex).

Webpack has solved this problem already, so let's be [great artists](https://www.youtube.com/watch?v=CW0DUg63lqU):

```js
# import config, override format option
rollup --config rollup.config.js -f umd
```

```js
// rollup.config.js
import babel from 'rollup-plugin-babel';

export default {
  entry: 'src/main.js',
  plugins: [ babel() ],

  // bundle options would need to go here too
  sourceMap: true
}
```

**Comment by Victorystick** [comment]
Good idea. Great artists indeed.

Should this configuration mainly be used by people who need to support non-ES6 formats, or will we promote such configurations in general?

**Comment by developit** [comment]
I just an into this and agree.
That being said, Webpack also automatically detects plugins installed in `node_modules` if not explicitly specified, which makes it possible to still use it exclusively via the CLI.  All that is needed is a common package prefix or suffix, which you're already establishing as `rollup-plugin-*`

**Comment by Rich-Harris** [comment]
@developit Interesting. It raises two questions:

* How do you conditionally enable plugins (e.g. if you're doing two separate builds, where one build doesn't use all the plugins)?
* How do you configure plugins? Or does it only work with plugins that don't require configuration?

**Comment by developit** [comment]
At least within the context of Webpack, conditionally enabling plugins is only supported when you're explicitly defining the Array of plugins to use.

They seem to have gone with the mantra of "work by default, but still be configurable" here.

Plugin configuration is declarative:  any top-level key corresponding to an un-prefixed plugin name is treated as configuration for that plugin.  I like this, because it means in the case where I need to conditionally enable (or really _disable_, since this is working from the perspective of "on by default"), I can still do so via static configuration rather than relying on invoking plugins myself.

That would make the rollup plugin installation/configuration process:

`npm i -D rollup-plugin-foo`

// then, if needed, add configuration:
```js
{
  ...
  "foo": {
    "shouldBar": true
  }
}
```

**Comment by Rich-Harris** [comment]
Have opened #229.

@developit My concern with that approach is that it potentially becomes a source of confusion about when plugins should or shouldn't run, and which ones need configuration. (Moreover, I don't think there are many situations where you wouldn't need to configure plugins. For example you wouldn't want Babel running on all your already-ES5 dependencies.)

I wondered about the `{"foo": {"shouldBar: true}}` form, but there will be times when plugins are order-dependent, so I think it's better to insist that they're always provided as an array.

**Comment by developit** [comment]
Perhaps a happy medium would be to allow the plugin order to be (optionally?) configurable via an Array of String plugin names?  `"plugins":["babel", "cjs"]`  That would also be somewhat in-line with other configuration-driven tools like [karma](http://karma-runner.github.io/0.13/config/configuration-file.html) and [eslint](http://eslint.org/docs/user-guide/configuring).

As for optional configuration - my main usecase for this has actually been Babel - I use `.babelrc` to configure it, so I have no need for inlined configuration.  This is the case with a few other build steps as well.

Also, while grabbing the eslint link above, I noted they support pulling their configuration from the `package.json`, which is probably a great reason to keep things JSON-serializable.

**Comment by Rich-Harris** [comment]
@developit that could work, yeah. Since it isn't mutually exclusive with the existing proposal it could be introduced at a later stage – my feeling is that we should go with the simple-to-implement option for now, and see how we end up actually using it. If it turns out that we *could* do most of what we need with config-less plugins that the Rollup CLI knows how to find (and install?) then we could certainly add that.

> which is probably a great reason to keep things JSON-serializable.

I do agree with you on this – I'm just wary of imposing that constraint on plugins until we've accumulated a bit more experience with them.

**Comment by Victorystick** [comment]
Closing as of 0.20.1. #230

**Comment by jbucaran** [comment]
I came upon this issue because I was looking how for to use plugins over the CLI, but instead it seems folks were talking about a config file. Really confusing.

**Comment by caub** [comment]
Just to be sure, `--plugin` was not implemented, and there are no way to run plugins inline, right?

(`rollup --plugin node-globals -f cjs foo-bar.js | node` would have been practical)

**Comment by lukastaegert** [comment]
Yes, a config file or the JS API are the only ways to add a plugin for now.

**Comment by dhall2211** [comment]
is there any updates on running plugins in a command line? I have tried to implement a build script with visualizer and cannot seem to get it working? base on the rollup doc i have tried this in my package.json file:

`"build:stats": "rollup -c -p 'visualizer={gzipSize: true, filename: 'stats_esm.html'}'"`

**Comment by caub** [comment]
```
echo 'module.exports={plugins:[require("visualizer")({gzipSize: true, filename: "stats_esm.html"})]}' > /tmp/rollup.config.js && rollup -c /tmp/rollup.config.js
```

**Comment by lukastaegert** [comment]
@dhall2211 your command works if you properly escape quotes, this worked for me:

```
"build:stats": "rollup -c -p 'visualizer={gzipSize: true, filename: \"stats_esm2.html\"}'"
```

**Comment by dhall2211** [comment]
@lukastaegert  I tried that before and still didn't work. Then i thought it maybe a typo so I copied your solution one to one and recieved this error. 

 rollup -c -p 'visualizer={gzipSize: true, filename: "stats_esm2.html"}'

[!] Error: Invalid --plugin argument format: "'visualizer={gzipSize:"
Error: Invalid --plugin argument format: "'visualizer={gzipSize:"
