### ISSUE TITLE
Variable binding edge cases

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2278]
We should make sure we cover the following cases comprehensively:

1. var + function -> function is declaration, vars are assignments

```js
console.log(x) // function
if (false)
  var x = 10;
console.log(x) // function
var x = 5;
console.log(x) // 5
function x () {}
```

2. function + function = second function used

```js
console.log(x()) // second
function x () { console.log('first') }
console.log(x()) // second
function x () { console.log('second') }
```

3. var + var -> no "true" declaration, all just assignments
```js
if (false)
  var p = 5;
else
  var p = 10;
console.log(p) // 10
var p = 6;
console.log(p) // 6
```

The cases in combination with let bindings all throw though, so those are not such a worry, although ideally we should check that we do throw, but that seems less urgent as it is non-working code behaviour.

**Comment by lukastaegert** [comment]
Is this just a reminder to not forget this is possible or does this have a specific improvement in mind?

Because at the moment, those cases are handled correctly in that no code is dropped wrongly (in your example, no code would be dropped anyway due to all the logs but if we were defining booleans and using if statements, even then everything should work).

So what do you mean by "comprehensive" in terms of tests we want to pass that we may or may not be passing already?

**Comment by guybedford** [comment]
Comprehensive in terms of testing that the declarations are being detected as the right instances.

It's about ensuring solid foundations on spec fundamentals, so that extensions to analysis in future don't need to worry about these kinds of issues and can instead move forward into higher-order analysis.

**Comment by shellscape** [comment]
@guybedford @lukastaegert this one still valid?

**Comment by lukastaegert** [comment]
As there was no bug to begin with but this was just a reminder, I think it can be closed without loss.

**Comment by guybedford** [comment]
These bugs don't tend to come up because:

1. Rollup always throws for redefinitions of bindings with functions, even when it is valid in ECMAScript (although in theory this means there is valid code such as `var p = 5; doStuff(p); function p () {  }` which won't build with Rollup, which could be considered a bug from a spec correctness point of view)

2. Rollup always deoptimizes binding expression analysis for multiple `var` declarations of the same name.

**Comment by lukastaegert** [comment]
As for 1. it is not Rollup itself that throws an error here but recent versions of acorn, and I think they added this check for spec compliance. Are you sure this is valid but n a module in strict mode?

**Comment by guybedford** [comment]
Ah, the top-level validation is applying. This can be avoided with a function wrapper so eg:

```js
function x () {
  function p () {}
  console.log(p); // function
  var p = 0;
  console.log(p); // 0
}
```

I can't see any immediate conflicts here in the analysis process though.
