### ISSUE TITLE
Dynamic imports are not tree-shaken

### ISSUE THREAD

**Issue by eight04** [rollup/rollup#2284]
Repro:
https://rollupjs.org/repl?version=0.60.7&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZ2V0Rm9vJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBpbXBvcnQoJTVDJTIyLiUyRmZvby5qcyU1QyUyMiklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAlNUMlMjJGT08lNUMlMjIlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

In the above example, `getFoo` is not used and it should generate an empty bundle.

**Comment by guybedford** [comment]
Yes, this is still pending development.

**Comment by eight04** [comment]
I also noticed that if a module is dynamically imported, the module won't be inlined even if the `import()` statement is removed by tree-shaking. Repro:
https://github.com/eight04/node-test/tree/rollup-dynamic-import-treeshaking

**Comment by guybedford** [comment]
@eight04 inlining of dynamic imports is not supported for code splitting workflows, only single-file builds.

**Comment by eight04** [comment]
I think if a module is imported both dynamically and statically, and the dynamic import is tree-shaken, the module should be inlined. For example:

*entry.js*
```js
// the entry doesn't use dynamic imports at all
import {foo} from "foo";
import {bar} from "bar";
// do something with foo, bar ...
```
Usually, `foo` and `bar` would be inlined correctly. However, if `foo` includes dynamic imports like this:
```js
export function foo() {
   // do something...
}
function someFunctionUseBar() {
  // oh yeah I use bar too but I import it dynamically!
  import("bar").then(bar => {
    // do something with bar...
  });
}
```
Then `bar` won't be inlined while the entry doesn't use dynamic import at all and `someFunctionUseBar` is removed by tree-shaking.

**Comment by lukastaegert** [comment]
Please have a look at #2575, I think this should resolve that issue.
