### ISSUE TITLE
experimentalPreserveModules now requires experimentalCodeSplitting

### ISSUE THREAD

**Issue by kellyselden** [rollup/rollup#2286]
@lukastaegert I remember in an old code review you asked me to make experimentalPreserveModules imply experimentalCodeSplitting. On master that association is broken. `Multiple inputs are only supported for experimentalCodeSplitting.` I'm just wondering if it was intentional or accidental?

**Comment by lukastaegert** [comment]
Sounds more like an accident. Thanks for pointing this out!

**Comment by lukastaegert** [comment]
Note though that with the 1.0.0, `experimentalCodeSplitting` is scheduled to disappear at which point this should work again properly anyway.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
