### ISSUE TITLE
Not correct inlining of Dynamic Import when bundling for CJS format

### ISSUE THREAD

**Issue by olstenlarck** [rollup/rollup#2300]
[Repro](https://rollupjs.org/repl?version=0.61.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmpvaW4lN0QlMjBmcm9tJTIwJ3BhdGgnJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwYXN5bmMlMjBmdW5jdGlvbiUyMGZvbyUyMChvcHRpb25zKSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMG9wdHMlMjAlM0QlMjBPYmplY3QuYXNzaWduKCU3QiUyMGJhciUzQSUyMDEyMyUyMCU3RCUyQyUyMG9wdGlvbnMpJTVDbiU1Q24lMjAlMjBjb25zdCUyMHJlcyUyMCUzRCUyMChhd2FpdCUyMGltcG9ydCgnLiUyRnphenp5JykpJTVDbiU1Q24lMjAlMjByZXR1cm4lMjByZXMuZGVmYXVsdCUyMCUyNiUyNiUyMGpvaW4ocmVzLmRlZmF1bHQucXV4JTJDJTIwJ29ra2trJyklNUNuJTdEJTVDbiU1Q25mb28oKS50aGVuKGNvbnNvbGUubG9nKSU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyemF6enkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMCU3QiU1Q24lMjAlMjBxdXglM0ElMjAnd29vaG9vJyU1Q24lN0QlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

In short. When we bundle for `es/esm` there is no problem (can't be seen in the repl in `es` tab).

```
mkdir repro && cd $_ && mkdir src
touch src/{index.mjs,zazzy.mjs}
```

src/index.mjs

```js
import {join} from 'path'

export default async function foo (options) {
  const opts = Object.assign({ bar: 123 }, options)

  const res = (await import('./zazzy'))

  return res.default && join(res.default.qux, 'okkkk')
}

foo().then(console.log)

```

bundles to `dist/index.mjs`

```js
import { join } from 'path';

async function foo (options) {
  const opts = Object.assign({ bar: 123 }, options);

  const res = (await Promise.resolve().then(function () { return zazzy$1; }));

  return res.default && join(res.default.qux, 'okkkk')
}

foo().then(console.log);

const zazzy = {
  qux: 'woohoo'
};

const zazzy$1 = /*#__PURE__*/Object.freeze({
  default: zazzy
});

export default foo;

```

Notice that the inline is `zazzy$1` which is correct, so when execute that file there is `res.default` correctly.

But the CJS bundle is this one (`dist/index.js`, note `.js`)

```js
'use strict';

const path = require('path');

async function foo (options) {
  const opts = Object.assign({ bar: 123 }, options);

  const res = (await Promise.resolve().then(function () { return zazzy; }));

  return res.default && path.join(res.default.qux, 'okkkk')
}

foo().then(console.log);

const zazzy = {
  qux: 'woohoo'
};

const zazzy$1 = /*#__PURE__*/Object.freeze({
  default: zazzy
});

module.exports = foo;

```

Which you can clearly see that `zazzy$1` is not used anywhere or i'm blind. The `foo` resolves to undefined because the awaited promise (`res`) does not `.default` because `zazzy` is returned instead of `zazzy$1`.

It's definitely a bug for me. Of course it _can_ be worked around with always adding `interop()` infront of the awaited dynamic import, but that's pretty weird.

**Comment by olstenlarck** [comment]
Not to mention that the `--experimental-modules` works that way, which in turn uses the `esm` loader anyway. So even if we use `node -r esm` it still works that way. So it's definitely a bug. 

Please some response on that. Thanks :)

**Comment by guybedford** [comment]
I believe this was resolved in https://github.com/rollup/rollup/pull/2295 already. If you're able to test on the master build, please let us know if that works for you.

**Comment by olstenlarck** [comment]
Oh, cool. Yup, it works! :)
