### ISSUE TITLE
Rollup load function to include a "mtime" or "hash" to avoid full re-load

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2301]
We can effectively cache the load hook in Rollup by having it return an "mtime" or "hash" (effectively an ETag).

Then passing that in as an argument can allow a new return value to reuse the existing cached load value.

This should offer some performance benefit by reducing file system load for rebuilds.

**Comment by keithamus** [comment]
One issue we've found is hashing can be quite error prone if the constituent parts of the pipeline change. e.g. on the surface it seems simple to say "load is pure; given a files input it outputs this transformed code+map" - however there is a peice of external state: the versions of that function. There needs to be a way for cache to be invalidated upon that change of state. For a project I'm working on which caches heavily, we include paginate caches by package.json - which means as a dependency (like babel) is updated, all cache is then invalidated. This is a little clumsy but it gets the job done. Another piece of the puzzle is that a hash can be expensive to compute - at least more expensive than mtime or size. Our caching is layered so we do the following (pseudo code ahead):

```js
if (stat(file).mtime > rememberedMtime) {
  doNotUseCache()
} else if (stat(file).size !== rememberedSize) {
  doNotUseCache()
} else if (hash(file) !== rememberedHash) {
  doNotUseCache()
} else {
  useCache()
}
```

**Comment by lukastaegert** [comment]
@keithamus Out of curiosity: In what situation would the mtime and size checks pass but the hash check fail?

Definitely a good point with the dependency versions though I would presume this issue is first about watch mode rebuilds and not about long-term caching.

If I understand this issue correctly, caching in this approach would be delegated to the individual plugins? So effectively, each plugin load hook would give us a token together with the loaded file; on rebuilds, we pass the previous token to the load hook and based on this information, the plugin can decide if it can return its cached version.

The genius about this approach is that we could even extend this to caching the transform hook. I.e. the load hook and all transform hooks give us a token each. Now on the next run, we pass its token back to the load hook. If it responds with the same token, we know nothing has changed here and we pass the token of the first transform hook back to that hook and so on. If at any point of this chain a token changes, all subsequent transforms will not be provided their token.

But this is just an idea. If we want to cache whole chains of transform plugins, maybe a different approach would make more sense.

**Comment by keithamus** [comment]
> Out of curiosity: In what situation would the mtime and size checks pass but the hash check fail?

`mtime` isn't perfect, there are plenty of edge cases where `mtime` isn't updated. It's also relatively easy to force an mtime of a file (`touch -at 1234`). But _using_ the mtime as a quick, cheap, positive signal for ditching cache is a good thing.

`size` isn't perfect - one usecase is if I fix a typo, say I typed `funtcion` and just change it to `function` - the `size` has remained identical but the code is _very_ different (goes from early `SyntaxError` to, potentially, fully functioning code).

> caching in this approach would be delegated to the individual plugins?

I don't think this would be ideal, for a few reasons: 

1. Some plugins might not implement caching, which would be a drag and mean lots of fragmentation
2. Each plugin could get caching wrong, if you pass an etag over and a plugin doesn't consider the above points, things go wrong
3. Unless you provided an API for caching which had a global config, I'd need to configure caching params for every plugin (which folder does it go in? which files get cleaned up?, etc)

> extend this to caching the transform hook

Caching the transform would be excellent. We do this with our babel transform hook - but again we paginate cache on package.json digest so when we change babel versions the cache is blown away.

---


I think the right sollution is exploring some notion of "surrogate keys". A file hash is one part of a set of cache keys. Perhaps plugins could expose their own cache key - which could be a version number (or whatever, it's just a string). Rollup could combine these in ways it needs:

```js
// Plugins expose their own `etag` which they can roll whenever a change happens
const resolvePlugin = { etag: '123', load(id) => ... }
const transformPlugin = { etag: '456', transform(code) => ... }

// Rollups cache goes something like this:

const tag = concat(
  getPluginEtags() ['123', '456']
  getFileEtag() // `deadbeef`
)

tag == '123456deadbeef'

// If the tag for this whole build is in the cache, we can skip it all
if (cache.has(tag)) {
  return cache.get(tag)
} else {
 // Check if we have a cache per-plugin
  for(const plugin of plugins) {
    const tag = concat(plugin.etag, getFileEtag())
    // If we have a cached result from this plugin, then we can skip this one plugin - otherwise we have to execute it.
    cache.get(etag) || executePlugin(plugin)
  }
}
```

**Comment by guybedford** [comment]
@keithamus sure I'd be happy to chat on this topic, and I'm sure @lukastaegert will let us know soon if he can find a spot in his schedule too.

**Comment by guybedford** [comment]
@keithamus howw about Tuesday evening GMT+2 to chat with myself and @lukastaegert?

**Comment by keithamus** [comment]
Sure @guybedford - that works for me. I've made a [doodle poll so we can pick an hour to talk](https://doodle.com/poll/9p3shk9f84uegsfz). I'd like to use [Zoom](https://zoom.us/) but happy with Google Hangouts or Skype instead.

**Comment by guybedford** [comment]
Looks like we’ve got two slots for today, @keithamus are you happy to go for the second one? Google hangouts may be slightly easier to arrange.

**Comment by keithamus** [comment]
Sure, let's go with the second slot - that is 19:00-UTC+1. We can do hangouts for sure. I'll paste a meeting link here closer to the time/

**Comment by keithamus** [comment]
https://meet.google.com/dzi-xppd-yzq @guybedford @lukastaegert

**Comment by guybedford** [comment]
@keithamus amazing you're looking into this, would be great to see it moving forward.

Note that `emitAsset` allows a dependencies argument, just like transform dependencies. Plugin authors should be able to rely on these features to properly detail the invalidation path. If there are options etc that affect this stuff, then we should ensure all caching digests a hash of the output options as well.

Between those things would that cover us do you think?

**Comment by guybedford** [comment]
Here's a sample API I was thinking of for this feature:

```js
load (id, cacheKey: string | null) {
  if (isValid(cacheKey))
    return true;
  return { code, cacheKey };
}
```

The cache key string can be used to encode a hash, an mtime, or anything else deemed an input into the load.

Then in terms of catching the side effects, it is the plugin's responsibility to ensure that it provides a pure idempotent function. As for plugin context calls:

* `warn` only happening on the first run seems fine to me.
* `error` calls will result in no cache entry, so that seems ok.
* `resolveId`, `parse` and `isExternal` calls, should all be pure.
* For `emitAsset` we currently track which emitAsset calls are called by the transform hook and then re-run them when using the cached transform (which is used when the load source matches the cache). The best option may just be to extend this same support to the `load` hook. We can track this in https://github.com/rollup/rollup/issues/2363.

Hopefully that should cover things? The only other thing I can think of is input options and output options perhaps make  optionsCacheKey or similar available to the plugin - `this.inputCacheKey`?

**Comment by guybedford** [comment]
Thinking about this further, I think it might be useful to have a similar approach for the transform function itself. Currently we match the transform cache if the input source is the same, but there could easily be other dependencies of the transform function that should apply. Eg transform options, and other file dependencies.

The most flexible way would seem to apply the same cache method we want to use with the load hook to also apply to the transform hook.

**Comment by guybedford** [comment]
The current caching work has effectively replaced the need for this.
