### ISSUE TITLE
Incorrect treeshaking of conditionals when using Object Spread

### ISSUE THREAD

**Issue by wessberg** [rollup/rollup#2303]
[See this repro](https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwYSUyMCUzRCUyMCU3QiU1Q24lNUN0cmVzdWx0JTNBJTIwdHJ1ZSU1Q24lN0QlM0IlNUNuJTVDbmNvbnN0JTIwYiUyMCUzRCUyMCU3QiU1Q24lNUN0Li4uYSU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKGIucmVzdWx0JTIwJTNGJTIwJTVDJTIyc3VjY2VzcyU1QyUyMiUyMCUzQSUyMCU1QyUyMmZhaWwlNUMlMjIpJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

The expected value is `console.log("success")`, but we're left with `console.log("fail")`.
It would seem that the Object spread syntax is accepted by Rollup, but I'm assuming you don't handle The Object Spread syntax when you traverse the Acorn AST. That's fine, but I think the correct behavior would be to opt-out from doing the tree-shaking like if `Object.assign` had been used instead of the spread syntax, since it currently breaks libraries and apps built with Rollup in situations like this

**Comment by lukastaegert** [comment]
Thanks for bringing this up! I have added a fix to #2315. With this fix, object rest spread will now always be handled like an "unknown" property.

**Comment by lukastaegert** [comment]
Fix released via Rollup v0.63.0, thanks for being patient!
