### ISSUE TITLE
How to Input source maps?

### ISSUE THREAD

**Issue by chentoo** [rollup/rollup#2304]
I saw https://github.com/rollup/rollup/issues/409
and https://github.com/rollup/rollup/pull/715

It looks like rollup can Input source maps.But I can't find any place to set it.
Is there any example?

Please help me, thanks!

**Comment by GordonSmith** [comment]
The following plugin works for me (typescript -> es6 JS -> bundle):  https://www.npmjs.com/package/rollup-plugin-sourcemaps

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
