### ISSUE TITLE
Warnings have different shapes when emitted from different hooks?

### ISSUE THREAD

**Issue by eight04** [rollup/rollup#2308]
For example, with this warning:
```js
{
  code: "MY_ERROR",
  message: "an error"
}
```
If the warning is emitted from `transform` hook, `onwarn` would receive:
```js
{
  plugin: "my-plugin-name",
  code: "PLUGIN_WARNING",
  pluginCode: "MY_ERROR",
  message: "an error"
}
```
If the warning is emitted from `buildEnd` hook, `onwarn` would receive:
```js
{
  plugin: undefined,
  code: "MY_ERROR",
  pluginCode: undefined,
  message: "an error"
}
```
`plugin` is missing and it's hard to tell which plugin emitted the warning.

**Comment by guybedford** [comment]
Thanks so much for looking into this - yes some standardisation could go a long way here, and help with refining this is very much appreciated.

**Comment by lukastaegert** [comment]
I guess so, please open a new issue if you stumble upon more inconsistencies.
