### ISSUE TITLE
Feature Request: dual mode `main` field of package.json

### ISSUE THREAD

**Issue by coreyfarrell** [rollup/rollup#2310]
I'd like to request that rollup consider distributing as a dual mode package.  This is needed to support loading rollup when running `node --experimental-modules` or when using `esm` and loading from an `.mjs` file.  By dual module package what I mean is that the package.json `main` field would not have the extension, so `"main": "dist/rollup"`.  Then rename `dist/rollup.es.js` to `dist/rollup.mjs`.  This would cause node to load the correct file (CJS or ESM).

To reproduce the failure create `script.mjs`:
```js
import {rollup} from 'rollup';
console.log(typeof rollup);
```
Then run `node --experimental-modules script.mjs` (node 8.5+) or `node -r esm script.mjs` (with the `esm` module installed).  In both cases it will report that rollup does not provide an export named 'rollup'.  This is because node uses the `main` field of package.json to resolve, so it only finds dist/rollup.js.

**Comment by guybedford** [comment]
@coreyfarrell it is great that you are interested in these compatibility paths, but note that the NodeJS modules implementation is still experimental can can change. Encouraging workflows around this could be risky if things were to turn out to be implemented differently. It's best to wait until there is a clear advisory from the Node modules team on this before rushing ahead, this stuff does just take time to finalise unfortunately.
