### ISSUE TITLE
Specify ES2015 entry point directory

### ISSUE THREAD

**Issue by ichernev** [rollup/rollup#2311]
I know about [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module), but I'm wondering if there is a way to specify root directory, instead of just a single file.

I'm maintainer of [moment.js](https://momentjs.com), and we have the core library + locale files, that should be accessible to users via UMD and ESM modules, so just a single entry point won't cut it.

For example, if we have the following folder structure:

```
.
└── dist
    ├── esm
    │   ├── locale
    │   │   ├── de.js
    │   │   └── ru.js
    │   └── moment.js
    └── umd
        ├── locale
        │   ├── de.js
        │   └── ru.js
        └── moment.js
```

Is there a nice way to have both of these to work

```
// UMD
requre('moment');            // requires dist/umd/moment.js
require('moment/locale/ru'); // requires dist/umd/locale/ru.js
// ESM
import moment from 'moment'; // requires dist/esm/moment.js
import 'moment/locale/ru';   // requires dist/esm/locale/ru.js
```

**Comment by TrySound** [comment]
You can generate .js + .mjs pair and user bundler will prefer mjs.

**Comment by ichernev** [comment]
By user bundler you mean rollup, or any bundler (like webpack, parcel).

**Comment by TrySound** [comment]
[Rollup](https://github.com/rollup/rollup/blob/master/src/utils/defaults.ts#L29-L36) and [webpack](https://webpack.js.org/configuration/resolve/#resolve-extensions) support it. Not sure about parcel.

**Comment by ichernev** [comment]
Thank you @TrySound!
