### ISSUE TITLE
Proposal: Expose ability to create custom formats/finalisers

### ISSUE THREAD

**Issue by rpetrich** [rollup/rollup#2312]
The ability to create custom finalisers would allow using rollup in scenarios where the existing bundle formats aren't suitable or in environments that mandate their own custom bundle format.

A working prototype of what the finaliser API could look like is available on [rpetrich/rollup#custom-finalisers](https://github.com/rpetrich/rollup/commits/custom-finalisers).

**Comment by lukastaegert** [comment]
Hey @rpetrich, that definitely looks intriguing, thanks a lot! As I am about to blast off on a 1.5 week vacation please be aware that reviews might take a while. @guybedford might also be interested in this.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
