### ISSUE TITLE
Proposal: Add ability to aggressively merge into the entry chunk

### ISSUE THREAD

**Issue by rpetrich** [rollup/rollup#2313]
I'm proposing an option to merge all modules used in the entry point into the entry point itself, with internal symbols given unsafe mangled names. Additional modules loaded dynamically would be chunked as usual, with modules already loaded in the entry point referred to by their mangled symbols. This would be especially useful when paired with dynamic import to easily produce a single small chunk for the first paint/initial render with additional modules loaded on demand asynchronously.

A prototype with a new `--aggressivelyMergeIntoEntryPoint` option is at [rpetrich/rollup#merge-into-entrypoint](https://github.com/rpetrich/rollup/commits/merge-into-entrypoint) (tests still to be added, feedback welcome)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by lukastaegert** [comment]
This should be possible via manual chunks.
