### ISSUE TITLE
Rollup traces exports before they are bound

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#2317]
Taken from rollup/rollup-plugin-commonjs#324:

It is possible that rollup fails bundling due to unmatched `traceExport` calls caused by this line: https://github.com/rollup/rollup/blob/cd437b7c62a231d7cea539e82a30729a5267df8d/src/Graph.ts#L841
which is called before the inter-module links have been set up. Not sure what the proper solution is.

The issue can be exposed via this repo: https://github.com/yurayko/rollup-plugin-commonjs-trbl if you adjust the comments in `rollup.config.js` (move the comment down one line).

**Comment by lukastaegert** [comment]
Update (taken from https://github.com/rollup/rollup-plugin-commonjs/issues/315#issuecomment-401976127):

This is another repository that seems to suffer from the same issue: https://github.com/aleclarson/rollup-bugs/tree/commonjs-issue-315

**Comment by guybedford** [comment]
There was actually the following warning for this test case that wasn't being flushed due to the error coming first:

```
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
node_modules/vue/dist/vue.esm.js (imported by  commonjs-proxy:node_modules/vue/dist/vue.esm.js)
```

I've created a branch to provide better error output here in https://github.com/rollup/rollup/pull/2334.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
