### ISSUE TITLE
Pass all-module-ids to addons(footer/banner/intro/outro) functions.

### ISSUE THREAD

**Issue by hh9527** [rollup/rollup#2318]
This is a feature request:

I need to collect some information (hashes, module types) in the module process stage. And after all modules are collected, inject some code to the chunk.

For now, because `intro` function will only received the PluginContext (via this), so I have to inject some string placeholder `/* __my_plugin_inject_here__ */` first, and in the `transformChunk` callback to replace it. (transformChunk can get the `chunk` which includes a `renderedModules`).

So, it is better to pass `chunk` or `renderedModules` to banner/footer/intro/outer.

If this proposal is accepted, I can submit a PR.

**Comment by lukastaegert** [comment]
Out of curiosity, why do you need to insert a placeholder that you replace later instead of just prepending your code in `transformChunk`?

**Comment by hh9527** [comment]
i need to give some faked global var initial values, something like this:

```js
(function() {
  var __myInjectedVar = /* placeholder */;
  // rest code
})()
```

**Comment by lukastaegert** [comment]
As banner/footer/intro/outro are created after the rollup phase but before the rendering, it might be possible to get *some* information about the chunks here. But not for instance the chunk hashes used in the chunk filenames as those depend on banner/footer/intro/outro themselves. And no information depending on the rendered output as is the case in transformChunk as again, we need banner/footer/intro/outro to render the output.

**Comment by lukastaegert** [comment]
What is the minimal information you would need?

**Comment by hh9527** [comment]
For now, I need all module's id only. But I think it's better to provide all referenced external module's id too.

In the first post, I mentioned 'hashes', it is not the chunk's hash, it is the module's hash which is calculated by my own plugin.

Some notes:

I can collect all modules by intercepting `load' hook. But this approach can not deal with watch mode. So, I need a module's id list to filter my own collections.

Another approach:

I can fake a special module, for example `__used_packages__`, and after rollup phase, my plugin will provide the __used_packages__ module's content, this approach need a new plugin hook method 'provideGlobals' which will be called after rollup phase.

```ts
// the signature of provideGlobals
type ChunkInfo = {
  modules: string[];
  externals: string[];
};

interface Plugin {
  // ...
  provideGlobals(id: string, chunkInfo: ChunkInfo) => Promise<{[id: string]: string}>;
}
```

```js
// foo.js
import packages from '__used_packages__';
export default function showPackages() {
  const list = packages.map(pkg => `  ${pkg.name}@${pkg.version}`);
  console.log('Powered by\n' + list.join('\n'));
}
```

```js
// rollup.config.js
export default {
  input: 'src/index.js',
  output: {
    format: 'iife'
  },
  external: ['__used_packages__'],
  plugins: [
    {
      async provideGlobals({ modules }) {
        return {
          __used_packages__: JSON.stringify(await getAllPackageInfo(modules))
        }
      }
    }
  ]
}
```

And the result is

```js
(function(usedPackages) {

  function showPackages() {
    const list = usedPackages.map(pkg => `  ${pkg.name}@${pkg.version}`);
    console.log('Powered by\n' + list.join('\n'));
  }

})([
  { "name": "lodash", "version": "4.17.0" },
  { "name": "react", "version": "16.0.1" },
  { "name": "react-dom", "version": "16.0.1" }
])
```

**Comment by hh9527** [comment]
The core idea is: rollup provide a hook after normal rollup phase, in this phase, plugin can provide some additional value by the all used module's id and external module's id.

**Comment by lukastaegert** [comment]
> The core idea is: rollup provide a hook after normal rollup phase, in this phase, plugin can provide some additional value by the all used module's id and external module's id

At that stage, we already know which modules are included so it would make sense to provide a hook to give access to some of the generated analysis data. Let's see what we can do here.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
