### ISSUE TITLE
Creating separate local modules

### ISSUE THREAD

**Issue by Johann-S** [rollup/rollup#2320]
Hi,

Currently on Bootstrap we try to build our plugins separately, to allow users to include specific plugins without the others.

We choose to build them in `UMD` to be sure it works on Bundlers (Webpack, Rollup...) and on browsers.

We have a plugin `Util` which is imported by all of our other plugins.

I made a script which build separately our plugins, it works well for Bundlers but it doesn't work on a browsers (`Util` is available in `window` but not on the plugin scope).

The script to build our plugins (I use Rollup API): https://github.com/twbs/bootstrap/blob/v4-dev-jo-bundle-plugins/build/build-plugins.js

The repository : https://github.com/twbs/bootstrap/tree/v4-dev-jo-bundle-plugins

I'm not sure if it's the reason but, for example our `Alert` plugin need the `Util` plugin but when we look the generated file (https://github.com/twbs/bootstrap/blob/v4-dev-jo-bundle-plugins/dist/js/plugins/alert.js)

We have something like this:
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('jquery'), require('./util.js')) :
  typeof define === 'function' && define.amd ? define(['jquery', './util.js'], factory) :
  (global.Alert = factory(global.jQuery,null));
}(this, (function ($,Util) { 'use strict';
```

And if I change manually `factory(global.jQuery,null)` by `factory(global.jQuery,global.Util)` everything works

I'm sure I miss something but I don't know what is it...

**Comment by guybedford** [comment]
Hi @Johann-S, I've created a branch at https://github.com/rollup/rollup/tree/missing-globals-warning to ensure you get a warning here from Rollup instead of just a null output. The warning should also provide the missing information you need to debug this.

I'd suggest try cloning and building that branch, and check what the id in the warning is, and why it isn't `./Util`.

If this works for you we can merge this helper too.

**Comment by Johann-S** [comment]
@guybedford finally I found a solution with just Babel, but I'll try your branch 😉

**Comment by Johann-S** [comment]
@guybedford it give me that: 
![image](https://user-images.githubusercontent.com/1689750/42804424-4b96a61e-89a9-11e8-988f-54a3aefd6c32.png)

**Comment by Johann-S** [comment]
Thank you very much @guybedford ! Thanks to your change I was able to fix my script !
