### ISSUE TITLE
additional code are added into the output file

### ISSUE THREAD

**Issue by SeanLeeCai** [rollup/rollup#2321]
repl code: [View the repro in the repl](https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKCUyMGN1YmUoJTIwNSUyMCklMjApJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMG1hdGhzLmpzJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiUyRiUyRiUyMG5vcm1hbCU1Q25leHBvcnQlMjBjb25zdCUyMGRpdiUyMCUzRCUyMCdkaXYnJTVDbiUyRiUyRiUyMFRoaXMlMjB2YXJpYWJsZSUyMGlzbid0JTIwdXNlZCUyMGFueXdoZXJlJTJDJTIwYnV0JTIwUm9sbHVwJTIwc3RpbGwlMjBpbmNsdWRlcyUyMGl0JTIwZnJvbSUyMHRoZSUyMGJ1bmRsZS4uLiU1Q25leHBvcnQlMjBjb25zdCUyMHRhZyUyMCUzRCUyMGRvY3VtZW50LmJvZHklMjAlM0YlMjAnYm9keSclMjAlM0ElMjAnZGl2JyU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwZ2V0cyUyMGluY2x1ZGVkJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwcmV3cml0ZSUyMHRoaXMlMjBhcyUyMCU2MHNxdWFyZSglMjB4JTIwKSUyMColMjB4JTYwJTVDbiU1Q3QlMkYlMkYlMjBhbmQlMjBzZWUlMjB3aGF0JTIwaGFwcGVucyElNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by eight04** [comment]
Rollup thinks that accessing the property of an object has side-effects. You can turn `treeshake.propertyReadSideEffects` to false. More details here:
https://rollupjs.org/guide/en#treeshake-treeshake-no-treeshake

**Comment by SeanLeeCai** [comment]
@eight04 
It works well when I turn `treeshake.propertyReadSideEffects` to false, but it seems my problem is another situation.

In my real case, I imported a component from 'element-ui', and I found that the output file is too big. So I checked the output file and found It includes `vue` source code:

ENTRY：test.js
```js
import { Rate } from 'element-ui'
// import Rate from 'element-ui/packages/rate'

export default {
  extends: Rate,
  name: 'rate-component'
}

```

`element-ui/packages/rate/src/main.vue`: [source code](https://github.com/ElemeFE/element/blob/dev/packages/rate/src/main.vue)
```vue
...
<script>
  import { hasClass } from 'element-ui/src/utils/dom';
  ...
</script>
...
```

`element-ui/src/utils/dom.js`: [source code](https://github.com/ElemeFE/element/blob/dev/src/utils/dom.js)
```js
import Vue from 'vue';
...
/* istanbul ignore next */
export function hasClass(el, cls) {
  if (!el || !cls) return false;
  if (cls.indexOf(' ') !== -1) throw new Error('className should not contain space.');
  if (el.classList) {
    return el.classList.contains(cls);
  } else {
    return (' ' + el.className + ' ').indexOf(' ' + cls + ' ') > -1;
  }
};
...
```
The function `hasClass` is purely, but the Statement `import Vue from 'vue'` still work.
Why the `vue` is included even though it never be used in `hasClass`?

---
My rollup config is:
```js
// inputOptions
module.exports = {
  input: 'src/test.js',
  treeshake: { propertyReadSideEffects: false },
  plugins: [
    resolve({
      extensions: [ '.vue', '.js', '.json', '.jsx' ],
      customResolveOptions: {
        moduleDirectory: 'node_modules'
      }
    }),
    alias({ resolve: ['.vue', '.js'] }),
    vuePlugin(),
    postcss({
      // extract: true,
      minimize: true,
      extensions: ['.css', '.less', '.sass']
    }),
    commonjs({ include: 'node_modules/**' }),
    babel({
      externalHelpers: false,
      runtimeHelpers: true,
      exclude: 'node_modules/**'
    })
  ]
}
```
```js
// outputOptions:
module.exports = {
    file: 'dist/test/index.rollup.js',
    name: 'test',
    format: 'umd',
    sourcemap: false, // 'inline'
    intro: 'var process = { env: { NODE_ENV: "production" } };'
}
```

**Comment by lukastaegert** [comment]
Vue is known to do some non-trivial transformations in its initialization code which prevents rollup from removing it because it cannot be sure there are no side-effects (and maybe there are such as global variables? I must admit I did not check yet in detail). We hope to improve here at some point but no promises for a short-term solution.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
