### ISSUE TITLE
TypeScript definitions for PluginContext are Incorrect

### ISSUE THREAD

**Issue by kristoferbaxter** [rollup/rollup#2328]
Today, the definition for `PluginContext` indicates the method `parse` will return an `ESTree.Program`, but this isn't quite true since `Node`s in the `Program` contain `start` and `end` members. 

It appears from a cursory glance that Rollup doesn't use the ESTree types internally when it parses an AST. (https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/Node.ts) 

Are the TypeScript definitions out of date or is the implementation incorrect?

### Interface in rollup.d.ts
```typescript
export interface PluginContext {
  parse: (input: string, options: any) => ESTree.Program;
}
```

#### Input Source
```typescript
import React from 'react';

export class MyComponent extends React.Component {
  render() {
    return React.createElement("div", null, this.props.string);
  }
}
```
#### Rollup Plugin Source
```typescript
export default function examplePlugin(): Plugin {
  return {
    transform: async (code: string, id: string) => {
      const program = this.parse(code, {});
      const importNodes = program.body.filter(node =>['ImportDeclaration'].includes(node.type));
      console.log(importNodes);
    },
  };
}
```

#### Output
```typescript
{
  type: 'ImportDeclaration',
  start: 0,
  end: 26,
  specifiers:
   [ Node {
       type: 'ImportDefaultSpecifier',
       start: 7,
       end: 12,
       local: [Object] } ],
  source:
   Node {
     type: 'Literal',
     start: 18,
     end: 25,
     value: 'react',
     raw: '\'react\'' } }
```

The `ImportDeclaration` contains `start` and `end` fields, but these are not present in the `ESTree` types for an `ImportDeclaration`. This discrepancy makes it difficult to leverage the custom `start` and `end` values for Plugins written using TypeScript.

#### ESTree Declarations
```typescript
interface BaseNodeWithoutComments {
  // Every leaf interface that extends BaseNode must specify a type property.
  // The type property should be a string literal. For example, Identifier
  // has: `type: "Identifier"`
  type: string;
  loc?: SourceLocation | null;
  range?: [number, number];
}

interface BaseNode extends BaseNodeWithoutComments {
  leadingComments?: Array<Comment>;
  trailingComments?: Array<Comment>;
}

interface BaseModuleDeclaration extends BaseNode { }

export interface ImportDeclaration extends BaseModuleDeclaration {
  type: "ImportDeclaration";
  specifiers: Array<ImportSpecifier | ImportDefaultSpecifier | ImportNamespaceSpecifier>;
  source: Literal;
}
```

**Comment by AndrewLeedham** [comment]
@kristoferbaxter what was the reason for closing? This still seems to be an issue, passing the `ast` from `this.parse` into estree-walker for example has a mismatch of types `Program` vs `Node`, where `Program` doesn't have `start` or `end`.

**Comment by lukastaegert** [comment]
I believe the correct type is actually an `Acorn.Node`, but Acorn had no official types in 2018. Maybe we should switch to the Acorn type, even though it is just a generic type for all kinds of Nodes.
