### ISSUE TITLE
Track object modifications via "this"

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#2345]
Taken from https://github.com/rollup/rollup/issues/2306#issuecomment-406612021:

In situations where an object is modified via accessing `this` in a function, the modification is not tracked properly. Example:

https://rollupjs.org/repl?version=0.63.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTVDbiUyMCUyMG1vZGlmeSgpJTIwJTdCJTVDbiU1Q3QlMjAlMjB0aGlzLm1vZGlmaWVkJTIwJTNEJTIwdHJ1ZSUzQiU1Q24lNUN0JTdEJTVDbiU3RCU1Q24lNUNub2JqLm1vZGlmeSgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwaXMlMjBtaXNzaW5nISU1Q25pZiUyMChvYmoubW9kaWZpZWQpJTIwY29uc29sZS5sb2coJ01PRElGSUVEJyklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Note that the use of `.call` or `.apply` is handled correctly:
https://rollupjs.org/repl?version=0.63.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25mdW5jdGlvbiUyMG1vZGlmeSgpJTIwJTdCJTVDbiUyMCUyMHRoaXMubW9kaWZpZWQlMjAlM0QlMjB0cnVlJTNCJTVDbiU3RCU1Q24lNUNubW9kaWZ5LmNhbGwob2JqKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGlzJTIwcmV0YWluZWQlMjBhcyUyMG9iaiUyMHdhcyUyMGElMjBjYWxsJTIwcGFyYW1ldGVyJTVDbmlmJTIwKG9iai5tb2RpZmllZCklMjBjb25zb2xlLmxvZygnTU9ESUZJRUQnKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

The modification-tracking needs to consider how a function is called:
https://rollupjs.org/repl?version=0.63.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25vYmoubW9kaWZ5JTIwJTNEJTIwbW9kaWZ5JTNCJTVDbiU1Q25mdW5jdGlvbiUyMG1vZGlmeSgpJTIwJTdCJTVDbiUyMCUyMHRoaXMubW9kaWZpZWQlMjAlM0QlMjB0cnVlJTNCJTVDbiU3RCU1Q24lNUNub2JqLm1vZGlmeSgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwaXMlMjBtaXNzaW5nISU1Q25pZiUyMChvYmoubW9kaWZpZWQpJTIwY29uc29sZS5sb2coJ01PRElGSUVEJyklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Closes #3093 
Closes #2473 
Closes #3027

**Comment by kzc** [comment]
I also encountered this bug in one of my apps.

The following patch fixes all test cases in #2345 and the related issue #2473, however it pessimizes code related to calling empty methods and functions. The resultant code is still correct, just less optimal. I wasn't sure which rollup API to use to determine the associated function that the `MemberExpression` is referencing and whether it had any side effects when called.

```patch
diff --git a/src/ast/nodes/CallExpression.ts b/src/ast/nodes/CallExpression.ts
index 172bd25..624e6da 100644
--- a/src/ast/nodes/CallExpression.ts
+++ b/src/ast/nodes/CallExpression.ts
@@ -17,6 +17,7 @@ import {
        UNKNOWN_VALUE
 } from '../values';
 import Identifier from './Identifier';
+import MemberExpression from './MemberExpression';
 import * as NodeType from './NodeType';
 import { ExpressionEntity } from './shared/Expression';
 import { ExpressionNode, NodeBase } from './shared/Node';
@@ -67,6 +68,12 @@ export default class CallExpression extends NodeBase implements DeoptimizableEnt
                                this
                        );
                }
+               if (
+                       this.callee instanceof MemberExpression
+                       && this.callee.object instanceof Identifier
+               ) {
+                       this.callee.object.deoptimizePath(UNKNOWN_PATH);
+               }
                for (const argument of this.arguments) {
                        // This will make sure all properties of parameters behave as "unknown"
                        argument.deoptimizePath(UNKNOWN_PATH);
```

The patch brought to light an invalid test case in the test suite (test/form/samples/recursive-calls/main.js). The relevant input:

```
$ cat removed6.js
const removed6 = {
        get x () {
                return globalVar ? removed6.x : () => {};
        }
};
removed6.x();
```
```
$ cat removed6.js | node
[stdin]:3
                return globalVar ? removed6.x : () => {};
                       ^

ReferenceError: globalVar is not defined
```
`rollup@1.2.2` incorrectly drops all the code in the example above despite the obvious side effects, but the patch correctly retains it as per the `node` run above.

The following patch variation has no test regressions (beyond that invalid test), however the third test case in the top post no longer works:

```patch
diff --git a/src/ast/nodes/CallExpression.ts b/src/ast/nodes/CallExpression.ts
index 172bd25..4de16a1 100644
--- a/src/ast/nodes/CallExpression.ts
+++ b/src/ast/nodes/CallExpression.ts
@@ -17,6 +17,7 @@ import {
        UNKNOWN_VALUE
 } from '../values';
 import Identifier from './Identifier';
+import MemberExpression from './MemberExpression';
 import * as NodeType from './NodeType';
 import { ExpressionEntity } from './shared/Expression';
 import { ExpressionNode, NodeBase } from './shared/Node';
@@ -67,6 +68,23 @@ export default class CallExpression extends NodeBase implements DeoptimizableEnt
                                this
                        );
                }
+               let v1, v2, v3, v4, v5, v6, v7, v8;
+               if (
+                       this.callee instanceof MemberExpression
+                       && this.callee.property instanceof Identifier
+                       && this.callee.object instanceof Identifier
+                       && (v1 = this.callee.object.variable)
+                       && (v2 = v1.init)
+                       && (v3 = v2.propertyMap)
+                       && (v4 = v3[this.callee.property.name])
+                       && (v5 = v4.exactMatchRead)
+                       && (v6 = v5.value)
+                       && (v7 = v6.body)
+                       && (v8 = v7.body)
+                       && v8.length
+               ) {
+                       this.callee.object.deoptimizePath(UNKNOWN_PATH);
+               }
                for (const argument of this.arguments) {
                        // This will make sure all properties of parameters behave as "unknown"
                        argument.deoptimizePath(UNKNOWN_PATH);
```

@lukastaegert Feel free to adapt the patches or ignore them. I don't plan to work on it further.

**Comment by shellscape** [comment]
@lukastaegert This looks like it's probably still valid. Thoughts?

**Comment by lukastaegert** [comment]
Definitely, and definitely critical. Fixing this is prerequisite for starting work on object member tree-shaking. I actually hope to start rather sooner than later on this.

**Comment by lukastaegert** [comment]
As this is a pressing issue and it will still take some time until I get to properly reworking the foundations of this, I would be open to a pull request for a non-invasive quick fix, even though that might neuter side-effect tracking for object methods.

The quick fix could be:
At the moment, each call expression deoptimizes all call arguments because we do not know if a function call might mutate some of them. When the callee is a MemberExpression, additionally deoptimizing the callee should solve the issue. This would be consistent with treating `this` as an additional parameter, which basically it is.

I should not be necessary to do anything for usages of `.call`, `.apply` or `.bind` as in all these situations, the object that will become `this` is already a call parameter and therefore properly deoptimized.
