### ISSUE TITLE
Cannot import rollup using esm

### ISSUE THREAD

**Issue by onlywei** [rollup/rollup#2347]
Hi everyone,

I want to use rollup via the JavaScript API and also use `import` and `export` in my build files, like the following:

```js
import rollup from 'rollup';
rollup.rollup( ... );
```

The way I am enabling `import` in NodeJS is by installing https://github.com/standard-things/esm, and then executing:

```
node -r esm build.js
```

The error I get is:
```
SyntaxError: Missing export 'default' in ES module: path/to/node_modules/rollup/dist/rollup.js
```

**Comment by lukastaegert** [comment]
Rollup indeed does not have a default export but uses named exports. This is not a problem when using the CJS build but requires a different handling for the ESM build. The correct way to use it is

```js
import {rollup} from 'rollup';
rollup(...);
```
