### ISSUE TITLE
Import of module.exports=require(<file>) don't include default

### ISSUE THREAD

**Issue by MikeTheReader** [rollup/rollup#2352]
I'm having an issue importing the default export from a project that uses a "proxy" file to handle the exports. I've created a repo for it, as that was the easiest way to reproduce the whole problem. That repo is at https://github.com/MikeTheReader/rollup-playground and includes a somewhat deeper explanation of what I'm seeing. Basically, it comes down to trying to include a package that uses a file like `module.exports = require("exportedDefault.js");` doesn't import correctly. I'm able to fix this by changing the file to export the object by hand. Something like:

```
const index = require('./index');

module.exports = {
  default: index.default,
  NAMED: index.NAMED,
  __esModule: true
}
```

but the fact that rollup creates the unwrapExports function call, but does nothing with the response from that call leads me to believe there may be a bug that this is tripping.

This is the closest I could get with a [REPL](https://rollupjs.org/repl?version=0.63.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMFVubmFtZWQlMkMlMjAlN0IlMjBOYW1lZCUyMCU3RCUyMGZyb20lMjAnLiUyRmluZGV4LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coJ1VubmFtZWQnJTJDJTIwVW5uYW1lZCklM0IlNUNuY29uc29sZS5sb2coJ05hbWVkJyUyQyUyME5hbWVkKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJpbmRleC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJtb2R1bGUuZXhwb3J0cyUyMCUzRCUyMHJlcXVpcmUoJ2NvZGUuanMnKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb2RlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwVW5uYW1lZCgpJTIwJTdCJTIwJTVDbiU1Q3Rjb25zb2xlLmxvZygnVW5uYW1lZCcpJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBOYW1lZCgpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnTmFtZWQnKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBVbm5hbWVkJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE).

Thanks for creating a great tool. Please let me know if there's any other information I can provide.

**Comment by lukastaegert** [comment]
Vanilla Rollup does not support reading CommonJS files so you will *need* to include [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs)in your config to be able to load the given file.

If you are already using this plugin, then it is probably an issue with this plugin in that it incorrectly translates the CJS module to an ESM module and the issue should be opened there.

**Comment by MikeTheReader** [comment]
Okay. Thanks much for the feedback. I wasn't clear on where vanilla rollup ended and the plugin started. I will close this and open it over there.
