### ISSUE TITLE
manualChunks option fails with unexpected error if the chunk only contains dynamic imports

### ISSUE THREAD

**Issue by taylorcode** [rollup/rollup#2353]
Hello from Dropbox!

The manualChunks option produces an unexpected error `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined` if the chunk group only contains dynamic imports:
```
manualChunks: {
  dynamic_imports: [
    'src/dynamic_used_by_a.js',
    'src/dynamic_used_by_both.js',
  ],
},
```

Repro here:
https://github.com/taylorcode/rollup-manualchunks-dynamic-import-issue

**Comment by guybedford** [comment]
Thanks for posting the replication here. Turns out this is to do with the dynamic import chunk being empty - if you add any non-treeshakable content it will work in the dynamic module in the example (eg just a console.log statement).
