### ISSUE TITLE
Ignore an import statement as if it wasn't there

### ISSUE THREAD

**Issue by AlbertoElias** [rollup/rollup#2357]
I have a module that uses a dependency that in many sites is available globally. Due to that, I'd like to generate a bundle that doesn't include that dependency, but the rest of the code stays the same.

The `external` option doesn't suit this use case, as the generated bundle still expects an import.

An example of the pre-compiled code:
```js
import ignorableModule from 'ignorable-module';

const test = new ignorableModule.Test();
```
And the generated bundle I want:
```js
const test = new ignorableModule.Test();
```

My use case is for https://github.com/wearesimbol/simbol, I'd like to generate a bundle without `Three.JS`

I tried creating a simple plugin for this:

```js
function ignoreThree() {
	return {
		transform(code, id) {
			if (!id.includes('three')) {
				return;
			}
			return {
				code: `export default window.THREE;`,
				map: null
			};
		}
	};
}
```

But that generates

```js
const test = new undefined();
```

Temporarily, I'm now using `rollup-plugin-replace`:

```js
replace({
			'three': ``,
			include: 'node_modules/simbol/**',
			delimiters: ['import * as THREE from \'', '\'']
		})
```

**Comment by lukastaegert** [comment]
The usual solution to the problem you describe is creating an IIFE bundle and using the `output.globals` option. This allows you to replace imports by available global variables. Of course this will also wrap your code into an IIFE to protect the global namespace and your bundle's namespace from each other.

Unfortunately, this is not available for e.g. ES or CJS modules (yet?). Would creating an IIFE bundle work for you?

**Comment by AlbertoElias** [comment]
No, unfortunately it doesn't as I'm creating a library that serves as an ES
module.

I'm using the replace hack for now, but I definitely think this could be
useful, specially for fronted code where having multiple copies of a
dependency hurts a lot more, and ES imports are static, so you can't check
if a module is there beforehand

**Comment by lukastaegert** [comment]
> I'm creating a library that serves as an ES module

So this means your resulting bundle has other exports and imports that should be retained?

This sounds like a good way forward would be to make `output.globals` work for *all*  bundle types. Which would also be more intuitive I think. The reason it does not work yet is that with the current implementation, it can be handled by the wrapper code of the bundle while making it work for all bundle types would mean feeding the global variable into the variable deconflicting mechanics so it is not shadowed by other variables. Definitely possible but will require some work on our side.

**Comment by AlbertoElias** [comment]
Yes exactly. That would be great actually. Thank you very much, I've been using rollup for some time and it's amazing

**Comment by guybedford** [comment]
@AlbertoElias one option here might be to create a module, `ignorable-module` that you add as a custom resolution (using rollup-plugin-resolve), then containing the source text:

```js
export default IgnorableModule;
```

**Comment by brettz9** [comment]
As a workaround, one can use plugins like https://github.com/jetiny/rollup-plugin-re to just strip out the imports.

**Comment by lukastaegert** [comment]
BTW [rollup-plugin-external-globals](https://github.com/eight04/rollup-plugin-external-globals) might also be worth a look.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by haqer1** [comment]
> BTW [rollup-plugin-external-globals](https://github.com/eight04/rollup-plugin-external-globals) might also be worth a look.

I left this comment for myself:
/* Works partially: leaves util.format while util is not defined (only function is imported, & importing everything would be wasteful)

P.S. rollup-plugin-re worked out better in my case once lack of documentation was overcome.
