### ISSUE TITLE
Rollup no longer warns when no name was provided for global module

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup#2358]
In the previous versions of rollup when no name was provided for a `global` one would get a warning stated something along;
 ```
ionic-angular (guessing 'ionicAngular')
```

However this is no longer the case when you use `globals` is specified. If it's specified and the value returned `undefined` or `null` no warning will be emitted and in the final output even if the moduleName won't be resolved.

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('ionic-angular')) :
	typeof define === 'function' && define.amd ? define(['ionic-angular'], factory) :
	(factory(null));
}(this, (function (ionicAngular) { 'use strict';
})));
```

I would expected that there would be a warning when I specify the `globals` option however I dont set it for a specific module.

rollup.config.js
```
export default {
    input: 'index.js',
    output: {
        file: 'bundle.js',
        format: 'umd',
        globals: []
    }
};
```
index.js
```
import * as foo from 'ionic-angular';
```

Terminal
```
Alans-iMac:rollup-test alan$ node_modules/.bin/rollup -c rollup.config.js

index.js → bundle.js...
created bundle.js in 10ms
```

Relates to: https://github.com/dherges/ng-packagr/pull/1026

**Comment by guybedford** [comment]
Apologies for the regression, my fault :)
