### ISSUE TITLE
What does double at symbol (@@) in the docs mean?

### ISSUE THREAD

**Issue by myshov** [rollup/rollup#2361]
Hi!
I can't understand this phrase in docs:

> @@8 will set process.env.INCLUDE_DEPS === 'true' and process.env.BUILD === 'production'.

What does @@ mean? The version of the library or something else?

**Comment by lukastaegert** [comment]
Thanks for pointing this out. This issue was caused by incorrectly formatted documents in our documentation. I created a fix that should go live shortly. Note that you might need to empty your cache for the new version to show up.
