### ISSUE TITLE
Consider supporting transformDependencies for load

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2363]
From discussion at https://github.com/rollup/rollup/pull/2259#issuecomment-406855965.

If you look at even standard examples like https://github.com/rollup/rollup/pull/2259/files#diff-db4f35ec21ccb04b7e2a26b7654c4397R327 they are use cases that can be handled via `load`.

Perhaps we need to think a little more generally about this.

//cc @eight04 @keithamus

**Comment by eight04** [comment]
I think when some code is generated by the plugin, the plugin should be able to define the dependency at that point. This includes `load`, `transform`, and maybe `transformChunk` (inline license header, footer, etc).

**Comment by guybedford** [comment]
One thing that would make this simpler is actually just changing it from `return { dependencies }` to a contextual function - `this.addWatchDependency(name)`.

**Comment by guybedford** [comment]
This could also replace the asset dependencies argument currently in place as well.

**Comment by guybedford** [comment]
I've looked into this quite deeply, and I think the complexity added to the whole system outweighs the benefit over just keeping dependencies to the `transform` function.

So I'd suggest rather sticking to using the `transform` hook for doing this after all. Happy to discuss further.

**Comment by guybedford** [comment]
(note the complexities are specifically around caching here)

**Comment by guybedford** [comment]
I ended up implementing a `this.addWatchFile` in https://github.com/rollup/rollup/pull/2389.
