### ISSUE TITLE
Reserved paths "\0" are unnecessary chunked

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#2365]
This what I get trying to bundle my app with rollup. Would be good to skip reserved paths.

```js
System.register(['./chunk-43c2cf49.js', 'styled-system', 'commonjs-proxy:styled-system', 'utils/styled-system'], function (exports, module) {
  'use strict';
  var commonjsGlobal, unwrapExports, createCommonjsModule, React, PropTypes, _react, _propTypes, assign, react_1, react_2, react_4, reactDom_2, classnames, _Transition, _reactDom, _TransitionGroup, react, react_3, react_5, react_6, react_7, react_8, react_9, react_10, invariant, _warning, emptyFunction, cn, reactDom_3, reactDom, reactDom_1, TransitionGroup, Transition, containsNode, getActiveElement, camelize, hyphenate, left, right, display, space, _styledSystem, sColor;
  return {
    setters: [function (module) {

```

Also is there a way to disable chunking other than with dynamic import? It's useful sometimes to have more control over code splitting through the code rather than with configuration.

**Comment by lukastaegert** [comment]
I guess the appearance of `\0` paths should be considered a bug.

> Also is there a way to disable chunking other than with dynamic import?

Could you elaborate what you have in mind here? Non-dynamic chunking means you have several entry points in your config. Should those be merged in some way? How would you envision controlling the code-splitting via code apart from dynamic import?

Depending on how it could work, it might also be possible to achieve this via plugin or maybe extend the plugin API to make this possible. I.e. imports following a certain format could generate new entry-points?

**Comment by TrySound** [comment]
Here's my structure
```js
// index.js
import { Page3 } from './Page3.js';
render(import('page-1.js'))
render(import('page-2.js'))
render(Page3)
// page-1
export const Page1 = () => {}
// page-2
export const Page2 = () => {}
// page-3
export const Page3 = () => {}
```

I want to get this output
```
index.js
page-1.js
page-2.js
```

Is it possible with current design?

**Comment by guybedford** [comment]
@TrySound did you try using the `optimizeChunks` option here perhaps? That will automatically merge chunks together when they are under a size threshold. Although you may need to modify the size thresold itself and there isn't much more control than this.

If you want it flattened the other alternative is simply to add `import './page-1.js'` and `import './page-2.js'` into the `index.js` file :)

**Comment by guybedford** [comment]
The null character thing does seem a separate issue though... do you know why it's doing that?

**Comment by lukastaegert** [comment]
@guybedford Which PR did the "fixed pending release" label refer to? Is this fixed now?

**Comment by TrySound** [comment]
After playing with configuration I cannot reproduce this anymore.

**Comment by lukastaegert** [comment]
Closing this due to the previous comment. Feel free to reopen if this is still an issue.
