### ISSUE TITLE
Support output.globals for other formats

### ISSUE THREAD

**Issue by eight04** [rollup/rollup#2374]
Related: https://github.com/rollup/rollup/issues/1665

Currently, `output.globals` is only used if `format` is `iife` or `umd`. If `format` is `es` and we want to map the external module to a global variable, we usually solve it with a shim/alias plugin (e.g. `export default $`). However, this solution doesn't work well with `experimentalCodeSplitting`. When code splitting is enabled, the shim module would be chunked instead of being inlined:
*entry.js*
```js
import $ from "./chunk-xxx.js";
...
```
*entry2.js*
```js
import $ from "./chunk-xxx.js";
...
```
*chunk-xxx.js*
```js
export default $;
```
By enabling `output.globals` for other formats, we can avoid sharing the shim module.

Another solution is to enable code splitting for `iife` when there is no shared dependency (or marking all shared dependencies as externals). Related: https://github.com/rollup/rollup/issues/2072

**Comment by eight04** [comment]
I made a plugin to handle this:
https://www.npmjs.com/package/rollup-plugin-external-globals

**Comment by lukastaegert** [comment]
+1 from me, I think this would make the experience much more consistent. It might not be easy to implement, though. At the moment, this option is only handled in the wrapper code added for the format.

It might be possible to handle this via adjusting the rendering logic to protect the globals from being deconflicted and just use the global names whenever the import is accessed.

**Comment by lukastaegert** [comment]
BTW had a look at your plugin, very nice! Seems the only thing missing is to hook it to the deconflicting mechanics (which is not directly exposed to plugins). To properly link it here, this would also resolve #2357.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by curran** [comment]
I faced a similar challenge and this is the solution I landed on: https://github.com/curran/rollup-react-pwa-example

Long story short:
 * The main client bundle uses iife format, so Rollup globals config works fine there.
 * The lazy loaded client bundle uses amd format. Rollup globals config _does not_ work there, however I used the `aliases` feature of `d3-require` (lightest AMD loader I could find) to accomplish the same thing.

**Comment by shellscape** [comment]
@lukastaegert have resisted getting into the business of maintaining one, but maybe it's time

**Comment by tschaub** [comment]
In our case, we're generating an `iife` build, and I'm surprised that `output.globals` isn't working.  I assumed that Rollup wouldn't even try to parse dependencies in this `output.globals` lookup, but it looks like that is not the case.  We were using the `rollup-plugin-external-globals` plugin to work around this.

I should try to create a simpler reproducible example, but here is a commit where I try to replace `rollup-plugin-external-globals` with the `output.globals` config: https://github.com/openlayers/openlayers/pull/15241/commits/effc55977e62b13ae8db0fd587fbee97a431c1c6.  And some detail on the failure here: https://github.com/openlayers/openlayers/pull/15241#issuecomment-1783201020
