### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#2377]
Regarding to @guybedford it's known that rollup is using a lot of memory (at least when used with `experimentalCodeSplitting`) - https://github.com/reakit/reakit/pull/168#issuecomment-410509574 . There is no issue tracking this, so here you go 😉 

**Why I'm even reporting this?**

CI build is taking over 15 minutes, whereas on my machine it's totally fine - just several seconds.

**Comment by shellscape** [comment]
@Andarist I believe the CI service used makes a difference as well here. Travis CI is notoriously awful with both resource allocation and memory allocation. Circle CI on the other hand, fares much better, and even more so when providing user-built images. While it doesn't address any potential memory issues in Rollup, it would be beneficial for your project immediately. I see from [your repo](https://github.com/reakit/reakit/blob/master/.travis.yml) that you're using Travis at the moment. If you would like to dabble with Circle (which I'm working on getting Rollup on) you can take a look at our [containers](https://github.com/rollup/containers) repo for building your own Docker containers for use on Circle. Aside from CI choice, I'll let those with more intimate knowledge of Rollup take the reigns on addressing memory use.

**Comment by Andarist** [comment]
We've found the culprit - at least in our case. It is `rollup-plugin-filesize`, gonna raise the issue there.

**Comment by guybedford** [comment]
@Andarist great to hear you sorted out the issue, and glad the new memory output could come in handy.
