### ISSUE TITLE
Webpack => Rollup test & feedbacks

### ISSUE THREAD

**Issue by Makio64** [rollup/rollup#2378]
Hi everyone, 

To give some context I'm a Webpack user and I tried Rollup over this weekend. After fews hours I get it works as my webpack with this config : [rollup.config](https://gist.github.com/Makio64/4878a315fae053d24f80908456a47622)

As I read the team was looking for feedbacks here we are !

First of all : **Rollup is great, the config might be tricky but the treeshaking is more effective than webpack and the generated code more clean** ( using the same babel config on Webpack & Rollup ).

**My 2 configs tricky points** :  The relative path setup for js/stylus/... & make the codesplitting works 

**The path setup** 
This one was really harder than I expected, i'm using 5 plugins to have it works correctly as I want : includePaths, rootImport, node-resolve, node-builtins, babel-plugin-module-resolver

In webpack it will be simply: 
```
	resolve: {
		extensions:['.json','.js','.styl','.html'],
		modules: [
			path.resolve(__dirname,'src/js'),
			path.resolve(__dirname,'src/stylus'),
			path.resolve(__dirname,'node_modules'),
		]
	},
```
Would be great to have a similar simple config for this part.

**The code splitting** 

My config  : 
```
	experimentalCodeSplitting : true,
	input: 'src/js/Preloader.js',
	output: {
		name: 'bundle.js',
		entryFileNames :'bundle.js',
		globals: 'bundle',
		// file: 'app/bin/bundle.js',
		dir: 'app/bin/',
		format: 'esm'
	},
```

About it:
- Many sources/articles on codeSplitting with Rollup mention experimentalDynamicImport, maybe adding a warning as this is not needed anymore will be nice: currently it just said the option doesnt exist.

- I was surprise I have to add 'dir/entryFileNames' and remove 'file'. It can simplify using **_file: 'app/bin/bundle.js'_**, from this its easy to find the directory / entryFileNames / name with maybe an optional 'chunkFilename' as webpack. Then the same config can be use with/without codeSplitting, only depending on _experimentalCodeSplitting : true/false_.

- Finally the js code : it took me some times to find a way to make the same code works in both Webpack & Rollup, here we are :
```
		// Rollup & Webpack dynamic code splitting ( bundles )
		import('./Main.js').then((Main) => {
			new Main.default()
		})
```
Not so pretty but it works on both.

Again Webpack will have a easier config as the user dont need to change the html with type='module'. Include systemjs or the equivalent of runtime.js from webpack will be nice by default.

------

Voila, sorry if it was a bit long, I'm pointing fews issues here instead of creating many issues but it give an overview of what it feels to migrate from Webpack to Rollup.  Again globally i felt good about Rollup and was happy to make it work as my webpack with better bundle compression in the end!

Hopefully it helps, thanks for your work!

Cheers

D

**Comment by shellscape** [comment]
This is a great user story. Thanks for writing it! What would your suggestions be for the project to make this kind of thing easier for folks who are interested in it?

**Comment by guybedford** [comment]
It is really great to get feedback like this indeed - thanks for taking the time to write up your experiences @Makio64.

> I was surprise I have to add 'dir/entryFileNames' and remove 'file'. It can simplify using file: 'app/bin/bundle.js', from this its easy to find the directory / entryFileNames / name with maybe an optional 'chunkFilename' as webpack. Then the same config can be use with/without codeSplitting, only depending on experimentalCodeSplitting : true/false.

This is something that has already been worked on in the 1.0 branch, and I'm hoping to bring it back into a current release soon. (in the case of only a single chunk though, for more than one chunk, the directory is needed to distinguish things properly)

> Finally the js code : it took me some times to find a way to make the same code works in both Webpack & Rollup, here we are :

I'd be interested to hear what you were trying that was working in webpack but not Rollup, and vice versa as well.

**Comment by Makio64** [comment]
@shellscape Create fews examples of complete rollup.config gist is the fastest way to make peoples understand and using it for example : 
- rollup.config for babel / [css,stylus,sass] / livereload 
- rollup.config for react / typescript / livereload
- rollup.config for dynamicChunks ..

Adding this after the getting start will help peoples create their config faster and not spend much time on it.

@guybedford 
Nice for the 1.0 branch! In case of multiple chunks dir can still be optional using this rule : 
- if the file option is "/app/bundle.js" then the directory is app/
- if the file option is "bundle.js" then the directory is ./

I didnt save the options of code splitting I tried for rollup/webpack but the example of rollup wasnt working with webpack for sure.

**Comment by alundiak** [comment]
> experimentalDynamicImport, maybe adding a warning as this is not needed anymore

@Makio64  
Not needed anymore because it's unflagged/removed from codebase or what? How did u set up ur config for building JS code with dynamic imports? I spend searching 3 days, and no success. Looks like either outdated, or missing babel/polyfill or smth else I don't get.


In regards Webpack vs. Rollup, I would love all similar tools merge into * one but * great :) I don't get why should we follow so much similar approaches which in fact do the same * thing.

PS. Now, I'm looking to Parcel, because it's config-less, and I expect it will doing same thing as Webpack and Rollup. Maybe with less pain for me.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
