### ISSUE TITLE
Investigate possible off-by-one sourcemaps line issue

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2379]
I've been noticing this for a while, but I think the source maps of Rollup itself have an off by one issue where the line number is one more than it should be. This can be seen when debugging or tracing the source map.

Would be good to investigate further as it may be affecting more than just our build.

**Comment by shellscape** [comment]
@guybedford @lukastaegert does this issue persist?

**Comment by lukastaegert** [comment]
I keep stumbling about this myself. Hope we can get to the bottom of this soon.

**Comment by guybedford** [comment]
I haven't seen this at all recently, so closing without a replication.
