### ISSUE TITLE
Malformed exports in chunks when code splitting

### ISSUE THREAD

**Issue by gregmagolan** [rollup/rollup#2391]
- Rollup Version: 0.64.1
- Operating System (or Browser): OSX (any browser)
- Node Version: 8.11.1

### How Do We Reproduce?

See https://github.com/gregmagolan/rollup-code-splitting-issue-repro

I ran into this issue when rolling up a much larger application. The minimal reproduction repo shows the same symptoms.

### Expected Behavior

Exports in chunks are generated correctly.

### Actual Behavior

Exports in chunks are malformed. Seems to be related to usage of the `export * from 'x'` form.

**Comment by gregmagolan** [comment]
@lukastaegert I tried this with rollup 0.55.0 as well and the same issue shows up so it doesn't look like it was introduced with #2068 or ##2118

**Comment by gregmagolan** [comment]
@lukastaegert Was looking through the chunking code in more detail and the TODO
```
            // TODO: there is one special edge case unhandled here and that is that any module
            //       exposed as an unresolvable export * (to a graph external export *,
            //       either as a namespace import reexported or top-level export *)
            //       should be made to be its own entry point module before chunking
```
Is that the edge case I'm running into?

**Comment by guybedford** [comment]
Thanks for the clear replication, this is definitely a bug. Whether it's specifically that comment or not I don't know yet, but it's certainly a related issue.

Will look into this soon.

**Comment by guybedford** [comment]
I managed to put a fix together for this in https://github.com/rollup/rollup/pull/2408. Should be released within the next week I expect. Thanks again for the clear test case.
