### ISSUE TITLE
Clarify transformBundle deprecation

### ISSUE THREAD

**Issue by AgronKabashi** [rollup/rollup#2395]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
Based on the documentation in the [plugin wiki](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins) and the description in PR #2208 one would assume that the hook `transformBundle` was replaced with `transformChunk` and thus not part of the API anymore. This is not the case however since rollup will currently call either `transformChunk` **or** `transformBundle` to prevent plugins conforming to the older API from breaking.

### Your Proposal for Changes
The documentation should clearly state that `transformBundle` has been deprecated (and not yet replaced).

**Comment by guybedford** [comment]
Thanks, yes this is a task for the 1.0 release candidate ensuring the deprecations are very clear.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
