### ISSUE TITLE
Why isn't the output tree-shaken?

### ISSUE THREAD

**Issue by ceremcem** [rollup/rollup#2396]
[Here is the example repo](https://github.com/ceremcem/rollup-test) that contains everything needed. 

[My question is](https://github.com/ceremcem/rollup-test/issues/2) : Why isn't the `dist/rollup-bundle.js` tree-shaken?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by ceremcem** [comment]
@shellscape Would you please re-open this issue?

**Comment by shellscape** [comment]
@ceremcem we're about a year out from when this was posted, and this looks like more of a support request than a bug report. Please try one of the support options first, and let us know if there's a bug identified. 

>  👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

**Comment by ceremcem** [comment]
Yes, it was a support request. I tried to get a help on gitter: https://gitter.im/rollup/rollup?at=5b6ddc305b07ae730a9e509f and they redirected me here. Okay, I'll ask it at SO. Thanks.
