### ISSUE TITLE
Proposal: Use Chokidar by default

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2403]
### Feature Use Case

Given the number of issues with Node.js fs watchers, it seems like using chokidar by default would improve the user experience for most users and help avoid painful issues, while also simplifying the workflow overall here.

### Feature Proposal

I take it the reason we don't include Chokidar by default is due to our unique build and not wanting to add a big dependency to the project?

Some options here might include:

* Have Chokidar as an optionalDependency (although npm will still install on Rollup install then)
* Build Chokidar into a chokidar.js file that is `require`'d by Rollup Node only when needed
* Prompt users to install Chokidar as soon as they use the watcher, or even do this install automatically into the local project as a devDependency.

Personally I think the "dependency aversion" has been taken a little too far here in sacrificing the user experience, and that having chokidar as a normal dependency would be fine.

**Comment by guybedford** [comment]
To also explain reasoning here - one of the reasons I'm bringing this up now is that I'm looking at https://github.com/rollup/rollup/issues/2383 to expose watcher events, and the Node.js file events have zero file context information that can be assumed by default, apart from "something happened here".

**Comment by guybedford** [comment]
Actually, for now, the simplest thing will be to just do the simplest naive hook of just noting an id has changed.

**Comment by lukastaegert** [comment]
Ok. Feel free to reopen this one as the idea of always using Chokidar doers not seem entirely bad to me on first glance.
