### ISSUE TITLE
how can i avoid rollup to package the base library ，like fs，path，http。

### ISSUE THREAD

**Issue by sanriqing** [rollup/rollup#2411]
emmm,i code a nodePlugin,when i run build。。。 
I got this --》

[!] Error: Could not load _http_client (imported by /myproject/libdemo/node_modules/proxying-agent/lib/proxying-agent.js): ENOENT: no such file or directory, open '_http_client'
Error: Could not load _http_client (imported by /myproject/libdemo/node_modules/proxying-agent/lib/proxying-agent.js): ENOENT: no such file or directory, open '_http_client'
    at /Users/yuanjiawang/.nvm/versions/node/v10.2.0/lib/node_modules/rollup/dist/rollup.js:21360:19

**Comment by shellscape** [comment]
> 👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Please try one of our suggested support options before opening an issue.

**Comment by sanriqing** [comment]
@shellscape 
tks very much...... I've looked up Google ,strackoverflow，but no answer was found.（Half a day passed）anyway ,tks again.
