### ISSUE TITLE
Malformed entry point & missing export in chunk when code splitting

### ISSUE THREAD

**Issue by gregmagolan** [rollup/rollup#2413]
- Rollup Version: 0.64.1
- Operating System (or Browser): OSX (any browser)
- Node Version: 8.11.1

### How Do We Reproduce?

See https://github.com/gregmagolan/rollup-code-splitting-issue-2-repro

I ran into this issue when rolling up a much larger application. The minimal reproduction repo shows the same symptoms.

### Expected Behavior

Entry point has valid symbol & that symbol is exported out of the chunk it resides in.

### Actual Behavior

Entry point has invalid symbol & that symbol is not exported out of the chunk it resides in.

**Comment by gregmagolan** [comment]
@guybedford @lukastaegert Here's the next rollup code-splitting issue I ran into after getting past #2391. Do you have some time to take a look? Thanks

**Comment by guybedford** [comment]
I will be looking into this soon, likely tomorrow or Thursday.

**Comment by guybedford** [comment]
I've posted a fix at https://github.com/rollup/rollup/pull/2420.

**Comment by gregmagolan** [comment]
Thanks @guybedford! You rock. I tried out your fix and I found no more issues with the chunks.

I'm now able to rollup an angular application with angular built from source using a bazel rollup_bundle role: https://github.com/gregmagolan/angular-bazel-example/tree/code-splitting
