### ISSUE TITLE
Transpiled generator functions cannot be tree shaken

### ISSUE THREAD

**Issue by conartist6** [rollup/rollup#2423]
- Rollup Version: 0.57.1
- Operating System (or Browser): Mac OSX 10.13.4
- Node Version: 10.9.0

### How Do We Reproduce?

REPL reproduction: [here](https://rollupjs.org/repl?version=0.65.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QmZvbyU3RCUyMGZyb20lMjAnLiUyRmluZGV4JyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJpbmRleC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBmb28lN0QlMjBmcm9tJTIwJy4lMkZmb28nJTNCJTVDbmV4cG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMGJhciU3RCUyMGZyb20lMjAnLiUyRmJhciclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbigpJTIwJTdCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwX3JlZ2VuZXJhdG9yUnVudGltZSUyMGZyb20lMjAlNUMlMjIlNDBiYWJlbCUyRnJ1bnRpbWUlMkZyZWdlbmVyYXRvciU1QyUyMiUzQiU1Q24lNUNudmFyJTIwX21hcmtlZCUyMCUzRCU1Q24lMkYqJTIzX19QVVJFX18qJTJGJTVDbl9yZWdlbmVyYXRvclJ1bnRpbWUubWFyayhiYXRjaCklM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGJhdGNoKG51bWJlciUyQyUyMGl0ZXJhYmxlKSUyMCU3QiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior
Unused function is tree shaken

### Actual Behavior
No tree shaking occurs

**Comment by conartist6** [comment]
It would seem that this is would be fixed by recognizing the `/*#__PURE__*/` comment, lack of support for which is tracked in #1293.

**Comment by conartist6** [comment]
Proposed test case:
```const negligableEffects = [];
function hasNegligableEffects(arg) {
	negligableEffects.push(arg);
}

/*#__PURE__*/ hasNegligableEffects();

assert.equal(negligableEffects, []);
```

**Comment by conartist6** [comment]
Sorry Github you get to be my rubber duck.

So I've got the test code, I managed to hit a debugger statement inside `CallExpression.prototype.hasEffects` while running only that test (using `mocha --inspect-brk`, and `config.solo`).

Now the only problem is that the comments don't appear to be in the AST. This is, presumably, the hard part. Fortunately it looks like rollup uses just one parser, acorn, so I won't have to deal with different parsers emitting comments using different semantics. Acorn emits comments to the onComments callback, but doesn't try to attach them to the DOM.

Rollup [collects comments onto Module instances](https://github.com/rollup/rollup/search?q=onComment&unscoped_q=onComment) but I'll need some fast way to join the data -- either a lookup of nearby AST nodes from a comment, or a lookup of nearby comments from an AST node. Since Modules have ASTs (but not the other way around), I guess I'll be looking for a module lifecycle method to iterate over comments finding those that mark something pure, and then finding the most relevant AST node and flagging it with, say, `markedPure: true`.

**Comment by conartist6** [comment]
I notice that I could attach module comments to `astContext` which is available in the program, but that would mean that every function call would need to go search through the possible pure marker comments and determine whether they were adjacent to the function call. This seems expensive error-prone and silly to me.

More promising is acorn's `walk.findNodeAfter(ast, pos, ...)` function. The question is, is it fast enough? Unfortunately the answer seems likely to be "no" since it will have to do a walk of the tree per magic comment. The implementation of that function is relatively simple though it seems, and since its semantics are [mostly] correct perhaps it could be copied and modified sufficiently to allow "sticky" searching.

**Comment by conartist6** [comment]
Well, indeed `findNodeAfter` is desirable, as is doing a walk with that algorithm which does not terminate upon finding the first result.

Unfortunately...

Acorn doesn't define a kind of walk that will work. findNodeAfter is pretty much the only kind of walk which does its testing on every node *before* recursing on the node's children. That is the special sauce which makes it work correctly -- grabbing the largest expression which starts after the comment. Recursive walks would solve the timing issue, but contain no provision for running a callback on every node.

I guess it's time to make a PR to acorn adding a new walk... I'm quite sure I was trying to accomplish something specific and (I thought) easy before I found myself modifying parsers.

**Comment by conartist6** [comment]
I have added the aforementioned PR to acorn. Fortunately they don't have tests, so there's not much work to do there -_-

https://github.com/acornjs/acorn/pull/721

**Comment by lukastaegert** [comment]
Hi @conartist6,

nice digging into this! I think performance is indeed a major concern here for which I see several possible solutions. On acorn side, my thought was always that the best approach would be to provide succeeding nodes directly in the onComment hook. Did not dig into if this is feasible for acorn but my guess is that it would save us and them a complete tree iteration if we just add the comments once we encounter the next node.

As this is probably difficult, your approach might be the next best thing.

If this does not go through, then faster than a tree-walk might actually be an on-demand backward text search. To my understanding, `/*#__PURE__*/` annotations are only recognized by call expressions anyway. So each call expression might do a backward search through the original source code until it encounters a non-whitespace character and then checks if it is a pure annotation.

Might need some addition to the ast context, though, as I think the original source is only available at rendering at the moment.

Annotations are not really loved by everyone, though. Our "usual approach" would be to try to improve the analysis but this does not work for external libraries for obvious reasons. What would work with hardly any performance overhead would be adding an option to specify pure functions for external imports. E.g. something like

```js
pureExternalImports: {
  "'@babel/runtime/regenerator'": ["default"]
}
```

This option could then in turn be added by `rollup-plugin-babel` so it would cause no friction for rollup users.

**Comment by lukastaegert** [comment]
> Fortunately they don't have tests

I am not so sure I feel the same way about this... Things I did not want to know.

**Comment by guybedford** [comment]
@conartist6 how is this function pure in the first place though, as the regenerator runtime will mutate that function?

**Comment by conartist6** [comment]
@lukastaegert  Don't worry it's only the walk functions that don't seem to be tested.  I think the backwards text search might work quite well, Rollup definitely does have the source available to it. The regenerator runtime is not external in this case, it's just a another file in `node_modules` but it makes every conceivable effort to be impervious to static analysis.

I understand that annotations aren't the greatest, but I also figure that including code transpiled by regenerator is going to be a relatively common case in the future as more programmers learn how to write generator functions. I'd rather not embrace a solution that will require that they all hunt down a new configuration option like pureExternalImports.

@guybedford The particular function in the regenerator runtime is responsible for swapping out the prototype chain of a function. It's obviously not the slightest bit pure itself; we'd never want to drop it, though fortunately its result is always used. We know because the transpiler did that the function does not have side effects in the original program, since declaring a generator function is pure.

**Comment by conartist6** [comment]
@lukastaegert On providing succeeding nodes in the onComment hook, that seems likely to be impossible as they won't have been parsed yet.

**Comment by conartist6** [comment]
Oh and finally I don't think the tree walk is bad at all. The AST works exactly like a search tree in this case, though it may not necessarily be well balanced it seems unlikely it'd be so unbalanced either. If there are no comments, we don't even have to do the walk, and we can quit walking once we've found all the comments.

**Comment by nathancahill** [comment]
Following this. Thanks for picking up the baton on this @conartist6.

> Our "usual approach" would be to try to improve the analysis but this does not work for external libraries for obvious reasons..

Not just external libraries, but vanilla JS code is provably impossible to completely statically analyze. Even accessing a getter might run unpure code. So I'd love to see `/*#__PURE__*/` annotation support as a fallback option for when all else fails.

**Comment by conartist6** [comment]
@nathancahill No problem, in the use case I have it's pretty important.

I've opened https://github.com/acornjs/acorn/pull/721 to track the needed changes to Acorn in order to use what I'm pretty sure is the most optimal strategy for implementing this feature, however it was summarily rejected. I hope the author will reconsider.

**Comment by leeoniya** [comment]
have you guys seen https://github.com/cherow/cherow?

it claims to be smaller and faster than acorn, "Emits an ESTree-compatible abstract syntax tree.", and may handle more cases.

**Comment by conartist6** [comment]
Shall I try swapping it in and see how the test suite holds up?

**Comment by conartist6** [comment]
I'm rather worried that it has a bug like this open https://github.com/cherow/cherow/issues/232

**Comment by leeoniya** [comment]
i think the v2 rewrite is coming along pretty fast. the velocity has slowed down a bit, but it sounds like it should get going again soon. https://github.com/cherow/cherow/issues/233

i imagine they'd find some additional motivation if they knew Rollup was evaluating replacing Acorn with Cherow ,too ;)

**Comment by conartist6** [comment]
I made a mistake, I actually can implement what I need without acorn changes. Will submit a PR here today or tomorrow!
