### ISSUE TITLE
Code splitting is duplicating Preact across output files

### ISSUE THREAD

**Issue by enure** [rollup/rollup#2425]
- Rollup Version: v0.65.0
- Operating System (or Browser): Mac OS 10.13.6
- Node Version: v9.11.2

### How Do We Reproduce?

See repro at https://github.com/enure/rollup-codesplit-preact-duplication.

### Expected Behavior

Preact would be included once in shared chunk in the output.

### Actual Behavior

Preact is included in both "bundle-dynamic-import.js" and "bundle-main.js".

At the top of both "bundle-*" files you will see:

```JavaScript
var VNode = function VNode() {};

var options = {};

var stack = [];

var EMPTY_CHILDREN = [];

function h(nodeName, attributes) {
	var children = EMPTY_CHILDREN,
	    lastSimple,
	    child,
	    simple,
```

Thank you for any assistance.

**Comment by enure** [comment]
I should note that I was seeing duplication of other modules across outputted files, however my repro only shows duplication of Preact.

**Comment by lukastaegert** [comment]
Hi, I checked out your repo and actually did not get any duplication (I have a theory, though, so see below). What did I do:
* Check out a fresh copy of your repo
* `cd cd rollup-codesplit-test-main`
* `yarn` (this part was not mentioned in your instructions but is definitely important and may in some way have to do with your issues)
* `npx rollup -c`

What I think happened for you:
I noticed you have quite a few package.json files and yarn.lock files lying around which all contain `preact` as a dependency. What has probably happened is that the different entry points imported `preact` from different `node_modules` folders. Even though the files may be identical in those situations, Rollup uses their full path to distinguish modules so it will think those are different modules which will lead to the duplication you noticed. In order for duplication-free code-splitting to work, you should make sure there is only a single node_modules folder from which all dependencies are resolved.

**Comment by enure** [comment]
The repro repo contains three folders, where each one is a unique node module. This mimics the setup I’m working with currently at work. One base project with shared es6 modules, and two dependent projects. For ease of repro I used the ‘file:’ syntax to link the dependencies rather than publishing dummy modules to npm.

I’m surprised you didn’t get the same repro but thank you for checking it out and providing the possible explanation. I also am wondering if using yarn link locally is causing me issues, since I think that would expose more node_modules folders.

Again thank you and I’ll take another look in the morning. I’ll also see if rollup can log the paths to the modules it’s bundling.

**Comment by lukastaegert** [comment]
> I’ll also see if rollup can log the paths to the modules it’s bundling

You can do this by adding a pseudo plugin to your plugins section that just has a `load` hook that does not return a value:

```
...
plugins: [
  { load(id) {console.log(id)} },
  ... // other plugins
]
```

This will simply log the paths of all modules that are loaded.

**Comment by enure** [comment]
```
$ npx rollup -c | grep preact

./bundle-dynamic-import.js, ./bundle-main.js → codesplit...

./rollup-codesplit-test-main/node_modules/rollup-codesplit-test-dynamic-import/node_modules/preact/dist/preact.mjs
./rollup-codesplit-test-main/node_modules/preact/dist/preact.mjs
./rollup-codesplit-test-main/node_modules/rollup-codesplit-test-dynamic-import/node_modules/rollup-codesplit-test-shared/node_modules/preact/dist/preact.mjs
./rollup-codesplit-test-main/node_modules/rollup-codesplit-test-shared/node_modules/preact/dist/preact.mjs

created codesplit in 263ms
```

My directory names are obnoxiously long, but as you can see here if you do have a node_modules directory in one of your dependencies, rollup will potentially use modules from that directory.

I would instead expect that it would use the modules only from the dependent projects directory.

I think this behavior could happen either when using `file:...` to link to local dependencies on the file system, or when using `yarn link` or `npm link`.

Thank you for pointing me towards a solution.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
