### ISSUE TITLE
Imported modules that have a package.json beside or above them will not be transpiled by babel plugin

### ISSUE THREAD

**Issue by blakemann** [rollup/rollup#2427]
# Expected Behaviour:
- Babel plugin should transpile all code in bundle / chunks

# Actual Behaviour:
- Some modules files will not be transpiled within the bundle if there is a `package.json` file in the same directory, or a parent directory, of the module to be imported.

# Minimal Example:

- [dependency-transpile-test.zip](https://github.com/rollup/rollup/files/2326225/dependency-transpile-test.zip)

# Summary of Example:

```javascript
// src/test.js

import { addSpaces } from '../dependencies/src/dependency.js';

class SayHello {

    constructor(){
        let string = 'Hello World';
        console.log(addSpaces(string));
    }

}

new SayHello();
```
```javascript
// dependencies/src/dependency.js

export function addSpaces(x){
    let y = '';
    x.split('').forEach((letter) => {
        y = `${y} ${letter}`;
    });
    return y;
}
```
```javascript
// dependencies/package.json

{} // file doesn't even need to have anything in it, just needs to exist and be valid json
```
```javascript
// rollup.config.js

import babel from 'rollup-plugin-babel';

export default {
    input: 'src/test.js',
    output: {
        file: 'dist/test.js',
        format: 'esm'
    },
    plugins: [
        babel()
    ]
}
```

# Resulting Bundled Code:
**_(result of running rollup with `esm` format and `babel` plugin)_**

```javascript
// dist/test.js

function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
}

function addSpaces(x) {
  let y = '';
  x.split('').forEach(letter => {
    y = `${y} ${letter}`;
  });
  return y;
}

var SayHello = function SayHello() {
  _classCallCheck(this, SayHello);

  var string = 'Hello World';
  console.log(addSpaces(string));
};

new SayHello();
```

Notice how the `addSpaces` function does not get transpiled. If you simply remove the `package.json` file from the `dependencies` directory, and re-bundle, the function will be correctly transpiled.

**Comment by lukastaegert** [comment]
My feeling is that this should actually be raised with `rollup-plugin-babel` as Rollup itself does not resolve dependencies and does not look for package.json files.

**Comment by blakemann** [comment]
@lukastaegert Yes, I would agree with that actually. I apologize, when I was creating the issue I was thinking it was either a rollup issue or a babel issue, and it totally slipped my mind that the plugin is it's own intermediary entity with it's own repo.

I'll close this one and re-open it there!

**Comment by blakemann** [comment]
For reference:
rollup/rollup-plugin-babel#242
