### ISSUE TITLE
renderChunk should be part build process

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#2434]
### Feature Use Case

Uglify in worker. I need to setup worker in for each build in `buildStart` and destroy worker in `buildEnd`. The problem is that `renderChunk` is called after `buildEnd`. As a workaround I can put `worker.end()` inside `generateBundle` hook but if one of `renderChunk` will throw an error then worker will never finish.

### Feature Proposal

Provide one more hook like `renderEnd/generationEnd` or call `buildEnd` after bundle generation. I think this is expected for a big amount of plugins. We need hooks before all transformations and after them.

**Comment by lukastaegert** [comment]
The problem that lead to this separation is that for the JavaScript API, there is no way of telling whether the user wants to create another output from a generated bundle or not. The `renderChunk` hook is called during output generation which can theoretically happen infinite times in such a setup.

Thus it is also unclear when you want to remove your worker.

One prominent example that uses is is when a user provides an array of output options via the CLI.

Not sure what would be a good solution here.

**Comment by TrySound** [comment]
I get it. Then I think we need a lifecycle around chunks generation. It should be called before all renderChunk calls and probably before generateBundle. Maybe call it `renderStart()` and `renderEnd(?error)`?

**Comment by tivac** [comment]
:+1: for lifecycles around chunk generationrs.
:+1: for `renderStart`
:+1: for `renderEnd`
:-1: for `renderError`, I want the hook to always be called if the hook exists just like `buildEnd`

**Comment by TrySound** [comment]
@tivac I actually proposed exactly the same api as buildEnd. `?error` is meant to be optional
```
renderStart()
renderEnd(?error)
```

**Comment by tivac** [comment]
😅 this is what I get for reading GH emails on the bus.

Sorry @trysound, I'm fully a 👍🏻 on this proposal!

**Comment by guybedford** [comment]
We do have a renderEnd, and it is called `generateBundle` called at that point in the life cycle.

There is no concept of the render lifecycle ending in this API - in theory you could keep the generated object around as long as you want and call render again as many times as you want.

**Comment by TrySound** [comment]
I would be happy to use it but any error thrown inside renderChunk will prevent worker closing and will prevent process from end.

**Comment by TrySound** [comment]
I need buildEnd(error) like thing.

**Comment by guybedford** [comment]
A `renderError` hook may well be useful for this use case, and should be trivial to add. A PR is welcome.

**Comment by lukastaegert** [comment]
Resolved via #2438
