### ISSUE TITLE
Hashes aren't correctly invalidated when running Rollup in watch mode

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#2435]
- Rollup Version: 0.65
- Operating System (or Browser): Mac OS
- Node Version: 10.9

### How Do We Reproduce?

https://github.com/Rich-Harris/rollup-watch-hash-bug

### Expected Behavior

Changing the content of a file invalidates the hash of the chunk that contains it. It should *also* invalidate the hashes of any chunks that *depend* on that chunk.

### Actual Behavior

It doesn't. The dependants' hashes stay the same, even though their content has changed to reflect the new import.

**Comment by nsivertsen** [comment]
I'm seeing what appears to be the same bug, in a Sapper application. The only difference is that for me this is not limited to watch mode, but also happens with normal builds.

Here's an example. The left box shows the JS assets loaded by the site before making changes to `[slug].html` and also after making the changes, while the browser still has the assets cached. The right bow shows the assets loaded after clearing the cache. Note that the only filename that changes is that of `[slug].html`:

![cache](https://user-images.githubusercontent.com/4019062/48906517-f9ce7e80-ee64-11e8-801c-b8e7209f0cbc.png)

**Comment by nsivertsen** [comment]
I just tested this against master (15e088536f156b2abb551c800e8e3869642acf73) because there were some changes to how chunking is done, but it is unfortunately still a problem.

@Rich-Harris's repro doesn't just apply to watch mode, `dist/main.67c2222f.js` also incorrectly keeps the same hash after changing `foo.js` when Rollup is run with `npm run build`.

**Comment by lukastaegert** [comment]
Ah I see. This issue is that static dependencies are taken into account when calculating hashes while dynamic dependencies are ignored. I might be able to sneak something into the next release as it would be nice to have this working for 1.0.

**Comment by nsivertsen** [comment]
Thank you, that would be fantastic!

**Comment by lukastaegert** [comment]
Fix at #2596, should be part of the next release
