### ISSUE TITLE
watchChange hook event listener re-attaches on every change

### ISSUE THREAD

**Issue by tivac** [rollup/rollup#2440]
- Rollup Version: v0.65.0
- Operating System (or Browser): Windows 10
- Node Version: 8.9.1

### How Do We Reproduce?

1. Download https://gist.github.com/tivac/72e776781aabd6fece83c514edbe5106
2. `npx rollup --config --watch`
3. Change `thing` inside `./index.js` a few times and watch as more and more logging appears

### Expected Behavior

Each plugin `watchChange` hook should get called once per file changed.

### Actual Behavior

Each plugin `watchChange` hook gets called `n` times per file changed, where `n` is the number of times any file has been changed.

```bash
C:\Users\tivac\Desktop\rollup-watchchange>npx rollup -c -w
npx: installed 1 in 1.816s
Path must be a string. Received undefined
C:\Users\tivac\Desktop\rollup-watchchange\node_modules\rollup\bin\rollup
rollup v0.65.0
bundles ./index.js → dist\bundle.js...
created dist\bundle.js in 14ms

[2018-09-04 13:26:32] waiting for changes...
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
rollup v0.65.0
bundles ./index.js → dist\bundle.js...
created dist\bundle.js in 3ms

[2018-09-04 13:26:36] waiting for changes...
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
rollup v0.65.0
bundles ./index.js → dist\bundle.js...
created dist\bundle.js in 3ms

[2018-09-04 13:26:37] waiting for changes...
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
C:\Users\tivac\Desktop\rollup-watchchange\index.js
```

### Notes

https://github.com/rollup/rollup/blob/0d104929409dc458e1ea1387622ae8edfe61f880/src/Graph.ts#L140

Appears to be the issue, maybe it needs a stronger check around figuring out whether or not a new listener should be attached? I don't know the guts of the codebase well enough to be sure.

**Comment by lukastaegert** [comment]
I think the logic is correct but it needs a cleanup. Hope to look into this soon.
