### ISSUE TITLE
Dynamic imports are always emitted 

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#2444]
- Rollup Version: 0.65.1
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

<img width="1583" alt="screenshot 2018-09-05 at 19 36 18" src="https://user-images.githubusercontent.com/127379/45110767-7c3b8200-b143-11e8-9d94-59eadfce4ad9.png">

### Expected Behavior

The emitted JS should be empty

### Actual Behavior

It's not empty

### Note

Probably a duplicate of: https://github.com/rollup/rollup/issues/2284
Sharing REPL is not working to me

**Comment by lukastaegert** [comment]
Yes, this is a known issue. I hope we can fix it in the future, there are some tree-shaking improvements that will need to come first, though.

**Comment by lukastaegert** [comment]
Fix at #2575
