### ISSUE TITLE
Default value in destructured arguments can produce invalid syntax

### ISSUE THREAD

**Issue by jsg2021** [rollup/rollup#2445]
- Rollup Version: rollup v0.65.2
- Operating System (or Browser): na
- Node Version: na

### How Do We Reproduce?

https://rollupjs.org/repl?version=0.65.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGJhciUyMGZyb20lMjAnLiUyRm90aGVyJyUzQiU1Q24lNUNuY29uc3QlMjBFTVBUWSUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwbnVsbCUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwdGVzdCUyMCglN0Jmb28lMjAlM0QlMjBFTVBUWSU3RCklMjAlN0IlNUNuJTVDdGJhcihmb28pJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyb3RoZXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjBFTVBUWSUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwbnVsbCUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwdGVzdCUyMCglN0Jmb28lMjAlM0QlMjBFTVBUWSU3RCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKGZvbyklM0IlNUNuJTdEJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior
no syntax error

**Comment by jsg2021** [comment]
Note the `EMPTY: EMPTY$1`

**Comment by lukastaegert** [comment]
Thanks a lot for bringing this up. Fix is in preparation. Slightly more compact reproduction:

https://rollupjs.org/repl?version=0.65.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGZGVwLmpzJyUzQiU1Q24lNUNuY29uc3QlMjBFTVBUWSUyMCUzRCUyMG51bGwlM0IlNUNuY29uc3QlMjAlN0Jmb28lMjAlM0QlMjBFTVBUWSU3RCUyMCUzRCUyMCU3QiU3RCUzQiU1Q25jb25zb2xlLmxvZyhmb28pJTNCJTVDbiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGVwLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwRU1QVFklMjAlM0QlMjBudWxsJTNCJTVDbmNvbnN0JTIwJTdCZm9vJTIwJTNEJTIwRU1QVFklN0QlMjAlM0QlMjAlN0IlN0QlM0IlNUNuY29uc29sZS5sb2coZm9vKSUzQiU1Q24lNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by lukastaegert** [comment]
Fix at #2446.
