### ISSUE TITLE
CLI: Let —config Handle String Content Instead Of Just Filepaths

### ISSUE THREAD

**Issue by bdkjones** [rollup/rollup#2448]
### Expected Behavior / Situation

For the CLI, I would like the —config option to accept EITHER  a filepath/name (as it does now) OR the actual *content* of that file, as a string. (See justification below.)

### Actual Behavior / Situation

The —config option currently accepts only a filename/path.

### Modification Proposal

I have a GUI application that presents options for Rollup so that users aren’t required to write/maintain their own config file. My app translates the GUI options into a correct configuration for rollup on the fly, just before calling the CLI. I would like to avoid having to write that config file to disk (slow) and, instead, pass it to the CLI as a string.(faster/cleaner). Example:

    -c=“[contents of my config file here]”

I realize this is an edge-case, but the ability would greatly help people integrate rollup into build systems. If I were to submit the enhancement as a pull request, would the team accept it? Are there potential side-effects I’m not aware of?

**Comment by shellscape** [comment]
My vote is for a local workaround. While it seems perfectly valid for your use-case, I can't see this being widely used.

If this is part of an app with an actual GUI or a CLI tool with an interface, I would recommending using a `WriteStream` to a `tmp` location (which will prevent conflicts, and should be cleaned up automatically based on OS-level user-environment settings) and directing Rollup to use an absolute path to the temp file. That would also be useful on your end if say, the options are identical to the last run (could be compared using various hashing algos), a config could be reused, rather than regenerated.

**Comment by bdkjones** [comment]
Yea, I mean, that’s the current approach. But that’s slower because my app first has to write the file, then rollup has to read it. I’d like to skip the unnecessary work, especially for those who aren’t yet on SSDs.

Other popular tools provide this ability, so I wagered rollup wouldn’t mind it either. If it’s rejected, I’ll just fork and use my own implementation of the rollup CLI with the enhancement.

**Comment by shellscape** [comment]
Providing a comprehensive list of other tools that allow that (and maybe PRs where that feature was merged) would help in determining if the scale of use would justify adding and supporting the feature.

**Comment by lukastaegert** [comment]
Adding another angle, from what I see, your tool has the potential of actually replacing the CLI of Rollup. Did you consider using Rollup's pure JavaScript interface directly? This is in fact what Rollup's CLI does. It will be far more powerful but it will require more work on your side. Needless to say, everything can happen in memory.

**Comment by bdkjones** [comment]
@lukastaegert Thanks! I have considered that, but I’ve been in this racket a very long time and experience has taught me that going through the CLI is usually a better, more stable implementation than trying to adopt each tool’s API directly. The latter tends to change frequently, whereas the CLI is kept consistent. Additionally, there’s often edge cases like source maps that are simply much easier to handle by going through the official CLI, which figures out the correct filepaths, etc.

(Much like how Xcode’s build system simply calls command line tools with various arguments, that’s what I do in CodeKit.)

All I REALLY need is a way to use rollup plugins from the CLI. Currently, that mandates the use of a config file, which is why I was interested in this.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
