### ISSUE TITLE
buildEnd doesn't pass error in argument anymore since 0.65

### ISSUE THREAD

**Issue by MikeKovarik** [rollup/rollup#2449]
- Rollup Version:  since 0.65.x
- Operating System (or Browser): Windows 10
- Node Version: 10.9.0

### How Do We Reproduce?

Run a simple plugin with the `buildEnd` on a file causes rollup to throw error.

```js
function myplugin() {
	return {
		name: 'myplugin',
		buildEnd(err) {
			console.log('buildEnd', err)
		}
	}
}
```

Or try using [rollup-plugin-notify](https://github.com/MikeKovarik/rollup-plugin-notify) which is based on `buildEnd`'s `err` argument.

### Expected Behavior

`buildEnd` plugin hook should pass error in argument if error is thrown during bundling. It worked great [since it was introduced](https://github.com/rollup/rollup/issues/1629#issuecomment-396607450) around 0.60. And I built [rollup-plugin-notify](https://github.com/MikeKovarik/rollup-plugin-notify) around it.

### Actual Behavior

But as of 0.65 `buildEnd` doesn't pass the error in the argument anymore. It's always undefined, no matter if bundling succeed or failed. I tested all versions between 0.60 and 0.65 and i can confirm that 0.60, 0.61, 0.62, 0.63, 0.64 works, but 0.65.x doesn't.

![image](https://user-images.githubusercontent.com/3995401/45269065-8339fb80-b487-11e8-9e6f-b8c9d0765561.png)

**Comment by lukastaegert** [comment]
Hi @MikeKovarik,
as it turns out, this was just a simple typing error and is already fixed in current master by @TrySound , please check it out! The next release will contain the fix.

**Comment by lukastaegert** [comment]
Added a specific test via #2450
