### ISSUE TITLE
Invalid optimisation: var-declared parameters become undefined

### ISSUE THREAD

**Issue by robpalme** [rollup/rollup#2451]
- Rollup Version: 0.59.0-onwards (also repro'd in latest 0.65.2)
- Operating System (or Browser): Windows 7, Chrome 68
- Node Version: n/a

### How Do We Reproduce?

The following function optimization is incorrect.

```javascript
// input
function fn (a) {
  var a;
  return a ? 1 : 0;
}
```
compiles to
```javascript
// output
function fn (a) {
  return 0;
}
```

https://rollupjs.org/repl?version=0.65.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm4lMjAoYSklMjAlN0IlNUNuJTIwJTIwdmFyJTIwYSUzQiU1Q24lMjAlMjByZXR1cm4lMjBhJTIwJTNGJTIwMSUyMCUzQSUyMDAlM0IlMjAlMjAlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZm4lM0IlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior

Redeclaration of a parameter as a  `var` should have no effect.

### Actual Behavior

Rollup assumes the `var` is a new binding with a value of `undefined`.
The generated code has semantics that do not match the source code.

**Comment by lukastaegert** [comment]
I usually like a good challenge but this really was a tricky one. Fix at #2456.
