### ISSUE TITLE
Ability to preserve relative paths and / or hook into module file naming

### ISSUE THREAD

**Issue by blakemann** [rollup/rollup#2452]
### Feature Use Case

I have a fairly large project that I am using rollup to bundle modules for. The current plan for architecture involves having various modules with the same names, organized into folders, ie:

    ... /user/manage.js
    ... /pig/manage.js
    ... /sheep/manage.js

Each of these modules will import common util/helper modules into them, so using rollups `experimentalCodeSplitting` option with multiple inputs is the route I'm taking. This results in a flat output directory that looks something like this:

    chunk-ab35cd63.js
    manage.js
    manage2.js
    manage3.js

But this is unfortunately a bit difficult to deal with in the application when it comes to loading those modules. Developers have to remember which number matches up to which location, and when new modules are added, they could potentially cause a number of other modules to be re-numbered.

### Feature Proposal

I think this could be solved in two ways:

#### Option One:

Add a `preserveRelativeDirectories` option to the build process, which could either be set to `true`, `false`, or a base path string. The base path would be the path that the directory structure would be preserved starting from. If `true`, rollup could analyze all inputs and find the highest common path between all modules to use as the base path. Generated chunk files would still live at the top level, as there should be no need for the application to load those files directly.

This would mean that given the following structure:

    ┌ src
    ├─┬ a
    │ └── module.js
    ├─┬ b
    │ └── module.js
    └── util.js

Where `a/module.js` and `b/module.js` are the input modules, and import some functionality from `util.js`, the following output would be generated:

    ┌ bundles
    ├─┬ a
    │ └── module.js
    ├─┬ b
    │ └── module.js
    └── chunk-ab35cd63.js

**Note: this is not the same behaviour as the `experimentalPreserveModules` behaviour.** This proposal still fully leverages the code splitting behaviour as is, it _only_ maintains directories for the bundles themselves, matching it's entry point input file location.

#### Option Two:

This behaviour that I want could potentially be implemented as a plugin instead of being part of core. Unfortunately, I was unable to find a way to hook in where I would need to be able to do this easily.

Therefore, options two is the implementation of a hook for the `generateId` function, which would allow me to add directory paths to the file name. At the moment, all of the hooks utilize promises to account for async functionality. Adding an asynchronous hook to this part of the code seems like it would add an unnecessary amount of complexity to the code that calls it, so I wonder if perhaps this is a good use case for adding a type of hook that is synchronously called, and simply returns a result rather than a promise. This seems like it would then make the process of hooking into the `generateId` function fairly straightforward, and from there implementing my desired behaviour should be simple.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by lukastaegert** [comment]
Though as elegantly, the object form of input lets you specify different paths for your chunks.
