### ISSUE TITLE
Aliased Imports as Named Parameter Defaults Cause Invalid Syntax

### ISSUE THREAD

**Issue by rockerest** [rollup/rollup#2453]
- Rollup Version: `>= 0.65.0 <= 0.65.2` (Introduced `0.65.0`)
- Operating System (or Browser): Windows 10, Firefox 62.0
- Node Version: 10.5.0

### How Do We Reproduce?

Import a named export as an alias (e.g. `{ thing as myThing }`) and then use it as the default value for a "named parameter" (i.e., an object parameter):
```
import { thing as myThing } from "./thingProvider.js";

function thingUser( { someKey = myThing } = {} ){
    // use someKey
}
```

Alternatively, see the repo [here](https://gitlab.com/repro-repos/aliased-import-as-named-param-default).

### Expected Behavior

The resulting output should not have invalid syntax.

### Actual Behavior

The resulting output contains object syntax like so: `{ a = b: c }`

**Comment by rockerest** [comment]
Sorry, didn't find the [prior report](https://github.com/rollup/rollup/issues/2445) when I searched for `alias` in the issues, as this bug is *specific* to aliased imports in my layman's opinion (note the `safe`/`safeStuff` on [these lines](https://github.com/rollup/rollup/issues/2445) which does not cause this bug).

I think this is the same, but it's manifesting slightly differently for me, so I'll leave it up to maintainers to close.

**Comment by lukastaegert** [comment]
Thanks! 

> It's strange (to me) that mine is only presenting when the import is aliased!
My guess is that the aliasing is causing a name clash with a variable in another module which is necessary for this bug to trigger.
