### ISSUE TITLE
`banner` is inserted before `rollup-plugin-uglify`?

### ISSUE THREAD

**Issue by gnirob** [rollup/rollup#2459]
Sorry for choosing the bug template, but I don't know if this is a bug or on purpose.

- Rollup Version: 0.65.2
- Operating System (or Browser): macOS 10.13.6
- Node Version: 10.10.0

### How Do We Reproduce?

`rollup.config.js`:

```js
import {uglify} from 'rollup-plugin-uglify';

export default {
  ...someOptions,
  output: {
    banner: '/*! Something */'
  },
  plugins: [
    ...somePlugins,
    uglify()
  ]
};
```

Then check the output file, no banner shows up.

### Expected Behavior

Banner is inserted after all procedures are done.

### Actual Behavior

Banner is cleared by `rollup-plugin-uglify`.

**Comment by feonit** [comment]
+1

**Comment by shellscape** [comment]
@feonit checkout [Github Reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) as an alternative to posting a "+1" reply.

**Comment by yingye** [comment]
Recommended [rollup-plugin-banner](https://www.npmjs.com/package/rollup-plugin-banner) to append content before js bundle.

**Comment by boringwong** [comment]
@yingye Good fresh project, you did what I wanted to do.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
