### ISSUE TITLE
Docs link is invalid (en)

### ISSUE THREAD

**Issue by transitive-bullshit** [rollup/rollup#2467]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The main `rollup` `en` docs link to the "big list of options" in this [section](https://rollupjs.org/guide/en#configuration-files), but this link is broken. It should link to a relative hash, but it instead links to `https://rollupjs.org/#big-list-of-options` which is missing the `/guide/en` url path.

### Your Proposal for Changes

Should be a quick one-line doc fix.

**Comment by lukastaegert** [comment]
Fixed via rollup/rollupjs.org#154 thanks to @mgred !
