### ISSUE TITLE
Build error : Could not load ... ENOENT: no such file or directory, open ...

### ISSUE THREAD

**Issue by RSamaium** [rollup/rollup#2468]
- Rollup Version: 0.66.1
- Operating System (or Browser): Linux
- Node Version: > 9

### How Do We Reproduce?

[Test it in Repl.it](https://repl.it/@RSamaium/RollupBug)

### Expected Behavior

All the modules having the term "newbot" are integrated in the final file but not for the other modules

### Actual Behavior

"botbuilder" is a sub-module of the "newbot-formats" module
* The first build, it works but I have a warning
`'botbuilder' is imported by node_modules/newbot-formats/src/formats/carousel.js, but could not be resolved – treating it as an external dependency`
* If we modify the test.js file, I have an error and the build is not done
`Error: Could not load botbuilder (imported by /home/runner/node_modules/newbot-formats/src/formats/quick-replies.js): ENOENT: no such file or directory, open 'botbuilder'
    at /home/runner/node_modules/rollup/dist/rollup.js:21721:19
    at <anonymous>`

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
