### ISSUE TITLE
 Variables declaration is removed after rebuilding module

### ISSUE THREAD

**Issue by harimambura** [rollup/rollup#2469]
- Rollup Version: 0.66.2
- Operating System (or Browser): Windows
- Node Version: 8.9.1

### How Do We Reproduce?
After running the rollup watch first build is ok (has valid and runnable code), but after changing the source file (add space or new line at example) and rebuilding bundle by watcher some of variable declarations is removed and bundle code is broken. I made the example to reproduce bug. Take a look at declaration of 'createVNode' and 'createTextVNode' variables.

here the repository with example https://github.com/harimambura/inferno_bug

### Expected Behavior
Declaration of variables should be exist after rebuilding sources

### Actual Behavior
Declaration of variables is removed after rebuilding sources

**Comment by bouzlibop** [comment]
@harimambura can this issue be closed? Wasn't it resolved [here](https://github.com/infernojs/babel-plugin-inferno/issues/52)?

**Comment by harimambura** [comment]
> @harimambura can this issue be closed? Wasn't it resolved [here](https://github.com/infernojs/babel-plugin-inferno/issues/52)?

Yes, it is. thanks
