### ISSUE TITLE
Valid JSON not recognized

### ISSUE THREAD

**Issue by johndeighan** [rollup/rollup#2472]
- Rollup Version:
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

First off - your "Head to" link above does not work. gitter tells me that it's not found!!!

Using rollup 0.66.1. Here is the error message I get - it at least looks like perfectly valid JSON is being rejected - unexpected token. What am I supposed to do with that? I'll try to create a small example, but in any case, the error message just sounds like your JSON parser is totally messed up. If now, your error messgae is messed up:

C:\wwwroot\speech-to-text [master +9 ~0 -0 !]> node_modules/.bin/rollup -c

src/speech-to-text.js → public/speech-to-text.js...
[!] Error: Unexpected token
node_modules\websocket\package.json (2:9)
1: {
2:   "_from": "websocket@^1.0.26",
            ^
3:   "_id": "websocket@1.0.28",
4:   "_inBundle": false,
Error: Unexpected token
    at error (C:\wwwroot\speech-to-text\node_modules\rollup\dist\rollup.js:3461:30)
    at Module.error (C:\wwwroot\speech-to-text\node_modules\rollup\dist\rollup.js:13358:9)
    at tryParse (C:\wwwroot\speech-to-text\node_modules\rollup\dist\rollup.js:13016:16)
    at Module.setSource (C:\wwwroot\speech-to-text\node_modules\rollup\dist\rollup.js:13089:33)
    at C:\wwwroot\speech-to-text\node_modules\rollup\dist\rollup.js:21758:20
    at <anonymous>

I have taken the time to uninstall and reinstall rolllup. I've done the same with a library that my code uses - watson-speech. I've also examined websocket's package.json looking for strange, unprintable characters - there are none.

### Expected Behavior

No errors

### Actual Behavior

Errors

**Comment by tivac** [comment]
Use `rollup-plugin-json` if you need to import json files, rollup only loads js by default.

**Comment by johndeighan** [comment]
Except that *I* don't need to import json files, but it looks like rollup-plugin-node-resolve (or rollup-plugin-commonjs) does. So, if rollup-plugin-json is required, it should be a dependency of modules that require it. However, I realize that rollup-plugin-json may need to be included in rollup.config.js, so I'm working that angle now. No success yet.

**Comment by shellscape** [comment]
Thanks for the heads up about the gitter links. I looked into it but was unable to get any error messages, looks like they do work, so it's possible you ran into a temporary glitch on their end.

**Comment by lukastaegert** [comment]
To my knowledge, there are three plugins necessary for full node compatibility:
* rollup-plugin-node-resolve
* rollup-plugin-commonnjs
* rollup-plugin-json

In the latest version of Rollup, the parse error caused by JSON files should have a little more information now.

About the `this` issue: It seems that in CommonJS files, `this` is equivalent to `exports` (at least that is what my experiments showed). If this is not your own code (i.e. you cannot fix it) and it causes actual issues, I fear the best thing you can do is raise an issue with `rollup-plugin-commonjs`. There *is*  an option to set the context to something other than `undefined`: https://rollupjs.org/guide/en#context-context

However this will probably not work for `exports` as this is transpiled away by `rollup-plugin-commonjs`.

**Comment by beauremus** [comment]
I believe I'm having a similar issue. I have a dependency that has a dependency on WebSocket. Initially, I saw @johndeighan error and found several suggestions that I should include rollup-plugin-json. I added this, and now I get an error

`[!] Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
node_modules/websocket/build/Release/bufferutil.node (1:0)
1: ����`

So it's trying to read a binary file.

Can I get help understanding why this doesn't work? I'm struggling to find the right words to Google.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
