### ISSUE TITLE
Rollup incorrectly eliminates conditions on object properties set through 'this'

### ISSUE THREAD

**Issue by ashmind** [rollup/rollup#2473]
- Rollup Version: 0.66.2
- Operating System (or Browser): Reproducible in Repl on Chrome 69 Win
- Node Version: N/A (Repl)

### How Do We Reproduce?

https://rollupjs.org/repl?version=0.66.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwbyUyMCUzRCUyMCU3QiU1Q24lNUN0aGlkZSgpJTIwJTdCJTIwdGhpcy5hY3RpdmUlMjAlM0QlMjBmYWxzZSUzQiUyMCU3RCUyQyU1Q3QlNUNuJTVDdHNob3coKSUyMCU3QiUyMHRoaXMuYWN0aXZlJTIwJTNEJTIwdHJ1ZSUzQiUyMCU3RCU1Q24lN0QlM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc2hvdygpJTIwJTdCJTIwby5zaG93KCklM0IlMjAlN0QlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBoaWRlSWZBY3RpdmUoKSUyMCU3QiU1Q24lNUN0aWYlMjAoby5hY3RpdmUpJTVDbiU1Q3QlNUN0by5oaWRlKCklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior
Logic in `hideIfActive` is preserved, as there are valid situations where `o.active` would be `true`.  
E.g: if `show()` is called first.

### Actual Behavior
`hideIfActive` is emptied, which breaks the logic (now you can't hide `o` when it's active).

**Comment by kzc** [comment]
Related issue: #2345

Tree shaking can be disabled as a workaround or use one of the patches in link above.

**Comment by shellscape** [comment]
This is still a valid bug in the latest version of the Rollup REPL.
