### ISSUE TITLE
Code treeshaken when method on string literal is called

### ISSUE THREAD

**Issue by miralemd** [rollup/rollup#2475]
- Rollup Version: 0.66.2
- Operating System (or Browser): Chrome
- Node Version: 10.10.0

### How Do We Reproduce?

[REPL](https://rollupjs.org/repl?version=0.66.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHZhciUyMGRhdGElMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTIwJTIwJTIwJTIwdmFyJTIwcCUyMCUzRCUyMCU1QyUyMmFiYyU1QyUyMi50cmltKCklM0IlNUNuJTVDbiUyMCUyMCUyMCUyMHAucmVwbGFjZSgnYiclMkMlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGRhdGEucHVzaCgncmVwbGFjZWQnKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBkYXRhJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

### Expected Behavior

Running the following snippet through rollup:

```js
export default function () {
    var data = [];
    var p = "abc".trim();

    p.replace('b', function () {
      data.push('replaced');
    });

    return data;
}
```

should not remove anything since there is no dead code.

### Actual Behavior

Rollup removes the call `p.replace` and produces the following output:

```js
function main () {
    var data = [];

    return data;
}
export default main;
```

The culprit for some reason is the method call on `"abc"` (seems like any string method will cause the issue).

It works fine when `var p = "abc"` or `String("abc").trim()` or when reassigning `p = p.replace(...`.

I just can't figure out why the code is removed when a method is called on the string literal?

**Comment by lukastaegert** [comment]
Hi @miralemd,

thanks for finding this issue. Fix at #2476.

To give a little background about what happened, and why the call to `.trim` triggered the issue: When calling a method on a literal like `trim` or `replace`, there is a logic present in the internal representation of literals to detect whether this call has side-effects that *will* detect side-effects in the argument of a `String.prototype.replace`.

Now if the string itself is the return value of another prototype method call such as `trim`, the same logic should apply. However, as this string no longer has a representation in your code, the logic needs to be wired up in a different place (internally, this is now a "virtual" string literal). And in fact, this wiring up was faulty.
