### ISSUE TITLE
Rollup package axios, can not be used

### ISSUE THREAD

**Issue by BlackHole1** [rollup/rollup#2477]
- Rollup Version: 0.65.2
- Operating System (or Browser): chrome 69.0.3497.100
- Node Version:v8.5.0

### How Do We Reproduce?
I created a demo that will be available for you to view: https://github.com/BlackHole1/rollup-axios-error-demo

### Expected Behavior
return axios object in nodejs

### Actual Behavior
error: `ReferenceError: XMLHttpRequest is not defined`

The code for axios source code to distinguish the running environment is:

![](https://camo.githubusercontent.com/828492b53f04d5aa065fd529b130ca02f310c278/687474703a2f2f6f6e377230747167752e626b742e636c6f7564646e2e636f6d2f466d694355474b71712d476c78613058477474673379645a627638692e706e67)

But after packaging, it becomes:

![](https://camo.githubusercontent.com/36b33f1395df9a80a245e2a2b02a36bef695bd3c/687474703a2f2f6f6e377230747167752e626b742e636c6f7564646e2e636f6d2f466e65377143527753454b71455837517942744f4879465f765336332e706e67)

Caused the XMLHttpRequest to be instantiated on the nodejs side

**Comment by RikkiGibson** [comment]
You need to produce a different physical bundle for nodejs to get the http adapter included instead of the xhr bundle. This is a better practice anyway because when you finally ship to a particular environment you don't want to ship an adapter that will never be used.

See the "browser" field for axios: https://github.com/axios/axios/blob/master/package.json#L72

**Comment by BlackHole1** [comment]
Thank you very much for your advice. I wrote a http request code compatible with browser and nodejs.Use require to introduce http and http. To solve the problem of packaging failure

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
