### ISSUE TITLE
JSDoc bug on `export default` for 'cjs'

### ISSUE THREAD

**Issue by mesqueeb** [rollup/rollup#2478]
- Rollup Version: latest
- Operating System (or Browser): macOS
- Node Version: v10.10.0

### How Do We Reproduce?

Say I have a simple JS helper function:
```JavaScript
/**
 * Explanation
 *
 * @param {string} str Explanation
 */
export default function (str) {
  // ...
}
```
Then, when I compile a file with Rollup like so
`output: {format: 'es'}`

and I do `import myFn from './compiled.es.js'`
JSDoc explanation will be shown in VSCode.

### Expected Behavior

JSDoc explanation should be shown in VSCode on commonJS format as well.

### Actual Behavior

When I do
`output: {format: 'cjs'}`

and I do `import myFn from './compiled.cjs.js'`
JSDoc explanation is not shown anymore at all for the file in VSCode.

**Comment by bouzlibop** [comment]
IMO It's not Rollup issue. After transpilation the function you mentioned looks exactly the same both in `cjs` and in `es` and JSDoc comment is preserved aswell.

BTW I'm using VSCode Version 1.27.2 (1.27.2) and the docs is shown properly.

<img width="753" alt="screen shot 2018-09-28 at 11 43 34" src="https://user-images.githubusercontent.com/8625570/46201219-d5966b80-c313-11e8-8b4f-cd6fdbf019cb.png">

<img width="751" alt="screen shot 2018-09-28 at 11 43 42" src="https://user-images.githubusercontent.com/8625570/46201240-d9c28900-c313-11e8-8729-23a8f6778c1c.png">

**Comment by mesqueeb** [comment]
@bouzlibop I also reported [over at JSDoc here](https://github.com/jsdoc3/jsdoc/issues/1573). Including a GIF showing the info not popping up. 🤣 

I'm also at VSCode `1.27.2`

Could you show your `compiled.cjs.js` ? Maybe I can learn something.

**Comment by mesqueeb** [comment]
@bouzlibop yeah you are doing `module.exports = main;` while my Rollup compiles to `exports.default = `

So weird that our Rollups have different results......

**Comment by mesqueeb** [comment]
@bouzlibop I have finally found my mistake.

My Rollup config had 
```
{
  // ...
  output: {
    // ...
    exports: 'named',
  }
}
```
Removing `exports: 'named'` fixed my problem.
