### ISSUE TITLE
Collecting named imports before the final bundle

### ISSUE THREAD

**Issue by diervo** [rollup/rollup#2482]
### Feature Use Case

We have a pipeline with several plugins that do all sort of javascript transformation (some of those add an `import statement` as part of the transform. Af the end of all those, when we have the bundle, we would want to collect the list of imports with all its named specifiers. 

For example if the final bundle has `import { x, y } from "foo"`, we would like to have an API that collected that the fact that you have a dependency on foo for the named imports for us.

Today rollup only exposed the imports that are used but not the imported names. We need all this to provide metadata for another system.

### Feature Proposal

Expose as part of the bundle API (or the api for some of the hooks like `renderChunk`, the metadata not only about the import modules for the named imports as well.

We know we could accomplish this by doing a manual AST traversal for acorn, but since rollup has already visited all of this Nodes, we could trivial expose this information.

### Work

My team and I will be happy to do the works if you guys agree that this is an interesting addition of metadata for rollup in general.

**Comment by guybedford** [comment]
@diervo did you have a look at the 1.0 branch here? This provides some metadata around the export names used and treeshaking, although this is also done at the level of the chunks if I recall correctly.

Perhaps take a look at the data provided there in the ouput object, and see how you might need that changed for your purposes?

**Comment by guybedford** [comment]
See for example the type of this object at https://github.com/rollup/rollup/blob/1.0/src/rollup/types.d.ts#L318.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
