### ISSUE TITLE
Imports are incorrectly reordered

### ISSUE THREAD

**Issue by bdwain** [rollup/rollup#2490]
- Rollup Version: 0.66.2 (but this seems to have been introduced in 0.55)
- Operating System (or Browser): OS X High Sierra
- Node Version: 9.11.1

### How Do We Reproduce?
[repl reproduction](https://rollupjs.org/repl?version=0.66.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCdmb28lMkZmaXJzdC5jc3MnJTNCJTIwJTJGJTJGdGhpcyUyMGNzcyUyMG5lZWRzJTIwdG8lMjBiZSUyMGZpcnN0JTIwZm9yJTIwc3BlY2lmaWNpdHklMjByZWFzb25zJTVDbiU1Q25pbXBvcnQlMjBibGFoJTIwZnJvbSUyMCcuJTJGYmxhaCclM0IlNUNuYmxhaCgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJsYWguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJ2JsYWglMkZzZWNvbmQuY3NzJyUzQiUyMCUyRiUyRmJ1dCUyMHRoaXMlMjBlbmRzJTIwdXAlMjBmaXJzdCU1Q24lMjAlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKCklN0IlN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior
The original import order should be maintained

### Actual Behavior
The imports that pull in content from other files get pushed to the top, above imports that are not resolved (because they are external packages)

**Comment by jamiewinder** [comment]
[Fixed link](https://rollupjs.org/repl?version=0.66.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCdmb28lMkZmaXJzdC5jc3MnJTNCJTIwJTJGJTJGdGhpcyUyMGNzcyUyMG5lZWRzJTIwdG8lMjBiZSUyMGZpcnN0JTIwZm9yJTIwc3BlY2lmaWNpdHklMjByZWFzb25zJTVDbiU1Q25pbXBvcnQlMjBibGFoJTIwZnJvbSUyMCcuJTJGYmxhaCclM0IlNUNuYmxhaCgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJsYWguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJ2JsYWglMkZzZWNvbmQuY3NzJyUzQiUyMCUyRiUyRmJ1dCUyMHRoaXMlMjBlbmRzJTIwdXAlMjBmaXJzdCU1Q24lMjAlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKCklN0IlN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

**Comment by bdwain** [comment]
oops thanks @jamiewinder . fixed in the original

**Comment by bdwain** [comment]
I was able to work around this temporarily by moving the imports that need to be first to a separate file

[repl](https://rollupjs.org/repl?version=0.66.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGZmlyc3QtaW1wb3J0cyclNUNuJTVDbmltcG9ydCUyMGJsYWglMjBmcm9tJTIwJy4lMkZibGFoJyUzQiU1Q25ibGFoKCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmxhaC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAnYmxhaCUyRnNlY29uZC5jc3MnJTNCJTIwJTJGJTJGYnV0JTIwdGhpcyUyMGVuZHMlMjB1cCUyMGZpcnN0JTVDbiUyMCU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAoKSU3QiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmaXJzdC1pbXBvcnRzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCdmb28lMkZmaXJzdC5jc3MnJTNCJTIwJTJGJTJGdGhpcyUyMGNzcyUyMG5lZWRzJTIwdG8lMjBiZSUyMGZpcnN0JTIwZm9yJTIwc3BlY2lmaWNpdHklMjByZWFzb25zJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by lukastaegert** [comment]
Ok, this issue was a really enlightening one. Previously, the only guarantees our bundling had were:
* Modules inside a bundle/chunk have the correct execution order
* An internal or external import is executed before the importing module

There was, however, *no guarantee* that external imports were executed in a particular order between themselves. I created a PR that solves your problem and many similar problems at the same time while improving execution order, please check it out: #2508

**Comment by bdwain** [comment]
Awesome! Thank you!
