### ISSUE TITLE
external can be altered

### ISSUE THREAD

**Issue by futurist** [rollup/rollup#2491]
### Feature Use Case

When adding `external` option to bundle `commonjs` `require`s, it's not enough just pass into an array.

The use case like below line:
https://github.com/paldepind/flyd/blob/6487d11052f60a6e50ece52df4a69c558ce78690/lib/index.js#L3

I want to generate an ES bundle, but alter the external `ramda/src/curryN`(commonjs style) into `ramda/es/curryN` as external, there's no way to do.

### Feature Proposal

Pass object item into `external` array, to control which external can be altered for which target, like

[webpack externals](https://github.com/webpack/webpack/tree/master/examples/externals), this can be an object to control the details.

**Comment by futurist** [comment]
When consider this feature, is it make sense to let external can be relative path? The use case like below:

I want to make an ES version from CJS source as below file:

https://github.com/paldepind/flyd/blob/master/module/every/index.js

```js
var flyd = require('../../lib');

module.exports = function(dur) {
  var s = flyd.stream();
  var target = Date.now();
  function timer() {
    if (s.end()) return;
    var now = Date.now();
    target += dur;
    s(now);
    setTimeout(timer, target - now);
  }
  timer();
  return s;
};
```

This CJS file contains `../../lib` which can be treated as an external?

The resulting ES output should like below:

```js
import flyd from '../../es';

export default function(dur) {
  var s = flyd.stream();
  var target = Date.now();
  function timer() {
    if (s.end()) return;
    var now = Date.now();
    target += dur;
    s(now);
    setTimeout(timer, target - now);
  }
  timer();
  return s;
};
```

That is, don't resolve `../../lib` if it's in the `external` list. The `../../lib` -> `../../es` transform can be done using any replacement.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
