### ISSUE TITLE
Github Milestones abandoned / out of date

### ISSUE THREAD

**Issue by David-Else** [rollup/rollup#2492]
Documentation Is:

- [x] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
Your github milestones are badly out of date: https://github.com/rollup/rollup/milestones

They make a very negative impression on a new user who wants to see the state of things.

### Your Proposal for Changes

just delete them, or keep them up-to-date.

**Comment by shellscape** [comment]
@David-Else can you explain further how you believe they are out of date? It looks to me like two milestones were completed at 100% and one is still pending work.

**Comment by David-Else** [comment]
I seem to remember they used to be updated often and have new versions added, now they have not been touched for 3 months.

0.63.0 and 0.63.2 are irreverent as they are complete, and we are now on v0.66.4 and there has been no milestones for any version since 0.63.2.

I looked inside 1.0.0 and found people are still commenting on the threads. Maybe it is just done in a way I am not expecting, but it does _look for the outside_ like no progress is being made towards the long awaited version 1 and the milestones are no longer being used as a way to communicate progress.

**Comment by shellscape** [comment]
I suppose I could see how that might appear as you describe, but I would go so far as to say only to highly critical individuals. You can also track progress on various projects (including v1.0.0) on the projects board https://github.com/rollup/rollup/projects/1 (project boards are far superior to milestones for a number of reasons). 

I've closed the two 0.6x.0 milestones to clean them up. The team working on the 1.0.0 release is still making a lot of good progress, and there are many ways to see that (following users, following the org, commit activity in this repo, the project board etc).

While the 1.0.0 milestone could probably use a refresher, I believe the information shared here satisfies the questions you had raised, and provides folks with a few options for looking into progress other than the milestones. I'm going to close this for now, but please feel free to follow up on this issue afterwards.

**Comment by David-Else** [comment]
Thanks @shellscape, I did not intend to be overly critical, I am just a bit OCD about these kind of things. Glad you have closer the 0.6x.0 milestones, much better... can't you feel the weight lifted? :) 

The projects board is much nicer, thanks for pointing it out.
