### ISSUE TITLE
More control over code splitting to specify a shared bundle

### ISSUE THREAD

**Issue by pitAlex** [rollup/rollup#2493]
Hello,

The feature I am requesting involves creating a shared bundle or chunk which you can then use in other builds and specify  that all code that is in this chunk should be excluded and left to be imported from it. To make better sense thing of it like this:
You have a site  and in its pages there are some components that are shared. Lets take header and footer as being the same everywhere. 

Since I worked with SystemJS, in this situation I will first create a single bundle by doing 
``header-module + footer-module`` with output ``example-shared-module`` in the build settings.
 Then whenever I am bundling together scripts of a page I will specify that bundle as things to be excluded. Things to be considered external, ex : ``page-entry-module - example-shared-module``.
This will leave something like ``SystemJS.register("page-entry-module", ["header-module", "footer-module"]`` and all I have to specify in config is ``bundles : { "example-shared-module" : ["header-module", "footer-module"] }  ``

Another example is to think of a "common" bundle in which there a modules used across the pages. What I found is that rollup's code splitting feature will split on its own and end up with putting a hole module in a single file instead of letting me specify that shared-module-a and shared-module-b should go into common-chunk-a.

I hope I am making sense and please excuse my bad english. My goal is to be able to have full control on how to organize my code, deciding what goes together and what goes separate to optimize loading. Because loading things in a single script is not always the best approach and I love the fact that rollup is trying to get away from that.

**Comment by guybedford** [comment]
Do you try using ‘manualChunks’ here?

**Comment by pitAlex** [comment]
When I try manualChunks, like in the following scenario, I get undesired results: 
We have modA.js, modB.js, modC.js and modD.js.
modA has things  all the rest use plus additional things only for it, while modD is shared between modB and modC. Using manualChunks I do: 
```
{
  input : ["modA.js", "modB.js", "modC.js"],
....
  manualChunks : {
    "shared" : ["modA.js","modD.js"]
  }
}
```
Result will be:  modA.js, modB.js, modC,js, shared.js and modD.js. I expected modA and modD to be both included into shared, however thats not the case. In shared.js what I have are modules that are used between all of them like lets say a "vendor" module.

**Comment by guybedford** [comment]
I think you'll probably find that the content of modA and modD is in the shared chunk and being used from there, but that alias wrapper modules are being created for the inputs.

The reason for this is that we will always guarantee that `import('modA')` exposes only the right export names for modA, so it is simply a wrapper module.

That said, modD shouldn't be output as its own module in the above as it is not at all exposed. So that could be a bug if you are getting an explicit `modD.js` with the above config, and there is no dynamic import to `modD`.

**Comment by pitAlex** [comment]
Well, actually moD.js is being outputted separately...for some reason. 

But there is now an example where not having control of creating shared modules in a more independent way hurts production. I have 10 pages right now that share a section. All are angular and this section is its own module. And I have to run build commands for each page anytime I am making changes to this section as I update it to new requirements or fix bugs. With systemjs builder, I could have excluded this module from the build commands of all the pages and then bundle it separately while excluding global scripts, like the angular library. This is something that I have not seen even webpack take into consideration and this is where I would like rollup to take the upper hand and provide a way to compile shared scripts that export all those shared methods so that we can point that bundle in a build command of a module that depends on those methods to reference them as external and just point the bundle as being a dependency, ex:
SystemJS.import(['sharedbundle.js'..... 
would be at the top. 

You can even make it a requirement that for this to work the code needs to stay es6 because we can use other stuff at the end to just make it es5 and transform those imports into amd or systemjs or cjs....

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
