### ISSUE TITLE
cache option causes incremental memory usage

### ISSUE THREAD

**Issue by edoardocavazza** [rollup/rollup#2494]
I think I found out a memory leak using the `cache` option. For some reason, the usage of the `inputOptions` variable in the `write` callback of the bundle result prevents the GC to correctly delete `inputOptions` from the memory. That's not a big problem, until you pass a previous bundle result through the `cache` option 😅, which causes a chain of previous bundles in the memory. I tried to manually `delete inputOptions.cache` after https://github.com/rollup/rollup/blob/master/src/rollup/index.ts#L169 and it seems to work, but I don't know if it is a proper solution. Anyway, I think that it could be a good temporary fix 😄

---

- Rollup Version: v0.66.4
- Operating System (or Browser): OSX
- Node Version: v10.9.0

### How Do We Reproduce?

Run Rollup in watch mode or using incremental build with the `cache` option.

### Expected Behavior
Memory usage should be more or less stable after an incremental build.

### Actual Behavior
Memory usage grows after an incremental build.

**Comment by lukastaegert** [comment]
Ok, I tried for some time to get the leak test https://github.com/rollup/rollup/blob/master/test/leak/index.js to turn red without your fix but I did not manage to. As you already did some digging, maybe you have some ideas? The test is pretty straightforward in that it attaches a callback to the generated bundle that is called once the garbage collector removes it. I tried also tracking the cache object (after adding another run), and it is collected as well.

I have no issue with completely reworking this test as long as it is red without your fix and green afterwards as it would be a pity to break this again in the future. As you observed the memory leak, maybe you know what is missing here?

**Comment by edoardocavazza** [comment]
Hi @lukastaegert, thanks for looking at that and for your work on rollup!

I see that [here](https://github.com/rollup/rollup/blob/master/test/leak/index.js#L21) you are using `bundle.cache` for the cache option, while I was using the `bundle` object (in fact, the test fails if changed).

I am using rollup from the early stages, and I think my mind "cached" this [wiki page](https://github.com/rollup/rollup/wiki/JavaScript-API/d627829e466704a5b8f750812a925d7c6e2bf8e0) when cache was introduced 😅.
Also, IMHO the documentation in the rollup website is misleading:

> **cache**
>
> `Object` A previously-generated bundle. Use it to speed up subsequent builds — Rollup will only reanalyse the modules that have changed.

Anyway, the incremental builds actually works using the bundle object 😄, maybe it's better to support only one of the options and throw if the whole bundle has been passed?

**Comment by edoardocavazza** [comment]
Further more, also passing `bundle.cache` to the cache option, unless the bundle is collected, rollup keeps in memory almost two bundle results (the current one and the cache) so I still think that could be a good improvement to remove the cache reference after the usage

**Comment by lukastaegert** [comment]
Good point! This should definitely be changed. Will try to throw an error if the previous bundle is used for caching it seems it does not work anyway (at least that's what the code looks like) and you will still get a memory leak if you do that.

As for this PR, maybe a short comment above this line stating that this helps to free up memory early would be good.

**Comment by edoardocavazza** [comment]
Added the comment! Thanks @lukastaegert
