### ISSUE TITLE
Tree-shaking is not working

### ISSUE THREAD

**Issue by Nandiin** [rollup/rollup#2497]
- Rollup Version: Rollup online REPL
- Operating System (or Browser): Rollup online REPL
- Node Version: Rollup online REPL

### How Do We Reproduce?

[reproductions in REPL](https://rollupjs.org/repl?version=0.66.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMEZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRmZvb0FuZEJhci5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vQW5kQmFyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm9vKGFyZyklMjAlN0IlNUNuJTVDdHJldHVybiUyMGFyZy5vcHRpb25zJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBGb28lMjAlM0QlMjBmb28oJTdCJTdEKSU1Q24lNUNuZnVuY3Rpb24lMjBiYXIoYXJnKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwYXJnLm9wdGlvbnMlNUNuJTdEJTVDbiU1Q25jb25zdCUyMEJhciUyMCUzRCUyMGJhciglN0IlN0QpJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBGb28lMkMlMjBCYXIlMjAlN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior

`Bar`-related code should be tree-shaken since it is not used and obviously has no side effects.

- I'm aware that in some situation, if the "unused" code seems impure(has side effects) to the rollup, rollup would treat it [conservatively](https://rollupjs.org/guide/en#tree-shaking-doesn-t-seem-to-be-working). But I cannot tell why the code in the reproduction REPL is treated as having a side effect.
- It's true that `foo` and `bar` functions are identical, if anyone concerns.
- I noticed this problem when I was using `rollup-plugin-vue`. It transpiles `.vue` files into independent render functions. Thn importing part of that bundle in another rollup project does not tree-shake the redundant render functions. I traced the problematic code and reproduced it in the REPL.

### Actual Behavior

`Bar`-related code still remains in the bundled output.

**Comment by lukastaegert** [comment]
To answer your question: The problem is the property access in

    function bar(arg) {
      return arg.options
    }

Rollup does not (yet) trace function argument values through function calls. In other words, when checking if calling `bar` has side-effects, it assumes that `arg` is an unknown value, e.g. `undefined`. For an undefined value, accessing a property would be the side-effect of throwing an exception.

There are plans to improve this but it will probably take some time.

So if I understand you correctly, this is a critical piece in tree-shaking Vue.js? This is good to know as this would of course put a little more priority on this.

**Comment by lukastaegert** [comment]
I see. The "typeof" may be tricky to track as well as Rollup's internal logic currently only works for primitive values: https://rollupjs.org/repl?version=0.66.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmlmJTIwKHR5cGVvZiUyMDElMjAlM0QlM0QlM0QlMjAnbnVtYmVyJyklMjBjb25zb2xlLmxvZygxKSUzQiU1Q25pZiUyMCh0eXBlb2YlMjAxJTIwISUzRCUzRCUyMCdudW1iZXInKSUyMGNvbnNvbGUubG9nKDIpJTNCJTVDbiU1Q25pZiUyMCh0eXBlb2YlMjAoZnVuY3Rpb24oKSU3QiU3RCklMjAlM0QlM0QlM0QlMjAnZnVuY3Rpb24nKSUyMGNvbnNvbGUubG9nKDMpJTNCJTVDbmlmJTIwKHR5cGVvZiUyMChmdW5jdGlvbigpJTdCJTdEKSUyMCElM0QlM0QlMjAnZnVuY3Rpb24nKSUyMGNvbnNvbGUubG9nKDQpJTNCJTVDbmlmJTIwKHR5cGVvZiUyMCgoKSUzRCUzRSU3QiU3RCklMjAlM0QlM0QlM0QlMjAnZnVuY3Rpb24nKSUyMGNvbnNvbGUubG9nKDUpJTNCJTVDbmlmJTIwKHR5cGVvZiUyMCgoKSUzRCUzRSU3QiU3RCklMjAhJTNEJTNEJTIwJ2Z1bmN0aW9uJyklMjBjb25zb2xlLmxvZyg2KSUzQiU1Q25pZiUyMCh0eXBlb2YlMjAlN0IlN0QlMjAlM0QlM0QlM0QlMjAnb2JqZWN0JyklMjBjb25zb2xlLmxvZyg3KSUzQiU1Q25pZiUyMCh0eXBlb2YlMjAlN0IlN0QlMjAhJTNEJTNEJTIwJ29iamVjdCcpJTIwY29uc29sZS5sb2coOCklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by Nandiin** [comment]
I didn't catch the idea why tracking "typeof" matters in this case. No matter how the ternary operator evaluates, the result of the expression would only be relevant to the argument `script`, and we can statically determine that:
- the return value of calling `__vue_normalize__` has not been used
- `__vue_normalize__` may cause a side effect through its `script` argument. However, in the unused `__vue_normalize__` function call, the `script` argument passed to it is still a local variable and we know it is not referenced anywhere else.
- we didn't call `__vue_normalize__` with `script = undefined`

Bingo, tree-shake it


I'm aware that this might be childish analysis, but I think it make sense, right?

**Comment by lukastaegert** [comment]
Yes, the `typeof` was indeed irrelevant, my bad.

> __vue_normalize__ may cause a side effect through its script argument. However, in the unused __vue_normalize__ function call, the script argument passed to it is still a local variable and we know it is not referenced anywhere else

Yes, but we still need to track the function call parameter to know `script.options` can be safely accessed. This is the ultimate goal but will take time.

**Comment by Nandiin** [comment]
> This is the ultimate goal
Happy to hear that! 😄

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
