### ISSUE TITLE
Invalid CJS exports in ESM build.

### ISSUE THREAD

**Issue by thysultan** [rollup/rollup#2498]
- Rollup Version: 0.66.4
- Operating System (or Browser): osx 10.12.4
- Node Version: 9.7.1

### How Do We Reproduce?

Repo: https://github.com/thysultan/dio.js/tree/X (updating to 0.66.4 from 0.64.1)

### Expected Behavior

Should not mangle/include `cjs` exports in `esm` builds.

### Actual Behavior

ESM modules produce cjs `export.name = value` exports with some of the exports mangled i.e

```js
// LGTM
export { Children, fragment as Fragment, struct$2 as Component, pure as PureComponent, render$1 as render, hydrate, create$8 as createContext, create$6 as h, create$6 as createElement, portal$1 as createPortal, comment$1 as createComment, clone as cloneElement, valid as isValidElement };

// Looks like the last three letters of expo(rts)
rts.h = create$6;
// invalid for esm modules.
exports.createElement = create$6;
exports.createPortal = portal$1;
exports.createComment = comment$1;
exports.cloneElement = clone;
exports.isValidElement = valid;
```

**Comment by lukastaegert** [comment]
Might be related to #2489

**Comment by lukastaegert** [comment]
This took me a while to figure but the reason is quite simple:
In your config you have

```
output: [
  {
    file: pkg.main,
    ...
  },
  {
    file: pkg.module,
    ...
  }
]
```

Now looking at your package.json file, both point to the *same*  target file `dist/dio.es.js` and one is overwriting the other. As the CJS output is a little longer, you see remains of the CJS bundle after the ESM bundle.

**Comment by thysultan** [comment]
Thanks
