### ISSUE TITLE
Rollup version:

### ISSUE THREAD

**Issue by Sabrinsulthana** [rollup/rollup#2500]
- Rollup Version:
- Operating System (or Browser):
- Node Version:

**Comment by Sabrinsulthana** [comment]
Hi friends,
    while performing the rollup it started compiling and shows unresolved dependency. I am new for this rollup version. so kindly help through this problem.

Thanks in advance

**Comment by shellscape** [comment]
@Sabrinsulthana hey there. it looks like you might be struggling with the issues here on github. here's a few links on issues that might be good to review:
https://help.github.com/articles/creating-an-issue/
https://guides.github.com/features/issues/
https://help.github.com/articles/about-issues/

We also ask that users try support options first for these types of questions:

> 👉🏽 Need help or tech support? Please don't open an issue! Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs.

Please also take a moment to read the issue type descriptions, and choose wisely when selecting the type of issue you open. Issue templates should also be followed and information in them should be heeded.
