### ISSUE TITLE
The process of rollup do not suspend automatically.

### ISSUE THREAD

**Issue by terrykingcha** [rollup/rollup#2501]
- Rollup Version: 0.66
- Operating System (or Browser): Mac OS X 11.13
- Node Version: 8

### How Do We Reproduce?

Run rollup like "rollup -c build/rollup.config.js",  the process do not suspend until press "Ctrl + C"

### Expected Behavior

Exit the process, after building is end.

### Actual Behavior

The process is hang-up all the time.

**Comment by shellscape** [comment]
@terrykingcha please do follow the instructions in the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>  1. Using the REPL at https://rollupjs.org/repl, or
>  2. Work to isolate the problem and provide the exact steps in this issue, or
>  3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     These may take more time to triage than the other options.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
