### ISSUE TITLE
virtual entry points

### ISSUE THREAD

**Issue by FND** [rollup/rollup#2509]
### Feature Use Case

When dynamically generating bundles (e.g. a sandbox where users can input source code to be evaluated on the fly; think a UI components library), we want to avoid having to create temporary files to serve as entry points.

This is because such temporary files result in various hurdles like requiring write permissions (whereas bundling itself works just fine with a read-only file system) or even performance and potential concurrency issues.

### Feature Proposal

For the reasons outlined above, it would be helpful if Rollup accepted a combination of source code and reference directory as entry points:

```javascript
rollup.rollup({
  input: {
    source: 'import foo from "./foo"; foo()',
    referenceDir: "/path/to/src"
  }
});
```

As far as I can tell, this would have to be implemented somewhere around here:
https://github.com/rollup/rollup/blob/c4715ee32e4e4cb75b7bfd6a3354af670ecb81e7/src/Graph.ts#L288
Unfortunately, I'm insufficiently familiar with Rollup's internals to provide a pull request at this time.

**Comment by tivac** [comment]
I'm pretty sure https://github.com/rollup/rollup-plugin-virtual/ could help here.

**Comment by FND** [comment]
Oh, excellent, that does indeed work - thank you!

FWIW, it appears import paths are relative to the current working directory, which isn't ideal (just because it's less predictable and can be a hassle to debug). The plugin might just be [a few LoC](https://github.com/rollup/rollup-plugin-virtual/blob/master/src/index.js), but it's not clear to me how I'd go about providing an explicit reference directory instead.

**Comment by tivac** [comment]
You're not wrong that a file can only be handled by a single `load` function, but every `transform` hook will run on it even if it was handled by a previous plugin's `transform` function.

I think there might be something else going on here.

**Comment by FND** [comment]
After some arduous debugging, I've identified the culprit¹: I simply need to omit the `\0` prefix from module names (i.e. `diskless:index.js` instead of `\0diskless:index.js`). In hindsight, that makes sense:

> If your plugin uses 'virtual modules' (e.g. for helper functions), prefix the module ID with `\0`. This prevents other plugins from trying to process it.

https://rollupjs.org/guide/en#conventions

So it was my mistake all along; my simple diskless plugin now does exactly what I need it to. Sorry for the noise.

¹ https://github.com/rollup/rollup-pluginutils/blob/fe8b70a981114becb856dfbc0f1099b6a255ce17/src/createFilter.js#L13
via
https://github.com/rollup/rollup-plugin-babel/blob/97953e150f1777487ed9860507fbd1846e66dd16/src/index.js#L55
and
https://github.com/rollup/rollup-plugin-babel/blob/97953e150f1777487ed9860507fbd1846e66dd16/src/index.js#L75

**Comment by FND** [comment]
Turns out that in order to support Node's resolution algorithm, I need to invoke [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) myself:

```javascript
let nodeResolve = require("rollup-plugin-node-resolve");
let resolver = nodeResolver(resolverConfig);
…
resolveId(importee, importer) {
    if(importer && importer.startsWith(disklessPrefix)) {
        let virtual = path.resolve(referenceDir, importer);
        return resolver.resolveId(importee, virtual);
    }

    return importee.startsWith(disklessPrefix) ? importee : null;
}
```

Of course in practice, that greatly complicates things because `resolverConfig` depends on the context (i.e. users' configuration, so I can't just hard-code the above).

I assume that's just the way `#resolveId` works though: All or nothing, i.e. it's not supposed to be combined with a cascade of adjacent plugins?
