### ISSUE TITLE
Rollup generates an error message while trying to resolve external modules in watch mode

### ISSUE THREAD

**Issue by xwisdom** [rollup/rollup#2513]
Hello, 

- Rollup Version: 0.66.2
- Operating System (or Browser): Chrome 69/Windows 10
- Node Version: v8.12.0

### How Do We Reproduce?

I'm getting an error message after editing a file while running rollup in watch mode. Here's my setup:

```javascript
// rollup config 
{
    // ...other props here...
    external: ["jquery"]
}
```

```javascript
// app.js
import $ from "jquery";
import object2 from "./module2.js";
console.log($("body").html());
console.log(object2);
```

```
// cli
rollup -c -w
```
After editing *module2.js* an error message is generated.

### Expected Behavior
Rollup should not attempt to resolve external modules. The output file should be updated without any error messages.

### Actual Behavior
The following error message is generate:

```
Error: Could not load jquery (imported by c:\myapp\scripts\app.js): ENOENT: no such file or directory, open 'c:\myapp\scripts\jquery'
```

I think rollup is ignoring the external config property when running in watch mode.

Note: The error will not be generated if changes were made to the file (app.js) containing the 'import $ from "jquery"' line of code. If I move the import statement to module2.js and then edit app.js, the error is generate.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
