### ISSUE TITLE
babel-plugin-macros

### ISSUE THREAD

**Issue by lifeiscontent** [rollup/rollup#2515]
- Rollup Version: 0.66.6
- Operating System (or Browser): OSX 10.14
- Node Version: 8.12.0

### Expected Behavior

babel-plugin-macros should work as expected.

### Actual Behavior

using babel-plugin-macros with rollup doesn't work due to your own module system.

**Comment by shellscape** [comment]
Thanks for the issue @lifeiscontent, but:

> Issues without minimal reproductions will be closed! Please provide one by:
> 1. Using the REPL at https://rollupjs.org/repl, or
> 2. Work to isolate the problem and provide the exact steps in this issue, or
> 3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>   These may take more time to triage than the other options.

Please do follow those instructions or we'll have to close this one.
