### ISSUE TITLE
Hints on locating build errors

### ISSUE THREAD

**Issue by btakita** [rollup/rollup#2516]
I'm getting an error with building a sapper project:

```
✗ client
Cannot read property 'imports' of undefined
```

It is difficult to locate the source of this error because there is no stack trace or any other hint as to what could be causing this error.

It would be helpful to have some sort of hint to at least print out where this error is occurring. Otherwise, finding the needle in the haystack can easily take hours of time.

Thank you!

**Comment by laurentpayot** [comment]
@btakita are you using the rollup sapper template? With a typescript or a coffeescript client? I had the same issue as you and it was because `client.js` is hard-coded in the rollup-only `extract_css` function of sapper.
I fixed it with a sed script in my postinstall npm script.

**Comment by antony** [comment]
I get this exact same error. If I run `npm run build` it shows me that a bundle which contains `@uppy` file uploader fails to build, but that's about all I get.

I have another Sapper project which doesn't make it to the bundling stage, and fails with:

```
> sapper build --legacy

> Building...
> Cannot read property 'type' of undefined
```

Having a very hard time finding out what is going on with it. I wish there was a way to provide a bit more context to these errrors.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
