### ISSUE TITLE
Align semantics for Wasm modules between early draft specifcation and Rollup

### ISSUE THREAD

**Issue by littledan** [rollup/rollup#2517]
### Expected Behavior / Situation

We have consensus among bundlers, browsers and specs about the semantics of Wasm modules with respect to ESM.

### Actual Behavior / Situation

There are various distinct semantics under discussion/implementation.

### Modification Proposal

Let's all talk about stuff and figure out what should change!

The [WebAssembly CG](https://www.w3.org/community/webassembly/) (which you're all welcome and encouraged to join, no W3C membership required) is discussing [this proposal](https://github.com/webassembly/esm-integration) for what it'd mean to integrate Wasm and ESM modules natively. Based on further conversations since that draft was written, [this explainer](https://github.com/linclark/esm-integration/blob/5f5aae04810f2b03144e75278ab50f4a095f28e2/proposals/esm-integration/README.md) (mostly by Lin Clark, with some edits from me) is my best guess of the current direction of the CG.

The core of the proposal is that Wasm modules are instantiated at ESM evaluation time (rationale at the bottom of the document). It's as if each Wasm module were a JS module with a top-level await for an instantiateStreaming call, which filled in the exports.

My understanding is that Rollup does things differently, and does Wasm instantiation during the ESM instantiate phase, supported by various rewrites that make this possible.

I'm not sure what semantics we should standardize exactly (whether it's one of these two, or some kind of combination/third option), but I think the ecosystem would be best served by bundlers agreeing with native semantics if possible.

cc @xtuc @lukewagner @linclark . cf https://github.com/webpack/webpack/issues/8144

**Comment by sokra** [comment]
Seem to be related to SystemJS:

https://github.com/systemjs/systemjs/blob/47f7429ea22f5f74218741286fac014860a789b3/src/features/wasm-load.js#L43-L48

**Comment by littledan** [comment]
Note, I've been working on improving the WebAssembly/ESM integration documentation and specification. I'd really appreciate more feedback from Rollup folks here, as I believe the semantics are rather different. See https://github.com/WebAssembly/esm-integration/blob/master/proposals/esm-integration/README.md for more details.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
