### ISSUE TITLE
Rollup can produce a bundle that tries to modify a frozen object, which is guaranteed to throw a TypeError at runtime

### ISSUE THREAD

**Issue by rmacklin** [rollup/rollup#2519]
- Rollup Version: 0.66.6
- Operating System (or Browser): Chrome 69
- Node Version: N/A (reproduced using REPL in Chrome 69)

### How Do We Reproduce?

First, observe that:

```js
// main.js
import * as foo from "./foo"

foo.newProp = 'hello'
```

```js
// foo.js
export function func1() {
  console.log('func1');
}

export function func2() {
  console.log('func2');
}
```

correctly results in `Error: Illegal reassignment to import 'foo'`

[REPL link](https://rollupjs.org/repl?version=0.66.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAlNUMlMjIuJTJGZm9vJTVDJTIyJTVDbiU1Q25mb28ubmV3UHJvcCUyMCUzRCUyMCdoZWxsbyclMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZnVuYzEoKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygnZnVuYzEnKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwZnVuYzIoKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygnZnVuYzInKSUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

However,

```js
// main.js
import foo from "./foo_wrapper"

foo.newProp = 'hello'
```

```js
// foo.js
export function func1() {
  console.log('func1');
}

export function func2() {
  console.log('func2');
}
```

```js
// foo_wrapper.js
import * as foo from "./foo"

export default foo
```

does not result it an error. It successfully compiles to:

```js
'use strict';

function func1() {
  console.log('func1');
}

function func2() {
  console.log('func2');
}

var foo = /*#__PURE__*/Object.freeze({
  func1: func1,
  func2: func2
});

foo.newProp = 'hello';
```

[REPL link](https://rollupjs.org/repl?version=0.66.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAlNUMlMjIuJTJGZm9vX3dyYXBwZXIlNUMlMjIlNUNuJTVDbmZvby5uZXdQcm9wJTIwJTNEJTIwJ2hlbGxvJyUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBmdW5jMSgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdmdW5jMScpJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBmdW5jMigpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdmdW5jMicpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vX3dyYXBwZXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwZm9vJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28lNUMlMjIlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmb28lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior

The `foo_wrapper` case should throw the same error as the simpler `foo` case.

### Actual Behavior

Rollup succeeds in compiling the bundle. The bundle tries to assign a property to a frozen object, which is guaranteed to throw `TypeError: Cannot add property newProp, object is not extensible` because we are in strict mode.

Rollup should catch this at compile time rather than producing a bundle that is guaranteed to throw an exception at runtime. (The same way that it prevents this in the simpler `foo` case.)

**Comment by rmacklin** [comment]
> If you want to modify variables of a module, then make a helper that modifies it from the module, then call it elsewhere.

I'm aware of this. I was not asking for how I should change the code in the example. Rather, the reason I opened this issue was to demonstrate that rollup is not failing to compile in the second example, even though it does correctly fail to compile in the first example. In my opinion, it seems that rollup should be able to detect that the second example is also invalid at compile time.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
