### ISSUE TITLE
Cache manifest

### ISSUE THREAD

**Issue by isidrok** [rollup/rollup#2520]
### Feature Use Case

When using `hashes` for the output files name it is difficult to know which file references each chunk, I have been trying to write a plugin for that but it is quite complicated to know which is the correct entry point specially if having several entries that share some code, for example:

```js
// foo.js
export const foo = 1;

// bar.js
export const bar = 2;

// index.js
import * as foo from './foo';
import * as bar from './bar';
import * as lib from 'somelib';

export { foo, bar, lib };

// rollup.config.js

{
  input: ['./foo.js', './bar.js', './index.js'],
  output: {
   dir: 'dist',
   entryFileNames: '[name].[hash].js',
   chunkFileNames: '[name].[hash].js',
  },
  experimentalCodeSplitting: true
}
```
This will result in two files beign generated for `foo` and `bar` and one file for `index` but I can't see a clear way to identify the entrypoint for `foo` or `bar` (which I assume is the wrapper file that just re-exports the other one).

### Feature Proposal

I was thinking that rollup could automatically generate some sort of assets manifest or if the information available inside the plugin hooks was enough to do that we could write a plugin.

It would be really cool if we were able to clearly identify from inside the `generateBundle` hook which files are to be used as entrypoints and which are "intermediate" files for handling common dependencies, so we could output something like:

```js
// static-manifest.json
{
  "bar.js": "bar.1.js",
  "foo.js": "foo.1.js",
  "index.js": "index.1.js"
}

// where bar.1.js and foo.1.js are the entrypoints for those chunks

//bar.1.js

import {bar} from './bar.2.js'


```

**Comment by shellscape** [comment]
@soyjuanmacias  please avoid adding "same problem" replies to issues and pull requests. Instead, please use [Github reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) on the reply or original post you agree with.

**Comment by isidrok** [comment]
I may have come up with a plugin, can anyone confirm that `entryModuleFacade` chunks won't have any `modules` once in the `generateBundle` hook?

**Comment by lukastaegert** [comment]
Sure. We started with minimal information to keep the API surface small but we are definitely open to extensions. The `isEntry` value that you can access in the bundle object you get via `generateBundle` will already help you to identify entry points. What further information would you love to have in here?

And you are correct about `entryModuleFacade` chunks. Those are always entry points but never contain any modules, they just serve to make sure you do not have any unwanted exports in your entry points.

**Comment by isidrok** [comment]
For example `isEntryModuleFacade` property would be more intuitive to use than checking the modules. And maybe an `isDynamicImport` and a reference to the source file (the original imported module) would be great aswell, not sure if that info is internally available though.

Thanks!

**Comment by lukastaegert** [comment]
isDynamicImport definitely sounds good. We'll need to think about how the proposition with the source file.

Why is it important to know if a facade is used?

**Comment by isidrok** [comment]
I need to know which modules are facades in order to use them from outside of the bundle that generated them, working on a multi-repo setup with SystemJS 2 and [import-maps](https://github.com/domenic/import-maps).

**Comment by isidrok** [comment]
Closing this since #2575

**Comment by lukastaegert** [comment]
👍It will probably take another 2-3 days until this is released as there are two more PRs I want to merge into the release.
