### ISSUE TITLE
Tree shaking named Imports with aliases get reverted to original name

### ISSUE THREAD

**Issue by jdalrymple** [rollup/rollup#2521]
- Rollup Version: 0.66.6
- Operating System (or Browser): Chrome 69
- Node Version: N/A (reproduced using REPL in Chrome 69)

### How Do We Reproduce?

```javascript
import { put, post, delete as del } from 'got';

console.log(post)
console.log(del)
console.log(put)
```

### Expected Behavior

```javascript
import { put, post, delete as del } from 'got';

console.log(post);
console.log(del);
console.log(put);
```

### Actual Behavior

```javascript
import { put, post, delete } from 'got';

console.log(post);
console.log(delete);
console.log(put);
```

Im not sure if this was previously brought up or is mentioned in the docs :/ I've looked through the closed and open issues but didnt see anything similar.

**Comment by jdalrymple** [comment]
Is this an actual problem, or is this by design?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by jdalrymple** [comment]
@shellscape Just retested in repl and obtained the same behaviour :). Is this the desired output or should rollup handle aliases?

**Comment by shellscape** [comment]
@jdalrymple I would expect not. Could you provide a link to the REPL that you used to test? That'll help the maintainers when they tackle this. In the mean time, I'm reopening and will add this to the list of middle-aged bugs that need attention.

**Comment by jdalrymple** [comment]
***CORRECTION**

It works for esm output, just not any of the others.

Here is the [repl](https://rollupjs.org/repl/?version=1.19.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHB1dCUyQyUyMHBvc3QlMkMlMjBkZWxldGUlMjBhcyUyMGRlbCUyMCU3RCUyMGZyb20lMjAnZ290JyUzQiU1Q24lNUNuY29uc29sZS5sb2cocG9zdCklNUNuY29uc29sZS5sb2coZGVsKSU1Q25jb25zb2xlLmxvZyhwdXQpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by jdalrymple** [comment]
**CORRECTION #2 **

Apparently i misread the code, looks like it works fine lol Sorry for the hassle

**Comment by shellscape** [comment]
No worries!

**Comment by lukastaegert** [comment]
This behaviour is by design. The reason is that in a bundle, a function can only have one unique name while in theory, each importer can do so via another name. The rationale here is that the name in the original file is the name intended by the original author and may be the most correct one, otherwise there would be no deterministic process to come up with a name.

**Comment by lukastaegert** [comment]
But maybe I also misread your issue. 🤪
