### ISSUE TITLE
rollup AMD modules var self = undefined

### ISSUE THREAD

**Issue by dazinator** [rollup/rollup#2523]
- Rollup Version: 0.66.2
- Operating System (or Browser): Windows 10 (Chrome)
- Node Version: 8.12.0 (npm 6.4.1)

### How Do We Reproduce?

Place the following two AMD module files under an `/amd` subfolder:

RollupPageModule.js:
```
define(function () {   
    var self = this;
    self.foo = function () {      
    };
    self.foo();
    return self;
});
```

RollupPage.js:
```
define(['./RollupPageModule'], function (moduleB) {
    console.log("hi this is a page level module.");
    moduleB.foo();
});
```

Then we run rollup, but the first plugin is the AMD plugin that re-writes the AMD modules as ES6 modules so that they can be bundled by rollup.

This script shows the options to run rollup with the plugin configured:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const lookup = require("module-lookup-amd");
const amd = require("rollup-plugin-amd");
const rollup = require('rollup');

var plugins = [];
var amdpluginConfig = {"rewire":function (moduleId, parentPath) { return lookup({ partial: moduleId, filename: parentPath, config: {baseUrl: '/amd'} }); }}
var amdPlugin = amd(amdpluginConfig);		
plugins.push(amdPlugin);

const bundle = rollup.rollup({input: '/amd/RollupPage.js' });
const { code, map } = bundle.generate({format: 'esm', file: 'rollupbundle.js'});

```

### Expected Behavior

Here is the generated code (contents of rollupbundle.js):

```
var self = undefined;
self.foo = function () {
};
self.foo();

console.log('hi this is a page level module.');
self.foo();
```

Not sure why `var self = this` is rewritten to `var self = undefined` causing the script to fail.

### Actual Behavior

As mentioned above.

**Comment by TrySound** [comment]
Why do you use `this` in your code? Why not window/self/global?

**Comment by dazinator** [comment]
There are a lot of knockoutjs view models written as AMD modules, and the standard pattern is `var self = this` for reasons this pattern is used here are some reasons: https://stackoverflow.com/questions/17163248/whats-the-advantage-of-using-var-self-this-in-knockout-js-view-models

However I am open to alternatives. The primary reason from my perspective is to capture the current context, such that other functions when fired as a result of DOM element events, those functions can reference `self` to get the original captured context as opposed to `this` which in the scope of that function could be anything (usually the current DOM element)

**Comment by TrySound** [comment]
This is not related to rollup. In valid es modules `this` is `undefined`. You should transpile it to whatever you want.

**Comment by dazinator** [comment]
I am thinking the bug is perhaps not rollup, but something perhaps for the rollup amd plugin to consider as that is the thing that takes AMD code and converts it to ES 6 module.

According to this (and your conversations above): http://exploringjs.com/es6/ch_modules.html#_browsers-scripts-versus-modules in the AMD world, a top level this refers to the current window, where as in ES6 it is undefined. Do you think the amd plugin for rollup when converting an AMD module to ES6 should actually convert a top level this to be Window rather than allowing the default conversion that seems to be happening, which end up `undefined` ? That's my best guess. If that sounds right I'll close this issue here and open it over there.

**Comment by TrySound** [comment]
Yes, this plugin should transpile it.

**Comment by dazinator** [comment]
@TrySound thanks for helping me onward in the right direction

**Comment by dazinator** [comment]
Thinking about this further, even though the plugin should transpile a top level `this` , I think what you said has sunk in a bit more. There is absolutely no need in my case, with AMD modules representing knockout view models, that I need to rely on `window`. This works just as well:

```
define(function () {   
    var self = {};
    self.foo = function () {      
    };    
    return self;
});

```

I have logged an issue with the plugin author anyway, but really its probably a scenario that most sensible people won't get into in the first place!
