### ISSUE TITLE
rollup is producing invalid sourcemaps

### ISSUE THREAD

**Issue by neelance** [rollup/rollup#2525]
- Rollup Version: 0.66.6
- Operating System (or Browser): OS X
- Node Version: v10.11.0

### How Do We Reproduce? (Edited)
See repository https://github.com/neelance/sourcemap-bug. Just run `./show-bug.sh`.

When I build the project with rollup 0.66.6, the generated sourcemap is invalid. The tool sm-tool gives the error `Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index`. The tool sourcemap-lookup is giving wrong answers. With rollup 0.66.2 everything is fine.

I tracked the issue down to the upgrade of the sourcemap-codec module from version 1.4.1 to 1.4.3 in commit 8a8721ea0657073de9db35862d4ab9e1dc402973. 

### Expected Behavior
Valid sourcemap gets generated.

### Actual Behavior
Generated sourcemap is invalid.

**Comment by shellscape** [comment]
@neelance thanks for the issue, but unfortunately you didn't follow our guidelines for reproductions:

> Issues without minimal reproductions will be closed! Please provide one by:
> 1. Using the REPL at https://rollupjs.org/repl, or
> 2. Work to isolate the problem and provide the exact steps in this issue, or
> 3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>     These may take more time to triage than the other options.

Please choose one of the options for providing a reproduction.

**Comment by neelance** [comment]
I actually managed to reproduce it with a minimal project: https://github.com/neelance/sourcemap-bug

**Comment by kyle1320** [comment]
After more investigation, it looks like this is indeed a bug in [`sourcemap-codec`](https://github.com/Rich-Harris/sourcemap-codec), which is used by both Rollup and `magic-string`, whereas UglifyJS uses [`source-map`](https://github.com/mozilla/source-map).

There is a PR open to fix the issue in `sourcemap-codec` (probably should have looked there first, hm...)

https://github.com/Rich-Harris/sourcemap-codec/pull/77

**Comment by tmcconechy** [comment]
We are also seeing after upgrading to 7.0.0 the same (or similar) issue. It was noted if we debug our scripts that have been sourcemapped via rollup. If an error occurs in the console and you click the lines of the error it goes to the wrong place. Also adding a debugger statement near the end of the script (works better near the top) will go to the wrong place. The only solution is to turn off sourcemaps in chrome.

When might this be in a release / which release out of curiosity?
