### ISSUE TITLE
Output includes require() calls

### ISSUE THREAD

**Issue by eljenso** [rollup/rollup#2528]
- Rollup Version: 0.66.6
- Operating System (or Browser): Fedora 28
- Node Version: v10.12.0

### How Do We Reproduce?

https://github.com/eljenso/rollup-apollo-issue

- `npm install`
- `npx rollup -c rollup.config.js`

### Expected Behavior
Should output correct SystemJS-compatible code.

### Actual Behavior
Output includes `require()` calls (e.g. `var wrap$1 = require('optimism').wrap;`).
This also happens when setting `esm` as format.

**Comment by ovac** [comment]
I have the same issue.

**Comment by eljenso** [comment]
No, I have switched back to webpack.

**Comment by stevezhaoUS** [comment]
I have the same issue. No wonder why Webpack has more users now.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
