### ISSUE TITLE
Support excluding sourceContent from source maps

### ISSUE THREAD

**Issue by kitsonk** [rollup/rollup#2530]
### Feature Use Case

When using bundle source maps where the main use case is just to remap error stacks, the `sourcesContent` can be unnecessary data which increases the source map size and can decrease the performance of the consuming application for significantly large bundles.

Both `magic-string` and the [source-map specification](https://sourcemaps.info/spec.html) treat `sourcesContent` as optional, but Rollup currently always includes sources.

See: denoland/deno#1087 for a specific real world use case.

### Feature Proposal

Provide a flag to exclude sources from the source map.

**Comment by aleclarson** [comment]
Yes please. Is there a workaround?

**Comment by kitsonk** [comment]
This was closed in 84c2fa084ee4d138aa541c3dc7657bf8f5eb98f9
