### ISSUE TITLE
NODE_ENV cannot be used

### ISSUE THREAD

**Issue by def14nt** [rollup/rollup#2533]
- Rollup Version: v0.66.0
- Operating System (or Browser): OpenSUSE Leap 15
- Node Version: v10.10.0

### How Do We Reproduce?

When trying out `process.env.NODE_ENV`, it seems that Rollup removes it without using hacks like `(process).env.NODE_ENV`. My objective is to have code run at development, and when `process.env.NODE_ENV === 'development'`, have the if statement be *left* there, because the condition would be true. I've tried various solutions like `rollup-plugin-replace`, but it seems my only option now is to run something on top of Rollup after compilation. Is there a way to fix this?

### Expected Behavior

If `process.env.NODE_ENV` is set to `development`, leave the if statement there so the code is run.

### Actual Behavior
The if statement is blindly removed.

**Comment by def14nt** [comment]
Oh dear, it seems it has started to work **without config**. Good job Rollup, I guess. Must be me :/

**Comment by def14nt** [comment]
Through my research, Rollup changes `if(always true statement)` to a block, and it removes `if(always false condition)` blocks.

**Comment by TrySound** [comment]
@def14nt This is the point of rollup. It produces optimized code. Your case is if statement treeshaking.

**Comment by def14nt** [comment]
I'm trying to find a way to make a toggleable development mode, which renders the source still usable by the browser. This might not be the best way.

**Comment by TrySound** [comment]
Just dont replace NODE_ENV and provide global variable instead which you may toggle.

**Comment by lukastaegert** [comment]
Yes. `rollup-plugin-replace` should only be used if you want to replace `process.env.NODE_ENV` and consequently simplify your code. By default, rollup will never replace global variables exactly because your use case is what library developers usually want.

**Comment by def14nt** [comment]
I have a solution that renders the source still usable in Chrome, without monkey patching the  `process` global.

I am going to just add the `console.*` to the source without any devmode checks, because terser has an option to strip `console.*` calls from the source. Problem solved!

**Comment by def14nt** [comment]
p.s I've come up with [an npm package](https://npmjs.com/rollup-replace-regex) which might be of use.

**Comment by TrySound** [comment]
Might be dangerous.

**Comment by def14nt** [comment]
@TrySound tbh i don't use it cos it doesn't have testing so bugs, just shows how to do it I guess. Wouldn't say it's dangerous tho

**Comment by Alfred-kai** [comment]
you can use rollup --environment params,eg
```
"scripts": {
    "build:dev": "cross-env NODE_ENV1=development && rollup -c --environment dev",
    "build:prod": "cross-env NODE_ENV1=production  && rollup -c --environment prod",
  },
```
then use `process.argv[4]` to judge environment
