### ISSUE TITLE
Watcher ignoring files in 'source' directory. 

### ISSUE THREAD

**Issue by dwkns** [rollup/rollup#2535]
- Rollup Version: 0.66.6
- Operating System (or Browser): OS X 10.14
- Node Version: v10.12.0

**Project structure**
```
/source
│    index.html
└─── /js
|    │   main.js.        // Entry point
│    │   helloWorld.js 
|
└─── /scss
     │   main.scss       // imported in js/main.js
     │   _body.scss      // imported in scss/main.scss
```
When watching my project using `node_modules/.bin/rollup -c -w` only changes to the js files and the first imported `scss/main.scss` files are detected. 

Changes to `index.html` & `scss/_body.scss` are ignored and the bundle is not rebuilt. 

```js
// rollup.config.js
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import copy from 'rollup-plugin-copy';
import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload';
import postcss from 'rollup-plugin-postcss';

export default {
    input: 'source/js/main.js',
    output: {
        file: 'build/js/bundle.js',
        format: 'iife'
    },
    watch: {
        include: 'source/**',
        clearScreen: false
    },
    plugins: [
        copy({
            'source/index.html': 'build/index.html',
            verbose: true
        }),
        resolve({
            preferBuiltins: true
        }),
        postcss({
            extract: './build/css/main.css',
            plugins: [],
            extensions: ['.css', '.sass', '.scss'],
            minimize: false
        }),
        commonjs(),
        babel({
            exclude: 'node_modules/**'
        }),
        serve({
            open: true,
            verbose: true,
            contentBase: 'build'
        }), 
        livereload()
    ]
};
```

[Example project repository](https://github.com/dwkns/rollup-watch-test)

### Expected Behavior
Changes to any file in the source folder should trigger a bundle rebuild. 

### Actual Behavior
Only changes to some files in source folder trigger bundle rebuild.

**Comment by tivac** [comment]
Sounds like the scss plugin doesnt tell rollup about its dependencies. Rollup only watches files that are part of the dependency graph for the bundle.

**Comment by dwkns** [comment]
@tivac It seems like an odd behaviour considering that you can pass in an `include` parameter. This would imply that everything within the 'included' directory should be watched. If not, what is its purpose?

It begs a couple of questions : 
- How can we see which files *are* included in the dependency graph?

- Is there a way of telling the watcher to watch all files in a given directory, regardless of whether they are in the dependency graph? 

- Is there a way of specifically adding files to the dependency graph?

**Comment by muyi0327** [comment]
+1

**Comment by muyi0327** [comment]
@dwkns +1

**Comment by lemoustachiste** [comment]
For what it's worth I worked around the `scss` dependency files issue by using an independent watcher:

`styles:build": "node-sass-chokidar src/styles -o src/styles`

Note that I am building to CSS within the same folder, and that triggers a refresh from the watcher.

This is my `rollup-plugin-sass` configuration:
```
sass({
        output: `${BUILD_OUTPUT_FOLDER}/index.css`,
        include: [`${SRC_INPUT_FOLDER}/styles/*.css`, `${SRC_INPUT_FOLDER}/styles/*.scss`],
        options: {
          outputStyle: 'compressed'
        }
      })
```

It'd be good if this could work natively though.

However I came here because I have no success triggering a refresh from a change in an .html file.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by GeorgeTailor** [comment]
Closing an issue just because no one answered it is not solving a problem.
There were some concrete questions asked by @dwkns.
