### ISSUE TITLE
Slow performance on import a huge ESM script

### ISSUE THREAD

**Issue by KayLeung** [rollup/rollup#2536]
- Rollup Version: v0.66.6
- Operating System (or Browser): Windows 10
- Node Version: v10.12.0

### How Do We Reproduce?

https://github.com/date-fns/date-fns/tree/master/examples/rollup
1. Run `misc.js` in above repo and compare the differences to change the syntax below

### Expected Behavior
expected Rollup only parse the import named exports

### Actual Behavior
The transpiling became very slow after import a huge ESM. For example, the date-fns.
https://github.com/date-fns/date-fns/blob/master/src/esm/index.js

Slow: (@2x slower)
`import {format} from 'date-fns/esm'`

Fast:
`import format from 'date-fns/esm/format'`

**Comment by kyle1320** [comment]
Parsing all of the imports is necessary – even if the imported / exported variables aren't used, the modules could still have side effects like assigning to a global object. Tree-shaking will remove unneeded code in the end, but the imported modules still need to be parsed just in case they contain any code that shouldn't be removed.

The best way to avoid unnecessary parsing would be to import the module directly, as in the "fast" method above.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
