### ISSUE TITLE
1.0 output API named entry points

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2537]
### Feature Use Case

When using named entry points, it isn't necessarily obvious to read them off in order from the output array in the 1.0 API.

### Feature Proposal

When using the object form of entry points, also provide these object properties on the output array so that you get:

```js
output[0] === output['entry.js']
```

ahh, the power of JavaScript.

**Comment by shellscape** [comment]
@guybedford is this still relevant, and is it a bug or enhancement in your mind?

**Comment by lukastaegert** [comment]
It is meant to be an enhancement but personally I’m not a big fan of providing the output in two ways by creating an array chimera.

**Comment by shellscape** [comment]
Shall we close this, or does it need further discussion?

**Comment by guybedford** [comment]
Happy to close this one.
