### ISSUE TITLE
Build stage return `Unexpected token` for .ts file

### ISSUE THREAD

**Issue by ravecat** [rollup/rollup#2542]
Thank you for work!

I faced with confused behaviour

My project include `.ts` files so I used `rollup-plugin-typescript`.

My `rollup.config.js`

```javascript
/* eslint-disable flowtype/require-valid-file-annotation, no-console, import/extensions */
import nodeResolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import babel from "rollup-plugin-babel";
import flow from "rollup-plugin-flow";
import sourceMaps from "rollup-plugin-sourcemaps";
import typescript from 'rollup-plugin-typescript';
import svg from 'rollup-plugin-svg';

const commonPlugins = [
  flow({
    pretty: true
  }),
  sourceMaps(),
  nodeResolve({
    jsnext: true,
    main: true,
    browser: true,
    extensions: [".ts", ".tsx", ".js", ".jsx"]
  }),
  babel({
    exclude: "node_modules/**",
  }),
  typescript(),
  svg(),
  commonjs({
    namedExports: {
      react: [
        "cloneElement",
        "createFactory",
        "Component",
        "PropTypes",
        "createElement",
        "createContext"
      ],
      "react-dom": ["render"],
      "react-is": ["isElement", "isValidElementType", "ForwardRef"]
    }
  }),
];

const globals = { react: "React", "react-dom": "ReactDOM" };

const configBase = {
  input: "./src/index.js",
  plugins: commonPlugins
};

const standaloneBaseConfig = {
  ...configBase,
  output: {
    file: "dist/myproject.js",
    format: "cjs",
    name: "sct",
    globals,
    sourcemap: true
  },
  plugins: configBase.plugins
};

export default standaloneBaseConfig;
```

And get error on build-stage

> src/common/theme.ts (58:21)
SyntaxError: /myproject/src/common/theme.ts: Unexpected token, expected ; (58:21)
  56 |   keyframes,
  57 |   ThemeProvider
> 58 | } = styledComponents as ThemedStyledComponentsModule<ThemeInterface>;

Probably it's not depends on that plugin, it's my guess. Can I get some advices about issue?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
