### ISSUE TITLE
Missing entry points when using --input command line flag, --dir, and experimentalCodeSplitting when entry point filenames collide

### ISSUE THREAD

**Issue by lennartjansson** [rollup/rollup#2543]
- Rollup Version: 0.64.1
- Operating System (or Browser): Ubuntu 16.04
- Node Version: 9.11.1

### How Do We Reproduce?

- Clone https://github.com/lennartjansson/rollup-starter-code-splitting. I've modified the code splitting starter code to have a few additional build commands to illustrate the bug.
- `$ npm run build`
    This should cause output files, including two entry point bundles, to be emitted to `public/module`. Note that the two entry points are named `main-a.js` and `subdir/main-a.js` -- to avoid the collision in bundle names, the two entry point bundles are respectively named `main-a.js` and `main-a2.js`.
- `$ rm -r public/module/*`
- `$ npm run build-with-input-flag-okay`
    Instead of passing the input entry points through the rollup.config.js, we now pass them on the command line with the `--input` flag. The flag occurs twice since we need to specify both entry points. This command works as expected. We will find two entry point bundles named `main-a.js` and `main-b.js` outputted to `public/module`.
- `$ rm -r public/module/*`
- `$ npm run build-with-input-flag-bad`
    This command passes `main-a.js` and `subdir/main-a.js` as entry points with `--input` flags.

### Expected Behavior

After `npm run build-with-input-flag-bad`, there are two bundles emitted to `public/module`, named `main-a.js` and `main-a2.js` and corresponding to entry points `main-a.js` and `subdir/main-a.js`.

### Actual Behavior

After `npm run build-with-input-flag-bad`, there is **one** bundle emitted to `public/module`, named `main-a.js` and corresponding to `subdir/main-a.js`. The first entry point is somehow forgotten by rollup, or the second entry point clobbers the first.

If the ordering of the entry points on the command line is reversed, then again only one bundle will be produced and it will correspond to the second entry point.

It is worth noting that passing the output directory with the command line flag `--dir` instead of the `output` property in rollup.config.js seems to be necessary to repro this bug.

**Comment by lukastaegert** [comment]
Thanks for the issue, this is definitely a bug. Potential fix at #2548, please have a look.
