### ISSUE TITLE
Tree shaking function arguments

### ISSUE THREAD

**Issue by AgronKabashi** [rollup/rollup#2544]
Not sure if this is a bug or not yet supported by rollup.

- Rollup Version: 0.66.4
- Operating System (or Browser): Chrome
- Node Version: 9.11.1

### How Do We Reproduce?
[repl](https://rollupjs.org/repl?version=0.66.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwaGFuZGxlU3RhdGUoc3RhdGUlMkMlMjBzb21lT3RoZXJBcmd1bWVudCklMjAlN0IlNUNuJTVDdHN0YXRlLnNvbWV0aGluZyUyMCUzRCUyMHRydWUlM0IlNUNuJTdEJTVDbiU1Q25oYW5kbGVTdGF0ZSglN0IlN0QpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior
`someOtherArgument` should be treeshaken since it is not used.

### Actual Behavior
`someOtherArgument` remains in the final bundle.

**Comment by lukastaegert** [comment]
Interesting idea but not without dangers as functions have a `length` property that is used by libraries such as ramda to determine the number of expected arguments for their auto-currying which could be broken by this.

If we manage to add proper deoptimization, this could be done, though.

**Comment by AgronKabashi** [comment]
I would imagine that this would best come in handy when tree shaking imported libraries.
If rollup is able to detect that certain arguments are not used then the code paths that are dependent on those variables could be removed.

Example
```js
export default function thirdPartyLib (arg1, arg2) {
  if (arg2) {
    // Do more stuff here, call other libraries etc
  }
  ...
}

//
import thirdPartyLibrary from "thirdPartyLibrary";

// Not using the second argument here or anywhere else in the code
thirdPartyLibrary(option); 
```

**Comment by MaxMilton** [comment]
The way I understand it, Rollup is a _module_ bundler so out of the box it has tree-shaking to remove unused _modules_. Perhaps I'm wrong but this is more like dead code elimination since it's about mangling the code inside of a module.

Sounds like it might be best left up a minifier like [rollup-plugin-terser](https://github.com/TrySound/rollup-plugin-terser) or [rollup-plugin-closure-compiler](https://github.com/ampproject/rollup-plugin-closure-compiler).

However, if using code splitting these kinds of plugins may not necessarily know how a function in used in a separate chunk... which presents its own challenge.

**Comment by lukastaegert** [comment]
> The way I understand it, Rollup is a module bundler so out of the box it has tree-shaking to remove unused modules. Perhaps I'm wrong but this is more like dead code elimination since it's about mangling the code inside of a module.

This is actually a common misconception. Tree-shaking in Rollup does not have to do anything with modules but is basically a different take on dead-code-elimination: https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80

That being said, I misunderstood your issue. I thought you were talking about situations where a parameter is not used in a function. The core to detecting unused arguments is to be able to track arguments, something rollup does not do yet. I am confident this will come to rollup at some point at which the tree-shaking your described will probably work. This is tricky, though, especially from a performance point, so it might come with strict limitations.

**Comment by AgronKabashi** [comment]
I'll close this then since it's not currently in scope for rollup and there are alternatives such as dead code elimination tools to use in the mean time.

**Comment by MaxMilton** [comment]
Thanks for that link @lukastaegert it's actually very insightful! Funny that I hadn't already read it considering I use rollup so much. Also fun to see the early days of the "tree-shaking" terminology.
