### ISSUE TITLE
Docs on how to inteprate timings?

### ISSUE THREAD

**Issue by dazinator** [rollup/rollup#2545]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I was pleased to find the ability in the javascript api, to set a `perf` flag, which exposes a getTimings() function on the bundle.

However now that I have access to the timings, it't not clear how I should interprate them. Here is what I see:

![image](https://user-images.githubusercontent.com/3176632/47920082-0f293c00-dea9-11e8-846c-2bbefa4bbc45.png)

I'd like to know what the total time is to product the bundle. I am trying to measure what the impact is of setting the `cache` on subsequent builds is, compared to not using the cache at all.

Can I assume that these timings represent a list of steps, and that each step is an array of metrics, with the first metric in the array being the time in milliseconds for that step to complete? So for the total build time I just sum them all? Or do some steps happen in parallel so summing wouldn't be accurate of the total build time? I'm not sure what the other metrics in the array represent either.

### Your Proposal for Changes

Describe the output / format of getTimings() including how to measure the overall build time.

**Comment by lukastaegert** [comment]
Hi @dazinator, thanks for the feedback.

I must admit that I would rather not document this API too thoroughly as this is not as polished and mainly for test purposes and I cannot guarantee that it will be as stable as other APIs (though we try of course).

The best way of getting an idea of what this option does is to see how the CLI handles it (via using the `--perf` option), which will add units to those numbers and print them in a readable form.

Order: Even though timings are an object, there is an order which is the one `Object.keys` will use when iterating the keys (as you see, this API may still lack some polish).

Nesting: There are "parent" blocks which include the timings of their "children" and are signified by their starting characters. `# BUILD`  and `# GENERATE` are the top level keys, their timings together are the total run time. The next level uses `## ` while further children have no prefix. Plugin hooks start with `- `.

Measurements: The first number represents the time taken (each key has two measurement points, a start and an end) in milliseconds, the second is the change in memory consumption while the third is total memory consumed. Hooks that run several times are accumulated. Plugin hooks with the suffix (async) are probably very inaccurate.

**Comment by shellscape** [comment]
@lukastaegert can we add some high-level documentation along with an obvious warning marker that the API is considered internal use only (or some such)?

**Comment by lukastaegert** [comment]
I guess you are right, PR here: rollup/rollupjs.org#166

**Comment by lukastaegert** [comment]
Closing this as the documentation has been extended. Feel free to reopen if you need more information.

**Comment by dazinator** [comment]
Thats great, thank you.
