### ISSUE TITLE
Javascript api and source map url

### ISSUE THREAD

**Issue by dazinator** [rollup/rollup#2546]
- Rollup Version: 0.66.2
- Operating System (or Browser): Windows 10
- Node Version: 8.12.0

Looking at this: https://github.com/rollup/rollup/blob/2d17db991f098d3694263a1d1483c3d6e2a84db8/bin/src/run/build.ts#L59

It appears that when specifying `inline` for sourcemaps option, via the javascript API, you have to append your own source map url ? If that is the case it should probably be clarified in the docs, or perhaps this is seen as a bug (i.e perhaps rollup should be appending this for you?)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
