### ISSUE TITLE
Tree-shaking not acting as expected

### ISSUE THREAD

**Issue by matthewmatician** [rollup/rollup#2547]
- Rollup Version: 0.67.0
- Operating System (or Browser): Chrome 70
- Node Version: 10

### How Do We Reproduce?
I'm trying to use rollup to allow mocking of data, and then have the production script not reference any mock data. Consider the following [**in this repl**](https://rollupjs.org/repl?version=0.66.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHRlc3RGdW5jJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZ0ZXN0aW5nTW9jay5qcyU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2codGVzdEZ1bmMpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRlc3RpbmdNb2NrLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRnRlc3RpbmdNb2NrLmpzJTVDbmxldCUyMG1vY2tpbmclMjAlM0QlMjBmYWxzZSUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjB0ZXN0RnVuYyUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGlmJTIwKG1vY2tpbmcpJTIwcmV0dXJuJTIwJ2Zha2UnJTNCJTVDbiUyMCUyMHJldHVybiUyMCdyZWFsJyUzQiU1Q24lN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

Notice that the built script has no reference to the mock. Now, if I give access to that `mock()` function (but don't reference it), not everything is shaken away as expected [**in this other repl**](https://rollupjs.org/repl?version=0.66.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHRlc3RGdW5jJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZ0ZXN0aW5nTW9jay5qcyU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2codGVzdEZ1bmMpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRlc3RpbmdNb2NrLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRnRlc3RpbmdNb2NrLmpzJTVDbmxldCUyMG1vY2tpbmclMjAlM0QlMjBmYWxzZSUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBtb2NrJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwbW9ja2luZyUyMCUzRCUyMHRydWUlM0IlNUNuJTdEJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMHRlc3RGdW5jJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwaWYlMjAobW9ja2luZyklMjByZXR1cm4lMjAnZmFrZSclM0IlNUNuJTIwJTIwcmV0dXJuJTIwJ3JlYWwnJTNCJTVDbiU3RCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE).

Notice that the output of the second example could again be run through rollup to shake away the reference to the mock.

### Expected Behavior
Output of the second link above should look like this:
```js
//testingMock.js

const testFunc = () => {
  return 'real';
};

console.log(testFunc);
```

### Actual Behavior
Instead, it looks like this:
```js
//testingMock.js
let mocking = false;

const testFunc = () => {
  if (mocking) return 'fake';
  return 'real';
};

console.log(testFunc);
```

Any ideas on how to get this to work would be greatly appreciated.

**Comment by lukastaegert** [comment]
Yes, I fear this is beyond the scope of the current analysis. The logic knows that even though `mocking` is initialized with `false`, somewhere in the code there is an assignment of `true`. The logic does not yet see that this other code is never called as currently, just the presence of this line will mark the value of `mocking` internally as `unknown`.

It is possible that a future iteration (actually more a planned rewrite) of the logic will be able to handle this but this is definitely a very long-term prospect.

**Comment by matthewmatician** [comment]
@lukastaegert, Thanks for the explanation. @GrosSacASac, thanks for the helpful hints. I was thinking I could just wash and repeat on rollup to get the desired result. But prepack looks really interesting.

**Comment by kzc** [comment]
fwiw...

```
$ cat mock1.js
const testFunc = () => { return 'real'; };
console.log(testFunc);

$ cat mock1.js | terser -c toplevel
console.log(()=>"real");
```
```
$ cat mock2.js
let mocking = false;
const testFunc = () => {
    if (mocking) return 'fake';
    return 'real';
};
console.log(testFunc);

$ cat mock2.js | terser -c toplevel
console.log(()=>"real");
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
