### ISSUE TITLE
format umd with external then uglify throw error

### ISSUE THREAD

**Issue by stephenliu1944** [rollup/rollup#2555]
- Rollup Version: 0.66.0
- Operating System (or Browser): windows7
- Node Version: v8.11.1

### How Do We Reproduce?
js file
![image](https://user-images.githubusercontent.com/5137237/48473056-9d4edc00-e832-11e8-8748-66474e24e8d8.png)

rollup.config.js
![image](https://user-images.githubusercontent.com/5137237/48473475-7a70f780-e833-11e8-9ca8-646a7e06c47d.png)

error message
![image](https://user-images.githubusercontent.com/5137237/48473421-62997380-e833-11e8-9654-f563f1de3660.png)

### Expected Behavior
working fine.

### Actual Behavior
throw error.

**Comment by eight04** [comment]
Use [terser](https://github.com/TrySound/rollup-plugin-terser) instead of ugilfy to compress esm.

**Comment by stephenliu1944** [comment]
> Use [terser](https://github.com/TrySound/rollup-plugin-terser) instead of ugilfy to compress esm.
![image](https://user-images.githubusercontent.com/5137237/48541437-91791d80-e8f7-11e8-80b2-899bf5690afa.png)
![image](https://user-images.githubusercontent.com/5137237/48541400-7d352080-e8f7-11e8-926b-8ea4310e1040.png)
I try to use rollup-plugin-terser but still throw error.

and how do I share a part of plugins config for each output format? 
thanks so much.

**Comment by eight04** [comment]
> I try to use rollup-plugin-terser but still throw error.

It's a plugin error. You may want to report it to [rollup-plugin-terser](https://github.com/TrySound/rollup-plugin-terser/issues).

> share a part of plugins config for each output format

Personally, I use a function to create the config:
https://github.com/eight04/linkify-plus-plus/blob/master/rollup.config.js#L32

**Comment by stephenliu1944** [comment]
> > I try to use rollup-plugin-terser but still throw error.
> 
> It's a plugin error. You may want to report it to [rollup-plugin-terser](https://github.com/TrySound/rollup-plugin-terser/issues).
> 
> > share a part of plugins config for each output format
> 
> Personally, I use a function to create the config:
> https://github.com/eight04/linkify-plus-plus/blob/master/rollup.config.js#L32

thanks eight04

**Comment by lukastaegert** [comment]
Closing this as it appears to only be an issue with `terser` at this point, feel free to re-open if you feel otherwise.
