### ISSUE TITLE
Destructured alias is not exported in system

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#2556]
- Rollup Version: 0.67.1

### How Do We Reproduce?

https://rollupjs.org/repl?version=0.67.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwJTdCJTVDbiU1Q3RQcm92aWRlciUzQSUyMEVudmlyb25tZW50UHJvdmlkZXIlMkMlNUNuJTVDdENvbnN1bWVyJTNBJTIwRW52aXJvbm1lbnRDb25zdW1lciU1Q24lN0QlMjAlM0QlMjBjcmVhdGVDb250ZXh0KCklMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyc3lzdGVtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behavior

Both EnvironmentProvider and EnvironmentConsumer should be exported.

**Comment by lukastaegert** [comment]
The question is how to transpile it properly. My best suggestion so far would be to transform this:

```js
export const {
  Provider: EnvironmentProvider,
  Consumer: EnvironmentConsumer,
  nested: {
    value: otherValue
  },
  array: [arrayvalue]
} = createContext();
```

to this

```js
const {
  Provider: EnvironmentProvider,
  Consumer: EnvironmentConsumer,
  nested: {
    value: otherValue
  },
  array: [arrayvalue]
} = createContext();
exports({
  EnvironmentProvider: EnvironmentProvider,
  EnvironmentConsumer: EnvironmentConsumer,
  otherValue: otherValue,
  arrayValue: arrayValue
});
```

I.e. in case we cannot write the definition inline as an export, just collect all defined and exported variables in a separate statement. What do you think @guybedford?

**Comment by TrySound** [comment]
This would make the output code even cleaner.
