### ISSUE TITLE
Rollup Plugin renderChunk throws TypeError

### ISSUE THREAD

**Issue by jonathantneal** [rollup/rollup#2557]
- Rollup Version: 0.67.1
- Operating System (or Browser): macOS Mojave 10.14.1 (18B75)
- Node Version: v11.10, also v10.13.0, also v9.11.2

### How Do We Reproduce?

Add a rollup plugin that uses `renderChunk(code)` to return `code` without transformations. Ideally, I would apply transformations, but that is not necessary to reproduce my issue.

My reproduction of the issue can be found here: https://github.com/jonathantneal/rollup-plugin-issue-with-render-chunk

The steps to reproduce the issue with that repo are to:
1. Clone that repository and move into its directory, then
2. Run `npm install` to install the dependency (rollup) needed by that repository, and then
3. Run `npm test`.

### Expected Behavior

The code is returned and rollup continues running without issue.

### Actual Behavior

The following `TypeError` is thrown:

```
TypeError: Cannot read property 'length' of undefined
    at Link.traceMappings (/CWD/node_modules/rollup/dist/rollup.js:13559:54)
    at collapseSourcemaps (/CWD/node_modules/rollup/dist/rollup.js:13680:21)
    at /CWD/node_modules/rollup/dist/rollup.js:14946:27
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

---

I am prepared for this to be a user error or misunderstanding on my part, and I can’t express properly how greatly I admire this project. Thank you so much for the efforts you put into it.

**Comment by kyle1320** [comment]
It looks like this is due to the `collapseSourcemaps()` utility function not always properly testing for missing sourcemaps.

A workaround is to return `{code, map: null}`, as `null` and `undefined` sourcemaps are treated differently.

**Comment by jonathantneal** [comment]
That work-around is successful for me, but does it still mean there is either an issue with the docs or the app? If I’ve misunderstood the docs or the functionality is intended, I’ll close this, of course.

**Comment by kyle1320** [comment]
It definitely looks like a bug in the code, and not the documentation. Just returning the transformed code is very clearly supported -- there is existing code and test cases for it, in addition to the documentation -- it's just resulting in an error if source maps are turned on.

I'll take a shot at fixing this.
