### ISSUE TITLE
non-strict mode syntax error.

### ISSUE THREAD

**Issue by amapleaf** [rollup/rollup#2559]
- Rollup Version: 0.67.1
- Operating System (or Browser): Windows 10 v1803
- Node Version:10.13

### How Do We Reproduce?
-Install rollup with `npm i rollup`
-Use the two files as follows
-Run with `node rollup.js`

### Expected Behavior

If this is not a bug, please give the corresponding documentation (I did not find the corresponding instructions)

If this is a problem, I hope you can fix it, thanks.

### Actual Behavior

When I processed a js file with rollup and babel, I got a syntax error. I found this reason is to use the syntax that is not allowed in strict mode in the file, such as using delete to delete variables, using arguments as the function's parameter name, using reserved words as variable names, using the with statement, and so on. Then I tested and found that even if I only used rollup, I couldn't handle it successfully, and I still reported the error in the same place, but the error content changed a little. So is this a bug?

The rollup file as follows:

```
const rollup = require('rollup');

let iOptions = {
    input: "main.js",
    plugins: [
    ]
}

const oOptions = {
    format: 'cjs',
    strict: false,
    dir: './',
    file: 'out.js',
    sourcemap: false
}

async function build() {
    const bundle = await rollup.rollup(iOptions);
    await bundle.write(oOptions);
}

build();
```

And the main.js:
```
var public = 1;
console.log(public);
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
