### ISSUE TITLE
add support for BigInt literal

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2561]
### Feature Use Case

```js
const bigint = 0n;
```

### Feature Proposal

Don't throw `Error: Identifier directly after number`.

**Comment by LongTengDao** [comment]
@lukastaegert Hi~ Is this problem in process?

**Comment by lukastaegert** [comment]
As this is not an official language feature, you need the appropriate acorn plugin: https://github.com/acornjs/acorn-bigint

Does this work for you in Rollup@1.0?

**Comment by LongTengDao** [comment]
@lukastaegert 

Really thanks and sorry, I didn't know bigint is not standard yet, because chrome and nodejs had supported it. I tried in firefox and edge, indeed it's only supported by v8 privately.

And your suggest works (`rollup({ acornInjectPlugins: [ require('acorn-bigint') ] })`), thanks!

There is a bug with `**` operator. Never mind. I opened an issue there.

**Comment by LongTengDao** [comment]
Oh, the problem may be in rollup. I opened a new issue #2626 @lukastaegert
