### ISSUE TITLE
Automatic name detection for output.name

### ISSUE THREAD

**Issue by mcshaman** [rollup/rollup#2563]
### Feature Use Case
I am building a boiler plate for dev environments and I am trying out Rollup for my JS bundling. I want to be able to pass an array of input files into Rollup to output as individual files. However it is difficult to automate the output.name attribute when it encounters JS modules.

```
Error: You must supply output.name for IIFE bundles
```

### Feature Proposal
It feels like it should be possible to provide a pretty good guess at the name to use based on the modules export statement. If it is assigned to a variable before the export statement then suggest that otherwise use something else (e.g. filename) or throw and error.

While I admit I there may be implications I am not considering regarding other Rollup features that may make this difficult. However if it is possible minimal config is always a big plus!

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by difr** [comment]
sad, but true. its impossible to use several entry points if format is IIFE

**Comment by shellscape** [comment]
@difr would `@rollup/plugin-multi-entry` help?

**Comment by difr** [comment]
@shellscape nop. "output.name" is the key, its scalar.
well, its not so sad. there is workaround: several options objects in array )
may be even better, coz multi entries can have different globals and so on.
