### ISSUE TITLE
Not tree-shaking unused constants when `process.env.*` used

### ISSUE THREAD

**Issue by lukeed** [rollup/rollup#2569]
- Rollup Version: 0.67.3
- Operating System (or Browser): OSX 10.13
- Node Version: 10.12

### How Do We Reproduce?

[REPL](https://rollupjs.org/repl?version=0.67.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuJTVDbiUyRiUyRiUyMEFzJTIwc29vbiUyMGFzJTIwSSUyMHJlYWQlMjBmcm9tJTIwJ3Byb2Nlc3MuZW52JyU1Q24lMkYlMkYlMjBmcm9tJTIwYW55d2hlcmUlMjBlbHNlJTIwaW4lMjBhcHBsaWNhdGlvbiUyQyU1Q24lMkYlMkYlMjB0aGUlMjBBUEklMjBmcm9tJTIwJ21hdGhzJyUyMGdldHMlMjBpbmNsdWRlZCU1Q25jb25zdCUyMCU3QiUyMEZPTyUyMCU3RCUyMCUzRCUyMHByb2Nlc3MuZW52JTNCJTVDbiU1Q25jb25zb2xlLmxvZyglMjBjdWJlKDUpJTIwKSUzQiUyMCUyRiUyRiUyMDEyNSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMEFQSSUyMCUzRCUyMCU2MGh0dHAlM0ElMkYlMkZhcGkuZXhhbXBsZS5jb20lMkYlMjQlN0Jwcm9jZXNzLmVudi5CQVIlN0QlNjAlM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSh4KSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

The moment the main (or any sibling) application file pulls a variable from `process.env`, the `API` constant from `maths.js` (which is unused) makes its way into the output.

### Expected Behavior

The `API` constant should not be there.

### Actual Behavior

The `API` constant _is_ there, despite being unused.

Similarly, if the contents of `maths.js` is as follows:

```js
const BAR = process.env.BAR;
export const API = `http://api.example.com/${BAR}`;

export function cube(x) {
	return x * x * x;
}
```

... then _only_ `const BAR = ...` will be included in the final output.

**Comment by TrySound** [comment]
@lukeed Rollup does not know anything about `process` object. All reads from objects are considered as side effects. It always worked this way. If you want to change this behaviour try `treeshake.propertyReadSideEffects` option.
https://rollupjs.org/guide/en

**Comment by lukeed** [comment]
That did it, thank you~!

I'm aware that it didn't have to be `process.env.*` – that's just the shared object that I happened to discover this with.

Thanks!
