### ISSUE TITLE
acornInjectPlugins with acorn-jsx gives "plugin is not a function" error

### ISSUE THREAD

**Issue by c-johnson** [rollup/rollup#2573]
- Rollup Version: 0.67.3
- Operating System (or Browser): OSX / Chrome latest
- Node Version: v10.13.0

### How Do We Reproduce?

I'm trying to get the acorn-jsx parser plugin (https://github.com/RReverser/acorn-jsx) to work via acornInjectPlugins (an acknowledged experimental property). Could be a problem with Rollup, Acorn, or Acorn-JSX -- hard to tell from here, but this seems like the recommended standard path to implement Rollup-JSX support without additional tooling.

### Expected Behavior

It parses JSX and rolls up ES6 modules. 

### Actual Behavior

```
src/index.js → bundle.js...
[!] TypeError: plugin is not a function
TypeError: plugin is not a function
    at /Users/chris/home/proj/urbit/core/rollup/src/Graph.ts:203:66
    at Array.reduce (<anonymous>)
    at new Graph (/Users/chris/home/proj/urbit/core/rollup/src/Graph.ts:203:42)
    at Object.rollup (/Users/chris/home/proj/urbit/core/rollup/src/rollup/index.ts:169:17)
    at build (/Users/chris/home/proj/urbit/core/rollup/bin/rollup:1207:19)
    at /Users/chris/home/proj/urbit/core/rollup/bin/rollup:1981:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

```
// rollup.config.js
var acornJSX = require('acorn-jsx');

module.exports = {
  input: 'src/index.js',
  acorn: {
    plugins: { acornJSX: true }
  },
  acornInjectPlugins: [
    acornJSX
  ],
  output: {
    file: 'bundle.js',
    format: 'umd'
  }
};

// terminal

$ rollup -c

// src/index.js

var root = (
  <div>Hello!</div>
);

```

**Comment by guybedford** [comment]
Is `acornJSX` as provided here definitely a function? That's all this error seems to be catching.

**Comment by lukastaegert** [comment]
Also note that from the package.json file, acorn-jsx seems to require acorn@6 while the current version of rollup is still on acorn@5. Please try the 1.0 branch which uses acorn@6 and tell us if you still have issues via `npm install rollup/rollup#1.0`.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
