### ISSUE TITLE
experimentalPreserveModules opotion doesn't work with import *

### ISSUE THREAD

**Issue by kghost** [rollup/rollup#2576]
- Rollup Version:
- Operating System (or Browser): Debian 9 (WSL)
- Node Version: v11.2.0

### How Do We Reproduce?

https://github.com/kghost/rollup-bug

try build this repo

### Expected Behavior

compile all module to corresponding esm file.

### Actual Behavior

src/m1.js was totally omitted by tree shaking, result output is illegal.

**Comment by lukastaegert** [comment]
Thanks for the issue, this is definitely a bug. I will have a look.

**Comment by lukastaegert** [comment]
Fix at #2584
