### ISSUE TITLE
Plugin API: where are the dependencies?

### ISSUE THREAD

**Issue by ondras** [rollup/rollup#2578]
- Rollup Version: 0.67.7
- Operating System (or Browser): Linux
- Node Version: 8.14.0

### How Do We Reproduce?

My rollup plugin, [rollup-plugin-graph](https://github.com/ondras/rollup-plugin-graph/), used to leverage the `ongenerate` API to check dependencies of individual bundled modules. This API is no longer present and the new `generateBundle` call is not passed enough information to provide the requested functionality.

How can my plugin easily see all modules and their dependencies so I can visualize them as a graph?

**Comment by lukastaegert** [comment]
For getting more chunk information in the bundle (should also apply to generateBundle), please have a look at and comment on #2575.
For getting more module information, please have a look and comment on #2565.

Feedback for both is highly welcome at this stage as I want both of them to be in the next release.

**Comment by ondras** [comment]
Hi @lukastaegert ,

thanks for the extra-prompt response! The linked PRs look great. In particular, the graph exposing feature seems to be exactly the functionality I require.
