### ISSUE TITLE
ouput.paths doesn't apply to dynamic imports 

### ISSUE THREAD

**Issue by isidrok** [rollup/rollup#2579]
- Rollup Version: 0.67.3
- Operating System (or Browser): Linux
- Node Version: 10.14.1

### How Do We Reproduce?

Using the following configuration, bundle the file `index.js` and confirm the results inside `dist/index.js`

```js
// rollup.conifg.js
export default {
  input: './index.js',
  experimentalCodeSplitting: true,
  external: [
    '@some/module',
    '@another/module'
  ],
  output: {
    dir: './dist',
    format: 'es',
    paths: {
      '@some/module': '/some/module.js',
      '@another/module': '/another/module.js',
    }
  }
};

// index.js
import '@some/module'; 
import('@another/module');

// dist/index.js
import '/some/module.js'; // --> OK
import('@another/module'); // --> NO OK
```

### Expected Behavior

`output.paths` option should apply to all kind of imports.

### Actual Behavior

`output.paths` does not apply to `dynamic` imports.

**Comment by frank-dspeed** [comment]
@isidrok for me that works the problem must be the @ char if i see that right? also they are marked as external this makes not much sense

**Comment by isidrok** [comment]
Hi, those are external modules since they come from another build, what I'm trying to accomplish is to generate the paths configuration following certain naming conventions, and keep the imports with the name of the packages in order to avoid coupling with the file system.

Good point about the @, will check the code later.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by gabemeola** [comment]
@shellscape Just tested. This still seems to be an issue.

**Comment by gabemeola** [comment]
@shellscape REPL: https://repl.it/repls/EvergreenLostCircle

**Comment by marcusdarmstrong** [comment]
Can also confirm, this is still an issue.
