### ISSUE TITLE
minification

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#258]
Is there a way to minify ast before generating? Maybe possible to use plugin for this?

**Comment by Victorystick** [comment]
Rollup doesn't generate its bundles from an AST. It manipulates an underlying MagicString instance based on the original source that preserves information required to generate source maps. That's also why all comments are preserved exactly as the we're written. Rollup isn't really designed to enable minification during bundling. We recommend using UglifyJS or a similar tool as a postprocessing step.

**Comment by TrySound** [comment]
@Victorystick I just would like to use `bundle.write` method without own fs.writeFile calling

**Comment by Victorystick** [comment]
Can't you just use `{ code } = bundle.generate( ... )` and pass the resulting code to UglifyJS?

**Comment by TrySound** [comment]
@Victorystick Yes I can, but also need to write this code on disk. In this case code becomes less elegant as when we use `bundle.write`.

**Comment by TrySound** [comment]
[Here's my example](https://github.com/TrySound/case/blob/3.0/gulpfile.js#L33-L57)

**Comment by Victorystick** [comment]
I see. Unfortunately, minification is out of scope for Rollup itself, and I doubt we'll add support for a minification plugin. /cc @Rich-Harris

**Comment by TrySound** [comment]
@Victorystick Thanks

**Comment by Rich-Harris** [comment]
Yeah, we'd have to add something like a `postprocess` hook for plugins. But I'm not sure that it makes that much sense, because you'd essentially need to create the bundle twice – once with the uglify plugin and once without (unless you only wanted the minified version). Probably more efficient to keep the two steps separate.
