### ISSUE TITLE
Dependencies on @types should be dev dependecies

### ISSUE THREAD

**Issue by AllNamesRTaken** [rollup/rollup#2580]
- Rollup Version: 0.67.3
- Operating System (or Browser): Windows / Chrome
- Node Version: 10.10.0

### How Do We Reproduce?

- Create minial TS project with rollup.
- npm i -D @types/requirejs
- type require in a .ts file. This will point to Nodes Require and not to the requirejs Require.
- this is due to @types/node being a dependency instead of a dev dependency and thus getting included in the project using rollup
- moving this to a dev dependency would solve this issue.

### Expected Behavior
@types/node should be a dev dependency in package.json instead of a normal dependency and typing ```require``` in a typescript file should use the Require interface from @types/requirejs if installed and no other conflicting type is installed in the project.

### Actual Behavior
@types/node is a dependecy and typing ```require``` in a typescript file will use the NodeJs require even though @types/requirejs is installed.

**Comment by lukastaegert** [comment]
I am sorry, I first commented on your PR before reading the issue. See my comment there why this cannot be a dev dependency. I am open for suggestions, though.

**Comment by lukastaegert** [comment]
Note that looking at requirejs, it seems that you can use `requirejs` synonymous with their `require` probably just to avoid conflicts with node`s `require`.

**Comment by AllNamesRTaken** [comment]
Closing this since it cannot be changed without breaking changes.
