### ISSUE TITLE
Remove --experimentalDynamicImport from doc

### ISSUE THREAD

**Issue by ashi009** [rollup/rollup#2583]
- Rollup Version: 0.67.4
- Operating System (or Browser): macOS 10.14.1
- Node Version: 10.7.0

### How Do We Reproduce?

Include --experimentalDynamicImport in the options as documented https://rollupjs.org/guide/en#experimentaldynamicimport-experimentaldynamicimpor. 

### Expected Behavior

no warning

### Actual Behavior

> [!] Error: Unknown input option: experimentalDynamicImport. Allowed options: acorn, acornInjectPlugins, cache, chunkGroupingSize, context, entry, experimentalCacheExpiry, experimentalCodeSplitting, experimentalPreserveModules, experimentalTopLevelAwait, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, optimizeChunks, perf, plugins, preferConst, preserveSymlinks, shimMissingExports, treeshake, watch

### Root cause

https://github.com/rollup/rollup/commit/4d4ec4c8b0e5223d99b35efb6003928b8fe23524 has removed the flag. The document should be updated accordingly.

**Comment by lukastaegert** [comment]
Thanks for pointing this out, the option is removed now.
