### ISSUE TITLE
output.entryFileNames - accept a function?

### ISSUE THREAD

**Issue by PatNeedham** [rollup/rollup#2585]
### Feature Use Case
Is it possible for `entryFileNames` option to accept a function in addition to a string?

For background context, this is what my rollup.config.js looks like:
```
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';
import globals from 'rollup-plugin-node-globals';
import builtins from 'rollup-plugin-node-builtins';
import babel from 'rollup-plugin-babel';
import json from 'rollup-plugin-json';

module.exports = {
  experimentalCodeSplitting: true,
  optimizeChunks: true,
  external: […],
  input: [
    'src/components/Alert.jsx',
    'src/components/Anchor.jsx',
    'src/components/Button.jsx’,
    'src/components/Dropdown/index.jsx', // inside own folder
    ‘src/components/SomethingElse/index.jsx’,  // inside own folder
    …
  ],
  output: {
    dir: 'dist',
    format: 'esm'
  },
  plugins: [
    json(),
    nodeResolve({
      jsnext: true,
      preferBuiltins: false,
      extensions: ['.js', '.jsx', '.json'],
    }),
    commonjs({
      include: [
        'node_modules/**'
      ],
      exclude: [
        'node_modules/process-es6/**'
      ],
      namedExports: {
        'node_modules/downshift/node_modules/react-is/index.js': ['isForwardRef'],
        'node_modules/prop-types/index.js': [ ... ],
        'node_modules/react/index.js': [ ... ],
        'node_modules/react-dom/index.js': ['createPortal', 'findDOMNode', 'render']
      }
    }),
    babel({
      exclude: 'node_modules/**',
      presets: ['@babel/preset-env', 'react-app'],
      plugins: [
        ['syntax-trailing-function-commas', { loose: true }],
        ['@babel/plugin-proposal-class-properties', { loose: true }],
      ],
      runtimeHelpers: true,
    }),
    globals(),
    builtins(),
  ],
}
```

The default `[name].js` value for output.entryFileNames field this leads to a dist folder which contains the majority of the components necessary, except for those like Dropdown, SomethingElse, etc. the ones inside their own folders. However, they do appear inside files named like `index.js`, `index1.js`, `index2.js`, etc.

What can be done to make Rollup create output files like `Dropdown.js` and `SomethingElse.js` instead of `index.js` and `index.1.js`?

### Feature Proposal
If `entryFileNames` accepted a function, that would address this issue because I could then write something like
```
output: {
    dir: 'dist',
    entryFileNames: (filePath) => endsWithIndexJSX(filePath) ? `${getLastFolderName(filePath)}.js` : `[name].js`
    format: 'esm'
  },
```

**Comment by lukastaegert** [comment]
This is definitely doable but might take some time. Note that you can already achieve the same (though maybe not as elegantly) today by using the object form of `input`:

```
input: [
  Alert: 'src/components/Alert.jsx',
  Dropdown: 'src/components/Dropdown/index.jsx', 
  // if you actually do want it in a special sub-folder
  separate/SomethingElse: 'src/components/SomethingElse.jsx', 
  …
],
```

**Comment by jakearchibald** [comment]
The same feature would solve a slightly different use-case:

Most names should feature a `[hash]`, but some resources (like a service worker, or in some cases a favicon) should not, so a single rule doesn't quite work.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by lukastaegert** [comment]
For me, making the file name output properties functions is definitely a desirable feature which could also solve some other issues. Reopening it to track this.

**Comment by shellscape** [comment]
@lukastaegert I'd like to tackle this one but I'll need some direction on when and where the function should be called. I've tracked down where the options are fetched from config, but unsure on the best place to call the fn. We're also going to get requests for `async` functions I'm sure, so I'll have to take that into consideration.

**Comment by lukastaegert** [comment]
I would not go for async functions unless there is actual demand. Also there are hardly any places in the user facing options where you can do something async.

Also I think this should make all three `XYfileNames` options replaceable with functions.

As for the right place, yes, `renderNamePattern` could be a good choice. I assume the idea is that if `pattern` is a function, it is called to get the actual pattern? Sounds good!

**Comment by frank-dspeed** [comment]
I did implement it in #3658 and added a test it works also with assets and all other filds that support a pattern.
