### ISSUE TITLE
can iife format remove required options  moduleName?

### ISSUE THREAD

**Issue by LeeeeeeM** [rollup/rollup#2586]
now i need get an object from new Function  returns such as
```
function getObj(rollupCodeStr) {
        return new Function(`return ${rollupCodeStr}`)
}
var rollupCodeStr =  fs.readFileSync(`xxx.js`, 'utf8')   // rollupCodeStr is just like `(function () { return 'rollup' } ())`
var a = getObj(rollupCodeStr)
// common demand
```

but in rollup format option, it requires an moduleName and the code must write like this

{
      entry: `xxx`,
      dest: `xxx`,
      format: 'iife',
      moduleName: 'st',
      banner: ''
    }

```
function getObj(rollupCodeStr) {
        return new Function(`${rollupCodeStr}; return st`)
}
var rollupCodeStr =  fs.readFileSync(`xxx.js`, 'utf8')   // rollupCodeStr is just like `var st (function () { return 'rollup' } ())`
var a = getObj(rollupCodeStr)

```
very confused!
is there any solution on it? 

------------------------------------------------------env start--------------------------------------
package.json
    "rollup": "^0.43.0",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-buble": "^0.15.0",
    "rollup-plugin-commonjs": "^5.0.5",
    "rollup-plugin-eslint": "^3.0.0",
    "rollup-plugin-json": "^2.0.2",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-postcss": "^0.2.0",
    "rollup-plugin-replace": "^1.1.1",
    "rollup-plugin-uglify": "^1.0.1",
    "rollup-watch": "^2.5.0",
    "rollup-plugin-alias": "^1.4.0",

node -v  
    v10.2.1
system
    Ubuntu SMP Wed Oct 24 10:58:50 UTC2018 x86_64 x86_64 x86_64 GNU/Linux

------------------------------------------------------env end--------------------------------------

**Comment by LeeeeeeM** [comment]
it means  i want this 
```javascript
(function() {
  
   return `i love rollup`
})
```
but rollup bundles like this
```javascript
var rrr = (function() {
  
   return `i love rollup`
})
```

**Comment by TrySound** [comment]
Do you want something like this?
https://rollupjs.org/repl?version=1.6.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKDUpJTVDbiU1Q25jb25zdCUyMGxvZzUlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKDUpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyaWlmZSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by TrySound** [comment]
By the way you use very old version.

**Comment by LeeeeeeM** [comment]
> By the way you use very old version.

tree-shaking mode works

**Comment by TrySound** [comment]
What? I meant you have very old version of rollup. `"rollup": "^0.43.0",`. It's 1.6 now.

> tree-shaking mode works

**Comment by LeeeeeeM** [comment]
![image](https://user-images.githubusercontent.com/35845083/54328246-30b0e600-4648-11e9-8800-9665b3c9b91d.png)
holy! it runs well in repl，poisonous in configfile

**Comment by lukastaegert** [comment]
The config file format has changed quite a bit since 0.43, the documentation on the website is always up to date: https://rollupjs.org/guide/en#output-name
