### ISSUE TITLE
need a hook that after all bundled files been writen

### ISSUE THREAD

**Issue by scrollbar-ww** [rollup/rollup#2589]
### Feature Use Case
i am coding a html plugin，it need calcute all output files hash，and put it in part of the file name.
using generateBundle hook, i can get output script file's code from the 'bundle' option ，
but cannot get other types of files，such as .css file writen by postcss plugin.

### Feature Proposal
a hook named afterGenerate()，and with the same arguments of generateBundle, will be nice.

thanks a lot

**Comment by isidrok** [comment]
If the file was written with `this.emitAsset` it should appear in the `generateBundle` hook (if I remember correctly), maybe you should open an issue in the postcss plugin to use that API. Nevertheless that would be a nice hook to have.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
