### ISSUE TITLE
Different import order produces different bundles with missing imports

### ISSUE THREAD

**Issue by bmblb** [rollup/rollup#2595]
- Rollup Version: 0.67.4
- Operating System (or Browser): Window 10 1809, Ubuntu 16.04 LTS
- Node Version: 8.9.4

Hello.

Recently during development process we faced problem with bundle produced by rollup missing some imports. It turned out to be related to the order of imports. I struggle to understand what is wrong them.

### How Do We Reproduce?

I made a simple slim application that shows the problem, please refer to this repo: https://github.com/bmblb/rollup-bug Steps to reproduce problem are described there.

### Expected Behavior
`examples/drag/app.module.js` contains `import Store from....`

### Actual Behavior
required import is missing from the bundle

I tried to debug rollup build process, and when chunks were rendered into output I noticed, that import statements looked not like I expected. My expectation was single chunk for single import, but 3 chunks I got were:
1. `//import Util from '../../../lib/Tool/util/Util.js';\n`
2. `//import Store from import Store from '../../../lib/Tool/data/Store.js';\nimport Task from './Task.js';\n`
3. `\n\n`

**Note**: among these 3 imports first 2 are commented and `import Task` is not.
That pointed me to idea to move task import to be first and output bundle was correct that time.

So it looks like rollup struggles to process imports in some cases, while browser can successfully process them.

**Comment by lukastaegert** [comment]
I believe you created this problem yourself. Looking into your rollup config, there is this innocent looking plugin. It even includes an explanation what you are doing. Basically, you are commenting out your own imports. Remove the plugin and everything works as expected.

```js
replace({
    patterns : [
        {
            exclude   : ['node_modules/**'],
            transform : function(code) {
                // We don't want to end up with all library classes in our rollup so we comment them
                return code.replace(/(import .*(lib\/Tool).+?(\.js';))/g, '//$1');
            }
        }
    ]
}),
```

**Comment by bmblb** [comment]
I removed `replace` plugin and did manually what it supposed to do - commented first two imports
```
/////  TaskStore.js

// import Util from '../../../lib/Tool/util/Util.js';
// import Store from '../../../lib/Tool/data/Store.js';
import Task from './Task.js';

export default class TaskStore extends Store {
```
This rolled up to same code, missing commented import:
```class Task extends Model {} // <-- correct

// import Util from '../../../lib/Tool/util/Util.js'; // <-- unexpected, we miss one import

class TaskStore extends Store { // <-- correct
```

There should be a different way to solve our problem indeed, but nevertheless, it still looks like output is inconsistent, unpredictable.
If commented import is invalid - why one is still present in the bundle?
If commented import is valid - why one is missing?

When we rollup code we expect it will be assembled as is, replacing imports with actual classes, and keep commented code. why should it be removed at all?

Further experiments with imports show that commented strings coul be just lost. Consider this usecase:
```
//// TaskStore.js
/* eslint-disable */
/* Here goes a long comment explainig smth */
import Util from '../../../lib/Tool/util/Util.js';
import Store from '../../../lib/Tool/data/Store.js';
import foo from '../../../lib/Tool/data/foo.js';

//// result
class Task extends Model {}

/* eslint-disable */ // <-- only one comment left. maybe it is irrelevant, maybe is. I think rollup should leave comments intact

class TaskStore extends Store {
```

**Comment by lukastaegert** [comment]
I am sorry, I must have misunderstood your issue. Comments follow indeed a very strict logic in Rollup but it was not designed to do what you did. If rollup would just leave all comments in place all the time, then in the face of tree-shaking, rollup would often produce huge chunks of meaningless comments in the output. Instead the assumption is that comments are tied to actual code where all non-code lines before a line of code and everything on the same line as some code is kept or removed together with that code. This works very well for annotations. I am not sure why you comment out imports and rely on the comments to be present but maybe there is a better way to achieve what you are after? Import statements are usually removed so the preceding comments are removed as well. Why don’t you just mark the Store import as external? This would just leave the import statement in your code and you could do with it as you please after bundling.

**Comment by lukastaegert** [comment]
BTW comments starting in the first line of output are always retained as well.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
