### ISSUE TITLE
Throw errors when accessing module ids on the plugin context before graph is complete

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#2598]
### Expected Behavior / Situation
Rollup should throw an error if `this.moduleIds` is accessed before all modules are known. `this.getModuleInfo` should throw an error if the module information could be incomplete.

### Actual Behavior / Situation
Rollup will return no modules or only a partial set of module ids when `this.moduleIds` is accessed before all modules have been loaded. It is unclear if `this.getModuleInfo` is reliable in such a situation.

### Modification Proposal
See above

**Comment by shellscape** [comment]
@lukastaegert is this still valid? Looks like #2565 is related, and merged.

**Comment by lukastaegert** [comment]
Actually I’m no longer sure we want this. Having partial information can still be useful.
