### ISSUE TITLE
v0.68 version breaks build pipeline

### ISSUE THREAD

**Issue by nanomosfet** [rollup/rollup#2599]
https://travis-ci.org/moment/moment/jobs/468717594

**Comment by lukastaegert** [comment]
It would be really nice if you supplied some more information when posting an issue. We have an issue template for a reason and you know your setup probably better than we do.

Nevertheless I had a look at your test setup. The reason the new build breaks your pipeline is that you make assumptions about the UMD header created by rollup which was slightly simplified. More precisely, some braces were removed (which now cause your syntax error). Removing the opening braces before `function` in these places should fix your pipeline:
- https://github.com/moment/moment/blob/b8f4fe2bf5bb9022655505d59b62aef12bc540d6/templates/default.js#L5
- https://github.com/moment/moment/blob/b8f4fe2bf5bb9022655505d59b62aef12bc540d6/templates/locale-header.js#L6
- https://github.com/moment/moment/blob/b8f4fe2bf5bb9022655505d59b62aef12bc540d6/templates/test-header.js#L6

Note however that it may be dangerous to rely on a specific UMD header format as we cannot guarantee that e.g. line-breaks stay consistent in minor versions if there is not change in functionality. Your setup looks very complicated and it looks like you are actually trying to optimize your UMD headers yourself. It might make more sense to do these optimizations upstream in Rollup instead.

**Comment by nanomosfet** [comment]
Thank you for looking into this even after my lack of information! I will go ahead and try these changes you suggested. 

I will look into making the optimizations upstream in Rollup. 

Thank you again

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
