### ISSUE TITLE
Async plugins

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#260]
Is there a way to use asynchronous in plugins? rollup could detect promise returned from plugin like
```js
export default function string (opts) {
	return {
		transform (code, id) {
			if (filter(id)) {
				if (opts.someAsyncOpt) {
					return new Promise(function (code) {
						resolve(code);
					});
				}
				return code;
			}
		}
	};
}
```

**Comment by Rich-Harris** [comment]
It could be done, certainly. There's a slight performance penalty associated with async-ifying transforms since you basically need to wrap everything in a `Promise.resolve()` – do you have a specific use case in mind?

**Comment by TrySound** [comment]
@Rich-Harris https://github.com/JohnPostlethwait/stringify accepts minificators for code. It make sense in browser. But minificators api can be async ([cssnano](https://gitter.im/ben-eb/cssnano) is async)
