### ISSUE TITLE
Proposal: Support Database Backend for input output cache

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#2601]
### Feature Use Case
I was the first person using rollup with 9TB data it was not working as expected. I needed to queue the rollup process and manage the parts it should rollup and then external join the files.

### Feature Proposal
Solution would be to allow rollup to form the module ast in a database as also the result 
in a query able database. I would prefer and Suggest Couchbase! 

- Needs alternate input method then filesystem most best a stream
- hooks to stream process state to DB and also read from it
- output to stream that can be writen where ever you want.

**Comment by frank-dspeed** [comment]
#2421 - is related

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by lukastaegert** [comment]
There are plans to add a plugin API for cache providers. No ETA on this but if we succeed, this should support any backend that people write a plugin for, including databases.
