### ISSUE TITLE
Docs: Explain That Multiple Resolve Plugins Are Supported

### ISSUE THREAD

**Issue by bdkjones** [rollup/rollup#2605]
Documentation Is:

- [X] Missing
- [X] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

I'm attempting to use Rollup in a project that contains both `node_modules` and `bower_components` folders. I'd like to know if Rollup supports multiple `resolve` plugins such that I can pass both `node-resolve` and `bower-resolve` to have Rollup try both to resolve import statements.

The documentation does not currently indicate if multiple resolve plugins are allowed.

### Your Proposal for Changes

Ideally, Rollup supports multiple resolve plugins and uses them in the order I pass them in my config file. For example, if I pass `node-resolve` first, Rollup would try to resolve an import path using that plugin and, if unsuccessful, move on to `bower-resolve`, which I pass second in my config file.

If Rollup does not support multiple resolve plugins, it would be good to indicate in the docs that only one can be passed at a time.

Finally, I realize this is an edge case. I am incorporating Rollup into an app and must support projects that use both bower_components and node_modules, sometimes both in the same project for legacy reasons.

**Comment by tivac** [comment]
This is supported, the docs for the [`resolveId`](https://rollupjs.org/guide/en#resolveid) plugin hook explicitly mention deferring to other resolution plugins if an `importee` can't be resolved.

It could be called out more clearly, potentially, but I'm not sure what you'd want that to look like.

**Comment by bdkjones** [comment]
Ah, excellent.

Since using third-party libraries is a big part of most workflows, it might be good to call this out more explicitly in the section that most people are going to visit for it: 
https://rollupjs.org/guide/en#tools

A short note after the `node-resolve` example explaining that *multiple* `resolve` plugins can be used and will run in the order passed would help folks that are stuck in the middle of a migration from Bower to npm. I don't think these folks will see the note in the "Hooks" section because they're not writing plugins themselves and thus aren't concerned with that API.

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
