### ISSUE TITLE
Regression: tree shaking wrong when var declaration+assignment is inside a conditional

### ISSUE THREAD

**Issue by nifgraup** [rollup/rollup#2606]
- Rollup Version: 0.68.1
- Operating System (or Browser): Linux
- Node Version: v8.9.3

### How Do We Reproduce?

test.js
```
// example 1
switch (test) {
  case 1:
    var hoisted = true;
  case 2:
    if (hoisted) console.log('Went also through  case 1.');
}

// example 2
if (x) {
  var h2 = true;
}
if (h2) console.log('x is true');

```
./bin/rollup --format cjs test.js

### Expected Behavior
no tree shaking

### Actual Behavior
```
'use strict';

// example 1
switch (test) {
  case 1:

  case 2:
    console.log('Went also through  case 1.');
}
console.log('x is true');

```
Regression point 187a256576cb56aa104b79aba0222031ac82a6de

**Comment by lukastaegert** [comment]
This was fixed via #2607 in Rollup@0.68.2
