### ISSUE TITLE
Can't combine rollup-plugin-alias with rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by StevenLiekens** [rollup/rollup#2609]
- Rollup Version: 0.68.1
- Operating System (or Browser): Windows 10
- Node Version: 11.3.0

### How Do We Reproduce?
[Vue.js docs](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only) have a section on how to use `rollup-plugin-alias` to change which module gets imported when doing `import Vue from 'vue';`.

#### package.json
```js
{
  "dependencies": {
    "vue": "^2.5.21"
  },
  "devDependencies": {
    "rollup": "^0.68.1",
    "rollup-plugin-alias": "^1.5.1",
    "rollup-plugin-node-resolve": "^4.0.0"
  },
  "scripts": {
    "build": "rollup -c"
  }
}
```

#### rollup.config.js
```js
import alias from 'rollup-plugin-alias';
import resolve from 'rollup-plugin-node-resolve';

export default {
    input: 'src/main.js',
    output: {
        file: 'dist/bundle.js',
        format: 'esm'
    },
    plugins: [
        alias({
           'vue': 'vue/dist/vue.esm.js'
        }),
        resolve()
    ]
};
```

#### src/main.js
```js
import Vue from 'vue';

const app = new Vue({
    el: '#app',
    data: {
        message: 'Hello Vue!'
    }
});
```

Now do `npm run build`

### Expected Behavior

rollup-plugin-alias rewrites
`import Vue from 'vue';` -> ` import Vue from 'vue/dist/vue.esm.js';`

rollup-plugin-node-resolve resolves
`'vue/dist/vue.esm.js'` -> `'../node_modules/vue/dist/vue.esm.js'`

### Actual Behavior

rollup-plugin-alias rewrites
`import Vue from 'vue';` -> ` import Vue from 'vue/dist/vue.esm.js';`

rollup-plugin-node-resolve is skipped

Rollup crashes
> src/main.js → dist/bundle.js...
[!] Error: Could not load vue/dist/vue.esm.js (imported by D:\src\repro\src\main.js): ENOENT: no such file or directory, open 'vue/dist/vue.esm.js'

**Comment by lukastaegert** [comment]
I am afraid rollup is behaving exactly as it should i.e. once a plugin resolves an ID, it is not automatically passed to other plugins to be resolved again. Which means that the Vue documentation is and probably has been for quite some time wrong and you should actually open an issue there. Cf. also this issue: rollup/rollup-plugin-alias#41

What would probably work is supplying the alias to the plugin the same way it is supplied for parcel. Would be nice to get some feedback if it works and if so, if someone would finally update the Vue documentation.

**Comment by StevenLiekens** [comment]
> What would probably work is supplying the alias to the plugin the same way it is supplied for parcel. Would be nice to get some feedback if it works and if so, if someone would finally update the Vue documentation.

I tried with a relative path, but it didn't work. Unlike with Parcel, the path seems to be relative to the source file that contains the import statement, not the package.json file.

What does work is using `path.resolve` to make the resolved ID absolute.

```js
import path from 'path';
import alias from 'rollup-plugin-alias';
import resolve from 'rollup-plugin-node-resolve';

// ...

plugins: [
    alias({
        vue: path.resolve('./node_modules/vue/dist/vue.esm.js')
    }),
    resolve()
]
```

But now I'm thinking I should't use rollup-plugin-alias for this. Maybe I'll use something like [patch-package](https://www.npmjs.com/package/patch-package) to set the `"module"` field of `node_modules/vue/package.json` to what I want it to be.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
