### ISSUE TITLE
output.sourcemapFile doesn't work, it seems always to use process.cwd().

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2610]
- Rollup Version: 0.66.6
- Operating System (or Browser): No relationship
- Node Version: 10.9.0

### How Do We Reproduce?

```
/build.js # output: { sourcemap: true, sourcemapFile: '/src/index.min.js' }
/src/index.js
```

### Expected Behavior

```json
{ "sources": ["index.js"] }
```

### Actual Behavior

```json
{ "sources": ["src/index.js"] }
```

Just same as the result without using `output.sourcemapFile`, the relative base path is always `process.cwd()`.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
