### ISSUE TITLE
make empty sourcemaps

### ISSUE THREAD

**Issue by rzkhosroshahi** [rollup/rollup#2615]
- Rollup Version: 1.0.0
- Operating System (or Browser): chrome macOS
- Node Version: 10.8.1

### How Do We Reproduce?
I have an issue with rollup even before the last update. I'm making source maps for declaration files and also for esm,cjs, etc files. but for modules, source maps generate empty and invalid files.
something like this:
`
{
  "version": 3,
  "file": "index.module.js",
  "sources": [],
  "sourcesContent": [],
  "names": [],
  "mappings": ";;;;;;;;;..........
`
You can see my project [in this repo](https://github.com/rzkhosroshahi/react-jalali-datepicker/tree/develop) on develop branch.

**Comment by kekeqy** [comment]
I have the same problem.It is normal when there are not many code files, but when there are many code files, it will generate empty.

**Comment by lukastaegert** [comment]
Hi @rzkhosroshahi I had a look at your repo and to me it seems the core issue is that you have a transformation that throws away all sourcemaps:

```js
// rollup.config.js
//...

export default {
  // ...
  plugins: [
    builtins(),
    {
      name: "replace moment imports",
      transform: code => ({
        code: code.replace(/import\s*\*\s*as\s*moment/g, "import moment"),

        // That's the problem! This will mark all source files as not having a sourcemap
        // which means the resulting bundle cannot have a sourcemap as well
        map: { mappings: "" }, 
      }),
    },
    // ...
  ],
  // ...
};
```

The "proper" solution would be to generate a sourcemap for the transformation but I understand this is quite a bit of work for an ad-hoc plugin. My recommendation would be instead to use `map: null`, which indicates that your transformation does not move code around. To make sure this is actually the case, you could just insert enough whitespace:

```js
code.replace(/import\s*\*\s*as\s*moment/g, "import      moment")
```
