### ISSUE TITLE
rollup wanting to generate multiple chunks

### ISSUE THREAD

**Issue by rbnlffl** [rollup/rollup#2616]
- Rollup Version: 1.0.0
- Operating System (or Browser): macOS 10.14.2
- Node Version: node v10.15.0, yarn v1.12.3

### How Do We Reproduce?
You can check out https://github.com/rbnlffl/mehrsprachig, run `yarn` and then `yarn start`.

### Expected Behavior
With rollup v0.68.0, the bundle would get generated, I expect the same to happen with v1.

### Actual Behavior
I get the following error, even though I don't generate multiple chunks and have an `output.file` specified.
```js
$ rollup -c

src/mehrsprachig.js → dist/mehrsprachig.esm.js...
[!] Error: You must set either output.file for a single-file build or output.dir when generating multiple chunks.
Error: You must set either output.file for a single-file build or output.dir when generating multiple chunks.
    at error (/Users/robin/Sites/mehrsprachig/node_modules/rollup/dist/rollup.js:3597:30)
    at normalizeOutputOptions (/Users/robin/Sites/mehrsprachig/node_modules/rollup/dist/rollup.js:18264:13)
    at generate (/Users/robin/Sites/mehrsprachig/node_modules/rollup/dist/rollup.js:18040:37)
    at Object.write (/Users/robin/Sites/mehrsprachig/node_modules/rollup/dist/rollup.js:18143:28)
    at /Users/robin/Sites/mehrsprachig/node_modules/rollup/bin/rollup:1079:80
    at Array.map (<anonymous>)
    at /Users/robin/Sites/mehrsprachig/node_modules/rollup/bin/rollup:1079:42
```

Maybe my configuration is wrong? I've been using the new syntax for a while now, but it could very well be possible that I've missed something that just got deprecated. Here's my `rollup.config.js`:

```js
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import { uglify } from 'rollup-plugin-uglify';
import { eslint } from 'rollup-plugin-eslint';
import pkg from './package.json';

// two separate objects for two separate outputs
// firstly esnext for bundlers, then umd for browsers
export default [{
    input: 'src/mehrsprachig.js',
    plugins: [
        eslint(),
        resolve(),
        commonjs()
    ],
    output: {
        dir: 'dist',
        sourcemap: true,
        file: pkg.module,
        format: 'es'
    }
}, {
    input: 'src/mehrsprachig.js',
    plugins: [
        eslint(),
        resolve(),
        commonjs(),
        babel(),
        uglify()
    ],
    output: {
        dir: 'dist',
        sourcemap: true,
        name: 'Mehrsprachig',
        file: pkg.main,
        format: 'umd'
    }
}];
```

The file I'm bundling (and transpiling) uses `import`s, but none of both are dynamic. Here the source:
```js
import 'whatwg-fetch';
import 'promise-polyfill/src/polyfill';

class Mehrsprachig {
    constructor({
        language = 'browser',
        sources = {
            'de': '/api/de',
            'en': '/api/en'
        },
        selector = '[data-mehrsprachig]'
    } = {}) {
        this.sources = sources;
        this.language = language;
        this.selector = selector;
        this.locales = {};
        this.nodes = [];

        this.bootstrap();
    }

    async setLanguage(language) {
        this.language = language;

        if (!this.locales[this.language]) {
            await this.getLocale();
        }

        localStorage.setItem('mehrsprachig', language);

        this.localize();
    }

    async bootstrap() {
        this.determineLanguage();
        this.nodes = document.querySelectorAll(this.selector);

        await this.getLocale();
        this.localize();
    }

    async getLocale() {
        const req = await fetch(this.sources[this.language]);
        const res = await req.json();

        this.locales[this.language] = res;
    }

    localize() {
        for (const node of this.nodes.values()) {
            const values = node.dataset.mehrsprachig.replace(/ /g, '').split(',');

            for (const item of values) {
                if (item.includes('=')) {
                    // when an item be a attibute=value pair
                    const attribute = item.split('=')[0];
                    const value = item.split('=')[1];

                    node.setAttribute(attribute, this.getLocalized(value));
                } else {
                    // when it be a single value item
                    // sometimes it really do be like dat
                    node.textContent = this.getLocalized(item);
                }
            }
        }

        document.documentElement.setAttribute('lang', this.language);
    }

    determineLanguage() {
        if (this.language === 'browser') {
            this.language = navigator.language.toLowerCase();
        }

        if (localStorage.getItem('mehrsprachig')) {
            this.language = localStorage.getItem('mehrsprachig');
        }
    }

    getLocalized(value) {
        const properties = value.split('.');
        let localized = this.locales[this.language];

        for (const property of properties) {
            localized = localized[property];
        }

        return localized;
    }
}

export default Mehrsprachig;
```

**Comment by rbnlffl** [comment]
Whoops: I've defined an `output.dir` _and_ an `output.file`. My bad! Only defining `output.file` and deleting the other did it for me.

**Comment by andybelldesign** [comment]
Just stopping by to let you know that this helped me in an equally whoops situation. Cheers @rbnlffl!

**Comment by gangsthub** [comment]
I solved it by passing the option

```js
{
  inlineDynamicImports: true,
}
```

I was indeed using dynamic imports.

**Comment by adi518** [comment]
> I solved it by passing the option
> 
> ```js
> {
>   inlineDynamicImports: true,
> }
> ```
> 
> I was indeed using dynamic imports.

Seems pretty strange. I wouldn't say that's the cause of your issue.

Anyway, I just had to deal with this API scheme error as well and what fixed it was merely renaming `file` to `dir` and hard-coding the build directory, which is `dist` in most cases. It seems Rollup wanted to decouple directory path from filename.

**Comment by lukastaegert** [comment]
The logic is very simple: If the output would contain more than one JavaScript chunk, using `file` will throw an error because if there is more than one file, they need different names 😜. If you use `dir`, Rollup will look at the various naming patterns, e.g. `entryFileNames`, to decide how files are named.
On the other hand, `dir ` can always be used even if there is a single chunk.

If the reason for having multiple chunks is the use of dynamic imports, which create additional chunks by default, then `inlineDynamicImports` would fix it.

**Comment by 8nix** [comment]
https://rollupjs.org/guide/en/#inlinedynamicimports

**Comment by dan-lovelace** [comment]
If anyone using Vite stumbles upon this, I had to set `dir: undefined` in `rollupOptions` like this:

```js
export default defineConfig({
  build: {
    assetsDir: "",
    rollupOptions: {
      input: "src/index.ts",
      output: {
        file: "../../dist/content-script.js",
        dir: undefined,
      },
    },
  },
});
```

**Comment by iDestin** [comment]
> If anyone using Vite stumbles upon this, I had to set `dir: undefined` in `rollupOptions` like this:
> 
> ```js
> export default defineConfig({
>   build: {
>     assetsDir: "",
>     rollupOptions: {
>       input: "src/index.ts",
>       output: {
>         file: "../../dist/content-script.js",
>         dir: undefined,
>       },
>     },
>   },
> });
> ```

i get this error in `vite 4.1.1`

`The "path" argument must be of type string. Received undefined`

**Comment by Polyhistor** [comment]
It's a bit counter intuitive to set entry file name as the output file name!... the output dir property is also set, which makes setting the file property impossible...

**Comment by HduSy** [comment]
> If anyone using Vite stumbles upon this, I had to set `dir: undefined` in `rollupOptions` like this:
> 
> ```js
> export default defineConfig({
>   build: {
>     assetsDir: "",
>     rollupOptions: {
>       input: "src/index.ts",
>       output: {
>         file: "../../dist/content-script.js",
>         dir: undefined,
>       },
>     },
>   },
> });
> ```

Thanks! your code "dir: undefined" really solved my problem,  but why, it's a so strange problem.
