### ISSUE TITLE
Simplify RollupOptions type

### ISSUE THREAD

**Issue by Kinrany** [rollup/rollup#2621]
Found this after trying to split my `rollup.config.ts` export in two:

```diff
 // rollup.config.ts
 import rollup from 'rollup';
 
-export const rollupOptions: rollup.RollupOptions = { /* all options */ };
+export const inputOptions: rollup.InputOptions = { /* input options */ };
+export const outputOptions: rollup.OutputOptions = { /* output options */ };
```

```diff
 // main.ts
 import rollup from 'rollup';
-import { rollupOptions } from './rollup.config.ts';
+import { inputOptions, outputOptions } from './rollup.config.ts';
 
-rollup.rollup(rollupOptions);
+rollup.rollup(inputOptions)
+  .then(bundle => bundle.write(outputOptions));
```

### Expected Behavior

No error, simple `RollupOptions` interface in [`types.d.ts`](https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts):

```ts
export interface RollupOptions extends InputOptions {
  outputOptions?: OutputOptions;
}
```

### Actual Behavior

Error:

```
Argument of type 'InputOptions' is not assignable to parameter of type 'RollupOptions'.
  Types of property 'cache' are incompatible.
    Type 'false | RollupCache | undefined' is not assignable to type 'RollupCache | undefined'.
      Type 'false' is not assignable to type 'RollupCache | undefined'.
```

Actual interface:

```ts
export interface RollupOptions extends InputOptions {
	cache?: RollupCache;
	input: string | string[] | { [entryName: string]: string };
	output?: OutputOptions;
}
```

### Modification Proposal

`input` can be removed because `RollupOptions['input']` and `InputOptions['input']` are exactly the same type.

`cache` can be removed too, but it might be a breaking change:  
`RollupOptions['cache']` is just `RollupCache | undefined`, while `InputOptions['cache']` also allows `false`.

**Comment by Kinrany** [comment]
By the way, congrats on 1.0.0 release! 😄

**Comment by lukastaegert** [comment]
Thanks and thanks a lot for catching this! In fact, the `cache` value for `InputOptions` was correct to allow `false`. These small fixes are highly appreciated and very helpful!

**Comment by Kinrany** [comment]
Yay! I'll make sure to post again if I find anything else :D
