### ISSUE TITLE
Rollup metadata is not available in options hook

### ISSUE THREAD

**Issue by AgronKabashi** [rollup/rollup#2624]
According to the documentation and #2394, this.meta should be available in all plugin hooks. This does not seem to be the case for `options` however.

- Rollup Version: >=0.65, 1.0
- Operating System (or Browser): MacOS Mohave 10.14.2
- Node Version: 9.3 & 10.3

### How Do We Reproduce?

```js
// Save this as test.config.js
export default {
  input: "test.config.js",
  output: {
    file: "build.js",
    format: "cjs"
  },
  plugins: [
    {
      resolveId () {
        console.log("ResolveId:", this.meta);
      },

      buildStart () {
        console.log("BuildStart:", this.meta);
      },

      options () {
        console.log("Options:", this.meta);
      }
    }
  ]
};
```

Run with `npx rollup -c test.config.js`

Output:
```bash
Options: undefined
BuildStart: { rollupVersion: '1.0.0' }
ResolveId: { rollupVersion: '1.0.0' }
```

### Expected Behavior
The option hook should have access to the `this.meta` object and output the proper rollup version.

### Actual Behavior
The option hook doesn't seem to have the proper context and thus `this.meta` is unavailable.

**Comment by lukastaegert** [comment]
Fix at #2642
