### ISSUE TITLE
Add a "reason" param to watchChange hook 

### ISSUE THREAD

**Issue by tivac** [rollup/rollup#2630]
### Expected Behavior / Situation

I'd like the `watchChange` hook to tell me **why** the file changed. 

### Actual Behavior / Situation

Currently the only thing it passes is *which* file changed. That's important, but not the whole story. It means my [rollup plugin](https://github.com/tivac/modular-css/blob/master/packages/rollup/rollup.js#L63-L72) could leave deleted files hanging around because I haven't written code to check the filesystem on every change and ensure a file exists (because that sounds slow & gross).

### Modification Proposal

The `watchChange` signature could be something along the lines of:

`(id: string, details: watchChangeDetails) => void`

where `watchChangeDetails` would probably start out as:

```
{
  // One of "added", "modified", "deleted", I dunno the TS notation for that sorry
  reason: string,
}
```

but could later encompass more fields if they ended up being useful.

**Comment by lukastaegert** [comment]
I guess we could just forward the reason provided by either `fs.watch` or `chokidar` though of course this could lead to inconsistencies depending on the use of chokidar. For `fs.watch`, this would be either `change` or `rename` (where the latter includes moving and deleting files) while for chokidar, many more values are possible. Would this help? Or should we normalize the chokidar types to what `fs.watch` does? I would rather not want to do it the other way around and do this analysis even if it might not be needed.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
