### ISSUE TITLE
how rollup package some files into one file

### ISSUE THREAD

**Issue by MuYunyun** [rollup/rollup#2637]
I want to use rollup to parcel the entry file `index.js`, it look like this:

```js
// index.js
var a = require("../a");
var b = require("../b");
const obj = {a, b}
module.exports = obj;
```

and now I don't know how to parcel a.js and b.js into one file, can anyone help.Thanks.

when I run the script as follow,

```js
const result = await rollup({
  input: path.resolve(rootPath,  'index.js'),
})
await result.write({
  file: `test.js`,
  format: 'cmd',
})
```

the result it package is still the same as firstly(The result I want is the content of a and b is in the test.js)

```js
// test.js
var a = require("../a");
var b = require("../b");
const obj = {a, b}
module.exports = obj;
```

**Comment by TrySound** [comment]
@MuYunyun rollup does not support commonjs out of the box. Use esm or https://github.com/rollup/rollup-plugin-commonjs

**Comment by MuYunyun** [comment]
@TrySound Thanks, it solve my problem perfectly!

The programme is written in typescript, and it's compiled to JavaScript with the module of ES5, so it seems it must use `rollup-plugin-commonjs`. Isn't It redundant in the process I describe. Is there some      ways to optimize the process?
