### ISSUE TITLE
Confusing docs about command line flags

### ISSUE THREAD

**Issue by everdimension** [rollup/rollup#2639]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The section about [command line flags](https://rollupjs.org/guide/en#command-line-flags)

I see a list of options which I expect to be exhaustive. I'm looking for a `--watch` option. It's not there. Hmm, does rollup not provide a watch option out of the box? 🤔 

But then... After the list, there's a paragraph that says:

> In addition, the following arguments can be used:

God this is so confusing. "*In addition*"? Why didn't these options deserve to be in the main list?

### Your Proposal for Changes

If these options are indeed somehow fundamentally different, I'd love to see the docs making it clear. Right now it just looks like a joke on the reader.
If not, they should be in the main list and the list should be exhaustive.

**Comment by lukastaegert** [comment]
Thanks for the feedback, please have a look at #2641 for my attempt on improving this.

**Comment by everdimension** [comment]
The PR looks great! Much more clear.
