### ISSUE TITLE
Add pure-like native function check for tree shake

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2644]
I saw there is a list for native pure function in rollup source code (`src/ast/nodes/shared/pureFunctions.ts`), it's useful for tree shake. Without that (and assumption of set/get did nothing side effect, native methods did not be overrided, etc), we can almost shake nothing, because every lib has it's initialization part which may use many native methods, and get/set many properties.

But there are some functions, not pure, but pure like. Pure functions should do nothing change to arguments, when pure-like functions (I don't know how to name them usually) do something change to arguments, but no side effect, so if the returned value of pure-like function is not used, it can also be considered to be shaked. Like: `Object.assign` `Object.freeze`...

Without this feature, so many external modules initialization part will leave...

### Feature Use Case

module.js:

```js
const object = Object.freeze(Object.assign(Object.create(null), { a:1, b:2 }));

export function f ( ) { return object; }

export function g ( ) { }
```

input.js:

```js
import { g } from './module.js';

console.log(g);
```

### Feature Proposal

Output this:

```js
function g ( ) { }

console.log(g);
```

Not:

```js
Object.freeze(Object.assign(Object.create(null), { a:1, b:2 }));

function g ( ) { }

console.log(g);
```

**Comment by LongTengDao** [comment]
@lukastaegert Hi! Sorry to trouble you again. Is this feature I mentioned possible and easy to implement? Or there could be a custom api for pure/pure-like functions?

**Comment by leeoniya** [comment]
have you seen https://github.com/rollup/rollup/pull/2429?

**Comment by LongTengDao** [comment]
> have you seen #2429?

Oh, that solution is better, thank you!
