### ISSUE TITLE
Need help to understand why the Javascript ESM package is not working in non ejected create react app

### ISSUE THREAD

**Issue by kopax** [rollup/rollup#2646]
## Use esm in create-react-app cause issue

I am building a tiny package and I use rollup to produce an **esm module**.

The project can be found here: https://github.com/yeutech-lab/react-router-dom-utils/

The source is just one little recursive function: https://github.com/yeutech-lab/react-router-dom-utils/blob/master/src/Routes.js that create the `<Route />` for a react application.

## Result 

When I import the distributed esm package with rollup, I have the following error during code execution:

![image](https://user-images.githubusercontent.com/1866564/50734819-7fb94580-11d7-11e9-91ae-5e4b4543a848.png)

```
×
TypeError: Object(...) is not a function
(anonymous function)
node_modules/@yeutech-lab/react-router-dom-utils/dist/@yeutech-lab/react-router-dom-utils.esm.js:102
   99 |         key: o.name
  100 |       }, o))) : y.push(e.createElement(n, a({
  101 |         key: o.name
> 102 |       }, o))), o.childRoutes && r(o.childRoutes));
  103 |     }), y;
  104 |   }(c));
  105 | };
```

## Reproduction

I have created a reproduction here: https://codesandbox.io/s/yqyro6lkvx

You can see in **codesandbox** that there is NO issue, while I have one.

I have tried to build my application also with create-react-app and my development and production build also have this error.

- What are the requirement that **codesandbox** fit and that I don't have to use this esm package in my non ejected create react app ?
-  Does other user will have this issue when using the default import.

I have verified my sources and the one difference is rollup, I can't tell what plugin change but the source code now behave differently.

Thanks again for your time and happy new year !)

**Comment by GrosSacASac** [comment]
What is your rollup config ?

**Comment by kopax** [comment]
```jsx
/* eslint-disable flowtype-errors/show-errors, no-console, import/extensions */
import nodeResolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';
import commonjs from 'rollup-plugin-commonjs';
import inject from 'rollup-plugin-inject';
import babel from 'rollup-plugin-babel';
import json from 'rollup-plugin-json';
import { terser } from 'rollup-plugin-terser';
import cleanup from 'rollup-plugin-cleanup';
import visualizer from 'rollup-plugin-visualizer';
import builtins from 'rollup-plugin-node-builtins';
import pkg from './package.json';
import declination from './declination.json';
const processShim = '\0process-shim';
const prod = process.env.PRODUCTION;
const mode = prod ? 'production' : 'development';
const { external, globals } = declination;

console.log(`Creating ${mode} bundle...`);

const output = prod ? [
  {
    name: pkg.name, exports: 'named', globals, file: `dist/${pkg.name}.min.js`, format: 'umd', sourcemap: true,
  },
  {
    name: pkg.name, exports: 'named', globals, file: `dist/${pkg.name}.cjs.min.js`, format: 'cjs', sourcemap: true,
  },
  {
    name: pkg.name, exports: 'named', globals, file: `dist/${pkg.name}.esm.js`, format: 'es', sourcemap: true,
  },
] : [
  {
    name: pkg.name, exports: 'named', globals, file: `dist/${pkg.name}.js`, format: 'umd', sourcemap: true,
  },
  {
    name: pkg.name, exports: 'named', globals, file: `dist/${pkg.name}.cjs.js`, format: 'cjs', sourcemap: true,
  },
  {
    name: pkg.name, exports: 'named', globals, file: `dist/${pkg.name}.esm.js`, format: 'es', sourcemap: true,
  },
];

const plugins = [
  // Unlike Webpack and Browserify, Rollup doesn't automatically shim Node
  // builtins like `process`. This ad-hoc plugin creates a 'virtual module'
  // which includes a shim containing just the parts the bundle needs.
  {
    resolveId(importee) {
      if (importee === processShim) return importee;
      return null;
    },
    load(id) {
      if (id === processShim) return 'export default { argv: [], env: {} }';
      return null;
    },
  },
  builtins(),
  nodeResolve({
    browser: true,
  }),
  commonjs({
    include: 'node_modules/**',
  }),
  replace({
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  }),
  inject({
    process: processShim,
  }),
  json(),
  babel({
    babelrc: false,
    exclude: 'node_modules/**',
    runtimeHelpers: true,
  }),
  cleanup(),
];

export default output.map((o) => ({
  input: 'src/index.js',
  external,
  output: o,
  plugins: prod ? plugins.concat([terser(), visualizer({ filename: './bundle-stats.html' })]) : plugins,
}));
```

**Comment by atherdon** [comment]
Wow - this config should be placed at some place as example!

**Comment by kopax** [comment]
About this issue: I have found that my issue was that I was minimizing the js of the esm build causing errors, I have fixed this.

@atherdon this config is available here:

https://github.com/rollup-umd/rollup

You can use it as follow:

     npm i @rollup-umd/rollup

and in `rollup.config.js`

    const { createConfig } = require('@rollup-umd/rollup');
    module.exports = createConfig();

Read the [documentation here](https://rollup-umd.github.io/rollup/#jsdoc)
