### ISSUE TITLE
UTF-8 characters in issue templates are invalid

### ISSUE THREAD

**Issue by benmccann** [rollup/rollup#2648]
Here's what I see:
![screenshot from 2019-01-07 12-59-17](https://user-images.githubusercontent.com/322311/50793195-3cfd7900-127c-11e9-88e7-bd7fed031b57.png)

This is due to unusual characters in https://github.com/rollup/rollup/tree/master/.github

I'm using Chrome 69 on Linux Mint

**Comment by shellscape** [comment]
@benmccann I'm sorry your browser is acting up there. The characters that your browser is rendering as the unicode placeholder aren't invalid, but rather emoji. Most modern systems support these nowadays. I'd recommend looking into getting Linux Mint updated with that support. [This might help](https://forums.linuxmint.com/viewtopic.php?t=270519).
