### ISSUE TITLE
"format: IIFE" without adding an IIFE

### ISSUE THREAD

**Issue by troynguyen-dmsi** [rollup/rollup#2649]
### Feature Use Case
* Variables could be intentionally global for access from external scripts
* A compiler from JavaScript to another language such as Java often expect top level returns 

### Feature Proposal
* Allow for an option that is exactly like `format: 'iife'` without actually altering the scoping of variables in the original file.

**Comment by troynguyen-dmsi** [comment]
I found a solution to the top level returns part of this issue by setting `acorn.allowReturnOutsideFunction = true`

**Comment by GrosSacASac** [comment]
'use strict'; (prepend string) + use format esm would be closest thing I would use in the meantime.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
