### ISSUE TITLE
ES Modules for Browsers with Gulp

### ISSUE THREAD

**Issue by QJan84** [rollup/rollup#2650]
I just want the scripts
`import anime from 'animejs';`
`import flatpickr from "flatpickr";`
inserted into a file as vanilla js. So the browser can read this.

**My testfile.js:**

```
import anime from 'animejs';
import flatpickr from 'flatpickr';
console.log("The 'anime ' and 'flatpickr ' script should be inserted in the outputfile (testfile.min.js)."); 
```

### Here is my gulp task:

```
gulp.task("js-babel-main", () => {
  console.log($.chalk.yellow.bold('--> JS::MAIN - Transpiling Javascript via Babel'));
  return gulp.src(pkg.paths.src.js + '**/*.js')
    .pipe($.plumber({
      errorHandler: onError
    }))
    .pipe(
      $.rollupEach({
        output: {
          format: 'iife'
        }
      })
    )
    .pipe($.babel())
    .pipe($.flatten())
    .pipe(gulp.dest(pkg.paths.build.js));
});
```

**Comment by TrySound** [comment]
Try this https://github.com/rollup/rollup-plugin-node-resolve

**Comment by QJan84** [comment]
Can someone explain something to me more exactly? I'm confused ... I need a complete example, if possible.
I have no entrypoint, because I access via `'** / *.js'` to several .js files.

It should just be with `import Swiper from' swiper ';` the script will be inserted into the respective file.

**Comment by QJan84** [comment]
```
gulp.task("js-babel-main", () => {
  console.log($.chalk.yellow.bold('--> JS::MAIN - Transpiling Javascript via Babel'));
  return gulp.src(pkg.paths.src.js + '**/*.js')
    .pipe($.plumber({
      errorHandler: onError
    }))
    .pipe($.betterRollup({
      input: pkg.paths.src.js + '**/*.js',
      format: 'iife',
      plugins: [
          $.rollupPluginMultiEntry(),
          // so Rollup can find `ms`
          $.rollupPluginNodeResolve(),
          // so Rollup can convert `ms` to an ES module
          $.rollupPluginCommonjs()
      ]
    }))
    .pipe($.babel())
    .pipe($.flatten())
    .pipe(gulp.dest(pkg.paths.build.js))
    .pipe($.filter("**/*.js"))
    .pipe($.browserSync.stream());
});

```

**This does not work!**

**My Output: (tried to import swiper.js - a touch slider)**

```
(function (swiper) {
  'use strict';

  swiper = swiper && swiper.hasOwnProperty('default') ? swiper['default'] : swiper;
  console.log("The 'Swiper' script should be inserted here.");
  var bla = 'blaaaaaaaaaaaaaaaaaaa';
  console.log(bla);
})(swiper);
```

**Comment by GrosSacASac** [comment]
Try to fix the fact that swiper could not be resolved
'use strict'; + use format esm would be closest thing I could think about.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
