### ISSUE TITLE
Dead code elimination not working on early return

### ISSUE THREAD

**Issue by ryan-codingintrigue** [rollup/rollup#2658]
- Rollup Version: 1.1.0
- Operating System (or Browser): OSX
- Node Version: 8.9.4

### How Do We Reproduce?

[Rollup REPL](https://rollupjs.org/repl?version=1.1.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpZih0cnVlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUMlMjJIaSElMjAlM0EpJTVDJTIyJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMGxvdHNPZkNvZGVIZXJlJTIwJTNEJTIwdHJ1ZSUzQiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAlNjBUaGlzJTIwc2hvdWxkbid0JTIwYmUlMjBpbmNsdWRlZCUyMGluJTIwdGhlJTIwYnVuZGxlJTJDJTIwcmlnaHQlM0YlMjAlMjQlN0Jsb3RzT2ZDb2RlSGVyZSU3RCU2MCUzQiU1Q24lN0QlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

```js
export default () => {
    if(true) {
        return "Hi :)";
    }
    const lotsOfCodeHere = true;
    return `This shouldn't be included in the bundle, right? ${lotsOfCodeHere}`;
};
```

### Expected Behavior

The outputted bundle should not include anything after the early `return` statement. Introducing an `else` at that point has the expected behaviour ([Rollup REPL](https://rollupjs.org/repl?version=1.1.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpZih0cnVlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUMlMjJIaSElMjAlM0EpJTVDJTIyJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyMGVsc2UlMjAlN0IlNUNuJTVDdCU1Q3QlNUN0JTIwJTIwY29uc3QlMjBsb3RzT2ZDb2RlSGVyZSUyMCUzRCUyMHRydWUlM0IlNUNuJTVDdCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU2MFRoaXMlMjBzaG91bGRuJ3QlMjBiZSUyMGluY2x1ZGVkJTIwaW4lMjB0aGUlMjBidW5kbGUlMkMlMjByaWdodCUzRiUyMCUyNCU3QmxvdHNPZkNvZGVIZXJlJTdEJTYwJTNCJTVDbiU1Q3QlNUN0JTdEJTVDbiU3RCUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)) and the two pieces of code are functionally equivalent.

### Actual Behavior

The output bundle includes the dead code which will never be executed

**Comment by lukastaegert** [comment]
Thanks, this is definitely on the larger roadmap. See also #2319 which is related. Cannot promise any short-term improvements here, though, as it requires some basic extensions to the tree-shaking algorithm that may interact with other planned improvements.

**Comment by ryan-codingintrigue** [comment]
Ahh you’re right that’s pretty much a duplicate. It was quite hard to search for such a generic term 😀

Thanks for taking a look. For now I’ll leave the if/else in with a comment to say it’s required by Rollup

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by lukastaegert** [comment]
There is also another issue tracking this (would need to look it up though). This is still in the pipeline!
