### ISSUE TITLE
Tree-shaken dynamic imports leave behind `undefined` in bundle

### ISSUE THREAD

**Issue by tivac** [rollup/rollup#2659]
When a dynamic import is removed via tree-shaking it leaves an `undefined` behind in the `Bundle` object that is passed to the `generateBundle` plugin hook. This seems unintended and can cause bugs in plugins that use that data like `@modular-css/rollup`.

- Rollup Version: 1.1.0
- Operating System (or Browser): Windows 10
- Node Version: 10.12.0

### How Do We Reproduce?

I made a gist. The [`README.md`](https://gist.github.com/tivac/7ad94d821922b2009cca7d704e470d0e#file-readme-md) contains repro steps.

### Expected Behavior

The `Bundle` object passed to `generateBundle` shouldn't have an `undefined` value inside of the `dynamicImports` array when a dynamic import is removed by tree-shaking.

### Actual Behavior

The `Bundle` object passed to `generateBundle` has an `undefined` value inside of the `dynamicImports` array when a dynamic import is removed by tree-shaking.

**Comment by lukastaegert** [comment]
Thanks for the nice repro! Fix at #2663.
