### ISSUE TITLE
Plugins: Add api to emit additional modules

### ISSUE THREAD

**Issue by Jamesernator** [rollup/rollup#2666]
### Feature Use Case

I'm currently implementing a transform for [html modules](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HTMLModules/explainer.md), however I'm currently stuck at how to do something. I would like to generate some additional modules from the inline modules of an HTML file.

For example given this html file:

```html
<!-- some-file.html -->
<!doctype html>

<script type="module">
  export default class MyElement {

  }
</script>

<script type="module">
  export const someMetadata = { x: 10 }
</script>
```

I would like to generate the following files "in the output" which is to say they might get bundled and stuff again later, but while working with them I'd want to generate something like this (which is pretty close to semantically correct with the proposal):

```js
// some-file_document.mjs

const documentString = `
  <!-- some-file.html -->
  <!doctype html>

  <script type="module">
    export default class MyElement {

    }
  </script>

  <script type="module">
    export const someMetadata = { x: 10 }
  </script>
`

export default new DOMParser().parseFromString(documentString, 'text/html')
```

```js
// some-file_inline-module1.mjs
import __document from './some-file_document.mjs'
import.meta.document = __documentName

export default class MyElement {

}
```

```js
// some-file_inline-module2.mjs
import __document from './some-file_document.mjs'
import.meta.document = __documentName

export const someMetadata = { x: 10 }
```

```js
// some-file.html.mjs
import __document from './some-file_document.mjs'
import * as someInlineModule1 from './some-file_inline-module1.mjs'
import * as someInlineModule2 from './some-file_inline-module2.mjs'

export * from './some-file_inline-module1.mjs'
export * from './some-file_inline-module2.mjs'

const defaultExports = [someInlineModule1, someInlineModule2]
  .filter(module => 'default' in module)

if (defaultExports.length > 1) {
  throw new Error("More than one default export!")
}

export default defaultExports.length === 0 ? __document : defaultExports[0]
```

### Feature Proposal

I propose the addition of a new emit method `this.emitModule(suggestedName: string, sourceText: string, entryPoint: boolean=false)` that can create an additional module (similar to assets but they can be bundled like source modules), the suggestedName might collide with another one so this should autogenerate a unique name in some way.

In addition there could be an additional option like `assetFileNames` that can be used for giving a name to auto-generated modules with similar string replacement options.

**Comment by Jamesernator** [comment]
Example of how I'd use such an API in the context my use case:

```js
'use strict'
const parse5 = require('parse5')
const babelGenerator = require("@babel/generator")

function* traverse(node) {
    yield node
    for (const childNode of node.childNodes || []) { 
        yield* traverse(childNode)
    }
}

function* findScripts(document) {
    for (const node of traverse(document)) {
        if (node.nodeName === 'script') {
            yield node
        }
    }
}

function toText(node) {
    let result = ''
    for (const node of node.childNodes) {
        if (node.nodeName !== '#text') {
            throw new Error("Only text nodes allowed")
        }
        result += node.value
    }
    return result
}

module.exports = function htmlImports({ isHtmlModule=file=>file.endsWith('.html') }={}) {
    return {
        name: 'html-imports',
        transform(code, id) {
            if (isHtmlModule(id)) {
                function toName(value) {
                    return path.join(
                        path.dirname(id),
                        `${ path.basename(id) }_${ value }`
                    )
                }


                const documentModuleRelative = this.emitModule(toName('document'), `
                    // build some-file_document.mjs with babel or something
                `)
                const modules = []
                const scripts = [...findScripts(parse5.parse(code))]
                for (const [index, scriptTag] of scripts.entries()) {
                    if (getAttribute(scriptTag, 'type') !== 'module') {
                        return `throw new SyntaxError("Can't import HTML module with non-module imports")`
                    }
                    
                    const name = toName(`${ path.basename(id) }_inline-module-${ index }`)

                    modules.push(this.emitModule(name, `
                        // build some-file_inline-module-<index>.mjs with babel or something
                    `))
                }

                const htmlModule = `
                    // build entry point with babel or something
                `

                return htmlModule
            }
            return null
        },
    }
}
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by lukastaegert** [comment]
There is a new `this.emitFile` API for this now, please check it out!
