### ISSUE TITLE
Rename Identifiers based on re-exports

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup#2668]
### Feature Use Case

More beautiful code :-)

### Feature Proposal

It would be nice if the identifier renaming algorithm could take hints from any re-exports if present.

Given this code:

```js
// a.js
export function Fn() {}

// b.js
export function Fn() {}

// main.js
export { Fn as AFn } from "./a.js"
export { Fn as BFn } from "./b.js"
```

Current rollup generates the following code ([REPL](https://rollupjs.org/repl?version=1.1.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMEZuJTIwYXMlMjBBRm4lMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmEuanMlNUMlMjIlNUNuZXhwb3J0JTIwJTdCJTIwRm4lMjBhcyUyMEJGbiUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGYi5qcyU1QyUyMiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBGbigpJTIwJTdCJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBGbigpJTIwJTdCJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE))

```js
function Fn() {}

function Fn$1() {}

export { Fn as AFn, Fn$1 as BFn };
```

However, this would be *so* much nicer:

```js
function AFn() {}

function BFn() {}

export { AFn, BFn };
```

This is something I noticed when working on [rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts/commit/43dac672b8c6e2cfdc88869f310eed24cd7108f3)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
