### ISSUE TITLE
Support custom context of systemjs

### ISSUE THREAD

**Issue by rail44** [rollup/rollup#2669]
### Feature Use Case

I'm working in the Internet advertising and thinking about whether to use rollup and systemjs in ad delivery scripts.
The problem here is that ad delivery script will be pasted to the web page of a third party, customer of us.
Therefore, if they already use systemjs, the global variable name `System` will be conflicts.

Fortunately, systemjs supports using modular systems in a limited context by calling constructors.
https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemconstructor

So I propose to use the name with the systemjs finalizer when some option like `customSystemContext` is available in webpack.config.js.

### Feature Proposal

rollup.config.js

```javascript
export default {
  ...
  output: {
    ...
    format: 'system',
    custemSystemContext: 'someAlternativeSystem',
  },
  ...
};
```

bundled javascript

```javascript
someAlternativeSystem.register([], function (exports, module) {
	'use strict';
        ...
});
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
