### ISSUE TITLE
Watch mode doesn't handle external modules properly

### ISSUE THREAD

**Issue by egoist** [rollup/rollup#2670]
- Rollup Version: 1.1.2
- Operating System (or Browser):
- Node Version: 

### How Do We Reproduce?

`index.js`

```js
import path from 'path'

console.log(path)
```

`rollup.config.js`

```js
export default {
  input: 'index.js',
  output: {
    format: 'cjs',
    file: 'dist/index.js'
  },
  plugins: [
    {
      resolveId(id) {
        if (id === 'path') {
          return false
        }
        return null
      }
    }
  ]
}
```

### Expected Behavior

It shouldn't print errors.

### Actual Behavior

Running `rollup -c -w` works on first build, but if you modify `index.js` it will print an error:

<img width="1416" alt="2019-01-30 6 14 02" src="https://user-images.githubusercontent.com/8784712/51974577-34831180-24bb-11e9-9f18-7f2dc084519f.png">

However it's actually built successfully, `dist/index.js` will reflect the changes.

btw if I use `external: ['path']` in `rollup.config.js` it works fine.

**Comment by lukastaegert** [comment]
Resolved (hopefully) via #2718
