### ISSUE TITLE
ExternalModule renderPath doesn't change with multiple outputs?

### ISSUE THREAD

**Issue by danielmahal** [rollup/rollup#2675]
- Rollup Version: 1.1.2
- Operating System (or Browser): Mac OS X 10.14 (18A391)
- Node Version: 10.11.0

### How Do We Reproduce?

```javascript
// input.js

import answer from 'the-answer'
console.log(answer)
```

```javascript
// rollup.config.js

export default {
  input: './input.js',

  external: [
    'the-answer'
  ],

  output: [
    {
      file: 'cjs.js',
      format: 'cjs'
    },

    {
      file: 'esm.js',
      format: 'esm',
      paths: id => `//unpkg.com/${id}@?module`
    }
  ]
}
```

`rollup -c`

### Expected Behavior

```javascript
// esm.js

import answer from '//unpkg.com/the-answer@?module';

console.log(answer);
```

### Actual Behavior
```javascript
//esm.js

import answer from 'the-answer';

console.log(answer);
```

If we reverse the order of outputs in the config, the `output.paths` work properly for the `esm` ouput, but the `cjs` ouput will have the wrong paths (unpkg ones)

The issue only applies in multioutput configutations

Maybe the problem is that `renderPath` is being reused?
https://github.com/rollup/rollup/blob/master/src/Chunk.ts#L600

**Comment by lukastaegert** [comment]
Thanks for spotting this, fix at #2706
