### ISSUE TITLE
Cannot split a chunk that has already been edited

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#2676]
- Rollup Version: 1.1.2
- Operating System (or Browser): MacOS
- Node Version: 11.6.0

### How Do We Reproduce?

* [REPL](https://rollupjs.org/repl?version=1.1.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGYS5qcyclM0IlNUNuaW1wb3J0JTIwJy4lMkZiLmpzJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwZm9vJTIwJTdEJTIwZnJvbSUyMCcuJTJGYy5qcyclM0IlNUNuJTVDbmZvbygpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJy4lMkZjLmpzJyUzQiU1Q25pbXBvcnQlMjAnLiUyRmQuanMnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBmb28oKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coMSklM0IlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0KCcuJTJGYi5qcycpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)
* [Repo](https://github.com/Rich-Harris/rollup-bug-repro)

### Expected Behavior

It bundles

### Actual Behavior

It doesn't bundle. Instead, we get the same error as in #2660 —

> [!] Error: Cannot split a chunk that has already been edited (0:7 – "import('./b.js')")

**Comment by Rich-Harris** [comment]
[Very slightly simpler repro](https://rollupjs.org/repl?version=1.1.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGYS5qcyclM0IlNUNuaW1wb3J0JTIwJy4lMkZiLmpzJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwZm9vJTIwJTdEJTIwZnJvbSUyMCcuJTJGYy5qcyclM0IlNUNuJTVDbmZvbygpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJy4lMkZjLmpzJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKDEpJTNCJTVDbiU3RCU1Q24lNUNuaW1wb3J0KCcuJTJGYi5qcycpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by lukastaegert** [comment]
Resolved via #2677
