### ISSUE TITLE
rollup renames missing export to existing local variable

### ISSUE THREAD

**Issue by filipesilva** [rollup/rollup#2687]
- Rollup Version: 1.1.2
- Operating System (or Browser): Windows
- Node Version: v10.10.0

### How Do We Reproduce?

```
git clone https://github.com/filipesilva/rollup-rename-missing-export
cd rollup-rename-missing-export
yarn
yarn simple-repro
yarn real-repro
```

This reproduction bears some explaining. We found it in production at https://github.com/angular/angular/issues/26743.

I tried to reduce it as much as possible but I didn't get the same results. So I included both the simple reproduction, and the real reproduction.

The reproduction centers around the function below, which references a missing export (`o.constructor`):
```
import * as o from './output_ast';
export function invalid(arg) {
    throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + o.constructor.name);
}
```
In the simple reproduction the function is in `./simple/utils.js`, and in the real reproduction it is in `./real/src/render3/view/util.js`.

Running `yarn simple-repro` generates the `simple-output.js` bundle. In this bundle the missing export is renamed to `undefined`:
```
function invalid(arg) {
    throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + undefined);
}
```

Running `yarn real-repro` generates the `real-output.js` bundle. But here the results are different. Instead of `undefined` the missing export was actually converted into the local `arg` variable:
```
function invalid(arg) {
    throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + arg.constructor.name);
}
```
This problem was undetected in our codebase for a while because it just to happens that `arg` was the correct variable to use. But it is extremely surprising, and overall incorrect, that Rollup is changing the variable this way.

### Expected Behavior
Missing export should not be transformed into an existing variable reference.

### Actual Behavior
Missing export is transformed into an existing variable reference.

**Comment by filipesilva** [comment]
Overnight it crossed my mind to check if the real example had two functions with the same name, one of which got renamed, and sure enough...
```
function invalid$1(arg) {
    throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + undefined);
}
```

Please disregard this issue. Rollup is not changing the variable to anything else but `undefined`.

**Comment by lukastaegert** [comment]
Closing following https://github.com/rollup/rollup/issues/2687#issuecomment-463104570 , feel free to reopen if I misinterpreted this comment.
