### ISSUE TITLE
Allow more programmatic control over manual chunks

### ISSUE THREAD

**Issue by philipwalton** [rollup/rollup#2688]
### Feature Use Case

*Note: I'm trying to do something with Rollup that I don't think is possible, so consider this a feature request. If it is possible, please let me know how it can be done.*

What I want to do is use Rollup to generate multiple output files (chunks) from a single input file. The reason I want to do this, is I want to deploy and version my application code separately from my third-party dependency code.

As an example, imagine my app has entry point `./main.mjs`, and this file loads other modules both local to my application as well as some in `node_modules`. Here's some super simplified code:

```js
import {vendor1} from 'npm-pkg-1';
import {vendor2a, vendor2b} from 'npm-pkg-2';

import {localA} from './localA.mjs';
import {localB} from './localB.mjs';

// ...
```

After running this through Rollup, I want my output files to look like this:

```
build/
  npm-pkg-1-XXXXXXXX.mjs
  npm-pkg-2-XXXXXXXX.mjs
  main-XXXXXXXX.mjs
```

And I want to load them using a single script tag like this:

```html
<script type="module" src="./main-XXXXXXXX.mjs"></script>
```

And inside `./main-XXXXXXXX.mjs` it would look like this:

```js
import { vendor1 } from './npm-pkg-1-XXXXXXXX.mjs';
import { vendor2a, vendor2b } from './npm-pkg-2-XXXXXXXX.mjs';

// The rest of the `main.mjs` bundle goes here...
```

The point here is that all modules from `npm-pkg-1` get collapsed into a single module (with a version string), and all modules from `npm-pkg-2` get collapsed into a different module (with its own version string as well).

Or, if you wanted, you should be able to configure rollup to collapse *all* third-party code into a single `vendor-XXXXXXXX.mjs` module.

Note, webpack already supports a feature similar to this using its [`optimization.splitChunks`](https://webpack.js.org/configuration/optimization#optimizationsplitchunks) and [`optimization.splitChunks.cacheGroups`](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroups) options. For example, on my blog I have the following config that allows me to independently version all my npm dependencies:

```js
splitChunks: {
  chunks: 'all',
  maxInitialRequests: Infinity,
  minSize: 0,
  cacheGroups: {
    npm: {
      test: /node_modules/,
      name: (mod) => {
        const pkgName = mod.context.match(/node_modules\/([^/]+)/)[1];
        return `npm-${pkgName}`;
      },
    },
  },
},
```

The only difference between what I'm suggesting here and what I can do with webpack, is with webpack I have to load the scripts individually in my HTML (and also include the webpack runtime):

```html
<script type="module" src="./runtime-XXXXXXXX.mjs"></script>
<script type="module" src="./npm-pkg-1-XXXXXXXX.mjs"></script>
<script type="module" src="./npm-pkg-2-XXXXXXXX.mjs"></script>
<script type="module" src="./main-XXXXXXXX.mjs"></script>
```

While listing all modules in the HTML isn't that much of a burden, my preference would be to just leverege the native module loader and not have to include the runtime.

Another side benefit of a feature like this, is you can dramatically reduce the number of total `import` statements your production code makes, which should help a lot with performance when using native modules in production.

Does something like this seem feasible?

### Feature Proposal

I expected the `manualChunks` option to work this this already, but it doesn't seem like it does. If that option could be extended (or a new option creating) to take a function that gets invoked with the module ID and returns a chunk name, that seems like the simplest API to me:

```js
manualChunks: (moduleID) => {
  if (moduleID.includes('node_modules')) {
    const packageName = moduleID.match(/node_modules\/([^/]+)/)[1];
    return packageName;
  } else {
    return 'main';
  }
},
```

**Comment by lukastaegert** [comment]
I believe there are several options of achieving what you are after, let me explain.

The simplest option is to just designate `npm-pkg-1` and `npm-pkg-2` as additional entry points. This will
* guarantees that all code imported by these files ends up in separate chunks from your remaining code
* does not guarantee that it will be only two chunks, depending on how many other chunks are created importing only some of the dependencies.

**Example:**
Config file:
```js
import resolve from 'rollup-plugin-node-resolve';

export default ({
  // to even better control the generated names and folders, use an object, e.g.
  // {main: 'main.js', 'vendor/pkg1': 'npm-pkg-1', 'vendor/pkg2': 'npm-pkg-2'}
  input: ['main.js', 'npm-pkg-1', 'npm-pkg-2'],
  plugins: [resolve()],
  output: [{
    dir: 'dist',
    format: 'esm',

    // fine-grained control over the generated names; note that the "entryFileNames" option
    // is now the more relevant one
    entryFileNames: '[name]-[hash].js',
    chunkFileNames: '[name]-[hash].js'
  }]
});
```

[Example where two chunks are created](https://rollupjs.org/repl?version=1.1.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnZlbmRvcjElN0QlMjBmcm9tJTIwJy4lMkZucG0tcGtnLTEnJTNCJTVDbmltcG9ydCUyMCU3QnZlbmRvcjJhJTJDJTIwdmVuZG9yMmIlN0QlMjBmcm9tJTIwJy4lMkZucG0tcGtnLTInJTNCJTVDbiU1Q25pbXBvcnQlMjAlN0Jsb2NhbEElN0QlMjBmcm9tJTIwJy4lMkZsb2NhbEEubWpzJyUzQiU1Q25pbXBvcnQlMjAlN0Jsb2NhbEIlN0QlMjBmcm9tJTIwJy4lMkZsb2NhbEIubWpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2cobG9jYWxBJTJDJTIwbG9jYWxCJTJDJTIwdmVuZG9yMSUyQyUyMHZlbmRvcjJhJTJDJTIwdmVuZG9yMmIpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybG9jYWxBLm1qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGxvY2FsQSUyMCUzRCUyMCdsb2NhbEEnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxvY2FsQi5tanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBsb2NhbEIlMjAlM0QlMjAnbG9jYWxCJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJucG0tcGtnLTEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjB2ZW5kb3IxJTIwJTNEJTIwJ3ZlbmRvcjEnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybnBtLXBrZy0yLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QnZlbmRvcjJhJTdEJTIwZnJvbSUyMCcuJTJGbnBtLXBrZy0yYS5qcyclM0IlNUNuZXhwb3J0JTIwJTdCdmVuZG9yMmIlN0QlMjBmcm9tJTIwJy4lMkZucG0tcGtnLTJiLmpzJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm5wbS1wa2ctMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjB2ZW5kb3IyYSUyMCUzRCUyMCd2ZW5kb3IyYSclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybnBtLXBrZy0yYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHZlbmRvcjJiJTIwJTNEJTIwJ3ZlbmRvcjJiJyUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

[Example where more chunks are created](https://rollupjs.org/repl?version=1.1.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnZlbmRvcjElN0QlMjBmcm9tJTIwJy4lMkZucG0tcGtnLTEnJTNCJTVDbmltcG9ydCUyMCU3QnZlbmRvcjJhJTJDJTIwdmVuZG9yMmIlN0QlMjBmcm9tJTIwJy4lMkZucG0tcGtnLTInJTNCJTVDbiU1Q25pbXBvcnQlMjAlN0Jsb2NhbEElN0QlMjBmcm9tJTIwJy4lMkZsb2NhbEEubWpzJyUzQiU1Q25pbXBvcnQlMjAlN0Jsb2NhbEIlN0QlMjBmcm9tJTIwJy4lMkZsb2NhbEIubWpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2cobG9jYWxBJTJDJTIwbG9jYWxCJTJDJTIwdmVuZG9yMSUyQyUyMHZlbmRvcjJhJTJDJTIwdmVuZG9yMmIpJTNCJTVDbiU1Q25pbXBvcnQoJy4lMkZkeW5hbWljLWNodW5rJykudGhlbigoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCd0aGlzJTIwY2FuJTIwY2F1c2UlMjB2ZW5kb3IlMjBjaHVua3MlMjB0byUyMHNwbGl0JykpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybG9jYWxBLm1qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGxvY2FsQSUyMCUzRCUyMCdsb2NhbEEnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxvY2FsQi5tanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBsb2NhbEIlMjAlM0QlMjAnbG9jYWxCJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJucG0tcGtnLTEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjB2ZW5kb3IxJTIwJTNEJTIwJ3ZlbmRvcjEnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybnBtLXBrZy0yLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QnZlbmRvcjJhJTdEJTIwZnJvbSUyMCcuJTJGbnBtLXBrZy0yYS5qcyclM0IlNUNuZXhwb3J0JTIwJTdCdmVuZG9yMmIlN0QlMjBmcm9tJTIwJy4lMkZucG0tcGtnLTJiLmpzJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm5wbS1wa2ctMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjB2ZW5kb3IyYSUyMCUzRCUyMCd2ZW5kb3IyYSclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybnBtLXBrZy0yYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHZlbmRvcjJiJTIwJTNEJTIwJ3ZlbmRvcjJiJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJkeW5hbWljLWNodW5rLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnZlbmRvcjJhJTdEJTIwZnJvbSUyMCcuJTJGbnBtLXBrZy0yYS5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKCdUaGlzJTIwY2F1c2VzJTIwdmVuZG9yMmElMjB0byUyMGJlJTIwaW4lMjBhJTIwc2VwYXJhdGUlMjBjaHVuayUyMGFzJTIwaXQlMjBpcyUyMG5vdyUyMHBhcnQlMjBvZiUyMHRoZSUyMGR5bmFtaWMlMjBjaHVuay5OZXZlcnRoZWxlc3MlMkMlMjB2ZW5kb3IlMjBjaHVua3MlMjB3aWxsJTIwYWx3YXlzJTIwYmUlMjBzZXBhcmF0ZSUyMGZyb20lMjBvdGhlciUyMGNodW5rcy4nKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

If you want to make sure that no additional chunks are created, manualChunks are the way to go. It would be interesting to know why they did not work for you, this is what worked for me:

```js
import resolve from 'rollup-plugin-node-resolve';

export default ({
  input: 'main.js',
  plugins: [resolve()],
  manualChunks: {'pkg-1': ['npm-pkg-1'], 'pkg-2': ['npm-pkg-2']}
  output: [{
    dir: 'dist',
    format: 'esm'
  }]
});
```

Note that you definitely need the `node-resolve` plugin!

**Comment by philipwalton** [comment]
Thanks for looking into this:

> The simplest option is to just designate `npm-pkg-1` and `npm-pkg-2` as additional entry points.

In my case this either doesn't work or isn't ideal for a few reasons:

- It requires me to know and enumerate all of my `node_module` dependencies. I'd prefer to be able to construct that list at runtime.
- It requires all my dependencies to themselves be entry points, but that's not the case for all npm dependencies, as this error shows (it's an npm package with multiple entry points, so there's [no "main" or "module" field](https://github.com/GoogleChromeLabs/idlize/blob/0.1.0/package.json)):

```
[!] Error: Could not resolve entry (idlize)
Error: Could not resolve entry (idlize)
    at error (/Users/philipwalton/Projects/philipwalton/blog/node_modules/rollup/dist/rollup.js:3597:30)
    at /Users/philipwalton/Projects/philipwalton/blog/node_modules/rollup/dist/rollup.js:17134:17
```

> It would be interesting to know why they did not work for you, this is what worked for me:

This is a nice example (I wish the docs had examples!). I wasn't actually aware that you could list raw package names in the module list. But even then this unfortunately doesn't quite work for me.

The problems here are effectively the same as the problems above: first, It requires me to know and enumerate all of my `node_module` dependencies. And even if I do know that, I have to know the order in which these dependencies resolve, or I get an error like this:

```
[!] Error: Cannot assign node_modules/dom-utils/index.js to the "npm.dom-utils" chunk as it is already in the "npm.autotrack" chunk.
Try defining "npm.dom-utils" first in the manualChunks definitions of the Rollup configuration.
```

While it's possible for me to manually work around this particular problem, it'd be a lot nicer if I could declare my manual chunks programmatically.

And the second problem, again, is not all my modules have entry points, so if they don't then I have to individually list the modules I want to belong to a particular chunk.

All this requires me to know a lot about my dependencies (and their dependencies).

* * *

Would it be possible to add the feature proposal I outlined above? Where the `manualChunks` option could take a function that gets called whenever a new module dependency is discovered, and the return value of that function would be the `chunkAlias` (and not returning anything could default to the entry chunk, so another dynamic chunk).

**Comment by philipwalton** [comment]
It's it's helpful, I was able to programmatically get Rollup to do what I want, but in order to do it I had to run Rollup twice: a first time to generate a module graph I could use to create `manualChunks`, and then a second time using the `manualChunks` object I'd just created.

Here's an example I though together (not super optimized, but maybe it'll help clarify what I'm trying to do):

```js
const {rollup} = require('rollup');
const resolve = require('rollup-plugin-node-resolve');

const tSort = (nodes) => {
  const sorted = [];
  const seen = new Set();
  const visit = (node) => {
    if (!seen.has(node)) {
      for (const dep of node.deps) {
        visit(dep);
      }
      seen.add(node);
      sorted.unshift(node);
    }
  }
  for (const node of nodes.values()) {
    visit(node);
  }
  return sorted;
}

const tSortRollupModules = (rollupModules) => {
  // Reverse the dependency graph generated by Rollup.
  // I.e. rather that a list of modules and their dependencies, make a list
  // of modules and the other modules who depend on them.
  const modules = new Map();
  const getOrCreateModule = (id) => {
    if (!modules.has(id)) {
      modules.set(id, {id, deps: new Set()})
    }
    return modules.get(id);
  };
  for (const {id, dependencies} of rollupModules) {
    for (const dep of dependencies) {
      getOrCreateModule(dep).deps.add(getOrCreateModule(id));
    }
  };
  return tSort(modules);
}

(async () => {
  // Do the prebundle to generate the dependency graph.
  const prebundle = await rollup({
    input: 'assets/javascript/main.js',
    plugins: [resolve()],
  });

  const modules = tSortRollupModules(prebundle.cache.modules);
  const manualChunks = {};

  const NODE_MODULE = /node_modules\/([^/]+)/;
  for (const mod of modules) {
    if (mod.id.match(NODE_MODULE)) {
      const chunk = RegExp.$1;
      let chunkMods = manualChunks[chunk] || [];

      // Delete the key, so when it's re-added it goes at the end.
      // A bit of a hack, but keys in `manualChunks` need to be ordered.
      if (chunk in manualChunks) {
        delete manualChunks[chunk];
      }
      manualChunks[chunk] = chunkMods
      chunkMods.push(mod.id);
    }
  }

  const bundle = await rollup({
    input: 'assets/javascript/main.js',
    plugins: [
      resolve(),
    ],
    manualChunks,
  });

  await bundle.write({
    dir: 'dist',
    format: 'esm',
    chunkFileNames: '[name]-[hash].mjs',
    entryFileNames: '[name]-[hash].mjs',
  });
})();
```

It's a fairly involved process to generate `manualChunks` correctly because Rollup is very picky about both the ordering of keys and values in that object (as you can see I had to sort the dependencies myself). It'd be great if correct ordering could be inferred by Rollup.

<details>
  <summary>In case you're curious, here's what that object looked like when run for my blog:</summary>
 <pre>{ 'workbox-core':
   [ '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-core/_version.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-core/_private/logger.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-core/_private/Deferred.mjs' ],
  idlize:
   [ '/Users/philipwalton/Projects/philipwalton/blog/node_modules/idlize/lib/queueMicrotask.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/idlize/lib/now.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/idlize/idle-callback-polyfills.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/idlize/IdleValue.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/idlize/IdleQueue.mjs' ],
  'dom-utils':
   [ '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/lib/parse-url.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/lib/parents.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/lib/matches.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/lib/get-attributes.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/lib/dispatch.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/lib/closest.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/lib/delegate.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/dom-utils/index.js' ],
  autotrack:
   [ '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/event-emitter.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/method-chain.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/constants.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/usage.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/tracker-queue.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/utilities.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/store.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/session.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/provide.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/url-change-tracker.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/page-visibility-tracker.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/media-query-tracker.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/impression-tracker.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/outbound-link-tracker.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/max-scroll-tracker.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/clean-url-tracker.js',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/autotrack/lib/plugins/event-tracker.js' ],
  'workbox-window':
   [ '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-window/_version.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-window/utils/WorkboxEvent.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-window/utils/urlsMatch.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-window/utils/EventTargetShim.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-window/messageSW.mjs',
     '/Users/philipwalton/Projects/philipwalton/blog/node_modules/workbox-window/Workbox.mjs' ] }
</pre>
</details>

Ideally, it'd be possible to do this in a single invocation of `rollup.bundle()`.

**Comment by Xazzzi** [comment]
> Rollup is very picky about both the ordering of keys and values in that object

So i recently ran into the same issue when trying to factor-out my vendor chunk in react application, like so:
```
import { dependencies } from './package.json';
// and then later in rollup config
manualChunks: {
  dependencies: Object.keys(dependencies),
},
```
Error was `Cannot assign node_modules/prop-types/index.js to the "dependencies" chunk as it is already in the "dependencies" chunk.`. This makes no sense to me, as if something is already in the chunk - why would bundler complain about it and not just reuse what's already there?
So i peeked into the source for where the error was thrown and made a small change to skip entries with chunkAlias that is the same as one we'd like to assign:
```
    if (manualChunkModules) {
        for (var _i = 0, _d = Object.keys(manualChunkModules); _i < _d.length; _i++) {
            var chunkName = _d[_i];
            currentEntryHash = randomUint8Array(10);
            for (var _e = 0, _f = manualChunkModules[chunkName]; _e < _f.length; _e++) {
                currentEntry = _f[_e];

+                if (currentEntry.chunkAlias === chunkName) {
+                  continue;
+                }

                if (currentEntry.chunkAlias) {
                    error({
                        code: 'INVALID_CHUNK',
                        message: "Cannot assign " + path.relative(process.cwd(), currentEntry.id) + " to the \"" + chunkName + "\" chunk as it is already in the \"" + currentEntry.chunkAlias + "\" chunk.\nTry defining \"" + chunkName + "\" first in the manualChunks definitions of the Rollup configuration."
                    });
                }
                currentEntry.chunkAlias = chunkName;
                modulesVisitedForCurrentEntry = (_a = {}, _a[currentEntry.id] = true, _a);
                addCurrentEntryColourToModule(currentEntry);
            }
        }
    }
```
My app seems to build and work just file with this tweak, but i'm worried that next two lines maybe did something important:
```
modulesVisitedForCurrentEntry = (_a = {}, _a[currentEntry.id] = true, _a);
addCurrentEntryColourToModule(currentEntry);
```
But on a first glance, if we already marked `currentEntry` with same `chunkAlias` earlier, then theese two lines were already executed earlier as well, and it seems more or less safe to just skip an iteration.

**Comment by guybedford** [comment]
@Xazzzi that does sound like a bug, please post a PR if you can.

Ideally we should make sure we are doing a unique comparison though, not based on `chunkAlias` check, but rather checking the chunk by its unique Id.

**Comment by lukastaegert** [comment]
@Xazzi #2809 should also solve your issue with manual chunks

**Comment by lukastaegert** [comment]
@philipwalton I created #2831 which allows manual chunks to be defined as a function. This should hopefully allow you to solve your use case.

**Comment by lukastaegert** [comment]
You need [`preserveEntrySignatures: "allow-extension"`](https://rollupjs.org/guide/en/#preserveentrysignatures), otherwise facade chunks are created.

**Comment by murtuzaalisurti** [comment]
@lukastaegert thanks, this worked for me!

```js
import resolve from 'rollup-plugin-node-resolve';

export default ({
  input: 'main.js',
  plugins: [resolve()],
  output: [{
    dir: 'dist',
    format: 'esm',
    // note that manualChunks should now be used inside the output options!
    manualChunks: {'pkg-1': ['npm-pkg-1'], 'pkg-2': ['npm-pkg-2']},
    chunkFileNames: "[name].js"
  }]
});
```
