### ISSUE TITLE
Custom output formats?

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#269]
I had to do something a lil’ dirty in [d3-bundler](https://github.com/d3/d3-bundler). I call bundle.generate with iife format and then mangle the resulting code:

``` js
function patch(code) {
  if (code.slice(0, 37) !== "(function (exports) { 'use strict';\n\n") throw new Error("unexpected output");
  if (outro = code.slice(-26) !== "\n})((this.exports = {}));\n") throw new Error("unexpected output");
  try { var version = require(path.resolve(entry, "../package.json")).version; } catch (ignore) {};
  return "!function(global, exports) {\n"
      + "  \"use strict\";\n"
      + "\n"
      + code.slice(37, -26)
      + (version ? "  exports.version = " + JSON.stringify(version) + ";\n" : "")
      + "\n"
      + "  if (typeof define === \"function\" && define.amd) global." + argv.name + " = exports, define(\"" + argv.name + "\", [], function() { return exports; });\n"
      + "  else if (typeof module === \"object\" && module.exports) module.exports = exports;\n"
      + "  else global." + argv.name + " = exports;\n"
      + "}(this, {});\n";
}
```

I do this because I have “special” requirements for my UMD module, as D3 is a library:
- I want to generate a named AMD module, not an anonymous one.
- I want to export a global even if AMD is available (but not with CommonJS).
- I want to automatically pull the version number from the package.json.

My hack’s not too bad since the iife format is pretty simple, but do you think this is the right way to do it?

**Comment by Rich-Harris** [comment]
Have wondered about this. Can definitely see the value in it. The reason it hasn't happened already is that it means exposing more of Rollup's guts than is ideal, at least as [currently implemented](https://github.com/rollup/rollup/tree/master/src/finalisers) – so we'd probably need to spend a bit of time finessing the API. (The really tricky part isn't the format-specific code that wraps the bundle as much as the identifier renaming logic, which differs according to whether the output is an ES6 module.)

In the shorter term, we can get [two out of three](https://www.youtube.com/watch?v=k5hWWe-ts2s):

* you can use `options.moduleId` to generate a [named AMD module](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22umd%22%2C%22moduleName%22%3A%22answer%22%2C%22moduleId%22%3A%22answer%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20default%2042%3B%22%7D%5D%7D)
* [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) can take care of the version number

What if we added an option to generate a global in an AMD environment? I've had need for similar things in the past myself, it's probably not that esoteric a requirement.

**Comment by Victorystick** [comment]
Another option is to use rollup-plugin-json and

main.js
```js
export { version } from './package.json';
```

**Comment by Rich-Harris** [comment]
Right now the plugin only exports `default`, so you'd need to import all of `package.json` and export `version` – I've opened https://github.com/rollup/rollup-plugin-json/issues/1 because I think that `export { version } from './package.json'` should work.

**Comment by Rich-Harris** [comment]
Released an updated version of the JSON plugin – it now supports `export { version } from './package.json'` and doesn't unnecessarily include the rest of the file.

**Comment by mbostock** [comment]
Wouldn’t importing a JSON file (as opposed to another ES6 module) such as package.json make my ES6 module incompatible with any non-Rollup loader?

Seems like a more compatible approach would be to auto-generate an ES6 version module as part of the build process.

**Comment by Rich-Harris** [comment]
Yes – tool-specific stuff in *distributed* code is a scourge, whether it's a Rollup plugin, a Browserify transform, a Webpack loader, or whatever. I've been bitten by this on a number of occasions and I'm determined to avoid there ever being a need for e.g. a `"rollup"` field in package.json.

In most of my packages I've been doing exactly what you suggest – generating an ES6 build (alongside the UMD build) at publish time, and pointing to it with `jsnext:main`, so my package.json looks something like this:

```js
{
  ...,
  "main": "dist/my-package.umd.js",
  "jsnext:main": "dist/muy-package.es6.js",
  "scripts": {
    "build": "rollup -c -f umd -o dist/my-package.umd.js && rollup -c -f es6 -o dist/my-package.es6.js",
    "prepublish": "npm run build"
  }
}
```

(In this example, the `-c` part of `rollup -c` means 'use the configuration in [rollup.config.js](https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file)'.)

There's some residual confusion over what the exact meaning of `jsnext:main` should be (https://github.com/jsforum/jsforum/issues/5), but this approach has been working pretty well for me.

**Comment by ayushmad** [comment]
I am not sure if this is helpful. But to bring in the package version this is what i do.

In my index.js[entry file] I do.
```javascript
export var version = publishedVersion | '0.1.12'; 
```
and in my bundler which uses rollup I do this.
```javascript
var _package = require('package.json'),
      rollup = require('rollup');
rollup.rollup({
  // Options
}).then({
  bundle.generate({
     intro: 'var publishedVersion=' + _package.version;  // Passed the package Version in the intro code
   });
```
Hope this helps.

**Comment by mbostock** [comment]
Thanks for the help. I’ve migrated all the D3 modules over to using Rollup directly rather than using [d3-bundler](https://github.com/d3/d3-bundler). I’ve also decided to not inline external dependencies in the default build, since that makes it easier to compose D3 modules using basic concatenation without duplicating code. I’m only planning on inlining when making a monolithic build (i.e., d3.v4.js). My guess is I can probably use Rollup directly for that, too, and eliminate d3-bundler entirely. So, thanks!

**Comment by Victorystick** [comment]
We may want to think about how to integrate other module formatters. If we add support for it, we could emphasise that it's an experimental API that could change?

> The really tricky part isn't the format-specific code that wraps the bundle as much as the identifier renaming logic, which differs according to whether the output is an ES6 module.

@Rich-Harris The same applies for other output formats, such as SystemJS. It too has _direct_ access to imported values. Rollup doesn't currently support SystemJS, and probably won't for some time. Regardless, I've been trying to promote writing `direct` instead of `es6` in the code. In the example below (from `src/Declaration.js`), we render variable names differently for `es6` (direct access) and every thing else (indirect access through an object).

```js
	render ( es6 ) {
		if ( es6 ) return this.name;
		if ( !this.isReassigned || !this.isExported ) return this.name;

		return `exports.${this.name}`;
	}
```

We could allow a format to specify whether they have _direct_ or _indirect_ access, and keep this code as is.

**Comment by snuggs** [comment]
A little stale. We can close this correct?

**Comment by stalniy** [comment]
is there a way to build `amd` and `cjs` but not global variable?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
