### ISSUE TITLE
Exports are not being taken into consideration in the hash generation

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#2692]
- Rollup Version: 1.1.2

### How Do We Reproduce?

https://rollupjs.org/repl?version=1.1.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZvbyUyQyUyMGJhciUyMCU3RCUyMGZyb20lMjAnLiUyRmRlcCclM0IlNUNuY29uc29sZS5sb2coZm9vKCklMkMlMjBiYXIoKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJvdGhlckVudHJ5LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHRoaW5nJTIwJTdEJTIwZnJvbSUyMCcuJTJGZGVwJyUzQiU1Q25jb25zb2xlLmxvZyh0aGluZygpKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmRlcC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJmdW5jdGlvbiUyMGZvbygpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMDElM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGJhcigpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMDIlM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMHRoaW5nKCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwYmFyKCklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMkMlMjBiYXIlMkMlMjB0aGluZyUyMCU3RCUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

<img width="1546" alt="screenshot 2019-02-14 at 13 22 34" src="https://user-images.githubusercontent.com/127379/52786894-759f2800-305c-11e9-9e51-b2d3a6235dcd.png">
<img width="1540" alt="screenshot 2019-02-14 at 13 22 46" src="https://user-images.githubusercontent.com/127379/52786896-78018200-305c-11e9-9b0a-1e70f54339b8.png">

### Expected Behavior

When the exports of a chunk changes, that should always result in a change in the hash.

### Actual Behavior

When the main.js module does NOT import `bar()`, it makes the `bar export` to be treeshaken in the chunk, but the filename (hash) is the same.

### Problematic

This actually breaks some production websites using strong caching, since, it's using a cached module that DOES NOT have some exports.

**Comment by snaptopixel** [comment]
@lukastaegert I ran into this (after deploying and breaking production 😢) and @manucorporat helped with the repro (I was using Rollup via StencilJS), it's pretty gnarly when you're caching via CDN.

**Comment by lukastaegert** [comment]
Sorry for this and thanks for the awesome repro. Fix at #2695.
