### ISSUE TITLE
New Option: sourcemapRoot

### ISSUE THREAD

**Issue by atompkins** [rollup/rollup#2697]
### Feature Use Case
This is for when you have your source published at a different URL to your bundle. Perhaps you don't want or can't publish your source alongside your bundle, or perhaps you only want to publish source on an internal server rather than exposing your source to the world.

### Feature Proposal
Add an extra option, sourcemapRoot, which maps to the sourceRoot key of the source map.

**Comment by isidrok** [comment]
Pretty good idea, I think this could be done with a plugin rewriting map `sources` as long as the sourcemap is published in the same URL as the bundle. Will give it a try later on.

**Comment by syranide** [comment]
Related, but not the same. #2743

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by aleclarson** [comment]
@shellscape Please reopen :)

**Comment by shellscape** [comment]
@aleclarson if you're willing to pick this up, we'd be happy to.
