### ISSUE TITLE
Command line option to list all source files

### ISSUE THREAD

**Issue by natevw** [rollup/rollup#2698]
### Feature Use Case

I want my Makefile (or other external build/watch system) to be able to know when an output file needs rebuilding. I can't just look at the entry file, since the changes might be in one of its dependencies. Rollup should be able to list all the files depended on by a given entry point.

### Feature Proposal

A `--list` option which outputs a newline-delimited list of all files that are used in the output, including the entry point.

For example, with [smash](https://github.com/mbostock/smash) one could write a Makefile rule:

```
bundle.js: $(shell smash --list src/bundle.js)
  smash src/bundle.js > bundle.js
```

Then if `src/bundle.js` **or any files it references, recursively** has been modified, the build action will be redone. Otherwise the output will be assumed to be up-to-date.

Note that this should ideally be a fast code path, which might mean introducing limitations for optimization purposes. (If it takes nearly as long to list the dependencies as it would to just re-build outright, then it's not worth doing at least in the build case…maybe still useful for watching purposes though.)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
