### ISSUE TITLE
rollup.es.js causes eslint to throw parse error, also references undefined symbol.

### ISSUE THREAD

**Issue by coreyfarrell** [rollup/rollup#2704]
- Rollup Version: 1.2.0
- Operating System (or Browser): any
- Node Version: 10.15.0

### How Do We Reproduce?

Minimal reproduction at https://github.com/coreyfarrell/rollup-issue.  The [import/named](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md) plugin is used to verify that `import` statements request valid exports.  Last night `rollup@1.2.0` caused the linter for [vinyl-rollup](https://github.com/cfware/vinyl-rollup) to fail as the `image/named` rule needs to parse the rollup ES module - a process which fails.

I'm unclear if it's allowed to create a new global symbol overwriting a symbol created by `import` but I'm concerned this might have identified an actual error in rollup.es.js.  From `rollup.config.js`:
```js
const expectedAcornImport = /import acorn__default, { tokTypes, Parser( as [\w$]+)? } from 'acorn';/;
const newAcornImport =
	"import * as acorn__default from 'acorn';\nimport { tokTypes, Parser } from 'acorn';";
```

It looks like the original source contains `import acorn__default, { tokTypes, Parser as Parser$1 } from 'acorn';` but the replacement drops `as Parser$1`.  Later in rollup.es.js `Parser$1` is referenced although it's undefined due to the import alteration.

### Expected Behavior

ESLint should be able to parse dist/rollup.es.js, it should not reference undefined variables.

**Comment by lukastaegert** [comment]
Thanks a lot for identifying this! Yes you are right, I messed up here 🙄 Will try to fix it right away!

**Comment by coreyfarrell** [comment]
Thank greenkeeper :smile: for re-running CI every time a dependency releases an update.  Also amazing response time!
