### ISSUE TITLE
Specifying global name for local import

### ISSUE THREAD

**Issue by slavafomin** [rollup/rollup#2708]
Hello! Thank you for this great tool and your hard work!

However, I'm marking one of my local modules (namely `data.json`) as an "external" one. But, how do I specify a global name for it?

Right now, I'm getting the following error:
`No name was provided for external module '/home/sfomin/project/data.json' in output.globals – guessing 'rawData'`

What should I put in `globals` map in order to specify the global name for this module?

I've tried several options, but it looks like it's only working if I specify the entire (absolute) path to the module, e.g.:

```
globals: {
  '/home/sfomin/project/data.json': 'my.data'
}
```

But, of course this is a terrible solution, because it will not work if I move the project directory or on other machines. Is there a way to specify a relative path somehow?

Thanks!

**Comment by lukastaegert** [comment]
A simple solution could be to use `__dirname` and supply a path relative to your Rollup config, e.g.

```
globals: {
  [path.join(__dirname, 'data.json)]: 'my.data'
}
```

**Comment by slavafomin** [comment]
@lukastaegert the problem is that I configure it from the JSON-file so I can't add any special logic to it.

I think the problem is in how Rollup treat local module paths. Maybe it should resolve such paths relative to the project directory, so the below setup will work?

```
globals: {
  './data.json': 'my.data'
}
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
