### ISSUE TITLE
Output of bundled and unbundled code differs: immer

### ISSUE THREAD

**Issue by chromy** [rollup/rollup#2712]
- Rollup Version: 1.2.2
- Operating System (or Browser):  Debian x86_64 GNU/Linux and MacOS 
- Node Version: v7.10.0 and v10.3.0

### How Do We Reproduce?

```
$ git clone https://github.com/chromy/2019-02-21-immer-and-rollup-bug.git
$ cd 2019-02-21-immer-and-rollup-bug
$ ./node_modules/.bin/rollup index.js --format iife -o bundle.js -c rollup.config.js
$ node index.js
$ node bundle.js
```

See also https://github.com/chromy/2019-02-21-immer-and-rollup-bug.git.

### Expected Behavior

The output of `node index.js` should be the same as `node bundle.js`.

### Actual Behavior

The output of `node index.js` and `node bundle.js` differ:

```
$ node index.js
{ produce: [Function: bound produce],
  default: [Function: bound produce],
  setAutoFreeze: [Function: bound setAutoFreeze],
  setUseProxies: [Function: bound setUseProxies],
  applyPatches: [Function: bound applyPatches$$1],
  createDraft: [Function: bound createDraft],
  finishDraft: [Function: bound finishDraft],
  Immer: [Function: Immer],
  original: [Function: original],
  isDraft: [Function: isDraft],
  isDraftable: [Function: isDraftable],
  nothing: Symbol(immer-nothing),
  immerable: Symbol(immer-draftable) }
[Function: bound applyPatches$$1]
```

```
$ node bundle.js
[Function: bound produce]
undefined
```

It seems like the bundled version is getting the default export of immer rather than the whole module.

I couldn't quite track down whether the problem originates in `rollup`, `rollup-plugin-commonjs`, `rollup-plugin-node-resolve`, or indeed `immer`. Would super appreciate any help and/or pointers you might have :smiley: Thanks so much for all your work on rollup!

**Comment by TrySound** [comment]
@chromy I would suggest to not use commonjs with rollup at least when it's not in dependencies.
The problem is that your commonjs module tries to import esm. Such interop doesn't have a standard and often produces unexpected to user results.

You may also try to disable `module` in node resolve plugin.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
