### ISSUE TITLE
Code splitting build uses local name instead of chunk name

### ISSUE THREAD

**Issue by coffeedoughnuts** [rollup/rollup#2713]
- Rollup Version: 1.2.2
- Operating System (or Browser): MacOS Mojave
- Node Version: 11.1.0

### How Do We Reproduce?

Dynamic imports (`import('./path/to/module')`) build using the path to your local module in `src`, instead of being replaced with the chunk-hash filename, if the index.js of the module you're importing only re-exports from other files.

Example of issue here: https://github.com/coffeedoughnuts/rollup-code-split-bug with more details and steps to reproduce in README

### Expected Behavior

dynamic imports build to be `import('./chunk-[hash].js')`

### Actual Behavior

dynamic imports are unchanged from source (`import('./lib')`)

**Comment by lukastaegert** [comment]
It looks like it could be related to using rollup-plugin-node-resolve and importing the directory name instead of `directory/index.js`. This would definitely qualify for a bug but can you check if it works correctly if you change the import to `await import('./lib/index.js')`? If not, does it make a difference if you also remove the node-resolve plugin?

**Comment by lukastaegert** [comment]
Belay that, I see I am wrong

**Comment by lukastaegert** [comment]
Vanilla example for reference: https://rollupjs.org/repl?version=1.2.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwbG9hZExpYiUyMCUzRCUyMGFzeW5jJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjAlN0IlMjBoZWxsbyUyMCU3RCUyMCUzRCUyMGF3YWl0JTIwaW1wb3J0KCcuJTJGbGliJyklNUNuJTIwJTIwcmV0dXJuJTIwJTYwJTI0JTdCaGVsbG8lN0QlNjAlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGliLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGhlbGxvJTIwJTdEJTIwZnJvbSUyMCcuJTJGaGVsbG8nJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmhlbGxvLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwaGVsbG8lMjAlM0QlMjAlNUMlMjJoZWxsbyU1QyUyMiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment]
Adding some non-treeshaken code fixes the name: https://rollupjs.org/repl?version=1.2.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwbG9hZExpYiUyMCUzRCUyMGFzeW5jJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjAlN0IlMjBoZWxsbyUyMCU3RCUyMCUzRCUyMGF3YWl0JTIwaW1wb3J0KCcuJTJGbGliJyklNUNuJTIwJTIwcmV0dXJuJTIwJTYwJTI0JTdCaGVsbG8lN0QlNjAlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGliLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGhlbGxvJTIwJTdEJTIwZnJvbSUyMCcuJTJGaGVsbG8nJTNCJTVDbmNvbnNvbGUubG9nKDEpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmhlbGxvLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwaGVsbG8lMjAlM0QlMjAlNUMlMjJoZWxsbyU1QyUyMiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment]
Fix at #2714
