### ISSUE TITLE
writeBundle should have the same signature as generateBundle

### ISSUE THREAD

**Issue by bennypowers** [rollup/rollup#2717]
### Expected Behavior / Situation
`generateBundle` takes an options argument which contains useful info like the bundle format. `writeBundle` does not. This seemingly precludes the ability to write assets based on the bundle in a per-format way. Use case: generating separate service workers with workbox for each build.

### Actual Behavior / Situation
`writeBundle` is unary, and unaware of the output options.

### Modification Proposal
I propose that `writeBundle` take the same arguments as `generateBundle`

**Comment by tivac** [comment]
You can work around this for now by specifying a `generateBundle` hook and then capturing the output options arg via closure variables, but in general I agree that it'd be nice if they were the same.

Since it's already defined to take just the bundle the two signatures can't be made identical w/o it being a breaking change :(

**Comment by bennypowers** [comment]
Yeah I'll have to implement that workaround

> Breaking change
Good thing there's Semver?

**Comment by lukastaegert** [comment]
We can include this at some point. I would be slightly hesitant to do so, though, as it is not possible to soft-deprecate this i.e. all plugins relying on the signature would break.

**Comment by bennypowers** [comment]
One solution to the breaking-API issue might be to expose some temporary hook with a deprecation message, like `onWriteBundle` which has the same siggy as `generateBundle`, with a deprecation message, say, 2 majors before changing `writeBundle`, at which point, onWriteBundle would delegate there.

**Comment by tyler-hogsett-microsoft** [comment]
@tivac 
> You can work around this for now by specifying a `generateBundle` hook and then capturing the output options arg via closure variables, but in general I agree that it'd be nice if they were the same.
I'm trying to figure out this workaround. I'm probably missing something, but if I am generating multiple bundles, how do I make sure that the outputOptions from one `generateBundle` call correspond to the same bundle in the `writeBundle` call?

**Comment by tivac** [comment]
@tyler-hogsett-microsoft I was thinking in a single bundle world, but I think the general approach could work for multiple bundles. You could use a `Map` keyed off the bundle object or check to see if order is stable and if it is an `Array` of the output options would also work in theory.

**Comment by tyler-hogsett-microsoft** [comment]
@tivac Ah, that makes sense. Thanks!

**Comment by shellscape** [comment]
@lukastaegert is this still valid for the 2.x pipeline?

**Comment by lukastaegert** [comment]
I think the approach of creating a new hook with a slightly different signature and soft-deprecating the old one could be in scope.

**Comment by shellscape** [comment]
Cool. We'll resurrect this one and revisit later on if it doesn't get any traction.

**Comment by lukastaegert** [comment]
Solved in rollup@2.0.0
