### ISSUE TITLE
Processing from source string

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#272]
It would be cool to add something like `contents` option to pass source string. `entry` will still be necessary to detect paths.

**Comment by eventualbuddha** [comment]
I'm curious what your use case here is.

**Comment by TrySound** [comment]
@eventualbuddha Everything in memory way :) Input can be preprocessed by something.

**Comment by Victorystick** [comment]
I don't see why you can't create a "from-memory" plugin. Configure Rollup like:

```js
// (Something's wrong with Github's highlighting of default exports of object literals.)
const config = {
  entry: 'src/main.js',

  plugins: [
    {
      // The first module to be loaded is entry. This function returns
      // the string once, and then undefined for all subsequent calls.
      load: once( () => "PUT YOUR SOURCE STRING HERE" )
    }
  ]
};

export default config;
```

**Comment by TrySound** [comment]
@Victorystick Thanks :) Nice solution.

**Comment by TrySound** [comment]
@Victorystick @Rich-Harris New one: [rollup-plugin-memory](https://github.com/TrySound/rollup-plugin-memory)

Any suggestions/corrections?

**Comment by Victorystick** [comment]
If you're building a complete plugin to load files from in-memory, you'll probably want to support more than just the entry module, no? Or do you only need it for the entry module?

You can skip the brackets and `return` with
```js
  load: once( () => contents )
```

**Comment by TrySound** [comment]
@Victorystick Nope it's just a helper for tools like gulp. But maybe in future if it will be need I will add other features or somebody make pr :).
Oh, exacly :)
