### ISSUE TITLE
Install and use Rollup locally

### ISSUE THREAD

**Issue by mesqueeb** [rollup/rollup#2720]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The documentation says [here](https://rollupjs.org/guide/en#creating-your-first-bundle):
> (later on we'll learn how to install it locally to your project so that your build process is portable, but don't worry about that yet)

However, I searched and searched and couldn't find anywhere in the documentation that explains how to do this! 😂

### Your Proposal for Changes

Add a section on how to install and use rollup in a project locally.

### Other

(PS: I'm also having a hard time finding how to do this on Google even! If anyone can help me out with some sweet advice, that would be great!! 🎯)

**Comment by ashubham** [comment]
You can use this project as a starter https://github.com/rollup/rollup-starter-app

Basically,
`npm i --save-dev rollup` This will install it locally in your `node_modules`
Now you can run it:
`./node_modules/.bin/rollup -c` OR you can add a script in the `package.json` as mentioned in the `package.json` of the above project.

**Comment by ScottA38** [comment]
@ashubham your suggestion was very helpful to me but I also just found that you can run node exectuables more cleanly with `npx --no-install [executable]` (so npx --no-install rollup). 

Technically this is off-topic as I arrived here due to the same issue as @mesqueeb explained but anyway..

**Comment by mesqueeb** [comment]
What does `--no-install` do? 👨🏻‍🚀

BTW, I still believe that the Rollup docs should be updated !!! It's been almost an entire quarter of a year.

Anyway I could help make a PR?

**Comment by lukastaegert** [comment]
> Anyway I could help make a PR?

Yes, please! At the moment, this project is solely maintained by people who work on it in their spare time. Helping with documentation is an easy way to contribute that makes a big difference and is very much appreciated!

**Comment by ScottA38** [comment]
@mesqueeb [npx](https://www.npmjs.com/package/npx) searches for a node executable locally and if it can't find it tries to download it by default. 

In order to prevent it from downloading unwanted packages/versions via your project's scripts or if you happen to be outside of the correct npm directory for a moment it is a safety net to use --no-install to prevent automatic install

**Comment by mesqueeb** [comment]
hi everyone. I added the PR! see #2995

**Comment by mesqueeb** [comment]
@ashubham 
This comment says that your proposed method of using rollup locally is not correct:
https://github.com/rollup/rollup/pull/2995#discussion_r303200518

and mentions down below another method:
https://github.com/rollup/rollup/pull/2995#discussion_r303202430

Can you please advise on how I should update my PR, since I originally used the info you gave me in this thread.

I'd like to get this PR merged, because Rollup has had this [written in the docs](https://rollupjs.org/guide/en#creating-your-first-bundle):
> (later on we'll learn how to install it locally to your project so that your build process is portable, but don't worry about that yet)

For several years, but still has 0 information on how to do this...... I'm sure a lot of newer developers need some extra help on this!!!

**Comment by ashubham** [comment]
@mesqueeb What @TrySound  suggested on the Thread is better and is portable/future proof. So I would suggest going with `npm run rollup` instead of `node_modules/.bin/rollup`

**Comment by mesqueeb** [comment]
Shellscape thanks so much. I can't wait until this goes live !!!

**Comment by shellscape** [comment]
@mesqueeb thank you for starting the PR!
