### ISSUE TITLE
Default export in not available in scope

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#2722]
Upgraded to new rollup version and got this stopped working
```js
export default class Image {}
export { Image }
```

- Rollup Version: 1.3.0
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

https://rollupjs.org/repl?version=1.3.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMEltYWdlJTIwJTdCJTdEJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBJbWFnZSUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior

Not error

### Actual Behavior

Export 'Image' is not defined

**Comment by lukastaegert** [comment]
Seems to be a regression of the refactored scope-hoisting in 1.2.0

**Comment by lukastaegert** [comment]
Turns out this is caused by the updated acorn version and needs to be resolved there: acornjs/acorn#811

**Comment by TrySound** [comment]
Cool thanks!
