### ISSUE TITLE
Official/documented way to get a list of all sources that contributed to a bundle

### ISSUE THREAD

**Issue by coreyfarrell** [rollup/rollup#2725]
### Feature Use Case

I created [vinyl-rollup](https://github.com/cfware/vinyl-rollup) which takes rollup options to create a new gulp stream.  This module currently looks at `bundle.cache.modules` to find a list of all `node_modules` that were bundled so greenkeeper yelled at me when `rollup@1.2.5` was released last night.  If a bundle contains `node_modules/some-web-component/index.js`, then by default `package.json` and any license file from `node_modules/some-web-component` is added to the gulp stream so they can be distributed in `dist/node_modules/**`.  In addition `vinyl-rollup` can be configured to copy the entire modules, I do this so that I can strip `sourcesContent` from the sourcemap (the `sources` points to files which are available via web).

### Feature Proposal

I'd like to request an official / semver covered property to retrieve a complete list of all sources that were added to the bundle.  In rollup-1.3.0 the following function gives me the result I need:
```js
function bundleGetSourceList(modules) {
	const files = new Set();

	modules.forEach(mod => {
		Object.values(mod.resolvedIds).forEach(({id}) => {
			files.add(id);
		});
	});

	return files;
}
```

In this example I'm using a `Set` to strip duplicate filenames from the result.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
