### ISSUE TITLE
Make a bundle only when some of the source files changed

### ISSUE THREAD

**Issue by egnartsms** [rollup/rollup#2731]
### Feature Use Case
I need to run a NodeJS script that does some auxiliary internal processing. My project is built with ES6 modules (imports/export) so I first have to create this script as a CommonJS bundle that's subsequently fed to node to run. (node --experimental-modules is out of option because of its own drawbacks.) 

Now, I don't want to build that script bundle each time I want to run it. I want it to be re-created only when any of the dependent .js modules (source files) changed. It's not currently possible with Rollup as far as I'm aware, and it's not possible to do with any of gulp plugins since the set of dependent modules is not statically specified: it can only be determined by Rollup since Rollup reads all the imports and can track dependencies.

### Feature Proposal
Add a command-line option (and JS API option) to compare the timestamp of the destination bundle (if it already exists at the time of Rollup invokation) with the timestamps of all the source files (modules), and in case the timestamp of the bundle is newer than all the source timestamps, don't do anything.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
