### ISSUE TITLE
Generate sourcemaps but omit the comment

### ISSUE THREAD

**Issue by syranide** [rollup/rollup#2743]
### Feature Use Case
When deploying to production we want to have sourcemaps for debuggability, but we do not want to expose the source maps to the public.

### Feature Proposal
So I would like to have a way of generating sourcemaps but not having the sourcemap comment be written to the output. I petitioned Webpack a long time ago and they introduced the `hidden-` prefix to their sourcemap modes. But maybe it makes more sense to have a separate property which controls whether the sourcemap comment is written or not.

**Comment by shellscape** [comment]
Hey folks. We'd welcome if someone stepped up to own this feature request. If it doesn't get any traction over the next month or so, we'll likely close it.

**Comment by rohitmohan96** [comment]
@shellscape I'd like to give this a try. Should it be similar to inline where we can have `sourcemap: 'hidden'` to not add a comment in the output file? Or should it be a new option?
