### ISSUE TITLE
Imported closure interfaces are tree shaked and cannot be resolved by Closure Compiler

### ISSUE THREAD

**Issue by VSjolund** [rollup/rollup#2746]
- Rollup Version: 1.6.0
- Operating System (or Browser): Ubuntu 18.04
- Node Version: 11.2.0

### How Do We Reproduce?

Clone [this](https://github.com/villzor/rollup-closure-type-bug) repository, then run 
```js
npm i && npm run build
```

### Expected Behavior
The imported interfaces are kept as they are referenced to in `/** @type {} */` clauses, or there is some way to tell Rollup not to strip unused imports, or force imports to be kept using some syntax similar to `/*@__PURE__*/`.

### Actual Behavior
I couldn't find any way to stop Rollup from stripping these imports as they are not used anywhere in the code, they're only referenced to in JSDOC comments.

### Illustrated fix
Run 
```js
npm run fix
```
Which includes the missing interface, and Closure can then successfully resolve it (the warning is gone).

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
