### ISSUE TITLE
Rollup Doesn't Correctly Bundle Protobufjs

### ISSUE THREAD

**Issue by mmacfadden** [rollup/rollup#2747]
- Rollup Version: 1.4.1
- Operating System (or Browser): Linux / Chrome
- Node Version: 10.10

### How Do We Reproduce?
I have created a repo which demonstrates the issue here:
https://github.com/mmacfadden/rollup-protobufjs

There are instructions in the readme of the Repo.

### Expected Behavior
The generated UMD module is usable.

### Actual Behavior
```js
Uncaught TypeError: Cannot read property 'emptyArray' of undefined
   at types.js:110
   at createCommonjsModule (index.umd.js:10)
   at index.js:65
   at index.umd.js:4
   at index.umd.js:5
```
An exception is thrown to the console when merely loading the bundle, before even using it. The issue seems to be that an object is being referenced in the resulting bundle before the object itself is being created. I suspect this has to do with resolution of circular dependencies.

I noted that protobufjs seems to have a browserify'ed version of the library already bundles, and I have used this browser version before, through hotlinking, however I would like to actually bundle protobufjs up in my library now, and it this issue.

**Comment by LarsDenBakker** [comment]
Rollup only bundles es modules. `protobufjs` is not an es module, I see that you're using the `commonjs` plugin to handle this so I think the issue should be posted there: https://github.com/rollup/rollup-plugin-commonjs

**Comment by mmacfadden** [comment]
@LarsDenBakker I can cross-post over there as well.  Probably a good idea. But it isn't clear to me, just yet, if the issue is in the conversion from CommonJS to an ES Module in the plugin or in the bundling by rollup after that conversion. The problem could be in either spot.

**Comment by mmacfadden** [comment]
FYI I also tried `rollup-plugin-cjs-es`, instead of `rollup-plugin-commonjs` which also did not work.

**Comment by kirillovdm** [comment]
@mmacfadden any success with this staff?

**Comment by eight04** [comment]
You have to break some circular dependencies on the critical path:
```diff
diff --git a/index.js b/index.js
index 2383a47..715621e 100644
--- a/index.js
+++ b/index.js
@@ -1,9 +1,9 @@
-import * as protobuf from "protobufjs/light";
-import * as awesome from "./awesome.json";
+const protobuf = require("protobufjs/light");
+const awesome = require("./awesome.json");
 
 const root = protobuf.Root.fromJSON(awesome);
 
-export function toMessage(awesomeField) {
+function toMessage(awesomeField) {
   // Obtain a message type
   const AwesomeMessage = root.lookupType("AwesomeMessage");
 
@@ -22,4 +22,6 @@ export function toMessage(awesomeField) {
   const buffer = AwesomeMessage.encode(message).finish();
 
   return buffer;
-}
\ No newline at end of file
+}
+
+module.exports = {toMessage};
diff --git a/package.json b/package.json
index fb4aef3..c8562a0 100644
--- a/package.json
+++ b/package.json
@@ -16,8 +16,11 @@
   "devDependencies": {
     "protobufjs": "^6.8.8",
     "rollup": "^1.6.0",
+    "rollup-plugin-cjs-es": "^0.9.0",
     "rollup-plugin-commonjs": "^9.2.1",
     "rollup-plugin-json": "^3.1.0",
-    "rollup-plugin-node-resolve": "^4.0.1"
-  }
+    "rollup-plugin-node-resolve": "^4.0.1",
+    "rollup-plugin-re": "^1.0.7"
+  },
+  "dependencies": {}
 }
diff --git a/rollup.config.js b/rollup.config.js
index d4c4dec..76aa576 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -1,5 +1,6 @@
 import resolve from 'rollup-plugin-node-resolve';
-import commonjs from 'rollup-plugin-commonjs';
+import re from "rollup-plugin-re";
+import cjs from 'rollup-plugin-cjs-es';
 import json from "rollup-plugin-json";
 
 export default [
@@ -25,8 +26,22 @@ export default [
         jsnext: true,
         main: true
       }),
-      commonjs(),
-      json()
+      json(),
+      re({
+        patterns: [
+          {
+            match: /types\.js$/,
+            test: /util\.emptyArray/,
+            replace: "Object.freeze ? Object.freeze([]) : []"
+          },
+          {
+            match: /root\.js/,
+            test: /util\.path\.resolve/,
+            replace: "require('@protobufjs/path').resolve"
+          }
+        ]
+      }),
+      cjs({nested: true}),
     ]
   }
 ];

```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by chenguangming** [comment]
> You have to break some circular dependencies on the critical path:
> 
> ```diff
> diff --git a/index.js b/index.js
> index 2383a47..715621e 100644
> --- a/index.js
> +++ b/index.js
> @@ -1,9 +1,9 @@
> -import * as protobuf from "protobufjs/light";
> -import * as awesome from "./awesome.json";
> +const protobuf = require("protobufjs/light");
> +const awesome = require("./awesome.json");
>  
>  const root = protobuf.Root.fromJSON(awesome);
>  
> -export function toMessage(awesomeField) {
> +function toMessage(awesomeField) {
>    // Obtain a message type
>    const AwesomeMessage = root.lookupType("AwesomeMessage");
>  
> @@ -22,4 +22,6 @@ export function toMessage(awesomeField) {
>    const buffer = AwesomeMessage.encode(message).finish();
>  
>    return buffer;
> -}
> \ No newline at end of file
> +}
> +
> +module.exports = {toMessage};
> diff --git a/package.json b/package.json
> index fb4aef3..c8562a0 100644
> --- a/package.json
> +++ b/package.json
> @@ -16,8 +16,11 @@
>    "devDependencies": {
>      "protobufjs": "^6.8.8",
>      "rollup": "^1.6.0",
> +    "rollup-plugin-cjs-es": "^0.9.0",
>      "rollup-plugin-commonjs": "^9.2.1",
>      "rollup-plugin-json": "^3.1.0",
> -    "rollup-plugin-node-resolve": "^4.0.1"
> -  }
> +    "rollup-plugin-node-resolve": "^4.0.1",
> +    "rollup-plugin-re": "^1.0.7"
> +  },
> +  "dependencies": {}
>  }
> diff --git a/rollup.config.js b/rollup.config.js
> index d4c4dec..76aa576 100644
> --- a/rollup.config.js
> +++ b/rollup.config.js
> @@ -1,5 +1,6 @@
>  import resolve from 'rollup-plugin-node-resolve';
> -import commonjs from 'rollup-plugin-commonjs';
> +import re from "rollup-plugin-re";
> +import cjs from 'rollup-plugin-cjs-es';
>  import json from "rollup-plugin-json";
>  
>  export default [
> @@ -25,8 +26,22 @@ export default [
>          jsnext: true,
>          main: true
>        }),
> -      commonjs(),
> -      json()
> +      json(),
> +      re({
> +        patterns: [
> +          {
> +            match: /types\.js$/,
> +            test: /util\.emptyArray/,
> +            replace: "Object.freeze ? Object.freeze([]) : []"
> +          },
> +          {
> +            match: /root\.js/,
> +            test: /util\.path\.resolve/,
> +            replace: "require('@protobufjs/path').resolve"
> +          }
> +        ]
> +      }),
> +      cjs({nested: true}),
>      ]
>    }
>  ];
> ```

it's works, thank you very much!

**Comment by HAHAHA44** [comment]
After I update my rollup to `v2.23.0` and using @rollup/plugin-commonjs, the issue is fixed.

The most important is that I set the transformMixedEsModules to true.
`commonjs({
      transformMixedEsModules: true,
    }),`

**Comment by lukastaegert** [comment]
We are finalizing a new version of the commonjs plugin in rollup/plugins#1038. It is pre-published as @rollup/plugin-commonjs@beta. Please give it a spin to see if it resolves the issue, ideally without additional config needed.

**Comment by 3Nigma** [comment]
> We are finalizing a new version of the commonjs plugin in [rollup/plugins#1038](https://github.com/rollup/plugins/pull/1038). It is pre-published as @rollup/plugin-commonjs@beta. Please give it a spin to see if it resolves the issue, ideally without additional config needed.

I can confirm that the `beta` release does fix the `protobuf.js` bundeling on my end. Thank you! 👏
