### ISSUE TITLE
Reserve __PURE__ comment in bundled file

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2749]
### Feature Use Case

input.js:
```js
export { a } from './ab.js';
export const c = {};
```

ab.js:
```js
export const a = /*#__PURE__*/ function () {
    return Object.freeze(Object.create(null));
} ();
export const b = /*#__PURE__*/ function () {
    return Object.freeze(Object.create(null));
} ();
```

output as util.js:
```js
export const a = function () {
    return Object.freeze(Object.create(null));
} ();
export const c = {};
```

which will get bad tree-shake result in further bundling:

input.js:
```js
export { c } from './util.js';
```

final output:
```js
! function () {
    return Object.freeze(Object.create(null));
} ();
export const c = {};
```

### Feature Proposal

output util.js:
```js
export const a = /*#__PURE__*/ function () {
    return Object.freeze(Object.create(null));
} ();
export const c = {};
```

then final output:
```js
export const c = {};
```

**Comment by lukastaegert** [comment]
Actually, this should already work as expected. Preserving unconsumed comments was an important goal for Rollup's implementation of pure comments:

https://rollupjs.org/repl?version=1.6.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZhYi5qcyclM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBjJTIwJTNEJTIwJTdCJTdEJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYWIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBhJTIwJTNEJTIwJTJGKiUyM19fUFVSRV9fKiUyRiUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwT2JqZWN0LmZyZWV6ZShPYmplY3QuY3JlYXRlKG51bGwpKSUzQiU1Q24lN0QlMjAoKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMGIlMjAlM0QlMjAlMkYqJTIzX19QVVJFX18qJTJGJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBPYmplY3QuZnJlZXplKE9iamVjdC5jcmVhdGUobnVsbCkpJTNCJTVDbiU3RCUyMCgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

Are there any other plugins involved in your setup that might remove comments? Also I am curious about your output:

```js
export const a = function () {
    return Object.freeze(Object.create(null));
} ();
export const c = {};
```

This is not the kind of output that Rollup usually creates. As you can see from the REPL link, Rollup always places exports at the end, i.e.

```js
const a = /*#__PURE__*/ function () {
    return Object.freeze(Object.create(null));
} ();

const c = {};

export { c, a };
```

Not sure we are seeing a Rollup issue here.

**Comment by LongTengDao** [comment]
@lukastaegert 

The "output" is written by hand, because the actual code is huge.

I tried again, and you are right.
So strange... It seems that I need to preserve the scene of the accident carefully next time.

I'll close this issue, until I meet this problem next time.
Thank you.

BTW: The repl feature you given is so cool! And you always found all things looks suspicious, admire+1

**Comment by LongTengDao** [comment]
I found the reason. The `/*#__PURE__#/` was dropped by `require('typescript').transpileModule`.

**Comment by everlose** [comment]
> 

I also have such a problem. Did you finally solve it and how did you do it

**Comment by everlose** [comment]
> I found the reason. The `/*#__PURE__#/` was dropped by `require('typescript').transpileModule`.

I also have such a problem. Did you finally solve it and how did you do it
