### ISSUE TITLE
[browser] process is not defined

### ISSUE THREAD

**Issue by aeosynth** [rollup/rollup#275]
rollup@0.20.5, using rollup.browser.js:

    rollup.rollup({entry: 'index.js'})
    Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
    defaults.js:22 Uncaught (in promise) ReferenceError: process is not defined(…)

there is no documentation on how to use the browser build, so maybe i'm doing something wrong

**Comment by Victorystick** [comment]
Indeed. Rollup's browser build doesn't get that much love. It looks like we've clumsily added a call to `process.cwd()` in defaults.js. We'll have to change that.

**Comment by Rich-Harris** [comment]
You probably need to specify a loader plugin – here's [how it's used on rollupjs.org](https://github.com/rollup/rollupjs.org/blob/367292f35958093cbb30e62bef37832443c5033d/src/app/main.js#L77-L94) (loading modules from memory). Without that, it falls back to trying to resolve against `process.cwd()`, which I suspect is the source of that error.

We should

* [ ] have a better error message
* [ ] update the documentation
