### ISSUE TITLE
Tree-shaking includes not imported class

### ISSUE THREAD

**Issue by 2beers** [rollup/rollup#2759]
- Rollup Version: 1.6.0
- Operating System (or Browser): Any browser
- Node Version: 10.15.0

### How Do We Reproduce?

`sdk.js` imports and exports `class A` from `a.js`; 
`main.js` imports `class A` from `sdk.js`;
`sdk.js` also contains code for `class B`.
`main.js` imports only `class A` but the resulted bundle also contains the code for `class B`
Link to [repl](https://rollupjs.org/repl?version=1.6.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QkElN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnNkayU1QyUyMiUzQiU1Q25jb25zdCUyMGElMjAlM0QlMjBuZXclMjBBKCklM0IlNUNuYS5vdXQoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY2xhc3MlMjBBJTdCJTVDbiU1Q3RvdXQoKSU3QiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKCU1QyUyMkElNUMlMjIpJTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNkay5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JBJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZhJTVDJTIyJTNCJTVDbiU1Q25jbGFzcyUyMEIlN0IlNUNuJTVDdG91dCgpJTdCJTVDbiU1Q3QlNUN0Y29uc29sZS5sb2coJTVDJTIyQSU1QyUyMiklM0IlNUNuJTVDdCU3RCU1Q24lN0QlNUNuY29uc3QlMjBiJTIwJTNEJTIwbmV3JTIwQigpJTNCJTVDbmIub3V0KCklM0IlNUNuJTVDbmV4cG9ydCUyMCU3QkElN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior
The bundle should be without `class B` included

### Actual Behavior
`class B` is included

Not sure if this is a bug or it's the expected behavior. By my  logic `class B` should not be included in the bundle.

**Comment by lukastaegert** [comment]
This is expected and correct behaviour. The problem is that sdk.js instantiates B and calls a method on it. The method has the very real side-effect of logging to the console which is why Rollup does not remove it. But even if this was not the case, Rollup would still retain the code because it cannot resolve class methods to determine if they have side-effects. If you remove the call to `b.out()`, `B` will be removed.

**Comment by lukastaegert** [comment]
By the way, tree-shaking has very little to do with imports and only with side-effects. This is a very common misconception which unfortunately keeps being propagated. The reason it works better with ES modules is because they allow side-effects detection to work across module boundaries.

**Comment by 2beers** [comment]
Thanks. That makes sense and I think I understand the  behavior .
