### ISSUE TITLE
Allow input contains syntaxes that babel supported.

### ISSUE THREAD

**Issue by hackwaly** [rollup/rollup#276]
I'd like to use rollup first then babel. This can reduce duplicates of babel helpers.
Can we switch parser to babylon to accept more syntaxes such as jsx, flow and so on?
BTW. Currently rollup rejects syntax  static member in class definition.

**Comment by Victorystick** [comment]
What you want is [`rollup-plugin-babel`](https://github.com/rollup/rollup-plugin-babel). It is the recommended solution to remove all duplicates of babel helpers while also accepting any new syntax. In the *Why?* section you can read about why this is better than running them one after the other.

**Comment by hackwaly** [comment]
Somtimes people just want to bundle es6 sources only and do not transpile them. Consider that currently chrome and node have supported a lot of es6 features.
Maybe we need to add a options to rollup to allow pass the parser impl in. I think this is not difficult. These es parser library use same or compatible AST format. So we can make the parser dependency as an optional dependency.

**Comment by TrySound** [comment]
@hackwaly You always can create own plugin for such syntaxes

**Comment by hackwaly** [comment]
I have read the plugin documentation https://github.com/rollup/rollup/wiki/Plugins

Yes it allows we transform any source file (such as coffeescript) to es6. But it limited that the plugin transoform from source to source, not from source to ast. So if the transformed code using some es6 feature that acorn not reconginzed, rollup will not work.

Thus, rollup is limited to output es6 source contains limited es6 feature set.

**Comment by Rich-Harris** [comment]
> Consider that currently chrome and node have supported a lot of es6 features.

What ES6 features are supported by Chrome but not Acorn?

**Comment by hackwaly** [comment]
Sorry, I'm wrong. Acorn support all ES6 features exactly. The features I used which acorn not supported is not in ES6. So, keep using acron do the best. It's parsing speed is incredible fast.
