### ISSUE TITLE
Version 1.5.0 broke rollup plugin rebase v1

### ISSUE THREAD

**Issue by bdwain** [rollup/rollup#2762]
- Rollup Version: 1.5.0 (still broken in latest)
- Operating System (or Browser): Mac Mojave Latest Chrome
- Node Version: 10

### How Do We Reproduce?

I made a reproduction of the issue here. https://github.com/bdwain/rollup-1.5-issue

### Expected Behavior
the import statement in the generated index file should be 

`import _hjhCwK from './dog_hjhCwK.jpg';`

you can bring this behavior back by downgrading rollup to `1.4.x`

### Actual Behavior
the import statement in the generated index file is

`import _hjhCwK from '../../dog_hjhCwK.jpg';`

The plugin I am using is https://github.com/sebastian-software/rollup-plugin-rebase/tree/1.1.0

I know there is a newer version of it, but I've had issues with it so I'm still on v1.

**Comment by lukastaegert** [comment]
I started looking into this and there is definitely a change in resolution behaviour for Rollup that could be an unintended bug. Will continue investigating.

**Comment by lukastaegert** [comment]
Yes, definitely a bug

**Comment by lukastaegert** [comment]
Fix at #2774

**Comment by bdwain** [comment]
Thanks!
