### ISSUE TITLE
REPL website is broken

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#2763]
1. Chrome 72.0.3626.121 (Official Build) (64-bit)
2. Open the REPL page at https://rollupjs.org/repl
3. Select any example (e.g. Tree Shaking)
4. Notice that top-right displays an error "Error: You must supply options.input to rollup"

It's not clear how (or whether it's possible) to specify `options.input` on this page. Maybe this is a usability problem but I suspect the actual page is broken.

**Comment by lukastaegert** [comment]
I cannot confirm this on my system using Chrome 72. Maybe there is an issue with the Service Worker. If you clear all site data (Dev tools > Application > Clear site data), does the problem persist?

**Comment by cowwoc** [comment]
@lukastaegert Yes. That did it :) Thank you!
