### ISSUE TITLE
Incorrect circular dependency warning when forward-declaring export

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#2764]
- Rollup Version: 1.6.0
- Operating System (or Browser): Microsoft Windows [Version 10.0.17763.379]
- Node Version: v10.15.1

### How Do We Reproduce?

As mentioned at https://github.com/rollup/rollup/issues/2763 I believe the REPL website is broken but here is my testcase nonetheless:

https://rollupjs.org/repl?version=1.7.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMENsYXNzQSUyMGZyb20lMjAnLiUyRkNsYXNzQS5qcyclNUNuaW1wb3J0JTIwQ2xhc3NCJTIwZnJvbSUyMCcuJTJGQ2xhc3NCLmpzJyUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMkNsYXNzQS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBDbGFzc0IlMjBmcm9tJTIwJy4lMkZDbGFzc0IuanMnJTVDbiU1Q25sZXQlMjBGb3J3YXJkRGVjbGFyYXRpb24lM0IlNUNuZXhwb3J0JTIwJTdCRm9yd2FyZERlY2xhcmF0aW9uJTIwYXMlMjBkZWZhdWx0JTdEJTNCJTVDbiU1Q25jbGFzcyUyMENsYXNzQSU1Q24lN0IlNUNuJTIwJTIwY3JlYXRlQigpJTVDbiUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBuZXclMjBDbGFzc0IoKSUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q3QlNUN0JTVDbkZvcndhcmREZWNsYXJhdGlvbiUyMCUzRCUyMENsYXNzQSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJDbGFzc0IuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQ2xhc3NBJTIwZnJvbSUyMCcuJTJGQ2xhc3NBLmpzJyU1Q24lNUNubGV0JTIwRm9yd2FyZERlY2xhcmF0aW9uJTNCJTVDbmV4cG9ydCUyMCU3QkZvcndhcmREZWNsYXJhdGlvbiUyMGFzJTIwZGVmYXVsdCU3RCUzQiU1Q24lNUNuY2xhc3MlMjBDbGFzc0IlNUNuJTdCJTVDbiUyMCUyMGNyZWF0ZUEoKSU1Q24lMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwbmV3JTIwQ2xhc3NBKCklM0IlNUNuJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNuRm9yd2FyZERlY2xhcmF0aW9uJTIwJTNEJTIwQ2xhc3NCJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

In case that doesn't work, here is the code:

main.js
```
import ClassA from './ClassA.js'
import ClassB from './ClassB.js'
```

ClassA.js
```
import ClassA from './ClassA.js'

let ForwardDeclaration;
export {ForwardDeclaration as default};

class ClassA
{
  ClassB createB()
  {
    return new ClassB();
  }
}

ForwardDeclaration = ClassA;
```

ClassB.js
```
import ClassB from './ClassB.js'

let ForwardDeclaration;
export {ForwardDeclaration as default};

class ClassB
{
  ClassA createA()
  {
    return new ClassA();
  }
}

ForwardDeclaration = ClassB;
```

### Expected Behavior
No circular dependency warning.

### Actual Behavior
Warning even though no circular dependency occurs.

**Comment by cowwoc** [comment]
Oops. The testcase I posted above fails at runtime.

Here is an updated testcase that does not (and still gets circular dependency warnings):

ClassA.js

```
import {ClassB} from './ClassB.js'

var ForwardDeclaration;

function initExports()
{
	if (ForwardDeclaration)
		return;

	class ClassA
	{
	  ClassB createB()
	  {
	    return new ClassB();
	  }
	}

	ForwardDeclaration = ClassA;
}

initExports();

export {ForwardDeclaration as ClassA, initExports};
```

ClassB.js

```
import {ClassA, initExports as declareSuperclass} from './ClassA.js'

var ForwardDeclaration;

function initExports()
{
	if (ForwardDeclaration)
		return;
        declareSuperclass();

	class ClassB extends ClassA
	{
	}

	ForwardDeclaration = ClassB;
}

initExports();

export {ForwardDeclaration as ClassB, initExports};
```

**Comment by lukastaegert** [comment]
Ok, but there IS a circular dependency in the static import graph, and this is what the warning is all about. This warning is not about accessing any imports (which can only be determined at runtime anyway) but simply about their existence.

If you want to hide the warning, you can add a filtering `onwarn` handler to your config like this:

```js
// rollup.config.js
export default {
  onwarn(warning, warn) {
    if (warning.code !== 'CIRCULAR_DEPENDENCY') {
      // this sends the warning back to Rollup's internal warning handler
      warn(warning);
    }
  },
  // other options
}
```

**Comment by cowwoc** [comment]
Makes sense I guess... Closing this issue.
