### ISSUE TITLE
acorn-bigint in rollup throw error when meat hex

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2766]
- Rollup Version: 1.4.1
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

_config.js:

```js
'use strict';

var { rollup } = require('rollup');
var AcornBigint = require('acorn-bigint');
var Acorn = require('acorn');

try { [...Acorn.Parser.extend(AcornBigint).tokenizer('0x80')]; }
catch(error){ var errorBelongToPlugin = true; }

errorBelongToPlugin || rollup({
  input: __dirname+'/main.js',
  acornInjectPlugins: [AcornBigint],
}).catch(console.error);
```

main.js:

```js
export default 0x80;
```

### Expected Behavior

no error

### Actual Behavior

```toml
stack = '''
Error: Unexpected token
    at error (rollup/dist/rollup.js:3601:30)
    at Module.error (rollup/dist/rollup.js:14470:9)
    at tryParse (rollup/dist/rollup.js:14390:16)
    at Module.setSource (rollup/dist/rollup.js:14664:35)
    at rollup/dist/rollup.js:17882:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)'''

code = 'PARSE_ERROR'

pos = 15

loc.column = 15

loc.file = '/main.js'

loc.line = 1

loc.frame = '''
1: export default 0x80;
                  ^'''
```

**Comment by LongTengDao** [comment]
@lukastaegert Oh, sorry, I might be self-defeating...

My example codes is not a rollup-test-format test, it's just a code (directly run), whose names are `_config.js` and `main.js`...

**Comment by LongTengDao** [comment]
@lukastaegert error only happen when meat hex number, like `0x80`.

**Comment by lukastaegert** [comment]
You checked that you are using the correct Rollup import (see above)?
Does the sample code from the test file compile correctly for you: https://github.com/rollup/rollup/blob/master/test/form/samples/big-int/main.js ?

The error is thrown by acorn, not Rollup. I am not too familiar with Bigint but if your code is indeed correct, then the only explanation is that the plugin is not working correctly. To my knowledge, this should only happen for the browser build UNLESS there is more than one copy of acorn in your node_modules folder or you have more than one node_modules folders.

In such a situation, acorn plugins may not work as well. This is something that acorn has messed up in a fundamental way and neither Rollup nor Acorn could easily fix this.

**Comment by lukastaegert** [comment]
Actually, your code does not look correct to me. According to the spec https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt there are only two ways to create a bigint:
- a literal number with an `n` at the end: `123n`
- via the `BigInt` function: `BigInt('0x80')`

Your example matches neither case.

**Comment by LongTengDao** [comment]
@lukastaegert Oh, yes! I have two node_modules/acorn... What a racking-brain situation!

And I changed to use rollup of latest 1.7.0.

Now problem disappear. I don't know which resolved this.

> Actually, your code does not look correct to me.

I was meaning no other than `0x80`, which cause an error, not `0x80n`. (when using acorn-bigint, bigint parsing is right, but hex number parsing wrong)

**Comment by shiyafei** [comment]
I also encountered the same problem, how can I solve it
