### ISSUE TITLE
Watch files with Interfaces (rollup-plugin-typescript2)

### ISSUE THREAD

**Issue by gribanov2la** [rollup/rollup#2767]
- Rollup Version: 1.7.0
- Operating System (or Browser): Ubuntu 16.04.5 LTS
- Node Version: 8.1.0

### How Do We Reproduce?

Run `rollup -c -w`

```
//index.ts
import ITest from './TestInterface';

class Test implements ITest {
    public log() {
        window.console.log(1);
    }
}

const test = new Test();
test.log();

// TestInterface.ts
export default interface ITest {
    log(): void;
}

//rollup.config.js
const typescript2Plugin = require('rollup-plugin-typescript2');

module.exports = {
	input: './src/index.ts',
	output: [{
		file: 'dist/bundle.js',
		sourcemap: true,
		name: 'my_bundle',
		format: 'umd'
	}],
	plugins: [
		typescript2Plugin({
			tsconfig: './tsconfig.json',
			useTsconfigDeclarationDir: true
		})
	]
};
```

### Expected Behavior

When changing the file "TestInterface.ts" watcher does not work, but when changing "index.ts" everything is OK

### Actual Behavior

When changing the file "TestInterface.ts" watcher do work.

Perhaps the problem is related to some kind of optimization and compilation in TS. I would like to be able to track all files, even if they do not perform any actions (as interfaces)

**Comment by lukastaegert** [comment]
I would assume this is not a rollup issue but an issue for rollup-plugin-typescript2 and is not fixable from within Rollup. To fix this issue, I guess rollup-plugin-typescript2 needs to use the this.addWatchFile plugin hook https://rollupjs.org/guide/en#this-addwatchfile-id-string-void
to watch additional interface files. Rollup does not understand TypeScript and can only handle what it is provided by the plugin.

**Comment by gribanov2la** [comment]
Thanks! I will try to solve this problem in this way.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
