### ISSUE TITLE
Break label is re-named wrongly

### ISSUE THREAD

**Issue by luwes** [rollup/rollup#2773]
- Rollup Version: 1.7.0
- Operating System (or Browser): Chrome
- Node Version: 10.14.1

### How Do We Reproduce?

Check out this repl.

https://rollupjs.org/repl?version=1.7.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG4lMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGVfMSclM0IlNUNuaW1wb3J0JTIwJTdCJTIwbiUyMGFzJTIweCUyMCU3RCUyMGZyb20lMjAnLiUyRm1vZHVsZV8yJyUzQiU1Q24lNUNuY29uc29sZS5sb2cobiUyQyUyMHgpJTNCJTVDbiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjB2YXIlMjBuJTIwJTNEJTIwMSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMG4oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBuJTNBJTIwaWYlMjAod2hhdGV2ZXIoKSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTVDdGJyZWFrJTIwbiUzQiUyMCUyRiUyRiUyMHRoaXMlMjBzaG91bGQlMjBiZSUyMG4lMkMlMjBub3QlMjBuJTI0MSU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior

It shouldn't get that extra $1 suffix. Break label should keep the same name.

### Actual Behavior

A break label with the same name as a duplicate module (needs a $1 suffix) gets renamed with that same suffix.

**Comment by lukastaegert** [comment]
Fix at #2776
