### ISSUE TITLE
this in class fields is misinterpreted

### ISSUE THREAD

**Issue by coreyfarrell** [rollup/rollup#2775]
- Rollup Version: 1.7.0
- Operating System (or Browser): Fedora building for Chrome 72+
- Node Version: 10.15.0

### How Do We Reproduce?

Minimum reproduction is at https://github.com/coreyfarrell/rollup-class-fields (I was not able to figure out how to add an acorn parser with REPL).  `rollup.config.js` demonstrates the issue (produces `broken.js`), `rollup.workaround.js` shows how I'm dealing with this for now, produces `workaround.js`.  Rollup can be run against both configs using `npm install && npm test`.

### Expected Behavior

The `this` keyword found anyplace within a class body should not be considered top-level.  For static class fields `this` is the class, for public class fields it refers to the instance.

### Actual Behavior

`this` in the following code gets replaced with `undefined`:
```js
class Example {
  a = 1;
  b = this.a + 1;
}
```

**Comment by lukastaegert** [comment]
Not sure if this should be classified as a bug or an enhancement as it only manifests with the stage-3 class fields proposal but I definitely see your point that this should be fixed as this feature is rather certain to become official at some point.

**Comment by GrosSacASac** [comment]
In the mean time you can use the standard syntax
```
class Example {
  constructor () {
       this.a = 1;
       this.b = this.a + 1;
  }
}
```
