### ISSUE TITLE
Getting around Tree Shaking between different Packages (e.g., monorepo)

### ISSUE THREAD

**Issue by Apidcloud** [rollup/rollup#2777]
Hello!

I'm trying to understand if tree shaking should work under a certain scenario. I didn't ask this on gitter because it's quite long, and stackoverflow seems to be dead lately. I originally tried this with webpack but the behaviour isn't what I expected, so I'm trying to determine if the tree shaking from rollup approaches the scenario below in a different way.

## Scenario - min repro [here](https://github.com/Apidcloud/tree-shaking-webpack)

- Multiple (library) packages (e.g., monorepo). 

- Each of them is bundled individually through a single entry point `index.js` which re-exports everything.

- They can depend on each other. e.g., package `A` can import what it needs from package `B` (`cube`). That is, only 1 of the functions available.

## Package A
![image](https://user-images.githubusercontent.com/3720818/54906586-30ff7b80-4ea9-11e9-85bd-a8a4b4ba260e.png)

## Package B
![image](https://user-images.githubusercontent.com/3720818/54906543-188f6100-4ea9-11e9-849d-f54f5ca46845.png)

How does rollup approach this? Shouldn't tree shaking (or dead code elimination) avoid including every function exported by package `B` (in this case, `unusedFn`) within package `A` bundle?

Am I thinking about it wrong? Or does this scenario need a different approach?

Thank you! 🙇

**Comment by lukastaegert** [comment]
It sounds like Rollup might solve your problem though not via tree-shaking but simply via the way code-splitting works (though tree-shaking would still apply). I recently wrote an article that goes into some detail about this very topic that might be interesting to you: https://levelup.gitconnected.com/code-splitting-for-libraries-bundling-for-npm-with-rollup-1-0-2522c7437697

In Rollup, modules can only be part of the module graph once so you always get deduplication. I would recommend having a look at the REPL to see if this what you are after: https://rollupjs.org/repl?version=1.7.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QmN1YmUlN0QlMjBmcm9tJTIwJy4lMkZtYXRoLmpzJyUzQiU1Q25leHBvcnQlMjAlN0J1bnVzZWRGbiU3RCUyMGZyb20lMjAnLiUyRnV0aWxzLmpzJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmluZGV4LWIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCY29uc3VtZXJGbiU3RCUyMGZyb20lMjAnLiUyRnNvbWVDb25zdW1lci5qcyclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzb21lQ29uc3VtZXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCY3ViZSU3RCUyMGZyb20lMjAnLiUyRm1hdGguanMnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGNvbnN1bWVyRm4oKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyhjdWJlKDMpKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglMjAqJTIweCUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydXRpbHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjB1bnVzZWRGbigpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdUaGlzJTIwaXMlMjBub3QlMjBwYXJ0JTIwb2YlMjBib3RoJTIwZW5kcG9pbnRzJyklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

Here I tried to add your code, designating two entry points `main.js` and `index-b.js`.

**Comment by Apidcloud** [comment]
Thank you so much for taking the time to look into this. 

It makes sense now. The article is super helpful. Is there any way to get it working with **UMD**, though? I noticed that in the Repl it says `UMD and IIFE output formats are not supported for code-splitting builds.`

Thank you so much again!

**Comment by lukastaegert** [comment]
Unfortunately not 🙄 The problem is that we would need to implement a way for chunk exports to solely work through global variables. Which is certainly doable but has not been implemented. Also, dynamic imports would probably not be very useful in an IIFE setting where everything needs to be pre-loaded anyway.

When using this in a browser context, there are several options, very much depending on your scenario:
- If there is only a single entry point for your browser build, you use your chunks only as an intermediate step and bundle everything together
- You WANT code-splitting for the browser, in which case
  - you can either directly target modern browsers and provide an ESM build, possibly providing a fallback for older browsers through something like https://github.com/Rich-Harris/shimport
  - you create an AMD or SystemJS build and manually add the corresponding runtime environment. https://github.com/rollup/rollup-starter-code-splitting showcases a more-or-less comprehensive example using SystemJS

**Comment by lukastaegert** [comment]
> Also, just to confirm: is there any special configuration in the repl you provided to guarantee that unusedFn is not present in index-b bundle? Or is that just the normal behaviour?

This is the default behaviour. Here it is important that `unusedFn` is not in the same module as other functionality used by `index-b`. Code-splitting works by splitting the modules into groups depending on which entry points depend on which modules. As `utils.js` is only used by the other chunk, it ends up in the chunk for modules only used by `main.js`. Tree-shaking, on the other hand, is responsible for removing `square()` entirely from all chunks.

**Comment by Apidcloud** [comment]
> Unfortunately not 🙄 The problem is that we would need to implement a way for chunk exports to solely work through global variables. Which is certainly doable but has not been implemented. 

Maybe it's not really a problem, because I would be targeting **modern browsers** and **node**. So in essence I would have to bundle each module as both `cjs` and `esm`, correct? 

Something like the example from the article you mentioned, where each entry is its own package within a monorepo (lerna):
```javascript
{
        input: {
            core: 'packages/core/src/index.js',
            utils: 'packages/utils/src/index.js',
            constants: 'packages/constants/src/index.js',
            common: 'packages/common/src/index.js'
        },
        output: [
            {
                dir: 'esm',
                format: 'esm'
            },
            {
                dir: 'cjs',
                format: 'cjs'
            }
        ]
    }
```

Again, thank you so much for taking the time to go through all this 🙇

**Comment by lukastaegert** [comment]
Exactly. Note that you only need to designate separate entry points for modules that you need to be able to import separately from the resulting chunks. The fewer entry points you designate, the more optimized your chunks will be.

In a browser, you then just need to add a single `<script type='module'>` tag to import your browser entry point. The browser will then take care of loading the rest.

**Comment by Apidcloud** [comment]
Yeah, I will only have one entry point per package. Because they can all be imported.

> In a browser, you then just need to add a single <script type='module'> tag to import your browser entry point. The browser will then take care of loading the rest.

A single `script` tag? I'm not sure I understand. Wouldn't I have to include the bundles I need to then access via `import`?

**Comment by lukastaegert** [comment]
Exactly. `import` statements will trigger the browser to load additional chunks so you do not have to care about this.

**Comment by Apidcloud** [comment]
Thank you! I will give it a shot and let you know how it goes.

**Comment by Apidcloud** [comment]
Oh wow, it was pretty simple to get it working 😲 (see [branch](https://github.com/Apidcloud/tree-shaking-webpack/tree/chore/rollup))

I wonder if I should disable the `es property` in `cjs` since I'm also bundling as `esm`. Any real tradeoffs there?

**Comment by lukastaegert** [comment]
Great to hear!

> I also wonder if I should disable the es property in cjs since I'm also bundling as esm. Any real tradeoffs there?

This property is important if you are re-bundling your chunks with another bundler that understands ES modules but for some reason uses the CJS version. If you can make sure one way or another that other ESM-aware bundlers (Webpack etc.) will always get the ESM version of your library (e.g. by telling them from where to import (: ), you can remove it safely.

**Comment by lukastaegert** [comment]
> Would I need dynamic loading to get the chunk with cube as in the repl?

A shared chunk should contain the `cube` function. The issue in your setup here is that the consumer is importing from `dist/...`, not from `src/math`, which is technically a different module than the module in `src` so there is technically no shared code between the modules.

If it is possible, I would always import from 'src'.

If you really need to create your library in a two-step process (which is sub-optimal but really depends on your situation) and need to import from `dist`, then you should designate the modules in `dist` as `external` using Rollup's `external` option.

**Comment by Apidcloud** [comment]
Thank you, I think I will keep it as it's just one line and it is safer.

> A shared chunk should contain the cube function. The issue in your setup here is that the consumer is importing from dist/..., not from src/math, which is technically a different module than the module in src so there is technically no shared code between the modules.

That repo is just to test. In a real monorepo it would be done through dependencies (which ultimately goes to the correspondent `dist` folder). Would it create the chunks in that case?

**Comment by lukastaegert** [comment]
> That said, wouldn't it create the chunks in that case?

In the REPL example I created, Rollup KNOWS which entry points use which files as everything draws from common sources. Thus Rollup also knows, which chunks it needs to create.

If you do it in a two step process—first bundle your library, then bundle your consumers—then Rollup does not know that a consumer will just need the `math` part when bundling your library and not create a separate chunk for it.

Nevertheless this does not need to be a problem. If you mark everything in the `dist` folder as `external` (note that `external` can be a function which makes this easy), then consumers would not bundle the code of your library but just contain an import statement to your library and you would still have no code-duplication.

If you later bundle everything for the web, tree-shaking would remove any code from your library that is not needed by your consumer.

**Comment by Apidcloud** [comment]
> If you do it in a two step process—first bundle your library, then bundle your consumers—then Rollup does not know that a consumer will just need the math part when bundling your library and not create a separate chunk for it.

Ah, maybe I should have used different terminology. The library is a monorepo, composed by multiple packages, which depend on each other—so they are technically consumers. but it's all part of the same library.

**Comment by lukastaegert** [comment]
Ah, I see. Then to stick with the monorepo, an approach like the following should work nicely:
- each component has an index.js file that exports all relevant functionality from its src folder (it looks like your consumer follows this approach but I guess all components should follow it)
- if you need functionality from another component, your import it from its index.js file and NOT from the dist folder
- when bundling, the dist folder should contain all modules with proper shared chunks

**Comment by Apidcloud** [comment]
> if you need functionality from another component, your import it from its index.js file and NOT from the dist folder (this should hopefully provide the encapsulation you are after)

But wouldn't that defeat the purpose of multiple packages? Because I wouldn't really be using dependencies. And they are all published.

I would still need a way to include the shared chunks in the respective `dist` folder, but that shouldn't be a problem.

**Comment by lukastaegert** [comment]
Yes, in that case `external` is probably what you want.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
