### ISSUE TITLE
Inline comments for dynamic imports are removed starting with rollup 1.4.0

### ISSUE THREAD

**Issue by BryceMehring** [rollup/rollup#2778]
- Rollup Version: 1.7.3
- Operating System (or Browser): MacOS 10.13.6
- Node Version: v11.12.0

### How Do We Reproduce?

Rollup 1.3.3 does not remove comments within dynamic import statements. Rollup 1.4.0 and above removes comments from dynamic import statements. For example:

```JS
import(/* webpackChunkName: "chunk-name" */ 'some-module')
```

the comment will be removed in the bundle

### Expected Behavior

Comments within the dynamic import should not be removed in the bundle.

### Actual Behavior

Comments are being removed within the dynamic module import.

**Comment by manucorporat** [comment]
Unfortunately we also have to support webpack and this is causing issues too. Here's a simple repo case: https://rollupjs.org/repl?version=1.9.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCglMkYqJTIwd2VicGFja0NodW5rTmFtZSUzQSUyMCU1QyUyMmNodW5rLW5hbWUlNUMlMjIlMjAqJTJGJy4lMkZtYXRocy5qcycpLnRoZW4oZnVuY3Rpb24lMjAobWF0aHMpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZyhtYXRocy5zcXVhcmUoNSkpJTNCJTVDbiU1Q3Rjb25zb2xlLmxvZyhtYXRocy5jdWJlKDUpKSUzQiU1Q24lN0QpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwc3F1YXJlJTIwZnJvbSUyMCcuJTJGc3F1YXJlLmpzJyUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCZGVmYXVsdCUyMGFzJTIwc3F1YXJlJTdEJTIwZnJvbSUyMCcuJTJGc3F1YXJlLmpzJyUzQiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjBzcXVhcmUoeCklMjAqJTIweCUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyc3F1YXJlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by manucorporat** [comment]
@lukeapage prepared a PR! https://github.com/rollup/rollup/pull/2797 :)
