### ISSUE TITLE
Support for relative paths with `output.paths`

### ISSUE THREAD

**Issue by dkuhnert** [rollup/rollup#2780]
### Feature Use Case

With two packages which gets rollup´d independently its currently not possible to use correct import mappings (`output.paths`) if the output is written to multiple directories.

Consider following example code:

### package1

package1/index.js
```javascript
export function add(a, b) {
	return a + b;
}
```

package1/rollup.config.js
```javascript
export default {
	input:{
		'package1': './index.js',
	},
	output: {
		dir: '/tmp/dist',
		format: 'es',
		exports: "named",
	},
};
```

### package2

package2/index.js
```javascript
import {add} from 'package1';
export function add1(a) {
	return add(a, 1);
}
```

package2/util/index.js
```javascript
import {add} from 'package1';
export function add2(a) {
	return add(a, 2);
}
```

package2/rollup.config.js
```javascript
export default {
	input:{
		'package2': './index.js',
		'package2/util': './util/index.js',
	},
	output: {
		dir: '/tmp/dist',
		format: 'es',
		paths: {
			package1: './package1.js'
		},
	},
	external: ['package1'],
}
```

Now we have three files:
- /tmp/dist/package1.js
- /tmp/dist/package2.js => `import {add} from './package1.js'` => ok
- /tmp/dist/package2/util.js => `import {add} from './package1.js'` => error should be `../package1.js`

The problem is that there is currently no option to make `output.paths` work with relative paths when have multiple input files.

### Feature Proposal

One option would be to detect if the result of `output.paths` is a relative path and handle this in the render function like it works with normal chunks.
This would be easy by just inserting `this.renormalizeRenderPath = isRelative(this.renderPath);` after https://github.com/rollup/rollup/blob/2e1aa54690441fddae3e0cb29702f7d23ab82b6f/src/ExternalModule.ts#L55-L56

But i'm not sure if that the best option and if this would break any current use cases. Making it configurable would be better then.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
