### ISSUE TITLE
Will there be a version work with deno?

### ISSUE THREAD

**Issue by Fenzland** [rollup/rollup#2781]
### Feature Use Case
```bash
deno https://www.rollupjs.com/rollup.js main.js --file=rolledup.ts
```
### Feature Proposal
NPM is too dirty. But now, a wonderful deno is coming. A module bundler like rollup will always be required for publishing packages for both deno and browsers. Will rollup take this work?

**Comment by arjunyel** [comment]
If you need an example of what Deno support would look like here is pika pack's version  https://github.com/pikapkg/builders/tree/master/packages/plugin-build-deno/

**Comment by GrosSacASac** [comment]
rollup already works in the browser so it should be easy to make something work

**Comment by GrosSacASac** [comment]
rollup already works in the browser so it should be easy to make something work

**Comment by revelt** [comment]
> Will there be a version work with deno?
Please correct the title, it's not grammatically correct. I guess it should be "Will there be a deno-compatible version?" or "Will there be a version that works with deno?"

> NPM is too dirty
It's a very subjective and opinionated claim

FIY, the Deno's API is not considered to be stable:
"The API is subject to change without notice."
—https://deno.land/manual.html#introduction

**Comment by shellscape** [comment]
Hey folks. Closing this one as it seems to be out of scope for the project.

**Comment by flying-sheep** [comment]
Why? We just need a version hosted somewhere that contains the whole thing bundled.

**Comment by shellscape** [comment]
@flying-sheep sounds like a great opportunity for a complimentary project. Lead the charge!
