### ISSUE TITLE
fail to bundle the modules from internet

### ISSUE THREAD

**Issue by Fenzland** [rollup/rollup#2786]
- Rollup Version: 1.7.4
- Operating System (or Browser): Linux Ubuntu 18.04 LTS, Chrome 73
- Node Version: 11.11.0

### How Do We Reproduce?

import * as THREE from 'https://three.js.fenzland.com';

console.log( THREE );

### Expected Behavior

Get the Three.js

### Actual Behavior

An **Uncaught ReferenceError: THREE is not defined**, was thrown.

**Comment by lukastaegert** [comment]
What output format did you use? As the URL hosts an ES module, `esm` is the only format which will work. For that format, your code will basically be unmodified by bundling and it works fine for me: https://rollupjs.org/repl?version=1.9.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMFRIUkVFJTIwZnJvbSUyMCdodHRwcyUzQSUyRiUyRnRocmVlLmpzLmZlbnpsYW5kLmNvbSclM0IlNUNuJTVDbmNvbnNvbGUubG9nKCUyMFRIUkVFJTIwKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by Fenzland** [comment]
My output is IIFE. I build this for <script nomodule>.

May be it's a practicable plan to download the modules recursively and put into the IIFE.

**Comment by lukastaegert** [comment]
Only `script type="module"` supports ES module imports. If you want to "import" things into an IIFE, add another script tag that creates a global variable. But as stated, your import target is an ES module. The only way that this will ever work is using it in a `script type="module"` tag. For Rollup, this means using the esm format

**Comment by Fenzland** [comment]
There is another solution to download the file and package them into the IIFE like deal with local files. For ESM, there is no strict boundary between local and internet file.

**Comment by lukastaegert** [comment]
Ah, now I understand what you mean. This is something I would see as the responsibility of plugins, it should not be too difficult. You could write a plugin that has a `resolveId` hook that detects if an id starts with `http(s)://` and if that is the case, downloads the file instead and returns a virtual id that represents that file. Then it also implements a load hook that returns the file contents when this id is encountered. There is a simple example on our website that shows you how to create virtual modules: https://rollupjs.org/guide/en#a-simple-example

**Comment by lukastaegert** [comment]
The plugin could also take care of caching when in watch mode.

**Comment by lukastaegert** [comment]
I think https://github.com/mjackson/rollup-plugin-url-resolve will do exactly what you want, thanks to @mjackson. Can this issue be closed?

**Comment by Fenzland** [comment]
@lukastaegert That's what I want. Thank you, and thanks to @mjackson
