### ISSUE TITLE
SourceMap test failure on Windows

### ISSUE THREAD

**Issue by nicolo-ribaudo** [rollup/rollup#279]
I just cloned this repository and `npm install`ed (which automatically runs mocha)

These tests fail:
```
      sourcemaps
        1) generates amd
        2) generates cjs
        3) generates es6
        4) generates iife
        5) generates umd
      sourcemaps-inline
        6) generates amd
        7) generates cjs
        8) generates es6
        9) generates iife
        10) generates umd
```

Here is an example:
```
  1) rollup form sourcemaps generates amd:

      AssertionError: { version: 3,
  file: 'amd.js',
  sources: [ '../foo.js', '../bar.js', '../main.js' ],
  sourcesContent:
   [ 'export default f deepEqual { version: 3,
  file: 'amd.js',
  sources: [ '../foo.js', '../bar.js', '../main.js' ],
  sourcesContent:
   [ 'export default f
      + expected - actual

       {
         "file": "amd.js"
      -  "mappings": ";;CAAe,SAAS,GAAG,IAAI;EAC9B,OAAO,CAAC,GAAG,EAAE,mBAAmB,EAAE,CAAC;;;CCDrB,SAAS,GAAG,IAAI;EAC9B,OAAO,CAAC,GAAG,EAAE,mBAAmB,EAAE,CAAC;;;CCEpC,OAAO,CAAC,GAAG,EAAE,oBAAoB,EAAE,CAAC;;CAEpC,GAAG,EAAE,CAAC;CACN,GAAG,EAAE,;;"
      +  "mappings": ";;CAAe,SAAS,GAAG,IAAI;EAC9B,OAAO,CAAC,GAAG,EAAE,mBAAmB,EAAE;;;CCDpB,SAAS,GAAG,IAAI;EAC9B,OAAO,CAAC,GAAG,EAAE,mBAAmB,EAAE;;;CCEnC,OAAO,CAAC,GAAG,EAAE,oBAAoB,EAAE;;CAEnC,GAAG,EAAE;CACL,GAAG,EAAE,;;"
         "names": []
         "sources": [
           "../foo.js"
           "../bar.js"

```

**Comment by Victorystick** [comment]
@nicolo-ribaudo I just installed Node 5 but haven't been able to reproduce the test failures.

**Comment by Rich-Harris** [comment]
I would guess (but haven't checked yet) that it's an npm 3 thing rather than a node 5 thing – trashing `node_modules` and reinstalling would probably reproduce the issue

**Comment by Victorystick** [comment]
@Rich-Harris I've done so, but still fail to reproduce it.

**Comment by nicolo-ribaudo** [comment]
The difference between the expected and the generated sourcemaps is that the second one has some unuseful mappings after some semicolons (but it is not wrong):

- Generated: [https://sokra.github.io/source-map-visualization/#base64,ZGVmaW5lKGZ1...](https://sokra.github.io/source-map-visualization/#base64,ZGVmaW5lKGZ1bmN0aW9uICgpIHsgJ3VzZSBzdHJpY3QnOwoKCWZ1bmN0aW9uIGZvbyAoKSB7DQoJCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBmb28uanMnICk7DQoJfQoKCWZ1bmN0aW9uIGJhciAoKSB7DQoJCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBiYXIuanMnICk7DQoJfQoKCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBtYWluLmpzJyApOw0KDQoJZm9vKCk7DQoJYmFyKCk7Cgp9KTsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9bWFpbi5jb21waWxlZC5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibWFpbi5jb21waWxlZC5qcyIsInNvdXJjZXMiOlsiQzovVXNlcnMvbmljb2wvRG9jdW1lbnRzL3JvbGx1cC90ZXN0L2Zvcm0vc291cmNlbWFwcy9mb28uanMiLCJDOi9Vc2Vycy9uaWNvbC9Eb2N1bWVudHMvcm9sbHVwL3Rlc3QvZm9ybS9zb3VyY2VtYXBzL2Jhci5qcyIsIkM6L1VzZXJzL25pY29sL0RvY3VtZW50cy9yb2xsdXAvdGVzdC9mb3JtL3NvdXJjZW1hcHMvbWFpbi5qcyJdLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBmb28gKCkge1xyXG5cdGNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBmb28uanMnICk7XHJcbn1cclxuIiwiZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gYmFyICgpIHtcclxuXHRjb25zb2xlLmxvZyggJ2hlbGxvIGZyb20gYmFyLmpzJyApO1xyXG59XHJcbiIsImltcG9ydCBmb28gZnJvbSAnLi9mb28nO1xyXG5pbXBvcnQgYmFyIGZyb20gJy4vYmFyJztcclxuXHJcbmNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBtYWluLmpzJyApO1xyXG5cclxuZm9vKCk7XHJcbmJhcigpO1xyXG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Q0FBZSxTQUFTLEdBQUcsSUFBSTtFQUM5QixPQUFPLENBQUMsR0FBRyxFQUFFLG1CQUFtQixFQUFFLENBQUM7OztDQ0RyQixTQUFTLEdBQUcsSUFBSTtFQUM5QixPQUFPLENBQUMsR0FBRyxFQUFFLG1CQUFtQixFQUFFLENBQUM7OztDQ0VwQyxPQUFPLENBQUMsR0FBRyxFQUFFLG9CQUFvQixFQUFFLENBQUM7O0NBRXBDLEdBQUcsRUFBRSxDQUFDO0NBQ04sR0FBRyxFQUFFLDs7In0=,ZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gZm9vICgpIHsNCgljb25zb2xlLmxvZyggJ2hlbGxvIGZyb20gZm9vLmpzJyApOw0KfQ0K,ZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gYmFyICgpIHsNCgljb25zb2xlLmxvZyggJ2hlbGxvIGZyb20gYmFyLmpzJyApOw0KfQ0K,aW1wb3J0IGZvbyBmcm9tICcuL2Zvbyc7DQppbXBvcnQgYmFyIGZyb20gJy4vYmFyJzsNCg0KY29uc29sZS5sb2coICdoZWxsbyBmcm9tIG1haW4uanMnICk7DQoNCmZvbygpOw0KYmFyKCk7DQo=)
- Expected: [https://sokra.github.io/source-map-visualization/#base64,ZGVmaW5lKGZ1...](https://sokra.github.io/source-map-visualization/#base64,ZGVmaW5lKGZ1bmN0aW9uICgpIHsgJ3VzZSBzdHJpY3QnOwoKCWZ1bmN0aW9uIGZvbyAoKSB7DQoJCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBmb28uanMnICk7DQoJfQoKCWZ1bmN0aW9uIGJhciAoKSB7DQoJCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBiYXIuanMnICk7DQoJfQoKCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBtYWluLmpzJyApOw0KDQoJZm9vKCk7DQoJYmFyKCk7Cgp9KTsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9bWFpbi5jb21waWxlZC5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYW1kLmpzIiwic291cmNlcyI6WyIuLi9mb28uanMiLCIuLi9iYXIuanMiLCIuLi9tYWluLmpzIl0sInNvdXJjZXNDb250ZW50IjpbImV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIGZvbyAoKSB7XG5cdGNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBmb28uanMnICk7XG59XG4iLCJleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBiYXIgKCkge1xuXHRjb25zb2xlLmxvZyggJ2hlbGxvIGZyb20gYmFyLmpzJyApO1xufVxuIiwiaW1wb3J0IGZvbyBmcm9tICcuL2Zvbyc7XG5pbXBvcnQgYmFyIGZyb20gJy4vYmFyJztcblxuY29uc29sZS5sb2coICdoZWxsbyBmcm9tIG1haW4uanMnICk7XG5cbmZvbygpO1xuYmFyKCk7XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Q0FBZSxTQUFTLEdBQUcsSUFBSTtFQUM5QixPQUFPLENBQUMsR0FBRyxFQUFFLG1CQUFtQixFQUFFOzs7Q0NEcEIsU0FBUyxHQUFHLElBQUk7RUFDOUIsT0FBTyxDQUFDLEdBQUcsRUFBRSxtQkFBbUIsRUFBRTs7O0NDRW5DLE9BQU8sQ0FBQyxHQUFHLEVBQUUsb0JBQW9CLEVBQUU7O0NBRW5DLEdBQUcsRUFBRTtDQUNMLEdBQUcsRUFBRSw7OyJ9,ZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gZm9vICgpIHsKCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBmb28uanMnICk7Cn0K,ZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gYmFyICgpIHsKCWNvbnNvbGUubG9nKCAnaGVsbG8gZnJvbSBiYXIuanMnICk7Cn0K,aW1wb3J0IGZvbyBmcm9tICcuL2Zvbyc7CmltcG9ydCBiYXIgZnJvbSAnLi9iYXInOwoKY29uc29sZS5sb2coICdoZWxsbyBmcm9tIG1haW4uanMnICk7Cgpmb28oKTsKYmFyKCk7Cg==)

If it can be useful to identify the problem, here are the dependencies version: https://gist.github.com/nicolo-ribaudo/d5902c084914a4ab0e65#file-npm-shrinkwrap-json

**Comment by Victorystick** [comment]
@nicolo-ribaudo You're running Windows, right? The issue may be related to the platform. You were talking about mappings for the semi-colons... I'm thinking _line endings_.

**Comment by TrySound** [comment]
@Victorystick By the way I have node 0.12. Need to rename this issue

**Comment by Rich-Harris** [comment]
I took the lazy approach – these tests are now skipped on Windows

**Comment by TrySound** [comment]
Dirty
