### ISSUE TITLE
--extend does not appear to function

### ISSUE THREAD

**Issue by brendanmig** [rollup/rollup#2798]
- Rollup Version: 1.9.0
- Operating System (or Browser): Tested on Windows, probably affects all.
- Node Version: 10.15.0

### How Do We Reproduce?

I am unable to get the --extend command line option to work. This gist contains the source, build script and output iife files: https://gist.github.com/brendanmig/39aa376e42685715d862e01a68129a39

The output quite obviously is not extending the Package namespace as expected, and if I load both modules in a page Package.one is undefined. If I build without --extend the only difference in the output is that Package is defined as `var Package = (function () {` instead of `this.Package = (function () {`

### Expected Behavior

Both generated modules extend the global `Package` object.

### Actual Behavior

Both generated modules create the global `Package` object which means the first created object gets clobbered by the second.

**Comment by lukastaegert** [comment]
`--extend` only works if you have only named exports. The idea is that when you bundle a default export as IIFE, then the variable is replaced with the export. As this default export can be basically anything, including a primitive value, there is no natural notion how this should work with `extend`. You should use named exports instead.

**Comment by brendanmig** [comment]
Ah, that makes a lot of sense. Thanks for the explanation. Coincidentally I'd already restructured my library to use ES6 named exports rather than CommonJS modules (after I posted this issue) and --extend is now working!
