### ISSUE TITLE
No matching version found for rollup@1.9.3

### ISSUE THREAD

**Issue by thebrodmann** [rollup/rollup#2804]
- Rollup Version: 1.9.3
- Operating System (or Browser): OS X
- Node Version: v11.9.0

### How Do We Reproduce?

Run `npm install rollup@1.9.3` or `yarn add rollup@1.9.3`. For furthur info please see https://github.com/thebrodmann/deox/issues/46.

### Expected Behavior

Install the mentioned version.

### Actual Behavior

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for rollup@1.9.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'deox'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brodmann/.npm/_logs/2019-04-10T07_45_06_855Z-debug.log
```

**Comment by lukastaegert** [comment]
Could have been an npm hickup. Try again, at least for me `npm i rollup@1.9.3` now works as expected.
