### ISSUE TITLE
Error with spread operator

### ISSUE THREAD

**Issue by cetra3** [rollup/rollup#281]
Trying to rollup [redux](https://github.com/rackt/redux) I get this error:

```
Error parsing /Users/cetra/git/redux/src/utils/applyMiddleware.js: Unexpected token (33:6) in /Users/cetra/git/redux/src/utils/applyMiddleware.js
```

Line 33 is part of the return statement which reads:
```
    return {
      ...store,
      dispatch
    }
```

Appears to be an error parsing the spread operator on return statements.

**Comment by Victorystick** [comment]
Rollup uses Acorn for parsing. Since the object-spread operator is currently in ES Stage 2, I'm not sure whether Acorn implements it or not. If not, that would explain the parse error.

I know that Acorn doesn't handle the Stage 1 export extensions we're looking forward to (#82). I believe it must be in the official spec for it to be implemented.

**Comment by Rich-Harris** [comment]
There's actually an open PR on the Redux repo that replaces the current build process with Rollup: https://github.com/rackt/redux/pull/964 You could take a look at that to see how it's done. Essentially, you need to transpile the source code to ES5 (which you'd need to do anyway, for it to run anywhere), which means using [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel).

I'll close this issue but feel free to ask any follow-up questions you have

**Comment by cetra3** [comment]
@Victorystick strange that it doesn't error out on the spread operator on the function, just on the return value.  I've also checked out the source for rollup and there does seem to be rudimentary support for the spread operator.

The spread operator is a part of ES6 standard, not ES7:
http://www.ecma-international.org/ecma-262/6.0/#sec-array-initializer

**Comment by Rich-Harris** [comment]
The spread operator for *arrays* is part of ES6. For *objects* the semantics are slightly different – it's a separate proposal that hasn't made it into a spec yet, and thus isn't supported by Acorn

**Comment by cetra3** [comment]
Ok, my apologies.  Thanks for the clarification.

**Comment by salztorte** [comment]
Is there a solution for this Problem? 

I try to use React and Redux and nothing goes.

**Comment by TrySound** [comment]
@salztorte Just process redux with babel and include [babel-plugin-transform-object-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread) in babel plugin list.

**Comment by salztorte** [comment]
thx for the quick answer.
