### ISSUE TITLE
Generate single css file with multiple js bundles(esm,umd,cjs)

### ISSUE THREAD

**Issue by cpmotion** [rollup/rollup#2817]
Documentation Is:

- [x ] Missing
- [x ] Needed
- [x ] Confusing
- [x ] Not Sure?

### Please Explain in Detail...
I'm trying to use Rollup to create a small component React lib. I simply want to bundle JS into multiple file formats mentioned in subject. But by default rollup scss plugin generates a separate .css and .css.map for each bundle. How can this be avoided/enabled within simple config? Do I need to resort to using the JS api to custom construct?

**Comment by lukastaegert** [comment]
I fear rollup core will not be able to help you here. Rollup core is solely a JavaScript bundler and handling other formats needs to be handled by plugins. What the scss plugin does sounds reasonable to me. If you want different behaviour, it will be a feature request for this plugin.

**Comment by cpmotion** [comment]
Understandable Lukas thanks for your reply. I already switched out my scss->css compilation to a separate simple Node script running node-sass and postcss. Works for what I need and I can leave JS bundling to Rollup. If I get time I'll explore writing a plugin for my original need as i think it is valid use case and could be helpful to others. Thanks.
