### ISSUE TITLE
fails with Illegal Instruction:4 if a referenced file is missing

### ISSUE THREAD

**Issue by BryanCrotaz** [rollup/rollup#2819]
- Rollup Version: 1.10.1
- Operating System (or Browser): macOS
- Node Version: 
works in node 6, fails in node 8 LTS and node 10 latest

### How Do We Reproduce?

Failed when an imported module was badly built so that it was missing all its `.js` files.
```
// some/path/index.js
import something from 'path/that/does/not/exist';
```
I was using:
```
options: {
    "input": {
      "Account": "src/lambda/Account/index.js",
      "Config": "src/lambda/Config/index.js",
      "Content": "src/lambda/Content/index.js",
      "CustomScripts": "src/lambda/CustomScripts/index.js",
      "DynamoStreamReader": "src/lambda/DynamoStreamReader/index.js",
      "GetSignedUrlForFile": "src/lambda/GetSignedUrlForFile/index.js",
      "GlobalAuthorizer": "src/lambda/GlobalAuthorizer/index.js",
      "IotDeviceConnection": "src/lambda/IotDeviceConnection/index.js",
      "Media": "src/lambda/Media/index.js",
      "Player": "src/lambda/Player/index.js",
      "Proxy": "src/lambda/Proxy/index.js",
      "PushGraphUpdates": "src/lambda/PushGraphUpdates/index.js",
      "Shakr": "src/lambda/Shakr/index.js",
      "Transcode": "src/lambda/Transcode/index.js",
      "TranscodeCompleted": "src/lambda/TranscodeCompleted/index.js",
      "UploadComplete": "src/lambda/UploadComplete/index.js",
      "User": "src/lambda/User/index.js"
    },
    "output": {
      "dir": ".",
      "entryFileNames": "./[name]/index.js",
      "format": "es"
    },
    "plugins": [
      {
        "name": "node-resolve"
      },
      {
        "name": "commonjs"
      },
      {
        "name": "json"
      },
      {
        "name": "terser"
      }
    ]
  }
```
### Expected Behavior
Error saying `missing file 'path/that/does/not/exist' imported by 'location of import' `

### Actual Behavior

```
#
# Fatal error in , line 0
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#
#
#
#FailureMessage Object: 0x7ffeefbf6f80./build.sh: line 6: 18932 Illegal instruction: 4
```
Commenting out the import of `module` in rollup makes the illegal instruction go away. Hope this helps you narrow it down.

**Comment by BryanCrotaz** [comment]
To be clear, once I fixed the imported module, the build worked, but it took 4 days to work out what the cause was.

**Comment by BryanCrotaz** [comment]
Just had it reoccur after switching from npm to yarn.

Again, commenting out the import of `module` fixed it.

in `dist/rollup.js`
line 28
`//var module$1 = _interopDefault(require('module'));`

**Comment by lukastaegert** [comment]
Just a general question first, is this really your plugins or is this just illustration:

```js
"plugins": [
      {
        "name": "node-resolve"
      },
      {
        "name": "commonjs"
      },
      {
        "name": "json"
      },
      {
        "name": "terser"
      }
    ]
```

This would just add four empty plugins without an effect. Still trying to reproduce. Usually, importing something that does not exist results in an "Rollup assumes xy to be external" warning. Your fix is really weird. I assume it is not possible to distill a minimal repo from your issue that I could run?

**Comment by BryanCrotaz** [comment]
Those are my plugins. And without them, I get the failures you’d expect so the plugins are definitely being loaded.

**Comment by lukastaegert** [comment]
Interesting. This should not load any plugin code but define new plugins that do not do anything. E.g. to use the commonjs plugin, you would need to

```
const commonjs = require('rollup-plugin-commonjs');

//...
"plugins": [
      commonjs()
    ]

```

**Comment by lukastaegert** [comment]
On second thought, maybe this is just an issue with how the options were extracted.

**Comment by lukastaegert** [comment]
Still, a reproduction that exposes the issue (e.g. a repository) would help immensely in resolving this issue.

**Comment by BryanCrotaz** [comment]
PM me at Bryan.crotaz@silvercurve.co.uk and i’ll give you temporary access to our private repo

**Comment by lukastaegert** [comment]
Sorry I could not find time to look into this. Googling showed that this error probably originates from a binary that is not compatible with your OS version. My guess is that this binary is actually Node, and that this is not a Rollup error (but the situation you described triggers a specific code path that contains too optimized machine code). What MacOS version are you running?

**Comment by shellscape** [comment]
Closing as abandoned. Please ping me to have this issue reopened if concerned parties have time to triage.
