### ISSUE TITLE
Reports `UNUSED_EXTERNAL_IMPORT` for JSX tags when adding `acorn-jsx` + breaks usage

### ISSUE THREAD

**Issue by swernerx** [rollup/rollup#2822]
- Rollup Version: 1.10.1
- Operating System (or Browser): macOS 10.14.4
- Node Version: v11.13.0

### Context

Our goal was to deliver JS bundled together with preserved JSX. The reason for this is that we bundle our component library for usage in different applications. For being able to use StyledComponents and JSX optimizations we ideally do these transformations in the applications projects (=transpile code from these specific node_modules). We know that this is not following a typical convention when publishing to NPM, but we figured that for our narrow use case the benefits outweigh any non-standard conformance.

The benefits of doing this are:

- Styled Components settings for e.g. `displayName` are toggleable by the application settings.
- JSX optimizations like "constant elements" can only be applied when bundling the application for production. 
- JSX debug instructions like adding React display names or source file hints can be added when the application is developed e.g. with HMR, etc.

We think this approach has great benefits over bundling two different libraries and e.g. selecting them via Webpack e.g. by preferring different fields in `package.json` like `main` and `main:production`. 

I saw that Rollup itself does not seem to be able to parse JSX. But there was [a somewhat documented support for adding JSX support](https://rollupjs.org/guide/en#acorninjectplugins) for the underlying Acorn parser. This is what I did in the reproduction example as well.

The actual issue contains two problems:

1. Usage of `React` is not connected to the usage of JSX. I figure we need some way to tell Rollup what *Pragma* and *PragmaFrag* to use - somewhat inspired from the wording in the [JSX transform Babel plugin](https://babeljs.io/docs/en/next/babel-plugin-transform-react-jsx.html). Both pragmas should be added to the module level usage list so that the tree shaking does not cleanup the imports.
2. The usage of JSX tags does not seem to register the underlying functions or classes to be registered as actual "usage". As they are not registered some optimization step seems to remove the actual imports and warns about non-usage after bundling. 

I am fine with everything that helps here, even if there are workarounds to fix current limitations.

### How Do We Reproduce?

Reproduction Issue: https://github.com/swernerx/rollup-jsx-bug

```js
import React from "react"
import { FormattedMessage } from "react-intl"

export default function Hello() {
  return <FormattedMessage id="foo"/>
}
```

### Actual Behavior

```js
'use strict';

require('react');
require('react-intl');

function Hello() {
  return <FormattedMessage id="foo"/>
}

module.exports = Hello;
```

And these warnings:

```
(!) Unused external imports
default imported from external module 'react' but never used
FormattedMessage imported from external module 'react-intl' but never used
```

### Expected Behavior

```js
'use strict';

var React = require('react');

var reactIntl = require('react-intl');
var FormattedMessage = reactIntl.FormattedMessage;

function Hello() {
  return <FormattedMessage id="foo"/>
}

module.exports = Hello;
```

**Comment by swernerx** [comment]
This is also an issue with the initial JSX support in my publishing helper [Preppy](https://github.com/sebastian-software/preppy). [Check out this snapshot here](https://github.com/sebastian-software/preppy/blob/master/test/jsx/__snapshots__/index.test.js.snap) which demonstrates the same problem.

**Comment by swernerx** [comment]
Maybe this is related to the fact that Rollup is now using Acorn v6. At the moment the plugin feature was introduced it seems like Rollup was still using v5 of Acorn.

**Comment by lukastaegert** [comment]
The problem is that the JSX support introduces quite a bunch of new AST nodes that Rollup does not know about and for instance does not know that `<FormattedMessage id="foo"/>` means that both `FormattedMessage` as well as `React` need to be included. We might got for a general solution to allow plugins to define basic behaviour of unknown nodes in the future but this could take a long time. For now, this is a direction how you might address this:

```js
// jsx-dependency-includer-plugin
// this package makes finding the right nodes easier
import {walk} from 'estree-walker';

export default () => ({
  transform(code) {
    const names = new Set();
    const ast = this.parse(code);
    walk(ast, {
      enter(node) {
        if (node.type === 'JSXIdentifier') {
          names.add('React');
          names.add(node.name);
        }
      }
    });

    if (names.size > 0) {
      // This is the magic. We add a non-existing function that gets passed all variables that
      // need to be included and that has a name that we can easily find in the generated output.
      // Rollup always assumes that unknown functions have side-effects so this line will
      // not be removed.
      return `${code};USED_JSX_NAMES(${Array.from(names).join(',')});`;
    }
  },
  renderChunk(code) {
    // here we remove all injected functions again.
    return code.replace(/USED_JSX_NAMES\([^)]*\);/g, '');
  }
});
```

If you need sourcemaps, you should probably use something like 'magic-string'  to do the source code transformations in the hooks.

**Comment by swernerx** [comment]
This looks great and not too complex to implement. Thanks for that!

I wonder what happens with name conflicts during bundling e.g. two included files export the same e.g. `Row` component. I assume that Rollup would rename occurrences then - at least normally. This will probably not work for JSXIdentifiers as these are still unknown to Rollup with this implementation, right?

**Comment by lukastaegert** [comment]
My assumption is that this should be handled gracefully-if it is the same Row component, the same variable will be used while a different component named Row will be renamed. But the best way would be to try it out.

**Comment by swernerx** [comment]
Puh

**Comment by lukastaegert** [comment]
Here is a version that will automatically rename tags based on renamed variables. Note though that this will not yet handle JSXMemberExpressions, i.e. `<My.Tag></My.Tag>` but this could be added as well with a little more work.

```js
import {walk} from 'estree-walker';
const MagicString = require('magic-string');

let nextId = 0;

export default () => ({
  transform(code) {
    const magicString = new MagicString(code);
    const idsByName = new Map();
    const ast = this.parse(code);
    walk(ast, {
      enter(node) {
        if (node.type === 'JSXIdentifier') {
          const tagId = idsByName.get(node.name) || `JSX_PLUGIN_ID_${nextId++}`;
          magicString.overwrite(node.start, node.end, tagId);
           idsByName.set(node.name, tagId);
        }
      }
    });

    if (idsByName.size > 0) {
      const usedNamesAndIds = Array.from(idsByName).map(
        ([name, tagId]) => `/*${tagId}*/${name}`
      );
      magicString.append(`;USED_JSX_NAMES(React,${usedNamesAndIds.join(',')});`);
      return magicString.toString();
    }
  },
  renderChunk(code) {
    const replacements = new Map();
    return code
      .replace(/USED_JSX_NAMES\(([^)]*)\);/g, (_, args) => {
        args
          .split(',')
          .map(arg => arg.match(/^\/\*([^*]*)\*\/(.*)$/))
          .slice(1)
          .forEach(([_, tagId, updatedName]) => replacements.set(tagId, updatedName));
      return '';
    })
    .replace(/JSX_PLUGIN_ID_\d+/g, tagId => replacements.get(tagId));
  });
```

**Comment by lukastaegert** [comment]
With some small modifications, this will now handle JSXMemberExpressions gracefully too as well as JSX tags taken from namespace imports (i.e. `import * as Tags from 'file'; export default <Tags.MyTag />`):

```js
const walk = require('estree-walker').walk;
const MagicString = require('magic-string');

let nextId = 0;

function getJsxName(node) {
	if (node.type === 'JSXMemberExpression') {
		return `${getJsxName(node.object)}.${getJsxName(node.property)}`;
	}
	return node.name;
}

export default () => ({
  transform(code) {
    const magicString = new MagicString(code);
    const idsByName = new Map();
    const ast = this.parse(code);
    walk(ast, {
      enter(node) {
        if (node.type === 'JSXMemberExpression' || node.type === 'JSXIdentifier') {
          const name = getJsxName(node);
          const tagId = idsByName.get(name) || `JSX_PLUGIN_ID_${nextId++}`;
          magicString.overwrite(node.start, node.end, tagId);
          idsByName.set(name, tagId);

          // if this is a JSXMemberExpression, do not treat the children as separate identifiers
          this.skip();
        }
      }
    });

    if (idsByName.size > 0) {
      const usedNamesAndIds = Array.from(idsByName).map(
        ([name, tagId]) => `/*${tagId}*/${name}`
      );
      magicString.append(`;USED_JSX_NAMES(React,${usedNamesAndIds.join(',')});`);
      return magicString.toString();
    }
  },
  renderChunk(code) {
    const replacements = new Map();
    return code
      .replace(/USED_JSX_NAMES\(([^)]*)\);/g, (_, args) => {
        args
          .split(',')
          .map(arg => arg.match(/^\/\*([^*]*)\*\/(.*)$/))
          .slice(1)
          .forEach(([_, tagId, updatedName]) => replacements.set(tagId, updatedName));
      return '';
    })
    .replace(/JSX_PLUGIN_ID_\d+/g, tagId => replacements.get(tagId));
  }
});
```

**Comment by swernerx** [comment]
Thanks again. This seems to work very good for my use cases. It will be part of Preppy v8 later during the day.

**Comment by swernerx** [comment]
https://twitter.com/sebastiansoft/status/1125503689312145415

I think we might want to close the issue now. :)

**Comment by aleclarson** [comment]
@lukastaegert I extended your work by injecting `acorn-jsx` in the plugin. Maybe y'all would consider maintaining a `@rollup/plugin-preserve-jsx` plugin?

https://gist.github.com/aleclarson/40a2f10f0f3bedd4ae5eee4e444e033f

**Comment by aleclarson** [comment]
PS: Your implementation accidentally renamed JSX attributes with an identical name to a local variable that was deconflicted. I fixed it here: https://gist.github.com/aleclarson/40a2f10f0f3bedd4ae5eee4e444e033f/revisions#diff-485a9f99367d0e50993766f5d64db4e15904e0901e318489be3a81d12a51e581

**Comment by lukastaegert** [comment]
> Maybe y'all would consider maintaining a @rollup/plugin-preserve-jsx plugin?

Sounds like a plan if we get some help adding it to the plugin repo. First step would be "New plugin request" issue: https://github.com/rollup/plugins/issues/new?template=NEW_PLUGIN.md

**Comment by swernerx** [comment]
Thanks for sharing @aleclarson - Added the modified version to preppy in a new release. Looks good so far. https://github.com/sebastian-software/preppy/releases/tag/10.9.0

**Comment by AnmSaiful** [comment]
@lukastaegert what do you think about #4172 ? I tried your solution, but no luck!
