### ISSUE TITLE
normalizeOutputOptions throws incorrectly when the build hasMultipleChunks but inlineDynamicImports is selected

### ISSUE THREAD

**Issue by sw-yx** [rollup/rollup#2827]
- Rollup Version: 1.10.1
- Operating System (or Browser): mac osx
- Node Version: 11.0.0

### How Do We Reproduce?

this set of output options should work:

```js
```

**Comment by lukastaegert** [comment]
A little more detail would be nice. Please note that there are situations where `inlineDynamicImports` will NOT prevent having multiple chunks, especially when there is more than one input :)

**Comment by sw-yx** [comment]
oops!! idk how come this went through. opened this while working on tsdx but decided to just abandon dynamic imports altogether. apologies for the stray issue.
