### ISSUE TITLE
Support import maps

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#2828]
### Feature Use Case

A small change to a chunk changes the hash of all chunks that reference it.

Ideally the browser should only have to fetch the changed module, and the rest would be cached.

### Feature Proposal

https://github.com/WICG/import-maps seems like the standard way forward. Of course, this shouldn't be on-by-default, since it isn't supported by any browsers yet.

However, AMD and SystemJS could probably make use of it today.

The 'map' would become a entry point, and its hash would change when its content changes (as with other entry points).

In the rest of the output, references to other modules would remain constant, but the map would update the url for modules that changed content.

**Comment by developit** [comment]
Prior to widely available support for Import Maps, could moving the existing mappings into a dedicated map chunk suffice?  It could be inlined into the HTML payload too.

**Comment by jakearchibald** [comment]
You won't be able to use that with esm output, but the AMD and SystemJS loaders could make use of it, yeah.

**Comment by lukastaegert** [comment]
On a high-level, I would see import map generation as something that should be the responsibility of plugins, especially as to my understanding, import maps are an HTML feature and not a JavaScript feature.

I do not know how to use import maps with AMD (did not find any documentation) but for SystemJS, this seems to be only possible via script tag and as such also beyond the scope of Rollup core: https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md

(that is, unless @guybedford hacks together a more permissive API)

And as I see it, this should already be possible as all the information is available: The `generateBundle` hook receives the names of all chunks as well as their content in form of a `code` property. So a plugin could easily use that hook, calculate hashes of all chunks and write the corresponding import map for a script tag.

**Comment by lukastaegert** [comment]
I think this should actually be a feature of an HTML generator plugin. Unfortunately there is no "official" plugin.

**Comment by jakearchibald** [comment]
Yeah, you're right. The only missing bit is predictable chunk naming, but seems like https://github.com/rollup/rollup/pull/2809 takes care of that.
