### ISSUE TITLE
Bundle non-module npm packages

### ISSUE THREAD

**Issue by vdclouis** [rollup/rollup#283]
Hi, I'm super interested in using rollup for my next project; it looks awesome!
I do however have a question. I've added some npm packages that need to be included in my web app. 
(Fetch and babel polyfill). The issue is that those packages are no modules but some regular methods or IIFEs. So I can't import them in my main entry file. 
Idealy I would like to bundle all those packages in a second bundle, say `vendor.js`. Anyways Any feedback is welcome :)

**Comment by Victorystick** [comment]
If they're polyfills in IIFEs, just include them before your code executes. I assume you can just concatenate them?

**Comment by vdclouis** [comment]
Aha, I didn't know you could import regular methods. 
So I could just do something like this?
In `src/main.js` 
```js
import '../node_modules/fetch/dist/fetch.js';

// rest of code
```

**Comment by Victorystick** [comment]
Or even:

```js
import 'fetch/dist/fetch.js';
```

**Comment by vdclouis** [comment]
Awesome! Why didn't I know this?!
Thanks!
