### ISSUE TITLE
`RenderedModule.removedExports` is wrong when using export declarations

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup#2834]
I’m not really sure if this is actually a bug or intended behavior.

The `removedExports` metadata refers to the `export declaration` that was removed.
However, if you have explicit `export { foo }` declarations, instead of `export function foo() {}`, it reports them as removed, since the `export declaration` itself will be rewritten by rollup, but the `function declaration` itself is still included and rendered.

In other words, `export function foo() {}` correctly reflects in `removedExports / renderedExports` whether the function is included in the output or not, however `function foo() {} export { foo }` will **always** list `foo` inside `removedExports`.

If this is indeed intended instead of a bug, it would be nice to provide a different implementation that really refers to the `function/class/const/whatever` that is being removed.

- Rollup Version: 1.11.0
- Operating System (or Browser): linux
- Node Version: 11.14

### How Do We Reproduce?

```ts
// main.js
export { a, c as b } from "./a";

// a.js
function a() {}
function b() {}
function c() {}

export { a, b, c };
// the `module` has: { "removedExports": ["a", "b", "c"] }
```

[REPL Link](https://rollupjs.org/repl?version=1.11.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGElMkMlMjBjJTIwYXMlMjBiJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZhJTVDJTIyJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBhKCklMjAlN0IlN0QlNUNuZnVuY3Rpb24lMjBiKCklMjAlN0IlN0QlNUNuZnVuY3Rpb24lMjBjKCklMjAlN0IlN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGElMkMlMjBiJTJDJTIwYyUyMCU3RCUzQiU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

For the testcase above, `removedExports` for `a.js` should list only `["b"]`, corresponding to the `function declaration` which was actually removed.

### Actual Behavior

For the testcase above, `removedExports` for `a.js` lists `["a", "b", "c"]`, which is kind of wrong, depending on your expectation on how `removedExports` should work.

It correctly lists **all** the `export declarations`, since they will be re-written by rollup someplace else, but the `function declarations` are still there.

**Comment by lukastaegert** [comment]
Hi @Swatinem, indeed this is not intended. Hope to be able to look into this soon.

**Comment by Swatinem** [comment]
PR coming up in a sec :-)
