### ISSUE TITLE
Improve text contrast to make documentation easier to read

### ISSUE THREAD

**Issue by d2s** [rollup/rollup#2840]
Documentation Is:
- A bit difficult to read, because default `font-weight: 300;` is too light on a larger screen resolution.
- Text color is not fully black, causing reduced visual contrast between text color and background.

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Reason for improved visual contrast is mainly for making it the documentation more accessible for people with limited eyesight. At the same time, many developers spend their days reading a lot of text, and the speed & clarity of reading matters a lot.

### Your Proposal for Changes

Example `color` and `font-weight` values that could make the content easier to read:

```css
p {
  font-weight: 400;
  color: #000;
}
```

**Comment by shellscape** [comment]
We'd happily review a pull request along these lines. Do note that the text color on the rollup documentation site is actually darker and closer to black than the default color on Github 😄  Closing for now, as this is the first critique of that we've received, but again want to make sure it's clear that we'd welcome a pull request.
