### ISSUE TITLE
Allow to change modules extensions when preserveModules is enabled

### ISSUE THREAD

**Issue by myklt** [rollup/rollup#2842]
First of all, I would like to thank you for super useful project and its maintenance.

### Feature Use Case

Tree shaking in Webpack works only when the modules are preserved. But at the same time, Webpack loaders use file extensions to decide whether to process the file or not. If we use `preserveModules` of Rollup when building a library, it keeps the original extensions even transforms the files to JS, what causes problems while loading those files.

I have created a small repository of React components library, which uses Rollup and CSS modules. In order to demonstrate the problem I tried to use it in standard Create React App setup.

- Library's Rollup config: https://github.com/myklt/myk-spa/blob/preserve-modules-issue/packages/react-components/rollup.config.js
 
- CRA usage of library component: https://github.com/myklt/myk-spa/blob/preserve-modules-issue/packages/react-app/src/App.tsx#L2

The error thrown while trying to start application is suggesting that `.scss` file was tried to be loaded with appropriate Webpack loader, even it is already compiled to JS.
```
./node_modules/@myklt/react-components/dist/es/src/components/Button/Button.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./node_modules/@myklt/react-components/dist/es/src/components/Button/Button.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
```

### Feature Proposal

We already have `preserveModules` option, which works pretty nicely, but there is a need for an option to specify generated modules extensions in case they are converted to JS from any other format. It could be an option for `preserveModules` or `output` configuration.

**Comment by TomCaserta** [comment]
I had this issue too, I worked around it by creating a plugin you can find here: https://www.npmjs.com/package/@betit/rollup-plugin-rename-extensions

**Comment by Birch-san** [comment]
@TomCaserta thanks very much; that extension has helped me workaround the file extension problem I'm experiencing in https://github.com/rollup/rollup/issues/2847.

**Comment by myklt** [comment]
Hi @TomCaserta , thanks a lot for this plugin! I hope something like that will land into Rollup itself. I tried the plugin in my react-components [library](https://github.com/myklt/myk-spa/blob/%40myklt/react-components%400.1.3/packages/react-components/rollup.config.js#L14) and it works like a charm, except the order in plugins config matters.

**Comment by philipwalton** [comment]
Just wanted to +1 this and say I came here looking to solve the exact same use case.

We're trying to switch to TypeScript in [Workbox](https://github.com/GoogleChrome/Workbox), but we want to continue to publish the full JS source for backwards compatibility. Currently our module source is published to npm using the `.mjs` extension (which [TypeScript doesn't support](https://github.com/Microsoft/TypeScript/issues/18442)), so I was hoping we could work around that using Rollup.

**Comment by lukastaegert** [comment]
I believe we can solve this by solving #2847

**Comment by shellscape** [comment]
Let's move discussion to #2847 for this common topic.
