### ISSUE TITLE
Name collision 

### ISSUE THREAD

**Issue by illuzen** [rollup/rollup#2845]
- Rollup Version: rollup v1.11.3
- Operating System (or Browser): Debian
- Node Version: v10.15.3

### How Do We Reproduce?

Hello, I'm trying to use jQuery's datatables with rollup and running into issues. Here's my rollup.config.js

```

export default {
    input: 'assets/js/test.js',
    output: {
      name: 'helloworld',
      file: 'build/js/main.min.js',
        format: 'iife'
        // format: 'umd'
    },
    plugins: [    ],
};
```
here is test.js

```
import 'datatables.net'

export function f() {
    return 1;
}

```
here is the beginning of dataTables.js
```
    (function( factory ) {

    	if ( typeof define === 'function' && define.amd ) {
    		// AMD
    		define( ['jquery'], function ( $ ) {
    			return factory( $, window, document );
    		} );
    	}
    	else if ( typeof exports === 'object' ) {
    		// CommonJS
    		module.exports = function (root, $) { // **************here's where the browser errors
    			if ( ! root ) {
    				// CommonJS environments without a window global must pass a
    				// root. This will give an error otherwise
    				root = window;
    			}

    			if ( ! $ ) {
    				$ = typeof window !== 'undefined' ? // jQuery's factory checks for a global window
    					require('jquery') :
    					require('jquery')( root );
    			}

    			return factory( $, root, root.document );
    		};
    	}
    	else {
    		// Browser
    		factory( jQuery, window, document );
    	}
    }

```
The complete dataTables library can be found here

http://cdn.datatables.net/1.10.19/js/jquery.dataTables.js

### Expected Behavior

I was expecting rollup to bundle these two resources together in a way that could be run in the browser without errors. 

### Actual Behavior

The name "exports" is shadowed by the input variable for the top level scope.
```
var helloworld = (function (exports) {
    'use strict';

    function f() {
        return 1;
    }

...
```

 so we get a "module" is not defined error on the module.exports line.

The datatables libraries do not appear to have es6 versions. I'm a bit new to this level of js development, so feel free to correct me if my approach is wrong.

**Comment by lukastaegert** [comment]
Rollup cannot import a UMD module without plugins as Rollup natively only understands ES modules. The easiest solution is to include rollup-plugin-commonjs, which should detect the use of `module.exports` and inject a proper CJS polyfill to make everything work.

**Comment by shellscape** [comment]
Closing as we've reached 60 days without comment + reply explaining the issue.
