### ISSUE TITLE
output es6 module

### ISSUE THREAD

**Issue by yukulele** [rollup/rollup#2846]
### Feature Use Case
Create es6 module usable in (modern) browser

### Feature Proposal
Target es6 module output with `output.format = 'module'`

**Comment by Birch-san** [comment]
Notionally, `output.format = 'esm'` already does what you're proposing.

**Comment by lukastaegert** [comment]
Fun fact: `output.format = 'module'` should actually work as well as it is internally an alias for `esm` :)
