### ISSUE TITLE
output.entryFileNames is ignored with preserveModules: true

### ISSUE THREAD

**Issue by Birch-san** [rollup/rollup#2847]
I want to write my source in TypeScript, and output `.mjs` ES modules for each TypeScript source file.

- Rollup Version: 1.11.3
- Operating System (or Browser): macOS
- Node Version: v11.8.0

### How Do We Reproduce?

```bash
mkdir -p rollup-ts-esm/src
cd rollup-ts-esm
npm init -y
npm i --save-dev 'rollup@1.11.3' 'rollup-plugin-typescript2@0.21.0' 'typescript@3.4.5'
>rollup.config.js <<EOJS
import typescript2 from 'rollup-plugin-typescript2'

export default {
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    entryFileNames: '[name].mjs',
    format: 'esm',
  },
  preserveModules: true,
  plugins: [
    typescript2({ include: 'src/**' }),
  ],
}
EOJS
>src/index.ts <<EOTS
export * from './lol'
export * from './wut'
EOTS
>src/lol.ts <<EOTS
export class Lol<T> {
  greater<T>(t1: T, t2: T): T {
    return t1 > t2 ? t1 : t2;
  }
}
EOTS
>src/wut.ts <<<'export class Wut {}'
npx rollup -c
ls dist
```

### Expected Behavior

Dist should contain:

```
index.mjs
lol.mjs
wut.mjs
```

`.mjs` extension, ESM-compliant contents.

### Actual Behavior

Dist contains:

```
index.ts
lol.ts
wut.ts
```

_`.ts`_ extension, ESM-compliant contents.

**Comment by Birch-san** [comment]
Workaround I'm using for now is:

```js
import typescript2 from 'rollup-plugin-typescript2'
import renameExtensions from '@betit/rollup-plugin-rename-extensions'

export default {
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    format: 'esm',
  },
  plugins: [
    typescript2({ include: 'src/**' }),
    renameExtensions({
      include: ['**/*.ts'],
      mappings: {
        '.ts': '.mjs',
      },
    }),
  ],
}
```

**Comment by DrecDroid** [comment]
Happening the same to me. Thanks for the workaround

**Comment by Robinfr** [comment]
Workaround unfortunately doesn't seem to work for me (probably because of JSX/TSX files).

**Comment by Andarist** [comment]
@lukastaegert @shellscape do you have any preferences on how API for this should look like and behave? I could implement this

**Comment by shellscape** [comment]
@Andarist that would be amazing, thank you. Lukas will have far better input on this than I, but I know that we're very open to suggestion. Shall I assign this to you?

**Comment by lukastaegert** [comment]
My hope is that we can reuse the existing entryFileNames property. The default is `[name].js` which would mean if for `preserveModules`, we set `[name]` to `file/path/without/extension`, it should be nearly identical to the way it works at the moment except that all extensions will become `.js`. Which may actually solve issues for some, e.g. when starting from TypeScript.

If you want extensions, we could allow `[ext]` and `[extname]` placeholders similar to those for assets. Not sure what to do with those when not preserving modules, though, as we do not have extensions e.g. when using the object form of `input`. Here we could just set them to `js` or `.js` respectively and see if we can implement it situations where we *do* have an extension available.

Thoughts?

**Comment by Andarist** [comment]
Sounds reasonable, let's see where I land with my PR regarding `[ext]`. Won't have time to work on this in following days - but I'll definitely try to get to this soon(-ish)

**Comment by myklt** [comment]
Thanks for the fix!

The only small problem now is that all files are converted using the same pattern and in the end we have even `.less` or `.scss` files named exactly the same. So in case of having 2 source files with the same name, but different extension, for example `Button.scss` and `Button.tsx`, after the build, we get `Button.js` and `Button2.js`.

**Comment by lukastaegert** [comment]
So this is a request to have the `[ext]` available? Or do you have something else in mind? Please create a ticket so that we know what people need.

**Comment by Andarist** [comment]
Please also tag me in that issue - would like to be involved in the discussion as I'm the one who made that change.

**Comment by awmottaz** [comment]
@myklt @lukastaegert @Andarist I created #3107
