### ISSUE TITLE
UMD Build doesn't build source map file

### ISSUE THREAD

**Issue by abhisekp** [rollup/rollup#2849]
- Rollup Version: v1.11.3
- Operating System (or Browser): Ubuntu Xenial 16.04
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
- Node Version: v12.0.0
- npm Version: 6.9.0

### How Do We Reproduce?

```js
// rollup.config.js

import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import compiler from '@ampproject/rollup-plugin-closure-compiler';
import typescript from '@wessberg/rollup-plugin-ts';
import pkg from './package.json';

export default [
  // browser-friendly UMD build
  {
    input: 'src/main.ts',
    external: ['yup'],
    output: {
      name: 'yupPhone',
      file: pkg.browser,
      format: 'umd',
      sourcemap: true,
      globals: {
        yup: 'yup',
      },
    },
    plugins: [
      resolve({
        browser: true,
        modulesOnly: true,
      }), // so Rollup can find `yup`
      commonjs(), // so Rollup can convert `yup` to an ES module
      typescript({
        transpiler: 'babel',
        verbosity: 3,
        clean: true,
        check: true,
      }),
      // compiler(),
    ],
  },

  // CommonJS (for Node) and ES module (for bundlers) build.
  // (We could have three entries in the configuration array
  // instead of two, but it's quicker to generate multiple
  // builds from a single configuration where possible, using
  // an array for the `output` option, where we can specify
  // `file` and `format` for each target)
  {
    input: 'src/main.ts',
    external: ['yup'],
    output: [
      { file: pkg.main, format: 'cjs', sourcemap: true },
      { file: pkg.module, format: 'es', sourcemap: 'inline' },
    ],
    plugins: [
      typescript({
        transpiler: 'babel',
        verbosity: 3,
        clean: true,
        check: true,
      }),
      // compiler(),
    ],
  },
];

```

### Expected Behavior

Create a sourcemap file called **`yup-phone.umd.js.map`**

### Actual Behavior

The UMD build contains the following line at the end but ***NO*** actual file is generated  
**`//# sourceMappingURL=yup-phone.umd.js.map`**

Also The ESM build contains the inline sourcemap but no sourcemap file is generated for CJS build. Only the following line is appended at the end of CJS file.  
**`//# sourceMappingURL=yup-phone.cjs.js.map`**

> Hence, only inline sourcemap is generated but file sourcemap is not.

**Comment by abhisekp** [comment]
I don't know. For some reason magical, now it builds.

**Comment by ventralnet** [comment]
Note: if you are using IntelliJ among other IDEs I noticed in the file explorer .map files are not shown.  Listing the directory in the terminal I saw my map file sitting there.
