### ISSUE TITLE
Any plans for static files plugins?

### ISSUE THREAD

**Issue by vdclouis** [rollup/rollup#285]
Are they any plans for say a sass plugin?
Or will rollup focus on js only?

**Comment by Victorystick** [comment]
> Are they any plans for say a sass plugin?

Could you elaborate?

**Comment by vdclouis** [comment]
Well webpack can convert less/sass to css for example.
I could however just use the command line and add a npm script.

**Comment by TrySound** [comment]
@vdclouis I think about css-modules. But need to close some issues and I will make it.

**Comment by petulla** [comment]
@TrySound Did the sass loader/node-sass implementation ever get made?

**Comment by TrySound** [comment]
@petulla Not at all. I'm not interested in any preprocessors except postcss. You can implement if you want. But still it's very ugly solution.

**Comment by Rich-Harris** [comment]
Some discussion about a node-sass plugin on Twitter earlier – https://twitter.com/Rich_Harris/status/698849899052457984. I'm a postcss guy as well, but you're not alone in looking for a sass version. Would be a useful addition to the stable.

**Comment by differui** [comment]
Hi @vdclouis, I created a ready simple one: [rollup-plugin-sass](https://www.npmjs.com/package/rollup-plugin-sass)
