### ISSUE TITLE
Rollup not removing unused constants

### ISSUE THREAD

**Issue by owen-m1** [rollup/rollup#2852]
- Rollup Version: 1.11.3
- Operating System (or Browser): Windows 10
- Node Version: v10.15.3

### How Do We Reproduce?
View [REPL](https://rollupjs.org/repl?version=1.11.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMEVkZ2UlMjAlN0QlMjBmcm9tJTIwJy4lMkZicm93c2VySW5mby5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKEVkZ2UpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYnJvd3NlckluZm8uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjB1c2VyQWdlbnQocGF0dGVybiklMjAlN0IlNUNuJTVDdHJldHVybiUyMG5hdmlnYXRvciUyMCUyNiUyNiUyMG5hdmlnYXRvci51c2VyQWdlbnQlMjAlMjYlMjYlMjAhIW5hdmlnYXRvci51c2VyQWdlbnQubWF0Y2gocGF0dGVybiklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMElFMTFPckxlc3MlMjAlM0QlMjB1c2VyQWdlbnQoJTJGKCUzRiUzQVRyaWRlbnQuKnJ2JTVCJTIwJTNBJTVEJTNGMTElNUMlNUMuJTdDbXNpZSU3Q2llbW9iaWxlKSUyRmkpJTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwRWRnZSUyMCUzRCUyMHVzZXJBZ2VudCglMkZFZGdlJTJGaSklM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBGaXJlRm94JTIwJTNEJTIwdXNlckFnZW50KCUyRmZpcmVmb3glMkZpKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMFNhZmFyaSUyMCUzRCUyMHVzZXJBZ2VudCglMkZzYWZhcmklMkZpKSUyMCUyNiUyNiUyMCF1c2VyQWdlbnQoJTJGY2hyb21lJTJGaSklMjAlMjYlMjYlMjAhdXNlckFnZW50KCUyRmFuZHJvaWQlMkZpKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMElPUyUyMCUzRCUyMHVzZXJBZ2VudCglMkZpUChhZCU3Q29kJTdDaG9uZSklMkZpKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior
I expect the output to only include the declaration for the const `Edge`, as the other variables are not imported and do not cause any side effects in the `browserInfo.js` file.

### Actual Behavior
You will see that the output file includes all of the browser info constants, even though they are not imported in `main.js` and are never used.

**Comment by lukastaegert** [comment]
There are several possible side-effects at play here that prevent Rollup from removing the code:

* `navigator` is not a standard variable across JavaScript environments and unfortunately rollup is not yet able to understand that in a pattern such as `navigator && navigator.userAgent`, it is not possible for an "undefined is not an object"  error to occur (sadly).

* Even if Rollup knew that, it would not know that `navigator.userAgent.match` exists and is a function without side-effects.

There are at least two ways of addressing this:
1. Annotate all calls to `userAgent` with a `/*@__PURE__*/` annotation: https://rollupjs.org/repl?version=1.11.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMEVkZ2UlMjAlN0QlMjBmcm9tJTIwJy4lMkZicm93c2VySW5mby5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKEVkZ2UpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYnJvd3NlckluZm8uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjB1c2VyQWdlbnQocGF0dGVybiklMjAlN0IlNUNuJTVDdHJldHVybiUyMG5hdmlnYXRvciUyMCUyNiUyNiUyMG5hdmlnYXRvci51c2VyQWdlbnQlMjAlMjYlMjYlMjAhIW5hdmlnYXRvci51c2VyQWdlbnQubWF0Y2gocGF0dGVybiklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMElFMTFPckxlc3MlMjAlM0QlMjAlMkYqJTQwX19QVVJFX18qJTJGdXNlckFnZW50KCUyRiglM0YlM0FUcmlkZW50LipydiU1QiUyMCUzQSU1RCUzRjExJTVDJTVDLiU3Q21zaWUlN0NpZW1vYmlsZSklMkZpKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMEVkZ2UlMjAlM0QlMjAlMkYqJTQwX19QVVJFX18qJTJGdXNlckFnZW50KCUyRkVkZ2UlMkZpKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMEZpcmVGb3glMjAlM0QlMjAlMkYqJTQwX19QVVJFX18qJTJGdXNlckFnZW50KCUyRmZpcmVmb3glMkZpKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMFNhZmFyaSUyMCUzRCUyMCglMkYqJTQwX19QVVJFX18qJTJGdXNlckFnZW50KCUyRnNhZmFyaSUyRmkpKSUyMCUyNiUyNiUyMCElMkYqJTQwX19QVVJFX18qJTJGdXNlckFnZW50KCUyRmNocm9tZSUyRmkpJTIwJTI2JTI2JTIwISUyRiolNDBfX1BVUkVfXyolMkZ1c2VyQWdlbnQoJTJGYW5kcm9pZCUyRmkpJTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwSU9TJTIwJTNEJTIwJTJGKiU0MF9fUFVSRV9fKiUyRnVzZXJBZ2VudCglMkZpUChhZCU3Q29kJTdDaG9uZSklMkZpKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

2. Set the `treeshake. propertyReadSideEffects` option to `false` and annotate the call to `.match` with a `/*@__PURE__*/` annotation (not tested as I cannot disable propertyReadSideEffects in the REPL; the annotation should probably go between `!!` and `navigator.userAgent.match(pattern)`

**Comment by owen-m1** [comment]
@lukastaegert I did the first solution and it works great 👌 

Thanks!
