### ISSUE TITLE
Using preserveModules causes exports in the entry point to disappear

### ISSUE THREAD

**Issue by TomCaserta** [rollup/rollup#2854]
- Rollup Version: 1.11.3
- Operating System (or Browser): macOS Mojave 10.14
- Node Version: v11.1.0

### How Do We Reproduce?

Small Repro repo: https://github.com/TomCaserta/rollup-export-issue

Essentially create a project with nested folder structure with index files that only export other files.

### Expected Behavior
Every export should be preserved.

### Actual Behavior
The entry point file becomes empty.

Note: Setting `treeshake` to `false` does modify the behaviour however it transforms `exports` into `imports`. Eg:

Original File:
```js
export * from './inner/index.js';
```

Output file:
```js
import './inner/index.js';
```

**Comment by lukastaegert** [comment]
I believe this is now fixed via #2863, thanks again, feel free to reopen if there are missing points.
