### ISSUE TITLE
Indicate whether a chunk is in the static or dynamic dependency graph

### ISSUE THREAD

**Issue by philipwalton** [rollup/rollup#2855]
### Feature Use Case

When deploying a site that uses real modules and dynamic `import()`, it's often helpful to know which chunks are in the initial, static dependency graph vs. chunks that are *only* dynamically imported (including static imports of only dynamically-imported chunks).

The use case for this is if you want to create a list of modules to preload (via [`modulepreload`](https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload)) and only include modules that would be initially imported via static `import` statements.

This is often necessary as the `modulepreload` spec doesn't not require UAs to preload module dependencies.

### Feature Proposal

Right now you can manually determine this in the `generateBundle` hook by looping through each entry point and inspecting that entry's imports, but it would be nice if this info were provided by Rollup.

There could be an additional flag exposed on the `assetInfo` object named something like `isStaticDependency`, which would be set to `true` if the chunk were a static dependency of any entry chunk.

* * *

Another interesting use-case for exposing this information would be a build-time check to ensure all dynamic entry points were **not also** static dependencies of any entry chunks (as that would kinda defeat the purpose of making them a dynamic import).

While converting one of my site's to use dynamic import, I accidentally forgot to do this in one place, and the module I thought I was lazily loading was actually being eagerly loaded. It would have been nice to get warning about this (perhaps something a plugin could do, if too opinionated for Rollup core).

**Comment by lukastaegert** [comment]
> perhaps something a plugin could do, if too opinionated for Rollup core

I am undecided on this one. The value of this information is clear when there is only a single entry point but it becomes less clear when there is more than one. In such a situation, are all entry points considered to be part of the static graph? And what about entry points emitted by chunks? My feeling is that looping through the bundle may be a better option here. A plugin could also just let you specify which entry points you are interested in (and provide a reasonable default).

**Comment by philipwalton** [comment]
Thanks for your thoughts. If you think this use case would be better handled by a plugin, that's fine by me.
