### ISSUE TITLE
Duplicated identifier when reexporting default

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#2865]
One of our users hit an error when trying to use `firebase` in their stencil project, i have debugged it a little further and managed to create a simple repo case in the REPL.

https://github.com/ionic-team/stencil/issues/1539

```
import { b as firebase$1, a as firebase$1 } from './chunk-bc81a3f0.js';
```
^^ generating the following line

- Rollup Version: 1.12.2
- Operating System (or Browser): Osx
- Node Version: 12.2.0

### How Do We Reproduce?

https://rollupjs.org/repl?version=1.12.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGElMjBmcm9tJTIwJy4lMkZtb2R1bGUxLmpzJyUzQiU1Q25pbXBvcnQlMjBiJTIwZnJvbSUyMCcuJTJGbW9kdWxlNC5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGElMkMlMjBiKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZTEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjBmaXJlYmFzZSUyMCUzRCUyMCU3QiU3RCUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZmlyZWJhc2UlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBmaXJlYmFzZSUyMGZyb20lMjAnLiUyRm1vZHVsZTEnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmaXJlYmFzZSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGUzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGElMjBmcm9tJTIwJy4lMkZtb2R1bGUxLmpzJyUzQiU1Q25pbXBvcnQlMjBiJTIwZnJvbSUyMCcuJTJGbW9kdWxlNC5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGElMkMlMjBiKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZTQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZmlyZWJhc2UlMjBmcm9tJTIwJy4lMkZtb2R1bGUyJyUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZmlyZWJhc2UlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior

It should not emit duplicated identifiers.

```
import { a as b, b } from '../chunk-4fb3a870.js';
```
^ `b` identifier is duplicated

**Comment by lukastaegert** [comment]
Thanks for the perfect reproduction! Default exports have been plaguing us time and again, this time I think I have a very good solution at #2866
