### ISSUE TITLE
Support clean folder import syntax and chunking

### ISSUE THREAD

**Issue by atomiks** [rollup/rollup#2870]
### Feature Use Case

Currently, users need to import like this:

```js
import {add} from 'math/esm/math-utils'
```

```
math/
├── esm/
|   ├── chunk-47812892.js
|   ├── math.js
│   ├── math-utils.js
```

This is a bit annoying and doesn't look clean. Ideally, they would just be able to do this:

```js
import {add} from 'math/utils'
```

```
math/
├── utils/
│   ├── math-utils.js
|   ├── package.json
├── esm/
|   ├── chunk-47812892.js
│   ├── math.js
```

`utils` becomes a folder with its own `package.json` and `"module"` field pointing toward `math-utils.js`. The filename includes the package's name as well for DevTools display, but not when importing since you're referencing a folder path. `math-utils` should utilize optimized chunks from the main entry point.

### Feature Proposal

I don't know if this is possible or realistic, but this is how `preact` does this for its `hooks` addon subfolder, but there's no chunking suport with this technique I think.

**Comment by lukastaegert** [comment]
Not sure if I completely understand your issue, I believe all you want should be possible without any changes to Rollup core.
- You can place chunks into sub-folders. In your case, you should be able to do something like
   ```js
   // rollup.config.js
   export default {
     input: {
       "esm/math": "src/math.js",
       "utils/math-utils": "src/math-utils.js"
     },
     output: {
       format: "esm",
       dir: "math",
       chunkFileNames: "esm/[name]-[hash].js"
     }
   }
   ```
   This should provide you with full chunking support
- Of course you will need to add the `package.json` file manually. Internally, Rollup will not simplify imports based on the presence of a this file but if you want to Rollup something else that imports your code, `rollup-plugin-node-resolve` will automatically resolve directory imports via package.json files.

**Comment by atomiks** [comment]
Wasn't aware, thanks! That technique works fine 🙂

**Comment by lukastaegert** [comment]
Maybe the docs should highlight this more 😉
