### ISSUE TITLE
Add pure module import rules

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2874]
### Feature Use Case

`treeshake.moduleSideEffects` can't help in further bundling.

If I generated a tool lib into a bundled file (with external imports in it), and others import it and other libs after that, they are hard to specify the situation of all the modules the libs had tried to imported.

#### plan a

```js
import { a } from 'no-side-effect';//#__PURE__: Mark modules which have no side effects for downward compatibility, because we check side effects by default;

import { b } 'side-effect';//!__PURE__: Or, mark modules which have side effects, because they are fewer.

await /*#__PURE__*/import('no-side-effect');
```

#### plan b

Or, treat all none-imports as side effect case, and all named-imports as no side effect case:

```js
import { a } from 'no-side-effect';

import 'side-effect';
```

```js
// if need named-import from side effect module, then none-import it again:
import 'side-effect';
import { b } 'side-effect';

// if there is no idea about side effect info, leave an empty named-import after treeshake:
import { a } from 'side-effect-unknown';
import { } from 'side-effect-unknown';
```

**Comment by lukastaegert** [comment]
I think the tool you are asking for that will actually be respected by other bundlers today is to add a `package.json` file specifying a `sideEffects` property. This is basically the documentation of this feature (at least the only that I am aware of): https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

This is respected at least by Webpack as well as rollup-plugin-node-resolve. As for the proposal with the comments, this could be doable but it would only be useful if it found greater adoption by other bundlers. Considering there is already the `package.json` solution I am not sure we can expect support here. The proposal with distinguishing via import patterns is also very specific, needs to be supported by other bundlers and is easily broken by tools that do automatic import deduplication/sorting. Also, it adds semantics into imports that is just not part of that syntax, I would not feel comfortable implementing it this way.

**Comment by LongTengDao** [comment]
@lukastaegert You are right, thanks tell me that solution, and adding meanings to spec is not very good.

But maybe when we considered rollup is currently the best and most widely used js packing tool, and minify tools (like terser) don't need to deal with packing things, a defacto standard which use conventional comment may be still good try.

But I'm not sure about that, maybe need more discussion and opinion. @fabiosantoscode What do you think of this?

**Comment by shellscape** [comment]
@LongTengDao is this issue something you would like to keep open and complete?

**Comment by LongTengDao** [comment]
@shellscape there is many ways to do that, so I prefer to close this issue.
