### ISSUE TITLE
Support different configuration languages

### ISSUE THREAD

**Issue by k2snowman69** [rollup/rollup#2879]
### Feature Use Case
Supporting other configuration languages can improve developer flow. For example, implementing a typescript configuration flow will allow for static typing of the config itself and provide inline errors in VSCode and other editors before the developer even runs the build.

### Feature Proposal
Implement something similar to Webpack's supported configuration languages. Based on the [documentation](https://webpack.js.org/configuration/configuration-languages/) they are using [interpret](https://github.com/gulpjs/interpret) to translate the configs from all the other languages back into javascript.

**Comment by waynevanson** [comment]
This would be super useful. In a typescript example, all the developer would have to do is ensure they had something like `ts-node` installed in the package or on their system. Webpack does this by default.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by nmccready** [comment]
@shellscape re-open

**Comment by dvkndn** [comment]
an editor-only work-around: https://stackoverflow.com/a/57330838

```ts
/** @type {import('rollup').RollupOptions} */
const options = {
  ...
};

export default options;
```

**Comment by seivan** [comment]
So there are few ways around this. 
One is to use the Rollup script API
and load it using 
```js
        "r:script": "ts-node rollup.config.ts",
```
where `tsconfig.json` has a 
```json
    "ts-node": {
        "compilerOptions": {
            "module": "CommonJS",
            "target": "ES5",
            "esModuleInterop": true,
            "importHelpers": true,
            "resolveJsonModule": true,
            "noImplicitAny": false, // Needed for plugins
            "noImplicitReturns": false, // Fix later
        }
    },
```

The other approach is to make a `rollup.config.js` that refers to `rollup.config.ts`

```js
require('ts-node').register({
    compilerOptions: {

        module: "CommonJS",
        target: "ES5",
        esModuleInterop: true,
        importHelpers: true,
        resolveJsonModule: true,
        noImplicitAny: false, // Needed for plugins
        noImplicitReturns: false, // Fix later



    },

    // and other tsconfig.json options as you like
});

module.exports = require('./rollup.config.ts');
```

I wish there was to use the `ts-node` without being forced to Rollup programatically.

**Comment by seivan** [comment]
> Some repositories do have the `rollup.config.ts` file at the moment ([for example](https://github.com/alexjoverm/typescript-library-starter/blob/master/rollup.config.ts)) but I don't see any typing in the file.

That's because it's a lie, it's just named `ts` for "consistency"... whatever the hell that means.

**Comment by sidvishnoi** [comment]
ICYMI: https://github.com/rollup/rollup/pull/3835
