### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by DIMITA** [rollup/rollup#2883]
This is my file's code 

`exports.execSql = function (execSql, callback){

    var conn= new mysql.createConnection(setting.dbconfig);
    conn.connect()
    .then(function () { 
        var require = new mysql.Request(conn);
        req.query(sql)
    .resolve(function (recordset) {
                callback(recordset);
        })
        .catch(function (err) {
            console.log(err);
        callback(null, err);
        })
    })
    .catch(function (err) {
        console.log(err);
        callback(null, err);
    });
};` 

And i have this error

TypeError: Cannot read property 'then' of undefined

Who can help me?

**Comment by lukastaegert** [comment]
Please do not abuse Rollup's issues, which are for bugs and feature requests, for support issues. This will keep the developers from improving Rollup. Stack-Overflow is a better place for these kind of questions. Also you completely ignored the issue template and did not mention how Rollup has anything to do with your issue.
