### ISSUE TITLE
`module` no longer avoided as a variable name

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#2886]
- Rollup Version: 1.13.0
- Operating System (or Browser): Linux
- Node Version: 12.3.1

### How Do We Reproduce?

Between 1.12.5 and 1.13.0, `module` stopped being avoided as a variable name. Compare [this REPL](http://rollupjs.org/repl?version=1.12.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMG1vZHVsZSUyMGZyb20lMjAnLiUyRmZvby5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKG1vZHVsZSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMDQyJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) and [this one](http://rollupjs.org/repl?version=1.13.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMG1vZHVsZSUyMGZyb20lMjAnLiUyRmZvby5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKG1vZHVsZSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMDQyJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE). The code produced in the REPL doesn't cause an error in Node, but if you bundle with `preferConst: true`, it results in `const module = 42;`, which Node does complain about as being a variable getting redeclared.

### Expected Behavior

`module` should continue to be deconflicted from the Node built-in, at least in `preferConst` mode.

### Actual Behavior

Rollup will output code like `const module = 42;`, which Node doesn't like.

**Comment by lukastaegert** [comment]
Thanks for spotting this, proper fix at #2889
