### ISSUE TITLE
Class expression with extends clause is removed

### ISSUE THREAD

**Issue by fasttime** [rollup/rollup#2891]
- Rollup Version: 1.13.1
- Operating System (or Browser):
- Node Version: 12.3.1

### How Do We Reproduce?

Consider the following exported function containing an anonymous class expression.

```js
export function isConstructor(fn) {
    if (fn === null)
        return false;
    try {
        void class extends fn { };
    } catch {
        return false;
    }
    return true;
}
```

In the bundled version, the class expression is dropped, causing the function to always branch out of the catch block.

```js
function isConstructor(fn) {
    if (fn === null)
        return false;
    try {
    } catch {
        return false;
    }
    return true;
}
```

The only way I found to fix the issue is turning off treeshaking completely, which is not desirable.

### Expected Behavior

```js
isConstructor(true);   // false
isConstructor(isNaN);  // false
isConstructor(String); // true
```

### Actual Behavior

```js
isConstructor(true);   // true
isConstructor(isNaN);  // true
isConstructor(String); // true
```

**Comment by lukastaegert** [comment]
As a side-effect, #2892 should solve this issue as well without forcing a complicated deoptimization around super class definitions.
