### ISSUE TITLE
`esm` output leaves behind dead namespace import

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup#2895]
I use `import * as ts from "typescript";` inside my code.
When targeting `esm` output in rollup, all the imports are rewritten to specific identifiers, but one `import * as ts` is left behind, which is not used anywhere in the resulting bundle.
The `commonjs` output works correctly in this regard.

- Rollup Version: 1.13.1
- Operating System (or Browser): arch
- Node Version: 11.15

### How Do We Reproduce?

I wasn’t really able to reduce the testcase. I can’t reproduce it with simple examples in the REPL.
A whole repo repro is here:
https://github.com/Swatinem/rollup-plugin-dts/tree/v1.0.0

### Expected Behavior

There should be no unused `import * as ts` left in the code.

### Actual Behavior

One `import * as ts` in left behind, but the resulting `ts` identifier is not referenced anywhere in the code. All the other namespace imports are resolved to specific imports.

See the output here:
https://unpkg.com/rollup-plugin-dts@1.0.0/dist/rollup-plugin-dts.mjs

**Comment by lukastaegert** [comment]
Managed to create a minimal repro. It seems to require a combination of destructuring and a call expression:
https://rollupjs.org/repl?version=1.14.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHN0dWZmJTIwZnJvbSUyMCdleHRlcm5hbCclNUNuJTVDbmNvbnN0JTIwJTdCeCU3RCUyMCUzRCUyMHN0dWZmLnkoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

If you change the assignment to not use the destructuring, the issue does not show:
https://rollupjs.org/repl?version=1.14.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHN0dWZmJTIwZnJvbSUyMCdleHRlcm5hbCclNUNuJTVDbmNvbnN0JTIweCUyMCUzRCUyMHN0dWZmLnkoKS54JTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by lukastaegert** [comment]
Thanks, there was really something we missed in our code, fix at #2900

**Comment by Swatinem** [comment]
Amazing how quickly you fix these things, thanks :-)
