### ISSUE TITLE
Treeshaking of arguments leads to SyntaxError

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#2909]
- Rollup Version: 1.14.4
- Operating System (or Browser): osx and browser
- Node Version: 12.0.0

### How Do We Reproduce?

https://rollupjs.org/repl?version=1.14.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QndyaXRlR2VvbWV0cnklN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuY29uc29sZS5sb2cod3JpdGVHZW9tZXRyeSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMHdyaXRlR2VvbWV0cnkoZ2VvbWV0cnklMkMlMjBvcHRfb3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwd3JpdGVQb2ludEdlb21ldHJ5KChnZW9tZXRyeSklMkMlMjBvcHRfb3B0aW9ucyklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMHdyaXRlUG9pbnRHZW9tZXRyeShnZW9tZXRyeSUyQyUyMG9wdF9vcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwdHlwZSUzQSUyMCdQb2ludCclMkMlNUNuJTIwJTIwJTIwJTIwY29vcmRpbmF0ZXMlM0ElMjBnZW9tZXRyeSUyQyU1Q24lMjAlMjAlN0QlM0IlNUNuJTdEJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behavior

It should generate valid JS:

### Actual Behavior

It does generate JS with syntax errors:
```js
function writeGeometry(geometry, opt_options) {
  return writePointGeometry((geometry);
}
```
^ notice the missing closing `)` after `geometry)`.

### Real world
This issue was first reported by an user of stencil when trying to use the `ol` (open layers) https://www.npmjs.com/package/ol package.

https://github.com/ionic-team/stencil/issues/1607

Specifically this piece of the code:

```js
function writePointGeometry(geometry, opt_options) {
  return {
    type: 'Point',
    coordinates: geometry.getCoordinates()
  };
}
function writeGeometry(geometry, opt_options) {
  geometry = /** @type {import("../geom/Geometry.js").default} */ (transformWithOptions(geometry, true, opt_options));
  var type = geometry.getType();

  /** @type {GeoJSONGeometry} */
  var geoJSON;
  switch (type) {
    case GeometryType.POINT: {
      geoJSON = writePointGeometry(/** @type {Point} */ (geometry), opt_options);
      break;
    }
 }
}
```

```js
      geoJSON = writePointGeometry(/** @type {Point} */ (geometry), opt_options);
```

**Comment by manucorporat** [comment]
Error seems related with https://github.com/acornjs/acorn/issues/136

**Comment by manucorporat** [comment]
The argument's start/end does not include the surrounding parentheses, looking into a solution...

**Comment by manucorporat** [comment]
Looks like this could be a problem for any expression surrounded by `parentheses`:
<img width="1602" alt="Screenshot 2019-06-09 at 16 26 04" src="https://user-images.githubusercontent.com/127379/59160152-57f64280-8ad3-11e9-8fbf-f1737415eacd.png">

This seems like a odd behaviour from acorn

**Comment by manucorporat** [comment]
I think the solution is to set `preserveParens: true`, but that would require to fix a lot of parts of rollup

**Comment by lukastaegert** [comment]
I was thinking about that, but I agree it would shake many things up and it would create a non-standard syntax tree. Meanwhile I found a simpler solution, which is to just find the next "," after the argument :) PR upcoming

**Comment by lukastaegert** [comment]
Fix at #2910

**Comment by manucorporat** [comment]
@lukastaegert damn! pushed a PR 30 seconds ago
https://github.com/rollup/rollup/pull/2911

**Comment by manucorporat** [comment]
same fix!!! haha
