### ISSUE TITLE
All call parameters are treeshaken with tryCatchDeoptimization: false

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#2913]
- Rollup Version: 1.14.5
- Operating System (or Browser): osx
- Node Version: 12.0.0

### How Do We Reproduce?

index.js
```js
function foo(bar) {
  bar.prop = 12;
}
function main(obj) {
  try {
    foo(obj);
  } catch (e) {
    console.error(e);
  }
}
main({});
```

rollup.config.js
```js
export default {
  input: 'index.js',
  treeshake: {
    tryCatchDeoptimization: false,
  },
  output: {
    format: 'es',
    file: 'output.js'
  }
};
```

Also, included a small repo case, just:

[rollup-bug.zip](https://github.com/rollup/rollup/files/3269840/rollup-bug.zip)

```
npm i
npm run build
```
and inspect the `output.js` file

### Expected Behavior

The parameter passed to the `foo` functions should not be treeshaken, since it's actually used.

```js
function main(obj) {
  try {
    foo(obj);
  } catch (e) {
    console.error(e);
  }
}
```
### Actual Behavior

```js
function main(obj) {
  try {
    foo();
  } catch (e) {
    console.error(e);
  }
}
```
making it crash at runtime, since foo expects an argument

**Comment by lukastaegert** [comment]
Fix at #2914. Turns out it was a simple oversight in TryStatement that could have caused even more mayhem, thanks for spotting and reporting it!
