### ISSUE TITLE
Problem compiling the whole angular project as hypothetical directory 

### ISSUE THREAD

**Issue by kumaraditya1999** [rollup/rollup#2919]
I am trying to bundle an angular project using rollup and rollup-hypothetical. The special case is that my entire angular project is hypothetical. I have made a json object and the key represents the realtive path to that file in project and the value represents the content of the folder. The problem is that it get bundled but then the bundling is not correct.I have tried to bundle the exact project normally using rollup and it works fine.But using hypothetical it generates error that can't resolve the all the parameters of app.component.So I checked the actual bundle and I found that there were some differences in the correct bundle and incorrect bundle.the template url and style url had the path '/app/app.component.html' where as in the correct bundle it had the html content '`<html><body><app-root></app-root></body></html>`' and like wise for the styles also.I want to know where its the issue with plugin or the rollup config.
```
const rollup = require('rollup');
const typescript = require('rollup-plugin-typescript');
const resolve = require('rollup-plugin-node-resolve');
const angular = require('rollup-plugin-angular');
var hypothetical = require( 'rollup-plugin-hypothetical');
var project = require('./project');



// for bundle.js
const  inputOptionsBundle = {
    input: './Project/src/main.ts',
    external: [
        '@angular/core',
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/http',
        '@angular/platform-browser',
        '@angular/platform-browser-dynamic',
        '@angular/router',
        '@angular/router-deprecated',
        'tslib'
      ],
      plugins: [
          
        hypothetical({
          files: project,
          impliedExtensions: ['.js','/','.ts','.html','.css'],
        }),
        typescript(),
        angular() ,
                 
      ],
};
const outputOptionsBundle = {
    format: 'iife',
    file: 'dist/bundle.es2015.js',
    globals: {
        '@angular/common' : 'vendor._angular_common',
        '@angular/compiler' : 'vendor._angular_compiler',
        '@angular/core' : 'vendor._angular_core',
        '@angular/http' : 'vendor._angular_http',
        '@angular/platform-browser' : 'vendor._angular_platformBrowser',
        '@angular/platform-browser-dynamic' : 'vendor._angular_platformBrowserDynamic',
        '@angular/router' : 'vendor._angular_router',
        '@angular/forms' : 'vendor._angular_forms',
        'tslib':'vendor._tslib'
      }
};

async function buildBundle(){
    const bundle = await rollup.rollup(inputOptionsBundle);
    const { output } = await bundle.generate(outputOptionsBundle);
    for (const chunkOrAsset of output){
        if(chunkOrAsset.isAsset){
        }else{
        }
    }
    await bundle.write(outputOptionsBundle);
}

for(var item in project){
  console.log(item);
}
buildBundle();

```

This is my rollup config. I am using the rollup api for bundling.Any help or alternatives are welcomed.Thanks

**Comment by shellscape** [comment]
Thanks for opening an issue, and sorry it took a while for a reply. We don't usually field support questions like this here in the issues - that's why we have a header in the issue templates that ask users to use other means for support. If you've identified a problem or shortcoming with Rollup, please use one of the appropriate templates.

Since this hasn't seen any activity in 60 days, and it's a support request, we're going to close this one. Please try one of the support options, which I've copied from the template below:

>   👉🏽 Need help or tech support? Don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs
