### ISSUE TITLE
whatwg/tc39/node.js JSON modules

### ISSUE THREAD

**Issue by dnalborczyk** [rollup/rollup#2920]
consider deprecating the **rollup json plugin** https://github.com/rollup/rollup-plugin-json and pull in core functionality into **rollup main**, with some changes in behavior.

the **expected change** would be to be consistent with (see below) whatwg/tc39/node.js and treat the json import as a **default import**, and **do not allow or support named exports** .

couple reasons for not considering named exports: confusing and non-consistent behavior of "JSON Object" vs "JSON Array" (+ others, "string", null etc.). Also how to handle a "default" property on an "JSON Object".

if the separate json plugin is still a better option, it would be still great to adopt the consensus of not allowing named exports to have the same expectations working across browsers, engines and tools.

additional background:

**WHATWG**
https://github.com/whatwg/html/issues/4315
https://html.spec.whatwg.org/#json-module-script
https://html.spec.whatwg.org/#creating-a-json-module-script  (give it some time to load)

**TC39** https://docs.google.com/presentation/d/1w8jWjD41htD7VxOejFqiHi6uGgHVWtZ_XmgFxgKkS7Q/edit#slide=id.g5947c7781f_0_20

**Node.js modules working group**
https://github.com/nodejs/node/pull/27752

related **Webpack** issue:
https://github.com/webpack/webpack/issues/9246

### Expected Behavior / Situation
```js
// allow
import data from './data.json'

// disallow, throw
import { foo } from './data.json'
```

### Modification Proposal

_edit: modified reasons section, added webpack issue reference_

**Comment by shellscape** [comment]
@lukastaegert what are your thoughts on this? I don't personally have an issue with JSON module support being external. But it seems everyone and their brother has integrated it into their core.

**Comment by lukastaegert** [comment]
If it becomes an official feature, we could put it into core. But there will still be need for rollup-plugin-json as property tree-shaking is a useful feature that even Rollup itself relies upon. I would see this as a nice-to-have.

**Comment by dnalborczyk** [comment]
this proposal was the precursor to `import assertions` and can be closed.
