### ISSUE TITLE
Dynamic imported lib chunked together with static import module

### ISSUE THREAD

**Issue by ashubham** [rollup/rollup#2923]
- Rollup Version: 1.14.6
- Operating System (or Browser): OSX
- Node Version: 10.11.0

### How Do We Reproduce?

```javascript
//app.js
import { a as ColorScaleComponent } from './chunk-bcf64e58.js';```

// .. more code ..

async function chartUIRenderGeoMap(chartVizComponent, $chartContent) {
    let [{ GeoMapComponent }, { GeoUtils }] = await Promise.all([
        import('./blink-geo-map-50f50ffb.js'), // Lazy loaded here
        import('./geo-utils-fc725734.js')
    ]);
```
```javascript
//blink-geo-map-50f50ffb.js
import { b as GeoTopologyDataStore, c as ol, d as BaseVectorSource, e as PolygonFeatureLoader, a as ColorScaleComponent } from './chunk-bcf64e58.js';
```

```javascript
// chunk-bcf64e58.js Here lies the problem

// Code for color scale
// geomap Library code
```
### Expected Behavior

ColorScale and the Geo Lib code should be in separate chunks as lib code chunk is supposed to be lazily loaded. Color scale has no  dependency on Geo.

### Actual Behavior

Static import and dynamic import code is chunked together in  `chunk-bcf64e58.js` causing it to load unnecessarily.

**Comment by lukastaegert** [comment]
Not sure what to make of this. What is your input module dependency structure? Usually if code does not end up in a separate dynamic chunk, there is already a static import of this code.

**Comment by ashubham** [comment]
Issue was on my end, we had static imports.
