### ISSUE TITLE
Dynamic import chunking error

### ISSUE THREAD

**Issue by edoardocavazza** [rollup/rollup#2925]
- Rollup Version: 1.15.0
- Operating System (or Browser): MacOS
- Node Version: 12.3.1

### How Do We Reproduce?

https://rollupjs.org/repl?version=1.15.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRmNodW5rMS5qcycpJTNCJTVDbmltcG9ydCgnLiUyRmNodW5rMi5qcycpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGRvU29tZXRoaW5nKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdkbyUyMHNvbWUlMjBzdHVmZicpJTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjaHVuazEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwZG9Tb21ldGhpbmclQzIlQTAlN0QlMjBmcm9tJTIwJy4lMkZsaWIuanMnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmNodW5rMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjBkb1NvbWV0aGluZyVDMiVBMCU3RCUyMGZyb20lMjAnLiUyRmxpYi5qcyclM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior

Rollup is able to generate two chunks which import a third chunk with some exports.

### Actual Behavior

Rollup fails with error `Error: Internal Error: Could not find export name for variable YYY`

**Comment by lukastaegert** [comment]
Thanks a lot, fix at #2928.
