### ISSUE TITLE
Supporting Supplementary Analysis

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2926]
### Feature Use Case

Rollup performs some highly advanced optimizations in its core, that inform the treeshaking and chunk rendering process.

The analysis components of Rollup are highly complex, with likely only @lukastaegert fully understanding this part of the codebase.

AST specifications form a base on top of which open source libraries were able to be provided that abstracted common operations. Eg Rollup didn't need to implement its own AST parser. Might there be the potential for code analysis to be plugged in to rollup in a similar way, and what might these interfaces look like?

Perhaps we could use such tools with supplementary analysis to tackle scenarios such as some of those listed in https://github.com/rollup/rollup/issues?q=is%3Aopen+is%3Aissue+label%3Atreeshaking.

### Feature Proposal

If we were to expose magic string, the AST, and allow some kind of analysis engine injection into the process, could we work out some conventions around this supplementation?

For example - having the analysis set `node.included` and then having a `node.analyze = false` or similar to opt-out of Rollup analysis that might set `included = true`.

Even if only minor optimizations were possible initially, exploring such a separation may help in refactoring the analysis and treeshaking components towards analysis generalizations that might prove useful.

It would very much be an experimental undertaking, but it could be interesting to see if it could go somewhere.

Would be interested to hear your thoughts further @lukastaegert.

**Comment by lukastaegert** [comment]
Sounds like a nice long-term perspective!

**Comment by lukastaegert** [comment]
In other news, this is how Stencil does it’s amazing HMR. Spoiler: web components are a crucial part, but I could see it translated to situations where you have some DI going. https://twitter.com/manucorporat/status/1137264361523884032?s=21
