### ISSUE TITLE
Chokidar is not resolved depending on location

### ISSUE THREAD

**Issue by AgronKabashi** [rollup/rollup#2934]
**Context:**
I'm building a CLI that uses rollup behind the scenes to transpile JavaScript and its configured to use chokidar to watch for file changes.

CLI has rollup and chokidar installed as dependencies.

CLI is then executed inside a different project, say `MyProject`.
$ MyProject> CLI --input src/index.js

### Actual Behavior / Situation
Rollup throws a warning: ```watch.chokidar was provided, but chokidar could not be found. Have you installed it?```
This occurs because chokidar is not installed as a dependency in `MyProject`.
If the CLI is run from within its own folder then it works because it has chokidar installed as a dependency.

### Expected Behavior / Situation
Rollup is able to locate chokidar without having to install it as a dependency in `MyProject`. It should use the version that is installed by the CLI.

### Modification Proposal
The main problem lies with this line:
https://github.com/rollup/rollup/blob/c9eeef7431f37dc3012fbe72cb2074362939547c/src/watch/chokidar.ts#L7

One solution could be to locate chokidar using the current working directory **or** its (rollup's) parent directory.

Another (less desirable) solution is to add a resolve path/callback property in the watch options.

**Comment by liangchunn** [comment]
Hitting this issue while creating my own CLI tool as well, right now I'm just hacking it with
```ts
chokidar = require(require.resolve('chokidar'));
```

**Comment by shellscape** [comment]
We're going to be updating to chokidar@3 and using it as the default in a coming release. Please see #2988.
