### ISSUE TITLE
Proposal: Unified file emission API

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#2938]
### Feature Use Case
Currently, it is not possible to add arbitrary files to the bundle except by manually hacking the bundle in `generateBundle`.

### Feature Proposal
I propose to add a new unified API `this.emitFile(options)`, where options is an object that can take one of several shapes:

```
// to emit JavaScript chunks
{
  type: 'chunk',
  id: string,
  name?: string
}

// to emit assets; those will be hashed and follow the assetFileNames scheme
{
  type: 'asset',
  name: string,
  source?: string | Buffer
}

// to emit arbitrary files; no additional logic will be applied from Rollup with regard to naming
{
  type: 'file',
  fileName: string,
  source?: string | Buffer
}
```

All three will have in common that
- they return a unique reference id
- they will be reemitted if emitted from a transform hook that is skipped in watch mode (and possibly a load hook if at some point we skip those as well)
- they can be referenced via `import.meta.ROLLUP_FILE_URL_${fileReferenceId}`
- the file name can be accessed via `this.getFileName(fileReferenceId)` (only in `generateBundle` for assets and chunks).

Both assets and general files will support deferring setting the source to a later stage, e.g. from the build to the generate phase. I also propose to lift the restriction that a source can only be set once.

Name conflicts will be handled the following way:
- When emitting type `file` and there has already been a `file` emitted with the same name: throw an error
- When emitting type `file` in `generateBundle` and there is any chunk or asset file name conflicting with this file: throw an error (to avoid this, people should delete the conflicting file from the bundle object first)
- Type `chunk` and `asset` will never throw errors due to name conflicts but will be deconflicted if necessary

Assets with the same source will be deduped. In case the name differs, one of the names will be picked. This does not apply to type "file".

The existing chunk and asset emission APIs will be ultimately deprecated for this unified API (in next major versions).

Closes #2532 
Closes #2959

**Comment by tivac** [comment]
I love this plan!

The only piece of feedback on the API that I can think of is that it might be a little easier to spot if your separated the `type` field out from the other details.

```js
this.emitFile("chunk", { ... })
```

Either way I'm excited to have this unified and to stop manually adding files to the bundle object 😅

**Comment by manucorporat** [comment]
I like better the simplicity of a single argument as an object, i think it's an api that will age better

**Comment by lukastaegert** [comment]
I guess there are arguments for both. I thing a good way forward is to keep it with Maggie Pint (an excellent talk by the way https://youtu.be/RdKT70ktaeo?t=641): Separate parameters for everything that is required and a parameter object for everything else. Which would go towards @tivac's suggestion as I do not think the types will go away any time soon (I actually see a fourth type coming at some point: custom-chunk, but not sure when I will find time to start working on custom chunk finalizers). I will update the description.

I will update the description.

**Comment by manucorporat** [comment]
In our experience even if something is "required". It's required in the present, but it might not be in the future. Deprecate an API from an object is easier than if it's first argument of a function call.

Maybe in this case it's clear it will never be deprecated 👍

**Comment by wessberg** [comment]
This is a good way forward that will also make https://github.com/rollup/rollup/issues/2532 obsolete

**Comment by ryanatkn** [comment]
This proposal looks great, thank you! I've been working around this and it looks like an elegant solution.  

I don't feel strongly about the parameter design, but I want to add some thoughts. Apologies if this feels like bikeshedding - please just ignore it in that case. I find the choice interesting to think about and there seem to be some meaningful tradeoffs.

I watched the clip from Maggie Pint and her primary point seems to be agnostic to the question of taking _[type, options]_ or _{type, ...options}_ in the case discussed here. Her example showed how `moment` needed code in 10 different files to figure out what some parameters mean. In the proposals here, it's a matter of `switch (type)` or `switch (options.type)` - both are unambiguous, performant, and easy to reason about from the outside and inside.

Right now I see two main ergonomic differences:

1. types (which have more practical impact in 2)
2. working with data structures to be passed to `emitFile`

Here's a possible type signature of _{type, ...options}_.

```ts
function emitFile(options: EmitFileOptions): string;
type EmitFileOptions =
  | {
      type: 'chunk';
      id: string;
      name?: string;
    }
  | {
      type: 'asset';
      name: string;
      source?: string | Buffer;
    }
  | {
      type: 'file';
      fileName: string;
      source?: string | Buffer;
    };
```

The type signature of the _[type, options]_ is more awkward and requires overloads:

```ts
function emitFile(
  type: 'chunk',
  options: {id: string; name?: string},
): string;
function emitFile(
  type: 'asset',
  options: {name: string; source?: string | Buffer},
): string;
function emitFile(
  type: 'file',
  options: {fileName: string; source?: string | Buffer},
): string;
```

The type signature has a practical impact outside of the type system: working with the function's data structure. Say you have a function that returns some file descriptions to be passed to `emitFile` - it's simple with the _{type, ...options}_ form.

```ts
function getSomeFiles(): EmitFileOptions[] {
  return [{type: 'chunk', id: '1'}, {type: 'asset', name: '2'}];
}
getSomeFiles().forEach(file => this.emitFile(file));
```

Doing this with the _[type, options]_ form requires the user to create a new ad-hoc data structure to represent the two parameters. One possibilty could look like this:

```ts
function getSomeFiles() {
  return [['chunk', {id: '1'}], ['asset', {name: '2'}]];
}
getSomeFiles().forEach((file) => this.emitFile(...file)); // or
getSomeFiles().forEach(([type, options]) => this.emitFile(type, options));
```

Users may find themselves defining `EmitFileOptions` in their own code that bundles the type with the options:

```ts
function getSomeFiles(): EmitFileOptions {
  return [{type: 'chunk', id: '1'}, {type: 'asset', name: '2'}];
}
getSomeFiles().forEach(({type, ...options}) => this.emitFile(type, options));
```

I like the idea of rollup exposing a single interface that can be leveraged in userland, and the _[type, options]_ form requires an additional data structure to represent its two `emitFile` parameters.

Thank you for all of your work. Rollup is a pleasure to work with.

**Comment by lukastaegert** [comment]
> Apologies if this feels like bikeshedding

It does not at all. Creating a good API requires careful considerations as it is hard to change it later. I am happy that writing this up as a proposal first generates that level of responses to help us get this right.

Your points are definitely valid, also considering that we will need a single-object-form for #2946. I will change it back to the object form.

**Comment by jakearchibald** [comment]
I particularly like `file` here. When trying to get Rollup to handle HTML, I find myself using hacks to workaround the hashing (but I *do* want hashing for other types of assets). File seems like it would help here.
