### ISSUE TITLE
Preserve triple backslash comments or add new option for preserving comments based on regex

### ISSUE THREAD

**Issue by aleclarson** [rollup/rollup#2943]
### Feature Use Case
When bundling typescript declarations with [`rollup-plugin-dts`](https://github.com/Swatinem/rollup-plugin-dts), Rollup should avoid stripping comments that start with a triple backslash.

### Feature Proposal
Two options here:
- add option to Rollup for preserving comments that match a user-provided regex
- make Rollup preserve triple backslash comments by default

**Comment by aleclarson** [comment]
A related issue is that comments are not parsed by Rollup when a plugin returns an AST from its `load` method.

**Comment by lukastaegert** [comment]
Actually except for PURE comments, Rollup does not parse comments at all and removes comments based on their Position in the file relative to removed content. Preserving certain comments would be a non-trivial change, especially since by default, acorn does not help us at all in associating comments with Nodes so everything needs to be done by hand.

**Comment by lukastaegert** [comment]
Putting it another way, we do not remove comments but we remove whitespace between AST nodes that may contain comments.

**Comment by lukastaegert** [comment]
> A related issue is that comments are not parsed by Rollup when a plugin returns an AST

If you are referring to PURE comments, those are translated to an `annotatedPure` flag on `CallExpression` or `NewExpression` nodes that you need to add yourself if you provide an AST

**Comment by aleclarson** [comment]
Thanks for the clarification! I guess `rollup-plugin-dts` can just use the `intro` hook to prepend the comment pragmas, so I think we're done here.
