### ISSUE TITLE
Proposal: Access to dependencies graph from generateBundle

### ISSUE THREAD

**Issue by btd** [rollup/rollup#2947]
### Feature Use Case
I have a plugin `rollup-plugin-visualizer`, in current version it uses `generateBundle` hook, to build from OutputBundle modules dependencies (bundle.modules). This allows only to see biggest peaces of bundle.
I am trying to build new diagram to show why something was included, and i do not see any clear way to get dependencies of modules.

### Feature Proposal
If ChunkInfo isEntry is true, it should contain list of imports (or module ids). And need to be able to get imports of some module by module id.

**Comment by lukastaegert** [comment]
There is already a method on the plugin context [this.getModuleInfo](https://rollupjs.org/guide/en#this-getmoduleinfo-moduleid-string-moduleinfo) that gives you for each module the modules imported by that module as well as some additional information. As the chunks already contain information which modules are included in each chunk, all information should be available.

**Comment by lukastaegert** [comment]
BTW the visuals created by your plugin look lovely, nice work!

**Comment by btd** [comment]
Thank you. Am i understand right that starting point would be bundle.facadeModuleId?

**Comment by lukastaegert** [comment]
For entryChunks, the facadeModuleId always exists and corresponds to the entry point of this chunk, so yes.

**Comment by btd** [comment]
Thank you

**Comment by lukastaegert** [comment]
You're welcome, looking forward to see what you do with this! And feel free to open more issues if you think there is information missing that you could make good use of.
