### ISSUE TITLE
Print the line that caused an error

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#296]
When an error occurs it would be fantastic to print the line that caused the error. When reexporting a missing identifier we could point out the guilty import specifier.

```
1 |  export { foo } from './bar.js';
  |           ^
Error: ...
```

I just wonder how this should integrate with transforms. Ideally, we'd like to point out the error in the original source. I assume source-maps could be used for that.

I suggest that we add a `source` property to thrown Errors in addition to `loc` and let `bin/handleError.js` print the source line. Thoughts?

_See https://github.com/rollup/rollup/issues/143#issuecomment-143150006_

**Comment by Rich-Harris** [comment]
+1. Though ideally we'd trace back to the original source, in cases where there are intermediate sourcemaps...

**Comment by eventualbuddha** [comment]
Babel may somehow report the original lines… sometimes. I'm honestly not entirely clear on how that works or whether I'm imagining it. Might be worth tracking down.

**Comment by flying-sheep** [comment]
right now i’m having the problem that it reports a line that doesn’t exist. it would be awesome if “invalid token” could at least print the token or even the line where something went wrong.

**Comment by flying-sheep** [comment]
i hacked it by inserting this into node_modules/rollup.js, right before an unhelpful `this.unexpected()` call in `pp$2.parseBindingAtom`:

```js
throw new Error('type: ' + JSON.stringify(this.type) + '\ncode: ' + this.input.substring(this.lastTokStart-20, this.end+20) + '\n')
```

as a result i could find the culprit, but it would be awesome if this project did that for me, *and* reported the true line numbers instead of wrong ones.

**Comment by yairEO** [comment]
Any news regarding such an important feature?

**Comment by Rich-Harris** [comment]
This is now implemented (though Rollup doesn't yet trace errors back through a sourcemap chain)
