### ISSUE TITLE
Disable tree shaking for specific symbol

### ISSUE THREAD

**Issue by slavafomin** [rollup/rollup#2963]
Hello!

Thank you for your hard work.

However, I have a dynamic function, which executes code loaded asynchronously by means of `eval()`. And the evaluated code depends on some function arguments to be present. However, when processed by Rollup, such arguments are removed from the target build, because they are not used anywhere directly.

Here's the example:

```typescript
/**
 * Executes the specified code in the isolated closure
 * with substituted CommonJS globals
 * and returns symbols exported by the module.
 */
function initializeModule(source: string, require: RequireFunction, exports: any = {}, module: any = {}) {

  eval(source);

  // "exports" or "module.exports" will be populated
  // with the exported symbols when the "eval" finishes
  return Object.assign({}, exports, module.exports);

}
```

As you can see, the evaluated code of the CommonJS module depends on the `require` argument, but it's being stripped from the final bundle, because it's not used in the `initializeModule()` function directly.

How do I make sure that it's not tree shaken away? Is there a compiler directive (special comment) for this maybe?

Thanks!

**Comment by lukastaegert** [comment]
Will need to look into this further, for now, the `treeshake: false` option should fix it.

**Comment by slavafomin** [comment]
> Will need to look into this further

Thanks )

> for now, the treeshake: false option should fix it

Obviously, I wouldn't want to disable entire tree-shaking because of a single false-positive.

The trick is just to use the argument in the function somehow to make the bundler see it. I'm doing this for now: `require('no-op'); eval(...);`.

**Comment by lukastaegert** [comment]
Ok, if we want to do this right, the use of eval will need to include all visible variables...

**Comment by lukastaegert** [comment]
One thing you could do is to use `new Function(...)` instead of `eval(...)`.

**Comment by lukastaegert** [comment]
Here is how Rollup does something similar in its tests:

```js
const runModule = new Function('module', 'exports', 'require', source);
const module = { exports: {} };
runModule(module, module.exports, require);
```

**Comment by lukastaegert** [comment]
The advantage of using `new Function` is that it does not create a closure to the surrounding variables and therefore Rollup does not need to exclude anything needlessly. Actually I am not sure if/when I will fix this ticket as I am a little short an time and considering I believe there is a good alternative for your issue.

**Comment by lukastaegert** [comment]
Marking it as a `wontfix` as I think this problem was already pondered in the past and `eval` just does not go well with scope-hoisting and tree-shaking while `new Function` solves similar issues without the drawbacks. There even is a separate entry dealing with this on the website: https://rollupjs.org/guide/en/#avoiding-eval

**Comment by shellscape** [comment]
Closing since we've hit the 60 day mark and it's tagged `wontfix`

**Comment by lukastaegert** [comment]
Running eval is REALLY dangerous in a bundling context as Rollup may rename variables if necessary at any time, resulting in your evaled variables resolving to OTHER variables instead–without warning. It is not possible to turn off this behaviour because it is fundamental to how Rollup works.
So even if we turn off tree-shaking if `eval` is used, difficult bugs can ensue.

Still, you can write a plugin that does just that, it would be something like this

```js
function noTreeShakingForEvalPlugin() {
  return {
    name: 'no-treeshaking-for-eval',
    transform(code) {
        // This is very fast but can produce lots of false positives.
        // Use a good regular expression or parse an AST and analyze scoping to improve as needed.
        if (code.indexOf('eval') >= 0) return {moduleSIdeEffects: 'no-treeshake'};
    }
  }
}
```

That would turn off tree-shaking just for modules using `eval`.

**Comment by lukastaegert** [comment]
See also https://rollupjs.org/guide/en/#transform

**Comment by lukastaegert** [comment]
See also https://rollupjs.org/guide/en/#transform

**Comment by HeWenKe** [comment]
look under code
const a = 'a';
const b = 'b';
const c = 'c';
let ary = [];
for (let val of ['a','b','c']){
ary.push(eval(val))
}
console.log(ary)
//打包以上代码，会把变量a，b,c 全部remove 掉，导致我for 循环的时候，找不到
