### ISSUE TITLE
Allow emitChunk to be called any time when in watch mode

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#2964]
### Feature Use Case

I have a build that runs kinda like this:

1. Get all HTML files in a particular directory.
1. Add html files as assets via `emitAsset`.
1. Parse HTML to find JS and assets.
1. Assets are added via `emitAsset`.
1. JS is added via `emitChunk`.
1. Update references in HTML with hashed asset & chunk names.
1. Output files (and remove hashing from HTML file names).

This works great, but I'm having difficulty getting watch mode working.

If a new HTML file appears in the directory, I process it (steps 2-5 above). However, I get an error "Cannot call emitChunk after module loading has finished."

### Feature Proposal

Some way to add chunks while watching.

**Comment by lukastaegert** [comment]
At first glance, retriggering the watcher feels like it drags a lot of additional complexity as this again will trigger emitting all existing chunks etc. To me it sounds it would also be ok to have a way of signalling rollup that you are not done emitting what needs to be emitted and basically stall the module loading phase?

**Comment by lukastaegert** [comment]
A simple way to achieve this would be to only resolve e.g. the transform promise of one of the emitted chunks until all chunks have been emitted. The module loading phase will not complete if some `load` or `transform` promise is still pending.

**Comment by jakearchibald** [comment]
> To me it sounds it would also be ok to have a way of signalling rollup that you are not done emitting what needs to be emitted

That doesn't quite work in this case. The idea here is the developer would turn on watch mode, and begin developing. During development, they *may* add additional HTML files, which I would like to bring into the build.

In this case, there isn't really a 'done emitting' state.

How does this work currently? Let's say I have a file like:

```js
console.log('hello');
```

I start Rollup in watch mode, then sometime later, I change the file:

```js
console.log('hello');

const modulePromise = import('./2.js');
```

Isn't this going to emit a new chunk sometime after module loading has finished? I guess I'm looking for a way to do that.

**Comment by lukastaegert** [comment]
> Isn't this going to emit a new chunk sometime after module loading has finished? I guess I'm looking for a way to do that.

As you are changing a file that is being watched, changing the file will trigger a complete rebuild. During the rebuild, the new import statement will trigger a new chunk being emitted while the module loading is running. I think what you actually want is probably using `this.addWatchFile` during the generate phase?

**Comment by lukastaegert** [comment]
It is technically impossible to emit new chunks or add files after the build phase is complete as all the chunking and tree-shaking depends on the all modules being present. As soon as something is added, we need to start from scratch.

**Comment by lukastaegert** [comment]
So basically, you just want to trigger a new build manually?

**Comment by jakearchibald** [comment]
> I think what you actually want is probably using `this.addWatchFile` during the generate phase?

What would I pass to `addWatchFile`, and when? The additional HTML files won't be there yet, and may never appear.

> So basically, you just want to trigger a new build manually?

Yeah, I think this is what it comes down to. I've detected a change, and would like to trigger a rebuild (but would like Rollup to be as smart about the rebuild as it can be, eg use caches).

**Comment by lukastaegert** [comment]
In watch mode, Rollup is already trying to be a little smart in watch mode by caching module resolution, transformation and parsing. There is a proposal for an extended plugin based caching solution but it will take some time #2946 . Also there are ideas to enable external watchers instead of Rollup’s own but they are still being developed. Where do the new HTML files come from, are they created by the user? You should be able to e.g. pass a folder to addWatchFile in the buildStart hook to watch for new files but I cannot check right now

**Comment by lukastaegert** [comment]
Yes, addWatchFile definitely accepts directories, we even wrote that on the website

**Comment by jakearchibald** [comment]
> Where do the new HTML files come from, are they created by the user?

Yeah, they're (pretty much) hand authored in this case.

> You should be able to e.g. pass a folder to addWatchFile in the buildStart hook to watch for new files but I cannot check right now

Huh, TIL. Although the HTML files aren't in a single directory. I'm monitoring `src/**/*.html`.

Maybe I can hack around it:

1. Create dummy file.
1. Tell Rollup to watch this file via `addWatchFile`.
1. When I see a new HTML file appear, make some change to the dummy file.

Thanks for all the help here btw!

**Comment by lukastaegert** [comment]
So if I understand you correctly you are running your own file watcher besides Rollup's watcher that monitors `src/**/*.html`?

**Comment by jakearchibald** [comment]
Yeah.

**Comment by jakearchibald** [comment]
A way to trigger a rebuild sounds like the answer here. Should I close this and create a separate issue for that?

**Comment by lukastaegert** [comment]
I think this might be helpful. In the end, the goal should be to specify a generic API to plugin in external watchers to replace/augment the existing watcher. Any input here is definitely welcome.

**Comment by jakearchibald** [comment]
Huh, I just tried adding a file, and Rollup saw it and restarted the build. It's one of those cases where it's doing exactly what I want but I don't know why. I'll dig into Rollup's watcher over the next few days and see if I can figure out how/why it's working.

**Comment by jakearchibald** [comment]
Closing this. It feels like it's taken care of via the planned watch integration.

**Comment by zhangHongEn** [comment]
> A simple way to achieve this would be to only resolve e.g. the transform promise of one of the emitted chunks until all chunks have been emitted. The module loading phase will not complete if some `load` or `transform` promise is still pending.

I have a special module that uses promises to wait, but how do I know when to stop waiting (after all modules except the current one are resolved)
