### ISSUE TITLE
rollup.watch ends immediately

### ISSUE THREAD

**Issue by sdegutis** [rollup/rollup#2966]
- Rollup Version: 1.16.2
- Operating System (or Browser): macOS 10.14.5 (18F132)
- Node Version: v11.14.0

### How Do We Reproduce?

Using the following semi-config:

```js
rollup.watch({
  // ...
  watch: {
    exclude: 'public/web_modules/**',
    include: 'public/**',
  },
});

const watcher = rollup.watch(config);

watcher.on('event', event => console.log(event.code));
```

Then run it via:

```bash
$ node index.js
```

### Expected Behavior

It outputs:

```
START
BUNDLE_START
BUNDLE_END
```

... and it should keep running, watching my directory for changes.

### Actual Behavior

It outputs:

```
START
BUNDLE_START
BUNDLE_END
END
```

and the process ends.

**Comment by sdegutis** [comment]
Here's the complete reproduction steps:

Run this in a fresh directory:

```bash
$ npm init -y
$ npm i -P rollup
$ npm i -P react@npm:@reactesm/react
$ npm i -D rollup-plugin-node-resolve
```

Put this in `index.js`

```js
const rollup = require('rollup');
const resolve = require('rollup-plugin-node-resolve');

const watcher = rollup.watch({
  input: [
    'react',
  ],
  output: {
    dir: 'public/web_modules',
    format: 'esm',
    sourcemap: false,
    exports: 'named',
    chunkFileNames: 'common/[name]-[hash].js',
  },
  watch: {
    exclude: 'public/web_modules/**',
    include: 'public/**',
  },
  plugins: [
    resolve(),
  ],
});

watcher.on('event', event => console.log(event.code));
```

Run this:

```bash
$ node index.js
```

**Comment by sdegutis** [comment]
I also tried adding `chokidar: false` to the `watch` options based on seeing it briefly in another issue, but it did not help.

**Comment by shellscape** [comment]
We're going to be updating to use chokidar@3 by default, and that should solve this issue. Please see #2988.
