### ISSUE TITLE
Wrong typing of SourceMap.version

### ISSUE THREAD

**Issue by theseanl** [rollup/rollup#2967]
- Rollup Version: 1.16.2
- Operating System (or Browser): 
- Node Version: v12.4.0

### How Do We Reproduce?
Try using `map` property of `OutputBundle` object in `generateBundle` hook 
as a return value `{ code, map }` of a `load` hook

### Expected Behavior
Does not produce any type error.

### Actual Behavior
```
[tsserver 2322] [E] Type '{ file: string; mappings: string; names: string[];   
sources: string[]; sourcesContent: string[]; version: string; toString():       
string; toUrl(): string; }' is not assignable to type 'string |                
ExistingRawSourceMap | { mappings: ""; }'.                                     
Type '{ file: string; mappings: string; names: string[]; sources: string[];  
sourcesContent: string[]; version: string; toString(): string; toUrl(): string 
; }' is not assignable to type 'ExistingRawSourceMap'.                         
Types of property 'version' are incompatible.    
```

There is a wrong type definition of `SourceMap.version` in https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts#L59
`magic-string` sets the version property as `3`, but the type declaration declares its type as `string`.

This is a propagation of a wrong type declaration of `magic-string` package, which is fixed in master branch in this Feb but not yet published to NPM: https://github.com/Rich-Harris/magic-string/commit/b6fd47dfe0f2839b90ae036ca10ee2b89436dc28

This prevents e.g. feeding `OutputChunk` output from `generateBundle` as a return value of another rollup plugin's `load` hook.

In order to resolve this issue, `magic-string` package must be updated in NPM with the current master branch, its version in rollup must be increased, and the type in `src/rollup/type.d.ts` must be updated.

**Comment by lukastaegert** [comment]
Fix at #2976
