### ISSUE TITLE
Error when including "joi" in project

### ISSUE THREAD

**Issue by lal12** [rollup/rollup#2969]
- Rollup Version: 1.16.2
- Operating System: Ubuntu
- Node Version: 10.9.0

### How Do We Reproduce?
- extract zip: [test.zip](https://github.com/rollup/rollup/files/3338605/test.zip)
- `npm install rollup-plugin-node-resolve rollup-plugin-commonjs rollup-plugin-json joi`
- run `node_modules/.bin/rollup -c rollup.config.js `
- run `node out/test.js`

### Expected Behavior
Script should print "hey" and exit.

### Actual Behavior
> /tmp/test/out/index.js:2044
> var options = lib$3.object({
>                    ^
>
> TypeError: Cannot read property 'object' of undefined
>     at Object.<anonymous> (/home/ll/tmp/test/out/index.js:2044:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>     at startup (internal/bootstrap/node.js:266:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

I am unsure if this is a plugin related bug or a general rollup problem, so I posted it here. The variable `lib$3` is used before it actually is defined/declare (ln 9142).

**Comment by shellscape** [comment]
Thanks for opening an issue. Please create a reproduction _without_ using plugins. If you're unable to, then that will let you know that it's not Rollup core, but rather one of the plugins in use. From there, you can incrementally add plugins to identify which is causing the issue, and which you can report the issue to.

**Comment by matthewp** [comment]
This happens because joi has circular references.

**Comment by matthewp** [comment]
joi requires several plugins to get building. I'm going to try and reduce it down to just be about the circular ref issue.

**Comment by matthewp** [comment]
Opened a bug in the plugins repo: https://github.com/rollup/plugins/issues/130

**Comment by lal12** [comment]
> joi requires several plugins to get building. I'm going to try and reduce it down to just be about the circular ref issue.

Yeah actually didn't notice the comment of @shellscape, however probably wouldn't been possible to build this example without plugins.
