### ISSUE TITLE
Access to a copy of the logo.

### ISSUE THREAD

**Issue by CrowdHailer** [rollup/rollup#297]
I really like rollup and am currently writing a blog post about my setup. I would really like to include the rollup logo somewhere. I looked on the main page but couldn't work out how to extract the logo. is there a png or even svg file with it hosted somewhere?

**Comment by Rich-Harris** [comment]
The logo is included as a Data URI on rollupjs.org – you'll have to copy and paste the below into your browser, as GitHub doesn't recognise it as a URL... It's white stroke on a transparent background so won't look like much until you put it on a coloured background (the site uses #e94c43, if you wanted to match it). Hope this helps, look forward to the blog post!

data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxNi4wLjEsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB3aWR0aD0iNDAwcHgiIGhlaWdodD0iNDAwcHgiIHZpZXdCb3g9IjAgMCA0MDAgNDAwIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCA0MDAgNDAwIiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxwYXRoIGZpbGw9IiMwMTAxMDEiIHN0cm9rZT0iI0ZGRkZGRiIgc3Ryb2tlLXdpZHRoPSI5IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgZD0iDQoJTTEyOS40OTgsMjI5LjU4MmMtMC4xMSwwLjU0My0wLjQyNCwxLjYxOS0wLjUzNiwyLjcxNWMtMC43NzEsNy41ODItMS4yMDcsMTUuMjA5LTIuMzE0LDIyLjc0DQoJYy0xLjUxMiwxMC4yODUtMy4yMjcsMjAuNTYyLTUuMzk5LDMwLjcyN2MtMi41NTgsMTEuOTY5LTUuNTkyLDIzLjgzOC04LjYyNSwzNS42OTdjLTEuODU5LDcuMjczLTQuMDczLDE0LjQ1Ny02LjE4NSwyMS42NjQNCgljLTEuMjMxLDQuMTk5LTIuNTAzLDguMzkxLTMuOTMzLDEyLjUyNWMtMC4yNzEsMC43ODMtMS4zNywxLjI3NS0yLjA4NywxLjkwNmMtMC4wOTktMC44NTUtMC40NzYtMS43OTEtMC4yNTUtMi41NTUNCgljMi4yOTEtNy45MzgsNC43MS0xNS44MzYsNy4wMy0yMy43NjhjMi4zOTMtOC4xOCw0Ljc1LTE2LjM3MSw3LjA1OC0yNC41NzZjMS40OTYtNS4zMTIsMy4wNjQtMTAuNjIxLDQuMjU1LTE2LjAxDQoJYzEuMTY5LTUuMjgzLDEuODY1LTEwLjY3NiwyLjg1OC0xNi4wMDJjMC4yMi0xLjE4MiwxLjAxLTIuMjYyLDEuMjAxLTMuNDM5YzAuNDQtMi43MjUsMC42MzYtNS40ODIsMS4wMDYtOC4yMjENCgljMC4xNzUtMS4yODUsMC41NDMtMi41NDcsMC43ODctMy44MjRjMC4xNS0wLjc4NywwLjI1Mi0xLjU4OCwwLjMzNS0yLjM4N2MwLjE1MS0xLjQ0NSwwLjI0OS0yLjg5OCwwLjQwOS00LjM0Ng0KCWMwLjQ5LTQuNDMyLDAuOTg0LTguODYxLDEuNTA3LTEzLjI4OWMwLjIwMi0xLjcwNSwwLjY3NS0zLjQsMC42NjctNS4xMDJjLTAuMDA2LTEuMjc3LTAuNjE0LTIuNTQ3LTAuODkyLTMuODMyDQoJYy0wLjE2LTAuNzQyLTAuNDIzLTIuMTExLTAuMjUzLTIuMTc2YzIuNjE4LTAuOTk0LDEuOTM1LTMuMzE0LDEuOTMtNS4wOThjLTAuMDI2LTkuMTU4LTAuMDUxLTE4LjMyNC0wLjQ2OC0yNy40NzMNCgljLTAuMjA5LTQuNTk2LTEuMzU0LTkuMTQxLTEuODg5LTEzLjczMWMtMC42ODYtNS44ODYtMS4xMTEtMTEuODAzLTEuNzg2LTE3LjY5Yy0wLjYzLTUuNDk0LTEuNzA0LTEwLjk0Ny0yLjExOS0xNi40NTQNCgljLTAuOTEyLTEyLjEwNC01LjM1Mi0yMy4xMS0xMC4xMDktMzQuMDMzYy0yLjcwMy02LjIwOC01LjU0NC0xMi4zNTctOC40MDgtMTguNDk0Yy0wLjUwNi0xLjA4NC0xLjQwMy0xLjk5NC0yLjE2NC0yLjk1DQoJYy0yLjE3Ny0yLjczNS00LjM3Ny01LjQ1NC02LjgxMy04LjQ4NGM0LjEyNS0wLjMzNyw2LjU0NywwLjc0LDcuODQsNC4zMDJjMC43MDMsMS45MzUsMi41LDMuNDQzLDMuNDc0LDUuMzE1DQoJYzEuODA3LDMuNDcxLDMuNDQyLDcuMDM4LDUuMDIxLDEwLjYyMWMxLjc0OCwzLjk2NSwzLjUwOSw3LjkzNyw0Ljk5MSwxMi4wMDVjNC44NDksMTMuMzA1LDguMTk5LDI2LjkwOSw5LjM0MSw0MS4xMjINCgljMS4xMzgsMTQuMTY5LDMuNDYzLDI4LjI0Myw0LjU5Nyw0Mi40MTFjMC42NjUsOC4zMDYsMC4wMTgsMTYuNzE2LTAuMDM4LDI1LjA4MmMtMC4wMDMsMC40OTIsMCwwLjk4NCwwLDEuOTE4DQoJYzEuOTU4LTEuMTcsMy42OTctMi4xNzYsNS40MDMtMy4yMzRjNi41MjMtNC4wNDUsMTMuMDgxLTguMDM3LDE5LjUzMS0xMi4xOTVjMy4xMjItMi4wMTQsNi4wMzEtNC4zNTQsOS4wNC02LjU0NQ0KCWMzLjQ1NS0yLjUxNCw2Ljk2NC00Ljk1OCwxMC4zNTEtNy41NjFjMS44NzktMS40NDQsMy41MS0zLjIwNyw1LjMzNC00LjcyOWM4LjM1OC02Ljk3MywxNi42MDktMTQuMDUxLDIzLjc0OS0yMi4zMjMNCgljNS4zOTYtNi4yNSwxMS40MzktMTIuMDMyLDE2LjE3OC0xOC43NDJjNy40ODItMTAuNjAyLDE1LjAzOS0yMS4zNDQsMTguNDc3LTM0LjE0OWMxLjA4LTQuMDM0LDEuMjI5LTguMzIyLDEuNzUtMTIuNTAxDQoJYzAuMzEzLTIuNTM0LDAuNzgxLTUuMDg4LDAuNzI1LTcuNjIzYy0wLjE1LTYuNDA0LDAuMjMtMTIuOTY2LTEuMDYxLTE5LjE2MWMtMS43MzItOC4zMjYtNS43MDktMTUuNjg4LTEyLjkxOC0yMS4wNzUNCgljLTUuNTI5LTQuMTM1LTExLjUyNS03LjA5LTE4LjA2Mi04LjkwNmMtMy4wNTMtMC44NDgtNi4zNjMtMC44ODgtOS41NjgtMS4wMjdjLTQuMzU0LTAuMTg4LTguNzY2LTAuNTUtMTMuMDY3LTAuMDcNCgljLTcuNywwLjg1Ny0xNS40MTIsMS45MzItMjIuOTgxLDMuNTZjLTExLjM0OSwyLjQ0LTIxLjY0NCw3LjkxNi0zMi4zMzksMTIuMjExYy0zLjY4NSwxLjQ4LTcuMDA3LDMuODQ0LTEwLjU0Myw1LjcxMQ0KCWMtMy45OSwyLjEwNi04LjEwOSwzLjk3Ny0xMi4wMzQsNi4xOTVjLTMuMjA4LDEuODEyLTYuMTk1LDQuMDExLTkuMzE0LDUuOTg2Yy0xLjc5OCwxLjEzOC0zLjc4OSwyLjAwMy01LjQ3MiwzLjI4Mg0KCWMtNC4yMTQsMy4yMDItOC4yNzksNi42LTEyLjQ2Myw5Ljg0M2MtMC43NDksMC41ODEtMS45MywwLjYxNS0yLjY1NSwxLjIxM2MtMi41NjMsMi4xMTUtNC45NTgsNC40MzUtNy41MzYsNi41MzINCgljLTEuMTU1LDAuOTM5LTIuNTU2LDEuNjEyLTMuOTI5LDIuMjE2Yy0wLjI3NCwwLjEyMS0xLjM4MS0wLjgyMi0xLjMzNC0wLjkyN2MwLjYxNS0xLjM2MSwxLjA0MS0zLjEzMiwyLjE0Mi0zLjg5OQ0KCWM3LjcwNC01LjM2NiwxNS41MzQtMTAuNTUxLDIzLjM2My0xNS43MzRjNi45NTEtNC42MDMsMTMuNTQxLTkuNzI5LDIxLjIzNi0xMy4yMThjNi44OTctMy4xMjYsMTMuNDEtNy4wOTMsMjAuMjY2LTEwLjMyMQ0KCWM0Ljg5Ni0yLjMwNSwxMC4wOTUtMy45NjQsMTUuMTI3LTUuOTg5YzIuNDg3LTEsNC44NTItMi4zMTUsNy4zNjEtMy4yNDVjOS41MTgtMy41MjQsMTkuNTMzLTQuODE1LDI5LjUwMi02LjE3OQ0KCWMyLjg5MS0wLjM5Niw1LjkwOCwwLjE2NCw4Ljg2OSwwLjIyNmM0LjU0NiwwLjA5NSw5LjE0My0wLjI1MiwxMy42MjQsMC4zMjljMy41NDYsMC40Niw3LjAzOCwxLjgwMywxMC4zOTQsMy4xNjINCgljNS44MDksMi4zNTUsMTAuOTE0LDUuOTc4LDE1LjIyNywxMC40NTVjNS43NjYsNS45OSw5LjM2NywxMy4yNzcsOS45MzksMjEuNjM2YzAuNDg2LDcuMDc3LDAuNjE1LDE0LjIxNiwwLjI4MSwyMS4yOTgNCgljLTAuMjYsNS40MTItMC43MzYsMTEuMDMzLTIuNDU1LDE2LjEwOGMtMi43MDUsNy45NzctNS4zOTYsMTYuMDkyLTEwLjczNCwyMi45MzVjLTEuODQ4LDIuMzY0LTIuODgzLDUuMzgxLTQuODExLDcuNjU3DQoJYy04LjU0NSwxMC4wODktMTcuMDM1LDIwLjI0NC0yNi4wMTQsMjkuOTQzYy0xMC4yNSwxMS4wNzItMjEuOTA3LDIwLjY0NS0zNC4xODUsMjkuMzk3Yy03LjA0NSw1LjAyMS0xNC40MTYsOS41ODYtMjEuNjMxLDE0LjM2OQ0KCWMtMC40NDEsMC4yOTMtMC44MDcsMC42OTgtMS4zOTQsMS4yMTVjMy4yMTQtMC4zODMsNi4xNjEtMC41MSw5LjAwMS0xLjEyM2M1LjQzLTEuMTc2LDEwLjcwOCwwLjEyNSwxNi4wNDIsMC41NzgNCgljMC45OSwwLjA4NCwxLjk3OSwwLjIzNSwyLjk2OSwwLjIzM2MxMS42NjQtMC4wMTQsMjIuMDQsMy40MjIsMzEuNzA0LDEwLjE3YzYuNzYxLDQuNzIyLDEzLjEzNSw5Ljc4MSwxOC42OTQsMTUuNzU3DQoJYzMuMTQ2LDMuMzgzLDUuODA5LDcuNDI0LDcuODQ2LDExLjU4MmMyLjc3OSw1LjY3NCw2LjI3MSwxMS4wMSw3LjkxLDE3LjI4MmMxLjc3MSw2Ljc3NywzLjkyNiwxMy40ODgsNi40NDEsMjAuMDI0DQoJYzEuNTcyLDQuMDg0LDMuOTg1LDcuODc4LDYuMjg1LDExLjY0MmMxLjk3MSwzLjIyNiw0LjEyMSw2LjM4Myw2LjUzMSw5LjI4N2M1LjIzOCw2LjMwMywxMi4xNTYsMTAuMTgsMTkuNjkxLDEzLjE1Mw0KCWM0LjA2NCwxLjYwNCw4LjE4OCwxLjU2MiwxMi40MTIsMS4zODZjMi4zODctMC4xMDMsNC43OTUsMC4xNTMsNy4xODYsMC4zNTFjMTIuNTA4LDEuMDI0LDIxLjUwMi00LjgzLDI4LjY3NC0xNC40MzcNCgljMy42OC00LjkyOSw2LjMxNi0xMC4yNTUsOC40NzEtMTYuMDdjMi4yMDctNS45NjksMy4wNjItMTEuOTIyLDMuMjk5LTE4LjEyN2MwLjEwNS0yLjc3NCwwLjY3NC01LjU0MywwLjYzMy04LjMxDQoJYy0wLjA1MS0zLjQ5MS0wLjQ4LTYuOTc5LTAuODA1LTEwLjQ2N2MtMC4xOTUtMi4xMS0wLjM0Mi00LjI0NC0wLjc3My02LjMxMmMtMS44MTQtOC42MzgtNS4wMzEtMTYuNTc4LTExLjYwOS0yMi44MTcNCgljLTAuODE4LTAuNzc3LTEuMzU3LTEuODU0LTIuMDE0LTIuOGMtMi42ODgtMy44NjgtNi02LjkzOC0xMC40NDktOC43NWMtMS42NjYtMC42NzgtMy4xNDgtMS44MTMtNC42OTMtMi43NzYNCgljLTYuNjM5LTQuMTQyLTEzLjkxLTYuNDM4LTIxLjQ1NS0zLjk5MmMtNy4xMjUsMi4zMTItMTMuODY1LDUuODY5LTE2LjIyNywxNC4wNzhjLTEuNDUzLDUuMDU2LTMuNTIzLDEwLjAwNC00LjMzLDE1LjE1Mw0KCWMtMC44MTEsNS4xODUtMS4yNjQsMTAuNzI0LTAuMzA3LDE1LjgxMmMxLjI4Myw2LjgxMiwyLjY1NiwxMy44NSw2LjQyMiwxOS45MTFjMi4zMDEsMy43MDUsNS4xMTEsNi45OSw5LjkwNiw3LjcxOA0KCWMzLjA2MiwwLjQ2Myw2LjE0NiwxLjk0Miw5LjEwNSwxLjY3MmMzLjkyOC0wLjM1Niw4LjE4NC0xLjI1MiwxMS40OC0zLjI2MWMzLjMxOC0yLjAxOCw1LjgyOC01LjUyNCw4LjM1Mi04LjY1NQ0KCWM0LjgyMi01Ljk4MywzLjgwOS0xNy4xNy0xLjI4Ny0yMi41MjFjLTIuNDc5LTIuNjAxLTQuMDY2LTYuMTcyLTcuNzU4LTcuMzg2Yy0yLjQ3NS0wLjgxMi01LjA3LTEuNDQ0LTcuNjU0LTEuNjU5DQoJYy0yLjI5MS0wLjE5LTUuMjQ4LDIuOTc4LTUuODc3LDUuNjY0Yy0wLjE0OCwwLjYzOS0wLjI5MSwxLjI4LTAuNDc5LDEuOTExYy0wLjc1NiwyLjU4OS0wLjA0LDMuOTM5LDIuNjA5LDQuNTU0DQoJYzIuNTQxLDAuNTg2LDUuMTE3LDEuMDIyLDguMjE5LDEuNjMzYy0wLjgyLDAuNjQ0LTEuMzE4LDEuMzMtMS45MzgsMS40N2MtMy41OCwwLjgxLTcuMDM1LDAuMTUzLTkuODYzLTIuMDY1DQoJYy0xLjA0Ny0wLjgyLTEuODgxLTIuOTg4LTEuNTc0LTQuMjRjMC43MjktMi45ODMsMS45MzQtNS45MzIsMy40MzItOC42MjdjMS40NDMtMi42MDEsNS40MTItMy43NzgsOC4zMTEtMi45MjQNCgljMi4yMTcsMC42NTMsNC41MiwxLjIxNyw2LjU0MywyLjI3NmMxLjgzNiwwLjk2MSwzLjc1MiwyLjI1NCw0LjkyNCwzLjkwNGMyLjQ2OSwzLjQ3Myw0Ljg1NSw3LjEwNCw2LjU3OCwxMC45NzkNCgljMi44NDQsNi4zOTYsMS4xOTUsMTIuNDIxLTIuMTcyLDE4LjM1NGMtMi4zNTgsNC4xNTYtNi4xMjEsNi43OTctOS4zMTUsMTAuMDMzYy0xLjAzNiwxLjA1NS0zLjAyMSwxLjE2LTQuNTYsMS43MzQNCgljLTUuODkzLDIuMTk3LTExLjQ4MywyLjAwNC0xNy41NjEtMC4yN2MtOS40NjMtMy41MzktMTMuMjkxLTEwLjcwMS0xNS4wODYtMTkuNzQ4Yy0wLjEyOS0wLjY0OC0wLjI0Mi0xLjMyNi0wLjUyNS0xLjkxMg0KCWMtMy41OTItNy4zODctMi4xNTQtMTUuMjE5LTIuMDU5LTIyLjkzYzAuMDktNy40MTQsMi45OS0xNC4xMDQsNS42MDItMjAuODNjMC42MjEtMS42MDQsMi4wOC0yLjk3MSwzLjM4MS00LjIwNQ0KCWM1LjI2Mi00Ljk5NiwxMS4xNjQtOC44NzksMTguNzAzLTkuMDhjMi42MDQtMC4wNyw1LjI4MSwwLjQxLDcuODM0LDEuMDJjMy4wODQsMC43MzgsNi4xOTEsMS4zNTcsOC45MDIsMy40MTQNCgljMi41MjEsMS45MSw1LjY4NCwyLjk3MSw4LjI0Miw0Ljg0MmMyLjM1NywxLjcyNyw0LjM5MywzLjkzOSw2LjM4Nyw2LjEwNWMyLjkxMiwzLjE1Niw2LjA3OCw2LjE5Nyw4LjM2Nyw5Ljc3OQ0KCWMyLjM2OSwzLjcxMSwzLjkzOCw3Ljk1Nyw1LjY0NiwxMi4wNTljMi45NjEsNy4xMjMsMi4xNjYsMTQuODEyLDIuODU5LDIyLjI0YzAuODg1LDkuNDU5LTAuMzcxLDE4Ljc5OS0zLjExNSwyNy45OTQNCgljLTIuMjg1LDcuNjYyLTYuMDU5LDE0LjM4Ny0xMC45ODksMjAuNTI3Yy04LjEyLDEwLjEwOS0xOC43MjIsMTQuMTM5LTMxLjU0MSwxMi41MzljLTEuMzA2LTAuMTYyLTIuNjc2LTAuMzQyLTMuOTQ4LTAuMTIxDQoJYy01Ljk1MSwxLjAyLTExLjMzLTAuNzc5LTE2LjUwOS0zLjMxMmMtNi4zODEtMy4xMTktMTIuODAzLTYuMjk5LTE3LjI4LTEyLjA5NmMtMi4yNTItMi45MTYtMy44NjMtNi4zNTQtNi4yNjktOS4xMTUNCgljLTUuODM0LTYuNzAzLTcuNzcxLTE1LjIxMS0xMS4wNjUtMjMuMDY0Yy0xLjY0Mi0zLjkxLTIuMTgzLTguMjctMy41ODktMTIuMjk3Yy0wLjk1OS0yLjc0OC0yLjUzOC01LjI4My0zLjg2Ni03LjkNCgljLTEuOTgzLTMuOTA0LTMuNjY2LTguMDE2LTYuMDgtMTEuNjM3Yy0yLjI0Mi0zLjM2NS01LjA3OC02LjQwOC04LjAwOC05LjIyM2MtMy40MTItMy4yNzctNy4xMDQtNi4yOTEtMTAuODYzLTkuMTc0DQoJYy02LjQ4NC00Ljk3MS0xMy43MDMtOC42Ny0yMS41OTEtMTAuNzY0Yy0zLjkzNC0xLjA0NS04LjA5Ni0xLjI3MS0xMi4xNjktMS43MzRjLTMuOTMzLTAuNDQ5LTcuODc5LTAuODMtMTEuODMtMS4wNjQNCgljLTguNjE0LTAuNTEyLTE2Ljc2LDEuMTg4LTI0LjM3MSw1LjM2M0MxMzIuMjAxLDIyOS4zNzksMTMxLjA3OSwyMjkuMzA3LDEyOS40OTgsMjI5LjU4MnoiLz4NCjwvc3ZnPg0K

**Comment by CrowdHailer** [comment]
Ok i will try and work that out. I was hoping for a stand alone image as I know how to add that as meta info so it will show up when the link is shared on fbook/twitter etc. I try and add one image per post. Anyways there must be a way to make this work I will investigate

**Comment by Rich-Harris** [comment]
If you open that link in a browser you'll be able to do Cmd-S and save it as an SVG file. Or you could copy and paste this into an SVG file. http://jsfiddle.net/fsrdqtor/ Unfortunately I don't have it hosted as a file anywhere right now

**Comment by Victorystick** [comment]
Look here: https://github.com/gilbarbara/logos/blob/master/logos/rollupjs.svg

**Comment by Victorystick** [comment]
Oh, and please share a link to the blog post once you're done! :wink:

**Comment by CrowdHailer** [comment]
Thanks for the help. right I've now got it working all three ways.
Hope to get the post up this evening. I am just experimenting with a watch setup using [entr](http://entrproject.org/)

**Comment by CrowdHailer** [comment]
Here is the link to my blog post. http://insights.workshop14.io/2015/11/12/organising-client-javascript-with-rollup-js.html

**Comment by eventualbuddha** [comment]
@CrowdHailer I just read your blog post and had a few comments. I figured I'd post here since why not:

> It is also a component of Babel (a full ES6 transpiler) so there is an easy next step to get working with the rest of ES6.

This implies that Rollup is part of Babel, which it isn't. They definitely compliment each other but they're separate tools.

> `import * as calculator from "../src/calculator";`

This code example is something of an anti-pattern for Rollup as (I believe) it potentially forces Rollup to include more code than is needed. It's better to do this: `import { add } from "../src/calculator";`.

**Comment by Victorystick** [comment]
@eventualbuddha `import * as calculator from '...'` isn't really an anti-pattern. Thanks to Rollup's [static namespace optimisation](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20*%20as%20calculator%20from%20'.%2Fcalculator.js'%3B%5Cn%5Cnalert(%20calculator.add(%201%2C%202%20)%20)%3B%22%7D%2C%7B%22name%22%3A%22calculator.js%22%2C%22code%22%3A%22export%20function%20add%20(%20x%2C%20y%20)%20%7B%5Cn%20%20return%20x%20%2B%20y%3B%5Cn%7D%5Cn%5Cnexport%20function%20mult%20(%20x%2C%20y%20)%20%7B%5Cn%20%20return%20x%20*%20y%3B%5Cn%7D%5Cn%5Cnexport%20function%20sub%20(%20x%2C%20y%20)%20%7B%5Cn%20%20return%20x%20-%20y%3B%5Cn%7D%22%7D%5D%7D) we generate equivalent code to `import { add } from '...'`.

**Comment by CrowdHailer** [comment]
Thanks for the feedback @eventualbuddha 

Mostly I just meant to say that rollup acts as a subset of something like babel. I will try and rewrite that to clarify.

Second a quick question. What is the dream way to distribute and consume packages using rollup.
I.e. I have a module that I want to make available to more than one project of mine. I have control over both so what is the best way.

I am thinking that it is to put the shared module on npm then add it as a dependency. finally make use of the rollup npm plugin.

If that is the case why is npm compatability a plugin? If it's part of the ideal work flow it makes sense to me that it should be bundled in.

**Comment by eventualbuddha** [comment]
@Rich-Harris can probably answer better than I. I'll take a crack at it if he doesn't get to it.

**Comment by Victorystick** [comment]
@CrowdHailer Originally, Rollup had the ability to look up dependencies in `node_modules`. But the algorithm it used was a simplified version that wasn't completely compliant with how Node worked. Beyond that, Rollup is fundamentally just a library that bundles modules; it isn't bound to Node or NPM.

That's why we decided to only keep the logic for resolving relative paths in Rollup core, and defer all other path resulution to Plugins. The NPM plugin resolves modules in `node_modules` using `node-resolve`, and a JSPM plugin (if one existed) would resolve through `jspm_modules`.

I once suggested that we move Rollup's CLI related code to another repo. That didn't happen at the time. Since it's one of Rollup's principles that we shouldn't include that which isn't used, I think it's only fair that people who use Rollup as a pure library don't have to install our CLI related dependencies.

**Comment by CrowdHailer** [comment]
@Victorystick good answer cheers.

I can see why you don't want to bundle the behaviour in. My general query still stands. How are you requiring 3rd party modules? I am thinking I will use npm and try and find libraries with esnext in the package.json. But i am curious if I am just attached to npm because of browserify or is that still the best solution
