### ISSUE TITLE
Regression in 1.14.0 with imports and unused parameters

### ISSUE THREAD

**Issue by mikeharder** [rollup/rollup#2970]
- Rollup Version: Regression introduced in `1.14.0`, still repros in `1.16.2`
- Operating System (or Browser): `Windows 10`
- Node Version: `10.16.0`

### Overview
If an imported function and unused parameter have the same name, `rollup@1.13.1` renames the parameter which generates a valid bundle, while `rollup@1.14.0` (and `rollup@1.16.2`) does not rename the parameter which causes a runtime error.  I believe this is a regression introduced by https://github.com/rollup/rollup/pull/2892.

### How Do We Reproduce?
```js
// log.js
export const context = console.log;


// main.js
import * as log from "./log";

function test(context) {
  log.context("hello");
}

test();
```

### Expected Behavior
[REPL](https://rollupjs.org/repl?version=1.13.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGxvZyUyMGZyb20lMjAlNUMlMjIuJTJGbG9nJTVDJTIyJTNCJTVDbiU1Q25mdW5jdGlvbiUyMHRlc3QoY29udGV4dCklMjAlN0IlNUNuJTIwJTIwbG9nLmNvbnRleHQoJTVDJTIyaGVsbG8lNUMlMjIpJTNCJTVDbiU3RCU1Q24lNUNudGVzdCgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybG9nLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwY29udGV4dCUyMCUzRCUyMGNvbnNvbGUubG9nJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

```
> npm install --global rollup@1.13.1
> rollup main.js --format cjs
```

```js
'use strict';

const context = console.log;

function test(context$1) {
  context("hello");
}

test();
```

### Actual Behavior
[REPL](https://rollupjs.org/repl?version=1.14.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGxvZyUyMGZyb20lMjAlNUMlMjIuJTJGbG9nJTVDJTIyJTNCJTVDbiU1Q25mdW5jdGlvbiUyMHRlc3QoY29udGV4dCklMjAlN0IlNUNuJTIwJTIwbG9nLmNvbnRleHQoJTVDJTIyaGVsbG8lNUMlMjIpJTNCJTVDbiU3RCU1Q24lNUNudGVzdCgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybG9nLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwY29udGV4dCUyMCUzRCUyMGNvbnNvbGUubG9nJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

```
> npm install --global rollup@1.14.0
> rollup main.js --format cjs
```

```js
'use strict';

const context = console.log;

function test(context) {
  context("hello");
}

test();
```

**Comment by lukastaegert** [comment]
Thanks for spotting this, fix at #2972
