### ISSUE TITLE
add option preferDestructuring

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2971]
### Feature Use Case

src:

```js
import { a, b } from 'external';
a();
b();
```

current dist (amd):

```js
define(['external'], function (external) {
    external.a();
    external.b();
});
```

current dist (cjs):

```js
const external = require('external');
external.a();
external.b();
```

### Feature Proposal

proposal dist (amd) with that option:

```js
define(['external'], function ({ a, b }) {
    a();
    b();
});
```

current dist (cjs) with that option:

```js
const { a, b } = require('external');
a();
b();
```

proposal dists are smaller, faster, and friendly for minify.

**Comment by shellscape** [comment]
@lukastaegert this seems legitimate. What are your thoughts?

**Comment by lukastaegert** [comment]
It could be done but it is problematic because it will completely prevent live-bindings. So circular dependencies will produce invalid code with this option. One of the reasons we keep the object member syntax for formats other than ESM an SystemJS is that this will produce valid live-bindings that auto-update when the exports object in the exporting module is modified. ESM does not need this as it is built into the spec while SystemJS uses a specific setter syntax to simulate it.

**Comment by lukastaegert** [comment]
Thus I’m not sure it is worth the effort both in implementing and maintaining it.

**Comment by shellscape** [comment]
How you've gained all this insight is a mystery to me 😅. Good to know, thank you. @LongTengDao does that make sense as to why we are not currently outputting the bundle using destructuring?

**Comment by lukastaegert** [comment]
> How you've gained all this insight is a mystery to me

You’d be surprised how much of this knowledge is crowd-sourced. There is always someone who knows better and those people tend to create issues. Understanding those issues taught me the weirdest things about JS.

**Comment by LongTengDao** [comment]
The default behaviour non-destructuring is absolutely right, so I suggest to add an option, which is default false.

But this aim is harder to achieve in minify tool by enable pure_getters option. Because in script context, `this` of the call is also making difference.

While in module context, call requiring `this` is very rare.

gzip can overcome the long properties which minify tool can't, but it still need dynamic property access.

So I think add this feature in packing tool is best.

But now I have a new proposal, what's better than `preferDestructure` like `preferConst`, is `staticize` like `globals` and `paths`:

1.  differenct external module could have different setting;
2.  the word destructure is a es 6 feature, while the feature here refer to staticize.

However, there is still other way to do this. I can create a `external.js` file, to import and destruct them before export:

```js
import * as external from 'external';
export const { a, b, c, d, e } = external;
```

And then all files need this module import from that.

So if this is trivial to rollup, it's not necessary.
