### ISSUE TITLE
export { default } from "external-x" fails in non-ESM formats

### ISSUE THREAD

**Issue by aapoalas** [rollup/rollup#2977]
- Rollup Version: 1.15.1
- Operating System (or Browser): Ubuntu 14.04
- Node Version: 8.10.0

### How Do We Reproduce?
[Link to Repl](https://rollupjs.org/repl/?version=1.16.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjAlN0QlMjBmcm9tJTIwJTVDJTIyZXh0ZXJuYWwtcm91bmQtdG8tbmVhcmVzdC10aHJlZS5qcyU1QyUyMiUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmFtZCUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

Simple explanation: Re-exporting the default of an external module doesn't work.

### Expected Behavior
If 'interop' is on, then the interop function should unwrap the default value and that value should then be returned (AMD module) / assigned to exports (CJS module) / ...

If 'interop' is off, then no unwrap should be done and the value from the module should be returned / assigned to exports as-is.

### Actual Behavior
The 'interop' function unwraps the default value. Then `value.default` is returned / assigned to exports.

### [While I'm here](https://github.com/rollup/rollup/issues/2979)
~~My use-case for Rollup has recently been with compiling ESM files into single AMD modules for use. The usage of these AMD modules does not care at all about original ESM format of the data and as such a simple return statement is enough. Occasionally, still, Rollup has been adding "exports" into the dependencies and using that as the means of output. It would be nice if there was a way to forbid this. But that's not really in any way connected with this bug report. Sorry about that.~~

**Comment by lukastaegert** [comment]
I’m working on a fix for this but due to other issues it may take another week to complete.

**Comment by lukastaegert** [comment]
Fix at #3084

**Comment by aapoalas** [comment]
Cool, thank you!
