### ISSUE TITLE
Add ability to opt-out of deconflicting per source file

### ISSUE THREAD

**Issue by dstaley** [rollup/rollup#2978]
### Feature Use Case
In my main entry point, I shadow the global variables `setTimeout` and `clearTimeout`. Rollup's awesome deconflicting feature adjusts these variable names using `getSafeName`. I'd appreciate the ability to tell Rollup "Hey, don't adjust the names of these variables in these specific files."

For an example of what I mean, [here's a REPL](https://rollupjs.org/repl/?version=1.2.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGJhc2UlMjBmcm9tJTIwJTVDJTIyLiUyRmJhc2UlNUMlMjIlM0IlNUNuJTVDbmNvbnN0JTIwJTdCJTIwc2V0VGltZW91dCUyQyUyMGNsZWFyVGltZW91dCUyMCU3RCUyMCUzRCUyMHRoaW5nKCklM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMEtpbnRvSHR0cENsaWVudCUyMCU3QiU1Q24lMjAlMjBjb25zdHJ1Y3RvcigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHRoaXMuYmFzZSUyMCUzRCUyMGJhc2UlM0IlNUNuJTIwJTIwJTdEJTVDbiU3RCU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXNlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZGVsYXkobXMpJTIwJTdCJTVDbiU1Q3QlMkYlMkYlMjBJJTIwd2FudCUyMHNldFRpbWVvdXQlMjB0byUyMGJlJTIwdGhlJTIwb25lJTIwZnJvbSUyMHRoaW5nKCklM0IlNUNuJTIwJTIwcmV0dXJuJTIwbmV3JTIwUHJvbWlzZShyZXNvbHZlJTIwJTNEJTNFJTIwc2V0VGltZW91dChyZXNvbHZlJTJDJTIwbXMpKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlMjBkZWxheSUyMCU3RCUzQiU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIydW1kJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

### Feature Proposal

Add a new option on `output` allowing the user to opt out specific variables per source file from deconflicting.

If this is something that can be accomplished with a plugin please let me know! I looked through the documentation and played with a few hooks but I wasn't able to find where this would be the most appropriate. For the time being I'm simply replacing the deconflicted names in a `renderChunk` hook. However this is brittle since any modifications to the source file need to be reflected in the plugin, and any updates to Rollup's deconflict naming scheme would break it.

**Comment by lukastaegert** [comment]
The problem is that in your original code, the variables are not shadowed as they are in different modules. So what you want is that your bundled code behaves different from your unbundled code.

For your use-case, https://github.com/rollup/rollup-plugin-inject is probably a much better solution. It allows you to replace global variables with imported variables and also allows you to limit this to certain modules if you want to. If you create a module like this:

```js
// thing.js
export const {setTimeout, clearTimeout} = thing();
```

you should be able to use a config like this

```js
inject({
  setTimeout: [path.resolve( 'thing.js' ), 'setTimeout'],
  clearTimeout: [path.resolve( 'thing.js' ), 'clearTimeout'],
})
```

**Comment by dstaley** [comment]
Thanks so much for the nudge in the right direction! The inject plug-in
worked beautifully.

I'm not sure where else the ability to opt-out of deconflicting could be
useful, so I think this could be closed.
