### ISSUE TITLE
import() with template literals pass undefined to resolveDynamicImport hook

### ISSUE THREAD

**Issue by tivac** [rollup/rollup#2980]
The `resolveDynamicImport` plugin hook doesn't seem to work correctly with template literals. It seems like it should!

- Rollup Version: 1.16.4
- Operating System (or Browser): Windows 10
- Node Version: 12.6.0

### How Do We Reproduce?

1. `npx degit tivac/rollup-resolvedynamicimport-issue`
2. `npm install`
3. `npm start`

### Expected Behavior

Two AST nodes are printed to the console

### Actual Behavior

`undefined` is printed first, then an AST node is printed.

**Comment by lukastaegert** [comment]
Thanks, you are absolutely right, fix at #2984
