### ISSUE TITLE
Telling rollup to output in esm instead outputs to common JS both in config file and -f flag. 

### ISSUE THREAD

**Issue by redelman431** [rollup/rollup#2994]
- Rollup Version:1.16.7
- Operating System (or Browser): Fedora Linux 26
- Node Version:10.6.0

### How Do We Reproduce?

Three ways  to reproduce:

Bug #1. Following the tutorial from https://rollupjs.org/guide/en/#tutorial create these files

main.js

```
import foo from './foo.js';
export default function () {
  console.log(foo);
}

```
foo.js
`export default 'hello world!';`

rollup.config.js
```
export default {
  input: 'src/main.js',
  output: {
    file: 'bundle.js',
    format: 'esm'
  }
};

```
~    

run command `rollup -c`

Bug #2. Repeat steps in bug #1 (rollup.config.js not necessary) but  run` rollup src/main.js -f esm` instead.

Bug #3. Follow all the standard steps in the tutorial all the way up to code splitting   part https://rollupjs.org/guide/en/#code-splitting where you enter rollup src/main.js src/main2.js -f esm -d dist            

### Expected Behavior

Bug #1: running rollup -c should output bundle.js in esm.
 
Bug #2: running rollup src/main.js -f esm should output in esm.

Bug #3 following tutorial up to code splitting when running  `rollup src/main.js src/main2.js -f esm -d dist` should output code splitting in ESM like this

```
<!doctype html>
<script type="module">
  import main2 from './dist/main2.js';
  main2();
</script>
```

### Actual Behavior

Bug #1 bundle.js outputs in commonJS like this.

```
var foo = 'hello world!';

function main () {
  console.log(foo);
}

export default main;
```
~        

Bug #2  outputs to stdout is in commonJS like this: 

 ```
   src/main.js → stdout...
var foo = 'hello world!';

function main () {
  console.log(foo);
}
```

Bug #3: Dist folder shows 

dist/main.js 
```
 function main () {
  import('./foo-5e0078b9.js').then(({ default: foo }) => console.log(foo));
}

export default main;
             
```
dist/main2.js
```

import foo from './foo-5e0078b9.js';

function main2 () {
  console.log(foo);
}

export default main2;
```

chunked foo.js file: 

```
var foo = 'hello world!';

export default foo;
```

**Comment by TrySound** [comment]
No 1
Why do you call this a commonjs?
![image](https://user-images.githubusercontent.com/5635476/61151341-637fc380-a4ee-11e9-9e19-287b847ae731.png)

No 2
Can't reproduce. The output is like this. You probably misread.
```js
main.js → stdout...
var foo = 'hello world!';

function main () {
  console.log(foo);
}

export default main;
created stdout in 33ms
```

No 3
Tutorial provides html as setup example. It's not the output example. You should write html by hands.
