### ISSUE TITLE
PURE annotations don't work with tagged template literals

### ISSUE THREAD

**Issue by modernserf** [rollup/rollup#3002]
- Rollup Version: 1.16
- Operating System (or Browser): Ubuntu 16.04.6 LTS
- Node Version: 10.15.3

### How Do We Reproduce?

[repl link](https://rollupjs.org/repl/?version=1.16.7&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHN0eWxlZCUyMGZyb20lMjAlNUMlMjJzdHlsZWQtY29tcG9uZW50cyU1QyUyMiUzQiU1Q24lNUNuY29uc3QlMjBCdXR0b25GdW5jJTIwJTNEJTIwJTJGKiU0MF9fUFVSRV9fKiUyRnN0eWxlZC5idXR0b24oJTVCJTVDJTIyJTVDJTIyJTVEKSUzQiU1Q25jb25zdCUyMEJ1dHRvblRlbXBsYXRlJTIwJTNEJTIwJTJGKiU0MF9fUFVSRV9fKiUyRnN0eWxlZC5idXR0b24lNjAlNjAlM0IlNUNuY29uc3QlMjBCdXR0b25UZW1wbGF0ZUNhbGwlMjAlM0QlMjAlMkYqJTQwX19QVVJFX18qJTJGc3R5bGVkKCdidXR0b24nKSU2MCU2MCUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior
Tagged template literals should be treated like function calls, and unused template literals annotated with `/*@__PURE__*/` should be removed from output.

### Actual Behavior
Tagged template literals that are annotated with `/*@__PURE__*/` are not removed, even though equivalent function calls are.

This twitter thread suggests the issue may be with terser: 
> rollup implements terser semantics in this case (otherwise it wreak havoc on the community with differences between tools), so probably its best to report it to terser, i believe tagged template call should be treated as function call
-- [Mateusz Burzyński](https://twitter.com/AndaristRake/status/1149091070967451649)

**Comment by shellscape** [comment]
Thanks for opening an issue, and apologies for it taking so long to get a reply. Citing this response https://twitter.com/fabiosantosart/status/1149096395586068481 by a Terser maintainer, please create an issue in the terser repo and they'll look into it.
