### ISSUE TITLE
Rollup TypeScript not properly targeting ES5

### ISSUE THREAD

**Issue by msukmanowsky** [rollup/rollup#3003]
- Rollup Version: 1.17.0
- Operating System (or Browser): Mac OSX 10.14.5
- Node Version: v10.15.3

### How Do We Reproduce?

1. Clone sample repo at https://github.com/msukmanowsky/rollup-typescript-es5
1. Run `npm run build` and check `dist/library-js.umd.js`
1. Given `tsconfig.json` and `rollup.config.js`, the designated target is ES5 which doesn't support arrow functions, yet the UMD build clearly shows arrow functions (see [here](https://github.com/msukmanowsky/rollup-typescript-es5/blob/master/dist/library-js.umd.js#L976) for an example).

### Expected Behavior

Since [tsconfig.json targets es5](https://github.com/msukmanowsky/rollup-typescript-es5/blob/master/tsconfig.json#L3), arrow functions should be converted to regular `function` syntax.

### Actual Behavior

Non ES5 features like arrow functions remain.

**Comment by manucorporat** [comment]
TS does not transpile JS dependencies, you should ran babel on top of your output JS. Rollup is configured to distribute es2015 JS: https://github.com/rollup/rollup/blob/master/tsconfig.json#L13

If you need support IE11, it's in your side to transpile it correctly, this is not a rollup issue, since rollup does not have anything to do with transpilation, look at the rollup-plugin-babel

**Comment by lukastaegert** [comment]
> TS does not transpile JS dependencies, you should ran babel on top of your output JS. Rollup is configured to distribute es2015 JS: https://github.com/rollup/rollup/blob/master/tsconfig.json#L13

this goes for Rollup's source code, TS output is handled solely by rollup-plugin-typescript. If you want to avoid Babel, a simple approach is to also run your .js files through TypeScript in which case TypeScript WILL do the transpilation for you. This is  actually what Rollup does via this special config: https://github.com/rollup/rollup/blob/def3ae2b4d2e5fde0f28d5ff1bf92ab9a2899e28/rollup.config.js#L94

**Comment by lukastaegert** [comment]
It will make things a little slower, but so will Babel, and there is only one place where you configure your target environment, namely your tsconfig

**Comment by msukmanowsky** [comment]
Thanks @manucorporat and @lukastaegert!

[Tried](https://github.com/msukmanowsky/rollup-typescript-es5/commit/b6c59631c2750f6fe5b45d7d0b686d4636e7fa7f) following @lukastaegert's suggestion to just use TypeScript for all files but this doesn't seem to work:

```
npm run build

> rollup-typescript-es5@1.0.0 build /Users/mikesukmanowsky/code/personal/rollup-typescript-es5
> rollup -c

loaded rollup.config.js with warnings
(!) Unused external imports
uglify imported from external module 'rollup-plugin-uglify' but never used

src/main.ts → dist/library-js.umd.js...
created dist/library-js.umd.js in 4.5s

src/main.ts → dist/library-js.cjs.js, dist/library-js.esm.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/main.ts (11:22)
 9:   }
10: 
11:   static isArray(thing: any) {
                          ^
12:     return isArray(thing);
13:   }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/mikesukmanowsky/code/personal/rollup-typescript-es5/node_modules/rollup/dist/rollup.js:9408:30)
    at Module.error (/Users/mikesukmanowsky/code/personal/rollup-typescript-es5/node_modules/rollup/dist/rollup.js:13347:9)
    at tryParse (/Users/mikesukmanowsky/code/personal/rollup-typescript-es5/node_modules/rollup/dist/rollup.js:13262:16)
    at Module.setSource (/Users/mikesukmanowsky/code/personal/rollup-typescript-es5/node_modules/rollup/dist/rollup.js:13573:33)
    at Promise.resolve.catch.then.then.then (/Users/mikesukmanowsky/code/personal/rollup-typescript-es5/node_modules/rollup/dist/rollup.js:16398:20)
```

Before I try going the Babel route, wanted to quickly see if perhaps I missed something with my rollup or typescript config?

**Comment by lukastaegert** [comment]
Hmm, looks ok to me, maybe there is some interaction with the spreaded `tsconfig.compilerOptions`, is there some `exclude`? The symptom looks like TypeScript is not picking up the TS files or thinks they are JavaScript instead. As it is working for Rollup, I wonder what is different for you. The order of plugins roughly seems to match the order that Rollup uses...

**Comment by msukmanowsky** [comment]
Was indeed a [stupid](https://github.com/msukmanowsky/rollup-typescript-es5/commit/6b45f6d989ea081ef40d01e76d319168f753664e) on my end. Seems to be working properly, closing this one out.

Thanks again!
