### ISSUE TITLE
Print pathinfo for each file

### ISSUE THREAD

**Issue by kraftwer1** [rollup/rollup#3004]
### Feature Use Case
Print pathinfo for each file

### Feature Proposal
In Webpack, there's an option output.pathinfo to include comments in bundles with information about the contained modules, e.g.:

    (window["webpackJsonp"] = window["webpackJsonp"] || []).push([["vendor"],{
    /***/ "./node_modules/@uirouter/angularjs/release/ui-router-angularjs.js":
    /*!*************************************************************************!*\
      !*** ./node_modules/@uirouter/angularjs/release/ui-router-angularjs.js ***!
      \*************************************************************************/
    /*! no static exports found */
    /***/ (function(module, exports, __webpack_require__) {
    (function (global, factory) {
        undefined;

It would be great to have something similar in Rollup as well.
Might be related to https://github.com/rollup/rollup/issues/1184?

**Comment by lukastaegert** [comment]
Everything is in place to write a plugin that does just that if anyone wants to pick this up:
https://rollupjs.org/guide/en/#renderchunk receives information about the rendered chunk that lists all included modules, see https://rollupjs.org/guide/en/#generatebundle for reference about the format; renderChunk can also inject comments if there is demand.

I do not see this as a candidate for a core feature.
