### ISSUE TITLE
Exported aliased asterisk cannot be modified in browser

### ISSUE THREAD

**Issue by EliasHasle** [rollup/rollup#3005]
Setup:
Assuming three is installed,

index.js:
````
import * as THREE from "three";
export {THREE};
````

Build UMD package named bundle.js

html:
````
<script src="bundle.js"></script>
<script>
/*Try to inject something (a typical use case is to 
import an example script from Three.js examples)*/
THREE.abc = {};
THREE.abc.def = "This string should be stored.";
</script>
````

Run in Chrome.

### Expected Behavior / Situation
I expect to be able to add properties to THREE, as is common practice from browser usage. Alternatively, I expect Chrome to protest when I try to assign to THREE.abc.

### Actual Behavior / Situation
Chrome responds with silence to the abc assignment, but fails with object undefined for the def assignment. Clearly, the first assignment was unsuccessful

I could work around the problem like this:
index.js:
````
import * as bareTHREE from "three";
var THREE = {};
Object.assign(THREE, bareTHREE);
export {THREE};
````

**Comment by EliasHasle** [comment]
@TrySound Why did you close? (I noticed now that some details were missing that I was sure I had added. I have now added them again.)

**Comment by TrySound** [comment]
@EliasHasle You created two issues.
https://github.com/rollup/rollup/issues/3006

**Comment by EliasHasle** [comment]
Oh, I just noticed. Sorry. Thanks. :-)
