### ISSUE TITLE
Exported aliased asterisk import cannot be modified in browser

### ISSUE THREAD

**Issue by EliasHasle** [rollup/rollup#3006]
Setup:
Assuming three.js is installed,

index.js:
````
import * as THREE from "three";
export {THREE};
````

Build UMD package named bundle.js

html:
````
<script src="bundle.js"></script>
<script>
//Extract THREE:
{THREE} = bundle;
</script>
<script>
/*Try to inject something (a typical use case is to 
import an example script from Three.js examples)*/
THREE.abc = {};
THREE.abc.def = "This string should be stored.";
</script>
````

Run in Chrome.

### Expected Behavior / Situation
I expect to be able to add properties to THREE, as is common practice from browser usage. Alternatively, I expect Chrome to protest when I try to assign to THREE.abc.

### Actual Behavior / Situation
Chrome responds with silence to the abc assignment, but fails with object undefined for the def assignment. Clearly, the first assignment was unsuccessful, even though the THREE object is well populated.

I could work around the problem like this:
index.js:
````
import * as bareTHREE from "three";
var THREE = {};
Object.assign(THREE, bareTHREE);
export {THREE};
````

### Modification Proposal
I do not know the exact reason for the current behavior, but I find it counter-intuitive that Rollup somehow emits an immutable object (that Chrome silently ignores attempts to alter). It is OK that the import is const, but properties of consts usually aren't locked, as my workaround demonstrates.

Note that the example in this issue is untested, but follows the pattern from my project. If it matters, I am applying `rollup-plugin-node-resolve` and `rollup-plugin-commonjs` (in that order). The Rollup config for three.js is in https://github.com/mrdoob/three.js/blob/dev/rollup.config.js

**Comment by lukastaegert** [comment]
The reason you cannot add properties is most likely that Rollup uses Object.freeze on namespace objects, which is what the ES module spec dictates. If you were to use actual ES modules in a browser, you would not be able to modify namespaces either. I do not know why the error is not thrown for you, but clearly modification fails. Using Object-assign is a legitimate way of creating a mutable copy from a frozen object. Beyond that, you can also opt out of the freezing behaviour via https://rollupjs.org/guide/en/#outputfreeze but be aware that your code will not work as expected when producing actual ES modules

**Comment by EliasHasle** [comment]
Thank you very much for a clear and reasonable explanation as wellas for providing a solution. Adding `freeze: true` to the UMD output solved the problem without the `Object.assign` workaround. If I later want to add an ESM output, I can omit the `freeze: true`. :-)
