### ISSUE TITLE
Hoist or prefetch a dynamic import's transitive dependencies 

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/rollup#3009]
### Feature Use Case
Consider this mockup of a typical web application: https://github.com/LarsDenBakker/rollup-code-splitting

`app.js` on page switch imports the currently active page using a dynamic import. `page-a`, `page-b`, and `page-c` all depend on some shared code.

In the rollup build output the app and pages a, b and c are separate files as well as a dynamic chunk with the shared dependencies.

When running this code in the browser, `app.js` first imports a page which then imports the shared chunk. The browser needs two roundtrips to the server in order to know all the required dependencies.

### Feature Proposal
In https://github.com/rollup/rollup/pull/2073 work was already done to hoist transitive static imports to the highest level. I'm wondering if we can do the same for dynamic imports.

The output of `app.js` would go from:
```js
function lazyLoad(page) {
  switch (page) {
    case 'a':
      return import('./page-a-2c3bb48b.js');
    case 'b':
      return import('./page-b-a68d5be4.js');
    case 'c':
      return import('./page-c-9448c98d.js');
  }
}
```

to:

```js
function lazyLoad(page) {
  switch (page) {
    case 'a':
      return Promise.all([
        import('./chunk-501514fe.js'),
        import('./page-a-2c3bb48b.js'),
      ]);
    case 'b':
      return Promise.all([
        import('./chunk-501514fe.js'),
        import('./page-b-a68d5be4.js'),
      ]);
    case 'c':
      return Promise.all([
        import('./chunk-501514fe.js'),
        import('./page-c-9448c98d.js'),
      ]);
  }
}
```

I'm not entirely certain if dynamic imports like this preserve execution order the same way as static imports. Otherwise we might need to look into adding prefetch links instead, though that sounds more like plugin territory.

Happy to work on a PR if I know the intended direction.

**Comment by acarl005** [comment]
I like this idea! Would it be possible to accomplish using a `<link rel="prefetch">` tag instead?
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ)

**Comment by LarsDenBakker** [comment]
@lukastaegert do you think this is something that could be in rollup core, or should it be a separate plugin?

**Comment by tivac** [comment]
I'm doing something kinda similar to this in a real hacky way for https://github.com/tivac/modular-css/tree/master/packages/rollup-rewriter

**Comment by lukastaegert** [comment]
As far as I know this will not preserve execution order, so I would be hesitant to put this into Rollup core. At the least, it would need to be configurable and off by default. But a plugin could definitely be useful. Together with https://rollupjs.org/guide/en/#renderdynamicimport and some solution for #3519, there should be something nice possible. However one problem is that chunk names are not yet known during `renderChunk`, so there might be something else needed.

**Comment by vikerman** [comment]
Created a plugin to do this for now - 
https://github.com/vikerman/rollup-plugin-hoist-import-deps

Had to use generateBundle instead of renderCHunk for now so that full graph is available (in circular dynamic deps and non-ESM cases).

**Comment by LarsDenBakker** [comment]
Closing this since we can use this plugin now.
