### ISSUE TITLE
`require.extensions` hook?

### ISSUE THREAD

**Issue by impinball** [rollup/rollup#301]
That would make this much easier to work with and test in Node.

**Comment by Rich-Harris** [comment]
Can you outline the use case in more detail? It sounds like something that might be best kept separate from the core library.

**Comment by impinball** [comment]
Test runners like Mocha have require hooks for Node.js. And this also
implements module resolution correctly in that modules export bindings, not
values. I'm interested in this because of that reason, and that I'm making
libraries that work on both server and client.

**Comment by Rich-Harris** [comment]
What would be the difference between using `require.extensions` and bundling the code under test before running Mocha? I typically have something like this in my package.json...

```js
{
  "scripts": {
    "build": "rollup -c",
    "test": "mocha",
    "pretest": "npm run build"
  }
}
```

...which has basically the same end result, no?

**Comment by impinball** [comment]
Never mind... I'm also looking at the asynchronous module resolution as
well. It would require quite a few things completely rewritten, given
Node's module loader is synchronous. Great work, though!

**Comment by Rich-Harris** [comment]
Cool! will close this issue

**Comment by Victorystick** [comment]
It might be a good idea to look into best practices for testing code with Rollup. Preferably one that reruns the tests on save.
