### ISSUE TITLE
Prevent splitting particular modules

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#3017]
### Feature Use Case

Imagine a module that contains localised values (in this example it's just strings, but it may also be JSX).

[Repl demo](https://rollupjs.org/repl/?version=1.18.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRmxhbmcuanMnJTNCJTVDbmNvbnNvbGUubG9nKGZvbyklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYWluMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBiYXIlMjAlN0QlMjBmcm9tJTIwJy4lMkZsYW5nLmpzJyUzQiU1Q25jb25zb2xlLmxvZyhiYXIpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGFuZy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMCdmb28nJTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwYmFyJTIwJTNEJTIwJ2JhciclM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

#### Input

**main.js** (entry point)

```js
import { foo } from './lang.js';
console.log(foo);
```

**main2.js** (entry point)

```js
import { bar } from './lang.js';
console.log(bar);
```

**lang.js**

```js
export const foo = 'foo';
export const bar = 'bar';
```

#### Current output

**main.js**

```js
import { f as foo } from './chunk-fa4f3665.js';

console.log(foo);
```

**main2.js**

```js
import { b as bar } from './chunk-fa4f3665.js';

console.log(bar);
```

**chunk-fa4f3665.js**

```js
const foo = 'foo';
const bar = 'bar';

export { bar as b, foo as f };
```

#### Ideal output

**main.js**

```js
const foo = 'foo';

console.log(foo);
```

**main2.js**

```js
const bar = 'bar';

console.log(bar);
```

…where a decent minifier will be able to inline the values.

### Proposal

A way to say "please don't code-split 'lang.js', always bundle it".

Alternatively (but much harder), Rollup could figure out how to split within a module.

**Comment by TrySound** [comment]
There is a proposal.
https://github.com/rollup/rollup/issues/2407

**Comment by jakearchibald** [comment]
Is that the same thing? It seems to be about dynamic import.

**Comment by surma** [comment]
I think #2407 is related, but not the same.

Just wanted to leave a [REPL sample](https://rollupjs.org/repl/?version=1.18.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QkElN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnNoYXJlZC5qcyU1QyUyMiUzQiU1Q24lNUNuaW1wb3J0KCU1QyUyMi4lMkZ3b3JrZXIuanMlNUMlMjIpJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhBKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNoYXJlZC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMEElMjAlM0QlMjA0JTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwQiUyMCUzRCUyMDUlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyd29ya2VyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QkIlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnNoYXJlZC5qcyU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2coQiklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=). Note that tree-shaking will remove B if you don't import it in `worker.js`. It seems plausible that Rollup could also be able to do tree... uh,.... splitting, I guess? So I'd expect the linked REPL example to generate _two_ chunk files, one for A and one for B.

**Comment by TrySound** [comment]
Ah, sorry. This is it
https://github.com/rollup/rollup/issues/2788#issuecomment-479338894

**Comment by jakearchibald** [comment]
Yeah, that's the same. Cheers!

**Comment by lukastaegert** [comment]
As stated on the other ticket, `manualChunks` are a way to prevent code-splitting and reduce the number of chunks.
