### ISSUE TITLE
Add CLI option to fail with warnings

### ISSUE THREAD

**Issue by cdfa** [rollup/rollup#3021]
### Feature Use Case
When building on a CI server, have the job fail if there are any warnings.

### Feature Proposal
A CLI option like `--no-warnings`, which still finishes the build and prints all warnings, but exits with a non-zero code.

**Comment by lukastaegert** [comment]
You can directly fail on the first warning by using an `onwarn` handler in the config file but I guess this is not what you want as this is neither a CLI option nor does it collect all warnings. Definitely an idea to be considered, though I am not yet sure about the name as this will not prevent warnings. Maybe `--fail-after-warnings` or something similar?

**Comment by cdfa** [comment]
Yeah I was trying to figure out a way to do it with `onwarn` before, but couldn't figure it out. I didn't put much thought into the name yet, but `--fail-after-warnings` sounds quite good!

**Comment by gonzarodriguezt** [comment]
Hey! Just to clarify the spec of this feat, it should finish the build, or just show the warnings and then fail?

**Comment by cdfa** [comment]
It should finish the build, showing any warnings that occur and then fail.

**Comment by davidclark87** [comment]
@lukastaegert this is super useful - thanks. One question - am I right in thinking `failAfterWarnings` is not exposed as a config file option? I was hoping to avoid it to each npm script where I run rollup.

**Comment by lukastaegert** [comment]
No, mainly because it does not translate well to the browser build and non-CLI builds will get a better picture by adding an `onward` handler.
