### ISSUE TITLE
Import default not working after exporting * from module

### ISSUE THREAD

**Issue by affanshahid** [rollup/rollup#3022]
- Rollup Version: 1.18.0
- Operating System (or Browser): Win 10/Chrome 76
- Node Version: 12.4.0

### How Do We Reproduce?

I have a file `src/Button/Button.tsx`:
```ts
export default function Button(){}
export interface ButtonProps {}
```

I am re-exporting all the exports in a file `src/Button/index.ts`:
```ts
export * from './Button'; //i.e src/Button/Button.tsx
```

In my entry file I am re-exporting everything including this particular component:
```ts
export { ButtonProps, default as Button } from './Button'; //i.e src/Button/index.ts
```

When running a UMD build with rollup however, I get an error at the line above:
```
src/index.ts → dist/comp-framework.js...
[!] Error: 'default' is not exported by src\Button\index.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module-
src\index.ts (1:22)
1: export { ButtonProps, default as Button } from './Button';

Error: 'default' is not exported by src\Button\index.ts
```

This is strange since running just `tsc` works absolutely fine. So has to be an issue with rollup or the typescript plugin. My rollup config (I've removed all other plugins other than TS to narrow down the issue):
```js
import typescript from 'rollup-plugin-typescript2';

const input = 'src/index.ts';
const globals = {
  react: 'React',
  'react-dom': 'ReactDOM',
};
const tsOverrides = {
  compilerOptions: {
    module: 'es2015',
    declaration: false,
  }
};

export default [
  {
    input,
    output: {
      file: 'dist/comp-framework.js',
      format: 'umd',
      name: 'CompFramework',
      globals
    },
    external: Object.keys(globals),
    plugins: [
      typescript({ typescript: require('typescript'), tsconfigOverride: tsOverrides, rollupCommonJSResolveHack: true }),
    ]
  },
  {
    input,
    output: {
      file: 'dist/comp-framework.min.js',
      format: 'umd',
      name: 'CompFramework',
      globals
    },
    external: Object.keys(globals),
    plugins: [
      typescript({ typescript: require('typescript'), tsconfigOverride: tsOverrides, rollupCommonJSResolveHack: true }),
    ]
  }
]
```

EDIT: [example on the REPL](https://rollupjs.org/repl/?version=1.18.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBERUZBVUxUJTIwRVhQT1JUUyU1Q24lMjAlMjAlMjBEZWZhdWx0JTIwZXhwb3J0cyUyMGZyb20lMjB0aGUlMjAnZW50cnklMjBtb2R1bGUnJTIwYXJlJTVDbiUyMCUyMCUyMGV4cG9ydGVkJTIwZnJvbSUyMHRoZSUyMGJ1bmRsZSUyMColMkYlNUNuZXhwb3J0JTIwJTdCJTIwZGVmYXVsdCUyMGFzJTIwYWZmYW4lMkMlMjBmb28lMjAlN0QlMjBmcm9tJTIwJy4lMkZhbnN3ZXIxJyUzQiUyMCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmFuc3dlci5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwNDIlM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAxJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmFuc3dlcjEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwKiUyMGZyb20lMjAnLiUyRmFuc3dlciclM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyaWlmZSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by TrySound** [comment]
Hi, this is by spec. `export *` does not consider `default`. I guess to prevent collision when exporting two modules. This how it works.
```
export * from './Button';
export { default } from './Button';
```

**Comment by affanshahid** [comment]
Alright makes sense!
