### ISSUE TITLE
Tree-shaking drops imports with side-effects

### ISSUE THREAD

**Issue by cristinecula** [rollup/rollup#3039]
- Rollup Version: 1.19.4
- Operating System (or Browser): Ubuntu 18.04
- Node Version: 12.4.0

I am trying to use billboard.js in my project and rollup removes more code than it should. The lib contains imports with side-effects, like so:

https://github.com/naver/billboard.js/blob/master/src/core.js#L10
https://github.com/naver/billboard.js/blob/master/src/config/config.js

Tree-shaking removes all imports of this type.

### How Do We Reproduce?

I tried creating a minimal reproduction on rollup repl, but the problem does not manifest there: [repl](https://rollupjs.org/repl/?version=1.19.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGJiJTIwJTdEJTIwZnJvbSUyMCcuJTJGYmlsbGJvYXJkLmpzJTJGc3JjJTJGY29yZSclM0IlNUNuJTVDbmJiLmdlbmVyYXRlKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiaWxsYm9hcmQuanMlMkZzcmMlMkZjb3JlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRioqJTVDbiUyMColMjBDb3B5cmlnaHQlMjAoYyklMjAyMDE3JTIwfiUyMHByZXNlbnQlMjBOQVZFUiUyMENvcnAuJTVDbiUyMColMjBiaWxsYm9hcmQlMjBwcm9qZWN0JTIwaXMlMjBsaWNlbnNlZCUyMHVuZGVyJTIwdGhlJTIwTUlUJTIwbGljZW5zZSU1Q24lMjAqJTJGJTVDbmltcG9ydCUyMENoYXJ0JTIwZnJvbSUyMCU1QyUyMi4lMkZpbnRlcm5hbHMlMkZDaGFydCU1QyUyMiUzQiU1Q25pbXBvcnQlMjBDaGFydEludGVybmFsJTIwZnJvbSUyMCU1QyUyMi4lMkZpbnRlcm5hbHMlMkZDaGFydEludGVybmFsJTVDJTIyJTNCJTVDbiU1Q25pbXBvcnQlMjAlNUMlMjIuJTJGY29uZmlnJTJGY29uZmlnJTVDJTIyJTNCJTVDbiU1Q25jb25zdCUyMGJiJTIwJTNEJTIwJTdCJTVDbiU1Q3RnZW5lcmF0ZShjb25maWcpJTIwJTdCJTVDbiU1Q3QlNUN0Y29uc3QlMjBpbnN0JTIwJTNEJTIwbmV3JTIwQ2hhcnQoKSUzQiU1Q24lNUN0JTVDdHJldHVybiUyMGluc3QlM0IlNUNuJTVDdCU3RCUyQyU1Q24lNUN0Y2hhcnQlM0ElMjAlN0IlNUNuJTVDdCU1Q3RmbiUzQSUyMENoYXJ0LnByb3RvdHlwZSUyQyU1Q24lNUN0JTVDdGludGVybmFsJTNBJTIwJTdCJTVDbiU1Q3QlNUN0JTVDdGZuJTNBJTIwQ2hhcnRJbnRlcm5hbC5wcm90b3R5cGUlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbmV4cG9ydCUyMCU3QmJiJTdEJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBiYiUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmlsbGJvYXJkLmpzJTJGc3JjJTJGaW50ZXJuYWxzJTJGQ2hhcnQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQ2hhcnRJbnRlcm5hbCUyMGZyb20lMjAlNUMlMjIuJTJGQ2hhcnRJbnRlcm5hbCU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNsYXNzJTIwQ2hhcnQlMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKGNvbmZpZyklMjAlN0IlNUNuJTVDdCU1Q3Rjb25zdCUyMCUyNCUyNCUyMCUzRCUyMG5ldyUyMENoYXJ0SW50ZXJuYWwodGhpcyklM0IlNUNuJTVDdCU3RCU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmlsbGJvYXJkLmpzJTJGc3JjJTJGaW50ZXJuYWxzJTJGQ2hhcnRJbnRlcm5hbC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBDaGFydEludGVybmFsJTIwJTdCJTVDbiU1Q3Rjb25zdHJ1Y3RvcihhcGkpJTIwJTdCJTVDbiU1Q3QlNUN0Y29uc3QlMjAlMjQlMjQlMjAlM0QlMjB0aGlzJTNCJTVDbiU1Q24lNUN0JTVDdCUyNCUyNC5hcGklMjAlM0QlMjBhcGklM0IlNUNuJTVDdCU1Q3QlMjQlMjQuY29uZmlnJTIwJTNEJTIwJTI0JTI0LmdldE9wdGlvbnMoKSUzQiU1Q24lNUN0JTdEJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiaWxsYm9hcmQuanMlMkZzcmMlMkZjb25maWclMkZjb25maWcuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQ2hhcnRJbnRlcm5hbCUyMGZyb20lMjAlNUMlMjIuLiUyRmludGVybmFscyUyRkNoYXJ0SW50ZXJuYWwlNUMlMjIlM0IlNUNuaW1wb3J0JTIwJTdCZXh0ZW5kJTdEJTIwZnJvbSUyMCU1QyUyMi4uJTJGaW50ZXJuYWxzJTJGdXRpbCU1QyUyMiUzQiU1Q24lNUNuZXh0ZW5kKENoYXJ0SW50ZXJuYWwucHJvdG90eXBlJTJDJTIwJTdCJTVDbiU1Q3RnZXRPcHRpb25zKCklMjAlN0IlNUNuJTVDdCU1Q3RyZXR1cm4lMjAlN0IlN0QlM0IlNUNuJTVDdCU3RCU1Q24lN0QpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJpbGxib2FyZC5qcyUyRnNyYyUyRmludGVybmFscyUyRnV0aWwuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjBleHRlbmQlMjAlM0QlMjAodGFyZ2V0JTIwJTNEJTIwJTdCJTdEJTJDJTIwc291cmNlKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0Zm9yJTIwKGNvbnN0JTIwcCUyMGluJTIwc291cmNlKSUyMCU3QiU1Q24lNUN0JTVDdHRhcmdldCU1QnAlNUQlMjAlM0QlMjBzb3VyY2UlNUJwJTVEJTNCJTVDbiU1Q3QlN0QlNUNuJTVDbiU1Q3RyZXR1cm4lMjB0YXJnZXQlM0IlNUNuJTdEJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlNUNuJTVDdGV4dGVuZCU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

I created this minimal branch on the project I'm working on
https://github.com/Neovici/cosmoz-charts/tree/rollup-repro

Checkout, then `npm i && npm run build`, then open `dist/cosmoz-chart.js` and search for `getOptions` and notice that it's declaration is missing.

### Expected Behavior

The code at https://github.com/naver/billboard.js/blob/master/src/config/config.js should make into the bundle

### Actual Behavior

The code is removed.

**Comment by cristinecula** [comment]
It seems that this bug does not manifest if I use the same rollup config directly in the billboard.js repo (i.e. without using rollup-plugin-resolve).

https://github.com/plumelo/billboard.js/tree/rollup-repro

Checkout, then `npm i && npm run build`, then open `dist/repro.js` and search for `getOptions` and notice that it's declaration is there.

**Comment by TrySound** [comment]
This is the problem.
https://github.com/naver/billboard.js/blob/master/package.json#L29-L31

**Comment by cristinecula** [comment]
Woah, thanks @TrySound! Didn't even know such a feature existed...
I'll submit a PR there. 

Thank you so much!
