### ISSUE TITLE
export default shouldn't follow variable changes

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#3040]
- Rollup Version: 1.19.4
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

It works right when `export default local;`:

```js
var local = 0;
export default local;// default is the value of local currently 0 forever
// same as export default (local);
local = 1;
```

```js
var local = 0;
export { local as default };// default keep same with local
local = 1;
```

It seems rollup check if there is rewrite to variable in the module, to promise `export default n` just export current value.

But when `export default global;`, here is bug:

```html
<script>
window.global=0;
</script>

<script type="module">
import global from './global.js';
console.log(global);
window.global = 1;
console.log(global);// expect 0 but got 1 after pack
</script>
```

### Expected Behavior

```
var global$1 = global;
console.log(global$1);// 0
window.global = 1;
console.log(global$1);// 0
```

### Actual Behavior

Using rollup packed file:

```js
console.log(global);// 0
window.global = 1;
console.log(global);// 1
```

---

I also accept this as a feature of rollup, to leave a way to export bind of global let, which is not global.property. After all, pack tool is not final environment, there could be differences.

But if so, it should be a stable feature of rollup, which say clearly in docs (difference with spec and promise not change unless major change).

**Comment by shellscape** [comment]
Thanks for opening an issue, and apologies that it took a while to get a response. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Work to isolate the problem and provide the exact steps in this issue, or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.

**Comment by LongTengDao** [comment]
https://rollupjs.org/repl/?version=1.27.14&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGdsb2JhbCUyMGZyb20lMjAnLiUyRmdsb2JhbC5qcyclM0IlNUNuZ2xvYmFsVGhpcy5jb25zb2xlLmxvZyhnbG9iYWwpJTNCJTVDbmdsb2JhbFRoaXMuZ2xvYmFsJTIwJTNEJTIwMSUzQiU1Q25nbG9iYWxUaGlzLmNvbnNvbGUubG9nKGdsb2JhbCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJnbG9iYWwuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZ2xvYmFsVGhpcy5nbG9iYWwlMjAlM0QlMjAwJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBnbG9iYWwlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by lukastaegert** [comment]
Thanks, I may have missed this issue earlier. Yes, I agree this is a bug. As global variables cannot be tracked by Rollup, they need to be treated the same way as reassigned local variables (or expressions that do not correspond to a variable), i.e. a new variable should be introduce. I do not think it is a big change to fix that, PR welcome!

**Comment by lukastaegert** [comment]
This is definitely fixed in current versions of Rollup: https://rollupjs.org/repl/?version=2.23.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGElMjBmcm9tJTIwJy4lMkZnbG9iYWwuanMnJTNCJTVDbmNvbnNvbGUubG9nKGEpJTNCJTJGJTJGJTIwMCU1Q25nbG9iYWxUaGlzLmElMjAlM0QlMjAxJTNCJTVDbmNvbnNvbGUubG9nKGEpJTNCJTJGJTJGJTIwMSUyQyUyMGJ1dCUyMGV4cGVjdCUyMDAlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJnbG9iYWwuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZ2xvYmFsVGhpcy5hJTIwJTNEJTIwMCUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwYSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE
