### ISSUE TITLE
Hot reload in docker container

### ISSUE THREAD

**Issue by zjoin** [rollup/rollup#3041]
I run svelte app image in docker container, but hot reload not working. How keep changes?

**Comment by shellscape** [comment]
Thanks for opening an issue @zjoin. Unfortunately this isn't the right place to come to for support.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs
