### ISSUE TITLE
dispose __proto__ export properly

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#3042]
- Rollup Version: 1.19.4
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

rollup options:

```toml
output.format = 'cjs'
```

main.js:

```js
import * as y from './mod.js';
export var x = 0;
export var __proto__ = y;
export var z = 2;
```

mod.js:

```js
export var a = 0;
export var __proto__ = 1;
export var b = 2;
```

### Expected Behavior

output[0].code:

```js
var a = 0;
var __proto__ = 1;
var b = 2;

var y = {
    a: a,
    __proto__: null,// case 2
    b: b
};
y.__proto__ = __proto__;

exports.x = 0;
exports.__proto__ = null;// case 1
exports.__proto__ = y;
exports.z = 2;
```

### Actual Behavior

output[0].code:

```js
var a = 0;
var __proto__ = 1;
var b = 2;

var y = {
    a: a,
    __proto__: __proto__,
    b: b
};

exports.x = 0;
exports.__proto__ = y;
exports.z = 2;
```

**case 1**: Set property `__proto__` to `null` before really set it would be safer.

**case 2**: Declare property `__proto__` as `null`, and set it later.

**Comment by shellscape** [comment]
@LongTengDao please fill in the missing data on the template

**Comment by LongTengDao** [comment]
@shellscape Hi, I tried to fill more info. I can't open a PR and fix this by myself...

**Comment by lukastaegert** [comment]
I'm not sure what assigning `null` to `__proto__` first should accomplish, I would assume we are still messing with the prototype. At least I could not find anything on what you are doing: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

My feeling is that we should just throw a warning or error when an export named `__proto__` is used in an entry point that "this may not work as expected and is not recommended".

**Comment by LongTengDao** [comment]
@lukastaegert

Throw a warning is the bottom line, if the problem can't be completely solved, but I think we can do it:

## condition 1: if `__proto__` is supported in runtime

### condition 1.1: the value `__proto__` want export is primitive but not `null`

The value assignment onto `__proto__` property will be ignore, which is not expected.

If set `__proto__` to null firstly, then the proto of the object will not be `Object.prototype` any more, and **`__proto__` is just a setter at `Object.prototype`**. The following real assignment of expected value will be valid and safe.

### condition 1.2: the value `__proto__` want export is non-primitive or `null`

The value assignment onto `__proto__` property will work, but not as expected. It will make the proto of the object to the value assigning, not really set the value as property `__proto__`'s value.

If set `__proto__` to null firstly... (same as condition 1.1)

## condition 2: `__proto__` is not supported in runtime

Just like the first step not exist, no more side effects.

**Comment by lukastaegert** [comment]
Ah, I see, you are right. Still I do not see it worthwhile enough to pursue from our side as this seems like a weird edge case to me—why would anyone want to call their exports __proto__, considering it is such a special property?—but if someone steps up with a reasonably low-impact PR I would merge it.

**Comment by LongTengDao** [comment]
@lukastaegert I can avoid this in my own projects, so currenctly leave it no-fix is acceptable for me. But a warning is still expected. Of cause, if the trouble to add a warning is same with fix that, we can just leave it, and waiting for someone do that.
