### ISSUE TITLE
Rollup silently deletes output directory

### ISSUE THREAD

**Issue by fronteed** [rollup/rollup#3046]
- Rollup Version: 1.19.4
- Operating System (or Browser): OS X
- Node Version: 8.10.0

### How Do We Reproduce?

1) Create `build` folder and add some files inside (we compile another files without rollup before rollup generates the main .js bundle).

2) Setup `rollup.config.js`:

```js
const commonjs = require('rollup-plugin-commonjs')
const nodeResolve = require('rollup-plugin-node-resolve')

module.exports = {
	input: 'src/index.js',
	output: {
		file: 'build/lib.js',
		format: 'iife',
		strict: false,
	},
	context: 'window',
	plugins: [
		commonjs({
			include: 'node_modules/**',
		}),
		nodeResolve({
			browser: true,
		}),
	],
}
```

3) Start compilation using cli `rollup -c ./rollup.config.js --environment=production`

### Expected Behavior

Rollup shouldn't delete the `build` folder if that folder already exists. We're using execa to launch rollup and other processes and we already have another assets compiled in the build folder before we launch rollup. We're also using `rollup-plugin-serve` on development build to watch and compile the bundle, so we can't build anything after server from `rollup-plugin-serve` is started.  

### Actual Behavior

Rollup deletes the `build` folder before compiling a bundle into `build/lib.js` path. There's no option to switch off this behavior.

**Comment by shellscape** [comment]
Thanks for opening an issue. What's the crux of the issue on this one; that the directory is removed, or that the files in the directory are removed?

**Comment by lukastaegert** [comment]
Also this behaviour surprises as I am quite sure this does NOT happen. Existing files will be overwritten if the names match but unrelated files should never be touched.

**Comment by fronteed** [comment]
> Thanks for opening an issue. What's the crux of the issue on this one; that the directory is removed, or that the files in the directory are removed?
Files in directory are removed.

**Comment by shellscape** [comment]
I was unable to reproduce this behavior with a minimal example, using the rollup repository as a baseline. Here's the steps I took to validate that this could not be reproduced:

1. created a `dummy` directory at the root
1. added `file.js` to the directory
1. added a new `rollup.config.js` file to the root and populated it with:

```js
module.exports = {
	input: 'test/cli/samples/allow-output-prefix/main.js',
	output: {
		file: 'dummy/bundle.js',
		format: 'iife'
	}
};
```

1. executed `node dist/bin/rollup -c ./rollup.config.js --environment=production`
1. observed that `file.js` was still present
1. executed `node dist/bin/rollup -c ./rollup.config.js`
1. observed that `file.js` was still present

At this point it looks like you have other tooling causing an issue, or perhaps an unintended action being taken by a plugin that's being used. At the core of Rollup, it's not deleting or removing other files in the output directory however.

If you can put together a repo that has a minimal reproduction, without the use of third-party plugins or tooling, and can reply with that, we'll be able to look into this further. At this time, we're going to close as cannot reproduce.
