### ISSUE TITLE
This line would change the origin option object

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#3050]
- Rollup Version: 1.19.4
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

```js
const acorn = {};

rollup({
  input: 'main.js',
  acorn,
  experimentalTopLevelAwait: true,
}).then(()=>{
  console.log(acorn.allowAwaitOutsideFunction);// true, then rollup below will work incorrectly
  rollup({
    input: 'main.js',
    acorn,
    experimentalTopLevelAwait: false,
  });
});
```

### Actual Behavior

https://github.com/rollup/rollup/blob/2443783d0b1214ab742373414ed03d4f0f75964f/src/Graph.ts#L171
https://github.com/rollup/rollup/blob/2443783d0b1214ab742373414ed03d4f0f75964f/src/Graph.ts#L178
https://github.com/rollup/rollup/blob/2443783d0b1214ab742373414ed03d4f0f75964f/src/Graph.ts#L179
https://github.com/rollup/rollup/blob/2443783d0b1214ab742373414ed03d4f0f75964f/src/Graph.ts#L180

**Comment by shellscape** [comment]
Thanks for the PR :beer:

Please add a more verbose description to the issue. It's not immediately obvious what you're attempting to resolve. That will also give the associated PR more context.

**Comment by LongTengDao** [comment]
@shellscape 

If `options.experimentalTopLevelAwait` is true, then rollup function will modify `acornOptions.allowAwaitOutsideFunction` to true (line 179), but `acornOptions` is the original `options.acorn` (line 171).

Then the original `options.acorn` object is modified. If user uses same object as option, problem happens.

In next rollup, user uses the same options.acorn object, with options.experimentalTopLevelAwait false, the rollup run as if the experimentalTopLevelAwait is true.

```js
const acorn = { ecmaVersion: 5 };// multi use option object

await rollup({ input: '1.js', acorn, experimentalTopLevelAwait: true });

await rollup({ input: '2.js', acorn, experimentalTopLevelAwait: false });
// wrong processing, because acorn object was modified
```

**Comment by lukastaegert** [comment]
I believe this is resolved now
