### ISSUE TITLE
Usage with Electron

### ISSUE THREAD

**Issue by szwacz** [rollup/rollup#306]
I'm trying to use rollup with [Electron runtime](http://electron.atom.io/). Electron is node.js and browser merged together, so it has native access to modules like `fs`.

What I'm trying to achieve is to use `import` in every case and drop entirely commonjs' `require`.

So for my case I'm trying:
```js
import fs from 'fs';
```
To be transpiled to:
```js
var fs = require('fs');
```

I've tried rollup plugins for npm and commonjs but without luck. Is this possible to do with current version of rollup? Is it worth pursuing?

Thanks!

**Comment by TrySound** [comment]
@szwacz External dependencies will be transpilled to regular require calls
Use plugins to manipulate npm and commonjs stuff
https://github.com/rollup/rollup-plugin-commonjs
https://github.com/rollup/rollup-plugin-npm

**Comment by szwacz** [comment]
Ahhh, you're totally right. I've used `format: 'iife'`, when I flipped this option to `cjs` it started to work.

**Comment by pjebs** [comment]
@szwacz Did you have to configure rollup differently for main and renderer process. (i.e. main process is node.js & renderer is a browser)?

**Comment by szwacz** [comment]
When I was submitting this issue the renderer and main process had very similar capabilities, so I believe I used the same config for both, it might not be the case today.
