### ISSUE TITLE
Error when using circular imports to import current module

### ISSUE THREAD

**Issue by OliverJAsh** [rollup/rollup#3071]
- Rollup Version: the version used by the REPLY—latest version I assume?
- Operating System (or Browser): latest Chrome on latest macOS
- Node Version: N/A (issue reproduced via REPL only)

### How Do We Reproduce?

[REPL](https://rollupjs.org/repl/?version=1.19.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG90aGVyJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZvdGhlciU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2cob3RoZXIuZm9vMSklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyb3RoZXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28xJTIwJTNEJTIwMSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMGZvbzIlMjAlM0QlMjAyJTNCJTVDbiU1Q25pbXBvcnQlMjAqJTIwYXMlMjBvdGhlciUyMGZyb20lMjAlNUMlMjIuJTJGb3RoZXIlNUMlMjIlM0IlNUNuZXhwb3J0JTIwJTdCJTIwb3RoZXIlMjAlN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

No error

### Actual Behavior

```
 RangeError: Maximum call stack size exceeded
```

FWIW [this works in webpack](https://github.com/OliverJAsh/tree-shaking-test/tree/proxy-circular), and is apparently allowed by the spec.

**Comment by lukastaegert** [comment]
Fix at #3077
