### ISSUE TITLE
Tagged Union for OutputChunk | OutputBundle

### ISSUE THREAD

**Issue by askbeka** [rollup/rollup#3079]
### Feature Use Case
When developing a plugin in typescript using generateBundle hook of siganture `options: OutputOptions, bundle: OutputBundle, ..)` where OutputBundle  = OutputChunk | OutputAsset;

in order to check if the type of file it is advised to use `.isAsset` flag. Which is problematic in typescript

Since `OutputChunk` does not have it and implicit conversion of type is required 
```ts
if ((chunkOrAsset as OutputAsset).isAsset) { //...
```

### Feature Proposal
[Tagged Union](https://en.wikipedia.org/wiki/Tagged_union) for the rescue!
Better option would be to provide a tag, say `type`, which will be of types: 
`type = 'asset' | 'chunk'`
which is a common field, anchor or [discriminantor](https://en.wikipedia.org/wiki/Discriminator)

this will make it easier to create pugins using typescript and improve overall the codebase. I have created a PR, which showcases it.

**Comment by lukastaegert** [comment]
This has been changed
