### ISSUE TITLE
Module '"./config"' has no exported member 'app_name'.

### ISSUE THREAD

**Issue by gd4Ark** [rollup/rollup#3090]
### Rediscover
config/index.ts
```ts
export default {
  app_name: 'app name'
}
```
index.ts
```ts
import { app_name } from './config/index'
```
error:
```bash
semantic error TS2305 Module '"./config"' has no exported member 'app_name'.
```
### My question
Current solution:
```ts
export const app_name = 'app_name'
```
What is the problem?

**Comment by shellscape** [comment]
@gd4Ark thanks for opening an issue. It is however a support request.

>  👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Please try one of those two avenues before opening an issue.

**Comment by gd4Ark** [comment]
Thank you for your instructions
