### ISSUE TITLE
Simplify Symbol.toStringTag for module namespaces

### ISSUE THREAD

**Issue by mkubilayk** [rollup/rollup#3097]
There is currently no way for Rollup to generate simple output of the `toStringTag` in module namespaces. It always uses a verbose polyfill. Ideally we should always generate simple output, or make the polyfill optional.

As configuration options are not available in the REPL, I'm posting the sample code here.

```javascript
// main.mjs 

import * as nsA from "./main.mjs";
console.log(nsA);
```

### Expected Behavior / Situation

Produce namespaces that has `Symbol.toStringTag` set and not have the polyfill behavior.

```javascript
// expected bundle.mjs

var nsA = /*#__PURE__*/Object.freeze({
    [Symbol.toStringTag]: 'Module'
});

console.log(nsA);
```

### Actual Behavior / Situation

With `namespaceToStringTag` option enabled, Rollup produces a polyfill for the environments that don't have `Symbol.toStringTag` available. 

```sh
npx rollup \
    --input main.mjs \
    --format esm \
    --namespaceToStringTag \
    --output.file bundle.mjs
```

```javascript
// bundle.mjs

var nsA = {
};
if (typeof Symbol !== 'undefined' && Symbol.toStringTag)
    Object.defineProperty(nsA, Symbol.toStringTag, { value: 'Module' });
else
    Object.defineProperty(nsA, 'toString', { value: function () { return '[object Module]' } });
/*#__PURE__*/Object.freeze(nsA);

console.log(nsA);
```

### Modification Proposal

We can either:
- make `output.namespaceToStringTag` option not produce the polyfill
- introduce a new configuration option that assumes `Symbol.toStringTag` is available

I would be happy to work on either of these proposals or any other approach you propose.

**Comment by lukastaegert** [comment]
Considering the fact that I do not think this is used very often, I agree that this solution definitely has more charm, especially since ES6 compatibility has become widespread. I also see the potential that, should we in the future add an option to e.g. use ES6 code for Rollup's auto-generated bits, this could be added by default (and only removed by the option).

**Comment by robpalme** [comment]
@lukastaegert if I read that correctly, I think you are saying that Rollup output can assume ES6 support, and therefore we can always use the simple output, and maybe in future Rollup could have an option to use ES5 for the auto-generated code if someone really wants it.  Is this correct?

My person view is that if people need ES5 output, they should be using Babel to down-level the code generated by Rollup.

**Comment by lukastaegert** [comment]
Not quite. At the moment, quite a bit care is used in several corners to maintain ES5 compatiblity. I would not get rid of this lightly, especially since there is not yet an easy way in `rollup-plugin-babel` to run it at the end in `renderChunk`.

**Comment by lukastaegert** [comment]
But I am open for this in a future major, and adding an option would work now.

**Comment by lukastaegert** [comment]
By the way if you are looking for important things that might be tackled in a Hackathon, this Babel issue is basically what I am talking about: rollup/rollup-plugin-babel#303
I do not think it is too much work, it just needs someone to implement it.

**Comment by robpalme** [comment]
Ok.  So there is a separate opportunity here: enhancing `rollup-plugin-babel` to perform a post-Rollup transform, to enable Rollup to later output modern code.  I'll see if anyone is interested in that.

For this specific issue `toStringTag`, would you like the proposed new option to be scoped to just this feature (e.g. `output.toStringTagES5: <boolean defaults to true>`), or alternatively. not limit the scope and just have `output.generatedCodeES5: <boolean defaults to true>`?

**Comment by lukastaegert** [comment]
The more I think about this, the more I feel that having an option to control the auto-generated code would be quite an overhead on the Rollup code-base while extending the Babel plugin to be able to transform the generated code would have the benefit that in some situations, people might even transpile down to ES3.

So to sum it up:
* For the issue at hand, I think switching the option to produce ES6 code without polyfill should be ok and enough to close this ticket.
* Besides that, extending the Babel plugin should be the way forward.
