### ISSUE TITLE
Do not create conflicts between files emitted in `generateBundle` for different outputs

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#3098]
- Rollup Version: 1.20.3
- Operating System (or Browser): Any
- Node Version: 12

### How Do We Reproduce?

Taken from https://github.com/rollup/rollup/pull/2999#issuecomment-528589283:
Note that I did not verify this myself, but I do not want this to go unnoticed cc @wessberg

### Expected Behavior
When creating several outputs and emitting files in `generateBundle` using the `fileName` option, the files are unique to each output and there are not conflicts between outputs.

### Actual Behavior
Apparently, files in later outputs cannot be generated with the same name but will throw a name conflict error.

**Comment by wessberg** [comment]
This issue was resolved in https://github.com/rollup/rollup/issues/3174 and released in v1.26.1.

**Comment by lukastaegert** [comment]
Unfortunately not completely. You can still create conflicts via the JS API. But the real fix is around the corner.

**Comment by wessberg** [comment]
For what it's worth, the problem I initially reported which involved using the `emitFile` API went away with v1.26.1. Keep up the good work Lukas, you're awesome! 👍
