### ISSUE TITLE
output of output.format = 'system' has `'use strict';` when output.strict = false

### ISSUE THREAD

**Issue by askbeka** [rollup/rollup#3100]
- Rollup Version: 1.20.3
- Operating System (or Browser): Linux
- Node Version: 10

Not sure fully if it is a bug. But it does not allow me to use modules that require to run in non strict mode to function properly.

### How Do We Reproduce?
Currently it is constant as seen from [this line](https://github.com/rollup/rollup/blob/b006d134794dfb1c487796144c01bb80e15a01c4/src/finalisers/system.ts#L176)

### Expected Behavior
No `'use strict';` added

### Actual Behavior
`'use strict';` is present

**Comment by lukastaegert** [comment]
Rollup is essentially as polyfill of sorts for ES modules, so the assumption is that you are writing code that is valid in an ES module. Thus for all other formats, use strict is added to make sure the behaviour is equivalent.

**Comment by lukastaegert** [comment]
Or to put it differently, modules are always implicitly in strict mode by specification. There is however a flag to disable this.

**Comment by askbeka** [comment]
@lukastaegert thanks. I have used that flag but systemjs output does not respect it. 
I can check if I can workaround it.

**Comment by lukastaegert** [comment]
Sorry, I kinda missed that point 😉. Yes, strict should also work for SystemJS but apparently was forgotten to be implemented. Marking it as a bug.

**Comment by lukastaegert** [comment]
Closed via #3101
