### ISSUE TITLE
1.21.0 includes a breaking change

### ISSUE THREAD

**Issue by yesmeck** [rollup/rollup#3104]
- Rollup Version: 1.21.0
- Operating System (or Browser): Chrome
- Node Version: 12

### How Do We Reproduce?

https://github.com/rollup/rollup/pull/3080 introduced `asset.type` breaks all plugins which generate asset using `asset.isAsset`.

### Expected Behavior

Minor version should backward compatibility。

### Actual Behavior

It's breaks many plugins, like [rollup-plugin-postcss ](https://github.com/egoist/rollup-plugin-postcss/blob/master/src/index.js#L183-L196)

**Comment by lukastaegert** [comment]
I see. Admittedly, these plugins were using an unofficial API, so technically it is only a breaking change in something we never promised to keep compatible; the proper way to emit assets is to use the file emission API, not mutate the bundle object.

I admit though that the file emission API only got powerful enough recently to support arbitrary asset emission, so I guess we will need to add a "fix" to keep supporting this pattern for the 1.x releases, especially considering that important plugins currently depend on it.

**Comment by lukastaegert** [comment]
Fix at #3105

**Comment by slavafomin** [comment]
@lukastaegert thank you for fixing it so quickly. When should we expect the new release (`1.21.1`)?

**Comment by lukastaegert** [comment]
Released now
