### ISSUE TITLE
@types packages should be peerDependencies

### ISSUE THREAD

**Issue by Feiyang1** [rollup/rollup#3108]
### Expected Behavior / Situation
@types packages should be peerDependencies.
I'd like to enforce Node 8 support in my project, but rollup includes @types/node@12 which introduce globals/types that are only available in newer Node versions, e.g. `Promise.prototype.finally`.

### Actual Behavior / Situation
@types packages are the direct dependency of rollup introducing undesirable global types from `@types/node`.

### Modification Proposal
The issue is similar to https://github.com/rollup/rollup/issues/2580
You mentioned that making @types packages devDeps is not an option because rollup reexport some of those types, but you can make them peerDependencies, so the consumer has control over the version of @types packages.

If the proposal sounds reasonable to you, I will create a PR for it.

**Comment by Feiyang1** [comment]
I think long term rollup should not depend on types that define globals, e.g. @types/node, which forces consumers to include types they don't intend to include during compilation.

**Comment by lukastaegert** [comment]
The problem is that making it a peerDependency would force EVERYONE to either install them manually or have warnings during install, which is also undesired. I fear the only reasonable way to handle this that I can think of is try to get rid of this dependency altogether, not sure if this is possible in any way.

**Comment by shellscape** [comment]
We could drop that into `optionalDependencies` but that's a mostly declarative, symbolic move. We certainly wouldn't want to force non-TypeScript users to receive warnings during install.

**Comment by tivac** [comment]
Why is that package needed? As a non-TS user I've never understood it's inclusion.

**Comment by Feiyang1** [comment]
An alternative is make a `@types/rollup` package and do not export types from `rollup` package.
People who want the types can install `@types/rollup` and I can work around the globals issue by not installing it.
It's also a win for non-TS user who then won't be forced to install types.

**Comment by Feiyang1** [comment]
https://github.com/rollup/rollup/pull/3131 solved my problem, but rollup regressed on `1.23.0`

**Comment by lukastaegert** [comment]
Sorry, fix is upcoming

**Comment by lukastaegert** [comment]
Rollup@2 will finally fix this for good: #3395

**Comment by lukastaegert** [comment]
Solved in rollup@2.0.0
