### ISSUE TITLE
Make Quickstart wiki page consistent with other wiki pages

### ISSUE THREAD

**Issue by itsrainingmani** [rollup/rollup#3118]
Documentation Is:

- [ ] Missing
- [x ] Needed
- [x ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In the wiki, every page except the Quickstart page either has content or includes a link to the rollup.js website. The Quickstart page only has the word __test__.
This is inconsistent with the rest of the wiki pages.

### Your Proposal for Changes

Change the content of the Quickstart page to either link to the appropriate [rollup.js page](https://rollupjs.org/guide/en/#quick-start) or include the actual content of the quickstart guide in the wiki page.

**Comment by shellscape** [comment]
Thanks for reporting this. Fixed.
