### ISSUE TITLE
Unexpected Token Error

### ISSUE THREAD

**Issue by frencojobs** [rollup/rollup#3123]
### Summary
Rollup replace does not work absolutely with double quoted tokens and works fine only when using single quoted tokens.

### Specs

- Rollup Version: ^1.21.4
- Operating System (or Browser): Chrome LTS on Ubuntu 19.04
- Node Version: 10.15.2

### How Do We Reproduce?

I am currently using it to build the production version of a npm package project, and to be able to work easily and efficiently also in development, I used `rollup-plugin-replace` to replace the word `ENV` with production, 

### Expected Behavior
To replace the word `ENV` with the word production.

### Actual Behavior
Works perfect only the word is in single quotes `'ENV'` and errors when using double quotes `"ENV"`

```bash
Error: Unexpected token
    at error (/www/node_modules/rollup/dist/rollup.js:10151:30)
    at Module.error (/www/node_modules/rollup/dist/rollup.js:14137:9)
    at tryParse (/www/node_modules/rollup/dist/rollup.js:14049:16)
    at Module.setSource (/www/node_modules/rollup/dist/rollup.js:14364:33)
    at Promise.resolve.catch.then.then.then (/www/node_modules/rollup/dist/rollup.js:17179:20)

```

**Comment by shellscape** [comment]
@frencojobs please see the issue template comments - a reproduction is required for bug reports.

**Comment by lukastaegert** [comment]
Also this is obviously an issue for rollup-plugin-replace and not rollup core

**Comment by frencojobs** [comment]
Wrong repo I guess, very sorry that I thought the bug was from rollup because of the error message. The bug actually is from rollup-plugin-replace.
