### ISSUE TITLE
treeshake incorrectly removes empty for..of and for await..of loops

### ISSUE THREAD

**Issue by toolbuilder** [rollup/rollup#3126]
Awesome tool! Thanks!

- Rollup Version: 1.21.4
- Operating System (or Browser): Ubuntu 16.04.6 LTS, also Firefox 69 and Electron
- Node Version: 10.16.0

### How Do We Reproduce?

Replicated in [REPL](https://rollupjs.org/repl/?version=1.21.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYXdhaXRhYmxlJTIwJTNEJTIwYXN5bmMlMjAoaXRlcmFibGUpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rmb3IlMjBhd2FpdCUyMChjb25zdCUyMHZhbHVlJTIwb2YlMjBpdGVyYWJsZSklMjAlN0IlNUNuJTVDdCU3RCU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBpcyUyMGVxdWl2YWxlbnQlMjB0byUyMHRoZSUyMGFib3ZlJTIwJ2F3YWl0YWJsZSclMjBmdW5jdGlvbi4lNUNuZXhwb3J0JTIwY29uc3QlMjBlcXVpdmFsZW50JTIwJTNEJTIwYXN5bmMlMjAoaXRlcmFibGUpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rjb25zdCUyMGl0ZXJhdG9yJTIwJTNEJTIwaXRlcmFibGUlNUJTeW1ib2wuYXN5bmNJdGVyYXRvciU1RCgpJTVDbiUyMCUyMGxldCUyMCU3QiUyMGRvbmUlMjAlN0QlMjAlM0QlMjBhd2FpdCUyMGl0ZXJhdG9yLm5leHQoKSU1Q24lMjAlMjB3aGlsZSUyMCghZG9uZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwKCU3QiUyMGRvbmUlMjAlN0QlMjAlM0QlMjBhd2FpdCUyMGl0ZXJhdG9yLm5leHQoKSklNUNuJTIwJTIwJTdEJTVDbiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwaXRlcmF0ZSUyMCUzRCUyMGl0ZXJhYmxlJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rmb3IlMjAoY29uc3QlMjB2YWx1ZSUyMG9mJTIwaXRlcmFibGUpJTIwJTdCJTVDbiU1Q3QlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyYW1kJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

The empty loops for sync and async for..of iteration should not be removed. They call iterator.next() multiple times, and are doing work.

### Actual Behavior

The empty loops are removed. As the REPL example shows, manually doing the iteration with a while loop and iterator.next() is a workaround.

I'm using code like this to iterate over chained async generators. For async code, it is the generators that do the work (HTTP queries, writing to DB, etc). I don't need to see the resolved values.

```javascript
export const awaitable = async (iterable) => {
   // This loop is removed, but it calls iterator.next(), which can have side-effects
  for await (const value of iterable) {
  }
}
```

**Comment by lukastaegert** [comment]
I con confirm this. I believe we should go for a quick fix first that always retains `for...of` loops.

Later, a more sophisitcated solution could track `Symbol.iterator` and `Symbol.asyncIterator` properties and check the side-effects of their return values' `next` function. Such a logic should also work for spread operators and manual iteration as well as interact properly with generators. It should also be tested for side-effects when passed to a function such as `Array.from`.

**Comment by lukastaegert** [comment]
Created #3127 as a follow-up
