### ISSUE TITLE
Support for private field declarations?

### ISSUE THREAD

**Issue by greggman** [rollup/rollup#3128]
- Rollup Version: 1.21.4
- Operating System (or Browser): N/A
- Node Version: 12.6.0

### How Do We Reproduce?

rollup this code

```
class Foo {
  #p;
  constructor(v) {
    this.#p = v;
  }
  getV() {
    return this.#p;
  }
};

const a = new Foo('hello');
const b = new Foo('world');
console.log(a.getV(), b.getV());
```

[repl](https://rollupjs.org/repl/?version=1.21.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiU1Q3QlMjNwJTNCJTVDbiU1Q3Rjb25zdHJ1Y3Rvcih2KSUyMCU3QiU1Q24lNUN0JTVDdHRoaXMuJTIzcCUyMCUzRCUyMHYlM0IlNUNuJTVDdCU3RCU1Q24lMjAlMjBnZXRWKCklMjAlN0IlNUNuJTVDdCU1Q3RyZXR1cm4lMjB0aGlzLiUyM3AlM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbmNvbnN0JTIwYSUyMCUzRCUyMG5ldyUyMEZvbygnaGVsbG8nKSUzQiU1Q25jb25zdCUyMGIlMjAlM0QlMjBuZXclMjBGb28oJ3dvcmxkJyklM0IlNUNuY29uc29sZS5sb2coYS5nZXRWKCklMkMlMjBiLmdldFYoKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior

It rolls up

### Actual Behavior

It gets a syntax error

Note: the code snippet above works in Chrome [https://jsfiddle.net/greggman/z5w1pd9m/](https://jsfiddle.net/greggman/z5w1pd9m/) and in node 12

```
$ node
Welcome to Node.js v12.6.0.
Type ".help" for more information.
> class Foo {
...   #p;
...   constructor(v) {
.....     this.#p = v;
.....   }
...   getV() {
.....     return this.#p;
.....   }
... };
undefined
> 
> const a = new Foo('hello');
undefined
> const b = new Foo('world');
undefined
> console.log(a.getV(), b.getV());
hello world
undefined
> 
```

**Comment by keithamus** [comment]
You can use the [acornInjectPlugins](https://rollupjs.org/guide/en/#acorninjectplugins) option coupled with the [acorn private class elements](https://github.com/acornjs/acorn-private-class-elements) plugin to handle this:


```js
import acornPrivateFields from 'acorn-private-class-elements'
export default {
    // … other options …
    acornInjectPlugins: [
        acornPrivateFields()
    ]
};
```

FWIW Private Fields are still a TC39 Stage 3 proposal and are not standardised ECMAScript (yet).

**Comment by greggman** [comment]
Oh, I thought the Chromium team had a policy not to ship any unapproved JavaScript features unless they were behind a flag (--experimental-javascript). Since they shipped private class fields not behind a flag in v74 I assumed that must mean the feature had passed some threshold of "approved" otherwise it would still be behind the flag

**Comment by lukastaegert** [comment]
I believe support in a major browser is a prerequisite for a Stage 3 feature to become Stage 4.

**Comment by shellscape** [comment]
Closing this one as resolved.
