### ISSUE TITLE
sub folder in external pkg is not treated as external

### ISSUE THREAD

**Issue by JounQin** [rollup/rollup#3129]
- Rollup Version: 1.21.4
- Operating System (or Browser): macOS Mojave
- Node Version: v12.10.0

### How Do We Reproduce?

https://github.com/rx-ts/eslint-mdx/blob/master/packages/eslint-plugin-mdx/src/rules/no-unescaped-entities.ts#L5

https://github.com/rx-ts/eslint-mdx/blob/master/package.json#L14

`eslint-plugin-react` has been marked as external automatically, but if we remove `eslint-plugin-react/lib/rules/no-unescaped-entities` from `externals`, it will not be treated as external automatically.

### Expected Behavior

Treat sub folder from `external` as `external` automatically when targetting `cjs` or `esm` format, or add an option to do it.

### Actual Behavior

As title and description above.

**Comment by lukastaegert** [comment]
The usual way to solve this is to make `external` a function and use something like `id.startsWith(...)`.

**Comment by JounQin** [comment]
Wow, I just didn't know `external` could be a function previously, thanks for your reply! Then I think this issue can be closed.
