### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by tborychowski** [rollup/rollup#313]
I tried to follow your [wikis for the CLI usage](https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file), but that doesn't work for me...
If the config is an ES6 module itselt (e.g. contains `import`) - the current version of node does not support that and it will fail:
```sh
rollup.js:1
(function (exports, require, module, __filename, __dirname) { import babel from 'rollup-plugin-babel';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

Can you provide an example that works (out of the box preferably)?

**Comment by TrySound** [comment]
@tborychowski Just use regular commonjs
```js
var babel = require('rollup-plugin-babel');
```

**Comment by tborychowski** [comment]
Sorry, my bad: I named the config file `rollup.js` so when I run `rollup -c` it was actually executing the config not the `rollup` CLI. 
It works now even with `import`.
Thanks!
