### ISSUE TITLE
CJS build with external react

### ISSUE THREAD

**Issue by larafale** [rollup/rollup#3130]
Hello guys, been pulling my hairs for 2 days now, please tell me what I'm doing wrong ?
All i want is to export a simple react component to be consumed by other react projects.

The problem I have is when i rollup a `cjs` build, even though `react` is set as external, when it comes to importing relative sub module (`import Foo from './bundle/foo'`), I still get `React` in the build (only for sub module, main module seems to work and use `React$1`), so when I use the build in another project (`nextjs` for exemple), I get a `React not found error`.

- Rollup Version:

```
"devDependencies": {
  "@babel/cli": "^7.6.0",
  "@babel/core": "^7.6.0",
  "@babel/preset-env": "^7.6.0",
  "@babel/preset-react": "^7.0.0",
  "react": "^16.9.0",
  "react-dom": "^16.9.0",
  "rollup": "^1.20.3",
  "rollup-plugin-babel": "^4.3.3",
  "rollup-plugin-commonjs": "^10.1.0",
  "rollup-plugin-node-resolve": "^5.2.0"
}
```

- Operating System (or Browser):

Osx

- Node Version:

v10.8.0

### How Do We Reproduce?

- Clone this repo https://github.com/larafale/rollup
- yarn install
- yarn run build

### Source

`src/index.js` :
```
import React from 'react'
import Foo from './bundle/foo'

export default () => (<div>
  <h1>hello</h1>
  <Foo />
</div>)
```

`src/bundle/foo.js` :
```
export default ({}) => {
  return (<span>foo</span>)
}
```

`rollup.config.js` : 
```
export default [
  {
    input: 'src/index.js',
    plugins: [
      babel(),
      resolve(),
      commonjs(),
    ],
    external: [ 'react' ],
    output: [
      {
        file: 'dist/index.cjs.js',
        format: 'cjs',
        name: 'MyLib',
        exports: 'named',
        globals: { react: 'React' }
      }
    ]
  }
]
```

### actual CJS build

`Foo` uses `React` and not `React$1`, so I get a `ReferenceError: React is not defined` when used in a project.

```
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React$1 = _interopDefault(require('react'));

function _objectDestructuringEmpty(obj) {
  if (obj == null) throw new TypeError("Cannot destructure undefined");
}

var Foo = (function (_ref) {
  _objectDestructuringEmpty(_ref);

  return React.createElement("span", null, "foo");
});

var index = (function () {
  return React$1.createElement("div", null, React$1.createElement("h1", null, "hello"), React$1.createElement(Foo, null));
});

exports.default = index;
```

### Expected Behavior

I want my `cjs` build to work, what am I doing wrong ?
Thanks

**Comment by TrySound** [comment]
you missed `import React from 'react';` in src/bundle/foo.js. Rollup considered it as global variable usage and did not touched it but instead renamed React in import statement to fix conflict.

**Comment by larafale** [comment]
can I marry you ? second time you've got my back, thanks a lot Bogdan !

**Comment by larafale** [comment]
so I need to include `import React from 'react'` in all my files right ?

**Comment by TrySound** [comment]
Yes, babel plugin does not add import automatically. At least for now. So you should import react in every module where jsx is used.

**Comment by yozi-developer** [comment]
Now babel do it automatically
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

```javascript
// If you are using @babel/preset-react
{
  "presets": [
    ["@babel/preset-react", {
      "runtime": "automatic"
    }]
  ]
}

```

**Comment by abhic91** [comment]
hey @TrySound, @yozi-developer . I am setting `"jsx": "react-jsx",` in `tsconfig.json`. Doing this creates a bundle with React. 

If I set `"jsx": "react",` and do `import React from 'react'`, I don't see React bundled into the output. How do I not add React into the bundle while using `"jsx": "react-jsx",`
