### ISSUE TITLE
Should preserveModules still apply Object.freeze() to import * from?

### ISSUE THREAD

**Issue by daleyjem** [rollup/rollup#3138]
When creating a single file bundle, and `Object.freeze` is applied to `import * from...` syntax, the imported namespace appears in the browser as type `Object`.

When I use the `preserveModules` option, `Object.freeze` is not applied, and the imported namespace appears in the browser as type `Module`. This appears to cause breakage in my app.

Is this the intended behavior, or a bug?

**Comment by lukastaegert** [comment]
Note: Please use the issue template! It is really little overhead but helps us structure and manage issues.

As for your question, not sure what you mean by type, but if you are referring to the string representation, the correct one for namespaces is `[object Module]`, not `[object Object]`. When bundling, Rollup by default does not add any special code to fix this as not too many people rely on this. There is however the [output.namespaceToStringTag](https://rollupjs.org/guide/en/#outputnamespacetostringtag) option to fix exactly that.

**Comment by lukastaegert** [comment]
This has however nothing to do with the application of `Object.freeze`.

**Comment by daleyjem** [comment]
Sorry... didn't see a template for the "Support, Help, and Advice" category.
