### ISSUE TITLE
Rollup issue whilst reading from /tmp/test.ts

### ISSUE THREAD

**Issue by theshumanator** [rollup/rollup#3157]
- Rollup Version: 1.23.1
- Operating System (or Browser): Mac OSX 10.14.6 (also on AWS Lambda)
- Node Version: v10.15.3

### How Do We Reproduce?
1. Create a ts file in /tmp/ say test.ts with `const x: string = "something"`
2. Sample compiler using rollup and the rollup typescript plugin: https://gist.github.com/theshumanator/03c09dcafd87cd8b5a04146c2b1a995a#file-test-compiler-ts

3. Run the above and you'll get the error:
`Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

### Expected Behavior
Compile and generate the js and js.map files.

### Actual Behavior
Error from rollup: `Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

If i try the above with write to the same directory I'm wokring on i.e. ./test.ts, it works fine. I've noticed the problem seems when it comes to compiling /tmp/test.ts.

There are no permission issues reading/writing to /tmp. I verified by doing the following:
`    const code = 'const x: string = "something"';`
`     await writeFileSync('/tmp/test.ts', code);`
`    const readFile = await readFileSync('/tmp/test.ts')`
`    console.log(readFile.toString())`

**Comment by lukastaegert** [comment]
This error means your TypeScript plugin is not triggering. Which is to be expected as you configure your plugin with `include: '**/*.{js,ts}'`. This includes all files below the current working directory and excludes everything else. I assume your `tmp` folder is not below the current working directory. You should also include your `tmp` folder.

**Comment by theshumanator** [comment]
Ahh I assumed it was a normal wild card. Thanks a lot. It works now.
