### ISSUE TITLE
using require() instead of import

### ISSUE THREAD

**Issue by ritz078** [rollup/rollup#316]
Hi,

I am creating a custom build which contains code like at the top of the file.

```js
if    (build.EMOJI)    var Emoji    = require('./modules/emoticons/emoji.es6');
if    (build.SMILEY)   var Smiley   = require('./modules/emoticons/smiley.es6');
if    (build.LINK)     var Url      = require('./modules/url.es6');
```

I can't use `import` here as according to spec `import` statements should be at the top of the file and also babel-eslint gives an error so I can only use `require`. Is there any way to bundle this ?

**Comment by eventualbuddha** [comment]
Just import them all and use something like https://github.com/rollup/rollup-plugin-replace to change build settings. I believe rollup will (or soon will) detect unused conditional branches and remove them, making some imports unused and therefore excluded.

**Comment by ritz078** [comment]
It doesn't do that. rollup-plugin-replace just replaces the string with its value. So even if i use uglifyjs to remove dead code , the imported code will remain.

**Comment by TrySound** [comment]
@ritz078 commonjs require is not about rollup. Use browserify instead.

**Comment by eventualbuddha** [comment]
@ritz078 @TrySound here's a demo repo showing how to do this: https://github.com/eventualbuddha/rollup-316

**Comment by Victorystick** [comment]
@eventualbuddha Nice!

**Comment by ritz078** [comment]
@eventualbuddha Thanks for the example. I found that it doesn't work if you use [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel) v1.x

**Comment by eventualbuddha** [comment]
I'm curious to know what's going on. Can you fork my example repo to show
how it's not working for you?

**Comment by ritz078** [comment]
Here it is https://github.com/ritz078/rollup-316

**Comment by Luchillo** [comment]
What if i want to just require conditionally? like this was in webpack, how to do now with Rollup?

```js
if (ENV === 'prod') {
  // Production


} else {
  // Development

  Error['stackTraceLimit'] = Infinity;

  require('zone.js/dist/long-stack-trace-zone');
}
```

**Comment by edoardocavazza** [comment]
@ritz078 Have you found a solution to fix tree shaking using rollup-plugin-babel?

**Comment by foisonocean** [comment]
+1

**Comment by TrySound** [comment]
@edoardocavazza Did you disable modules conversion in your babel config?

**Comment by foisonocean** [comment]
@TrySound 
I use `babel-preset-es2015-rollup`, but it still doesn't work

**Comment by TrySound** [comment]
Use babel-preset-es2015 and pass `modules: false` option there.

**Comment by edoardocavazza** [comment]
@TrySound Nope, I achieve the conditional import of a module importing all my modules and removing the unwanted using `rollup-plugin-replace` and `process.env`. But it is not a real solution :(

**Comment by TrySound** [comment]
@edoardocavazza This is reasonable restriction for module system. You may always swap module in rollup config. Resolve plugins are quite simple.

**Comment by foisonocean** [comment]
@TrySound Is there any difference between `babel-preset-es2015` and `babel-preset-es2015-rollup`? I thought `babel-preset-es2015-rollup` has already set `modules: false`

**Comment by TrySound** [comment]
Hm.. just adds also external helpers plugin. Okay. Use rollup preset.
What exactly does not tree shake?

**Comment by foisonocean** [comment]
@TrySound I guess this is because I want to conditional import 3rd module from npm, which is written by commonjs. I use `rollup-plugin-node-resolve` and `rollup-plugin-commonjs`, it seems tree shake broken when I import a commonjs module.

**Comment by TrySound** [comment]
@foisonocean It isn't broken. It just does not work because commonjs is dynamic and unpredictable. That's why es2015 modules exists.

**Comment by foisonocean** [comment]
@TrySound Is any way to conditional import a commonjs module?

**Comment by TrySound** [comment]
@foisonocean Yes, as I said, via plugin api
```js
{
  resolveId(importee, importer) {
    return newImportee.
  }
}
```

**Comment by foisonocean** [comment]
@TrySound 
Thanks a lot.
By the way, what should I return in `resolveId` if I just don't want import this module when `process.env.NODE_ENV === 'production'`?
`return false` works but it cause a warning: `'default' is imported from external module 'xxx' but never used`

**Comment by TrySound** [comment]
Null

**Comment by foisonocean** [comment]
@TrySound Return `null`? It doesn't work, [plugin doc](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins) says return `null` or `undefined` is the default behavior.

**Comment by TrySound** [comment]
Yep. If you want to change path you pass something. If not you just skip it with null value.

**Comment by foisonocean** [comment]
@TrySound 
Sorry for my English, I think you don't understand me.
This is what I want to do with commonjs:
```javascript
  if (ENV === 'production') {
    const obj = require('aCommonJSModuleFromNPM')
    // do something with obj
  }
```
When `ENV` is not equal to `production`, I don't want to import any module.
`resolveId` can change the path of a module, can it just skip import the module?

**Comment by TrySound** [comment]
Then you may return path to any empty module.
