### ISSUE TITLE
Try/catch not tree-shaken if containing empty statement

### ISSUE THREAD

**Issue by stephanedr** [rollup/rollup#3161]
- Rollup Version: 1.24.0
- Operating System (or Browser): Linux
- Node Version: 10.16.3

### How Do We Reproduce?

With tryCatchDeoptimization=false.
```
try {
    ;
}
catch (e) {
}
```
This code is generated after plugin stripping code.

### Expected Behavior
Completely removed.

### Actual Behavior
Generates:
```
try {
}
catch (e) {
}
```
Workaround: run rollup a 2nd time to remove it.

**Comment by lukastaegert** [comment]
try-statements are always completely deoptimized. If you want tree-shaking inside try-statements such as removing an empty statement, that you need to set the `treeshake.tryStatementDeoptimization: false` flag

**Comment by lukastaegert** [comment]
But admittedly, the empty statement should actually be preserved...

**Comment by lukastaegert** [comment]
Oh sorry, I did not read properly, you already used the flag

**Comment by lukastaegert** [comment]
Good point, the logic was slightly tailored towards the tryCatchDeoptimization: true case. Now the false case will properly look for side-effects in #3166.
