### ISSUE TITLE
Last empty statements of case clauses are tree-shaken, but the lines are not removed.

### ISSUE THREAD

**Issue by stephanedr** [rollup/rollup#3162]
- Rollup Version: 1.24.0
- Operating System (or Browser): Linux
- Node Version: 10.16.3

### How Do We Reproduce?

```
switch (a) {
    case 0:
        console.log();
        break;
    case 1:
        ;
    default:
        ;
}
```

### Expected Behavior
```
switch (a) {
    case 0:
        console.log();
        break;
    case 1:
    default:
}
```

### Actual Behavior
```
switch (a) {
    case 0:
        console.log();
        break;
    case 1:

    default:

}
```

**Comment by lukastaegert** [comment]
This has been a long-standing issue, but with some recent improvements in our rendering helpers, it was actually not too difficult to fix in #3166.
