### ISSUE TITLE
Try/catch structure should be tree-shaken when try block is empty

### ISSUE THREAD

**Issue by stephanedr** [rollup/rollup#3163]
- Rollup Version: 1.24.0
- Operating System (or Browser): Linux
- Node Version: 10.16.3

### How Do We Reproduce?

With `tryCatchDeoptimization=false`.
```
try {
}
catch (e) {
    console.log();
}
```

### Expected Behavior
Completely removed, as no errors can be thrown (should also be removed with `tryCatchDeoptimization=true`).

Note that if a `finally` block exists, it must be preserved (without the `finally` keyword).

### Actual Behavior
```
try {
}
catch (e) {
    console.log();
}
```

**Comment by lukastaegert** [comment]
Good point, the logic was slightly tailored towards the `tryCatchDeoptimization: true`  case. Now the `false` case will properly look for side-effects in #3166.
