### ISSUE TITLE
amd file extension

### ISSUE THREAD

**Issue by kekcuuuk** [rollup/rollup#3171]
Hello! At the moment I am working on writing widgets for amoCRM CRM system. In their work, they use RequireJS to asynchronously load new scripts. My problem is that Rollup automatically cuts the ".js" file extension. The fact is, I can’t change the RequireJS configuration file. As a result, it turns out that my modules are simply not found and are not loaded. What to do in this case? Could you make trimming file extensions optional?

https://github.com/rollup/rollup/issues/1466

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).
