### ISSUE TITLE
Incorrect tree-shaking with switch + default

### ISSUE THREAD

**Issue by jbt** [rollup/rollup#3177]
- Rollup Version: 1.25
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

The following code gets aggressively tree-shaken and all the functional parts get removed:

```js
var bar;
switch (foo) {
	default:
		bar = 1;
}

console.log(bar)
```

[REPL version](https://rollupjs.org/repl/?version=1.25.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMGJhciUzQiU1Q25zd2l0Y2glMjAoZm9vKSUyMCU3QiU1Q24lNUN0ZGVmYXVsdCUzQSU1Q24lNUN0JTVDdGJhciUyMCUzRCUyMDElM0IlNUNuJTdEJTVDbiU1Q25jb25zb2xlLmxvZyhiYXIpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

Output code should be pretty much the same as input code

### Actual Behavior

Pretty much everything important gets accidentally removed:

```js
'use strict';

switch (foo) {
	}
```

This is a reduced case of a bug that's causing ReactDOM to break in 1.25 (it's fine with 1.23, and was broken in 1.24 due to #3168) - the functional parts of `commitAttachRef` get removed: [Reduced REPL version](https://rollupjs.org/repl/?version=1.25.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMEhvc3RDb21wb25lbnQlMjAlM0QlMjA1JTNCJTVDbnZhciUyMFNjb3BlQ29tcG9uZW50JTIwJTNEJTIwMjElM0IlNUNuJTVDbmZ1bmN0aW9uJTIwZ2V0UHVibGljSW5zdGFuY2UoaW5zdGFuY2UpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMGluc3RhbmNlJTNCJTVDbiU3RCU1Q25mdW5jdGlvbiUyMGNvbW1pdEF0dGFjaFJlZihmaW5pc2hlZFdvcmspJTIwJTdCJTVDbiUyMCUyMHZhciUyMHJlZiUyMCUzRCUyMGZpbmlzaGVkV29yay5yZWYlM0IlNUNuJTVDbiUyMCUyMGlmJTIwKHJlZiUyMCElM0QlM0QlMjBudWxsKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBpbnN0YW5jZSUyMCUzRCUyMGZpbmlzaGVkV29yay5zdGF0ZU5vZGUlM0IlNUNuJTIwJTIwJTIwJTIwdmFyJTIwaW5zdGFuY2VUb1VzZSUzQiU1Q24lNUNuJTIwJTIwJTIwJTIwc3dpdGNoJTIwKGZpbmlzaGVkV29yay50YWcpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGNhc2UlMjBIb3N0Q29tcG9uZW50JTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGluc3RhbmNlVG9Vc2UlMjAlM0QlMjBnZXRQdWJsaWNJbnN0YW5jZShpbnN0YW5jZSklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYnJlYWslM0IlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaW5zdGFuY2VUb1VzZSUyMCUzRCUyMGluc3RhbmNlJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyMCUyRiUyRiUyME1vdmVkJTIwb3V0c2lkZSUyMHRvJTIwZW5zdXJlJTIwRENFJTIwd29ya3MlMjB3aXRoJTIwdGhpcyUyMGZsYWclNUNuJTVDbiU1Q24lMjAlMjAlMjAlMjBpZiUyMChlbmFibGVTY29wZUFQSSUyMCUyNiUyNiUyMGZpbmlzaGVkV29yay50YWclMjAlM0QlM0QlM0QlMjBTY29wZUNvbXBvbmVudCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwaW5zdGFuY2VUb1VzZSUyMCUzRCUyMGluc3RhbmNlLm1ldGhvZHMlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMjAlMjBpZiUyMCh0eXBlb2YlMjByZWYlMjAlM0QlM0QlM0QlMjAnZnVuY3Rpb24nKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjByZWYoaW5zdGFuY2VUb1VzZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTIwZWxzZSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoIXJlZi5oYXNPd25Qcm9wZXJ0eSgnY3VycmVudCcpKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB3YXJuaW5nV2l0aG91dFN0YWNrJTI0MShmYWxzZSUyQyUyMCdVbmV4cGVjdGVkJTIwcmVmJTIwb2JqZWN0JTIwcHJvdmlkZWQlMjBmb3IlMjAlMjVzLiUyMCclMjAlMkIlMjAnVXNlJTIwZWl0aGVyJTIwYSUyMHJlZi1zZXR0ZXIlMjBmdW5jdGlvbiUyMG9yJTIwUmVhY3QuY3JlYXRlUmVmKCkuJTI1cyclMkMlMjBnZXRDb21wb25lbnROYW1lKGZpbmlzaGVkV29yay50eXBlKSUyQyUyMGdldFN0YWNrQnlGaWJlckluRGV2QW5kUHJvZChmaW5pc2hlZFdvcmspKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMjAlMjAlMjAlMjByZWYuY3VycmVudCUyMCUzRCUyMGluc3RhbmNlVG9Vc2UlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbiU1Q25jb21taXRBdHRhY2hSZWYobmV4dEVmZmVjdCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==). It looks like 1.24 actually treats this behaviour fine - [REPL](https://rollupjs.org/repl/?version=1.24.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMEhvc3RDb21wb25lbnQlMjAlM0QlMjA1JTNCJTVDbnZhciUyMFNjb3BlQ29tcG9uZW50JTIwJTNEJTIwMjElM0IlNUNuJTVDbmZ1bmN0aW9uJTIwZ2V0UHVibGljSW5zdGFuY2UoaW5zdGFuY2UpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMGluc3RhbmNlJTNCJTVDbiU3RCU1Q25mdW5jdGlvbiUyMGNvbW1pdEF0dGFjaFJlZihmaW5pc2hlZFdvcmspJTIwJTdCJTVDbiUyMCUyMHZhciUyMHJlZiUyMCUzRCUyMGZpbmlzaGVkV29yay5yZWYlM0IlNUNuJTVDbiUyMCUyMGlmJTIwKHJlZiUyMCElM0QlM0QlMjBudWxsKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBpbnN0YW5jZSUyMCUzRCUyMGZpbmlzaGVkV29yay5zdGF0ZU5vZGUlM0IlNUNuJTIwJTIwJTIwJTIwdmFyJTIwaW5zdGFuY2VUb1VzZSUzQiU1Q24lNUNuJTIwJTIwJTIwJTIwc3dpdGNoJTIwKGZpbmlzaGVkV29yay50YWcpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGNhc2UlMjBIb3N0Q29tcG9uZW50JTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGluc3RhbmNlVG9Vc2UlMjAlM0QlMjBnZXRQdWJsaWNJbnN0YW5jZShpbnN0YW5jZSklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYnJlYWslM0IlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaW5zdGFuY2VUb1VzZSUyMCUzRCUyMGluc3RhbmNlJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyMCUyRiUyRiUyME1vdmVkJTIwb3V0c2lkZSUyMHRvJTIwZW5zdXJlJTIwRENFJTIwd29ya3MlMjB3aXRoJTIwdGhpcyUyMGZsYWclNUNuJTVDbiU1Q24lMjAlMjAlMjAlMjBpZiUyMChlbmFibGVTY29wZUFQSSUyMCUyNiUyNiUyMGZpbmlzaGVkV29yay50YWclMjAlM0QlM0QlM0QlMjBTY29wZUNvbXBvbmVudCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwaW5zdGFuY2VUb1VzZSUyMCUzRCUyMGluc3RhbmNlLm1ldGhvZHMlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMjAlMjBpZiUyMCh0eXBlb2YlMjByZWYlMjAlM0QlM0QlM0QlMjAnZnVuY3Rpb24nKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjByZWYoaW5zdGFuY2VUb1VzZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTIwZWxzZSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoIXJlZi5oYXNPd25Qcm9wZXJ0eSgnY3VycmVudCcpKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB3YXJuaW5nV2l0aG91dFN0YWNrJTI0MShmYWxzZSUyQyUyMCdVbmV4cGVjdGVkJTIwcmVmJTIwb2JqZWN0JTIwcHJvdmlkZWQlMjBmb3IlMjAlMjVzLiUyMCclMjAlMkIlMjAnVXNlJTIwZWl0aGVyJTIwYSUyMHJlZi1zZXR0ZXIlMjBmdW5jdGlvbiUyMG9yJTIwUmVhY3QuY3JlYXRlUmVmKCkuJTI1cyclMkMlMjBnZXRDb21wb25lbnROYW1lKGZpbmlzaGVkV29yay50eXBlKSUyQyUyMGdldFN0YWNrQnlGaWJlckluRGV2QW5kUHJvZChmaW5pc2hlZFdvcmspKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMjAlMjAlMjAlMjByZWYuY3VycmVudCUyMCUzRCUyMGluc3RhbmNlVG9Vc2UlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbiU1Q25jb21taXRBdHRhY2hSZWYobmV4dEVmZmVjdCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) - so perhaps this bug arose out of the fix for #3168.

**Comment by lukastaegert** [comment]
Thanks a lot for spotting this. The issue was a simple oversight with weird effects that only showed in very particular situations. To be precise, the switch statement is included due to a side-effect in the condition (in this case because it is an unknown global) at a point where the cases themselves have no side-effect (because the console.log is not yet included) resulting in no code after the switch statement being included, preventing the side-effect (in fact, the statement was treated like a throw). Fix at #3178
