### ISSUE TITLE
Consider supporting class tree generation for exposing internal classes

### ISSUE THREAD

**Issue by marcospassos** [rollup/rollup#318]
Hey guys! This project is just awesome, thanks for sharing it with us.

I believe would be a great addition the option of generating modules that exposes not only the entry point, but all the internal classes. It allows using any class of the package from external modules. 

Example:

Given a module `Acme` which contains a class named `Foo`, located under `Utils/`:
```js
export default class Foo {
  bar() {
    return 'baz';
  }
}
```
And a class named `Bar`, located under `/`:

```js
import Foo from 'Utils/Foo'

export default class Bar {
  constructor() {
    this.foo = new Foo();
  }
}
```
I expect the output:
```js
(function () {
  class Bar {
  //..
  }

  this.Bar = Bar;

  class Foo {
  //..
  }

  this.Utils = this.Utils || {};
  this.Utils.Foo = Foo;
}).call(this.Acme = {});

// From another library
let foo = new Acme.Utils.Foo();
let bar = foo.bar();

if (foo instanceof Acme.Bar) {
   console.log('Bar!');
}
```

**Comment by eventualbuddha** [comment]
In general I'd say that exposing all internal classes, or any implementation details, is a bad practice as it handicaps your ability to refactor without major version bumps. If such a feature existed you'd have to have some way of marking things as "public" to avoid that problem, but then you're just recreating module semantics in a non-standard way.

What is the use case for this? Attempting to port a Google Closure-style project to ES6 modules? I can say pretty confidently that this option wouldn't exist in core, but would be fine as a plugin of you can figure out a way to write it.

**Comment by eventualbuddha** [comment]
And of course if you decide to try a plugin and run into problems any of us would be happy to help. Check the wiki for some docs on writing plugins.

**Comment by marcospassos** [comment]
@eventualbuddha It's not a bad practice.

```js
class Game {
   addPlayer(player) {
   }
}

class Player {
}
```
External module:
```js
game.addPlayer(new Player('Marcos'));
```

How can I expose the class `Player`? It is possible to encapsulate the creation of the player in the `addPlayer` method, but it is not always enough.

**Comment by eventualbuddha** [comment]
@marcospassos It's not a bad practice to expose *some* classes, but not *all* classes. Perhaps we're talking past each other a bit. If I had a package with a class `Game` and a class `Player`, I might organize it like so:

```js
// Game.js
export default class Game {
  addPlayer(player) {
  }
}

// Player.js
export default class Player {
}

// index.js
import Player from './Player';
import Game from './Game';

export { Player, Game };
```

Then you could build your package using the `umd` format like so:

```js
rollup({ entry: 'index.js' }).then(bundle =>
  bundle.write({ dest: 'acme.js', format: 'umd', moduleName: 'Acme' }));

You could then use `acme.js` like you described:

```js
const game = new Acme.Game();
game.addPlayer(new Acme.Player());
```

**Comment by marcospassos** [comment]
Yes, I expressed myself wrong, my intention is to expose only a few classes and your suggestion does the trick.

Thanks a lot!
