### ISSUE TITLE
Illegal reassignment to import with setters

### ISSUE THREAD

**Issue by camille-hdl** [rollup/rollup#3187]
- Rollup Version: 1.20
- Operating System (or Browser): macOS
- Node Version: 12.8.0

### How Do We Reproduce?

I forked the starter-lib repo : https://github.com/camille-hdl/rollup-starter-lib

run:  
* `npm install`
* `npm run build`

### Expected Behavior

Project should bundle

### Actual Behavior

I get an error:

`Illegal reassignment to import 'MapboxGl'`

The code I added in main.js is simple:
```js
import ReactMapboxGL from "react-mapbox-gl";

const Map = ReactMapboxGL({
	accessToken: "123123"
});
```

`react-mapbox-gl` resolves to `node_modules/react-mapbox-gl/lib-esm/map.js` where we find:

```js
import * as MapboxGl from 'mapbox-gl';
/* ... */
MapboxGl.accessToken = accessToken;
```
which throws the Illegal reassignment error.

However, in `node_modules/mapbox-gl/src/index.js`, `accessToken` is a setter, not an export:

```js
const exported = {
/* ... */
get accessToken(): ?string {
        return config.ACCESS_TOKEN;
},
set accessToken(token: string) {
        config.ACCESS_TOKEN = token;
},
/* ... */
};
export default exported;
```

In that case, shouldn't `MapboxGl.accessToken = accessToken;` be legal?

Maybe I'm missing something here?

**Comment by kzc** [comment]
The error produced by Rollup matches the behavior of both `node --experimental-modules` and native ES6 browsers.

See https://exploringjs.com/es6/ch_modules.html#_in-es6-imports-are-live-read-only-views-on-exported-values:

> **16.7.2 In ES6, imports are live read-only views on exported values**
>
> In contrast to CommonJS, imports are views on exported values. In other words, every import is a live connection to the exported data. Imports are read-only:
>
>    * Unqualified imports (import x from 'foo') are like const-declared variables.
>    * The properties of a module object foo (import * as foo from 'foo') are like the properties of a frozen object.

I don't how the following could have worked:
```js
import * as MapboxGl from 'mapbox-gl';
MapboxGl.accessToken = accessToken;
```

Perhaps it was intended to be bundled with a non-standard compliant bundler?

If the code were changed to the following it would work in both Node and native ES6 browsers:
```js
import MapboxGl from 'mapbox-gl';
MapboxGl.accessToken = accessToken;
```

**Comment by camille-hdl** [comment]
Thank you @kzc for the explanation.

I opened an issue on the react-mapbox-gl repo since the problem seems to be on their end if I understand correctly.

**Comment by nrgapple** [comment]
@camille-hdl can you link the issue you opened?

**Comment by camille-hdl** [comment]
@nrgapple here : https://github.com/alex3165/react-mapbox-gl/issues/795

I haven't tried with an up-to-date version of react-mapbox-gl in a while though, so maybe they fixed it since then.

**Comment by kushal-iotasol** [comment]
@camille-hdl any update on this one is this fixed I am getting this issue on v4 of react-mapbox-gl

**Comment by camille-hdl** [comment]
@kushal-iotasol I haven't tried, but looking at https://github.com/alex3165/react-mapbox-gl/blob/master/src/map.tsx, I can still see the problematic code

```
import * as MapboxGl from 'mapbox-gl';
(MapboxGl as any).accessToken = accessToken;
if (apiUrl) {
        // tslint:disable-next-line:no-any
        (MapboxGl as any).config.API_URL = apiUrl;
}
```

as well as mixed `import` / `require` syntax, so unless Rollup has become more lenient, I don't think anything has changed.
