### ISSUE TITLE
output globals with external does not work

### ISSUE THREAD

**Issue by seeliang** [rollup/rollup#3188]
Hi guys,

I have tried Gitter, no response.
and could not fully understand the documents,
 since none of the things I have tried works.

so here we go

- Rollup Version:1.25.2
- Operating System (or Browser):macOS 10.15
- Node Version: 10.17

### How Do We Reproduce?

```JavaScript
import babel from 'rollup-plugin-babel';
export default {
  input: 'index.js',
  external: ['react','react-dom'],
  output: {
    file: 'dist/js/bundle.js',
    format: 'esm',
    name: 'bundle',
    globals: {
      react: 'React',
      'react-dom': 'ReactDOM'
    }
  },
  plugins: [
    babel(),
  ]
};
```

### Expected Behavior

bundle.js should NOT have 

```JavaScript
import React from 'react';
import ReactDOM from 'react-dom';
```
### Actual Behavior
bundle.js has
```JavaScript
import React from 'react';
import ReactDOM from 'react-dom';
```

### To achieve expected behaviour
```JavaScript
import babel from 'rollup-plugin-babel';
import externalGlobals from "rollup-plugin-external-globals";
export default {
  input: 'index.js',
  output: {
    file: 'dist/js/bundle.js',
    format: 'esm'
  },
  plugins: [
    babel(),
    externalGlobals({
      react: "React",
      "react-dom": 'ReactDOM'
    })
  ]
};
```

**Comment by lukastaegert** [comment]
output.globals only sets the global variable for external imports in IIFE bundles (and UMD bundles when they are used in a script tag), in other formats it has no effect. https://www.npmjs.com/package/rollup-plugin-external-globals is probably what you want.

**Comment by lukastaegert** [comment]
Ah sorry, I see you found that plugin, is it working for you? There are technical reasons this is not supported in core, mostly because it would need to work very differently for non-IIFE formats, potentially provide larger output after minification, and it is totally unclear how to handle this with UMD.

**Comment by lukastaegert** [comment]
Maybe we should rename the option to something like iifeGlobals to reduce the confusion.

**Comment by seeliang** [comment]
@lukastaegert  thanks for the quick reply.
Yes, these are quite different from others, but if the official decision is to implement in this way, 
then i think it is ok. and i will use the plugin instead

i think we could update the doc to demonstrate the idea in a better way, and may external as well

**Comment by mikeaustin** [comment]
I've been using Webpack for most project, but have tried Rollup recently. The configuration can be just as confusing as Webpack with things like this. How does this sample project work, for example, using external for react?

I'm currently setting window.React = React to be able to use externals/peer deps. What other ways are there?
