### ISSUE TITLE
Object property has been treated as invariable value even it has been muted in method [treeshaking]

### ISSUE THREAD

**Issue by huozhi** [rollup/rollup#3192]
- Rollup Version: 1.25.2 and 1.2.x 
- Operating System (or Browser): Mac OS X
- Node Version: 8.10.x

looks like the bug has existed since v1.

### How Do We Reproduce?

input code
```js
var obj = {
  prop: null,
  setProp(value) { this.prop = value }
}

obj.setProp(123)

function output() {
  if (obj.prop) {
    var a = 3
    var b = 4
    return a + b
  }
  return -1
}

console.log(output())
```

bundle it with rollup with `treeshake` option on, it will be bundled as following content

output
```js
var obj = {
  prop: null,
  setProp: function setProp(value) { this.prop = value; }
};

obj.setProp(123);

function output() {
  return -1
}

console.log(output());
```
Even I config `treeshake.propertyReadSideEffects` to `true`, it still bundled as the following. 

### Expected Behavior

the expressions in the `output` function shouldn't be optimized and erased.

### Actual Behavior

the condition `obj.prop` should be `123` instead of `null` since it's muted by `obj.setProp` method. but rollup still treat it as an invariable value then erased the code under the condition.

**Comment by kzc** [comment]
Well known bug: #2345 #3093 #2473 #3027

Either disable `treeshake` altogether or use the patch in https://github.com/rollup/rollup/issues/2345#issuecomment-466451823.
