### ISSUE TITLE
SystemJS external module destructuring

### ISSUE THREAD

**Issue by baryla** [rollup/rollup#3195]
I'm using the Rollup browser API to compile and bundle some code into SystemJS and then I'm using SystemJS to load everything. The REPL below shows what I'm trying to achieve. 
Basically I import React from unpkg (I use SystemJS to map the imports) and then I try to get the exported `Component`. 

- Rollup Version: 1.26.0
- SystemJS Version: 0.21.6
- Operating System (or Browser): Browser (Rollup API)
- Node Version: 10.6.3

### How Do We Reproduce?
https://rollupjs.org/repl/?version=0.67.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMFJlYWN0JTJDJTIwJTdCJTIwQ29tcG9uZW50JTIwJTdEJTIwZnJvbSUyMCdyZWFjdCclM0IlNUNuJTVDbmNvbnNvbGUubG9nKFJlYWN0JTJDJTIwQ29tcG9uZW50JTJDJTIwUmVhY3QuQ29tcG9uZW50KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnN5c3RlbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior
In the console log, I should get:
- `React` object with all properties such as `Component`, `Children` etc.
- `Component` function
- `React.Component` function

### Actual Behavior
In the console log, I get:
- `React` object with all properties such as `Component`, `Children` etc.
-  `undefined` 
- `React.Component` function

I believe the problem lies in the way `setters` are defined in the SystemJS register function because if I change: 
```
// from
React = module.default;
Component = module.Component;

// to
React = module.default;
Component = React.Component;
```
it will work as expected. I believe this is a bug but if not, can someone correct me please or tell me what I'm doing wrong or if there is a setting for this? It's kind of confusing me more because when I do the same thing but instead of importing `React`, I import `Svelte` and then destructure  it - it works great but if I try `Vue` it also fails. I'm not sure if this makes sense? If you need more information, let me know. 

I think this may be related to: https://github.com/rollup/rollup/pull/2587 ?

**Comment by lukastaegert** [comment]
I’m not sure why you think destructuring players into this because maybe I overlook where it is used? What I think might be the problem, though, is that React is distributed as CommonJS and the SystemJS runtime needs to translate it, which apparently does not work well. Two options:
- Do not use named imports for Component but rather pick everything from the default React import, i.e. React.Component
- Switch to something like es-react, which is an unofficial redistribution of React as ES modules (or probably es-react-production). I have a feeling that this should be able to resolve named imports correctly.

**Comment by lukastaegert** [comment]
https://github.com/lukejacksonn/es-react

**Comment by baryla** [comment]
Thanks for your help @lukastaegert. It's really strange but I managed to "solve" this by just using a different version of SystemJS. Unfortunately a very old one. Version 0.19.47 seems to be the last one that supports import statements like this `import React, { Component } from 'react';` :(

**Comment by lukastaegert** [comment]
Nice to hear but not surprising. The official NodeJS interop between CommonJS and ESM is that you only get a default export from a CommonJS module in an ESM module. Thus the fact that React is promoting a named import style even though it is distributed as CommonJS means it relies on some very specific, non-standard behaviour of e.g. Webpack. I really hope they fix this mess eventually.
