### ISSUE TITLE
Argument names can break symbol renaming.

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#32]
See https://gist.github.com/mbostock/525efe52c9015002fdca for a test case.

Consider two identical foo.js and bar.js:

```js
function thing(thing) {}
 
export default thing;
```

And an index.js which is rolled up:

```js
import foo from "./foo";
import bar from "./bar";
 
export {
  foo,
  bar
};
```

The resulting code is broken:

```js
'use strict';
 
function thing(thing) {}
 
var bar = _thing;
 
function thing(thing) {}
 
var foo = thing;
 
exports.foo = foo;
exports.bar = bar;
```

If you change foo.js or bar.js so that the argument `thing` has a different name than the function `thing`, the error is fixed.

**Comment by Rich-Harris** [comment]
Thanks - fixed in 0.8.3. The code that ensures this...

```js
var foo = 42;

function bar () {
  var foo = 43;
}
```

...becomes this...

```js
var renamed_foo = 42;

function bar () {
  var foo = 43;
}
```

...rather than this...

```js
var renamed_foo = 42;

function bar () {
  var renamed_foo = 43;
}
```

...wasn't accounting for functions that have an argument with the same name - turns out to be unrelated to #33.
