### ISSUE TITLE
class with field didn't be treeshaked

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#3207]
- Rollup Version: 1.19.4
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

```js
class A {
    field;
}
```

### Expected Behavior

Treeshaked if unused.

### Actual Behavior

Class with filed in it will not be treeshaked.

Though class filed is not in stage 4, but since #2775 is marked as a bug, I report this...

**Comment by shellscape** [comment]
Missing a few fields on the issue template 😉

**Comment by LongTengDao** [comment]
Ah... Thank you! I can't see the relationship between the issue and OS/NodeVersion information...

**Comment by shellscape** [comment]
It's info we ask everyone to fill in, even maintainers 🚀  Please don't skip sections next time around!

**Comment by lukastaegert** [comment]
Unfortunately, this cannot be improved until class properties are officially supported. Until that time, Rollup will treat the corresponding syntax tree nodes as "unknown", which means it is very conservative about them as it does not know in which situations they might have side-effects. #2775 is different in that it could be easily fixed without official class property support.
