### ISSUE TITLE
Never treat modules starting with dot as external dependency

### ISSUE THREAD

**Issue by szwacz** [rollup/rollup#321]
The problem I've encountered:
```js
import foo from './baar'; // I ment 'bar' but mistyped it
```
Rollup was ok with that, and just treated it as external:
```
Treating './baar' as external dependency
```
But this is clearly an error. How about if any module name starts with dot `.` and can't be found, raise error instead of treating it as external dependency?

**Comment by Victorystick** [comment]
I only think that's only fair. An earlier version of Rollup required all external dependencies to be explicit, but now they're all implicit. Something in the middle would be better.

**Comment by callumlocke** [comment]
I'm getting this same problem (`Treating './some-file' as external dependency`) even though my `external` option is `[]`.

Is that a bug in rollup? I'm using v0.21.0.

**Comment by Victorystick** [comment]
It's not a bug per se, but it's bad behaviour. Rollup no longer requires explicitly stating `external` modules. It assumes modules that it cannot find are external and continues.

> How about if any module name starts with dot `.` and can't be found, raise error instead of treating it as external dependency?

... is what we should do.

**Comment by Rich-Harris** [comment]
Agree – #328
