### ISSUE TITLE
rollup-plugin-dts triggers a runtime error in rollup core v1.26.0+

### ISSUE THREAD

**Issue by aleclarson** [rollup/rollup#3210]
- Rollup Version: 1.26.0+
- Operating System (or Browser): macOS
- Node Version: 12.13.0

### How Do We Reproduce?

1. Clone my library:

```sh
git clone https://github.com/alloc/wana.git -b rollup-1.26
```

2. Install and build:

```sh
cd wana && yarn && yarn build
```

3. Notice how `yarn build` exits **without an error**

4. Upgrade to Rollup 1.26.0:

```sh
yarn add rollup@1.26.0 -D
```

5. Run `yarn build` and notice the error

6. Use `node --inspect-brk` to investigate further 😉 

### Expected Behavior

No runtime error.

### Actual Behavior

After upgrading to `rollup@1.26.0`, my library cannot run `rollup -c` without consistently throwing an error while using [`rollup-plugin-dts`](https://github.com/Swatinem/rollup-plugin-dts). I've confirmed that `rollup@1.25.2` does *not* have the same issue.

```sh
$ rollup -c

src/index.ts → dist/index.js...
created dist/index.js in 924ms

src/index.ts → dist/index.cjs.js...
created dist/index.cjs.js in 653ms

src/index.ts → dist/index.d.ts...
[!] TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at Module.addExport (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:9971:40)
    at ExportNamedDeclaration.initialise (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:6783:22)
    at new NodeBase (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:3110:14)
    at new ExportNamedDeclaration (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:6773:1)
    at Program$1.parseNode (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:3230:27)
    at new NodeBase (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:3109:14)
    at new Program$1 (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:8190:1)
    at Module.setSource (~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:9904:20)
    at ~/dev/wana/node_modules/.pnpm/registry.npmjs.org/rollup/1.26.0/node_modules/rollup/dist/rollup.js:12641:20
    at async Promise.all (index 0)

error Command failed with exit code 1.
```

/cc @Swatinem

**Comment by lukastaegert** [comment]
@Swatinem Is it possible that the plugin creates a synthetic ExportNamedDeclaration where `source` is `undefined` instead of the correct value `null`? This would explain the error.

**Comment by lukastaegert** [comment]
We can also fix this on Rollup side (and probably will), but as a rule of thumb, Rollup expects the generated AST to conform to the ESTree spec and does not validate this, which usually means that "missing" properties are expected to be `null`.

**Comment by Swatinem** [comment]
>
> @Swatinem <https://github.com/Swatinem> Is it possible that the plugin
> creates a synthetic ExportNamedDeclaration where source is undefined
> instead of the correct value null? This would explain the error.
>
That is a very likely explanation.
I'm still on vacation for a few days and don't have access to fix this
right now.

>

**Comment by lukastaegert** [comment]
I will push a fix to Rollup by changing how we find out if a named export is a re-export but it is slightly brittle as in my experiments it only worked if the export statement is not included in the bundle. I would very much recommend you check if your generated Nodes are ESTree compliant (i.e. containing all necessary `null`s) if you find some time.

**Comment by aleclarson** [comment]
🎉

**Comment by Swatinem** [comment]
renovate auto-bumped `rollup-plugin-dts`’ rollup dependency, so I guess I can call this fixed.

And yes, I do not explicitly set that prop to `null`, however I do for `declaration`.
https://github.com/Swatinem/rollup-plugin-dts/blob/7baa96cc77cb676601e9102bee72309e19b65276/src/astHelpers.ts#L43-L53
I can’t remember why exactly, as I personally prefer `undefined` over `null`; maybe it was because of a similar issue back then.

However the `@types/estree` types allow both `undefined` and `null`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8e0fa6fc55e715ccd9ee1656ba4ce2106067fbf9/types/estree/index.d.ts#L523-L528

@lukastaegert what do you recommend the *correct* thing to do here is? If you say to use an explicit `null`, then the `@types` would have to be updated accordly as well, otherwise this ambiguity will hit more people in the future.

**Comment by lukastaegert** [comment]
I think they should. To my knowledge, this is the official spec, which does not allow for `undefined`; this is the spec I look at when doing AST work in Rollup and it is also observed by acorn: https://github.com/estree/estree/blob/master/es2015.md#exportnameddeclaration

Also, making sure that the shape of objects of the same type stays consistent can improve performance in certain situations.

**Comment by lukastaegert** [comment]
Also it improves serializability, as JSON does not support explicit `undefined`
