### ISSUE TITLE
Configuration external with global form React and Hooks

### ISSUE THREAD

**Issue by Jucian0** [rollup/rollup#3213]
Hello everyone, sorry if this issue is in the incorrect place.
How does this work?
I'm getting this error when running my web app

Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)

This is my configuration rollup 

`const pkg = require('./package.json')
const libraryName = 'sensedia-web-components'

export default {
  input: `src/${libraryName}.ts`,
  external: [
    ...Object.keys(pkg.peerDependencies),
    ...Object.keys(pkg.dependencies),
    ...Object.keys(pkg.devDependencies)
  ],
  output: {
    file: pkg.main,
    name: camelCase(libraryName),
    format: 'umd', sourcemap: true,
    globals: {
      'react': 'React',
      'react-dom': 'ReactDOM',
      'styled-components': 'styled'
    }
  },
  watch: {
    include: 'src/**',
  },
  plugins: [
    json(),
    typescript({ useTsconfigDeclarationDir: true }),
    commonjs(),
    resolve({
      dedupe: ['react', 'react-dom'], // Default: []
    }),
    sourceMaps(),
  ],
}`

this is out my terminal when run `npm ls react`
![Captura de tela de 2019-11-06 06-55-24](https://user-images.githubusercontent.com/8399579/68288039-7a7c8f80-0062-11ea-9bfc-fc16b8bbd65f.png)

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).
