### ISSUE TITLE
Module is removed when using preserveModules

### ISSUE THREAD

**Issue by merceyz** [rollup/rollup#3221]
- Rollup Version: 1.26.4
- Operating System (or Browser): Windows 7
- Node Version: v12.10.0

### How Do We Reproduce?
1. Clone https://github.com/merceyz/rollup-preserve-modules-bug
2. Install and build (build output is included in the repo)

### Expected Behavior
```
$ find dist
dist
dist/index.js
dist/sub-module
dist/sub-module/index.js
dist/sub-module/sub-module.js
```
### Actual Behavior
```
$ find dist
dist
dist/index.js
dist/sub-module
dist/sub-module/sub-module.js
```

`dist/sub-module/index.js` is missing, most likely because it isn't referenced anymore.

Setting `treeshake: false` includes `dist/sub-module/index.js` but causes `dist/index.js` to look like this
```js
import { foo } from './sub-module/sub-module.js';
import './sub-module/index.js';
```

**Comment by shellscape** [comment]
This is correct behavior and by design. The reference in `sub-module/index.js` is superfluous and so it is dropped when tree shaking.
