### ISSUE TITLE
Writing a plugin with a load() method to read files from a non-disk location

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup#323]
You can run the following snippet here and see the logs:
https://tonicdev.com/callumlocke/rollup-non-existent-entry-file

```js
var rollup = require('rollup');

rollup.rollup({
    entry: 'non-existent.js',
    plugins: [
        {
            load: function (id) {
                console.log('id is: ' + JSON.stringify(id));
                return 'someCode();';
            }
        }
    ]
});
```

- **Expected:** the plugin's `load()` method should log `id is: "non-existent.js"`
- **Actual:** it logs `id is: null`

If I set `entry` to a file that *does* exist, then the plugin's load method is passed the actual file path (resolved into an absolute path from `process.cwd()`).

My worry is, why does rollup even check if the file exists on disk? If I'm providing a plugin with a `load()` method, I expected rollup just to use that method to load files. I don't want it to use the disk directly at all.

My use case: I want to use rollup to bundle a bunch of files that I have in memory. The files don't necessarily exist on disk. (Even if some of them happen to exist on disk, I definitely don't want rollup to read these from disk directly, because the on-disk files might just be templates/precursors that need to be preprocessed somehow before I pass them to rollup.) I was hoping that I could just make plugin with a `load()` method, and rollup would always use this to read files. Am I misunderstanding how plugins work?

**Comment by TrySound** [comment]
@callumlocke Already exists
https://github.com/TrySound/rollup-plugin-memory

**Comment by Victorystick** [comment]
@callumlocke From what I can tell, TrySound's rollup-plugin-memory only loads the _entry_ from memory. You say you require _all_ modules to be loaded from memory, right?

If you add this line, `id` will be the path regardless of whether the file exists or not.
```diff
var rollup = require('rollup');

rollup.rollup({
    entry: 'non-existent.js',
    plugins: [
        {
+           resolveId: function (id) { return id; },
            load: function (id) {
                console.log('id is: ' + JSON.stringify(id));
                return 'someCode();';
            }
        }
    ]
});
```

Rollup allows all plugins to specify their own `load` functions. If one function cannot handle a given `id`, it can just return `undefined` or `null` and let another function have a go at it.

The default `load` function loads files from the filesystem, and the default `resolveId` function appears to only resolve `id`s it can find a corresponding file for.

If you want the `id` to stay as it is, use the above `resolveId` function. That way you can go ahead and implement `load` just the way you want it. :smiley: Does that clarify it?

**Comment by TrySound** [comment]
@callumlocke You can make a pr or issue in my plugin. We will discuss

**Comment by Rich-Harris** [comment]
> If you want the `id` to stay as it is, use the above `resolveId` function

woah there... :grinning: `resolveId` is responsible for resolving an ID relative to its importer – simply returning the input will cause `../foo.js` to be treated differently from `../../foo.js` even if they refer to the same file (and neither will actually get loaded). The function would have to implement path resolution as well.

> My worry is, why does rollup even check if the file exists on disk?

I know. It's a PITA. It didn't, previously, but two (in my opinion extremely misguided) Node.js design decisions necessitate it:

* `foo` could mean `foo` or `foo/index`, depending on what's on the filesystem
* a `.js` extension gets added, depending on what's on the filesystem

Because of that, we have to accommodate various bad practices that we've all adopted. Unfortunately that means we have to check the filesystem at resolution time rather than waiting till load time.

**Comment by Victorystick** [comment]
D'oh! That's me not thinking things through. :stuck_out_tongue:

**Comment by callumlocke** [comment]
@TrySound thanks. Is it correct that your plugin is just for providing the entry contents up front (not all files)?

@Victorystick that seems to do it, thanks! Yes I want to use my load() function to load all files.

@Rich-Harris thanks, I'm realising now I don't have much understanding of how multiple plugins work. I notice the commonjs plugin's `resolveId()` function [starts with](https://github.com/rollup/rollup-plugin-commonjs/blob/3c5551874db3be87edc03af43dc60fbaad6a26de/src/index.js#L27) `if ( importee[0] !== '.' ) return;`. Does returning undefined mean "skip this plugin entirely for this file"?

If there are two plugins that both provide a load() method, what defines which load() method gets used – is it whether or not the first plugin's resolveId() method returns undefined?

**Comment by TrySound** [comment]
@callumlocke Yes, but we can think about major update for multiple files.

**Comment by Rich-Harris** [comment]
@callumlocke For both `resolveId` and `load`, the first one to return a truthy value 'wins' – they needn't belong to the same plugin. So the commonjs plugin, for example, has some extra logic for finding `foo/index.js` when you wrote `foo.js` (the default resolver doesn't add `index`, but it's a permitted pattern in commonjs modules), but doesn't bear any responsibility for a) locating packages in `node_modules` or b) loading commonjs modules it finds with that extra `/index` logic – that's still the job of the default loader, loading from the filesystem.

**Comment by callumlocke** [comment]
OK it's making more sense now, thanks. So if I understand correctly, the process for importing a file looks something like this:

1. Resolve the id to a real file path:
  - Call each plugin's `resolveId()` function in turn, stopping as soon as one of them returns a file path, otherwise use the [default `resolveId()` function](https://github.com/rollup/rollup/blob/d35ffb156568ed1294b9b9961e1c54f48b36ce3c/src/utils/defaults.js#L17-L28).
  - If the resolved ID has already been imported in the bundle, stop here.
2. Load the file's contents from that resolved file path:
  - Call each plugin's `load()` function in turn, stopping as soon as one of them returns contents, otherwise use the [default `load()` function].(https://github.com/rollup/rollup/blob/d35ffb156568ed1294b9b9961e1c54f48b36ce3c/src/utils/defaults.js#L4-L6)
3. Run it through all the transformers:
  - Call every plugin's `transform()` function, in series. Each transformer's output is passed into the next. (There is no default transform function.)
4. Scan the transformed contents for import statements. For each one, repeat these steps.

Is that right?

**Comment by Victorystick** [comment]
@callumlocke Yes, that's accurate. :+1:

**Comment by callumlocke** [comment]
Awesome :) One final question then I'll close this...

> Unfortunately that means we have to check the filesystem at resolution time rather than waiting till load time.

Is there any way for me to turn this off? For my case it's essential that I can configure rollup to *never* touch the disk. If none of my plugins are able to resolve the ID, I want rollup to just accept the import is unresolvable and error out accordingly, rather than try to find it on disk itself.

From [this line](https://github.com/rollup/rollup/blob/d35ffb156568ed1294b9b9961e1c54f48b36ce3c/src/Bundle.js#L28) it looks like there's no way to turn it off... Would you accept a PR to add an option for this, something like `disableDefaults`? This would disable the default `resolveId`, `load` and `onwarn` functions.

**Comment by Victorystick** [comment]
> it looks like there's no way to turn it off...

Just `throw` and Rollup shouldn't try to use the defaults. :smile:

**Comment by callumlocke** [comment]
ah ok I guess that'll work, thank you!
