### ISSUE TITLE
How to get information about dynamic imports in plugin context

### ISSUE THREAD

**Issue by btd** [rollup/rollup#3232]
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

If i use generateBundle hook, i can get `imports` and `dynamicImports` for chunks. If i go deep starting to get dependency graph with `this.getModuleInfo` function - it returns only `importedIds`, which do not contain info about dynamic imports. It could be simplified to like:

```
C ---> A --- dynamic ---> B
       |
       v
       D
```
In this case i will get C->A, A->D only.
### Your Proposal for Changes
Include dynamicImportedIds to this.getModuleInfo? Or somehow to get this info from chunk if it was generated because it was imported by some other place?

Thank you

**Comment by lukastaegert** [comment]
Will add this to an upcoming PR, thanks for your patience!

**Comment by btd** [comment]
Thanks, yesterday i tried to implement it myself

**Comment by lukastaegert** [comment]
What timing... This is the PR in question: #3449

**Comment by btd** [comment]
May i ask question while you are here. Is it possible to gather source after treeshake? I mean with removed imports/exports and if some parts of not used code removed?
I need this to make more precise gzip/brotli size (currently i just get it from transform hook)

**Comment by lukastaegert** [comment]
Theoretically yes, but it would not be for free performance wise. We could add a getter to the return value that calculates the size on call.

**Comment by btd** [comment]
Ahh, ok. I imagined something like this. Thanks anyway.

**Comment by lukastaegert** [comment]
I might still add this in the way I described. It should not be hard to implement, it will be just another `.toString` on the magicString bundle. The question is what should happen if you call it before tree-shaking, I would probably let it throw.

**Comment by btd** [comment]
Yes, all wrong usage should throw ideally. It is better to be explicit that something used not right instead of silent fail.

**Comment by lukastaegert** [comment]
Ok, I decided to not add this yet as I would rather first refactor the hashing algorithm before making this available. I must admit this is not ideal, could you reopen a separate issue for making the rendered source available so that it is not forgotten?

**Comment by btd** [comment]
Thanks a lot. I will create one more
