### ISSUE TITLE
Switch statements: module truncated after empty default case

### ISSUE THREAD

**Issue by jjhembd** [rollup/rollup#3236]
- Rollup Version: 1.27.0
- Operating System (or Browser): Google Chrome
- Node Version: n/a

### How Do We Reproduce?
See this [simple test on REPL](https://rollupjs.org/repl/?version=1.27.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbmNhdCUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGc3dpdGNoLmpzJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhjb25jYXQoJTVCJTVDJTIyd2hpc3BlciU1QyUyMiUyQyUyMCU1QyUyMkklNUMlMjIlMkMlMjAlNUMlMjJoYXZlJTVDJTIyJTJDJTIwJTVDJTIyYSU1QyUyMiUyQyUyMCU1QyUyMlNFQ1JFVCU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJzaG91dCU1QyUyMiUyQyUyMCU1QyUyMmRvbid0JTVDJTIyJTJDJTIwJTVDJTIydGVsbCU1QyUyMiUyQyUyMCU1QyUyMmFueW9uZSU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJsaXN0JTVDJTIyJTJDJTIwJTVDJTIyRXNwZWNpYWxseSUyMG5vdCU1QyUyMiUyQyUyMCU1QyUyMkFsaWNlJTVDJTIyJTJDJTIwJTVDJTIyQm9iJTVDJTIyJTJDJTIwJTVDJTIyQ2hhcmxlcyU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJjb3VudCU1QyUyMiUyQyUyMCU1QyUyMk51bWJlciUyMG9mJTIwcGVvcGxlJTIwd2UlMjBjYW4lMjB0ZWxsJTVDJTIyJTVEKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzd2l0Y2guanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBjb25jYXQoc3RyaW5ncyklMjAlN0IlNUNuJTIwJTIwdmFyJTIwZmlyc3QlMkMlMjBzZWNvbmQlMkMlMjByZXN0JTNCJTVDbiU1Q24lMjAlMjAlMkYlMkYlMjBTaW1wbGUlMjBjYXNlcyUzQSUyMG9uZSUyMHNwZWNpYWwlMjBzdHJpbmclNUNuJTIwJTIwJTVCZmlyc3QlMkMlMjAuLi5yZXN0JTVEJTIwJTNEJTIwc3RyaW5ncyUzQiU1Q24lMjAlMjBzd2l0Y2glMjAoZmlyc3QpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNhc2UlMjAlNUMlMjJ3aGlzcGVyJTVDJTIyJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHJlc3QubWFwKHMlMjAlM0QlM0UlMjBzLnRvTG93ZXJDYXNlKCkpLmpvaW4oJTVDJTIyJTIwJTVDJTIyKSUzQiU1Q24lMjAlMjAlMjAlMjBjYXNlJTIwJTVDJTIyc2hvdXQlNUMlMjIlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwcmVzdC5tYXAocyUyMCUzRCUzRSUyMHMudG9VcHBlckNhc2UoKSkuam9pbiglNUMlMjIlMjAlNUMlMjIpJTNCJTVDbiUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGY29uc29sZS5sb2coJTVDJTIyJTIwJTIwUm9sbHVwJTIwdHJ1bmNhdGVzJTIwdGhlJTIwcmVzdCUyQyUyMFVOTEVTUyUyMHdlJTIwZG8lMjBzb21ldGhpbmclMjBoZXJlJTVDJTIyKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBicmVhayUzQiU1Q24lMjAlMjAlN0QlNUNuJTVDbiUyMCUyMCUyRiUyRiUyMFJlbWFpbmluZyUyMGNhc2VzJTNBJTIwdHdvJTIwc3BlY2lhbCUyMHN0cmluZ3MlNUNuJTVDdCUyRiUyRiUyMFRISVMlMjBXSE9MRSUyMEJMT0NLJTIwRElTQVBQRUFSUyUyMElGJTIwVEhFJTIwUFJFVklPVVMlMjBERUZBVUxUJTIwSVMlMjBFTVBUWSU1Q24lMjAlMjAlNUJmaXJzdCUyQyUyMHNlY29uZCUyQyUyMC4uLnJlc3QlNUQlMjAlM0QlMjBzdHJpbmdzJTNCJTVDbiUyMCUyMHN3aXRjaCUyMChmaXJzdCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY2FzZSUyMCU1QyUyMmxpc3QlNUMlMjIlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwc2Vjb25kJTIwJTJCJTIwJTVDJTIyJTNBJTIwJTVDJTIyJTIwJTJCJTIwcmVzdC5qb2luKCU1QyUyMiUyQyUyMCU1QyUyMiklM0IlNUNuJTIwJTIwJTIwJTIwY2FzZSUyMCU1QyUyMmNvdW50JTVDJTIyJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHNlY29uZCUyMCUyQiUyMCU1QyUyMiUzQSUyMCU1QyUyMiUyMCUyQiUyMHJlc3QubGVuZ3RoJTNCJTVDbiUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVDJTIyRVJST1IlM0ElMjBVbmtub3duJTIwY2FzZSU1QyUyMiUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE). Note: in my browser, some of the code is hidden until I click in the code boxes.

With an empty default case in the first switch block, the rest of the module is deleted from the bundle. But if I un-comment the console.log in the default, then the bundle is fine.

### Expected Behavior
The code after the first switch block should be retained

### Actual Behavior
All code after the empty default case is deleted

**Comment by jjhembd** [comment]
The problem appears starting from v1.25.0.
- [Test in v1.24.0](https://rollupjs.org/repl/?version=1.24.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbmNhdCUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGc3dpdGNoLmpzJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhjb25jYXQoJTVCJTVDJTIyd2hpc3BlciU1QyUyMiUyQyUyMCU1QyUyMkklNUMlMjIlMkMlMjAlNUMlMjJoYXZlJTVDJTIyJTJDJTIwJTVDJTIyYSU1QyUyMiUyQyUyMCU1QyUyMlNFQ1JFVCU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJzaG91dCU1QyUyMiUyQyUyMCU1QyUyMmRvbid0JTVDJTIyJTJDJTIwJTVDJTIydGVsbCU1QyUyMiUyQyUyMCU1QyUyMmFueW9uZSU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJsaXN0JTVDJTIyJTJDJTIwJTVDJTIyRXNwZWNpYWxseSUyMG5vdCU1QyUyMiUyQyUyMCU1QyUyMkFsaWNlJTVDJTIyJTJDJTIwJTVDJTIyQm9iJTVDJTIyJTJDJTIwJTVDJTIyQ2hhcmxlcyU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJjb3VudCU1QyUyMiUyQyUyMCU1QyUyMk51bWJlciUyMG9mJTIwcGVvcGxlJTIwd2UlMjBjYW4lMjB0ZWxsJTVDJTIyJTVEKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzd2l0Y2guanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBjb25jYXQoc3RyaW5ncyklMjAlN0IlNUNuJTIwJTIwdmFyJTIwZmlyc3QlMkMlMjBzZWNvbmQlMkMlMjByZXN0JTNCJTVDbiU1Q24lMjAlMjAlMkYlMkYlMjBTaW1wbGUlMjBjYXNlcyUzQSUyMG9uZSUyMHNwZWNpYWwlMjBzdHJpbmclNUNuJTIwJTIwJTVCZmlyc3QlMkMlMjAuLi5yZXN0JTVEJTIwJTNEJTIwc3RyaW5ncyUzQiU1Q24lMjAlMjBzd2l0Y2glMjAoZmlyc3QpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNhc2UlMjAlNUMlMjJ3aGlzcGVyJTVDJTIyJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHJlc3QubWFwKHMlMjAlM0QlM0UlMjBzLnRvTG93ZXJDYXNlKCkpLmpvaW4oJTVDJTIyJTIwJTVDJTIyKSUzQiU1Q24lMjAlMjAlMjAlMjBjYXNlJTIwJTVDJTIyc2hvdXQlNUMlMjIlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwcmVzdC5tYXAocyUyMCUzRCUzRSUyMHMudG9VcHBlckNhc2UoKSkuam9pbiglNUMlMjIlMjAlNUMlMjIpJTNCJTVDbiUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGY29uc29sZS5sb2coJTVDJTIyJTIwJTIwUm9sbHVwJTIwdHJ1bmNhdGVzJTIwdGhlJTIwcmVzdCUyQyUyMFVOTEVTUyUyMHdlJTIwZG8lMjBzb21ldGhpbmclMjBoZXJlJTVDJTIyKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBicmVhayUzQiU1Q24lMjAlMjAlN0QlNUNuJTVDbiUyMCUyMCUyRiUyRiUyMFJlbWFpbmluZyUyMGNhc2VzJTNBJTIwdHdvJTIwc3BlY2lhbCUyMHN0cmluZ3MlNUNuJTVDdCUyRiUyRiUyMFRISVMlMjBXSE9MRSUyMEJMT0NLJTIwRElTQVBQRUFSUyUyMElGJTIwVEhFJTIwUFJFVklPVVMlMjBERUZBVUxUJTIwSVMlMjBFTVBUWSU1Q24lMjAlMjAlNUJmaXJzdCUyQyUyMHNlY29uZCUyQyUyMC4uLnJlc3QlNUQlMjAlM0QlMjBzdHJpbmdzJTNCJTVDbiUyMCUyMHN3aXRjaCUyMChmaXJzdCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY2FzZSUyMCU1QyUyMmxpc3QlNUMlMjIlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwc2Vjb25kJTIwJTJCJTIwJTVDJTIyJTNBJTIwJTVDJTIyJTIwJTJCJTIwcmVzdC5qb2luKCU1QyUyMiUyQyUyMCU1QyUyMiklM0IlNUNuJTIwJTIwJTIwJTIwY2FzZSUyMCU1QyUyMmNvdW50JTVDJTIyJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHNlY29uZCUyMCUyQiUyMCU1QyUyMiUzQSUyMCU1QyUyMiUyMCUyQiUyMHJlc3QubGVuZ3RoJTNCJTVDbiUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVDJTIyRVJST1IlM0ElMjBVbmtub3duJTIwY2FzZSU1QyUyMiUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE): Works OK, bundle includes everything
- [Test in v1.25.0](https://rollupjs.org/repl/?version=1.27.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbmNhdCUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGc3dpdGNoLmpzJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhjb25jYXQoJTVCJTVDJTIyd2hpc3BlciU1QyUyMiUyQyUyMCU1QyUyMkklNUMlMjIlMkMlMjAlNUMlMjJoYXZlJTVDJTIyJTJDJTIwJTVDJTIyYSU1QyUyMiUyQyUyMCU1QyUyMlNFQ1JFVCU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJzaG91dCU1QyUyMiUyQyUyMCU1QyUyMmRvbid0JTVDJTIyJTJDJTIwJTVDJTIydGVsbCU1QyUyMiUyQyUyMCU1QyUyMmFueW9uZSU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJsaXN0JTVDJTIyJTJDJTIwJTVDJTIyRXNwZWNpYWxseSUyMG5vdCU1QyUyMiUyQyUyMCU1QyUyMkFsaWNlJTVDJTIyJTJDJTIwJTVDJTIyQm9iJTVDJTIyJTJDJTIwJTVDJTIyQ2hhcmxlcyU1QyUyMiU1RCkpJTNCJTVDbmNvbnNvbGUubG9nKGNvbmNhdCglNUIlNUMlMjJjb3VudCU1QyUyMiUyQyUyMCU1QyUyMk51bWJlciUyMG9mJTIwcGVvcGxlJTIwd2UlMjBjYW4lMjB0ZWxsJTVDJTIyJTVEKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzd2l0Y2guanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBjb25jYXQoc3RyaW5ncyklMjAlN0IlNUNuJTIwJTIwdmFyJTIwZmlyc3QlMkMlMjBzZWNvbmQlMkMlMjByZXN0JTNCJTVDbiU1Q24lMjAlMjAlMkYlMkYlMjBTaW1wbGUlMjBjYXNlcyUzQSUyMG9uZSUyMHNwZWNpYWwlMjBzdHJpbmclNUNuJTIwJTIwJTVCZmlyc3QlMkMlMjAuLi5yZXN0JTVEJTIwJTNEJTIwc3RyaW5ncyUzQiU1Q24lMjAlMjBzd2l0Y2glMjAoZmlyc3QpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNhc2UlMjAlNUMlMjJ3aGlzcGVyJTVDJTIyJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHJlc3QubWFwKHMlMjAlM0QlM0UlMjBzLnRvTG93ZXJDYXNlKCkpLmpvaW4oJTVDJTIyJTIwJTVDJTIyKSUzQiU1Q24lMjAlMjAlMjAlMjBjYXNlJTIwJTVDJTIyc2hvdXQlNUMlMjIlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwcmVzdC5tYXAocyUyMCUzRCUzRSUyMHMudG9VcHBlckNhc2UoKSkuam9pbiglNUMlMjIlMjAlNUMlMjIpJTNCJTVDbiUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGY29uc29sZS5sb2coJTVDJTIyJTIwJTIwUm9sbHVwJTIwdHJ1bmNhdGVzJTIwdGhlJTIwcmVzdCUyQyUyMFVOTEVTUyUyMHdlJTIwZG8lMjBzb21ldGhpbmclMjBoZXJlJTVDJTIyKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBicmVhayUzQiU1Q24lMjAlMjAlN0QlNUNuJTVDbiUyMCUyMCUyRiUyRiUyMFJlbWFpbmluZyUyMGNhc2VzJTNBJTIwdHdvJTIwc3BlY2lhbCUyMHN0cmluZ3MlNUNuJTVDdCUyRiUyRiUyMFRISVMlMjBXSE9MRSUyMEJMT0NLJTIwRElTQVBQRUFSUyUyMElGJTIwVEhFJTIwUFJFVklPVVMlMjBERUZBVUxUJTIwSVMlMjBFTVBUWSU1Q24lMjAlMjAlNUJmaXJzdCUyQyUyMHNlY29uZCUyQyUyMC4uLnJlc3QlNUQlMjAlM0QlMjBzdHJpbmdzJTNCJTVDbiUyMCUyMHN3aXRjaCUyMChmaXJzdCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY2FzZSUyMCU1QyUyMmxpc3QlNUMlMjIlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwc2Vjb25kJTIwJTJCJTIwJTVDJTIyJTNBJTIwJTVDJTIyJTIwJTJCJTIwcmVzdC5qb2luKCU1QyUyMiUyQyUyMCU1QyUyMiklM0IlNUNuJTIwJTIwJTIwJTIwY2FzZSUyMCU1QyUyMmNvdW50JTVDJTIyJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHNlY29uZCUyMCUyQiUyMCU1QyUyMiUzQSUyMCU1QyUyMiUyMCUyQiUyMHJlc3QubGVuZ3RoJTNCJTVDbiUyMCUyMCUyMCUyMGRlZmF1bHQlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVDJTIyRVJST1IlM0ElMjBVbmtub3duJTIwY2FzZSU1QyUyMiUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE): Broken, bundle truncated (same behavior as 1.27.0)

**Comment by lukastaegert** [comment]
Thanks, fix at #3241

**Comment by jjhembd** [comment]
Thanks for the quick fix!
And many thanks for your ongoing work on Rollup! My coding life became much
more enjoyable after I started using it.
Jeshurun
