### ISSUE TITLE
bundle commonjs dependencies installed through bower?

### ISSUE THREAD

**Issue by jay8t6** [rollup/rollup#324]
@Rich-Harris @Victorystick Is it possible to bundle external commonjs dependencies that are installed through bower?

**Comment by Victorystick** [comment]
@jay8t6 The best way to do it would be to create `rollup-plugin-bower`, and use that.

Until that exists, you could always write your own `resolveId` function and implement the Bower resolution algorithm from there.

```js
// rollup.config.js

export default {
  entry: './app.js',
  plugins: [
    {
      resolveId: function ( id, importer ) {
        return ...;
      }
    }
  ]
};
```

**Comment by jay8t6** [comment]
@Victorystick  thanks for the response. I am kinda confused about what to do with the resolveId function.

// src/demo.js
import angular from 'bower/angular';
import uirouter from 'bower/angular-ui-router';

import routing from './home/home.routes';
import HomeController from './home/home.controller';

angular.module('app', [])
  .config(routing)
  .controller('HomeController', HomeController)
  .name;

// rollup.config.js
rollup.rollup({
      entry: 'src/demo.js',
      plugins: [
        babel({
          presets: ['es2015-rollup']
        }),
        {
          resolveId: function (id, importer) {
            //should I just get the list of bower dependecies 
            //from bower.json and just return it here?
          }
        },
        commonjs({
          //I want to convert the bower dependencies to es6 too.
          //will the commonjs modules from bower be converted to es6 here?
        })
      ]
    }).then(function (bundle) {
      bundle.write({
        format: 'es6',
        dest: 'build/bundle.js'
      });
    });

Thanks for your help with this!

**Comment by Rich-Harris** [comment]
In 99% of cases, the ID returned by `resolveId` is an absolute path to a JavaScript file (the other 1% is edge cases like loading from memory in a browser setting) – so most likely it should return something like `/path/to/your/project/bower_components/some-library/dist/some-library.js`.

From my own hellish experiences with Bower, it's not always straightforward to find that file. I once wrote a package called [list-bower-paths](https://www.npmjs.com/package/list-bower-paths) to help with it, but YMMV, frankly – with that package `resolveId` would look something like this:

```js
var lbp = require('list-bower-paths');
var bowerPaths = lbp.sync();

// ...
{
  resolveId: function(id, importer) {
    // if `id` isn't in `bowerPaths`, it will fall through harmlessly
    return bowerPaths[id];
  }
}
```

> will the commonjs modules from bower be converted to es6 here?

Yes – it should automatically convert CommonJS files wherever they're found.

**Comment by boneskull** [comment]
@jay8t6 you could also try to [stop using bower](https://npmcdn.com/)

**Comment by Rich-Harris** [comment]
Going to close this issue – if anyone ends up writing a bower plugin, let us know and add it to the [wiki](https://github.com/rollup/rollup/wiki/Plugins)!

**Comment by csbun** [comment]
Here is the plugin: [rollup-plugin-bower-resolve](https://github.com/mjeanroy/rollup-plugin-bower-resolve)

**Comment by Rich-Harris** [comment]
thanks @csbun, have added it to the wiki
