### ISSUE TITLE
Static method calls always considered have side effect

### ISSUE THREAD

**Issue by ashi009** [rollup/rollup#3250]
- Rollup Version: 1.27.3
- Operating System (or Browser): macOS 10.15.1
- Node Version: v12.12.0

### How Do We Reproduce?

https://rollupjs.org/repl/?version=1.27.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwQSUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU3RCU1Q24lNUN0c3RhdGljJTIwbSgpJTIwJTdCJTdEJTVDbiU3RCU1Q24lNUNubmV3JTIwQSgpJTNCJTVDbkEubSgpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior

Both call exprs are removed.

### Actual Behavior

The call to the empty static method is kept.

**Comment by shellscape** [comment]
@lukastaegert I think the issue here is that `new A()` could produce side effects, but it's not really doing anything at present, so it's trimmed. The static method call is in the same boat - it's not doing anything so should it be removed? Or is the problem here reversed whereby neither the creation of a new `A` nor the static method call should be removed?

**Comment by lukastaegert** [comment]
No, your first take is correct, the static method call should be removed. This is not implemented yet, just as any advanced class related optimizations. Static methods could be a low-hanging fruit, though

**Comment by shellscape** [comment]
Sounds good. I'll try to tackle that.

**Comment by lukastaegert** [comment]
The longer I think about, I would not underestimate this one. To work sufficiently reliable, you would need a logic to track reassigned static properties, similar to how ObjectExpression does it. Also, it should handle multiple methods with the same name correctly. Treeshaking is always a dangerous game.

**Comment by lukastaegert** [comment]
This will be resolved in #4018:
https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwQSUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU3RCU1Q24lNUN0c3RhdGljJTIwbSgpJTIwJTdCJTdEJTVDbiU3RCU1Q24lNUNubmV3JTIwQSgpJTNCJTVDbkEubSgpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE
