### ISSUE TITLE
AMD modules unnecessarily uses exports when preservedModules is enabled

### ISSUE THREAD

**Issue by mgol** [rollup/rollup#3258]
### Expected Behavior / Situation

When compiling source from ES modules to AMD with `--preserveModules`, I'd expect default exports in the module to be transformed into unwrapped return values in the resulting AMD module. An example:

Input:
```js
export default window.document;
```

Output:
```js
define( function() {
	"use strict";

	return window.document;
} );
```

### Actual Behavior / Situation

The module using a default export is converted to one putting what was exported into `exports.default`:

Input:
```js
export default window.document;
```

Output:
```js
define(['exports'], function (exports) { 'use strict';

	var document = window.document;

	exports.default = document;

});
```

Check with Rollup `1.25.2` & `1.27.5`.

### Modification Proposal

At least when a module doesn't use named exports but only default ones, I'd expect the generated AMD modules to be using the usual `return`-style exports.

This is, in particular, important to jQuery which wants to transform its new ES modules-based source back to AMD keeping previous idiomatic semantics of those modules.

Ref https://github.com/rollup/rollup/issues/2979#issuecomment-555619356

**Comment by lukastaegert** [comment]
Fix at #3265
