### ISSUE TITLE
[Need help]How to config the watch options to output the log of the code compilation in the terminal with rollup.watch api?

### ISSUE THREAD

**Issue by Sara2009** [rollup/rollup#3259]
in the build.js
```javascript
const watchOptions = {
        ...getInputOptions(true),
        output: [getOutputOptions()],
        watch: {
            exclude: 'node_modules/**',
            clearScreen: true,
        }
    };
const watcher = rollup.watch(watchOptions);
watcher.on('event', stats => {
       
 });
```
Then in the package.json
`"watch": "node ./watch.js",`

I run `npm run watch`. There is no log output in the terminal.

How can I get the output log of the rollup compilation just like rollup CLI?

**Comment by shellscape** [comment]
> 👉🏽 Need help or tech support? Please don't open an issue! Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs.

**Comment by Sara2009** [comment]
> > 👉🏽 Need help or tech support? Please don't open an issue! Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs.

Sorry to bother you~ I'll close this issue. Thanks a lot.

**Comment by nshen** [comment]
> > > 👉🏽 Need help or tech support? Please don't open an issue! Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs.
> 
> Sorry to bother you~ I'll close this issue. Thanks a lot.

How did you resolve this?

**Comment by Sara2009** [comment]
> > > > 👉🏽 Need help or tech support? Please don't open an issue! Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs.
> > 
> > 
> > Sorry to bother you~ I'll close this issue. Thanks a lot.
> 
> @Sara2009 How did you resolve this?

I just use the watch event to custom the output log. 
```javascript
let startBundleTime;
watcher.on('event', (event) => {
        switch (event.code) {
            case 'START':
                startBundleTime = Date.now();
                break;
            case 'BUNDLE_START':
                console.log(`bundles ${event.input} → ${Array.isArray(event.output) ? event.output.join(',') : event.output}`);
                break;
            case 'BUNDLE_END':
                console.log(`created ${Array.isArray(event.output) ? event.output.join(',') : event.output} in ${Date.now() - startBundleTime}ms`);
                break;
            case 'END':
                console.log('wainting for changes');
                break;
            default:
                break;
        }
        // event.code can be one of:
        //   START        — the watcher is (re)starting
        //   BUNDLE_START — building an individual bundle
        //   BUNDLE_END   — finished building a bundle
        //   END          — finished building all bundles
        //   ERROR        — encountered an error while bundling
        //   FATAL        — encountered an unrecoverable error
    });
```
I don't find a way to config as easy as webpack:
```javascript
compiler.run((err, stats) => {
            if(err) {
                console.log(err);
            } else {
                console.log(stats.toString({
                    colors: true,
                    chunks: false
                }))
            }
        });
```
