### ISSUE TITLE
[!] Error: Could not resolve './something' from src\js\somethingelse.tsx 

### ISSUE THREAD

**Issue by croban** [rollup/rollup#3261]
I have following rollup.config:

```
// Rollup plugins
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
    input: 'src/consent/consent.tsx',
    output: {
        format: "iife",
        file: "build/consent.js",
        sourceMap: "inline",
        name:'consent' 
    },
    plugins: [
        resolve({
            mainFields: ['main', 'jsnext:main', 'browser'],
        }),
        commonjs({

        }),
        babel({
            exclude: './node_modules/**',
            extensions: ['.js', '.jsx', '.ts', '.tsx'],
        }),
    ],
};
```

consent.tsx imports views.tsx

`import { Views } from "./views";`

and views.tsx looks like this:

```
import * as React from "jsx-dom"

export module Views {
    export const Layout = () => <div>
        <h1 className="what">Hello world</h1>
        <p>
            Lorem ipsaaaum dolor sit, amet consectetur
            adipisicing elit. Quae sed consectetur
            placeat veritatis
            illo vitae quos aut unde doloribus, minima eveniet et
            eius voluptatibus minus aperiam
            sequi asperiores, odio ad?
            </p>
    </div>;
}
```

babel.config:

```
{
	"presets": [
		"@babel/typescript",
		["@babel/env", {
			"targets": "last 2 version",
			"modules": false
		}]
		,"@babel/preset-react"
	],
	"plugins": [
		"@babel/proposal-class-properties",
		"@babel/proposal-object-rest-spread",
		["@babel/plugin-transform-typescript", {
			"allowNamespaces": true
		}]
	]
}
```

when I execute
`rollup -c`
Could not resolve './views' from src\consent\consent.tsx 

Do I miss some configuration or?

**Comment by lukastaegert** [comment]
Hi @croban, did you try asking elsewhere first, e.g. on Stackoverflow? This looks mostly like a support request, and Rollup's issues is not the most likely place where you will get a quick response. There are only few developers here who prefer to focus on actionable bugs and feature requests and will probably ignore this issue. Note that it is not that we would not love to help you, but it is that we just do not have the resources to answer support requests, especially if they need some digging. Otherwise, there would be no Rollup development.

**Comment by croban** [comment]
Okay, I will try to get an answer on stackoverflow, but it is strange for me because executing 
babel build does not cause this error:
`babel src/consent --out-file src/consent/build/consent.js --extensions \".ts,.tsx\" --source-maps inline`

**Comment by lukastaegert** [comment]
If you can set up a minimal repro, e.g. a gist or a repository, this would make it easier to debug this. Could also be a Windows path name issue considering the error message with mixed forward and backward slashes.

**Comment by croban** [comment]
Thx @lukastaegert 
Here is the [gist](https://gist.github.com/croban/b0bd5196e634cfbf1fd7d28ef041e367)
Is that okay?

**Comment by croban** [comment]
My fault, I haven't specified ts(x) extensions for resolve plugin.
credits goes to:  [@a-tarasyuk](https://github.com/a-tarasyuk/rollup-typescript-babel/blob/master/rollup.config.js)

final config:
```
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

const extensions = ['.js', '.jsx', '.ts', '.tsx'];

export default [{
    input: 'src/consent/consent.tsx',
    output: {
        format: "iife",
        file: "build/consent/consent.js",
        sourceMap: "inline",
        name: 'sui.consent'
    },
    watch: {
        include: ['src/consent/consent.tsx', 'src/utils/cookies.ts'],
        exclude: 'node_modules/**'
    },
    plugins: [
        resolve({
            mainFields: ['module', 'main', 'jsnext:main', 'browser'],
            extensions
        }),
        commonjs(),
        babel({
            exclude: './node_modules/**',
            extensions,
        }),
    ],
}];
```
