### ISSUE TITLE
how to export many inputs as .mjs files

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#3262]
Documentation Is:

- [x ] Missing
- [ x] Needed
- [ x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I want to bundle some files and i expect the result to be .mjs including all chunks-xxxxx.mjs

used config.
```
import commonjs from "rollup-plugin-commonjs";
import nodeResolve from "rollup-plugin-node-resolve";
import removeSteal from "rollup-plugin-remove-steal"
import { terser } from "rollup-plugin-terser";

export default [{
    input: [
        "can/es/can-route-pushstate",
        "can/es/can-route",
        "can/es/can-type",
        "can-stache-element"
    ],
    output: {
      dir: "can-bundle",
      format: "esm",
    },
    plugins: [
      commonjs({
        // non-CommonJS modules will be ignored, but you can also
        // specifically include/exclude files
        include: [ "./index.js", "node_modules/**" ], // Default: undefined
  
        // if true then uses of `global` won't be dealt with by this plugin
        ignoreGlobal: false, // Default: false
  
        // if false then skip sourceMap generation for CommonJS modules
        sourceMap: false // Default: true
      }),
        nodeResolve({ mainFields: ['jsnext', 'module', 'main'] }),
        removeSteal({}),
        terser()
    ]
  }];
```

### Your Proposal for Changes
define a default extension like .mjs for the output

**Comment by lukastaegert** [comment]
You can adjust extensions via https://rollupjs.org/guide/en/#outputentryfilenames and https://rollupjs.org/guide/en/#outputchunkfilenames

If you have a suggestion from where in the docs we should link here, PR always welcome.

**Comment by frank-dspeed** [comment]
@lukastaegert thats exactly what i was looking for. i think this information needs to get moved from advanced to standard case as this is the standard case. 

The Standard case out of my view is to bundle a es6+ project with some cjs dependencys as es6+ modules.

**Comment by lukastaegert** [comment]
Well, the standard case used to be creating a single bundle and use the `fileName` option, in which case you have full control over the extension as well. But these should probably mentioned together with the introduction of the `dir` option.

**Comment by milesj** [comment]
@lukastaegert While using those options works, any rollup helpers that are included in the output will fail mjs since they are `js` files.

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/milesj/Projects/boost/packages/cli/mjs/_virtual/_rollupPluginBabelHelpers.js' imported from ./mjs/components/HiddenInput.mjs
```

Seems like these helpers should use `.mjs` file extension (they are already using import/export syntax) to match output files. The same could be said for `.cjs` also.

**Comment by lukastaegert** [comment]
Interesting question that should probably be raised with the plugins in question.

**Comment by frank-dspeed** [comment]
i think this is solved today. the input({}) Object notation + chunk and other filename pattern support config settings solve all the cases really well in my case also the helpers get set to the correct extension via the chunk filename pattern as the helpers do always get a shared chunk
