### ISSUE TITLE
Config input field should have precedence over cli input flag

### ISSUE THREAD

**Issue by yongjun21** [rollup/rollup#3263]
### Expected Behavior / Situation

Config can take the form of a function to allow more fine tuned config based on cli arguments. However, when using cli, leftover arguments are taken to be the inputs and these inputs have precedence over config inputs thus prevent us from modifying input in the function config.

What I want to do

```js
// rollup.config.js
export default args => {
  const inputs = args.input || getDefaultInputs()
  return inputs.map(getConfig)
}

function getConfig (input) {
  return {
    input: prefix + input // modify input
  }
}
```

### Actual Behavior / Situation

When executing `rollup someInput -c`, the above code fails as the prefix is not applied since cli input has precedence over config input.

### Modification Proposal

Config input field should have precedence over CLI input flag

**Comment by lukastaegert** [comment]
The current idea is that CLI always has precedence over config as it is meant for ad-hoc overrides. If you do not want it to be an override, you can just remove parameters from the command object. I.e. in your example, you should do

```js
// rollup.config.js
export default args => {
  const inputs = args.input || getDefaultInputs()
  delete args.input; // this means you handled the input and Rollup should not handle it
  return inputs.map(getConfig)
}
...
```

Admittedly, this is not mentioned in the docs, maybe we should do that.

**Comment by yongjun21** [comment]
Thanks. Is working now
