### ISSUE TITLE
rollup.config.coffee

### ISSUE THREAD

**Issue by MegaJSDeveloper** [rollup/rollup#3268]
Please add native `rollup.config.coffee` support. Gulp and Webpack have native CoffeeScript config support, if CoffeeScript is installed.

`rollup.config.js`:
```javascript
import 'coffeescript/register'
import './rollup.config.coffee'
```

is not works:
```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
rollup.config.coffee (7:12)
```

`rollup --config rollup.config.coffee` not works too

**Comment by jacksteamdev** [comment]
This is something that a plugin would handle, not Rollup itself.

A quick Google search returns [rollup-plugin-coffee-script](https://www.npmjs.com/package/rollup-plugin-coffee-script) and [rollup-plugin-coffee2](https://www.npmjs.com/package/rollup-plugin-coffee2).

**Comment by MegaJSDeveloper** [comment]
@jacksteamdev we are talking about a coffeescript configuration file.

**Comment by shellscape** [comment]
@MegaJSDeveloper this is an important part of the Bug Report issue template, and why your issue hasn't had many replies:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Work to isolate the problem and provide the exact steps in this issue, or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

It doesn't help that CoffeeScript is a dying language, and it's not likely that anyone spends time to triage this until a proper reproduction is provided. It's surprising that this hasn't been closed yet since the issue doesn't provide a reproduction, and the issue template was removed. Once you add a repro, you'll probably receive some help with this.

**Comment by MegaJSDeveloper** [comment]
@shellscape CoffeeScript is a *NOT* dying language, by virtue of your incompetence, you have fallen victim to this obsolete myth. coffeescript is, thanks to me, an actively developing language.

**Comment by Rich-Harris** [comment]
@MegaJSDeveloper We're not going to add CoffeeScript support.

Furthermore, your unwarranted language violates of Rollup's [code of conduct](https://github.com/rollup/rollup/blob/master/CODE_OF_CONDUCT.md). I'm closing and locking this issue. If you carry on like this, we'll have no choice but to block you.
