### ISSUE TITLE
How to turn off color output

### ISSUE THREAD

**Issue by kikonen** [rollup/rollup#3270]
How to turn off color output from rollup?

Problem is that generated output is unreadable, green, cyan and yellow colors outputted by rollup are unreadable in console (yes, I most certainly don't use black background color in terminal).

So far I noticed that I can patch "tc.enabled" to false in node_modules/rollup/dist/bin/rollup. However, this is naturally a bit inconvenient.

**Comment by shellscape** [comment]
> 👉🏽 Need help or tech support? Please don't open an issue! Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs.

If this is a documentation issue, please edit your issue and insert the Documentation issue template.

**Comment by lukastaegert** [comment]
Not sure it is a documentation error, there might actually not be an easy way to do that

**Comment by kikonen** [comment]
For me it seems that this flag controls the logic, and I failed to find other references in code to toggle this flag expect this const.

node_modules/rollup/dist/bin/rollup
```
const tc = {
    enabled: process.env.FORCE_COLOR ||
        process.platform === "win32" ||
        (process.stdout.isTTY && process.env.TERM && process.env.TERM !== "dumb")
};
```
Thus there appears to be some environment variable, which forces color on, but my desire is exact opposite of that. And messing up with TERM is kind-of-no-go option.

**Comment by lukastaegert** [comment]
We could change the use of `FORCE_COLOR` to go two ways, i.e. if it is present, it could either force it on or force it off. PR welcome.

**Comment by kikonen** [comment]
Ack, I try to look into it

**Comment by GrosSacASac** [comment]
See also https://no-color.org/

**Comment by kikonen** [comment]
Btw, this is my problem case :)

![image](https://user-images.githubusercontent.com/478935/70262504-236ef500-179d-11ea-9105-2c36dfb934f6.png)
