### ISSUE TITLE
Input from string/input stream

### ISSUE THREAD

**Issue by shacoshe** [rollup/rollup#3276]
### Feature Use Case
being forced to work with files is very limited and slow.  i could do much more with rollup if it was easier. '@rollup/plugin-virtual' is a complicated solution. 

### Feature Proposal
allow the input to be a string/input stream please.

**Comment by shacoshe** [comment]
rollup is giving me allot of pain. 
https://stackoverflow.com/questions/58976769/rollup-js-how-to-import-additional-files-without-changing-source-files
lets say i am generating a new file. how can i set the working directory ? 
this forces me to create a new files where my source file is located since all imports are relative ?

**Comment by shellscape** [comment]
Since `@rollup/plugin-virtual` does exist for that purpose, I'd be interested in improving it to where it was not perceived as complicated.

As for your to your original post, that sounds like it should be opened as a separate documentation issue.

**Comment by lukastaegert** [comment]
If the question is how to pipe files into Rollup, e.g.

```
echo “export const x = 42” | rollup -f cjs 
```

I think this is actually not yet possible. PRs are definitely welcome, even incomplete ones that may be refined.

**Comment by shacoshe** [comment]
> If the question is how to pipe files into Rollup, e.g.
> 
> ```
> echo “export const x = 42” | rollup -f cjs 
> ```
> 
> I think this is actually not yet possible. PRs are definitely welcome, even incomplete ones that may be refined.

thank you very much for the comment.

**Comment by shacoshe** [comment]
thank you for the comments i am not familiar with rollup code. how can i get help ?

**Comment by shacoshe** [comment]
i had to write a simple plugin that get the first file loaded and add imports to it...
its working. is it alright  to do so ?

`function includeFiles (input, include) {
    var loadCalled = true;
    if(include.length > 0) {
        var importFiles = '';
        loadCalled = false;
        for(i in include) {  importFiles += 'import \'' + include[i].replace(/\\/g, '/') + '\';\n'; }
    }
    return {
        name: 'include-files',
        resolveId ( source ) {
            return null;
        },
        load ( id ) {
            if(!loadCalled) {
                loadCalled = true;
                return importFiles + fs.readFileSync(id, 'utf-8');;
            }
            return null;
        }
    };
}`

**Comment by PierBover** [comment]
> Since `@rollup/plugin-virtual` does exist for that purpose, I'd be interested in improving it to where it was not perceived as complicated.
> 
> As for your to your original post, that sounds like it should be opened as a separate documentation issue.

@shellscape does `@rollup/plugin-virtual` allow for a string to Rollup's input?

Maybe I'm missing something but from the docs it seems it's meant to create virtual modules that will be imported in the source code, rather than providing Rollup with code to start bundling.

**Comment by shellscape** [comment]
@PierBover it's not entirely clear what you're trying to accomplish. If the `virtual` plugin doesn't do what you need, you could try taking a look at https://github.com/rollup/awesome for another plugin or solution that might work for you

**Comment by PierBover** [comment]
@shellscape I'd like to pass a string of code to Rollup's input instead of a path to a file.

This plugin used to have that functionality:
https://github.com/TrySound/rollup-plugin-memory

But it was deprecated in favor of `@rollup/plugin-virtual` which AFAIK can't do that.

**Comment by lukastaegert** [comment]
The syntax is different but what it does is exactly the same, except that `@rollup/plugin-virtual` is much more powerful because any module can be virtual, not only the entry module.

This is what you probably want:

```js
import virtual from '@rollup/plugin-virtual';

export default {
  input: 'entry',
  // ...
  plugins: [
    virtual({
      entry: `export default 'whatever'`,
    })
  ]
};
```

So your entry point is a virtual module, and that can be any string.

**Comment by PierBover** [comment]
Thanks  @lukastaegert !

I will submit a PR to add that to `@rollup/plugin-virtual` docs. This is not quite obvious to Rollup beginners like myself.
