### ISSUE TITLE
format cjs not export default value

### ISSUE THREAD

**Issue by MegaJSDeveloper** [rollup/rollup#3284]
i write:

```javascript
export default class Cat{}
export var ololo = 11
```

i want:
```javascript
module.exports = class Cat{}
module.exports.default = module.exports
module.exports.ololo = 11
```

i get:
```javascript
module.exports.default = class Cat{}
module.exports.ololo = 11
```

nodejs api is:
```javascript
var Module = require('module')
```

nodejs api **ISNT**:
```javascript
var Module = require('module').default
```

nodejs api **ISNT**:
```javascript
let {Module} = require('module')
```

how can I build the library correctly for node js api?
---

p.s. Unfortunately your opinion about the default export is not interesting nodejs developers. Rollup has option for **CORRECT** export by default for nodejs?

**Comment by lukastaegert** [comment]
What is correct here is solely your personal opinion, please be respectful. Rollup should have even given you a warning that what you get is probably not what you want.

There are reasons for why it is the way it is which are rooted in the incompatibility between ES modules and CommonJS modules. This makes it possible for the CJS output to be consumed via an ES module aware bundler while correctly mapping object properties back to named exports. This pattern is also used by other bundlers.

Your suggestion would work in your example but would not work here:

```js
// input
export default null
export var ololo = 11

// output
module.exports = null
module.exports.default = module.exports // runtime error
```

The only way to get the desired result you want is to ONLY use a default export and attach everything there:

```js
// input
export default class Cat {}
Cat.default = Cat;
Cat.ololol = 11;

// output
'use strict';

class Cat {}
Cat.default = Cat;
Cat.ololol = 11;

module.exports = Cat;
```

Note that in that case, an ESM bundler will probably only detect a default export on your module, but apparently you do not care about this anyway.

**Comment by MegaJSDeveloper** [comment]
@lukastaegert Sorry if it seemed to you that I was rude to you, I am from Russia and use Google translator =)

Why not make a flag doing what I say?
```javascript
module.exports = Cat;
```

**Comment by fregante** [comment]
This is a pretty popular request due to the confusion between ESM and CJS. Probably searching “commonjs default export” in this repo will show you other examples and possible solutions to it.

**Comment by fregante** [comment]
I found this discussion https://github.com/rollup/rollup/issues/1961#issuecomment-423037881

**Comment by 1977474741** [comment]
> @lukastaegert抱歉，如果您认为我对您无礼，我来自俄罗斯并使用谷歌翻译=）为什么不按照我说的做一面**旗帜呢？**
> 
> 格式`"node"`
> 
> ```js
> // code
> export default Cat
> export var lol = 11
> 
> // compile to:
> module.exports = Cat;
> module.exports.lol = 11;
> ```
> 
> 如果 Nodejs 开发人员写了这个，他也会得到运行时错误 =)
> 
> ```js
> module.exports = null
> module.exports.lol = 11;
> ```
> 
> 我们可以构建两个版本的库：
> 
> `package.json`
> 
> ```json
> {
> "main": "index.js",
> "module": "index.es.js"
> }
> ```
> 
> `rollup.config.js`
> 
> ```js
> var pkg = require('package.json');
> 
> output: [
>   {file: pkg.main, format: 'node', sourcemap: true},
>   {file: pkg.module, format: 'es', sourcemap: true}
> ]
> ```

这种方法我试了，在外部不管你用import还是require，他最终指向的路径都是module的配置
