### ISSUE TITLE
Cannot import index.js by referencing parent directory

### ISSUE THREAD

**Issue by SquarePear** [rollup/rollup#3285]
- Rollup Version: v1.27.13
- Operating System (or Browser): macOS 10.15.1
- Node Version: v13.3.0

### How Do We Reproduce?

https://github.com/SquarePear/rollupbug3285

Create a file that imports another index.js file by referencing the parent directory

```js
// app.js
import test from './test'
```

```js
// test/index.js
console.log('Success')
```

```
app.js
test/
|-- index.js
```

### Expected Behavior
Importing `test/index.js` and logging on run

`Success`

### Actual Behavior
`Error: Could not resolve './test' from app.js`

### Extra Information
If you change `import test from './test'` to `import test from './test/index'`, it works fine, so it isn't just an config / file not found problem.

**Comment by shellscape** [comment]
>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Work to isolate the problem and provide the exact steps in this issue, or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Because the issue you're reporting relies on a directory structure to reproduce, option #3 is going to be required to properly triage.

**Comment by SquarePear** [comment]
https://github.com/SquarePear/rollupbug3285

**Comment by shellscape** [comment]
Thanks for providing a reproduction. Please see #346 and the description of the cause of the problem and resolution - I've confirmed that it resolves your scenario. I was able to find that issue using _"rollup could not resolve index.js"_ as the google search term and it was the first result.

**Comment by yfwz100** [comment]
Can you provide a working example?

**Comment by lukastaegert** [comment]
Rollup core does not resolve index files as this is not standard behaviour across JavaScript runtimes (e.g. your browser does not support this either). You need `@rollup/plugin-node-resolve` for that.
