### ISSUE TITLE
After rollupjs is packaged into js, is there any way to avoid the static file path error referenced by resolve (__ dirname, './test.json')?

### ISSUE THREAD

**Issue by rxliuli** [rollup/rollup#3289]
It is mainly used in the development environment __dirname + relative path, after packaging is a file and the dependent files have not been copied over, so problems will occur
Throw all those files that need to be resolved to a resource directory under the project root directory in some way, and then access them with an absolute path relative to the project root path (if you have used a dependency management tool such as maven, then Can understand this approach ...)
Or is there some kind of rollup plugin that can automatically compile and copy the resource files that depend on resolve in the project to the packaged directory at compile time?

Directory before compilation

- src
  - index.js
  - babel
    - plugin.js
    - resource
      - babel.config.js

Want the compiled directory

- dist
  - bundle.js
  - resource.xsd91
    - babel.config.js

**Comment by shellscape** [comment]
Thanks for opening an issue. Unfortunately this isn't a support forum for Rollup. Citing the issue template(s):

>  Please - do not - remove this template.
>   Please - do not - skip or remove parts of this template.
>   Or your issue may be closed.
> 
>   👉🏽 Need help or tech support? Please don't open an issue!
>   Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

You can consult the Rollup Awesome list for plugins that might help you as well https://github.com/rollup/awesome
