### ISSUE TITLE
Trying to rollup Vue with TypeScript and vue-property-decorator

### ISSUE THREAD

**Issue by bhabgs** [rollup/rollup#3291]
As the title says, and I don't have any code example right now, how is it so impossible to combine Rollup, Vue, Typescript and vue-property-decorator? Whenever I try it wants to add vue-property-decorator as an external dependency. Any link to a working solution would be appreciated.
[source code address https://github.com/zx-js/Mobile-Design](https://github.com/zx-js/Mobile-Design)

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).
