### ISSUE TITLE
Option to fail if any externals detected

### ISSUE THREAD

**Issue by geelen** [rollup/rollup#3293]
### Feature Use Case

I am writing a build tool that allows for user input to specify the names of plugins, which are then passed through to rollup. Example:

```json
{
  "pipeline": [
    "@fab/some-core-plugin",
    "@other-org/community-plugin",
    "./my-single-file.js"
  ]
}
```

Each of those statements get converted into `require` statements in a file that gets rolled up.

### Feature Proposal

I'd like to be able to invoke the rollup JS api `rollup.rollup(...)` in such a way that _any_ unexpected externals throws an exception. I'm already doing a few checks ahead of the compilation but for some reason the rollup module resolution is not finding certain files. At the moment I get this warning:

```
'@other-org/community-plugin' is imported by user-defined-pipeline, but could not be resolved – treating it as an external dependency
```

Ideally, the build would just crash with an exception, something like

```
ERROR: '@other-org/community-plugin' is imported by user-defined-pipeline, but could not be resolved. Rollup build cannot continue
```

Forgive me if such a thing is already possible but I couldn't figure out how.

**Comment by lukastaegert** [comment]
You can add a custom `onwarn` handler to the options that throws for unexpected external dependencies:

```js
rollup.rollup({
  onwarn(warning, handler) {
    if (warning.code === 'UNRESOLVED_IMPORT') {
      throw new Error(warning);
    }
    handler(warning);
  },
  // ... other options
}
```

Calling `handler(warning)` will trigger the default warning handler, which is logging the warning to the console. You can also skip this to swallow other warnings. See https://rollupjs.org/guide/en/#onwarn for more details.

**Comment by geelen** [comment]
Awesome, that totally fixed my problem! Now I can collect all the `UNRESOLVED_IMPORT`s in the build and throw them all in a nice error at the end 👍

**Comment by lukastaegert** [comment]
Glad I could help! If you are interested or want more inspiration, Rollup's own CLI does something very similar for a wider range of warnings: https://github.com/rollup/rollup/blob/master/cli/run/batchWarnings.ts#L222
