### ISSUE TITLE
Specify `banner` and stuff via CLI?

### ISSUE THREAD

**Issue by tomekwi** [rollup/rollup#330]
I usually specify my config through a `rollup.config.js`. But I found myself wanting to override `--banner` and `--intro` via CLI. As you see [in this gist](https://gist.github.com/tomekwi/988a0371af0c8ce24339), it doesn’t work.

Do you eventually want to port all JS options (at least those that make sense) to the CLI?

**Comment by Rich-Harris** [comment]
No reason not to have those options in there. Would be an easy win for anyone out there looking to earn their contributor stripes :grinning:

**Comment by Rich-Harris** [comment]
Forgot to close this issue – supported in latest releases

**Comment by tomekwi** [comment]
:+1: Great news!
