### ISSUE TITLE
Got an error when packing node_modules\canvas\build\Release\canvas.node

### ISSUE THREAD

**Issue by HelloDennis** [rollup/rollup#3306]
**rollup version:** v1.27.14
**node version:** v10.15.3
**npm version:** 6.13.4
**syster:** windows 10

When I pack it, i got this error:

> **[!] Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)**
> node_modules\canvas\build\Release\**canvas.node** (1:2)
> 1: MZ� �� � @ � � �!�L�!This program cannot be run in DOS mode.
> ^
> 2: $ �=�\j��\j��\j��:n��\j��:i��\j��:o�\j�<����\j��4i��\j��4n��\j��\j�u\j��4o��\j��:k��\j��\k�G\j�85c��\j�85j��\j�85���\j�85h��\j�Rich�\j�
> 0� p l P p �. @ .text h3 4 `.rdata �, P . 8 @ @.data
> � @ B
> �%I ���%�H ���%"I ���%�F ���%"G ���%�H ���%�F ���%�G ���%�G ���%�H ���%�F ���%*F ���%�F ���%�H ���%�G ���%"H ���%�F ���%�E ���%G ���%"G ���%G ���
> G ���%jG ���%JG ���%�F ���%�F ���%�F ���%�G ���%G ���%:H ���%rG ���%�E ���%RE ���%�G ���%:G ���%zG ���%�F ���%�G ���%�G ���%RE ���%JG ���%�E ���%F
> ���%�F ���%2E ���%jG ���%�F ���%�E ���%G ���%F ���%�F ���%RG ���%�E ���%"E ���%ZF ���%:E ���%�D ���%�F ���%�D ���%�F ���%�F ���%jG ���%�E ���%�F ��
> �%G ���%�D ���%�E ���%BF ���%�F ���%JE ���%
> 3: F ���%�D ���%�D ���%�E ���%�C ���%*E ���%�D ���%jD ���%�D ���%E ���%�E ���%:D ���%�E ���%�F ���%�C ���%�C ���%*D ���%BE ���%�C ���%�E ���%�C ���%
> rF ���%
> Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

There is a loader for webpack here: https://github.com/Automattic/node-canvas/issues/867.
However, i don't know how to deal with it in rollup.

Is there any plugin which can pack .node files?

Thanks so much!

**Comment by shellscape** [comment]
Please don't ignore Issue or Pull Request templates. Since you are reporting a possible bug, you should have used the Bug issue template and filled it out. Please do that, and make sure to add a proper reproduction. When you've updated your issue properly, we'll be able to triage it.
