### ISSUE TITLE
Bundling: Redundant bare import statements

### ISSUE THREAD

**Issue by clintwood** [rollup/rollup#3308]
### Env
- Rollup Version: 1.27.14
- Operating System (or Browser): linux
- Node Version: v13.2.0

### How Do We Reproduce?
See this example repo: https://github.com/clintwood/rollup-issue
I have included the build output in `build`.

### Expected Behavior
Both `build/entrypoints/app.js` and `build/manual/app.js` should **not** contain the two bare import statements at the top of the file.

### Actual Behavior
Both `build/entrypoints/app.js` and `build/manual/app.js` contain the two redundant (and unused) bare import statements at the top of the file as shown below:
```javascript
import './Intro.js';
import './Main.js';
...
```

**Comment by lukastaegert** [comment]
Rollup "hoists" transitive dependencies of entry points into the entry point file. This does not affect execution order but speeds up the loading process. Without this, running app.js would
1. load and parse app.js
2. see that it depends on Core.js
3. load and parse Core.js
4. see that it depends on Intro.js and Main.js
5. load and parse those
6. run Intro, Main, Core, app

With this optimization, Step 2 will also discover the dependencies on Intro and Main and make the waterfall two steps shorter. There is a request to add a flag to disable this but no work has been done yet.

**Comment by clintwood** [comment]
@lukastaegert thank you for the quick response!

Can I assume the optimization would not occur for dynamic imports then - which is my primary concern?

**Comment by lukastaegert** [comment]
It should also happen for dynamic imports as they would also benefit from this optimization e.g. in a browser environment. Adding a flag should not be too complicated.

**Comment by lukastaegert** [comment]
Ah, you probably meant something different than I did. Only dynamic imports will be hoisted, but the optimization also applies to dynamic entry points:

https://rollupjs.org/repl/?version=1.27.14&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRmR5bmFtaWMnKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmR5bmFtaWMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJ2R5bmFtaWMnKSUzQiU1Q24lNUNuJTJGJTJGJTIwdGhpcyUyMGNodW5rJTIwd2lsbCUyMGNvbnRhaW4lMjBpbXBvcnRzJTIwdG8lMjBib3RoJTIwZGVwMSUyMGFuZCUyMGRlcDIlNUNuaW1wb3J0JTIwJy4lMkZkZXAxJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJkZXAxLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKCdkZXAxJyklM0IlNUNuaW1wb3J0JTIwJy4lMkZkZXAyJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmRlcDIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJ2RlcDInKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by lukastaegert** [comment]
Otherwise this would prevent lazy loading

**Comment by clintwood** [comment]
Awesome - that's what I expected!
Thank you for your detailed replies!
