### ISSUE TITLE
don't supports data: urls in dynamic imports and static

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#3309]
- Rollup Version: latest
- Operating System (or Browser): NodeJS
- Node Version: 13.2

### How Do We Reproduce?

```js
import 'data:text/javascript, console.log('Buhhh')'
import me from 'data:application/json, { "my": 'json''}
import('data:application/json, { "my": 'json''})
``` 

### Expected Behavior
codesplitting the result tree shake it 

### Actual Behavior
no tree shake but at last the object is in place

Would be nice if we could lineout concepts to handle that
as i have made a loader for such stuff
https://github.com/direktspeed/esm-loader

**Comment by shellscape** [comment]
@frank-dspeed please fill out the appropriate issue template - our issue templates aren't optional.

**Comment by frank-dspeed** [comment]
@shellscape done

**Comment by lukastaegert** [comment]
It should not be too difficult to handle this. The concept would be:

```js
{
  resolveId(id) {
    if (isDataUrl(id)) {
      return id;
    }
    return null;
  },
  load(id) {
    if (isDataUrl(id)) {
      return getCodeFromDataUrl(id);
    }
    return null;
  }
}
```

Of course you would need to implement `isDataUrl` and `getCodeFromDataUrl`. If you do it this way, it would also work for static imports.

**Comment by shellscape** [comment]
If you're interested in this feature being supported by a [core plugin](https://github.com/rollup/plugins), please open a [New Plugin Request](https://github.com/rollup/plugins/issues/new?template=NEW_PLUGIN.md) issue over at [rollup/plugins](https://github.com/rollup/plugins).

**Comment by shellscape** [comment]
Closing in favor of https://github.com/rollup/plugins/issues/125.
