### ISSUE TITLE
Duplicate import declarations in the same file

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#331]
duplicate `import` declarations in the same file seems to break Rollup. Here's a basic example:
### In some file:

```
import * as controllers from 'bundle';
```
### contents of file `bundle.js`

```
import a from 'a';

export function foo(){
    return a;
}

import a from 'a';

export function bar(){
    return a;
}
```

tldr;

I am using Gulp to bundle all files in a folder and generate some file which has X amount of exports (from each file in the folder), the reason is so I could do something like this:

```
import * as controllers from 'controllers_bundle';
```

which will import all my controllers' functions so I won't have to manually write each import for each controller.

Anyway, when then gulp task combines the files, I get one big file which has many import declaration which repeat themselves since those controller files are mostly importing the same files themselves.

I then get a Duplicate declaration error on my bash console and my everything stops. I would think Rollup would be smart enough to internally check if an imported file has in itself duplicate import declarations and remove them...

**Comment by eventualbuddha** [comment]
In your example, `bundle.js` is indeed invalid because it tries to bind `a` twice. How is `bundle.js` being created?

**Comment by yairEO** [comment]
Gulp concatenates all the files in some directory and sub-directories. I think it's pretty easy thing to do when there's a big list of stuff to import, in many places, and that list keeps changing and you want to automate things. Wouldn't you agree it's very tempting to do what I just did?

**Comment by eventualbuddha** [comment]
Why not let rollup do it? You can specify the entry point and build `bundle.js` using guaranteed-correct ES6 semantics.

**Comment by yairEO** [comment]
i want one file with many exports, so i could import that fire anywhere. That one file is a combined number of files. It's automated, rollup cannot automate this without explicitly importing all those files manually and then exporting again as variables. 

Let's say you need to import tons of files, why writing all the import rules manually when gulp can just concatenate all of them to one file which you could import anywhere you want?

**Comment by eventualbuddha** [comment]
> Let's say you need to import tons of files, why writing all the import rules manually when gulp can just concatenate all of them to one file which you could import anywhere you want?

You can't simply combine ES6 modules like this and expect it to work. Even CommonJS will have problems if you do that. In both cases, relative imports will completely break. If you happen to name two functions or variables the same name it'll break. Using `rollup` to build the bundle will prevent all these issues.

The problem, though, is that rollup only supports a single entry point and so imports must all be specified, as you said. To address that you could simply have a build step that creates the entry file automatically with a list of imports for each file you want.

**Comment by yairEO** [comment]
Yes relative paths might break if all the concatenated files aren't on the same level originally. If they are on the same level then simply deleting duplicate imports should work.

I've resorted to what you've said, created a file which imports ask the others and re-exports everything

**Comment by Victorystick** [comment]
@yairEO Why not generate something like this?
```js
// controllers.js
export { default as Foo } from './xyz/Foo.js';
export { default as Bar } from './Bar.js';
```

Each file can export it's controller as the default export. The controllers file combines all their exports through a single interface.

**Comment by yairEO** [comment]
@Victorystick - I tested this method, as you suggested. it works, but the problem is that when I import that `controllers.js` file, it will dump all the code from within that file in the Rollup process. I mean, normally I would expect something to be included in the "rolledup" code one it is actually being used. so an import declaration will normally be ignored if it isn't being refereed anywhere in the code. 

Why is that anyway? Can't Rollup just not add `Foo` and `Bar` if they aren't being used?

**Comment by maraisr** [comment]
Think this is till an issue..

https://github.com/maraisr/mosaic.js/blob/master/dist/mosaic.js#L55 Is repeated twice in the script.

**Comment by TrySound** [comment]
@maraisr Did you try the latest version of rollup?

**Comment by maraisr** [comment]
@TrySound well yeah - if you head on over to [package.json](https://github.com/maraisr/mosaic.js/blob/master/package.json) for the project, you'll see what versions im using.. Which is 0.33.0.

My [rollup.conf.js](https://github.com/maraisr/mosaic.js/blob/master/rollup.conf.js)
My [package.json](https://github.com/maraisr/mosaic.js/blob/master/package.json)

**Comment by Rich-Harris** [comment]
Going to close this as it doesn't look like Rollup is behaving unexpectedly – feel free to reopen a new issue with repro if I'm mistaken

**Comment by Dark-Energy** [comment]
in my project many modules, some modules import other modules, some modules are imported many times. code of this modules duplicated, though names of variables and functions changes. in result code is breaking. may could  build some sort of import graph before doing bundling?
