### ISSUE TITLE
Dont generate additional chunk for always-imported shared code

### ISSUE THREAD

**Issue by yannayl** [rollup/rollup#3310]
### Expected Behavior / Situation
When compiling the following files:
```
// main.js
import { foo } from './shared.js';
import('./dyn_import.js').then(mod => { mod.bar() });

// shared.js
export function foo() { console.log('foo'); }; 

// dyn_import.js
import { foo } from './shared.js';

export function bar() { foo(); console.log('bar'); }; 
```

The code in `dyn_import.js` is loaded if and only if the code of `shared.js` is loaded. Therefore it shouldn't be imported again and there is no need for additional chunk for it. The code of `shared.js` can be embedded in the main chunk.

### Actual Behavior / Situation
Three chunks are generated, one for each file. However, this is very wasteful.

### Modification Proposal
In such a case, generate only two files. Embed `shared.js` code in the main chunk and let the imported code access it.

**Comment by yannayl** [comment]
This might be related to  #2772

**Comment by lukastaegert** [comment]
Sounds like a duplicate of #3124 to me

**Comment by yannayl** [comment]
Correct. Sorry I missed it. Closing
