### ISSUE TITLE
Size of output bundle in CommonJS format is so different from SystemJS and ESM format

### ISSUE THREAD

**Issue by shrinktofit** [rollup/rollup#3315]
- Rollup Version: v1.21.4
- Operating System (or Browser): Windows 10 x64
- Node Version: v10.16.0

### How Do We Reproduce?
For project [cocos](https://github.com/cocos-creator/engine/tree/3d-v1.0.3), sizes of the generated bundle are different.

Because we invoke the rollup API directly, so I can only summary the build result:

Format/terser | Without plugin `terser`  | With plugin `terser`     | With plugin `terser` `modules` forcely set to `true`
-|-|-|-
CommonJS    |`3,287KB`                        |`2,008KB`                       | `2,012KB`
SystemJS       |`3,986KB`                        |`1,703KB`                       | `1,990KB`
ESM               |`3,239KB`                        |`1,707KB`                       | `1,708KB`

You can see that if we do uglify, the CommonJS format increase about 300 KB size than SystemJS and ESM.

1. We use plugins: `babel`, `multiEntry`, `resolve`, `json`, `commonJS`
2. We use default rollup input options except for: `input`, `plugins`

It's hard to dig out why the sizes are so different. We have tried to use compare tools but have no useful conclusion.

Here is also the bundles:
[compare.zip](https://github.com/rollup/rollup/files/4015168/compare.zip)

**Comment by lukastaegert** [comment]
Very hard to say. The differences between e.g. CJS and ESM are very profound and cannot be explained by things Rollup does. For instance you have this:

```js
// esm
function log(message) {
    for (var _len3 = arguments.length, optionalParams = new Array(_len3 > 1 ? _len3 - 1 : 0), _key3 = 1; _key3 < _len3; _key3++) optionalParams[_key3 - 1] = arguments[_key3];
    return ccLog.apply(void 0, [ message ].concat(optionalParams));
}

// cjs
function log(message) {
    for (var _len3 = arguments.length, optionalParams = new Array(1 < _len3 ? _len3 - 1 : 0), _key3 = 1; _key3 < _len3; _key3++) optionalParams[_key3 - 1] = arguments[_key3];
    return ccLog.apply(void 0, [ message ].concat(optionalParams));
}
```

Note how `new Array(_len3 > 1 ?` becomes `new Array(1 < _len3 ?`, which is nothing Rollup would ever do. Also tree-shaking does not seem to work very well for your CJS output, which can only be explained by having different input. There is a big `debugInfos` variable in the unminified output that is unused but not removed. Are there different plugins for these formats? Does Babel/TypeScript/... do some different pre-processing? That's where I would start looking.

**Comment by shrinktofit** [comment]
Thx @lukastaegert .

Under your guide. I debugged into the workflow of rollup.
I found that the codes in each format are exactly same before `render format` phase during chunk rendering.

The `render format` phase, as I know, is built in rollup. It brings first differences to formats.
However the differences are subtle and normal: the CommonJS have some `exports.`, that's all.

The differences become huge after invocation of plugins' `renderChunk` or `transformChunk` API.
After I tried. I found that the plugin `rollup-plugin-terser` contributes a large part of this difference.
When I turn the terser option `modules` to `false`(the option is forced to be `true` by plugin itself, I Hacked),
the size of generated ESM result is close to CJS now.
The `modules` options may infer `terser` to eliminate some global names.

A strange question is SystemJS still keeps minor size.
Is this because SystemJS bundle do not use global variables?

**Comment by kzc** [comment]
The issue is in rollup-plugin-terser, not rollup core:

https://github.com/TrySound/rollup-plugin-terser/blob/9243334fc160ffb4bb9c7bab37449ad61ba42c25/index.js#L33

The plugin only sets `module: true` if the rollup output format is "es" or "esm". Otherwise it unconditionally sets `module: false` for all other rollup output formats - regardless of whether the rollup-plugin-terser `module` option was set by the user:

```
$ cat code.js
export function SomeLongFunctionName(x) {
    console.log(x);
}
SomeLongFunctionName(1);
SomeLongFunctionName(2);
SomeLongFunctionName(3);
```
```
$ cat test1.rollup.js
module.exports = [{
  input: 'code.js',
  output: {
    plugins: [
      require("rollup-plugin-terser").terser({
        module: true, // <-- rollup-plugin-terser incorrectly sets to false for cjs
        output: {
          beautify: true,
        },
      }),
    ],
  },
}];
```
```
$ dist/bin/rollup -c test1.rollup.js -f cjs --silent
"use strict";

function SomeLongFunctionName(o) {
    console.log(o);
}

Object.defineProperty(exports, "__esModule", {
    value: !0
}), SomeLongFunctionName(1), SomeLongFunctionName(2), SomeLongFunctionName(3), exports.SomeLongFunctionName = SomeLongFunctionName;
```

You can work around this plugin bug by using `terser({toplevel: true})` which is largely the same as `module: true`:

```
$ cat test2.rollup.js
module.exports = [{
  input: 'code.js',
  output: {
    plugins: [
      require("rollup-plugin-terser").terser({
        toplevel: true,
        output: {
          beautify: true,
        },
      }),
    ],
  },
}];
```
```
$ dist/bin/rollup -c test2.rollup.js -f cjs --silent
"use strict";

function e(e) {
    console.log(e);
}

Object.defineProperty(exports, "__esModule", {
    value: !0
}), e(1), e(2), e(3), exports.SomeLongFunctionName = e;
```

File an issue with rollup-plugin-terser regarding it not honoring the user setting of `module`.

**Comment by TrySound** [comment]
Is it safe to set module: true for commonjs?

**Comment by TrySound** [comment]
> module (default false) — Use when minifying an ES6 module. "use strict" is implied and names can be mangled on the top scope. If compress or mangle is enabled then the toplevel option will be enabled.


Looks like toplevel is the way to go. I will set it for commonjs format out of the box and will allow users to override both options.

**Comment by kzc** [comment]
It's probably safe to use `toplevel: true` for commonjs/cjs modules. Undeclared global variables would still retain their original names.

But in any case, a minify option should only be set if the property key is not present in the plugin's userOptions.

```diff
-      const normalizedOptions = Object.assign({}, userOptions, {
+      let normalizedOptions = Object.assign({}, userOptions, {
         sourceMap: userOptions.sourcemap !== false,
-        module: outputOptions.format === "es" || outputOptions.format === "esm"
       });
+      if (!Object.prototype.hasOwnProperty.call(userOptions, "module")) {
+        normalizedOptions.module = outputOptions.format === "es" || outputOptions.format === "esm"
+      }
```

**Comment by kzc** [comment]
Looking at the diff, the `sourceMap` option may have the same issue as `module`.

Checking the presence of the property key is preferable over checking the property value because even `undefined` can be a valid user option setting.

**Comment by TrySound** [comment]
IMO plugins should not give an ability to manipulate source maps directly. Should not be any problem here.

**Comment by kzc** [comment]
The plugin fix in https://github.com/TrySound/rollup-plugin-terser/pull/59 is more comprehensive and appears to handle all these cases.
