### ISSUE TITLE
Add newline after banner, custom banner

### ISSUE THREAD

**Issue by thednp** [rollup/rollup#3316]
* Is it possible to have a ONE line banner like `// My Script | License | author | version`?
* Is is possible to add a newline after any kind of banner?

Thanks

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. We also ask that users _not_ remove or ignore issue templates as they're not optional. Please try one of the avenues mentioned above (and in the issue templates).
