### ISSUE TITLE
Cannot import output of Elm app

### ISSUE THREAD

**Issue by ulisses-alves** [rollup/rollup#3322]
- Rollup Version: 1.28.0
- Operating System (or Browser): Windows 10
- Node Version: 10.15.1

### How Do We Reproduce?

1. Create a simple Elm application as this one https://github.com/ulisses-alves/rollup-elm-issue
2. Run `npm run build`

### Expected Behavior
You would be able to build successfully.

### Actual Behavior
Error is thrown:
`TypeError: Cannot read property 'include' of null`

Note: You can successfully open a node interactive prompt and import the Elm output, which would mean that it is valid JavaScript.

**Comment by shellscape** [comment]
@ulisses-alves thanks for opening an issue. Could you also add the output fro Rollup to that gist? That will aid in first-pass triage, and there might be something that stands out as a problem right away.

**Comment by shellscape** [comment]
> Import the module in a simple rollup project and build.

There's no universal simple rollup project, so we're going to need to see your Rollup configuration at the very least.

**Comment by laurentpayot** [comment]
@ulisses-alves From the [Elm docs](https://guide.elm-lang.org/webapps/) it seems that [`Browser.document`](https://gist.github.com/ulisses-alves/b8dfcd4ddb97d3cdaea9f8bb78712bff#file-app-elm-L9) Elm output is not meant to be bundled, but to be executed in the main thread via `<script src="elm.js"></script>` so that the global variable `Elm` is available and `Elm.Main.init()` can be called.

**Comment by ulisses-alves** [comment]
@shellscape I have updated the gist with the complete setup.

@laurentpayot I believe that's just the case of the docs not adding more steps to the tutorial than needed. Elm can be used as a commonjs module (you can see for yourself by importing the output file from node directly). There's also a webpack, parcel and rollup (which I maintain) plugins available.

**Comment by ulisses-alves** [comment]
I have noticed that it seems not related to the "module export" part of it, and more about the contents of the App itself. There's a more minimal version of the App that can be written that no longer triggers the issue:
```elm
module App exposing (main)

import Html exposing (..)

main : Html msg
main = text "Hello"
```

**Comment by laurentpayot** [comment]
@ulisses-alves nice rollup plugin, stared :+1:

**Comment by ulisses-alves** [comment]
> 
> 
> @ulisses-alves thanks for opening an issue. Could you also add the output from the `elm` command to that gist? That will aid in first-pass triage, and there might be something that stands out as a problem right away.
@shellscape 

The output from `elm make` is under `src/app.js`.

**Comment by shellscape** [comment]
This may be an issue with `@rollup/plugin-commonjs`. I'm not sure if it's setup to handle using modules which are faux-commonjs lacking `module.exports`. First time I've seen that need. @lukastaegert might have more insight.

**Comment by lukastaegert** [comment]
It appears the issue you stumbled across was #3324 which is now closed, so please close this issue if you agree.

On a separate note, `src/app.js` does not appear CommonJS at all but rather something very similar to Rollup's own IIFE format. Thus you do not need the CommonJS plugin at all, even though it "fixes" your setup by creating an empty default export that you can import and then ignore.

What I would rather do is change your `index.js` file to just

```js
import './app';
```

This will make your output a few bytes shorter and still create a global variable called `Elm` (this is what the code in app.js does).

**Comment by ulisses-alves** [comment]
@lukastaegert 
That format is odd to me. In node you can even require it an actually get exported values!
Anyway, this is how I made it work on rollup-plugin-elm:
https://github.com/ulisses-alves/rollup-plugin-elm/blob/807ed11d462b2a46e645794a4f2588a46d9c3126/src/index.js#L56

In regards to the issue - I have just tested with 1.29.0 and it seems to be fixed. Thanks for checking it out.
