### ISSUE TITLE
Support mixed type/extending config.external

### ISSUE THREAD

**Issue by gingur** [rollup/rollup#3329]
### Expected Behavior / Situation
I have a plugin that wants to inject an `external` function or array. To do this, I'm using [options](https://rollupjs.org/guide/en/#options) to access the `inputOptions` and add my own `external` definition. Prior definitions of `external`, and any additional definitions of `external` should also work.

### Actual Behavior / Situation
If the consumer has specified their own function or array for `external`, they would be lost when modifying the `inputOptions`.

### Modification Proposal
Allow functions to be passed into an `external` array. This would allow my plugin to convert an existing `external` definition into an array, if it isn't already, and then push my `external` array items or function into the `inputOptions`.

**Comment by gingur** [comment]
from what I can tell, the logic is in https://github.com/rollup/rollup/blob/5e9a135a5654f2bf7dfa60e8968da75bf4a6005e/src/ModuleLoader.ts#L45

**Comment by gingur** [comment]
From what I can tell, this is the source https://github.com/rollup/rollup/blob/5e9a135a5654f2bf7dfa60e8968da75bf4a6005e/src/ModuleLoader.ts#L45-L59

**Comment by lukastaegert** [comment]
We could do that, but the recommended way for plugins to make dependencies external would be to implement a `resolveId` hook: https://rollupjs.org/guide/en/#resolveid

Did you consider this? Would it work for you? Mutating options should only ever be a last resort.

**Comment by gingur** [comment]
That is actually exactly what I need, and it looks like it supports async too which is critical since my externals come from an external source. Thank you!
