### ISSUE TITLE
Messages logged which should not need to be when all has gone well.

### ISSUE THREAD

**Issue by CrowdHailer** [rollup/rollup#333]
I have a `rollup.config.js` file which uses the npm plugin. When I run rollup I get the following message "Treating 'rollup-plugin-npm' as external dependency". That is not relevant to me and is distracting because I would be interested in the list of external dependencies that my code.

I assume that when using the `-c` flag that rollup is used to bundle the config file. Does rollup have an option to run silently and can that be used internally when rolling up the config file. Obviously if there is an error I want to be notified.

My rollup.config.js file is

```js
import npm from 'rollup-plugin-npm';

export default {
  entry: 'index.js',
  format: "iife",
  moduleName: "Main",
  dest: "bundle.js",
  sourceMap: true,

  plugins: [
    npm({
      jsnext: true
    })
  ]
};

```

**Comment by Rich-Harris** [comment]
Agree, it's annoying! Thanks, fixed in 0.22.1
