### ISSUE TITLE
Unexpected empty imports for external and pure modules in the output files

### ISSUE THREAD

**Issue by Mensu** [rollup/rollup#3332]
- Rollup Version: 1.29.0
- Operating System (or Browser): Mac OS
- Node Version: 12.9.1

### How Do We Reproduce?

Reproducible repo: https://github.com/Mensu/rollup-reproduce-issues-3332

The point is: use multiple entry points importing the same shared module which imports a function from an external and pure third-party module

1. create the following three files

- index.js and utils.js
```js
export * from './shared';
```

- shared.js
```js
import { isNumber } from 'lodash-es';

export function checkIsNumber(value) {
  return isNumber(value);
}

```

2. edit rollup config
    - set two entry points: `index.js` and `utils.js`
    - set `external` to `id => id === 'lodash-es'`, marking `lodash-es` as external
    - set `treeshake.moduleSideEffects` to `false`, marking every module as without side effects

3. build with rollup

### Expected Behavior
There are no empty imports like `import 'lodash-es'` in the output entry files

### Actual Behavior
There appears an empty import `import 'lodash-es'` in the output entry files

```js
import 'lodash-es';
export { c as checkIsNumber } from './shared-70166db4.js';
```
What's the point of adding an empty import in the output files when the module has been marked as without side effects?

**Comment by lukastaegert** [comment]
This is to speed up the load/parse loop. `lodash-es` is a secondary dependency that would only be discovered once the shared chunk has been parsed. Hoisting the import here does not affect execution order but will improve startup time.

I REALLY have to write an FAQ about this because it seems to trip up many people.

**Comment by Mensu** [comment]
> This is to speed up the load/parse loop. `lodash-es` is a secondary dependency that would only be discovered once the shared chunk has been parsed. Hoisting the import here does not affect execution order but will improve startup time.
> 
> I REALLY have to write an FAQ about this because it seems to trip up many people.

Thanks for your clarification! I just tried using the package with `import 'lodash-es'` and found that even with the empty import statement, not all of the codes of `lodash-es` was bundled (but only codes related to `isNumber`). I didn't know that😢

Now I understand and have no problem with rollup hoisting the import here.

**Comment by EstebanVictorio** [comment]
> This is to speed up the load/parse loop. `lodash-es` is a secondary dependency that would only be discovered once the shared chunk has been parsed. Hoisting the import here does not affect execution order but will improve startup time.
> 
> I REALLY have to write an FAQ about this because it seems to trip up many people.

@lukastaegert is this FAQ available? 😄

**Comment by lukastaegert** [comment]
Not really, but there is an option to control this behavior: https://rollupjs.org/guide/en/#outputhoisttransitiveimports
