### ISSUE TITLE
Chat room for Rollup

### ISSUE THREAD

**Issue by CrowdHailer** [rollup/rollup#334]
I think there are a number of interesting discussions around the use of rollup particularly with respect to plugins. ( I have spent the morning with the npm plugin reading about load paths so I could use rollup with local modules)

In my opinion it would be good to have a channel for chatting. 
Simply for ease of setup I like gitter.

**Comment by Victorystick** [comment]
I'm all for a Gitter channel. :+1:

**Comment by Rich-Harris** [comment]
Good idea! https://gitter.im/rollup/rollup
