### ISSUE TITLE
Proposal deduping based on the file content

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#3344]
### Feature Use Case
When many files get imported from node_modules they often import none flattened versions of files that share the same content we could dedub that and link them all to the right chunk

**Comment by lukastaegert** [comment]
Unfortunately we cannot just dedupe JS files that have the same content unless we are sure they are stateless. If they retain any state, internal caches, initialization code etc. in local variables, deduping will change functionality.

**Comment by kzc** [comment]
See related issue #3205

**Comment by lukastaegert** [comment]
Good catch. Closing this in favour of #3205 as I believe there is sufficient overlap, and #3205 contains your examples. Also I do not want to say that something like this will never happen, but it will definitely be a long shot.
