### ISSUE TITLE
Rollupjs doesn't resolve require('xxx') correctly.

### ISSUE THREAD

**Issue by Sara2009** [rollup/rollup#3355]
I use a babel plugin named 'babel-plugin-transform-import-css'. It will tranform the css code like this:
```javascript
import classes from './Component.css'
// ... some code
```
The code above will  be transpiled to::
```javascript
var classes = {
    root: 'lib-foo-root-SFs0',
    // ... some classes ...
}
require('load-styles')('.root{color:red}; ...some css...') // puts styles into the head
// ... some code
```
But when i use rollupjs to build the code as UMD format. The `require('load-styles')` is not resovled at all.  So i meet a mistake in the browser.

My rollup config is as below:
```javascript
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import alias from 'rollup-plugin-alias';
import { uglify } from 'rollup-plugin-uglify';
import postcss from 'rollup-plugin-postcss';
import replace from 'rollup-plugin-replace';
import typescript from '@rollup/plugin-typescript';

function getBabelConfig() {
    return {
        presets: [
            [
                '@babel/preset-env', {
                    targets: {
                        browsers: ['last 2 versions', 'IE >= 9'],
                    },
                    loose: true,
                    modules: false,
                },
            ],
            [
                '@babel/preset-react',
            ],
            '@babel/typescript',
        ],
        plugins: [
            [
                '@babel/plugin-proposal-decorators',
                {
                    legacy: true,
                },
            ],
            '@babel/plugin-proposal-class-properties',
            [
                '@babel/plugin-transform-runtime',
                {
                    absoluteRuntime: false,
                    corejs: false,
                    helpers: true,
                    regenerator: true,
                    useESModules: true,
                },
            ],
            [
                // https://www.npmjs.com/package/babel-plugin-transform-import-css
                'babel-plugin-transform-import-css', {
                    generateScopedName: '[local]',
                },
            ],
        ],
    };
}

export default function getRollupPlugins(minify) {
    const babelConfig = getBabelConfig();
    babelConfig.runtimeHelpers = true;
    const plugins = [
        replace({
            'process.env.NODE_ENV': minify ? 'production' : 'development',
        }),
        postcss({
            extensions: ['.css', '.less'],
            extract: false,
            modules: false,
            minimize: !!minify,
        }),
        typescript(resolveHelper('../../config/tsconfig.json').compilerOptions),
        alias({
            resolve: ['', '.jsx', '.js', '.tsx', '.ts'],
        }),
        resolve({
            extensions: ['.jsx', '.js', '.tsx', '.ts', '.json', '.node'],
            mainFields: ['module', 'main'],
        }),
        commonjs({
            include: /node_modules/,
        }),
    ];

    plugins.push(babel(babelConfig));

    if (minify) {
        plugins.push(uglify());
    }
    return plugins;
}
```

**Comment by baryla** [comment]
@Sara2009 could you post the error that you're getting? At first glance, this doesn't seem like an error with Rollup but one of the modules but it'd be helpful to see what you're getting.

**Comment by lukastaegert** [comment]
Rollup does not support CommonJS. If your plugin cannot generate ESM imports, then you need rollup-plugin-commonjs

**Comment by lukastaegert** [comment]
Maybe it is a problem with plugin order. In any case, this is quite likely not an issue for Rollup core.

**Comment by Sara2009** [comment]
> Rollup does not support CommonJS. If your plugin cannot generate ESM imports, then you need rollup-plugin-commonjs

I use the rollup-plugin-commonjs. I think the problem is that there are two format import in one file. For example, the file may be like below after the rollup plugins as the code shown above:
```javascript
import A from 'A';
import B from 'B';
var classes = {
    root: 'lib-foo-root-SFs0',
    // ... some classes ...
}
require('load-styles')('.root{color:red}; ...some css...') // puts styles into the head
// ... some code
```
The rollup will resolve the A and B correctly as they are ES module. But the `require('load-styles')` is ignored. The same babel config is correct resolved when i use webpack. Because webpack has its own require to resolve whether the ES module import or the commonjs require. Maybe I should to use another bable-plugin to transform the code using ES module.

**Comment by Sara2009** [comment]
> @Sara2009 could you post the error that you're getting? At first glance, this doesn't seem like an error with Rollup but one of the modules but it'd be helpful to see what you're getting.

There is no error when i build the file using rollup. But the buided file is not what i want. The `require('load-styles')('.root{color:red}; ...some css...')` is not resolved at all. What i want is that  the source code of 'load-styles' is inserted in the builded file. But the fact is that rollup does nothing with it.

**Comment by TrySound** [comment]
Commonjs plugin ignores es modules. Any import/export statement identifies es module. Better to not mix esm and cjs in one module.

**Comment by lukastaegert** [comment]
Yes, the plugin will ignored mixed imports. If you need this, the plugin repo https://github.com/rollup/plugins is the place for feature requests.

**Comment by baryla** [comment]
> > @Sara2009 could you post the error that you're getting? At first glance, this doesn't seem like an error with Rollup but one of the modules but it'd be helpful to see what you're getting.
> 
> There is no error when i build the file using rollup. But the buided file is not what i want. The `require('load-styles')('.root{color:red}; ...some css...')` is not resolved at all. What i want is that the source code of 'load-styles' is inserted in the builded file. But the fact is that rollup does nothing with it.

Hmm. I'd suggest you fork the `babel-plugin-transform-import-css` and edit:

```js
function putStyleIntoHeadAst({ code }) {
  return jsStringToAst(`require('load-styles')(\`${ code }\`)`);
}
```
and instead of `require`, play around with dynamic `import`.

**Comment by Sara2009** [comment]
> > > @Sara2009 could you post the error that you're getting? At first glance, this doesn't seem like an error with Rollup but one of the modules but it'd be helpful to see what you're getting.
> > 
> > 
> > There is no error when i build the file using rollup. But the buided file is not what i want. The `require('load-styles')('.root{color:red}; ...some css...')` is not resolved at all. What i want is that the source code of 'load-styles' is inserted in the builded file. But the fact is that rollup does nothing with it.
> 
> Hmm. I'd suggest you fork the `babel-plugin-transform-import-css` and edit:
> 
> ```js
> function putStyleIntoHeadAst({ code }) {
>   return jsStringToAst(`require('load-styles')(\`${ code }\`)`);
> }
> ```
> 
> and instead of `require`, play around with dynamic `import` or submit a PR there to have the option to use the `import` statement.

OK. Thanks a lot for your advice. :)
