### ISSUE TITLE
[question] Any plans for a vue file plugin.

### ISSUE THREAD

**Issue by amanpatel** [rollup/rollup#336]
Webpack has ```vue-loader```  and browserify has ```vueify```. The first time I started using webpack, I was somewhat not impressed with the file sizes that it was generating.  Rollup seems like the answer to my prayers.

Was wondering if the community was familiar with a rollup plugin that incorporates .vue files. Similar loaders also exists for react/JSX transofmers, which allow you to create web components (style+template+ES5 module) in a single file.

**Comment by eventualbuddha** [comment]
@amanpatel I'm not aware of a plugin for `.vue` files, and a [quick search](https://www.npmjs.com/search?q=rollup-plugin) doesn't turn one up. However, it should be pretty easy to [write one](https://github.com/rollup/rollup/wiki/Plugins)! All you really need to do is write a `transform` method that returns the transformed code (and optional sourcemap). See [`rollup-plugin-babel`'s `transform` method as an example](https://github.com/rollup/rollup-plugin-babel/blob/41a7d4e6db4ead5ad127d3b08a824f34e8bdfeaf/index.js#L25-L41).

**Comment by amanpatel** [comment]
Thanks for the helpful post and pointer to a possible implemention. I think I might take this one on.

**Comment by eventualbuddha** [comment]
No problem! When you do perhaps we can add it to the [Plugins wiki page](https://github.com/rollup/rollup/wiki/Plugins).
