### ISSUE TITLE
Tree shaking optimizations break asm.js

### ISSUE THREAD

**Issue by DirtyHairy** [rollup/rollup#3360]
- Rollup Version: 1.30.1
- Operating System (or Browser): MacOS (Firefox to validate asm.js)
- Node Version: 13.6.0

### How Do We Reproduce?

The following code is valid asm.js:

```
export default function asmjs() {
    "use asm";

    function noop(e) {
        e = e|0;
    }

    return { noop: noop };
}
```

Running rollup with tree shaking enabled yields the following  output:

```
function asmjs() {
    "use asm";

    function noop(e) {
    }

    return { noop: noop };
}
```

As can be checked by generating an UMD module and running in Firefox, the result is not valid asm.js anymore --- the statement `e = e|0;` is required by asm.js in order to fix the type of e.

Another example is the following valid asm.js code:

```
export default function asmjs() {
    "use asm";

    function noop(e) {
        e = e|0;

        switch (e|0) {
            case 10:
                return 10;

            default:
                return e|0;
        }

        return e|0;
    }

    return { noop: noop };
}
```

Rollup deletes the superfluous return, breaking asm.js validation:

```
function asmjs() {
    "use asm";

    function noop(e) {
        e = e|0;

        switch (e|0) {
            case 10:
                return 10;

            default:
                return e|0;
        }
    }

    return { noop: noop };
}
```

In both cases, disabling tree shaking preserves asm.js semantics and generates valid asm.js. Those two examples reproduce the cases that I stumbled over, but there may be other problematic cases.

### Expected Behavior

Rollup should keep asm.js valid after transformation. I think it would be sufficient to avoid optimizing functions that contain the `'use asm'` directive as first statement.

### Actual Behavior

The optimizations made by rollup break asm.js validation and cause the code to run slower in browsers that supports asm.js.

**Comment by lukastaegert** [comment]
Hi, I am always surprised how often I learn something new about JavaScript while working on this project. Today I learned some of the basic semantics of asm.js (and of course tried it out in Firefox). Checking with the [specification](http://asmjs.org/spec/latest/) I absolutely agree that the most prudent course is what you suggest, to simple turn off code optimizations in asm.js code. Does not seem to be too difficult, actually, fix upcoming.

**Comment by lukastaegert** [comment]
Fix at #3362. You can try it out if this works for you via `npm install rollup/rollup#gh3360-preserve-use-asm-code` before we release this.

**Comment by DirtyHairy** [comment]
Hi Lukas!

Thanks for the fast response. Unfortunately, using a rollup build from the branch still removes the assignment and return statements from my examples. I have verified that the compiled code actually contains the modifications on the branch, and that `deoptimizeBody` is set. The test suite completes successfully, too. Am I doing something wrong, or is something still missing?

Cheers
    -Christian

**Comment by lukastaegert** [comment]
Hi Christian,

maybe we can look into this better via a repro:
https://repl.it/@lukastaegert/RollupAsmJS

When you run this, it will install Rollup from the branch (sorry, may take ages initially) and bundle your example (correctly). Maybe you can fork this (or I can invite you as collaborator if you have a Repl.it username) to change it to reproduce what is not working for you. Maybe plugins are involved?

**Comment by lukastaegert** [comment]
So so, now this is kind of embarassing: You are right, it was broken. And coverage actually told me, because my awesome modifications were not entirely covered! Also, the test case was missing the most crucial bits (the "dead code"), so it was useless, what was I thinking!?
So why was it broken? I added a "initial value" to `deoptimizeBody` in its definition. Unfortunately, those values are assigned AFTER the constructor has done its thing. `initialise`,  however, is called by the super constructor. Oopsie. So TypeScript just overwrote the flag every time.

Should be working now, please check again!

**Comment by DirtyHairy** [comment]
Awesome, thanks alot --- works fine now (my real use case is [here](https://github.com/6502ts/6502.ts)). Didn't know about repl.it, I'll have to remember that.

I wasn't aware of that peculiarity of TS either --- I was under the assumption that the autogenerated code for member initialization always ran before the constructor body (and a lot of my code would break badly if it didn't). Turns out that the actual behaviour is even trickier: the generated constructor first executes a possible call to super, then runs the autogenerated code and finally runs the constructor body.

Anyway, thanks again

Cheers
    -Christian

PS: Told you I would open a PR eventually. I didn't make it that far, but I'll try again next time 😛

**Comment by lukastaegert** [comment]
> PS: Told you I would open a PR eventually. I didn't make it that far, but I'll try again next time 😛

❤️❤️❤️

> my real use case is here

This looks like an awesome and crazy project! With a cool tech stack involving Elm!? BTW I see you are using `rollup-plugin-typescript2`. Would be interested if you could give the updated `@rollup/plugin-typescript@3` a whirl and see how it compares. It finally got proper diagnostics and emit-less types support, but I wonder if it is slower due to lack of caching or maybe has other issues...?

**Comment by DirtyHairy** [comment]
> This looks like an awesome and crazy project! With a cool tech stack involving Elm!?

Thanks alot 😏 Actually, the Elm part is the youngest. The emulator used to have a React/Redux based frontend and a build process built on Browserify and Grunt, and it was only last year that I redid the build process with Rollup and rewrote the frontend in Elm (I grew tired of keeping the React dependencies updated). I am not fully done with the switch, either, there still is Travis that needs to be disabled, together with a few debug tools.

> Would be interested if you could give the updated @rollup/plugin-typescript@3 a whirl and see how it compares

Sure, I'll give it a spin and report back.
