### ISSUE TITLE
Rollup fails when plugin's hook is defined using AsyncFunction

### ISSUE THREAD

**Issue by slavafomin** [rollup/rollup#3367]
Hello!

Thank you for this great tool!

However, when plugin's hook is defined using [AsyncFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction), Rollup fails with the following error: `Error: Unknown object type "asyncfunction"`.

It looks like Rollup is too aggressive when it comes to plugin's format validation and it probably relies on `constructor.name` instead of using `typeof` operator.

I believe this code should demonstrate the problem:

```js
export default function myPlugin() {
  return {
    name: 'my-plugin',
    generateBundle: async () => {
      return await Promise.resolve();
    },
  }
}
```

Thanks!

---

- Rollup Version: `1.27.13`
- Node Version: `10.16.3`

**Comment by slavafomin** [comment]
After looking deeper into the source code of Rollup I can't find an issue there. It looks like some rogue plugin is causing this problem, I'm going to investigate further.

**Comment by slavafomin** [comment]
Yep, it was some [weird behavior](https://github.com/ezolenko/rollup-plugin-typescript2#plugins-using-asyncawait) of the [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2).

Sorry for the false alaram :)

**Comment by shellscape** [comment]
@slavafomin thanks for stopping by. If you have the need to open another issue in the future, please note that we require everyone to fill out the appropriate issue template in its entirety and ask that no one modify the templates.
