### ISSUE TITLE
RFC [v2.0.0]: Align format specifiers passed to plugins with error messages and documentation

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#3370]
### Expected Behavior / Situation
The format names used in error messages (e.g. "esm") and the documentation are aligned with what is passed to plugins.

### Actual Behavior / Situation
For historical reasons even though error messages and documentation always use "esm", plugins receive "es" instead of "esm". We should fix that in some way for Rollup@2!

### Modification Proposal
This is a "Request for comments" as there are several possible solutions.

1. The simplest solution would be to just pass "esm" to plugins instead of "es" and be done with it.
2. There was however the suggestion to use this chance to align with Node and pass the following to plugins:
   - "module" instead of "es(m)"
   - "commonjs" instead of "cjs"
   Both are already valid aliases that can be used by the end user, though of course internally at the moment they are just mapped to "es" and "cjs". If we go for the second choice, I would also align all documentation and error messages but leave the old format specifiers as valid aliases for end users. We could also just change to "module" and leave "cjs" alone.

Opinions?

For reference:
- TypeScript supports "CommonJS", "ES6", "ES2015", "ESNext" (with arbitrary capitalization)
- babel-preset-env: "commonjs", "cjs"; ES modules can be used implicitly via "targets.esmodules"

**Comment by hugomrdias** [comment]
Align with node imo is the better option, maybe others will follow and every one's life is simpler for it.

**Comment by TrySound** [comment]
Commonjs modules are also modules. `module` for esm always confused me.

**Comment by isidrok** [comment]
I think of modules as a broader concept such as a Java package or a C# namespace so I would avoid using `module` to specify a `module format` since `cjs`, `amd`, etc... are also modules.

Script tags have type `module` but I think this is ok since there is only one type of module that can be run on the browser, but Rollup has a wider scope.

Regarding `es` vs `esm` I prefer `es` since the `m` seems redundant as we are already talking about module formats.

Anyway I would try to use the same nomenclature in both output options and the information passed to plugins.

**Comment by hugomrdias** [comment]
You think rollup should ignore node and browsers and do something different ? what about consistency ?

Don't forget that cjs, amd, etc are all hacks not real ecmascript modules this is at the core of rollup. All the hacks are supported by plugins, the native features are supported by default.

**Comment by shellscape** [comment]
> Don't forget that cjs, amd, etc are all hacks not real ecmascript modules

Something might have been lost in translation on this, but CJS, AMD, IIFE are not _hacks_. They're different module formats that Rollup can support via Plugins. I want to make sure everyone understands that distinction.

That said, one of the pain points with Webpack was that it tried to offer distinctions between Node and Browser environments, which eventually opened the floodgates to every other conceivable platform (or what webpack calls "targets").

Aligning with Node or the Browser would be a mistake imho. Node and the Browser are platforms. ES Modules are a specific module format with a specification / standards document. CommonJS is another separate format with [specifications](https://en.wikipedia.org/wiki/CommonJS#Specifications). 

> Regarding es vs esm I prefer es since the m seems redundant as we are already talking about module formats.

I agree with @isidrok on this. My vote goes to standardizing on `es` across the Rollup ecosystem.

**Comment by LarsDenBakker** [comment]
I think `es` is  a good name, and wont break a lot of existing plugin code :)

**Comment by lukastaegert** [comment]
I guess this is a slight vote in favour of `es`, and I see the arguments. The beauty of this is that this is the only way that would NOT be a breaking change—the only things that needs to be done is adjust some error messages and documentation. I will try to compile a PR for this.

**Comment by lukastaegert** [comment]
Closed in rollup@2.0.0
