### ISSUE TITLE
Rollup generate empty entry file when using dynamic imports.

### ISSUE THREAD

**Issue by foisonocean** [rollup/rollup#3373]
- Rollup Version: v1.31.0
- Node Version: v13.7.0

### How Do We Reproduce?

https://codesandbox.io/s/rollup-empty-entry-issue-23qw0

In the browser view of the codesandbox, you can check the output of rollup.

### Expected Behavior

The entry file should contains meaningful code.

### Actual Behavior

The entry file only contains import statement of other files. In the example of the codesandbox I post before, the entry file only contains one line code: `import './chunk-7c1c3124.js';`, in this case, the `chunk-7c1c3124.js` should be the entry file.

**Comment by lukastaegert** [comment]
Thanks, but I would close this in favour of #3358 and the discussion in that issue. The situation will likely improve in the future. The discussion in #3358 will give you the necessary background.
