### ISSUE TITLE
[CLI]: Switch over to a less verbose argument parser library

### ISSUE THREAD

**Issue by jamesgeorge007** [rollup/rollup#3376]
### Expected Behavior / Situation
As of now the CLI depends on `minimist` for the purpose of argument parsing which isn't actively maintained anymore. Switching over to any of the better solutions, say `commander.js` would be a better idea.

### Actual Behavior / Situation
Consumes an `arg-parser library` which is no longer actively maintained.

### Modification Proposal
Switch over to a better argument parser library.

**Comment by jamesgeorge007** [comment]
Since this calls for a major refactor, I would love to hear out from the maintainers.

**Comment by shellscape** [comment]
I like where the motivation is coming from, but Commander is a hard vote no from me. It's way overkill for our needs. yargs-parser would be much more prudent.

**Comment by jamesgeorge007** [comment]
Sounds good. So shall I go ahead or should we wait to hear what others have to say?

**Comment by shellscape** [comment]
Definitely wait for more input.

**Comment by lukastaegert** [comment]
yargs-parser looks like it can be configured to work the same way as minimist with regard to objects and negations and does not look too big. Definitely worth a shot.

**Comment by LarsDenBakker** [comment]
I've been using https://www.npmjs.com/package/command-line-args for a lot of CLIs, it works out pretty well.
