### ISSUE TITLE
Cannot import ES6 module package

### ISSUE THREAD

**Issue by davidcallanan** [rollup/rollup#3378]
- Rollup Version: 1.29.0
- Operating System (or Browser): Windows 10
- Node Version (if applicable): 13.8.0
- Link to reproduction: I will look into doing this soon

### Expected Behavior

I have created a node package `foo`, with `{"type": "module"}` defined in its `package.json`. This results in its JavaScript files [behaving like ES6 modules](https://nodejs.org/api/esm.html).

My web application depends on `foo`, and is set up using rollup. Rollup of course supports ES6 modules syntax.

Expected behavior: to be able to import `foo` in my web application.

### Actual Behavior

However, it refuses to load my `foo` package because

> `require() of ES module is not supported.`

This is confusing me because I am not using `require` anywhere, I am using the ES6 import syntax to import `foo`. For some reason rollup is failing to transpile this project, and I believe this might be a bug, or a not yet supported feature.

**Comment by shellscape** [comment]
Citing the issue template:

>   **Issues without minimal reproductions will be closed!** Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a proper reproduction or we'll have to close your issue without triage.

**Comment by davidcallanan** [comment]
@shellscape  Yes, I'll do that as soon as I can

**Comment by davidcallanan** [comment]
Can't reproduce the issue, it must be from a plugin
