### ISSUE TITLE
rollup-watch does not with HTML files

### ISSUE THREAD

**Issue by deveras** [rollup/rollup#3380]
- Rollup Version: 1.31.0
- Operating System (or Browser): MAC
- Node Version (if applicable): 12.14.1
- Link to reproduction (IMPORTANT, read below):

### Expected Behavior
Expected watch object to include index.html as per following configuration:
```
export default {
  input: 'source/js/index.js',
  watch: {
    chokidar: true,
    include: [ 'source/index.html' ],
    exclude: ['node_modules/**'],
    clearScreen: false
  },
```

also tried:
    include: [ 'source/**' ],
    include:  'source/**',
    include: 'source/index.html'

tried with and without chokidar also.
....

### Actual Behavior
index.html file is not watched

**Comment by shellscape** [comment]
Citing the issue template:

>   **Issues without minimal reproductions will be closed!** Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a proper reproduction or we'll have to close your issue without triage.

**Comment by seivan** [comment]
@deveras I think `include` means exclusive include from the existing graph..

```
Limit the file-watching to certain files. Note that this only filters the module graph but does not allow to add additional watch files:
```

@shellscape Honestly, closing issues like this for a lack of reproducible case isn't very productive, especially if a config is shown that literally shows what the mistake might be, how do you expect people to find answers if the documentation doesn't show how to add additional files and the issues related to said question are instantly closed?

**Comment by shellscape** [comment]
@seivan sorry, that is our policy. 99% of issues reported here are the result of a user-specific environment; be it build, repo, file structure, file contents, or system. If folks reporting an issue cannot abide by the requests in the issue template, and don't want to take the time to put together a reproducible case for us to triage, then we're not going to spend the time trying to recreate their environment and the conditions to reproduce the error reported.
