### ISSUE TITLE
Add rollup.watch event documentation

### ISSUE THREAD

**Issue by SidOfc** [rollup/rollup#3383]
Documentation Is:

- [x] Missing
- [x] Needed (<-- EDIT: checked this box too, as in "needed in my opinion")
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Just recently switched from a browserify watcher to using rollup.watch. Since things work a bit differently I wanted to add some watch messages on `BUNDLE_START` and `BUNDLE_END` / `ERROR` events.

I got this to work by reading [rollup.watch](https://rollupjs.org/guide/en/#rollupwatch), but then was interested in showing compile errors and bundle sizes on rebuild as well. This is where the documentation starts to "lack" in my opinion.

I see only one comment about `event.code`, it takes up the entire body of the example, and nothing else is explained at all. I could not easily find references or other pages as to "what" this event object actually is, what its properties / methods are, or even how to use them. To me, it "feels" undone anyway.

It actually makes me feel a bit like I'm an idiot as well 😅 (perhaps I am, did I miss a link, am I reading outdated docs?)

### Your Proposal for Changes

If rollup internally knows what event properties and methods exist, I would be really happy if I could just find them in the docs, or find a reference to the complete "event" that gets passed in to `rollup.on('watch', event => ...)`. This would help everyone understand "what" the event is they are trying to extract information from.

So at minimum, my proposal would be to "add a link to the docs for the .watch event object". This would help most folks happily on their way (assuming it's either gonna be chokidar or fs.watch stuff coming through).

Last but not least, thank you so much for building and maintaining rollup and taking the time to go through the issues!

Cheers,
Sidney

**Comment by SidOfc** [comment]
After checking out the [source code](https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts) I came up with this solution to use with `watcher.on('event')`:

```js
ROLLUP_LISTENERS = {
    ERROR: event => console.error(event.error.message),
    BUNDLE_START: event => console.info(`Compiling ${path.basename(event.input.toString())}...`),
    BUNDLE_END: event => {
        const input = path.basename(event.input.toString()),
            output = path.basename(event.output.toString());

        console.info(`Compiled ${input} -> ${output} in ${event.duration / 1000.0} seconds!`);
    }
};

// somewhere else
rollup
    .watch(...)
    .on('event', event => ROLLUP_LISTENERS[event.code] && ROLLUP_LISTENERS[event.code](event));

```

Above example may help sketch an image of what I was trying to actually create. In this case I think it would have been good if the documentation stated something along the lines of:

> Additionally, some events have special attributes attached, depending on the `code` of the event:
> - **ERROR**  events contain an `error` property with a `message` that may be `console.error`'d
> - **BUNDLE_START** events contain `input` which means ... and `output` which means ... etc
> - **BUNDLE_END** events contain `input` and `output` from **BUNDLE_START** and the compilation `duration` in milliseconds

Just thinking out loud here :)

**Comment by g4rry420** [comment]
I believe this issue has been resolved in this pr - https://github.com/rollup/rollup/pull/3883/files#diff-e081ae87f76d4255aa739f10c63c1d0404e60c5169f50236159e6c191bcdf139

**Comment by SidOfc** [comment]
Hello there, sorry for the late reply, in the meantime I've been moving non npm library projects from rollup to webpack so the need for this custom code and the nitty gritty has been removed. At any rate I do see some useful comments in here which document which properties the different events contain.

Given that was the problem raised by this issue I also think it's fair to close. Thank you @g4rry420 for the heads up on this commit and @lukastaegert for rollup. It's still a wonderful bundler I use for various projects!
