### ISSUE TITLE
Licence in .es.js does belong to microsoft exclusive????

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#3396]
https://unpkg.com/browse/rollup@1.31.1/dist/rollup.es.js

At the top you can read that it is owned by microsoft APACHE 2.0 i think thats not allowed while i love to have apache 2.0 licence i wonder why it is not matching the md file and why microsoft?

**Comment by lukastaegert** [comment]
The license refers to the bundled TSLib helpers and is correctly reflected here starting line 492: https://unpkg.com/browse/rollup@1.31.1/LICENSE.md

Rollup@2 will no longer have that dependency

**Comment by shellscape** [comment]
_Please do not remove the issue templates for any type of issue._
