### ISSUE TITLE
Parametrize output.banner/output.footer

### ISSUE THREAD

**Issue by stropho** [rollup/rollup#3398]
### Feature Use Case
Prepend//append different content to different entry points.
At the moment e.g. the `banner` could be `string | (() => string | Promise<string>)`. In case of a function, it would be great to have some idea which entry point are we working with in order to resolve correct content and insert it to the code file.

This is obviously useful only when working with multiple entry points, i.e. `input` is of type `{ [entryName: string]: string }`

In my case, I'd use it for some of those standalone JSDoc such as `@module` which seem to disappear in the output generated from rollup.

### Feature Proposal
banner/footer function will have some more information in its parameters. 
It could be the value pair from `input` map.
It could be the placeholders' values used in `output.entryFileNames`
It could have more output chunk information ?
It could something else.

I'd go with the easiest choice, not sure which one it is.

**Comment by lukastaegert** [comment]
Sounds useful but it is not a small change as this will also have some impact on hash generations. At the moment, the algorithm makes use of the fact that it does not change.

Still keeping this as a future improvement.

For the time being, you could manually insert banners in the `renderChunk` hook, which has all this information available.

**Comment by lukastaegert** [comment]
This feature will be included in #4543
