### ISSUE TITLE
Missing referenceId

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#3403]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

https://rollupjs.org/guide/en/#resolvefileurl

This seems to be missing documentation for `referenceId`.

### Your Proposal for Changes

I would submit a PR, but I'm not 100% sure what the right answer is. I'm guessing that `ROLLUP_ASSET_URL` and `ROLLUP_CHUNK_URL` are deprecated in favour of `ROLLUP_FILE_URL`.

**Comment by lukastaegert** [comment]
>  I'm guessing that ROLLUP_ASSET_URL and ROLLUP_CHUNK_URL are deprecated in favour of ROLLUP_FILE_URL

You are right. The whole process is described with examples here https://rollupjs.org/guide/en/#file-urls but I guess we forgot to link this section to the documentation of `resolveFileUrl`. PR welcome! Not sure how to mark the deprecation properly as it does not really fit into the existing categories of deprecated hooks and deprecated context functions, though.

**Comment by lukastaegert** [comment]
Oh my, yes, the section for `resolveFileUrl` IS wrong, not sure how this happened. There is only a `referenceId` today. I think it was copied from the previous incarnation and not updated properly...

**Comment by jakearchibald** [comment]
Fixed in https://github.com/rollup/rollup/pull/3404
