### ISSUE TITLE
URL resolution in AMD format breaks in WebWorkers

### ISSUE THREAD

**Issue by surma** [rollup/rollup#3408]
- Rollup Version: v1.31.1
- Operating System (or Browser): Mac OS / Chrome
- Node Version (if applicable): v13.9
- Link to reproduction (IMPORTANT, read below): https://gist.github.com/surma/bf3c39d57c908b805c1a8f5cadb7f2f7

### Expected Behavior

The generated JS file should be usable in a [WebWorker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)

### Actual Behavior

The file does _not_ work in a WebWorker as the asset URL resolution code relies on `document.baseURI`, and `document` is unavailable in a Worker:

```js
var binaryUrl = new URL(require.toUrl('./assets/test-7c3fc2d8.bin'), document.baseURI).href;
```

I am working around this by mocking `document` for Worker contexts, but it would be nice if the asset URL resolution code could rely on `location` instead, which is available in both `Window` and `Worker`.

```js
self.document = {
  baseURI: `${location.protocol}//${location.host}/`
};
```

(The `esm` output format is not affected as `import.meta.url` is used in that context.)

**Comment by lukastaegert** [comment]
While this is true, I am not sure how Rollup should fix it except make the overhead bigger by adding additional checks to the wrapper code. But if you have a good suggestion, please provide it. The idea is anyway that Rollup is adding a "reasonable default" implementation that works for most people but that you should customize if you have special needs. And I would say this is special in so far that Rollup output will not run in a worker unmodified as AMD, you need to add an `importScripts` or added loader code at the top of your entry.

For this case, we added the [`resolveFileUrl`](https://rollupjs.org/guide/en/#resolvefileurl) hook to customize what the generated code is and also make it more efficient, e.g. by directly providing a resolved URL. This PR is a nice example of this surma/rollup-plugin-off-main-thread#14 😜

**Comment by lukastaegert** [comment]
Oh sorry, just realized you actually provided a solution, my bad

**Comment by lukastaegert** [comment]
I guess we could accomodate the change, but my point still stands that out code is not optimal for everyone and can be easily customized without mocking `document`.

**Comment by LarsDenBakker** [comment]
Unfortunately location is not the same as baseUri as it does not take into account the document base (set with `<base>`)

**Comment by surma** [comment]
I have no recollection of the PR ever. How awkward.

Going via `resolveFileUrl` makes a lot of sense. Happy to go down that route. Thanks for the help.

**Comment by surma** [comment]
> Note that all formats except CommonJS and UMD assume that they run in a browser environment where URL and document are available.

If I only had read the docs, lol.
