### ISSUE TITLE
Document next steps for each hook

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#3409]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Forked from https://github.com/rollup/rollup/issues/3402.

https://rollupjs.org/guide/en/#hooks - It's currently difficult to figure out the order in which hooks are called, and how it relates to the rest of Rollup's processing.

This leads to confusion like https://github.com/rollup/rollup/issues/2739 - it isn't clear from the docs that `renderChunk` comes after hashing.

### Your Proposal for Changes

State which hook comes first. Then for each hook, state what happens after that hook. As in, the docs for `resolveId` could end with something like:

**Next lifecycle steps**: This hook is called for all remaining imports in the currently processing module. Then [`load`](https://rollupjs.org/guide/en/#load) is called for each import in the same order.

(I don't know if the above is accurate, it's just an example)

Then, once that data is there, the community can help with creating a diagram.

**Comment by lukastaegert** [comment]
I created a draft PR here: #3418. Build phase is done, I hope to complete the generate phase soon.
