### ISSUE TITLE
Can't pass an array into output option in rollup config

### ISSUE THREAD

**Issue by Kirpich634** [rollup/rollup#3411]
- Rollup Version: 1.32.0
- Operating System (or Browser): Mac OS Catalina
- Node Version (if applicable): v10.17.0
- Link to reproduction (IMPORTANT, read below): https://github.com/Kirpich634/rollup-keker

### Expected Behavior

Will get two files 'lib/kek.js' and 'es/kek.js'

### Actual Behavior
```
npm run build

> @ build /Users/kirpich634/Projets/rollup-keker
> node build.js

(node:15616) UnhandledPromiseRejectionWarning: Error: You must specify "output.file" or "output.dir" for the build.
    at error (/Users/kirpich634/Projets/rollup-keker/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Object.write (/Users/kirpich634/Projets/rollup-keker/node_modules/rollup/dist/shared/node-entry.js:13981:28)
    at rollup.then.bundle (/Users/kirpich634/Projets/rollup-keker/build.js:7:12)
```

According to the documentation, we can put an array inside an output option 
https://github.com/rollup/rollup/pull/3184
<img width="1680" alt="Снимок экрана 2020-02-29 в 00 22 11" src="https://user-images.githubusercontent.com/19504525/75588549-f83d2e80-5a89-11ea-8902-334e9fcda659.png">

I've tried to localize the root of the problem in the rollup index: https://github.com/rollup/rollup/blob/master/src/rollup/index.ts

It seems that in `normalizeOutputOptions` function we always pass `config.output` into the `mergeOptions` as an object instead of an array:

normalizeOutputOptions:
```
	const mergedOptions = mergeOptions({
		config: {
			output: {
				...rawOutputOptions,
				...(rawOutputOptions.output as object),
				...(inputOptions.output as object)
			}
		}
	});
```

mergeOptions:
```
export default function mergeOptions({
	config = {},
        ...
} {
	....
	const output = config.output;
	const normalizedOutputOptions = Array.isArray(output) ? output : output ? [output] : [];
```

I do not understand why you do this: 
```
config: {
	...rawOutputOptions,
	...(rawOutputOptions.output as object),
	...(inputOptions.output as object)
}
```

Can we do something like this ??
```
config: {
	output: rawOutputOptions		
}
```

**Comment by lukastaegert** [comment]
No, because this is not supported when using the JS API and is also not intended to be supported. You have been looking at the documentation for config files, not the documentation for the JS API. When directly using the JS API, the idea is that you just call `bundle.generate` or `bundle.write` once for each output.

**Comment by lukastaegert** [comment]
The reason we do the strange merge is because at some point, passing input options as output options was done by some tools even though it is not intended to work this way. By specification, you should pass a single outputOptions object to bundle.write and nothing else

**Comment by Kirpich634** [comment]
Thank you for your help.
