### ISSUE TITLE
Else without braces and spaces gets concatenated to function names

### ISSUE THREAD

**Issue by CadenP** [rollup/rollup#3419]
- Rollup Version: 1.32.0 (also for 1.10.1, didn't try others)
- Operating System (or Browser): Windows (WSL: Ubuntu), Chrome
- Node Version (if applicable): 13.5.0
- Link to reproduction (IMPORTANT, read below): https://rollupjs.org/repl/?version=1.32.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwc29tZXRoaW5nJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZyglNUMlMjJ0aGluZyU1QyUyMiklMjAlMkYlMkYlMjBzaWRlJTIwZWZmZWN0JTIwdG8lMjBrZWVwJTIwdGhlJTIwbWV0aG9kJTIwbmFtZSU1Q24lNUNuaWYlMjAobWF0aC5yYW5kKDAlMkMlMjAxKSUyMCUzRCUzRCUzRCUyMDAuNSklMjAlN0IlMjAlMkYlMkYlMjBub25zZW5zaWNhbCUyMHRvJTIwc2ltcGx5JTIwa2VlcCUyMHRoZSUyMGlmJTJGZWxzZSU1Q24lN0QlMjBlbHNlJTVDJTIycHJvZHVjdGlvbiU1QyUyMiElM0QlM0QlNUMlMjJsb2NhbCU1QyUyMiUzRnNvbWV0aGluZygpJTNBdm9pZCUyMDAlM0IlMjAlMkYlMkYlMjBub3RpY2UlMjB0aGUlMjAlNUMlMjJlbHNlc29tZXRoaW5nJTVDJTIyJTIwcmVzdWx0JTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior
`else` and following function name should be separated by a space.

### Actual Behavior
`else` is combined with the function name.

### Context
This is found in the npm `history` module in file `history.js` of the v5 beta (in the installed module; I can't find it on GitHub). As such, I cannot modify it on my own. The file looks to have been previously minimized, and is valid until Rollup is run on it in my project.

The code as it appears is as follows (edited for brevity):
```js
if(null!=e){/* ... */}else"production"!==process.env.NODE_ENV?x(!1,"You are trying to block a POP navigation ..."):void 0;else u("POP")
```

My config uses `@rollup/plugin-replace` to replace `process.env.NODE_ENV` with, in this case, a non-`"production"` string, which then results in the following code after Rollup completes:

```js
if(null!=e){/* ... */}elsex$2(!1,"You are trying to block a POP navigation ...");else u("POP");
```

The resulting error is `Uncaught SyntaxError: Unexpected token 'else'`, which is pointing to the `else u("POP");` part of the code, since the previous `else` was converted to `elsex$2`.

**Comment by lukastaegert** [comment]
Thanks for spotting this, fix at #3421.
