### ISSUE TITLE
Rollup misprocesses imports, causes crash at runtime

### ISSUE THREAD

**Issue by wereHamster** [rollup/rollup#3424]
- Rollup Version: 2.0.0
- Operating System (or Browser): macOS
- Node Version (if applicable): 13.x
- Link to reproduction (IMPORTANT, read below): https://github.com/wereHamster/linaria-react-rollup-bug

To reproduce the bug, clone the repo, `npm i`, `rollup -c rollup.config.js`, `node output.js`.

I reported the error first to linaria (https://github.com/callstack/linaria/issues/543), but it could also be a bug in rollup (or a misconfiguration on my end, though I don't see anything wrong with my rollup config…).

### Expected Behavior

No crash at runtime.

### Actual Behavior

Crash at runtime.

**Comment by lukastaegert** [comment]
I did a quick check, so I think what is happening is the following:
- You told `rollup-plugin-commonjs` that `linaria/react` has a named export `styled` (which it kindof has in the TS types, but in CJS it is more complicated)
- But it also has a default export which apparently is imported by another part of the application (at least in the CJS parts)
- If a file has mixed default and named exports in CJS, then the default export is expected to be a property `.default` (which is wrong here)

So try the following:
- remove the `namedExports` option from your CJS plugin in your rollup config
- just import the default from `linaria/react` and use the `.styled` property in your code

In any case as you are importing the CJS version, this is what will be happening anyway.

**Comment by wereHamster** [comment]
I found another workaround: Set `mainFields: "main"` in the resolve plugin. The problem seems to be caused by mixing CJS and ESM code…

**Comment by wereHamster** [comment]
I have a simpler test. Using this input file (which runs fine directly under nodejs)

```js
const isPropValid = require("@emotion/is-prop-valid");
console.log(isPropValid);
console.log(isPropValid.default("x"));
```

When I compile it using babel (with just the commonjs + node-resolve plugins), it produces bad output:

```
'use strict';

function memoize(fn) {
  var cache = {};
  return function (arg) {
    if (cache[arg] === undefined) cache[arg] = fn(arg);
    return cache[arg];
  };
}

var reactPropsRegex = /…snip/;

var index = memoize(function (prop) {
  return reactPropsRegex.test(prop) || prop.charCodeAt(0) === 111
  /* o */
  && prop.charCodeAt(1) === 110
  /* n */
  && prop.charCodeAt(2) < 91;
}
/* Z+1 */
);

console.log(index);
console.log(index.default("x"));

```

**Comment by TMaszko** [comment]
It produces bad output because order matters in `mainFields` option. Here https://github.com/rollup/plugins/tree/commonjs-v11.1.0/packages/node-resolve#mainfields you have default options. First is `module` so it takes `.esm` file and then it trying converts it from esm to commonjs `thats why you get rid off `export default` and because it's not a `.cjs` file you are not getting default property :) 
Hope this explanation helps ! :)
