### ISSUE TITLE
Why is $1 appended to external dependencies?

### ISSUE THREAD

**Issue by flekschas** [rollup/rollup#343]
I am running into the issue that Rollup (`v0.21.1`) is appending `$1` to external dependencies when creating an IIFE.

Here's an example:

```
import * as d3 from 'd3';
class Whatever {
   ...
}
export default Whatever;
```

Now for some reason this gets converted into:

```
var whatever = (function (d3$1) { ... })(d3$1);
```

This causes an issue because there is no global object called `d3$1`. Is this to be expected to is this a bug? For some reason this doesn't happen all the time. I am another file which also depends on `d3` without `$1` being appended.

**Comment by flekschas** [comment]
Okay I figured out that this behavior is caused by the fact that I forgot to import d3 in another class that I imported. It might be helpful to print a warning about potential name clashes.

My actually looked like this:
```
// whatever.js
import * as d3 from 'd3';
import * as d3 from './stuff.js';
export default class Whatever {
   ...
}

// stuff.js
export default class Stuff {
   constructor () {
      // Here I used `d3` but forgot to import it. This caused the main import to change `d3` to `d3$1`.
      this.stuff = d3.svg.diagonal();
   }
}
```

**Comment by acidjazz** [comment]
Why was this closed? I think a warning is a great idea

**Comment by TrySound** [comment]
@Rich-Harris I think we should be more agile this case
```
Treating 'd3' as external dependency
No name was provided for external module 'd3' in options.globals – guessing 'd3$1'
```
The global variable should be the same or similar to imported name, not just what we just invent.

**Comment by chrisbeaver** [comment]
I am trying to workin with this one here too. I have an entry point to my library at /src/scripts/main.js, and in main.js I want to define variables that can be accessed by modules from within the IIFE. So essentially, how do I do this?
// hypothetically created main.js
(function() {
let x = 5;
function useX()
{
    console.log(x);
}
useX();
})();

useX.js would be a module in this case I import, but it's not going to access the higher scoped x that I want. Instead, it renames it:

 let x$1 = 5;

How can I access variables that are a level up in scope without exporting and importing? I went that route, and it led to issues with callback on AJAX handlers. Thanks!

**Comment by guybedford** [comment]
I believe this is the current behaviour in the latest version but let me know if I'm wrong.

**Comment by m-schuetz** [comment]
I've also had the $1 issue which caused some problems down the line because I needed the original export names during runtime. @flekschas comment finally helped me to resolve this: https://github.com/rollup/rollup/issues/343#issuecomment-161741656

A warning that a class is being renamed because it is used somewhere without an import declaration could probably help others who run into the same issue.

**Comment by kirkouimet** [comment]
Did this warning ever make it into rollup? Running into this now.

**Comment by Sidnioulz** [comment]
In a Vue codebase, this very issue has caused my code to be unusable, because Nuxt apps wouldn't import my Vue variable suffixed with `$1`.

There was no missing import. I had a Vue Class Component file with a default export named `Foo`:

```ts
export default class Foo extends Vue {
```

That default export is loaded by an `index.ts` file that renames it to `Bar`, and creating an export named `Foo` which was a wrapped version of the original component:

```ts
import Bar from './Foo.vue'
export { default as Bar } from './Foo.vue'
export const Foo = someIrrelevantWrapper(Bar)

That export would be transformed into `Foo$1` because in another file, a `Foo` default export existed. That is despite the fact that my project never directly exports said `Foo`.

When the library is imported in a Nuxt project, Vue goes bonkers:
`[Vue warn]: Invalid component name: "Foo$1". Component names should conform to valid custom element name in html5 specification.`

That probably has to do with variable names being used to populate name properties in Vue internals. Now, the fact of the matter is that this `$1` suffix has no logical basis. I cannot help but think there is a shortcut taken in the logic that aims to avoid duplicate names.

As you can surely guess, I can't share a MWE as this is proprietary code and it would take me days to extract all the build chain and make a relevant example, but I'm happy to test hypotheses on my end if given instructions.
