### ISSUE TITLE
Merged sourcemap should embed input source contents

### ISSUE THREAD

**Issue by edoardocavazza** [rollup/rollup#3433]
### Feature Use Case

Web apps debug can be hard if you have a lot of pre-bundled components and modules as dependency and the sourcemap covers app's only sources.

### Feature Proposal

When a plugin loads a sourcemap (for example, using [rollup-plugin-sourcemaps](https://www.npmjs.com/package/rollup-plugin-sourcemaps) or the [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel) with the `inputSourceMap` option), rollup should collect and handle source contents files instead of wipe them out.

**Comment by lukastaegert** [comment]
Please add a reproduction using one of those plugins. Rollup does preserve sourcemaps if a plugin provides them in a `load` hook, otherwise it would not make sense that rollup-plugin-sourcemaps exists.

**Comment by edoardocavazza** [comment]
Hi @lukastaegert, thanks for your reply. Here is a reproduction case: https://gitlab.com/edoardo.cavazza/rollup-sourcemaps

**Comment by edoardocavazza** [comment]
You are right @lukastaegert, it seems that it is a bug with the babel sourcemaps. I swear I had a check before opening the issue 😅 I am sorry for the noise!
