### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ashubham** [rollup/rollup#3434]
- Rollup Version: 1.31
- Operating System (or Browser): osx
- Node Version (if applicable): 12.10
- Link to reproduction (IMPORTANT, read below):
https://github.com/apollographql/apollo-client/issues/6035

This is most probably due to this snippet of code in apollo-client:
```
export function requireReactLazily(): typeof import('react') {
  return React || (React = require('react'));
}
```
I am using plugin-commonjs/node-resolve.
Output format: `esm`

### Expected Behavior

Rollup should bundle `React` along with apollo-client. And not fail during runtime.

### Actual Behavior

App load fails with `require is not defined` error.

**Comment by lukastaegert** [comment]
Rollup does not support mixing CommonJS and ES modules, not even with rollup-plugin-commonjs. As this snippet is in Apollo and not your own code I am really not sure how to fix this except trying to hand-patch it and trying to convince them to use a properly well-defined module format instead of something dreamed up by Webpack that no actual runtime supports. The idiomatically correct and supported approach to do a lazy import is to use a dynamic import.
Alternatively, putting the snippet in a pure CJS module that does not use the `export` keyword would work as well.

**Comment by ashubham** [comment]
FWIW, this didn't work even when I put the output as `cjs` in rollup. Is that expected too ?

**Comment by ashubham** [comment]
@lukastaegert I see that `apollo-client` offers a `cjs` dist too. Is there a way to force `node-resolve` plugin to force resolve from `main` instead of `module` field for a particular package ?

**Comment by TrySound** [comment]
You can write simple plugin to handle this case until apollo fix it. I had a lot of such plugins a while ago.
```
{
  transform(code, id) {
    if (id.includes('@apollo/client/react/react.js')) {
      return `import * as React from 'react';export function requireReactLazily(){return React}`
    }
  }
}
```

**Comment by lukastaegert** [comment]
Not easily without forcing everything to use CJS. I would try to do a deep import of the CJS entry

**Comment by ashubham** [comment]
@TrySound your workaround seems to work, with a minor change of `import React from 'react';` instead of `import * as React from 'react';`.

I will close the issue as it seems to be more with `apollo-client` rather than rollup itself. Anyways, thanks for helping out folks!

**Comment by TrySound** [comment]
@ashubham Named exports is the recommended way now. Default export will be removed from react eventually.
It will lead to issue with named exports detection but there is a workaround for this too
```
import * as react from 'react';
import * as reactDom from 'react-dom';
commonjs({
  namedExports: {
    react: Object.keys(react),
    'react-dom': Object.keys(reactDom)
  }
})
```
By the way soon rollup is gonna detect all named exports automatically.

**Comment by s33h0w** [comment]
@ashubham I had the same problem. And I found that this repository is archived. Now you can set [`transformMixedEsModules=ture`](https://github.com/rollup/plugins/tree/master/packages/commonjs#transformmixedesmodules) with using [`@rollup/plugin-commonjs`](https://github.com/rollup/plugins/tree/master/packages/commonjs) to use the mixed ES and CommonJS modules.

> ### transformMixedEsModules: 
> Instructs the plugin whether or not to enable mixed module transformations. This is useful in scenarios with mixed ES and CommonJS modules. Set to true if it's known that require calls should be transformed, or false if the code contains env detection and the require should survive a transformation.
