### ISSUE TITLE
Should emitFile take an importer?

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#3436]
### Feature Use Case

Take plugin code like this:

```js
const prefix = 'typescript:';
{
  async resolveId(id, importer) {
    if (!id.startsWith(prefix)) return null;

    const realId = id.slice(prefix.length);
    const resolveResult = await this.resolve(realId, importer);
    if (!resolveResult) {
      throw Error(`Cannot resolve ${realId}`);
    }
    return prefix + resolveResult.id;
  },
}
```

Which converts `typescript:./whatever.ts` to `typescript:/full/path/to/whatever.ts`, based on the importer.

However, another plugin cannot invoke this via `emitFile`:

```js
this.emitFile({
  type: 'chunk',
  id: 'typescript:./whatever.ts',
});
```

The other plugin would have to understand the `typescript:` prefix, and handle resolving itself.

### Feature Proposal

```js
this.emitFile({
  type: 'chunk',
  id: 'typescript:./whatever.ts',
  importer: '…',
});
```

The value of `importer` would be passed to `resolveId`.

**Comment by lukastaegert** [comment]
> However, another plugin cannot invoke this via emitFile

I do not believe this is true. An `id` from `emitFile` should run through the whole chain of `resolveId`, `load` and `transform`. Not happy to implement a new mechanism on top of the existing one.

**Comment by jakearchibald** [comment]
> An `id` from `emitFile` should run through the whole chain of `resolveId`

Right, but what will `importer` be?

**Comment by lukastaegert** [comment]
What do you mean importer? The first plugin that feels responsible for the id will load it, in case of a `.ts` id it will be the TypeScript plugin, and it is also passed to all transformers. Just how regular imports work.

**Comment by lukastaegert** [comment]
The mechanism that resolves, loads and transforms entry points and imports is the same mechanism that resolves, loads and transforms emitted chunks.

**Comment by lukastaegert** [comment]
Ah, sorry, I totally misunderstood what you meant. You mean the second argument of `resolveId`. I thought you meant something like a loader.

**Comment by lukastaegert** [comment]
Yes, being able to configure the importer would make sense when emitting a file.

**Comment by jakearchibald** [comment]
Yep! Sorry for explaining it badly.

**Comment by lukastaegert** [comment]
Please have a look if #3442 would work for you.
