### ISSUE TITLE
Broken sourcemaps for two outputs of different entryFileNames in same dir

### ISSUE THREAD

**Issue by danimoh** [rollup/rollup#3439]
- Rollup Version: 2.0.2
- Operating System: Fedora
- Node Version: 12.13.1
- Link to reproduction: https://repl.it/repls/GraveProudCore

### Expected Behavior

Generated sourcemaps for individual bundles generated in an output dir should reference their respective bundle file.

### Actual Behavior

All sourcemaps for bundles named via `entryFileNames` in the same output dir reference the last generated file (`"file":"bundle.cjs.js"` in the example repl).
Chrome DevTools fails to parse the erroneous sourcemaps.

### Use case

The repl setup is somewhat artificial. The desired behavior can in the example be achieved more elegantly and without issues by using `output.file` instead of `output.dir` in combination with `output.entryFileNames`. However, there are uses cases where such a setup makes sense, for example when one wants to generate declaration files with the typescript plugin which requires specifying the `dir` option.

**Comment by danimoh** [comment]
For anyone running into this issue:
This can be fixed with a very simple output plugin, for example for the repl linked in the issue:

```js
import path from 'path';

// Fixes broken sourcemaps generated by rollup which might mess up association to a sourcemap's bundle file when writing
// multiple outputs to the same directory, see https://github.com/rollup/rollup/issues/3439.
function fixSourcemaps() {
    return {
        name: 'fix-sourcemaps',
        generateBundle: (options, bundle) => {
            for (const assetOrChunkInfo of Object.values(bundle)) {
                if (!assetOrChunkInfo.map) return; // has no sourcemap
                assetOrChunkInfo.map.file = path.basename(assetOrChunkInfo.fileName);
            }
        },
    };
}

export default {
  input: 'input.js',
  output: [
    {
      dir: 'output',
      format: 'es',
      entryFileNames: 'bundle.es.js',
      sourcemap: true,
      plugins: [fixSourcemaps()],
    },
    {
      dir: 'output',
      format: 'cjs',
      entryFileNames: 'bundle.cjs.js',
      sourcemap: true,
      plugins: [fixSourcemaps()],
    },
  ],
};
```

**Comment by lukastaegert** [comment]
Sorry, for this, fix at #3440

**Comment by lukastaegert** [comment]
Respect you found such an easy workaround using the plugin API 👍

**Comment by danimoh** [comment]
Awesome, thank you for the fix :)
