### ISSUE TITLE
Expose importer path to dynamicImportFunction

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/rollup#3444]
### Feature Use Case
Native dynamic imports resolve paths relative to the importing module. When implementing a dynamic import polyfill, it would be ideal to implement the same logic. 

### Feature Proposal
When using `dynamicImportFunction`, only the imported module path is exposed. It would be great if the importing module URL could be exposed as well.

So instead of:

```
importShim('./foo.js');
```

Do:

```
importShim('./foo', import.meta.url);
```

A dynamic import polyfill could then resolve the URL somewhat like this:

```
window.importShim = (id, importer) => {
  const importPath = new URL(id, importer);
  // ... rest of the logic
});
```

**Comment by LarsDenBakker** [comment]
See https://github.com/GoogleChromeLabs/dynamic-import-polyfill/issues/8 why this is necessary for polyfills.

**Comment by lukastaegert** [comment]
I see your point, but I am still undecided. Another approach I am considering is to add a new `renderDynamicImport` hook that has the ability to both transform the import function and the arguments, and especially add additional ones. Still, your suggestion makes sense as a default when a `dynamicImportFunction` is supplied.

**Comment by lukastaegert** [comment]
Here is the `renderDynamicImport` hook, including an example how to solve your issue: #3449 

My preference would be to go with this hook and otherwise deprecate the `dynamicImportFunction` with the next major version.

**Comment by LarsDenBakker** [comment]
Deprecating `dynamicImportFunction` sounds like the right approach here!
