### ISSUE TITLE
Tree shaking in dynamic modules

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#3447]
### Feature Use Case

[Repl example](https://rollupjs.org/repl/?version=2.1.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmFzeW5jJTIwZnVuY3Rpb24lMjBtYWluKCklMjAlN0IlNUNuJTVDdGNvbnN0JTIwJTdCJTIwZXhwb3J0MSUyMCU3RCUyMCUzRCUyMGF3YWl0JTIwaW1wb3J0KCcuJTJGdXRpbHMuanMnKSUzQiU1Q24lNUN0ZXhwb3J0MSgpJTNCJTVDbiU3RCU1Q24lNUNubWFpbigpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydXRpbHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBleHBvcnQxKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKDEpJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBleHBvcnQyKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKDEpJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

`export2` is unused but appears in the bundle.

### Feature Proposal

Object shape tracking was mentioned in https://github.com/rollup/rollup/issues/3417#issuecomment-594363336.

I'm aware this issue has been discussed in many other issues, but it felt like it didn't have its own issue. Feel free to close if it doesn't need one.

**Comment by frank-dspeed** [comment]
I think this is overall impossible 

```js
import(variable)
``` 

we will never know what gets used and whats not get used as it could be even imported in other context as well.

but we can keep it open maybe we have in future some sort of AI that can guess that after a full pupeteer test or something like that

**Comment by lukastaegert** [comment]
Oops, wrong account, now that was funny

**Comment by mischnic** [comment]
> future some sort of AI

Indeed...

**Comment by guybedford** [comment]
Wow the bots really are getting pretty good :)

**Comment by jakearchibald** [comment]
@frank-dspeed 

> I think this is overall impossible
> 
> ```js
> import(variable)
> ```

Right, but that isn't what this issue is about. This is about cases where the bundler knows which module is being imported.

**Comment by frank-dspeed** [comment]
@jakearchibald such code splitting is possible via wrappers

original-module.js
```js
exports  { me, him, watson, otherDog, cat}
```

wrapper-i-call-this-lib.js
```js
exports { watson, otherDog } from './original-module.js'
```

myapp.js
```js  
import { watson } from './wrapper-i-call-this-lib.js'
``` 


other-part-of-app.js
```js  
import('./wrapper-i-call-this-lib.js').then(({ otherDog })=>console.log('Not as cute as watson))
``` 

#### Resulting

cunk of wrapper-i-call-this-lib.js that is shared will still contain only watson and otherDog
```js
exports { watson, otherDog } from './original-module.js'
```

**Comment by frank-dspeed** [comment]
@jakearchibald the wrapper or lib.js is the file where you can put your information about the import exports that are used project wide that also allows easy code injection for tests and all that.

**Comment by frank-dspeed** [comment]
After working now some month on the vscode rollup integration i regonized that the algo that typescript uses is able to do this via unused vars so we rollup could reuse the typescript ast via a adapter at present and maybe also on the long run replace acornjs with typescript

we could also replicate the typescript algo that allows to do so but i am not a big fan of that idea.as we do not have the man power for it while it would be cool to do a acorn js version of un used variables inside a project 

The most fast way would be to give the acorn ast to typescript then get from typescript the un used variables and strip them.
