### ISSUE TITLE
Cannot call this.emitFile for asset with Uint8Array in browser: Buffer is not defined

### ISSUE THREAD

**Issue by nitsky** [rollup/rollup#3450]
In the browser build of rollup, when I call this.emitFile from a plugin for an asset with a Uint8Array as the source, I get a crash: "Buffer is not defined".

Below is a link to the line that assumes Buffer is defined globally. Buffer is not available in the browser.
https://github.com/rollup/rollup/blob/master/src/utils/FileEmitter.ts#L113

Here is the specification in the types that Uint8Array should be allowed:
https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts#L130

- Rollup Version: 2.1.0
- Operating System (or Browser): Browser

**Comment by lukastaegert** [comment]
Definitely a bug, thanks for reporting.

**Comment by lukastaegert** [comment]
Resolved via #3452
