### ISSUE TITLE
Can't resolve index.js files

### ISSUE THREAD

**Issue by t128** [rollup/rollup#346]
Hi,

*rollup* is not able to resolve *index.js* modules from a directory eg:
```javascript
// main.js
import foo from './foo';

foo();
```

```javascript
// foo/index.js
export default function doThings() {
  return 'barz';
}
```

the warning:
```
Treating './foo' as external dependency
```

**Comment by Victorystick** [comment]
That behaviour is _Node and NPM specific_ and therefore not included in the core Rollup library. Please install [`rollup-plugin-npm`](https://github.com/rollup/rollup-plugin-npm) to add the behaviour.

**Comment by t128** [comment]
i actually second this :)

thank you

**Comment by rbrtmrtn** [comment]
`rollup-plugin-npm` has been renamed to [`rollup-plugin-node-resolve`](https://www.npmjs.com/package/rollup-plugin-node-resolve).

**Comment by wickkidd** [comment]
Moved to https://github.com/rollup/plugins as [node-resolve](https://github.com/rollup/plugins/blob/master/packages/node-resolve).

**Comment by jedwards1211** [comment]
I assumed `@rollup/plugin-node-resolve` was here but the first line of its readme says:

> A Rollup plugin which locates modules using the Node resolution algorithm, for using third party modules in node_modules

So I thought, uhoh, I don't want to include stuff from `node_modules` in my bundle, maybe this isn't the plugin I'm looking for...

Seems like we should clarify its purpose in the docs.

**Comment by jedwards1211** [comment]
My server-side code is full of babel-transpiled import statements that use node resolution, from the days before Node even supported ESM...do I have to refactor my entire codebase to even bundle my code with rollup?

**Comment by MrJadaml** [comment]
hmm, I have the node resolve plugin and I am still seeing these issues:

```
import resolve from '@rollup/plugin-node-resolve'
import babel from 'rollup-plugin-babel'
import typescript from 'rollup-plugin-typescript2'
import postcss from 'rollup-plugin-postcss'

const packageJson = require('./package.json')

export default {
  input: 'src/index.js',
  output: {
    file: packageJson.module,
    format: 'esm',
  },
  plugins: [
    resolve(),
    babel({
      runtimeHelpers: true,
      presets: [
        '@babel/preset-react',
      ]
    }),
    typescript({ useTsconfigDeclarationDir: true }),
    postcss({ modules: true }),
  ],
  external: [/node_modules/],
}
```
source of the error when running build:
```
import Input from './input'
import Link from './link'
import Text from './text'

export { Input, Link, Text }
```
If I do `import Input from './input/index.tsx' I run into a whole other issue: https://github.com/Microsoft/TypeScript/issues/27481
_it's a real party over in that issue..._

**Comment by Hanawa02** [comment]
I agree with @jedwards1211, what I need is not to resolve modules from external packages, but from my own repo.

What I have is:
```js
// src/components/index.js
import AboutSection from "./about-section"
```

and I have a normal working vue component in `src/components/about-section/index.vue`.

If I change my import to this it works:

```js
// src/components/index.js
import AboutSection from "./about-section/index.vue"
```

There is a solution for my case, but would be nice if I didn't need to define the file if it's an index one.
