### ISSUE TITLE
Extend the documentation by adding examples

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/rollup#3463]
Can you please extend the documentation by providing examples, like for this:

bootstrap 4 uses as peer dependencies popper.js (available as ES6 module) and jquery (no es module).  Bootstrap, popper.js and jquery provide a separate .js file.  To have a functional website all three must be loaded by the browser.  However loading them separately means three HTTP requests, so better is to unify them into one.  Moreover, since version 3 jquery comes in slim and fat variant.  For bootstrap the slim variant is sufficient.

Please provide an example how to create a javascript file by rollup, lets  say in ES6, iife and UMD output, so that the size of the file is nearly the same as the sum of the sizes of jquery/dist/jquery.slim.min.js, popper.js/dist/esm/popper.min.js, and bootstrap/dist/js/bootstrap.min.js .  Using or not, globals, external, import and whatsoever.

This example will help verymuch how Rollup works.

**Comment by shellscape** [comment]
If this is a documentation request, please fill out the documentation issue template. Otherwise, your issue may be closed.

**Comment by dilyanpalauzov** [comment]
This is a documentation request and a hint.

I`ll do you a favour and close this myself.
