### ISSUE TITLE
output.paths w/ dynamic imports

### ISSUE THREAD

**Issue by gingur** [rollup/rollup#3464]
- Rollup Version: 2.2.0
- Operating System (or Browser): Windows
- Node Version (if applicable): 12.16.1
- Link to reproduction: [repl](https://repl.it/@gingur/rollup-repro)

### Expected Behavior
When using `output.paths`, I expect all module references to be updated.

```js
// config
output.paths = { a: 'http://a.js' };
```

```js
// input
import 'a';
import('a');
```

```js
// output
define(['require', 'http://a.js'], function (require, a) {
   new Promise(function (resolve, reject) { require(['http://a.js'], resolve, reject) });
});
```

### Actual Behavior
```js
// output
define(['require', 'http://a.js'], function (require, a) {
   new Promise(function (resolve, reject) { require(['a'], resolve, reject) });
});
```
Only static module references are being converted, dynamic imports are using the original path instead of the resolved paths module id.

**Comment by lukastaegert** [comment]
Fix at #3508
