### ISSUE TITLE
New colouring algorithm issue

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#3466]
- Rollup Version: 2
- Operating System (or Browser): any
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): https://github.com/rollup/plugins/pull/241

I'm not sure what this bug about. Looks like rollup detects something. Would be better to have warning if it affects runtime.

### Expected Behavior

Probably chunk.modules should not be empty

### Actual Behavior

chunk.modules is empty which leads to run plugin fail

**Comment by lukastaegert** [comment]
chunk.modules is empty if all modules are tree-shaken. If that is case, it should also be an empty chunk. Is that the case? Or what is the connection here. I do not really have a lot of time on my hands for debugging unfortunately at the moment, the CI output does not help much.

**Comment by lukastaegert** [comment]
Also, is 2 (.?.? it does not hurt to add the actual version) the version where the issue first occurs

**Comment by TrySound** [comment]
Sorry, here's detailed repro with rollup 2.2.0
https://github.com/TrySound/rollup-issue

Treeshaking is not a problem. The problem comes when root module and dynamic import depend on one library and both have module level expressions.

Here's content of bundle. Root chunk does not reference to entry point module. Though run plugin depends on this

https://github.com/rollup/plugins/blob/cbc341d07cc1343ee03ada5d268b8f2ee4778c63/packages/run/lib/index.js#L52

```
[Object: null prototype] {
  'index.js': {
    code: "'use strict';\n\nrequire('./index-37608f29.js');\n\n",
    dynamicImports: [],
    exports: [],
    facadeModuleId: '/Users/bogdancadkin/host/rollup-sandbox/index.js',
    fileName: 'index.js',
    imports: [ 'index-37608f29.js' ],
    isDynamicEntry: false,
    isEntry: true,
    map: null,
    modules: [Object: null prototype] {},
    name: [Getter],
    type: 'chunk'
  },
  'index-37608f29.js': {
    code: "'use strict';\n" +
      '\n' +
      'const log = value => console.log(value);\n' +
      '\n' +
      'log(0);\n' +
      '(async () => {\n' +
      "  await new Promise(function (resolve) { resolve(require('./dynamic-8a9dfc94.js')); });\n" +
      '})();\n' +
      '\n' +
      'exports.log = log;\n',
    dynamicImports: [ 'dynamic-8a9dfc94.js' ],
    exports: [ 'log' ],
    facadeModuleId: null,
    fileName: 'index-37608f29.js',
    imports: [],
    isDynamicEntry: false,
    isEntry: false,
    map: null,
    modules: [Object: null prototype] {
      '/Users/bogdancadkin/host/rollup-sandbox/library.js': [Object],
      '/Users/bogdancadkin/host/rollup-sandbox/index.js': [Object]
    },
    name: [Getter],
    type: 'chunk'
  },
  'dynamic-8a9dfc94.js': {
    code: "'use strict';\n" +
      '\n' +
      "var index = require('./index-37608f29.js');\n" +
      '\n' +
      'index.log(0);\n',
    dynamicImports: [],
    exports: [],
    facadeModuleId: '/Users/bogdancadkin/host/rollup-sandbox/dynamic.js',
    fileName: 'dynamic-8a9dfc94.js',
    imports: [ 'index-37608f29.js' ],
    isDynamicEntry: true,
    isEntry: false,
    map: null,
    modules: [Object: null prototype] {
      '/Users/bogdancadkin/host/rollup-sandbox/dynamic.js': [Object]
    },
    name: [Getter],
    type: 'chunk'
  }
}
```

**Comment by lukastaegert** [comment]
This is not a Rollup bug but a bug in the plugin that has been present before Rollup 2, see my comment at rollup/plugins#241
