### ISSUE TITLE
getFileName returns incorrect result with multiple outputs

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/rollup#3467]
- Rollup Version: v1.31.0 & v2.2.0
- Operating System (or Browser): OS X
- Node Version (if applicable): 10
- Link to reproduction (IMPORTANT, read below): https://repl.it/repls/MetallicMinorCareware

### Expected Behavior
When using `this.getFileName` on a manually created chunk, I don't get the correct filename with multiple build outputs. In `generateBundle` for both phases, I get the filename of the last output.

I set the output to directory, since the REPL doesn't seem to support multiple outputs? 

### Actual Behavior
I get the same same file name for both phases.

**Comment by lukastaegert** [comment]
Please do not forget to add the Rollup version to the template. I assume it is the latest but once someone gets to looking into this, who knows what latest was when you created the issue.

**Comment by LarsDenBakker** [comment]
Sorry about that, I got this with rollup v2.2.0 locally and the v1.31. loaded by the repl.

**Comment by lukastaegert** [comment]
Ok, this one is nastier than I thought. Basically it is caused by an unfortunate design design where chunk objects are reused for each output. The long term goal is to refactor everything so that this is no longer the case, but the question is how long this will take. This would also fix this issue. But I am not sure how to provide a short-term fix.

**Comment by LarsDenBakker** [comment]
Thanks for looking into it. For now I am able to work around it by using two separate output plugins.

**Comment by lukastaegert** [comment]
Fix at #3645, which will finally move chunk creation to the output generation phase and make manualChunks, inlineDynamicImports and preserveModules output options.

**Comment by LarsDenBakker** [comment]
Thats great! It enables a lot of possibilities.
