### ISSUE TITLE
Async function support

### ISSUE THREAD

**Issue by t128** [rollup/rollup#347]
Hi,

it seems that there is no *async*/*await* support in rollup.

```javascript
async function fooBarz() {
  await asyncBarz();
}
```
throws a parser error.

**Comment by eventualbuddha** [comment]
You can use [`rollup-plugin-babel`](https://github.com/rollup/rollup-plugin-babel) to make this work, I believe.

**Comment by t128** [comment]
actually i want to compile my code to es6, babel would return es5 code. My problem is the parse error when i *rollup* it.

**Comment by eventualbuddha** [comment]
It looks like the [`transform` plugin hook can return an object with an `ast` property](https://github.com/rollup/rollup/blob/6bc0ef45bff8f652164c305a4f50d13ed762db89/src/Bundle.js#L147-L151) that will be used instead of rollup parsing itself. I'm guessing something like this will work:

```js
import { parse } from 'babylon';

rollup({
  // …
  plugins: [
    {
      transform(source) {
        return { source, ast: parse(source, { sourceType: 'module', plugins: ['asyncFunctions'] }) };
      }
    }
  ]
});
```

**Comment by t128** [comment]
```javascript

		plugins: [
			{
				transform(source) {
					const ast = $.babylon.parse(source, {
						sourceType: 'module',
						plugins: ['asyncFunctions'],
					}).program;

					return {
						code: source,
						ast,
						map: { mappings: '' },
					};
				},
			},
		],
```

seems to work, but the sourcemap is invalid

**Comment by t128** [comment]
by using some undocumented babel features (`babelrc: false`) i came up with this:

```javascript
import rollupBabel from 'rollup-plugin-babel';
[...]
		plugins: [
			rollupBabel({
				babelrc: false,
				plugins: ['transform-async-to-generator', 'external-helpers-2'],
			}),
		],
```

that way we can also use other babel features eg. *jsx*.

**Comment by Victorystick** [comment]
> undocumented babel features (`babelrc: false`)

Neat! Too bad it is an undocumented feature. :cry:

**Comment by alexlur** [comment]
Acorn 4.0 is out with `async/await` support.
