### ISSUE TITLE
Label being incorrectly removed with treeshaking disabled

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#3473]
- Rollup Version: 2.3.1
- Link to reproduction (IMPORTANT, read below): https://github.com/guybedford/rollup-label-bug

### Expected Behavior

There are three labeled `while` loops in the build with `loop:` names.

When running the build with treeshaking enabled, all three labels remain in the output.

### Actual Behavior

When running the build with treeshaking **disabled**, the first `loop:` label is removed! As a result the internal `break loop` fails further parsing.

**Comment by guybedford** [comment]
@lukastaegert any ideas why this might be happening?

**Comment by lukastaegert** [comment]
I see that this labeled break does not have a label to jump to, maybe it is related? https://github.com/guybedford/rollup-label-bug/blob/master/build.js#L220

**Comment by lukastaegert** [comment]
It is hard to reduce the test case

**Comment by guybedford** [comment]
Thanks for taking a look - I've managed to isolate it down to three files in a circular reference that use the same label name, where one of the files contains a function from the other. The isolation at https://github.com/guybedford/rollup-label-bug/blob/master/tokenize-string.js now builds the local file directly. It's definitely a complex case - but the fact remains a valid label (and the code is definitely valid) should not be removed when treeshaking is disabled.

**Comment by lukastaegert** [comment]
Managed to solve it, fix at #3492
