### ISSUE TITLE
Allow emitting chunk in output generation phase

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/rollup#3477]
### Feature Use Case
I am using the new `rollup-plugin-babel` feature where it runs on the generated build output. I created a separate plugin which creates a chunk with babel helpers, and I want to emit this chunk in the build output. 

Unfortunately it is not possible to to emit assets during the output generation phase. The current workaround is to emit an asset instead. The downside is that the generated filename will follow the asset logic instead of chunk logic, and other plugins won't pick up the chunk.

### Feature Proposal
Allow emitting chunks in the output generation phase. Probably with some restrictions, since rollup's build logic is already done.

**Comment by lukastaegert** [comment]
This is fundamentally difficult because it would basically mean to run the build phase again as part of the generate phase. I mean, chunks are not just emitted, they are parsed, tree-shaken, linked etc. As all you want is a file name, you could of course just use a fixed file name via the `fileName` option.

**Comment by LarsDenBakker** [comment]
Is there a way to emit the chunk without doing parsing, tree-shaking etc. So basically put the chunk in the state it would be in after the build logic is finished. Or do you think assets are the correct method for this? It works, but it's a bit strange since it outputs them with the same format as other assets like images.

**Comment by lukastaegert** [comment]
Yes, assets are the correct format IMO. The alternative would be either an entirely new type of chunk or an option to specify which naming scheme to use. But if you emit them as `{type: 'asset', fileName: 'my-chunk.js', source: '...'}` i.e. adding a `fileName` option, you can completely override all naming schemes.

**Comment by LarsDenBakker** [comment]
Thanks for the info. I know I can override the filename in the plugin, but I'd like the user to specify the filename format.

I'll close this issue since there isn't anything actionable.

**Comment by lukastaegert** [comment]
Well, maybe one actionable point could be to allow specifying an alternative naming scheme to be used when issuing an asset that should look like a chunk. I think there a re more use-cases for this.
