### ISSUE TITLE
Baseline Acorn plugins

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#3478]
I'd like to propose that RollupJS provide support-by-default for a baseline set of Acorn plugins matching the ~stage 4 support.

Since any new syntax feature needs Rollup support from an analysis perspective anyway, it seems like it would improve safety in providing a fully supported baseline.

Acorn plugins can be a pain to use due to the indirect plugin injection system, version mismatch issues and conventions and lack of support and maintenance from the Acorn ecosystem. Acorn has been historically over-conservative, and will continue to be so this would help users a lot to simply provide this support out of the box.

For example, static class fields is almost impossible to set up currently despite being a feature shipping in Chrome - it should always be possible to ship JS from Rollup that Chrome supports!

### Feature Proposal

The proposal is to include by default numeric separators and static class fields for now, even though Acorn core doesn't ship with these by default. Then to update this list to match what is shipping in browsers.

This feature could be opt-in or opt-out to use only full ECMA-262 stability.

**Comment by lukastaegert** [comment]
Yes. In the past this was not a problem as acorn was usually quick to support stage 4. I guess we need to take this into our own hands now... PR welcome.

**Comment by lukastaegert** [comment]
I would make it neither opt-in nor opt-out. I do not see any issues for people not using these features.

**Comment by lukastaegert** [comment]
> Then to update this list to match what is shipping in browsers

This would basically also add some stage-3 features. Not sure about that.

**Comment by guybedford** [comment]
I'd be glad to add them, but currently don't know how to. I just tried to configure https://github.com/acornjs/acorn-class-fields and https://www.npmjs.com/package/acorn-static-class-features but both throw due to being for the v6 version of Acorn.

Maybe @adrianheine might have suggestions here.

Yes not all stage3 is necessary, but I think there's a sort of user-consensus that can be found on what to include.

**Comment by lukastaegert** [comment]
Well, I think THAT is the reason why they are not part of acorn yet...

**Comment by guybedford** [comment]
First step: https://github.com/acornjs/acorn-class-fields/pull/8

Next problem is that Acorn is required as a peer dependencies in these libraries - another argument for building this stuff into rollup.

**Comment by lukastaegert** [comment]
True, a "correct" fix would require a rework of these plugins to use the acorn instance that is passed in instead of requiring it, and that would still not solve the issue of the plugin-interdependency.

**Comment by lgersman** [comment]
I would really love to throw way babel in favor of just rollup/acorn. 

So many developers struggle with babel because of its (configuration) complexity. But often they are forced to use it since rollup/acorn does not support jsx out of the box. Does somebody know if the acorn jsx plugin (https://github.com/acornjs/acorn-jsx) works with rollup ?  

If you want to use rollup to "just transform jsx" but leave everything else "as is" (modern / green-browser-es7) you end up currently in a mess of babel configuration. plus - the babel output is always bloated with helpers / unwanted tranformations and stuff. 

I would really love to get an option to use more or less "just rollup" with a few acorn plugins.

**Comment by guybedford** [comment]
Looks like progress is being made here.
