### ISSUE TITLE
Support regex in config.external

### ISSUE THREAD

**Issue by johannes-z** [rollup/rollup#3480]
Related to: https://github.com/rollup/rollup/issues/2882

### Feature Use Case
In webpack it's quite easy to control which packages are external, as it allows an array of strings, regex, etc. This is especially for namespaced/scoped packages.

For example, in [webpack](https://webpack.js.org/configuration/externals/#externals)I'm able to do the following:

```js
externals: [
  /^@pnp\/.*/, // matches for example @pnp/sp, @pnp/common, @pnp/odata, @pnp/logging, ...
  'some-other-dep',
  /node_modules/
]
```

In rollup you either have to specify all the externals specifically, like so:

```js
external: [
  '@pnp/sp',
  '@pnp/odata',
  'some-other-dep',
  // /node_modules/ doesn't work
]
```

or write a function that does that kind of matching for you. I had success with the following function:

```
const externals = [
  /^@pnp.*/,
  'camljs',
  'jquery',
]
// ...
external: id => externals.some(_id => _id === id || (_id.test && _id.test(id))),
```

### Feature Proposal
Rollup could support this out of the box as well. I think webpack's externals is more like a mixture between rollup's `globals` and `external` (correct me if I'm wrong), but `config.external` is already an array anyway. It might as well support regex.

If this is something you want to add, I'm willing to create a PR.

**Comment by lukastaegert** [comment]
Sounds reasonable and I do not see any issues with adding this. So the supported formats would be:
- string
- regexp (new)
- array of strings or regexps (previously only string)
- function

PR welcome!
