### ISSUE TITLE
using the output option "sourcemapPathTransform: () => {}"  causes a TypeError that points to a rollup script

### ISSUE THREAD

**Issue by KilianKilmister** [rollup/rollup#3484]
- Rollup Version: 2.3.3
- Operating System (or Browser): MacOs Catalina
- Node Version (if applicable): v13.12.0
- Link to reproduction (IMPORTANT, read below): https://repl.it/@KilianKilmister/TremendousWoodenQuadrants

### Expected Behavior
Rollup raising an error that mentions the invalid option chosen

### Actual Behavior
Undescriptive TypeError:
```js
TypeError: Cannot read property 'indexOf' of undefined
    at normalize (/Users/USER/dev/QuestJS/node_modules/rollup/dist/shared/rollup.js:6565:14)
    at /Users/USER/dev/QuestJS/node_modules/rollup/dist/shared/rollup.js:15829:61
    at Array.map (<anonymous>)
```

Note: `output.sourcemap`must be set to true aswell 
was a bitch to track this one down. Hopefully this will save some people some trouble

**Comment by lukastaegert** [comment]
Resolved via #3561 thanks to @Simonwep, released in v2.10.3
