### ISSUE TITLE
2.3.3  SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by Here21** [rollup/rollup#3486]
- Rollup Version: 2.3.3
- Operating System (or Browser): Mac OS 10.15
- Node Version (if applicable): 8.11.2
- Link to reproduction (IMPORTANT, read below):

### Expected Behavior
When use rollup@2.2.0 it was succeed.

![image](https://user-images.githubusercontent.com/12051024/78635584-2576cb00-78d9-11ea-948e-9917479fae72.png)

### Actual Behavior
When use rollup@2.3.3 it compile failed.

![image](https://user-images.githubusercontent.com/12051024/78635142-1e9b8880-78d8-11ea-928f-6c25893ea5af.png)

But rollup "repl" always be good.

I had switch rollup to 2.2.0, but I'd like to know, it's Dynamic imports problem? and how to resolve it.

**Comment by TrySound** [comment]
This is because node v8 is not supported anymore.
Minimum required version is 10
https://github.com/rollup/rollup/blob/master/CHANGELOG.md#200

**Comment by Here21** [comment]
@TrySound Oh, THANKS 

Support information demonstrated on obvious position of website or README perhaps good.

**Comment by TrySound** [comment]
It's here. Your package manager should warn you
https://github.com/rollup/rollup/blob/master/package.json#L136-L138

**Comment by Here21** [comment]
Maybe cuz my npm version, I don't saw any warn of node version.

![image](https://user-images.githubusercontent.com/12051024/78652629-8eb80780-78f4-11ea-8586-d0a0db57fa90.png)

![image](https://user-images.githubusercontent.com/12051024/78652695-a55e5e80-78f4-11ea-9571-5c5be5b8fb7d.png)
