### ISSUE TITLE
aws-sdk s3 error: Cannot read property 'memoizedProperty' of undefined

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#3495]
- Rollup Version:  2.6.0
- Operating System (or Browser):  Mac
- Node Version (if applicable):  12.13.1
- Link to reproduction (IMPORTANT, read below):

Shell asked me to open this ticket. It's a newer version of https://github.com/aws/aws-sdk-js/issues/1769

Basically, if you build this

```js
import S3 from "aws-sdk/clients/s3";

exports.handler = async req => {
  try {
    const s3 = new S3({});
    return new Promise(res => {
      var sourceParams = { Bucket: "xxx", Key: "xxx" };
      s3.getObject(sourceParams, (err, data) => {});
    });

    return "";
  } catch (err) {
    return "Err " + (err || "nothing");
  }
};
```

with these Rollup assets

package.json

```
  "dependencies": {
    "aws-sdk": "^2.656.0",
    "jimp": "0.10.1"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^11.0.2",
    "@rollup/plugin-json": "^4.0.2",
    "@rollup/plugin-node-resolve": "^7.1.1",
    "rollup": "^2.6.0",
    "rollup-plugin-terser": "^5.3.0",
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11"
  }
```

and this rollup config

```js
import { terser } from "rollup-plugin-terser";
import commonjs from "@rollup/plugin-commonjs";
import resolve from "@rollup/plugin-node-resolve";

import json from "@rollup/plugin-json";

module.exports = {
  input: "./index.js",
  output: {
    name: "main",
    format: "cjs",
    file: "./index-bundle.js"
  },
  external: [
    "fs",
    "util",
    "stream",
    "events",
    "crypto",
    "http",
    "https",
    "domain",
    "os",
    "path",
    "dgram",
    "buffer",
    "url",
    "querystring",
    "child_process",
    "timers",
    "string_decoder",
    "zlib",
    "assert"
  ],

  plugins: [commonjs(), resolve({ preferBuiltins: true }), terser({}), json()]
};
```
And you run the result in a Lambda function (or maybe anywhere, not sure), you get the same error message as in the original GitHub issue, namely 

> "errorMessage": "Cannot read property 'memoizedProperty' of undefined",

webpack does not have this problem.

**Comment by shellscape** [comment]
Adam should have used a REPL or a repo but he is naughty.

**Comment by lukastaegert** [comment]
I feel with you, but if you expect us to run a lambda function in AWS to debug this, it is very unlikely to be fixed soon.

**Comment by arackaf** [comment]
Like I said, Shell asked me to create this, mentioning that he wants to see it fixed, failing as it does in such a high-visibility package. 

Honestly I moved on and bundled with weBpack, to unblock myself. Best of luck hear, though 👊

**Comment by shellscape** [comment]
@lukastaegert I asked @arackaf to open this based on a Twitter convo. I'll take lead on setting up a REPL we can use to debug.

**Comment by shellscape** [comment]
Don't have time to triage this one, and looks like it was solved by using serverless plugins.

**Comment by arackaf** [comment]
Indeed - aws-sdk is already included in the runtime, so it should never have been bundled to begin with.

Thanks for taking a look!
