### ISSUE TITLE
Rollup to ESM to not create empty default chunks

### ISSUE THREAD

**Issue by mcshaz** [rollup/rollup#3496]
### Expected Behavior / Situation
I am trying to serve module/nomodule scripts, using dynamic import statements to save modern browsers the overhead of loading unnecessary code.

If the input file in the rollup config exports a function, and I run rollup with `format: 'esm'` it works beautifully in creating 1 small chunk which tests for support, and a larger chunk to be dynamically loaded if unsupported.

### Actual Behavior / Situation
However, when the input file is changed to a script which imports the function named above, but does not export anything, the default output file contains nothing but an import reference:
```javascript
import"./example-page-script-d90aa7ad.mjs";
```
That is instead of 2 chunks as above, 3 chunks are created, the first (default file) of which is empty.

### Modification Proposal
empty entry files are not created - chunked files all contain some code.

**Comment by lukastaegert** [comment]
This will be improved once I find the time, #3358 is the tracking issue. See there for why this is happening and how it might be improved.
