### ISSUE TITLE
Rollup class fields error: 'super' keyword outside a method

### ISSUE THREAD

**Issue by pschroen** [rollup/rollup#3505]
- Rollup Version: 2.6.1
- Operating System: macOS Mojave
- Node Version: 13.7.0
- Link to reproduction: https://rollupjs.org/repl/?version=2.6.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBnZXRWYWx1ZSgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMDEyMyUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbmNsYXNzJTIwU3ViQ2xhc3MlMjBleHRlbmRzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBwcm9wJTIwJTNEJTIwc3VwZXIuZ2V0VmFsdWUoKSUzQiU1Q24lN0QlNUNuYXNzZXJ0LmVxdWFsKG5ldyUyMFN1YkNsYXNzKCkucHJvcCUyQyUyMDEyMyklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior

The `super` keyword is valid in class fields. For reference:
https://2ality.com/2019/07/public-class-fields.html#the-scope-of-field-initializers

### Actual Behavior

Error: 'super' keyword outside a method

**Comment by lukastaegert** [comment]
This is an issue in the underlying acorn plugin, I filed an issue upstream: acornjs/acorn-class-fields#9. Not sure when it will be resolved, though, as development is somewhat stalled there 😢

**Comment by ChocolateLoverRaj** [comment]
It still gives the same error. I don't think this issue was fixed.

**Comment by lukastaegert** [comment]
Well, it works in the reproduction now: https://rollupjs.org/repl/?version=2.23.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBnZXRWYWx1ZSgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMDEyMyUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbmNsYXNzJTIwU3ViQ2xhc3MlMjBleHRlbmRzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBwcm9wJTIwJTNEJTIwc3VwZXIuZ2V0VmFsdWUoKSUzQiU1Q24lN0QlNUNuYXNzZXJ0LmVxdWFsKG5ldyUyMFN1YkNsYXNzKCkucHJvcCUyQyUyMDEyMyklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

If it is still broken for you, please post a new one.

**Comment by ChocolateLoverRaj** [comment]
Ok, i realised that my error is slightly different than the error on the issue. It still gives the error message, 'super' keyword outside a method. My error is with static properties using the 'super' keyword. I will start a separate issue.

**Comment by pschroen** [comment]
Referencing the new issue (#3702), should have caught this before...

**Comment by lukastaegert** [comment]
In their defense, this time the issue is likely in another plugin, namely acorn-static-class-features vs.acorn-class-fields
