### ISSUE TITLE
Support for .ts and .tsx file resolutions

### ISSUE THREAD

**Issue by LabEG** [rollup/rollup#351]
For using this plugin https://github.com/rollup/rollup-plugin-typescript, i need change rollup code =\

https://github.com/rollup/rollup/blob/master/src/utils/defaults.js#L11-L12

This is not good.

**Comment by Victorystick** [comment]
This works without any changes if you specify the extension in your import statement. :+1: 

But if that's not something you want, go ahead and create an issue in the `rollup-plugin-typescipt` repo. It should take care of TypeScript specific file extensions.
