### ISSUE TITLE
Anonymous function with a / in the default values

### ISSUE THREAD

**Issue by SandroMiguel** [rollup/rollup#3513]
- Rollup Version: 2.7.2
- Operating System (or Browser): Chrome 81
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): https://rollupjs.org/repl/?version=2.7.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRm1vZHVsZV8xLmpzJykudGhlbihmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnc29tZXRoaW5nJyklM0IlNUNuJTdEKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZV8xLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbih0ZXh0JTIwJTJGKiUzRCUyMCclMkYnKiUyRiklMjAlN0IlN0QlMjAlMkYlMkYlMjBPSyU1Q24lMkYlMkYlMjBJJTIwY2FuJ3QlMjB3cml0ZSUyMGFuJTIwYW5vbnltb3VzJTIwZnVuY3Rpb24lMjB3aXRoJTIwJTJGJTIwaW4lMjB0aGUlMjBkZWZhdWx0JTIwdmFsdWVzJTVDbiUyRiUyRiUyMEJ1dCUyMEklMjBjYW4lMjB3cml0ZSUyMGElMjBuYW1lZCUyMGZ1bmN0aW9uJTIwd2l0aCUyMCUyRiUyMGluJTIwdGhlJTIwZGVmYXVsdCUyMHZhbHVlcyU1Q24lMkYlMkYlMjBVbmNvbW1lbnQlMjB0aGUlMjBwYXJhbWV0ZXIlMjBkZWZhdWx0JTIwdmFsdWUlMjB0byUyMHJlcHJvZHVjZSUyMHRoZSUyMGVycm9yLiUyMFRoaXMlMjBicm93c2VyJTIwd2luZG93JTIwd2lsbCUyMGZyZWV6ZS4lNUNuJTJGJTJGJTIwZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uKHRleHQlMjAlM0QlMjAnaGVsbG8nKSUyMCU3QiU3RCUyMCUyRiUyRiUyME9LJTVDbiUyRiUyRiUyMGV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbih0ZXh0JTIwJTNEJTIwJyUyRicpJTIwJTdCJTdEJTIwJTJGJTJGJTIwTk9LJTIwJTNDLSUyMEZyZWV6ZXMlMjBicm93c2VyJTIwdGFiJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behavior
Don't freeze

### Actual Behavior
Freezes the browser window

I can't write an **anonymous function** with a `/` in the default values
But I can write a **named function** with a `/` in the default values

`export default function(text = 'hello') {} // OK
`

`export default function(text = '/') {} // NOK
`

`export default function something(text = '/') {} // OK
`

**Comment by lukastaegert** [comment]
Thanks for spotting and reporting, fix upcoming!
