### ISSUE TITLE
Incorrect tree shaking result when a function which returns assigned uninitialized var binding is called with `|| false`

### ISSUE THREAD

**Issue by JLHwung** [rollup/rollup#3543]
- Rollup Version: 2.0.0
- Operating System (or Browser): Browser
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): [REPL](https://rollupjs.org/repl/?version=2.0.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwYmFyKCklMjAlN0IlNUNuJTIwJTIwdmFyJTIweCUzQiU1Q24lMjAlMjB4JTIwJTNEJTIwNDIlM0IlNUNuJTIwJTIwcmV0dXJuJTIweCUzQiU1Q24lN0QlNUNud2luZG93LmZvbyUyMCUzRCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTIwJTIwdmFyJTIweCUyMCUzRCUyMGJhcigpJTIwJTdDJTdDJTIwZmFsc2UlM0IlNUNuJTIwJTIwcmV0dXJuJTIweCUyMCUzRiUyMHglMjAlM0ElMjAyMSUzQiU1Q24lN0QlM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==
)

### Expected Behavior

Evaluating `window.foo()` should return `42`

### Actual Behavior

It returns `21` after transforms.

### Additional Context

This example is crafted from a babel [issue](https://github.com/babel/babel/issues/11534#issuecomment-625742700) where `@babel/standalone` incorrectly throws on some valid regex. I have manually tree-shaken the unrelated codes and hope it helps. 

This issue was introduced after 1.27.9, babel has to pin Rollup to this version before it is resolved.

**Comment by dasa** [comment]
Appears to have been fixed in 2.0.5: https://github.com/rollup/rollup/blob/master/CHANGELOG.md#205

**Comment by lukastaegert** [comment]
Yes it is: [REPL](https://rollupjs.org/repl/?shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwYmFyKCklMjAlN0IlNUNuJTIwJTIwdmFyJTIweCUzQiU1Q24lMjAlMjB4JTIwJTNEJTIwNDIlM0IlNUNuJTIwJTIwcmV0dXJuJTIweCUzQiU1Q24lN0QlNUNud2luZG93LmZvbyUyMCUzRCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTIwJTIwdmFyJTIweCUyMCUzRCUyMGJhcigpJTIwJTdDJTdDJTIwZmFsc2UlM0IlNUNuJTIwJTIwcmV0dXJuJTIweCUyMCUzRiUyMHglMjAlM0ElMjAyMSUzQiU1Q24lN0QlM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
