### ISSUE TITLE
Support nullish coalescing

### ISSUE THREAD

**Issue by domoritz** [rollup/rollup#3544]
### Feature Use Case

I would like to use nullish coalescing documented at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator. 

### Feature Proposal

```js
export const c = a ?? b;
```

Should compile to

```js
const c = a ?? b;

export { c };
```

Related issue: https://github.com/rollup/rollup/issues/3469

**Comment by lukastaegert** [comment]
Apparently, nullish coalescing has already been merged upstream and is just waiting to be released. For a month now 🙄 acornjs/acorn#890

But I guess we could switch to a direct Github build of acorn until then.

**Comment by hardfist** [comment]
@lukastaegert It seems that acorn nullish coalescing  coalescing has released
