### ISSUE TITLE
when class or variable dont have export it outputs empty

### ISSUE THREAD

**Issue by aelbore** [rollup/rollup#3549]
- Rollup Version: 2.8.2
- Operating System (or Browser): OSX 
- Node Version (if applicable): 13.13.0
- Link to reproduction (IMPORTANT, read below):

Input Code (./src/index.ts)
```javascript
class HelloWorld {
  static get props() {
    return {
      name: {
        type: String
      }
    }
  }
}
```

Rollup Config
```javascript
export default {
  input: './src/index.ts',
  output: {
    file: './dist/main.js',
    format: 'es'
  }
}
```

### Expected Behavior
should transform or have output

### Actual Behavior
empty output

**Comment by lukastaegert** [comment]
This is how tree-shaking works, statements without side-effects such as an unused declaration are removed. If you do not want this for some reason, set the `treeshaking` option to `false`.

**Comment by aelbore** [comment]
@lukastaegert thanks it works when `treeshaking` set to false, now this is the use of treeshaking 👍 i can close this many thanks.
