### ISSUE TITLE
Illegal imports

### ISSUE THREAD

**Issue by chpio** [rollup/rollup#355]
hi,

im trying to import an other module of mine (which was compiled by rollup to es2015) in my current module. But it seems there is an syntax error in the generated *import* in the other module.

```
SyntaxError:  /myproject/node_modules/js-utils/index.es2015.js: Unexpected token (1:14)
> 1 | import * as fs, { FSWatcher, ReadStream, Stats, WriteStream, createReadStream, createWriteStream, unwatchFile, watch, watchFile } from 'fs';
    |               ^
  2 | 
  3 | /* eslint-disable no-console */
  4 | function asyncMain(func) {
```

changing the generated code to:
```javascript
import * as fs from 'fs';
import { FSWatcher, ReadStream, Stats, WriteStream, createReadStream, createWriteStream, unwatchFile, watch, watchFile } from 'fs';
```
~~fixed~~ workarounded the error.

ps: 
[@see my build script (other module)](https://github.com/sudeti/js-utils/blob/f7397e8c00dea4fcd1c5ee192d702bda69bfa3d2/gulpfile.babel.js#L31-L47)
[@see source code (other module)](https://github.com/sudeti/js-utils/blob/f7397e8c00dea4fcd1c5ee192d702bda69bfa3d2/src/fs.js)
[@see my build script (current module)](https://github.com/rollup/rollup-plugin-commonjs/issues/21)
pps: maybe it's a bug in babel

**Comment by eventualbuddha** [comment]
@chpio what does your original code look like before it's transformed into the invalid code? Your link to the build script is a link to https://github.com/rollup/rollup-plugin-commonjs/issues/21.

**Comment by chpio** [comment]
the src-code: https://github.com/sudeti/js-utils/blob/4bac1a67e6e01a30f89c45f6c01018567bc35515/src/fs.js

**Comment by Rich-Harris** [comment]
0.21.3 released with the fix – no more workarounds necessary :)
