### ISSUE TITLE
[2.3.1+] no longer supports module.exports.default property

### ISSUE THREAD

**Issue by Shin-Ogata** [rollup/rollup#3554]
- Rollup Version: 2.3.1
- Operating System (or Browser): Windows 10
- Node Version (if applicable):  12.1.0

Thank you for your great job.
I found problem that no longer consider `module.exports.default` property when configuration file given.

I have the configuration file like as following.

- build.config.js
```js
module.exports = {
    // for rollup
    default: {
      // rollup configuration here
      :
    },
    // for bundle-dts
    dts: {
      :
    },
    minify: {
        // for terser
        js: {
          :
        },
    },
};

```

### Expected Behavior

`module.exports.default` should be supported as rollup configs. This worked in 2.3.0, but appears not to work in 2.3.1.

### Actual Behavior

```
$ rollup -c ./build.config.js
(!) You have passed an unrecognized option
Unknown input options: default. Allowed options: acorn, acornInjectPlugins, cache, context, experimentalCacheExpiry, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveEntrySignatures, preserveModules, preserveSymlinks, shimMissingExports, strictDeprecations, treeshake, watch

 → stdout...
[!] Error: You must supply options.input to rollup
Error: You must supply options.input to rollup
```

It seems the problem caused from this changes.
https://github.com/rollup/rollup/commit/943995d046465bd927bcef728c938f7b2e0c5f98#diff-4926a181406c10e58542e4c2229a7464L113

Probably it's fixed by estimating `configFileExport.default` before `configFileExport` like this.

```js
async function getConfigList(configFileExport, commandOptions) {
    const config = await (typeof configFileExport === 'function'
        ? configFileExport(commandOptions)
        : configFileExport.default || configFileExport);

```

**Comment by lukastaegert** [comment]
> module.exports.default should be supported as rollup configs

not sure where you got this from, you were relying on undocumented functionality here. Nevertheless, you should be able to make it work again if you do the interop pattern properly by adding an `__esModule: true` property.

I.e.

```js
module.exports = {
    __esModule: true,
    // for rollup
    default: {
      // rollup configuration here
      :
    },
    // for bundle-dts
    dts: {
      :
    },
    minify: {
        // for terser
        js: {
          :
        },
    },
};
```

The reason is that we switched to stricter interop here because honestly I did not think anyone would do that, or rather people would be writing an ES module if they wanted additional named exports.

**Comment by Shin-Ogata** [comment]
Thank you for quick response.
I confirmed that the way you proposed the `__esModule` property works correctly.

> The reason is that we switched to stricter interop here because honestly I did not think anyone would do that, or rather people would be writing an ES module if they wanted additional named exports.

Yes, I make sense this reason.
I showed one fix code, but I think you can close this issue with changing nothing.

Thanks again.
