### ISSUE TITLE
Getting error: "Cannot read property 'getDependenciesToBeIncluded' of undefined" after upgrading to v2.10.0

### ISSUE THREAD

**Issue by cato** [rollup/rollup#3557]
Not sure if this is a bug with Rollup or the Post CSS plugin. But it started when I upgraded from Rollup `v2.9.0` to `v2.10.0`, so I'll start here. 

Sorry in advance if it should be in the Post CSS Plugin Repo. 

- Rollup Version: 2.10.0
- Operating System (or Browser): macOS Catalina
- Node Version (if applicable): 12.6.3
- Link to reproduction (IMPORTANT, read below): https://repl.it/@cato1/PaltryImmediateCopycat

### Expected Behavior
After upgrading from `2.9.0` to `2.10.0`, Rollup + Post CSS Plugin should build as usual.

### Actual Behavior
After upgrading from `2.9.0` to `2.10.0`, Rollup + Post CSS Plugin throw this error during build:
` TypeError: Cannot read property 'getDependenciesToBeIncluded' of undefined`

**Comment by lukastaegert** [comment]
Thanks for reporting. It appears the bug was actually introduced in 2.9.1. Fix at #3558.

**Comment by lukastaegert** [comment]
BTW your minimal repro was crucial in finding a fix for that quickly 👍
