### ISSUE TITLE
Code splitting should also split virtual modules.

### ISSUE THREAD

**Issue by darionco** [rollup/rollup#3562]
### Expected Behavior / Situation
I am creating a project that uses worker modules and code splitting, in the example below I would expect that my built modules do not depend on each other so workers can be instantiated safely.

main.js
```
import 'some/cjs/module1'
import 'some/cjs/module2'

const worker = new Worker('main.worker.js', { type: 'module' });

// do stuff...
```

main.worker.js
```
import 'some/cjs/module1'

// do stuff...
```

rollup.config.js
```
const config = {
  input: ['main.js., 'main.worker.js'],
  output: {
    dir: 'dist/',
    format: 'esm',
    chunkFileNames: 'dependencies/[name].js'
  },
  plugins: [
    resolve(...),
    commonjs(...)
  ],
  manualChunks(id) {
    if (id.includes('node_modules/')) {
        const parsed = path.parse(id);
        const folders = parsed.dir.split('/');
        while (folders.shift() !== 'node_modules') {}
        if (folders.length > 1 && folders[0].startsWith('@')) {
            return `${folders[0]}/${folders[1]}`;
        }
        return folders[0];
    }
  }
}
```

### Actual Behavior / Situation
The resulting files in the `dependencies` folder end up sharing the virtual modules injected by `plugin-commonjs` (or any other plugin) and importing each other.

In the example above this can be problematic because if `some/cjs/module1` ends up importing `some/cjs/module2` as a dependency and `some/cjs/module2` accesses the DOM or other API available only on the main thread on import, my worker will crash and not work.

In my specific use case my worker is importing `protobufjs` which, after the build ends up importing `mapbox-gl` to use one virtual module that ends up being injected to it. `mapbox-gl` performs some DOM tests on import which end up crashing my worker because the API is not available in workers..

### Modification Proposal
I know that I could use the option `preserveModules` to fix this issue but that option outputs things in incredibly nested folder structures and for larger projects this quickly becomes unmanageable.

Couldn't the build process output the virtual module to its own file when it detects that two chunks are using it? It already detects when two chunks use the same virtual module but it ends up creating unintended dependencies by importing one of the chunk into the other one.

Putting this behaviour behind a flag should be fine, although I would argue that this should be the default behaviour when code splitting is enabled.

**Comment by lukastaegert** [comment]
If Rollup created dependencies, then there are dependencies, and it does not matter if the file is virtual or not. It sounds to me that something else is broken in your setup. Are you sure `preserveModules` really solves your issue? `manualChunks` can also very much mess things up.

**Comment by darionco** [comment]
Thanks for the reply, the final build indeed had faux dependencies but, as you correctly pointed out, the key is in `manualChunks`. So in reality it was me introducing faux dependencies and not rollup. Turns out that for `manualChunks` to split virtual modules from chunks you need to handle them manually, which makes sense in hindsight.

Removing `manualChunks` does solve the issue but I end up with a bunch of files named `index.js`, `index2.js`, etc. (This is due to the libraries naming and nothing to do with rollup). Those files make it really hard to explore the build though, which I have to do while debugging.

Either way, handling virtual modules in my `manualChunks`  fixed my issue, however I would like to propose adding the ability for `chunkFileNames`, `entryFileNames` and `assetFileNames` to take a function with `id`, `name`, `format` and `hash` as parameters. The ability to dynamically name chunks would solve edge cases like mine.

Either way, thanks for your help!
