### ISSUE TITLE
rollup build a package I don't need

### ISSUE THREAD

**Issue by baixiaoyu2997** [rollup/rollup#3563]
when i use rollup build with download-git-repo,packed file contains `electron`

i test on rollup-starter-lib.
```
// package.json
"dependencies": {
    "download-git-repo":"^3.0.2"
  },
  "devDependencies": {
    "@rollup/plugin-json": "^4.0.3",
    "@rollup/plugin-commonjs": "^11.1.0",
    "@rollup/plugin-node-resolve": "^7.1.3",
    "rollup": "^2.10.2"
  },
```
```
// rollup.config.js
{
    input: 'src/main.js',
    output: [
      { file: pkg.module, format: 'es' }
    ],
    plugins: [
      json(),
      resolve(),
      commonjs() 
    ]
  }
```
output file:
```diff
import fs from 'fs';
import path$1 from 'path';
import url from 'url';
import events from 'events';
import http from 'http';
import stream$2 from 'stream';
import os from 'os';
import 'net';
import tls from 'tls';
import https from 'https';
import assert from 'assert';
import util$7 from 'util';
import buffer$2 from 'buffer';
import constants from 'constants';
import string_decoder$1 from 'string_decoder';
import zlib from 'zlib';
import querystring from 'querystring';
import punycode from 'punycode';
+ import electron from 'electron';
import child_process from 'child_process';

---------------
if (opts.useElectronNet && process.versions.electron) {
	const electron$1 = electron;
	fn = electron$1.net || electron$1.remote.net;
}
```
I'm pretty sure I don't need `electron` in my code. so , what I missed

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.
