### ISSUE TITLE
Rollup treeshaking remove "augmentation-and-re-export" code. (Different behaviour with webpack)

### ISSUE THREAD

**Issue by csr632** [rollup/rollup#3565]
- Rollup Version: rollup@2.10.2
- Operating System (or Browser): chrome 80.0.3987.149
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): https://github.com/csr632/rollup-issue/tree/sideEffects
This repo config both rollup and webpack for comparison. 

```
// package.json of library
{
  "name": "test-package-default-export",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "sideEffects": false  // sideEffects flag!
}

// index.js of library
import Menu from "./menu";  // content of this file is not important
import Item from "./item";       // content of this file is not important
Menu.Item = Item;                 // augmentation and re-export!
console.log("side effect in test-package-default-export");
export default Menu;

// user code
import DefaultExport from "test-package-default-export";
console.log("test-package-default-export", DefaultExport.Item); // DefaultExport.Item is undefined
```

### Expected Behavior
`Menu.Item` should be defined. The "item" module should be bundled. **Webpack behaves like this.**

### Actual Behavior
User find out that `Menu.Item` is undefined. The "item" module is tree-shaked.

# Investigate
Interestingly, if the library use **named export**:
```
import Menu from "./menu";
import Item from "./item";
Menu.Item = Item;
console.log("side effect in test-package-named-export");
export { Menu };
```
both rollup and webpack will behave the same: the "item" module is tree-shaked and `Menu.Item` will be undefined. The reproduction repo have demo for this.

**So in summary**:
- if `node_modules/library/index.js` use **default export**
  - webpack **keep** the augmentation-and-re-export code
  - rollup **remove** the augmentation-and-re-export code
- if `node_modules/library/index.js` use **named export**
  - webpack **remove** the augmentation-and-re-export code
  - rollup **remove** the augmentation-and-re-export code

I think the behaviour of webpack is more reasonable. Because when we export a value as a name-export, we are exporting the **binding**; But when we export a value as a default-export, we are exporting the **value**, we should evaluate the whole module (`node_modules/library/index.js`) to get the correct value! So rollup should not remove `node_modules/library/index.js` when it has default export.

# Workaround
I can force rollup to treat "Menu" as a value instead of a binding:
```js
// index.js of library
import Menu from "./menu";
import Item from "./item";
Menu.Item = Item;
export default (null, Menu); // export an expression instead of a bare binding
```

**Comment by lukastaegert** [comment]
I agree with your reasoning. Note that I usually do no like having "Webpack does X" as an argument but since for side-effects, we are basically piggy-backing on the infrastructure that authors put into their packages to please Webpack, this time the comparison might be in order.

Fix at #3572, which will align with the behaviour of Webpack: Keep side-effects if there is a default export declaration involved, do not keep it for reexported bindings. This also means that `export {Menu as default}` will be the same as using a named export, which aligns with your argument.

**Comment by csr632** [comment]
@lukastaegert 
The issue still exist in a more complex case. I have updated [the reproduction](https://github.com/csr632/rollup-issue/tree/sideEffects).

**Comment by lukastaegert** [comment]
Oh man, hopefully #3602 will finally solve this for good.
