### ISSUE TITLE
BaseNode bind with TypeError by undefined. 

### ISSUE THREAD

**Issue by morlay** [rollup/rollup#3568]
- Rollup Version: 2.9.x 2.10.x
- Operating System (or Browser): macOS 10.15.4
- Node Version (if applicable): 14
- Link to reproduction (IMPORTANT, read below): 

just break some plugin with manual ast. like: https://github.com/Swatinem/rollup-plugin-dts/pull/95

it works in old version (2.8.x).

may something changed cause this `undefined` `exported` of  ExportAllDeclaration pass to `BaseNode.bind`.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.
