### ISSUE TITLE
Rollup scews up unit tests

### ISSUE THREAD

**Issue by Kflash** [rollup/rollup#357]
I had a previous issue thread here regarding rollup, and figured I should give it a last try.
I'm almost there, but now it screws up the unit tests....

I use Karma with webpack for my unit tests in the browser. I can't use ES2015 syntax, because it will throw. I tried to do this:

```
presets: ['es2015-rollup']
```

in the webpack section. Well. Then it scream about some babelHelpers that is not there. So then I tried to install `babel-plugin-external-helpers-2` and used that as a plugin. Didn't solve the problem either.

I'm using  `babel-loader@6.2.0` for webpack. Seems to be a enemy of Rollup.

Anyway I went back to scratch `.babelrc` and modified it to accept `es2015 preset`. 

After that my unit tests works, but now I couldn't build the distro build with rollup.

If I did, Rollup will start to throw errors and demand me to use the  `es2015-rollup preset`. 

So I tried to modify the rollup config file, to accept the rollup preset, but then it start to throw about babelHelpers and ask me to disable my previous setup.

I can further add that Rollup also screws up my Mocha tests for node. Same there.
Also the Mocha unit tests for browser seem to share the same destiny.

Any solution on this mess, other then push the delete button and walk away?

Repo is located here: https://github.com/Kflash/boily

If you try to run one unit tests and use import in the first line, it will throw this:

`Uncaught SyntaxError: Unexpected token import`

The unit tests also throws this:

```
ERROR in ./test/browser/boily.js
Module parse failed: xxx.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import boily from '../../src/index';
|
|   describe('should be a object', function () {
```
This happen because Im using  `babel-loader@6.2.0` and `ES2015 rollup preset`

**Comment by pkozlowski-opensource** [comment]
Out of curiosity: why would you use rollup during unit testsing? IMO it should be only used for production / deployement builds. So I would assume rollup output is used in e2e tests but not unit tests

**Comment by Kflash** [comment]
I'm not using rollup for unit tests. As I wrote Im using webpack for that. But the rollup preset screwed this up. However I just got Karma / Webpack unit tests workins. 
Still issues with Mocha server / node unit tests.

**Comment by Kflash** [comment]
The huge problem I'm facing are when I'm forced to use `ES2015-rollup preset`. For mocha tests on nodeJS. It seems to require the `ES2015 preset` and will not work if I use `ES2015-rollup preset`.

How to solve this? Two issues solved now regarding this with a workaround, but for Mocha on node, seems not to be solved.

**Comment by arv** [comment]
@pkozlowski-opensource One reason one might want to use rollup for unit testing instead of babel-plugin-transform-es2015-modules-commonjs is that commonjs does not work with cyclic dependencies.

@Kflash One way around your issue would have been to use different environments. One for your mocha/karma unit tests and one for your production version: https://babeljs.io/docs/usage/babelrc/#env-option

**Comment by Kflash** [comment]
@arv I found solution on almost everything. But then I figured out that I can't transpile with Babel in unit tests anymore. Example import of modules are not working. That is the only issue left, but I don't see any reason to waste more hours. I have a couple of other workflows I will use from now on.

But if you have any good ideas how to solve the last issue, it would be helpfull. The repo is on the link I posted earlier.

**Comment by Kflash** [comment]
You can close this. I got it working now after a lot of trouble. So I can't recommend this to anyone. Not easy at all!

**Comment by Rich-Harris** [comment]
Sorry for the pain, I know it well! Unfortunately it's not really possible to override configuration in Babel 6 like it was in Babel 5. For the record, if anyone else ends up here, I've solved similar problems by having a separate `.babelrc` file in my `src` file, so that my project looks like this:

```bash
my-project/
|- .babelrc # with es2015 preset
|- src/
  |- .babelrc # with es2015-rollup preset
  |- my-project.js
|- test/
  |- test.js
```

**Comment by Kflash** [comment]
@Rich-Harris I work together with a person you know very well in real life too, and we solved all isues so far. As you can see here: https://github.com/trueadm/inferno/tree/perf-spike

We have one issue left. Uglify doesn't seem to be so friendly when it comes to minified build. Any ideas to help out on that?

**Comment by raphaelokon** [comment]
@Rich-Harris Sorry to reactivate this thread … your proposed solution doesn't seem to work :-(
I found better workaround that allows me use a `.babelrc` in the root (for testing etc.) and a custom babel setting in my `rollup.config.js`

```js
my-project/
|- rollup.config.js # with es2015-rollup preset in babel plugin
|- .babelrc # with es2015 preset
|- src/
  |- my-project.js
|- test/
  |- test.js
```

```js
// rollup.config.js
…
plugins: [
  babel({
    babelrc: false,
    presets: ['es2015-rollup'],
    exclude: 'node_modules/**'
  })
]
…
```

@Kflash the above solution worked for me. And I quite like the separation of concerns (keeping the rollup-babl-plugin specific stuff in the rollup config).
