### ISSUE TITLE
Simple file hitting maximum call stack size error

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#3579]
- Rollup Version: 2.10.5
- Operating System (or Browser):
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): http://rollupjs.org/repl/?version=2.10.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHVuZGVmaW5lZCU1Q24lNUN0JTJDJTIwb3ducyUyMCUzRCUyMCU3QiU3RC5oYXNPd25Qcm9wZXJ0eSU1Q24lNUN0JTJDJTIwdG9TdHJpbmclMjAlM0QlMjAlN0IlN0QudG9TdHJpbmclNUNuJTVDdCUyQyUyMGlzRmluaXRlJTIwJTNEJTIwaXNGaW5pdGUlNUNuJTVDdCUyQyUyME5PTl9IT1NUX1RZUEVTJTIwJTNEJTIwJTdCJTIwJTVDbiU1Q3QnYm9vbGVhbiclM0ElMjAxJTVDbiU1Q3QlMkMlMjAnbnVtYmVyJyUzQSUyMDElMjAlNUNuJTVDdCUyQyUyMCdzdHJpbmcnJTNBJTIwMSU1Q24lNUN0JTJDJTIwJ3VuZGVmaW5lZCclM0ElMjAxJTIwJTVDbiU3RCUzQiU1Q24lNUNudmFyJTIwaXMlMjAlM0QlMjBleHBvcnRzLmlzJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25pcy5hcnJheWxpa2UlMjAlM0QlMjBmdW5jdGlvbiUyMCh2YWx1ZSklMjAlN0IlNUNuJTVDdHJldHVybiUyMHZhbHVlJTIwISUzRCUzRCUyMHVuZGVmaW5lZCUyMCU1Q24lNUN0JTI2JTI2JTIwb3ducy5jYWxsKHZhbHVlJTJDJTIwJ2xlbmd0aCcpJTIwJTVDbiU1Q3QlMjYlMjYlMjBpc0Zpbml0ZSh2YWx1ZS5sZW5ndGgpJTNCJTVDbiU3RCUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGlzJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior

Rollup should parse the source.

### Actual Behavior

Hits a maximum stack size!

It seems to be because of the `var undefined` mixed with the object and var declaration list. Not sure why exactly. Definitely an edge case of edge cases I admit :)

**Comment by lukastaegert** [comment]
Actually it is not related to `undefined`, it is the recursive declaration. Still, I thought those were covered, but alas: https://rollupjs.org/repl/?version=2.10.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMGlzRmluaXRlJTIwJTNEJTIwaXNGaW5pdGUlM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMCh2YWx1ZSklMjAlN0IlNUNuJTVDdHJldHVybiUyMGlzRmluaXRlKHZhbHVlLmxlbmd0aCklM0IlNUNuJTdEJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment]
Fix at #3581
