### ISSUE TITLE
Short circuiting condition incorrectly

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#3588]
- Rollup Version: 2.10.8
- Operating System (or Browser): all
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below):

https://rollupjs.org/repl/?version=2.10.8&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZ2V0T2JqZWN0KCklMjAlN0IlNUNuJTVDdGNvbnN0JTIwcmVzdWx0JTIwJTNEJTIwYW55dGhpbmcoKSUzQiU1Q24lMjAlMjBjb25zdCUyMGltYWdlJTIwJTNEJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJlc3VsdCUyQyU1Q24lMjAlMjAlN0QlM0IlNUNuJTIwJTIwcmV0dXJuJTIwaW1hZ2UlM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGhvbGEoKSUyMCU3QiU1Q24lNUN0Y29uc3QlMjBpbWFnZSUyMCUzRCUyMGdldE9iamVjdCgpJTNCJTVDbiUyMCUyMGlmJTIwKGltYWdlLnJlc3VsdHMlMjAhJTNEJTNEJTIwMCUyMCUyNiUyNiUyMGltYWdlLnJlc3VsdCUyMCElM0QlM0QlMjA2KSUyMCU3QiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKCdoZWxsbycpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbmhvbGEoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior
```js
  if (image.results !== 0 && image.result !== 6) {
```

should emit:

```js
  if (image.results !== 0 && image.result !== 6) {
```

### Actual Behavior
It drops the `image.results !== 0` condition: 

```js
  if ( image.result !== 6) {
```

**Comment by lukastaegert** [comment]
As far as I can see, the behaviour is correct as `image.results` with a plural s is `undefined`. If you change it to `image.result` it is retained.

**Comment by manucorporat** [comment]
I need to sleep more, sorry about it!
