### ISSUE TITLE
Importing es module in config from npm doesn't work

### ISSUE THREAD

**Issue by shirotech** [rollup/rollup#3589]
Not sure what's going on but consider the following:

In the `rollup.config.js`

```js
import keys from 'lodash-es/keys';
console.log('keys', keys); // just a test

export default {
  input: 'entry/test.js',
  output: {
    dir: 'dist',
    format: 'cjs',
  },
};
```

This error occurs:
```
import arrayLikeKeys from './_arrayLikeKeys.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

However, when I change it to be relative, suddenly it works.
```js
import keys from './node_modules/lodash-es/keys';
```

```
keys [Function: keys]

entry/test.js → dist...
created dist in 8ms
✨  Done in 0.67s.
```

Does anyone know why or a proper fix without making the import path relative?

**Comment by lukastaegert** [comment]
https://rollupjs.org/guide/en/#using-untranspiled-config-files

non-relative imports are considered external and by default transpiled to require statements, which do not work for ES modules. See above for how to avoid this.

**Comment by shirotech** [comment]
Still doesn't work, I've tried the following:

1. changed config to .mjs, now `import keys from 'lodash-es/keys';` is looking for `keys.mjs` which doesn't exist, forcing it to `import keys from 'lodash-es/keys.js';` gives the same import error.

**Comment by lukastaegert** [comment]
It is likely that lodash-es is just not configured correctly for native Node ES modules. If there are no mjs files, their package.json would need to contain a `type: module` entry.

**Comment by lukastaegert** [comment]
Also, extensionless imports may not work correctly if there are no exports defined in their package.json file

**Comment by lukastaegert** [comment]
By that I mean deep imports like `lodash-es/keys`

**Comment by shirotech** [comment]
I see, thanks @lukastaegert it seems ES modules still have a long way to go for wider adoption. Will continue to use `esm` package for now.

**Comment by lukastaegert** [comment]
Yes unfortunately. Node ESM has become stable only very recently, I would suspect for support to improve significantly over the next year.
