### ISSUE TITLE
Rollup replaced my main class name (SDK) with default name.

### ISSUE THREAD

**Issue by luenmuvel** [rollup/rollup#3593]
My input class is called SDK and it is precisely the file that exports that class, the one that I indicate in the **"input"** key of the **rollup.config.js** file. Before starting to do my unit tests, I had no problem, I have made modifications to internal code (_refactoring_) but nothing weird. This is how I worked it a few days ago:

index.html
```javascript
this.belpay = new belpay.SDK('test', {
            username: 'username',
            password: 'password',
            key: 'abc-def',
          });
```

Now I have to do it like this:

index.html
```javascript
this.belpay = new belpay.default('test', {
            username: 'username',
            password: 'password',
            key: 'abc-def',
          });
```

In the browser I have the following error:

![imagen](https://user-images.githubusercontent.com/34595961/82835834-ca9a3280-9e8a-11ea-9da1-7e7307c9b6f6.png)

Before, when I did the same, I had the following:

![imagen](https://user-images.githubusercontent.com/34595961/82838272-50b97780-9e91-11ea-82e8-077ff2f79b4b.png)

I don't understand why now it shows me **default**. I've always had this setting in **rollup.config.js**

```javascript
import nodePolyfills from 'rollup-plugin-node-polyfills';
import babel from 'rollup-plugin-babel';
import serve from 'rollup-plugin-serve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import json from 'rollup-plugin-json';

export default {
  input: 'src/index.js',
  context: 'window',
  output: [
    {
      file: 'dist/belpay.js',
      format: 'umd',
      name: 'belpay',
      exports: 'named',
      globals: ['axios'],
    },
    {
      file: 'dist/belpay.min.js',
      format: 'umd',
      name: 'belpay',
      plugins: [terser()],
      exports: 'named',
    },
  ],
  external: ['axios'],
  plugins: [
    babel({
      exclude: ['node_modules/**'],
      runtimeHelpers: true,
    }),
    nodePolyfills(),
    serve({
      host: 'localhost',
      port: 1234,
      contentBase: 'dist',
      historyApiFallback: true,
      allowCrossOrigin: true,
    }),
    commonjs({
      include: 'node_modules/axios/**',
    }),
    livereload({
      watch: 'dist',
      verbose: true,
    }),
    json(),
  ],
};
```

Any suggestion to improve this file will be welcome.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
