### ISSUE TITLE
Importing Rollup CLI via npm

### ISSUE THREAD

**Issue by benmccann** [rollup/rollup#3596]
I'm trying to use https://github.com/sveltejs/sapper. It tries to provide a `sapper` command that executes rollup. However, the integration is a bit brittle and I've encountered a few bugs in that project that I'd like to try to fix. I think it would reduce the brittleness if it used code from the `cli` project directly rather than trying to reinvent the wheel. Is the code for the Rollup CLI available on npm anywhere?

**Comment by lukastaegert** [comment]
Well, it is part of `rollup` on npm. On Github you find it here https://github.com/rollup/rollup/tree/master/cli

**Comment by benmccann** [comment]
I'm trying to find a way to import `handleError`, but don't see it there.

`grep -r handleError node_modules/rollup/dist/rollup.es.js` returns no results

**Comment by shellscape** [comment]
@benmccann thanks for opening an issue, but support isn't something we offer here, as mentioned on the issue template selection page and in every issue template. Lukas gave you a good starting point to investigate your initial question. If you find that you're unable to accomplish what you're after, please choose the appropriate template (feature or modification), fill out the entire template, and we'll work through the process with you.
