### ISSUE TITLE
support for __dirname

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#360]
This probably belongs in a plugin I guess?

but say I have this

// a.js
```
import 'folder/a.js';
```
//folder/b.js
```
fs.readFile(path.join(__dirname, 'external.png'));
```

when rolled-up I get

```
fs.readFile(path.join(__dirname, 'external.png'));
```

where-as it would be nice if I get

```
fs.readFile(path.join(__dirname + '/folder', 'external.png'));
```

alternatively I have to know `__dirname` is relative to the root when used with rollup or I have to ban use of `__dirname` from any code and any sub modules that are rolled up...

**Comment by Victorystick** [comment]
I guess this should is best taken care of by `rollup-plugin-commonjs`?

**Comment by lukeapage** [comment]
hrmm well, I'm not sure.. in my case I'm using `__dirname` in es6 code - but I have control over that, it is most nasty when it occurs in sub-modules.

I think its either a core concern or a new plugin, thats reccomended for node.js usage.

**Comment by Victorystick** [comment]
I see. A Node plugin, perhaps? We'll end up with _a lot_ of plugins for people who want to use Node code. Tricky.
```
rollup-plugin-commonjs
rollup-plugin-node
rollup-plugin-npm
...
```

**Comment by eventualbuddha** [comment]
Maybe the node plugin would just bundle various behaviors from other
plugins?

**Comment by Victorystick** [comment]
@eventualbuddha :+1:, and add `__dirname` `__filename`?

**Comment by eventualbuddha** [comment]
@Victorystick yeah, `__dirname` and `__filename` could either be implemented directly by the `node` plugin or could be another plugin pulled in by the same.

**Comment by TrySound** [comment]
Supported in https://github.com/calvinmetcalf/rollup-plugin-node-globals

**Comment by StreetStrider** [comment]
Hello, everyone. I'm experimenting how Rollup can be used for Node.js bundling, so I dig how `__dirname` works. `node-globals` transform `__dirname` into absolute path, which leads to bundle become not portable in any other location. Ideally, I'm expecting it to work it in the manner @lukeapage mentioned: `__dirname + '/relpath'`. That will allow bundle to stick to actual Node's `__dirname` for main (entry) file and still got properly working `__dirname`'s in dependent files.
Is there any efforts in that direction, something I can investigate? @TrySound, @Victorystick

**Comment by caub** [comment]
@TrySound Do you know if this would be possible without a plugin? because on my code editor I run javascript (just for quick debugging) with `rollup --silent -f cjs $fullFileName | node` I can't really set a plugin from the CLI (can I?), and it has the `__dirname` equals `.` issue

**Comment by sanriqing** [comment]
> 大家好。我正在试验Rollup如何用于Node.js捆绑，所以我挖掘了如何`__dirname`工作。`node-globals`转换`__dirname`为绝对路径，这导致捆绑在任何其他位置变得不可移植。理想情况下，我希望它以@lukeapage提到的方式工作：`__dirname + '/relpath'`。这将允许bundle坚持实际节点的`__dirname`主（入口）文件，并仍然`__dirname`在依赖文件中正常工作。
> 我是否可以在这方面做出任何努力？@TrySound，@ Victorstick

report

**Comment by shellscape** [comment]
@sanriqing apologies - can you please translate that to English?

**Comment by sanriqing** [comment]
> @sanriqing apologies - can you please translate that to English?
> 
> Ah I see that's just the previous comment in another language. Not sure what you were going for there bud.

i'm sorry, i use google translation。Forget to close.The reference is  what streetstrider say.rollup Convert the ‘__dirname’ to the  specific value .it made a mistake when someone use the builded file
