### ISSUE TITLE
Code stripped from original embedded code

### ISSUE THREAD

**Issue by devleaks** [rollup/rollup#3603]
- Rollup Version: 2.10.9
- Operating System (or Browser):
- Node Version (if applicable): 13.8.0
- Link to reproduction (IMPORTANT, read below): https://github.com/devleaks/lap

Test case [here](https://github.com/devleaks/lap).

I use a piece of code from leaflet (mapping library) and one of its plugin leaflet-ant-path.
A piece of code of one of leaflet-ant-path function is (unuglified from dist):
```JavaScript
{
    key: "_calculateAnimationSpeed",
    value: function()
    {
        var t = this.options,
            e = this._map,
            n = this._animatedPathId;
        if (!t.paused && e)
        {
            var r = e.getZoom(),
                o = document.getElementsByClassName(n),
                i = 1 + t.delay / 3 / r + "s",
                a = ["-webkit-", "-moz-", "-ms-", "-o-", ""]
                .map(function(t)
                {
                    return "".concat(t, "animation-duration: ").concat(i);
                })
                .join(";");
            Array.from(o, function(t)
            {
                (t.style.cssText = a), t.setAttribute("data-animated", "true");
            });
        }
    },
}
```

For unknown (buggy?) reason, this is the code in the generated rollup bundle that is passed to `createCommonjsModule` and later to `unwrapExports`.

It is missing a portion of the code.
```JavaScript
{
    key: "_calculateAnimationSpeed",
    value: function()
    {
        var t = this.options,
            e = this._map,
            n = this._animatedPathId;
        if (!t.paused && e)
        {
            var r = e.getZoom(),
                o = document.getElementsByClassName(n),
                i = 1 + t.delay / 3 / r + "s";
        }
    },
}
```

Why does this code get stripped? I can't tell if it is a plugin issue (commonjs) or a general rollup issue. Is this a tree shaking issue? Shaked too much? Please leave my baobab alone :-D.

### Expected Behavior

Generated code does not get stripped.
In test case, blue and purple line is animated. Start the working.html file.

### Actual Behavior

In test case, blue and purple line is not animated because of stripped code.

**Comment by lukastaegert** [comment]
I just learned that `Array.from` can have a side-effectful second argument. Should be easy to fix.

**Comment by devleaks** [comment]
Thanks for the prompt correction.
