### ISSUE TITLE
Support numeric separators

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#3605]
### Feature Use Case

Numeric separators are already supported in node and recently babel added it under flag to env preset. Though I got a syntax error in rollup when tried to make a bundle with `{ node: 'current' }` target.

### Feature Proposal

Add existing plugin to not get syntax error
https://github.com/acornjs/acorn-numeric-separator

**Comment by lukastaegert** [comment]
Fixed in https://github.com/rollup/rollup/releases/tag/v2.16.0
