### ISSUE TITLE
Watch specific plugin logic outside `cli` context

### ISSUE THREAD

**Issue by dionysiusmarquis** [rollup/rollup#3608]
### Feature Use Case

Be able to add watch specific logic in plugins triggered by `rollup.watch`.

### Feature Proposal

`@rollup/plugin-typescript` uses `process.env.ROLLUP_WATCH` for example. When running `Rollup` watch outside of `cli` context the watch logic of such implementations will be skipped.
I don't know if this is intentional, it would be a handy feature for plugins anyway.

**Comment by lukastaegert** [comment]
I created #3616 to address this, please have a look if this would work for you

**Comment by dionysiusmarquis** [comment]
@lukastaegert 👌Yes, that works
