### ISSUE TITLE
invalid number if number begins with 0

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#361]
Hi,

I get the following error rolling up mkdirp using the npm and commonjs plugins.

I am also using babel, but if I disable the plugin I still get an error (just no codeFrame or _babel property on the error)

```
{ [SyntaxError: app/node_modules/mkdirp/index.js: Invalid number (19:15)]
  pos: 426,
  loc: Position { line: 19, column: 15 },
  _babel: true,
  codeFrame: '  17 |     \n  18 |     if (mode === undefined) {\n> 19 |         mode = 0777 & (~process.umask());\n     |                ^\n  20 |     }\n  21 |     if (!made) made = null;\n  22 |     ' }
  17 |
  18 |     if (mode === undefined) {
> 19 |         mode = 0777 & (~process.umask());
     |                ^
  20 |     }
  21 |     if (!made) made = null;
  22 |
```

**Comment by Victorystick** [comment]
This is, I believe, due to all sources being processed by Rollup being in _strict mode_, and digits starting with `0` are invalid in strict mode.

**Comment by lukeapage** [comment]
you are right, it seems sensible enough. I'll move the bug to mkdirp

**Comment by aurbano** [comment]
Is there a way to override this?

Multiple dependencies of a package I'm using have this problem and it would speed things up if at least that could be overridden.

**Comment by lukastaegert** [comment]
`--no-strict` on the command line or `strict: false` in your rollup config may help you (as long as you do not emit ES6 modules which have strict mode enabled by default).

**Comment by guybedford** [comment]
@aurbano are you using the CommonJS plugin here or are these ES modules? Note that ideally the CommonJS plugin itself should handle rewriting this.
