### ISSUE TITLE
SystemJS renderer setter uses shadowed variable name `module`

### ISSUE THREAD

**Issue by joeljeske** [rollup/rollup#3613]
- Rollup Version: 2.12.1
- Operating System (or Browser):
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below):

https://rollupjs.org/repl/?version=2.12.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG1vZHVsZSUyQyUyMG90aGVyJTIwJTdEJTIwZnJvbSUyMCd0ZXN0JyUzQiU1Q24lNUNuY29uc29sZS5sb2cobW9kdWxlJTJDJTIwb3RoZXIpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnN5c3RlbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior

The name "module" can be used as a named export/import without collision

### Actual Behavior

The name "module" collides with the SystemJS setters block causing type errors.

**Comment by guybedford** [comment]
Thanks so much for catching this @joeljeske, I've created a PR to fix this at https://github.com/rollup/rollup/pull/3614.

**Comment by joeljeske** [comment]
Of course. Thanks for the quick turnaround
