### ISSUE TITLE
give sourcemapPathTransform the path of the sourcemap it's generating

### ISSUE THREAD

**Issue by dgoldstein0** [rollup/rollup#3615]
This is sort of a feature request and a bug report at the same time...

### Feature Use Case

I am working on a rollup-based tool that integrates with bazel.  We're using sourcemapPathTransform to change the paths in the output sourcemaps from nonsensical (relative to a location that only exists at build time) to something that actually looks meaningful.  Unfortunately, the paths passed in are relative to the location of the sourcemap file rollup is generating, which we Don't Know.  So far this has been fine, because all of our outputs were going into the same folder (specified on the command line with `--dir`) - but I just hit a case where we are trying to use a nested folder for the output, and now the value of `--dir` is not the folder containing the sourcemap, but the parent folder; but in `sourcemapPathTransform` we have no way of knowing that, so we are generating the wrong result.

It might also be relevant that I'm using `preserveSymlinks: true` in my config, and obviously `sourcemap: true`.

### Feature Proposal
right now `sourcemapPathTransform` takes a single argument, a value for the `sources` of a sourcemap, and lets you transform it.  I propose that we need a second argument - the path to the sourcemap.  By having this, my code could `path.dirname(sourcemapPath)` and use that instead of the value of `--dir`.

An alternative idea would be to make the singular existing argument to `sourcemapPathTransform` an absolute path instead of a relative path; however this far more likely to break existing usage.

**Comment by lukastaegert** [comment]
Resolved in v2.15.0
