### ISSUE TITLE
optimization - merging const objects

### ISSUE THREAD

**Issue by danielgindi** [rollup/rollup#3625]
### Feature Use Case

# base.js
```js
export default {
  a: 1,
  b: 2,
};
```

# user.js
```js
import base from './base';

export default {
  ...base,
  c: 3,
  d: 4,
};
```

# -->
```js
export default {
  a: 1,
  b: 2,
  c: 3,
  d: 4,
};
```

### Feature Proposal

When an object is never modified, if we can merge it into other objects that mix them in - that would be great.  
This also applies to `Object.assign` but may be more complicated.  
I'm not sure yet if it's theoretically possible to know if the base object is not modified somewhere else in the code.

**Comment by kzc** [comment]
```
$ rollup user.js --silent -p terser
var a={a:1,b:2,c:3,d:4};export default a;
```

**Comment by danielgindi** [comment]
@kzc Yeah that actually does it. I looked at a situation where there were two separate files depending on `base.js`, and terser chose the shorter version which is keep them separate. So I didn't notice it did that already.

I have a huge object to merge where I'd like to keep best performance when first loading the js file - but that may not be a requirement for most users.

Thanks.
