### ISSUE TITLE
rollup api does not output error info

### ISSUE THREAD

**Issue by mingzepeng** [rollup/rollup#363]
well, when I use cli command to bundle a js with syntax ,it would output error.but if I wrote rollup api in a js file,eg build.js and in command `node ./build.js`,it does not output any error info

**Comment by eventualbuddha** [comment]
That may be due to not handling the rejected promise returned by rollup (via `.catch`). Can you show some more of your code?

**Comment by mingzepeng** [comment]
@eventualbuddha  according to your advice,I add catch, but it still does not output any error info
```javascript
rollup.rollup({
  entry: './src/index.js'
}).then( function ( bundle ) {
  bundle.write({
    banner : banner,
    format: 'umd',
    moduleName : 'beyondLib',
    dest: './dist/beyondLib.js'
  });
}).catch(function (e) {
  throw e;
})
```
node version  : v4.2.3
system : windows 10

**Comment by eventualbuddha** [comment]
Feel free to drop by the [chat room](https://gitter.im/rollup/rollup) to ask questions!
