### ISSUE TITLE
Using commonjs exports with rollup/plugin-typescript

### ISSUE THREAD

**Issue by 43081j** [rollup/rollup#3635]
If you could document how to deal with a mixed commonjs/esm situation, that would be so nice.

Basically, I have a project which is as follows:

* Written in typescript (ES modules)
* Transpiled to common JS (because of the following points)
* Has a single dependency which is [unfortunately] a common JS module
* This single dependency has commonjs-style default export (`module.exports = function() { ... }`)

Given this example source:

```ts
export async function test() {
  const dep = await import('cjs-dependency');
  ...
};
```

Keep in mind, `cjs-dependency` has an awful default export:

```ts
module.exports = function() { ... }
```

At this point, typescript is happy (with `module: commonjs`) as the typescript types of that module specify `export = someFunction;`.

Where I'm stuck and where doesn't seem documented is how to bundle this for a browser while maintaining the interface...

Note that the obvious mess here is that the dependency _should_ be using a named or default export. Dynamic imports in browsers should resolve to a module, not a function (in an ideal would it would be `const {default: dep} = await import(...)`).

#### Using the typescript plugin

If I use your typescript plugin, combined with the commonjs plugin, this single dependency is output like so:

```ts
export default index;
export { dist as __moduleExports };
```

However, now this means the interface has changed, so the consumer looks like this:

```ts
const dep = await import('./index-89d9a024.js');
dep(); // ERROR, you can't call a module...
```

Which won't be right anymore, as the function which used to exist there in commonjs-world now exists at `default` (i.e. `const {default: dep} = ...`).

#### Consuming transpiled code directly

I've also tried (my preference) building my sources normally via `tsc`, and having rollup consume the built javascript as-is with the commonjs/resolve plugins.

This results in consumption looking like so:

```ts
    const dep = await Promise.resolve().then(() => dist);
```

Which is a pain, since here rollup has inlined the dependency and not cared about making a chunk at all.

But at least the interface is correct/maintained!

However, it also replaced my own exports with a default:

```ts
export default index;
```

so now my own interface is wrong...

---

Is there any solution to this? and is any of this documented anywhere? i've struggled for days now to find any place you've documented this mixture of commonjs and esm. It seems either way is a loss, the interface of either my own module or the dependency is mangled by rollup.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by aleclarson** [comment]
Please provide a git repository with a minimal reproduction. 👍
