### ISSUE TITLE
Tree shaking missing variable definition?

### ISSUE THREAD

**Issue by jamiewinder** [rollup/rollup#364]
It looks like the tree-shaking is not supporting this scenario:

```javascript
const defaultGreeting = 'Hello';
const defaultName = 'World';

export function greet(opts) {
  const {
    greeting = defaultGreeting,
    name = defaultName
  } = opts;
  console.log(greeting + ' ' + name);
}
```

Rollup produces:
```javascript
function greet(opts) {
  const {
    greeting = defaultGreeting,
    name = defaultName
  } = opts;
  console.log(greeting + ' ' + name);
}
```
Note that `defaultGreeting` and `defaultName` are referenced in the code, but not defined anywhere.

Is there a way to disable tree shaking for now?

**Comment by eventualbuddha** [comment]
I'm looking into this.

**Comment by Rich-Harris** [comment]
thanks :+1: [0.21.3 released with the fix](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22const%20defaultGreeting%20%3D%20'Hello'%3B%5Cnconst%20defaultName%20%3D%20'World'%3B%5Cn%5Cnexport%20function%20greet(opts)%20%7B%5Cn%20%20const%20%7B%5Cn%20%20%20%20greeting%20%3D%20defaultGreeting%2C%5Cn%20%20%20%20name%20%3D%20defaultName%5Cn%20%20%7D%20%3D%20opts%3B%5Cn%20%20console.log(greeting%20%2B%20'%20'%20%2B%20name)%3B%5Cn%7D%22%7D%5D%7D)
