### ISSUE TITLE
Rollup does not error when full plugin name is passed onto the command line

### ISSUE THREAD

**Issue by TimvdLippe** [rollup/rollup#3646]
- Rollup Version: 2.18.0
- Operating System (or Browser): n/a
- Node Version (if applicable): n/a
- Link to reproduction (IMPORTANT, read below): https://repl.it/repls/DistortedBasicJavadocs#.replit

### Expected Behavior

Specifying a plugin name that does not have any effect should return an exit code 1. E.g. The following command should fail:

```bash
npx rollup -c --plugin rollup-plugin-terser
```

For the code snippet:

```js
console.log('main entry');

const this_should_be_minified = 42;

function addAFunction() {
  return this_should_be_minified;
}

console.log(addAFunction());
```

### Actual Behavior

The commandline silently accepts the name, but does not do anything. E.g. it rolls up, but does not minify and keeps the original source file intact.

The correct version should have been

```bash
npx rollup -c --plugin terser
```

If you run this command, then it correctly minifies and exits cleanly:

```js
console.log("main entry");console.log(42);
```

**Comment by lukastaegert** [comment]
Thanks for bringing this up, I created #3647 to address this, please check
