### ISSUE TITLE
Bundle in order?

### ISSUE THREAD

**Issue by devmanbr** [rollup/rollup#3649]
I've been trying to get acquainted with Rollup for a few days, and one thing has left me confused. 

- Rollup Version: 2.18.1
- Operating System (or Browser): Windows 10
- Node Version (if applicable): .
- Link to reproduction (IMPORTANT, read below): .

### Expected Behavior
Rollup, either by default or by specific configuration, should insert the imported scripts at the point where they were inserted.

### Actual Behavior
Rollup always groups the contents of an imported script at the beginning of the file. This is a problem for very long synchronous scripts.

Does Rollup not support this, or am I not sure how to configure it correctly?

I'm using it via CLI, with the settings file (rollup.config.js). It works well, except in the situation I mentioned above.

I've search the internet for days for answers, and I haven't found anything about it. Can you help with that?

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.
