### ISSUE TITLE
Rollup tree shake removes all fn arguments when using object spread operator

### ISSUE THREAD

**Issue by Filipoliko** [rollup/rollup#3652]
- Rollup Version: 2.18.1
- Operating System (or Browser): MacOS 10.14.6
- Node Version (if applicable): 14.4.0
- Link to reproduction (IMPORTANT, read below): https://github.com/Filipoliko/rollup-test

### Expected Behavior

When a function is defined with multiple arguments and the first one is not being used, then once the function is called with arguments passed via object spread operator (`fn(...[arg1, arg2])`), rollup build (with `treeshake: true`) should preserve all the arguments.

### Actual Behavior

If a function `fn(arg1, arg2) {...}` is using only `arg2` and not `arg1`, then when it is called using the spread operator `fn(...[arg1, arg2])`, the rollup build removes all the arguments. It works fine, if you call it without the spread operator `fn(arg1, arg2)` or disable rollups `treeshake` configuration.

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #3654
