### ISSUE TITLE
[Mac OS] "Error: EMFILE: too many open files" for large projects

### ISSUE THREAD

**Issue by wessberg** [rollup/rollup#3662]
- Rollup Version: 2.19.0
- Operating System (or Browser): Mac OS 10.15.5
- Node Version (if applicable): 14.4.0

Hey there. My team is relying heavily on Rollup as the foundation of our build pipeline for a very large codebase with a very large amount of dependencies. We usually end up with around ~400 chunks for our primary web application.

Recently we migrated from Rollup 1.32.1 to 2.19.0 and since then we constantly run into `EMFILE: too many open files` errors on Mac OS when we run Rollup in watch mode during the second or third rebuild after changing one or more files.

I would hope that I could provide more details than this, but I'm not sure if there have been significant changes to the watch pipeline with Chokidar, but it would seem that a lot more files is attempted to be opened/read from simultaneously now, at least in this particular codebase.

### Expected Behavior

Ideally, watch mode should continue working, even for projects with thousands of open files. Using something like [`graceful-fs`](https://github.com/isaacs/node-graceful-fs) as a drop-in replacement for `fs` could fix this issue since it, according to the README, _"queues up `open` and `readdir` calls, and retries them once something closes if there is an EMFILE error from too many file descriptors."_.

### Actual Behavior

Watch-builds fail on Mac OS with an `Error: EMFILE: too many open files` error after one or few rebuilds in projects with a very large amount of watched files. In this particular codebase, this only became a problem after migrating to Rollup 2.19.0 from 1.32.1.

**Comment by lukastaegert** [comment]
I do not think we changed anything substantially except always relying on chokidar, so maybe chokidar is less forgiving here than fs. watch. Did you trying playing around with the chokidar options? Otherwise it appears you can drop in graceful-fs from the outside https://github.com/isaacs/node-graceful-fs#global-patching so you actually might try that and tell us if that helps. I am a little wary of pulling in another dependency at that point, though. This seems like fixing the symptoms but not the problem. But it would need someone to dig in deeper to tell us what the problem actually is. Or chokidar.

**Comment by wessberg** [comment]
Thanks for the follow-up! We tested with patching `fs` globally with `graceful-fs` for a few days, and while it did remove the EMFILE errors, it still eventually resulted in fatal errors like `Error: Could not resolve entry module (...)`, so no luck unfortunately.

As for Chokidar, we didn't previously play around with the Chokidar options. As far as I remember, Chokidar was opt-in before, right? I will try some options out and see how they might impact this problem and report back to you.

**Comment by wessberg** [comment]
Alright, we have successfully completely resolved the issue by disabling FS events by passing `useFsEvents: false` to the Chokidar options. For some reason, using FS Events with Chokidar on Mac OS leads to `EMFILE` errors in our particular codebase. I don't know if you can use this for anything, but at least know you might be able to recommend disabling FS events if this issue pops up again in the future.

**Comment by lukastaegert** [comment]
Nice work digging through this! Sounds like this might be a candidate for the troubleshooting section of the website https://rollupjs.org/guide/en/#troubleshooting what do you think? PR definitely welcome, I think just a few words should be enough.

**Comment by wessberg** [comment]
Sure, no problem! PR here: https://github.com/rollup/rollup/pull/3667
