### ISSUE TITLE
Extend UMD loader to use globalThis

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#3666]
### Actual Behavior / Situation
```js
(function (global, factory) {
   typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
   typeof define === 'function' && define.amd ? define(factory) :
   (global = global || self, global.myBundle = factory());
}(this, (function () { 'use strict';
 /* code */
})));
```

### Modification Proposal
(function (global, factory) {
   typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
   typeof define === 'function' && define.amd ? define(factory) :
/**   
(global = global || self, global.myBundle = factory()); 
needs refactor
**/
}(this, (function () { 'use strict';
 /* code */
})));

**Comment by lukastaegert** [comment]
What are environments that support neither `this` nor `self` but do not throw when either is accessed? `globalThis` seems like it  makes sense here but it is only supported in rather new environments. The question is also how big do we really want to make the already rather bulky wrapper?

So what is your use case, i.e. the environment that requires that and does not work with the existing wrapper?

**Comment by frank-dspeed** [comment]
@lukastaegert I agree the environments are GraalJS, Deno while deno will probally fix that via bundling inside parcel but for beeing technical correct i think this is the right step todo as all new environments will use globalThis and it works in browsers and node so i think this is the way to go as it is the standard for exact that problem

**Comment by lukastaegert** [comment]
I believe #3691 would fix this sufficiently?

**Comment by frank-dspeed** [comment]
@lukastaegert it looks like for me at last i did only execute the code in my head but i think it does at last the most importent thing. All Tests that i did execute in my head did pass so LGTM+1 for #3691
