### ISSUE TITLE
Create and build lib.js

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#3672]
### Expected Behavior / Situation
we create src/lib.ts it will export everything that gets imported by src/ and also the only exampt is watch this way we can create the /dist/rollup/shared/rollup.js in a way that it exports everything used and this can then be used to Compose custom builds
even with more then one graph it will simply give the user the option to use /dist/es/rollup.js or the lib version /dist/es/shared/rollup.js that will then expose everything like utils and Graph and Bundle Chunk Module Loader PluginDriver your know.

I only want your go ahad. :) or your no so i can go ahead and hard fork.

### Actual Behavior / Situation
dist rollup is importing src/rollup/rollup.ts

### Modification Proposal
Everything should import from a single entrypoint to archive a extra build flavor without overhead that i call lib-rollup

**Comment by lukastaegert** [comment]
`Graph`, `Chunk` etc are deliberately not exposed to be able to perform far reaching refactorings at any time without the need for major versions. Exposing those will either massively slow done development or lead to crappy code quality over time. Also at the moment, Rollup's public API is completely documented, which will and can no longer be after that. Also I fear it will create a new meta ecosystems of tools that rely on that that we will constantly break with each version. In short: If you want this, please create your own fork and take care of maintaining it, and also make sure it is clear it is not officially supported.
