### ISSUE TITLE
Does tree-shaking only perform one pass?

### ISSUE THREAD

**Issue by shrinktofit** [rollup/rollup#3674]
- Rollup Version: 2.21.0
- Operating System (or Browser): Windows 10
- Node Version (if applicable): 14.4.0
- Link to reproduction (IMPORTANT, read below):

https://rollupjs.org/repl/?version=1.27.12&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25jb25zdCUyMGVtcHR5Rm4lMjAlM0QlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTdEJTNCJTVDbiU1Q25mdW5jdGlvbiUyMGlnbm9yaW5nQXJncyUyMCgpJTIwJTdCJTIwcmV0dXJuJTIwZW1wdHlGbiUzQiUyMCU3RCU1Q24lNUNuZnVuY3Rpb24lMjB0YWtpbmdBcmdzKG5hbWUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGdsb2JhbFRoaXMuc2lkZUVmZmVjdCUyMCUzRCUyMCU1Qm5hbWUlNUQlM0IlMjAlMkYlMkYlMjBTaW11bGF0ZSUyMHNpZGUlMjBlZmZlY3QlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwZW1wdHlGbiUzQiU1Q24lN0QlNUNuJTVDbmNvbnN0JTIwbWVudSUyMCUzRCUyMGZhbHNlJTIwJTNGJTIwdGFraW5nQXJncyUyMCUzQSUyMGlnbm9yaW5nQXJncyUzQiU1Q24lNUNuYXBwbHlEZWNvcmF0b3IoY2xhc3MlMjAlN0IlN0QlMkMlMjBtZW51KCdBJTIwbWVudScpKSUzQiU1Q24lNUNuJTJGKiolNUNuJTIwKiUyMFNpbXVsYXRlJTIwZGVjb3JhdG9yJTIwY2FsbC4lNUNuJTIwKiUyRiU1Q25mdW5jdGlvbiUyMGFwcGx5RGVjb3JhdG9yKGNvbnN0cnVjdG9yJTJDJTIwZGVjb3JhdG9yKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBnbG9iYWxUaGlzLnNpZGVFZmZlY3QlMjAlM0QlMjAlNUJjb25zdHJ1Y3RvciUyQyUyMGRlY29yYXRvciU1RCUzQiUyMCUyRiUyRiUyMFNpbXVsYXRlJTIwc2lkZSUyMGVmZmVjdCU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behavior

Arguments passed to `menu` are omitted.

### Actual Behavior

The argument `'A menu'` is not omitted. But if I change the line
```js
const menu = false ? takingArgs : ignoringArgs;
```
into
```js
const menu = ignoringArgs;
```
The argument is omitted.

**Comment by lukastaegert** [comment]
Good catch. The problem is not so much of the number of passes because tree-shaking works a little differently here. It is rather that argument elimination is not tracked for return values of conditional expressions. This is easy to fix, see #3680
