### ISSUE TITLE
#output-exports does not exist

### ISSUE THREAD

**Issue by oliversalzburg** [rollup/rollup#3675]
Documentation Is:

- [X] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
Certain configuration combinations cause the following message to printed to the console:
```
(!) Mixing named and default exports
https://rollupjs.org/guide/en/#output-exports
```

The URL points to an anchor that does not exist.

### Your Proposal for Changes
Add the anchor to the documentation or change the console output.

**Comment by lukastaegert** [comment]
Thanks for spotting, this is fixed in Rollup 2.22.0
