### ISSUE TITLE
Add: Documentation for including SystemJS loader directly

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#3676]
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
As Pointed out in issue: #3624 it is sometimes wanted while not recommended to include the loader as it is shared when there is more then one entrypoint and if it is a single file bundle the systemjs formart makes no sense. 

### Your Proposal for Changes
Anyway i would want to add a example to the docs in the Code Splitting Build section at the end

#### Example multiple Entrypoints Not Working at present!
```js
//Transform SystemJS.min file to assign SystemJS only if it is not already loaded needed to be loaded more then once in multiple entrypoints
const transformMinifiedSystemJSVersion = (minSystemJS)=>{
    let [start,end] = minSystemJS.split('.System=new ');
    const globalVarName = start.charAt(start.length - 1); // 'm'
    return `${start}.System=${globalVarName}.System || new ${end}`
}

// using http-server inside the https://github.com/stealify/example-rollup-inline-systemjs clone project call test.html
const baseUrl = 'http://localhost:8080'

//if you use output name you need to include the systemjs loader with extra register named module
import fs from 'fs'
export default {
    input: './src/main.js',
    output: {
        dir: './dist',
        banner: transformMinifiedSystemJSVersion(fs.readFileSync('./node_modules/systemjs/dist/s.min.js')),
        footer: (fileName)=>`System.import(baseUrl+'/'+fileName)`,
        format: 'systemjs',
    }
}
```

We Need footer and banner to recive fileName
As you can see in this example we will need the resulting fileName to produce the import url

See: https://github.com/rollup/rollup/issues/3678

#### Example Single file bundle Working!
Single file bundle that uses SystemJS dynamic import with external dependencies for example or if it gets inlined into a script tag inside HTML

```js
//if you use output name you need to include the systemjs loader with extra register named module
import fs from 'fs'
export default {
    input: './src/main.js',
    output: {
        dir: './dist',
        banner: fs.readFileSync('./node_modules/systemjs/dist/s.min.js'),
        footer: `System.getRegister()[1]({},System).execute()`,
        format: 'systemjs',
    }
}
```

A repo that illustrates the current working state as example

https://github.com/stealify/example-rollup-inline-systemjs

**Comment by frank-dspeed** [comment]
## Additional info
at present there is a open issue so we can remove the transform maybe in future.

https://github.com/systemjs/systemjs/pull/2209

**Comment by shellscape** [comment]
This is an excellent use case for a directory of "recipes"

**Comment by lukastaegert** [comment]
Definitely. Also note that I would consider this solution to be a rather brittle hack as it will likely break with any new SystemJS release. Thus if we put this onto the main website, it would put the burden of keeping up with SystemJS releases on us, which I do not like. I would prefer if the SystemJS maintainers (@guybedford likely) would add an official way to support this that does not rely on patching their loader.

And at least for me, your solution does not work, try this example:

```js
// main.js
export const value = 'value';
console.log('main ' + value);
import('./lib.js');

// lib.js
import { value } from './main.js';
console.log('lib ' + value);
```

For me, it immediately throws with "exports is not a function". And even if it worked, I would expect this to cause issues like executing the loader and main twice when handling the dynamic import because it does not know which file the originally registered code belonged to.

No, I definitely want an official solution for that before we recommend it to anyone.

**Comment by frank-dspeed** [comment]
@lukastaegert https://github.com/stealify/example-rollup-inline-systemjs
A complet repo with your example and now all is working you where right i tested in a browser HTML file first because it took me so long to evalute all the edge cases with named registers that worked befor in older systemjs versions and many more 

but that example that is now linked works reproduce able :)

**Comment by frank-dspeed** [comment]
@shellscape I am also for a recipes section that will help many people a lot as they use always old tutorials maybe we could make a recips and Tutorial Section   we could reuse recipes in tutorials and combine them

**Comment by isidrok** [comment]
This can also be solved using a not so complex plugin by creating a loader file that includes SystemJS and imports bundle entries:

```js
import fs from 'fs';

function system(options) {
    return {
        name: 'system',
        async generateBundle(options, bundle) {
            const entries = Object.values(bundle)
                .filter(chunk => chunk.isEntry)
                .map(chunk => `System.import('./${chunk.fileName}')`);
            const filesToInclude = await Promise.all(
                 options.include.map((file) => fs.promises.readFile(file, 'utf8'))
            );
            const code = `
                (function(){
                    ${filesToInclude.join('\n')}
                    ${entries.join('\n')}
                }());
                `;

            this.emitFile({
                type: 'asset',
                fileName: options.fileName,
                source: code
            })
        }
    }
}


system({
  include: [
    require.resolve('systemjs/dist/s')
  ],
  fileName: 'loader.js'
})
```

Could also be modified to work with other runtimes such as RequireJS

**Comment by frank-dspeed** [comment]
@isidrok the only problem this leads to is that we do not get the result of a dingle file that contains a systemjs bundle and the loader.

**Comment by isidrok** [comment]
@frank-dspeed  that can be accomplished using a different approach with some caveats:

```js
function system(config) {
    return {
        name: 'system',
        async generateBundle(options, bundle) {
            const entryCode = Object.values(bundle)
                .find(chunk => chunk.isEntry)
                .code;
            const filesToInclude = await Promise.all(
                config.include.map((file) => fs.promises.readFile(file, 'utf8'))
            );
            const code = `
                (function(){
                    if(!window.__system_ready__){
                        ${filesToInclude.join('\n')}
                    }
                    if(window.__system_ready__){
                        ${entryCode}
                    }
                    if(!window.__system_ready__){
                        window.__system_ready__ = true;
                        System.import('./${config.fileName}')
                    }

                }());
                `;
            this.emitFile({
                type: 'asset',
                fileName: config.fileName,
                source: code
            })
        }
    }
}
```

In the snippet, `window.__system_ready__` is used in order to not evaluate SystemJS nor import the module more than once.

It would need proper support for source maps and if any other chunk relies on the entry it will fail because the entry module is registered in a different file.

**Comment by frank-dspeed** [comment]
@isidrok good point with the current script stuff but that only works when the browser supports currentScript and thats not always the case :(

**Comment by frank-dspeed** [comment]
@isidrok look there at the readme there are rules and edge cases explained

**Comment by frank-dspeed** [comment]
@isidrok in general there are 2 cases one case is inline into HTML in that case we got it working as in that case we do not need the exports of the inlined entrypoints.

//Usage:
//<script>${code}</script>
//<script src="https://localhost:8080/single-file-bundle/dist/main.js"></script>

// code-splitting only sideEffects no use of exports
//<script src="https://localhost:8080/single-file-bundle/dist/main.js">System.import('otherEntrypoint')</script>
//NOT WORKING <script src="https://localhost:8080/single-file-bundle/dist/main.js">/*use of any code exported by app */app()</script>
/*
NOT WORKING Circular dependency on entrypoint
<script src="https://localhost:8080/single-file-bundle/dist/main.js">
    SystemJS.import('otherEntrypoint').then(exports=>)
</script>
*/
```

**Comment by isidrok** [comment]
@frank-dspeed I don't see any problem with circular dependencies and code-splitting, it's working fine using my last snippet. Regarding `document.currentScript`, there are some clever polyfills out there using stack traces to detect which script originated the error:

```js
try { throw new Error() }
catch (err) {
   getScriptUrl(err.stack)
}
```

Take a look at https://github.com/amiller-gh/currentScript-polyfill

**Comment by frank-dspeed** [comment]
@isidrok maybe you should then start creating plugin-systemjs :)

**Comment by frank-dspeed** [comment]
I found out that discussion in issues is not a great thing to do. I will assign my self to the project of inventing a method to transfer knowleg and much information without writing a book :)

**Comment by isidrok** [comment]
> @isidrok maybe you should then start creating plugin-systemjs :)

Here we go: [rollup-plugin-systemjs-loader](https://github.com/isidrok/rollup-plugin-systemjs-loader). Comes with support for sourcemaps and circular dependencies from entry files.

Will publish it to npm in august after polishing it, don't have much free time right now.

**Comment by frank-dspeed** [comment]
I Think that is solved now @isidrok has created a version that does not allow inlining into html but at last it allows to have a single file bundle.

**Comment by isidrok** [comment]
I know this is closed, just came to say the plugin is already published https://github.com/isidrok/rollup-plugin-systemjs-loader
