### ISSUE TITLE
importing a file as name doesn’t work

### ISSUE THREAD

**Issue by flying-sheep** [rollup/rollup#368]
due to the way their ES5-ified code doesn’t agree with how the commonjs plugin converts it to ES6 syntax, i decided to do:

```js
import RR from 'react-redux/dist/react-redux'
```

which ends up in my code as

```js
var reactRedux = (function (module) { ... });
```

which is obviously completely surprising. i can only guess the name got derived from the file name? but silently completely discarding the name i chose is certainly wrong…

**Comment by eventualbuddha** [comment]
@flying-sheep I believe the name is derived from the file name, as you say. I believe this happens because there could be multiple imports of that file and it's easier to standardize on that, but that's just a guess on my part. While it's perhaps unexpected that the name you gave it isn't being used, it should work as expected since references to `RR` are also renamed.

See my [rollup-386](https://github.com/eventualbuddha/rollup-386) sample project for a simple example. Is the issue here that you were searching through the generated code for `RR` and didn't find it? Or was it actually causing a problem?

**Comment by flying-sheep** [comment]
well, i debugged the application i’m trying to port to rollup using the browser console due to several other problems (which i filed bugs for), and couldn’t find the name i gave in the global namespace.

where can i see what possible multiple imports there are? FYI: that dist file is wrapped in a universal module definition.

**Comment by Rich-Harris** [comment]
@flying-sheep can you provide a minimal reproduction illustrating the problem? Not sure I understand how you're bundling stuff and where it's going wrong. Thanks

**Comment by flying-sheep** [comment]
```console
$ npm install react-redux
```

then

```js
import RR from 'react-redux/dist/react-redux'
```

then (in the browser console)

```js
console.log(reactRedux) //ok
console.log(RR) //name error
```

**Comment by Rich-Harris** [comment]
Neither should work! The fact that you can log the value of `reactRedux` suggests that you're creating a bundle with either the CommonJS or ES6 format. (If you don't specify a format, Rollup defaults to ES6.) If you were exporting anything from your entry module, or importing any external modules, this would result in an error.

If you're building an application, you probably want a self-executing IIFE, using `--format iife` (or `format: 'iife'` if you're using a config file or the JavaScript API).

Inside a module that imports `RR`, `RR` refers to whatever is exported from `react-redux/dist/react-redux`:

```js
import RR from 'react-redux/dist/react-redux'
console.log( RR ); // {...}
```

But you should not rely on things being named in a particular way that's accessible outside the bundle, unless you export it from your entry module:

```js
// main.js
import RR from 'react-redux/dist/react-redux'

// make it available as a global
window.RR = RR;

// or export it from your bundle, so it can be accessed from outside the bundle
// (e.g. in the console) as `whateverYouCalledYourBundle.RR`
export { RR };
```

**Comment by flying-sheep** [comment]
what’s the canonical way to execute stuff in a browser environment then?

**Comment by Rich-Harris** [comment]
IIFE is the easiest way. If you have any external dependencies they should appear as `<script>` tags before the Rollup bundle. The alternative is to use AMD with a loader like RequireJS – more hassle to set up, but arguably more scalable if you have lots of dependencies (that have their own dependencies...).

UMD is good for when you don't know the execution environment (i.e. you're building a library).

**Comment by flying-sheep** [comment]
ah, i see. so only *function declarations* and *var declarations* implicitly assign to the global object.

all globally available things after using rollup’s default packaging are simply side effects of an undefined process (i.e. how rollup choses to internally rename things)

therefore there’s no way to get a semantic browser execution environment ATM, which would basically compile all `var` and `function` declarations to `(global || window).foo = ...`

**Comment by Rich-Harris** [comment]
Yes – that's expected *and desired* behaviour. The only way bits of your application should be accessible to the outside world is if you explicitly export them. That's also how ES6 modules will work in the browser once they're natively supported.

**Comment by flying-sheep** [comment]
hmm, the [`<module/>` proposal](https://github.com/dherman/module-tag/blob/master/explainer.md) says that their contents are executed in a scope, so no `var` and `function`, but it says nothing about `export`s. maybe we should define what happens with `export`s of a `<module/>` (dherman/module-tag#4)
