### ISSUE TITLE
`Property 'xxx' does not exist on type 'Vue'`  is thrown when accessing public member of a Vue class

### ISSUE THREAD

**Issue by orobert91** [rollup/rollup#3686]
When calling a public method on a Vue/TypeScript class, an error `Property 'xxx' does not exist on type 'Vue'` is thrown.

- Rollup Version: 1.32.1
- Operating System (or Browser): Windows x64 Build 18363
- Node Version (if applicable): N/A
- Link to reproduction (IMPORTANT, read below): https://repl.it/@orobert91/PropertyDoesNotExistOnTypeVue

### Expected Behavior
Should compile.
Compiles fine with tsc and WebPack.

### Actual Behavior
Does not compile.

**Comment by shellscape** [comment]
It looks like your issue is with `rollup-plugin-typescript2` and not Rollup, please create an issue with that project. I'd also advise you to update to the current major version of Rollup, as you're a full major behind.
