### ISSUE TITLE
Bug: UMD cannot run in strict mode

### ISSUE THREAD

**Issue by Jack-Works** [rollup/rollup#3689]
- Rollup Version: 2.22.2
- Operating System (or Browser): browser
- Node Version (if applicable): N/A
- Link to reproduction (IMPORTANT, read below): https://rollupjs.org/repl/?version=2.22.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAxJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIydW1kJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global = global || self, global.myBundle = factory());
}(this || globalThis, (function () { 'use strict';

	var main = 1;

	return main;

})));
```

### Actual Behavior

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global = global || self, global.myBundle = factory());
}(this, (function () { 'use strict';

	var main = 1;

	return main;

})));
```

Related: https://github.com/facebook/react/issues/18040

**Comment by Jack-Works** [comment]
the `global = global || self` the trick only works for the browser. We need `globalThis` to make it work on other environments.

**Comment by lukastaegert** [comment]
It works for all environments that have either `this` or `self` point to the global object. The problem is
- on older systems, there is no `globalThis` so we have to move that one after other options otherwise it will throw with an Uncaught ReferenceError
- on Node, there is no self, so we would need to move `self` after `globalThis`

No matter how we turn it, we will likely need to probe one of the options via `typeof`. Maybe `global = global || typeof self === 'undefined' ? globalThis : self`? Other suggestions?

**Comment by lukastaegert** [comment]
To make it nicer, we could also move this into the first argument.

**Comment by Jack-Works** [comment]
The lodash way is good enough to me.
https://github.com/lodash/lodash/pull/4347/files
 Besides, I have a request: please make the globalThis at the first place.

Here is my reason: in Firefox web extension content script, globalThis does not equal to window. globalThis means the current global object (sandbox) and the window means the global object out of the sandbox.

**Comment by lukastaegert** [comment]
Makes sense. I assume #3691 would work for you?
