### ISSUE TITLE
Double backslashes in chunk module file paths on Windows

### ISSUE THREAD

**Issue by benmccann** [rollup/rollup#3694]
- Rollup Version: 2.23.0
- Operating System (or Browser): Windows
- Link to reproduction (IMPORTANT, read below): https://github.com/sveltejs/sapper/blob/f3e9fc48d281ff990458a4a537a50d59db105e37/src/core/create_compilers/RollupCompiler.ts#L38

### Expected Behavior

The following plugin should print paths with only a single backslash on Windows:

```
{
	name: 'rollup-test',
	renderChunk: (code: string, chunk: any) => {
		console.log(JSON.stringify(chunk.modules));
	},
}
```

### Actual Behavior

The chunk modules all have double backslashes on a Windows machine:
```
"C:\\Users\\simon\\Source\\my-app\\node_modules\\svelte\\internal\\index.mjs"
```

Unfortunately I don't have a Windows machine to test with, but @Shackless was able to identify this on his machine

We've gotten a number of bug reports in Sapper (https://github.com/sveltejs/sapper/issues/1256 and https://github.com/sveltejs/sapper/issues/1333) because it has a Rollup plugin which tries to match this path to a another path and it bombs out when it can't find a match due to the double slash. We can work around it there, but it seems a bit odd to be getting these paths as input to the plugin

**Comment by lukastaegert** [comment]
Ok, correct me if I am wrong, but `JSON.stringify(someString)` is always printing the string in a form that it could appear in a JSON file. That means that backslashes ARE escaped because `"\"` is not a valid JavaScript string, please try it in your console. Or run `JSON.stringify('\u005c')` which is the charcode for a backslash and see what you get. So to me, this sounds like a wrong use of `JSON.stringify`.

**Comment by Shackless** [comment]
Yes, you're right. The problem was something else: While the path starts with a leading uppercase char in `chunks.module`, it was compared with a path starting with a lowercase char. I think this ticket can be closed.

**Comment by benmccann** [comment]
Thanks for pointing out that backslash is an escape character in JSON!

It looks like Node is inconsistent in normalizing drive names on Windows. It lowercases them it you call `join` but the paths from Rollup start with `C:`
