### ISSUE TITLE
Static class fields error: 'super' keyword outside a method.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [rollup/rollup#3702]
- Rollup Version: 2.23.0
- Operating System (or Browser): Windows
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): [https://rollup.js.org/repl/](https://rollupjs.org/repl/?version=2.23.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwQSUyMCU3QiU1Q24lNUN0c3RhdGljJTIwc2NvcmUlMjAlM0QlMjA1JTNCJTVDbiU3RCU1Q24lNUNuY2xhc3MlMjBCJTIwZXh0ZW5kcyUyMEElMjAlN0IlNUNuJTVDdHN0YXRpYyUyMHNjb3JlJTIwJTNEJTIwc3VwZXIuc2NvcmUlMjAlMkIlMjA1JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior
Should've have this error. There is no javascript error when running it.

### Actual Behavior
Doesn't work and shows error.

**Comment by lukastaegert** [comment]
Apparently this is an acorn issue again, I created an upstream issue: acornjs/acorn-static-class-features#7

**Comment by ChocolateLoverRaj** [comment]
So is this issue just waiting for someone to respond to the acornjs issue?

**Comment by lukastaegert** [comment]
Exactly

**Comment by ChocolateLoverRaj** [comment]
How long do you think it will take for acornjs to look at the issue? It doesn't seem like it is very active.

**Comment by lukastaegert** [comment]
I guess any outside support is welcome.

**Comment by ChocolateLoverRaj** [comment]
## The upstream issue has been closed. 
I wonder why. 
There wasn't even a closing comment saying anything.

**Comment by ChocolateLoverRaj** [comment]
### My Mistake
I didn't realize that the closed issue is linked to a commit. I think they fixed it in the upstream repo.
