### ISSUE TITLE
this.addWatchFile does not listen for new files added to a directory

### ISSUE THREAD

**Issue by mjackson** [rollup/rollup#3704]
- Rollup Version: 2.23.0
- Operating System (or Browser): macos
- Node Version (if applicable): 14.3.0
- Link to reproduction (IMPORTANT, read below): https://github.com/mjackson/rollup-watch-dir

### Expected Behavior

I'm expecting a rebuild when a new file is added to a directory that was passed to `this.addWatchFile`.

### Actual Behavior

New files do not trigger a rebuild.

**Comment by mjackson** [comment]
I believe this may be fixed by listening for the `add` event (in addition to the `change` and `unlink` events) in the file watcher [here](https://github.com/rollup/rollup/blob/cd47fcf3169d9592e9065ec2d376859475d0b108/src/watch/fileWatcher.ts#L61-L62), but I'm not familiar enough with the code to be sure. FWIW I cloned the repo and was going to fix the bug myself but I couldn't get all tests to pass locally.

**Comment by lukastaegert** [comment]
On slow machines, some tests might run into timeouts. You can focus on specific tests by adding `solo: true` in `_config.js` files for directory based tests and of course `describe.only` or `it.only` for file based tests. I think for watch we still only have the latter, but this should at least give you the opportunity to see if you can get your new test to run. Last, you can add a long timeout to a an `it` or `describe` via adding a `it('...', () => {...}).timeout(20000)` or more

**Comment by tzachbon** [comment]
I'm sorry to bring up the dead. We face a similar issue, and I feel this PR (#3812) missed this place:
https://github.com/rollup/rollup/blob/61d6820f54616506dc08c8500683d2c9bb75a0cc/src/Graph.ts#L84

Maybe I don't understand the full flow, but what's the difference between them? @lukastaegert

**Comment by lukastaegert** [comment]
The PR is correct as there are two distinct set of events:
* file watcher events: That is what the PR is listening for. They are created by chokidar.
* Rollup watcher events: These are emitted by Rollup's watcher. Currently, the only emitted event on file additions/changes/removals is `change`: https://github.com/rollup/rollup/blob/6d8924c8acd7fd124da5fa8026537e1c629f1515/src/watch/watch.ts#L95
  However, the original event is passed as a parameter

But I believe with #4427, which is now released in Rollup v2.70.0, your problems are resolved?

In any case, I will close this issue now as it has been resolved via #3812 a long time ago.
