### ISSUE TITLE
Rollupjs.org unavailable

### ISSUE THREAD

**Issue by jonathan-s** [rollup/rollup#3706]
Can't access the site. 
<img width="973" alt="Screenshot 2020-08-05 at 11 05 30" src="https://user-images.githubusercontent.com/2124818/89393840-a0c37e80-d70b-11ea-818a-a66725c203b6.png">

**Comment by kescherCode** [comment]
![image](https://user-images.githubusercontent.com/23276523/89414791-4803de00-d72b-11ea-9ebd-ff212780f482.png)

**Comment by shellscape** [comment]
Hey folks. The cert expired and we're getting in touch with the person who takes care of that. To prevent "same," "me too" type replies, we're going to lock this one - but rest assured that we're aware and working towards fixing it!

**Comment by lukastaegert** [comment]
Should be fixed now, if it is not working for your, wait a little for the DNS update to propagate and/or restart your browser.
