### ISSUE TITLE
AMD and CJS missing default in dynamic import

### ISSUE THREAD

**Issue by dasa** [rollup/rollup#3708]
- Rollup Version: 2.23.0
- Operating System (or Browser): macOS
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below):

[Rollup REPL](https://rollupjs.org/repl/?version=2.23.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCglNUMlMjIuJTJGZm9vLmpzJTVDJTIyKS50aGVuKGZ1bmN0aW9uKGZvbyklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIybWFpbiU1QyUyMiUyQyUyMGZvby5kZWZhdWx0KSUzQiU1Q24lN0QpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGxvZ2dlciUyMGZyb20lMjAlNUMlMjIuJTJGbG9nZ2VyLmpzJTVDJTIyJTNCJTVDbmxvZ2dlciglNUMlMjJmb28lNUMlMjIpJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwJTVDJTIyZm9vJTVDJTIyJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybG9nZ2VyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbihtc2cpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZyhtc2cpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZm9vJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28uanMlNUMlMjIlM0IlNUNuaW1wb3J0JTIwbG9nZ2VyJTIwZnJvbSUyMCU1QyUyMi4lMkZsb2dnZXIuanMlNUMlMjIlM0IlNUNuJTVDbmxvZ2dlcihmb28pJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior

The dynamic import in `main.js` should have a `default`, but does not. It does work correctly if `bar.js` is not also an entry module.

When running the original `main.js` code, the console log is:

```
foo
main foo
```

### Actual Behavior

When running output AMD or CJS `main.js` code, the console log is:

```
foo
main undefined
```

**Comment by lukastaegert** [comment]
Thanks for spotting, this was an issue where quite a few things needed to come together. Fix at #3709.

**Comment by dasa** [comment]
Thanks for the quick fix!
