### ISSUE TITLE
Rollup docs website timing out

### ISSUE THREAD

**Issue by maxwell8888** [rollup/rollup#3715]
Since yesterday, http://rollupjs.org/guide/en/ has been timing out when serving the following resources:
`main.847281349.css`   
`client.a8f3174f.js`  
So just barebones html is rendered, after about 10 seconds.

**Comment by shellscape** [comment]
Thanks for letting us know. Looks good on my end. No network errors or timeouts. Could be regional on your end.

**Comment by maxwell8888** [comment]
I just tried again and it's working fine now 👍
