### ISSUE TITLE
Documentation on @rollup/plugin-babel is misleading

### ISSUE THREAD

**Issue by Robin-Hoodie** [rollup/rollup#3717]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Regarding [the part on using `@rollup/plugin-babel`](https://rollupjs.org/guide/en/#babel), the following is mentioned:

> 
```
{
  "presets": [
    ["@babel/env", {"modules": false}]
  ]
}
```
> There are a few unusual elements to this setup. First, we're setting "modules": false, otherwise Babel will convert our modules to CommonJS before Rollup gets a chance to do its thing, causing it to fail.

However, when then looking at [the documentation of `@rollup/plugin-babel` itself](https://github.com/rollup/plugins/tree/master/packages/babel#modules), the following on `modules` is mentioned:

> Modules
This is not needed since Babel 7 - it knows automatically that Rollup understands ES modules & that it shouldn't use any module transform with it. Unless you forcefully include a module transform in your Babel configuration.

### Your Proposal for Changes

Update rollup documentation, and remove the `{"modules": false}` in the codeblock as well as the explanation below it.

**Comment by Andarist** [comment]
@Robin-Hoodie PR for the docs improvement would be highly appreciated - it seems that this one should be quite easy to make.
