### ISSUE TITLE
Rollup 2.24 breaks UMD bundle

### ISSUE THREAD

**Issue by HitkoDev** [rollup/rollup#3723]
- Rollup Version: >= 2.24 
- Operating System: N/A
- Node Version: N/A
- Link to reproduction: https://repl.it/repls/VagueTiredApplications (or just create UMD bundle from the following input)

```js
import {resolve} from 'dns'
import 'util'
import {writeFileSync} from 'fs'

resolve('name')
writeFileSync('foo', 'bar')
```

### Expected Behavior

Wrapper function looks like

```js
function (dns, util, fs) {
  // content
}
```

### Actual Behavior

Wrapper function looks like

```js
function (dns, , fs) {
  // content
}
```

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #3724
