### ISSUE TITLE
Rollup added to technology comparison database

### ISSUE THREAD

**Issue by dancancro** [rollup/rollup#373]
Hi,

I maintain a database of development technology features and recently added rollup to it. If you would like to see the differences between things or correct errors, just go [here](http://www.dancancro.com/compare-app-technologies/). Rollup is listed among Package Managers on the Tools page. The categories aren't that important. In this database any technology can provide any benefit.

You can also do a complete account of rollup's features by doing a questionnaire [here](http://www.dancancro.com/technology-questionnaires/)

**Comment by Victorystick** [comment]
@dancancro First of all, Rollup should be listed under the Loader category, along with Browserify and Webpack.

I don't understand what kind information you store there, and what you'd want from us. What do the matrix cells mean? What are the _scores_? The questionnaire is just too long for me.

**Comment by Rich-Harris** [comment]
Closing this to keep the issue tracker tidy – if anyone out there wants to fill out the questionnaire, please do!
