### ISSUE TITLE
Avoid warning: If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.

### ISSUE THREAD

**Issue by nylen** [rollup/rollup#3735]
### Expected Behavior / Situation

I expect to be able to avoid the warning generated when `output.name` is not specified for an IIFE bundle, if I know why that is and I know it won't cause problems.

A way to elide the `return` of the IIFE entirely would also be helpful.

In this case I'm trying to use Rollup to concatenate some JavaScript files and expand the `require` statements they contain, to generate a script file that is suitable for including in browsers.  This JavaScript code only modifies existing global objects, and it is really just organized into separate files in the source tree for convenience, so there is no need for this warning. The project is currently using Webpack for this use case, which works fine but generates a bit of extra boilerplate code.

More info:

- In-progress change from Webpack to Rollup: https://github.com/ClassicPress/ClassicPress/pull/607
- `rollup.config.cjs`: https://github.com/ClassicPress/ClassicPress/blob/try/rollup-js/rollup.config.cjs
- Example input file: https://github.com/ClassicPress/ClassicPress/blob/try/rollup-js/src/wp-includes/js/media/audiovideo.manifest.js
- Example generated file with empty output statement: https://github.com/ClassicPress/ClassicPress/blob/try/rollup-js/src/wp-includes/js/media-audiovideo.js#L992

### Actual Behavior / Situation

Rollup shows a warning:

```
src/wp-includes/js/media/audiovideo.manifest.js → src/wp-includes/js/media-audiovideo.js...
(!) If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.
created src/wp-includes/js/media-audiovideo.js in 199ms
```

and generates an empty output/return statement for each of these IIFE bundles:

```js
(function () {
	'use strict';

	/* snip */

	var audiovideo_manifest = {

	};

	return audiovideo_manifest;

}());
```

neither of which are necessary/helpful for this use case.

### Modification Proposal

Add a way for Rollup users to ignore this warning and omit the output statement as part of an `iife` bundle. This could be an option like `iifeExports: false` or something else.

### Request for clarification

In the Rollup code for this warning I see references to `hasExports` indicating that this warning should only be shown if my code exports some values to the outside environment:

https://github.com/rollup/rollup/blob/4b41f4e59e51aea51be0bf7fb110296321cb1895/src/finalisers/iife.ts#L60-L65

Why does Rollup think my code has exports when it doesn't? If there is a way to fix that, then that would also solve my current issue (apart from the spurious output/return statement which really isn't that big of a deal).

**Comment by lukastaegert** [comment]
The reason you are seeing this warning is because you are using CommonJS files as import, which implicitly always have the `exports` object as default export, no matter if you use it or not. The fix is simple: Use an ES module as entry point that does not have exports. In your case, such an ES module could consist of a single import statement importing the file you are actually interested in.

**Comment by nylen** [comment]
Works perfectly: https://github.com/ClassicPress/ClassicPress/pull/607/commits/b220a6cf6453e095d13a5543ef434046ca6304eb

Thanks!
