### ISSUE TITLE
destructuring in exports

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#374]
[Trying to do this](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22const%20defaultGreeting%20%3D%20'Hello'%3B%5Cnconst%20defaultName%20%3D%20'World'%3B%5Cn%5Cnexport%20function%20greet(opts)%20%7B%5Cn%20%20const%20%7B%5Cn%20%20%20%20greeting%20%3D%20defaultGreeting%2C%5Cn%20%20%20%20name%20%3D%20defaultName%5Cn%20%20%7D%20%3D%20opts%3B%5Cn%20%20console.log(greeting%20%2B%20'%20'%20%2B%20name)%3B%5Cn%7D%5Cn%5Cnexpor%5Cn%5Cn%2F%2Fexport%20const%20%7B%20a%20%7D%20%3D%20foo%3B%22%7D%5D%7D),
```js
export const { a } = foo;
```
yields ` TypeError: Cannot set property 'isExported' of null`. I assume we should handle this?

**Comment by eventualbuddha** [comment]
Ah, yep. That's a bug.

**Comment by Rich-Harris** [comment]
What's the expected behaviour here? Is this definitely a valid export? Is `a` the value of `foo.a` at the time at which the declaration is evaluated, or is it bound (i.e. always reflects the value of `foo.a`)? I got a bit lost in the spec, can't quite figure out what's what.

**Comment by Victorystick** [comment]
It's just a destructuring assignment so it should reflect the value of `foo.a` when it's evaluated.

```js
var a; // declares `a`
export var b; // declares and exports `b`
var { c } = obj; // declares `c`
export var { d } = obj; // declares and exports `d`
```

[Here's how Babel handles it](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=true&spec=false&code=export%20const%20%7B%20a%20%7D%20%3D%20foo%3B%0A%0Aexport%20const%20%7B%20bar%3A%20%7B%20baz%20%7D%20%7D%20%3D%20foo%3B).
