### ISSUE TITLE
preserveModules creates wrong output

### ISSUE THREAD

**Issue by johannes-z** [rollup/rollup#3743]
- Rollup Version: `^2.26.4`
- Operating System (or Browser): Ubuntu 1804
- Node Version (if applicable): `10.19.0`
- Link to reproduction (IMPORTANT, read below): https://repl.it/repls/KindlyHospitableDataset

### Expected Behavior
The emitted `lib` folder should look like this:
- `main.js`
- `HelloWorld.vue_rollup-plugin....js`
- `HelloWorld.vue.js`

### Actual Behavior
The emitted `lib` folder looks like this:
- `node_modules/`
- `src`
  - `HelloWorld.vue_rollup-plugin....js`
  - `HelloWorld.vue.js`
- `main.js`

The plugins resolve and commonjs do nothing to remedy this, also adding those libraries added to node_modules to externals does nothing. 

#### Additional
In a monorepo, all the files within `lib` are also under the path the monorepo is under, i.e. if the package is in `/my-project/packages/my-package`, the output will look like this. `/my-project/packages/my-package/lib/package/my-package/main.js`

**Comment by lukastaegert** [comment]
The answer is simple: There are several files from `node_modules` that are included in the build, and `preserveModules` preserves the directory structure. If you do not want this, or you want some partial bundling, I fear your only option would be to put all files that you want as separate inputs as an array into the `input` property.

**Comment by johannes-z** [comment]
Shouldn't marking those `node_modules` as `externals` be sufficient to not have them copied to the dist folder? I tried a number of ways preventing those node_modules from ending up in my dist folder, but nothing seemed to work. Especially @rollup/plugin-commonjs always messed up the dist folder because it creates a `_virtual` folder.

**Comment by lukastaegert** [comment]
Hmm, I thought ids were passed twice through `external`, but apparently only unresolved ids are passed here. Will need to check this again. Anyway, if you use a function for `external` you can log what ids are passed here and add those to external that are needed. In your case

```
external: ['tslib', 'vue', 'vue-class-component', 'vue-property-decorator', 'vue-runtime-helpers/dist/normalize-component.mjs']
```

did the trick. Or if you do it via a function

```
external(id) {
  return id === 'tslib' || id.startsWith('vue');
}
```

and last via regular expression

```
external: /^(tslib$|vue)/
```

**Comment by lukastaegert** [comment]
Fix for the `external` behaviour here: #3753. This was apparently overlooked for quite some time.

**Comment by johannes-z** [comment]
Thanks! Seems to work for me now.

**Comment by cimchd** [comment]
Just in case someone (like me) finds this topic first. In a monorepo it may help to also add `preserveModuleRoot` option. 

See: https://github.com/rollup/plugins/issues/321
