### ISSUE TITLE
Variables conflict: imported module and local variable have the same name

### ISSUE THREAD

**Issue by cyberalien** [rollup/rollup#3746]
- Rollup Version: 2.26.5
- Operating System (or Browser): OSX 10.15.6
- Node Version (if applicable): 13.12.0
- Link to reproduction (IMPORTANT, read below): https://github.com/cyberalien/rollup-bug-demo

### Expected Behavior

Original code:

```js
import { stringToIcon, validateIcon } from '@iconify/core/lib/icon/name';

export function cleanIconName(name) {
	if (typeof name === 'string') {
		name = stringToIcon(name);
	}
	return name === null || !validateIcon(name) ? null : name;
}
```

Expected to remain about the same after bundling

### Actual Behavior

Same function from bundle generated by rollup:

```js
	function cleanIconName(name) {
		if (typeof name === 'string') {
			name = name.stringToIcon(name);
		}
		return name === null || !name.validateIcon(name) ? null : name;
	}
```

Function `stringToIcon` imported from an external module was assigned to variable `name`, so it became `name.stringToIcon`. Also parameter of `cleanIconName` where `stringToIcon` is used has name `name`.

Because of that, instead of calling function, code throws an error.

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #3747
