### ISSUE TITLE
Releases starting with 2.24.0 seem to break JSX syntax when not transpiling

### ISSUE THREAD

**Issue by swernerx** [rollup/rollup#3748]
- Rollup Version: 2.26.6
- Operating System (or Browser): MacOS 10.15.6
- Node Version (if applicable): v12.18.2
- Link to reproduction (IMPORTANT, read below):

I had previously been using a JSX parse helper for Rollup created by @lukastaegert which worked like charm: https://github.com/rollup/rollup/issues/2822#issuecomment-486676465. 

For context: We are relying on the fact the 3rd parties users of our UI libraries might want use different transpile settings for JSX e.g. enabling/disabling debug hints. Therefor we thought that keeping the JSX intact for library publishing might be a good way doing that. This means we enable `preset-env` from babel, but exclude `preset-react`. Our library will be transpiled to something widely compatible but will keep JSX intact so that this can be transpiled as needed by the application.

Unfortunately due to changes which had happend with v2.24.0 this functionality is broken for CommonJS output as invalid code is being produced. Inside JSX brackets it now contains expressions like this one:

Old (before 2.24.0):

```js
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React = _interopDefault(require('react'));
var Header = _interopDefault(require('components/Header'));

function MyPage() {
  return <Header>Title</Header>
}
```

New (from 2.26.6):

```js
var React = require('react');
var Header = require('components/Header');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);
var Header__default = /*#__PURE__*/_interopDefaultLegacy(Header);

function MyPage() {
  return <Header__default['default']>Title</Header__default['default']>
}
```

I do not have any background information on why the `default` property is not assigned anymore to the variable. Maybe someone with deeper knowledge on this topic can help.

The JSX helper is used as shared by @lukastaegert and can be found here: 
https://github.com/sebastian-software/preppy/blob/master/src/jsxPlugin.js

I guess it would be easier to tweak the output the the `default` handling than alter this plugin. But I am open to all solutions which help.

Thanks a lot.

**Comment by lukastaegert** [comment]
A simple way to flatten the property accesses would be to pass the `output.externalLiveBindings: false` option.

**Comment by lukastaegert** [comment]
I assume that `<Header__default.default/>` would also be a valid JSX tag? Because with Rollup 3, output will likely change in that way as we plan on raising the compatibility target to ES2015.

**Comment by swernerx** [comment]
Interesting. Thanks!

Regarding to whether this is a valid JSX tag... good question. I passed that syntax through prettier and it failed so I guessed it is invalid.

**Comment by swernerx** [comment]
Working:
<img width="651" alt="Bildschirmfoto 2020-08-27 um 16 50 14" src="https://user-images.githubusercontent.com/145201/91458067-6326c100-e885-11ea-8f5a-6ebdeb8e9f39.png">

Not working:
<img width="702" alt="Bildschirmfoto 2020-08-27 um 16 50 37" src="https://user-images.githubusercontent.com/145201/91458112-7043b000-e885-11ea-8ad4-68f7cc8ab48f.png">

**Comment by shellscape** [comment]
@swernerx this kind of situation is exactly why we ask for reproductions and have such a stern warning about not providing them:

> Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   
>   For some bugs it this may seem like overkill but believe us, very often what seems like a
>   "clear issue" is actually specific to some details of your setup. Having a runnable
>   reproduction not only "proves" your bug to us but also allows us to spend all our effort
>   fixing the bug instead of struggling to understand your issue.

**Comment by swernerx** [comment]
I know and I agree @shellscape - that's not that I am not willing to. I just need the time for it as this is more custom code involved I cannot use the repl offered here. I have to go with option 3.

Also as this error only happens with the "inofficial" jsx handling provided by @lukastaegert I was not sure about the best approach.

**Comment by swernerx** [comment]
Here is a repro as a new git repository... pretty lean showcase I guess:
https://github.com/swernerx/rollup-lazy-jsx

**Comment by lukastaegert** [comment]
Thanks for taking the time. Going back to one of my original comments

> A simple way to flatten the property accesses would be to pass the output.externalLiveBindings: false option

is this a valid interim solution for you until Rollup 3?

**Comment by swernerx** [comment]
It seems to work that way. I even tested that flag in the repository I shared. 

I am not aware though of what other side-effects this might have. Even though the code with `output.externalLiveBindings: false` looks simpler it is mentioned in the docs that disabling it produces less optimal code. Can you elaborate on this?

The issue is probably CommonJS only, right?

**Comment by lukastaegert** [comment]
Depends on your definition of optimal. In a manner of speaking, it produces more optimal code as it is smaller and faster. But there can be issues if you have circular dependencies, however those are usually rather rare.

The issue will manifest in CommonJS, AMD, UMD and IIFE.

**Comment by swernerx** [comment]
Interesting. Thanks for clarification. The same situation is true for ESM, correct, as this would never allow circular deps at all. So setting this flag to false unifies behavior between CJS and ESM, does it?

**Comment by lukastaegert** [comment]
Ah, maybe I should clarify. This issue only manifests if at runtime, your code has a circular dependency with an *external* dependency. ESM and SystemJS should not have any issues here.

**Comment by lukastaegert** [comment]
Internal circular dependencies should not cause issues except a warning.

**Comment by swernerx** [comment]
I guess the issue you describe "circular dependency with an external dependency" would be pretty uncommon for Preppy for.. it's about publishing shared libraries. That said I guess it's safe do set `output.externalLiveBindings: false` for this case. Thanks!

**Comment by swernerx** [comment]
See also: https://github.com/sebastian-software/preppy/releases/tag/10.7.0

**Comment by lukastaegert** [comment]
Nice! Yes, I also think the issue should be rather uncommon, it is more about correctness in edge case scenarios. I hope I can get some work towards Rollup@3 done soon...
