### ISSUE TITLE
Crash with "TypeError: Cannot read property 'render' of null"

### ISSUE THREAD

**Issue by DreierF** [rollup/rollup#3749]
- Rollup Version: 2.26.6
- Operating System (or Browser): Not relevant
- Node Version (if applicable): Not relevant
- Link to reproduction (IMPORTANT, read below): [Minimal failing sample REPL](https://rollupjs.org/repl/?version=2.26.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwVU5IQU5ETEVEX1JFSkVDVElPTl9ERUxBWSUyMCUzRCUyMDAlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwcmVtb3ZlVW5oYW5kbGVkUmVqZWN0aW9uXyh0KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpZiUyMChVTkhBTkRMRURfUkVKRUNUSU9OX0RFTEFZJTIwJTNFJTIwMCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwZm9yJTIwKHZhciUyMHAlMjAlM0QlMjB0JTNCJTIwcCUyMCUyNiUyNiUyMHAudW5oYW5kbGVkUmVqZWN0aW9uSWRfJTNCJTIwcCUyMCUzRCUyMHAucGFyZW50XyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwd2luZG93LmNsZWFyVGltZW91dChwLnVuaGFuZGxlZFJlamVjdGlvbklkXyklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcC51bmhhbmRsZWRSZWplY3Rpb25JZF8lMjAlM0QlMjAwJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlMjBlbHNlJTIwaWYlMjAoVU5IQU5ETEVEX1JFSkVDVElPTl9ERUxBWSUyMCUzRCUzRCUyMDApJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGZvciUyMCh2YXIlMjBwJTIwJTNEJTIwdCUzQiUyMHAlMjAlMjYlMjYlMjBwLmhhZFVuaGFuZGxlZFJlamVjdGlvbl8lM0IlMjBwJTIwJTNEJTIwcC5wYXJlbnRfKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBwLmhhZFVuaGFuZGxlZFJlamVjdGlvbl8lMjAlM0QlMjBmYWxzZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCU3RCU1Q24lNUNucmVtb3ZlVW5oYW5kbGVkUmVqZWN0aW9uXyh1bmRlZmluZWQpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior

Code is processed without errors

### Actual Behavior

Rollup crashes with "TypeError: Cannot read property 'render' of null".

**Comment by kzc** [comment]
Node and Chrome produce the error above.

Curiously on Firefox the error is different: "TypeError: this.usedBranch is null". Some async functions may be firing in a different order.

**Comment by lukastaegert** [comment]
Thanks for spotting. So the problem surfaces when rendering a logical expression that is not actually executed. I will investigate how to solve it:
https://rollupjs.org/repl/?version=2.26.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmlmJTIwKGZhbHNlKSUyMCU3QiU1Q24lMjAlMjBmb3IlMjAodmFyJTIwcCUzQiUyMHVua25vd25HbG9iYWwlMjAlMjYlMjYlMjB0cnVlJTNCKSUyMCU3QiU3RCU1Q24lN0QlMjBlbHNlJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKHApJTNCJTVDbiU3RCU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by lukastaegert** [comment]
Fix at #3752. As it turned out, there were quite a few more edge cases that were broken, which prompted me to reimplement how hoisted variables in if-statements are rendered.
