### ISSUE TITLE
Comparing to Webpack.

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#375]
Hello! I'd highly recommend you submit a PR for this table: https://webpack.github.io/docs/comparison.html

It can be edited [here](https://github.com/webpack/docs/wiki/comparison/_edit).

It could get you exposure to the Webpack audience (and ultimately help the JavaScript community).

**Comment by dcworldwide** [comment]
Interesting idea.

**Comment by Victorystick** [comment]
Sweet! Added [Rollup to the comparison](https://github.com/webpack/docs/wiki/comparison)!
