### ISSUE TITLE
rollup --config re-computes imported import.meta.url

### ISSUE THREAD

**Issue by ctjlewis** [rollup/rollup#3758]
- Rollup Version: Latest
- Operating System (or Browser): Linux
- Node Version (if applicable): Latest
- Link to reproduction (IMPORTANT, read below): https://repl.it/repls/DaringRoughHypertalk
Clicking RUN will print `url` as seen by `node rollup.config.js` and `rollup -c rollup.config.js`.

### Expected Behavior
When exporting via:
```javascript
// index.js
export const url = import.meta.url;
```

And importing in a Rollup **config** that will be executed with `rollup -c`:
```javascript
// rollup.config.js
import { url } from './index.js'
```

`url` should equal the `import.meta.url` for the file in which it is **exported**, in this case, **`file:///path/to/index.js`**.

### Actual Behavior
Rollup seems to rewrite `import.meta.url` source in the config file such that `import.meta.url` is re-computed at runtime, and `url` is equal to **`file:///path/to/rollup.config.js`**. This conflicts with Node's output, and causes errors in compiled bundles.

**Comment by ctjlewis** [comment]
See: https://github.com/TeleworkInc/.gnv/blob/556cb88bfaa8b11f9f41c01a80dd89acb3f9378a/rollup.externs.js#L20
```javascript
/**
 * Rollup will hot-swap the source and re-compute PACKAGE_ROOT using
 * `import.meta` for this file, so we must resolve back to parent dir.
 *
 * This only occurs when executing this file via `rollup -c`.
 */
const packageJson = readPackageJson(path.resolve(PACKAGE_ROOT, '..'));
// const packageJson = readPackageJson(PACKAGE_ROOT);
```

**Comment by ctjlewis** [comment]
Hate to bug you, and super low priority, but any advice on how to workaround @lukastaegert or @Andarist?

**Comment by lukastaegert** [comment]
https://rollupjs.org/guide/en/#resolveimportmeta

**Comment by ctjlewis** [comment]
No, I wrote an import meta plugin - this issue is related to how `rollup -c` evaluates `import.meta` while executing the config file, and how it differs from expected behavior (see OP).

**Comment by lukastaegert** [comment]
Ah sorry, should have read this properly. While this is related to https://rollupjs.org/guide/en/#using-untranspiled-config-files, we could actually solve it at least for import.meta.url in `rollup -c` by injecting a plugin in the CLI that fixes this here https://github.com/rollup/rollup/blob/master/cli/run/loadConfigFile.ts#L65-L81. If you prepare a PR for this, I would be more than willing to review and merge this.
