### ISSUE TITLE
--environment argument for CLI

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#376]
Discovered that you can't do `export FOO=bar && rollup -c` on Windows. I'm not sure if there's a way to provide environment variables to an `npm run` script that works in both Windows and *nix. So it might be helpful if you could do this sort of thing:

```bash
rollup -c --environment FOO=bar
```

Any thoughts on whether this is the best way? Examples from other tools?

**Comment by eventualbuddha** [comment]
This is the closest I could find:
http://superuser.com/questions/223104/setting-environment-variable-for-just-one-command-in-windows-cmd-exe

**Comment by thisconnect** [comment]
unfortunately there is no npm way (https://github.com/npm/npm/issues/2800) to set env per task.
you could use `cross-env` "cross-env NODE_ENV=production npm run ..."
