### ISSUE TITLE
Handle stringified sourcemaps

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#377]
Via https://github.com/egoist/rollup-plugin-postcss/issues/1#issuecomment-166938098. It's not uncommon for compilers to return sourcemaps as JSON rather than as objects, so perhaps it would make sense for Rollup to detect when that's the case and handle it accordingly. Would be a one-liner somewhere around [here](https://github.com/rollup/rollup/blob/cabc4ee097c6b0ee1b03c300709233ef9495d293/src/utils/transform.js#L29)

**Comment by Victorystick** [comment]
That might be good. The [TypeScript plugin](https://github.com/rollup/rollup-plugin-typescript/blob/master/index.js#L34-L35) works around this as well.
