### ISSUE TITLE
null facadeModuleId

### ISSUE THREAD

**Issue by benmccann** [rollup/rollup#3772]
- Rollup Version: 2.6.11
- Link to reproduction: https://github.com/benmccann/null-facadeModuleId

### Expected Behavior

The docs say that `facadeModuleId` can be `null`, but not under what circumstances. It's seemed to me that it's normally defined for my own code, but not for npm modules. I think that I may have encountered a bug, but perhaps this `null` occurrence is expected and just needs to be documented

### Actual Behavior

I have [a repo to reproduce](https://github.com/benmccann/null-facadeModuleId) where I've added a plugin that prints the `facadeModuleId`:
```
			{
				renderChunk(code, chunk) {	
					console.log('Rendering chunk ' + chunk.fileName + ' with facadeModuleId ' + chunk.facadeModuleId);
				}
			}
```

When you run `npm run build`, it outputs the following:

>Rendering chunk client.ace9fc64.js with facadeModuleId /home/bmccann/src/tmp/sapper-bug-repro/src/client.js
Rendering chunk index.014760b5.js with facadeModuleId null
Rendering chunk about.9e4c9a51.js with facadeModuleId /home/bmccann/src/tmp/sapper-bug-repro/src/routes/about.svelte
Rendering chunk other.8973fdd3.js with facadeModuleId /home/bmccann/src/tmp/sapper-bug-repro/src/routes/other.svelte
>
>┌──────────────┐
│ built client │
└──────────────┘
   50.1 kB client.ace9fc64.js
           │ src/node_modules/@sapper/app.mjs (36.5%)
           │ node_modules/svelte/internal/index.mjs (24.7%)
           │ src/node_modules/@sapper/internal/App.svelte (15.3%)
           │ src/components/Nav.svelte (8.2%)
           │ src/node_modules/@sapper/internal/error.svelte (5.7%)
           │ src/routes/_layout.svelte (4.7%)
           │ node_modules/svelte/store/index.mjs (3.4%)
           │ src/node_modules/@sapper/internal/manifest-client.mjs (1.4%)
           │ src/client.js (0.1%)
           └ src/node_modules/@sapper/internal/shared.mjs (0.0%)
   4.08 kB index.014760b5.js
           │ src/routes/index.svelte (99.5%)
           └ src/something.js (0.5%)
   1.75 kB about.9e4c9a51.js
           └ src/routes/about.svelte
   1.17 kB other.8973fdd3.js
           └ src/routes/other.svelte

This shows that `index.014760b5.js` has a `null` `facadeModuleId` and is comprised of `src/routes/index.svelte` and `src/something.js` which are both directly in my project. This seems unexpcted to me. I would expect it to be `/home/bmccann/src/tmp/sapper-bug-repro/src/routes/index.svelte`

This is not a minimal reproduction because I first wanted to confirm my understanding of how `facadeModuleId` is intended to work. As a first step, adding to the documentation would be helpful here. I haven't easily been able to create a minimal reproduction, but if this does look like a possible bug then I will see if I can reproduce it without the svelte plugin, etc.

Thanks for all your work on Rollup!!

**Comment by lukastaegert** [comment]
The facadeModuleId means that this chunk exhibits the same export signature as the given module. It is only defined in two situations:
- the chunk is an entry chunk, in which case it will be the corresponding entry module
- the chunk is dynamically imported and there are no exports in the chunk that did not exist on the module that was originally dynamically imported

For all other chunks it is null. The simplest scenario to create such a chunk is to have two entry modules that import a shared module. Then the shared module is in its own chunk but does not have a facadeModuleId. It is also possible to create this situation with two independent dynamic imports.

**Comment by benmccann** [comment]
Thanks! This is super helpful!
