### ISSUE TITLE
Write CSS outside the JS destination folder

### ISSUE THREAD

**Issue by 8483** [rollup/rollup#3777]
### Feature Proposal

Why is the path relative to the `bundle.js` destination?  

I need to save the CSS in a separate location, **outside** the destination, and it doesn't allow it, gives this error.

```
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute 
nor relative paths and do not contain invalid characters, received "/bundle-svelte-activities.css".
```

**Comment by shellscape** [comment]
This is identical to #3776, you've just pasted the same support request into a Feature Request template. Please _read_ the content of the template:

>   👉🏽 Need help or tech support? Please don't open an issue!
>  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs
