### ISSUE TITLE
Support name-spaced UMD module names

### ISSUE THREAD

**Issue by ericf** [rollup/rollup#378]
I'd like to set the `--name` option to be something like: `Foo.bar`. Rollup will accept this as input and output `Global.Foo.bar = ...` in the UMD module, but this will break if `Foo` isn't already defined.

Browserify supports name-spaced module names by recognizing this pattern and generating code to make sure the object is defined before the member expression assignment. Something like:

```js
(global.Foo || (global.Foo = {})).bar = ...
```

It would be great if Rollup also supported this for name-spaced UMD module names.

**Comment by ericf** [comment]
Thanks! :smile:

**Comment by Rich-Harris** [comment]
Thanks for raising it! Just published a new version with this fix – 0.22.1

**Comment by ericf** [comment]
@Rich-Harris I've tried this out in 0.22.2 and it appears to be generating bad code. You can [see in this example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22umd%22%2C%22moduleName%22%3A%22foo.bar%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20default%2042%3B%22%7D%5D%7D).

The comma expression needs parens around it, otherwise it throws in a CommonJS or AMD environment.

**Comment by ericf** [comment]
PR to address the above problem: https://github.com/rollup/rollup/pull/392

**Comment by sevencai** [comment]
Is there any way to disable name-spaced UMD module names?

Sometimes I just need a dot in exported name, like `1.0 `version in it.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/23190922/222941983-62361621-b369-496b-8d22-96a32cfe58ee.png">
