### ISSUE TITLE
A method of adding an import based on dependency graph

### ISSUE THREAD

**Issue by benmccann** [rollup/rollup#3790]
### Feature Use Case

Sapper has a CSS-handling plugin, which has recently been significantly cleaned up and is about ready to graduate into a separate Rollup plugin for wider community use:

https://github.com/sveltejs/sapper/blob/ead10eebb7416971a390a0190f1df7c1f3327791/src/core/create_compilers/RollupCompiler.ts#L156

It finds CSS that a dynamically imported chunk tree includes and then rewrites the dynamic imports with an extra bit of code. That code makes it so that in parallel to the original dynamic import we also write `link` tags pointing to the CSS.

So as not to duplicate code across chunks, this plugin emits a new `inject_styles` chunk. It then adds an import to that chunk where it's used. The problem here is that this `import` does not show up in the `chunk.imports` for the plugins that follow it.

### Feature Proposal

Things I've tried:
* I've tried doing `chunk.imports.push(newImport)` when adding the import in `generateBundle`. This does not persist for the next plugin
* I've tried rewriting the code in `transform`. This does not work because I don't have access to the dependency graph. When I call `this.getModuleInfo` it returns empty arrays for the `importedIds` and `dynamicallyImportedIds`
* I've tried rewriting the code in `renderChunk`. However, I don't know the file name to add. If I simply do `import __inject_styles from 'inject_styles.js'` then that doesn't get properly rewritten to include the hash in the filename.

It would be nice if at least one of these worked or there was another solution to this problem

### Related Requests

https://github.com/rollup/rollup/issues/3519

**Comment by codepunkt** [comment]
I've been running into an issue that is kinda similar. Did you have any success?

**Comment by lukastaegert** [comment]
> I've tried rewriting the code in transform. This does not work because I don't have access to the dependency graph. When I call this.getModuleInfo it returns empty arrays for the importedIds and dynamicallyImportedIds

Sorry for not getting back to you when this issue was created. A lot has happened since then, especially the introduction of the `this.load` context function. I have recently put some work into streamlining the process of scanning dependency graphs inside build time hooks, maybe #4358 will allow you to solve the issue?

**Comment by benmccann** [comment]
Sapper has been replaced by SvelteKit, which is built on top of Vite, so I no longer have a direct need for this. I see a few folks from the Vite team copied on https://github.com/rollup/rollup/pull/4358. As far as I'm concerned, I'm happy with any solution they're happy with, so feel free to link this issue to that PR so that it will be closed by it

**Comment by lukastaegert** [comment]
#4543 now allows you (even encourages you) to update the `import`/`export` information when updating a chunk

**Comment by lukastaegert** [comment]
#4543 now allows you (even encourages you) to update the `import`/`export` information when updating a chunk
