### ISSUE TITLE
Plan for import assertions and non-JS module types

### ISSUE THREAD

**Issue by justinfagnani** [rollup/rollup#3799]
### Feature Use Case

Importing JSON, CSS, and HTML according to upcoming JavaScript and HTML standards.

### Feature Proposal

Import assertions are a Stage 3 TC39 proposal to allow source code to assert that an import has a specific type (among other possible assertions): https://github.com/tc39/proposal-import-assertions

Assertions are being added to unblock the JSON, CSS, and HTML modules proposals which allow importing those file type as JavaScript modules.

This means that we'll be able to import JSON, CSS and HTML into JavaScript natively, and ideally in bundlers without any specific loaders (or perhaps a "web standard loader" that implements all web-native module types?):

```js
import styles from './styles.css' assert {type: 'css'};

// or

const styles = await import('./styles.css', {assert: {type: 'css'}});
```

I filed an [issue on Acorn for import assertion support](https://github.com/acornjs/acorn/issues/983).

The JSON and CSS proposals are furthest along, with implementations in Chromium behind flags.

- [Cascading Style Sheet Module Scripts Explainer](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md)
- [JSON Modules](https://github.com/tc39/proposal-json-modules)

**Comment by lukastaegert** [comment]
If there is an acorn plugin for import assertions, then we can include this in the Rollup build even if it is not part of acorn core. But I did not see one, so maybe this requires some community effort to drive forward.

**Comment by justinfagnani** [comment]
Yeah, there doesn't appear to be an acorn plugin yet.

After that exists though, what would be the plan for Rollup support of the module types that the web platform supports? Would these be built-in?

**Comment by guybedford** [comment]
There are basically two main cases for RollupJS - handling these module types for externals and handling these module types for RollupJS inlining.

For all types of modules, when they are externals, the import statement just stays in the chunk just the same.

For the inlining cases:

* Wasm modules: We will have a bundle story with the module linking proposal, so that there are ways to effectively output rollup'd Wasm per chunk.
* JSON modules: It would probably make sense to just inline the JSON as JS code.
* CSS modules: Is there a story for combining multiple constructed stylesheets while retaining semantics? Otherwise they may just have to always remain externals. This is a shame as CSS imports today can do better than that by having one optimized CSS file per chunk.

It's worth noting that all of the above are already possible today - the syntax is if anything a restriction in forcing RolllupJS behaviour for inlining or errors at runtime.

Would be good to hear your thoughts on CSS chunking further.

**Comment by dasa** [comment]
> * JSON modules: It would probably make sense to just inline the JSON as JS code.

It might be better to use `JSON.parse` instead if it's 10 kB or larger according to: https://v8.dev/blog/cost-of-javascript-2019#json

**Comment by justinfagnani** [comment]
> CSS modules: Is there a story for combining multiple constructed stylesheets while retaining semantics? Otherwise they may just have to always remain externals. This is a shame as CSS imports today can do better than that by having one optimized CSS file per chunk.

The story is to transform them to JS and do explicit `new CSSStyleSheet(); sheet.replaceSync()` calls. Later the story will be WebBundles, since CSS has no native multi-file support.

> This is a shame as CSS imports today can do better than that by having one optimized CSS file per chunk.

The semantics are all wrong though. We need to be able to access each stylesheet individually, and importantly _not_ apply them to the main document. The non-standard CSS imports do not support that.

**Comment by guybedford** [comment]
> The story is to transform them to JS and do explicit new CSSStyleSheet(); sheet.replaceSync() calls

Do you mean having the stylesheet strings inline in the JS to do this? That sounds like it could work just fine actually!

Would it be worth getting a RollupJS plugin going that can do this work? @tivac has previously done a lot of work in this space as well. We don't yet have any official style / css plugin AFAICT, and there's nothing to stop this sort of workflow from becoming a standard one already now even without import assertions.

**Comment by tivac** [comment]
If it's just a straight transform of CSS to JS string as the default export that seems really trivial.

Feels like you would still want some sort of .css file outputting and bundling though for SSR/progressive enhancement workflows?

**Comment by justinfagnani** [comment]
> Do you mean having the stylesheet strings inline in the JS to do this?

Basically. The transform wouldn't export the CSS text though, just a stylesheet.

```css
p {
  color: red;
}
```

would transform to:

```js
const stylesheet = new CSSStyleSheet();

stylesheet.replaceSync(`p {
  color: red;
}`);

export default stylesheet;
```

**Comment by justinfagnani** [comment]
FYI, I just filed: https://github.com/w3c/csswg-drafts/issues/5629#issuecomment-710415765 to propose multiple stylesheets per .css file, which would address the bundling question even without Web bundles.

**Comment by daKmoR** [comment]
an acron plugin seems to be available for import assertions.
https://github.com/xtuc/acorn-import-assertions

In order to support `import data from "./data.json" assert { type: "json" };` in rollup? what would we need to do? 🤔

somehow load this acorn plugin and it should work? or are there more steps? 🤔

**Comment by guybedford** [comment]
@daKmoR just the import assertion plugin should be necessary. We could then possibly look at supporting JSON imports by default in RollupJS further perhaps just based on file extension.

**Comment by CxRes** [comment]
I am running into two issues as I try to use import assertions with dynamic imports:
1. Rollup checks for a closing bracket at the end of first argument to import(), finds a comma and throws!
2. Using the [acorn-import-assertion](https://github.com/xtuc/acorn-import-assertions) plugin throws with error (even after commenting out the close bracket check):
```sh
TypeError: Cannot read property 'bind' of undefined
    at ImportExpression.bind (file:///D:/myproj/node_modules/.pnpm/rollup@2.56.2/node_modules/rollup/dist/es/shared/rollup.js:2425:23)
```

There is also a plugin (https://github.com/calebdwilliams/rollup-plugin-import-assert) for this but that tries to interpret the import path even for dynamic and import the file while bundling (all I want to achieve is for the dynamic import statement to be left alone)!

**Comment by thepassle** [comment]
I recently spent some time to add support for import assertions and CSS/JSON modules to our application at work, I figured I'd write down the experience in case anybody is looking to do the same, and hopefully it'll help rollup in supporting them better.

I've put it in a separate gist, because it got a bit long and didnt want to pollute this issue too much.

https://gist.github.com/thepassle/d46a7cabf2dd15ba3bb43397430e182f

Most notably and relevant to this thread is that:
- Rollup will crash on the css syntax after adding the acorn plugin for import assertions, currently the only realistic option seems to be to transform the CSS to JS, which feels sort of wrong
- Rollup will transform the imports incorrectly (even after marking them as external), e.g.:

```js
import styles from './styles.css' assert { type: 'css' };
```

Always becomes:

```js
import './styles.css';
```

See the gist for more info. Hopefully it's helpful.

**Comment by mathe42** [comment]
Why not just say - as it is currently - rollup supports only js out of the box and change the resolveID hook to get an extra argument with the contents of assertion this would allow the following in plugins:

Assume style.css contains a class "red".

 ```js
import {red} from './styles.css' assert { type: 'css', module: true };
```

The proposal is not limited to a type field (that is only what other proposals currently use / need)


The resolveId hook could get the folowing type
```ts
type resolveId = (source: string, importer: string | undefined, options: {isEntry: boolean, custom?: {[plugin: string]: any}, assertions: Record<string, any>) => string | false | null | {id: string, external?: boolean | "relative" | "absolute", moduleSideEffects?: boolean | "no-treeshake" | null, syntheticNamedExports?: boolean | string | null, meta?: {[plugin: string]: any} | null}
```

this should be a small but powerfull change in the syntax. A lot of plugins could change there syntax to a specific assertion. For example the comlink-plugin you could use 
```ts
import worker from './myworker.js' assert { type: 'comlink' };
```

For rollup we don't need the `assert { type: 'json' }` as the filename contains this information. And if a user don't want the default import syntax a plugin can change that but only need to rely on the filename. So the assert syntax can be used to inform a plugin wich transforms or loader you want.

**Comment by thepassle** [comment]
> The proposal is not limited to a type field (that is only what other proposals currently use / need)

I think its a bad idea to have to adhere to custom build-time conventions/syntax to support native browser functionality. Plugins will definitely start to abuse the assertion, but I dont think it should be the default behavior.

**Comment by dmail** [comment]
> For rollup we don't need the assert { type: 'json' } as the filename contains this information

A browser understands the following and I hope rollup too one day (for now I have a super big custom plugin to allow that):

```js
import style from 'https://cdn.com/styles.css' assert { type: 'css' };
```

In that scenario code fetching the ressource still have to check the content type received from server is "text/css" as a browser would.

**Comment by justinfagnani** [comment]
> For rollup we don't need the `assert { type: 'json' }` as the filename contains this information

To match browser behavior you absolutely _do_ need the assertion. If you assume standard mime-types and someone writes:

```ts
import * as foo from 'foo.js' assert {type: 'json'};
```

Then Rollup should *fail*, since that's what the browser would do.

**Comment by dnalborczyk** [comment]
> > For rollup we don't need the `assert { type: 'json' }` as the filename contains this information
> 
> To match browser behavior you absolutely _do_ need the assertion. If you assume standard mime-types and someone writes:
> 
> ```ts
> import * as foo from 'foo.js' assert {type: 'json'};
> ```
> 
> Then Rollup should **fail**, since that's what the browser would do.

the same is _currently_ true for `node.js` (albeit `import assertions` still sitting behind a flag).

**Comment by lukastaegert** [comment]
Initial support in #4646
