### ISSUE TITLE
something wrong with circular dependency

### ISSUE THREAD

**Issue by 1o1w1** [rollup/rollup#3802]
- Rollup Version:  2.28.2
- Operating System (or Browser):  chrome 83.0.4103.106
- Node Version (if applicable):  v12.13.1
- Link to reproduction (IMPORTANT, read below):  https://repl.it/join/lxvfxyul-g15810649119

### Expected Behavior
An error will be reported after the temp.umd.js (which is in the demo) is imported
![image](https://user-images.githubusercontent.com/22697045/94762751-1e89ca80-03db-11eb-85a1-7dfc64991628.png)

### Actual Behavior
no error

**Comment by 1o1w1** [comment]
#https://github.com/rollup/plugins/issues/466#issuecomment-653022185

**Comment by 1o1w1** [comment]
https://github.com/rollup/plugins/issues/466#issuecomment-653022185
I also reported the bug to rollup/plugins

**Comment by isidrok** [comment]
You need to exclude core-js from babel itself or `@babel/preset-env` with `useBuiltins: 'usage'` will create a circular reference trying to process core-js itself:

```js
babel({
  babelHelpers: "bundled",
  extensions: [".js",".ts"],
  exclude: [/core-js/], // <--- HERE
  presets: [
    [
       "@babel/preset-env",
        {
           modules: false,
           targets: {
             browsers: ["> 1%", "last 2 versions", "ie 11"],
           },
           useBuiltIns: 'usage',
           corejs: 3.6
         },
    ],
 ],
}),
```

If your transformations also need `regenerator-runtime` or `@babel/runtime` its also a good idea to exclude them.

**Comment by 1o1w1** [comment]
@isidrok 
> You need to exclude core-js from babel or @babel/preset-env with useBuiltins: 'usage' will create a circular reference trying to process core-js itself:

In the other words, users have to provide  polyfill  by  themselves in browser environment.
If i want to include polyfill in my bundle, are there any other options available?

**Comment by isidrok** [comment]
> In the other words, users have to provide polyfill by themselves in browser environment

Thats not what I meant. Just exclude core-js from babel as I showed in the snippet. Polyfills will be correctly included.

**Comment by 1o1w1** [comment]
![image](https://user-images.githubusercontent.com/22697045/94846311-82e87080-0453-11eb-90d2-2395b27225d4.png)
i mean ,if  i direct reference the umd bundle  in browser environment  .   there is no polyfill in  bundle

**Comment by isidrok** [comment]
Did you made the changes? See line 18 of rollup.config.js https://repl.it/@g15810649119/MistyIroncladLearning It is generating the correct output.

**Comment by 1o1w1** [comment]
it  is  work !  Thanks  for your reply   
I misspelled the word 'external'

**Comment by MarvinXu** [comment]
> You need to exclude core-js from babel or `@babel/preset-env` with `useBuiltins: 'usage'` will create a circular reference trying to process core-js itself:
> 
> ```js
> babel({
>   babelHelpers: "bundled",
>   extensions: [".js",".ts"],
>   exclude: [/core-js/], // <--- HERE
>   presets: [
>     [
>        "@babel/preset-env",
>         {
>            modules: false,
>            targets: {
>              browsers: ["> 1%", "last 2 versions", "ie 11"],
>            },
>            useBuiltIns: 'usage',
>            corejs: 3.6
>          },
>     ],
>  ],
> }),
> ```
> 
> If your transformations also need `regenerator-runtime` or `@babel/runtime` its also a good idea to exclude them.

This did solve circular dependency, BUT it breaks the polyfill. Internal polyfills in core-js won't be added.
