### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined

### ISSUE THREAD

**Issue by kri7217** [rollup/rollup#3805]
![Screenshot from 2020-10-01 19-44-37](https://user-images.githubusercontent.com/20268760/94822012-d640cb80-041f-11eb-8567-a0e323c55f3a.png)

- Rollup Version: 2.0.0
- Operating System (or Browser): Ubuntu 18.04
- Node Version (if applicable): 10.16
- Link to reproduction (IMPORTANT, read below):

### Expected Behavior

PrivateKey(otps) is generate even before key$1 is defined.

### Actual Behavior

function PrivateKey(opts) {
assert_1.object(opts, 'options');
key$1.call(this, opts);

this._pubCache = undefined;
}
util__default['default'].inherits(PrivateKey, key$1);    //Here key$1 is undefined and leads to this error  **line number 24834**

var key$1 = function(){}
..........................................................................................................................................

Key$1 coming as undefined.
Above apart of the code is generated by rollup.

Error:
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
at Proxy.inherits (util.js:280:11)

**Comment by shellscape** [comment]
Thanks for using our template, but you've ignored the reproduction instructions and we cannot help you without that

**Comment by kri7217** [comment]
used rollup with config to generate a package

**Comment by shellscape** [comment]
Issues without minimal reproductions will be closed! Please provide a link to one by:
  1. Using the REPL at https://rollupjs.org/repl/, or
  2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
     (allows full use of all rollup options and plugins), or
  3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     These may take more time to triage than the other options.

----

If you cannot provide one we cannot help you, and we'll have to close your issue.

**Comment by Yalhu** [comment]
I have this problem. 
There is a warning  when rollup.
```sh
(!) Circular dependencies
node_modules/readable-stream/lib/_stream_readable.js -> node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_readable.js
node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_writable.js -> node_modules/readable-stream/lib/_stream_duplex.js

```

**Comment by wymiatacz** [comment]
Hi,
I think I reproduced the problem.
Please have a look at [repro.zip](https://github.com/rollup/rollup/files/6075589/repro.zip)
There is indeed a circular dependency between sshpk's commonjs modules.
In order to fix the problem it is enough to move "var key = Key;" in bundle.js from line 12240 at least before line 9832, where it is used.
Is there maybe some option to make rollup or its commonjs plugin work this way?

**Comment by phbernard** [comment]
I encountered this issue, probably because I had packages listed as `dependencies` in `package.json`. I moved them to `peerDependencies` and it fixed the problem.

**Comment by nmsn** [comment]
So,what caused this problem?
I meet this problem when using rollup.

**Comment by ci7lus** [comment]
If you are encountering this in jszip: https://github.com/Stuk/jszip/issues/673

**Comment by Yalhu** [comment]
Finally, I find the cause of this issue is the code `const ora = require('ora')`. If don't use `ora`, there is on problem.
But it works well via webpack.

I really don't know how to resolve it on rollup.

**Comment by milahu** [comment]
same error when bundling [snyk/nodejs-lockfile-parser](https://github.com/snyk/nodejs-lockfile-parser)

reproduce

```bash
git clone --depth 1 https://github.com/milahu/rollup-bug-demo-superCtor-undefined.git
cd rollup-bug-demo-superCtor-undefined
pnpm install
npm run build
node dist/index.js
```

<details>

bundling to format `cjs` and running `node bundle.js`

```
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type function. Received undefined
```

bundling to format `esm` and running `node bundle.mjs`

```
config.config = snyk_config_1.loadConfig(__dirname + '../..');
                                         ^
ReferenceError: __dirname is not defined in ES module scope
```

also warnings for cyclic deps

```
(!) Circular dependencies
node_modules/snyk-config/dist/nconf/nconf/common.js -> node_modules/snyk-config/dist/nconf/nconf/stores/memory.js -> node_modules/snyk-config/dist/nconf/nconf/common.js
node_modules/snyk-config/dist/nconf/nconf/common.js -> snyk-config/dist/nconf/nconf/stores/memory.js -> node_modules/snyk-config/dist/nconf/nconf/common.js?commonjs-proxy -> node_modules/snyk-config/dist/nconf/nconf/common.js
node_modules/snyk-config/dist/nconf/nconf.js -> node_modules/snyk-config/dist/nconf/nconf/provider.js -> node_modules/snyk-config/dist/nconf/nconf.js
...and 15 more
```

</details>

> But it works well via `webpack`.

i already had problems with circular dependencies in rollup, trying to bundle goldenlayout. also worked with webpack

**Comment by kzc** [comment]
https://github.com/rollup/rollup/issues/4195#issuecomment-932425498

**Comment by kri7217** [comment]
I solved the problem by rearranging the dependencies in rollup config

**Comment by kri7217** [comment]
I used rollup for bundling. In the rollup.config, there is section to
mention dependencies. I tried interchanging the items in the dependencies
array.

**Comment by lukastaegert** [comment]
We are finalizing a new version of the commonjs plugin in rollup/plugins#1038. It is pre-published as `@rollup/plugin-commonjs@beta`. Please give it a spin to see if it resolves the issue, ideally without additional config needed.

**Comment by milahu** [comment]
@lukastaegert success with https://github.com/milahu/rollup-bug-demo-superCtor-undefined

**Comment by jigz** [comment]
> We are finalizing a new version of the commonjs plugin in [rollup/plugins#1038](https://github.com/rollup/plugins/pull/1038). It is pre-published as `@rollup/plugin-commonjs@beta`. Please give it a spin to see if it resolves the issue, ideally without additional config needed.

works for me
