### ISSUE TITLE
Treat Warnings as Errors

### ISSUE THREAD

**Issue by leaanthony** [rollup/rollup#3809]
### Feature Use Case

Rollup's exit code for warnings is 0. This makes it very hard for programs externally executing rollup to detect warnings. The only option available is parsing stdout which is not very maintainable.

### Feature Proposal

Add a `treat warnings as errors` flag. When given this, any warnings will result in rollup exiting with a status that is not 0.

### Further Information

Whilst this *could* be handled using `onwarn` this puts the burden of implementing this feature on each project whilst it would be best implemented in rollup itself. There is obviously a need for this as a workaround was created in the [React](https://github.com/facebook/react/pull/12868) project.

**Comment by lukastaegert** [comment]
You mean like https://rollupjs.org/guide/en/#--failafterwarnings ?

**Comment by leaanthony** [comment]
In my defence, it does not appear in the `--help` output.

**Comment by lukastaegert** [comment]
Actually it does, but now that you mention it, it is not sorted alphabetically correctly. It appears between `--silent` and `--sourcemapExcludeSources`. I will try to fix this with the next release.
