### ISSUE TITLE
Local import and regex in external configuration

### ISSUE THREAD

**Issue by Naeoth** [rollup/rollup#3810]
- Rollup Version: 2.28.2
- Operating System (or Browser): MacOS (10.15.7)
- Node Version (if applicable): 14.8.0
- Link to reproduction (IMPORTANT, read below): https://github.com/Naeoth/rollup-issue

To avoid unresolved dependencies warning on compilation, I use a regex for the external rollup configuration to exclude all the imports which starts with "." (it means all the local import in fact).
It worked perfectly before 2.26.8 but a [change](https://github.com/rollup/rollup/pull/3753) in 2.26.8 broke the trick.
It seems that now, it's impossible to exclude the local import with a regex if you have a least a regex with `/.+/` or `/.*/`.

### Expected Behavior

Include the import like `"./..."` in the bundle with the regex in the external.

### Actual Behavior

Treat the import like `"./..."` as external module with the regex in the external.

**Comment by lukastaegert** [comment]
Is this the same as #3811 ?
