### ISSUE TITLE
Regex in external doesn't exclude local import

### ISSUE THREAD

**Issue by Naeoth** [rollup/rollup#3811]
- Rollup Version: 2.28.2
- Operating System (or Browser): MacOS (10.15.7)
- Node Version (if applicable): 14.8.0
- Link to reproduction (IMPORTANT, read below): https://github.com/Naeoth/rollup-issue

To avoid unresolved dependencies warning on compilation, I use a regex (`/^[^.].+/`) for the external rollup configuration to exclude all the imports which starts with "." (it means all the local import in fact).
It worked perfectly before 2.26.8 but a [change](https://github.com/rollup/rollup/pull/3753) in 2.26.8 broke the trick.
It seems that now, it's impossible to exclude the local import with a regex if you have a least a regex with `/.+/` or `/.*/`.

### Expected Behavior

Include the import like `"./..."` in the bundle with the regex in the external.

### Actual Behavior

Treat the import like `"./..."` as external module with the regex in the external.

**Comment by lukastaegert** [comment]
While I understand your pain, the previous behaviour was both inconsistent and contradicted what was written in the documentation. But I think there is still a way to achieve what you want.

So what happens is that when you import e.g. `./foo.js`, first the string `"./foo.js"` is checked against the regular expression. Then it is resolved to a full path, e.g. `"/Users/myself/project/foo.js"`, and checked against the regular expression again.

So what you need to do is extend your regular expression to also exclude absolute paths. On non-Windows systems, this should be as easy as

```
/^[^./].+/
```

while on Windows, you need something more involved. Another variant would be to use a function:

```js
import path from 'path';

// ...

external(id) {
  return id[0] !== '.' && !path.isAbsolute(id);
}
```

Hope this helps.

**Comment by Naeoth** [comment]
It works like a charm thank you so much ! I'm using the function variant to be compatible with all environments.
