### ISSUE TITLE
preserveEntrySignatures: exports-only

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#3820]
### Feature Use Case

`preserveEntrySignatures` is a really nice API for selecting when facades are really needed (and it turns out not so much!).

But turning on `'allow-extension'` might still cause issues for some facades where the exact names might be needed.

### Feature Proposal

The proposal is for an `exports-only` setting, which would effectively follow `'strict'` for all entry modules that have exports, but set it to `'allow-extension'` for all entry modules that have any exports.

This way the top-level "exportless" entry point always gets collapsed, but we avoid risk for other types of chunks.

**Comment by lukastaegert** [comment]
Sounds sensible and could be a good default for the next major version. Thus we could also avoid the ugly warning you get when an entry point has no exports.
