### ISSUE TITLE
Files still merged even with preserveModules 

### ISSUE THREAD

**Issue by johannes-z** [rollup/rollup#3826]
This might also be a bug, but I think `preserveModules` is working as intended...

Link to Repro: https://repl.it/repls/RunnyHumbleOolanguage

### Expected Behavior / Situation
The usecase for this is re-exporting modules, i.e. to expose internal APIs through `<package_name>/lib/X`. With `preserveModules`, the build folder should have the exact same structure, including files. 

The built folder should look like this:
```
/lib
    - /utilities
        - test.js
    - main.js
    - Test.js
```

### Actual Behavior / Situation
Files, especially ones that only re-export, get merged with the file that's importing them.

```
/lib
    - /utilities
        - test.js
    - main.js // includes Test.js export call
```

### Modification Proposal
`preserveModule` should prevent this from happening.

**Comment by lukastaegert** [comment]
What is happening is are two things
- First, Rollup will always resolve internal reexports. I.e. if module A imports `foo` from module B that reexports `foo` from module C, then in the `preserveModules` output, module A will actually import `foo` from C.
- `preserveModules` still applies tree-shaking which means here: If a module that is not an entry point does not contain any code with side-effects, then it is not rendered. A file that only contains reexports never has side-effects. This is a feature!

So if you rely on such files being present, you have two possibilities:
- Either turn off tree-shaking. Besides the `treeshake` option, you could even do this on a per-file basis by setting `moduleSideEffects` to `"no-treeshake"` e.g. in a `transform` hook. Not sure we added this feature to the user-facing `treeshake.moduleSideEffects` option as well...
- Or make the relevant file an entry point, in which case all (re)exports will be preserved

**Comment by lukastaegert** [comment]
My feeling is that making those files entry points is more likely what you actually want.

**Comment by johannes-z** [comment]
Ah I see. I initially thought `preserveModule` would preserve the source structure, and not automatically treeshake reexporting files. Thanks for clearing that up!
