### ISSUE TITLE
UMD bundle broken somewhere after 2.15.0 release

### ISSUE THREAD

**Issue by Havunen** [rollup/rollup#3829]
- Rollup Version: 2.32.1
- Operating System (or Browser): Linux, all browsers
- Node Version (if applicable): 14.14.0
- Link to reproduction (IMPORTANT, read below): https://github.com/infernojs/inferno/ 

```
npm i && npm run build
http-server
```
open examples/playground, see UMD header removes inferno global reference

In rollup 2.15.0 UMD bundle header was implemented in a way that it allowed to merge functionality into shared global variable.
After upgrading rollup to latest version it seems global variable gets overridden by empty object, breaking the code.

Originally this issue was reported to InfernoJS https://github.com/infernojs/inferno/issues/1527

Rollup options

```json
{
   "output":{
      "file": "some-inferno-package"
      "format":"umd",
      "globals":{
         "inferno":"Inferno",
         "inferno-clone-vnode":"Inferno",
         "inferno-compat":"Inferno",
         "inferno-component":"Inferno",
         "inferno-create-class":"Inferno",
         "inferno-create-element":"Inferno",
         "inferno-devtools":"Inferno.DevTools",
         "inferno-extras":"Inferno",
         "inferno-hydrate":"Inferno",
         "inferno-hyperscript":"Inferno",
         "inferno-mobx":"Inferno.Mobx",
         "inferno-redux":"Inferno.Redux",
         "inferno-router":"Inferno.Router",
         "inferno-server":"Inferno.Server",
         "inferno-shared":"Inferno",
         "inferno-test-utils":"Inferno.TestUtils",
         "inferno-vnode-flags":"Inferno"
      },
      "name":"Inferno"
   },
   "indent":true,
   "extend":true,
   "sourcemap":false
}
```

In previous version of rollup UMD header was like this:

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('inferno')) :
    typeof define === 'function' && define.amd ? define(['exports', 'inferno'], factory) :
    (global = global || self, factory(global.Inferno = global.Inferno || {}, global.Inferno));
}(this, (function (exports, inferno) { 'use strict';

// Code

    Object.defineProperty(exports, '__esModule', { value: true });

})));
```

In recent version of rollup the UMD header has changed to following, resulting inferno object getting overriden

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('inferno')) :
    typeof define === 'function' && define.amd ? define(['exports', 'inferno'], factory) :
    (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.Inferno = {}, global.Inferno));
}(this, (function (exports, inferno) { 'use strict';

    // inferno object is empty object
    // CODE

    Object.defineProperty(exports, '__esModule', { value: true });

})));

```

This feature was used to extend the library with plugins and other opt-in functionality in browser environment

like this:
```
<script src="https://unpkg.com/inferno@7.4.2/dist/inferno.js"></script>
<script src="https://unpkg.com/inferno-component@7.4.2/dist/inferno-component.js"></script>
<script src="https://unpkg.com/inferno-create-element@7.4.2/dist/inferno-create-element.js"></script>
<script src="https://unpkg.com/inferno-hyperscript@7.4.2/dist/inferno-hyperscript.js"></script>
```

### Expected Behavior

UMD should extend shared global variable

### Actual Behavior

UMD header overrides shared global variable

**Comment by shellscape** [comment]
Thank for the issue. Unfortunately you may have missed the following in our issue template for reporting bugs:

>   Please - do not - remove this template.
>   Please - do not - skip or remove parts of this template.


>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>      
>   For some bugs it this may seem like overkill but believe us, very often what seems like a
>   "clear issue" is actually specific to some details of your setup. Having a runnable
>   reproduction not only "proves" your bug to us but also allows us to spend all our effort
>   fixing the bug instead of struggling to understand your issue.

These are pretty clear. While we're more than happy to spend time to help resolve bugs, we ask that you respect our time in turn by following the instructions above. Please update your ticket accordingly and we'll be happy to help!

**Comment by shellscape** [comment]
Thank you for updating the issue ❤️

**Comment by lukastaegert** [comment]
`extend` is now an output option! Just like `indent` and `sourcemap` -> Putting all options into the `output` block should help!

**Comment by Havunen** [comment]
That was it! thanks a lot @lukastaegert  ❤️
