### ISSUE TITLE
Docs specify plugin meta data but no longer passes it via getModuleInfo()

### ISSUE THREAD

**Issue by jdalton** [rollup/rollup#3830]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [x] Not Sure?

### Please Explain in Detail...

The docs mention:
https://github.com/rollup/rollup/blob/master/docs/05-plugin-development.md#custom-module-meta-data

The ability to pass meta-data from the plugin `transform` hook is documented but `this.getModuleInfo()` no longer returns an object with a `.meta` property.

### Your Proposal for Changes

Update docs with suggested way or remove the documented functionality.

**Comment by lukastaegert** [comment]
Works perfectly for me. Please check you are using the latest version of Rollup, if it still does not work, please open a bug ticket with a working reproduction.

**Comment by jdalton** [comment]
Ah you're right. Thank you!
