### ISSUE TITLE
`assetFileNames` not worked.

### ISSUE THREAD

**Issue by underfin** [rollup/rollup#3832]
- Rollup Version:  2.32.1
- Operating System (or Browser):  mac
- Node Version (if applicable):  v12.18.3
- Link to reproduction (IMPORTANT, read below): https://github.com/underfin/rollup-assetFileNames-not-work

### Expected Behavior

The `[name].[hash].[ext]` should work and output css filename should be `1.[hash].css`

``` js
const outputOptions = {
  output: {
    dir: 'dist',
    entryFileNames: '[name].[hash].js',
    assetFileNames: '[name].[hash].[ext]'
  },
  plugins: [
    {
      generateBundle() {
        this.emitFile( {
          name: '1.css',
          type: 'asset',
          fileName: '1.css',
          source: '1'
        })
      },

    }
  ]
};
```

### Actual Behavior

output assets filename is `1.css`.

**Comment by lukastaegert** [comment]
I see you are supplying a `fileName` when emitting the asset. `fileName` always wins. The pattern is only applied if you do not supply a `fileName`.

**Comment by lukastaegert** [comment]
https://rollupjs.org/guide/en/#thisemitfileemittedfile-emittedchunk--emittedasset--string

> If a fileName is provided, it will be used unmodified as the name of the generated file, throwing an error if this causes a conflict.

**Comment by underfin** [comment]
Thanks :)
