### ISSUE TITLE
import('./index.css') is missing after packing 

### ISSUE THREAD

**Issue by Yukyi** [rollup/rollup#3837]
Rollup Version: 2.30.0
Operating System (or Browser): mac
Node Version (if applicable): v12.19.0
Link to reproduction (IMPORTANT, read below):

### Expected Behavior

`
if(true) {
  import('./index.css')
}
`
I want to introduce a CSS dynamically

I set inlineDynamicImports: true .

It's missing after packing

how can i introduce a CSS dynamically?

### Actual Behavior

The output JS file contains import（'./ index.css'）

**Comment by shellscape** [comment]
It doesn't look like you're reporting a bug, requesting a feature, or reporting a documentation issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).
