### ISSUE TITLE
suppress warnings for dynamic imports

### ISSUE THREAD

**Issue by Pomax** [rollup/rollup#3838]
### Feature Use Case

Code with [dynamic imports](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports), which by definition are already responsible for the "what if it doesn't exist" case:

```js
let fetch = globalThis.fetch;

if {!fetch) {
  import("fs")
  // dynamic imports, i.e. "import(...)" rather than "import X from Y", return a Promise
  .then(fs => {
    fetch = (url) => new Promise(
      (resolve, reject) => fs.readFile(url, (err, data) => {
        if (err) return reject(err);
        const filecontents = data.toString(`utf8`);
        resolve({ text: () => filecontents });
    );
  })
  // and a Promise should always catch rejections
  .catch(err => throw new Error(`this can't run unless the Fetch API or filesystem module is available`);
}
```

### Feature Proposal

Instead of the current warning:

```bash
input.js → stdout...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
fs (imported by input.js)
```

This should just run without any objections, as any code with dynamic imports essentially promises `rollup` that it already has code in place to deal with the "doesn't resolve" case (because if it doesn't, this code will yield an `UnhandledPromiseRejectionWarning` at parse time, or even a parse run termination)

**Comment by lukastaegert** [comment]
It is not that simple. By default, dynamic imports do have special meaning in Rollup: It means that the target of the dynamic import should be bundled into a different chunk. If the dynamic import cannot be found at compile time, then Rollup assumes this is an error on the user side and warns about it (exceptions are truly dynamic imports that contain non-string expressions, but I am not happy about Rollup not warning here at the moment as it tends to confuse userse). You can tell Rollup this is intended by using the [resolveDynamicImport](https://rollupjs.org/guide/en/#resolvedynamicimport)  hook and returning a string. This string will replace the argument of the import and also this will disable warnings for this import:

```js
() => ({
  resolveDynamicImport(specifier) {
    // This will add quotes to the specifier
    return JSON.stringify(specifier);
  }
})
```

**Comment by lukastaegert** [comment]
But looking at your example, forget my ramblings, what you need to do is mark the module as `external` in your rollup config. This is what you intend anyway, but you should make this intention known.

**Comment by lukastaegert** [comment]
https://rollupjs.org/guide/en/#external

**Comment by Pomax** [comment]
Except I don't have/want to have a rollup config. I'm just using rollup as pure CLI utility, running it with `npx rollup --no-treeshake input.js > dist/output.js`

**Comment by Pomax** [comment]
(and then of course it's up to whoever runs things with `--ignore-external` to have separate rollup tasks for each dynamic import they _do_ need rolled up)

**Comment by Pomax** [comment]
Looking at your link, it's possible that `-e` already does this, but the docs seem very unclear on this:

> When given as a command line argument, it should be a comma-separated list of IDs:
> `rollup -i src/main.js ... -e foo,bar,baz`

What are `foo,bar,baz`? (always an excellent idea to never use "foo" and "bar" but real words that refer back to previous code examples if there are any, or self-explain their use like `-e modules,to,ignore`)

**Comment by lukastaegert** [comment]
True, docs PR welcome. In the end, anything that works for the external option should work here as well, e.g. fs

**Comment by Pomax** [comment]
does that mean I'm understanding the docs correctly in thinking foo,bar,baz are the strings used in the imports?

**Comment by lukastaegert** [comment]
Yes. You can supply either the strings used in imports, or the absolute paths of the modules that would be imported if the import is resolved. Just like it is described here: https://rollupjs.org/guide/en/#external
What you cannot do from the CLI of course is supply a function.

**Comment by Pomax** [comment]
cheers. that solves my issue then - I'll see if I have time to file a docs PR but given how little free time I have atm it might be a while =(
