### ISSUE TITLE
Proposal: Register module transformation chain in ModuleInfo

### ISSUE THREAD

**Issue by umbopepato** [rollup/rollup#3856]
### Feature Use Case

Some plugins may need to know wether a module was previously transformed by specific other plugins. In my use case [`rollup-plugin-postcss-lit`](https://github.com/umbopepato/rollup-plugin-postcss-lit) should only modify modules processed by `rollup-plugin-postcss`: this is currently managed using an include/exclude filter, which requires users to duplicate some options between the two plugins (not without risk of errors). This functionality would simplify the configuration while also allowing plugins to notify the user about wrong plugin order or unmet dependencies.

### Feature Proposal

Add a `transformedBy` property to `ModuleInfo` containing an array of ids of plugins that performed a transformation on the module, in execution order.

```typescript
interface ModuleInfo {
  transformedBy: string[];
}
```

For example:

```javascript
// rollup.config.js

plugins: [
  postcss(...),
  babel(...),
  myPlugin(),
],
```

```javascript
// my-plugin.js

transform(code, id) {
  console.log(this.getModuleInfo(id));
  // Meta {
  //   ...
  //   transformedBy: ['postcss', 'babel'],
  // } 
},
```

If this would be a welcome addition, I'd be happy to open a PR 🙂

**Comment by lukastaegert** [comment]
I see your problem but I wonder if it wouldn't be better to rather use any of the existing mechanisms for inter-plugin-communication: https://rollupjs.org/guide/en/#inter-plugin-communication

More precisely, this looks like a use-case for custom module meta-data. Of course this would require a change in the postcss plugin to add this data. But on the upside, this is much more powerful and future-proof as the PostCSS plugin can add a whole plethora of meta-data here.

**Comment by umbopepato** [comment]
Sure, I thought about that but still I was curious to know whether this more "centralized" solution that doesn't require any change in plugins could be interesting for other plugins as well 🙂
I do recognize that the number of plugins with a strict inter-dependence is fairly low so if this is of no help for at least detecting errors in plugins configuration then I agree: it's probably not worth adding.
