### ISSUE TITLE
Files containing only comments are not included in the bundle

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [rollup/rollup#3858]
### Description

I have a project where I would like to split JSDoc type definitions in their own file.
That file will have nothing in it except the comments for the type definitions.
Unfortunately, if a file only consists of comments it is ignored by rollup.
I'd expect the comments to be copied over. Or is there some option param I've overseen that enables that behaviour?
Thank you

### Questions:

- Rollup Version: 2.33.1
- Operating System (or Browser): nodejs
- Node Version (if applicable): v12.18.4
- Link to reproduction (IMPORTANT, read below): https://rollupjs.org/repl/?version=2.33.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGdHlwZXMuanMnJTNCJTVDbiU1Q24lMkYqKiUyMCU0MHBhcmFtJTIwJTdCRm9vJTdEJTIwZm9vJTIwKiUyRiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAoZm9vKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coZm9vKCU1QyUyMmJhciU1QyUyMikpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnR5cGVzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRioqJTVDbiUyMColMjAlNDB0eXBlZGVmJTIwJTdCZnVuY3Rpb24lN0QlMjBGb28lNUNuJTIwKiUyMCU0MHBhcmFtJTIwJTdCc3RyaW5nJTdEJTIwYmFyJTVDbiUyMColMjAlNDByZXR1cm4lMjAlN0IqJTdEJTVDbiUyMColMkYlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIydW1kJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior
The comments from the empty file are included in the main build

### Actual Behavior
The file is ignored and the comments are also ignored

### Trials
- I tried exporting `null` that would not work either and also break my jsdoc parser.
- I tried setting `treeshake.moduleSideEffects === true` also here the comments are not included
- When I add `console.log()` to it, it will get included including all comments. It's what I have done now. But it feels very stupid :D

**Comment by lukastaegert** [comment]
`treeshake: false` should do the trick. But if you actually want tree-shaking but just not for this specific file, you need to use the plugin interface, which gives you another value for `moduleSideEffects`: "no-treeshake" https://rollupjs.org/guide/en/#transform

```
{
  name: "disable-treeshaking",
  transform(code, id) {
    if (id.endsWith('types.js')) {
      return {moduleSideEffects: 'no-treeshake'};
    } 
  }
}
```

`moduleSideEffects: true` does not help you because it just means: Do not ignore side-effects in this module. But as there are no side-effects, there is nothing to ignore.

**Comment by ThibaultJanBeyer** [comment]
Amazing, thank you a lot! 👍
