### ISSUE TITLE
Some files are not preserved when `preserveModules` is true.

### ISSUE THREAD

**Issue by 07akioni** [rollup/rollup#3865]
- Rollup Version: 2.33.1
- Operating System (or Browser): Mac, Chrome
- Node Version (if applicable): 10.22.0
- Link to reproduction (IMPORTANT, read below):
https://repl.it/@07akioni/PresentPapayawhipRatios

### Expected Behavior
`locales.js` is preserved.

### Actual Behavior
`locales.js` is not preserved.

**Comment by lukastaegert** [comment]
preserveModules still performs tree-shaking and short-circuits reexports. If you need files to be available with all their exports, make them entry points.

**Comment by 07akioni** [comment]
> preserveModules still performs tree-shaking and short-circuits reexports. If you need files to be available with all their exports, make them entry points.

Is there any method to keep the file stayed? Thanks

**Comment by lukastaegert** [comment]
Turn off tree-shaking or make them entry points
