### ISSUE TITLE
Variable assignment incorrectly pruned within catch clause

### ISSUE THREAD

**Issue by SquidDev** [rollup/rollup#3869]
- Rollup Version: 2.33.1
- Operating System (or Browser): Browser
- Node Version (if applicable): 12.3.1
- Link to reproduction (IMPORTANT, read below): [Repl link][repl]

First, a disclaimer: I didn't actually write code this horrendous. This is produced by a compiler, hence the rather ... non-conventional JS code.

The REPL example above should be relatively clear. It appears Rollup's optimiser/DCE pass is incorrectly removing a variable assignment within a `catch` clause.

### Expected Behavior
The variable assignment would not be removed. One would expect the above program to print `Oh no`.

### Actual Behavior
The variable assignment is removed, and so `result` is never assigned. The program prints `undefined`.

[repl]: http://rollupjs.org/repl/?version=2.33.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZygpJTIwJTdCJTVDbiUyMCUyMHZhciUyMHJlc3VsdCUzQiU1Q24lMjAlMjBnJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHRyeSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBicmVhayUyMGclM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTIwY2F0Y2glMjAoXyklMjAlN0IlMjAlN0QlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTNCJTVDbiUyMCUyMCU3RCU1Q24lMjAlMjB0cnklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdGhyb3clMjAlNUMlMjJPaCUyMG5vJTVDJTIyJTNCJTVDbiUyMCUyMCU3RCUyMGNhdGNoJTIwKGUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJlc3VsdCUyMCUzRCUyMGUlM0IlMjAlMkYlMkYlMjBOb3QlMjBpbiUyMHRoZSUyMGNvbXBpbGVkJTIwb3V0cHV0ISU1Q24lMjAlMjAlN0QlNUNuJTIwJTIwY29uc29sZS5sb2cocmVzdWx0KSUzQiUyMCUyRiUyRiUyMHVuZGVmaW5lZCUyQyUyMHJhdGhlciUyMHRoYW4lMjAlNUMlMjJPaCUyMG5vJTVDJTIyLiU1Q24lN0QlNUNuJTVDbmcoKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by lukastaegert** [comment]
Thanks for spotting this, this was indeed a tricky and interesting one. Fix at #3871.

**Comment by SquidDev** [comment]
Thank you for the speedy fix ❤️. I know how hard optimiser bugs can be to debug :).
