### ISSUE TITLE
timedPlugin leaves unhandled promise rejections when hook throws

### ISSUE THREAD

**Issue by gluck** [rollup/rollup#3876]
- Rollup Version: v1.31.0
- Operating System (or Browser): Linux
- Node Version (if applicable): 12
- Link to reproduction (IMPORTANT, read below): https://repl.it/@FrancoisValdy/rollup-repro#rollup.js

### Expected Behavior

As the build error is catched, no promise rejection should be left uncaught

### Actual Behavior

UnhandledPromiseRejectionWarning gets thrown/displayed

- Removing `perf: true` fixes the issue.
- The unhandled promise is [here](https://github.com/rollup/rollup/blob/0c4a5db25ce3c0b7f55390b174e0a1c9901f8d24/src/utils/timers.ts#L111), replacing this line by `result = result.then(...)` also fixes the issue, not leaving the created promise hanging. I can PR if agreed.

**Comment by lukastaegert** [comment]
Hi, sorry this issue got a little under the radar. Yes, a PR is welcome if you still want to give it a go.
