### ISSUE TITLE
Imports are not resolved from files on Win 10 network share

### ISSUE THREAD

**Issue by hmt** [rollup/rollup#3877]
- Rollup Version: 2.33.3
- Operating System (or Browser): Electron 10
- Node Version (if applicable): 12 I think it is
- Link to reproduction (IMPORTANT, read below): see code example

My Electron app uses the rollup API to compile and build Svelte components. This works well but recently it stopped working. Since this is an enterprise environment and I can't just install and reinstall the app on my own I have to report my somewhat limited findings here. I'm using a very simple rollup config file with the svelte rollup plugin that returns the bundled component. If the component uses no imports the build step works fine. If however the component uses any import from a relative file (either node_modules or any other `./other.js` file it fails silently. No error message or anything. Just nothing. This only happens when the files that are read by rollup are on a Windows 10 network share. It works ok with local files. There is also no problem with the imported file not being found. If I enter a wrong filename rollup throws an error because the import is not found. So it somehow 'sees' the file but cannot import it.

### Expected Behavior
It should compile any svelte component whether with imports or not from any location

### Actual Behavior
If there is an import it fails on woindows network shares

This works:
```
<script>let e = "world"</script>
hello {e}
```

This won't work:
```
# component.svelte
<script>import {e} from './file.js'</script>
hello {e}

# file.js
export let e = "world"
```

My config that I use for bundling is here: https://github.com/schild-report/schild.report/blob/master/src/rollup_worker.js

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a valid reproduction and we'll be happy to triage further.

**Comment by hmt** [comment]
Thank you very much for your comment. I read the issue template carefully but am not aware of any method to reproduce the bug. Is there any known way to get a test setup with windows and network shares? Do Github actions provide these? I don't have a windows machine myself so I'm very interested in getting my hands on a testing environment.

**Comment by hmt** [comment]
I debugged a little bit further. It is possible to reproduce this issue when bundling from a shared folder in Virtual Box too. I added a plugin that shows me the imported module IDs:

```js
  function myplugin () {
      moduleParsed(moduleInfo) {
        console.log('Imported Ids: ', moduleInfo.importedIds)
        return null
   }    }  }
```

When I run this plugin on the shared drive I'm getting the message:

```
TypeError: Cannot read property 'id' of undefined
```

The entry point is otherwise fine and returns the correct ID.

**Comment by shellscape** [comment]
We use GitHub actions for running Windows tests, so that could be a vid path

**Comment by hmt** [comment]
Looking a bit further the problem can be resolved if I place all .js files inside a node_modules folder. Everything then works. It only affects js imports, not .svelte files. So I assume this is related to the svelte compiler and not rollup or the svelte rollup plugin. Sorry for spamming the issue. 
Deleted the original answer because it was misleading.

**Comment by hmt** [comment]
I managed to fix the issue by running `npm init` which created a default `package.json` and an empty `node_modules` folder. After that all files resolved magically.
