### ISSUE TITLE
Warning [DEP0148] DeprecationWarning

### ISSUE THREAD

**Issue by GrosSacASac** [rollup/rollup#3890]
- Rollup Version: 2.34.0
- Operating System (or Browser): WIN10
- Node Version (if applicable): 15.2.1
- Link to reproduction (IMPORTANT, read below): https://gist.github.com/GrosSacASac/ec161cb36dea93a73f034783d860c9b5

### Expected Behavior

No Warning

### Actual Behavior

```
PS C:\XXXX\rollup-repro> node .\main.js
(node:2120) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of 
the package at C:\XXXX\rollup-repro\node_modules\rollup\package.json imported from C:\XXXX\rollup-repro\main.js.
Update this package.json to use a subpath pattern like "./dist/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a _valid_ reproduction and we'll be happy to triage further. Valid reproductions include instructions and a means to execute them. From your gist, there's no context and nothing that would help maintainers triage.

**Comment by shellscape** [comment]
Also wanted to note that odd-numbered Node versions are discouraged as they're essentially "community test, possibly unstable" and are not LTS versions.

**Comment by lukastaegert** [comment]
I think there is a reproduction gist attached that looks sufficient. But I agree with @shellscape, does the issue also manifest on latest Node 14?

**Comment by shellscape** [comment]
@lukastaegert gists aren't considered valid reproductions (if they are, we should update the templates) and there were no instructions provided as to how to reproduce.

> Valid reproductions include instructions and a means to execute them. From your gist, there's no context and nothing that would help maintainers triage.

**Comment by lukastaegert** [comment]
Maybe we should. Technically, a gist is just a special kind of repository, you could even clone it like one:

```
git clone https://gist.github.com/ec161cb36dea93a73f034783d860c9b5
```

And it is optimized for readability, which I like. The instructions in this one, `node main.js` are rather bare-bones but I think I can work with this.

**Comment by abernier** [comment]
I can also reproduce with `rollup@2.41.0` using Rollup Javascript API

```
DEP0148] DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of the package at /Users/abernier/sewan/front-ui-kit/node_modules/rollup/package.json.
```

**Comment by jwanner83** [comment]
Is there any update to this?

I still encounter this problem with `rollup@2.56.2` using the Rollup JavaScript API on Node `v16.5.0`. 
```
(node:17549) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of the package at /Users/jwa/Development/playground/liferay-npm-bundler-improved/node_modules/rollup/package.json.
Update this package.json to use a subpath pattern like "./dist/*".
```

If you guys want a reproduction template, just let me know.
