### ISSUE TITLE
imports generated by `rollupConfig.treeshake = false` may create unusable output (for rollup itself).

### ISSUE THREAD

**Issue by 07akioni** [rollup/rollup#3897]
- Rollup Version: 2.34.1
- Operating System (or Browser): Mac
- Node Version (if applicable): v12.16.1
- Link to reproduction (IMPORTANT, read below):

https://repl.it/join/wpkwnjbg-07akioni

https://github.com/07akioni/rollup-bug

### Expected Behavior

it outputs `{ a: 'a', b: [ 'b', 'a' ] }`

### Actual Behavior

it outputs `# { a: 'a', b: undefined }`

The bundled app is
```
var a = 'a';

var ab = /*#__PURE__*/Object.freeze({
	__proto__: null,
	a: a,
	b: b
});

var b = ['b', a];

console.log({ ...ab });

var preset = 'wow';

console.log(preset);
```

However `var b = ['b', a];` should come before `var ab = ...`

It is result from
```
// package/b/b.js (generated by rollup with no tree-shaking)

import a from '../a/a.js';
import '../ab.js'; // <------------ The import stmt cause the problem

var b = ['b', a];

export default b;
```

**Comment by lukastaegert** [comment]
It appears this one was fixed in #3840
