### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by cupcakearmy** [rollup/rollup#3906]
- Rollup Version: ^2.34
- Operating System (or Browser): macOS Big Sur 11.0.1
- Node Version (if applicable): 12.20.0
- Link to reproduction (IMPORTANT, read below): Not possible

Need some guidance on how to track down this bug.

So I've a little Svelte official template and for some reason it keeps breaking the heap. It's don't even a big project (max 20 Files). I have no Idea how to track down. Any kind of help would be really appreciated.

It's the official svelte template with typescript, ibm carbon and firebase.

### Actual Behavior

```
$ rollup -c

src/main.ts → public/build/bundle.js...

<--- Last few GCs --->

[5832:0x102d81000]   122990 ms: Scavenge 2038.9 (2049.9) -> 2038.2 (2049.9) MB, 6.2 / 0.0 ms  (average mu = 0.135, current mu = 0.002) allocation failure 
[5832:0x102d81000]   123000 ms: Scavenge 2039.0 (2049.9) -> 2038.7 (2050.2) MB, 6.7 / 0.0 ms  (average mu = 0.135, current mu = 0.002) allocation failure 
[5832:0x102d81000]   123013 ms: Scavenge 2039.3 (2050.2) -> 2038.8 (2050.7) MB, 6.2 / 0.0 ms  (average mu = 0.135, current mu = 0.002) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x100a02f39]
Security context: 0x23a990e808d1 <JSObject>
    1: exec [0x23a990e89a51](this=0x23a904ece1b1 <JSRegExp <String[43]: _4y829ko2km000_(?:(\d+)|(AT)|(HASH))_(\w+)?>>,0x23a918610869 <String[17]: _4y829ko2km000_1_>)
    2: leave [0x23a918610a59] [/******/node_modules/svelte/compiler.js:7271] [bytecode=0x23a9c6679521 offset=47](this=0x23a904ecdde1 <Object map = 0x23a9e3911009>,0x23a918...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1011f5195 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a5a29 node::Abort() [/usr/local/bin/node]
 3: 0x1000a5b8f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001ee277 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001ee217 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100384db5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10038660a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x10038308e v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100380e40 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10038cc6a v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10038ccf1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10035ae6a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x1006aa698 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x100a02f39 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
error Command failed with signal "SIGABRT".
```

**Comment by shellscape** [comment]
We don't offer support here, and reproductions are required for requesting triage. Please try StackOverflow, or our Discord chat (linked in the template and README) for support on issues like this.

**Comment by cupcakearmy** [comment]
@shellscape thats understandable of course. I realise it's very vague issue.

Is there any way to monitor what consumes memory in rollup?

with `node --max_old_space_size=8192 ./node_modules/.bin/rollup -c` i managed to make it work but I'm sitting around ~7gb of ram usage (~12gb virtual)

**Comment by cupcakearmy** [comment]
@shellscape thats understandable :) Can't find the discord anywhere, it it private maybe xD
I'm stuck at ~7gb ram (~12gb virtual) 😅

**Comment by cupcakearmy** [comment]
Solved it finally.

```
import { Add16 } from 'carbon-icons-svelte' // Nope
import Add16 from 'carbon-icons-svelte/lib/Add16' // Yes
```

Back to sub 500mb ram and build times in 15s 😅

**Comment by lukastaegert** [comment]
One problem is that Rollup due to its architecture can indeed use up a lot of memory if the module graph is huge. Fortunately in. my experience, Node works well if you set `--max_old_space_size` to something that far exceeds your installed memory, apparently resorting to paging. But I am glad you found a solution.

**Comment by michaelcuneo** [comment]
> Solved it finally.
> 
> ```
> import { Add16 } from 'carbon-icons-svelte' // Nope
> import Add16 from 'carbon-icons-svelte/lib/Add16' // Yes
> ```
> 
> Back to sub 500mb ram and build times in 15s 😅

I have this exact same problem with a svelte project, but I cannot see what is taking up the ram. How did you narrow yours down to the import issue?

I can't even hit save once on mine before I need to restart. It's extremely counterproductive.

**Comment by cupcakearmy** [comment]
@michaelcuneo At the end I did the good old "commend out the whole application and add it slowly back in until it breaks". So in my case i was adding components back in and the first componennt with an icon broke the bundler, so I did the same thing for that componennt and commented out everything until I noticed that with the icon it was breaking and without it did not.
Probably not the answer you were hoping for 😆 depending on the project that could be a longer endevour

**Comment by cupcakearmy** [comment]
Maybe create a repro repo and have one of the rollup people look over it? I'm really not an expert on rollup

**Comment by paranoidPhantom** [comment]
Having the same problem and made a repro: https://codesandbox.io/p/github/paranoidPhantom/school.550/dev?import=true

(`npm run build` fails)

Maybe this is a rollup issue...
