### ISSUE TITLE
`write` or `generate` cause everything to freeze

### ISSUE THREAD

**Issue by adamchipperfield** [rollup/rollup#3910]
- Rollup Version: ^2.35.1
- Operating System (or Browser): MacBook Pro 2017
- Node Version (if applicable): 12.13.1

### Expected Behavior
When I run `bundle.write` or `bundle.generate` the expected behaviour for each method occurs and the rest of the code continues.

### Actual Behavior
Everything just freezes and it seems to slow my Mac down... the terminal is still and following code just won't run because I'm awaiting on `write` or `bundle`. No files are also created when using `write`.

```javascript
await rollup.rollup(options[0])
  .then((bundle) =>
    bundle.write(
      options[0].output[0]
    )
  )
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.
