### ISSUE TITLE
Cannot find module '...

### ISSUE THREAD

**Issue by Yalhu** [rollup/rollup#3914]
- Rollup Version: 2.35.1
- Operating System (or Browser): Mac OS
- Node Version (if applicable): 10.20.1 and v12.20.0
- Link to reproduction (IMPORTANT, read below):

    "@babel/core": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@rollup/plugin-babel": "^5.2.2",
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-json": "^4.1.0",

### Expected Behavior
rollup can output a file but the file does not work well.
rollup.config.js
```js
export default {
  input: 'src/index.js',
  output: {
    dir: 'output',
    format: 'cjs',
    sourcemap: 'inline',
    exports: 'auto'
  },
  plugins: [ 
    json(),

    nodeResolve({
      jsnext: true,
      main: true,
      index: true
    }),

    commonjs({
      include: './src/**',
      exclude: 'node_modules/**',
    }),

    babel({
      babelHelpers: 'bundled',
      exclude: 'node_modules/**',
      include: ['./src/**'],
      extensions: ['.js'],
    }),
  ]
};
```
babel.config
```js
module.exports = {
  "presets": [
    ["@babel/preset-env", { 
      "modules": false,
    }]
  ],
}
```
### Actual Behavior
There is an error, when I exec `node output/index.js`
```js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './objects/separator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/tal/huyalong/Github/vli/output/index.js:2363:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I don't know how to resolve it. Thanks for your help!

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.
