### ISSUE TITLE
Rollup fails to emit nested index files with preserveModules option

### ISSUE THREAD

**Issue by peterjcaulfield** [rollup/rollup#3916]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.1.0
- Rollup Version: 2.35.1
- Operating System (or Browser): Mac OS Catalina 10.15.7
- Node Version: 12.0.0
- Link to reproduction: https://github.com/peterjcaulfield/rollup-index-issue

### Expected Behavior

Rollup used with `plugin-typescript` and `preserveModules: true` should produce same directory output as `tsc` command when used with the same `tsconfig.json`. 

It should emit a file for every `.ts` file found in the `include`-ed source.

### Actual Behavior

Rollup fails to emit nested index files only emitting a root level `index.js` for the compiled source. 

### Additional Information

In my repro repo I created two scripts. One for compiling with rollup using `plugin-typescript` and one just using `tsc`. The corresponding outputs look like this:

**source**
```
-> % tree src
src
├── component
│   ├── Button
│   │   ├── Button.ts
│   │   └── index.ts
│   └── index.ts
└── index.ts
```
2 directories, 4 files

**Rollup output via `npm run build:rollup`**

```
-> % tree dist
dist
├── component
│   └── Button
│       └── Button.js
└── index.js

2 directories, 2 files
```

**tsc output via `npm run build:typescript`**

```
-> % tree dist
dist
├── component
│   ├── Button
│   │   ├── Button.js
│   │   └── index.js
│   └── index.js
└── index.js

2 directories, 4 files
```

Seems related to:

- https://github.com/rollup/rollup/issues/2854
- https://github.com/rollup/rollup/issues/3806

**Comment by peterjcaulfield** [comment]
I created a more minimal repro without the typescript plugin (just using `.js` files) [here](https://github.com/peterjcaulfield/rollup-index-issue/tree/js-version)

**Comment by lukastaegert** [comment]
Files that are not entry points and do not have side-effects are removed by tree-shaking. If you need a file
- make it an entry point, or
- add a side-effect, or
- turn off tree-shaking

**Comment by peterjcaulfield** [comment]
Hi @lukastaegert thanks for the quick response. I'd like to retain tree-shaking for other cases if possible and the entry point option doesn't sound very ergonomic.

Can you give me a pointer on how to leverage the middle option of "add a side-effect". I had a look at `treeshake.moduleSideEffects` but this seems to work at the level of a statement as opposed to something like an index file.

Thanks

**Comment by lukastaegert** [comment]
A side-effect is calling a global function like console.log or doing something that could throw an error or some other similar things. Probably not something you want to do. If you want tree-shaking but keep this specific, I really see no way around making the file an entry point. Otherwise, what is the point of tree-shaking if it does not remove unnecessary things?

**Comment by peterjcaulfield** [comment]
"A side-effect is calling a global function like console.log or doing something that could throw an error or some other similar things."

Ah I thought you meant there was some way to tag the index files so they are treated as effectful when the treeshaking is performed by rollup. Yes unfortunately this would be even less ergonomic than rolling an entry for every index file I wish to be retained in the output.

"I really see no way around making the file an entry point."

I guess the source of dissonance here is that the Typescript compiler considers these index files as being part of the root entry as they are emitted in the final bundle whereas rollup does not. Can I ask what is the reason for that discrepancy? I think I read before somewhere in the rollup issues that relying on an index for exposing modules is hacky?

I would expect the module structure incl. index files to be maintained with something like `preserveModules`.

"Otherwise, what is the point of tree-shaking if it does not remove unnecessary things?"

I don't think in this case rollup has the context to determine if these index files are necessary as it relates to how a user will be able to import things with the generated output so from my perspective the optimisation is overly aggressive.

**Comment by lukastaegert** [comment]
The idea of Rollup's process is that the only real guarantees you get for exposed exports and created files is for your entry points. Beyond that, Rollup assumes it has freedom to optimize. If the index file is part of your external API, it should definitely be an entry point.

One last thing you can do is disable treeshaking on a per-module basis in the transform plugin hook.

But really, entry points are semantically the correct solution. Otherwise even if the file exists, there is no guarantee if all exports are rendered or if unused ones are removed.

In the worst case, you can make every file an entry point. This could also be done by a plugin that re-emits every file in the transform or load hook. But this would still very much limit what tree-shaking can achieve as then, all exports are considered as essential.

**Comment by peterjcaulfield** [comment]
> The idea of Rollup's process is that the only real guarantees you get for exposed exports and created files is for your entry points. Beyond that, Rollup assumes it has freedom to optimize. If the index file is part of your external API, it should definitely be an entry point.

Ok thanks for clarifying the semantics (and for enumerating some workarounds!). I opted to go for the entry point solution via glob:

```js
export default {
  input: glob.sync("src/?(component)/**/index.ts"),
  output: [
    {
      dir: "dist/esm",
      format: "esm",
    },
    {
      exports: "named",
      dir: "dist/cjs",
      format: "cjs",
    },
  ],
...
```

**Comment by theMasix** [comment]
@peterjcaulfield Great solution to the issue.

But I have an issue with the next step. How would you generate `.d.ts` files for these files corresponding to the new file structure?

I use `rollup-plugin-dts` but it does not create declaration files for `component/**/index.ts` (whereas creates declarations for `component/Button/Button.ts` which is imported by `component/Button/index.ts`)

My folder structure is the same as yours. and here is my rollup config:

```json
export default [
  // Build cjs and esm
  {
    input: glob.sync('src/?(components|utility|hooks)/**/index.ts'),
    output: [
      {
        dir: 'dist/node',
        format: 'cjs',
        preserveModules: true,
        preserveModulesRoot: 'src/components',
      },
      {
        dir: 'dist',
        format: 'es',
        preserveModules: true,
        preserveModulesRoot: 'src/components',
      },
    ],
    external: [
      ...Object.keys({
        ...packageJson.peerDependencies,
        ...packageJson.dependencies,
      }),
    ],
    plugins: [
      alias(pathAliasResolveConfig),
      commonjs(),
      externals(),
      resolve(),
      esbuild(),
    ],
  },
  // Build Types
  {
    input: entryPoints,
    output: [
      {
        dir: 'dist',
        format: 'es',
        preserveModules: true,
        preserveModulesRoot: 'src/components',
      },
    ],
    plugins: [
      alias(pathAliasResolveConfig),
      dts({
        compilerOptions: {
          incremental: false,
        },
      }),
    ],
  },
];

```

**Comment by NotYoojun** [comment]
I turned off tree-shake, but this problem still appears.
