### ISSUE TITLE
Circular dependencies introduced by requrie statements inside function are not handled properly

### ISSUE THREAD

**Issue by nandin-borjigin** [rollup/rollup#3917]
- Rollup Version: 2.35.1
- Operating System (or Browser): macOS Big Sur 11.1
- Node Version (if applicable): 12.20.0
- Link to reproduction (IMPORTANT, read below): https://github.com/nandin-borjigin/rollup-issue-circular-deps/

### Expected Behavior
The generated bundle should have no flaw. 
The circular dependencies should be handled properly, as there is a "loose dependency" in the circle.

_By "loose dependency" I mean a CommonJs `require` statement inside a function body, as the required variable doesn't need to be defined before the dependent in module scope._

There is a more detailed description in the reproduction repo's README.

### Actual Behavior
The circle in dependency graph causes a package to be bundled after it's "strict dependent" only to satisfy a "loose dependency" of itself.

**Comment by nandin-borjigin** [comment]
It might also involves `commonjs` plugin as `require` (import) statements in function body are actually not supported in es modules. So `commonjs` simply hoists all `require` statements to top level, breaking the "looseness" of the dependency. As rollup itself only processes es modules, this issue may need to be solved entirely by the plugin.

A quick thought is:
1. break the loose dependency by replacing in-function require statements with proper placeholder string.
2. replace placeholder strings back with correct variable references accordingly.

**Comment by lukastaegert** [comment]
Yes, it is an issue of the commonjs plugin. A PR to resolve this partially is in the works but will require more time.

**Comment by nandin-borjigin** [comment]
Closing as this is an issue of the commonjs plugin, track it here https://github.com/rollup/plugins/pull/658.
