### ISSUE TITLE
Object literals in output causing syntax errors

### ISSUE THREAD

**Issue by jbt** [rollup/rollup#3920]
- Rollup Version: 2.36.0
- Operating System (or Browser): any
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): [repl](https://rollupjs.org/repl/?version=2.36.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRmZvby5qcyclMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTVDdCU1Q24lN0QlNUNuJTVDbmZvby5wcm9wVHlwZXMlMjAlM0QlMjAlN0IlMjBmb28lM0ElMjBzb21ldGhpbmcoKSUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

I've started seeing non-tree-shakeable object literals appearing in my output as of 2.36.0 when the thing to which they were assigned is shaken away. But without the assignment, they're not interpreted as object literals and throw syntax errors.

Spotted this with `.propTypes` being applied to a React component as a default export which was being removed, but the prop types defintion was left in the output.

Seems to work fine with 2.35.1 so I guess it's related to #3919

[repl link](https://rollupjs.org/repl/?version=2.36.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRmZvby5qcyclMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTVDdCU1Q24lN0QlNUNuJTVDbmZvby5wcm9wVHlwZXMlMjAlM0QlMjAlN0IlMjBmb28lM0ElMjBzb21ldGhpbmcoKSUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

Input:

```js
export default function foo() {}

foo.propTypes = { foo: something() }
```

### Expected Behavior

If `foo` gets tree-shaken then the non-tree-shakeable definition of `propTypes` shouldn't produce invalid output.

### Actual Behavior

Output is just `{ foo: something() };` which on its own is invalid js because without the assignment it's not interpreted as an object literal

**Comment by lukastaegert** [comment]
Thanks for spotting! This was definitely an oversight on my part as this is a variation of an issue we already solved for other similar optimizations. Fix at #3921, will release once CI is clear.

**Comment by jbt** [comment]
Amazing, nice one!

**Comment by jbt** [comment]
Just tested my case with 2.36.1 and working perfectly now! Appreciate the quick fix :raised_hands:
