### ISSUE TITLE
Installing rollup displays a warning due to fsevents using old versions

### ISSUE THREAD

**Issue by stof** [rollup/rollup#3931]
- Rollup Version: 2.37.1
- Operating System (or Browser): Ubuntu
- Node Version (if applicable): 12.20.1
- Link to reproduction (IMPORTANT, read below):
    - add a dependency on `rollup`
    - run `yarn` to install it

### Expected Behavior

no warning

### Actual Behavior

The `fsevents` optional dependency displays a warning:

```
rollup > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
```

It would be great if the constraint could be updated to avoid such warning.

**Comment by lukastaegert** [comment]
It turns out there is a bug in latest `fsevents`, which is why we did not yet upgrade. I will keep a close eye on fsevents/fsevents#355
