### ISSUE TITLE
sourcemaps passed from non-js assets seem to be ignored 

### ISSUE THREAD

**Issue by CxRes** [rollup/rollup#3938]
- Rollup Version: 2.38.0
- Operating System (or Browser): Windows 10 x64 (though irrelevant)
- Node Version (if applicable): 14.15.4 (though irrelevant)
- Link to reproduction (IMPORTANT, read below): https://repl.it/@CxRes/no-css-sourcemap

It seems that for a non-css source the sourcemap passed as return value of the transform plugin is ignored. We are observing this in [rollup-plugin-styles](https://github.com/Anidetrix/rollup-plugin-styles) where the generated css sourcemap that is passed is just ignored as can be seen in the reproduction. The relevant code lines are [linked here](https://github.com/Anidetrix/rollup-plugin-styles/blob/caff61f6aa32948571eb83a136ac13bd5637ca6e/src/index.ts#L118). Also, please refer to my discussion with the author @Anidetrix [here](https://github.com/Anidetrix/rollup-plugin-styles/issues/160#issuecomment-766811562). 

The author of this plugin @Anidetrix is forced to add the sourcemap directly to the css string bundled in the js output file as a string. But this puts sourcemaps in two places and is extremely ugly. Ideally all sources, js or not, should be in the same map file.

### Expected Behavior

The sourcemap for the CSS should be passed along the build pipeline and included in the generated sourcemap

### Actual Behavior

Missing css source in sourcemap.

PS: I have tried passing the code part only ie without the sourcemap added to the code, unlike what the plugin author does. It makes no difference!

**Comment by lukastaegert** [comment]
I can confirm that #4334 seems to fix this issue for me by including the CSS source.
