### ISSUE TITLE
The order of loading module is changed

### ISSUE THREAD

**Issue by eight04** [rollup/rollup#3958]
- Rollup Version: 2.38.5
- Operating System (or Browser): Windows 10
- Node Version (if applicable): 15.5.1
- Link to reproduction (IMPORTANT, read below):

rollup@2.38.5
https://rollupjs.org/repl/?version=2.38.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAlNUMlMjIuJTJGcHJlZi5qcyU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2coZm9vKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZm9vJTIwZnJvbSUyMCU1QyUyMi4lMkZwcmVmLmpzJTVDJTIyJTNCJTVDbmNvbnNvbGUubG9nKGZvbyklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHBvbHklMjBmcm9tJTIwJTVDJTIyLiUyRnBvbHlmaWxsLmpzJTVDJTIyJTNCJTVDbmNvbnNvbGUubG9nKHBvbHkpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIycHJlZi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBwb2x5JTIwZnJvbSUyMCU1QyUyMi4lMkZwb2x5ZmlsbC5qcyU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMHBvbHklMjAlMkIlMjAxJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnBvbHlmaWxsLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAxJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

rollup@2.32.1
https://rollupjs.org/repl/?version=2.32.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAlNUMlMjIuJTJGcHJlZi5qcyU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2coZm9vKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZm9vJTIwZnJvbSUyMCU1QyUyMi4lMkZwcmVmLmpzJTVDJTIyJTNCJTVDbmNvbnNvbGUubG9nKGZvbyklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHBvbHklMjBmcm9tJTIwJTVDJTIyLiUyRnBvbHlmaWxsLmpzJTVDJTIyJTNCJTVDbmNvbnNvbGUubG9nKHBvbHkpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIycHJlZi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBwb2x5JTIwZnJvbSUyMCU1QyUyMi4lMkZwb2x5ZmlsbC5qcyU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMHBvbHklMjAlMkIlMjAxJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnBvbHlmaWxsLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAxJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior
`polyfill.js` should be loaded first.

### Actual Behavior
With rollup@2.38.5, `polyfill.js` is loaded after `pref.js`

rollup@2.32.1 works fine.

IDK if this change is intentional. This affect multi-chunk IIFE builds (rollup-plugin-iife) that relies on the import order (`ChunkInfo.imports`) to inject IIFE scripts. I got a `polyfill is undefined` error when loading `pref.js` after upgrading rollup to the latest version.

**Comment by lukastaegert** [comment]
Is this actually breaking anything? If I read the code correctly, polyfill is still loaded and executed before pref because the pref chunk has a dependency on the polyfill file. It is just written differently in the code. This change was introduced to improve behaviour in the presence of circular dependencies.

**Comment by lukastaegert** [comment]
Basically, Rollup is following the import order as written in the modules as much as possible and adds hoisted transitive dependencies at the end now. Of course that means that an IIFE plugin would need to manually determine the actual execution order now by looking at the dependency graph.
