### ISSUE TITLE
Actually used unnecessarily

### ISSUE THREAD

**Issue by akauppi** [rollup/rollup#3963]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

I spotted this:

>When providing a function, it is actually called with three parameters

I feel the "actually" is extraneous, and can be removed. 

There is a trend of overuse of "actually" as a filler word. This is especially prevalent in spoken US English and Youtube has *lots* of it.

This is the first time I see it in IT documentation and I *wish* that Rollup can withhold the temptation and not start using filler words.

### Your Proposal for Changes

Remove the "actually".
Check how many similar cases there are in Rollup docs.

**Comment by lukastaegert** [comment]
PR welcome
