### ISSUE TITLE
How to debug Rollup build output with a massive encoding log?

### ISSUE THREAD

**Issue by frantic0** [rollup/rollup#3965]
- Rollup Version: **^2.36.1**
- Operating System (or Browser): **Mac OS High Sierra (Chrome Version 88.0.4324.182 (Official Build) (x86_64))**
- Node Version (if applicable): **v12.18.0**
- Link to reproduction (IMPORTANT, read below): [https://github.com/frantic0/sema-engine-rollup](https://github.com/frantic0/sema-engine-rollup)

I recently built a library with Rollup that has a few non-usual bits. That includes, for instance, loading up a wasm module, workers with importScripts and a few occurences of eval() in the global scope.

Now I used the rollup-starter-app to create a demonstrator and client app for that library. The repo is [https://github.com/frantic0/sema-engine-rollup](https://github.com/frantic0/sema-engine-rollup)

I managed to get everything working, after hitting a few walls and adding the following rollup plugins

```
import { wasm } from "@rollup/plugin-wasm";
import workerLoader from "rollup-plugin-web-worker-loader";
import dynamicImportVars from "@rollup/plugin-dynamic-import-vars";
import copy from "rollup-plugin-copy";
```

### Expected Behavior

Having a clean build without errors or at least being able to parse through the build output to find the origin of the error.

### Actual Behavior

In the build output, I'm getting this massive log of what seems to be some encoding...

[https://i.stack.imgur.com/5dG97.jpg](https://i.stack.imgur.com/5dG97.jpg)

I'm not sure where this log is coming from and it is so massive that it clears out all the information of the build in the terminal...

What is the best way to tackle this issue and how to debug it effectively?

**Comment by lukastaegert** [comment]
You could redirect stderr into a file to read the log.

**Comment by frantic0** [comment]
thank you @lukastaegert 

I'm not sure if I should close the issue here and open a new issue, please do let me know.

I redirected stderr into this file on repo [err.log](https://github.com/frantic0/sema-engine-rollup/edit/main/err.log) 

Basically the file has this content

```
rollup v2.39.0
bundles src/main.js → public...
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules/sema-engine/sema-engine.mjs
1:

2:
```

where 1:  seems to contain a string with the bundle, minified, and 2: a base64-encoded string (sourceMappingURL) 

I'm not sure of what to make of this... Is this error caused by the use of eval?

**Comment by lukastaegert** [comment]
This is just a warning, not an error. We should probably format the code sample a bit better. Otherwise, it says your output was created successfully.

**Comment by frantic0** [comment]
is there a way to prevent these huge strings from printing out and obscuring other warnings and build info?

I tried `rollup -c -w --silent` to no effect...

**Comment by frantic0** [comment]
closing this issue with solution "rollup -cw 2>err.log 1>out.log" to be able to understand how to debug the build log
