### ISSUE TITLE
"error.stack;" expression removed by tree-shaker, breaks bindings

### ISSUE THREAD

**Issue by mildsunrise** [rollup/rollup#3974]
- Rollup Version: 2.39.1
- Operating System (or Browser): Node
- Node Version (if applicable):
- [Link to reproduction](https://rollupjs.org/repl/?version=2.39.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyMCUyMGxldCUyMHBzdENhbGxlZCUyMCUzRCUyMGZhbHNlJTVDbiUyMCUyMEVycm9yLnByZXBhcmVTdGFja1RyYWNlJTIwJTNEJTIwZnVuY3Rpb24oZSUyQyUyMHN0KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBwc3RDYWxsZWQlMjAlM0QlMjB0cnVlJTVDbiUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwY29uc3QlMjBkdW1teSUyMCUzRCUyMCU3QiU3RCU1Q24lNUN0JTJGJTJGJTIwcnVuJTIwdGhlJTIwJ3ByZXBhcmVTdGFja1RyYWNlJyUyMGZ1bmN0aW9uJTIwYWJvdmUlNUNuJTIwJTIwRXJyb3IuY2FwdHVyZVN0YWNrVHJhY2UoZHVtbXkpJTNCJTVDbiUyMCUyMGR1bW15LnN0YWNrJTNCJTVDbiU1Q24lMjAlMjBjb25zb2xlLmxvZyhwc3RDYWxsZWQpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

### Expected Behavior

The `dummy.stack;` line is not removed.

### Actual Behavior

The `dummy.stack;` line is removed.

Accessing `stack` is necessary for the `prepareStackTrace` function to be called. Removing it breaks the [`bindings`](https://github.com/TooTallNate/node-bindings/blob/c8033dcfc04c34397384e23f7399a30e6c13830d/bindings.js#L172) package. (I'm not sure that the tree-shaker can be smart enough to detect the side-effect here, but the documentation asked to file an issue, and I didn't find an existing one, so I did)

**Comment by kzc** [comment]
Odd API. Who knew?

* https://v8.dev/docs/stack-trace-api#customizing-stack-traces
* https://nodejs.org/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt

I guess all `stack` property reads have to be registered as having side effects.

**Comment by kzc** [comment]
This is notable:

https://v8.dev/docs/stack-trace-api#compatibility

Compatibility

The API described here is specific to V8 and is not supported by any other JavaScript implementations. Most implementations do provide an error.stack property but the format of the stack trace is likely to be different from the format described here.

**Comment by mildsunrise** [comment]
yes, everything regarding stack traces is probably implementation dependent... if you think this is out of scope feel free to close, I just wanted to let you know

**Comment by mildsunrise** [comment]
for context: even if implementation dependent, this API seems to be important in the ecosystem; so much that we explicitly preserved its behavior when source maps are present (nodejs/node#31143)

**Comment by kzc** [comment]
It's not my call, but I'm not against supporting this if it's widely used - even though property reads with side effects are an anti-pattern. It would be relatively easy to add a side effect for all `stack` property reads. It would be more difficult to isolate non-error related `stack` property reads.

**Comment by kzc** [comment]
This patch retains all `stack` property accesses:

```patch
--- a/src/ast/nodes/MemberExpression.ts
+++ b/src/ast/nodes/MemberExpression.ts
@@ -71,4 +71,16 @@ function getStringFromPath(path: PathWithPositions): string {
 }
 
+// properties with read side effects - there's only one now
+const properyEffects = {
+       __proto__: null,
+       stack: true
+};
+
+function propertyReadHasEffects(property: any) {
+       if (property.type == 'Literal' && property.value in properyEffects) return true;
+       if (property.type == 'Identifier' && property.name in properyEffects) return true;
+       return false;
+}
+
 export default class MemberExpression extends NodeBase implements DeoptimizableEntity {
        computed!: boolean;
@@ -174,4 +186,5 @@ export default class MemberExpression extends NodeBase implements DeoptimizableE
        hasEffects(context: HasEffectsContext): boolean {
                return (
+                       propertyReadHasEffects(this.property) ||
                        this.property.hasEffects(context) ||
                        this.object.hasEffects(context) ||
```

With patch:
```
$ echo 'var o={}; o.foo; o["foo"]; o.stack;' | rollup --silent
var o={}; o.stack;
```
```
$ echo 'var o={}; o.foo; o["foo"]; o["stack"];' | rollup --silent
var o={}; o["stack"];
```

**Comment by kzc** [comment]
`--treeshake.propertyReadSideEffects=always` can now be used as a workaround for tree shaking with getters with side effects.

**Comment by mildsunrise** [comment]
sorry about not replying, and thank you for patching this :blush:
