### ISSUE TITLE
sourceMapping comments are not stripped if plugin parses the ast

### ISSUE THREAD

**Issue by yannayl** [rollup/rollup#3982]
- Rollup Version: 2.40.0
- Operating System (or Browser): any
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): https://repl.it/@yannayl/rollup-repro-plugin-parse-ast-not-remove-sourcemapping

### Expected Behavior
A plugin which calls `this.parse` (i.e. hooking `load` or `transform`) and doesn't modify anything should not affect the output.

### Actual Behavior
If a plugin calls `this.parse` rollup does not remove the sourceMappping comment from the module.

### Root Cause
Accounting for sourceMappingURL comments happens in the [`Module.setSource` function](https://github.com/rollup/rollup/blob/a12ec5b1125020c6509fb38a8b9218eea1301cc4/src/Module.ts#L728) in conjunction with the `tryParse` function in the same file. However, this function is not called if `ast` already exists.

This issue is related to  #3979

**Comment by yannayl** [comment]
I think that this logic can be simply implemented with simple regex search on the code, without using the AST parser. I don't think it will impact performance in a significant way (if this is of importance) because the code is already live in memory (and very recently cached) the regex is simple and the number of hits should be once at most.

Not using the ast parser will decouple this logic from the AST parsing and resolve the issue.

**Comment by yannayl** [comment]
Improved idea find comment candidates for removal with regex and verify they aren't part of any ast node.
this might degrade performance though, as we walk the ast for that once more. Not sure if significant...

**Comment by lukastaegert** [comment]
Thinking about this idea:
source mapping comments are meant to be top-level. So what you have to do is iterate over the top-level statements and see if one contains the comment. And if you are crazy and want to optimise performance for large files: top-level statements are ordered. So you could actually do a binary search within the top-level statements to find if there is an overlap, and this should be quite fast. The question is if one would want to go that way, though.

**Comment by lukastaegert** [comment]
On the other hand, if we parse the ast ourselves we could still reuse the old logic, and this would be a quite common scenario. I guess in the end it boils down to a question of performance vs. implementation complexity.

**Comment by yannayl** [comment]
fixed by #3987
