### ISSUE TITLE
How do I define globals for import multiple exports from module?

### ISSUE THREAD

**Issue by amitpareek49** [rollup/rollup#3991]
I am trying to import exports from a npm module. How do I define globals in the rollup configuration file?

For eg. I want to import two variables from a single module so that I can leverage the benefits of tree shaking.

import {foo, bar} from 'abc';

Any guidance will be really appreciated.

**Comment by akauppi** [comment]
I can probably help you, but the question description is not very clear.

**Comment by shellscape** [comment]
>   👉🏽 Need help or tech support? Please don't open an issue!
>   Head to https://is.gd/rollup_chat or https://stackoverflow.com/questions/tagged/rollupjs
