### ISSUE TITLE
Set base URL of dynamically loaded modules

### ISSUE THREAD

**Issue by kim366** [rollup/rollup#3992]
### Feature Use Case
An SPA with prerendered routes, such as `/`, `/login`, etc. Currently, when bundling all dynamic `import()` statements in the bundle have a relative path beginning with `.`. This is an issue, since for `/login` it will load `/login/loaded-chunk[hash].js`. 

### Feature Proposal
It should be possible to set the base URL of loaded modules. Setting this to `/` would solve the above issue. It may also be useful when the entire website is hosted on another route, such as `/forum`.

PS: In case this already is a feature, the documentation should be improved on this topic, since after extensive research, I have not found a solution.

**Comment by kim366** [comment]
I just saw you had a neat REPL, so here's an example. Notice how the module is loaded with a `.` in front: https://rollupjs.org/repl/?version=2.40.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmFzeW5jJTIwZnVuY3Rpb24lMjBmKCklMjAlN0IlNUNuJTVDdCU1Q3Rjb25zb2xlLmxvZyhhd2FpdCUyMGltcG9ydCgnLiUyRm1vZHVsZV8xLmpzJykuZGVmYXVsdCklM0IlNUNuJTdEJTVDbiU1Q25mKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJjb25zb2xlLmxvZygnYWJjJyklNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAzJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q%3D

**Comment by kim366** [comment]
I published a plugin for this: https://github.com/kim366/rollup-plugin-base-url

**Comment by shellscape** [comment]
Please consider adding this plugin to rollup/awesome

**Comment by kim366** [comment]
Thanks for the hint. It's

> If you just created something, wait at least 30 days before submitting

though, so I'll wait :)
