### ISSUE TITLE
Invalid build if `chunkFileName` has wrong path segment separator for OS

### ISSUE THREAD

**Issue by jacksteamdev** [rollup/rollup#3993]
- Rollup Version: ^2.41.2
- Operating System (or Browser): Linux Mint 19.3 Cinnamon and Windows 10
- Node Version (if applicable): v14.15.1
- Link to reproduction (IMPORTANT, read below): https://repl.it/join/mumhzhkb-jacksteamdev

### Expected Behavior

When the [wrong path segment separator](https://nodejs.org/api/path.html#path_path_sep) for the OS is used for `output.chunkFileNames` to put chunks in a subfolder, Rollup should error or generate a working bundle.

An alternative solution would be to change the docs to suggest using `path.join('chunks','[name]-[hash].js')`, instead of a forward slash.

### Actual Behavior

Rollup outputs an invalid bundle if the POSIX separator is used on Windows. The chunks are not put into a folder, but rather the intended folder name is literally in the file name. The import paths have the intended structure, but those files do not exist.

I used an [escaped backslash in the REPL](https://replit.com/@jacksteamdev/rollup-repro#rollup.config.js) to demonstrate the problem. The behavior is the same on Windows with a forward slash or on POSIX with a backslash.

This is a problem on shared boilerplates. Related issue: https://github.com/extend-chrome/js-react-boilerplate/issues/2

**Comment by lukastaegert** [comment]
Actually the intention was to always use forward slashes in the bundle object on all environments to have consistent bundle objects across environments. Until now I always assumed that `fs.writeFile` would work correctly on Windows (actually I just tried it in a Windows REPL and `fs.mkdirSync` and `fs.writeFileSync` handle forward slashes correctly). So I wonder what the actual issue is.

**Comment by jacksteamdev** [comment]
> Actually the intention was to always use forward slashes

Weird, right? If `fs` can actually handle any slash, then the problem is not a Rollup problem, but maybe a Node regression?

@lukastaegert Just curious, what Windows REPL did you use? (I don't have a Windows computer for development).
