### ISSUE TITLE
Invalid code when accessing `.default` on a namespace import from external dependency

### ISSUE THREAD

**Issue by nicolo-ribaudo** [rollup/rollup#3996]
- Rollup Version: 2.40.0
- Operating System (or Browser): not relevant
- Node Version (if applicable): not relevant
- Link to reproduction: [repl](https://rollupjs.org/repl/?version=2.41.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGRlcCUyMGZyb20lMjAlNUMlMjJkZXAlNUMlMjIlM0IlNUNuJTVDbmNvbnNvbGUubG9nKCU1QyUyMkhhcyUyMGRlZmF1bHQlM0YlNUMlMjIlMkMlMjAhIWRlcC5kZWZhdWx0KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

When getting `.default` from a namespace import, if the imported module doesn't have a default export it should return `undefined`.

The input code in the repl example should be left as-is:
```js
import * as dep from "dep";

console.log("Has default?", !!dep.default);
```

### Actual Behavior

It produces invalid code, generating a default import statement which throws at runtime if the dependency doesn't have a `default` export.

If the dependency is internal (bundled), Rollup warns but correctly generates `undefined` in the output code: [repl](https://rollupjs.org/repl/?version=2.41.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGRlcCUyMGZyb20lMjAlNUMlMjIuJTJGZGVwJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglNUMlMjJIYXMlMjBkZWZhdWx0JTNGJTVDJTIyJTJDJTIwISFkZXAuZGVmYXVsdCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJkZXAuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjB4JTIwJTNEJTIwMiUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by lukastaegert** [comment]
This is actually a very good point. I created a fix at #3999 that will change the behaviour in so far as external namespace members will be kept as property accesses and no longer replaced by named imports as this DOES indeed fundamentally change behaviour in case an export (including the default) does not exist as it would replace a possible runtime error with a certain parse-time error.

**Comment by lukastaegert** [comment]
Here is the fix in the REPL: https://rollupjs.org/repl/?circleci=14551&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGRlcCUyMGZyb20lMjAlNUMlMjJkZXAlNUMlMjIlM0IlNUNuJTVDbmNvbnNvbGUubG9nKCU1QyUyMkhhcyUyMGRlZmF1bHQlM0YlNUMlMjIlMkMlMjAhIWRlcC5kZWZhdWx0KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by lukastaegert** [comment]
One disadvantage is that for formats like CJS, you now always get the external namespace helper, but I think we can live with that.

**Comment by nicolo-ribaudo** [comment]
Yeah I don't think this is a common case and, if I use `import * as x`, I wouldn't be surprised to see the namespace helper (even if it might actually be unnecessary).

**Comment by stefcameron** [comment]
This is causing problems for me now, see comment on the PR: https://github.com/rollup/rollup/pull/3999#issuecomment-800668747
