### ISSUE TITLE
Incorrect optimization of empty object destructuring in function parameters

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#3997]
- Rollup Version: 2.41.2
- Operating System (or Browser): REPL in Browser
- Node Version (if applicable): n/a
- Link to reproduction (IMPORTANT, read below):

https://rollupjs.org/repl/?version=2.41.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm9vKCU3QiU3RCklMjAlN0IlNUNuJTVDdGJhcigpJTNCJTVDbiU3RCU1Q24lNUNuZm9vKCU3QiU3RCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

input:

```js
function foo({}) {
	bar();
}

foo({});
```

output:

```js
function foo({}) {
	bar();
}

foo();
```

### Expected Behavior

If `{}` is going to be removed where we call `foo`, it should also be removed where `foo` is defined.

### Actual Behavior

`{}` is optimized away in call of `foo` but not in definition of `foo`, leading to a runtime exception.

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #3998.
