### ISSUE TITLE
Tree shaking: pure function not detected with optional chaining

### ISSUE THREAD

**Issue by laurentpayot** [rollup/rollup#4006]
- Rollup Version: 2.42.2
- Operating System: Ubuntu 20.10
- Node Version: 15.11
- Link to reproduction :

  - [Tree-shaking not working with optional chaining](https://rollupjs.org/repl/?version=2.42.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRm15TGliLmpzJyU1Q24lNUNuY29uc29sZS5sb2coZm9vKCkpJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm15TGliLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVDJTIyZm9vJTVDJTIyJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBiYXIlMjAlM0QlNUNuJTVDdCU1Q3QlMkYlMkYlMjB0cmVlJTIwc2hha2luZyUyME5PVCUyMFdPUktJTkclMjB3aXRoJTIwb3B0aW9uYWwlMjBjaGFpbmluZyUzQSU1Q24lNUN0JTVDdCUyRiolNDBfX1BVUkVfXyolMkZnbG9iYWxUaGlzLmN1c3RvbUVsZW1lbnRzJTNGLmRlZmluZSgnbXktY3VzdG9tLWVsZW1lbnQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNsYXNzJTIwZXh0ZW5kcyUyMEhUTUxFbGVtZW50JTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbnN0cnVjdG9yKCklMjAlN0IlMjBzdXBlcigpJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbm5lY3RlZENhbGxiYWNrKCklMjAlN0IlMjB0aGlzLm15Q3VzdG9tRWxlbWVudCgpJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGF0dHJpYnV0ZUNoYW5nZWRDYWxsYmFjaygpJTIwJTdCJTIwdGhpcy5teUN1c3RvbUVsZW1lbnQoKSUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBzdGF0aWMlMjBnZXQlMjBvYnNlcnZlZEF0dHJpYnV0ZXMoKSUyMCU3QiUyMHJldHVybiUyMCU1QidiYXInJTVEJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG15Q3VzdG9tRWxlbWVudCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRoaXMuaW5uZXJIVE1MJTIwJTNEJTIwdGhpcy5nZXRBdHRyaWJ1dGUoJ2JhcicpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwKSUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)
  - [Tree-shaking working _without_ optional chaining](https://rollupjs.org/repl/?version=2.42.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRm15TGliLmpzJyU1Q24lNUNuY29uc29sZS5sb2coZm9vKCkpJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm15TGliLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVDJTIyZm9vJTVDJTIyJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBiYXIlMjAlM0QlNUNuJTVDdCU1Q3QlMkYlMkYlMjB0cmVlLXNoYWtpbmclMjBXT1JLSU5HJTIwd2l0aG91dCUyMG9wdGlvbmFsJTIwY2hhaW5pbmclM0ElNUNuJTIwJTIwJTIwJTIwZ2xvYmFsVGhpcy5jdXN0b21FbGVtZW50cyUyMCUyNiUyNiUyMCUyRiolNDBfX1BVUkVfXyolMkZjdXN0b21FbGVtZW50cy5kZWZpbmUoJ215LWN1c3RvbS1lbGVtZW50JyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjbGFzcyUyMGV4dGVuZHMlMjBIVE1MRWxlbWVudCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zdHJ1Y3RvcigpJTIwJTdCJTIwc3VwZXIoKSUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25uZWN0ZWRDYWxsYmFjaygpJTIwJTdCJTIwdGhpcy5teUN1c3RvbUVsZW1lbnQoKSUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBhdHRyaWJ1dGVDaGFuZ2VkQ2FsbGJhY2soKSUyMCU3QiUyMHRoaXMubXlDdXN0b21FbGVtZW50KCklMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwc3RhdGljJTIwZ2V0JTIwb2JzZXJ2ZWRBdHRyaWJ1dGVzKCklMjAlN0IlMjByZXR1cm4lMjAlNUInYmFyJyU1RCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBteUN1c3RvbUVsZW1lbnQoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0aGlzLmlubmVySFRNTCUyMCUzRCUyMHRoaXMuZ2V0QXR0cmlidXRlKCdiYXInKSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCklMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
 

### Expected Behavior

In the REPL, `myLib.js` can be used in the browser, or in NodeJS (no usage of the `bar` custom element).

In NodeJS, where `bar` is never imported, `bar` should not be included in the bundle.

### Actual Behavior

When using optional chaining, `bar` is included in the bundle even if not imported.

Related to https://github.com/rollup/rollup/issues/3469?

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #4007
