### ISSUE TITLE
Support recommendations for plugins rollup v1 vs v2

### ISSUE THREAD

**Issue by btd** [rollup/rollup#4008]
Hi, i would like to ask get your opinion about supported rollup versions.
According to NPM download stats there are 1m downloads for rollup v1.32. It is quite huge. I am maintaining plugin for rollup and thinking about deprecating v1 of rollup. 
So i would like to get some sort of official statement like 'we do not support v1 anymore'?

**Comment by lukastaegert** [comment]
We are not planning to backport patches to Rollup 1 as we do not have the resources for it and the upgrade path is rather straightforward.

**Comment by btd** [comment]
Thank
