### ISSUE TITLE
Value tracking through ObjectExpression nodes doesn't handle __proto__ properly

### ISSUE THREAD

**Issue by marijnh** [rollup/rollup#4014]
- Rollup Version: current master
- Operating System (or Browser): Linux
- Node Version (if applicable): 15.5
- Link to reproduction (IMPORTANT, read below): https://605c3fa99677b800085f7f45--rollup.netlify.app/repl/?version=2.42.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmxldCUyMHklMjAlM0QlMjAlN0Jmb28lM0ElMjB0cnVlJTdEJTVDbmxldCUyMHglMjAlM0QlMjAlN0JfX3Byb3RvX18lM0ElMjB5JTdEJTVDbmlmJTIwKHguZm9vKSUyMGNvbnNvbGUubG9nKCU1QyUyMiElNUMlMjIpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

```
let y = {foo: true}
let x = {__proto__: y}
if (x.foo) console.log("!")
```

Rollup reduces that to an empty chunk, assuming that since `x` doesn't have a `foo` property, `x.foo` must produce undefined (second return from `ObjectExpression.getLiteralValueAtPath`).

### Expected Behavior

That code will log `"!"` when ran normally, so I'd expect Rollup to preserve the `console.log` call.

### Actual Behavior

The call is optimized out.

Noticed this when reading the code in ObjectExpression.ts for #3989. I suspect the easiest solution would be to just deoptimize if there's a `__proto__` property.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

There are two other options available to you. Situations like these are why we have multiple options. Please choose one, add a reproduction and we'll be happy to triage further.

**Comment by marijnh** [comment]
Oh, christ, are you a bot or did you just not even bother to read the text of the report?

@lukastaegert Please reopen this.

**Comment by shellscape** [comment]
I'm not a bot, and I acknowledged that you're having difficulty with the REPL as it's not responding. There are two other options for providing reproductions. We ask this of _everyone_, even maintainers.

Please consider this a warning according to our Code of Conduct (https://github.com/rollup/rollup/blob/master/CODE_OF_CONDUCT.md#our-standards), as your reply was both disrespectful and derogatory.

**Comment by marijnh** [comment]
The reproduction case is _in_ the issue. It's a three-liner and I explain what current Rollup does with it. If you're going to be this hostile to contribution then, really, I will stop bothering.

**Comment by lukastaegert** [comment]
Please everyone calm down. At the moment, @marijnh is really doing great work for Rollup core and I understand that it is a pain. The Rollup REPL is quite a bit easier to handle than repl.it. Note that there is actually already a related issue about this, but it is very old: https://github.com/rollup/rollup/issues/2219#issue-326529739
This one is about assignment to __proto__, which is also unhandled.
I think your suggestion is sane and should be easy to implement. We might also fix the other issue at the same time by adding special handling for __proto__ assignments at ObjectExpression (indirect assignments should already be handled as in such a case, we reassign all properties anyway).

**Comment by lukastaegert** [comment]
Added a reproduction using the direct link of the deployed REPL. Not sure what is wrong between Netlify and CloudFlare today.
