### ISSUE TITLE
Assignments to side-effecting getters in class prototypes can be incorrectly tree-shaken

### ISSUE THREAD

**Issue by marijnh** [rollup/rollup#4016]
- Rollup Version: 2.42.4
- Operating System (or Browser): Any
- Node Version (if applicable): Any
- Link to reproduction (IMPORTANT, read below): [link](https://605c3fa99677b800085f7f45--rollup.netlify.app/repl/?version=2.42.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMGdldCUyMGJhcigpJTIwJTdCJTIwY29uc29sZS5sb2coJTVDJTIyV09PJTVDJTIyKSUyMCU3RCU1Q24lN0QlNUNuRm9vLnByb3RvdHlwZS5iYXIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

### Expected Behavior

The code should exhibit a side effect (running `console.log`).

### Actual Behavior

Rollup removes the entire program and emits an empty chunk.

This is caused by `ClassNode.hasEffectsWhenAccessedAtPath` being too liberal, but I expect just tightening that up the obvious way will cause significant regressions in tree-shaking on some code. We may have to start tracking class instance properties to properly fix this without regressing.

**Comment by marijnh** [comment]
See eb6ce177061bcc68d and #3598

**Comment by marijnh** [comment]
(I have a fix for this in my upcoming patch, waiting on #4011 to merge because it depends on the new method added by that.)

**Comment by kzc** [comment]
Known issue: #2219

Workaround: #3985
