### ISSUE TITLE
Simple in-memory externals compilation case failure

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#402]
Finally have the pieces together to do a proper jspm integration here, will be working on it this week.

So here's my really simple test case that keeps falling over on the latest version. Any help ~~understanding why it is trying to access the file system (and failing)~~ would be appreciated:

```javascript
var rollup = require('rollup');

rollup.rollup({
  entry: 'test.js',
  external: ['jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck'],
  plugins: [{
    resolveId: function(id, importer, options) {
      console.log('resolve: ' + id);
      if (id == './dep.js')
        return 'dep.js';
      return id;
    },
    load: function(path, options) {
      console.log('load: ' + path);
      if (path == 'test.js')
        return "import _classCallCheck from 'jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck';\n" +
          "import { a } from './dep.js';\n" +
          "export var Q = function Q() {\n" +
          "  _classCallCheck(this, Q);\n" +
          "\n" + 
          "  console.log('hello world');\n" +
          "};";

      if (path == 'dep.js')
        return "export var a = 'a'; export var b = 'b';";

      return '';
    }
  }]
})
.then(function(output) {
  console.log(output);
})
.catch(function(e) {
  console.error(e);
});
```

The above gives the following output:

```
resolve: test.js
load: test.js
resolve: jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck
resolve: ./dep.js
load: jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck
load: dep.js
[Error: Module jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck does not export default (imported by test.js)]
```

But I've explicitly marked "jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck" as external in the above so surely it should not be trying to load it?

**Comment by guybedford** [comment]
Correction: the issue is not due to file system access. If I add the following to the `load` function it works correctly, so it is entirely about externals matching:

```javascript
      if (path == 'jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck')
        return "export default 'asdf'";
```

**Comment by Rich-Harris** [comment]
> Finally have the pieces together to do a proper jspm integration here, will be working on it this week.

:metal: 

`external` is a tiny bit of a misnomer – it doesn't tell Rollup to treat `classCallCheck` as an external so much as it tells it not to be *surprised* that `classCallCheck` is external.

The way to indicate that a module is external (and I realise this could probably be more intuitive/better documented) is to return a falsy value from `resolveId`:

```js
var rollup = require('rollup');

var external = ['jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck'];

rollup.rollup({
  entry: 'test.js',
  external: external,
  plugins: [{
    resolveId: function(id, importer, options) {
      console.log('resolve: ' + id);
      if (id == './dep.js')
        return 'dep.js';
      if (~external.indexOf(id)) return false;
      return id;
    },
    load: function(path, options) {
      console.log('load: ' + path);
      if (path == 'test.js')
        return "import _classCallCheck from 'jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck';\n" +
          "import { a } from './dep.js';\n" +
          "export var Q = function Q() {\n" +
          "  _classCallCheck(this, Q);\n" +
          "\n" +
          "  console.log('hello world');\n" +
          "};";

      if (path == 'dep.js')
        return "export var a = 'a'; export var b = 'b';";

      return '';
    }
  }]
})
.then(function(bundle) {
  console.log(bundle.generate({format:'cjs'}).code);
})
.catch(function(e) {
  console.error(e);
});
```

If the `external` option is missing, or doesn't contain `classCallCheck`, all that happens is you get a warning (it used to be an error, but people rightly found that irritating):

```
Treating 'jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck' as
external dependency
```

**Comment by guybedford** [comment]
Amazing, thanks that sorts it out! I guess I'm interpreting the API from the perspective of an integration developer rather than an end user, so may have different contracts in mind, but expected that was the meaning of `external`. Perhaps just a documentation note on the resolve false would help others.

Feel free to close as you see fit!

Will report back further in the new year :)

**Comment by Rich-Harris** [comment]
Have updated the wiki to be a bit more helpful, will close this in favour of #407
