### ISSUE TITLE
Rollup export miss some module 

### ISSUE THREAD

**Issue by StEvUgnIn** [rollup/rollup#4030]
Hello,

After building my project and packing it rollup. It forgets to export the common.js module

- Rollup Version: 2.44.0
- Operating System (or Browser): Edge (latest)
- Node Version (if applicable): 15.5.1
- Link to reproduction (IMPORTANT, read below): https://github.com/Hackerspace-LeLab/gl-matrix

```
yarn
yes | yarn run build
```

### Expected Behavior
dist/
- cjs
- common
- esm
- imports
- mat2
- mat2d
- mat3
- mat4
- quat
- quat2
- vec2
- vec3
- vec4

### Actual Behavior
dist/
- cjs
- esm
- imports
- mat2
- mat2d
- mat3
- mat4
- quat
- quat2
- vec2
- vec3
- vec4

**Comment by lukastaegert** [comment]
You are using Rollup to bundle CommonJS code but did not add `@rollup/plugin-commonjs`. Thus, Rollup things `require` is just some global function and does not bundle your dependencies.
