### ISSUE TITLE
How do I solve this issue "`this` has been rewritten to `undefined`"?

### ISSUE THREAD

**Issue by iceleo-com** [rollup/rollup#4031]
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/detect-browser/es/index.js
1: var __spreadArrays = (this && this.__spreadArrays) || function () {
                         ^
2:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
3:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
...and 1 other occurrence

This is my rollup config file

```
import { babel } from '@rollup/plugin-babel';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import builtins from 'rollup-plugin-node-builtins';
import { uglify } from "rollup-plugin-uglify";
import alias from '@rollup/plugin-alias';
import scss from 'rollup-plugin-scss';

export default {
    input: 'src/index.js',
    plugins: [
        scss(),
        alias({
            entries: [
                { find: 'react', replacement: 'preact/compat' },
                { find: 'react-dom', replacement: 'preact/compat' }
            ]
        }),
        nodeResolve(),
        babel({
            plugins: [
                '@babel/plugin-syntax-dynamic-import', // add support for dynamic imports (used in app.js)
                '@babel/plugin-proposal-class-properties',
                [
                    '@babel/plugin-transform-react-jsx',
                    {
                        pragma: 'h',
                        pragmaFrag: 'Fragment',
                    },
                ],
            ],
            presets: [
                ['@babel/preset-env', {
                    targets: '> 1%, last 2 versions, Firefox ESR, ie >= 11, iOS >= 9',
                }],
            ],
            babelHelpers: 'bundled',
        }),
        commonjs(),
        builtins(),
        uglify(),
    ],
    cache: true,
    output: {
        file: 'dist/cart-connect.js',
        format: 'umd',
        name: 'ccApp',
        sourcemap: false,
    }
};

```

**Comment by xon52** [comment]
I have this exact issue. How did you solve it?

**Comment by iceleo-com** [comment]
hi @xon52 ,

You need to contact the developer of the library to fix this issue. In my case, I need to contact the "detect-browser" developer

OR you can copy the lib to your local folder and import it from your local folder, then replace the global "this" variable with window variable.
In my case
`var __spreadArrays = (**this && this**.__spreadArrays) || function () {`
will be replace with
`var __spreadArrays = (**window**.__spreadArrays) || function () {`

**Comment by xon52** [comment]
@iceleo-com I see your [detect-browser ticket](https://github.com/DamonOehlman/detect-browser/issues/162) is still open so I presume that hasn't been fixed.
Your solution would work locally, but to fix the libraries (like `detect-browser` or in my case `vue-property-decorator`) I believe it's a babel issue. Babel makes the `__spreadArrays` function to replace the spreader operator for legacy browsers and inserts that broken code in the top of the file that uses the spreader operator.
I'll raise it with them to see if they can fix it.
