### ISSUE TITLE
Reference to buggy not maintained rollup-plugin-node-polyfills in warning

### ISSUE THREAD

**Issue by PFight** [rollup/rollup#4032]
- Rollup Version: 2.44.0
- Operating System (or Browser): Windows 10
- Node Version (if applicable): v12.16.1
- Link to reproduction (IMPORTANT, read below): https://github.com/PFight/rollup-react-named-export-problem

When some module uses node builtins, rollup generates warning like this:

    Rollup: "Creating a browser bundle that depends on Node.js built-in module ('util'). You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills"

Plugin rollup-plugin-node-polyfills is not updated two years, and has critical bug: https://github.com/ionic-team/rollup-plugin-node-polyfills/issues/25

There is good maintained alternative rollup-plugin-node-builtins, that does not produces a bug. We should replace reference in warning.

**Comment by lukastaegert** [comment]
This plugin has only become available recently, but a PR to change the comment/documentation is very welcome!

**Comment by PFight** [comment]
Discovered, that rollup-plugin-node-builtins requires rollup-plugin-node-globals to polyfill some node API. But with rollup-plugin-node-globals I'm getting the same error as in https://github.com/PFight/rollup-react-named-export-problem

It make impossible to use styled-components@5.2.3. I forced to stuck on styled-components@4.3.2, because in this version they are not using "stream" module. Building 5.2.3 with just rollup-plugin-node-builtins I'm getting "stream" as external depenency...

So, error in https://github.com/PFight/rollup-react-named-export-problem is actual for two plugins - rollup-plugin-node-polyfills and rollup-plugin-node-globals. I think, it is issue in that magic logic of automatic commonjs export resolution. Please, can you point out, what those plugins making bad, breaking commonjs in rollup? We could try fork/pull-request one of them, to make it possible use latest styled-components.
