### ISSUE TITLE
async options hook returning null blows up

### ISSUE THREAD

**Issue by trhinehart-godaddy** [rollup/rollup#4038]
- Rollup Version: 2.45.0 (latest)
- Operating System (or Browser): Windows
- Node Version (if applicable): 12
- Link to reproduction: https://replit.com/@trhinehart/rollup-repro-async-options

### Expected Behavior
returning null should not try to parse options

### Actual Behavior
> TypeError: Cannot read property 'context' of null

`normalizeInputOptions` eventually gets called with the returned `null` value, throwing the above error. Issue only happens when returning a Promise.

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #4039
