### ISSUE TITLE
Error with source maps "source.traceSegment is not a function"

### ISSUE THREAD

**Issue by CrowdHailer** [rollup/rollup#404]
I have upgraded from rollup 0.20.5 to 0.23.1 and a previously working configuration is now throwing the following error.

> source.traceSegment is not a function

If I don't try and create a source map then I do not get any errors.

**Comment by Rich-Harris** [comment]
Can you share some details of your setup (or even a repro?) I wonder if it's getting confused about a sourcemap generated by a plugin. Thanks

**Comment by Rich-Harris** [comment]
Turns out it happened in cases where module `x` had transforms applied, but module `y` didn't. Fixed in 0.24.0.
