### ISSUE TITLE
Is there any way to get current file / entry path as a parameter passed into the `banner` function?

### ISSUE THREAD

**Issue by dickeylth** [rollup/rollup#4043]
### Feature Use Case

In my case I want to get current file path to generate according banner string, so is there any way to get current file / entry path as a parameter passed into the `banner` function?

**Comment by dickeylth** [comment]
duplicated of #3678

**Comment by Song-aff** [comment]
3.0版本提供了，或者可以先参考我写的这个插件
https://github.com/Song-aff/rollup-plugin-banner-obj
