### ISSUE TITLE
Exporting an object as default rolls up everything?

### ISSUE THREAD

**Issue by fskreuz** [rollup/rollup#405]
I just installed Rollup, took the maths example with a little tweak: I exported an object containing the functions as default export.

index.js
```js
import Maths from './maths.js';
console.log( Maths.cube( 5 ) );
```

maths.js
```
function square ( x ) {
  return x * x;
}

function cube ( x ) {
  return x * x * x;
}

// HERE!
export default {
  square,
  cube
}
```

The result:
```
$ rollup -f iife ./index.js
(function () { 'use strict';

  function square ( x ) {
    return x * x;
  }

  function cube ( x ) {
    return x * x * x;
  }

  var Maths = {
    square,
    cube
  }

  console.log( Maths.cube( 5 ) );

})();
```

`Maths.square` wasn't used but it's included? Is this expected output or am I missing something here?

**Comment by Victorystick** [comment]
When you're creating `maths` default export, you're effectively _using_ both `square` and `cube`.

To import all exports of a module, write `index.js` like this instead
```js
import * as Maths from './maths.js';
console.log( Maths.cube( 5 ) );
```
and leave `maths` as it is on the Rollup site.

**Comment by fskreuz** [comment]
Ahh, got it. Thanks!
