### ISSUE TITLE
Add more information to `UNUSED_EXTERNAL_IMPORT` warning

### ISSUE THREAD

**Issue by cawa-93** [rollup/rollup#4052]
### Feature Use Case
During build, I receive an uninformative warning:
```node
'default' is imported from external module 'util' but never used
```
There is no information on **where** this is happening.  I had to spend a lot of time to find the cause.

### Feature Proposal
Add to the message at least minimal information about the location of the problem. At first look, this feature does not look very complicated:
https://github.com/rollup/rollup/blob/dba6f13132a1d7dac507d5056399d8af0eed6375/src/ExternalModule.ts#L113-L118
_Code only as an example of implementation_ 
```js
        const importers = unused.flatMap(name => this.declarations[name].module.importers)

        const importersList = importers.reduce((s, importer) => s + `\n\t${importer};`, '')

        this.options.onwarn({
            code: 'UNUSED_EXTERNAL_IMPORT',
            message: `${names} imported from external module '${this.id}' but never used in ${importersList}`,
            names: unused,
            source: this.id,
            importers,
        });
```

```node
 'default' is imported from external module 'util' but never used in
        util?commonjs-external;
        C:/Users/kozac/Dev/vite-electron-builder/node_modules/glob/sync.js;
        C:/Users/kozac/Dev/vite-electron-builder/node_modules/glob/glob.js;
```

**Comment by lukastaegert** [comment]
Sounds like a good idea. Would you be willing to turn this into a proper pull request?

**Comment by cawa-93** [comment]
@lukastaegert Ok. I will try.
