### ISSUE TITLE
Add CLI flag to explicitly disable config file transpilation

### ISSUE THREAD

**Issue by pastelmind** [rollup/rollup#4055]
### Feature Use Case

Rollup gained support for native ESM configs in #3445. This feature enables Rollup to "give up" transpiling and let Node.js execute the raw ESM. However, support for ESM configs are still flaky at the moment:

- Rollup requires Node.js >= 13 to support native ESM config. However, native ESM is well-supported in Node.js v12.x as well. In [12.17.0](https://nodejs.org/en/blog/release/v12.17.0/), the `--experimental-modules` flag was made redundant; in [12.22.0](https://nodejs.org/en/blog/release/v12.22.0/) native ESM was declared "stable".
   Node.js v12 is scheduled to be maintained until April 2022. In the meantime, many projects staying on v12 will be unable to use native ESM for their Rollup config file.
   See: https://github.com/rollup/rollup/blob/a4a3b8a7d881d93bcd0a10110b858e948394ea94/cli/run/loadConfigFile.ts#L15-L17
   - This can be fixed by changing the constant, or by using a proper semver comparison.

- When `package.json` has `"type": "module"`, Node.js treats all scripts with the `.js` extension as native ESM. This behavior was introduced in Node.js 12+. However, Rollup does not respect this field when consuming `rollup.config.js`: it still transpiles the config to CJS before passing it to Node.js.
   This becomes a problem if the config file imports a pure ES module: Because Rollup transpiles the `import`s to `require()`s, the build fails with "**Node tried to require an ES module from a CommonJS file, which is not supported.**".
   See: https://github.com/rollup/rollup/blob/a4a3b8a7d881d93bcd0a10110b858e948394ea94/cli/run/loadConfigFile.ts#L115-L123
   - This cannot be "fixed" without breaking existing code that may be relying on Rollup transpiling the config.

While these two issues can be resolved separately, we may expect further edge cases until the ecosystem adapts to native ESM. Rollup's "should I transpile the config?" detection method may not reflect the interests of its users. Furthermore, changes in the detection method would break existing code that relies on the current behavior. Therefore, it would be nice to give users an escape hatch that gives full control over whether Rollup should transpile its config file.

### Feature Proposal

Add a `--[no--]skip-config-transpile` CLI flag. `--skip-config-transpile` will force Rollup _not_ to transpile the config, and `--no-skip-config-transpile` will force Rollup to transpile the config. In both cases, Rollup leaves the decision up to the user; it forgoes checking the version of Node.js or the config file extension.

Some notes:

- If either flag is not provided, Rollup retains the current behavior. This maintains backwards compatibility.
- Since the decision to transpile a config file must be made before loading the config, we cannot control this behavior through the config file itself. This has to be a CLI flag.
- When the ecosystem around native ESM solidifies, Rollup could change the default behavior without worrying about large-scale breakage.

**Comment by lukastaegert** [comment]
Maybe a positive flag might be less confusing as it avoids the double negation of `--no-skip-config-transpile`, i.e `--transpile-config` or `no-transpile-config`.
Otherwise am I right to assume that providing this flag will override Rollup's auto-detection, meaning that `.mjs` could be force-transpired for Node 14?
I guess a PR for this would be welcome.

**Comment by pastelmind** [comment]
I'm not familiar with Rollup's codebase. Could you provide suggestions on what files should I look at to add a CLI option? Also, do I need to write tests for CLI options?

**Comment by lukastaegert** [comment]
> Also, do I need to write tests for CLI options?

Yes please. CLI tests are found in `/test/cli/samples` and work by directly invoking a command and looking at the generated output. They are configured by a `_config.js` file in the respective folder which also supports a `minNodeVersion` flag if you want to test something only on e.g. ESM capable Node versions. One difference one could test is that transpiled config files do not need extensions for their imports while non-transpiled config files can import ES modules from `node_modules` (there is a special node_modules folder in `/test/cli` for this).

> Could you provide suggestions on what files should I look at to add a CLI option? 

The entire CLI is in the `/cli` folder. The most important part for you is in `loadConfigFile.ts` where it is decided how the file is loaded. Here you have access to the command options.

Also, you should extend documentation in `/cli/help.md` and `/docs/01-command-line-reference.md`.
