### ISSUE TITLE
Add support for the "modern" way package.json indicates CJS vs. ESM code

### ISSUE THREAD

**Issue by Pomax** [rollup/rollup#4061]
### Feature Use Case

modern Node allows for [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) in the `package.json` file, allowing projects to indicate various entry points for various modes such as CJS vs ESM. E.g.:

```
  "type": "module",
  "exports": {
    "import": "./src/library.js",
    "require": "./dist/legacy.cjs"
  },
```

This means that what Rollup and others originally invented the use of the `module` property for should no longer be required for modern ("modern" being anything for Node v14 or newer) code bases.

### Feature Proposal

It would make a lot of sense to add support for checking the package.json file for a coditional exports section, with the `module` property as fallback for when a package.json does not use conditional exporting.

**Comment by lukastaegert** [comment]
This has been implemented in `@rollup/plugin-node-resolve` for quite some time now: https://github.com/rollup/plugins/tree/master/packages/node-resolve#package-entrypoints

There will be no support in Rollup core as Rollup core does not parse package files.

**Comment by lukastaegert** [comment]
For the import type detection, it should work in tandem with the latest version of `@rollup/plugin-commonjs`: https://github.com/rollup/plugins/pull/611

**Comment by Pomax** [comment]
I see, thank you.
