### ISSUE TITLE
Cannot read property 'deoptimizePath' of undefined

### ISSUE THREAD

**Issue by si3nloong** [rollup/rollup#4067]
- Rollup Version: `v2.47.0`
- Node Version (if applicable): `v15.4.0`

<img width="1092" alt="Screenshot 2021-05-06 at 6 38 55 PM" src="https://user-images.githubusercontent.com/28108597/117311534-d83ba300-aeb6-11eb-85f7-22a1f3cb53a1.png">

PR #4070  is included

**Comment by domoritz** [comment]
We are having the same issue. You can reproduce it on https://github.com/vega/svelte-vega/tree/70d27428b33c53c634778bd7817db295150a8669.
