### ISSUE TITLE
Behaviour of options.external

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#407]
Follow-up to #402. At the moment `external` is a bit of a weird option – it doesn't actually cause Rollup to ignore any external IDs, it just means 'don't warn the user if an ID is found to be that of an external module, as long as it's in this array'.

It would probably make a lot more sense if we didn't even try to resolve IDs in `external`. Would also probably make life easier for people writing custom resolvers.

**Comment by guybedford** [comment]
:+1:

**Comment by Rich-Harris** [comment]
Released 0.24.0 with this change

**Comment by guybedford** [comment]
Just tested this out and it is working great for me.
