### ISSUE TITLE
Reduce disk impact of Rollup NPM package

### ISSUE THREAD

**Issue by TimvdLippe** [rollup/rollup#4076]
### Expected Behavior / Situation

Rollup should have a minimal disk impact in `node_modules`

### Actual Behavior / Situation

Rollup takes up 4.3MB of disk space in the `node_modules/` of Chrome DevTools, which puts it in the top 10 largest packages.

```$ du -sh node_modules/rollup/dist/* | sort -rn
988K	node_modules/rollup/dist/shared
364K	node_modules/rollup/dist/rollup.browser.js
 72K	node_modules/rollup/dist/bin
 24K	node_modules/rollup/dist/rollup.d.ts
4.0K	node_modules/rollup/dist/rollup.js
4.0K	node_modules/rollup/dist/loadConfigFile.js
1.3M	node_modules/rollup/dist/rollup.browser.js.map
1.3M	node_modules/rollup/dist/es
```

Rollup ships with a sourcemap that takes up 30% of its bundle.

### Modification Proposal

Similarly to what we have done with Acorn (https://github.com/acornjs/acorn/pull/1023) and ESLint (https://github.com/eslint/eslint/issues/14098), can we remove the sourcemap from the NPM package?

**Comment by lukastaegert** [comment]
The source map was added as people are using the REPL to debug Rollup.

**Comment by lukastaegert** [comment]
Note that the source map for the browser build is also the only one we are including, specifically to support this use case.

**Comment by TimvdLippe** [comment]
@lukastaegert I understand. Since I think that the majority of Rollup users integrate Rollup in their build system, would it maybe be possible to separate out the REPL-support in a separate NPM package? E.g. something like `rollup-repl` which would include the browser bundle and the corresponding sourcemap. That would save significant disk space and network usage for the majority of Rollup users (I am assuming that is the case here, I don't have concrete data), while still supporting the Rollup REPL users.

**Comment by lukastaegert** [comment]
Might be a good idea for the next major version to think about the package structure. Separating the browser build from the rest is likely a good idea as there should be little overlap between their consumers.

**Comment by TimvdLippe** [comment]
@lukastaegert Quick question: when are you expecting to publish a new major version?

**Comment by lukastaegert** [comment]
At least some months from now. It is clear what should be part of that version but work has been blocked by other issues.
