### ISSUE TITLE
Suppress warning messages

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#408]
I'm using that `return false` in the resolveId function now and it's working great.

Only it seems to give a message each time _Treating 'jspm_packages/npm/babel-runtime@6.3.19/helpers/classCallCheck' as external dependency_.

It would be great to be able to disable these messages via a `rollup({ warn: false })` option or similar in https://github.com/rollup/rollup/blob/master/src/utils/defaults.js#L32.

**Comment by Rich-Harris** [comment]
You can supply a custom `onwarn` function that will intercept warnings:

```js
var warnings = [];

rollup.rollup({
  entry: 'src/main.js',
  onwarn: function ( message ) {
    if ( /external dependency/.test( message ) ) return;
    console.error( message );
  }
}).then(...);
```

Just realised that isn't in the wiki – will update it.

**Comment by guybedford** [comment]
Excellent, thanks!

**Comment by ibqn** [comment]
@Rich-Harris is there a way to call the default `onwarn` implementation after processing some filtering in the overwritten `onwarn` function?

Because, at the moment when I use the custom `onwarn` function I lose default coloring and warning message format :-(.

**Comment by Rich-Harris** [comment]
@ibqn not currently, no. The source code is [here](https://github.com/rollup/rollup/blob/master/bin/src/logging.js) if you want to crib it. not sure what the best way to expose it would be

**Comment by ibqn** [comment]
@Rich-Harris This is exactly the way I do it here for [Angular2-quick-start](https://github.com/ibqn/ng2-quick-start/commit/d5eb2de849b0273ce9d8510d7d80a25c701de3bf) however this look very ugly;)

Suddenly, this is a well known warning message, which appears during the rollup of the AOT compilation with [Angular2](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#run-rollup).

It would be great if something like this were possible in the `rollup.config.js` file:

```javascript
import { handeWarning } from 'rollup';
...
const warnFilter = /The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten/;

export default {
  ...
  format: 'iife',
  onwarn: warning => {  // overwite the default warning function
      const str = warning.toString();

      if (warnFilter.test(str)) return;
      handeWarning(warning);
  },
  ...
}
```

**Comment by Rich-Harris** [comment]
Maybe an alternative would to be make the functions chainable:

```js
export default {
  ...
  format: 'iife',
  onwarn: ( warning, next ) => {
      if ( warning.code === 'THIS_IS_UNDEFINED' ) return; // you can do this now btw
      next( warning );
  },
  ...
}
```

**Comment by ibqn** [comment]
@Rich-Harris Yes, sounds good!

**Comment by caub** [comment]
Is there a way to ignore warnings when using it from shell?

I have lots of: before actual results  (I'm running a file with `rollup -f cjs ... | node`)
```
Warning: 'url' is imported by src/index.js, but could not be resolved – treating it as an external dependency
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

Warning: 'http' is imported by src/index.js, but could not be resolved – treating it as an external dependency
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

Warning: 'https' is imported by src/index.js, but could not be resolved – treating it as an external dependency
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

Warning: 'zlib' is imported by src/index.js, but could not be resolved – treating it as an external dependency
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
...
```

**Comment by Rich-Harris** [comment]
@caub yep — `--silent`. See also https://github.com/rollup/rollup/pull/1491 — will hopefully get some time to finish that off soon, it will make those messages much less obtrusive. (We should probably hide those messages for builtin modules like `url` and `http` anyway, at least for `cjs` bundles.)

**Comment by AlexGalays** [comment]
These warnings seem more annoying than helpful in general.
Even if `lodash-es` is whitelisted, you still get warnings for all its submodules.

**Comment by krabbypattified** [comment]
@curran #1491 means we have colorful warnings and no longer need `console.error` :)

**Comment by curran** [comment]
@krabbypattified Thanks, but I'm not understanding how to have colorful warnings while ignoring the circular dependency warnings. Is that what you're suggesting? How could it be done?

**Comment by krabbypattified** [comment]
@curran 
```js
{
  onwarn(warning, warn) {
    if (message.code === 'CIRCULAR_DEPENDENCY') return
    warn(warning)
  }
}
```

**Comment by mikemaccana** [comment]
For folks using D3 (see https://github.com/d3/d3-interpolate/issues/58)

```
// https://github.com/d3/d3-interpolate/issues/58
const D3_WARNING = /Circular dependency.*d3-interpolate/
```
(and then later)

```
  onwarn: function ( message ) {
    if ( D3_WARNING.test(message) ) {
      return
    }
  },
```

**Comment by codefactor** [comment]
Hello - I mentioned this one inside #2082 and given this problem is sort of solved in #408 - I figured it is good to reach out here instead.

I wonder if much thought was given to suppressing warnings using comment directives -- something that things like `prettier` and `eslint` both support today. For example something like this would be great:
```
// rollup-disable-warning-next-line EVAL
eval(safeString);
```
I understand that updating the config.js to do something like this:
```
{
  onwarn: (warning, warn) => {
    if (warning.code === 'EVAL' && /[/\\](my_safe_eval.js|some_other_file.js)$/.test(warning.loc.file)) {
      return;
    }
    warn(warning);
  }
}
```
Looks like I have 2 options:
1. Disable EVAL for the entire rollup
2. Disable EVAL for files that match a regex

Option 1 is not really great because it removes a useful warning that is good to have. Option 2 is not great either because it requires config.js maintenance over time as new evals are added to more places. In short, the config.js is not the most logical place to identify a safe usage of EVAL -- it should be placed as close to the offending location as possible. That's why the comments are so nice in `eslint` and `prettier`

**Comment by flcoder** [comment]
+1 // rollup-disable-warning-next-line EVAL
IMO, this is easy for consumers

**Comment by alexanderbird** [comment]
In my case, I wanted to suppress warnings for 3rd party code: 

```
    onwarn: function onwarn(warning, warn) {
      if (warning.id.indexOf(__dirname + '/node_modules/') === 0) return;
      warn(warning);
    },

```

**Comment by GustavoFenilli** [comment]
> In my case, I wanted to suppress warnings for 3rd party code:
> 
> ```
>     onwarn: function onwarn(warning, warn) {
>       if (warning.id.indexOf(__dirname + '/node_modules/') === 0) return;
>       warn(warning);
>     },
> ```

For my case I wanted to suppress warnings for 3rd party but circular dependency wasn't from id, but ids so I made this simple fn to add it to the `onwarn`.

```js
const isThirdParty = (warning) => {
  if (warning.id && /node_modules/.test(warning.id)) return true;
  if (warning.ids && warning.ids.every((id) => /node_modules/.test(id))) return true;

  return false;
}
```
