### ISSUE TITLE
2.41.4 doesnt work as expected

### ISSUE THREAD

**Issue by milesj** [rollup/rollup#4082]
- Rollup Version: 2.41.4
- Operating System (or Browser):  macos, linux
- Node Version (if applicable): 10+
- Link to reproduction (IMPORTANT, read below): https://github.com/milesj/packemon/pull/60/checks

### Expected Behavior

So I maintain this package called Packemon (https://github.com/milesj/packemon), which standardizes the package building process a bit. It's been working great, so I attempted to update to that latest rollup version from 2.40.0. However, a handful of my tests started failing at 2.41.4+, and I have no idea why. You can see this in action here: https://github.com/milesj/packemon/pull/60

What's failing exactly is that I have a handful of unit tests that run rollup, where I spy on `fs.writeFile` to intercept the contents, and write snapshots to verify the rollup builds. Here's some examples:

- The spies being created: https://github.com/milesj/packemon/blob/master/tests/helpers.ts#L60
- Fixture entry points: https://github.com/milesj/packemon/tree/master/tests/__fixtures__/project-rollup/src
- Tests creating the snapshots: https://github.com/milesj/packemon/blob/master/tests/outputs.test.ts#L55
- The snapshots themselves: https://github.com/milesj/packemon/blob/master/tests/__snapshots__/outputs.test.ts.snap

These tests pass on <=2.41.3 but start failing on >=2.41.4. But how do they break exactly? Well they _do not write a snapshot at all_, nor does it throw an error. It's almost like the `fs.writeFile` is no longer being called.

I've dug into this for over an hour now, both in packemon and rollup's codebase, but I cannot find anything wrong. I'm running out of ideas and looking for any guidance.

### Actual Behavior

Rollup writes files?

**Comment by milesj** [comment]
Ok, after sleeping on it, looking at the _dist_ rollup code, and reading [this thread](https://github.com/rollup/rollup/pull/3998), I think I know what's happening. 

In <=2.41.3, the fs calls simply looked like this:
```js
var fs = require('fs');

fs.writeFile(dest, data, err => {}):
```

In >=2.41.4, the fs calls are now wrapped in a namespace like this:
```js
var fs = require('fs');

function _interopNamespaceDefault(e) {
  var n = Object.create(null);
  if (e) {
    Object.keys(e).forEach(function (k) {
      n[k] = e[k];
    });
  }
  n['default'] = e;
  return n;
}

var fs__namespace = /*#__PURE__*/_interopNamespaceDefault(fs);

fs__namespace.writeFile(dest, data, err => {}):
```

I have a feeling this namespace remapping stuff is breaking jest spies, and I'm not entirely sure there's a workaround for it.

**Comment by milesj** [comment]
I was able to get this working by using `bundle.generate()` in tests, and `bundle.write()` in non tests: https://github.com/milesj/packemon/pull/60/files

I'll leave this open for now so you're at least aware.

**Comment by lukastaegert** [comment]
This is still curious to say the least. The namespace helper should only be triggered if you are doing actual namespace imports, i.e. `import * as fs from 'fs`. But I can only see default imports here, which *should* actually work. Except if Jest does some magic of its own here. My first approach would have been to play with the interop option to just get rid of the interop code: https://rollupjs.org/guide/en/#outputinterop
Both `esModule` and `default` would remove the interop code, and if there is no "actual" default import as we have it in the case of `fs`, the choice would actually not matter. It can also be a function to only target specific externals.

**Comment by milesj** [comment]
I was able to work around this, so will close this for now.
