### ISSUE TITLE
suboptimal tree shaking of sequences

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#4083]
- Rollup Version: v2.48.0
- Operating System (or Browser): any
- Node Version (if applicable): any

### [Repro](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMjAlMkMlMjBjb25zb2xlLmxvZyglNUMlMjJoZWxsbyU1QyUyMiklMkMlMjAxJTJDJTIwMiUyQyUyMDMlM0IlNUNuY29uc29sZS5sb2coJTVDJTIyd29ybGQlNUMlMjIpJTJDJTIweCUyMCUzRCUzRSUyMHglM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

```
$ cat input.js
0, console.log("hello"), 1, 2, 3;
console.log("world"), x => x;
```

### Expected Behavior

```js
console.log("hello");
console.log("world");
```

### Actual Behavior
```
$ rollup input.js --silent
console.log("hello"), 3;
console.log("world"), x => x;
```

Rollup appears to have an issue tree shaking the last element in the sequence if another element has side effects. 

This may have not been noticed earlier because rollup is often used with minifiers, and they will drop side-effect-free elements in sequences.

```
$ rollup input.js -p terser --silent
console.log("hello"),console.log("world");
```

There is no issue with rollup if all elements in the sequence are side-effect free:

```
$ echo '1, 2, x => x;' | rollup 

- → stdout...

(!) Generated an empty chunk
```

**Comment by lukastaegert** [comment]
Yes, sequence expressions do not know at the moment why they are included, so they keep their return value if they are included in case it is relevant.

**Comment by kzc** [comment]
It'd be safe to assume that the sequence return value would not be relevant if the sequence parent is an `ExpressionStatement`.

But since rollup doesn't alter the AST, I guess whether the sequence return is used or not has to be tracked across nodes:

```
$ echo 'var u = 1 ? (2, console.log("OK"), /*@__PURE__*/big_calc()) : f();' | rollup --silent
(console.log("OK"), /*@__PURE__*/big_calc()) ;
```

**Comment by lukastaegert** [comment]
Dropping the return if the parent is an `ExpressionStatement` would definitely be a safe improvement. For optimisations, there is a tracking logic that at least knows if the rendered parent is an `ExpressionStatement`.

**Comment by kzc** [comment]
> there is a tracking logic that at least knows if the rendered parent is an ExpressionStatement.

Good stuff.

I'm not well versed in that tracking logic, so I'll leave that to you.

Is there any documentation providing a 40,000 foot overview of how rollup optimization generally works? It can be brief and need not be very specific. People like me familiar with AST manipulation and optimization have a bit of a conceptual disconnect. AST nodes are not dropped or rearranged in rollup, but ultimately nodes are included or not included and removed from the code MagicString. What goes on in between is a bit fuzzy to me.

**Comment by lukastaegert** [comment]
That would be tricky. But the part that does the dropping ist the `render` method of each Node. This is also the one that knows if some simplification happened in one of the parents via the optional `renderedParentType` property of the third argument (the presence of this options means that the rendered parent is not the real parent).

However, rendering happens during the generate phase while for the current issue, one would need to know if the expression value is used during the build/tree-shaking phase.

But what could easily be done during tree-shaking is conditionally including the last sequence element depending on if "this.parent" is an ExpressionStatement.

This will happen in the `include` method that is called several times during tree-shaking. You will see that here, SequenceExpressions always include their last element, and this logic should be changed.

**Comment by kzc** [comment]
That's helpful, thanks.  I was not aware of `renderedParentType`.

Even more basic - please correct me if I'm wrong - there are three primary phases involved in optimization: (1) the binding phase, (2) the tracking-logic construction and tree-shaking phase, and (3) the generate/render phase.  Although the AST structure is immutable, any node may have a "return" value that could essentially take the place of the subtree, or an unknown value. The tree shaking phase performs multiple walks of the tree and specific nodes and their children can be retained or eliminated via the `include` method.  Values as well as side effects can be propagated up the tree via virtual methods on the AST node classes. 

However, I'm still not clear on the concept of "Paths", a.k.a. `ObjectPath`.

> But what could easily be done during tree-shaking is conditionally including the last sequence element depending on if "this.parent" is an ExpressionStatement.
>
> This will happen in the include method that is called several times during tree-shaking. You will see that here, SequenceExpressions always include their last element, and this logic should be changed.

I tried that initially, but clean up of the trailing comma aside, unless I'm mistaken it would only handle cases like in the top post where the immediate parent is an ExpressionStatement, not for the indirect optimized scenario in https://github.com/rollup/rollup/issues/4083#issuecomment-843286128.  

I'll sit this one out. Looking forward to the PR.

**Comment by lukastaegert** [comment]
> unless I'm mistaken it would only handle cases like in the top post where the immediate parent is an ExpressionStatement
which I would expect to be 95% of all cases.

>  there are three primary phases involved in optimization
Correct, at least as far as ASTs are involved. On the larger scale of modules and the graph there are more phases like parsing and linking but those are not relevant for the AST. Note that the first two phases happen during `rollup.rollup()` (the "build" phase), while rendering happens during `bundle.generate()`.

> any node may have a "return" value
If you are referring to `getLiteralValueAtPath`, yes, this one is used by various conditionals to determine truthiness.

> The tree shaking phase performs multiple walks of the tree and specific nodes and their children can be retained or eliminated via the include method

Well, from a mental model the idea of tree-shaking is to always include and never remove, i.e. we start with nothing and then add stuff for various reasons, usually side effects. Once a node is included, it will get its `include` method called again in the next pass as there may be additional children that still need to be included.

> Values as well as side effects can be propagated up the tree via virtual methods on the AST node classes

Yes, at the moment we copy the AST nodes into our AST classes that have the additional values. I did not yet find an efficient way of operating on the original AST that allows the same conciseness

> .However, I'm still not clear on the concept of "Paths", a.k.a. ObjectPath

This has a lot to do with resolving MemberExpressions and ObjectExpressions. So we want to know if in

```js
var foo = {bar(){}};
foo.bar()
```

`foo.bar()` has a side effect. Then the CallExpression will check if  `foo.bar` has an effect "whenCalledAtPath `[]`". As `foo.bar` is a MemberExpression, it will ask its object `foo` if it has an effect when called at path `['bar']`. As `foo` is an identifier, it forwards the request to LocalVariable which will forward it to its initialiser, the ObjectExpression `{bar(){}}`. This one will ask its property `bar(){}` if it has an effect when called at path `[]` and then it sees it is an empty method and the answer is `false`.
All of these object path things works like that.

**Comment by kzc** [comment]
@lukastaegert Thanks for the additional detail, and your work on the project in general.

Rollup has a unique approach of AST optimization while preserving the original source code structure with MagicString. This imposes constraints that are not obvious to those familiar with traditional AST-based compilers and code generators. High level documentation providing an overview of rollup-specific concepts and terms would help potential contributors. Source-level comments only go so far.

**Comment by lukastaegert** [comment]
I added a fix at #4083 that goes for the most simple approach. Still unresolved is the wrong association if a "pure" comment is placed before the first expression, which I will have a look at next.

**Comment by kzc** [comment]
Cool.

I was thinking about how one might further simplify the indirect case mentioned above:

```
$ echo 'var u = 1 ? (2, console.log("OK"), /*@__PURE__*/big_calc()) : f();' | rollup --silent
(console.log("OK"), /*@__PURE__*/big_calc()) ;
```

Is there a virtual method on an AST base class along the lines of (the fictitious) `NodeBase.getReducedAstNodeOrNull()`?  In this particular example the `ConditionalExpression` node could have that method return the `ConditionalExpression.consequent` AST node object reference outright since the `ConditionalExpression.test` is always truthy.

**Comment by lukastaegert** [comment]
No, and I am not sure this is the best way to handle it. Especially since it does not matter if the conditional is simplified to decide if you need to include the last sequence expression element:

```js
getSomeValue() ? (console.log('effect'), /*@__PURE__*/big_calc()) : (console.log('effect'), /*@__PURE__*/big_calc());
```

would still be equivalent to

```js
getSomeValue() ? console.log('effect') : console.log('effect');
```

as the return value is unused. My idea would be to separate inclusion of the node from inclusion of its value. e.g. by passing an additional flag to `include` to mark the value as unused. Then each node can decide what it means if the value is unused and can include its children accordingly.

**Comment by kzc** [comment]
> My idea would be to separate inclusion of the node from inclusion of its value. e.g. by passing an additional flag to include to mark the value as unused. 

Yes, that approach could work. I was just exploring an alternate approach that I think can lead to some  simplification of code.

Either way, solving this indirect unused value issue would lead to general optimization improvements. Here's the example adapted to use an array:

```
$ echo '[2, console.log("OK"), /*@__PURE__*/big_calc()] ;' | rollup --silent
[2, console.log("OK"), /*@__PURE__*/big_calc()] ;
```
```
$ echo '[2, console.log("OK"), /*@__PURE__*/big_calc()] ;' | uglify-js -c
console.log("OK");
```

It appears that Rollup does not currently simplify unreferenced array literals:

```
$ echo '[2, console.log("OK"), 3];' | rollup --silent
[2, console.log("OK"), 3];
```
```
$ echo '[2, console.log("OK"), 3];' | uglify-js -c
console.log("OK");
```

and unreferenced object literals:
```
$ echo '({ a: console.log("effect") });' | rollup --silent
({ a: console.log("effect") });
```
```
$ echo '({ a: console.log("effect") });' | uglify-js -c
console.log("effect");
```

**Comment by kzc** [comment]
Pure annotated calls with side effects in their arguments could also benefit from this proposed optimization:

```
$ echo '/*@__PURE__*/ foo(2, effect(), 3);' | rollup --silent
/*@__PURE__*/ foo(2, effect(), 3);
```
```
$ echo '/*@__PURE__*/ foo(2, effect(), 3);' | uglify-js -c
effect();
```

The pure call could be dropped leaving a sequences of its arguments `(2, effect(), 3);` which in turn could be simplified to `effect();`.
