### ISSUE TITLE
Issue with packages that specify side effects

### ISSUE THREAD

**Issue by TheMcMurder** [rollup/rollup#4084]
- Rollup Version: 2.48.0
- Operating System (or Browser): MacOS 11.3 / affects all browsers
- Node Version (if applicable): run on 12.16.1 and v14.16.0
- Link to reproduction (IMPORTANT, read below): https://github.com/TheMcMurder/rollup-test

### Expected Behavior

CSS is bundled into the output. The dependencies specify their side effects with: `sideEffects: ["*.css"]`. See package json files for [button](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/button/package.json#L14), [theme](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/theme-default/package.json#L15), and [provider](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/provider/package.json#L15)

<img width="296" alt="Screen Shot 2021-05-17 at 3 09 06 PM" src="https://user-images.githubusercontent.com/3059715/118558651-30c73780-b724-11eb-833a-9c5f9161c1c4.png">

### Actual Behavior

CSS is not bundled into the output

<img width="205" alt="Screen Shot 2021-05-17 at 2 46 39 PM" src="https://user-images.githubusercontent.com/3059715/118558665-345abe80-b724-11eb-94ba-650d8e28b555.png">

I'm happy to help solve this issue but I'm not certain where in rollup the issue lies. I found some test cases [here](https://github.com/rollup/rollup/blob/master/test/function/samples/module-side-effects/transform/main.js) but am not entirely certain where I would add another test case.

**Comment by TheMcMurder** [comment]
Perhaps this is solved by https://twitter.com/lukastaegert/status/1394618692374351872?s=20. ❤️

**Comment by TheMcMurder** [comment]
I'm still seeing the same issue on Rollup `2.49.0-0` which I believe is the beta version that adds support for `sideEffects: ["*.css"]`.

**Comment by lukastaegert** [comment]
The beta version has nothing to do with that unfortunately.

Handling the side-effects property in package.json files is not part of rollup core at all but part of [`@rollup/plugin-node-resolve`](https://github.com/rollup/plugins/tree/master/packages/node-resolve), which is in general the plugin that handles package.json files as this is a core part of the Node resolution algorithm.

At this point I am not sure if it is an issue with the postcss plugin or with the node-resolve plugin, but very likely it is not an issue with rollup core.

If you want to help with debugging, the important part is to figure out what is removed and why. Is it only the CSS that is missing or also some files in between?
One thing to do could be to run Rollup with `format: "es"` and `output.preserveModules: true`. This will not necessarily run, but you get a picture of the relevant module graph that Rollup sees on your hard drive. Then one could try to find out what is the diff between the two graphs. In the end, it could be a bug in the node-resolve plugin, but it could also be wrong assumptions how to use the sideEffects property.

**Comment by lukastaegert** [comment]
Though it looks to me very much like an issue with node-resolve. The CSS import just seems to be missing while the CSS does look like it has enough side-effects of its own.

**Comment by TheMcMurder** [comment]
Thanks for taking a look at this. I followed your suggested debugging steps and tried a few additional ones.

## es format and preserveModules

After setting `output.format: "es"` and `output.preserveModules: true` the build output looked correct except it was missing the CSS.

The source code had and import to `main.css` but the output code omitted the import statement.

### NPM Source code
<img width="1595" alt="Screen Shot 2021-05-24 at 10 26 13 AM" src="https://user-images.githubusercontent.com/3059715/119377719-ab3f0c80-bc7a-11eb-870f-8bbbf2726373.png">

### Output code
<img width="1512" alt="Screen Shot 2021-05-24 at 10 26 19 AM" src="https://user-images.githubusercontent.com/3059715/119377733-b2661a80-bc7a-11eb-8fe7-b1a52df342e0.png">

## PostCSS `extract: true`

One area I tested before submitting this PR was if the CSS plugin was getting the CSS at all, I assumed it was a configuration issue. So I added some logging whenever a file was loaded and parsed by the plugin. What I saw was that the plugin was always processing the CSS but the CSS was only output _anywhere_ if I used `extract: true`. I assumed this had to do with rollup core preventing the side effects of injecting CSS but when the CSS was extracted everything worked because there was no side effect.

When I configured postCSS like this:
```js
postcss({
  extensions: ['.css'],
  extract: true,
}),
```
### Output

<img width="266" alt="Screen Shot 2021-05-24 at 10 32 37 AM" src="https://user-images.githubusercontent.com/3059715/119378430-85663780-bc7b-11eb-889a-01edfd623d36.png">

I assumed this had to do with how rollup core was handling the import and what effects it was allowing, but it being inside `@rollup/plugin-node-resolve` makes a lot of sense to me. I'm not super familiar in that area either but I'll poke around there a bit today.

**Comment by TheMcMurder** [comment]
Some more testing. 

I think it all comes down to how `pluginutils` filters things out with the `sideEffects`:
- [createFilter](https://github.com/rollup/plugins/blob/53776ee3fc59587fe5ff0c756216185f48372507/packages/pluginutils/src/createFilter.ts#L26) is called by [getPackageInfo](https://github.com/rollup/plugins/blob/53776ee3fc59587fe5ff0c756216185f48372507/packages/node-resolve/src/util.js#L42)
- getPackageInfo passes in the exact value of the [sideEffects](https://github.com/rollup/plugins/blob/53776ee3fc59587fe5ff0c756216185f48372507/packages/node-resolve/src/util.js#L147)
- createFilter sets up [the rootdirectory to search](https://github.com/rollup/plugins/blob/53776ee3fc59587fe5ff0c756216185f48372507/packages/pluginutils/src/createFilter.ts#L27)
- the sideEffects array that is passed to `picomatch` doesn't match anything in nested directory

Normally I think this behavior is exactly what we would want. In this specific case I'm not sure the best way to solve the issue. I think it is

## An example

If the side effect is `["*.css"]` that value is passed directly into 'picomatch' which is a problem in this case because the `css` is in a nested directory `.../node_modules/@react-spectrum/providers/dist/main.css` and `picomatch` behaves as expected in this case by _not_ matching `providers/dist/main.css` from the `providers` directory

If I change the package.json side effects to be: `["**/*.css"]` the css is properly included. Picomatch looks for CSS in any nested folder in `providers`

## Brainstorming fixes
- Always use a wildcard when dealing with `sideEffects`
- Modify the resolve root path to be relative to the importing module (`.../providers/dist/module.js` could set the `resolutionBase` as `.../providers/dist/` instead of `.../providers/`
- something else

**Comment by TheMcMurder** [comment]
@lukastaegert based on your comments I did a bunch of experimenting with a few different official rollup plugins. I expect my ignorance is leading me to bad place to put the fix but my instinct here is to put one of the brainstorming fixes into `@rollup/pluginutils` instead of `@rollup/plugin-node-resolve` 

I'm a bit hesitant to add functionality in that area because I know it's used extensively by plugins and I'm not sure I understand it well enough to make such a potentially large change.
