### ISSUE TITLE
Input source maps support

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#409]
Not trying to make more work, but also came across this possibility. When using the `load` hook, each file could potentially have its own originating source map to chain into the Rollup optimization.

(in other news just completed the jspm Rollup work here!)

![screen shot 2016-01-01 at 21 25 32](https://cloud.githubusercontent.com/assets/598730/12071921/ac93e62c-b0ce-11e5-9537-f819926558b1.png)

**Comment by guybedford** [comment]
Not needing to make more work here, and I know there are certainly other priorities. Just to note this as a possibility, feel free to close.

**Comment by Rich-Harris** [comment]
I think this is a reasonable thing to consider including. A workaround in the meantime might be to use [sorcery](https://github.com/Rich-Harris/sorcery) – it *should* (never any certainties with sourcemaps, in my experience...) be able to combine the sourcemap Rollup generates with pre-existing ones.

**Comment by guybedford** [comment]
Well that's a convenient project to have on hand!

When @crisptrutski did input source maps work for Traceur, it ended up being a relatively simple implementation at https://github.com/google/traceur-compiler/pull/1608/files.

Working through all the edge cases of this stuff is a pain I know though.

**Comment by guybedford** [comment]
Any news on a feature like this? Input source maps would be really useful to ensure we're getting the right source map generation in jspm (currently there are offset issues due to the multi-compilation steps). If this project is using `source-map`, it is designed to work very easily with input source maps, as shown in the PR link above.

I can potentially see if I can work on something along these lines as well. Just let me know your thoughts.

**Comment by Victorystick** [comment]
At first I thought we'd only need to patch `transform.js` with the following, but it didn't seem to get the source maps generated properly.

```diff
export default function transform ( source, id, transformers ) {
	let sourceMapChain = [];

	if ( typeof source === 'string' ) {
		source = {
			code: source,
			ast: null
		};
	}

+	// If the source already has a source map defined,
+	// add it to the chain of source-maps to collapse.
+	if ( source.map ) {
+		sourceMapChain.push( source.map );
+	}

	let originalCode = source.code;
	let ast = source.ast;
```

**Comment by Rich-Harris** [comment]
I guess the question is how far do you go? Suppose I import some-lib.js, which has an accompanying sourcemap that includes foo.js, bar.js and baz.js, which *also* have sourcemaps pointing to foo.coffee, bar.coffee and baz.coffee? Should Rollup follow those chains as far as they go, or just the first level?

Sorcery is designed to handle scenarios like that. Perhaps we could create rollup-plugin-sorcery which would compose all pre-Rollup sourcemaps once the bundle has been generated?

**Comment by guybedford** [comment]
In jspm, each build step will handle just the direct input source map (as is provided by Babel and Traceur) but the final source map will then trace back to the original sources correctly no matter how many steps are involved. The handling of this simple case of just providing the direct input source map naively would work fine from my perspective, and can always be improved later. It may also be beneficial from a performance perspective as well.

**Comment by guybedford** [comment]
Closed by https://github.com/rollup/rollup/pull/715.

**Comment by kylecordes** [comment]
I came across this issue months passed the most recent discussion, and in surprised actually that rollup doesn't "just work" and consume input source maps out of the box.
