### ISSUE TITLE
`var` use before defined incorrect, `let`/`const` TDZ errors masked by tree shaking

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#4101]
- Rollup Version: rollup v2.50.1
- Operating System (or Browser): n/a
- Node Version (if applicable): v16.1.0

### Repro

```
$ cat misc.js
(function bug1() {
    var first = state();
    var on = true;
    var obj = { state: state };
    console.log(first, obj.state());
    function state() {
        return on ? "ON" : "OFF";
    }
})();
(function bug2() {
    var a = "PASS";
    for (var b = 2; --b >= 0; ) {
        (function() {
            var c = function() {
                return 1;
            }(c && (a = "FAIL"));
        })();
    }
    console.log(a);
})();
```

### Expected Behavior

```
$ cat misc.js | node
OFF ON
PASS
```

### Actual Behavior

```
$ cat misc.js | rollup --silent | node
ON ON
FAIL
```
```
$ cat misc.js | rollup --silent
(function bug1() {
    var first = state();
    var obj = { state: state };
    console.log(first, obj.state());
    function state() {
        return "ON" ;
    }
})();
(function bug2() {
    var a = "PASS";
    for (var b = 2; --b >= 0; ) {
        (function() {
            (function() {
                return 1;
            })((a = "FAIL"));
        })();
    }
    console.log(a);
})();
```

**Comment by kzc** [comment]
There might be a relatively simple fix for this. Consider the addition of these synthetically introduced redundant valueless `var` declarations at the top of the problematic functions in question:

```
$ cat misc2.js 
(function bug1() {
    var on;           // <----- introduce synthetically
    var first = state();
    var on = true;
    var obj = { state: state };
    console.log(first, obj.state());
    function state() {
        return on ? "ON" : "OFF";
    }
})();
(function bug2() {
    var a = "PASS";
    for (var b = 2; --b >= 0; ) {
        (function() {
            var c;    // <----- introduce synthetically
            var c = function() {
                return 1;
            }(c && (a = "FAIL"));
        })();
    }
    console.log(a);
})();
```
```diff
--- misc.js
+++ misc2.js
@@ -1,3 +1,4 @@
 (function bug1() {
+    var on;           // <----- introduce synthetically
     var first = state();
     var on = true;
@@ -12,4 +13,5 @@
     for (var b = 2; --b >= 0; ) {
         (function() {
+            var c;    // <----- introduce synthetically
             var c = function() {
                 return 1;
```
```
$ cat misc2.js | node
OFF ON
PASS
```

The test now passes:
```
$ rollup -v
rollup v2.50.3
```
```
$ cat misc2.js | rollup --silent | node
OFF ON
PASS
```
Since `var` variables have function scope, Rollup could initialize them internally as `undefined` at top of function rather than the position they appear within the function.

**Comment by lukastaegert** [comment]
True, but this basically means that all var variables are completely deoptimized. I.e. this would be more or less equivalent to just not track any values for var variables. Which would be a huge loss. But for now, I see no way to fix this without breaking analysis short of implementing basic flow analysis, which would be huge in and off itself. The only quick fix I see would be to introduce a flag to decide if we deoptimize all var variables.

**Comment by kzc** [comment]
At least in this case there might be a heuristic to remedy the situation:
```js
            var c = function() {
                return 1;
            }(c && (a = "FAIL"));
```
as there are no assignments or updates to the `var` `c` in the decl's init subtree, so it ought to remain `undefined`. It only has a value after the init. One could mark all the `c` identifiers within the init tree to not assume it has a value. If there are any assignments or updates to the variable within the init tree then this particular variable has to be deoptimized for each of its uses.

**Comment by kzc** [comment]
@lukastaegert It appears that this bug is not limited to `var` variables. It is a general bug that also affects `const` and `let` variables - but in the opposite way. Incorrect code is transformed without warning to produce a program that has different runtime behavior:

Given an incorrectly written program:
```
$ cat misc3.js 
console.log(function() {
    if (x) return "HELLO";
    const x = 1;
    return "WORLD";
}());
```
Here's the expected runtime error:
```
$ cat misc3.js | node
[stdin]:2
    if (x) return "HELLO";
    ^

ReferenceError: Cannot access 'x' before initialization
```
And here's the actual incorrect result produced with rollup:
```
$ rollup -v
rollup v2.50.4
```
```
$ cat misc3.js | rollup --silent | node
HELLO
```
Notice that rollup produced no error or warning:
```
$ cat misc3.js | rollup

- → stdout...
console.log(function() {
    return "HELLO";
}());
```
```
$ echo $?
0
```
If the rollup user does not test their code without rollup, or with `rollup --no-treeshake`, they wouldn't be aware of the error in their original code that was masked.

**Comment by kzc** [comment]
Here's a simpler example of a TDZ failure being masked:

```
$ echo 'let x = x;' | node
[stdin]:1
let x = x;
        ^
ReferenceError: Cannot access 'x' before initialization
```

```
$ echo 'let x = x;' | rollup

- → stdout...

(!) Generated an empty chunk
```

**Comment by kzc** [comment]
Workaround for the var-use-before-defined bugs by deoptimizing all `var` variables: #4139

The only workaround for the masking of `let`/`const` [TDZ errors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz) is to disable tree shaking altogether - and if optimization is required a minifier like uglify-js that retains the TDZ violating code could be used. (Terser at time of this writing hides TDZ violations similar to rollup.)

These two issues above are result of the same underlying variable analysis problems. A proper fix for either would resolve both issues.
