### ISSUE TITLE
CSS code-splitting with "rollup-plugin-styles" is broken by PR #4104 (Rollup v2.50.2)

### ISSUE THREAD

**Issue by AurelienStebe** [rollup/rollup#4130]
- Rollup Version: v2.50.1 - v2.50.2
- Operating System (or Browser): MacOS
- Node Version (if applicable): v14.17.0
- Link to reproduction: https://replit.com/@AurelienStebe/rollup-tree-shaking-error-repro#rollup.config.js

### Expected Behavior

The output of Rollup v2.50.1, which makes CSS code-splitting with static CSS outputs possible.

### Actual Behavior

Since Rollup v2.50.2 (still the same in the recent v2.51.0 release), the CSS code-splitting doesn't work. The CSS code is duplicated between outputs and the static assets overwrite each others.

I traced the change to PR #4104 and this new "if" condition in particular : https://github.com/rollup/rollup/blob/592b9fed918ccc99d48ece917a70015ac1898e52/src/Module.ts#L368-L370

The modules are not external, so I think the issue is with `isIncluded()` and effectively the `ast.included` and `namespace.included` booleans are `false` in my logs.
Unfortunately, this is where my knowledge ends. The question is, should "rollup-plugin-styles" change something or should the lines above be changed ? ... and why (just curious) ?

I am not the maintainer of "rollup-plugin-styles", but I do use it in my frontend framework project (GladeJS).
I know this is on the hackish-side of Rollup usage, but I was about to release my CSS code-splitting feature. 😇

**Comment by lukastaegert** [comment]
I will have a look

**Comment by lukastaegert** [comment]
I created a fix at #4138, please verify that it really solves the issue and the plugin is now working as expected. Basically what is happening is that when you set a module to `no-treeshake`, now all imported modules will be included and may generate chunks.

**Comment by AurelienStebe** [comment]
Yes, I can confirm that the PR works, even in the middle of my complex Rollup config.
Thanks a lot, this is exactly what I need to trace the CSS dependencies. Excellent job, as always. 👍
