### ISSUE TITLE
How do I change the id that gets passed to the load hook?

### ISSUE THREAD

**Issue by Myrmod** [rollup/rollup#4132]
So I wrote a small plugin, which shall essentially replace a file.
```js
import fs from 'fs'

/**
 * @function replaceFiles
 * @param {({find: string, replacement: string})[]} replacements
 */
export default function replaceFiles(replacements) {
   if (!replacements?.length) {
      return null;
   }

   return {
      name: 'rollup-plugin-replace-files',
      load: async (id) => {
         const foundReplace = replacements.find((replacement) => replacement.find === id);

         if (foundReplace) {
            console.info(`replace "${foundReplace.find}" with "${foundReplace.replacement}"`);

            try {
               const code = fs.readFileSync(foundReplace.replacement, 'utf8');

               // return new file content
               return {
                  code,
                  // and return the new id!
               };
            } catch (err) {
               console.error(err);

               return null;
            }
         }

         return null;
      }
   }
}
```
This replaces the files content, but the imports of this new file aren't resolved correctly. So I would like to be able to return not only the code of the file, but its id as well. So that my imports are being resolved correctly.

### Feature Use Case
I think there is only one real use case for this. You could change a files "position" in your file tree from where to resolve its imports.

### Feature Proposal
In `node_modules/rollup/dist/rollup.d.ts:98` we got the corresponding interface. I would suggest to change it to:
```ts
export interface SourceDescription extends Partial<PartialNull<ModuleOptions>> {
	ast?: AcornNode;
	code: string;
        id? string;
	map?: SourceMapInput;
}
```

I hope this suggestion doesn't come from me missunderstanding something. I think this would solve my current problem and enable me to replace any files that are being imported while resolving their imports as well.

Kind regards

**Comment by lukastaegert** [comment]
The resolveId hook is the one you need to change ids. After an import is resolved to an id via this hook, it does not make a lot of sense to change it again IMO, especially since this may violate expectations of other plugins.

**Comment by Myrmod** [comment]
> The resolveId hook is the one you need to change ids. After an import is resolved to an id via this hook, it does not make a lot of sense to change it again IMO, especially since this may violate expectations of other plugins.

Yes I tried that:

```js
{
        name: 'testing',
        resolveId: (source, importer, options) => {
          console.log({ source, importer, options });

          const foundReplace = replacements.find((replacement) => replacement.find === source);

          if (foundReplace) {
            console.info(`replace "${foundReplace.find}" with "${foundReplace.replacement}"`);

            try {
              // return new file content
              return {
                id: foundReplace.replacement,
              };
            } catch (err) {
              console.error(err);

              return null;
            }
          }

          return null;
        },
      },
```

But `resolveId` doesnt "see" the files I have. So it seems not to be an option

**Comment by lukastaegert** [comment]
You can use [this.resolve](https://rollupjs.org/guide/en/#thisresolvesource-string-importer-string-options-skipself-boolean-custom-plugin-string-any--promiseid-string-external-boolean--absolute-modulesideeffects-boolean--no-treeshake-syntheticnamedexports-boolean--string-meta-plugin-string-any--null) to hook into the resolution process to find out what `id` an import would resolve to (do not forget to add `skipSelf: true`). Then you have the id that would be passed to the `load` hook and can decide what id you would rather want to have.

**Comment by Myrmod** [comment]
> You can use [this.resolve](https://rollupjs.org/guide/en/#thisresolvesource-string-importer-string-options-skipself-boolean-custom-plugin-string-any--promiseid-string-external-boolean--absolute-modulesideeffects-boolean--no-treeshake-syntheticnamedexports-boolean--string-meta-plugin-string-any--null) to hook into the resolution process to find out what `id` an import would resolve to (do not forget to add `skipSelf: true`). Then you have the id that would be passed to the `load` hook and can decide what id you would rather want to have.

Thank you I tried:

```js

async resolveId(source, importer, options) {
          const resolved = await this.resolve(source, importer, { skipSelf: true })
          console.log(resolved.id);
          ...
```

But I don't get the `App.tsx` either. So Do I have the wrong place? What would be the correct one?

**Comment by lukastaegert** [comment]
Maybe there is another plugin in front of your plugin that is resolving first. Try moving your plugin to first position.

**Comment by Myrmod** [comment]
> Maybe there is another plugin in front of your plugin that is resolving first. Try moving your plugin to first position.

even removing all other plugins doesn't change anything.

**Comment by Myrmod** [comment]
I just found the issue by slowly finding my way through the build. The issue lies not within RollUp.

I am using ViteJS, which as I have read was supposed to only use RollUps raw `resolveId` method. This is not the case. So there is some code running beforehand, which somehow filters my files. This is the working Plugin:

```js
export default function replaceFiles(replacements) {
   if (!replacements?.length) {
      return null;
   }

   return {
      name: 'rollup-plugin-replace-files',
      enforce: 'pre',
      async resolveId(source, importer) {
         const resolved = await this.resolve(source, importer, { skipSelf: true })

         const foundReplace = replacements.find((replacement) => replacement.find === resolved.id);

         if (foundReplace) {
            console.info(`replace "${foundReplace.find}" with "${foundReplace.replacement}"`);

            try {
               // return new file content
               return {
                  id: foundReplace.replacement,
               };
            } catch (err) {
               console.error(err);

               return null;
            }
         }

         return null;
      },
   }
}
```
