### ISSUE TITLE
Class method name and block scope

### ISSUE THREAD

**Issue by troch** [rollup/rollup#414]
When having some code like this (https://github.com/troch/path-parser/blob/master/modules/Path.js#L174-L178), rollup complains: `/home/thomas/Development/router5/node_modules/route-node/node_modules/path-parser/modules/Path.js: Duplicate declaration "match"`

It seems it happens if a class method and a variable inside its block scope have the same name.

```javascript
class A {
    b() {
        const b = 'b';
    }
}
```

**Comment by Rich-Harris** [comment]
It looks like this is a Babel bug – [this issue](https://phabricator.babeljs.io/T2805) seems relevant. `const` and `let` both result in errors, albeit different ones (`var` works fine):

```bash
# const
SyntaxError: const.js: "b" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)
  1 | class A {
  2 |   b () {
  3 |     const b = 'b';
  4 |   }
  5 | }
  6 |

# let
TypeError: let.js: Duplicate declaration "b"
  1 | class A {
  2 |   b () {
> 3 |     let b = 'b';
    |         ^
  4 |   }
  5 | }
  6 |
```

Without Babel, [this code](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20class%20A%20%7B%5Cn%20%20%20%20b()%20%7B%5Cn%20%20%20%20%20%20%20%20const%20b%20%3D%20'b'%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cnexport%20function%20C%20()%20%7B%7D%3B%5CnC.prototype.d%20%3D%20function%20d%20()%20%7B%5Cn%20%20let%20d%20%3D%2042%3B%5Cn%7D%22%7D%5D%7D) goes through Rollup just fine, as does the [original code in question](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20default%20class%20Path%20%7B%5Cn%20%20%20%20match(path%2C%20trailingSlash%20%3D%200)%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20trailingSlash%3A%20falsy%20%3D%3E%20non%20optional%2C%20truthy%20%3D%3E%20optional%5Cn%20%20%20%20%20%20%20%20let%20source%20%3D%20optTrailingSlash(this.source%2C%20trailingSlash)%5Cn%20%20%20%20%20%20%20%20%2F%2F%20Check%20if%20exact%20match%5Cn%20%20%20%20%20%20%20%20let%20match%20%3D%20this._urlMatch(path%2C%20new%20RegExp('%5E'%20%2B%20source%20%2B%20(this.hasQueryParams%20%3F%20'%5C%5C%5C%5C%3F.*%24'%20%3A%20'%24')))%5Cn%5Cn%20%20%20%20%20%20%20%20%2F%2F%20If%20no%20match%2C%20or%20no%20query%20params%2C%20no%20need%20to%20go%20further%5Cn%20%20%20%20%20%20%20%20if%20(!match%20%7C%7C%20!this.hasQueryParams)%20return%20match%5Cn%20%20%20%20%20%20%20%20%2F%2F%20Extract%20query%20params%5Cn%20%20%20%20%20%20%20%20let%20queryParams%20%3D%20parseQueryParams(path)%5Cn%20%20%20%20%20%20%20%20let%20unexpectedQueryParams%20%3D%20Object.keys(queryParams)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.filter(p%20%3D%3E%20this.queryParams.concat(this.queryParamsBr).indexOf(p)%20%3D%3D%3D%20-1%20)%5Cn%5Cn%20%20%20%20%20%20%20%20if%20(unexpectedQueryParams.length%20%3D%3D%3D%200)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Extend%20url%20match%5Cn%20%20%20%20%20%20%20%20%20%20%20%20Object.keys(queryParams)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.forEach(p%20%3D%3E%20match%5Bp%5D%20%3D%20queryParams%5Bp%5D)%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20return%20match%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%5Cn%20%20%20%20%20%20%20%20return%20null%5Cn%20%20%20%20%7D%5Cn%7D%22%7D%5D%7D) – so I'll close this.

**Comment by troch** [comment]
Thanks a lot. That makes sense, the npm dependency is still being built with babel 5, thus why I didn't experience the issue when building it on its own.
