### ISSUE TITLE
JavaScript heap out of memory due to memory leak

### ISSUE THREAD

**Issue by izevo** [rollup/rollup#4140]
- Rollup Version: 2.15.2
- Operating System (or Browser): any
- Node Version (if applicable): 14
- Link to reproduction (IMPORTANT, read below):

### Expected Behavior
When rollup watch restart, the modules of last time will be released.

### Actual Behavior
But it will be not. these modules are still keep by ARRAY_PROTOTYPE.
So it cause a memory leak.

I take memory snapshot before and after watch restart. Please see the picture below:

![image](https://user-images.githubusercontent.com/6970177/122039832-a567c180-ce09-11eb-8cdf-885747c6e8b3.png)

I read the code of ARRAY_PROTOTYPE, then find some code maybe cause memory leak.

`expressionsToBeDeoptimizedByKey` & `thisParametersToBeDeoptimized`

`ARRAY_PROTOTYPE` is a global variable, so the property`expressionsToBeDeoptimizedByKey` and  `thisParametersToBeDeoptimized` never clear. 

![image](https://user-images.githubusercontent.com/6970177/122038416-2756eb00-ce08-11eb-85fd-e0467ddb2d0d.png)

![image](https://user-images.githubusercontent.com/6970177/122038511-42295f80-ce08-11eb-9dcd-e747b5335bf7.png)

**Comment by lukastaegert** [comment]
Good catch! At the moment, these variables are actually supposed to be stateless, but as they are reusing the stateful `ObjectEntity`, this is obviously not the case. I will think about how to improve here, maybe an "immutable" flag for now.

**Comment by lukastaegert** [comment]
Can you verify if #4142 resolves this?

**Comment by izevo** [comment]
> Can you verify if #4142 resolves this?

I have tried and it can resolve this problem.
Please merge the branch and publish a version quickly, thanks~

**Comment by lukastaegert** [comment]
Done
