### ISSUE TITLE
Unexpected bare import statement for external dependency

### ISSUE THREAD

**Issue by sgb-io** [rollup/rollup#4143]
(Also asked in the Discord but no luck so far)

In this example project, you can see there are a few plugins and in particular, I have made `react` external. I used the `external` field to ensure it doesn't get included, plus used the `externalGlobals` plugin to map React to the externally-available version that it will later use.

The issue happens when using the `ReactJsonView` component from `react-json-view`. So far, I am unable to figure out what about this library or it's dependencies might cause this issue.

I tried setting `hoistTransitiveImports` to `false` but it does not change the result.

- Rollup Version: ^2.45.2
- Operating System (or Browser): Windows/macOS (issue occurs on both)
- Node Version (if applicable): 12.x
- Link to reproduction: https://github.com/sgb-io/rollup-externals-issue-example

### Expected Behavior

A bundle without an `import 'react';` statement at the top

### Actual Behavior

The bundle ends up with an `import 'react';` statement at the top

**Comment by lukastaegert** [comment]
Rollup does not know what happens inside the `react` import, so it assumes it has some side effects like declaring global variables. Use `treeshake.moduleSideEffects: "no-external"` to tell Rollup that this is not the case. https://rollupjs.org/guide/en/#treeshake

**Comment by sgb-io** [comment]
@lukastaegert thank you for the explanation, I can confirm that solves the issue. I am still a bit unclear why this statement appears (a React app with the same configuration but without this react-json-view library in the tree does not result in the same effect) - I guess it must be a certain import statement from some sub dependency.

Thank you for maintaining this project!
