### ISSUE TITLE
Maximum call stack error during parsing results in wrong error message

### ISSUE THREAD

**Issue by nolanlawson** [rollup/rollup#4150]
- Rollup Version: 9c436a7c7 (2.52.3)
- Operating System (or Browser): MacOS
- Node Version (if applicable): 12.22.1
- Link to reproduction: https://github.com/nolanlawson/rollup/commit/ab4c7fc22101bdcc14d6ac42a66a6931c01527a2

```shell
git clone git@github.com:nolanlawson/rollup.git
cd rollup
git checkout repro-max-call-stack
npm i
npm run test:quick
```

### Expected Behavior

When parsing a JavaScript source file containing enough nesting that Node throws a `RangeError: Maximum call stack size exceeded`, I would expect to see an error with that message (or similar message) thrown by `rollup.rollup()`.

### Actual Behavior

Instead of the `Maximum call stack size exceeded` error, the following error is thrown:

```
TypeError: Cannot destructure property 'column' of 'locate(...)' as it is undefined.
    at Module.addLocationToLogProps (/Users/nlawson/workspace/rollup/dist/shared/rollup.js:10413:15)
    at Module.error (/Users/nlawson/workspace/rollup/dist/shared/rollup.js:9887:14)
    at Module.tryParse (/Users/nlawson/workspace/rollup/dist/shared/rollup.js:10287:25)
    at Module.setSource (/Users/nlawson/workspace/rollup/dist/shared/rollup.js:10190:24)
    at ModuleLoader.addModuleSource (/Users/nlawson/workspace/rollup/dist/shared/rollup.js:19504:20)
    at async ModuleLoader.fetchModule (/Users/nlawson/workspace/rollup/dist/shared/rollup.js:19560:9)
    at async Promise.all (index 0)
```

The issue is that the actual max call stack error is caught and handled here:

https://github.com/rollup/rollup/blob/72125168ec6798b919a931742d2def5f4e69093b/src/Module.ts#L804-L811

But then the error-handling code itself runs into an error, because the `locate` function returns `undefined`:

https://github.com/rollup/rollup/blob/72125168ec6798b919a931742d2def5f4e69093b/src/Module.ts#L947

This behavior can be confusing, since it's not obvious that the actual problem is a max call stack error.

**Comment by lukastaegert** [comment]
Ah I see. So we implicitly assume that `acorn` only throws exceptions that reference a code location, and obviously this is wrong and we should check for this before trying to get a proper location.

**Comment by lukastaegert** [comment]
PR welcome if you want, otherwise I can have a look in the next days.

**Comment by semoal** [comment]
This could be solved just returning as fallback an empty object; probably column and line as undefined are checked elsewhere.

```ts
 let { column, line } = locate(code!, pos, { offsetLine: 1 }) || {}; 
```

Tried this on my local machine where I found this issue too, and works fine, I can create a pull request if you don't mind :)

**Comment by lukastaegert** [comment]
I would assume it creates a weird error message, though, at least in the CLI that always prints the location if present. Just not adding a location if there is none would be ideal.

**Comment by lukastaegert** [comment]
Would you still be willing to attempt a PR? Very nicely, @nolanlawson already created a test as his reproduction that you can use (except that I would add this one to the `misc` file instead of keeping it in its own file for now). If you are unsure, we can talk about details in the PR.

**Comment by semoal** [comment]
> Would you still be willing to attempt a PR? Very nicely, @nolanlawson already created a test as his reproduction that you can use (except that I would add this one to the `misc` file instead of keeping it in its own file for now). If you are unsure, we can talk about details in the PR.

Just opened a pull request Lukas, let's continue the conversation there if it needs some modifications =)
