### ISSUE TITLE
code incorrectly dropped

### ISSUE THREAD

**Issue by CarloCannas** [rollup/rollup#4161]
### Rollup Version

v2.50.5

### Operating System (or Browser)

n/a

### Link To Reproduction

https://rollupjs.org/repl/?version=2.50.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm4oKSU3QiU1Q24lMjAlMjBjb25zdCUyMG9iaiUyMCUzRCUyMCU3QiU1Q24lNUN0JTVDdHRlc3QoKSUyMCU3QiU1Q24lMjAlNUN0JTVDdCUyMGlmJTIwKHR5cGVvZiUyMG9iai50ZXN0Zm4lMjAlM0QlM0QlM0QlMjAlNUMlMjJmdW5jdGlvbiU1QyUyMiklN0JvYmoudGVzdGZuKCklN0QlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCUzQiU1Q24lMjAlMjAlNUNuJTIwJTIwcmV0dXJuJTIwb2JqJTNCJTVDbiU3RCU1Q24lNUNuKGFzeW5jJTIwZnVuY3Rpb24oKSU3QiU1Q24lNUN0Y29uc3QlMjBvYmolMjAlM0QlMjBhd2FpdCUyMGZuKCklM0IlNUNuJTVDdG9iai50ZXN0Zm4lMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCU1QyUyMnlheSU1QyUyMiklM0IlNUNuJTVDdG9iai50ZXN0KCklM0IlNUNuJTdEKSgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behaviour

The statement `if (typeof obj.testfn === "function"){obj.testfn()}` is present in output, running the code prints `yay` in the console. 

### Actual Behaviour

Rollup drops line 4, running the output code doesn't print anything in console.

Version 2.50.5 seems to be the one which introduced the issue: [on 2.50.4 line 4 isn't dropped](https://rollupjs.org/repl/?version=2.50.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm4oKSU3QiU1Q24lMjAlMjBjb25zdCUyMG9iaiUyMCUzRCUyMCU3QiU1Q24lNUN0JTVDdHRlc3QoKSUyMCU3QiU1Q24lMjAlNUN0JTVDdCUyMGlmJTIwKHR5cGVvZiUyMG9iai50ZXN0Zm4lMjAlM0QlM0QlM0QlMjAlNUMlMjJmdW5jdGlvbiU1QyUyMiklN0JvYmoudGVzdGZuKCklN0QlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCUzQiU1Q24lMjAlMjAlNUNuJTIwJTIwcmV0dXJuJTIwb2JqJTNCJTVDbiU3RCU1Q24lNUNuKGFzeW5jJTIwZnVuY3Rpb24oKSU3QiU1Q24lNUN0Y29uc3QlMjBvYmolMjAlM0QlMjBhd2FpdCUyMGZuKCklM0IlNUNuJTVDdG9iai50ZXN0Zm4lMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCU1QyUyMnlheSU1QyUyMiklM0IlNUNuJTVDdG9iai50ZXN0KCklM0IlNUNuJTdEKSgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

Is seems to be `async`/`await` releated: [removing `await`](https://rollupjs.org/repl/?version=2.50.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm4oKSU3QiU1Q24lMjAlMjBjb25zdCUyMG9iaiUyMCUzRCUyMCU3QiU1Q24lNUN0JTVDdHRlc3QoKSUyMCU3QiU1Q24lMjAlNUN0JTVDdCUyMGlmJTIwKHR5cGVvZiUyMG9iai50ZXN0Zm4lMjAlM0QlM0QlM0QlMjAlNUMlMjJmdW5jdGlvbiU1QyUyMiklN0JvYmoudGVzdGZuKCklN0QlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCUzQiU1Q24lMjAlMjAlNUNuJTIwJTIwcmV0dXJuJTIwb2JqJTNCJTVDbiU3RCU1Q24lNUNuKGFzeW5jJTIwZnVuY3Rpb24oKSU3QiU1Q24lNUN0Y29uc3QlMjBvYmolMjAlM0QlMjBmbigpJTNCJTVDbiU1Q3RvYmoudGVzdGZuJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZyglNUMlMjJ5YXklNUMlMjIpJTNCJTVDbiU1Q3RvYmoudGVzdCgpJTNCJTVDbiU3RCkoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) from the iife body produces the expected output, [adding `async` to `fn`](https://rollupjs.org/repl/?version=2.50.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmFzeW5jJTIwZnVuY3Rpb24lMjBmbigpJTdCJTVDbiUyMCUyMGNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTVDbiU1Q3QlNUN0dGVzdCgpJTIwJTdCJTVDbiUyMCU1Q3QlNUN0JTIwaWYlMjAodHlwZW9mJTIwb2JqLnRlc3RmbiUyMCUzRCUzRCUzRCUyMCU1QyUyMmZ1bmN0aW9uJTVDJTIyKSU3Qm9iai50ZXN0Zm4oKSU3RCU1Q24lNUN0JTVDdCU3RCU1Q24lNUN0JTdEJTNCJTVDbiUyMCUyMCU1Q24lMjAlMjByZXR1cm4lMjBvYmolM0IlNUNuJTdEJTVDbiU1Q24oYXN5bmMlMjBmdW5jdGlvbigpJTdCJTVDbiU1Q3Rjb25zdCUyMG9iaiUyMCUzRCUyMGZuKCklM0IlNUNuJTVDdG9iai50ZXN0Zm4lMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCU1QyUyMnlheSU1QyUyMiklM0IlNUNuJTVDdG9iai50ZXN0KCklM0IlNUNuJTdEKSgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) instead makes the issue appear again.

Seems a regression introduced by https://github.com/rollup/rollup/pull/4115

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #4162

**Comment by CarloCannas** [comment]
Wow, thank you for the really quick fix!

**Comment by CarloCannas** [comment]
@lukastaegert unfortunately it seems the fix doesn't work in every case: if I make `fn` `async` and put it in another module the issue comes back.

https://rollupjs.org/repl/?version=2.52.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmZuJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZmbi5qcyU1QyUyMiUzQiU1Q24lNUNuKGFzeW5jJTIwZnVuY3Rpb24oKSU3QiU1Q24lNUN0Y29uc3QlMjBvYmolMjAlM0QlMjBhd2FpdCUyMGZuKCklM0IlNUNuJTVDdG9iai50ZXN0Zm4lMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCU1QyUyMnlheSU1QyUyMiklM0IlNUNuJTVDdG9iai50ZXN0KCklM0IlNUNuJTdEKSgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwYXN5bmMlMjBmdW5jdGlvbiUyMGZuKCklN0IlNUNuJTVDdGNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTVDbiU1Q3QlNUN0dGVzdCgpJTIwJTdCJTVDbiU1Q3QlNUN0JTVDdGlmJTIwKHR5cGVvZiUyMG9iai50ZXN0Zm4lMjAlM0QlM0QlM0QlMjAlNUMlMjJmdW5jdGlvbiU1QyUyMiklN0JvYmoudGVzdGZuKCklN0QlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCUzQiU1Q24lNUNuJTVDdHJldHVybiUyMG9iaiUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Could you please give another look at it?

**Comment by lukastaegert** [comment]
Turns out it was only the `async` keyword, which triggered a different, albeit related issue. Fix at #4163.
