### ISSUE TITLE
Build Manifest for Layered Builds

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#4167]
### Feature Use Case

Currently RollupJS has to build based on either treating a module as external or having access to all module sources and running a single large monolitic build.

It would be nice if there were a middle ground, similar to traditional bundling approaches, where it could be possible to have multiple component build operations compose with a base application build, referencing the modules from the correct chunk files.

This would allow for saving work when only changing a single component to rebuild, and also assist users who don't want to externalise or split up chunks at certain levels, as it effectively provides an easy way to create bigger chunks as well.

### Feature Proposal

The proposal would be to have the ability to construct a build manifest, which represents the definition of each of the output files and chunks based on which files they contain and which export name maps they use.

For example, an application that builds react.js and lib.js might output the manifest:

dist/manifest.json
```js
{
  './chunk-sdf.js': {
    '../src/react.js': {
       'asdf': 'React',
       'p': 'default'
    },
    '../src/lib.js': {
      'asdf': 'Another'
    }
  }
}
```

Note that all paths in the manifest are relative to the manifest itself, so that references to the original files in the "src" folder require backtracking in the above example.

Each chunk consists of a number of module paths, each with their export name maps defined.

To apply the manifest for a subsequent build, consider building:

```js
import { React } from 'react';
import { Another } from './lib.js';
```

`'react'` would be resolved to `./src/react.js` which matches the manifest, as a result the build would treat the resolved file as `./dist/chunk-sdf.js` taking the `React` export to instead be the `asdf` export.

If an export were not matched, a warning could be thrown and say the original source used or the entire build could throw.

In terms of tree-shaking, private modules that don't expose all their exports might benefit from an option / way to flag that their exports are still public despite being in the same chunk.

The API would need a `manifest` output option to save the manifest to a file, and a `manifest` input option to read a manifest from a file. Both could be replaced by direct JSON for API usage. The above should fully describe most of the details of the implementation.

Feedback welcome, I may be able to work on this soon.

**Comment by lukastaegert** [comment]
So the idea is to not rebuild chunks if nothing in the chunk changes, but if a file in the chunk itself changes, then I do rebuild this entire chunk, right?
With regard to tree-shaking: If a new export from a given chunk is used, then this is not an unexpected scenario, we could just rebuild that chunk. Similar if an export is no longer used. 
That way, it would be zero config for the user but might rebuild a little more often than necessary. Then we could add options to always expose the exports of certain modules if it makes sense.
The question is how this internally ties into the tree-shaking and chunking algorithms (which again uses side effect information from the tree-shaking run to optimise chunking). You lose information about import side effects, but maybe this is not a problem. And if a dynamic import is added, the whole chunking may change.

**Comment by guybedford** [comment]
> So the idea is to not rebuild chunks if nothing in the chunk changes, but if a file in the chunk itself changes, then I do rebuild this entire chunk, right?

The chunk would never be rebuilt - instead the first build would be treated as the authoritative source for modules that it is defined to provide by the manifest. Because the chunks would be considered fixed distribution assets at the point of completion of the first build.

> we could just rebuild that chunk. Similar if an export is no longer used.

As a result these workflows wouldn't apply - so some marking mechanism or fallback would still need to apply.

> And if a dynamic import is added, the whole chunking may change.

Again this wouldn't apply - the fixed chunk boundaries defined by the first build would be set.

> You lose information about import side effects, but maybe this is not a problem. 

This is a good point, and is similar to normal external handling I suppose in that the default behaviour of treating the external as "potentially with side effects" should apply. There would be no source analysis of the original source, which should also lead to the performance cost saving here as well.

**Comment by guybedford** [comment]
In the use case that we were evaluating for this, it was decided that the overall approach was simply too much complexity for very little benefit since separate files are more compatible with import maps and general bundler workflows anyway.

Instead we are using separate entry points for all public modules and this provides more than adequate performance for the use case anyway.
