### ISSUE TITLE
'rollup@latest' is not in the npm registry

### ISSUE THREAD

**Issue by lmulin** [rollup/rollup#4169]
### Rollup Version

2.52.7

### Operating System (or Browser)

Windows 10

### Node Version (if applicable)

14.16.1

### Link To Reproduction

see Actual Behaviour

### Expected Behaviour

The latest version of rollup v2.57.2 can be downloaded via "npm install rollup". 

### Actual Behaviour

I get the error code 404 by "npm install rollup"

npm ERR! code E404
npm ERR! 404 Not Found - GET https://nexus.inet.bundesbank.de/repository/npm-public/rollup/-/rollup-2.52.7.tgz
npm ERR! 404
npm ERR! 404  'rollup@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Please help.

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).

Talk to whoever administers the npm proxy you're using.

**Comment by lukastaegert** [comment]
You should likely have a chat with whoever maintains nexus.inet.bundesbank.de/repository/npm-public
