### ISSUE TITLE
CLI prints warning when using custom arguments

### ISSUE THREAD

**Issue by jespertheend** [rollup/rollup#4171]
### Rollup Version

v2.43.1

### Operating System (or Browser)

macOS 11.4

### Node Version (if applicable)

v15.8.0

### Link To Reproduction

https://replit.com/@jespertheend/rollup-repro#rollup.config.js

### Expected Behaviour

No warning would be shown, since the custom argument is used in the build config

### Actual Behaviour

A warning is shown: "You have passed an unrecognized option"

**Comment by lukastaegert** [comment]
This is intended to alert you to possible typos. There are two ways to avoid this:
* You will not get a warning if your option starts with `--config`, e.g. `--configArg=foo`. This is described in this paragraph: https://rollupjs.org/guide/en/#configuration-files
* You can manually "clean up" the command line options in the rollup config for the same effect:
  ```
  export default args => {
    console.log("Custom arg: ",args.customArg)
    delete args.customArg
    return {
      input: 'src/main',
      output: {
        format: 'esm'
      },
    };
  };
  ```

**Comment by jespertheend** [comment]
Ah I wasn't aware of that. Thanks for the info!
