### ISSUE TITLE
Rollup omits JSX imports (perhaps cannot recognize imported components)

### ISSUE THREAD

**Issue by AnmSaiful** [rollup/rollup#4172]
### Rollup Version

v2.52.8

### Operating System (or Browser)

Windows and Linux

### Link To Reproduction

https://replit.com/@AnmSaiful/rollup-omits-jsx-imports

### Expected Behaviour

It should emit the `Rollup` component function to the `component.jsx` chunk, and import it in the `page.jsx` chunk.

```jsx
//→ entry.js:
import { H as Home } from './page.jsx';

Home();

//→ component.jsx:
function Rollup() {
  return <div>Rollup!</div>
}

export { Rollup as R };

//→ page.jsx:
import { R as Rollup } from './component.jsx';

function Home() {
  return <Rollup />;
}

export { Home as H };
```

### Actual Behaviour

It does not emit the `Rollup` component function to the `component.jsx` chunk and does not import it in the `page.jsx` chunk. Rather, it generates an empty chunk (i.e. `component.tsx`).

```jsx
//→ entry.js:
import { H as Home } from './page.jsx';

Home();

//→ component.jsx:


//→ page.jsx:
function Home() {
  return <Rollup />;
}

export { Home as H };
```

```
(!) Generated an empty chunk
component.jsx
```

**Comment by AnmSaiful** [comment]
Adding the source here for reference.

```jsx
// ---- component.jsx ----
export default function Rollup() {
  return <div>Rollup!</div>
}

// ---- page.jsx ----
import Rollup from "./component.jsx";

export default function Home() {
  return <Rollup />;
}

// ---- entry.js ----
import Home from "./page.jsx";

Home();

// ---- rollup.config.js ----
import jsx from "acorn-jsx";

export default {
  acornInjectPlugins: [ jsx() ],
  input: "entry",
  output: {
    format: "es",
    chunkFileNames: "[name]",
    manualChunks: {
      "component.jsx": [ "component.jsx" ],
      "page.jsx": [ "page.jsx" ],
    },
  },
};

// ---- package.json ----
{
  "name": "rollup-omits-jsx-imports",
  "dependencies": {
    "acorn-jsx": "^5.3.1",
    "react": "^17.0.2",
    "rollup": "^2.51.2"
  }
}
```

**Comment by lukastaegert** [comment]
Aren't you doing anything with the JSX, like rendering it?

**Comment by lukastaegert** [comment]
Even if you add the acorn plugin for JSX, Rollup will not understand the semantics of JSX i.e. that the tag names actually refer to local variables. You need a plugin similar to what was outlined here: https://github.com/rollup/rollup/issues/2822#issuecomment-486676465

An important part is this line `magicString.append(`;USED_JSX_NAMES(React,${usedNamesAndIds.join(',')});`);` which creates artificial usages of the variables in plain JavaScript.

**Comment by lukastaegert** [comment]
I believe this should be a good plugin implementation: https://github.com/sebastian-software/preppy/blob/master/src/jsxPlugin.js

**Comment by AnmSaiful** [comment]
@lukastaegert thank you so much, it works like a charm!

Special thanks to the author of the plugin @swernerx. You're absolutely brilliant!!

I've added it to the REPL so if anyone else goes through the issue, can have a quick workaround.

**Comment by AnmSaiful** [comment]
By the way, I'm trying to work with NextJS, and it is not working as expected. Seems need to wait until there's an official plugin for JSX.
