### ISSUE TITLE
BUG: Comment Parsing (if statment that contains only a comment)

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#4173]
### Rollup Version

latest

### Operating System (or Browser)

browser and nodejs 

### Node Version (if applicable)

latest

### Link To Reproduction

https://rollupjs.org/repl/?version=2.52.8&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbW9kdWxlXzEuanMnJTVDbiUyRiolMjBEWU5BTUlDJTIwSU1QT1JUUyU1Q24lMjAlMjAlMjBSb2xsdXAlMjBzdXBwb3J0cyUyMGF1dG9tYXRpYyUyMGNodW5raW5nJTIwYW5kJTIwbGF6eS1sb2FkaW5nJTVDbiUyMCUyMCUyMHZpYSUyMGR5bmFtaWMlMjBpbXBvcnRzJTIwdXRpbGl6aW5nJTIwdGhlJTIwaW1wb3J0JTIwbWVjaGFuaXNtJTVDbiUyMCUyMCUyMG9mJTIwdGhlJTIwaG9zdCUyMHN5c3RlbS4lMjAqJTJGJTVDbmlmJTIwKGRpc3BsYXlNYXRoKSUyMCU3QiU1Q24lNUN0aW1wb3J0KCcuJTJGbWF0aHMuanMnKS50aGVuKGZ1bmN0aW9uJTIwKG1hdGhzKSUyMCU3QiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKG1hdGhzLnNxdWFyZSg1KSklM0IlNUNuJTVDdCU1Q3Rjb25zb2xlLmxvZyhtYXRocy5jdWJlKDUpKSUzQiU1Q24lNUN0JTdEKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBzcXVhcmUlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBzcXVhcmUlN0QlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGN1YmUlMjAoeCUyMCklMjAlN0IlNUNuJTVDdHJldHVybiUyMHNxdWFyZSh4KSUyMColMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzcXVhcmUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZV8xLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwUGFyc2VyJTIwJTdCJTVDbiUyMCUyMGNvbnN0cnVjdG9yKG9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyRiUyRiUyME93biUyMG1pbmltYWwlMjBFdmVudEVtaXR0ZXIlMjBJbXBsJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwZXZlbnRFbWl0dGVyJTIwJTNEJTIwZ2V0RXZlbnRFbWl0dGVyKCklM0IlNUNuJTIwJTIwJTIwJTIwdGhpcy5vbiUyMCUzRCUyMGV2ZW50RW1pdHRlci5vbiUzQiU1Q24lMjAlMjAlMjAlMjB0aGlzLmVtaXQlMjAlM0QlMjBldmVudEVtaXR0ZXIuZW1pdCUzQiU1Q24lMjAlMjAlMjAlMjAlMkYlMkYlMjBPbmx5JTIwbmVlZGVkJTIwd2hlbiUyMGV4cG9zaW5nJTIwY2FsbGJhY2tzLiU1Q24lMjAlMjAlMjAlMjAlMkYlMkZPYmplY3QuYXNzaWduKHRoaXMlMkMlMjBldmVudEVtaXR0ZXIpJTNCJTVDbiUyMCUyMCUyMCUyMCUyRiUyRiUyMEltcGwlNUNuJTIwJTIwJTIwJTIwdGhpcy5vcHRpb25zJTIwJTNEJTIwbWVyZ2VPcHRpb25zKERFRkFVTFRfT1BUSU9OUyUyQyUyMG9wdGlvbnMpJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjB0aGlzLnRyZWVBZGFwdGVyJTIwJTNEJTIwdGhpcy5vcHRpb25zLnRyZWVBZGFwdGVyJTNCJTVDbiUyMCUyMCUyMCUyMHRoaXMucGVuZGluZ1NjcmlwdCUyMCUzRCUyMG51bGwlM0IlNUNuJTIwJTIwJTIwJTIwJTJGJTJGJTIwVGVzdHMlMjBkbyUyMG5vdCUyMHJ1biUyMGlmJTIwdGhpcyUyMGlzJTIwbm90JTIwSW1wbCU1Q24lMjAlMjAlMjAlMjBpZiUyMCh0aGlzLm9wdGlvbnMuc291cmNlQ29kZUxvY2F0aW9uSW5mbyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGKiolNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwKiUyMHNldHMlMjBzdGFydCUyMGVuZCUyMGFzJTIwYWxzbyUyMHRyZWVBZGFwdGVyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMColMjBub2RlU291cmNlQ29kZUxvY2F0aW9uJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMColMjAlNDBwYXJhbSUyMCU3QiolN0QlMjBwYXJzZXIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwKiUyMCU0MHJldHVybnMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkZhZGRMb2NhdGlvbkluZm9QYXJzZXJTdGF0ZSh0aGlzKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkZMb2NhdGlvbkluZm9QYXJzZXJNaXhpbih0aGlzKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTVDbiUyMCUyMCUyMCUyMGlmJTIwKHRoaXMub3B0aW9ucy5vblBhcnNlRXJyb3IpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMCUyMCUyMEVycm9yUmVwb3J0aW5nUGFyc2VyTWl4aW4odGhpcyUyQyUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkYlMjAlMjAlMjAlMjAlMjBvblBhcnNlRXJyb3IlM0ElMjB0aGlzLm9wdGlvbnMub25QYXJzZUVycm9yJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMCUyMCUyMCU3RCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwR2V0cyUyMHNldCUyMGJ5JTIwLi4lMkZsb2NhdGlvbi1pbmZvJTJGcGFyc2VyLW1peGluJTIwX2Jvb3RzdHJhcCU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0aGlzLm9uUGFyc2VFcnJvciUyMCUzRCUyMHRoaXMub3B0aW9ucy5vblBhcnNlRXJyb3IlM0IlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCU1Q24lN0QlNUNubmV3JTIwUGFyc2VyKCklM0IlNUNuJTJGJTJGZXhwb3J0JTIwJTdCJTIwUGFyc2VyJTIwJTdEJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmFtZCUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behaviour

    if (this.options.sourceCodeLocationInfo) {
      /**
       * sets start end as also treeAdapter
       * nodeSourceCodeLocation
       * @param {*} parser
       * @returns
       */
      //addLocationInfoParserState(this);
      //LocationInfoParserMixin(this);
    }

### Actual Behaviour

      if (this.options.sourceCodeLocationInfo) ;

**Comment by frank-dspeed** [comment]
even more isolated example:

https://rollupjs.org/repl/?version=2.52.8&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbW9kdWxlXzEuanMnJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlXzEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTVDbiUyMCUyMCUyMCUyMGlmJTIwKG9wdGlvbnMuc291cmNlQ29kZUxvY2F0aW9uSW5mbyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGKiolNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwKiUyMHNldHMlMjBzdGFydCUyMGVuZCUyMGFzJTIwYWxzbyUyMHRyZWVBZGFwdGVyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMColMjBub2RlU291cmNlQ29kZUxvY2F0aW9uJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMColMjAlNDBwYXJhbSUyMCU3QiolN0QlMjBwYXJzZXIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwKiUyMCU0MHJldHVybnMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkZhZGRMb2NhdGlvbkluZm9QYXJzZXJTdGF0ZSh0aGlzKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkZMb2NhdGlvbkluZm9QYXJzZXJNaXhpbih0aGlzKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmFtZCUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by lukastaegert** [comment]
Your code does not contain side effects, that is why statements are simplified. If you want comments to be treated like side effects, I fear you need to turn off tree-shaking. The generated code looks valid and equivalent to the source  to me.

**Comment by lukastaegert** [comment]
```js
if (expression);
```

is indeed valid JavaScript. It could be further simplified to

```js
expression;
```

but that is not implemented.

**Comment by frank-dspeed** [comment]
@lukastaegert i do not depend on this but it broke my eslint and i tought it would be a bug but if thats not one i am fine with that.

still leaves the question why other comments do not get removed and this one gets removed.
