### ISSUE TITLE
Wrong system format output after tree shaking if export is a ternary expression

### ISSUE THREAD

**Issue by alvinleung1996** [rollup/rollup#4201]
### Rollup Version

v2.56.0

### Operating System (or Browser)

Debian 10

### Link To Reproduction

https://rollupjs.org/repl/?version=2.56.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYSUyMCUzRCUyMHdpbmRvdy5jb25maWclMjAlM0YlMjAxJTIwJTNBJTIwMiU1Q25leHBvcnQlMjBjb25zdCUyMGIlMjAlM0QlMjB0cnVlJTIwJTNGJTIwMSUyMCUzQSUyMDIlNUNuZXhwb3J0JTIwY29uc3QlMjBjJTIwJTNEJTIwZmFsc2UlMjAlM0YlMjAxJTIwJTNBJTIwMiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnN5c3RlbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behaviour

```javascript
System.register('myBundle', [], function (exports) {
	'use strict';
	return {
		execute: function () {

			const a = exports('a', window.config ? 1 : 2);
			const b = exports('b', 1);
			const c = exports('c', 2);

		}
	};
});
```

### Actual Behaviour

```javascript
System.register('myBundle', [], function (exports) {
	'use strict';
	return {
		execute: function () {

			const a = exports('a', window.config ? 1 : 2);
			const b = 1 ;
			const c = 2);

		}
	};
});
```

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #4202
