### ISSUE TITLE
How to turn off treeshaking in manualChunks?

### ISSUE THREAD

**Issue by ruleeeer** [rollup/rollup#4207]
Sorry, I don't want to ask a question here, but I can't open https://is.gd/rollup_chat and I see that stackoverflow didn't find my question.
What I want to know is how can I turn off `treeshaking` in `manualChunks`, for example if I use vue and add vue to manualChunks
+ app.js
``` js
import {createApp} from 'vue'
let app = createApp({...});
```

+ rollup.config.js
``` js
export default {
  inpot: ...
  output: {
    ...
    manualChunks:{
       'vue':['vue'],
     }
  }
}
```
Then I found that the generated vue chunk only exported the method createApp,because i use createApp only
 I don't want the content in the manualChunk to be treeshaken, but no matter I use command line `--no-treeshake` or specify `treeshake: false` in the configuration file, it doesn't work, could you tell me how to do it to achieve the effect?
I want to package a shared vue for remote app use, just like ModuleFederation

![image](https://user-images.githubusercontent.com/70385062/129759550-8a218cf5-c145-4d8d-b3fb-2c197129147e.png)

**Comment by lukastaegert** [comment]
Vue needs to be an entry point for all exports to be retained, not a manual chunk. Manual chunks should only ever be a last resort feature as they can change output semantics.
