### ISSUE TITLE
Default exports with parens fails

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#421]
Via https://github.com/rollup/rollup-plugin-babel/issues/28.

[This fails](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20foo%20from%20'.%2Ffoo.js'%3B%5Cnfoo()%3B%22%7D%2C%7B%22name%22%3A%22foo.js%22%2C%22code%22%3A%22%2F%2F%20remove%20the%20parens%20and%20it%20works%5Cnexport%20default%20(function%20()%20%7B%5Cn%20%20console.log(%5C%22Hi!%5C%22)%3B%5Cn%7D)%22%7D%5D%7D):

```js
// main.js
import foo from './foo.js';
foo();

// foo.js
export default (function () {
  console.log("Hi!");
})
```

Remove the parens around the default export and it works fine. It appears to be specific to functions ([this works fine](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20foo%20from%20'.%2Ffoo.js'%3B%5Cnconsole.log(foo)%3B%22%7D%2C%7B%22name%22%3A%22foo.js%22%2C%22code%22%3A%22export%20default%20(42)%22%7D%5D%7D)).

This is particularly problematic because this is how Babel transpiles arrow function expressions.

**Comment by Pauan** [comment]
I just upgraded to version 0.24.1, and it's fixed! Thanks a lot!
