### ISSUE TITLE
rollup/plugin-commonjs improperly orders execution of code from protobufjs

### ISSUE THREAD

**Issue by kskalski** [rollup/rollup#4216]
### Rollup Version

rollup 2.56.3, rollup/plugin-commonjs 20.0.0

### Operating System (or Browser)

Windows / Chrome

### Node Version (if applicable)

v12.20.1

### Link To Reproduction

https://github.com/kskalski/rollup-protobufjs

### Expected Behaviour

Code runs without error, in particular code from protobufjs [object.js](https://github.com/protobufjs/protobuf.js/blob/d13d5d5688052e366aa2e9169f50dfca376b32cf/src/object.js) is executed before its reference in [field.js](https://github.com/protobufjs/protobuf.js/blob/d13d5d5688052e366aa2e9169f50dfca376b32cf/src/field.js)  thus avoiding use of uninitialized variable ``ReflectionObject``

### Actual Behaviour

Error during runtime

```
field.js:6 Uncaught TypeError: Cannot read property 'prototype' of undefined
   at field.js:6
   at index.umd.js:4
   at index.umd.js:5
```

**Comment by kskalski** [comment]
In fact it's related to circular dependency reported by rollup:
``node_modules\protobufjs\src\object.js -> node_modules\protobufjs\src\util.js -> node_modules\protobufjs\src\type.js -> node_modules\protobufjs\src\namespace.js -> node_modules\protobufjs\src\object.js``

**Comment by kskalski** [comment]
Closing in favor of https://github.com/rollup/plugins/issues/988 since I believe its fix is entirely in a scope of the commonjs plugin

**Comment by lukastaegert** [comment]
We are finalizing a new version of the commonjs plugin in rollup/plugins#1038. It is pre-published as `@rollup/plugin-commonjs@beta`. Please give it a spin to see if it resolves the issue, ideally without additional config needed.
