### ISSUE TITLE
Rollup creates an UnhandledPromiseRejectionWarning when module parsing fails

### ISSUE THREAD

**Issue by kherock** [rollup/rollup#4217]
### Rollup Version

v2.56.3

### Operating System (or Browser)

macOS, Debian

### Node Version (if applicable)

12,14

### Link To Reproduction

https://replit.com/@KyleHerock/rollup-unhandled-rejection

### Expected Behaviour

When I catch the error, Node.js shouldn't warn or exit about an unhandled rejection error:

```console
$ npx rollup --version & node -r trace-unhandled/register .
Could not resolve './foo' from src/main.js
Error has been handled

exit status 1
```

### Actual Behaviour

Rollup does handle the errors elsewhere, but the `Promise.all` here needs a no-op catch handler:

https://github.com/rollup/rollup/blob/05fe93d235b732905d007dce4e273e8a8a9f6aaa/src/ModuleLoader.ts#L340-L344

This result is that an unhandled rejection warning is printed before Node exits:

```console
$ npx rollup --version & node -r trace-unhandled/register .
Could not resolve './foo' from src/main.js
Error has been handled
(node:692) UnhandledPromiseRejectionWarning
[ Stacktrace altered by https://github.com/grantila/trace-unhandled ]
Error: Could not resolve './foo' from src/main.js
    ==== Promise at: ==================
    at Promise.then (<anonymous>)
    at ModuleLoader.fetchModule (/home/runner/rollup-repro/node_modules/rollup/dist/shared/rollup.js:19767:12)
    at async Promise.all (index 0)

    ==== Error at: ====================
    at error (/home/runner/rollup-repro/node_modules/rollup/dist/shared/rollup.js:151:30)
    at ModuleLoader.handleResolveId (/home/runner/rollup-repro/node_modules/rollup/dist/shared/rollup.js:19862:24)
    at /home/runner/rollup-repro/node_modules/rollup/dist/shared/rollup.js:19856:26

    ==== Shared trace: ================

exit status 1
```

The CLI doesn't suffer from this problem since it calls `process.exit(1)` before Node has a chance to send out the warning.

**Comment by lukastaegert** [comment]
Makes sense. Would you create a small PR to fix this? I do not think we can really test it, though.
