### ISSUE TITLE
Side-effects and cyclical call expressions

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#422]
#400 fixed #397, but at the cost of _always_ marking functions that call either other recursively as having side-effects, whether or not they do. Compare:
- [recursive](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20even%20%7D%20from%20'.%2Feven-odd.js'%3B%5Cn%5Cneven%28%205%20%29%3B%20%2F%2F%20has%20no%20side-effects%2C%20so%20should%20be%20removed%22%7D%2C%7B%22name%22%3A%22even-odd.js%22%2C%22code%22%3A%22export%20function%20even%20%28%20n%20%29%20%7B%5Cn%5Ctreturn%20n%20%3D%3D%3D%200%20%7C%7C%20odd%28%20n%20-%201%20%29%3B%5Cn%7D%5Cn%5Cnexport%20function%20odd%20%28%20n%20%29%20%7B%5Cn%5Ctreturn%20n%20!%3D%3D%200%20%26%26%20even%28%20n%20-%201%20%29%3B%5Cn%7D%22%7D%5D%7D)
- [non-recursive](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20even%20%7D%20from%20'.%2Feven-odd.js'%3B%5Cn%5Cneven%28%205%20%29%3B%20%2F%2F%20has%20no%20side-effects%2C%20so%20should%20be%20removed%22%7D%2C%7B%22name%22%3A%22even-odd.js%22%2C%22code%22%3A%22export%20function%20even%20%28%20n%20%29%20%7B%5Cn%5Ctreturn%20n%20%3D%3D%3D%200%20%7C%7C%20odd%28%20n%20-%201%20%29%3B%5Cn%7D%5Cn%5Cnexport%20function%20odd%20%28%20n%20%29%20%7B%5Cn%5Ctreturn%20n%20%25%202%3B%5Cn%7D%22%7D%5D%7D)

The output of the second is empty, as it should be.

Realistically, this is a complete edge case, but it would be nice to detect it and handle it anyway.

**Comment by mbostock** [comment]
This pattern occurs quite a bit in D3. For example, in [interpolateRgb](https://github.com/d3/d3-interpolate/blob/master/src/rgb.js). Here’s a minimalist example:

```js
export default (function interpolateGamma(gamma) {
  function interpolate(a, b) {};
  interpolate.gamma = interpolateGamma;
  return interpolate;
})(1);
```

Related #305.

**Comment by Rich-Harris** [comment]
This was fixed recently, closing
