### ISSUE TITLE
Rollup can generate chunks that are non-importable in a module context

### ISSUE THREAD

**Issue by danielroe** [rollup/rollup#4222]
### Rollup Version

v2.56.3

### Operating System (or Browser)

MacOS

### Node Version (if applicable)

v14.17.3

### Link To Reproduction

https://replit.com/@DanielRoe1/rollup-repro#src/index.mjs

### Expected Behaviour

I would expect this generated virtual module chunk to be imported successfully. Perhaps the `#` character could be stripped.

### Actual Behaviour

The hash character splits the import (note: only from within an `.mjs` file). It fails with:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/runner/rollup-repro/dist/_virtual_' imported from /home/runner/rollup-repro/dist/index.mjs
```

This is despite the fact that the import (and filename) is `./_virtual_#test.mjs`.

**Note**: I've filed this against `rollup/rollup` as although the particular example is using the virtual module I can imagine a situation where a valid import is structured (say within TS) that outputs to `.mjs` and therefore produces non-runnable JS.

**Comment by lukastaegert** [comment]
Interestingly, this appears to be a quirk of the Node ES module support that is not shared by CommonJS Node. Now I am not sure how to best approach this:
- We could just add hashes to the list of forbidden characters https://github.com/rollup/rollup/blob/81fa9e9812be882e8ca791c0bd4314d23f0d5640/src/utils/sanitizeFileName.ts#L7 . But this might break legitimate usages of the hash character for others (not sure how big the risk is, though).
- We could limit forbidding hashes to ESM output as the filename sanitizer is only created once here where we know the output format https://github.com/rollup/rollup/blob/81fa9e9812be882e8ca791c0bd4314d23f0d5640/src/utils/options/normalizeOutputOptions.ts#L64-L69 . Again, this would also apply when generating browser ES modules, but also the question is how important this is.
- Everyone could build their own filename sanitizer via the https://rollupjs.org/guide/en/#outputsanitizefilename option if the current one is not good enough
