### ISSUE TITLE
Newbie here: UX tip

### ISSUE THREAD

**Issue by rowild** [rollup/rollup#4226]
I usually work with webpack. Trying rollup no and would like to give you y initial feedback.
What cost me a lot of time was to figure out on which server the dev page is delivered. When running "npm run dev" a little window pops up for a VERY VERY short time in the terminal which looks like the info that would be needed. I had to record my screen and play the video slowly to find out that this was indeed the info about localhost:5000.

For a newbie this is really really bad. If I hadn't had the time, I would neither have recorded it nor tested rollup further.

This is bad UX/UI design. I strongly suggest to change that...

Thank you!

**Comment by shellscape** [comment]
Rollup doesn't ship with a dev server. Perhaps you're using a third party app/plugin and meant to give that project this feedback?

**Comment by rowild** [comment]
Thank you for your fast feedback!

It's one of the 2 projects that the docu recommends to check out. If that is the case then I would still suggest to add more info at that very place where those 2 projects are mentioned. 

This is shown in the terminal:

![Bildschirmfoto 2021-09-08 um 16 16 44](https://user-images.githubusercontent.com/213803/132526452-ea8d225f-6738-4178-8a80-4ffc1c90706b.png)

**Comment by shellscape** [comment]
Recommending ≠ supporting. We're not in the business of supporting third party projects. You'll find this is common in the Node ecosystem - you'll need to go to the project repositories/pages for the thing you're using. `serve` has a pretty robust community and I would suggest opening a new issue with that project.

**Comment by rowild** [comment]
"recommending is not supporting" - well: my recommendation IS meant as support. But if you prefer to ignore feedback and just provide time consuming, needless answers - even though you DO ask for feedback - then go ahead.

Just because sth is common it doesn't mean it is good and should stay the way it is. "Covid is common nowadays." "CO2 is very common nowadays"... 

Providing a docu that leads to troubles is bad. That's a fact. You can ignore that. That would be a fact too. But hey, not my project...

**Comment by shellscape** [comment]
@rowild since it seems like you might be new to the vast world of Open Source Software and interacting with OSS communities, I would suggest reviewing the following two publications:

https://css-tricks.com/open-source-etiquette-guidebook/
https://liberamanifesto.com/
