### ISSUE TITLE
How to know where an asset came from?

### ISSUE THREAD

**Issue by tanekim77** [rollup/rollup#4229]
Suppose I have two files with same name in folder A and A/B.
A/a.scss
A/B/a.scss

If I pass these two files directly as input, total four files are generated, a.123c4.js, a.df343.css, a.35353.js, and a.dfsdf.css.
Suppose I created a custom plugin, then in generateBundle menthod, 
![image](https://user-images.githubusercontent.com/20119808/134475683-d978fdfa-ca9a-4f45-b430-9b51946e5fdd.png)
The bundle is an object with fileName key and either an asset or chunk object as value. 
An asset object structure looks like this
![image](https://user-images.githubusercontent.com/20119808/134475981-fbfb79b6-8aa1-453f-8d81-52c17ab18eeb.png)
Looking at this structure, suppose I am looking at an asset with a fileName 'assets/a.df343.css' and name : 'a.css'. How do I know from which of the two files a.123c4.js and a.35353.js the css file is related to?

It would be awesome if there is a field like filePath: 'A/B/a.scss' in the asset structure in generateBundle method so that I can at least know this asset came from this file. Currently, there is only name field, which would only show 'a.scss', and I have no idea which of A/a.scss or B/a.scss it came from

**Comment by FoxDaxian** [comment]
maybe this is conflict with purpose of rollup.
maybe you can set unique filename to diff them.
or maybe your css-loader not expose the info~

this is demo for you below:
```javascript
// rollup plugins option
plugins: [
        {
            load(id) {
                if (id.endsWith('.css')) {
                    const referenceId = this.emitFile({
                        type: 'asset',
                        name: path.basename(id),
                        source: fs.readFileSync(id),
                    });
                    console.log(referenceId);
                    return `export default import.meta.ROLLUP_FILE_URL_${referenceId};`;
                }
            },
            generateBundle(a, b) {
                console.log(b);
            },
        }
]
```

this is output by above:

![image](https://user-images.githubusercontent.com/19708789/134614106-5a6bd832-4ace-494d-bb10-9b76ccae16ae.png)

![image](https://user-images.githubusercontent.com/19708789/134614186-07f5baf9-bb65-4e02-a199-03a67cbf34c1.png)

the file-path is obvious~

**Comment by tanekim77** [comment]
Thanks, it helped!
