### ISSUE TITLE
Can't use typescript config

### ISSUE THREAD

**Issue by elonzh** [rollup/rollup#4232]
### Rollup Version

2.57.0

### Operating System (or Browser)

Windows 11 21H2(Build 22000.194)

### Node Version (if applicable)

v14.17.1

### Link To Reproduction

@rollup/plugin-typescript@^8.2.5

### Expected Behaviour

Build with typescript config

### Actual Behaviour

❯ rollup --config rollup.config.ts --configPlugin typescript
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
rollup.config.ts (5:11)
3: import { RollupOptions } from 'rollup'
4:
5: let bundles: Array<RollupOptions> = []
...

**Comment by FoxDaxian** [comment]
Could you share you project online use [replit](https://replit.com/) or something like replit else?

**Comment by elonzh** [comment]
Seems "rollup.config.ts" should be included in `tsconfig.json`(the `include` key) which vite not.
