### ISSUE TITLE
`treeshake` is not working when `moduleSideEffects: false`

### ISSUE THREAD

**Issue by loynoir** [rollup/rollup#4239]
### Rollup Version

v2.58.0

### Operating System (or Browser)

ArchLinux

### Link To Reproduction

https://github.com/loynoir/reproduce-rollup-4239

### Input
```js
import { isNode } from "~lib";

if (isNode) {
  console.log(true);
} else {
  console.log(false);
}
```

### Expected Behaviour

```sh
# // moduleSideEffects: false
$ env WORKAROUND_ROLLUP_4239=1 rollup -c

index.js → stdout...
{
  console.log(true);
}
```

### Actual Behaviour

```sh
# moduleSideEffects: false
$ env rollup -c

index.js → stdout...
const isNode = true;

if (isNode) {
  console.log(true);
} else {
  console.log(false);
}
```

**Comment by loynoir** [comment]
@FoxDaxian 
I'm confused.

Is there similar flag, which can do below?
- shake away falsy code block if used
```js
{
  console.log(false);
}
``` 
- shake away import statement if not used, like `moduleSideEffects: false`

**Comment by loynoir** [comment]
Currently my workaround is
- `moduleSideEffects: false` for most cases
- hard coded pattern to match condition-shake-modules, and remove `moduleSideEffects` field

The hard coded part seems not very graceful. 🤔

**Comment by FoxDaxian** [comment]
`moduleSideEffects` indicate rollup can shake all unused code and do not care side effects~
and `tree shake` or `dce` run rely static analyze, not dynamic~

This is my thought about you question~
