### ISSUE TITLE
The rollup's installation folder, namely node_modules/rollup/dist/es/ doesn't contain the package.json file

### ISSUE THREAD

**Issue by costingeana** [rollup/rollup#4253]
### Expected Behavior / Situation

Rollup `v 2.58.1`

The rollup's installation folder, namely `node_modules/rollup/dist/es/` should contain a `package.json` file; the content of the package.json file is `{"type":"module"}`. 
This should happen according to https://github.com/rollup/rollup/blob/master/build-plugins/emit-module-package-file.ts#L6 

### Actual Behavior / Situation

Rollup `v 2.58.1`

The rollup's installation folder, namely `node_modules/rollup/dist/es/` does not contain anymore a `package.json` file; the previous version (2.58.0) had a `node_modules/rollup/dist/es/package.json` file.

The missing of the `package.json` file causes an error like the following:

> export { version as VERSION, defineConfig, rollup, watch } from './shared/rollup.js';
^^^^^^
 
SyntaxError: Unexpected token 'export'
at compileFunction (<anonymous>)
at Object.compileFunction (node:vm:352:18)
at wrapSafe (node:internal/modules/cjs/loader:1031:15)
at Module._compile (node:internal/modules/cjs/loader:1065:27)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)
at ESMLoader.import (node:internal/modules/esm/loader:281:24)
at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)

The code that generates the above error (a commonjs module), dynamically imports rollup: it loads the rollup's esm output from commonjs via `import()`:
`const { rollup } = await import('rollup');`

Below, you can see the content of the published packages for versions `2.58.0` and `2.58.1`.

`npm pack rollup@2.58.0`

> npm notice
npm notice 📦  rollup@2.58.0
npm notice === Tarball Contents ===
npm notice 222.6kB CHANGELOG.md
npm notice 35.6kB  LICENSE.md
npm notice 8.8kB   README.md
npm notice 74.2kB  dist/bin/rollup
npm notice 17B     dist/es/package.json
npm notice 391.6kB dist/es/rollup.browser.js
npm notice 335B    dist/es/rollup.js
npm notice 869.6kB dist/es/shared/rollup.js
npm notice 137.5kB dist/es/shared/watch.js
npm notice 542B    dist/loadConfigFile.js
npm notice 391.0kB dist/rollup.browser.js
npm notice 1.5MB   dist/rollup.browser.js.map
npm notice 25.4kB  dist/rollup.d.ts
npm notice 560B    dist/rollup.js
npm notice 120.9kB dist/shared/index.js
npm notice 22.5kB  dist/shared/loadConfigFile.js
npm notice 8.0kB   dist/shared/mergeOptions.js
npm notice 870.9kB dist/shared/rollup.js
npm notice 13.6kB  dist/shared/watch-cli.js
npm notice 9.7kB   dist/shared/watch.js
npm notice 5.4kB   package.json
npm notice === Tarball Details ===
npm notice name:          rollup
npm notice version:       2.58.0
npm notice filename:      rollup-2.58.0.tgz
npm notice package size:  1.1 MB
npm notice unpacked size: 4.7 MB
npm notice shasum:        a643983365e7bf7f5b7c62a8331b983b7c4c67fb
npm notice integrity:     sha512-NOXpusKnaRpbS[...]a887gZJ1AiXvw==
npm notice total files:   21
npm notice
rollup-2.58.0.tgz

`npm pack rollup`

> npm notice
npm notice 📦  rollup@2.58.1
npm notice === Tarball Contents ===
npm notice 222.8kB CHANGELOG.md
npm notice 35.6kB  LICENSE.md
npm notice 8.8kB   README.md
npm notice 74.2kB  dist/bin/rollup
npm notice 391.7kB dist/es/rollup.browser.js
npm notice 335B    dist/es/rollup.js
npm notice 869.8kB dist/es/shared/rollup.js
npm notice 137.5kB dist/es/shared/watch.js
npm notice 542B    dist/loadConfigFile.js
npm notice 391.1kB dist/rollup.browser.js
npm notice 1.5MB   dist/rollup.browser.js.map
npm notice 25.4kB  dist/rollup.d.ts
npm notice 560B    dist/rollup.js
npm notice 120.9kB dist/shared/index.js
npm notice 22.5kB  dist/shared/loadConfigFile.js
npm notice 8.0kB   dist/shared/mergeOptions.js
npm notice 871.1kB dist/shared/rollup.js
npm notice 13.6kB  dist/shared/watch-cli.js
npm notice 9.7kB   dist/shared/watch.js
npm notice 5.4kB   package.json
npm notice === Tarball Details ===
npm notice name:          rollup
npm notice version:       2.58.1
npm notice filename:      rollup-2.58.1.tgz
npm notice package size:  1.1 MB
npm notice unpacked size: 4.7 MB
npm notice shasum:        b9a0f9e601129d9a4686b7ec3159095f7a73825f
npm notice integrity:     sha512-dNhchlN/3k3EK[...]oR+BgWNjTEYLA==
npm notice total files:   20
npm notice

### Modification Proposal

I'm not sure if the current behavior is intended, or the `node_modules/rollup/dist/es/package.json` file wasn't published by mistake. 
IMHO, a new rollup's version should be published, and it should contain the aforementioned file.

**Comment by Jack-Works** [comment]
Still cannot import `rollup/dist/loadConfigFile.js` in ES Module with Node 17.0.1 and rollup v2.26.0
