### ISSUE TITLE
Support change the root variable name while iife format.

### ISSUE THREAD

**Issue by fanmingfei** [rollup/rollup#4261]
### Feature Use Case

Some platform like WeChat Mini Game, not have this variable. So we need to set iife root variable name.

```js
export default {
  output: {
    IIFERootVariableName: 'window'
  }
}
```

rollup -n "a.b.c"

old output:
```js
this.a = this.a || {};
this.a.b = this.a.b || {};
this.a.b.c = ...
```
new output:
```js
window.a = window.a || {};
window.a.b = window.a.b || {};
window.a.b.c = ...
```

### Feature Proposal

https://github.com/rollup/rollup/blob/66b3139b4be1d52342088dc00ef89fb9412f639a/src/finalisers/iife.ts#L103

**Comment by FoxDaxian** [comment]
I not sure what is your scene. but I think let rollup implement is unnecessary~

and maybe this way works for you~

```javascript
const outputOptions = {
    footer: 'window.a.b = c;',
    dir: './dist',
    format: 'iife',
    name: 'c',
};
```

output like this below:

```javascript
var c = (function () {
    'use strict';
    var index = {
    };

    return index;

}());
window.a.b = c;
```
hope can help you~

**Comment by fanmingfei** [comment]
@FoxDaxian thanks
