### ISSUE TITLE
support preserving dynamic import() for non-string argument in cjs format

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#4263]
### Feature Use Case

Currently rollup only supports loading `cjs` plugins via the CLI `--plugin` option due to its explicit use of `require()` in the implementation.  I've created a working patch (not included) for rollup to support either loading `cjs` or `esm` format plugins from the CLI. This patch relies on the use of dynamic `import()`.  Curiously, I can build this new version of rollup using esbuild, but not rollup itself. This is due to rollup transforming `import()` to `require()` for `-f cjs` which is the output format of the rollup CLI.

Here's a stripped down version of a `cjs`/`esm` plugin loader for illustrative purposes:

```
$ cat debug-plugin.js
import(process.argv[2]).then(x => {
    console.log(x.default());
}).catch(e => {
    console.error(e)
});
```
Here's a couple of sample plugins we'll use to test it:
```
$ cat cjs-plugin.js
const plugin = {
    name: "cjs-plugin",
    transform: c => `console.log("${plugin.name}");\n${c}`
};
module.exports = () => plugin;
```
```
$ cat esm-plugin.mjs
const plugin = {
    name: "esm-plugin",
    transform: c => `console.log("${plugin.name}");\n${c}`
};
export default () => plugin;
```
Here it's dynamically loading various `cjs` and `esm` plugins from the CLI:
```
$ node debug-plugin.js @rollup/plugin-node-resolve
{
  name: 'node-resolve',
  buildStart: [Function: buildStart],
  generateBundle: [Function: generateBundle],
  resolveId: [AsyncFunction: resolveId],
  load: [Function: load],
  getPackageInfoForId: [Function: getPackageInfoForId]
}
```
```
$ node debug-plugin.js ./cjs-plugin.js 
{ name: 'cjs-plugin', transform: [Function: transform] }
```
```
$ node debug-plugin.js ./esm-plugin.mjs 
{ name: 'esm-plugin', transform: [Function: transform] }
```
Here's the rollup `cjs` output for `debug-plugin.js`:
```
$ rollup debug-plugin.js -f cjs --silent
'use strict';

function _interopNamespace(e) {
    if (e && e.__esModule) return e;
    var n = Object.create(null);
    if (e) {
        Object.keys(e).forEach(function (k) {
            if (k !== 'default') {
                var d = Object.getOwnPropertyDescriptor(e, k);
                Object.defineProperty(n, k, d.get ? d : {
                    enumerable: true,
                    get: function () { return e[k]; }
                });
            }
        });
    }
    n["default"] = e;
    return Object.freeze(n);
}

(function (t) { return Promise.resolve().then(function () { return /*#__PURE__*/_interopNamespace(require(t)); }); })(process.argv[2]).then(x => {
    console.log(x.default());
}).catch(e => {
    console.error(e);
});
```
Notice that the dynamic `import()` was replaced with `require()`. This is not suitable for loading esm rollup plugins from the CLI.

### Feature Proposal

Introduce a rollup option to preserve dynamic `import()` for non-string argument in `cjs` format:

```
$ rollup debug-plugin.js -f cjs --silent --keep-dynamic-import
```
to generate this output:
```js
import(process.argv[2]).then(x => {
    console.log(x.default());
}).catch(e => {
    console.error(e)
});
```

so that I can ultimately create a version of rollup (that can be built with rollup) to do this:

```
$ echo 'hello()' | rollup -p ./cjs-plugin.js --silent
console.log("cjs-plugin");
hello();
```
```
$ echo 'hello()' | rollup -p ./esm-plugin.mjs --silent
console.log("esm-plugin");
hello();
```

**Comment by lukastaegert** [comment]
You can do this today via the plugin interface using the [`renderDynamicImport` hook](https://rollupjs.org/guide/en/#renderdynamicimport). Your use-case is even documented there as an example. This allows for much more fine-grained control following the idea that keeping a dynamic import is not a default but a very conscious decision.
As a matter of fact, Rollup already does this when loading config files: https://github.com/rollup/rollup/blob/d67ef8cf71c5f9286c2d71a960ce394581fb2191/build-plugins/esm-dynamic-import.ts#L14-L19
I would assume that this should be easily adaptable to your use-case.

**Comment by kzc** [comment]
Thanks for bringing `renderDynamicImport` to my attention.  The following change appears to be sufficient to get the dynamic `import()` working in my feature branch for the rollup CJS build and allow `esm` plugins to be specified on the command line:

```patch
--- a/build-plugins/esm-dynamic-import.ts
+++ b/build-plugins/esm-dynamic-import.ts
@@ -13,7 +13,7 @@ export default function addBinShebangAndEsmImport(): Plugin {
                name: 'esm-dynamic-import',
                renderDynamicImport({ moduleId }) {
                        importFound = true;
-                       if (moduleId.endsWith('loadConfigFile.ts')) {
+                       if (moduleId.endsWith('commandPlugins.ts') || moduleId.endsWith('loadConfigFile.ts')) {
                                return { left: 'import(', right: ')' };
                        }
                }
```

And for the rollup `cjs` CLI build at least, there doesn't appear to be any downside to removing the `if` condition to allow the dynamic `import()` to be retained in all cases for all source files. `npm test` still runs without error.

I appreciate the flexibility of being able to customize dynamic imports in plugins, but what I don't understand is the motivation behind changing `import()`s into `require()`s for the `cjs` output format by default as opposed to being an opt-in.

**Comment by lukastaegert** [comment]
When this feature was implemented, there was no such thing as Node ESM support. And in many cases, it could still be what you want: Get the ESM build for ESM and the CJS build for CommonJS. After all, we also change static imports to requires, if you do not do the same for dynamic imports, you could get to a situation where in the ESM build, static and dynamic import get the same module while they get different modules when transpiled to CommonJS.

**Comment by kzc** [comment]
Thanks for the explanation. Makes sense.  I suppose the default could be revisited now that Node ESM support exists.

I did notice in the course of creating the [commonjs alternative plugin](https://github.com/rollup/rollup/issues/4195#issuecomment-932425498) that rollup tends to favor using the ESM version of modules for static requires and static imports if they exist due to the default `mainFields` in `@rollup/plugin-node-resolve`. Probably just as well.

I'll see if I can clean up `--plugin` use for `esm` modules. I already noticed a difference in path handling for dynamic `import()` versus `require` for NodeJS.  Dynamic `import` paths must have a file extension for `./relative/file` and `/absolute/file` paths, unlike `require` paths. Perhaps the dynamic `import` could be a fallback if the `require` fails.  It doesn't matter which of `cjs` or `esm` plugins is loaded if both exist.

**Comment by StreetStrider** [comment]
Thank you for the info on the hook. This allowed me to solve issues with dynamic imports in my cjs setup. I understand why this is not the default behavior. However, now, when [node esm](https://nodejs.org/api/esm.html#modules-ecmascript-modules) is stable, dynamic imports become the only escape hatch for cjs setups in order to load esm-only modules (a lot of packages got esm-only update theese days). I found no specific explanations on how to solve this issue and I think this might worth to be explicitly solved via some simple option or plugin and mentioned directly in the docs.
