### ISSUE TITLE
Rollup warns about unresolved dependencies even though marked as external

### ISSUE THREAD

**Issue by perrin4869** [rollup/rollup#4264]
### Rollup Version

2.59.0

### Operating System (or Browser)

Slackware64-current

### Node Version (if applicable)

16.11.1

### Link To Reproduction

https://replit.com/@perrin4869/rollup-repro

### Expected Behaviour

Running `rollup -c` should not warn about unresolved dependencies, since `timers` is marked as external

### Actual Behaviour

```
❯ rollup -c

index.js → index.out.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
timers/promises (imported by index.js)
created index.out.js in 23ms
```

**Comment by dasa** [comment]
Try `const external = 'timers/promises';` instead of `const external = 'timers';`.

**Comment by perrin4869** [comment]
Well, of course that would remove the warning, but it wouldn't fix the issue :)
I expected that marking `timers` as external means that `timers/promises` would be considered external as well...
If this isn't the intended behavior though then there is no issue
In reality I am using [`builtin-modules`](https://www.npmjs.com/package/builtin-modules) to set the external dependencies

**Comment by ankeetmaini** [comment]
You can supply a function to `external` and exclude modules starting with `timers/*`

```js
import nodeResolve from '@rollup/plugin-node-resolve'
import cjs from '@rollup/plugin-commonjs';

export default {
    input: './main.js',
    output: {
      file: 'bundle.js',
    },
    external: (id) => {
        if (id.includes('react')) return true;
        return false;
    },
    plugins: [
        cjs(),
        nodeResolve()
    ]
};
```

**Comment by perrin4869** [comment]
Yeah of course there are countless ways to silence the warning, just thought this is something that can be improved upstream, but feel free to close this if this isn't a priority or it isn't the expected behavior

**Comment by dnalborczyk** [comment]
@perrin4869  you might be interested in: https://github.com/sindresorhus/builtin-modules/issues/12 

it seems tho it would make more sense to skip a third party module all-together and just use the built-in version:
https://nodejs.org/api/module.html#modulebuiltinmodules

**Comment by perrin4869** [comment]
Oh thanks! I didn't realize this, nice!
