### ISSUE TITLE
external files are being bundled for commonjs

### ISSUE THREAD

**Issue by dnalborczyk** [rollup/rollup#4273]
### Rollup Version

2.60.0

### Operating System (or Browser)

n/a

### Node Version (if applicable)

n/a

### Link To Reproduction

n/a

### Expected Behaviour

.

### Actual Behaviour

**foo.js**
```js
const foo = require("./foo.js")

console.log(foo)
```

**foo.js**
```js
module.exports = "foo";
```

**rollup.config.js**
```js
import commonjs from "@rollup/plugin-commonjs";

export default {
  external: ["./foo.js"],
  input: "./index.js",
  output: {
    file: "./build/bundle.js",
    format: "module",
  },
  plugins: [commonjs()],
}
```

**bundled:**
```js
import './foo.js';

var requireTest = {};

var require$$0 = "foo";

const foo = require$$0;

console.log(foo);

export { requireTest as default };
```

possibly a commonjs-plugin bug (also does not work with the json plugin). might ignore the `external` setting, or rollup is not passing it along. hence I'm filing it here.

works when source files are `esm`.

```js
import foo from "./foo.js"

console.log(foo)
```

```js
export default "foo"
```

**bundled:**
```js
import foo from './foo.js';

console.log(foo);
```

failed attempt to cross file: https://github.com/rollup/plugins/issues/1044

**Comment by FoxDaxian** [comment]
it is works after remove `commonjs`:

```javascript
export default {
  external: ["foo.js"],
  input: "./index.js",
  output: {
    exports: 'auto',
    file: "./build/bundle.js",
    format: "cjs",
  },
  plugins: [],
}
```

output:

```javascript
'use strict';

const foo = require("./foo.js");

console.log(foo);
```

seem need file issue to `rollup/plugins` again.

**Comment by FoxDaxian** [comment]
actually rollup provides some use case in `rollup/test/form/samples/external-imports/main.js`

**Comment by dnalborczyk** [comment]
> it is works after remove `commonjs`:

thanks @FoxDaxian , you are right. now I'm entirely lost and confused. 🤔  

> seem need file issue to `rollup/plugins` again. 

not going to. out of principle.

**Comment by lukastaegert** [comment]
This is indeed an issue with the commonjs plugin. I added a fix to the PR rollup/plugins#1038 I am working on at the moment. May take a while until it is merged though (by the way, that one will look for more beta testers soon).

**Comment by dnalborczyk** [comment]
@FoxDaxian 

it got a little late yesterday. I was surprised as I thought he commonjs syntax is unknown to rollup. and as it turns out, it is. this is not _really working_ without the `commonjs plugin`, as you get to the same result excluding the `external` parameter.

```js
export default {
  // external: ["foo.js"], <--- removed
  input: "./index.js",
  output: {
    exports: 'auto',
    file: "./build/bundle.js",
    format: "cjs",
  },
  plugins: [],
}
```

**Comment by FoxDaxian** [comment]
@dnalborczyk 
I think it is.
and used `import` after remove external. will output as below:

```javascript
'use strict';
var foo = "foo";
console.log(foo);
```

rollup do not have `require statement node`, it can deal with `import statement` only. so it result like `external` even though excluding the `external`.

----
can not found some `require statement node`
![image](https://user-images.githubusercontent.com/19708789/142343331-6d6e0e68-e9d4-4d7d-9d9b-327fc90e62cd.png)

**Comment by FoxDaxian** [comment]
maybe this can explain the problem we encountered:

![image](https://user-images.githubusercontent.com/19708789/142343764-a26e67c8-65dd-466d-a073-8f1fd48dfdaa.png)
