### ISSUE TITLE
What's Rollup's stance on side-effectful imports

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#429]
I've encountered this issue once before, where I have an import for side-effects and then import that rely on those side-effects. How should Rollup handle things [like this](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20'.%2FsetImmediate-polyfill.js'%3B%5Cnimport%20asap%20from%20'.%2Fasap.js'%3B%5Cn%5Cnconsole.log(%20asap(%20()%20%3D%3E%20console.log(%20'foo'%20)%20)%20)%3B%22%7D%2C%7B%22name%22%3A%22asap.js%22%2C%22code%22%3A%22%2F%2F%20uses%20the%20best%20available%20option%5Cnexport%20default%20window.setImmediate%20%7C%7C%C2%A0window.setTimeout%3B%22%7D%2C%7B%22name%22%3A%22setImmediate-polyfill.js%22%2C%22code%22%3A%22%2F%2F%20this%20goes%20in%20too%20late%5Cnwindow.setImmediate%20%3D%20function%20()%20%7B%7D%3B%22%7D%5D%7D)? I think that many people, instinctively, would expect the first import to execute before the second; but currently that is not the case.

```js
// This first import should execute...
import './setImmediate-polyfill.js';
// ... before this.
import asap from './asap.js';

console.log( asap( () => console.log( 'foo' ) ) );
```

Rollup will detect that `main` requires the other two, but that there is no dependency between the other modules. It therefore places them in some deterministic, but arbitrary order.

**Comment by pkozlowski-opensource** [comment]
Ha! Excellent question! We struggle with users importing shims / polyffils on the Angular2 side a lot. People tend to do it mostly to have a bundler (rollup / webpack / whatever) to handle all their code.

My personal opinion for now is that things like shims / polyfills do non-trivial amount of monkey patching and loading them through a module loader is asking for troubles. But I would very much like to hear what others think / do in practice.

**Comment by Swatinem** [comment]
related to #335.

Lets look at the spec:
* https://tc39.github.io/ecma262/#sec-source-text-module-records <- says that the `[[RequestedModules]]` internal prop of a module record has the imports in source order.
* https://tc39.github.io/ecma262/#sec-moduleevaluation <- then this says to iterate over all the modules in order and evaluate them.

So the spec is pretty clear about having imports evaluated in source order.

**Comment by Rich-Harris** [comment]
Thanks @Swatinem, was hoping someone would dig up the relevant bit of spec! So https://tc39.github.io/ecma262/#sec-moduleevaluation is basically describing a straightforward topological sort, up until the point we encounter cyclical dependencies – at which point we're supposed to short-circuit.

Does this mean that a situation like this...

```js
// main.js
import A from './A.js'; // 1
import B from './B.js';

new A();
new B();

// A.js
import B from './B.js'; // 2

export default class A {
  b () {
    return new B();
  }
}

// B.js
import A from './A.js'; // 3 – short-circuits before A can be evaluated...

export default class B extends A { // ...meaning this can't execute
  a () {
    return new A();
  }
}
```

...should result in an error, because `B.js` gets evaluated before `A.js`? If the two imports in `main.js` were reversed, everything would be fine – which seems undesirable, because `main.js` shouldn't need to be concerned about the relationship between `A.js` and `B.js`.

Rollup shifts the order in a way that's designed to avoid that scenario. Is that incorrect?

**Comment by guybedford** [comment]
Yes this does throw in the spec unless B comes first in the ordering due to
another import in a larger dep tree.

**Comment by Rich-Harris** [comment]
Huh. Guess we should fall in line then. Seems a bit of a shame, but I suppose it makes sense – at the very least, we should be able to identify those cases and recommend a course of action at bundle time:

```
[ROLLUP]: Module /path/to/a.js depends on /path/to/b.js, but will be evaluated first due
to the order of imports. This may cause a runtime error – consider swapping lines 3 and
6 in /path/to/main.js. See https://github.com/rollup/rollup/wiki/Troubleshooting#cycles
for more information.
```

Will open a separate issue.

**Comment by Victorystick** [comment]
Also right. The path forward is layed out by #435. I'll close this issue.
