### ISSUE TITLE
Consider an alternative solution for virtual modules

### ISSUE THREAD

**Issue by g-plane** [rollup/rollup#4290]
### Expected Behavior / Situation

Use another special mark or character to mark a module as a virtual module, not `\0`.

### Actual Behavior / Situation

Rollup regards module whose ID starts with `\0` as "virtual modules", but when integrating with SWC, for example, using [rollup-plugin-swc](https://github.com/SukkaW/rollup-plugin-swc), will break the parser, because Rust's [`String`](https://doc.rust-lang.org/std/string/struct.String.html) doesn't support it. It seems that Rust will treat `\0` as string terminator. (I'm not sure)

Related issue in SWC: https://github.com/swc-project/swc/issues/2853

### Modification Proposal

Currently I don't have thoughts on this.

**Comment by lukastaegert** [comment]
How would swc handle other problematic characters like quotes or backslashes? Would it escape those?

Problem here is, this is a convention that is used by uncountable plugins throughout the entire Rollup eco system that we cannot just "change".

**Comment by g-plane** [comment]
> How would swc handle other problematic characters like quotes or backslashes? Would it escape those?

Yes, it will be escaped.

**Comment by lukastaegert** [comment]
The best I can think of for now is that you manually escape ids/replace the character and replace it back in the output

**Comment by lukastaegert** [comment]
A better solution would be to work with the swc people to find a convention how to pass \0 in ids

**Comment by g-plane** [comment]
This [rollup-plugin-swc](https://github.com/SukkaW/rollup-plugin-swc) does as you says: it manually escapes the `\0` in ids.
