### ISSUE TITLE
Handle `export enum` incorrectly

### ISSUE THREAD

**Issue by wqcstrong** [rollup/rollup#4291]
### Rollup Version

2.60.2

### Operating System (or Browser)

macOS Monterey

### Node Version (if applicable)

16.13.0

### Link To Reproduction

https://github.com/wqcstrong/export-name-from-module

### Expected Behaviour

Don't import the unused module in the bundle and its behavior is like the module produce some side effect.

### Actual Behaviour

import the unused module because `export enum` in the module

**Comment by wqcstrong** [comment]
BTW, any other conditions result to the error bundle like above?
Thx~

**Comment by NotZoeyDev** [comment]
I've been having the same issue recently and it's quite annoying as I cannot seem to find a way to make it not happen.

**Comment by wqcstrong** [comment]
> I've been having the same issue recently and it's quite annoying as I cannot seem to find a way to make it not happen.

I assume that `export enum` syntax may be treated as produce side effects by `rollup-plugin-typescript2`, although the assumption is invalid in my reproduction demo.  So this's not rollup issue~

**Comment by NotZoeyDev** [comment]
> > I've been having the same issue recently and it's quite annoying as I cannot seem to find a way to make it not happen.
> 
> I assume that `export enum` syntax may be treated as produce side effects by `rollup-plugin-typescript2`, although the assumption is invalid in my reproduction demo. So this's not rollup issue~

Actually it happens with `rollup-plugin-esbuild` too which is what I'm having problems with at the moment!

**Comment by dnalborczyk** [comment]
`rollup` **only** cares about the generated javascript, which in the case of your `Test enum` is being transpiled to:

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwCrAM7wN4CwAUHHIgIarDEC+QA

```js
export var Test;
(function (Test) {
    Test[Test["name"] = 0] = "name";
})(Test || (Test = {}));
```

you should rather use Objects as enums or union types instead. enum is not (yet) part of ecmascript.

**Comment by wqcstrong** [comment]
> `rollup` **only** cares about the generated javascript, which in the case of your `Test enum` is being transpiled to:
> 
> https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwCrAM7wN4CwAUHHIgIarDEC+QA
> 
> ```js
> export var Test;
> (function (Test) {
>     Test[Test["name"] = 0] = "name";
> })(Test || (Test = {}));
> ```
> 
> you should rather use Objects as enums or union types instead. enum is not (yet) part of ecmascript, but there's hope: https://github.com/Jack-Works/proposal-enum

Why this generated `Test` not removed by tree-shaking?

**Comment by wqcstrong** [comment]
Following is the expected interation behavior between rollup and plugins:
1. rollup resolve the `Button.ts` source id
2. typescript plugin transforms the content and return the result:
```js
var Button = function Button() {
  console.log('Button');
};
var Test;

(function (Test) {
  Test[Test["name"] = 0] = "name";
})(Test || (Test = {}));

export { Button, Test };
```
3. the `Button` and `Test` is not used in rollup module graph and can be removed with tree-shaking
4. remove the import statment in importer file after source module parsed

**Comment by wqcstrong** [comment]
@dnalborczyk what I missed🤕  , please give me some helps, thx~

**Comment by dnalborczyk** [comment]
@lukastaegert could you shed some light on this?

**Comment by lukastaegert** [comment]
> Why this generated Test not removed by tree-shaking?

For performance reasons, when checking functions for side effects, they do not try out (yet) all possible parameter values they are called with, they just assume the worst, which is usually all parameters being `undefined`.

Improving here is something I wanted to do for a long time, but it is some very delicate mechanics with lots of things to consider, and there are more important bugs I need to work on at the moment.

The usual "fix" for these kinds of TypeScript issues is using `treeshake.moduleSideEffects: true` (or use a function if a blanket `true` is too much). Basically this tells Rollup: Only look for side effects if you include something from the module. A good default for most well-written modules.

**Comment by wqcstrong** [comment]
> > Why this generated Test not removed by tree-shaking?
> 
> For performance reasons, when checking functions for side effects, they do not try out (yet) all possible parameter values they are called with, they just assume the worst, which is usually all parameters being `undefined`.
> 
> Improving here is something I wanted to do for a long time, but it is some very delicate mechanics with lots of things to consider, and there are more important bugs I need to work on at the moment.
> 
> The usual "fix" for these kinds of TypeScript issues is using `treeshake.moduleSideEffects: true` (or use a function if a blanket `true` is too much). Basically this tells Rollup: Only look for side effects if you include something from the module. A good default for most well-written modules.

Thanks for your answer, I'll take a try later.

**Comment by lukastaegert** [comment]
Ah sorry, it would be  `treeshake.moduleSideEffects: false`

**Comment by wqcstrong** [comment]
@NotZoeyDev  the advice from me is not to use `enum` for now. As above says that:

> you should rather use Objects as enums or union types instead.
