### ISSUE TITLE
support #private in syntax

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#4292]
### Feature Use Case

```js
class A {
    #p;
    isA () { return #p in this; }
}
```

### Feature Proposal

That's already stage 4, supported by nodejs, browser and latest acorn (v8.6.0).

**Comment by dnalborczyk** [comment]
for reference: https://github.com/tc39/proposal-private-fields-in-in

**Comment by lukastaegert** [comment]
Should be supported now
