### ISSUE TITLE
Expose isIncluded

### ISSUE THREAD

**Issue by william57m** [rollup/rollup#4297]
### Feature Use Case

I'm implementing a plugin that gather some informations from the files I include in my bundle, however, I don't want to go over the files that are tree-shacked. I didn't find any way to find this information from the getModuleInfo method or any hooks. I finally found that there is a way to know that internally, but unfortunately it's not exposed. I think it's a really helpful piece of information that should be exposed to plugin writter.

### Feature Proposal

Exposing this method on the module informations would be helpful to know if the file is actually bundled or not, that would also allow help plugin writter to skip some files and improve the execution time in some case.

In `Module.ts`
```diff
this.info = {
   ...
  isEntry,
  isExternal: false,
+ get isIncluded() {
+   return module.isIncluded();
+ },
  ...
}
```

**Comment by lukastaegert** [comment]
That also depends on a which time your plugin runs. The earliest point where this information would be reliable is at the very end of the build phase i.e. when the `buildEnd` hook runs (and of course during the generate phase). Moreover, it can fail in unexpected ways if the module for which it is queried has not been linked properly (and if it does not fail, it may be wrongly `false`). So at what point would your plugin need it?

**Comment by william57m** [comment]
It could run in any of the output generation hooks. My plugin in question wouldn't impact the output, just gather informations for stats and validation.

**Comment by william57m** [comment]
@lukastaegert would you considerate exposing this information if well implemented? Or do you see any issues (technically and/or regarding the API coherence)

**Comment by lukastaegert** [comment]
Looking at it again, I do not see an issue here except of course the fact that this information is unreliable before tree-shaking is run. And one would need to check if it crashes if you run it on a module during its load or transform hook.
Ideally, it should return `null` in those cases and only return a boolean once it is reliable.

**Comment by lukastaegert** [comment]
One way could be to check if `graph.phase` is `BuildPhase.GENERATE`

**Comment by josuevalrob** [comment]
@william57m I am having some weird issues:
`[!] TypeError: Cannot read properties of null (reading 'included')`

```

TypeError: Cannot read properties of null (reading 'included')
    at Module.isIncluded (/the-rock/ui/.yarn/cache/rollup-npm-3.2.3-da5a5e4969-e4b4f3b70f.zip/node_modules/rollup/dist/shared/rollup.js:13555:25)
    at getIncludedModules (/the-rock/ui/.yarn/cache/rollup-npm-3.2.3-da5a5e4969-e4b4f3b70f.zip/node_modules/rollup/dist/shared/rollup.js:16893:21)
    at Bundle.generateChunks (/the-rock/ui/.yarn/cache/rollup-npm-3.2.3-da5a5e4969-e4b4f3b70f.zip/node_modules/rollup/dist/shared/rollup.js:16855:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bundle.generate (/the-rock/ui/.yarn/cache/rollup-npm-3.2.3-da5a5e4969-e4b4f3b70f.zip/node_modules/rollup/dist/shared/rollup.js:16770:28)
    at async /the-rock/ui/.yarn/cache/rollup-npm-3.2.3-da5a5e4969-e4b4f3b70f.zip/node_modules/rollup/dist/shared/rollup.js:24884:27
    at async catchUnfinishedHookActions (/the-rock/ui/.yarn/cache/rollup-npm-3.2.3-da5a5e4969-e4b4f3b70f.zip/node_modules/rollup/dist/shared/rollup.js:24024:20)
    at async Promise.all (index 0)
    at async build (/the-rock/ui/.yarn/cache/rollup-npm-3.2.3-da5a5e4969-e4b4f3b70f.zip/node_modules/rollup/dist/bin/rollup:1554:5)
    ```

**Comment by lukastaegert** [comment]
Would be nice if you could create a reproduction for that error so that we can investigate. This looks like something that should not happen.

**Comment by Zagorodnyi** [comment]
Same issue here 

```
[!] TypeError: Cannot read properties of null (reading 'included')
TypeError: Cannot read properties of null (reading 'included')
    at Module.isIncluded (/.../node_modules/rollup/dist/shared/rollup.js:13555:25)
    at getIncludedModules (/.../node_modules/rollup/dist/shared/rollup.js:16893:21)
    at Bundle.generateChunks (/.../node_modules/rollup/dist/shared/rollup.js:16855:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Bundle.generate (/.../node_modules/rollup/dist/shared/rollup.js:16770:28)
    at /.../node_modules/rollup/dist/shared/rollup.js:24884:27
    at catchUnfinishedHookActions (/.../node_modules/rollup/dist/shared/rollup.js:24024:20)
    at async Promise.all (index 0)
    at build (/...node_modules/rollup/dist/bin/rollup:1554:5)
```

rollup.config.js:

```javascript
const pkg = jsonfile.readFileSync(resolve('package.json'));

module.exports =  {
  './src/index.ts',
  output: [
    { dir: resolve('dist'), format: 'cjs' },
  ],
  external: [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.peerDependencies || {}),
  ],
  plugins: [
    postcss({
      modules: true,
  }),
    rollupTypescript2({
      typescript,
      clean: true,
    }),
    commonjs(),
    nodeResolve(),
  ]
}

```

**Comment by lukastaegert** [comment]
Out of curiosity, does switching to '@rollup/plugin-typescript` have an effect? Otherwise, we need a full reproduction with source files to start debugging.

**Comment by tkalliom** [comment]
We are also using rollup-plugin-typescript2 and ran into the `Cannot read properties of null (reading 'included')` error when attempting to upgrade Rollup and plugins. It seems to be something to do with the handling of `external`: while it previously worked for us, now rollup
 * in some cases fails on missing the JSON plugin when handling something that should have been skipped altogether, and
 * in other cases fails with the above-mentioned error, having a seemingly partial data structure describing a module listed in `external`

If the `external` declaration is removed, the error about `included` disappears. It almost seems as if `external` is somehow half-way respected, and the error is produced when handling a data structure describing a semi-skipped module? However, despite trying, I could not manage to produce a reproducible example from scratch; rollups worked. It could be something to do with our project structure (private packages in a monorepo, and Lerna is used). I may try the other way around, deleting stuff from a copy of our repo until the problem no longer appears, if I have more time at some point.

At https://github.com/unjs/nitro/issues/200 there is speculation that Node version might be related. We saw the issue on Node 16.18.1.

**Comment by tkalliom** [comment]
I filed a bug report with reproduction code regarding the issue discussed here: https://github.com/rollup/rollup/issues/4722
