### ISSUE TITLE
Failure exporting imported sub-modules

### ISSUE THREAD

**Issue by brianmhunt** [rollup/rollup#430]
### Minimal Working Example

_tl;dr_ [A minimal example exhibiting the problem is](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22umd%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20*%20as%20maths%20from%20'.%2Fmaths.js'%3B%5Cnexport%20%7Bmaths%7D%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22import%20*%20as%20algebra%20from%20'.%2Falgebra.js'%5Cnexport%20%7Balgebra%7D%22%7D%2C%7B%22name%22%3A%22algebra.js%22%2C%22code%22%3A%22export%20var%20wink%20%3D%2012%22%7D%5D%7D):
### entry.js

``` javascript
import * as pkg from './package.js'
export {pkg}
```
### package.js

``` javascript
import * as sub from './sub.js'
export {sub}
```
### sub.js

``` javascript
export var wink = 10
```

Running `rollup entry.js` gives:

```
var wink = 10

var pkg = Object.freeze({
    sub: null
});

export { pkg };⏎
```

Where `pkg.sub` should be `Object.freeze({wink: wink})`

Running `rollup package.js` works as expected.

For some more context, see below.

---

In the package [tko.utils](https://github.com/knockout/tko.utils), I have the following code:
### spec/utilsDomBehaviors.js

``` javascript
import * as utils from '../index.js'
// ...
```
### index.js

``` javascript
import './src/bind-shim.js'
export * from './src/array.js'
// ...
import * as virtualElements from './src/dom/virtualElements.js'
import * as domData from './src/dom/data.js'

export {virtualElements, domData}
```

This compiles as-expected when running `rollup index.js` (or the equivalent gulp task, `gulp make`).

However, a problem exhibits when I run, from the project root (or from the `spec` directory, with the `entry` changed accordingly):

``` javascript
> rollup({ entry: 'spec/utilsDomBehaviors.js' }).then((b) => global.bundle = b)
> console.log(bundle.generate({ format: 'es6' }).code)
// ... Code!
```

The `shim` imports fine, and the the `array` imports/exports as expected.

However, resulting code does not contain either `virtualElements` or `domData`.   One would expect it to be an `Object.freeze...`.

The objects are referenced in the export part as:

``` javascript
var utils = Object.freeze({
  virtualElements: null,
  domData: null$1,
  // ...
  }
```

The problem also occurs when using `bundle.write`, and regardless of the output format.

This issue prevents the easy use of the `karma-rollup-preprocessor` plugin.

**Comment by Rich-Harris** [comment]
Fixed in 0.24.1 – thanks

**Comment by brianmhunt** [comment]
:beers:

**Comment by christopherthielen** [comment]
I think this is still a problem in 0.25.4: 

Link to minimal reproduction http://bit.ly/1UpzaOC

If this is a different problem, please yell at me and I'll open a new issue.

index.js:
`export * from "./core"`
core.js:
`import * as common from "./common"; export { common };`
common.js:
`export const foo = "foo";`

generates (globals):
```
(function (exports) {
	'use strict';

	const foo = "bar"

	exports.common = null;

}((this.myBundle = this.myBundle || {})));
```

**Comment by brianmhunt** [comment]
Good point @christopherthielen – One can see [the problem exhibiting from your example, on rollupjs.org](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20*%20from%20%5C%22.%2Fcore%5C%22%22%7D%2C%7B%22name%22%3A%22core.js%22%2C%22code%22%3A%22import%20*%20as%20common%20from%20%5C%22.%2Fcommon%5C%22%5Cnexport%20%7B%20common%20%7D%22%7D%2C%7B%22name%22%3A%22common.js%22%2C%22code%22%3A%22export%20const%20foo%20%3D%20%5C%22foo%5C%22%3B%22%7D%5D%7D)

**Comment by tyler-johnson** [comment]
Here is a temporary workaround for anyone who was caught by this like I was:

main.js:
`export * from "./middle.js";`
middle.js:
`import * as _foo from "./foo.js"; export const foo = _foo;`
foo.js:
`export const foo = "bar";`

[Rollup JS Version](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20*%20from%20%5C%22.%2Fmiddle.js%5C%22%22%7D%2C%7B%22name%22%3A%22middle.js%22%2C%22code%22%3A%22import%20*%20as%20_foo%20from%20%5C%22.%2Ffoo.js%5C%22%3B%5Cn%5Cnexport%20const%20foo%20%3D%20_foo%3B%22%7D%2C%7B%22name%22%3A%22foo.js%22%2C%22code%22%3A%22export%20const%20foo%20%3D%20%5C%22bar%5C%22%3B%22%7D%5D%7D)

**Comment by Rich-Harris** [comment]
As far as I can tell this is [fixed in recent versions](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwKiUyMGZyb20lMjAlNUMlMjIuJTJGY29yZSU1QyUyMiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb3JlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGNvbW1vbiUyMGZyb20lMjAlNUMlMjIuJTJGY29tbW9uJTVDJTIyJTVDbmV4cG9ydCUyMCU3QiUyMGNvbW1vbiUyMCU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb21tb24uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAlNUMlMjJmb28lNUMlMjIlM0IlMjIlN0QlNUQlN0Q=) – I remember us fixing something similar, so that all makes sense. Will close this (again! 😀 )
