### ISSUE TITLE
Can't skip scoped package

### ISSUE THREAD

**Issue by jbach** [rollup/rollup#431]
````
[Error: Package @risingstack/graffiti (imported by foo.js) does not have a jsnext:main field. You should either allow legacy modules with options.main, or skip it with options.skip = ['@risingstack/graffiti'])]
````
Even though I'm skipping it. Is this related to https://github.com/rollup/rollup/issues/131? Because the fix to #131 seems to have been removed with https://github.com/rollup/rollup/commit/157a665e9210e6691ccd84493a470bfa8103a7af?

**Comment by eventualbuddha** [comment]
What does your config look like?

**Comment by jbach** [comment]
Basically like this:

```JavaScript
{
	plugins: [
		npm({
			jsnext: true,
			main: false,
			skip: ['@risingstack/graffiti']
		})
	]
}
```

I guess this issue would also be solved by https://github.com/rollup/rollup-plugin-npm/issues/6.

**Comment by Rich-Harris** [comment]
Fixed in latest release of rollup-plugin-npm. Thanks!
