### ISSUE TITLE
How to run rollup in deno?

### ISSUE THREAD

**Issue by jespertheend** [rollup/rollup#4310]
This is a response to #2781 but the issue is locked so I can't comment there.
I keep coming to that issue for an answer every time I need this. Hopefully this helps someone.

You can use [esm.sh](https://esm.sh/) to run rollup in deno:
```js
import {rollup} from "https://esm.sh/rollup@2.61.1";

const bundle = await rollup({ //...
```

Alternatively you can install rollup from npm and use the [node compatibility layer](https://deno.land/std@0.110.0/node):
```js
import {createRequire} from "https://deno.land/std@0.110.0/node/module.ts";
const require = createRequire(import.meta.url);
const {rollup} = require("rollup");

const bundle = await rollup({ //...
```

**Comment by shellscape** [comment]
Please consider a Pull Request to the docs rather than an issue in the future.

**Comment by jespertheend** [comment]
Ah sorry about that, I was hoping #2781 would automatically create a link back to this issue.
I have created #4311
