### ISSUE TITLE
I need a longer hash with customizable length.

### ISSUE THREAD

**Issue by yangdan8** [rollup/rollup#4317]
### Feature Use Case

The hash value of fixed 8-bit file content is too easy to conflict. I need a longer hash with customizable length. How should I set it

[hash:30]
[hash:6]

### Feature Proposal

[hash:30]
[hash:6]

**Comment by frank-dspeed** [comment]
@yangdan8 you can already define names via a function you could simply add your own hash function and even drop the rollup hash from the mask please read the documentation about file name patterns

**Comment by lukastaegert** [comment]
This is now included in #4543
