### ISSUE TITLE
Output plugin is not run when added via the outputOptions hook

### ISSUE THREAD

**Issue by Septh** [rollup/rollup#4330]
### Rollup Version

2.62.0

### Operating System (or Browser)

Windows 10 21H1

### Node Version (if applicable)

16.13.1

### Link To Reproduction

https://replit.com/@Septh/rollup-output-plugin-repro

### Expected Behaviour

The added plugin is executed.

### Actual Behaviour

The added plugin is not executed. :)

Also, the `inputOptions` object passed to the `options` hook actually has an `output` property (which is, as expected, an array of `OutputOptions`). However, this is not documented and the official `InputOptions` type misses this property. Is this a feature we can rely on?

**Comment by lukastaegert** [comment]
Yes, that is not (yet?) supported as it is kind of tricky to set up.
