### ISSUE TITLE
bug: @@toStringTag property undefined, should be 'Module'

### ISSUE THREAD

**Issue by dnalborczyk** [rollup/rollup#4336]
### Rollup Version

2.62.0

### Operating System (or Browser)

n/a

### Node Version (if applicable)

n/a

### Link To Reproduction

https://rollupjs.org/repl/?version=2.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG5zJTIwZnJvbSUyMCcuJTJGZm9vLmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2cobnMlNUJTeW1ib2wudG9TdHJpbmdUYWclNUQlMjAlM0QlM0QlM0QlMjAnTW9kdWxlJyklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAnYmFyJyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

```js
// index.js
import * as ns from './foo.js';

console.log(ns[Symbol.toStringTag] === 'Module')
```

```js
// foo.js
export const foo = 'bar'
```

rollup bundle:
```js
const foo = 'bar';

var ns = /*#__PURE__*/Object.freeze({
	__proto__: null,
	foo: foo
});

console.log(ns[Symbol.toStringTag] === 'Module');
```

### Expected Behaviour

prints: true

### Actual Behaviour

prints: false

**Comment by kzc** [comment]
esbuld is no different in this regard:

```
$ esbuild index.js --bundle | node
false
```

How would you model the bundle in order for such a thing to work?  By explicitly setting that property in the generated namespace?

```
$ cat 0.js
const foo = 'bar';

var ns = /*#__PURE__*/Object.freeze({
	__proto__: null,
	[Symbol.toStringTag]: "Module",
	foo: foo
});

console.log(ns[Symbol.toStringTag] === 'Module');
```
```
$ node 0.js
true
```

Does any code in the wild rely on this construct?

**Comment by dnalborczyk** [comment]
> esbuld is no different in this regard:
> 
> ```
> $ esbuild index.js --bundle | node
> false
> ```

it's a bug in `esbuild` as well ;)

> How would you model the bundle in order for such a thing to work? By explicitly setting that property in the generated namespace?
> 
> ```
> $ cat 0.js
> const foo = 'bar';
> 
> var ns = /*#__PURE__*/Object.freeze({
> 	__proto__: null,
> 	[Symbol.toStringTag]: "Module",
> 	foo: foo
> });

that might as well be all what's needed, yeah.

> Does any code in the wild rely on this construct?

hard to know. it's in the spec, I would expect that a bundler should (ideally) not alter the runtime. it's a potential easy fix and aligns `rollup` with the spec and other bundlers: https://sokra.github.io/interop-test/#import--as-x

**Comment by dnalborczyk** [comment]
out of curiosity, I was wondering how `rollup` would fare running against [test262](https://github.com/tc39/test262). I gave it a try and ran with a subset (only `module` feature flagged) of the tests as `rollup` doesn't distinguish between `script` and `module` code (as far as I know) and it looks quite amazing overall.

**Comment by kzc** [comment]
I don't know about test262, but a while back rollup was run against uglify-js' ES6+ test suite and the dozen or so failures were filed and fixed.  The `script` tests were also skipped, as rollup cannot handle them. We also dealt with most of the typical TDZ issues in rollup several months ago.

I'd personally suggest to hold off adding `[Symbol.toStringTag]: "Module"` to the namespace until a user reports the issue in real world code. And even then, to only inject it if the property or string literal `toStringTag` appears in any input.

Are there any other special ES module Symbol `import` properties?

**Comment by dnalborczyk** [comment]
> I don't know about test262

it's the TC39 ecmascript language spec test suite. that's the test suite language implementers run against.

> but a while back rollup was run against uglify-js' ES6+ test suite and the dozen or so failures were filed and fixed.

interestingly I added the rollup-terser plugin on top in a subsequent run which unfortunately resulted in more failures. I'll try to file those issues in terser eventually as well. not sure how uglify would be doing, I gotta check [as well].

> I'd personally suggest to hold off adding `[Symbol.toStringTag]: "Module"` to the namespace until a user reports the issue in real world code.

I don't know, is that a good strategy? I would think one would preemptively fix any known bugs. I don't think it would be great if say `chrome` or `node.js` would follow a similar strategy: "wait until it's been reported".

> And even then, to only inject it if the property or string literal `toStringTag` appears in any input.

you mean if anyone is actually reading the property? sure, if that's possible. I don't know how much overhead that would add?  🤷‍♂️ 

> Are there any other special ES module Symbol `import` properties?

I'm fairly sure that's 'it (I might have to report back on that one).

the test is here btw: https://github.com/tc39/test262/blob/main/test/language/module-code/namespace/Symbol.toStringTag.js

**Comment by kzc** [comment]
> it's the TC39 ecmascript language spec test suite. that's the test suite language implementers run against.

Thanks, I was familiar with the test suite but not its results with Rollup.

> I don't know, is that a good strategy? I would think one would preemptively fix any known bugs. I don't think it would be great if say chrome or node.js would follow a similar strategy: "wait until it's been reported".

There are outright bugs, and then there are features that are not supported. NodeJS and Chrome have to be 100% ES spec compliant down to the most obscure feature.  Rollup has a number of known limitations like the aforementioned lack of non-strict mode handling. I think this issue falls in that category.

> you mean if anyone is actually reading the property? sure, if that's possible. I don't know how much overhead that would add?

In my opinion the small overhead to scan all AST string literals and properties would be worth it not to include the 30 odd bytes `[Symbol.toStringTag]: "Module"` to every imported namespace for this rarely used feature.

**Comment by lukastaegert** [comment]
The output.namespaceToStringTag option is there to address this. It is decidedly an opt-in for various reasons.

**Comment by kzc** [comment]
Good stuff.  

Next time I'll [grep](https://github.com/rollup/rollup/search?q=toStringTag+Module&type=) before I jump into a discussion.
;-)

**Comment by dnalborczyk** [comment]
> The [output.namespaceToStringTag](https://rollupjs.org/guide/en/#outputnamespacetostringtag) option is there to address this. It is decidedly an opt-in for various reasons.

dang, I had no clue, way too many options  😄  I'll give it a try ...

**Comment by lukastaegert** [comment]
Acutally considering your last remark, Symbol properties are always non-enumerable, so there should be nothing to do (unless you can write a test that proves otherwise)

**Comment by dnalborczyk** [comment]
> there is a difference in behavior for `Object.assign({}, namespace)` as well as `{...namespace}` as enumerable Symbols are indeed copied in those cases [stackoverflow.com/a/31030427/11576601](https://stackoverflow.com/a/31030427/11576601)

interesting, I did not know that.

**Comment by dnalborczyk** [comment]
just for posterity:

```js
console.log(
	Object.getOwnPropertyDescriptor(Object.freeze({[Symbol.toStringTag]: 'Module'}), Symbol.toStringTag)
)

// prints:
{
  value: 'Module',
  writable: false,
  enumerable: true,
  configurable: false
}
```
