### ISSUE TITLE
Fails on computed object literal keys

### ISSUE THREAD

**Issue by twhb** [rollup/rollup#434]
Given the code `var x = {[foo]: 'bar'};`, rollup seems to be unaware that the variable `foo` is used. It will remove `foo`'s declaration if it is not used elsewhere, or, if `foo` is renamed to avoid conflict with another file, will not rename the reference in the object literal (causing it to refer to the wrong value).

**Comment by Victorystick** [comment]
Reproduced on [Rollup's site](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22var%20foo%20%3D%20'foo'%3B%5Cn%5Cnexport%20var%20x%20%3D%20%7B%5Bfoo%5D%3A%20'bar'%7D%3B%22%7D%5D%7D).

**Comment by Rich-Harris** [comment]
Thanks – released 0.24.1 with the fix

**Comment by twhb** [comment]
Love the turnaround time, thanks!
