### ISSUE TITLE
Documentation references rollup-plugin-polyfill-node on a hacked repo

### ISSUE THREAD

**Issue by Rheeseyb** [rollup/rollup#4346]
### Documentation is

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [X] Not sure?

### Please Explain in Detail...

The documentation point around polyfilling node references [snowpackjs/rollup-plugin-polyfill-node](https://github.com/snowpackjs/rollup-plugin-polyfill-node), however as of a few weeks ago that repo was hijacked (see [this issue](https://github.com/withastro/astro/issues/2281)).

It's unclear from that issue whether ownership will be returned, or what this means for the published npm package.

### Your Proposal for Changes

It _seems like_ the documentation should now be pointing at [FredKSchott/rollup-plugin-polyfill-node](https://github.com/FredKSchott/rollup-plugin-polyfill-node), but that needs verifying

**Comment by dnalborczyk** [comment]
thanks for the notification. it seems that account was hijacked for a bug bounty. the github redirect appears to be fixed, and I assume the npm published module was not affected.

> Your Proposal for Changes
It seems like the documentation should now be pointing at FredKSchott/rollup-plugin-polyfill-node, but that needs verifying

mind creating a PR for the change?
