### ISSUE TITLE
Illegal reassignment to import

### ISSUE THREAD

**Issue by mnater** [rollup/rollup#436]
Entry:
````javascript
import {bar} from "./bar.js";

export var Foo = {
    setBar: function (value) {
        bar = value;
    },
    logBar: function () {
        console.log(bar);
    }
}
````

bar.js:
````javascript
export var bar = 42;
````

I expected:
````javascript
var bar = 42;

var Foo = {
    setBar: function (value) {
        bar = value;
    },
    logBar: function () {
        console.log(bar);
    }
}

exports.Foo = Foo;
```
Rollup exits with error _Illegal reassignment to import 'bar'_

What am I doing wrong here? – Thanks

**Comment by eventualbuddha** [comment]
You are importing `bar`, but then reassigning it within the same file. That's not allowed.  If you want to mutate the value of `bar` you need something from the original file that exports it to set it. I hope that helps!

**Comment by mnater** [comment]
Thanks.
I'm still thinking in CommonJS and having trouble to wrap my head around es6 modules.
Here is a good explanation: http://exploringjs.com/es6/ch_modules.html#sec_imports-as-views-on-exports
