### ISSUE TITLE
Using with React.js

### ISSUE THREAD

**Issue by ritz078** [rollup/rollup#437]
Hi ,

I am trying to set it up with React but its giving me an error. Maybe someone can see the code and suggest something.

**.babelrc**

```
{
  "presets": ["es2015-rollup" , "react"]
}
```

**rollup.config.js**

```js
var babel = require('rollup-plugin-babel');
var commonjs = require('rollup-plugin-commonjs');
var npm = require('rollup-plugin-npm');

var config = {
    entry: 'main.js',
    dest: 'build.js',
    format: 'cjs',
    plugins: [
        babel(),
        npm({
            jsnext: true,
            main: true
        }),
        commonjs({
            include: 'node_modules/**'
        })
    ]
};

module.exports = config;
```

**main.js**

```js
import React from 'react'

var x = React.createClass({
    render: function() {
        return (
            <div></div>
        )
    }
})

export default x;
```

Command that i ran `rollup -c`

The error is 

```shell
Assigning to rvalue (93:17) in /Users/ritz078/projects/react-filters/node_modules/react/lib/ReactElementValidator.js
SyntaxError: Assigning to rvalue (93:17) in /Users/ritz078/projects/react-filters/node_modules/react/lib/ReactElementValidator.js
    at Parser.pp.raise (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:943:13)
    at Parser.pp.toAssignable (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:1073:14)
    at Parser.pp.parseMaybeAssign (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:116:58)
    at Parser.pp.parseVar (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:2038:24)
    at Parser.pp.parseVarStatement (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:1925:8)
    at Parser.pp.parseStatement (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:1726:19)
    at Parser.pp.parseBlock (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:1987:21)
    at Parser.pp.parseFunctionBody (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:603:22)
    at Parser.pp.parseFunction (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:2065:8)
    at Parser.pp.parseFunctionStatement (/Users/ritz078/projects/react-filters/node_modules/rollup-plugin-commonjs/node_modules/acorn/dist/acorn.js:1830:15)
```

Thanks in advance.

**Comment by eventualbuddha** [comment]
I just tried your example setup which you can see here: https://github.com/eventualbuddha/rollup-437

It works for me, and `build.js` is require-able in node:

```
$ node -e 'console.log(require("./build"))'
{ [Function: Constructor] displayName: 'x' }
```

Perhaps you have a different version of something that is behaving badly?

**Comment by ritz078** [comment]
complete reinstallation of npm modules fixed that. Can't i get get the result in cjs mode as 

```js
var React = require('react')

// othercode
```

currently all are including whole React in all the formats.

**Comment by Rich-Harris** [comment]
@ritz078 I'm not quite sure what you mean by that! If it's a separate thing, can you open a new issue with details on how to reproduce it? Otherwise it will get lost.

FWIW I think the correct way to use React is this (because it's really just a namespace):

```js
import * as React from 'react';
```

**Comment by Victorystick** [comment]
@ritz078 `import !== require`. You can think of it like this.

* `import * as ...` imports the entire namespace. These are _roughly equivalent_.
```js
import * as React from 'react';

const React = require( 'react' );
```

* `import { ... }` imports specific named exports from the namespace, _roughly_ like destructuring.
```js
import { createElement } from 'react';

const { createElement } = require( 'react' );
// or
const createElement = require( 'react' ).createElement;
```

* `import ...` imports the `default` export, which is just a named export with the _special_ name `default`. It's just some sugar for `import { default as ... }`.
```js
import React from 'react';
// or
import { default as React } from 'react';

const { default: React } = require( 'react' );
// or
const React = require( 'react' ).default;
```

**Comment by ritz078** [comment]
Thanks a lot for the info @Victorystick 

What i wanted is if my main file is : 

```js
import * as React from 'react'

var x = React.createClass({
    render: function() {
        return (
            <div></div>
        )
    }
})

export default x;
```

I want my output file to be 

```js
const React = require('react')

var x = React.createClass({
    displayName: "x",

    render: function render() {
        return React.createElement("div", null);
    }
});

module.exports = x;
```

So basically i wan't to only convert the actual code that i wrote intead of importing the whole React file. (Don't even want to add the React components that i have used). You can assume that i want to use `es6` or `cjs` format but at the same time use rollup-plugin-babel to convert the code written in center. 

But currently no matter what format i set, whole React library is present in the build. You can see this repo created by @eventualbuddha [https://github.com/eventualbuddha/rollup-437](https://github.com/eventualbuddha/rollup-437) to see what i am talking about.

**Comment by Victorystick** [comment]
@ritz078 Rollup will attempt to include all imports in the bundle, as long it can safely locate and process them. You can tell Rollup to _ignore specific dependencies_ by marking them as _external_ dependencies. Just add `react` to this list.

```diff
var babel = require('rollup-plugin-babel');
var commonjs = require('rollup-plugin-commonjs');
var npm = require('rollup-plugin-npm');

export default {
    entry: 'main.js',
    dest: 'build.js',
    format: 'cjs',
+   external: [ 'react' ],
    plugins: [
        babel(),
        npm({
            jsnext: true,
            main: true
        }),
        commonjs({
            include: 'node_modules/**'
        })
    ]
};
```

**Comment by ritz078** [comment]
Thanks a lot @Victorystick . Totally missed that one.
