### ISSUE TITLE
Some thoughts about treeshake performance

### ISSUE THREAD

**Issue by JSerFeng** [rollup/rollup#4392]
Hi, I'm big fan of Rollup, recently I'm reading Rollup's source code, it was very great to read, I learned a lot, but I also have some questions, hope I can get answers here.
If I want treeshake, Rollup must go through the whole ast nodes one by one, and if there is one node that has side-effects, then Rollup will invoke `node.include()` which will still go through the whole ast nodes again, and check out those nodes that need to be included. Is there any reason that must check the ast nodes twice other than caching if the node has effects. this node has some effects , something like node.confirmHasEffects = true.
if there is some other reasons please let me know,

**Comment by JSerFeng** [comment]
In case I don't get myself clear.
Let's say we have 3 ast nodes here, 
```
Program
  A pure
  B pure
  C impure
```
we have to check 
`A -> A's sub ast tree -> B -> B's sub ast tree -> C !!! oops effects here`
then we invoke node.include() on Program, then
```
A -> A's sub ast tree again all pure
B -> B's sub ast tree again all pure
B -> B's sub ast tree all pure then B.include() -> B's sub ast tree.include()
```

we check them twice, if there are tons of nodes, the scanning process will become very slow

**Comment by lukastaegert** [comment]
Yes, the main reason is that the side effect check stops at the first side effect. But the Node may have many children. Imagine B is a BlockStatement and C is just the first child. When including B, we cannot just stop at C, there may be other children that should also be included.

**Comment by lukastaegert** [comment]
Caching is also a bad idea because there may be many tree-shaking passes, and we do not want old caching information lying around for the next pass.

**Comment by JSerFeng** [comment]
But I mean, imagine B's 9rd child has effects, then I already know that B's 1 - 8 children are all pure, then when I include B, there is no need to check if B's 1-8 children have effects again, am I right

**Comment by JSerFeng** [comment]
Sorry, I recently review some code and I get it ! Very glad to receive your detail explanation  🙏
