### ISSUE TITLE
Should explicitly false `external` be different from undefined `external`

### ISSUE THREAD

**Issue by aleclarson** [rollup/rollup#4396]
Maybe this ship has sailed, but I'll ask anyway. :)

If I return `external: false` from a `resolveId` hook, Rollup will still consult `options.external` and prefer its result.

https://github.com/rollup/rollup/blob/89ee52cab11f0a35f05393bf119cf611ef029e83/src/ModuleLoader.ts#L476-L478

Is there a reason `resolveId` is not respected, and its `external: false` property is treated as `undefined`?

**Comment by lukastaegert** [comment]
Currently, we assume the user knows best. For the next major, we could consider revisiting this and infer an explicit `false` to mean "and do not ask the user". But I fear this may actually cause issues with plugins over-eagerly adding `false` as a value.

**Comment by aleclarson** [comment]
It's likely too rare of a use case, and since there is a workaround in my scenario, I won't push for it
