### ISSUE TITLE
rollup fails on "export * from ..."

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#44]
When I attempt to `rollup` code like that below, I get this error:
```
Module wat.js does not export wat (imported by main.js)
```

I assume this is due to "export * from ...". Minimal example:
```javascript
// --- main.js
import { wat } from './wat';

wat();

// --- wat.js
export * from './wat-impl';

// --- wat-impl.js
export function wat() {}
```

Do you have plans to support this pattern in the pipeline?

**Comment by Rich-Harris** [comment]
Ah. Yep, this definitely needs to be supported, thanks for raising it

**Comment by Victorystick** [comment]
I guess I'll close this since the PR got merged. :+1:
