### ISSUE TITLE
Cannot split a chunk that has already been edited (Watch API only)

### ISSUE THREAD

**Issue by haseebanwar** [rollup/rollup#4415]
### Rollup Version

2.67.3

### Operating System (or Browser)

Windows

### Node Version (if applicable)

16

### Link To Reproduction

https://github.com/haseebanwar/rollup-issue
After cloning the repo, if you run
```shell
npm run build
```
It will work fine but if you run
```shell
npm start
```
You will see the error

### Expected Behaviour

It bundles

### Actual Behaviour

It doesn't bundle

I am using [rollup-plugin-terser](https://www.npmjs.com/package/rollup-plugin-terser) as an output plugin. Not sure if this is an error from rollup or the terser plugin. The reason I am creating an issue here first is that rollup only throws this error when I use the watch API. It works fine with `rollup.rollup` function.

[#2660](https://github.com/rollup/rollup/issues/2660) and [#2676](https://github.com/rollup/rollup/issues/2676) looks familiar

**Comment by haseebanwar** [comment]
Excuse me if I am asking too early, but do we have any updates on this? This is stopping a very crucial function of our build tool. I am also trying to figure out the issue myself but no leads now.

**Comment by lukastaegert** [comment]
This error is usually generated by magicstring, which is responsible for generating sourcemaps in Rollup and some other plugins. Did not find time to look into this, though.

**Comment by haseebanwar** [comment]
I hope someone will pick it soon

**Comment by danielbayerlein** [comment]
https://github.com/Rich-Harris/magic-string/issues/208

**Comment by haseebanwar** [comment]
Hi @lukastaegert, were you able to look into this?

Thanks

**Comment by lukastaegert** [comment]
We finally have a fix for this at #4589
