### ISSUE TITLE
Optional chaining cannot appear in left-hand side

### ISSUE THREAD

**Issue by ohabash** [rollup/rollup#4420]
### Rollup Version

rollup@2.68.0

### Operating System (or Browser)

mac

### Node Version (if applicable)

v14.16.0

### Link To Reproduction

Replicating the bug is impossible as the infected code is not known

### Expected Behaviour

I am trying to build my angular application but rollup throws an error

### Actual Behaviour

I am trying to build my angular application but rollup throws an error

>Optional chaining cannot appear in left-hand side (Note that you need plugins to import files that are not JavaScript)
Error: Optional chaining cannot appear in left-hand side (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/omar/Sites/met-libs-nx/node_modules/rollup/dist/shared/rollup.js:159:30)
    at Module.error (/Users/omar/Sites/met-libs-nx/node_modules/rollup/dist/shared/rollup.js:12437:16)
    at Module.tryParse (/Users/omar/Sites/met-libs-nx/node_modules/rollup/dist/shared/rollup.js:12813:25)
    at Module.setSource (/Users/omar/Sites/met-libs-nx/node_modules/rollup/dist/shared/rollup.js:12716:24)
    at ModuleLoader.addModuleSource (/Users/omar/Sites/met-libs-nx/node_modules/rollup/dist/shared/rollup.js:22191:20)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
![Screen Shot 2022-02-28 at 6 19 52 PM](https://user-images.githubusercontent.com/15847500/156080871-308966ea-6503-4dc5-9e5b-b507edbb3900.png)

I have asked ng-packagr and angular and it seems the problem is with rollup. However changing rollup version numbers or looking for infected code has not provided a solution 

is there any help you can provide on this issue?

### Other dependancies
```
Angular CLI: 13.2.5
Node: 14.16.0
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 13.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@angular/fire                   7.2.1
@schematics/angular             13.2.5
ng-packagr                      13.2.1
rxjs                            6.6.7
typescript                      4.5.5
```

**Comment by lukastaegert** [comment]
The error is thrown by acorn, which is Rollup's embedded parser. However, without a reproduction or information about the file that is throwing the error, I have little hope anyone will be able to help you. I think it is also possible that it tries to import a non-JavaScript file which contains some `.?` in some place.

In any case, even though Rollup emits the error, Rollup also emits all the necessary information about the error location in form of the `Error.loc` and `Error.frame` attributes. If angular CLI is swallowing this information, it should be a ticket to them to expose it, otherwise it is indeed close to impossible to debug this.

**Comment by ohabash** [comment]
It would be really hard to make a reproduction as I dont know which, if any, of the 1000s of dependencies and files may be causing the error. But i will start with all my deps and aligned version numbers and see if it will error out the same. 

Thank you for telling me about the `Error.loc` I will look deeper. I understand why the direct problem cannot be pointed out in this forum however I would be very happy to hear debug advice. Next steps are becoming very blurry and weeks are passing. 😅

**Comment by ohabash** [comment]
This was our solution. https://github.com/ng-packagr/ng-packagr/issues/2259#issuecomment-1057218567

would have been nice to see the error source in the throw but thanks for helping.

**Comment by ohabash** [comment]
This was our solution. https://github.com/ng-packagr/ng-packagr/issues/2259#issuecomment-1057218567

would have been nice to see the error source in the throw but thanks for helping.

**Comment by lukastaegert** [comment]
> would have been nice to see the error source in the throw but thanks for helping

Do not forget to forward this to angular-CLI 😉 Rollup's CLI would have shown the error location
