### ISSUE TITLE
How to keep [hash] unchanged when in different path

### ISSUE THREAD

**Issue by l1shu** [rollup/rollup#4426]
I found same source file will create different [hash] when in different file path. 

How to keep their hash unchanged even they are in different file path? Just according to their content, like [contenthash]

**Comment by frank-dspeed** [comment]
this should maybe get renamed and joined with the issues @surma from google about deterministic hashing which is on the list of the web tooling report.

**Comment by lukastaegert** [comment]
Should be fixed with #4543
