### ISSUE TITLE
Hoisted functions inside block statements are inadvertently removed, even when used

### ISSUE THREAD

**Issue by unleashy** [rollup/rollup#4430]
### Rollup Version

v2.69.1

### Operating System (or Browser)

Windows 10

### Link To Reproduction

https://rollupjs.org/repl/?version=2.69.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTVDdCU3QiU1Q24lNUN0JTVDdGZ1bmN0aW9uJTIwYSgpJTIwJTdCJTdEJTVDbiU1Q3QlN0QlNUNuJTVDdHJldHVybiUyMGEoKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behaviour

Rollup must not get rid of the hoisted function `a`, even though it is within a block; i.e. this should be the output:

```js
function foo() {
  {
    function a() {}
  }

  return a();
}

export { foo };
```

This happens regardless of what's inside `a`, even if it is side-effectful or not.

### Actual Behaviour

Rollup removes the function `a` inside the block as if it isn't hoisted and then used, creating totally invalid code.

**Comment by lukastaegert** [comment]
Wow, this looks like a serious scoping bug. I will have a look.

**Comment by lukastaegert** [comment]
Actually, this behaviour is entirely correct (and we even placed a comment in the code to remind us https://github.com/rollup/rollup/blob/994c1eccf4d53e416a010f47e54a2086f1a0f4e9/src/ast/nodes/Identifier.ts#L70)

As vanilla Rollup only processes ES modules, it assumes that all code is using strict mode even if it is not explicitly declared as such (which is the case for ES modules). In strict mode if there was a global variable `a`, `foo` would indeed call this global variable. If there is no such variable, the code just throws an error.

Just try to run this in a browser console:

```js
function foo() {
	'use strict';
	{
		function a() {}
	}
	return a();
}
foo();
```

Interestingly, this was considered kind of invalid/non-standardized syntax in ES3/ES5 times https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#paving_the_way_for_future_ecmascript_versions but has been allowed with ES2015 but with the semantics that Rollup uses.

**Comment by unleashy** [comment]
Oh wow yeah that makes complete sense. I totally forgot about this part of strict mode, woops! Sorry for wasting your time and thank you very much!
