### ISSUE TITLE
How to get the `rootDir` in the build hooks

### ISSUE THREAD

**Issue by tzachbon** [rollup/rollup#4435]
We are developing a plugin and we need to know the project's `rootDir` (The base directory, an absolute path, for resolving entry points from the configuration) inside the `buildStart`.
Does rollup provide this information?

**Comment by lukastaegert** [comment]
Rollup CLI uses `process.cwd()` as a reference point. Other than that, no.

**Comment by tzachbon** [comment]
Alright, thanks for the quick response
