### ISSUE TITLE
Rollup build fails on windows: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by lovettchris** [rollup/rollup#4439]
### Rollup Version

2.70.0

### Operating System (or Browser)

Windows 11

### Node Version (if applicable)

v16.14.0

### Link To Reproduction

https://github.com/Vtec234/vscode-lean4

### Expected Behaviour

The following steps should build without error - it builds without error on Linux, but not on Windows:

1. git clone https://github.com/Vtec234/vscode-lean4
2. git checkout infoview-hooks
3. npm install
4. npx lerna bootstrap
5. npm run build

This even passes in an MSYS2 environment on the same windows machine using the exact same npm and nodejs binaries.  

### Actual Behaviour

On Windows I get this error:
```
[!] SyntaxError: Cannot use import statement outside a module
d:\Temp\vtec234\vscode-lean4\lean4-infoview\rollup.config.js:1
import commonjs from '@rollup/plugin-commonjs';
^^^^^^
```

On debugging the error is originating here:

```
SyntaxError: Cannot use import statement outside a module
  at Object.compileFunction (node:vm:352:18)
  at wrapSafe (node:internal/modules/cjs/loader:1032:15)
  at Module._compile (node:internal/modules/cjs/loader:1067:27)
  at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
  at Object.require.extensions.<computed> [as .js] (c:\\Users\\clovett\\AppData\\Roaming\\npm\\node_modules\\rollup\\dist\\shared\\loadConfigFile.js:617:13)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at Module.require (node:internal/modules/cjs/loader:1005:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at loadConfigFromBundledFile (c:\\Users\\clovett\\AppData\\Roaming\\npm\\node_modules\\rollup\\dist\\shared\\loadConfigFile.js:622:42)
```

**Comment by kenpower** [comment]
UPDATE

omg, this is such a stupid bug! My project folder is `Abc`, but I went there with `cd abc`. Surprisingly, the cd worked in git-bash (windows) even though there was case mismatch between folder name and `cd` argument . 

Fixed rollup by doing `cd .. & cd Abc`.

**Comment by lovettchris** [comment]
The point of the bug is that rollup on Windows (not git-bash) should not be sensitive to case of drive letters of folder names.  You should not have to do "cd Abc" for rollup to be happy.

**Comment by furstenberg** [comment]
We see the same error. Unsure if it's the same issue, since for us it changed with v2.67.0. 

If we use v.2.66.1 everything works. Update to v2.67.0+ and it gives "SyntaxError: Cannot use import statement outside a module".

**Comment by lukastaegert** [comment]
Can you check if this issue still persists in rollup@2.74.0?

**Comment by lovettchris** [comment]
not quite, the error moved from:
```
[!] SyntaxError: Cannot use import statement outside a module
d:\git\leanprover\vscode-lean4\lean4-infoview\rollup.config.js:1
```
to:
```
src/index.ts, src/react-popper.ts → dist...
[!] (plugin typescript) Error: ENOENT: no such file or directory, mkdir '.rollup.cache\d:\git\leanprover\vscode-lean4\lean4-infoview\dist\infoview'
```

Notice the bogus "rollup.cache" path that is followed by a "drive letter" (d:) which is an illegal path on Windows.  So some sort of "path join" operation has failed to recognize a full path here.

**Comment by lukastaegert** [comment]
Since Rollup does not have a disk cache, I would assume it is some plugin or something in your build pipeline that is doing this.

**Comment by lovettchris** [comment]
I found the culprit, another similar casing bug in typescript TSCache implementation, I'll file a bug against them, thanks.
```
    cachedFilename(fileName) {
        return path__default["default"].join(this._cacheFolder, fileName.replace(/^([A-Z]+):/, '$1'));
    }
```
