### ISSUE TITLE
mbostock/smash like use case

### ISSUE THREAD

**Issue by btakita** [rollup/rollup#445]
I have a bunch of legacy javascript files that define & use global variables.

No es6, no commonjs, no amd.

I just want to smash these files together, just like smash did.

Is this possible in rollup? I havn't figured out how...

**Comment by Victorystick** [comment]
It is not currently possible due to ES module semantics. If I understand SMASH correctly, it just concatenates files based on `import`s; all files are executed in the same scope. According to ES2015 module semantics, each module should be evaluated in its own scope, meaning that a function defined in one module won't be visible in another unless explicitly exported and imported.

**Comment by btakita** [comment]
Then your documentation on your homepage is misleading & confusing. This is the real world, with real js files that aren't always es6.

~~~javascript
import { cube } from './maths.js';
console.log( cube( 5 ) ); // 125
~~~

~~~ javascript
// This function isn't used anywhere, so
// Rollup excludes it from the bundle...
export function square ( x ) {
	return x * x;
}

// This function gets included
export function cube ( x ) {
	// rewrite this as `square( x ) * x`
	// and see what happens!
	return x * x * x;
}
~~~

~~~javascript
'use strict';

// This function gets included
function cube ( x ) {
	// rewrite this as `square( x ) * x`
	// and see what happens!
	return x * x * x;
}

console.log( cube( 5 ) ); // 125
~~~

**Comment by eventualbuddha** [comment]
Rollup has plugins that allow it to work with other module formats, such as rollup-plugin-commonjs. The homepage says several times that it operates on ES2015 modules, so I'm not sure what change we could make to clarify it. Would a guide on transitioning to ES2015 from other formats be useful?

**Comment by Rich-Harris** [comment]
A while back I tried a similar thing – porting D3 (which used SMASH) to ES6 modules: https://github.com/rollup/d3-jsnext. I struggled with some things like `d3.event` (which many different modules can set, violating the rules of ES6 modules), and the project has been totally superseded by D3v4 which is being built with ES6 modules, but it basically worked.

Essentially you need to figure out which variable is exported by each module, and add export statements accordingly:

```js
// this...
var foo = 'bar';
function baz () {}

// becomes this:
export var foo = 'bar';
export function baz () {}
```

Then, with the map of exports you generate during that process, you add import statements by identifying which undeclared variables are used in each module:

```js
// this...
console.log( foo );
baz();

// becomes this...
import { foo, baz } from '../some-module.js';

console.log( foo );
baz();
```

That's basically what's involved. It's not something that could be handled by a Rollup plugin; it would need to be a separate SMASH -> ES6 migration script. Unfortunately it's not trivial – you need to generate an AST, attach scope information, and do a bunch of analysis – but if there are many SMASH codebases in the wild then maybe a migration tool would be a useful thing to have. It's out of Rollup's scope though, unfortunately.

**Comment by btakita** [comment]
It's more than smash.

It's all of the legacy javascript libraries that interact with global
variables. Literally the majority of javascript...

On Tue, Jan 12, 2016 at 8:46 AM, Rich Harris <notifications@github.com>
wrote:

> A while back I tried a similar thing – porting D3 (which used SMASH) to
> ES6 modules: https://github.com/rollup/d3-jsnext. I struggled with some
> things like d3.event (which many different modules can set, violating the
> rules of ES6 modules), and the project has been totally superseded by D3v4
> which is being built with ES6 modules, but it basically worked.
>
> Essentially you need to figure out which variable is exported by each
> module, and add export statements accordingly:
>
> // this...var foo = 'bar';function baz () {}
> // becomes this:export var foo = 'bar';export function baz () {}
>
> Then, with the map of exports you generate during that process, you add
> import statements by identifying which undeclared variables are used in
> each module:
>
> // this...console.log( foo );baz();
> // becomes this...import { foo, baz } from '../some-module.js';
> console.log( foo );baz();
>
> That's basically what's involved. It's not something that could be handled
> by a Rollup plugin; it would need to be a separate SMASH -> ES6 migration
> script. Unfortunately it's not trivial – you need to generate an AST,
> attach scope information, and do a bunch of analysis – but if there are
> many SMASH codebases in the wild then maybe a migration tool would be a
> useful thing to have. It's out of Rollup's scope though, unfortunately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rollup/rollup/issues/445#issuecomment-170915772>.
>



-- 
Brian Takita
briantakita.com
about.me/brian_takita

**Comment by btakita** [comment]
> Would a guide on transitioning to ES2015 from other formats be useful?

Yes! The more docs the better. Is the `rollup` api mature?

**Comment by btakita** [comment]
i ended up using a json file to define the files to concatenate using `gulp-concat`.

**Comment by Rich-Harris** [comment]
> It's more than smash.

That's a very good point – porting a SMASH codebase to ES6 actually involves *ignoring* the existing import statements.

I can see the value in a migration tool that, given a set of legacy files, is able to figure out the various imports and exports and make them explicit. It's not even Rollup-specific. I don't have time to work on such a tool right now, but perhaps one day, if no-one beats me to it.

**Comment by btakita** [comment]
i ended up concatenating files defined in a json file using shelljs.cat.

it also supports `--watch`.

right now, it's not something that is releasable as a general tool. i'll
clean up the code & paste a snippet, if nobody beats me to it
​
