### ISSUE TITLE
Absolute path issues

### ISSUE THREAD

**Issue by gokul1630** [rollup/rollup#4454]
I have a problem with absolute import,
while development absolute imports work fine but after bundle, I got error like shown in the image,
but if I use relative import  in development and after bundling the package everything works fine
![image](https://user-images.githubusercontent.com/43679827/161434077-d66baeb2-6b84-4932-a230-0e7e1e28b664.png)

**Comment by lukastaegert** [comment]
Looking at your screenshot, I do not think we will fix issues with parcel here. Also, please do not remove the issue template and add a Validation reproduction the next time you create an issue.
