### ISSUE TITLE
Circular Dependency: Range Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sandeep-gh** [rollup/rollup#4459]
### Rollup Version

2.70.1

### Operating System (or Browser)

OpenBSD

### Node Version (if applicable)

12.22.6

### Link To Reproduction

https://github.com/sandeep-gh/rollup_circular_dependency_bug

### Expected Behaviour

The command should create a bundled javascript consisting of main.js and all the javascript libraries produced from transcrypt

### Actual Behaviour

Runs into recursive function calls eventually exceeding the max stack size. The addict.py is not the most mature code but still rollup shouldn't end up with recusive function call.

**Comment by sandeep-gh** [comment]
I have very painstakingly created a git repo that recreates the bug. Would be good even if some high level  idea what could be wrong, or generally how to approach a fix/workaround. Also,  I see too many untriaged bugs, its a bit unsettling to use in production.

**Comment by lukastaegert** [comment]
Thanks! I could boil down your repo to this minimal reproduction: https://rollupjs.org/repl/?version=2.70.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QkRpY3QlMjBhcyUyMEFkZGljdCUyQyUyMERpY3QlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRm1haW4uanMlNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMCU3QkRpY3QlMkMlMjBBZGRpY3QlN0QlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

As you can see, the code is invalid as it is reexporting something from itself that does not exist. If you run it in a browser, you will get something like this:
<img width="639" alt="cycle" src="https://user-images.githubusercontent.com/12949268/164878791-d0891e8d-49c3-44d6-9e47-8588b5476172.png">

But I agree that Rollup should not crash but instead display a helpful error in such a situation. I will look into it. And this should also be a case that should be "fixable" via https://rollupjs.org/guide/en/#shimmissingexports

**Comment by lukastaegert** [comment]
#4472 should at least give you the proper error.

**Comment by sandeep-gh** [comment]
Thank you so much. I get the issue, I think.  There seems to  a problem with the python to javascript translator.  Will close the issue for now as a not a rollup bug. Thanks so much again.
