### ISSUE TITLE
`import.meta.url` transformation produces invalid file URL strings

### ISSUE THREAD

**Issue by mdjermanovic** [rollup/rollup#4461]
### Rollup Version

2.70.1

### Operating System (or Browser)

Windows

### Node Version (if applicable)

v16.14.0

### Link To Reproduction

https://github.com/mdjermanovic/rollup-import-meta-url-repro

### Expected Behaviour

`import.meta.url` to be transformed to an expression that always evaluates to valid URL strings.

### Actual Behaviour

When `__filename` contains special characters or sequences such as `%2F`, `new (require('u' + 'rl').URL)('file:' + __filename).href` could be an invalid file URL string.

```
node:internal/modules/cjs/loader:1216
      throw new ERR_INVALID_ARG_VALUE('filename', filename,
      ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:///C:/milos/rollup-import-meta-url-repro/my%2Fdir/index.cjs'
    at new NodeError (node:internal/errors:371:5)
    at Function.createRequire (node:internal/modules/cjs/loader:1216:13)
    at Object.<anonymous> (C:\milos\rollup-import-meta-url-repro\my%2Fdir\index.cjs:5:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_INVALID_ARG_VALUE'
}

```

Ref: https://github.com/eslint/eslint/issues/15766

**Comment by fasttime** [comment]
I can imagine a modest potential for misuse, considering that, for instance, `file:/home/someuser/workspace/my_project/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/hosts#foo=1/subfolder/index.js` resolves to the same path as `file:/etc/hosts` ([demo link](https://runkit.com/fasttime/6256d2580f199f000a7a351f)).

**Comment by sveinnthorarins** [comment]
Ran into this problem today, can't run vite cause my project path contains a '#' symbol and vite is bundled with rollup.

Why is nobody taking a look at this?

**Comment by lukastaegert** [comment]
PR welcome

**Comment by fasttime** [comment]
@sveinnthorarins I could be wrong but your issue may be a different one as Rollup intentionally replaces some characters like `"#"` with underscores for compatibility across file systems. I went on and did a [PR](https://github.com/rollup/rollup/pull/4875) for the bug here.

**Comment by sveinnthorarins** [comment]
@fasttime Thanks for making the PR.

Yeah well, from tracking my problem and its error messages, the issue stated here (the poor transformation of `import.meta.url` into `new URL(filePath).href`) is my first and main concern.

The issue you're mentioning might then take on the mantle (of causing me problems) after this issue is fixed :laughing: :flushed:
