### ISSUE TITLE
Dead-code elimination of unused default parameters

### ISSUE THREAD

**Issue by bitjson** [rollup/rollup#4466]
### Feature Use Case

I maintain [Libauth](https://github.com/bitauth/libauth/), a library that offers WebAssembly crypto implementations (`ripemd160`, `sha1`, `sha256`, `sha512`, and `secp256k1`). As a [pure ESM library](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), Libauth can asynchronously instantiate each WASM implementation internally, exporting simple interfaces that behave like collections of JS-only functions (with better performance). Many of Libauth's exported functions also use one of these built-in WASM instances as a default parameter. For example, `decodeBase58Address` has the definition:

```ts
export const decodeBase58Address = (
  address: string,
  sha256: { hash: (input: Uint8Array) => Uint8Array } = internalSha256
) => {
  // ...
};
```

Most applications can simply call `decodeBase58Address(address)` to automatically use the default, WASM-based `sha256` implementation (`internalSha256`).

However, applications that already have another `sha256` implementation can provide that implementation as the second parameter: `decodeBase58Address(address, mySha256Implementation)`. In this case, the default parameter (`internalSha256`) is dead code and should be possible to eliminate from the application's bundle, saving hundreds of KBs from those bundles.

### Feature Proposal

During dead-code elimination/tree shaking, default parameters that aren't used by the bundle can be removed.

For this simple example:

`module.js`:
```js
const internalAdd = (a, b) => (a === '0' ? b : a + b); // should not appear in bundle
export const addAndLog = (a, b, impl = internalAdd) => console.log(impl(a, b));
```

`app.js`:

```js
import { addAndLog } from './module.js';
const myAdd = (a, b) => a + b;
addAndLog(1, 2, myAdd); // => 3
```

The produced bundle should include only:
```js
const addAndLog = (a, b, impl) => console.log(impl(a, b));
const myAdd = (a, b) => a + b;
addAndLog(1, 2, myAdd); // => 3
```

A detailed example (testing with all known bundlers) is available at this repo: https://github.com/bitjson/shake-default-params

**Comment by lukastaegert** [comment]
Hi, sorry for the silence. I think this is actually an interesting idea and while it is quite non-trivial, I did some work in #4498 which should make this possible. You can already try this out, there are just some small things I want to polish.

**Comment by lukastaegert** [comment]
#4498 is ready now, you can check in the REPL how it handles your example https://rollupjs.org/repl/?pr=4498&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGFkZEFuZExvZyUyMCU3RCUyMGZyb20lMjAnLiUyRm1vZHVsZS5qcyclM0IlNUNuY29uc3QlMjBteUFkZCUyMCUzRCUyMChhJTJDJTIwYiklMjAlM0QlM0UlMjBhJTIwJTJCJTIwYiUzQiU1Q25hZGRBbmRMb2coMSUyQyUyMDIlMkMlMjBteUFkZCklM0IlMjAlMkYlMkYlMjAlM0QlM0UlMjAzJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwaW50ZXJuYWxBZGQlMjAlM0QlMjAoYSUyQyUyMGIpJTIwJTNEJTNFJTIwKGElMjAlM0QlM0QlM0QlMjAnMCclMjAlM0YlMjBiJTIwJTNBJTIwYSUyMCUyQiUyMGIpJTNCJTIwJTJGJTJGJTIwc2hvdWxkJTIwbm90JTIwYXBwZWFyJTIwaW4lMjBidW5kbGUlNUNuZXhwb3J0JTIwY29uc3QlMjBhZGRBbmRMb2clMjAlM0QlMjAoYSUyQyUyMGIlMkMlMjBpbXBsJTIwJTNEJTIwaW50ZXJuYWxBZGQpJTIwJTNEJTNFJTIwY29uc29sZS5sb2coaW1wbChhJTJDJTIwYikpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by bitjson** [comment]
@lukastaegert wow, fantastic! Thanks so much for working on this! Looking forward to seeing the PR land 👍
