### ISSUE TITLE
Error message points to dead Repository

### ISSUE THREAD

**Issue by FelixBenning** [rollup/rollup#4469]
### Rollup Version

v2.70.2

### Operating System (or Browser)

Firefox

### Node Version (if applicable)

v16.13.2

### Link To Reproduction

https://github.com/FelixBenning/bibcite/tree/98a811bfb19f435eb1e88c9d517fa4c8725935fe

### Expected Behaviour

The warning should be helpful/no warning and things just work

### Actual Behaviour

The repository https://github.com/snowpackjs/rollup-plugin-polyfill-node does not exist anymore and I get the following error message pointing to it

```
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on "path", "url", "stream", "http", "punycode", "https" and "zlib". You might need to include https://github.com/snowpackjs/rollup-plugin-polyfill-node
```

I am also using `import nodePolyfills from "rollup-plugin-polyfill-node";` So I really just expect things to work :(

**Comment by frank-dspeed** [comment]
@FelixBenning this is not a ErrorMessage it is a so called Warning you can catch it via 
rollup.config.js
```
export default {
    input: []
    onwarn(warning, warn) {
     // this calls warn on every warning exempt CIRCULAR_DEPENDENCY 
     message.code !== 'CIRCULAR_DEPENDENCY') && warn(warning)
   }
}
```

https://rollupjs.org/guide/en/#onwarn
