### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by naorye** [rollup/rollup#447]
Importing from symlink doesn't work. For example:

```
import func from 'common/script/func';

func();
```

Where 'common' is a symlink in 'node_modules'.
The resulting file is the sameas the original.

**Comment by mmolhoek** [comment]
would love to see this one fixed/merged, so ionic 2 will read npm linked modules correctly

**Comment by pascalrijk** [comment]
+1

**Comment by scottopolis** [comment]
I'm having this issue as well.

**Comment by patriknyblad** [comment]
+1

**Comment by Rich-Harris** [comment]
Finally fixed in 0.37.1

**Comment by yaycmyk** [comment]
@Rich-Harris Would it be possible to deduplicate followed-symlinks?

I'm using a lerna monorepo and consume the same module in many other packages, but once the symlink has been followed, it isn't identified as already being in the corpus of imported modules and thus is included many times in the master bundle.

**Comment by longlho** [comment]
ping @Rich-Harris ^^
