### ISSUE TITLE
Rollup doesn't respect `sideEffects`

### ISSUE THREAD

**Issue by pd4d10** [rollup/rollup#4470]
### Rollup Version

2.70.1

### Operating System (or Browser)

macOS

### Node Version (if applicable)

16

### Link To Reproduction

https://stackblitz.com/edit/node-lr98tg

### Expected Behaviour

As `lib/common.js` are listed in the `sideEffects` field, these lines should not be removed:

https://github.com/wooorm/lowlight/blob/0803fc3416cbdf59f204da243313e3315eb34617/lib/common.js#L1-L36

### Actual Behaviour

They are removed incorrectly

#### Reproduce steps

1. Open the reproduction link above
2. run `npm run build`
3. Check if the JS output has these `highlight.js` languages code bundled in

Related issues:
https://github.com/vitejs/vite/issues/7635
https://github.com/rollup/plugins/issues/1159

**Comment by fregante** [comment]
There are more issues found in Vite as well:

- https://github.com/vitejs/vite/issues/10735#issuecomment-1427557199

**Comment by lukastaegert** [comment]
Fix at #4867
