### ISSUE TITLE
Unable to rebuild on Linux platform

### ISSUE THREAD

**Issue by guimard** [rollup/rollup#4476]
### Rollup Version

2.70.2

### Operating System (or Browser)

Debian

### Node Version (if applicable)

14.19.1

### Link To Reproduction

https://github.com/rollup/rollup.git itself

### Expected Behaviour

Able to rebuild rollup from sources

### Actual Behaviour

rollup build depends on fsevents which isn't available on Linux platform, so build fails with the following error:
```
$ npm run build
[...]
cli/run/loadConfigFile.ts, src/node-entry.ts → dist...
[!] Error: Could not resolve '../../../src/watch/fsevents-importer' from ../../../src/watch/fsevents-importer?commonjs-external
Error: Could not resolve '../../../src/watch/fsevents-importer' from ../../../src/watch/fsevents-importer?commonjs-external
```

**Comment by dnalborczyk** [comment]
this is a bit surprising as the ci also runs on linux: https://github.com/rollup/rollup/runs/6169265611?check_suite_focus=true

github actions uses `ubuntu`, based on `debian`.  🤔

**Comment by guimard** [comment]
Hi @dnalborczyk,

I just forked https://github.com/rollup/rollup and tries to reproduce build.

Cheers,

**Comment by dnalborczyk** [comment]
if it helps, here is a `Dockerfile` if you are familiar with `docker`

`Debian 11` with `node.js v14.19.1` pre-installed.

```Dockerfile
FROM node:14.19.1-bullseye

RUN git clone https://github.com/rollup/rollup.git --depth=1 && \
    cd rollup && \
    npm ci && \
    npm test
```

in the shell:
```shell
docker build .
```

**Comment by guimard** [comment]
Hi,

found, was a bad hook in my Debian packaging hooks.

Thanks!

**Comment by ibraelillo** [comment]
@guimard I'm having the same issue right now, may you expose what you did to solve it?

**Comment by guimard** [comment]
@ibraelillo: just to refresh node_modules/\*
