### ISSUE TITLE
How to ignore some imports?

### ISSUE THREAD

**Issue by dipakw** [rollup/rollup#4481]
Hi,

I've been playing around rollup and I find it good for my project. Now I am trying to bundle a `react` project and it works fine. However, I would like to tell rollup that `useEffect` is a global function so don't import its code into the bundle. To achieve this, I found there's a rollup option `output.globals`, but it didn't work, maybe I didn't know how to use that?

Below is my rollup configuration, but it still imports the `useEffect` code into the bundle.

```js
{
  output: {
    globals: {
      "react": "useEffect"
    }
  }
}
```

There is another option called `external`, so if I set `external: ["react"]`, it converts the import statement to `var react = require('react')` and wherever the `useEffect` called, it places `react.useEffect`. It's a bit better than the previous case in my case, however, I don't want this too for some reason.

I want rollup to treat that `useEffect` as a global function. I am aware that if I remove `import { useEffect } from "react";` it does what I want, however, for some reason I need to have that import statement and rollup needs to ignore it.

**Comment by lukastaegert** [comment]
Something like a plugin

```js
{
  resolveId(id) {
    // To make it simpler and not replace it with a file system path
    if (id === 'react') return 'react';
  },
  load(id) {
    if (id === 'react') return 'export const useEffect = window.useEffect';
  }
}
```

Only downside is that it replaces react with a module that ONLY has the useEffect export. You could also extend this to merge in the other react exports via `export * from 'react'` except then you need to add an exception to the resolver to resolve `react` correctly when imported from a module with id `react`.

**Comment by dipakw** [comment]
Hey thanks @lukastaegert 

Another thing is, do you have any idea like used functions and variables must be declared? For example if I am using a variable which is not declared yet, rollup doesn't throw any error, it just compiles successfully.

**Comment by lukastaegert** [comment]
It certainly helps to declare variables, otherwise they are considered global variables by Rollup, and your code will throw when you access them and they do not exist.

**Comment by dipakw** [comment]
I knew that @lukastaegert 

Is there any way to enable variables/functions declarations check? Any plugin? I didn't find.

**Comment by lukastaegert** [comment]
I would see this as the responsibility of static code analysis, e.g.
* https://eslint.org/docs/rules/no-implicit-globals
* https://eslint.org/docs/rules/no-undef

You could run eslint also as a Rollup plugin if you wanted to.

**Comment by dipakw** [comment]
Hey @lukastaegert 

Thanks mate, eslint did the job.
