### ISSUE TITLE
feat(): Serial Mode for builds

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/rollup#4500]
### Feature Use Case

I want to use rollup programatical in other environments and compat layer and loader like browsers, raw v8, graaljs, deno, limitless

some engines like electron for example do need to listen for native sideEffects this forces the need to use sync code 
so the ESM module system can not get used to bootstrap a electron environment but also rollup can not get used because it returns a promise

### Feature Proposal

create a rollupSync export that only uses sync features of rollup and implement some sync features :)

**Comment by lukastaegert** [comment]
I would recommend to run some transpilation step across Rollup that replaces async/await with Promises and then inject a synchronous Promise replacement. At least from my side, there is no capacity or interest to enable a synchronous flow as asynchronicity is deeply baked into many parts of Rollup that can be touched by plugins. And it might be extended in the future once we explore ways to parallelize builds.

**Comment by frank-dspeed** [comment]
ok i expected such a answer my workaround is to build rollup binary and this way abstract the async js flow via child_process
