### ISSUE TITLE
New rollup version results in different generated output and drops some if/else cases

### ISSUE THREAD

**Issue by digaus** [rollup/rollup#4504]
### Rollup Version

2.74.0

### Operating System (or Browser)

MacOS, Linux, Windows

### Node Version (if applicable)

12.x.x

### Link To Reproduction

https://github.com/digaus/rollup-demo

### Expected Behaviour

Since 2.74.0 angular lib compilation now produces different and wrong results.

This is a major issue for us and might break other libs and applications because it is not noticed while compiling. It completely drops use cases... 

This happens when bundling to `FESM2015`. In `ESM2015` code still looks fine...

Adding `"rollup": "2.73.0"` to the `package.json` fixes this for now...

See https://github.com/digaus/rollup-demo for reproduction

### Actual Behaviour

Do not drop any code :)

**Comment by costingeana** [comment]
Hello, guys,
I observed this behavior in the morning, but I thought I am doing something wrong. Please compare the following code snippets:

- code is removed (it should not): [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjAlN0IlNUNuJTIwZjElNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGlicmFyeS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
- code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RyZXR1cm4lMjBmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lMjAlMkIlMjAzJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
- code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJTVDJTIyYWJjZCU1QyUyMiklM0IlNUNuJTVDdHJldHVybiUyMHRva2VuJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by digaus** [comment]
> Hello, guys, I observed this behavior in the morning, but I thought I am doing something wrong. Please compare the following code snippets:
> 
> * code is removed (it should not): [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjAlN0IlNUNuJTIwZjElNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGlicmFyeS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
> * code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RyZXR1cm4lMjBmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lMjAlMkIlMjAzJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
> * code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJTVDJTIyYWJjZCU1QyUyMiklM0IlNUNuJTVDdHJldHVybiUyMHRva2VuJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
> 
> I hope they help you to identify the issue(s).

Yes same here. Thought I was too stupid 🤷‍♂️ Refactored code and had the issue from the other issue here. That's how I identified rollup as the cause.

**Comment by lukastaegert** [comment]
> Hello, guys,
I observed this behavior in the morning, but I thought I am doing something wrong. Please compare the following code snippets:
> code is removed (it should not): [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjAlN0IlNUNuJTIwZjElNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGlicmFyeS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RyZXR1cm4lMjBmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lMjAlMkIlMjAzJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJTVDJTIyYWJjZCU1QyUyMiklM0IlNUNuJTVDdHJldHVybiUyMHRva2VuJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
I hope they help you to identify the issue(s).

All of them look correct to me:
* In the first example, `f2` does not have a side effect and the return value is not used -> remove
* In the second example, the return is used -> we need to keep it
* In the third example, `f2` has a side effect in calling a global function -> keep it

**Comment by digaus** [comment]
> > Hello, guys,
> > I observed this behavior in the morning, but I thought I am doing something wrong. Please compare the following code snippets:
> > code is removed (it should not): [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjAlN0IlNUNuJTIwZjElNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGlicmFyeS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
> > code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RyZXR1cm4lMjBmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwdG9rZW4lMjAlMkIlMjAzJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
> > code is not removed: [link](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZjEodG9rZW5zJTJDJTIwaWR4KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjB0b2tlbiUyMCUzRCUyMHRva2VucyU1QmlkeCU1RCUzQiU1Q24lNUN0JTVDbiU1Q3RmMih0b2tlbiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGYyKHRva2VuKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJTVDJTIyYWJjZCU1QyUyMiklM0IlNUNuJTVDdHJldHVybiUyMHRva2VuJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTVDbiUyMGYxJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
> > I hope they help you to identify the issue(s).
> 
> All of them look correct to me:
> 
> * In the first example, `f2` does not have a side effect and the return value is not used -> remove
> * In the second example, the return is used -> we need to keep it
> * In the third example, `f2` has a side effect in calling a global function -> keep it

What about my use case? 🙈

**Comment by lukastaegert** [comment]
I will need more time for the original issue. The repo will help, but I have some family things coming up. Therefore I reverted the main feature from 2.74.0 for now in a 2.74.1 release so that I can take some time to understand the issue properly. Hope 2.74.1 fixes your issue for now? But please keep this one open as I want to roll back the revert soon once I got things figured out.

**Comment by costingeana** [comment]
Hello again,
Indeed, my first example wasn't good for highlighting the problem I encountered. I apologize.
I attached below 2 more code snippets that are closer to the code where I observed the problem. The code is a bit messy, but as I said previously, I tried to preserve the context.
- [parameter is removed: check the call of getParams function](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwbnVtYmVyKHRva2VucyUyQyUyMGlkeCUyQyUyMHBhcnNlck9wdGlvbnMlMkMlMjBlbnYlMkMlMjBvcHRpb25zJTIwJTNEJTIwJTdCJTdEKSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHRva2VuJTIwJTNEJTIwdG9rZW5zJTVCaWR4JTVEJTNCJTVDdCU1Q24lNUN0JTVDbiU1Q3RsZXQlMjBudW1iZXJDb250ZW50JTNCJTVDbiUyMCUyMCUyMCUyMHRyeSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBudW1iZXJDb250ZW50JTIwJTNEJTIwbmV3JTIwSW50bC5OdW1iZXJGb3JtYXQob3B0aW9ucy5sb2NhbGUlMkMlMjBnZXRQYXJhbXModG9rZW4pKS5mb3JtYXQoY29udGVudCklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTIwY2F0Y2glMjAoZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbnVtYmVyQ29udGVudCUyMCUzRCUyMG5ldyUyMEludGwuTnVtYmVyRm9ybWF0KG9wdGlvbnMubG9jYWxlKS5mb3JtYXQoY29udGVudCklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMG51bWJlckNvbnRlbnQlM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGdldFBhcmFtcyh0b2tlbiklMjAlN0IlNUNuJTIwJTIwJTIwJTIwaWYlMjAodG9rZW4uYXR0cnMpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyME9iamVjdC5mcm9tRW50cmllcyh0b2tlbi5hdHRycyklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMCU3QiU3RCUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiU1Q24lMjBudW1iZXIlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGlicmFyeS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
- [function is removed (body and call): check the createCollapseButton function](https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwcmVuZGVyVG9vbGJhcihyZXFQYXlsb2FkKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMGNvZGVCbG9ja1RhYmxlJTIwJTNEJTIwcmVxUGF5bG9hZC50YXJnZXQlM0IlNUNuJTVDdCU1Q24lNUN0aWYlMjAoY29kZUJsb2NrVGFibGUuY2hpbGROb2RlcyU1QjIlNUQpJTIwJTdCJTVDbiU1Q3QlNUN0Y29uc3QlMjBjb2xsYXBzZUJsb2NrJTIwJTNEJTIwY29kZUJsb2NrVGFibGUuY2hpbGROb2RlcyU1QjIlNUQuY2hpbGROb2RlcyU1QjAlNUQlM0IlNUNuJTVDdCU1Q3Rjb25zdCUyMG5vT2ZIaWRkZW5MaW5lcyUyMCUzRCUyMGNvZGVCbG9ja1RhYmxlLmNoaWxkTm9kZXMlNUIxJTVELmdldEF0dHJpYnV0ZSgnZGF0YS1oaWRkZW5saW5lcycpJTNCJTVDbiU1Q3QlNUN0Y29uc3QlMjBjb2xsYXBzaWJsZUNvbnRlbnQlMjAlM0QlMjBjb2RlQmxvY2tUYWJsZS5jaGlsZE5vZGVzJTVCMSU1RCUzQiU1Q24lNUN0JTVDdCU1Q24lNUN0JTVDdGNvbGxhcHNlQmxvY2suY2hpbGROb2RlcyU1QjAlNUQuYXBwZW5kQ2hpbGQoY3JlYXRlQ29sbGFwc2VCdXR0b24uY2FsbCh0aGlzJTJDJTIwbm9PZkhpZGRlbkxpbmVzJTJDJTIwY29sbGFwc2libGVDb250ZW50KSklM0IlNUNuJTVDdCU3RCU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwY3JlYXRlQ29sbGFwc2VCdXR0b24obm9PZkhpZGRlbkxpbmVzJTJDJTIwY29sbGFwc2libGVDb250ZW50KSUyMCU3QiU1Q24lNUN0Y29uc3QlMjBjb2xsYXBzZUJ1dHRvbiUyMCUzRCUyMGNyZWF0ZUFwcCglN0Jub09mSGlkZGVuTGluZXMlMkMlMjBjb2xsYXBzaWJsZUNvbnRlbnQlN0QpJTNCJTVDbiU1Q3QlNUNuJTVDdHJldHVybiUyMGNvbGxhcHNlQnV0dG9uLiUyNGVsJTNCJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjBjcmVhdGVBcHAob3B0aW9ucyklMjAlN0IlNUNuJTVDdHJldHVybiUyMCU3QiU1Q24lNUN0JTVDdCUyRiUyRiUyMGl0JTIwZG9lc24ndCUyMG1hdHRlciUyMHdoYXQncyUyMGhlcmUlNUNuJTVDdCU3RCUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiU1Q24lMjByZW5kZXJUb29sYmFyJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYnJhcnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by digaus** [comment]
@lukastaegert 
2.74.1 seems to work for now, thank you for the fast release 👍

**Comment by costingeana** [comment]
I can also confirm that 2.74.1 is ok. Thank you.

**Comment by lukastaegert** [comment]
I created a new PR #4510 that reimplements parameter tree-shaking in a more conservative way. Could you verify that this PR works for you via `npm install rollup/rollup#parameter-defaults`?

**Comment by costingeana** [comment]
Hello and sorry for the delay,
I confirm that the PR works for me. Thank you.
