### ISSUE TITLE
Constructor default value was removed

### ISSUE THREAD

**Issue by ericwangqing** [rollup/rollup#4505]
### Rollup Version

2.74.0

### Operating System (or Browser)

Chrome

### Link To Reproduction

https://rollupjs.org/repl/?version=2.74.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEIlMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGUuanMnJTVDbmNvbnN0JTIwYiUyMCUzRCUyMG5ldyUyMEIoKSU1Q25jb25zb2xlLmxvZyhiKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJjbGFzcyUyMEElMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKGElM0QnZGVmYXVsdCcpJTIwJTdCJTVDbiU1Q3QlNUN0dGhpcy5hJTIwJTNEJTIwYSU1Q24lNUN0JTdEJTVDbiU3RCU1Q24lNUNuY2xhc3MlMjBCJTIwZXh0ZW5kcyUyMEElMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTVDdCU1Q3RzdXBlcigpJTVDbiU1Q3QlN0QlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBCJTIwJTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behaviour

The constructor of A should have default value.

### Actual Behaviour

The default value was removed.

**Comment by lukastaegert** [comment]
Thank you so much! Considering the issues, I will roll back the parameter default tree-shaking in a patch release for now and refine it for another few days. Please keep the issue open as I intend to fix it with a proper release later.

**Comment by ericwangqing** [comment]
Sounds great! looking forward the new release :)
