### ISSUE TITLE
TypeError: Cannot read property 'render' of null

### ISSUE THREAD

**Issue by salmin89** [rollup/rollup#4506]
### Rollup Version

2.74

### Operating System (or Browser)

not relevant

### Node Version (if applicable)

not relevant

### Link To Reproduction

unsure how to replicate it in repl

### Expected Behaviour

we use ng-packagr to build our Angular packages. Its dependencies just says latest rollup. Running a build with rollup@2.74 generates this error:

`TypeError: Cannot read property 'render' of null`

Downgrading rollup to @2.73 fixes this for now.

### Actual Behaviour

latest version should still work

**Comment by lukastaegert** [comment]
It would be really helpful to finally get a stack trace of this error. In any case, I will roll back the parameter default tree-shaking for now, which should hopefully fix the issue. If you could provide a reproduction of sorts for rollup@2.74.0, that would also be super helpful.

**Comment by salmin89** [comment]
this is all I can provide since this is coming from a library that's using rollup and not our own code

![image](https://user-images.githubusercontent.com/10077295/169373536-6116b3a3-a63d-4890-8c60-83fc328a1a35.png)

**Comment by lukastaegert** [comment]
Perfect, thanks a lot!

**Comment by salmin89** [comment]
> I created a new PR #4510 that reimplements parameter tree-shaking in a more conservative way. Could you verify that this PR works for you via `npm install rollup/rollup#parameter-defaults`?

This works for us. Thank you! :)
