### ISSUE TITLE
Parameter's default value is removed when it's not supposed to

### ISSUE THREAD

**Issue by jindrahm** [rollup/rollup#4516]
### Rollup Version

2.75.0+

### Operating System (or Browser)

macOS Monterey

### Node Version (if applicable)

16.14.0

### Link To Reproduction

https://replit.com/@jindrahm/ParamDefaultBug?v=1

### Expected Behaviour

The following code should remain basically untouched after bundling by rollup.

```javascript
const systemService = {restart};

function restart(options = {}) {
  if (options.countdown) {
    console.log('shows restart dialog with a countdown');
  } else {
    console.log('restarts immediately');
  }
}

systemService.restart();
```

### Actual Behaviour

But it generates this code which throws an error because rollup removed the `options` param default value so it cannot access the `countdown` property of `undefined`.

```javascript
const systemService = {restart};

function restart(options) {
    if (options.countdown) {
    console.log('shows restart dialog with a countdown');
  } else {
    console.log('restarts immediately');
  }
}

systemService.restart();
```

**Comment by ggmartins091** [comment]
Up.
I'm having the same problem here, using some methods from MUI packages where there are default parameters with empty objects, they are resolved to undefined.

Version 2.75.3 does not fix it.

**Comment by lukastaegert** [comment]
Sorry for this. Fix at #4518

**Comment by inukshuk** [comment]
I think this is not completely fixed yet. I'm trying to build a minimal test case, but meanwhile I have a module including a function with the signature: `export function f(a, b = {}, c = new Set())` which is imported into two bundles. In one of the bundles the parameters end up defined as `(a, b, c)` in the other as `(a, b, c = new Set())` -- if I use the configuration of either of the two bundles but change to bundle only the module exporting the function, both default parameters stay intact. So it looks to me like the way the functions are used have an effect on which parameter defaults survive bundling.

**Comment by lukastaegert** [comment]
> So it looks to me like the way the functions are used have an effect on which parameter defaults survive bundling.

Well, that is the whole point of default parameter tree-shaking. The question is just if it is missing in a situation where it is definitely making a difference.

**Comment by ggmartins091** [comment]
> > So it looks to me like the way the functions are used have an effect on which parameter defaults survive bundling.
> 
> Well, that is the whole point of default parameter tree-shaking. The question is just if it is missing in a situation where it is definitely making a difference.

I've just tested with version 2.75.4 and this issue is still reproducible: https://github.com/vitejs/vite/issues/8395#issuecomment-1141673344

Its is basically something like this:
`function foo() {
	const bar = (options = {}) => {
		console.log(options);
	}
	return bar;
}

foo()(); // console.logs "undefined"`

**Comment by inukshuk** [comment]
> Well, that is the whole point of default parameter tree-shaking. The question is just if it is missing in a situation where it is definitely making a difference.

Yes, sorry, I just ran into the issue before even reading up on the feature itself! In my case I could narrow it down to the use of `try/catch` blocks. For example, given a function defined as:

```js
export function uniq(array, into = [], memo = new Set()) { /* ... */ }
```

```js
import { uniq } from './util'

export function x() {
  try {
    return uniq([])

  } catch {
    return []
  }
}
```

Yields a `function uniq(array, into, memo)` without default parameters.

While a usage like:
```js
export function y() {
  return uniq([])
}
```
Includes all of them. In my own code base there must be a third case which I haven't been able to isolate yet, where only the default value of the second parameter is dropped.
