### ISSUE TITLE
`assert { type: 'json' }` results in "Error: Unexpected token"

### ISSUE THREAD

**Issue by cmcculloh** [rollup/rollup#4530]
### Rollup Version

2.75.6

### Operating System (or Browser)

macOS Monterey

### Node Version (if applicable)

16.15.1

### Link To Reproduction

https://rollupjs.org/repl/?version=2.75.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGRhdGElMjBmcm9tJTIwJTVDJTIydGVzdC1qc29uLWltcG9ydCUyRmRhdGEuanNvbiU1QyUyMiUyMGFzc2VydCUyMCU3QiUyMHR5cGUlM0ElMjAlNUMlMjJqc29uJTVDJTIyJTIwJTdEJTNCJTVDbiU1Q25jb25zb2xlLnRhYmxlKGRhdGEpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGF0YS5qc29uJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlMjAlMjAlNUMlMjJpZCU1QyUyMiUzQSUyMDElNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behaviour

When `index.js` includes `assert { type: 'json'}` on an import, and I run `yarn rollup index.js` it should not error.

This includes both non-npm module json files:
```
import data from "./data.json" assert { type: "json" };
```

And those in an npm module:
```
import data from "test-json-import/data.json" assert { type: "json" };
```

https://nodejs.org/docs/latest-v16.x/api/esm.html#json-modules

Also see this minimal reproduction repo: https://github.com/cmcculloh/rollup-import-json

### Actual Behaviour

Rollup errors on the `assert`

```
index.js → stdout...
[!] Error: Unexpected token
index.js (1:61)
1: import data from "./node_modules/test-json-import/data.json" assert { type: "json" };
```

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/157303/174094960-41a751de-771d-4458-bafe-8cd2e5b2204c.png">

**Comment by cmcculloh** [comment]
Just found this plugin which fixes this issue: https://github.com/swiing/rollup-plugin-import-assertions

No idea what your roadmap is like though, whether you want this as a plugin or if it ought to just work in core, so I'll leave this open.

**Comment by lukastaegert** [comment]
There is an older issue for the topic: #3799

The plan is definitely to support them eventually. It is just not clear how to do it at the moment, there are some scenarios that need to be cleared up:
* Will plugins have access to this information in resolveId?
* Do we actually act on this e.g. by implementing a default handler for 'json'?
* If such an assertion is on an external dependency, do we emit the assertion in the output?

**Comment by lukastaegert** [comment]
Initial support in #4646
