### ISSUE TITLE
Read existing source maps for imported modules

### ISSUE THREAD

**Issue by ygoe** [rollup/rollup#4532]
I'm using rollup to bundle JavaScript files. (There might be other usages, I don't know what rollup can do more.) In the basic scenario, I'm only importing source files into a bundle file. The generated source map will be created and point to all the imported source files.

But for a "single file" scenario (distribute a single file including all dependencies), I bundle some source files and also a differently bundled file into a new bundle file. Because the bundling options are different (with and without IIFE, including patching because rollup.js doesn't support IIFE parameters), I cannot bundle all original source files in a single step but need the two-step procedure. One of the imported modules is now an already bundled file with its own source map file.

The new single file bundle now has an incomplete source map. It can only point to the content of the first step bundle but not to the original source file.

This could be fixed by reading the existing source map file of the imported module, to generate a complete source map for the new bundle.

I tried to understand the rollup code but didn't find anything releated to importing files or reading source maps. Where should I look to get an idea how far I can patch rollup myself to get this feature as soon as possible?

I'm not using or even familiar with any JavaScript API of tools like these. I can only call their .cmd files as stand-alone tools from other processes. So anything in an options array won't work for me, it has to be accessible through command-line arguments. But actually, I don't expect any customisation here. If an imported file has a *.map file with it, just consider it, instead of ignoring it like now.

**Comment by lukastaegert** [comment]
https://www.npmjs.com/package/rollup-plugin-sourcemaps

**Comment by lukastaegert** [comment]
Usually, this is not what people want by default as source map handling is expensive.

**Comment by ygoe** [comment]
I've seen this on my search but couldn't make any sense of it. How should I use it from the command line?

My priorities are:

1. Function
2. Performance

In that order. If it needs to be expensive to work, then so be it. Better slow than not at all.

**Comment by lukastaegert** [comment]
Just add the plugin as described in its documentation. If your source files reference source maps, either inline or via a comment that references a file next to it, they should be used.

**Comment by ygoe** [comment]
> Just add the plugin as described in its documentation.

The only discoverable documentation is the short readme file. It shows me code that looks like JavaScript code. Where should I put that? This is what I'm currently doing:

    C:\Users\...\rollup ui-singlefile.js -o build\ui-singlefile.bundle.js -m

What do I need to change in this command line to use the plugin?

**Comment by ygoe** [comment]
Turned out that anonymous code blob in the readme is a config file for rollup. Never seen or used them. And they don't fit in my workflow either. This is how I managed to get it working without such files:

```
npm install -g rollup
npm install -g rollup-plugin-sourcemaps
rollup ui-singlefile.js -o build\ui-singlefile.bundle.js -m -p rollup-plugin-sourcemaps
```

**Comment by justinfagnani** [comment]
By the way, [rollup-plugin-sourcemaps](https://www.npmjs.com/package/rollup-plugin-sourcemaps) seems very unmaintained now and causes npm resolution problems for anyone on Rollup v3 or v4.

It'd be nice if there were an official plugin, or if this feature were built in.

**Comment by filipsobol** [comment]
Maybe not an official plugin that some of you hoped for, but I just released `unplugin-sourcemaps` that works with Rollup and other bundlers — https://www.npmjs.com/package/unplugin-sourcemaps. Its only dependency is `unplugin` which is a library for creating universal plugins for bundlers.

Also, if you need bundle visualization that considers existing source maps, then check out `sonda` - https://www.npmjs.com/package/sonda.

**Comment by cedx** [comment]
> Usually, this is not what people want by default [...].

It's a strange opinion for me. When I enable the `sourcemap` option, I expect exactly the opposite.
That is, if the `input` file has already a sourcemap associated with it, I expect it to be read automatically (and without going through an additional plug-in).
This is what `esbuild` does, for example.

> It'd be nice if there were an official plugin, or if this feature were built in.

Yes, definitely.

**Comment by olsonpm** [comment]
my use-case for this feature is a browser ide "playground" to try out my library.  I was hoping to pre-bundle my library with inline sourcemaps - then have @rollup/browser bundle that with the user code - for that final bundle to include original source maps.

I'll look into another approach

**Comment by lukastaegert** [comment]
If you are using `@rollup/browser`, you need to write a plugin with a `load` hook anyway to handle loading your files. In the load hook, you can directly [return a `map`](https://rollupjs.org/plugin-development/#load) with your code to provide the sourcemap, would this cover your use-case?

**Comment by olsonpm** [comment]
Yes i am using @rollup/browser.  I got it working by writing my source files out to json, writing a plugin to resolve ids appropriately, and bundling the user code with that.  Might not be the best way but it worked fine for my case.

Thanks for your all your work over the years.  Rollup has come a long way
