### ISSUE TITLE
"Plugins development" section is broken in docs

### ISSUE THREAD

**Issue by Septh** [rollup/rollup#4545]
### Documentation is

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [X] Not sure?

### Please Explain in Detail...

Previously, when you clicked on some hook name in the charts, the page would scroll to that hook's doc and that was great.

Now, the chart gets replaced by an inline copy of the whole docs site (the picture below shows the results of me clicking on the **watchChange** hook, for example). This happens with both Firefox and Chrome.

![image](https://user-images.githubusercontent.com/11949623/177004250-1aa11392-70c9-4c6c-bcc4-d6eea0b3ea02.png)

### Your Proposal for Changes

Don't know.

**Comment by lukastaegert** [comment]
Thanks for spotting, seems like a bug in mermaid, will downgrade

**Comment by Septh** [comment]
Thank you. I think I'll open an issue on mermaid as well when/if I have time (and inspiration).
