### ISSUE TITLE
Provide new hook for plugin state reset between builds

### ISSUE THREAD

**Issue by aleclarson** [rollup/rollup#4550]
### Feature Use Case

Plugins often use `buildStart` to initialize and reset internal state, so the plugin can work with `rollup --watch` command. The problem is that this forces Vite to call `buildStart` hook in development, so Rollup plugins don't break due to undefined internal state. Calling `buildStart` in development is confusing and makes plugins harder to understand, since newbies understandably assume that `buildStart` only runs for actual builds (ie: `vite build` command). For these reasons, I see using the `buildStart` hook to initialize internal state as an anti-pattern that could be avoided by adding a new hook.

### Feature Proposal

This wrapper shows how the new hook would function if implemented with current hooks:
```ts
function provideNewHook(plugin) {
  plugin.newHook()

  let needsReset = false
  return {
    buildStart() {
	  if (needsReset) {
	    needsReset = false
	    plugin.newHook()
	  }
    },
    watchChange() {
	  // Track if the new hook should be called on next `buildStart` hook.
	  needsReset = true
    }
  }
}
```
This would allow Vite to call the new hook in development, instead of calling `buildStart` hooks.

**Comment by lukastaegert** [comment]
Ah no, you actually want to replace buildStart entirely. That feels it makes stuff really weird for writing isomorphic plugins as you would basically often just duplicate functionality between the hooks. In the end, it sounds like you just do not like the name of the hook?

**Comment by aleclarson** [comment]
No, the `buildStart` hook would remain.

I'm proposing that Rollup adds a new `setup` hook that Rollup calls exactly like `buildStart`, and Vite would stop calling `buildStart` in its development server mode (calling `setup` instead).

I talked to @patak-dev about the idea, and he said the ecosystem churn is too much to bear. I think I've settled on the same conclusion. Vite will just have to live with `buildStart` being a misnomer.

**Comment by lukastaegert** [comment]
> the ecosystem churn is too much to bear

Unfortunately also my feeling. If it helps at least slightly, you could extend the `buildStart` signature to something like

```
(options: InputOptions, flags: { devMode: boolean }) => void
```

so that (Vite-)plugins would be able to detect `devMode` for adjusted caching behaviour etc. but also because then your own plugin documentation would make it more clear that this hook runs during development as well.
