### ISSUE TITLE
how to build multi pages into different directory and config different base path with rollupOptions?

### ISSUE THREAD

**Issue by hackftz** [rollup/rollup#4553]
hello, my friend!

In my project(build by vite), i want to dynamically config the `output dir` and `base path` from input config.

I just want to know that if rollup is currently support this function.

Or in another way, I have to create two `vite.config.ts` to solve this problem, but I thought it is complicated.

Hope to get answer here, I am very appreciate it.

**Comment by lukastaegert** [comment]
I do not think you can change Vite config from rollup's config, but please ask the Vite people, not us. Maybe you can make `output` an array, but again this is a question for Vite, not us.
