### ISSUE TITLE
Multiple outputs are concatenated into a single file 

### ISSUE THREAD

**Issue by jonkoops** [rollup/rollup#4554]
### Rollup Version

2.75.7

### Operating System (or Browser)

Any

### Node Version (if applicable)

Any

### Link To Reproduction

https://github.com/Leaflet/Leaflet/compare/export-esm

### Expected Behaviour

The resulting output is split over two files.

### Actual Behaviour

The resulting output ends up in a single file.

### Details

We're trying to implement ESM support for Leaflet. However our code changes to export the globals and re-export the package seem to somehow break Rollup internally and our outputs all end up in a single file instead of multiple files for each module format.

**Comment by lukastaegert** [comment]
Avoid using the same file name for different outputs

**Comment by jonkoops** [comment]
Ahhh, yeah totally missed that due to the fact that it uses the `main` field here for the naming. Thanks @lukastaegert!
