### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by Manonicu** [rollup/rollup#4563]
Hey there! If you need help or tech support then this is not the place to ask. Please head to the [Rollup Discord](https://is.gd/rollup_chat) instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

If you arrived here because you think Rollup's documentation is unclear, insufficient or wrong, please consider creating an issue for the documentation instead.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/12791216/178107694-ff745d90-754e-4dcf-8c99-b9bbd47a8c47.png">

`docs:dev: Module not found: Can't resolve '../../assets/images/search-stroke.svg'`

**Comment by lukastaegert** [comment]
If you have issues using assets ins scss (or whatever this is), you need some plugin, Rollup does not have any special handling for style files. Googling turned up https://www.npmjs.com/package/rollup-plugin-scss and https://www.npmjs.com/package/rollup-plugin-sass, or you want to use something like https://vitejs.dev which will probably do this correctly out of the box.
