### ISSUE TITLE
Externalized imports within chunk are included in chunk's consumer code

### ISSUE THREAD

**Issue by bluwy** [rollup/rollup#4564]
### Expected Behavior / Situation

Repro: https://github.com/bluwy/rollup-chunk-import-issue

When a chunk imports modules which are externalized and marked side-effect free via `treeshake.moduleSideEffects` `no-external` or `false`, consumer of the chunk should not have the import included.

In the repro above, I expect `dist/one.js` to be:

```js
import { f as foo } from './shared-27380fce.js';

foo();
```

### Actual Behavior / Situation

It is currently.

```js
import { f as foo } from './shared-27380fce.js';
import 'fs';

foo();
```

### Modification Proposal

I think `import 'fs'` could be removed. I tried looking for an explanation but failed to find one, so I'd be keen to know if this is intentional, and the reason behind it as this had generated unused code for [Vite](https://cdn.jsdelivr.net/npm/vite@3.0.0-beta.9/dist/node/cli.js) (for example), and had caused [warnings on esbuild side](https://github.com/evanw/esbuild/issues/1785) when re-bundled by it, e.g. https://github.com/sveltejs/kit/issues/4644

**Comment by lukastaegert** [comment]
https://rollupjs.org/guide/en/#outputhoisttransitiveimports

**Comment by lukastaegert** [comment]
> I tried looking for an explanation but failed to find one

Considering I even wrote an FAQ section on the topic, maybe it should be linked in more places?

**Comment by bluwy** [comment]
Thanks! That's exactly what I'm looking for. Sorry for the issue noise.



> Considering I even wrote an FAQ section on the topic, maybe it should be linked in more places?

I think it is good for now. I was having trouble searching for it on Google, and maybe my search terms are incorrect. I should also check the FAQ first. But this will help me point others to it if I ever stumble on it again.
