### ISSUE TITLE
Sourcemaps - debugging in chrome - lines do not correspond with source

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#457]
I'm using the `iife` format for rollup, and my breakpoints simply don't correspond with the source.  Specifically today, I'm trying to debug in a constructor.

https://github.com/FezVrasta/bootstrap-material-design/tree/v4-dev/grunt

I'm not quite sure where to start in providing additional information.  What do I need to collect to be helpful?

**Comment by eventualbuddha** [comment]
> What do I need to collect to be helpful?

@rosskevin Either a smaller example that illustrates the problem or thorough instructions on using the linked repo to reproduce the issue would be great!

**Comment by rosskevin** [comment]
I'm going to close this and reopen it or start a new one at the next occurrence.  I have a documentation site published for an open project and I should be able to find a good case.
