### ISSUE TITLE
Riot.js plugin

### ISSUE THREAD

**Issue by cognitom** [rollup/rollup#459]
The first version of the plugin for Riot.js. Can I add it to the [wiki](https://github.com/rollup/rollup/wiki/Plugins)?

- https://www.npmjs.com/package/rollup-plugin-riot
- https://github.com/riot/rollup-plugin-riot

I've read the [guideline](https://github.com/rollup/rollup/wiki/Rollup-Plugin-Guidelines) carefully, but I'm a bit new to Rollup. Any feedbacks or suggestions are welcome :-) Thanks.

**Comment by eventualbuddha** [comment]
@cognitom Thanks for the contribution! Feel free to add it to the wiki. The feedback I gave does not need to be done before doing so. Cheers!

**Comment by eventualbuddha** [comment]
(I'll let @Rich-Harris or @Victorystick close this once we've had another pair of eyes on it.)

**Comment by cognitom** [comment]
@eventualbuddha thank you for quick feedbacks. I've updated the wiki :-)

**Comment by eventualbuddha** [comment]
Closing since it's been a while and haven't heard anything. Thanks @cognitom!
