### ISSUE TITLE
The emitted file "assets/******.css" overwrites a previously emitted file of the same name

### ISSUE THREAD

**Issue by waversky** [rollup/rollup#4604]
### Rollup Version

3.0.5

### Operating System (or Browser)

windows 10

### Node Version (if applicable)

16.15.1

### Link To Reproduction

no

### Expected Behaviour

![image](https://user-images.githubusercontent.com/18565394/184313996-476521df-842a-4a14-8603-42cb836e21ac.png)

### Actual Behaviour

![image](https://user-images.githubusercontent.com/18565394/184313092-9f1dff38-f9a9-4fd0-b820-26a4249dacef.png)
vite update to 3.x an exception occurred
update to 2.9.11 so good

**Comment by lukastaegert** [comment]
I hope you created an issue for Vite because we are not maintaining Vite and it seems impossible to fix from Rollup side. If they use the same name, assets will overwrite each other.

**Comment by waversky** [comment]
OK , Thank you for your reply !

**Comment by zjjjjjjjjjjd** [comment]
> OK , Thank you for your reply !

哥们，这咋搞，我也想把一部分css合并
