### ISSUE TITLE
Add support to keep '.js' extension for amd

### ISSUE THREAD

**Issue by wh1tevs** [rollup/rollup#4606]
### Feature Use Case

I am developing embedded applications for a CMS which uses the amd module system. And that CMS don't allow to request any files without extensions (for security purposes). So, when application bundled in one module it's ok, but when i have separated module which required other bundled module CMS throw 404 error.

### Feature Proposal

i think it should be something like this:

```js
expoer default {
  input: './index.js',
  output: {
    format: 'amd',
    file: 'script.js',
    amd: {
      keepExtension: true, // false by default
    },
};
```

and produce output like:
```js
define(['./foo.js'], function (foo) {
/* bundle */
})

**Comment by lukastaegert** [comment]
PR welcome!

**Comment by dasa** [comment]
I just wanted to mention that this would violate the [spec](https://github.com/amdjs/amdjs-api/blob/master/AMD.md) for module ids: 

> Module identifiers may not have file-name extensions like ".js".

Normally the AMD loader will add ".js" to the URL when it injects the scripts.

**Comment by lukastaegert** [comment]
That depends on the implementation. RequireJS, which is arguably one of the most important AMD implementations, does support `.js` extension but uses different resolution logic when it encounters them: https://requirejs.org/docs/api.html#jsfiles
