### ISSUE TITLE
Entry file - fail to "bundle" a variable which it's var defined above

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#461]
This code will not be copied to the bundled output:

    var foo;
    foo = 1;

[Demo link](http://rollupjs.org) - copy the above code to the entry point and run

**Comment by vanruesc** [comment]
What you're seeing there kicking in is the tree-shaking mechanism that makes Rollup so sexy.

Your particular code snippet will end up inside one big closure in the final bundle. In there, it wouldn't have any side-effects and will thus be dropped to keep the bundle minimal.

Unless you use ```foo``` in some meaningful way like assigning it to the global window object (f*** the police) it will be removed.

I don't know how Rollup actually finds out what code has side-effects and what doesn't. I think that is, in fact, a problem area, but I haven't run into any problems with that myself.

**Comment by eventualbuddha** [comment]
@vanrusec is right. If there's code that you're using that isn't being included then that's a bug.
