### ISSUE TITLE
Rollup throws TRANSPILED_ESM_CONFIG error when importing ESM module with type:module in package.json

### ISSUE THREAD

**Issue by flying-sheep** [rollup/rollup#4617]
### Rollup Version

2.78.1

### Operating System (or Browser)

Linux/Firefox

### Link To Reproduction

https://replit.com/@flying-sheep/rollup-repro-esm-from-ts

### Expected Behaviour

rollup.config.ts gets compiled to ESM and imports `<projdir>/node_modules/@mdx-js/rollup/index.js` as ESM

### Actual Behaviour

rollup.config.ts seems to get compiled to CJS despite `target: ES2020` in the tsconfig.json.

**Comment by lukastaegert** [comment]
I very much recommend reading the documentation for this one: https://rollupjs.org/guide/en/#using-untranspiled-config-files

Rollup CLI will also print this link to the documentation next to the error.

**Comment by lukastaegert** [comment]
As it is TypeScript, the only way to support this is via transpilation to CommonJS, unfortunately.

**Comment by flying-sheep** [comment]
But wouldn't i still be unable to import that ESM module from commonjs? How can I configure rollup to compile a typescript config to ESM and use that?

**Comment by lukastaegert** [comment]
You just cannot at the moment. Currently, the best possibility for us would be to build upon this API https://nodejs.org/api/esm.html#loaders but not only is it experimental, but the need to configure it upfront via Node CLI flags makes it very hard to use.

**Comment by flying-sheep** [comment]
I think I understand the problems here now. On the other hand, the number of ESM only modules will only increase, and I don’t think forcing people to use CJS instead of typescript is a great thing.

It seems impossible to do this at the moment, because rollup always compiles to CJS: https://github.com/rollup/rollup/blob/eb1fab7883846e16af1d8c650715e725a20a2665/cli/run/loadConfigFile.ts#L87

Can you provide a flag to allow a workaround?

**Comment by lukastaegert** [comment]
Actually you made me think, and if we accept that we do it a little more slowly, we could just make it work by writing the transpiled file to disk and then dynamically importing it. If this works out, I will change the mechanism for Rollup 3 because you are right, tying ourselves to CommonJS this way is a problem. I will let you know once I have something for you to play around with.

**Comment by flying-sheep** [comment]
That’s great, thank you!

**Comment by lukastaegert** [comment]
Fix at #4621
