### ISSUE TITLE
Rollupjs without bundle

### ISSUE THREAD

**Issue by Alphapage** [rollup/rollup#462]
Hello,

Is it possible to use rollupjs to optimize code and keep files structure (ie without bundle in unique file) ?
If no, do you plan to support this ?

Thanks in advance for your answers.

**Comment by TrySound** [comment]
@Alphapage Rollup is **bundler**. If you want to precess `.js` use gulp or bash pipeline with clis.

**Comment by Alphapage** [comment]
How do you do tree shaking with other tools?

**Comment by Victorystick** [comment]
@Alphapage It's only when you create a bundle that you can safely do tree-shaking.
