### ISSUE TITLE
Consider using faster hash algorithm

### ISSUE THREAD

**Issue by aleclarson** [rollup/rollup#4626]
I wonder if Rollup really needs SHA256's cryptographic security for its content hash production, or would it be better off using something faster like Murmurhash3 (of which there is a JS-only implementation here: https://github.com/unjs/ohash/blob/58a0d67ce9f3ed4b33526ea4c254a24e13fe290e/src/crypto/murmur.ts)?

**Comment by lukastaegert** [comment]
Well, it is important to not have hash collisions but other than that, of course we can try different algorithms. Though it is not large numbers we are currently talking about, e.g. hashing all of Rollup for me takes about 7ms. One nice thing about using SHA is that we use Node's builtin `crypto`, which again to my understanding uses native code, at the very least it was faster than all JS implementations I tested at the time. But I did not test other algorithms.

**Comment by marcusdarmstrong** [comment]
I can offer a pitch for a project I've previously contributed to: https://github.com/jungomi/xxhash-wasm (also in use in parcel: https://github.com/parcel-bundler/parcel/blob/v2/packages/utils/hash/package.json#L36). The reduced computational complexity of non-cryptographic hash algorithms easily make up for the difference in overhead between wasm and native code in my own benchmarking.

**Comment by lukastaegert** [comment]
That looks amazing except for the Node 15 engine requirement. Maybe something for Rollup 4 then.

**Comment by lukastaegert** [comment]
Or we directly go for the old, version if it is still noticeably faster than crypto.

**Comment by TrickyPi** [comment]
Closed as using xxhash in V4.
