### ISSUE TITLE
show generated file size on the terminal

### ISSUE THREAD

**Issue by ritz078** [rollup/rollup#463]
Thought this will we really useful while development while trying to optimize the library. Webpack already does this.

**Comment by TrySound** [comment]
@ritz078 You can make a plugin for this.

**Comment by ritz078** [comment]
That will be nice. I will do that .

**Comment by TrySound** [comment]
:+1:

**Comment by eventualbuddha** [comment]
@ritz078 If you run into problems implementing this, feel free to comment here.

**Comment by ritz078** [comment]
@eventualbuddha Is there some problem with `transformBundle` ?
@TrySound Even rollup-plugin-uglify which uses `transformBundle` isn't working for me.

Its not getting executed.

Instead `transform` is working fine.

**Comment by TrySound** [comment]
@ritz078 Are your sure you use the last rollup version?

**Comment by ritz078** [comment]
yes its v0.25.1

**Comment by TrySound** [comment]
@ritz078 And cli and local?

**Comment by ritz078** [comment]
cli is v0.21.0, local is v0.25.1

**Comment by TrySound** [comment]
@ritz078 Cli didn't support transformBundle. Until we don't use semver (version start with 0.*), global and local version should be the same in minor to prevent imcompatibilities.

**Comment by ritz078** [comment]
fixed this issue by updating cli. Is `useStrict` and `sourceMapFile` deprecated ?

**Comment by TrySound** [comment]
Which warn do you get?

**Comment by ritz078** [comment]
`Unexpected key 'sourceMapFile' found, expected one of: banner, dest, entry, external, footer, format, globals, indent, intro, moduleId, moduleName, onwarn, outro, plugins, sourceMap
`

**Comment by TrySound** [comment]
@Victorystick Did we forget to add them?

**Comment by Victorystick** [comment]
I think `sourceMap` works as `sourceMapFile` used to do. Not sure about `useStrict`.

**Comment by TrySound** [comment]
These options are used in source code

**Comment by TrySound** [comment]
And they are defined in docs.

**Comment by ritz078** [comment]
<img width="287" alt="screen shot 2016-01-27 at 5 25 32 pm" src="https://cloud.githubusercontent.com/assets/5389035/12612772/2d56062c-c51b-11e5-9974-80d489419b21.png">

I have almost completed the plugin. Its present [here](https://github.com/ritz078/rollup-plugin-filesize) But have to add tests . 

A question : What do i return when i am not making any changes to the code. I have tried 

```js
return {
  code : code,
  map : {mappings:''}
}
```

but this gives an error that sourcemap can't be generated. Currently i haven't returned anything and its working fine but i fear i may break somewhere.

**Comment by TrySound** [comment]
Add please `format` (for number) and `render` option (for output).

**Comment by ritz078** [comment]
1. Do you mean i should also show the `format` of the bundled file in the console ? What do you mean by `render` ?
2. Maybe you missed the question i asked in my previous comment.
3. This thread is just becoming longer and the issues may get lost. Should i create new ones to keep track of them like `sourceMapFile` and `useStrict` or the question I asked ?

**Comment by TrySound** [comment]
I mean `format` gets count of bytes and returns '100 B', '2 KB' or something like that. `render` gets formatted size and returns message like your rect.

**Comment by TrySound** [comment]
And you should define defaults with your current format and render

**Comment by ritz078** [comment]
oh that will be done in addition to optional theme for dark and light terminals.

**Comment by ritz078** [comment]
Done.
