### ISSUE TITLE
Improve error when manualChunks includes external modules

### ISSUE THREAD

**Issue by sapphi-red** [rollup/rollup#4633]
### Expected Behavior / Situation

When `manualChunks` includes modules externalized by a plugin.

#### Reproduction
```js
import nodeResolve from '@rollup/plugin-node-resolve';

export default {
  input: 'src/main.js',
  external: ['react'],
  output: {
    dir: 'dist',
    format: 'esm',
    exports: 'auto',
    manualChunks: {
      react: ['react'],
    },
  },
  plugins: [
    nodeResolve(),
    {
      name: 'externalizer',
      resolveId(source, importer, options) {
        if (source === 'react') {
          return { external: true };
        }
      },
    },
  ],
};
```
[stackblitz](https://stackblitz.com/edit/rollup-template-whqurg?file=rollup.config.js)

In a real world situation, this happens when bundling for SSR with Vite (Vite sets `external` in a plugin).

### Actual Behavior / Situation

Currently rollup outputs the following error:

> [!] Error: Entry module cannot be external (react).

I know it's wrong to include externalized modules to `manualChunks`. But I feel this is a bit difficult to understand.
(My understanding is: `manualChunks` makes each specified module as an entry module, so `react` is an entry module.)

### Modification Proposal

Output an error like:

> [!] Error: Manual chunks includes an externalized module (react).

or

> [!] Error: Externalized module (react) should not be included in `manualChunks`.

**Comment by sfase3** [comment]
Hi there, did you fix it?
