### ISSUE TITLE
Is there a way to keep variable function

### ISSUE THREAD

**Issue by easyfrog** [rollup/rollup#4638]
An object like this:

```js
{
      func: function() {}
}
```

after rollup it will change to :

```js
{
      func() {}
}
```

So is there a way to keep it `variable: function() {}` type?

**Comment by lukastaegert** [comment]
Rollup is not doing this: https://rollupjs.org/repl/?version=2.79.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKCU3QmZ1bmMlM0ElMjBmdW5jdGlvbigpJTIwJTdCJTdEJTdEKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

Probably a plugin of yours
