### ISSUE TITLE
Is it okay to create a rollup bundle that depends on the build output of another rollup bundle

### ISSUE THREAD

**Issue by haseebanwar** [rollup/rollup#4650]
### Link to reproduction
[https://github.com/haseebanwar/rollup-watcher](https://github.com/haseebanwar/rollup-watcher)

See the rollup config at the root `index.js` file. You will see configuration for two bundles
- One takes input from `src/index.js` and outputs the bundle at `dist`
- Second takes input from `playground/index.js` and outputs the bundle at `playground/build`

If you see the `playground/index.js` file, it imports a variable from the `dist` of the first bundle.

```js
// playground/index.js

// this tells rollup to look for the "module" key in package.json
// which then points to `dist/index.js` (output of the first bundle)
import { text } from '../';
```

Since the config is defined in a way that bundle one is created before the second bundle, and rollup works.

So, is there a chance rollup tries to create the second bundle before the first one is finished? Or rollup kicks them off in parallel (that may cause the build to fail)?

**Comment by lukastaegert** [comment]
No, configs in arrays are handled sequentially exactly to support such use cases.

**Comment by haseebanwar** [comment]
Thanks, @lukastaegert appreciate your quick response.
