### ISSUE TITLE
Function parameter only used as the init of a destructuring declaration in a for loop head incorrectly marked as unused

### ISSUE THREAD

**Issue by nicolo-ribaudo** [rollup/rollup#4654]
### Rollup Version

2.79.1

### Operating System (or Browser)

Node.js on Linux, Repl on Firefox

### Link To Reproduction

https://rollupjs.org/repl/?version=2.79.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwY2hlY2socCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwaXNEZWNsYXJlZEluTG9vcChwKSUzQiU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwaXNEZWNsYXJlZEluTG9vcChwYXRoKSUyMCU3QiU1Q24lMjAlMjBmb3IlMjAobGV0JTIwJTdCJTIwcGFyZW50UGF0aCUyMCU3RCUyMCUzRCUyMHBhdGglM0IlM0IpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMHBhcmVudFBhdGglM0IlNUNuJTIwJTIwJTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q%3D

(found in https://github.com/babel/babel/pull/15027)

### Expected Behaviour

It shouldn't transform `isDeclaredInLoop(p)` to `isDeclaredInLoop()`.

### Actual Behaviour

It incorrectly removes an argument from the `isDeclaredInLoop` function call.

**Comment by lukastaegert** [comment]
Fix at #4663
