### ISSUE TITLE
Failure to get results with gulp, though command line works

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#466]
This repo is effectively a test case at this point for getting rollup to work with gulp:
https://github.com/alienfast/gulp-pipeline

```javascript
import gulp from 'gulp'
import extend from 'extend'
import Rollup from 'rollup'

//rollup src/index.js --output dist/gulp-pipeline.es2015-cmdline.js --format es6

let rollupBaseSettings = {
  entry: 'src/index.js',
  //plugins: [],
  sourceMap: true,
  format: 'es6',
}

gulp.task('rollup:es2015', () => {
  let settings = extend(true, rollupBaseSettings, {dest: 'dist/gulp-pipeline.es2015.js'})
  Rollup.rollup(settings)
})

gulp.task('rollup:es2015-promise', () => {
  let settings = extend(true, rollupBaseSettings, {dest: 'dist/gulp-pipeline.es2015-promise.js'})
  return Rollup.rollup(settings).then((bundle) => {
    return bundle.write(settings)
  })
})
```

1.  Command line works: `rollup src/index.js --output dist/gulp-pipeline.es2015-cmdline.js --format es6` as evidenced in this [dist file](https://github.com/alienfast/gulp-pipeline/blob/master/dist/gulp-pipeline.es2015-cmdline.js)
2.  Gulp with a promise rolls up imports, and no other code as shown in this [dist file](https://github.com/alienfast/gulp-pipeline/blob/master/dist/gulp-pipeline.es2015-promise.js)
3.  Gulp with direct execution of rollup module method has no output whatsoever.  This is quite confusing because before a dependency change, it was working fine whereas the promise method was yielding the same as above.

I deleted node_modules and reinstalled, no change.

I would actually expect all three to work, what am I missing here?  This repo can be pulled quickly and tested: 
https://github.com/alienfast/gulp-pipeline.git

**Comment by TrySound** [comment]
`rollup:es2015` task won't because you didn't execute bundle generation. It can be executed by calling `bundle.generate` or `bundle.write`. rollup function itself doesn't accept `dest`, `sourceMap` and `format` options.
Read documentation more attentively please.
https://github.com/rollup/rollup/wiki/JavaScript-API#rolluprollup-options-

Also you should always specify gulp when the task is end by calling callback, return stream or promise. 

Here's full example
```js
import gulp from 'gulp'
import { rollup } from 'rollup'

gulp.task('rollup:es2015', () => {
  return rollup({
    entry: 'src/index.js',
  }).then(bundle => {
    return bundle.write({
      dest:  'dist/gulp-pipeline.es2015.js',
      sourceMap: true,
      format: 'es6',
    })
  })
})
```

Your last example should work and I'm don't understand what it the problem, Use my example please and make a report if something won't work.

**Comment by rosskevin** [comment]
@TrySound the last example `rollup:es2015-promise` doesn't work, whether I split the settings into separate hashes or not. I did read the docs, the only reason `rollup:es2015` exists was just a last ditch attempt to make it work.

Please consider this issue filed as it doesn't work.  The repo is sitting as a test case.

**Comment by TrySound** [comment]
@rosskevin I don't understand what doesn't work. Show output code or error log. Show anything.

**Comment by TrySound** [comment]
Oops, sorry. Forget about repo

**Comment by rosskevin** [comment]
@TrySound  the output files are linked above in the numbered attempts.  e.g. the promise method is https://github.com/alienfast/gulp-pipeline/blob/master/dist/gulp-pipeline.es2015-promise.js

**Comment by rosskevin** [comment]
Note: that the .babelrc in the root is diff than the .babelrc in the src so that it plays nicely with the es6 gulpfile.  I don't think this is a problem but could be easily overlooked and worth review.

**Comment by rosskevin** [comment]
hmmm ... I see myself using `Rollup.rollup`, and your sample using just `rollup`...I'll look at that

**Comment by TrySound** [comment]
@rosskevin es2015 feature
`import { rollup } from 'rollup'`

**Comment by rosskevin** [comment]
I changed it to a named import with no affect:

```javascript
import { rollup } from 'rollup'

// TODO: may need to integrate babelrc: false instead - https://github.com/rollup/rollup-plugin-babel/issues/35#issuecomment-174253752

//rollup src/index.js --output dist/gulp-pipeline.es2015-cmdline.js --format es6

let rollupBaseSettings = {
  entry: 'src/index.js',
  //plugins: [],
  sourceMap: true,
  format: 'es6',
}

gulp.task('rollup:es2015-promise', () => {
  let settings = extend(true, rollupBaseSettings, {dest: 'dist/gulp-pipeline.es2015-promise.js'})
  return rollup(settings).then((bundle) => {
    return bundle.write(settings)
  })
})
```

**Comment by TrySound** [comment]
I got the same result with your command.
The problem is that you do not call imported stuff. If it is not used it won't be in dest.

**Comment by TrySound** [comment]
This works fine
```js
import EsLint from './eslint'
import Browserify from './browserify'
import Scss from './scss'

Scss()
Browserify()
EsLint()

```

**Comment by TrySound** [comment]
@rosskevin Read more here
http://www.2ality.com/2015/12/webpack-tree-shaking.html

**Comment by rosskevin** [comment]
I was thinking tree shaking originally, but dismissed it because the command line did _not_ yield the same result.

Why would cmdline not tree-shake?

**Comment by TrySound** [comment]
@rosskevin Maybe you have older rollup installed globally?

**Comment by rosskevin** [comment]
Nothing global (unless I have the cmd wrong)

```
$ npm ls rollup
/Users/kross/Downloads
└── (empty)
```

**Comment by rosskevin** [comment]
yep

**Comment by rosskevin** [comment]
```
$ which rollup
/usr/local/bin/rollup

$ rollup -v
rollup version 0.22.2
```

**Comment by TrySound** [comment]
@rosskevin We don't use semver yet, so different "middle" version can be not compatible.

**Comment by rosskevin** [comment]
So, any way to disable tree shaking for a general use ES2015 lib rollup?  I'll remove the global.

**Comment by TrySound** [comment]
@rosskevin Why? Do you want to edit dest file?

**Comment by TrySound** [comment]
Nothing will be executed in your original source.

**Comment by rosskevin** [comment]
No, we'll have a bunch of these classes, just looking for a flag to be sure they are all included.  Since this is a general lib, we aren't executing anything.

**Comment by rosskevin** [comment]
I'm expecting jsnext:main to point to the ES2015 rollup file, unless that's bad form and it should point at the src/index.js?

**Comment by TrySound** [comment]
Then you should also export you tasks like this
```js
export { default as EsLint } from './eslint'
export { default as Browserify } from './browserify'
export { default as Scss } from './scss'
```

**Comment by rosskevin** [comment]
Perhaps my class file shouldn't have that structure, and should `export default class` instead of having the closure around it?

**Comment by TrySound** [comment]
You can use everything. It's your project. class or closure choice is not rollup issue.

**Comment by TrySound** [comment]
rollup is about only modules.

**Comment by rosskevin** [comment]
Awesome, thanks for the help.  Do you have a style preference on closure vs the straight export?

**Comment by TrySound** [comment]
You can write to me in gitter.
