### ISSUE TITLE
provide a config parse package for users

### ISSUE THREAD

**Issue by PengBoUESTC** [rollup/rollup#4660]
### Feature Use Case

In some build tools based on rollup , like `vite`, users can parse the config file themselves, and make it easier to expand

### Feature Proposal

extract the base function of config file parse, like `loadAndParseConfigFile`, as  a independent package.

**Comment by lukastaegert** [comment]
I do not see the big advantage over using the helper that is exposed by rollup core. Exposing it via Rollup core allows for efficient code re-use within Rollup that would not be possible with a separate package.

**Comment by PengBoUESTC** [comment]
> I do not see the big advantage over using the helper that is exposed by rollup core. Exposing it via Rollup core allows for efficient code re-use within Rollup that would not be possible with a separate package. See also https://rollupjs.org/guide/en/#programmatically-loading-a-config-file

OK, but I notice that there is no `.d.ts` file for` loadConfigFile` module

**Comment by lukastaegert** [comment]
> OK, but I notice that there is no .d.ts file for loadConfigFile module

Fair enough, that could be added.
