### ISSUE TITLE
[v3.0] bundle.map can no longer be updated inside generateBundle()

### ISSUE THREAD

**Issue by Shin-Ogata** [rollup/rollup#4665]
### Rollup Version

v3.0.0

### Operating System (or Browser)

Windows 10 (Chrome)

### Link To Reproduction

https://github.com/Shin-Ogata/fieldwork/blob/master/packages/tool/tasks/rollup-plugin/source-map-root.js

### Expected Behaviour

I'm using a tiny plugin for updating source-map as below.
This is to adjust the `sources` and `sourceRoot` in the `source-map` for easier debugging in the Inspector.

```js
'use strict';

const { relative } = require('path');

function setSourceMapRoot({ relativePath, sourceRoot } = {}) {
    const [domain] = sourceRoot ? sourceRoot.split(':') : [''];
    const regexNS = new RegExp(`^([\\s\\S]+)(/@${domain}/)([\\s\\S]+)$`);
    const replacePath = src => relative(relativePath, src)
        .replace(/\\/g, '/')
        .replace(/^\w+:\/(?!\/)/, '$&/')
        .replace(regexNS, '$3')
        .replace(/^\.\.\/node_modules\//, '')
    ;
    return Object.freeze({
        name: 'source-map-root',
        generateBundle(outputOptions, bundle, isWrite) {
            for (const { map } of Object.values(bundle)) {
                if (!map) {
                    continue;
                }
                if (relativePath && Array.isArray(map.sources)) {
                    // trim relative path. ex) `../../src/config.ts` -> `config.ts`
                    map.sources = map.sources.map(replacePath);
                }
                if (sourceRoot) {
                    // add sourceRoot property. ex) `domain:///module-name/`
                    map.sourceRoot = sourceRoot;
                }
            }
        },
    });
}

module.exports = setSourceMapRoot;
```

After the build process, the changes are reflected in the source maps.

### Actual Behaviour

It worked fine up to v2.79.1, but from v3.0.0 it is no longer reflected in the generated source map.
And no error is displayed at this time.

I'm aware this behavior is a bug, but please let me know how should I do to modify the bundled source-map if I'm wrong.
Thank you for your great jobs every time.

**Comment by lukastaegert** [comment]
Yes, that is one of the breaking changes. The sourcemaps are now emitted as actual files before generateBundle, so your plugin could operate on those in the bundle object (by removing them and re-emitting them as assets). Admittedly, it could be slightly trickier for inline sourcemaps as you would need to edit the comment in the generated chunks by decoding and re-encoding it.

**Comment by Shin-Ogata** [comment]
> The sourcemaps are now emitted as actual files before generateBundle, so your plugin could operate on those in the bundle object (by removing them and re-emitting them as assets). 

Thank you for quick response.
How can I know the actual emitted file path in `generateBundle()` ?

Does it include in the properties of [ChunkInfo](https://rollupjs.org/guide/en/#generatebundle)?

**Comment by Shin-Ogata** [comment]
How can I know the chunk path?
I couldn't figure it out by following the key included in the `bundle` below.

```
[
  'exports',
  'facadeModuleId',
  'isDynamicEntry',
  'isEntry',
  'isImplicitEntry',
  'moduleIds',
  'name',
  'type',
  'dynamicImports',
  'fileName',
  'implicitlyLoadedBefore',
  'importedBindings',
  'imports',
  'modules',
  'referencedFiles',
  'code',
  'map'
]
```

**Comment by lukastaegert** [comment]
It is the `fileName` property

**Comment by Shin-Ogata** [comment]
> It is the fileName property

Unfortunately, `fileName` doesn't seem to contain a directory path.

```js
for (const key of Object.keys(bundle)) {
    const chunk = bundle[key];
    console.log(Object.keys(chunk));
    console.log(`fileName: ${JSON.stringify(chunk.fileName)}`);
    // fileName: "core-utils.js"
}
```

Or should the directory be considered the path passed to `output.file`?
But that is unlikely, as it would be a problem if there were `.map` files that is outside `rollup` responsibility in that directory.

**Comment by Shin-Ogata** [comment]
> But that is unlikely, as it would be a problem if there were .map files that is outside rollup responsibility in that directory.

Sorry I misunderstood a little.
So you were saying that you should manipulate the .map file of the final product, right?
Then I agree.

**Comment by lukastaegert** [comment]
No, you should be able to do it in JavaScript in the bundle. 
> Unfortunately, fileName doesn't seem to contain a directory path
Yes, paths are relative to the `dir` or `file` option as the bundle does not know if or where it will be written.

**Comment by Shin-Ogata** [comment]
> No, you should be able to do it in JavaScript in the bundle.

I got it. indeed.
And the temporary files are not created.
But I think that it is necessary to consider whether it is work to be done with a plug-in.
I understand the situation. Thanks a lot.

**Comment by lukastaegert** [comment]
Incidentally, we have quite a few options around sourcemaps these days, I'm not sure what the overlap of your plugin with [`sourcemapBaseUrl`](https://rollupjs.org/guide/en/#outputsourcemapbaseurl) and [`sourcemapPathTransform`](https://rollupjs.org/guide/en/#outputsourcemappathtransform) is?

**Comment by Shin-Ogata** [comment]
Thank you for information.

What I want to do is create and display root for each library on inspector as follows.
For that I need to adjust `sourceRoot` and `sources` in source-map.

![inspector](https://user-images.githubusercontent.com/10623508/195477185-2d956470-5c2d-48cd-995d-2ec2b4eef62e.png)

> [sourcemapBaseUrl](https://rollupjs.org/guide/en/#outputsourcemapbaseurl)

It option seems to be different purpose.  
The option is to specify a 'base url' for the 'sourceMappingURL' in the last line of the js source, but this doesn't match my purpose.


> [sourcemapPathTransform](https://rollupjs.org/guide/en/#outputsourcemappathtransform)

Yes. This option works well enough to adjust `sources`.

**Comment by Shin-Ogata** [comment]
By the way, are you going to continue this behavior change in the future? (do not reflect bundle.map in `generateBundle`)  
I feel little bit a strange that changes in `generateBundle` are not reflected, but I respect your decision.  
In that case I'd move to `writeBundle` at least or I'd consider any other solutions.

Thanks,

**Comment by lukastaegert** [comment]
> I feel little bit a strange that changes in generateBundle are not reflected

The problem is that at this point, people can just manually mess with the actual sourcemap files, so updating them after `generateBundle` could become problematic.

**Comment by Shin-Ogata** [comment]
Ok, so what do you think that the right `hook` to patch the `source-map` created by `rollup`.
- `generateBundle`
- `writeBundle`
- others

**Comment by lukastaegert** [comment]
Definitely `generateBundle`. Otherwise, tools that just run `bundle.generate` (like the browser build of Rollup, and people that runs scripts for in-memory builds) will not be able to use the plugin.

**Comment by Shin-Ogata** [comment]
I was able to make it work as expected with the following changes.


```js
'use strict';

const { relative } = require('path');

function refrect(opts, content, map) {
    if (!sourcemap) {
        // noop
        return;
    }

    if ('inline' === sourcemap) {
	// source-map helper module
        const { appendInlineSourceMap } = require('../lib/source-map-utils');
        content.code = appendInlineSourceMap(content.code, map);
    } else {
        content.source = JSON.stringify(map);
    }
}

function setSourceMapRoot({ relativePath, sourceRoot } = {}) {
    const [domain] = sourceRoot ? sourceRoot.split(':') : [''];
    const regexNS = new RegExp(`^([\\s\\S]+)(/@${domain}/)([\\s\\S]+)$`);
    const replacePath = src => relative(relativePath, src)
        .replace(/\\/g, '/')
        .replace(/^\w+:\/(?!\/)/, '$&/')
        .replace(regexNS, '$3')
        .replace(/^\.\.\/node_modules\//, '')
    ;
    return Object.freeze({
        name: 'source-map-root',
        generateBundle(outputOptions, bundle) {
            for (const content of Object.values(bundle)) {
                const { map: srcmap, source } = content;
                const map = srcmap || JSON.parse(source);
                if (!map) {
                    continue;
                }
                if (relativePath && Array.isArray(map.sources)) {
                    // `sourcemapPathTransform` option available
                    map.sources = map.sources.map(replacePath);
                }
                if (sourceRoot) {
                    map.sourceRoot = sourceRoot;
                }
                refrect(outputOptions, content, map);
            }
        },
    });
}

module.exports = setSourceMapRoot;
```

My problem is solved, so you can decide this issue to keep open or close.
Thank you for your help.

**Comment by lukastaegert** [comment]
Nice! That looks simple enough.
