### ISSUE TITLE
cache: false not working

### ISSUE THREAD

**Issue by johann1301s** [rollup/rollup#4677]
```js
const bundle = await rollup({
  input: 'packagesrc/button.tsx',
  cache: false, // <---- cache is disabled
  onwarn: () => {},
  plugins: [
    dts({
      compilerOptions: {
        incremental: false
      }
    })
  ]
})

const result = await bundle.generate({})
```

Rollup is still generating `.rollup.cache` folder. Why?

**Comment by lukastaegert** [comment]
What is that folder you are talking about? Rollup does not have a disk cache. Maybe some plugin of yours?

**Comment by johann1301s** [comment]
<img width="489" alt="Skjermbilde 2022-10-16 kl  19 52 11" src="https://user-images.githubusercontent.com/25029220/196050411-5903b082-9b61-4f6e-850e-43e11cffd739.png">

**Comment by johann1301s** [comment]
I think you are right, its probably one of my plugins.

**Comment by johann1301s** [comment]
I checked it out again, and it is not rollup that is creating the folder. It is `@rollup/plugin-typescript`. I switched to `rollup-plugin-typescript2` and it seems to have solved my issue.

Thank you! Closing this issue:)
