### ISSUE TITLE
`new.target` is treated as `import.meta`

### ISSUE THREAD

**Issue by petamoriken** [rollup/rollup#4678]
### Rollup Version

v3

### Operating System (or Browser)

Chrome 106

### Link To Reproduction

https://rollupjs.org/repl/?version=3.2.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2cobmV3LnRhcmdldCklM0IlNUNuJTIwJTIwJTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmFtZCUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behaviour

```js
define(['exports'], (function (exports) { 'use strict';

  class Foo {
    constructor() {
      console.log(new.target);
    }
  }

  exports.Foo = Foo;

}));
```

### Actual Behaviour

```js
define(['exports'], (function (exports) { 'use strict';

  class Foo {
    constructor() {
      console.log(({ url: new URL(module.uri, document.baseURI).href }));
    }
  }

  exports.Foo = Foo;

}));
```

**Comment by lukastaegert** [comment]
Oops, fix at #4679.
