### ISSUE TITLE
Confusing es6 format name

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#468]
https://github.com/rollup/rollup/wiki/JavaScript-API#format
I think we should change `es6` format name to `es2015` as standard name. es6 is informal way to specify new standard features, but it shouldn't be used in documentation and especially in api.
/cc @Rich-Harris @Victorystick @eventualbuddha

**Comment by rosskevin** [comment]
Agreed, I noticed that today as I switched my other nomenclature to es2015, the `format` option rejects `es2015` as a value.

**Comment by Victorystick** [comment]
Yes, we'd do best to move away from the `es6` name. Perhaps we should go with `esm`; ECMAScript modules? With `es6` and `es2015` as aliases?

**Comment by TrySound** [comment]
@Victorystick Why only three chars? There is `iife` with four chars. So `ecma` seems better.

**Comment by Victorystick** [comment]
> Why only three chars?

`ecmascript-modules` seemed a bit long. :stuck_out_tongue: I thought we'd emphasise the _modules_ part. Since neither CommonJS, or IIFE has any mention of _module_, I suppose `ecma` makes sense. :+1:

**Comment by eventualbuddha** [comment]
Having `ecma` be the real name and `es6` begin issuing a warning seems good to me.

**Comment by arturparkhisenko** [comment]
Disscussion about formats in [twitter of Axel Rauschmayer](https://twitter.com/rauschma/status/693149204261294083) @rauschma

**Comment by Rich-Harris** [comment]
What about just `es`? To me that makes more sense as an abbreviation of `ecmascript`. (Also, I prefer green bikesheds...)

**Comment by TrySound** [comment]
@Rich-Harris Hm.. sure. Using standard abbreviation instead of "legacy" js seems much better.

**Comment by yaycmyk** [comment]
What about 'native'?

**Comment by TrySound** [comment]
Native is too big and incorrect. We decide `es` as new standard.

**Comment by Victorystick** [comment]
:+1: `es`

:-1: bikeshedding

**Comment by callumlocke** [comment]
:+1: es

I don't think this is bikeshedding, it's API design, names matter

**Comment by TrySound** [comment]
It's convention like callback style for node.

**Comment by eventualbuddha** [comment]
Let's do `es`. I think `native` suffers from association with native code
(i.e. compiled code).

**Comment by stevemao** [comment]
> I think we should change es6 format name to es2015 as standard name. es6 is informal way to specify new standard features, but it shouldn't be used in documentation and especially in api.

This is not correct. According to @ljharb , > ES6 and ES2015 are both correct identifiers for that version of the spec, and ES7 and ES2016 will both be correct identifiers for the upcoming version

**Comment by ljharb** [comment]
Specifically, last year's spec is the 6th edition of ECMAScript, named "ES2015". "ES6" is a shorthand for "ES, 6th edition".

**Comment by thepian** [comment]
es would indicate that it will output a newish format rather than some particular compatibility approach, makes sense.

**Comment by backspaces** [comment]
I'd stick with es6. Its a cli argument, for heaven's sate!  It would be like using commonJS instead of cjs.

**Comment by Rich-Harris** [comment]
As of 0.32.0, `es6` is deprecated in favour of `es` (it'll still work, but with a warning)

**Comment by ljharb** [comment]
The only difficulty is that "what `es` means" will change, potentially every single day, as changes are merged into the official spec. ¯\\\_(ツ)_/¯

**Comment by Rich-Harris** [comment]
@ljharb nah, the ES module spec is done. Changes to other parts of ECMAScript don't concern us here

**Comment by pitrp** [comment]
What about bin/src/help.md?
   `-f, --format [es6]       Type of output (amd, cjs, es6, iife, umd)`
Should probably just mention `es` now.  The referenced wiki pages are already updated.

**Comment by TrySound** [comment]
@pitrp Good catch. Thanks!

**Comment by snuggs** [comment]
@TrySound @Rich-Harris coincidentally i've been giving lightening talks about this very topic.  I was in a room with 20 developers whom were arguing over this very topic (in regards to file extensions). When they asked my thoughts I said "You guys can have the battle of file extensions. Why not just say `.es` and call it a day?! 

The room went quiet.

I've been using `.es` for months now while the filename/extension/acronym saga continues. My convention is immediately I can tell a "module's" status in the transpilation pipeline from merely looking at the extension. `.es` probably needs transipiling. `.js` Already transpiled. Have moved all my apps over to this convention and works smashingly (even with rollup/bubble)

@TrySound thanks for seeing eye to eye on this. As developers we sometimes have our noses so high in the air often we can't see what's directly under them. #FreeJewelry

👍  for `es`

![capture d ecran 2016-09-05 a 21 14 14](https://cloud.githubusercontent.com/assets/38223/18259014/8beee794-73ad-11e6-8800-700c757f1215.png)

**Comment by ljharb** [comment]
If node ends up going with `.mjs`, then that's the extension that everyone will settle on, but `.es` is as good as anything else.

@Rich-Harris the module spec is not done; there's two proposals to change it on the docket for us to discuss in the September TC39 meeting. Nothing's done in JS until it's web-incompatible to change it :-)

**Comment by TrySound** [comment]
We decide not to use any new extensions and separate formats only with `main` and `module` fields in `package.json`. So it's better to use the same `.js`. `es` in this context is just output format name.

**Comment by snuggs** [comment]
Oh dude no stress @TrySound wasn't about file extension of `.es` as much as it's about the debating of what to call ecmascript. Was more a praise to rollup / buble for working with `.es` extensions out of the box (little do some know). And that extension has nothing to do with rollup as it has to do more with `require`

Here's my hack when all else fails:
```javascript
require.extensions['.es'] = require.extensions['js']
```
Easy peasy lemon squeezy. Smooth like butter. :-D
