### ISSUE TITLE
Suggest an alternative to rollup-plugin-terser in doc

### ISSUE THREAD

**Issue by yukulele** [rollup/rollup#4688]
### Documentation is

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not sure?

### Please Explain in Detail...

Rollup doc [suggest](https://rollupjs.org/guide/en/#using-output-plugins) to use [rollup-plugin-terser](https://github.com/TrySound/rollup-plugin-terser) as minifier.

Unfortunately this plugin is not compatible rollup@3 and is not in active development since 2 years.

### Your Proposal for Changes

Since minification is a very basic Rollup's users need, the doc should suggest a more robust solution.

**Comment by schlawg** [comment]
Is it truly not compatible?  Or does somebody just need to allow rollup 3 in its package dependencies?

**Comment by dasa** [comment]
Hopefully there will be an official plugin available soon: https://github.com/rollup/plugins/pull/1323

**Comment by yukulele** [comment]
done :tada: 
https://github.com/rollup/plugins/tree/master/packages/terser#readme

**Comment by dasa** [comment]
Updating the Rollup doc still seems like a good idea.

**Comment by yukulele** [comment]
Indeed

**Comment by lukastaegert** [comment]
Docs PR welcome!
