### ISSUE TITLE
User specified include

### ISSUE THREAD

**Issue by chrisseto** [rollup/rollup#469]
My apologies if there is a way to do this, I've yet to find one.

Is there a way to include specific files, ideally via glob, that are not otherwise imported?

I'm developing an app using [riot](http://riotjs.com) which maintains an internal registry of tags.
`.tag` files just need to be executed to use them. It would be very useful to automatically include all files with a given extension.

```javascript
export default {
  format: 'cjs',
  entry: 'src/main.js',
  dest: 'build/bundle.js',
  include: ['src/**/*.tag'],
  plugins: [
    riot(),
    babel()
  ]
};
```

Looking through the code there doesn't seem to be a great place to do this with plugins.
Most hooks exist for transforming existing code, not adding in new code.

**Comment by TrySound** [comment]
Here simple example
https://github.com/TrySound/rollup-plugin-string/blob/master/src/index.js
You can make plugin

**Comment by chrisseto** [comment]
@TrySound thanks for the example but I'm afraid that's not quite what I'm looking for.
That's still a transform on incoming files, unless you're suggesting injecting import statements into the entry point.

**Comment by TrySound** [comment]
@chrisseto Don't understand. Import, but not import?

**Comment by chrisseto** [comment]
@TrySound pretty much, I'd like the equivalent of `gulp.src(['my-entry-point.js', 'extraneous/files/*.js'])`

**Comment by TrySound** [comment]
You can use banner.
https://github.com/rollup/rollup/wiki/Plugins#creating-plugins

**Comment by TrySound** [comment]
But I i'm not sure what you want is good pattern.

**Comment by chrisseto** [comment]
I'll take a look into that, thank you for your help!
I realise this is not a great pattern but the convenience outweighs the "anti-patternness" of it, for this specific use case.

**Comment by Victorystick** [comment]
@chrisseto I'd create a file that imports the files you want, and import that. It's guaranteed to work. If you don't want to manage it manually, just generate it from a glob of the files you want.

**Comment by eventualbuddha** [comment]
You can probably achieve this with [rollup-plugin-mutli-entry](https://github.com/eventualbuddha/rollup-plugin-multi-entry):

```js
import multiEntry from 'rollup-plugin-multi-entry';
import babel from 'rollup-plugin-babel';
import riot from 'rollup-plugin-riot';

export default {
  format: 'cjs',
  entry: ['src/main.js', 'src/**/*.tag'],
  dest: 'build/bundle.js',
  plugins: [
    riot(),
    babel(),
    multiEntry()
  ]
};
```

**Comment by chrisseto** [comment]
@eventualbuddha, that was the one plugin I didn't look at. Thank you!
