### ISSUE TITLE
Import alias reverted in bundled file

### ISSUE THREAD

**Issue by Jack-Works** [rollup/rollup#4696]
### Rollup Version

latest in playground

### Operating System (or Browser)

browser

### Link To Reproduction

https://rollupjs.org/repl/?version=3.2.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyME1vZHVsZSUyMGFzJTIwVG9wTW9kdWxlJTIwJTdEJTIwZnJvbSUyMCcuJTJGbW9kdWxlLmpzJyU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGbW9kdWxlLmpzJyU1Q24lNUNuZXhwb3J0JTIwY2xhc3MlMjBFdmFsdWF0b3IlMjAlN0IlNUNuJTIwJTIwY29uc3RydWN0b3IoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjbGFzcyUyME1vZHVsZSUyMGV4dGVuZHMlMjBUb3BNb2R1bGUlMjAlN0IlN0QlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coTW9kdWxlKSU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjbGFzcyUyME1vZHVsZSUyMCU3QiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behaviour

No error

### Actual Behaviour

ReferenceError: Cannot access 'Module' before initialization

Rollup did a bad name transform

**Comment by lukastaegert** [comment]
Thank you for spotting + the concise repro. Fix at #4697.
