### ISSUE TITLE
chunk hashes, import and long term caching

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [rollup/rollup#4709]
Not sure if this issue has been brought up here already, sorry if it has been, I didn't find anything. Anyway - open then repro and change any of the `'foo'` string to something else. You'll see that all hashes change, which is bad for long term caching, obviously you don't want your users to download your full application if only there's a typo fix in a small chunk.

This repro contains recursive imports, which not always can be avoided. However even without this recursion all chunks "above" the changed one will have changed hashes (ex. if you have main -> index -> module_1 -> util, and also module_2 imported in index, but module_2 doesn't import util - in this case change in util will change the hash of index, module_1 and util). Better but not ideal.

Webpack on the other hand creates runtime.js (or whatever the file is called) with hashes, and updating util.js would change the hash only for util.js and runtime.js chunks.

Any plans to improve the behaviour?

[https://rollupjs.org/repl/?version=3.2.5&shareable=JTdCJTIybW9kdW...](https://rollupjs.org/repl/?version=3.2.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRmluZGV4LmpzJyklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJpbmRleC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQoJy4lMkZtb2R1bGVfMS5qcycpJTVDbmltcG9ydCgnLiUyRm1vZHVsZV8yLmpzJyklNUNuaW1wb3J0KCcuJTJGbW9kdWxlXzMuanMnKSU1Q25leHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMCdmb28nJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAnLiUyRnV0aWwuanMnJTVDbmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRmluZGV4LmpzJyUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBmb28lMjAlN0QlMjBmcm9tJTIwJy4lMkZpbmRleC5qcyclNUNuY29uc29sZS5sb2coZm9vJTJDJTIwJ2ZvbycpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZV8zLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRmluZGV4LmpzJyU1Q25jb25zb2xlLmxvZyhmb28lMkMlMjAnZm9vJyklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydXRpbC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJjb25zb2xlLmxvZygnZm9vJyklMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

**Comment by jacekkarczmarczyk** [comment]
Cool, that sounds like something doable ;)

**Comment by dasa** [comment]
> While only supported in some browsers

There's also a shim available at: https://github.com/guybedford/es-module-shims

**Comment by jacekkarczmarczyk** [comment]
Seems like this has been already discussed in https://github.com/rollup/rollup/issues/3407
