### ISSUE TITLE
Rollup sometimes fails with “Cannot read properties of null (reading 'included')” when using “external”

### ISSUE THREAD

**Issue by tkalliom** [rollup/rollup#4722]
### Rollup Version

3.4.0

### Operating System (or Browser)

Linux

### Node Version (if applicable)

16.18.1

### Link To Reproduction

https://github.com/tkalliom/rollup-isincluded-bug

### Expected Behaviour

Rollup does not do anything with dependencies declared as `external`.

### Actual Behaviour

Rollup does some processing with an `external` dependency, failing with `Cannot read properties of null (reading 'included')`. This is a regression; we encountered this trying to upgrade Rollup from 2.6 to 3.4.

There was some previous discussion regarding this issue in the comments of #4297 – others have run into this as well

**Comment by lukastaegert** [comment]
Thanks for the reproduction, it was very insightful. Fix at #4725 .
