### ISSUE TITLE
`output.assetFileNames()`: provide original file path of assets

### ISSUE THREAD

**Issue by brillout** [rollup/rollup#4724]
### Feature Use Case

I'd like to preserve the original file structure by using `output.assetFileNames()`. But for that I need the original file path of the assets.

Currently, `AssetInfo` is missing that information:

```ts
type AssetInfo = {
  name?: string;
  source: string | Uint8Array;
  type: 'asset';
};
```

### Feature Proposal

Provide the original file path of the asset:

```ts
type AssetInfo = {
  name?: string;
  source: string | Uint8Array;
  type: 'asset';
  // New property:
  originalFilePath: string
};
```

**Comment by lukastaegert** [comment]
I definitely see the use of adding additional meta information here. Note though that this this would be a field solely filled and read by plugins. So I guess there should be clear expectations what people put in here:
- The resolved absolute file name?
- The same, but with normalised slashes?
- A file url?
- A relative path (relative to what?)?

Alternatively, we could also add a `meta` field as we have in other places where plugins can store arbitrary information provided they obey some rules (namespaces by plugin?).

So would you rather expect a specific field here that every plugin should be refactored to add, or more like a general way to attach meta information?

**Comment by brillout** [comment]
I was assuming that the original file path is known by Rollup, e.g. I can access the file path of scripts by using `facadeModuleId`. But, since this isn't the case, I'm wondering whether it's worth it to introduce a new convention merely for this.

Regarding your questions, I think I lack knowledge about Rollup for having preferences: each of your proposals sounds good to me.

**Comment by lukastaegert** [comment]
The only way to create assets in Rollup is by emitting them, which also limits the available information: https://rollupjs.org/guide/en/#thisemitfile

**Comment by lukastaegert** [comment]
I that case, adding additional properties would probably not achieve your goal as all plugins would need to learn about them for this to work.

**Comment by brillout** [comment]
I see. I'm not sure if it's worth it. I'm closing this but I can re-open if someone else is interested.

**Comment by koskinpark** [comment]
Hello! The thing is.. we (and probably lots of other people and our amount will grow that's for sure) are following component's approach. When we have some component's folder with component's related files inside, like:

- component folder name
- - component.source.css
- - component.source.js
- - component.some-other-files

and we want to build our assets into component's folder, like:
- component folder name
- - dist
- - - component.compiled.css
- - - component.compiled.js
- - component.source.css
- - component.source.js
- - and so on


In that case component is really independent, so it have everything inside. But i don't see an easy way to customize vite somehow to provide such functionality -> coz it puts all assets in some pre-defined folder (like `dist` folder by default).

**Comment by koskinpark** [comment]
- component-1
- - component-1.src.css
- - component-1.src.js
- - dist
- - - component-1.css
- - - component-1.js

- component-2
- - component-2.src.css
- - component-2.src.js
- - dist
- - - component-2.css
- - - component-2.js

and so on

**Comment by brendanarnold** [comment]
We have a use case where we want to restrict access to assets on some paths under our `src` directory. Being able to 'rebuild' the `src` structure to some degree under `dist/assets` would mean we can apply simple rules against serving content in individual directories. Our only option at the moment is to include the neessary info in every asset filename which is less han ideal.

**Comment by albertreed** [comment]
FWIW - we have a similar situation. There is a collection of binary assets (images mostly) that are stored in a separate directory but are cooked by rollup and as a result, are collapsed back into the dist folder. At deploy-time need to be split off from the rest of the build to be hosted elsewhere. Right now the only solution we've found is to sort of awkwardly copy all the files, appending a special key in the filename that gets picked up by `assetFileNames` so they can be stored separately. 

Has anyone found a more elegant solution?

**Comment by brillout** [comment]
(Re-opening since there seem to be interest from other users.)

**Comment by casually-creative** [comment]
I have a semi-working implementation that achieves this by using some path magic on the facadeModuleId. (vite.js)

```js
rollupOptions:
{
	input: [...getEntryScriptsFilePaths(__dirname), ...getEntryStylesFilePaths(__dirname)],
	output:
	{
		dir: "./wwwroot/",
		entryFileNames: (chunkInfo) =>
		{
			const originalScriptExtensions = [".js", ".ts", ".jsx", ".tsx"];
			const originalStyleExtensions  = [".css", ".scss"];

			const relativePath = path.relative(path.join(__dirname, "Assets"), chunkInfo.facadeModuleId);

			if (!relativePath)
				return chunkInfo.name;

			const extension = path.extname(relativePath);
			const fileName  = path.basename(relativePath, extension);
			const relativePathWithoutExtension = path.join(path.dirname(relativePath), fileName);

			if (originalScriptExtensions.includes(path.extname(relativePath)))
			{
				const filePath = `${relativePathWithoutExtension}.js`;

				console.log("1: " + filePath);
				return filePath;
			}

			if (originalStyleExtensions.includes(path.extname(relativePath)))
			{
				const filePath = `${relativePathWithoutExtension}.css`;

				console.log("2: " + filePath);
				return filePath; // This is not working as intended. The css files are placed in the root "assets" directory instead of the relative path I provide.
			}

			return chunkInfo.name;
		},
		sourcemap: true
	}
}
```

*note: this follows a typical structure in .NET Core. See wwwroot as dist, and Assets as src.*

The output is this:

```
wwwroot/forms-4383d2a6.css                           0.05 kB │ gzip:   0.07 kB
wwwroot/cards-9a4cb5a8.css                           0.06 kB │ gzip:   0.07 kB
wwwroot/buttons-6091058e.css                         0.21 kB │ gzip:   0.14 kB
wwwroot/modals-e184ac9e.css                          0.39 kB │ gzip:   0.19 kB
wwwroot/decorations-f620784a.css                     0.72 kB │ gzip:   0.25 kB
wwwroot/layout-aa32be54.css                          1.60 kB │ gzip:   0.45 kB
wwwroot/styles-a0e7bad7.css                          4.02 kB │ gzip:   1.27 kB
wwwroot/tables-f3e96490.css                          5.24 kB │ gzip:   0.73 kB
wwwroot/errors-f7300b4d.css                          5.34 kB │ gzip:   1.05 kB
wwwroot/styles-202ee804.css                          9.28 kB │ gzip:   1.79 kB
wwwroot/index-94323a0f.css                          15.64 kB │ gzip:   3.86 kB
wwwroot/index-7c2f51f0.css                          21.87 kB │ gzip:   6.20 kB
wwwroot/index-69583cf9.css                          28.47 kB │ gzip:   5.67 kB
wwwroot/Scripts\General\tables.js                    0.41 kB │ gzip:   0.27 kB │ map:     0.97 kB
wwwroot/Scripts\General\all-pages.js                 0.46 kB │ gzip:   0.33 kB │ map:     0.89 kB
wwwroot/index-99794716.js                            1.61 kB │ gzip:   0.56 kB │ map:     3.82 kB
wwwroot/Scripts\Pages\Planning\Transport\index.js  176.90 kB │ gzip:  35.25 kB │ map:   324.34 kB
wwwroot/Scripts\Pages\Planning\Stable\index.js     536.72 kB │ gzip: 102.62 kB │ map:   941.19 kB
wwwroot/index-4a96550d.js                          941.37 kB │ gzip: 187.13 kB │ map: 1,605.46 kB
```

However its not working for the stylesheets, even though I'm doing exactly the same as with the script files. All the scripts are in the right place but the stylesheets are not. I believe this to be bug in rollup.

There's also this from the official docs but it ends up with the same stylesheets issue (2nd section): https://rollupjs.org/configuration-options/#input

**Comment by supuwoerc** [comment]
I am also a user who is interested in this feature...my requirement is to change the output file to the name of the folder, but I can't get the path right now  :(

**Comment by e2goon** [comment]
I've done some testing and there seems to be a bug.

```js
rollupOptions: {
  ...,
  output: {
    assetFileNames: "assets/[name].[ext]",
  },
},
```

After adding the above options.

![image](https://github.com/rollup/rollup/assets/45934/17a64260-b257-4d54-8819-0bc5d9c4a6b1)

When I build it, it exports a file named style_v2.css, which is what I want, but it actually imports and uses style_v2.scss.

However, if you import the style_v2.scss file from a single sub.html file and build it, the sub.scss file is exported.

If you want a file named style_v2.css to be output, you'll need to call the same file's scss from at least two html files to make it happen.

**This is a bug.**

**Comment by JoshuaCrewe** [comment]
We have a similar approach to one of the comments above (https://github.com/rollup/rollup/issues/4724#issuecomment-1398010927) but we are putting the output in the dist folder.

Each component has its own template, styles and scripts. The template file is irrelevant here but the style and script files should be compiled down to their own dist files. These files are all called the same thing (`style.scss` and `script.js`) so the output files end up being `style.css`, `style2.js` `etc.`

The current solution in webpack land is to compile each to their own folder in `dist` which is named after the component. So we get the name from the containing folder and use this in the output path. This currently works for JS in vite but not for the styles.

For JS, it is something like the following :
```
    entryFileNames: (assetInfo) => {
        if (assetInfo.name == 'app') {
            return `js/[name].js`;
        }

        let path = assetInfo.facadeModuleId;
        let d = path.split('/');
        let name = d[d.length - 2];
        let file = d[d.length - 1];
        let ext = file.split('.').pop();

        return `js/components/${name}.js`;
    },
```

As has already been pointed out, `facadeModuleId` isn't there for `assetFileNames` and no more information is supplied about the entry file which can be used, nor is there a way to pass that information in. The feature proposal from OP would be sufficient for our use case as well I feel.

**Comment by cunjieliu** [comment]
need this feature

**Comment by amengdewo** [comment]
need this feature

**Comment by ejhernandez913** [comment]
+1

**Comment by cyocun** [comment]
+1

**Comment by AlexC-ux** [comment]
+1

**Comment by fklee** [comment]
+1

**Comment by romainwurtz** [comment]
+1

**Comment by lukastaegert** [comment]
I see there is a lot of interest in that feature. I still want to point out that with how Rollup works, this will need an extension in the [`this.emitFile`](https://rollupjs.org/plugin-development/#this-emitfile) plugin API so that plugins can provide this, and then a change in all relevant plugins (especially the Vite-provided plugins, but also regular Rollup plugins) to add this information.

So here would be a simple proposal, following the original issue:

We extend the interface for emitted assets with a `originalFileName` property that is expected to correspond to an absolute path on disk.

```ts
interface EmittedAsset {
	type: 'asset';
	name?: string;
	needsCodeReference?: boolean;
	fileName?: string;
+	originalFileName?: string;
	source?: string | Uint8Array;
}
```

If present, this property will be attached to `PrerenderedAsset` and `OutputAsset` in all relevant locations like the `generateBundle` hook.

```ts
interface PreRenderedAsset {
	name: string | undefined;
+	originalFileName: string | null;
	source: string | Uint8Array;
	type: 'asset';
}
```

Thoughts?
