### ISSUE TITLE
areEntryPointsContainedOrDynamicallyDependent function,entriesToCheck 500 billion counts( bug ),Build took 5 hours

### ISSUE THREAD

**Issue by cayweb778** [rollup/rollup#4733]
### Rollup Version

2.79.1

### Operating System (or Browser)

macos

### Node Version (if applicable)

16.9

### Link To Reproduction

https://github.com/cayweb778/hello.git

### Expected Behaviour

#4732

### Actual Behaviour

#4732

**Comment by lukastaegert** [comment]
Would be nice to keep the discussion to a single thread for now, closing this in favor of the original issue https://github.com/rollup/rollup/issues/4732.
