### ISSUE TITLE
What is areEntryPointsContainedOrDynamically Dependent used for?

### ISSUE THREAD

**Issue by cayweb778** [rollup/rollup#4734]
What is areEntryPointsContainedOrDynamically Dependent used for? I removed it, reduced the construction time from 5 hours to less than 5 minutes, and simply tested the running status. It is good.

about Explore details #4732

**Comment by lukastaegert** [comment]
Would be nice to keep the discussion to a single thread for now, closing this in favor of the original issue #4732.
