### ISSUE TITLE
[Rollup3.6+] vite build is slow ,vite transform 10000+ file( 2000+[vue] file), It takes 2 hours to build a mac os air t¹ 🐞 bug

### ISSUE THREAD

**Issue by cheng-io** [rollup/rollup#4740]
### Rollup Version

3.7.1-0

### Vite Version

4.0.0-beta.3

### Operating System (or Browser)

macos

### Node Version (if applicable)

16.9

### Link To Reproduction

https://github.com/cayweb778/vite2rolluptest.git

**Comment by cayweb778** [comment]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/40415260/206326548-8d0a3d28-e6e7-4b8e-98ec-7169fc4cd4d0.png">

**Comment by cayweb778** [comment]
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/40415260/206358009-4d042012-2d6c-46b2-ac54-2522ae2cf44e.png">

Slow in this function `buildAlreadyLoadedModulesByDynamicEntry`

**Comment by cayweb778** [comment]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/40415260/206359190-f891c3bf-771c-4d0e-8d46-4a2f36d59f92.png">

**Comment by lukastaegert** [comment]
Unfortunately, it is based on the old algorithm again that is slightly harder to understand, but as I learned from you, faster.

**Comment by cayweb778** [comment]
🎉🎉🎉  Thank you very much, Very Good, It's Fast!!!!

**Comment by cayweb778** [comment]
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by cayweb778** [comment]
The construction problem has been solved, and the construction speed is relatively fast, as well as the low memory construction

**Comment by cayweb778** [comment]
It's really exciting

**Comment by cayweb778** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/40415260/206381607-86bb1d7a-e1ca-4c14-b5cf-656a97e54d64.png">

**Comment by cayweb778** [comment]
It's good, if there is a problem, I will try to open it

**Comment by lukastaegert** [comment]
I will close the issue once I did a proper release with the fix.

**Comment by rxliuli** [comment]
Solved some of the performance issues, two of my app builds that were close to 5k modules now do not have issues, but another app that is over 6k modules still fails

**Comment by lukastaegert** [comment]
Would be interesting if you could pinpoint which part of the Rollup run is still exceptionally slow. Still the chunking algorithm? Incidentally, I forgot to close this issue after releasing the previous fix.

**Comment by rxliuli** [comment]
> Would be interesting if you could pinpoint which part of the Rollup run is still exceptionally slow. Still the chunking algorithm? Incidentally, I forgot to close this issue after releasing the previous fix.

It's been going on in vite for a long time, someone made a minimal reproducible example project, ref: https://github.com/vitejs/vite/issues/2433#issuecomment-1347627941

**Comment by lukastaegert** [comment]
Ah, so this is about OOM issues, I thought you were talking about performance issues. Unfortunately this is nothing I can fix by tweaking some algorithms, it requires some major changes. Which will happen, but it will take months at least. Until then, increasing `--max-old-space-size` is your best option. Depending on your OS, this can be set to values far exceeding physical memory. Will close this issue as the current issue has been fixed.
