### ISSUE TITLE
 Error: Cannot find module 'node:process'

### ISSUE THREAD

**Issue by 214531562** [rollup/rollup#4748]
### Rollup Version

3.7.3

### Operating System (or Browser)

windows 10  x64

### Node Version (if applicable)

14.19.1 

### Link To Reproduction

https://rollupjs.org/repl/

### Expected Behaviour

 internal/modules/cjs/loader.js:883
16:57:59   throw err;
16:57:59   ^
16:57:59 
16:57:59 Error: Cannot find module 'node:process'
16:57:59 Require stack:
16:57:59 - /var/jenkins_home/workspace/node-package-corpfecommon-corp-fe-bizcomp-newpolicy/node_modules/rollup/dist/bin/rollup
16:57:59     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
16:57:59     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
16:57:59     at Module.require (internal/modules/cjs/loader.js:952:19)
16:57:59     at require (internal/modules/cjs/helpers.js:88:18)
16:57:59     at Module.<anonymous> (/var/jenkins_home/workspace/node-package-corpfecommon-corp-fe-bizcomp-newpolicy/node_modules/rollup/dist/bin/rollup:16:19)
16:57:59     at Module._compile (internal/modules/cjs/loader.js:1063:30)
16:57:59     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
16:57:59     at Module.load (internal/modules/cjs/loader.js:928:32)
16:57:59     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
16:57:59     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
16:57:59   code: 'MODULE_NOT_FOUND',

### Actual Behaviour

rollup version  3.7.3

**Comment by lukastaegert** [comment]
Rollup 3 requires Node 16, Node 14 is end-of-life
