### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by iam-peekay** [rollup/rollup#475]
Hi. I keep getting this error, despite bundling using cjs format. My rollup config file looks like this: 
```
import babel from 'rollup-plugin-babel';

export default {
  entry: 'client/src/app.js',
  dest: 'dist/bundle.js',
  plugins: [ babel() ],
  format: 'cjs'
};
```

and I'm bundling by running ```rollup -c``` in root directory. I've also set my .babelrc file to have the es2015-rollup preset. But for some reason, i keep getting this error and can't figure out what's going on.

Any help would be really appreciated.

**Comment by eventualbuddha** [comment]
Can you provide more detail? Do you get the error when running rollup? Or when running the generated code? Is there a stack trace? Can you share the contents of app.js?

**Comment by eallik** [comment]
@iam-peekay but how did you end up resolving this?
