### ISSUE TITLE
[!] Error: Could not resolve error for .js and .jsx file references inside index.ts

### ISSUE THREAD

**Issue by abf7d** [rollup/rollup#4752]
### Rollup Version

2.60.0

### Operating System (or Browser)

Windows / Chrome

### Node Version (if applicable)

v18.12.1

### Link To Reproduction

https://github.com/abf7d/rollup-example

### Expected Behaviour

I am trying to rollup and publish a repo with an older version of react that is using plain .js and .jsx files. It has a few typescript files as well. I have followed [this tutorial](https://github.com/alexeagleson/template-react-component-library) but added a js file, included a reference to it in index.ts folder in the src folder. When I try to execute the `rollup -c` command I get an error that says 
```
dist/esm/types/index.d.ts → dist/index.d.ts...
[!] Error: Could not resolve './path-to/my/jsfile.js' from dist/esm/types/index.d.ts
```

I added @rollup/plugin-babel to the rollup config to process the jsx file.

### Actual Behaviour

The following error occurs when I reference a js file in index.ts in the src folder and run `rollup -c`
```
dist/esm/types/index.d.ts → dist/index.d.ts...
[!] Error: Could not resolve './path-to/my/jsfile.js' from dist/esm/types/index.d.ts
```
When I reference a .jsx file inside index.ts I get the error:
```
dist/esm/types/index.d.ts → dist/index.d.ts...
[!] Error: Could not resolve './path-to/my/jsxfile.jsx' from dist/esm/types/index.d.ts
```

**Comment by Tanimodori** [comment]
Your config contains two steps. In the first step, actual code gets bundled and declaration files are emitted by `@rollup/plugin-typescript` (which uses `typescript` to emit types). In the second step, declaration files are consumed by `rollup-plugin-dts` and generate a bundled `d.ts` file.


`rollup.config.js`

```js
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "@rollup/plugin-typescript";
import postcss from "rollup-plugin-postcss";
import dts from "rollup-plugin-dts";
import { babel } from '@rollup/plugin-babel';

const packageJson = require("./package.json");

export default [
  // Step 1
  {
    input: "src/index.ts",
    output: [
      {
        file: packageJson.main,
        format: "cjs",
        sourcemap: true,
      },
      {
        file: packageJson.module,
        format: "esm",
        sourcemap: true,
      },
    ],
    plugins: [
      resolve({extensions: ['.js', '.ts']}),
      babel({ babelHelpers: 'bundled', extensions: [".js", ".jsx"], }),
      commonjs(),
      typescript({ tsconfig: "./tsconfig.json" }),
      postcss(),
    ],
  },
  // Step 2.
  {
    input: "dist/esm/types/index.d.ts",
    output: [{ file: "dist/index.d.ts", format: "esm" }],
    plugins: [dts()],
    external: [/\.(css|less|scss)$/],
  },
];
```

The first bundle step was successful to generate. But `typescript` cannot know what types are in `js` and `jsx` files so it leaves it as-is.

`index.d.ts`

```ts
export * from './components';
export * from './Avivator/src/constants.js';
export * from './Avivator/src/test.jsx';
```

The latter two lines are causing `rollup-plugin-dts` to throw an error as it may not be able to expect `js` and `jsx` in `d.ts`, which ultimately stops the whole build.

I suggest remove the second step or writing your own d.ts to denote types those js and jsx files.

I see no bugs related to rollup itself. We are safe to close this issue.
