### ISSUE TITLE
Overlapping class names

### ISSUE THREAD

**Issue by plusgut** [rollup/rollup#4753]
### Rollup Version

3.7.4

### Operating System (or Browser)

firefox

### Link To Reproduction

https://rollupjs.org/repl/?version=3.7.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEJhciUyMGZyb20lMjAlNUMlMjIuJTJGZm9vJTVDJTIyJTVDbiU1Q25jb25zdCUyMHdyYXBwZXIlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjbGFzcyUyMEZvbyUyMGV4dGVuZHMlMjBCYXIlN0IlN0QlNUNuJTVDbiUyMCUyMHJldHVybiUyMEZvbyU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKHdyYXBwZXIoKSklNUNuJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBGb28lMjAlN0IlN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behaviour

When several classes with the same name exist, the classname should be made unique.
`  class Foo$1 extends Foo{}`

Same as in version 2.79.1 https://rollupjs.org/repl/?version=2.79.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEJhciUyMGZyb20lMjAlNUMlMjIuJTJGZm9vJTVDJTIyJTVDbiU1Q25jb25zdCUyMHdyYXBwZXIlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjbGFzcyUyMEZvbyUyMGV4dGVuZHMlMjBCYXIlN0IlN0QlNUNuJTVDbiUyMCUyMHJldHVybiUyMEZvbyU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKHdyYXBwZXIoKSklNUNuJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBGb28lMjAlN0IlN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Actual Behaviour

`  let Foo$1 = class Foo extends Foo{};
`

The class-name collides with the name of the sub class and and an exception is thrown

`Uncaught ReferenceError: can't access lexical declaration 'Foo' before initialization`

And also to use a class expression is unnecessarily long.

### Further information
The regression got introduced by Version 3.2.1 https://github.com/rollup/rollup/blob/master/CHANGELOG.md#321

**Comment by lukastaegert** [comment]
This was part of an optimization to keep the internal name of the class. I will see how I can fix this.

**Comment by lukastaegert** [comment]
Turns out that while there was a logic in place to avoid such conflicts, it ignored classes defined in default exports. Fixed in #4756

**Comment by plusgut** [comment]
Thank you so much, that`s so great
