### ISSUE TITLE
Replace repl.it reproduction template with a StackBlitz based solution (contributions welcome)

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#4755]
Currently, our repl.it based template https://repl.it/@rollup/rollup-repro no longer works with Rollup 3 as it runs with Node 14. And as the user experience of repl.it is not the best IMO, this could be an opportunity to create a default StackBlitz template for bugs.

- Should run Rollup when opened
- With a bare config file

I can create one myself, but there are many other things I also need to look into, so if someone wants to set something up, that would be very welcome!

**Comment by sapphi-red** [comment]
I've been using this template for a while. Does this one look good to you?
https://stackblitz.com/fork/rollup-template?file=rollup.config.js,src/main.js

**Comment by lukastaegert** [comment]
I like it, very minimal but easy to understand, and the additional scripts for code execution are very useful in reproductions.
Minor things: The format should be `es` without `m` and `exports` does not have an effect for that format. Other than that I think it is perfect!

**Comment by lukastaegert** [comment]
Question: Do you know of it is possible for me to directly edit the template? I really like that apparently it is some kind of "non-personal top-level" template. But I think it would be good if we could directly update the template periodically from Rollup side. Or do only StackBlitz associates have direct access to those templates?

**Comment by lukastaegert** [comment]
Ah, nevermind, I can just directly edit the slug! Awesome!

**Comment by lukastaegert** [comment]
I replaced the link, thanks a lot!
