### ISSUE TITLE
[workflow] could run a single test

### ISSUE THREAD

**Issue by TrickyPi** [rollup/rollup#4767]
### Feature Use Case

Currently, we don't have a command to run a single test, e.g. only run the `test/function/samples/associate-getter-return-values` test. Now, for running a single test, i have to comment some tests in `test/test.js` and write some conditional judgment in  `runSamples` function in `test/util.js` to filter other tests, so if we can support this, the debugging experience will be better.

### Feature Proposal

I think we can extend current test command, e.g. the test command can accept a folder path, i.e. `npm run test:only test/function/samples/associate-getter-return-values`, or we can add a new test command to achieve this.

**Comment by lukastaegert** [comment]
It is just missing documentation. Add `solo: true` you a `_config.js` file

**Comment by lukastaegert** [comment]
But if you think it is more useful  to your workflow, we could also add command line parameters. Another thing I could get behind is to allow renaming folders to `<folderName>.only` and interpret this as a `describe.only`/`it.only`. This would also allow to run only sets of tests based on folder structure (as samples can be arbitrarily nested)

**Comment by TrickyPi** [comment]
> It is just missing documentation. Add `solo: true` you a `_config.js` file

Oh, it's awesome, I think it's useful enough for me. Could we add this to `CONTRIBUTING.md`?

**Comment by lukastaegert** [comment]
Please do!
