### ISSUE TITLE
How to process a buffer with javascript API?

### ISSUE THREAD

**Issue by steelbrain** [rollup/rollup#477]
Currently the wiki page only states options that accept a file path. It would be nice to be able to execute this on strings and specify it's path on the file system. That path can then be used to resolve requires and things like that. Other pre-processors like babel and less support this already

**Comment by eventualbuddha** [comment]
This can be done with plugins, specifically [`rollup-plugin-memory`](https://github.com/TrySound/rollup-plugin-memory) could be used or a [custom plugin](https://github.com/rollup/rollup/wiki/Plugins) like it. If you have questions about how to achieve this, feel free to comment here or visit us on [Gitter](https://gitter.im/rollup/rollup).

**Comment by steelbrain** [comment]
@eventualbuddha Thanks for the pointer!
