### ISSUE TITLE
underscore-escaped filenames break web-extension. Filenames starting with "_" are reserved for use by the system.

### ISSUE THREAD

**Issue by milahu** [rollup/rollup#4772]
### Rollup Version

3.8.1

### Operating System (or Browser)

linux, chrome

### Link To Reproduction

https://github.com/milahu/search-aggregator-browser-extension/tree/repro-rollup-underscore-prefix-breaks-webext

### Expected Behaviour

emit filenames which are compatible with web extensions

### Actual Behaviour

im using vite with `build.rollupOptions.output.preserveModules = true` for faster dev builds (2x faster), but this emits paths like `dist/_virtual/index.js` which are illegal in web extensions

chrome error

> Failed to load extension
>
> Cannot load extension with file or directory name \_virtual.
> Filenames starting with "_" are reserved for use by the system.
>
> Could not load manifest.

blame `sanitizeFileName`

```js
const INVALID_CHAR_REGEX = /[\u0000-\u001F"#$&*+,:;<=>?[\]^`{|}\u007F]/g;
const DRIVE_LETTER_REGEX = /^[a-z]:/i;
function sanitizeFileName(name) {
    const match = DRIVE_LETTER_REGEX.exec(name);
    const driveLetter = match ? match[0] : '';
    // A `:` is only allowed as part of a windows drive letter (ex: C:\foo)
    // Otherwise, avoid them because they can refer to NTFS alternate data streams.
    return driveLetter + name.slice(driveLetter.length).replace(INVALID_CHAR_REGEX, '_');
}
```

quickfix: add `z` prefix before `_` prefix
the extra prefix should be short, to keep filenames short
the extra prefix should be configurable in rollupOptions

```js
    const name2 = driveLetter + name.slice(driveLetter.length).replace(INVALID_CHAR_REGEX, '_');
    return (name2[0] == "_") ? ("z" + name2) : name2
```

alternative fix: use a plugin to rename files, but currently i dont see how that could work in vite,
except in `transformIndexHtml` where i can patch import paths in sources (slow)

repro

```sh
cd $(mktemp -d)
git clone --depth 3 https://github.com/milahu/search-aggregator-browser-extension \
  --branch repro-rollup-underscore-prefix-breaks-webext
cd search-aggregator-browser-extension
mkdir dist/
readlink -f dist/ # use this path to "load unpacked" extension in chrome
# HEAD is fixed by patches/rollup+3.8.1.patch
git checkout 4791a80c1e137d42e618710a7e716293c3dd190f # broken
pnpm install
npm run dev # wait for "built in 15000ms." then load extension
```

vite.config.js

```js
import { defineConfig } from "vite";
import { crx } from "@crxjs/vite-plugin";
import manifest from "./src/manifest";

export default defineConfig(({ command }) => ({
  plugins: [
    crx({ manifest }),
  ],
  build: {
    rollupOptions: {
      output: {
        format: 'esm',
        preserveModules: true, // this causes the error
        preserveModulesRoot: __dirname,
      },
    },
  },
}));
```

**Comment by lukastaegert** [comment]
There are already two ways to address this:

- add a custom file name sanitizer [`output.sanitizeFileName`](https://rollupjs.org/guide/en/#outputsanitizefilename)
- fix the file name in [`output.entryFileNames`](https://rollupjs.org/guide/en/#outputentryfilenames) function

I really do not like adding a `z_` before virtual, then maybe make it `virtual_` instead. Also note that it is not the `sanitizeFileName` function that is responsible, this is just the folder for files that do not correspond to file system locations https://github.com/rollup/rollup/blob/0d543a28e2facf05849fa860bb4a8ae7c9c916c8/src/Chunk.ts#L1014-L1014

> im using vite with build.rollupOptions.output.preserveModules = true for faster dev builds (2x faster)

Interesting why that would be the case. Are you on latest Rollup? You could also try `build.rollupOptions.treeshake = false` to speed up things.

**Comment by milahu** [comment]
> * add a custom file name sanitizer [`output.sanitizeFileName`](https://rollupjs.org/guide/en/#outputsanitizefilename)

awesome! pardon my ignorance ...

so i can just use

vite.config.js

```js
import { defineConfig } from "vite";
import { crx } from "@crxjs/vite-plugin";
import manifest from "./src/manifest";

const INVALID_CHAR_REGEX = /[\u0000-\u001F"#$&*+,:;<=>?[\]^`{|}\u007F]/g;
const DRIVE_LETTER_REGEX = /^[a-z]:/i;

function sanitizeFileName(name) {
    // based on rollup.js
    const match = DRIVE_LETTER_REGEX.exec(name);
    const driveLetter = match ? match[0] : '';
    // A `:` is only allowed as part of a windows drive letter (ex: C:\foo)
    // Otherwise, avoid them because they can refer to NTFS alternate data streams.
    //return driveLetter + name.slice(driveLetter.length).replace(INVALID_CHAR_REGEX, '_');
    const name2 = driveLetter + name.slice(driveLetter.length).replace(INVALID_CHAR_REGEX, '_');
    // underscore filename prefix is illegal in web extensions.
    // chrome error: Filenames starting with "_" are reserved for use by the system.
    return (name2[0] == "_") ? ("z" + name2) : name2
}

export default defineConfig(({ command }) => ({
  plugins: [
    crx({ manifest }),
  ],
  build: {
    rollupOptions: {
      output: {
        format: 'esm',
        preserveModules: true,
        preserveModulesRoot: __dirname,

        sanitizeFileName,

      },
    },
  },
}));
```

> > im using vite with build.rollupOptions.output.preserveModules = true for faster dev builds (2x faster)
> 
> Interesting why that would be the case. Are you on latest Rollup? You could also try `build.rollupOptions.treeshake = false` to speed up things.

yes, rollup 3.8.1

to make the build faster, i have

```js
rollupOptions: {
preserveModules: true,
treeshake: false,
minify: false,
}
```

currently the slowest part is transforming modules
20 seconds on first build
10..15 seconds on rebuild = still 90% too much, because not incremental

related discussion https://github.com/vitejs/vite/discussions/6108

**Comment by lukastaegert** [comment]
`minify` is not really a Rollup option...
