### ISSUE TITLE
RFC: Add `resolvedBy` information to resolved ids

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#4773]
### Feature Use Case

I think I saw this somewhere on Discord but cannot find it any more. Currently when module resolution fails or returns unexpected results, it is hard to debug which plugin is responsible. This is especially tricky in scenarios where plugins resolve more module ids than expected.

### Feature Proposal

The idea is to add a new, purely informational flag `resolvedBy: string` to the `ResolvedId` type. When a plugin resolves an id, Rollup would add the resolving plugin's name to the resolved id. If Rollup itself resolves the file, we add `rollup`.

For debugging, one can then use `this.resolve` in a plugin hook to read this flag.

If a plugin returns a value for `resolvedBy` in the `resolveId` hook, then Rollup uses this name. This is to cover the scenario where a plugin just forwards the `this.resolve` result without or with only minimal modification.

This could be a good issue for an external contributor.

**Comment by TrickyPi** [comment]
I'd like to do this.

**Comment by lukastaegert** [comment]
This issue has been resolved via #4789 as part of rollup@3.10.0. You can test it via `npm install rollup`.
