### ISSUE TITLE
spec: namespace object keys should be sorted

### ISSUE THREAD

**Issue by dnalborczyk** [rollup/rollup#4776]
small spec alteration by rollup generated code

### Rollup Version

3.9.0

### Operating System (or Browser)

n/a

### Node Version (if applicable)

n/a

### Link To Reproduction

https://rollupjs.org/repl/?version=3.9.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJ2JhciclM0IlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGZvbyUyMGFzJTIwJUMzJUI4JTIwJTdEJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGZvbyUyMGFzJTIweiUyMCU3RCUzQiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMjBhcyUyMCUyNCUyMCU3RCUzQiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMjBhcyUyMCU1QyU1Q3UwM0MyJTIwJTdEJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmb28lM0IlNUNuZXhwb3J0JTIwJTdCJTIwZm9vJTIwYXMlMjBfX18lMjAlN0QlM0IlNUNuZXhwb3J0JTIwJTdCJTIwZm9vJTIwYXMlMjBhYSUyMCU3RCUzQiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMjBhcyUyMFolMjAlN0QlM0IlNUNuZXhwb3J0JTIwJTdCJTIwZm9vJTIwYXMlMjAlQzMlQjYlMjAlN0QlM0IlNUNuZXhwb3J0JTIwJTdCJTIwZm9vJTIwYXMlMjBBJTIwJTdEJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGZvbyUyMGFzJTIwJTI0JTI0JTI0JTIwJTdEJTNCJTVDbiU1Q25pbXBvcnQlMjAqJTIwYXMlMjBucyUyMGZyb20lMjAnLiUyRm1haW4uanMnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhPYmplY3QuZ2V0T3duUHJvcGVydHlOYW1lcyhucykpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

rollup input:

```js
// main.js
const foo = 'bar';

export { foo as ø };
export { foo as z };
export { foo as $ };
export { foo as \u03C2 };
export default foo;
export { foo as ___ };
export { foo as aa };
export { foo as Z };
export { foo as ö };
export { foo as A };
export { foo as $$$ };

import * as ns from './main.js';

console.log(Object.getOwnPropertyNames(ns));
```

### Expected Behaviour

```js
var ns = /*#__PURE__*/Object.freeze({
	__proto__: null,
	get $ () { return foo; },
	get $$$ () { return foo; },
	get A () { return foo; },
	get Z () { return foo; },
	get ___ () { return foo; },
	get aa () { return foo; },
	get default () { return foo; },
	get z () { return foo; },
	get ö () { return foo; },
	get ø () { return foo; },
	get ς () { return foo; },
});

const foo = 'bar';

console.log(Object.getOwnPropertyNames(ns));

export { foo as $, foo as $$$, foo as A, foo as Z, foo as ___, foo as aa, foo as default, foo as z, foo as ö, foo as ø, foo as ς };
```

### Actual Behaviour

```js
var ns = /*#__PURE__*/Object.freeze({
	__proto__: null,
	get ø () { return foo; },
	get z () { return foo; },
	get $ () { return foo; },
	get ς () { return foo; },
	get default () { return foo; },
	get ___ () { return foo; },
	get aa () { return foo; },
	get Z () { return foo; },
	get ö () { return foo; },
	get A () { return foo; },
	get $$$ () { return foo; }
});

const foo = 'bar';

console.log(Object.getOwnPropertyNames(ns));

export { foo as $, foo as $$$, foo as A, foo as Z, foo as ___, foo as aa, main as default, foo as z, foo as ö, foo as ø, foo as ς };
```

interestingly the generated exports are sorted (although I think they wouldn't need to be):

```js
export { foo as $, foo as $$$, foo as A, foo as Z, foo as ___, foo as aa, main as default, foo as z, foo as ö, foo as ø, foo as ς };
```

**Comment by lukastaegert** [comment]
Ah I see, I was not aware there was any implied sorting, but at least all browsers seem to adhere to this. While this is probably not critical, I think this would be a good opportunity for an external contributor so I will add the corresponding label.

> interestingly the generated exports are sorted

If I remember correctly, this was done to produce more stable hashes as there is not really a difference between two modules if only the order of exports differs. In that respect, sorting the namespace what also help to make hashes slightly more stable.
