### ISSUE TITLE
Access to list of all imported modules

### ISSUE THREAD

**Issue by OverZealous** [rollup/rollup#478]
I would be nice if the returned `bundle` object from `rollup(...).then(bundle)` included an array of all files that were imported.

My main use case for this is tying together non-JS modules with their components (like Webpack), so I can get a list of which modules are in use, and not include those that aren't.

I see there's a `bundle.imports`, but it apparently isn't exposing the same thing.

**Comment by OverZealous** [comment]
I'm an idjit—I just saw it's exported as `bundle.modules`! Sweet!

**Comment by jharris4** [comment]
In case it helps anyone, it looks like `bundle.modules` got replaced with `bundle.cache.modules` in version 1.x.
