### ISSUE TITLE
Give some bigger config examples (combining several plugins)

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup#479]
I would like to see some big `rollup.config.js` examples showing how to combine several rollup plugins for real practical purposes.

At the moment, each plugin's docs are quite isolated, and it's painful figuring out how to piece everything together. Every time I come back to rollup after a few weeks away from it, I have this same problem because I've forgotten it all :)

The holy grail config I'm always trying to get is:
- bundle my code with rollup
- using rollup's babel plugin, but with my own custom babel config (e.g. so I can use async functions and stuff)
- using rollup's common-js/npm plugins to convert non-jsnext dependencies into rollup-able code
  - but I want to manually exclude certain deps from this, either because I know they do weird require calls that cannot be safely converted to `import` statements, or because I want to keep them external because I want multiple bundles to share the same dep. For these excluded deps, I want my own code's `import` statement to be converted to a `require` call. So my final rollup output will contain a few require calls (which I can then use with any common-js based tool like browserify, or just run it in Node).

It sounds like a straightforward use of three plugins, but I always end up with about 6 browser tabs open (various wiki pages and plugin readmes) and asking myself questions like: what order should these plugins go in, whether I should be doing things in the common-js or the npm plugin, what do all these console warnings mean, etc... A few big, complex, practical example configs in the wiki would go a long way to solving this.

**Comment by eventualbuddha** [comment]
This may not entirely solve your issue, but does this help? https://github.com/rollup/rollup-starter-project

**Comment by callumlocke** [comment]
A little, but it only uses the babel plugin so it's a very simple example.

What I'd really like to see is some heavier real world scenarios:

- bundling a library (intended for both Node and browser use)
- bundling a CLI app for Node (the bundling priorities may be different – e.g. startup time more important than overall bundle filesize)
- bundling a regular clientside javascript that makes use of Node libraries
- bundling a clientside script, but excluding certain dependencies and bundling these separately so they can be loaded as one 'lib' bundle and shared between multiple main scripts

And ideally all the above examples/demos should have a mixture of jsnext and non-jsnext dependencies, and maybe even include an extra final build step for browserifying the rollup output to bundle in certain tricky deps that couldn't be converted on the fly.

**Comment by N1kto** [comment]
up! Mostly interested in the right order multiple plugins should be organized in. E.g. I have some transpiler plugin, also want to use `commonJS` plugin and `node-resolve` plugin. So, what should be the right order to list mentioned plugins in `rollup.config.js` and **why**?

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
