### ISSUE TITLE
rollup3.7.2 chunking algorithm introduce tow many js chunks

### ISSUE THREAD

**Issue by tjx666** [rollup/rollup#4802]
### Rollup Version

3.7.2

### Operating System (or Browser)

MacOS  Ventura 13.0.1 (22A400

### Node Version (if applicable)

16.19.0

### Link To Reproduction

https://github.com/vitejs/vite/issues/11659

### Expected Behaviour

check here https://github.com/vitejs/vite/issues/11659

@lukastaegert 

### Actual Behaviour

check here https://github.com/vitejs/vite/issues/11659

**Comment by tjx666** [comment]
@lukastaegert 

https://github.com/vitejs/vite/issues/11659#issuecomment-1379957827

> we need to make it configurable whether to use the original algorithm or not.

When will this land?

For now, I have to lock the rollup version to 3.7.1

**Comment by lukastaegert** [comment]
Sorry, I got distracted by other things. I will try to put something together in the next days.

**Comment by lukastaegert** [comment]
Here you go: #4837
