### ISSUE TITLE
Using digest('base64url') rather than digest('hex')?

### ISSUE THREAD

**Issue by dqh-au** [rollup/rollup#4803]
### Expected Behavior / Situation

Output filename hashes use A-Z, a-z, 0-9, -, _ characters (URL-safe base64)

### Actual Behavior / Situation

Output filename hashes use a-f, 0-9 (hexadecimal)

### Modification Proposal

By changing digest('hex') to digest('base64url'), the chance of hash collision would be greatly reduced for the same number of emitted hash characters, and the resulting files would still be filename and url safe.

maxHashSize would reduce to 27 from 64, however the error for requesting a length beyond this (e.g. `entryFileNames: '[name].[hash:64].js'`) should probably be a warning rather than an error.

Thank you for considering, I am a very happy recent convert to rollup.

**Comment by lukastaegert** [comment]
I would not want to change this for Rollup@3 because I expect some tools make assumptions about the format of hashes in regular expressions etc. But I am happy to note this down as an improvement for Rollup@4. Changing the error to a warning would be fine for me.

**Comment by lukastaegert** [comment]
Fair point, but my feeling is that this is an option that hardly anyone would use, so we should just do "the right thing" but avoid breaking changes. I actually thought about this for Rollup 3 but it was already late in the process and I did not want to further delay e.g. Vite 4 by adding this as well.
