### ISSUE TITLE
Tree-shaking of unused classes is broken

### ISSUE THREAD

**Issue by weaintplastic** [rollup/rollup#4808]
### Rollup Version

2.52.8 and up (including v3)

### Operating System (or Browser)

Mac OS

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-nlhtgx?file=src/main.js

### Expected Behaviour

I've expected unused classes, regardless if they are extending from and external module, an internal module or not extending at all, to be removed from the final bundle as part of the tree-shaking process.

### Actual Behaviour

Unused classes that do extend from external modules are bundled starting with Rollup version 2.52.8 even though the external package is free from sideEffects and has `sideEffects: false` defined in their package.json.

I don't fully understand the related code that was published with version 2.52.8, but I hope you can point me in the right direction to understand the root cause of this and how I might be able to rewrite code in order to enable tree-shaking of a newer generation to deal with those type of classes better.

For context: We are maintaining a design system library with web components based on [stencil](https://stenciljs.com/). The issue was raised by one of our consumers who have noticed that their bundle almost doubled in size after upgrading Rollup. After investigating we've identified the class definitions – like the one in my example – to be problematic. Unfortunately, that's compiler output. But once we understand the problem we might be able to file an issue with the Stencil maintainers.

**Comment by weaintplastic** [comment]
Good morning. Is there anything I can do in order to help this ticket being triaged? I'm more than happy to provide more or other examples to reproduce the issue.

**Comment by TrickyPi** [comment]
The unexpected result cuased by `@rollup/plugin-node-resolve` plugin.

**Comment by rburgst** [comment]
any news on this, having the same issue!

**Comment by lukastaegert** [comment]
I had a look and found the underlying cause. Will post a fix in the next days.

**Comment by lukastaegert** [comment]
Fix at #4866

**Comment by weaintplastic** [comment]
@lukastaegert thanks so much for the fix. I've updated my reproduction example with the new version and can confirm that it is working as expected: https://stackblitz.com/edit/rollup-repro-nlhtgx?file=package.json,dist-rollup3171%2Fmain.js
