### ISSUE TITLE
import {a, b} from 'foo' doesn't work with commonjs modules

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup#481]
Sorry if this has already been covered, but I couldn't find a report of this exact problem...

Here's an example (I'm using rollup's npm and commonjs plugins):

```js
import {red, yellow} from 'chalk';
```

The chalk module does it's exporting [like this](https://github.com/chalk/chalk/blob/308f6b6a1eb4bb217fe873ee81a56237c1231b06/index.js#L97): `module.exports = new Chalk();`

I guess the problem is the commonjs plugin can't see the named 'exports' like `module.exports.red`, `module.exports.yellow` because there's no way to statically see those property names.

Would it be possible for the commonjs plugin to detect this case, and modify my code to something like this:

```js
import _ref from 'chalk';
var red = _ref.red;
var yellow = _ref.yellow;
```

...or is my code fundamentally incorrect in trying to `import {x, y}` from a non-ES6 module? (I've assumed it's 'ok' because babel's es2015-to-commonjs transform makes this kind of thing work.)

**Comment by eventualbuddha** [comment]
rollup is fairly strict about named imports when it bundles a module. You could simply leave it as an external module if you'd like to use the looser semantics. Otherwise you probably want something like this:

```js
import chalk from 'chalk';
const { red, yellow } = chalk;
```

**Comment by callumlocke** [comment]
So is it outside the scope of the commonjs plugin to make this work automatically?

**Comment by Rich-Harris** [comment]
There's no way to make it work automatically, but there is a (secret! should probably document it...) feature in rollup-plugin-commonjs:

```js
rollup.rollup({
  /* ... */,
  plugins: [
    npm({ main: true }),
    commonjs({
      namedExports: {
        chalk: [ 'red', 'yellow' ]
      }
    })
  ]
}).then(...)
```

Having said that, it's probably easier in this case to use a namespace import – that's how I use chalk:

```js
import * as chalk from 'chalk';
```

**Comment by callumlocke** [comment]
nice! i'll close this one then
