### ISSUE TITLE
self reference in static block is not working well on rename

### ISSUE THREAD

**Issue by nicolashenry** [rollup/rollup#4811]
### Rollup Version

3.10.0

### Operating System (or Browser)

Chrome

### Link To Reproduction

https://rollupjs.org/repl/?version=3.10.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMFRlc3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZ0ZXN0MS5qcyclM0IlNUNuaW1wb3J0JTIwJTdCJTIwVGVzdCUyMGFzJTIwVGVzdDIlMjAlN0QlMjBmcm9tJTIwJy4lMkZ0ZXN0Mi5qcyclM0IlNUNuY29uc29sZS5sb2coVGVzdC50ZXN0JTJDJTIwVGVzdDIudGVzdCklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0MS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlNUNuZXhwb3J0JTIwY2xhc3MlMjBUZXN0JTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMHRlc3QlMjAlM0QlMjAnVGVzdDEnJTNCJTVDbiUyMCUyMHN0YXRpYyUyMCU3QiUyMGNvbnNvbGUubG9nKFRlc3QudGVzdCklM0IlMjAlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRlc3QyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25leHBvcnQlMjBjbGFzcyUyMFRlc3QlMjAlN0IlNUNuJTIwJTIwc3RhdGljJTIwdGVzdCUyMCUzRCUyMCdUZXN0MiclM0IlNUNuJTIwJTIwc3RhdGljJTIwJTdCJTIwY29uc29sZS5sb2coVGVzdC50ZXN0KSUzQiUyMCU3RCU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behaviour

When running, it should give the following in console.

```
Test1
Test2
Test1 Test2
```

### Actual Behaviour

Currently it give an error:
```
VM93:3 Uncaught ReferenceError: Test$1 is not defined
    at <static_initializer> (<anonymous>:3:24)
    at <anonymous>:1:14
```

**Comment by TrickyPi** [comment]
@lukastaegert I'm wondering if this is a right way to solve this problem, using the class name instead of `renderName` in the static block, like in the following code.
```js
let Test$1 = class Test {
  static test = 'Test1';
  static { console.log(Test.test); }
};
```

**Comment by lukastaegert** [comment]
Yes, I think that should work.

**Comment by nicolashenry** [comment]
I realized that keeping name on static block is maybe not enough, it should probably be kept on non-static block also. For [example ](https://rollupjs.org/repl/?version=3.10.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGKiUyMFRSRUUtU0hBS0lORyUyMColMkYlNUNuaW1wb3J0JTIwJTdCJTIwVGVzdCUyMCU3RCUyMGZyb20lMjAnLiUyRnRlc3QxLmpzJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBUZXN0JTIwYXMlMjBUZXN0MiUyMCU3RCUyMGZyb20lMjAnLiUyRnRlc3QyLmpzJyUzQiU1Q25jb25zb2xlLmxvZyhUZXN0LnRlc3QlMkMlMjBUZXN0Mi50ZXN0KSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRlc3QxLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25leHBvcnQlMjBjbGFzcyUyMFRlc3QlMjAlN0IlNUNuJTIwJTIwY29uc3RydWN0b3IoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZyhUZXN0LnRlc3QpJTNCJTVDbiUyMCUyMCU3RCU1Q24lMjAlMjBzdGF0aWMlMjB0ZXN0JTIwJTNEJTIwJ1Rlc3QxJyUzQiU1Q24lMjAlMjBzdGF0aWMlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coVGVzdC50ZXN0KSUzQiU1Q24lMjAlMjAlMjAlMjBuZXclMjBUZXN0KCklM0IlNUNuJTIwJTIwJTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0Mi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlNUNuZXhwb3J0JTIwY2xhc3MlMjBUZXN0JTIwJTdCJTVDbiUyMCUyMGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coVGVzdC50ZXN0KSUzQiU1Q24lMjAlMjAlN0QlNUNuJTIwJTIwc3RhdGljJTIwdGVzdCUyMCUzRCUyMCdUZXN0MiclM0IlNUNuJTIwJTIwc3RhdGljJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKFRlc3QudGVzdCklM0IlNUNuJTIwJTIwJTIwJTIwbmV3JTIwVGVzdCgpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE) would give this as a result if the fix is done only on static block (so an error would be raised): 
```ts
let Test$1 = class Test {
  constructor() {
    console.log(Test$1.test);
  }
  static test = 'Test1';
  static {
    console.log(Test.test);
    new Test();
  }
};
```
The name should probably be also be kept everywhere inside the class:
```ts
let Test$1 = class Test {
  constructor() {
    console.log(Test.test);
  }
  static test = 'Test1';
  static {
    console.log(Test.test);
    new Test();
  }
};
```
I am not sure that the PR is taking this into account.

**Comment by TrickyPi** [comment]
Oh, thanks! I didn't take this into account, I'll fix it later in the PR.
