### ISSUE TITLE
`this.parse` errors when using css import assertions

### ISSUE THREAD

**Issue by thepassle** [rollup/rollup#4813]
### Rollup Version

3.10.0

### Operating System (or Browser)

MacOS

### Node Version (if applicable)

18

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-fbdojc?file=package.json

### Expected Behaviour

Given the following source code:

```js
import styleSheet from './styles.css' assert { type: 'css' };

console.log(styleSheet);
```

Calling `this.parse` on this source code in a rollup plugin's `transform` hook does not error

### Actual Behaviour

`this.parse` gives the following error:
```
[!] (plugin at position 1) SyntaxError: Unexpected token (1:5)
```

**Comment by lukastaegert** [comment]
If you get a syntax error, then acorn does not support it and it needs to be fixed upstream at the corresponding plugin https://github.com/xtuc/acorn-import-assertions

**Comment by thepassle** [comment]
Thanks, I'll create an issue on the acorn plugin then :)

I thought the acorn plugin to support import assertions was added to rollup in v3 though, wasnt it?

**Comment by lukastaegert** [comment]
Sure, but we do not maintain the plugin.
