### ISSUE TITLE
line-height: 1.5 your website

### ISSUE THREAD

**Issue by corysimmons** [rollup/rollup#482]
![image](https://cloud.githubusercontent.com/assets/224636/12700193/73675610-c7a6-11e5-9949-cf847e53b905.png)

This is entirely too little line-height. :dancers:

**Comment by corysimmons** [comment]
Also, what's with the `http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20cube%20%7D%20from%20'.%2Fmaths.js'%3B%5Cnconsole.log(%20cube(%205%20)%20)%3B%20%2F%2F%20125%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22%2F%2F%20This%20function%20isn't%20used%20anywhere%2C%20so%5Cn%2F%2F%20Rollup%20excludes%20it%20from%20the%20bundle...%5Cnexport%20function%20square%20(%20x%20)%20%7B%5Cn%5Ctreturn%20x%20*%20x%3B%5Cn%7D%5Cn%5Cn%2F%2F%20This%20function%20gets%20included%5Cnexport%20function%20cube%20(%20x%20)%20%7B%5Cn%5Ct%2F%2F%20rewrite%20this%20as%20%60square(%20x%20)%20*%20x%60%5Cn%5Ct%2F%2F%20and%20see%20what%20happens!%5Cn%5Ctreturn%20x%20*%20x%20*%20x%3B%5Cn%7D%22%7D%5D%7D` URL?

**Comment by callumlocke** [comment]
The URL is so you can share links to rollup examples

**Comment by Rich-Harris** [comment]
Yeah, it is a little tight! Thanks for pointing it out. 1.5 would be *waaaay* too much in that context though – I've gone for 1.2 :grinning:

**Comment by corysimmons** [comment]
I disagree with the "_waaaay_" sentiment but 1.2 is better than nothing. Splittin' hairs. :)
