### ISSUE TITLE
Add search box to docs

### ISSUE THREAD

**Issue by sapphi-red** [rollup/rollup#4821]
### Documentation is

- [ ] Missing
- [X] Needed
- [ ] Confusing
- [ ] Not sure?

### Please Explain in Detail...

The search box really helps me find what I want to know.

### Your Proposal for Changes

Add Algolia DocSearch integration that is builtin to Vitepress or alternatives.
https://vitepress.vuejs.org/guide/theme-search#search

**Comment by lukastaegert** [comment]
Definitely a welcome addition, did not find time to look into this, though.

**Comment by sapphi-red** [comment]
Thank you!
