### ISSUE TITLE
Feature request: set source code array with filepaths

### ISSUE THREAD

**Issue by Alphapage** [rollup/rollup#483]
Hello,

I think it is not possible to set an array of source code + filepath instead of letting rollup.js reads the files.
So, if the array is set in config, then rollup.js will search the source code in the array first, else it will try to load from file.
```
var rollup = require( 'rollup' );

rollup.rollup({
  // The bundle's starting point. This file will be
  // included, along with the minimum necessary code
  // from its dependencies
  entry: 'main.js',
  sources : [ { sourceCode : "import Test from './Test'", filePath: "./main.js" },
                    { sourceCode : "export default class Test {}", filePath: "./Test.js" } ]
}).then( function ( bundle ) {
  // Generate bundle + sourcemap
  var result = bundle.generate({
    // output format - 'amd', 'cjs', 'es6', 'iife', 'umd'
    format: 'cjs'
  });

  fs.writeFileSync( 'bundle.js', result.code );

  // Alternatively, let Rollup do it for you
  // (this returns a promise). This is much
  // easier if you're generating a sourcemap
  bundle.write({
    format: 'cjs',
    dest: 'bundle.js'
  });
});
```

Do you think my request is admissible ?

Thanks in advance for your answers.

**Comment by Rich-Harris** [comment]
This could easily be achieved with a [plugin](https://github.com/rollup/rollup/wiki/Plugins) – it would work something like this:

```js
var source = require( 'rollup-plugin-source' ); // does not exist yet!

rollup.rollup({
  entry: 'src/main.js',
  plugins: [
    source({
      'src/main.js': "import Test from './Test.js'",
      'src/Test.js': "export default class Test {}"
    })
  ]
}).then(...)
```

I think that'd be a sensible plugin for us to have. There's no need to have it in core (plugins are designed for exactly this purpose) but I'll leave this issue open as a reminder that we need to create that plugin.

**Comment by Alphapage** [comment]
I'm glad you are interested in such a feature :-)

**Comment by callumlocke** [comment]
:+1: want this too, might make it

**Comment by callumlocke** [comment]
Thinking about it, for my use case, a custom lookup function would be more flexible:

```js
var source = require( 'rollup-plugin-source' ); // does not exist yet!

rollup.rollup({
  entry: 'src/main.js',
  plugins: [
    source((modulePath) => {
      // look up modulePath somewhere and return/promise the contents...
    })
  ]
}).then(...)
```

I guess the plugin could accept either an object or a function?

**Comment by Rich-Harris** [comment]
@callumlocke I like that idea. There's precedent – the `globals` object can be provided as an object or a function: [getGlobalNameMaker.js](https://github.com/rollup/rollup/blob/d8542b6f942a1dfdef9c9738e9771c970efe29b9/src/finalisers/shared/getGlobalNameMaker.js#L2)

**Comment by Victorystick** [comment]
Closing as this can be implemented using a plugin.
