### ISSUE TITLE
This has two plugins A, B, both executed in the closeBundle phase. I want to execute B after A is executed. Can I do it

### ISSUE THREAD

**Issue by Dengzygx** [rollup/rollup#4836]
This has two plugins A, B, both executed in the closeBundle phase. I want to execute B after A is executed. Can I do it

**Comment by lukastaegert** [comment]
If you think there is a bug, please use the issue template and post a link to a reproduction. If this is a support request, you should probably post it to something like [StackOverflow](https://stackoverflow.com/questions/tagged/rollupjs) instead.
