### ISSUE TITLE
Fails with `export {}`

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#486]
Via https://github.com/rollup/rollup-plugin-babel/issues/37

**Comment by Pauan** [comment]
In my opinion, I'm fine with Rollup not allowing `export {}`

However, it should fail with a descriptive error such as `Empty export is not allowed`

**Comment by Rich-Harris** [comment]
Have opened #498. I don't think it should fail, since it's not disallowed by the spec and Acorn parses it just fine. But it is probably worth a warning, since it'd be hard to understand what was causing https://github.com/rollup/rollup-plugin-babel/issues/37 otherwise
