### ISSUE TITLE
react error process is not defined

### ISSUE THREAD

**Issue by jonathandion** [rollup/rollup#487]
Hi guys,

Rollup bundle my file without errors but I have a react error "**Uncaught ReferenceError: process is not defined**" 

There is my rollup config :
`babel({
      exclude: 'node_modules/**',
      presets: ["es2015-rollup", "react"],
      plugins: ["syntax-jsx"]
}),`

and my package.json :

` {
    "babel-plugin-syntax-jsx": "^6.3.13",
    "babel-preset-es2015-rollup": "^1.1.1",
    "babel-preset-react": "^6.3.13",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-redux": "^4.1.2",
    "rollup-plugin-babel": "^2.3.9",
    "rollup-plugin-commonjs": "^2.2.0",
    "rollup-plugin-npm": "^1.3.0"
  }`

Any issues ?

Thanks !

**Comment by Rich-Harris** [comment]
This happens because React uses `process.env` to determine whether you're in a development or production environment. From [getting-started.md](https://github.com/facebook/react/blob/f7850dd3d78d313a9e7774870e85c32719fbe233/docs/docs/getting-started.md):

---

**Note:** by default, React will be in development mode, which is slower, and not advised for production. To use React in production mode, set the environment variable `NODE_ENV` to `production` (using envify or webpack's DefinePlugin). For example:

```js
new webpack.DefinePlugin({
  "process.env": {
    NODE_ENV: JSON.stringify("production")
  }
});
```

---

So to build it with Rollup, you need to replace `process.env.NODE_ENV` with either `"development"` or `"production"` – you can use [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) for this:

```js
rollup({
  entry: 'main.js',
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    })
  ]
}).then(...)
```

**Comment by jonathandion** [comment]
Thanks Rich for the reply it's working now. Now I have an issue with redux... well.

**Comment by dsblv** [comment]
I've just faced the same issue and I think there has to be the plugin that will automagically smoothen all the frictions of `node`→`browser` transition. Kind of like [browserify does](https://github.com/substack/insert-module-globals).

I think I'm able to implement this, but maybe someone already did it? Seems like the problem can be a dealbraker for many people.

**Comment by salztorte** [comment]
@jonathandion i had problems with redux to. Here is one [Solution](https://github.com/rollup/rollup/issues/281#issuecomment-180397344)

**Comment by TrySound** [comment]
rollup-plugin-replace works pretty well. Think could be closed.

**Comment by mbrevda** [comment]
another option for those having issues with rollup-plugin-replace is the [Babel transform](https://babeljs.io/docs/plugins/transform-inline-environment-variables/)

**Comment by Guria** [comment]
`rollup-plugin-replace` works not as expected for providing `env`. it only replaces exact strings and wouldn't work with `process.env['NODE_ENV']`. Has anyone met `webpack-define-plugin` analog for rollup?

**Comment by lukastaegert** [comment]
Should not be too difficult to write. Here is a simple add-hoc plugin that handles all accessed to `process` gracefully and will even optimize `process.env['NODE_ENV']`. Feel free to just put this into your rollup config as suggested here or refine it and release it as a proper plugin:

```js
// rollup.config.js
// The virtual id for our shared "process" mock. We prefix it with \0 so that other plugins ignore it
const INJECT_PROCESS_MODULE_ID = '\0inject-process';

export default ({
  // ...
  plugins: [
    // ...
    {
      name: 'inject-process-plugin',
      resolveId(id) {
        // this tells Rollup not to try to resolve imports from our virtual id
        if (id === INJECT_PROCESS_MODULE_ID) {
          return INJECT_PROCESS_MODULE_ID;
        }
      },
      load(id) {
        if (id === INJECT_PROCESS_MODULE_ID) {
          // All fields of 'process' we want to mock are top level exports of the module.
          // For now I hardcoded "NODE_ENV" but you probably want to put more logic here.
          return `export const env = {NODE_ENV: 'production'};\n`
        }
      },
      transform(code, id) {
        // Each module except our virtual module gets the process mock injected.
        // Tree-shaking will make sure the import is removed from most modules later.
        // This will produce invalid code if a module defines a top-level "process" variable, so beware!
        if (id !== INJECT_PROCESS_MODULE_ID) {
          return `import * as process from '${INJECT_PROCESS_MODULE_ID}';\n${code}`;
        }
      }
    }
  ]
});
```

**Comment by Guria** [comment]
@lukastaegert works like a charm, though now I have a warning in console:
```
(!) Broken sourcemap
https://rollupjs.org/guide/en#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as 'inject-process-plugin') should generate accompanying sourcemaps
```

**Comment by lukastaegert** [comment]
Ah yes, that is to be expected. A "proper" plugin would need to take care of sourcemaps as well. The way most rollup plugins do that is by installing Rich-Harris' https://github.com/rich-harris/magic-string package and use it to do the code transformation. I cannot check right now if this works but this is what *should*  work:

```js
// rollup.config.js
import MagicString from 'magic-string';

// ...
export default ({
  // ...
  plugins: [
    // ...
    {
      name: 'inject-process-plugin',
      // ...
      transform(code, id) {
        if (id !== INJECT_PROCESS_MODULE_ID) {
          const magicString = new MagicString(code);
          magicString.prepend(`import * as process from '${INJECT_PROCESS_MODULE_ID}';\n`);
          return {code: magicString.toString(), map: magicString.generateMap()};
        }
      }
    }
  ]
});
```

**Comment by Guria** [comment]
Fixed it with `magicString.generateMap({ highres: true })`

**Comment by Guria** [comment]
So final solution is:

```
import MagicString from 'magic-string';

// The virtual id for our shared "process" mock. We prefix it with \0 so that other plugins ignore it
const INJECT_PROCESS_MODULE_ID = '\0inject-process';

export default () => ({
  name: 'inject-process-plugin',
  resolveId(id) {
    // this tells Rollup not to try to resolve imports from our virtual id
    if (id === INJECT_PROCESS_MODULE_ID) {
      return INJECT_PROCESS_MODULE_ID;
    }
  },
  load(id) {
    if (id === INJECT_PROCESS_MODULE_ID) {
      // All fields of 'process' we want to mock are top level exports of the module.
      // For now I hardcoded "NODE_ENV" but you probably want to put more logic here.
      return `export const env = ${JSON.stringify(env)};\n`;
    }
  },
  transform(code, id) {
    // Each module except our virtual module gets the process mock injected.
    // Tree-shaking will make sure the import is removed from most modules later.
    // This will produce invalid code if a module defines a top-level "process" variable, so beware!
    if (id !== INJECT_PROCESS_MODULE_ID) {
      const magicString = new MagicString(code);
      magicString.prepend(`import * as process from '${INJECT_PROCESS_MODULE_ID}';\n`);
      return { code: magicString.toString(), map: magicString.generateMap({ hires: true }) };
    }
  }
});
```

Thanks @lukastaegert

**Comment by seivan** [comment]
Sorry for waking an old thread, but I just want to point out that although the approach mentioned [here](https://github.com/rollup/rollup/issues/487#issuecomment-486229172) will only work to some degree. It will still leave behind "a lot" (around 2kb for both `React` & `React-Dom`) of development code

I actually had better results with jsut using 
`'process.env.NODE_ENV': JSON.stringify('production')`

But from what I understand it wouldn't work in areas where the `NODE_ENV` is checked with key look up. 
Can't we just add these? 

`'process.env.NODE_ENV': JSON.stringify('production')`
`'process.env.['NODE_ENV']': JSON.stringify('production')`
`'process.env.["NODE_ENV"]': JSON.stringify('production')`

It sure is a hack, but not sure it's that far away from magic string replacements :)?

**Comment by TrySound** [comment]
> But more specifically, why can't we somehow just do like this before running the whole thing?

You can but the point of static analysis is to get rid from dead code in production for example so we could get smaller bundle.

**Comment by easoncxz** [comment]
I came across this exact issue, for the same exact reason, but found a different solution (from doing string-replacements in the style of `@rollup/plugin-replace`).

Inspired by a similar Github issue:

- https://github.com/rollup/rollup-plugin-commonjs/issues/183#issuecomment-287046393

I tried "bringing out the big guns" and do a Browserify-style inject of all nodejs machinery into the bundle for the browser, by using one or both of these two Rollup plugins:

- https://github.com/calvinmetcalf/rollup-plugin-node-globals (probably the more necessary and relevant one for this thread)
- https://github.com/calvinmetcalf/rollup-plugin-node-builtins

It did solve my issue, and my little React app does appear to run in my browser via my Rollup-produced bundle. (I was using jspm beforehand, without any bundling.)

As I'm working on a project where my goal is just to learn things, instead of having particular production shipping/performance/size requirements, I don't mind my bundles (esp. just development bundles) being kind of huge, and I find this conceptually simpler and less hacky. Maybe this alternative approach could be helpful for somebody.

**Comment by amannm** [comment]
I went with this solution: **https://github.com/rollup/rollup/issues/487#issuecomment-486229172** to get my react build working with rollup. Wish this didn't have to live in my config...

**Comment by TrySound** [comment]
@amannm 
I build my react app with rollup. This is enough.
```
        replace({
            'process.env.NODE_ENV': JSON.stringify('production'),
        }),
```

**Comment by adjenks** [comment]
I don't understand why people aren't suggesting to put the actual variable in there like this:
```
        replace({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
        }),
```
It works fine for me. Is there a reason why people are hard-coding the mode?

**Comment by TrySound** [comment]
@adjenks Because it does not always need to be changed. I use rollup only for production build. Hardcoded value is enough for me.

**Comment by jeremybradbury** [comment]
I think this was prematurely closed.

I tried all of the things in https://github.com/rollup/rollup/issues/487 and they don't work for Svelte.

process is always undefined even when using the replace methods.

You may assume this is an old issue, but I think it's a new one without a universal workaround.

as of now I have no way to pass any env variables to my Svelte app during the build.

**Comment by victornpb** [comment]
I was facing a similar issue, but I didn't want to use the replace plugin, I wanted something more strict and explicit.
So I created this plugin https://github.com/victornpb/rollup-plugin-baked-env

The way it works is, you import the environment variable you need
```js
import { NODE_ENV, FOO, BAR } from 'process.env';

console.log(FOO, BAR);
if (NODE_ENV === 'production') {
    // code
}
```

The content of the variable will be baked inside your bundle. 
And you get the benefit that you get compile errors if your code reference variables that doesn't exist.

**Comment by muhamadzolfaghari** [comment]
I'm writing a code snippet that retrieves environment variables from `.env ` files, which will be used with the rollup-plugin-replace plugin.

Since the plugin doesn't support empty objects, we need to ensure that if any .env file is empty, an empty object ({}) won't be passed to the plugin.

May there are other ways such as meta `dotenv` pack to get pair key value from each file but I try to use another way.

```js
function getEnvRecord(prev, line) {
  const result = line.split("=");
  const key = `process.env.${result[0]}`;
  // try to stringfiy the value to avoid any errors
  return { ...prev, [key]: `"${result[1]}"` };
}

function getEnvFiles() {
  const envContents = {};
  // There are sample files for env you can use fs.readDir to get all possible 'env' files in the root directory
  const envFiles = ["env", "env.development", "env.production"];

  for (const file of envFiles) {
    const filePath = path.join(process.cwd(), `.${file}`);
    if (!fs.existsSync(filePath)) continue;
    const content = fs.readFileSync(filePath, "utf-8");
    // get env contents from each file and get key value of environment variables
    envContents[file] = content
      .split(/\r?\n/)
      .map((line) => line.trim())
      .reduce(getEnvRecord, {});
  }

  return envContents;
}

function getEnvReplacer() {
  const envContents = getEnvFiles();
  const env = process.env.NODE_ENV;
  if (!env || env === "development") return envContents["env.development"];
  if (env === "production") return envContents["env.production"];
  return envContents["env"];
}
```

After that we can pass `getEnvReplacer` to replace.

```js
import replace from "rollup-plugin-replace";

const rollupConfig = [
  {
    plugins: [
      replace({ /* other replacers, */ ...getEnvReplacer() }),
    ],
  }
];
```
