### ISSUE TITLE
Wiki request: add new plugin guideline

### ISSUE THREAD

**Issue by TehShrike** [rollup/rollup#488]
A lot of build tools don't prioritize sourcemaps, and it becomes obvious when you try to use them for much.  From the [Plugins](https://github.com/rollup/rollup/wiki/Plugins) wiki page it looks like Rollup gives them first-class support.

I suggest that another point be added to the [plugin guidelines wiki page](https://github.com/rollup/rollup/wiki/Rollup-Plugin-Guidelines): "**make sure your plugin outputs correct source mappings if appropriate**".

**Comment by TrySound** [comment]
Added https://github.com/rollup/rollup/wiki/Plugins#conventions
