### ISSUE TITLE
Rollup failed to resolve import "NonExistingPath" from ...

### ISSUE THREAD

**Issue by Nefcanto** [rollup/rollup#4893]
### Rollup Version

3.18.0

### Operating System (or Browser)

Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)

### Link To Reproduction

https://github.com/Nefcanto/ViteRollUpTryCatch

## Things inside `try/catch` should not break the build.

I'm using `try/catch` to import a component.

This component might exist or might not exist in the specified path.

It works in the development environment. But when I want to build it, the `try/catch` is not respected.

```

    let dynamicComponent = null
    try {
        import('NonExistingPath')
            .then(x => dynamicComponent = x)
            .catch(error => console.log(error))
    } catch (error) {
        console.log(error)
    }

```

### Actual Behaviour

I can't build my project. Rollup breaks the build because I have a dynamic import in a `try/catch` from a path that does not exist.

Steps to reproduce
- Clone
- `npm run dev`
- Home page can be seen
- `npm run build`
- Build fails

**Comment by lukastaegert** [comment]
There is a list of noise around Rollup in your setup, and maybe there is an issue in one of your plugins as well. But usually in a situation as yours, you should add `NonExistingPath` to the `external` option https://rollupjs.org/configuration-options/#external

**Comment by lukastaegert** [comment]
Small tip: The try-catch will not catch a failed import unless you await the import.

**Comment by lukastaegert** [comment]
Otherwise, Rollup has no issues with this except possibly a warning about the import https://rollupjs.org/repl/?version=3.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmxldCUyMGR5bmFtaWNDb21wb25lbnQlMjAlM0QlMjBudWxsJTVDbiUyMCUyMCUyMCUyMHRyeSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpbXBvcnQoJ05vbkV4aXN0aW5nUGF0aCcpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMC50aGVuKHglMjAlM0QlM0UlMjBkeW5hbWljQ29tcG9uZW50JTIwJTNEJTIweCklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwLmNhdGNoKGVycm9yJTIwJTNEJTNFJTIwY29uc29sZS5sb2coZXJyb3IpKSU1Q24lMjAlMjAlMjAlMjAlN0QlMjBjYXRjaCUyMChlcnJvciklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coZXJyb3IpJTVDbiUyMCUyMCUyMCUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlN0QlN0Q=

**Comment by Nefcanto** [comment]
> Small tip: The try-catch will not catch a failed import unless you await the import.

@lukastaegert, Thank you. Weired tip. Is this a JavaScript thing? I didn't know that. Or is it a Rollup thing?

**Comment by lukastaegert** [comment]
It is JavaScript. A try catch can only catch “synchronous” errors unless it is an async function and the error is awaited.

**Comment by Nefcanto** [comment]
@lukastaegert if it's a JS thing, then how does it work in my dev mode? Why does it break for prod only?

**Comment by Tanimodori** [comment]
> @lukastaegert if it's a JS thing, then how does it work in my dev mode? Why does it break for prod only?

The dev mode doesn't work neither. Vite failed to resolve this dependency. It just catches the error and keeps the server running. Rollup just throws the error.

```bash
Error: Cannot find module 'NonExistingPath' imported from 'D:/__TEMP__/ViteRollUpTryCatch/src/routes/index.tsx'
    at nodeImport (file:///D:/__TEMP__/ViteRollUpTryCatch/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52451:25)
    at ssrImport (file:///D:/__TEMP__/ViteRollUpTryCatch/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52374:20)
    at ssrDynamicImport (file:///D:/__TEMP__/ViteRollUpTryCatch/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52401:16)
    (omitted)
    at async Proxy.renderToStream (file:///D:/__TEMP__/ViteRollUpTryCatch/node_modules/@builder.io/qwik/server.mjs:575:3)
    at async D:\__TEMP__\ViteRollUpTryCatch\node_modules\@builder.io\qwik\optimizer.cjs:1846:28 {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by Tanimodori** [comment]
Note that the timing of dependency resolvent and actual import of client is different.

| import statement     | external | resolvent    | actual import | when error           | catchable   |
|----------------------|----------|--------------|---------------|----------------------|-------------|
| `import 'nonExist'`  | false    | compile-time | sync import   | compile-time error   | tool-varied |
| `import('nonExist')` | false    | compile-time | async import  | compile-time error   | tool-varied |
| `import 'nonExist'`  | true     | runtime      | sync import   | runtime import error | no          |
| `import('nonExist')` | true     | runtime      | async import  | runtime import error | yes         |

**Comment by Nefcanto** [comment]
@Tanimodori thank you for the explanation. How identical code can be `external` and also `internal`? Can you please clarify what you mean by external?

I added the `NonExistingPath` to my rollup configuration and it worked. But I still don't know the true meaning of external. It's all my code, thus why some of it should be called internal and some external?

**Comment by Tanimodori** [comment]
The essence of `import` is to find the corresponding module with given module name. There are two major questions here:

### Who should take the responsibility of finding the actual module? 

This step is often call *module resolution*. 

* If the bundler (e.g. `rollup`) should do the job, the dependency module is resolved *internally*. For example, your project code (`./foo.js`), lib modules (`lodash`), virtual modules by bundler plugin (`virtual:windi.css`) are internal. The module must exist on compile time or the bundler wouldn't be able to link/generate the actual code for it.
* If the client (e.g. browsers, `node`, `electron`) should do the job, the dependency module is resolved *externally*. For example, remote modules powered by CDN (like `unpkg`) are external. The bundler should do nothing on external modules and leave the resolution job to the client.

How a module should be resolved internally or externally is determined in bundler's config (for rollup, it is [external](https://rollupjs.org/configuration-options/#external)). It is just based on your config and the module name, not the import statement type.

**Comment by Nefcanto** [comment]
Very clear and informative. Thank you so much @Tanimodori.
