### ISSUE TITLE
Treeshaking breaks static blocks in some cases

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup#4895]
### Rollup Version

3.18.0

### Operating System (or Browser)

linux x64

### Link To Reproduction

https://rollupjs.org/repl/?version=3.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwc3ltYm9sSXRlcmF0b3IoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjB0aGlzLl9yZXN1bHRzJTVCU3ltYm9sLml0ZXJhdG9yJTVEKCklM0IlNUNuJTdEJTVDbmV4cG9ydCUyMGNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHN0YXRpYyUyMCU3QiUyMFN5bWJvbC5pdGVyYXRvciUzQiUyMCU3RCU1Q24lMjAlMjAlMjAlMjBjb25zdHJ1Y3RvcigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRoaXMuX3Jlc3VsdHMlMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY29uc3QlMjBwcm90byUyMCUzRCUyMEZvby5wcm90b3R5cGUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoIXByb3RvJTVCU3ltYm9sLml0ZXJhdG9yJTVEKSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBwcm90byU1QlN5bWJvbC5pdGVyYXRvciU1RCUyMCUzRCUyMHN5bWJvbEl0ZXJhdG9yJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

### Expected Behaviour

Treeshaking breaks static blocks in some cases.

The below input, will produce broken code

```ts
function symbolIterator() {
    return this._results[Symbol.iterator]();
}
export class Foo {
    static { Symbol.iterator; }
    constructor() {
        this._results = [];
        const proto = Foo.prototype;
        if (!proto[Symbol.iterator])
            proto[Symbol.iterator] = symbolIterator;
    }
}
```

### Actual Behaviour

```ts
function symbolIterator() {
    return this._results[Symbol.iterator]();
}
class Foo {
    s }
    constructor() {
        this._results = [];
        const proto = Foo.prototype;
        if (!proto[Symbol.iterator])
            proto[Symbol.iterator] = symbolIterator;
    }
}

export { Foo };

```

**Comment by TrickyPi** [comment]
The simplify REPL
https://rollupjs.org/repl/?version=3.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMCUyMHN0YXRpYyUyMCU3QiUyMDElMjAlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=

I took a look and found that the `findFirstLineBreakOutsideComment` returns a wrong location when the `static` code doesn't contain `/n`.
https://github.com/rollup/rollup/blob/de255540b9070fef6a37fcb711f4b913cd2ac319/src/utils/renderHelpers.ts#L104
So, if we change the code to the following
```js
...
  static {
    1}
...
```
https://rollupjs.org/repl/?version=3.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMCUyMHN0YXRpYyUyMCU3QiUyMCU1Q24lMjAlMjAlMjAlMjAlMjAxJTIwJTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE
Treeshaking will produce correct code.
