### ISSUE TITLE
how to preserve license or first comment in root file

### ISSUE THREAD

**Issue by caridy** [rollup/rollup#490]
I have noticed that `babelHelpers` definition is inserted at the very top of the file, is there a way to signal where to insert it, or at least re-insert a license notice at the top of the output while preserving the source map?

**Comment by Victorystick** [comment]
Sure thing! Rollup refers to anything outside of the actual bundle as the `banner` and `footer` respectively. You can specify either from the CLI with the `--banner` and `--footer` options.

```sh
rollup -i your-entry.js -o bundle.js --banner '/* MIT licence */'
```

Or in your `rollup.config.js` file
```js
export default {
	entry: 'your-entry.js',
	dest: 'bundle.js',
	banner: '/** MIT licence */'
};
```

**Comment by caridy** [comment]
that does the trick @Victorystick, thanks!
