### ISSUE TITLE
Non-deterministic asset file name when multiple asset has same content with a different name

### ISSUE THREAD

**Issue by sapphi-red** [rollup/rollup#4909]
### Rollup Version

3.19.1

### Operating System (or Browser)

stackblitz

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-dju2ff?file=rollup.config.js

### Expected Behaviour

When calling `this.emitFile` with a same content but with different filename, rollup dedupes that and only outputs a single asset.
But because rollup always uses the filename used in the first call, the asset file name is non-deterministic when `this.emitFile` is called in parallel.

For example, Vite outputs CSS files by `this.emitFile` and uses the chunk name as a file name of the CSS file. `renderChunk` is called in parallel and when there's multiple CSS files containing the same content, the build becomes non-deterministic.

I think it would be nice to fix this on rollup side as I guess this can happen by using rollup without Vite.

### Actual Behaviour

Rollup outputs assets with deterministic file names.

One possible solution is to sort all the file names and choose the first one.

Related: https://github.com/vitejs/vite/issues/11911, https://github.com/vitejs/vite/issues/12256

**Comment by sun0day** [comment]
I can give a try
