### ISSUE TITLE
Rollup's tree-shaking isn't applying to exported async functions

### ISSUE THREAD

**Issue by ericf** [rollup/rollup#492]
I have a `utils.js` module which exports multiple, named, async functions. When `importer.js` imports one of these async function exports, Rollup is including _all_ of them in the bundle. It seems that Rollup's tree-shaking algo is getting caught up with the async functions, when I removed the `async`/`await` keywords from the `utils.js` module, only the imported functions were included in the bundle, as expected. The way I worked around this was to put each function in its own module.

I'm using the latest versions of `rollup`, `rollup-plugin-babel`, `babel-preset-stage-3`, and `babel-regenerator-runtime`.

**Comment by Rich-Harris** [comment]
Interesting – can you provide a reproduction? Feeding the results from [the Babel REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&playground=false&code=async%20function%20foo%20()%20%7B%0A%20%20var%20foo%20%3D%20await%20somethingAsync('foo')%3B%0A%20%20return%20foo%3B%0A%7D%0Aasync%20function%20bar%20()%20%7B%0A%20%20var%20bar%20%3D%20await%20somethingAsync('bar')%3B%0A%20%20return%20bar%3B%0A%7D) into [rollupjs.org](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20foo%2C%20bar%20%7D%20from%20'.%2Futils.js'%3B%5Cn%5Cnfoo().then(%20%2F*...*%2F%20)%3B%22%7D%2C%7B%22name%22%3A%22utils.js%22%2C%22code%22%3A%22export%20function%20foo()%20%7B%5Cn%20%20var%20foo%3B%5Cn%20%20return%20regeneratorRuntime.async(function%20foo%24(context%241%240)%20%7B%5Cn%20%20%20%20while%20(1)%20switch%20(context%241%240.prev%20%3D%20context%241%240.next)%20%7B%5Cn%20%20%20%20%20%20case%200%3A%5Cn%20%20%20%20%20%20%20%20context%241%240.next%20%3D%202%3B%5Cn%20%20%20%20%20%20%20%20return%20regeneratorRuntime.awrap(somethingAsync('foo'))%3B%5Cn%5Cn%20%20%20%20%20%20case%202%3A%5Cn%20%20%20%20%20%20%20%20foo%20%3D%20context%241%240.sent%3B%5Cn%20%20%20%20%20%20%20%20return%20context%241%240.abrupt('return'%2C%20foo)%3B%5Cn%5Cn%20%20%20%20%20%20case%204%3A%5Cn%20%20%20%20%20%20case%20'end'%3A%5Cn%20%20%20%20%20%20%20%20return%20context%241%240.stop()%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%2C%20null%2C%20this)%3B%5Cn%7D%5Cnexport%20function%20bar()%20%7B%5Cn%20%20var%20bar%3B%5Cn%20%20return%20regeneratorRuntime.async(function%20bar%24(context%241%240)%20%7B%5Cn%20%20%20%20while%20(1)%20switch%20(context%241%240.prev%20%3D%20context%241%240.next)%20%7B%5Cn%20%20%20%20%20%20case%200%3A%5Cn%20%20%20%20%20%20%20%20context%241%240.next%20%3D%202%3B%5Cn%20%20%20%20%20%20%20%20return%20regeneratorRuntime.awrap(somethingAsync('bar'))%3B%5Cn%5Cn%20%20%20%20%20%20case%202%3A%5Cn%20%20%20%20%20%20%20%20bar%20%3D%20context%241%240.sent%3B%5Cn%20%20%20%20%20%20%20%20return%20context%241%240.abrupt('return'%2C%20bar)%3B%5Cn%5Cn%20%20%20%20%20%20case%204%3A%5Cn%20%20%20%20%20%20case%20'end'%3A%5Cn%20%20%20%20%20%20%20%20return%20context%241%240.stop()%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%2C%20null%2C%20this)%3B%5Cn%7D%22%7D%5D%7D) doesn't show the bug (perhaps I'm using async functions wrong? Haven't bothered with them yet...), so it's not clear what's happening.

**Comment by Rich-Harris** [comment]
Closed via #1173, by configuring Acorn to parse ES2017. Doesn't fix the fact that transpiled async functions are hard to treeshake, but facilitates an alternative (rollup, then transpile)
