### ISSUE TITLE
Multiple entries to generate static html files with pug and i18next language files support

### ISSUE THREAD

**Issue by payalord** [rollup/rollup#4923]
Hi, this is actually not just support issue/question(s), but maybe a bug too. I'll explain in the end of this description.
I'm using `vite`, but `vite` is using `rollup` to build, here is what I'm trying to accomplish with `pug`:
Rollup version used by Vite in my case: `3.18.0`

Pages:
```
src/pages/index.pug
src/pages/about/index.pug
```
Language files:
```
src/language/en.json
src/language/fr.json
```

I want to make rendered output like:
```
dist/en/index.html
dist/fr/index.html
dist/en/about/index.html
dist/fr/about/index.html
```

I ended up by generating entry points like this:
```
{
    'en/index.html': '[resolved dirname here]/src/pages/index.en.pug'
    ...
}
```

Then created a plugin, where `resolveId` and `load` properly extracting language from `id` filename and correcting it to proper filename without language. Then I'm reading the correct `pug` file in `load` and compiling pug into html with i18next and provided correct language and returning it back. Also by adding to the id extension `.html` I disabled rollup checking it as JS source code. Since it is just html. So per each language entry it will be correctly translated html now.

The output I've got so far is:
```
dist/src/pages/index.en.html
dist/src/pages/index.fr.html
dist/src/pages/about/index.en.html
dist/src/pages/about/index.fr.html
```

And messages in the terminal:
```
Generated an empty chunk: "en/index.html".
...
```

So my question is, first why it is generated empty chunks? And why output in dist in the wrong file/dir structure? While in the docs:
https://rollupjs.org/configuration-options/#input

> Note that it is possible when using the object form to put entry points into different sub-folders by adding a `/` to the name. The following will generate at least two entry chunks with the names `entry-a.js` and `entry-b/index.js`, i.e. the file `index.js` is placed in the folder `entry-b`

As it is said in docs here, by using `/` we can make it to create a sub-directory as needed. But nothing of this worked as expected --> `dist/en/index.html` no such output there. It's like completely ignored entry property keys and did it wrong by using instead path `src/pages...` to write in dist.

Thanks!

**Comment by Tanimodori** [comment]
I don't think rollup should be used to deal with html as it cannot understand it at all...

You can do it at vite's plugin level but I don't think it is rollup's responsibility for html things.

**Comment by payalord** [comment]
Thanks. Vite is using rollup at plugin level and just adding a couple of it's own modules/hooks. Overall vite's plugin is a rollup plugin about 90%. So probably if I'll ask same question at vite project, they will redirect here since rollup is processing/building in the end. But I'll try to ask there too.

**Comment by Tanimodori** [comment]
Could you please provide a minimum reproduction of your setup? It can help devs here to understand and debug the setup. You need a reproduction anyway when you submit this issue to vite.

**Comment by payalord** [comment]
@Tanimodori Sure, here is the link: https://stackblitz.com/edit/vitejs-vite-hmmxdq please in terminal press Ctrl+C to stop auto running Vite command and type `npm run build` manually to run the build proccess. When it will finish it check `dist` directory. In `vite.config.js` you can see we are passing rollupOptions to rollup, such as `input`, and in dist you can see how wrong it is generated the paths to the files. I expected the paths will be `en/index.html` for example. While it is not. Thank you.

**Comment by payalord** [comment]
@Tanimodori also to do not get confused. Entry point's value filename is like `index.en.pug` - `vite-plugin.pug` parsing a language out from it and creating a filename as `index.pug` and only then loading it right and passing content to pug to compile. (Since I don't know any other method to pass custom parameters for each entry point individually).

**Comment by payalord** [comment]
@Tanimodori Hi, yes. Thank you very much for your help. So you are using `buildStart`, `generateBundle` with `this.emit` to provide the files as assets. Since you are using `this.emit` file and providing source to it, will rollup check that source for `<script src="./src/main.js"></script>` and catch the link to `main.js` and compile it too as an asset?

**Comment by payalord** [comment]
@Tanimodori I already tested it, there is still couple problems. But no problem, thanks for the clue and good example. I'll try to find a fix for loading `.js` files myself from here. 😃👍

**Comment by Tanimodori** [comment]
@payalord The `index.html` and `src/main.js` are the default entry of a vite projects since I haven't overriden the `build.rollupOptions.input`. They are the same as any other vite project. The `src/main.js` here is treated as chunk which will be processed by rollup.

**Comment by payalord** [comment]
> @payalord So you are talking about inlining js files in `*.pug` files right?

Yeah, exactly.
Example pug code like (`src/pages/index.pug`):
```
p #{__('hello')
script(src=src/main.js)
```
Where `main.js` will be properly processed by vite/rollup.

> https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/html.ts and https://github.com/vituum/vite-plugin-pug may be helpful.

Thanks for references. 👍

**Comment by Tanimodori** [comment]
@payalord Please checkout https://stackblitz.com/edit/vite-pug-i18n-tss1hp

This setup still generates empty chunk warnings as normal vite project.

```
> npm run build

> vite-starter@0.0.0 build
> vite build

vite v4.2.1 building for production...
✓ 6 modules transformed.
Generated an empty chunk: "fr\test\index.html".
Generated an empty chunk: "en\test\index.html".
dist/fr/test/index.html       0.01 kB
dist/en/test/index.html       0.01 kB
dist/en/index.html            0.09 kB
dist/fr/index.html            0.09 kB
dist/assets/main-bf2ffe78.js  0.74 kB │ gzip: 0.42 kB
✓ built in 196ms
```

This is due to rollup couldn't found any js chunk of those html entries, a.k.a. those html files contains no scripts. Those warnings are safe to ignore.
