### ISSUE TITLE
Why isn't the packaged product import statement at the top

### ISSUE THREAD

**Issue by gezhicui** [rollup/rollup#4927]
config:
![image](https://user-images.githubusercontent.com/50941611/229670117-b1933f8a-52c7-4500-91fc-5df1177ec117.png)

result:
![image](https://user-images.githubusercontent.com/50941611/229670193-5ca23eaa-784b-4bbc-867f-71cc4f5fbefc.png)

**Comment by Tanimodori** [comment]
Those function above are rollup helpers for maintaining correct runtime behavior.

If you move the sync imports before those helpers, the code behaves identically as before. The sync import modules will be always executed before the module body in the order of where they are in the code. Ref: https://stackoverflow.com/questions/35551366/what-is-the-defined-execution-order-of-es6-imports
