### ISSUE TITLE
export to multiple globals without moduleName (IIFE) 

### ISSUE THREAD

**Issue by thisconnect** [rollup/rollup#494]
Hi, would this be something that rollup could support:
- export multiple globals and not specify a moduleName using IIFE. 

``` javascript
import redux from 'redux';
import inferno from 'inferno';
import infernoDOM from 'inferno-dom';
import otherLib from 'otherLib';

export default { redux, inferno, infernoDOM };
```

I can be done manually, but feels wrong:

``` javascript
import redux from 'redux';
import inferno from 'inferno';
import infernoDOM from 'inferno-dom';
import otherLib from 'otherLib';

// oh noe
window.redux = redux;
window.inferno = inferno;
window.infernoDOM = infernoDOM;
window.otherLib = otherLib;

export default { redux, inferno, infernoDOM };
```

followup question:
if redux and otherLib both use the same lodash module+version is this shared in such a build?

**Comment by Rich-Harris** [comment]
Yeah, I can see the value of that. Would presumably apply to UMD as well. Perhaps with an option like `multipleGlobals` (thoughts?). It would work with named exports rather than defaults, like so:

```js
export { redux, inferno, infernoDOM };
```

The `moduleName` option would continue to apply if there was also a default export.

> if redux and otherLib both use the same lodash module+version is this shared in such a build?

With rollup-plugin-npm (soon [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-npm/issues/20)), Rollup simply follows the Node resolution algorithm – so the answer depends on whether lodash is deduplicated. By default, it *will* be deduped with npm3, and won't with npm2. If you need to exert finer control than that, you can do so by [supplying your own plugin](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins) with a `resolveId` function.

**Comment by thisconnect** [comment]
Sorry for my slow reply. Thanks for the clarification about deduped modules that is perfect!

> The `moduleName` option would continue to apply if there was also a default export.

Yes that makes sense. So with `multipleGlobals ` and `moduleName: 'myLib'`something like this 
```javascript
const foo = 2;
export const bar = 1; // window.bar == 1 ?
export default foo; // myLib == 2 ?
```

I am not 100% how this example behaves currently, with IIFE and `exports: 'default'` vs `exports: 'named'`.

from the wiki https://github.com/rollup/rollup/wiki/JavaScript-API#exports:

> `named` – suitable if you're exporting more than one thing

Could be understood as that should export to multiple globals.

I am ok with `multipleGlobals`, but to me it would not be clear how this behaves in combination with  `exports: 'default'` vs `exports: 'named'`... or maybe it still miss something.

`exports: 'global'` ?

**Comment by thisconnect** [comment]
In regards to Code splitting #372 I guess this would be great to be able to specify x entry points and build a common shared lib from that. If possible with an option to exclude stuff from the shared lib

**Comment by XDex** [comment]
Any updates on this?

**Comment by thisconnect** [comment]
At the moment I would love if `moduleName ` was optional, not sure if this would work for UMD

**Comment by Rich-Harris** [comment]
So, this is kind of a hack but you could use `moduleName: 'window'` – [demo](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnVtZCUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJ3aW5kb3clMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwdmFyJTIwZm9vJTIwJTNEJTIwMSUzQiU1Q25leHBvcnQlMjB2YXIlMjBiYXIlMjAlM0QlMjAyJTNCJTIyJTdEJTVEJTdE). That way, any named exports (it only works with named exports) get assigned to `window`.

**Comment by XDex** [comment]
@Rich-Harris a hacky workaround, but does the job for now, thanks!

**Comment by Rich-Harris** [comment]
I'll close this as the 'hack' is basically how it would be implemented anyway, and this is probably enough of an edge case that the solution is good enough

**Comment by julmot** [comment]
@Rich-Harris The demo link doesn't work anymore. Can you share a new example?
