### ISSUE TITLE
The `enumerable` `__proto__` field should not exist in the namespace.

### ISSUE THREAD

**Issue by j-murata** [rollup/rollup#4942]
### Expected Behavior / Situation

Suppose you have the following source code and configuration file.

<p><details open>
<summary><code>src/lib.mjs</code></summary>

```js
export function print1() { console.log(1); }
export function print2() { console.log(2); }
```

</details></p>

<p><details open>
<summary><code>src/index.mjs</code></summary>

```js
export * as Lib from './lib.mjs';
```

</details></p>

<p><details open>
<summary><code>rollup.config.js</code></summary>

```js
export default {
    input: 'src/index.mjs',
    output: {
        file: 'dist/index.mjs',
        format: 'es',
    },
};
```

</details></p>

If you run `rollup` on them, you will currently get the following output.

<p><details open>
<summary><code>dist/index.mjs</code></summary>

```js
function print1() { console.log(1); }
function print2() { console.log(2); }

var lib = /*#__PURE__*/Object.freeze({
	__proto__: null,
	print1: print1,
	print2: print2
});

export { lib as Lib };
```

</details></p>

The namespace object has an `enumerable` `__proto__` field that also appears in the editor's intellisense, which will probably confuse the user of this module.

![screen-shot](https://user-images.githubusercontent.com/16046688/232539690-21d98cfe-e696-4ca8-9921-fb13854f75f4.png)

### Actual Behavior / Situation

See above

### Modification Proposal

[`defineProperty`]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
[`Object.setPrototypeOf(obj, null)`]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf

Instead of adding `__proto__: null` directly, why not use [`Object.setPrototypeOf(obj, null)`]?

```js
var lib = /*#__PURE__*/Object.freeze(Object.setPrototypeOf({
	print1: print1,
	print2: print2
}, null));
```

Or you could [`defineProperty`] with `enumerable: false` for the `__proto__` field only.

~*As an aside, it would be nice to be able to choose whether the indent character in the output text is a tab or a space.*~

**Comment by lukastaegert** [comment]
There is not enumerable `__proto__` field, this is a bug in IntelliSense. You can try yourself by running this in the console:

```js
var o = {__proto__:null, a: 1};
Object.keys(o); // ["a"]
Object.getOwnPropertyDescriptors(o); // { a: ... }, but no __proto__
```

We could do it differently, but it would produce less optimal code. That IntelliSense wrongly detects this is not nice, though. It is probably because TypeScript does not understand `__proto__` very well.

> As an aside, it would be nice to be able to choose whether the indent character in the output text is a tab or a space.

You mean [output.indent](https://rollupjs.org/configuration-options/#output-indent) is not respected?

**Comment by j-murata** [comment]
Oh, I didn't know that the `__proto__` field is treated specially when added directly.
And I see that the following outputs fall under `less optimal code`. I understood this.

```js
var lib = /*#__PURE__*/Object.freeze(Object.setPrototypeOf({
    print1: print1,
    print2: print2
}, null));
```
```js
var lib = /*#__PURE__*/Object.freeze(Object.assign(Object.create(null), {
    print1: print1,
    print2: print2
}));
```
In any case, now that I know the problem is not caused by *rollup*, I will close this issue.

-----
> You mean [output.indent](https://rollupjs.org/configuration-options/#output-indent) is not respected?

My apologies. I was not aware that a string could be passed to this option.
