### ISSUE TITLE
Extending rollup cli with rollup init

### ISSUE THREAD

**Issue by raphaelokon** [rollup/rollup#495]
Hi.
I extended `rollup` CLI with a `rollup init` command to initialise a `rollup.config.js` (and other necessary files like an ~~appropirate~~ appropriate `.babelrc`). Is this something that you guys would like to include in the main package?

Cheers
—R

**Comment by Rich-Harris** [comment]
Sounds like a great idea! Would love to hear more

**Comment by raphaelokon** [comment]
Thanks. It is similar to what an `npm init` bur for `rollup` ==> an initialisation config wizard in for your `rollup.config.js`. I will do a fork and push my stuff so you can see what I mean.

**Comment by TrySound** [comment]
I don't think it's a good idea. js config format can have different code style which should be edited every time. Config itself is pretty simple. So I don't see any reasons introducing this feature.

**Comment by raphaelokon** [comment]
@TrySound I think it depends. I just gave it a bash because [rollup's config page](http://rollupjs.org/guide/#using-config-files) didn't help me to config my projects – I had to read through GH issues and SO questions, where I discovered additional properties that could be set. And while I agree that there are different ways and permutations how you could config it, I believe that there are only a handful of canonical starter configs (target specific envs or libs etc), where a `rollup init` could at least help you get started.
I am closing this and will post a link to the init once I find time to finish it.

**Comment by shouston3** [comment]
I would quite like this to be implemented in the cli.

@raphaelokon How did you get on with implementing this?

@Rich-Harris Any chance of this issue being reopened? I wouldn't mind working on it if it's a feature the community would like

**Comment by Rich-Harris** [comment]
@shouston3 I actually made a start on this a while back, but never got round to finishing it: https://github.com/rollup/rollup-init. Agree that it would be worth having in the CLI, particularly for setting up projects with a set of plugins for handling `node_modules` and CommonJS etc

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.

**Comment by lazarljubenovic** [comment]
Can someone link to the new issues? Having difficulties finding those and I'm very interested in this feature. My biggest pain point is having to look up examples on every project for simple things :/
