### ISSUE TITLE
Treeshake "static" dynamic import

### ISSUE THREAD

**Issue by antfu** [rollup/rollup#4951]
### Feature Use Case

Treeshake is such a brilliant idea. Nowadays, it powers so many frameworks/libraries to innovate without worries too much about the bundle size.

It's great that you can take some parts from a package, without paying the cost of the entire bundle:

```ts
import { unique } from 'lodash-es'
```

It works great on static imports. However, sometimes when you want to make some part lazy-load, treeshaking stopped to work:

```ts
const { unique } = await import ('lodash-es') // entire `lodash-es` will be bundled
```

###### Workaround

There is a workaround to this, is that you can create a temporary module that does the reexport:

```ts
// ./re-export.js
import { unique } from 'lodash-es'
```

```ts
const { unique } = await import ('./re-export.js') // now you have tree-shaking
```

However, this makes it verbose to use and easy to miss.

### Feature Proposal

Support tree-shaking dynamic imports that are known at build time. Namely, doing object  destructure and directly assigning with `await import()`

###### Valid cases

```ts
const { foo, default: anotherName } = await import('foo')
```

```ts
const { foo } = await import('foo')
const { bar } = await import('foo')
```

```ts
(await import('foo')).foo
```

###### Invalid cases

(Tree shaking is not applicable, to the current behavior.)

```ts
// full bundle
const foo = await import('foo')
```

```ts
// not waiting
const promise = import('foo')
```

```ts
// rest
const { foo, ...bar } = await import('foo')
```

```ts
// imported multiple times, but one of them is not tree shakable
const { foo } = await import('foo')
const foo = await import('foo')
```

----

Even though the "valid cases" are a bit strict, I believe it's still a very common pattern for people to benefit from. 

----

Idea credits: Webpack 5.80 https://twitter.com/TheLarkInn/status/1648739331807510528

**Comment by antfu** [comment]
Let me know if you think this is a good direction.

I am already working on it locally, might need sometime to get familiar with the codebase :)

**Comment by sapphi-red** [comment]
Linking some related issues: #3417, #3447, https://github.com/vitejs/vite/issues/11080

**Comment by antfu** [comment]
Thanks for the reference!
