### ISSUE TITLE
only the first line of comments before `import` statement is preserved 

### ISSUE THREAD

**Issue by viocha** [rollup/rollup#4953]
### Rollup Version

3.20.7

### Operating System (or Browser)

windows

### Link To Reproduction

https://rollupjs.org/repl/?version=3.20.7&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMCUzRCUzRFVzZXJTY3JpcHQlM0QlM0QlNUNuJTJGJTJGJTIwJTQwbmFtZSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyME5ldyUyMERlbW8lNUNuJTJGJTJGJTIwJTQwbmFtZXNwYWNlJTIwJTIwJTIwVmlvbGVudG1vbmtleSUyMFNjcmlwdHMlNUNuJTJGJTJGJTIwJTQwbWF0Y2glMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NhbGxfdXJscyUzRSU1Q24lMkYlMkYlMjAlNDByZXF1aXJlJTIwJTIwJTIwJTIwJTIwaHR0cHMlM0ElMkYlMkZjZG4uanNkZWxpdnIubmV0JTJGbnBtJTJGanF1ZXJ5JTQwMyU1Q24lMkYlMkYlMjAlNDB2ZXJzaW9uJTIwJTIwJTIwJTIwJTIwMS4wJTVDbiUyRiUyRiUyMCUzRCUzRCUyRlVzZXJTY3JpcHQlM0QlM0QlNUNuJTVDbiUyRiUyRiUyMGNvbW1lbnRzJTIwYmVmb3JlJTIwaW1wb3J0JTIwc3RhdGVtZW50JTVDbmltcG9ydCUyMGRhdGElMjBmcm9tJTIwJy4lMkZhLmpzJyUzQiU1Q24lNUNuJTVDbmNvbnNvbGUubG9nKGRhdGEpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBjb21tZW50cyUyMGluJTIwYS5qcyU1Q25jb25zdCUyMGRhdGElM0QnZGF0YSclM0IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGRhdGElM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0FmYWxzZSU3RCU3RA==

### Expected Behaviour

![normal](https://user-images.githubusercontent.com/66580331/233833652-9ccc0b59-2dc3-4592-ab29-1b2fe39de34e.png)

all the comments are preserved , which only happens when the `import` statement is in the first line

### Actual Behaviour

![error](https://user-images.githubusercontent.com/66580331/233833607-f4225d36-f44c-45b4-a6f4-c4a0d97691a6.png)

the `import` statement is hoisted to the beginning of the file ，and multiline comments are trimmed

from
```js
// ==UserScript==
// @name        New Demo
// @namespace   Violentmonkey Scripts
// @match       <all_urls>
// @require     https://cdn.jsdelivr.net/npm/jquery@3
// @version     1.0
// ==/UserScript==
```
to
```
// ==UserScript==
```

similar issue: #3763

**Comment by lukastaegert** [comment]
Fix at #4975

**Comment by viocha** [comment]
> Fix at #4975

The issue has not been resolved completely.

![Snipaste_2023-10-21_12-06-34](https://github.com/rollup/rollup/assets/66580331/e7d9035d-40fc-4f72-bf0c-f4971009fc22)

as the picture shows,
- only the first chunk of comments will be kept if the comments before the import statement are separated by blank lines. 
- and the inlined code from the import statement doesn't appear at the original position

link: https://rollupjs.org/repl/?version=4.1.4&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMGNvbW1lbnRzJTIwMSU1Q24lMkYlMkYlMjBjb21tZW50cyUyMDIlNUNuJTVDbiUyRiolNUNuJTIwJTIwVE9ETyUzQSUyMHRvZG8xJTVDbiolMkYlNUNuJTVDbiUyRiolNUNuJTIwJTIwVE9ETyUzQSUyMHRvZG8yJTVDbiolMkYlNUNuJTVDbiU1Q25pbXBvcnQlMjBkYXRhJTIwZnJvbSUyMCcuJTJGYS5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGRhdGEpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBjb21tZW50cyUyMDMlNUNuJTVDbiUyRiolNUNuJTIwJTIwVE9ETyUzQSUyMHRvZG8zJTIwJTVDbiolMkYlNUNuJTVDbmNvbnN0JTIwZGF0YSUzRCcxMjMnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBkYXRhJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBZmFsc2UlN0QlN0Q=

**Comment by lukastaegert** [comment]
The assumption is that the comments at the start of `main.js` describe the contents of `main.js` and the comments at the start of `a.js` describe the contents `a.js`. Hence, they are in the correct position, above the content of each file.

**Comment by viocha** [comment]
> The assumption is that the comments at the start of `main.js` describe the contents of `main.js` and the comments at the start of `a.js` describe the contents `a.js`. Hence, they are in the correct position, above the content of each file.

Thank you for taking the time to respond.
I know the import statement should be written at the beginning of the js file. But sometimes, I need to write some comments before the import statements. If I run rollup, the import statement will be hoisted before the comments, causing the code of a.js module to appear before the comments in main.js. It would be great if rollup could provide an option to prevent the hoisting of import statements.
In addition, even if treeshaking is disabled, some comment information in the main.js file is still not retained, as shown in the picture.

**Comment by lukastaegert** [comment]
Imports are not hoisted, they are completely removed and recreated based on what cannot be found in a chunk. That does not make a lot of difference to users, but explains why we cannot just "not hoist" imports. If several modules in a chunk import the same binding from a dependency, we need to merge those exports to produce valid and efficient code. The comment logic is like this: A comment on a separate line is considered to describe the next statement below. If that statement is removed, then the comment needs to be removed with it. The only exception are comments at the beginning of a file not separated by empty lines as those are considered to describe the file instead and are retained if any content of that file is not removed.
