### ISSUE TITLE
Unnecessary imports in bundled file

### ISSUE THREAD

**Issue by eye-wave** [rollup/rollup#4959]
### Rollup Version

3.21.0

### Operating System (or Browser)

Linux

### Node Version (if applicable)

20.0.0

### Link To Reproduction

https://github.com/eye-wave/playlist-manager-for-discord

### Expected Behaviour

after running `rollup -c` i'd expect my code bundle to look like this:
```js
import {g as o,s as i} from "./index-4768d999.js";i(parseInt(o("--limit", "-l")) || void 0);
```

---
also as a side note, i've noticed that when using "googleapis" npm module, initial compile time takes over 10 seconds, even when having them in external modules in rollup.config.mjs

### Actual Behaviour

what i instead got was these imports for some reason, i'll paste the code without minification for better readability
i've also tried building the code without resolve, and terser plugin but results were the same
```js
import {
  g as o,
  s as i
} from "./index-4768d999.js";
import "dotenv/config";
import "./songs-a4418d3d.js";
import "csv-parser";
import "d3-dsv";
import "node:fs";
import "node:path";
import "discord.js";
import "node:child_process";
import "googleapis";
import "node:http";
import "node:url";
import "open";
i(parseInt(o("--limit", "-l")) || void 0);
```

**Comment by dasa** [comment]
I think you may be running into this: https://rollupjs.org/faqs/#why-do-additional-imports-turn-up-in-my-entry-chunks-when-code-splitting

**Comment by eye-wave** [comment]
Oh, i didn't know that. Looks like this wasn't a bug after all.
thank you!
