### ISSUE TITLE
In vite.config.ts, using both @vitejs/plugin-legacy and UnoCSS simultaneously will cause build failure.

### ISSUE THREAD

**Issue by SadWood** [rollup/rollup#4963]
### Rollup Version

3.21.0

### Operating System (or Browser)

MacOS 13.3.1

### Node Version (if applicable)

18.7.0

### Link To Reproduction

https://github.com/SadWood/vite-legacy-unocss.git

### Expected Behaviour

build success

### Actual Behaviour

[vite:css-post] Plugin error - Unable to get file name for unknown file

**Comment by lukastaegert** [comment]
Why post this in the Rollup repo? I am closing this because either Vite or any of the mentioned plugins appear to be much better places for this issue.
