### ISSUE TITLE
switch is not a scope

### ISSUE THREAD

**Issue by Leubeling** [rollup/rollup#4976]
### Rollup Version

v3.21.3

### Operating System (or Browser)

5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Node Version (if applicable)

v18.16.0

### Link To Reproduction

https://rollupjs.org/repl/?version=3.21.4&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwcGFyc2VHcmFwaGljQ2FudmFzKHApJTdCJTVDbiUyMCUyMCUyMCUyMGxldCUyMHIlM0Qnd3JvbmcnJTNCJTVDbiUyMCUyMCUyMCUyMGxldCUyMHQlM0RnZXQocCklM0IlMjAlMkYlMkYlMjBpbnN0ZWFkJTIwYm90aCUyMGxldCUyMC0lM0UlMjBib3RoJTIwdmFyJTIwd2lsbCUyMGJlJTIwcmVuZGVyJTVDbiUyMCUyMCUyMCUyMHN3aXRjaCh0KSU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjYXNlJTVDJTIycG9pbnRzJTVDJTIyJTNBJTIwJTJGJTJGJTIwaWYlMjB0aGlzJTIwd291bGQlMjBiZSUyMGElMjAlNUMlMjIuLi4lM0ElN0IlMjAuLi4lMjAlN0RicmVhayUzQiU1QyUyMiUyMC0lM0UlMjBib3RoJTIwbGV0JTIwd2lsbCUyMGJlJTIwcmVuZGVyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGxldCUyMHQlM0QlNUMlMjJjb3JyZWt0JTVDJTIyJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHIlMjAlM0QlMjBzb21lKHQpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJyZWFrJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyMCUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjByJTNCJTVDbiU3RCU1Q24lNUNucGFyc2VHcmFwaGljQ2FudmFzKHVuZGVmaW5lZCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

### Expected Behaviour

after rendering:
... Column number three is not optimized.

### Actual Behaviour

after rendering:
... Column number three is incorrectly optimized.

**Comment by Leubeling** [comment]
I observed this behavior with an npm package that was minimized by webpack.

**Comment by lukastaegert** [comment]
Thank you for spotting, fix at #4979
