### ISSUE TITLE
external function using absolute paths

### ISSUE THREAD

**Issue by scholz-timo** [rollup/rollup#4977]
### Rollup Version

3.5.0

### Operating System (or Browser)

windows

### Node Version (if applicable)

18.14.2

### Link To Reproduction

not-required

### Expected Behaviour

We as a team are not sure if this behavior is intended, but after the first pass of external (when running programmatically) it will do a second pass with absolute path(s).

### Actual Behaviour

It should retain the relative path to check.

**Comment by lukastaegert** [comment]
Yes, that is absolutely intended. This is to cover the two ways how you can mark a module as external https://rollupjs.org/configuration-options/#external. While it might be useful to only mark e.g. `./foo.js` as external, it is usually not what you want in that case as for a file in a nested folder, the import would be `../foo.js`. So you would need to list all possible ways that `foo.js` can be imported. For that reason, relative externals are resolved to absolute paths and then compared against `externals` a second time. 

Note that plugins can prevent this behaviour by using the object form of `resolveId` to mark an import as external. https://rollupjs.org/plugin-development/#resolveid
