### ISSUE TITLE
RFC: Logging API

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup#4981]
### Feature Use Case

Currently, the only way to log in a structured way from Rollup core is to (ab)use warnings. This turned out problematic for some recent features (especially `experimentalMinChunkSize`), where I wanted to log some status information for the user. The current "workaround" was to log to the console, but this is definitely not the desired goal:
- higher level tools like Vite should be able to filter logs or present them in a visually consistent way
- plugins should be able to add their own logs
- plugins should be able to access and filter logs

### Feature Proposal

I propose to add a new logging API to Rollup. My suggestion is to model it after `onwarn` but with additional plugin support. Similar to warnings, logs should be able to have custom properties that can be parsed by higher level tools to provide better handling, filtering and visual representation. It would have several parts:

### A user-facing `onLog` option

The user can supply an `onLog` function option with mostly the same signature and behavior as `onwarn`:

```ts
interface InputOptions {
	// ...
	onLog?: LogHandlerWithDefault;
}

interface NormalizedInputOptions {
	// ...
	onLog?: LogHandler;
}

type LogHandlerWithDefault = (
	log: GeneratedRollupLog,
	defaultHandler: LogHandler
) => void

type LogHandler = (log: GeneratedRollupLog) => void;

// In generated logs, at least the level is always present
interface GeneratedRollupLog extends RollupLog {
	level: LogLevel;
}

interface RollupLog {
	level?: LogLevel; // This is added for logs
	binding?: string;
	cause?: unknown;
	code?: string;
	exporter?: string;
	frame?: string;
	hook?: string;
	id?: string;
	ids?: string[];
	loc?: {
		column: number;
		file?: string;
		line: number;
	};
	message: string;
	names?: string[];
	plugin?: string;
	pluginCode?: string;
	pos?: number;
	reexporter?: string;
	url?: string;
}

type LogLevel = 'warning' | 'info' | 'debug';
```

Note that only the non-normalized `onLog` option receives the `default` handler. When used from the CLI, Rollup will pass in something that looks reasonable together with other output (and is passed to stderr) while the JavaScript API default handler will probably do a `console.info`, `console.warn` or `console.debug` depending on the log level.

Other high-level tools could similarly use the `options` hook to overwrite the `onLog` handler with their own implementation that passes in their own default handler to any user-provided function.

If an `onLog` function is supplied, it will "swallow" all logs unless they are passed on to the default handler.

All current warnings will also be passed to `onLog` with a level of `warning`, i.e. this can completely replace `onwarn`.

Note that this rich API will also allow logs to have a "position" in a module (as warnings currently have, at least some of them). This could be very useful for logs that are related to code positions.

The `code` property will allow certain types of logs to be identified to e.g. filter certain logs.

The fact that we have a fixed set of possible properties that always have a certain meaning should make it easy to provide a nice representation. I vaguely remember e.g. that there was some criticism that Vite would not always display code positions of warnings properly (but maybe this is fixed already?). In any case, here is how Rollup displays rich warnings (and also reduces the amount of similar warnings displayed): https://github.com/rollup/rollup/blob/master/cli/run/batchWarnings.ts

### Plugin logs

Similar to `this.warn`, there would be a `this.log` plugin context function:

```ts
interface PluginContext extends MinimalPluginContext {
	// ...
	log: (
		log: RollupLog | string,
		options?: {
			pos?: number | { column: number; line: number };
			dedupe?: true // idea to reduce noise?
		}
	) => void;
}
```

If a string is passed or otherwise no `level` is provided, the level would be `info`. Passing a `pos` would make Rollup add additional information to the log similar to `this.warn`, namely `id`, `column` and `line` (which are calculated from `pos` if that one is a number).

### Plugin hook

This would be a new addition.

```ts
FunctionPluginHooks {
	// ...
	onLog: (this: PluginContext, log: GeneratedRollupLog) => false | void;
}
```

The hook would be synchronous (as there could be many logs and sync is faster) and sequential. If a hook returns `false`, then the log is not passed to any further plugins but "swallowed" instead. To "replace" a log, a plugin could use `this.log` with the new log and return `false`. Otherwise, plugins can edit the properties of the log to add additional information and of course process the logs internally in some way.

### Open questions

- Should all logs have a `code`, either as a required property or Rollup adds a default `code` or are we happy with some logs not having a `code`?
- Currently, errors are also kind of logs but with the special effect that there can usually be only one error and that errors abort the build. Should errors also be passed to the logging API before aborting the build? I am currently leaning to "no" because plugins can easily access errors via the `buildEnd` and `renderError` hooks and there is no use to "filter" errors. Alternatively, do we want an "error" log level? Again, I am leaning towards "no" to have only one "kind of error".
- Should we return `false` to filter a log in the plugin hook, or should we instead return `true` or something else?

### RFC

I would be very interested to receive feedback on this one. I did not implement anything yet, but it should be fairly straightforward as it could reuse most of the warning API.

Would be nice if tools like Vite would add their own handling for this API if it is implemented.

cc e.g. @yyx990803 @antfu @patak-dev @marvinhagemeister @sapphi-red and anyone else interested.

**Comment by lukastaegert** [comment]
I would not deprecate `onwarn`, though, but it might be a candidate for future deprecation if this API is well accepted.

**Comment by patak-dev** [comment]
Sounds good to me. For reference, we have a `customLogger` option in Vite in place that could mostly be replaced by this feature. I think we should implement support for the new API in the Vite dev server after you add it and wire our logs through it deprecating Vite's logger abstraction: https://vitejs.dev/config/shared-options.html#customlogger

We have a `warnOnce` feature to dedupe noisy logs. Maybe there could be a `{ dedupe: true }` option we could pass to `this.log`?

**Comment by lukastaegert** [comment]
Sounds like an idea. How does `warnOnce` work, i.e. how does it know what warnings are "the same"? Does it look at the `code`, `message`...? What is the effect if there are multiple warnings?

Currently for Rollup CLI, deduping is part of the display logic. I.e. for certain warnings, Rollup merges the warnings and displays e.g. "... and 5 more occurrences" etc. while rollup core still shows all warnings.
If "dedupe" is a property of the log, then we could use this as a flag for the displayer of the logs that only e.g. the first five logs of a kind should be shown. For Rollup CLI, deduping is based on codes.

**Comment by patak-dev** [comment]
`warnOnce` in Vite currently dedupes based on `message`, directly [ignoring duplicates](https://github.com/vitejs/vite/blob/775505d748d8cd076e823a80d47647ca8e6badf6/packages/vite/src/node/logger.ts#L120). We only have it as `warnOnce(messsage, options)` with options being
```
export interface LogOptions {
  clear?: boolean
  timestamp?: boolean
}
```

**Comment by lukastaegert** [comment]
> warnOnce in Vite currently dedupes based on message

Out of curiosity, is there an issue that prompted this feature to be implemented? After all, plugins should be easily able to dedupe themselves, but maybe it is an awesome debugging feature when developing plugins. But for anything else, it strikes me as odd that deduping is triggered by the plugins that show those warnings.

Similarly, it looks as if the plugin decides whether timestamps, which again feels to me to be mostly useful for debugging. And I am unsure what `clear` does?

This is mostly to understand the implications better, and to gauge what could easily be implemented by plugins, or whether we need to handle it in Rollup core. For instance, we could allow logs to have additional Vite-specific properties which are just passed through by Rollup and then interpreted accordingly by Vite.

Another question to clarify: Can plugins log "error" logs that are not related to errors, or is each error log indeed caused by an error? Would Rollup need to pass errors to plugin handlers first before stopping the build for the implementation to be useful to you?

Also, looking at your implementation, it occurs to me that Rollup should probably have a `logLevel` option as well, at least Rollup CLI.

**Comment by patak-dev** [comment]
> > warnOnce in Vite currently dedupes based on message
> 
> Out of curiosity, is there an issue that prompted this feature to be implemented? After all, plugins should be easily able to dedupe themselves, but maybe it is an awesome debugging feature when developing plugins. But for anything else, it strikes me as odd that deduping is triggered by the plugins that show those warnings.

Good point. We added it as part of a security fix [https://github.com/vitejs/vite/pull/3377], and we didn't put much thought onto it. We should have used `warn` and dedupe at the caller site instead.

> Similarly, it looks as if the plugin decides whether timestamps, which again feels to me to be mostly useful for debugging. 

We use `timestamp` to mark add it to errors, or when there is a server restart or page reload. It was added [here](https://github.com/vitejs/vite/commit/ca02b9b7d3f89e9fefa7ee23e8b643eafe87ac26#diff-863416a9b0769ffb1d7e36b6840ce6d0d84170a80a5c4ce4539464b0ebcbd137R102) for reference. We could have a utility function `withTimestamp(msg)` instead though.

> And I am unsure what `clear` does?

It clears the screen (if possible) so only this log is visible. We use it when there is a server restart. Normally the user doesn't care about the previous logs in this case. I don't know if it would be better to call a helper before logging in to clear and then log. Adding the clear to a log that may be filtered may end up with edge cases.

> This is mostly to understand the implications better, and to gauge what could easily be implemented by plugins, or whether we need to handle it in Rollup core. For instance, we could allow logs to have additional Vite-specific properties which are just passed through by Rollup and then interpreted accordingly by Vite.

I think this is something to plan, even if we don't need it because of the features above. It seems useful to pass meta in the logs (same as it is useful in other places in rollup).

> Another question to clarify: Can plugins log "error" logs that are not related to errors, or is each error log indeed caused by an error? Would Rollup need to pass errors to plugin handlers first before stopping the build for the implementation to be useful to you?

I see a few cases where we are logging a soft error and continuing https://github.com/vitejs/vite/blob/d63129b5f028646596bd5c57d2832eaf441c77b7/packages/vite/src/node/plugins/css.ts#L948. Maybe this should be modeled as a warning though. I think we could adapt here in Vite core, but I don't know if other plugins in the ecosystem are also using errors in this way 🤔 

> Also, looking at your implementation, it occurs to me that Rollup should probably have a `logLevel` option as well, at least Rollup CLI.

Sounds good to me.

**Comment by sapphi-red** [comment]
Looks good to me 👍 

> To "replace" a log, a plugin could use `this.log` with the new log and return `false`.

I think this can occur a infinite loop. Would `this.log` have a `skipSelf` option like we have with `this.resolve`? or would it work like `skipSelf: true` by default?
I guess we don't need `onLog` to be called recursively so I think it'll be better to simply skip it.

> Should all logs have a `code`, either as a required property or Rollup adds a default `code` or are we happy with some logs not having a `code`?

I prefer to make `code` required. But I guess it's fine to make `code` optional. The logs from plugins will always have `plugin` at least and that would be sufficient in most cases.

> Currently, errors are also kind of logs but with the special effect that there can usually be only one error and that errors abort the build. Should errors also be passed to the logging API before aborting the build? I am currently leaning to "no" because plugins can easily access errors via the `buildEnd` and `renderError` hooks and there is no use to "filter" errors. Alternatively, do we want an "error" log level? Again, I am leaning towards "no" to have only one "kind of error".

Both sounds good to me.

> Should we return `false` to filter a log in the plugin hook, or should we instead return `true` or something else?

Since the plugin hook name is `onLog`, I think returning `false` is more intuitive.

**Comment by lukastaegert** [comment]
Thanks so much for feedback!

> I think this can occur a infinite loop. Would this.log have a skipSelf option like we have with this.resolve? or would it work like skipSelf: true by default

This is true indeed. From the experience with `this.resolve`, the default should definitely be `skipSelf: true`. The only question is if we need to expose this as an option, i.e. whether `skipSelf: false` would actually be important. Maybe we go without this option in the initial version as you suggested.

As I side note, I seriously consider changing the default of `skipSelf` to `true` for `this.resolve` in the next major version as well.
