### ISSUE TITLE
Rollup shouldn't close stdout or subsequent writes will fail.

### ISSUE THREAD

**Issue by mlstich** [rollup/rollup#4995]
### Expected Behavior / Situation

The expected behaviour is the one before #4983 - not to close stdout with `process.stdout.end()`. Subsequent writes to stdout (through node) will continue to be successful.

### Actual Behavior / Situation

With #4983 / Rollup v3.21.6, stdout is closed. Subsequent writes to stdout will fail.

Our specific case:

- We use the [Firebase action-hosting-deploy](https://github.com/FirebaseExtended/action-hosting-deploy) GitHub action to deploy to firebase.
- We use a [predeploy hook](https://firebase.google.com/docs/cli#hooks) to invoke rollup as part of the deployment.
- With v3.21.6 this started to fail because stdout (within node) is closed after the rollup commands but the GitHub action looks for the success message from deployment in that log (see https://github.com/FirebaseExtended/action-hosting-deploy/blob/4d0d0023f1d92b9b7d16dda64b3d7abd2c98974b/src/deploy.ts#L150).

### Modification Proposal

Roll back the change in #4983 (and solve it differently, without affecting the node process beyond Rollup).

**Comment by lukastaegert** [comment]
Are you calling Rollup CLI as a Node script instead of as a separate process? How is it a problem that we close stdout but not that we call `process.exit`? the change was introduced because explicitly calling `process.exit` was aborting the CLI before stdout was fully written. Explicit `process.exit` on the other hand solved issues with Rollup not closing in certain configurations.

**Comment by mlstich** [comment]
> Are you calling Rollup CLI as a Node script instead of as a separate process?

Yes, you can but it that way. The GitHub action does that. Using the firebase CLI alone doesn't produce the issue.

> How is it a problem that we close stdout but not that we call `process.exit`

Good point! I'm not familiar with how that's handled however.

I created a repro to demonstrate the issue: https://github.com/mlstich/rollup-stdout-repro.

**Comment by mlstich** [comment]
Workaround (as an alternative to pinning the dependency): Redirect stdout to `/dev/null` when invoking rollup:

```
rollup main.js --file bundle.js > /dev/null
```

**Comment by lukastaegert** [comment]
Fix at #5004

**Comment by mlstich** [comment]
Awesome, thanks for the fix!
