### ISSUE TITLE
Consider removing indent from iife finalizer

### ISSUE THREAD

**Issue by Bobris** [rollup/rollup#5]
Please think about poor guys like me with notebooks where every space is valuable.

https://github.com/rollup/rollup/blob/master/src/finalisers/iife.js#L31

**Comment by Rich-Harris** [comment]
Yes, now that you mention it it probably is a bit superfluous. How about if Rollup accepts an `indent` option which could be `true` (auto-indent), `false` (don't indent) or a string (e.g. empty string, two spaces, one tab etc)?

**Comment by Bobris** [comment]
Yes, it would be nice. Of course very low priority.

**Comment by Rich-Harris** [comment]
Have added this feature as described - it's in 0.7.1

**Comment by Bobris** [comment]
:+1: :tada:
