### ISSUE TITLE
Plugin write hook

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup#500]
Hi!

I have just written a plugin that needs to output more files to the output folder alongside the bundle.
It would be nice if rollup had a `write` hook for plugins to make this more streamlined.

I can work on a PR if this seems like a good idea?

**Comment by tylerbeck** [comment]
Hey @Swatinem,  I've got a pull request in progress for this feature... check it out and let me know what you think.

https://github.com/rollup/rollup/pull/353

**Comment by TrySound** [comment]
https://github.com/rollup/rollup/pull/742
