### ISSUE TITLE
More agressive tree shaking when exporting object literals?

### ISSUE THREAD

**Issue by krzksz** [rollup/rollup#501]
Just wondering, would it be possible to do a more aggressive tree shaking when the module is exporting object literal, like [in this situation](http://goo.gl/F7m6Rm)? As you can see, even if I am using only a single property, whole object is being included. Whether the concept would extend on named exports of object literals is a matter of discussion.
The use case would involve libraries like jQuery or Lodash, which contain many functions while you only use a couple of them. The idea of exporting object literal is to preserve all of the functions in common namespace e.g. `$.addClass`, `$.each` etc...

I have no idea if the above is possible, but it would help to further decrease generated bundle sizes.

**Comment by krzksz** [comment]
I see it is somehow related to https://github.com/rollup/rollup/issues/349 with the difference that it should be simpler to just check objects properties.

**Comment by mark-rushakoff** [comment]
For lodash in particular, [babel-plugin-lodash] allows you to import lodash and use its methods, and then the plugin will rewrite the code to use e.g. `import map from 'lodash/map' even though you used it as `_.map`.

**Comment by krzksz** [comment]
Agree, but you still need a specialized plugin for it. What I am proposing would affect all of the libraries that use ES2015 modules including those that are specific for every project. The thing that I am trying to achieve is the ability to export multiple methods under a common namespace(represented by object literal) without disabling tree-shaking.

**Comment by eventualbuddha** [comment]
This could be done for very specific cases, probably similar to how the lodash plugin does it. Anything dynamic would probably have to unwind all optimizations.

**Comment by lukastaegert** [comment]
@krzksz Would it be possible to provide your initial example again via the [current version of the REPL](https://rollupjs.org/repl)? Your initial link no longer works as the URL format seems to have changed and I would like to understand the initial issue better.

**Comment by krzksz** [comment]
Hey @lukastaegert, thanks for your interest in this. I looked into an URL and I believe it was something like this: https://goo.gl/hxsSPf

As @eventualbuddha mentioned there will be some dynamic cases which could introduce errors when this kind of optimization is done like https://goo.gl/fYHyF3, but the solution would be to introduce _slow paths_ as it is in e.g. V8.

For starters we could disable this optimization in following cases:

1. Imported object is reassigned or passed to other variable/function.
2. Code is accessing object variable using array `[]` syntax.
3. There is an `eval` or Function constructor in the code.

Then while it is done we could probably work our way through points 1. and 2. to achieve better results.

I'm not that familiar with rollup internals but I can help however possible to make this happen.

**Comment by lukastaegert** [comment]
Hi, could you check your links again? For me, they both seem to point to the default example and not your code. Beyond taht, it *sounds* like it is something I have been wondering about myself. Currently, I am working on fixing up the declaration and call handling and after that I plan on implementing basic member expression assignment tracking which might already provide a good basis for this.
As I understand it, you suggest omitting/not adding properties that will not be accessed. I think this will be possible but we have to be VERY CAREFUL to bail out of this behaviour as soon as anything is done with the object that depends on all keys being present, e.g. doing an Object.keys, a for-in loop etc.
The upside might be that at some point we could treeshake fluent interfaces which in my opinion is like the holy grail of treeshaking 🙀 
I will keep this in the back of my head. However, as this carries a high risk of introducing quite a bit of complexity into rollup, I want to finish the things I mentioned above first.

**Comment by krzksz** [comment]
Hey, I'm aware of the complexity it introduces especially if rollup doesn't have any variable tracking implemented just yet.

As to the links, they both do link to default tree shaking example which I altered a bit in terms of exported values, but I can also provide the code here directly:

```javascript
// main.js entry module
import maths from './maths.js';
console.log( maths.cube( 5 ) ); // Notice only .cube property is used
```
```javascript
// maths.js module

// This function isn't used anywhere, so
// Rollup COULD exclude it from the bundle...
function square ( x ) {
	return x * x;
}

function cube ( x ) {
	return x * x * x;
}

export default {
	square,
	cube
}
```

**Comment by lukastaegert** [comment]
Oh, my bad, I didn't look properly. Thanks for the feedback, I will comment again on this issue once we start making progress towards this.

**Comment by kzc** [comment]
@krzksz Recent versions of `uglify-es` perform the optimization you've described.

Given:
```
$ rollup -v
rollup version 0.53.3

$ uglifyjs -V
uglify-es 3.3.4
```
```js
$ cat main.js
// main.js entry module
import maths from './maths.js';
console.log( maths.cube( 5 ) ); // Notice only .cube property is used
```
```js
$ cat maths.js 
// maths.js module

// This function isn't used anywhere, so
// Rollup COULD exclude it from the bundle...
function square ( x ) {
	return x * x;
}

function cube ( x ) {
	return x * x * x;
}

export default {
	square,
	cube
}
```
compare:
```js
$ rollup main.js -f es --silent
// maths.js module

// This function isn't used anywhere, so
// Rollup COULD exclude it from the bundle...
function square ( x ) {
	return x * x;
}

function cube ( x ) {
	return x * x * x;
}

var maths = {
	square,
	cube
}

// main.js entry module
console.log( maths.cube( 5 ) ); // Notice only .cube property is used
```
to:
```js
$ cat maths.rollup.js 
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-es';

export default {
    input: 'main.js',
    plugins: [
        uglify({
            toplevel: true,
            compress: {
                passes: 4,
            },
        }, minify)
    ],
    output: {
        file: 'maths.bundle.js',
        format: 'es',
    },
};
```
```js
$ rollup -c maths.rollup.js --silent && cat maths.bundle.js 
console.log(125);
```

**Comment by guybedford** [comment]
I believe this is implemented in Rollup now, but please say if there are still features missing here.

**Comment by lukastaegert** [comment]
No I think this is still missing but really high up on the task list now.

**Comment by guybedford** [comment]
Repl - https://rollupjs.org/repl?version=0.60.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMG1haW4uanMlMjBlbnRyeSUyMG1vZHVsZSU1Q25pbXBvcnQlMjBtYXRocyUyMGZyb20lMjAnLiUyRm1hdGhzLmpzJyUzQiU1Q25jb25zb2xlLmxvZyglMjBtYXRocy5jdWJlKCUyMDUlMjApJTIwKSUzQiUyMCUyRiUyRiUyME5vdGljZSUyMG9ubHklMjAuY3ViZSUyMHByb3BlcnR5JTIwaXMlMjB1c2VkJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMG1hdGhzLmpzJTIwbW9kdWxlJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMENPVUxEJTIwZXhjbHVkZSUyMGl0JTIwZnJvbSUyMHRoZSUyMGJ1bmRsZS4uLiU1Q25mdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTNCJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglMjAqJTIweCUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTVDdHNxdWFyZSUyQyU1Q24lNUN0Y3ViZSU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by eight04** [comment]
After this is implemented, would tree shaking work with commonjs plugin? IIRC it maps the namespace object to default export in the proxy module.

**Comment by lukastaegert** [comment]
This is what we hope for. Either the current CJS plugin or a reworked plugin that @guybedford is working on.

**Comment by guybedford** [comment]
Tracking under object shape tree-shaking in https://github.com/rollup/rollup/issues/2201.
