### ISSUE TITLE
Rollup watches a path even if that id is loaded by `load` hook

### ISSUE THREAD

**Issue by sapphi-red** [rollup/rollup#5013]
### Rollup Version

3.22.0

### Operating System (or Browser)

stackblitz

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-zpgwkm?file=run.js

### Expected Behaviour

If the content is loaded by a `load` hook (= the content isn't loaded by the rollup's default behavior), that path is not added to the watcher. If the content is loaded by a `load` hook, the content is not necessarily dependent on the file at that path.

### Actual Behaviour

Even if the content is loaded by a `load` hook, that path is added to the watcher.

I'm not sure if this is an intended behavior. I'm wondering if this is a behavior to make it easier to create plugins.

related: https://github.com/vitejs/vite/issues/13234

**Comment by lukastaegert** [comment]
I think this is by accident. Following your arguments, though, I guess we should delay fixing it for the next major version as it might be a breaking change of sorts. I will make a note.
