### ISSUE TITLE
Can't bundle with React-Router

### ISSUE THREAD

**Issue by salztorte** [rollup/rollup#502]
Hey,
I'm not sure if i should write this Issue in this Repo or in the Repo of React-Router Repo-

I try to use the React-Router for my project but i cant build it with rollup because of

`Cannot overwrite the same content twice: 'invariant'`

Ok the Error is clear but i dont know how to fix it. 

Some ideas??

**Comment by TrySound** [comment]
@salztorte Show your code, config and full stack trace.

**Comment by salztorte** [comment]
index.js
```
import React from 'react';
import { render } from 'react-dom';
import { Router, Route, hashHistory } from 'react-router';


render(
    <div>Hallo Welt</div>,
    document.getElementById('content'));
```

rollup.config.js
```
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import npm from 'rollup-plugin-npm';
import replace from 'rollup-plugin-replace';

export default {
    entry : 'src/index.js',
    dest : 'www/build/bundle.js',
    format : 'iife',
    plugins : [
        replace({
                    'process.env.NODE_ENV' : JSON.stringify('production')
                }),
        npm({jsnext : true, main : true}),
        commonjs({
                     namedExports : {
                         'node_modules/react/react.js' : ['Component', 'Children', 'createElement', 'PropTypes'],
                         'node_modules/react-dom/index.js' : ['render']
                     }
                 }),
        babel()
    ]
};
```

Error
```
Cannot overwrite the same content twice: 'invariant'
Error: Cannot overwrite the same content twice: 'invariant'
    at Object.patch (C:\Users\FRA\AppData\Roaming\npm\node_modules\rollup\www\ROLLUP\rollup\node_modules\magic-string\dist\magic-string.es6.js:424:12)
    at Object.overwrite (C:\Users\FRA\AppData\Roaming\npm\node_modules\rollup\www\ROLLUP\rollup\node_modules\magic-string\dist\magic-string.es6.js:393:8)
    at C:\Users\FRA\AppData\Roaming\npm\node_modules\rollup\www\ROLLUP\rollup\src\Module.js:516:19
    at Array.forEach (native)
    at C:\Users\FRA\AppData\Roaming\npm\node_modules\rollup\www\ROLLUP\rollup\src\Module.js:489:25
    at Array.forEach (native)
    at Module.render (C:\Users\FRA\AppData\Roaming\npm\node_modules\rollup\www\ROLLUP\rollup\src\Module.js:429:19)
    at C:\Users\FRA\AppData\Roaming\npm\node_modules\rollup\www\ROLLUP\rollup\src\Bundle.js:222:26
    at Array.forEach (native)
    at Bundle.render (C:\Users\FRA\AppData\Roaming\npm\node_modules\rollup\www\ROLLUP\rollup\src\Bundle.js:221:23)

```

**Comment by salztorte** [comment]
I find out that i can bundel the react-router if i use the cjs release instead of the es6 release.

Is just a work around but it works.

**Comment by TrySound** [comment]
@salztorte Yep. Maybe it's because commonjs can't be converted in es6.

**Comment by TrySound** [comment]
@salztorte Hm... I run your config without errors. Is your react stuff frash?

**Comment by salztorte** [comment]
I reinstalled all dependencies but always the same problem.

**Comment by TrySound** [comment]
@salztorte Create please repo which reproduce your problem.

**Comment by salztorte** [comment]
Here is the repo
[https://github.com/salztorte/RollupReactRouter](https://github.com/salztorte/RollupReactRouter)

Thanks

**Comment by TrySound** [comment]
@salztorte Sorry man. It still works. Which OS you use?

**Comment by salztorte** [comment]
At the Moment Windos 8.1.

**Comment by TrySound** [comment]
@salztorte node, npm versions?

**Comment by salztorte** [comment]
@TrySound node version is 5.5.0 
& 
npm version ist 3.7.1

**Comment by chrisbateman** [comment]
I'm seeing the same error. It only occurs when you add the replace plugin for `process.env.NODE_ENV`.

**Comment by salztorte** [comment]
@chrisbateman I try it but and rollup run without problems. But then i can't run the bundel in the browser because` process is not defined`. 

And the solution for this problem was the replace plugin.

**Comment by TrySound** [comment]
@salztorte Okay. You found problem. Move issue here https://github.com/rollup/rollup-plugin-replace and ref to this issue.
