### ISSUE TITLE
sourcemapBaseUrl

### ISSUE THREAD

**Issue by bgbahoue** [rollup/rollup#5020]
### Rollup Version

v3.23.0

### Operating System (or Browser)

MacOS Ventura 13.3 (22E252)

### Node Version (if applicable)

v18.14.2

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-eki6jk?file=dist%2Fmain.js

### Expected Behaviour

Using the below rollout configuration file
```
export default {
  input: 'src/main.js',
  output: {
    dir: 'dist',
    format: 'cjs',
    sourcemap: 'true',
    sourcemapBaseUrl: 'https://storage.googleapis.com/bucketName/scripts',
  },
  plugins: [],
};
```

I would be expecting to get this at the bottom of the CJS file
`//# sourceMappingURL=https://storage.googleapis.com/bucketName/SCRIPTS/main.js.map` (capitalized for redibility)

### Actual Behaviour

With the following configuration file
```
export default {
  input: 'src/main.js',
  output: {
    dir: 'dist',
    format: 'cjs',
    sourcemap: 'true',
    sourcemapBaseUrl: 'https://storage.googleapis.com/bucketName/scripts',
  },
  plugins: [],
};
```

I'm getting the following sourceMap link at the bottom of the CJS file
`//# sourceMappingURL=https://storage.googleapis.com/bucketName/main.js.map` (no `/scripts`)

**Comment by lukastaegert** [comment]
It works if you set `sourcemapBaseUrl: 'https://storage.googleapis.com/bucketName/scripts/'` with a trailing slash. Maybe Rollup should add a trailing slash automatically in case it is missing. PR welcome.
