### ISSUE TITLE
Code splitting with CJS deps resolve to empty object if only one chunk is loaded

### ISSUE THREAD

**Issue by ArnaudBarre** [rollup/rollup#5025]
### Rollup Version

3.23.0

### Operating System (or Browser)

Mac OS Intel

### Node Version (if applicable)

19.8.1

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-qtdfme?file=package.json&view=editor

### Expected Behaviour

Output more similar to esbuild

### Actual Behaviour

Loading `a.js` wihtout `b.js` result into broken runtime code (faPrint is an empty object)

**Comment by TrickyPi** [comment]
I took a look at this issue and found that Rollup incorrectly handles dynamic chunks if the `moduleSideEffects` value of the resolving CJS module is `false`. I created a more intuitive reproduction https://stackblitz.com/edit/rollup-repro-mevfls?file=src%2Fmain.js.

**Comment by TrickyPi** [comment]
updated reproduction https://stackblitz.com/edit/rollup-repro-mevfls?file=src%2Fc.js, it's weird.
