### ISSUE TITLE
Add format like es but for Nodejs only

### ISSUE THREAD

**Issue by crystalfp** [rollup/rollup#5030]
### Feature Use Case

I want to bundle a Node application that requires "es" functionalities, like top level await.
When I run my application without bundling it, it runs without problems inside node.
The bundling with rollup works, but it enables features that make sense only in a browser environment, like the `navigator` object.
Note that this happens also for the "cjs" format.
If the loaded packages are well-behaved, that is not a problem to use "es" format, but there are packages, in my case "chalk", that decide at runtime if it runs in a browser or not and seems that inside rollup it takes the wrong decision.

### Feature Proposal

Add a new format, that could be called "node-es" for example, that is like the "es" format, but runs inside Nodejs only.

**Comment by dnalborczyk** [comment]
@crystalfp could you create a small repro repository? otherwise it's impossible to know what issue you are running into.

**Comment by crystalfp** [comment]
Sure!
Here it is:  
[bug2.zip](https://github.com/rollup/rollup/files/11783864/bug2.zip)

To reproduce:
1. unzip, cd bug2
2. npm i
3. npm run bundle
4. npm run start:node (success: prints a message)
5. npm run start:bundled (fail with navigator not found error)

**Comment by crystalfp** [comment]
Yes! This solve the problem. Now I check the solution also on the full application. In the meantime I close the issue.
Thanks again!
mario
