### ISSUE TITLE
Circular dependencies - console warning

### ISSUE THREAD

**Issue by ivodolenc** [rollup/rollup#5033]
### Rollup Version

3.25.0

### Operating System (or Browser)

mac

### Node Version (if applicable)

18.12.1

### Link To Reproduction

-

### Expected Behaviour

No console warnings.

### Actual Behaviour

Hi, in the latest version `3.25.0` it throws a warning in the console on build: `(!) Circular dependencies ...` 

In the previous version `3.24.1` this is not the case.

**Comment by TrickyPi** [comment]
Rollup@3.24.1 also throws a warning in the console, Could you provide a minimal repro?

<img width="548" alt="Screenshot 2023-06-11 at 11 06 13 PM" src="https://github.com/rollup/rollup/assets/33021497/b010428e-a7c6-48ee-8972-b96f6302e4e3">

**Comment by TrickyPi** [comment]
Hmmm, Maybe we can have a config to filter logs?
like this
```json
{
   disabledLogs: [ 'CIRCULAR_DEPENDENCY', 'CIRCULAR_REEXPORT' ]
}
```
@lukastaegert looking forward to your thoughts.

**Comment by lukastaegert** [comment]
Not yet convinced about this. It does not appear to be much shorter than writing a function, so the convenience would be limited. In any case, I am currently working on a related feature that should probably be finalised first: https://github.com/rollup/rollup/pull/5035

As I only have a phone for the next two weeks, it will take a little time to be completed, though.

**Comment by TrickyPi** [comment]
> It does not appear to be much shorter than writing a function

yeah, I think so too.

**Comment by ivodolenc** [comment]
Hmm, it seems that this is not a bug after all, and there is a solution for manually silencing the warning.

So, as far as I'm concerned, you can close this as resolved.

**Comment by ivodolenc** [comment]
According to this [example](https://github.com/rollup/rollup/pull/5035) from Lukas, I was able to silence the warning and it works as expected.

Here is a complete example if anyone is interested:

```js
// rollup.config.js

import { defineConfig } from 'rollup'
import { getLogFilter } from 'rollup/getLogFilter'
import esbuild from 'rollup-plugin-esbuild'
import dts from 'rollup-plugin-dts'
import pkg from './package.json' assert { type: 'json' }

const exports = {
  main: pkg.exports['.']
}

// Filters logs
const logFilter = getLogFilter(['!code:CIRCULAR_DEPENDENCY'])
const onLog = (level, log, handler) => {
  if (logFilter(log)) handler(level, log)
}

export default defineConfig([
  {
    input: './src/index.ts',
    output: [
      { file: exports.main.import, format: 'esm' },
      { file: exports.main.require, format: 'cjs' }
    ],
    plugins: [esbuild()]
  },
  {
    input: './src/types/index.ts',
    output: { file: exports.main.types, format: 'esm' },
    plugins: [dts()],
    onLog
  }
  // ...
])
```

Thanks for your time and help 👍 I'm closing this as resolved.
