### ISSUE TITLE
building sites with `vitepress` generates TypeError with `rollup`

### ISSUE THREAD

**Issue by jrappen** [rollup/rollup#5039]
### Rollup Version

3.25.1

### Operating System (or Browser)

ubuntu-latest via GitHub actions

### Node Version (if applicable)

20.3.0

### Link To Reproduction

https://github.com/da-michele/da-michele.com

### Expected Behaviour

Migrating my site from [`vuepress` (v2)](https://github.com/vuepress/vuepress-next) to [`vitepress`](https://github.com/vuejs/vitepress) and then building it via GitHub workflow should work.

### Actual Behaviour

Website code at:

- https://github.com/da-michele/da-michele.com/

GitHub workflow at:

- https://github.com/da-michele/da-michele.com/blob/main/.github/workflows/cd.yml

Output:

```text
Run pnpm run docs-build
  pnpm run docs-build
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin

> da-michele-website@ docs-build /home/runner/work/da-michele.com/da-michele.com
> vitepress build ./docs --minify false


  vitepress v1.0.0-beta.2

- building client + server bundles...
[vite:vue] error.code.startsWith is not a function
file: /home/runner/work/da-michele.com/da-michele.com/docs/de/menu/index.md
✖ building client + server bundles...
build error:
TypeError: error.code.startsWith is not a function
    at logPluginError (file:///home/runner/work/da-michele.com/da-michele.com/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:2633:35)
    at file:///home/runner/work/da-michele.com/da-michele.com/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:24925:26
    at async transform (file:///home/runner/work/da-michele.com/da-michele.com/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:23811:16)
    at async ModuleLoader.addModuleSource (file:///home/runner/work/da-michele.com/da-michele.com/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:24011:30)
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

Not sure if this is a issue on my side, an issue with `vitepress` or an issue with `rollup`?

I double checked both docs and my code.

/cc FYI @brc-dd

**Comment by brc-dd** [comment]
It's not a bug with Rollup or VitePress. All your code looks quite messy. For example, you're specifying `<img :src="/foo">`, where foo is not quoted. it's being treated as unterminated regex. There is also code like `<img :dark="..." light="...">`  --  not sure what you're trying to do by that. For some reason, you're exporting stuff from `<script setup>`, this is not valid Vue.
