### ISSUE TITLE
 ReferenceError: __name is not defined

### ISSUE THREAD

**Issue by lixiaofa** [rollup/rollup#5053]
### Rollup Version

^2.75.7

### Operating System (or Browser)

chrome

### Node Version (if applicable)

v18.16.0

### Link To Reproduction

https://github.com/lixiaofa/fast-plus/actions/runs/5443372337/jobs/9900013548

### Expected Behaviour

no error

### Actual Behaviour

pnpm build is ok , locally.
Error reported in github actions

![image](https://github.com/rollup/rollup/assets/23230215/922cc2fd-6582-4b74-990d-68a1f870f4f9)
https://github.com/lixiaofa/fast-plus/actions/runs/5443372337/jobs/9900013548

**Comment by lukastaegert** [comment]
The stack trace is not from Rollup, it looks like an error when converting Vue SFCs, maybe in some plugin.

**Comment by lixiaofa** [comment]
> 

Thank you for your guidance. I have found the reason

**Comment by blackhu0804** [comment]
> > 
> 
> Thank you for your guidance. I have found the reason

I have encountered the same problem, how can I solve it?
