### ISSUE TITLE
rollup -c command ends with syntax error in rollup

### ISSUE THREAD

**Issue by roysahil** [rollup/rollup#5055]
### Rollup Version

1.26.1

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

10.24.1

### Link To Reproduction

None

### Expected Behaviour

rollup -c command should run successfully for build. 

### Actual Behaviour

It ends with an error at /node_modules/rollup/dist/bin/rollup:1271

const SECOND_ROUNDING_EPSILON = 0.000_000_1;

SyntaxError: Invalid or unexpected token. 

This error occurs only when I run this command inside the Jenkins pipeline which has node version 10.24.1.

There is no error if I run the same command locally where I have node version 14.18.1 installed.

**Comment by lukastaegert** [comment]
Probably because Node 10 does not support `_` separators in numbers. You would need to add some plugin that removes underscores from your numbers, or do not use Node 10. It is not part of Rollup core to transpile syntax for older Node versions.
