### ISSUE TITLE
Rollup 3.26.2 breaks Nitro's Deno builds

### ISSUE THREAD

**Issue by AaronDewes** [rollup/rollup#5067]
### Rollup Version

3.26.2

### Operating System (or Browser)

Linux

### Node Version (if applicable)

18

### Link To Reproduction

https://github.com/unjs/nitro

### Expected Behaviour

Nitro works as usual with the Deno preset.

### Actual Behaviour

https://github.com/unjs/nitro/issues/1432.

Can be tested by running `NITRO_PRESET=deno-deploy pnpm nitro build playground` in the Nitro root. This fails with Rollup 3.26.2, but works if I downgrade to 3.26.1.

**Comment by TrickyPi** [comment]
There are some wrong options in the`src/presets/deno-deploy.ts`. An external module cannot be included in the `manualChunks`. You can fix this problem by changing the `manualChunks` option to the following.
```js
manualChunks: (id) => {
  if (id !== "https://deno.land/std/http/server.ts") return "index";
},
```

**Comment by AaronDewes** [comment]
Okay, but the change you made regarding that in 3.26.2 was a breaking change (because the previous version worked without issues). In a patch release, breaking changes should be avoided in my opinion (and according to semver).

**Comment by lukastaegert** [comment]
Ah, the issue is that external modules are actually passed to the `manualChunks` function. This should not be the case as those cannot be included. If we can fix this, then this would no longer be a breaking change except for the obvious case where someone explicitly included an external id.

**Comment by TrickyPi** [comment]
Oh sorry folks, it's my fault. I submitted a PR to fix it.

**Comment by AaronDewes** [comment]
Thank you!
