### ISSUE TITLE
can i stream into rollup? eg. for usage with gulp

### ISSUE THREAD

**Issue by bcherny** [rollup/rollup#508]
eg. i have a typescript project, and i'd like to compile and roll up the object stream:

ideally i'd like something like 

```coffee
gulp.task 'ts', ->
  gulp
    .src '**/*.ts'
    .pipe (ts tsProject)
    .js.pipe rollup()
    .pipe gulp.dest '.'
```

**Comment by salztorte** [comment]
there are a gulp-rollup plugin. [Here](https://www.npmjs.com/package/gulp-rollup)

**Comment by TrySound** [comment]
@bcherny gulp plugin for rollup using is bad idea caz it's wrapper where it do not need.
For typescript transpliling you can use https://github.com/rollup/rollup-plugin-typescript

**Comment by TrySound** [comment]
As you can see gulp wrappers have some bugs https://github.com/rollup/rollup-plugin-typescript/issues/29. We have a good promise API which works elegant with gulp. I updated [Build tool usage](https://github.com/rollup/rollup/wiki/Build-tools) wiki page.
