### ISSUE TITLE
RenderedModule.code should be readonly in TypeScript declaration

### ISSUE THREAD

**Issue by lazarljubenovic** [rollup/rollup#5081]
### Rollup Version

3.25.1

### Operating System (or Browser)

/

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-jwpcpq?file=package.json,rollup.config.ts

### Expected Behaviour

TypeScript reports an error because `code` is modeled to be readonly.

### Actual Behaviour

No error form TypeScript. Error observable only from the runtime behavior.

**Comment by lukastaegert** [comment]
Thanks for spotting, PR welcome!
