### ISSUE TITLE
A problem with punctuation in Chinese documents

### ISSUE THREAD

**Issue by cloudmoonocus** [rollup/rollup#5082]
### Documentation is

- [ ] Missing
- [X] Needed
- [X] Confusing
- [ ] Not sure?

### Please Explain in Detail...

There is a problem with punctuation in Chinese documents
中文文档标点有问题
![image](https://github.com/rollup/rollup/assets/98140702/cccc41d0-14ba-458e-aefe-af06970bc352)

### Your Proposal for Changes

改为：某些插件也可以专门应用于某些输出，有关特定输出插件可以做什么的详细信息，请参见 [插件钩子](https://cn.rollupjs.org/plugin-development/#build-hooks)。

**Comment by TrickyPi** [comment]
For issues of Chinese docs, please report here https://github.com/rollup/rollup-docs-cn.
