### ISSUE TITLE
Will rollup remove the lib's code, such as jquery, react?

### ISSUE THREAD

**Issue by guotie** [rollup/rollup#509]
Hi, If my code require jquery or react, can rollup remove jquery or react's unused code?

**Comment by salztorte** [comment]
That is the tree-shaking feature of rollup.

**Comment by eventualbuddha** [comment]
The library has to be written in such a way that rollup can understand the parts and how to separate them. jQuery is a particularly bad anti-example as it attaches everything to a global object, sometimes dynamically. You might be better off using alternatives that work better with rollup that use ES modules.
