### ISSUE TITLE
Rollup doesn't use index.js when a folder is imported

### ISSUE THREAD

**Issue by bogas04** [rollup/rollup#510]
CommonJS has given me a habit to create folders for react components and use index.js in them. Code becomes neat this way and component specific dependencies can be isolated. This doesn't work with ES2015 syntax in rollup though.

```js
// Can't resolve ./Home
import Home from './Home';
// Works fine
import Home from './Home/index.js';
```
I think this might break existing codebases which use above code organization style.

**Comment by TrySound** [comment]
@bogas04 Rollup do not follow node resolve algorithm out of the box. Use [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) for this case.

**Comment by bogas04** [comment]
Woah! Thanks for quick response

**Comment by dfahlander** [comment]
`rollup-plugin-node-resolve` seems not to fix this issue for local modules. I ended up having to install [rollup-plugin-local-resolve](https://www.npmjs.com/package/rollup-plugin-local-resolve) to fix it.

**Comment by Grawl** [comment]
looks like it's not working with rollup-plugin-alias

**Comment by JoshMcCullough** [comment]
> I successfully fixed using [rollup-plugin-local-resolve](https://www.npmjs.com/package/rollup-plugin-local-resolve)!

No idea how I'm just running into this for the first time, when I've published a billion NPM packages.
