### ISSUE TITLE
When I develop a plugin and use the 'options' hook to modify the 'dir' configuration, the information printed in the console is not correct！

### ISSUE THREAD

**Issue by martin-yin** [rollup/rollup#5106]
### Rollup Version

3.28.1

### Operating System (or Browser)

mac m1

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-cproxd?file=edit-options.js

### Expected Behaviour

```js
~/projects/rollup-repro-cproxd
❯ npm install && npm run build

added 1 package in 2s

> rollup-repro@0.0.0 build
> rollup -c rollup.config.js


src/main.js → newDir...
created dist in 13ms
```

### Actual Behaviour

```js
~/projects/rollup-repro-cproxd
❯ npm install && npm run build

added 1 package in 2s

> rollup-repro@0.0.0 build
> rollup -c rollup.config.js


src/main.js → dist...
created dist in 13ms
```

I didn't find a similar issue on the repository.

I've identified the cause of this problem in the source code.

https://github.com/rollup/rollup/blob/master/cli/run/build.ts#L17

When the `CLI` fetches the `output`, the `options hook` hasn't been triggered yet.

I've been thinking about this issue for a while and can't seem to find a solution for the fix. So, how should this problem be addressed?

**Comment by lukastaegert** [comment]
Rollup has two sets of options: inputOptions and outputOptions. While the CLI allows you to provide outputOptions via the `output` key, this key is not part of the internal options, this is just convenience. The reason is that you can create many outputs from a single input. Use the `outputOptions` hook to modify `dir`.

**Comment by martin-yin** [comment]
> 汇总有两组选项：输入选项和输出选项。虽然 CLI 允许您通过键提供输出选项，但此键不是内部选项的一部分，这只是方便。原因是您可以从单个输入创建多个输出。使用钩子修改 .`output``outputOptions``dir`

Thank you, I understand
