### ISSUE TITLE
The sourcemap is incorrect when use brackets to access properties

### ISSUE THREAD

**Issue by xinchaobeta** [rollup/rollup#511]
The file `a.js` :

``` js
import * as c from './b'

function a() {
  debugger;
  return c['b']
}

console.log(a())
```

The file `b.js` : 

``` js
export const b = 2
```

Then use 

``` bash
rollup a.js -o build.js -f iife -m true
```

to compile and after that, in chrome devtool **you can see the breakpoint line is incorrect**.

But If you replace the code `return c['b']` in file `a.js` with `return c.b` , then everything will be ok

**Comment by Rich-Harris** [comment]
Sorry for non-response — closing, as this appears to be fixed in recent versions
