### ISSUE TITLE
Rollup adds some extra imports after building (preserveModules: true)

### ISSUE THREAD

**Issue by fmva** [rollup/rollup#5110]
Hi, I don't understand why rollup adds extra imports after building if I use preserveModules is set up with "true".

The structure of folders: 
![image](https://github.com/rollup/rollup/assets/34112356/ddc9c7a2-e8b3-459b-8f64-399cbf94d9e3)

```
"rollup": "^3.28.1",
"@rollup/plugin-typescript": "^11.1.2",
```

**rollup.config**

```
const typescript = require('@rollup/plugin-typescript');

module.exports = function _rollupFn() {
  return {
    input: './src/utils/index.ts',
    external: [/node_modules/],
    treeshake: false,
    output: [
      {
        dir: './dist',
        format: 'es',
        sourcemap: true,
        preserveModules: true,
      },
    ],
    plugins: [typescript()],
  };
};

```

**src/utils/ModuleA**
```


// boo.ts
import { foo } from '../ModuleB';

export const boo = () => {
  console.warn('boo');
  foo();
};

// index.ts
export * from './boo';
```

**src/utils/ModuleB**
```
// foo.ts
export const foo = () => {
  console.warn('foo');
};

// index.ts
export * from './foo';
```
**src/utils/index.ts**

```
export * from './ModuleA';
export * from './ModuleB';
```

In the final build I have some redundant imports.

The structure of build: 
![image](https://github.com/rollup/rollup/assets/34112356/15bb0b92-8fa9-4a4f-aee8-8375a12f0f16)

**dist/index.js**
```
import './ModuleA/index.js';  // <-- redundant import
import './ModuleB/index.js'; //  <-- redundant import
export { boo } from './ModuleA/boo.js';
export { foo } from './ModuleB/foo.js';
//# sourceMappingURL=index.js.map
```
**dist/ModuleA/boo.js**
```
import '../ModuleB/index.js'; //  <-- redundant import
import { foo } from '../ModuleB/foo.js';

const boo = () => {
    console.warn('boo');
    foo();
};

export { boo };
//# sourceMappingURL=boo.js.map
```

As you can see in the result bundle I have some extra imports. Why does rollup add these imports and is there a way to get rid of these extra imports ?

**Comment by shens3** [comment]
I also encountered the same problem, how did you solve it?

**Comment by chaitanyapotti** [comment]
Facing same issue. How was this solved?
