### ISSUE TITLE
Support new "using" keyword for disposable objects

### ISSUE THREAD

**Issue by hazae41** [rollup/rollup#5113]
### Rollup Version

3.28.1

### Operating System (or Browser)

macOS

### Node Version (if applicable)

20.3.1

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-zruwr9?file=src%2Fmain.ts

### Expected Behaviour

It should build successfully if using TypeScript 5.2 and latest `tslib`, `@rollup/plugin-typescript`

### Actual Behaviour

Error on build: `RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

**Comment by hazae41** [comment]
It also crashes on latest `rollup@4.0.0-13`

`RollupError: Expected ';', '}' or <eof>`

**Comment by TrickyPi** [comment]
For Rollup V3, we need to wait for `acorn.js` to support parsing `using`. But it's in stage 3 for js, I'm not sure the team of `acorn.js` will support it right away. For Rollup V4, which is under development, SWC can parse it with the option `jsc.parser.usingDecl`, I'll take a look at this issue on Rollup V4.

**Comment by hazae41** [comment]
Thanks for the tip, `ES2022` target works! But for people reading this, for some reason `ESNext` doesn't 🤨

**Comment by hazae41** [comment]
https://github.com/microsoft/TypeScript/issues/55609

The issue seems to be related to either `tslib` or `@rollup/plugin-typescript`, since it works in `tsc`

**Comment by dnalborczyk** [comment]
> Thanks for the tip, `ES2022` target works! But for people reading this, for some reason `ESNext` doesn't 🤨

`ESNext` essentially only strips the types, so the runtime you are running the transpiled code in needs to support the `using` syntax. there is no runtime support as of today as far as I know.

**Comment by Hebilicious** [comment]
@TrickyPi I am not familiar at all with the rollup codebase, but do you have any idea on how we could have this supported in rollup 4 ? ie setting usingDecl to true in the internal rollup parser ?
