### ISSUE TITLE
File name extensions not respected with several outputs and entry file names

### ISSUE THREAD

**Issue by jerome-benoit** [rollup/rollup#5117]
### Rollup Version

3.28.1

### Operating System (or Browser)

Linux

### Link To Reproduction

https://github.com/poolifier/poolifier/tree/master/examples/typescript/websocket-server-pool/ws-hybrid

### Expected Behaviour

The intermediate files generated shall respect the `entryFileNames` setting regarding bundled file extensions and import to avoid referencing ESM bundled code into CommonJS bundled code.  

### Actual Behaviour

The link gives an example to reproduce the issue: 

+ comment out 
```
preserveModules: true,
preserveModulesRoot: './src'
```
in both outputs rollup configuration 
+ pnpm build
+ pnpm start

Error at loading `types-<hash>.js` module.

**Comment by lukastaegert** [comment]
The intermediate files you mention do not follow the `entryFileNames` pattern, they follow the [`chunkFileNames`](https://rollupjs.org/configuration-options/#output-chunkfilenames) pattern.

**Comment by jerome-benoit** [comment]
Closed, not a bug.
