### ISSUE TITLE
Tree shaking not occurring correctly in try/catch

### ISSUE THREAD

**Issue by luc122c** [rollup/rollup#5120]
### Rollup Version

3.28.1

### Operating System (or Browser)

stackblitz

### Node Version (if applicable)

16.20.0

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-tree-shake?file=src%2Fmain.js&file=dist%2Fmain.js

### Expected Behaviour

In the linked example, we have two identical functions with an `if` statement which will always execute. Inside the branch, we log a message, then return. After the `if` statement, we log another message. When compiling this function, the second message should be tree-shaken, as the `return` statement would always prevent it from being reached. 

### Actual Behaviour

In the first instance, it is correctly tree shaken. In the second instance, we have placed it inside a try/catch block. Here, the second message is not tree shaken.

**Comment by lukastaegert** [comment]
That is by design and needs to be toggled explicitly: https://rollupjs.org/configuration-options/#treeshake-trycatchdeoptimization

**Comment by luc122c** [comment]
How interesting! Thanks for pointing to the docs :)
