### ISSUE TITLE
RollupError: "TreeshakingPreset" is not exported by node_modules/rollup/dist/rollup.d.ts

### ISSUE THREAD

**Issue by moltar** [rollup/rollup#5128]
I am using `tsup` with the `--dts-resolve` option, which essentially inlines the type into the bundle.

My use case is to inline tsup's own `Options` type for some internal tooling.

I am running into an error in the `rollup` package:

> RollupError: "TreeshakingPreset" is not exported by "../../node_modules/rollup/dist/rollup.d.ts", imported by "node_modules/tsup/dist/index.d.ts".

It happens here:

https://github.com/rollup/rollup/blob/6cb637d07e552c159bcf124dbdf1078a51ef8107/src/rollup/types.d.ts#L506

I can confirm that when I _did_ export it (by editing the file in `node_modules`), the error went away.

Would you be open to exporting this type?

I can add a PR.

**Comment by lukastaegert** [comment]
> Would you be open to exporting this type?

Sure, there is no problem in making this public.
