### ISSUE TITLE
producing invalid export statement

### ISSUE THREAD

**Issue by tyler-johnson** [rollup/rollup#513]
Hello, I have the following ES6 code, nothing fancy:

```js
import Trackr from "trackr";
export { Trackr };
```

When I run rollup on this code (`rollup code.js`), it produces the following ES6 code:

```js
import Trackr from 'trackr';



export { default as Trackr };
```

For some reason it is exporting the Trackr variable as `default`. Attempting to export the Trackr variable as something else results in the same weirdness:

```js
import Trackr from "trackr";
export { Trackr as somethingelse };
```

```js
import Trackr from 'trackr';



export { default as somethingelse };
```

This was run with rollup v0.25.3 and Node.js v5.5.0

**Comment by tyler-johnson** [comment]
FYI, this does work, so it is what I will be using in the mean time:

```js
import _Trackr from "trackr";
export var Trackr = _Trackr;
```
```js
import _Trackr from 'trackr';

var Trackr = _Trackr;

export { Trackr };
```

**Comment by Rich-Harris** [comment]
thanks :+1: fix will be released shortly
