### ISSUE TITLE
Tree shaking not work if module external

### ISSUE THREAD

**Issue by shaodahong** [rollup/rollup#5138]
### Rollup Version

latest

### Operating System (or Browser)

Chrome

### Link To Reproduction

https://rollupjs.org/repl/?version=2.1.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMEVYVEVSTkFMJTIwSU1QT1JUUyU1Q24lMkYlMkYlMjBZb3UlMjBjYW4lMjBpbXBvcnQlMjBleHRlcm5hbCUyMG1vZHVsZXMlMjBpbnRvJTIweW91ciUyMGJ1bmRsZSUyMCVFMiU4MCU5MyU1Q24lMkYlMkYlMjBpdCUyMGRvZXNuJ3QlMjBtYXR0ZXIlMjBpZiUyMHRoZXkncmUlMjBFUzIwMTUlMjBvciUyMGxlZ2FjeSU1Q25pbXBvcnQlMjAlN0JhJTdEJTIwZnJvbSUyMCcuJTJGYSclNUNuJTVDbmNvbnNvbGUubG9nKGEpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlMjQlMjBmcm9tJTIwJ2pxdWVyeSclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwdGVzdCgpJTIwJTdCJTVDbiUyMCUyMCUyNCgnYm9keScpLmh0bWwoJyUzQ2gxJTNFSGVsbG8lMjB3b3JsZCElM0MlMkZoMSUzRScpJTNCJTVDbiU3RCU1Q24lNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwYSUyMCUzRCUyMDElMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyYS5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJhbWQlMjIlMkMlMjJpbnRlcm9wJTIyJTNBJTIyZGVmYXVsdCUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=

### Expected Behaviour

```
define([], function () { 'use strict';

  const a = 1;

  // EXTERNAL IMPORTS

  console.log(a);

});
```

### Actual Behaviour

`jquery` module is unused and should not be in the deps, If that’s the case, in practical projects, if `jquery` is not used but still needs to be loaded.

```
define(['jquery'], function ($) { 'use strict';

  $ = $ && Object.prototype.hasOwnProperty.call($, 'default') ? $['default'] : $;

  const a = 1;

  // EXTERNAL IMPORTS

  console.log(a);

});
```

**Comment by lukastaegert** [comment]
An "unused" module can still have side effects when imported, e.g. it could create global variables. As Rollup cannot know that for external modules, you need to tell it e.g. via `treeshake.moduleSideEffects: 'no-external'`
https://rollupjs.org/repl/?version=2.1.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMEVYVEVSTkFMJTIwSU1QT1JUUyU1Q24lMkYlMkYlMjBZb3UlMjBjYW4lMjBpbXBvcnQlMjBleHRlcm5hbCUyMG1vZHVsZXMlMjBpbnRvJTIweW91ciUyMGJ1bmRsZSUyMCVFMiU4MCU5MyU1Q24lMkYlMkYlMjBpdCUyMGRvZXNuJ3QlMjBtYXR0ZXIlMjBpZiUyMHRoZXkncmUlMjBFUzIwMTUlMjBvciUyMGxlZ2FjeSU1Q25pbXBvcnQlMjAlN0JhJTdEJTIwZnJvbSUyMCcuJTJGYSclNUNuJTVDbmNvbnNvbGUubG9nKGEpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlMjQlMjBmcm9tJTIwJ2pxdWVyeSclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwdGVzdCgpJTIwJTdCJTVDbiUyMCUyMCUyNCgnYm9keScpLmh0bWwoJyUzQ2gxJTNFSGVsbG8lMjB3b3JsZCElM0MlMkZoMSUzRScpJTNCJTVDbiU3RCU1Q24lNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwYSUyMCUzRCUyMDElMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyYS5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJhbWQlMjIlMkMlMjJpbnRlcm9wJTIyJTNBJTIyZGVmYXVsdCUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQSU3QiUyMm1vZHVsZVNpZGVFZmZlY3RzJTIyJTNBJTIybm8tZXh0ZXJuYWwlMjIlN0QlN0QlN0Q=

It is true, however, that in the case that no exports are used, we do not need to create the `$` variable.

**Comment by shaodahong** [comment]
> It is true, however, that in the case that no exports are used, we do not need to create the `$` variable.

@lukastaegert Thanks, and can we determine whether to keep an external module based on the `sideEffects` field? I think ‘no-external’ should not be a global module setting.

**Comment by lukastaegert** [comment]
https://rollupjs.org/configuration-options/#treeshake-modulesideeffects use a function

**Comment by lukastaegert** [comment]
The `node-resolve` plugin will observe the `sideEffects` field. Otherwise, you can also use a function https://rollupjs.org/configuration-options/#treeshake-modulesideeffects
