### ISSUE TITLE
Tree-shaking mistakenly removes IF statement as a dead code (regression since 3.19.0)

### ISSUE THREAD

**Issue by Pr05p3ro** [rollup/rollup#5152]
### Rollup Version

3.29.2

### Operating System (or Browser)

MacOS 13.5.2

### Node Version (if applicable)

v18.16.0

### Link To Reproduction

https://rollupjs.org/repl/?version=3.29.2&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGKiUyMFRSRUUtU0hBS0lORyUyMColMkYlNUNuaW1wb3J0JTIwJy4lMkZtYXRocy5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBjcmVhdGVDYWxsYmFjayhib3gpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMChuZXdWYWx1ZSklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwYm94JTVCMCU1RCUyMCUzRCUyMG5ld1ZhbHVlJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBib3glNUIwJTVEJTNCJTIwJTJGJTJGJTIwQ29tbWVudCUyMHRoaXMlMjBsaW5lJTIwdG8lMjBnZXQlMjBjb3JyZWN0JTIwb3V0cHV0JTVDbiUyMCUyMCU3RCUzQiU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwdGVzdCh2YWx1ZSklMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBib3glMjAlM0QlMjAlNUJudWxsJTVEJTNCJTVDbiUyMCUyMGNvbnN0JTIwY2FsbGJhY2slMjAlM0QlMjBjcmVhdGVDYWxsYmFjayhib3gpJTNCJTVDbiU1Q24lMjAlMjAlMkYlMkYlMjBDYWxsYmFjayUyMGlzJTIwcGFzc2VkJTIwdG8lMjBleHRlcm5hbCUyMGxpYnJhcnklMjB0aGF0JTIwaW5kaXJlY3RseSUyMGNoYW5nZXMlMjBib3glNUIwJTVEJTIwdmFsdWUuJTVDbiUyMCUyMHdpbmRvdy5kb1NvbWV0aGluZyhjYWxsYmFjayUyQyUyMHZhbHVlKSUzQiU1Q24lNUNuJTIwJTIwJTJGJTJGJTIwc2ltcGxpZmljYXRpb24lMjB0byUyMCU2MHJldHVybiUyMGJveCU1QjAlNUQlMjAhJTNEJTIwbnVsbCUzQiU2MCUyMHdpbGwlMjBiZSUyMHByZXNlcnZlZCU1Q24lMjAlMjAlMkYlMkYlMjBob3dldmVyJTIwJTYwaWYlNjAlMjBpcyUyMHdyb25nbHklMjBkZXRlY3RlZCUyMGFzJTIwZGVhZCUyMGNvZGUlNUNuJTIwJTIwaWYlMjAoYm94JTVCMCU1RCUyMCElM0QlMjBudWxsKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjB0cnVlJTNCJTVDbiUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwZmFsc2UlM0IlNUNuJTdEJTVDbiU1Q250ZXN0KDEpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

### Expected Behaviour

`if (box[0] != null) { ... }` statement should be preserved, since `box[0]` is modified in runtime. Correct behaviour in 3.18.0 version: [3.18.0 REPL](https://rollupjs.org/repl/?version=3.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGKiUyMFRSRUUtU0hBS0lORyUyMColMkYlNUNuaW1wb3J0JTIwJy4lMkZtYXRocy5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBjcmVhdGVDYWxsYmFjayhib3gpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMChuZXdWYWx1ZSklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwYm94JTVCMCU1RCUyMCUzRCUyMG5ld1ZhbHVlJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBib3glNUIwJTVEJTNCJTVDbiUyMCUyMCU3RCUzQiU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwdGVzdCh2YWx1ZSklMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBib3glMjAlM0QlMjAlNUJudWxsJTVEJTNCJTVDbiUyMCUyMGNvbnN0JTIwY2FsbGJhY2slMjAlM0QlMjBjcmVhdGVDYWxsYmFjayhib3gpJTNCJTVDbiU1Q24lMjAlMjB3aW5kb3cuZG9Tb21ldGhpbmcoY2FsbGJhY2slMkMlMjB2YWx1ZSklM0IlNUNuJTVDbiUyMCUyMGlmJTIwKGJveCU1QjAlNUQlMjAhJTNEJTIwbnVsbCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwdHJ1ZSUzQiU1Q24lMjAlMjAlN0QlNUNuJTVDbiUyMCUyMHJldHVybiUyMGZhbHNlJTNCJTVDbiU3RCU1Q24lNUNudGVzdCgxKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=)

### Actual Behaviour

Up to version 3.18.0 in the following example (part of the code in REPL) `if (box[0] != null) { ... }` statement was preserved when tree-shaking is enabled.
Starting from version 3.19.0 `if` statement is removed as dead code even if "safest" tree-shaking preset is used.
Reproduced in version 3.29.2 and the only way to get correct output at the moment is to disable tree-shaking entirely.

```
function test(value) {
  const box = [null];
  const callback = createCallback(box);

  window.doSomething(callback, value);

  if (box[0] != null) {
    return true;
  }

  return false;
}
```

**Comment by lukastaegert** [comment]
Thanks for spotting! Your analysis was spot on and very helpful, fix at #5153.
