### ISSUE TITLE
Treeshaking wrongly removes `if` statement

### ISSUE THREAD

**Issue by nicolo-ribaudo** [rollup/rollup#5156]
### Rollup Version

v3.29.3

### Operating System (or Browser)

everywhere

### Link To Reproduction

https://rollupjs.org/repl/?version=3.29.3&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q24lNUNuJTIwZXhwb3J0JTIwZnVuY3Rpb24lMjBidWlsZEVsZW1lbnRDYWxsKHVwZGF0ZVN0YXRlJTJDJTIwc2lkZUVmZmVjdHMpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwc3RhdGUlMjAlM0QlMjAlN0IlMjBwdXJlJTNBJTIwZmFsc2UlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwdXBkYXRlU3RhdGUoc3RhdGUpJTNCJTIwJTJGJTJGJTIwU2V0JTIwc3RhdGUucHVyZSUyMCUzRCUyMHRydWUlNUNuJTIwJTIwJTIwJTIwaWYlMjAoc3RhdGUucHVyZSklMjBzaWRlRWZmZWN0cygpJTNCJTVDbiUyMCUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE

### Expected Behaviour

The `if (state.pure)` statement should not be dropped

### Actual Behaviour

It is dropepd

@lukastaegert Guy told me to ping you :)

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #5158
