### ISSUE TITLE
Preact "does not export Component" (but it does)

### ISSUE THREAD

**Issue by mandx** [rollup/rollup#517]
I've created a test repo [here](https://github.com/mandx/rollup-test-setup). To reproduce the bug, clone that repo, run `npm install` and then run `npm run build:development`.

This may be related to #366 but in this case the loaded file (`node_modules/preact/src/preact.js`) is ES6 code (the Preact package does have a `jsnext:main` entry and Rollup uses it).

This is the content of `node_modules/preact/src/preact.js`:
```js
import h from './h';
import Component from './component';
import render from './render';
import { rerender } from './render-queue';
import options from './options';

export default {
	h,
	Component,
	render,
	rerender,
	options,
	hooks: options
};
```

And this is how I would like to import it (`src/js/index.js`):
```js
/** @jsx h */
import { render, h, Component } from 'preact';

// ...
```
Am I doing something wrong in my Rollup/Babel setup?

**Comment by Victorystick** [comment]
Preact is expiring an object literal, not a set of named exports. This means that you must import Preact as the default import.

```js
import Preact from 'preact';
```

Unfortunately, Preact's approach to its exports doesn't lend itself well to Rollup's tree-shaking. A better approach would be for Preact to do this instead.

```js
export { default as h } from './h';
export { default as Component } from './component';
export { default as render } from './render';
export { rerender } from './render-queue';
export { default as options, default as hooks } from './options';
```

**Comment by mandx** [comment]
I understand, thanks for the explanation! Now that I think of it, I can always directly import what I need from Preact, like this:

```js
import h from 'preact/src/h';
import Component from 'preact/src/component';
import render from 'preact/src/render';
// ...
```

**Comment by woleicom** [comment]
If it's open source libraries? Don't want to modify the open source library code
react-router.js：
```js
/* components */
import _Router from './Router';
export { _Router as Router };
import _Link from './Link';
export { _Link as Link };
import _IndexLink from './IndexLink';
export { _IndexLink as IndexLink };
import _withRouter from './withRouter';
export { _withRouter as withRouter };
````

my app.js
```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Router,Route ,browserHistory } from 'react-router';
const { render } = ReactDOM;

import App from './components/App';
render(
    (<Router history={browserHistory}>
        <Route path="/" component={App}>
        </Route>
    </Router>), document.getElementById('content'));
```

build console：
···
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Module E:\work\rollup\node_modules\react\react.js does not export PropTypes (imported by E:\work\rollup\node_modules\react-router\es6\InternalPropTypes.js)
    at Module.trace (E:\work\rollup\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:6230:29)
    at E:\work\rollup\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:5770:34
    at Array.forEach (native)
    at E:\work\rollup\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:5767:24
    at Array.forEach (native)
    at Module.bindAliases (E:\work\rollup\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:5756:28)
    at E:\work\rollup\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:7279:62
    at Array.forEach (native)
    at E:\work\rollup\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:7279:19

···

This kind of grammar no solution？
