### ISSUE TITLE
object dot notation in aliased variable imports throws error

### ISSUE THREAD

**Issue by petulla** [rollup/rollup#518]
hi all

An import that uses object dot property notation throws an error. E.g.,: 

```
import {
  select as window.mylib.select
} from "lib-select";
```

This throws: `Unexpected token`.

I'm wondering if this an issue that needs addressing or is just how es2015 will be. Thanks.

**Comment by Victorystick** [comment]
That is indeed a syntax error, as per the ES2015 spec.

I'm not sure what your trying to accomplish by `window.mylib.select` though. Do you mean to import `select` _from_ `window.mylib`? In that case, write

```js
import select from 'select';
```
and configure Rollup to locate the global using

```js
export default {
  ...
  globals: {
    'select': 'window.mylib.select'
  }
};
```
