### ISSUE TITLE
Which extra binary is needed for 4.0?

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/rollup#5181]
### Documentation is

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not sure?

### Please Explain in Detail...

The release notes for 4.0 at https://github.com/rollup/rollup/releases/tag/v4.0.0 contain:

> The NodeJS build now relies on an optional native binary; for unsupported platforms, users can use the @rollup/wasm-node package that has the same interface as Rollup but relies on WASM artifacts (https://github.com/rollup/rollup/pull/5073)

Please adjust the release notes and mention which is this optional native binary.

Moreover, the word “relies” implies for me that the binary (or a substitute for it) must be present, while the wording “optional native binary” means that the binary can be absent without substitution.

### Your Proposal for Changes

Consider wording like:

> NodeJS build now requires ABC, either as native binary, or as WASM artifact.

**Comment by lukastaegert** [comment]
The point is that you should not need to care about this as Rollup will install the correct one if one is available, just like esbuild would. Maybe this is indeed too confusing.

**Comment by dilyanpalauzov** [comment]
For me it is unclear how shall I install what system-wide, so that during the upgrade to the next minor rollup version, rollup does remove whatever programmes (then unnecessary) it has installed.

**Comment by lukastaegert** [comment]
Yes exactly. There is nothing to install, it is just another npm dependency. I will update the wording.

**Comment by lukastaegert** [comment]
How about:

Rollup now includes native code that is automatically installed (and removed) as an [optional npm dependency](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies) if your platform and architecture is supported. More precisely, Rollup has a list of `optionalDependencies`, each of which only install on a specific [`os`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#os) and [`cpu`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#cpu). If your system is not supported, you will receive an error message when starting Rollup that will tell you about your platform and architecture and gives you a list of supported ones. In that case, you can instead use `@rollup/wasm-node` as a platform-independent drop-in replacement.

See #5186.

**Comment by dilyanpalauzov** [comment]
This ticket was about the release nozes at https://github.com/rollup/rollup/releases/tag/v4.0.0 .  The release notes there were not changed.
