### ISSUE TITLE
Cannot build node application using the @opentelemetry/opentelemetry-js package

### ISSUE THREAD

**Issue by vpmedia** [rollup/rollup#5185]
### Rollup Version

v4.0.2

### Operating System (or Browser)

MacOS 14.0

### Node Version (if applicable)

v20.8.0

### Link To Reproduction

https://github.com/vpmedia/express-template/actions/runs/6449937820/job/17508799059

### Expected Behaviour

Build completes.

### Actual Behaviour

Build throws exception.

Repro project:
https://github.com/vpmedia/express-template

Also reported this issue for the library authors:
https://github.com/open-telemetry/opentelemetry-js/issues/4191

With Rollup v3.29.4 it works..

**Comment by TrickyPi** [comment]
The behavior of V3 is the same as V4. The issue lies in your 'external' configuration, which doesn't cover all dependencies. Consider using '/node_modules/' instead.

**Comment by vpmedia** [comment]
@TrickyPi Thanks, working!
