### ISSUE TITLE
Invalid Peer-dependency range for @rollup/plugin-utils and v4

### ISSUE THREAD

**Issue by runspired** [rollup/rollup#5188]
### Rollup Version

v4.0.2

### Operating System (or Browser)

MacOS Ventura 13.6

### Link To Reproduction

if needed will build later

A failed dependency bump with this issue may be observed here https://github.com/emberjs/data/pull/8970

### Expected Behaviour

latest @rollup/plugin-babel works with lates rollup (v4)

### Actual Behaviour

Install results in this error:

```
└─┬ @rollup/plugin-babel 6.0.4
  └─┬ @rollup/pluginutils 5.0.4
    └── ✕ unmet peer rollup@^1.20.0||^2.0.0||^3.0.0: found 4.0.2
```

**Comment by TrickyPi** [comment]
Reinstall `@rollup/plugin-babel`. The latest version of `@rollup/pluginutils` is `5.0.5`, and its peerDependency rollup field include `^4.0.0`.
