### ISSUE TITLE
show the previous build size diff when build summary is shown?

### ISSUE THREAD

**Issue by mtariqsajid** [rollup/rollup#5193]
### Feature Use Case

is it possible to show previous and current build size diff just like react-scripts show when new build is finish
![image](https://github.com/rollup/rollup/assets/68206359/5923b05a-8290-4f06-9dc8-cc1e10ebdd75)

### Feature Proposal

show the build size diff of current and previous

**Comment by lukastaegert** [comment]
You can write a plugin to do that. Otherwise, I see this as out-of-scope for Rollup core at the moment.

**Comment by mtariqsajid** [comment]
> You can write a plugin to do that. Otherwise, I see this as out-of-scope for Rollup core at the moment.

thanks for your reply
