### ISSUE TITLE
Failed to run on arm platforms

### ISSUE THREAD

**Issue by joshuaavalon** [rollup/rollup#5194]
### Rollup Version

4.0.2

### Operating System (or Browser)

Alpine 3.18

### Node Version (if applicable)

18.18.1

### Link To Reproduction

https://github.com/joshuaavalon/rollup-arm-bug

### Expected Behaviour

Build successfully like other platforms.

### Actual Behaviour

When you use `node:18-alpine` Docker and target platform like `linux/arm/v6` and `linux/arm/v7`, it show the following error.

https://github.com/joshuaavalon/rollup-arm-bug/actions/runs/6490693336/job/17626861855

> #24 31.37 > rollup-arm-bug@1.0.0 build
#24 31.37 > rollup -c
#24 31.37 
#24 33.63 node:internal/modules/cjs/loader:1[340](https://github.com/joshuaavalon/rollup-arm-bug/actions/runs/6490693336/job/17626861855#step:7:345)
#24 33.63   return process.dlopen(module, path.toNamespacedPath(filename));
#24 33.63                  ^
#24 33.63 
#24 33.63 Error: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /app/node_modules/@rollup/rollup-linux-arm-gnueabihf/rollup.linux-arm-gnueabihf.node)
#24 33.63     at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
#24 33.63     at Module.load (node:internal/modules/cjs/loader:1119:32)
#24 33.63     at Module._load (node:internal/modules/cjs/loader:960:12)
#24 33.63     at Module.require (node:internal/modules/cjs/loader:1143:19)
#24 33.63     at require (node:internal/modules/cjs/helpers:119:18)
#24 33.63     at Object.<anonymous> (/app/node_modules/rollup/dist/native.js:49:36)
#24 33.63     at Module._compile (node:internal/modules/cjs/loader:1256:14)
#24 33.63     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
#24 33.63     at Module.load (node:internal/modules/cjs/loader:1119:32)
#24 33.63     at Module._load (node:internal/modules/cjs/loader:960:12) {
#24 33.63   code: 'ERR_DLOPEN_FAILED'
#24 33.63 }

**Comment by sschultze** [comment]
On Windows ARM64 (with ARM64 Node.js), `process.dlopen` fails as well. A good workaround is using `@rollup/wasm-node` instead.

**Comment by lukastaegert** [comment]
It looks like the problem is that we do not have a MUSL build for regular `arm` architectures (i.e. not arm64). I will have a look in the next days if we can set one up.

**Comment by newives** [comment]
The same problem occurs on Windows. Vite relies on rollup, causing the Vite project to fail to run.

<img width="478" alt="图片" src="https://github.com/rollup/rollup/assets/81661030/02b53757-e2aa-42db-85f1-db8535ba91ef">

<img width="649" alt="图片" src="https://github.com/rollup/rollup/assets/81661030/9173949d-d92d-4da3-8b32-b0c0c401eafd">

**Comment by morpheus-87** [comment]
I've got another error on my Raspberry Pi:
```
> tsc && vite build

node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /drone/src/node_modules/@rollup/rollup-linux-arm-gnueabihf/rollup.linux-arm-gnueabihf.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/drone/src/node_modules/rollup/dist/native.js:60:48)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.16.0
```

Is this caused by the same issue?

**Comment by lukastaegert** [comment]
Probably. Unfortunately, I was not able to cross-compile an ARM Linux build for MUSL systems, which yours likely is. I would have hoped you get a better error with latest Rollup, though, which should point you to use the WASM build.

**Comment by morpheus-87** [comment]
Thank you very much for the clarification! How could I achieve a WASM build with Vite?

**Comment by patak-dev** [comment]
@morpheus-87, if you are using `pnpm`, you can add an [override](https://pnpm.io/package_json#pnpmoverrides) in your package.json:
```json
  "pnpm": {
    "overrides": {
      "rollup": "npm:@rollup/wasm-node"
    }
  }
```
Other package manager have similar features ([npm](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides), [yarn](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/))

**Comment by morpheus-87** [comment]
Thanks for your help, @patak-dev , it works like a charm 🥳  because I'm using `npm`, I had to add the following snippet to my `package.json`:
```
"overrides": {
    "vite": {
      "rollup": "npm:@rollup/wasm-node"
    }
  }
```

**Comment by BeycanDeveloper** [comment]
@morpheus-87 this not working for me also i cannot install this package on my docker container

@patak-dev can you help me?

`"overrides": {
  "vite": {
    "rollup": "npm:@rollup/wasm-node"
  }
}`

**Comment by silvenon** [comment]
It doesn't work for me either 😕 I tried the following just in case, I tried overriding it all the way as well just in case:

```json
"overrides": {
  "rollup": "npm:@rollup/wasm-node"
}
```

Ensured that it was indeed overridden:

```
❯ npm why rollup
rollup@4.9.1 dev overridden
node_modules/rollup
  overridden rollup@"npm:@rollup/wasm-node" (was "^4.2.0") from vite@5.0.10
  node_modules/vite
  ...
```

But getting the same error:

```
Error: Cannot find module @rollup/rollup-linux-arm64-musl.
```

Using `node:18-alpine` Docker image.

**Comment by BeycanDeveloper** [comment]
@silvenon you can try yarn, this working.

**Comment by silvenon** [comment]
What did work was specifying a version higher than what my `rollup` previously was:

```json
"overrides": {
  "vite": {
    "rollup": "npm:@rollup/wasm-node@^4.9.2"
  }
}
```

My `rollup` was previously `4.9.1`. I have no idea why this works, it seems like a bug with npm and `overrides`, like it only "notices" them if there's something new.

Now building my app passes 🥳

**Comment by filipbekic01** [comment]
Can't manage to run it.

**Comment by connorfinnigan512** [comment]
It may not be applicable to everyone's projects, but what finally solved this for me was changing this to this in my Dockerfile:

`FROM node:20-alpine AS builder`
->
`FROM node:latest AS builder`

**Comment by Reeska** [comment]
Today I upgraded to latest vite version and I got this issue on Gitlab CI, with this stack trace:
```
> vite build
/builds/front-js-components/ocs/ocs-apps/apps/ocs-stb/node_modules/rollup/dist/native.js:87
		throw new Error(
		      ^
Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4[82](https://gt.ocs.fr/front-js-components/ocs/ocs-apps/-/jobs/161001#L82)8). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/builds/front-js-components/ocs/ocs-apps/apps/ocs-stb/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/builds/front-js-components/ocs/ocs-apps/apps/ocs-stb/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
```

I try to override rollup version used by vite with the following trick, but it didn't change anything:
```
  "overrides": {
    "vite": {
      "rollup": "npm:@rollup/wasm-node"
    }
  }
```

**Comment by citrusjunoss** [comment]
How can I fix it, I don't want to delete the lock file, which would cause a dependency on version upgrades, which would create new problems.

`> node ./scripts/build.mjs --appid=$npm_config_appid --pipeid=$npm_config_pipeid --domain=$npm_config_domain
/builds/open/frontend/open-api-doc/node_modules/rollup/dist/native.js:87
		throw new Error(
		      ^
Error: Cannot find module @rollup/rollup-linux-x64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/builds/open/frontend/open-api-doc/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/builds/open/frontend/open-api-doc/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:[35](https://gitlab.qizhidao.com/open/frontend/open-api-doc/-/jobs/4957577#L35)6:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-musl'
  Require stack:
  - /builds/open/frontend/open-api-doc/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at requireWithFriendlyError (/builds/open/frontend/open-api-doc/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/builds/open/frontend/open-api-doc/node_modules/rollup/dist/native.js:96:76)
      at Module._compile (node:internal/modules/cjs/loader:1[37](https://gitlab.qizhidao.com/open/frontend/open-api-doc/-/jobs/4957577#L37)6:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
      at Module.load (node:internal/modules/cjs/loader:1207:32)
      at Module._load (node:internal/modules/cjs/loader:1023:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/builds/open/frontend/open-api-doc/node_modules/rollup/dist/native.js'
    ]
  }
}
Node.js v20.11.0`

**Comment by sapphi-red** [comment]
I was able to build for armv7 musl by adding `'armv7-unknown-linux-musleabihf': 'arm-linux-musleabihf'` to https://github.com/napi-rs/napi-rs/blob/8eea78054a557be7532288f450b7efa0507223be/cli/src/build.ts#L29-L41, but it stuck on https://github.com/nodejs/docker-node/issues/1798 when running tests for napi-rs. Given that [armv7 musl isn't included in tier 1 or tier2 support of Node.js](https://github.com/nodejs/node/blob/main/BUILDING.md#platform-list), it might break any time and I guess adding a build for this would cause a big maintenance burden.

**Comment by lukastaegert** [comment]
> it might break any time

Only if we change the rust version too often. As it stands, we did not do that more than once, and I do not plan on doing it too often. So I would not see that as an argument, but apparently there is some demand for that platform.

**Comment by juliusiqbal** [comment]
I had to use in package.json file and remove node_modules folder and run npm install.

```json
"overrides": {
    "vite": {
      "rollup": "npm:@rollup/wasm-node"
    }
  }
```

I had to run below commands for dockerized app where `npm i` should run inside container.

```bash
docker compose run reusebin-ui npm i && \
  docker compose down && \
  rm -rf node_modules && \
  docker compose up --build
```

**Comment by sapphi-red** [comment]
> > it might break any time
> 
> Only if we change the rust version too often. As it stands, we did not do that more than once, and I do not plan on doing it too often. So I would not see that as an argument, but apparently there is some demand for that platform.

It's not only rust, but also the node version needs to be fixed. After upgrading node version a test might fail.
Made a PR upstream: https://github.com/napi-rs/napi-rs/pull/2019, https://github.com/napi-rs/napi-rs/pull/2020

**Comment by lukastaegert** [comment]
Now that I actually managed to add smoke tests for (emulated) ARM v7 to the pipeline, I think I see what you mean. Of course it could also be a bug in the emulator, but the MUSL version does not run, not because of Rollup but because running `npm` itself just hangs and does not recover. The GNU version runs fine, though: https://github.com/rollup/rollup/actions/runs/8774450926/job/24075678218

**Comment by connorfinnigan512** [comment]
I encountered this again and was able to resolve by running npm install from inside the container:
`docker compose run {your_service_name} npm install`

**Comment by Alletkla** [comment]
> What did work with npm was specifying a version higher than what my `rollup` previously was:
> 
> "overrides": {
>   "vite": {
>     "rollup": "npm:@rollup/wasm-node@^4.9.2"
>   }
> }
> My `rollup` was previously `4.9.1`. I have no idea why this works, it seems like a bug with npm and `overrides`, like it only "notices" them if there's something new, otherwise it doesn't update `package-lock.json`.
> 
> Now building my app works! 🥳

Deleting package-lock and running npm  again, also worked.

It seems there need to be a version change to update package.lock (which makes kind of sense, but not in this special case)
