### ISSUE TITLE
Cannot find module 'rollup/parseAst' or its corresponding type declarations.

### ISSUE THREAD

**Issue by sagargurtu** [rollup/rollup#5199]
### Rollup Version

v4.0.2

### Operating System (or Browser)

Chrome

### Link To Reproduction

https://stackblitz.com/edit/parseast-error?file=src%2Fmain.ts,tsconfig.json

### Expected Behaviour

Importing from `'rollup/parseAst'` should not throw error.

### Actual Behaviour

Importing from `'rollup/parseAst'` throws the following error:
```
Cannot find module 'rollup/parseAst' or its corresponding type declarations.
```

**Comment by lukastaegert** [comment]
Unfortunately, this only works if you set `"moduleResolution": "node16"` (or "bundler") in your tsconfig.json.

**Comment by sagargurtu** [comment]
`"node16"` has its own set of issues. Reproduction: https://stackblitz.com/edit/parseast-error-gfgsbm?file=src%2Fmain.ts

See https://github.com/microsoft/TypeScript/issues/50058

**Comment by TrickyPi** [comment]
One workaround, Setting `"moduleResolution": "Bundler"` in your tsconfig.json.

**Comment by skhaz** [comment]
I am still experiencing this issue. Why has it been closed?

**Comment by okinawaa** [comment]
me too still experiencing this issue.

**Comment by lukastaegert** [comment]
> I am still experiencing this issue. Why has it been closed?

Because everything is working as intended and setting `moduleResolution: "bundler"` or `"node16"` fixes it. If you cannot do that for some reason, you can instead try to import from `"rollup/dist/parseAst"` or `"rollup/dist/parseAst.js"`, which is the actual file location.

**Comment by dirkluijk** [comment]
Note that this is breaking for anyone having a TS project with ES modules using `rollup` as transitive dependency. For example, I am using `vitest`, which depends on `vite`, which has an import for `rollup/parseAst` that breaks for me.

My workaround now is to add a custom mapping in my `tsconfig.json`:
```json
"paths": {
  // workaround for: https://github.com/vitest-dev/vitest/issues/4567
  "rollup/parseAst": ["./node_modules/rollup/dist/parseAst"]
}
```

I am not an export in module systems in the JavaScript ecosystem. Should I report this with Vitest?

**Comment by dirkluijk** [comment]
Never mind, adding `"skipLibCheck": true` resolved the issue for me and doesn't require any hacky workaround.

**Comment by skhaz** [comment]
`skipLibCheck` is a hack IMO.

**Comment by jordi-studyportals** [comment]
I ran into this issue while using vitest. I got the rollup error because vitest was using vite, so I couldn't change the import.
`node_modules/vite/dist/node/index.d.ts:5:41 - error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.`

My problem was caused tsc because my test folder and vitest.config.ts file were included into the typescript build of my project by accident. I had to add the folder and the vitest.config.ts file to the exluded items in my tsconfig and that resolved the issues for me.

**Comment by dirkluijk** [comment]
As suggested by @jordi-studyportals, I removed `skipLibCheck: true` and added `"vitest.config.ts"` and  `"**/**.test.ts"` to my tsconfig `exclude` list instead. That did the trick.

**Comment by reachAkash** [comment]
first set "module" : "ES2015" then "moduleResolution" : "Bundler" in tsconfig.json file. It'll fix the issue, atleast fixed for me.

**Comment by skhaz** [comment]
Not every project can do those chances.

The wrong here is the library.

**Comment by luunox** [comment]
If you use the tsconfig by vite then change the file content of "tsconfig.json"

from:

```
{
  "references": [{ "path": "tsconfig.app.json" }, { "path": "tsconfig.node.json" }]
}
```

to:

```
{
  "extends": ["./tsconfig.app.json", "./tsconfig.node.json"]
}
```

**Comment by MagdalenaTyminska** [comment]
> > I am still experiencing this issue. Why has it been closed?
> 
> Because everything is working as intended and setting `moduleResolution: "bundler"` or `"node16"` fixes it. If you cannot do that for some reason, you can instead try to import from `"rollup/dist/parseAst"` or `"rollup/dist/parseAst.js"`, which is the actual file location.

The problem is, that it doesn't.
At least to me.



> If you use the tsconfig by vite then change the file content of "tsconfig.json"
> 
> from:
> 
> ```
> {
>   "references": [{ "path": "tsconfig.app.json" }, { "path": "tsconfig.node.json" }]
> }
> ```
> 
> to:
> 
> ```
> {
>   "extends": ["./tsconfig.app.json", "./tsconfig.node.json"]
> }
> ```

tried this too to no avail.

The other solutions were for `vitest` which I don't use.

For me the issue still exists and seems there is no working solution to that - at least I haven't found one.

**Comment by arevno** [comment]
moduleResolution: "bundler" does NOT address this issue for Vite.

**Comment by mrmgomes** [comment]
> moduleResolution: "bundler" does NOT address this issue for Vite.

If you have a path reference to "**./tsconfig.node.json**" in your tsconfig.json file, you have to change the moduleResolution to "bundler" on that **tsconfig.node.json** file. Changing on tsconfig.json won't do anything.

It worked for me.

**Comment by nimobeeren** [comment]
Adding `"skipLibCheck": true` to `tsconfig.json` worked for me.

I started encountering this issue after installing `vitest` and adding some tests. My app doesn't use `vite`, it's an Azure Functions app. My working tsconfig:

```jsonc
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "strict": true,
    "allowJs": true,
    "maxNodeModuleJsDepth": 1,
    "lib": [], // don't include the default DOM lib since we're in Node.js
    "resolveJsonModule": true,
    "skipLibCheck": true
  },
  "include": ["src/", "test/", "vitest.config.ts"]
}
```

**Comment by yunylz** [comment]
still occurs

**Comment by Griffork** [comment]
Still occurs.

**Comment by spirin22** [comment]
Both approaches worked for me:

- https://github.com/rollup/rollup/issues/5199#issuecomment-2374040117
- https://github.com/rollup/rollup/issues/5199#issuecomment-2643123630

**Comment by netra-goswami** [comment]
> > moduleResolution: "bundler" does NOT address this issue for Vite.
> 
> If you have a path reference to "**./tsconfig.node.json**" in your tsconfig.json file, you have to change the moduleResolution to "bundler" on that **tsconfig.node.json** file. Changing on tsconfig.json won't do anything.
> 
> It worked for me.

it works for me Thanks

**Comment by colinbes** [comment]
I have tried all iterations in this post and none of them work for me.
Vite 6.3.5, vitest 3.1.3

**Comment by lukasapp** [comment]
What helped me solve the issue (without `skipLibCheck`) is by defining a custom path for `rollup/parseAst` in your `compilerOptions.paths`:

File `tsconfig.json`
```
{
  "compilerOptions": {
    // ... other compiler options

    "paths": {
      "rollup/parseAst": ["./node_modules/rollup/dist/parseAst"]
    }
  }
}
```

Hope this is helpful for anyone landing on this thread.
