### ISSUE TITLE
iife bundle for the browser with $ and jQuery undefined

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#520]
I'm not sure if related: https://github.com/rollup/rollup/issues/59#issuecomment-124151031

My goal is to create an `iife` bundle with all my assets for the browser.  I'm successfully bundling, but my dependencies require `jQuery` are failing, one such is [jquery-ujs](https://github.com/rails/jquery-ujs/blob/master/src/rails.js)

I'm using [`nodeResolve , commonjs, babel`](https://github.com/rollup/rollup/issues/519#issuecomment-184907595) plugins to rollup the `iife` format (which appears successful on the surface).   Both `jquery` and `jquery-ujs` are in the resulting bundle, but it appears I'm not exporting it properly or making it available in the proper way.  Adding `globals: { 'jquery': 'jQuery' }` had no affect.

Any guidance on making jQuery available in my bundle?

**Comment by TrySound** [comment]
@rosskevin Globals option is for
```js
import $ from 'jquery';
```
to
```js
var $ = jQuery;
```
jQuery is global variable defined out of bundle.

**Comment by rosskevin** [comment]
@TrySound - I'm not quite following. 

I would expect I want at the top of my bundle the global:
```
var jQuery = (function() ...
var $ = jQuery
```

Which would make both `jQuery` and `$` available to the rest.  How do I achieve that?

**Comment by TrySound** [comment]
Globals means global variables which will be associated with your import path. Not something global in your bundle.

**Comment by rosskevin** [comment]
If I do this:
```javascript
import $ from 'jquery'
var jQuery = $
```

I see `var jquery=__commonjs(function(module,exports,global){` and `var jQuery$1 = require$$0;` in my iife bundle.

**Comment by rosskevin** [comment]
Ok, so can I define a global?  How can I make `$` and `jQuery` available as a global?  Am I missing some kind of export syntax?

**Comment by TrySound** [comment]
You can add script tag with jQuery before your bundle.

**Comment by rosskevin** [comment]
Ok, certainly I could unbundle jQuery, which might make sense anyway based on cdn caching strategies...I'll do that.

For sake of my understanding because I feel like a blind man using rollup, is there a way for my entry point to export a global `var x = 1`?

**Comment by TrySound** [comment]
@rosskevin `window.x = 1`?

**Comment by rosskevin** [comment]
That's not really creating a new global though, just attaching to the window global.  

It's ok, was just curious.

**Comment by TrySound** [comment]
@rosskevin You can use also
https://github.com/rollup/rollup/wiki/JavaScript-API#introoutro

**Comment by rosskevin** [comment]
Is there any way to use `intro` to load a bundled jquery?  The reason I ask is that I'd like to keep dependency management in one spot and bundling it does that for me.

**Comment by TrySound** [comment]
You can use plugin api for this.

**Comment by sachse** [comment]
Hi @rosskevin, I'm curious if you could share what your solution to this ended up being?

**Comment by rosskevin** [comment]
I think I loaded it globally but cannot remember.  Please peruse https://github.com/FezVrasta/bootstrap-material-design/tree/v4-dev

**Comment by fahmilatib** [comment]
@sachse @rosskevin 

I think this is what you guys are looking for? https://github.com/rollup/rollup/issues/592#issuecomment-205783255

**Comment by bschwartz757** [comment]
@rosskevin @TrySound just wondering if you found a good way to do this. I tried the relevant bits from bootstrap-material-design: https://github.com/FezVrasta/bootstrap-material-design/blob/master/rollup.config.js, specifically the `globals`, `external`, and `cjs({...})` parts, but I'm still not able to reference jquery in my bundle (i.e., all of the following result in `undefined`):
// main.js
```
(function($) {
  console.log("jquery: ", $);
})(window.jquery);
var $ = window.jquery;
console.log("jquery: ", window.$);
console.log("jQuery: ", $);
```

My rollup.config, for reference: 
```
import svelte from "rollup-plugin-svelte";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import buble from "rollup-plugin-buble";
import uglify from "rollup-plugin-uglify";

const production = !process.env.ROLLUP_WATCH;

export default {
  input: "src/main.js",
  output: {
    sourcemap: true,
    format: "iife",
    name: "app",
    file: "public/js/bundle.js"
  },
  globals: {
    jquery: "jQuery",
    "popper.js": "Popper"
  },
  external: ["jquery", "popper.js"],
  plugins: [
    svelte({
      dev: !production,
      css: css => {
        css.write("public/css/bundle.css");
      }
    }),
    resolve(),
    commonjs({
      include: ["node_modules/bootstrap/**", "node_modules/jquery/**"],
      namedExports: {
        "node_modules/jquery/dist/jquery.js": "jquery"
      }
    }),
    production && buble({ exclude: "node_modules/**" }),
    production && uglify()
  ]
};
```
