### ISSUE TITLE
Questions when bundling with vite html template

### ISSUE THREAD

**Issue by katanazero86** [rollup/rollup#5200]
```
<script type="module" src="./cart.js"></script>
```

```
<script src="./cart.js"></script>
```

We are conducting project practice using the vite html template.

If you are curious, if you specify module, the corresponding js file output is generated when building.

On the other hand, if you just load the script, the corresponding js file will not be created at build time.

I wonder what the reason is.

I am also curious if there is a setting related to this in rollup.

thank you

**Comment by lukastaegert** [comment]
This is entirely handled by Vite. Rollup core has no logic to handle HTML files.

**Comment by katanazero86** [comment]
> This is entirely handled by Vite. Rollup core has no logic to handle HTML files.

rollup bundle not html !
thank you :)
