### ISSUE TITLE
How to code share when I need a UMD or IIFE build (no usage of ES import statements)

### ISSUE THREAD

**Issue by supermacro** [rollup/rollup#5212]
## Context

I am building a chrome extension. For those who don't know, chrome extensions have differente entry-points and as such have different bundles:

- content scripts (JS that is injected into the DOM for each tab)
- background scripts (JS that runs as a single centralized service worker in the background and can pass messages to the individual content scripts) 
- ... and a few other kinds of JS / HTML

I've configured my vite / rollup configuration to spit out one IIFE bundle per entrypoint above (e.g. one bundle for the content script, one bundle for the background script, etc). And all works well.

## Problem

I would like to start sharing code between the content scripts and background script. The issue I am having is that the moment code is being shared from, say, a `shared` dir, then the bundle begins to contain ES module `import` statements - which I want to avoid. The JS then fails to run because the browser does not recognize this ES `import` statement. Even if it did understand it, I don't want to do async imports anyways - I just want a single bundle.

## Supporting files:

- https://gitlab.com/giioo/vite-rollup-issue-repro 
    - I created a repository that reproduces this very issue. When you run `npm run build` you will see that the bundles contain `import` statements. 
- images (see attached)

# Question

How do I ensure that my bundles continue to be a single IIFE / UMD build even when I start sharing code?

### Images
![image](https://github.com/rollup/rollup/assets/10621548/ddd7ed59-645b-4b3e-9cb3-cde9cd31588c)

**Comment by TrickyPi** [comment]
One common approach is to create a Rollup build process for each input entry. Another approach is to write a plugin to handle shared files, similar to the example in this link https://github.com/TrickyPi/github-contributions-colorful/blob/fe3090f4428a850e53752410aedf8e35892d12c9/vite.config.ts#L25-L43

**Comment by xsfunc** [comment]
same problem

**Comment by supermacro** [comment]
I ended up just creating a dedicated build processes for each input file in a programmatic fashion using vite's `build` function:

![image](https://github.com/rollup/rollup/assets/10621548/5c66f85d-1665-4ef4-b0bf-8e7439069b12)
