### ISSUE TITLE
Using rollup with webpack in web app

### ISSUE THREAD

**Issue by borisirota** [rollup/rollup#522]
Its more a question than issue.

I would like to use rollup for its tree shaking and minimal bundle size (compare to alternatives) capabilities for JS files in my project as a pre step before running webpack to bundle it with other assets (css, images, etc.).

Currently, rollup is failing because it doesn't understand css syntax.

Is it possible to achieve only js [,jsx] bundling and ignore all other file types (treat it as external) without specifying each file's path in the externals array (which can be very tedious) ? treat it exactly like node_modules without the node-resolve plugin.

Maybe something like [webpack's resolve.extensions](https://webpack.github.io/docs/configuration.html#resolve-extensions).

Thanks

**Comment by Victorystick** [comment]
It may make sense to provide a function to the `external` option, or to let the `external` array contain functions. That way, you could do:

```js
export default {
  ...
  external: [
    function ( id ) { return id.endsWith( '.css' ); }
  ]
};
```

**Comment by egoist** [comment]
Any news on this feature? 🤔

**Comment by travi** [comment]
I also have this use case, but for `.scss` files. I like the proposal of providing a function, but also wonder if a glob, like `**/*.scss`, could be supported. From the config perspective at least, that approach seems a bit simpler.

**Comment by Rich-Harris** [comment]
A good workaround in the meantime might be to use `glob.sync`:

```js
// rollup.config.js
import { resolve } from 'path';
import { sync as glob } from 'glob';

export default {
  ...,
  external: glob( '**/*.css' ).map( file => resolve( file ) ).concat( 'otherExternal' )
};
```

That would automatically exclude all .css files.

I don't think an equivalent to `resolve.extensions` makes sense, because that feature is designed to allow you to write broken code (by skipping the file extension). Adding built-in glob support would add a lot of complexity for something that's a fairly niche feature.

I *do* like the idea of allowing `external` to be a function though.

**Comment by travi** [comment]
Thanks. That's basically where I landed last night, but I hadn't made it back here yet to include the suggestion.

**Comment by Rich-Harris** [comment]
In 0.26.5 you can supply a function instead of an array for `options.external`, so I've closed this. Thanks all

**Comment by travi** [comment]
Very helpful update. Mind including details [in the wiki](https://github.com/rollup/rollup/wiki/JavaScript-API#external) that covers options for `external`?

**Comment by Rich-Harris** [comment]
done 👍

**Comment by borisirota** [comment]
Awesome 👍  Thanks !
