### ISSUE TITLE
How to auto import other file?

### ISSUE THREAD

**Issue by QC2168** [rollup/rollup#5242]
I have two js files, main.js need to use preload.js, but now package the main file, preload file will not be packaged

How do I achieve this
```js
// main.js
const preload = join(__dirname, "./preload.js");
const createWindow = async () => {
  const win = utools.createBrowserWindow("./index.html", {
    webPreferences: {
      preload
    }
  });
};
```
```js
// preload.js
console.log('preload.js')
```

**Comment by irisu-white** [comment]
The "preload.js" file is not an imported module in "main.js", so rollup will not resolve and bundle it. You can use the "rollup-plugin-copy" plugin to copy the "preload.js" file to your output directory.

**Comment by QC2168** [comment]
Thanks
