### ISSUE TITLE
[!] (plugin commonjs--resolver) RollupError: Identifier "fn" has already been declared

### ISSUE THREAD

**Issue by coderaiser** [rollup/rollup#5247]
### Rollup Version

4.4.0

### Operating System (or Browser)

mac os

### Node Version (if applicable)

v20.9.0

### Link To Reproduction

https://github.com/putoutjs/bundle

### Expected Behaviour

Build without errors

### Actual Behaviour

<img width="865" alt="image" src="https://github.com/rollup/rollup/assets/1573141/554e0d97-aabd-44b4-a793-88f0577af25d">

Everything works good with `Rollup` `v4.3.1`

**Comment by sapphi-red** [comment]
Umm, it seems the error comes from this part.
https://github.com/FredKSchott/rollup-plugin-polyfill-node/blob/eb507a21ad82236255988548dea6120d7a277de2/polyfills/util.js#L588-L640

minimal repro: [1](https://rollupjs.org/repl/?version=4.4.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBwcm9taXNpZnkoKSUyMCU3QiU1Q24lMjAlMjBpZiUyMChjb25kaXRpb24pJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHZhciUyMGZuJTNCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMGZuJTNCJTVDbiUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwZnVuY3Rpb24lMjBmbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiU1Q24lMjAlMjAlN0QlNUNuJTIwJTIwcmV0dXJuJTIwZm4lM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE), [2](https://rollupjs.org/repl/?version=4.4.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBwcm9taXNpZnkoKSUyMCU3QiU1Q24lMjAlMjB2YXIlMjBmbiUzQiU1Q24lMjAlMjBmdW5jdGlvbiUyMGZuKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTVDbiUyMCUyMCU3RCU1Q24lMjAlMjByZXR1cm4lMjBmbiUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=)

[acorn doesn't throw an error](https://ast.sxzz.moe/#eNpdjkEKhDAMRa8SsnLAEzjXGGbVTaktdNCkpK0g4t0njqiDq/6+nzyy4IAdfuxks5OYCraYFFjHQpqd5lDJlcgESXiMOYa5ecBixBBADNA4pj5uAycFmKxAoOfxFV+q0EXW7dnjaQ90aY+Nv+m75Af1QtYLl6026N1o316y2gx2CgZbfC4G273PXMX515z8Xo/c10GzynD9Ar86WJY=)

**Comment by lukastaegert** [comment]
Interesting. So this forbidden:

```js
var fn;
function fn(){};
```

but this is allowed:

```js
function foo() {
  var fn;
  function fn(){};
}
```

So if I understand this, the reasoning is that inside a function, the `var` is hoisted beyond the body scope maybe into the "parameter scope", which is why `function` and the `var` in the second example are not considered to be in the same scope. This also makes it easier to understand why a local function can have the same name as a parameter of the enclosing function: They are not considered to be in the same scope. I will fix it.

**Comment by lazka** [comment]
I'm getting the same error since the update from 4.3.1 to 4.4.0:

```
[!] (plugin commonjs--resolver) RollupError: Identifier "Vt" has already been declared
node_modules/jspdf/dist/jspdf.es.min.js (236:40507)
```

let me know if I should provide more info.
