### ISSUE TITLE
Remap id from a temp folder to sources origin

### ISSUE THREAD

**Issue by Alphapage** [rollup/rollup#525]
Hello,

I need to copy my files to a temp folder before rollup.
The problem is when I want to use sourcemap, then the sourcemap is redirected to the temp folder instead of the origin folder.

I tried to implement a plugin, but I can't find a way. I think something like resolvedId(id) function is missing or necessary to return the location origin.
resolveId : preprocess id => load : load source => resolvedId : post process remapped id to use in sourcemap

Am I right or is it possible to implement it now ?

Thanks in advance for your help.

**Comment by eventualbuddha** [comment]
Why can't you use rollup on the original files? If you can't get around that, can you simply edit the source map to point to the original file path afterward?

**Comment by Alphapage** [comment]
I'm doing some little changes using sweet.js to the temp files which doesn't affect the sourcemap.
I'm not an expert in sourcemap to be able to change the location to point to the origin folder. Are you telling me it could be possible using transform instead of a resolvedId function ? But how ?

**Comment by eventualbuddha** [comment]
Ah… I think I misremembered how the filename stuff works in source maps. Typically the name of the source map file is in the generated file as a comment, but that won't help you here. What you really want is to get a source map from sweet.js and combine it with the source map from rollup. One way to do that is to make a sweet.js plugin for rollup, and then rollup will handle chaining the source maps together. If you do it as two distinct steps you'll need to handle that yourself using something like [sorcery](https://github.com/Rich-Harris/sorcery).
