### ISSUE TITLE
RollupError: Identifier has already been declared

### ISSUE THREAD

**Issue by cheeaun** [rollup/rollup#5259]
### Rollup Version

4.5.0

### Operating System (or Browser)

macOS Chrome

### Node Version (if applicable)

v18

### Link To Reproduction

https://rollupjs.org/repl/?version=4.5.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjB0ZXN0JTIwJTNEJTIwZnVuY3Rpb24lMjBtYXhBcmdzKG1heEFyZ3MpJTIwJTdCJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjB0ZXN0JTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=

### Expected Behaviour

The RollupError shouldn't happen. It didn't happen in previous Rollup v3.

### Actual Behaviour

`RollupError: Identifier "maxArgs" has already been declared` shows up.

This started when I upgrade my project to Vite 5 which uses Rollup **v4.2.0** (older than current one). Running the build task produces this error:

![Screenshot 2023-11-20 at 5 35 26 PM](https://github.com/rollup/rollup/assets/2296/1074f7f8-4c3e-4e39-bb9f-60107163c86b)

The error happens in a library called [`moize`](https://github.com/planttheidea/moize). The line referred is in [`src/index.ts`](https://github.com/planttheidea/moize/blob/6647f854d82f8ac30bb39792da6315dd34458ea1/src/index.ts#L469) (not the `dist`). This library generates the dist output with Rollup **^3.21.5**. I've tried cloning the `moize` repo on my local machine, upgrades the Rollup version to v4.2.0, run the build step and can confirm the same error happens. I've also tried v4.5.0 and same error happens.

![Screenshot 2023-11-20 at 5 47 37 PM](https://github.com/rollup/rollup/assets/2296/09a14b39-8868-4cff-9829-b1fd3d457fe2)

I've funneled it down to this shortest [reproducible code on REPL](https://rollupjs.org/repl/?version=4.5.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjB0ZXN0JTIwJTNEJTIwZnVuY3Rpb24lMjBtYXhBcmdzKG1heEFyZ3MpJTIwJTdCJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjB0ZXN0JTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=) ❌:

```js
const test = function maxArgs(maxArgs) {}
export default test;
```

Here's 3 code examples that I can do to **remove** the error:

1. [REPL](https://rollupjs.org/repl/?version=4.5.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBtYXhBcmdzKG1heEFyZ3MpJTIwJTdCJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBtYXhBcmdzJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=) ✅ - Remove the `const` declaration
    ```js
    function maxArgs(maxArgs) {}
    export default maxArgs;
    ```
2. [REPL](https://rollupjs.org/repl/?version=4.5.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjB0ZXN0JTIwJTNEJTIwZnVuY3Rpb24lMjAobWF4QXJncyklMjAlN0IlN0QlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMHRlc3QlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiU3RCU3RA==) ✅ - Remove the function name
    ```js
    const test = function (maxArgs) {}
    export default test;
    ```
3. [REPL](https://rollupjs.org/repl/?version=4.5.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjB0ZXN0JTIwJTNEJTIwZnVuY3Rpb24lMjBtYXhBcmdzKG1heEFyZ3MyKSUyMCU3QiU3RCU1Q25leHBvcnQlMjBkZWZhdWx0JTIwdGVzdCUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE) ✅ - Rename the argument name
    ```js
    const test = function maxArgs(maxArgs2) {}
    export default test;
    ```

**Comment by lukastaegert** [comment]
Thanks for reporting, fix at #5262

**Comment by lee1994522** [comment]
The issue still persists in 4.6.0.

**Comment by lukastaegert** [comment]
@lee1994522 That is not the case, you can verify with the reproduction above: https://rollupjs.org/repl/?version=4.6.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjB0ZXN0JTIwJTNEJTIwZnVuY3Rpb24lMjBtYXhBcmdzKG1heEFyZ3MpJTIwJTdCJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjB0ZXN0JTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=

That means you likely hit a different issue, for which we would need some kind of reproduction to be able to resolve it.
