### ISSUE TITLE
'xxx is not defined' when used with TypeScript namespaces

### ISSUE THREAD

**Issue by jamiewinder** [rollup/rollup#526]
I'm using TypeScript and Rollup together, and the following seems to be causing problems. I have a bit of code like this:

``` typescript

export namespace Convert {
    export function toNumber(value: any): number {
        // ...
    }
}
```

Which TypeScript compiles into:

``` javascript

export var Convert;
(function (Convert) {
    function toNumber(value) {
        // ...
    }
    Convert.toNumber = toNumber;
})(Convert || (Convert = {}));
```

So far so good, but when this code file is rolled-up, it looks like this:

``` javascript
Convert;
(function (Convert) {
    function toNumber(value) {
        // ...
    }
    Convert.toNumber = toNumber;
})(Convert || (Convert = {}));
export { Convert };
```

Note that the preceding 'var' is removed from the first line. This causes a 'Convert is not defined' error when the line is encountered.

**Comment by TrySound** [comment]
@jamiewinder Do you use `rollup-plugin-typescript`?

**Comment by jamiewinder** [comment]
@TrySound - No, I just let TypeScript compile to ES2015 and have Rollup use that.

**Comment by Victorystick** [comment]
I've been able to reproduce the error. The [minimal amount of code](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20var%20a%3B%5Cna%20%3D%201%3B%22%7D%5D%7D) that reproduces the error is

```js
export var a;
a = 1;
```

which yields
```js
a;
a = 1;

export { a };
```

A slightly [different example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22var%20a%3B%5Cna%20%3D%201%3B%5Cnexport%20%7B%20a%20%7D%3B%22%7D%5D%7D)
```js
var a;
a = 1;
export { a };
```

which yields
```js
a = 1;

export { a };
```

**Comment by Rich-Harris** [comment]
Looks like this has been fixed (at least, the repro above now behaves correctly), so will close
