### ISSUE TITLE
module interop with External Modules

### ISSUE THREAD

**Issue by bchenSyd** [rollup/rollup#5261]
hi guys, 

I'm using `rollup` to bundle my library and i'm running into an issue today. 

## here is my source code
1. I'm using a third party library in my code. That 3rd party library is a common js module, marked as `__esModule`, something like below
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default="A custom component"
```
2.   I'm importing that 3rd party lib in my `index.ts` file
```ts
import  ThirdPartyComponent from 'thirdPartyLib'

export const MyComponent = ()=><ThirdPartyComponent/>
```
3. I don't want to bundle that thirdParty lib, so I've marked it `external`. After building my lib to esm output, I'm getting
```js
import  ThirdPartyComponent from 'thirdPartyLib'

var MyComponent = function MyComponent() {
  // issue!   ThirdPartyComponent is a module object, not the default export
  return /*#__PURE__*/React.createElement(ThirdPartyComponent, null, "hello"); 
};
export { MyComponent };
```
which seems to be correct. 

## here is the problem

when consuming bundled lib  from a client app (CRA with typescript), I'm getting an error complaining `ThirdPartyComponent` isn't a valid react component, but rather a module object (i.e. `{ _esModule: true, default: 'A customer compoent'}).

if I import `thirdPartyLib` **directly** from the client app, it's actually working fine. This is because `babel` is doing its job and will return the default export . However , when importing the same third party library **indirectly** via a `rolled-up` lib, the default export isn't returned but rather a module object is returned. 

I hope I've made myself clear. any thoughts?

**Comment by bchenSyd** [comment]
is it possible to let `rollup` compile above source code into 

```js
import  ThirdPartyComponent from 'thirdPartyLib'

var MyComponent = function MyComponent() {
  return /*#__PURE__*/React.createElement(ThirdPartyComponent.default, null, "hello");
};

```

**Comment by tonyghiani** [comment]
I'm getting the same issue for a library of mine, any solution is more than welcome 👀

**Comment by bchenSyd** [comment]
might be a typescript issue though... `esModuleInterop` is only working on direct depenencies, not sub dependencies;

**Comment by tonyghiani** [comment]
That's exactly what was happening, I initially bundled into the build a small dependency, and when building the library the output was something like:
```
const index = require('./relative-path/index.ts')

index.default()
```

but after externalizing the library, the output code is
```
const defaultExport = require('library')

defaultExport()
```
This gave me an error since I was expecting a function to be the default export, not the module.

I solved it only by exporting the default function and removing an additional named export which was not required.
