### ISSUE TITLE
require external dependency unexpectly when the file require from vendor chunk

### ISSUE THREAD

**Issue by HomyeeKing** [rollup/rollup#5263]
### Rollup Version

4.5.0

### Operating System (or Browser)

OSX Chrome

### Node Version (if applicable)

v16.19.0

### Link To Reproduction

https://github.com/HomyeeKing/rollup-test

### Expected Behaviour

should not require the unused external dependency, only require the necessary from the vendor chunk

### Actual Behaviour

if one file need requrie from vendor chunk, and the external one also included in vendor, the file will require the external dependency as well

see reproduce repo for more details

**Comment by lukastaegert** [comment]
I am not sure but I assume it is this what you are struggling with?

- https://rollupjs.org/faqs/#why-do-additional-imports-turn-up-in-my-entry-chunks-when-code-splitting
- https://rollupjs.org/configuration-options/#output-hoisttransitiveimports

**Comment by HomyeeKing** [comment]
exactly, thanks for your information
