### ISSUE TITLE
Many extra chunks are generated

### ISSUE THREAD

**Issue by spectre900** [rollup/rollup#5266]
### Rollup Version

4.5.1

### Operating System (or Browser)

Playground

### Node Version (if applicable)

NA

### Link To Reproduction

https://rollupjs.org/repl/?version=4.5.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHMxJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkLTEuanMnJTVDbiU1Q25jb25zdCUyMCU3QiUyMGQxJTIwJTdEJTIwJTNEJTIwaW1wb3J0KCcuJTJGZHluYW1pYy0xLmpzJyklM0IlNUNuY29uc3QlMjAlN0IlMjBkMiUyMCU3RCUyMCUzRCUyMGltcG9ydCgnLiUyRmR5bmFtaWMtMi5qcycpJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGNvbXBvbmVudCUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBzMShkMShkMih4KSkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwczElMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMS5qcyclNUNuaW1wb3J0JTIwJTdCJTIwczIlMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMi5qcyclNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwZDElMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwczEoczIoeCkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJkeW5hbWljLTEuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwczElMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMS5qcyclNUNuaW1wb3J0JTIwJTdCJTIwczIlMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMi5qcyclNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwZDIlMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwczEoczIoeCkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJkeW5hbWljLTIuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBzMSUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCU3QiUyMCU1Q24lMjAlMjByZXR1cm4lMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJzaGFyZWQtMS5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHMyJTIwJTNEJTIwKHgpJTIwJTNEJTNFJTIwJTdCJTIwJTVDbiUyMCUyMHJldHVybiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMnNoYXJlZC0yLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

### Expected Behaviour

[Playground 1](https://rollupjs.org/repl/?version=4.5.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHMxJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkLTEuanMnJTVDbiU1Q25jb25zdCUyMCU3QiUyMGQxJTIwJTdEJTIwJTNEJTIwaW1wb3J0KCcuJTJGZHluYW1pYy0xLmpzJyklM0IlNUNuY29uc3QlMjAlN0IlMjBkMiUyMCU3RCUyMCUzRCUyMGltcG9ydCgnLiUyRmR5bmFtaWMtMi5qcycpJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGNvbXBvbmVudCUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBzMShkMShkMih4KSkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwczElMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMS5qcyclNUNuaW1wb3J0JTIwJTdCJTIwczIlMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMi5qcyclNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwZDElMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwczEoczIoeCkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJkeW5hbWljLTEuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwczElMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMS5qcyclNUNuaW1wb3J0JTIwJTdCJTIwczIlMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMi5qcyclNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwZDIlMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwczEoczIoeCkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJkeW5hbWljLTIuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBzMSUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCU3QiUyMCU1Q24lMjAlMjByZXR1cm4lMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJzaGFyZWQtMS5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHMyJTIwJTNEJTIwKHgpJTIwJTNEJTNFJTIwJTdCJTIwJTVDbiUyMCUyMHJldHVybiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMnNoYXJlZC0yLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==)

We expect only 3 chunks to be formed: main, dynamic-1 and dynamic-2. However many small extra chunks are generated.

[Playground 2](https://rollupjs.org/repl/?version=4.5.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHMxJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkLTEuanMnJTVDbiU1Q25jb25zdCUyMCU3QiUyMGQxJTIwJTdEJTIwJTNEJTIwaW1wb3J0KCcuJTJGZHluYW1pYy0xLmpzJyklM0IlNUNuY29uc3QlMjAlN0IlMjBkMiUyMCU3RCUyMCUzRCUyMGltcG9ydCgnLiUyRmR5bmFtaWMtMi5qcycpJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGNvbXBvbmVudCUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBzMShkMShkMih4KSkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwczElMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMS5qcyclNUNuaW1wb3J0JTIwJTdCJTIwczIlMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMi5qcyclNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwZDElMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwczEoczIoeCkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJkeW5hbWljLTEuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwczElMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMS5qcyclNUNuaW1wb3J0JTIwJTdCJTIwczIlMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQtMi5qcyclNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwZDIlMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwczEoczIoeCkpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJkeW5hbWljLTIuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBzMSUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCU3QiUyMCU1Q24lMjAlMjByZXR1cm4lMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJzaGFyZWQtMS5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHMyJTIwJTNEJTIwKHgpJTIwJTNEJTNFJTIwJTdCJTIwJTVDbiUyMCUyMHJldHVybiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMnNoYXJlZC0yLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmV4cGVyaW1lbnRhbE1pbkNodW5rU2l6ZSUyMiUzQTEwMDAwMDAwMDAwJTJDJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE)

Setting `experimentalMinChunkSize` does not merge the extra generated chunks. 

[Playground 3](https://rollupjs.org/repl/?version=4.5.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwJTdCJTIwZDElMjAlN0QlMjAlM0QlMjBpbXBvcnQoJy4lMkZkeW5hbWljLTEuanMnKSUzQiU1Q25jb25zdCUyMCU3QiUyMGQyJTIwJTdEJTIwJTNEJTIwaW1wb3J0KCcuJTJGZHluYW1pYy0yLmpzJyklM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwY29tcG9uZW50JTIwJTNEJTIwKHgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMGQxKGQyKHgpKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHMxJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkLTEuanMnJTVDbmltcG9ydCUyMCU3QiUyMHMyJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkLTIuanMnJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGQxJTIwJTNEJTIwKHgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHMxKHMyKHgpKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyZHluYW1pYy0xLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHMxJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkLTEuanMnJTVDbmltcG9ydCUyMCU3QiUyMHMyJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkLTIuanMnJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGQyJTIwJTNEJTIwKHgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHMxKHMyKHgpKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyZHluYW1pYy0yLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwczElMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAlN0IlMjAlNUNuJTIwJTIwcmV0dXJuJTIweCUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyc2hhcmVkLTEuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBzMiUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCU3QiUyMCU1Q24lMjAlMjByZXR1cm4lMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJzaGFyZWQtMi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJleHBlcmltZW50YWxNaW5DaHVua1NpemUlMjIlM0ExMDAwMDAwMDAwMCUyQyUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==)

Also in examples where `experimentalMinChunkSize` does work it tries to merge chunks that are manually specified using dynamic imports. Such dynamically imported chunks should not be merged.

So the behaviour we are looking for is:
1. Small extra chunks should not be generated at all.
2. If at all they are generated we should be able to merge them.
3. Dynamically imported modules should never be merged.

### Actual Behaviour

Many extra chunks are generated that are extremely small and also possible merges are not applied.

**Comment by lukastaegert** [comment]
Thank you very much for this issue, your reproduction was extremely helpful in finding out why many merges were not taking place. This lead to a fundamental improvement of the algorithm in #5294 which will resolve this issue once released.

**Comment by spectre900** [comment]
Thank you for the fix @lukastaegert

**Comment by spectre900** [comment]
@lukastaegert  can you please look into this?

**Comment by lukastaegert** [comment]
To avoid executing code before it should be executed or executing code twice, at the moment the small chunks unfortunately are a necessity. Webpack avoids this issue because they do not produce flat chunks. Here, every chunk itself contains a registry of modules and a module loader that allows for parts of a chunk to not be executed when a chunk is loaded but rather at a later time.
I am aware that we need _something_ in that direction in Rollup, and I have various vague ideas. Still, this will be a huge undertaking taking at least months, and we need to come up with some rock-solid solutions. In any case, this will be an opt-in as it only makes sense for web-bundling but not for library bundling where you want to avoid any duplication.
