### ISSUE TITLE
Hygienic rename breaks shorthand destructuring assignments

### ISSUE THREAD

**Issue by RReverser** [rollup/rollup#527]
Consider following code:

index.js:
```javascript
import { useModuleStuff } from './module';
const Stuff = 'localStuff';

useModuleStuff();
```

module.js:
```javascript
const { Stuff } = GlobalNamespace;

export function useModuleStuff() {
  return new Stuff();
}
```

In order to avoid conflicts between local and imported `Stuff` variables, Rollup renames the latter one, which is a good thing, but it doesn't take into account the destructuring semantics and generates following code:

```javascript
const { Stuff$1 } = GlobalNamespace;

function useModuleStuff() {
  return new Stuff$1();
}

useModuleStuff();
```

As you can see, destructuring got the form `const { Stuff$1 } = GlobalNamespace` which is not semantically equivalent to `const Stuff$1 = GlobalNamespace.Stuff` anymore.

**Comment by Victorystick** [comment]
The faulty code [in action](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20useModuleStuff%20%7D%20from%20'.%2Fmodule'%3B%5Cnconst%20Stuff%20%3D%20'localStuff'%3B%5Cn%5CnuseModuleStuff()%3B%22%7D%2C%7B%22name%22%3A%22module.js%22%2C%22code%22%3A%22const%20%7B%20Stuff%20%7D%20%3D%20GlobalNamespace%3B%5Cn%5Cnexport%20function%20useModuleStuff()%20%7B%5Cn%20%20return%20new%20Stuff()%3B%5Cn%7D%22%7D%5D%7D). This should definitely be taken care of.

**Comment by RReverser** [comment]
@Victorystick Yup, sorry - initially thought about posting URL from the playground (as I experimented there) but then thought that actual code examples as part of the issue might be more useful format.

**Comment by Victorystick** [comment]
@RReverser I usually post both. It's nice to go back to old issues and see them working as expected in the playground. :smile:
