### ISSUE TITLE
`transform` plugin hooks is forbidden to be asynchronous

### ISSUE THREAD

**Issue by ericmorand** [rollup/rollup#5277]
### Documentation is

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not sure?

### Please Explain in Detail...

The documentation clearly establishes that the `transform` hook is asynchronous:

https://rollupjs.org/plugin-development/#transform

> Kind: async, sequential

</body>
</html>

But, trying to actually implement an asynchronous `transform` hook is not possible:

```ts
    const transform: TransformHook = (
        code,
        _id
    ) => {
        return Promise.resolve({
            code: code,
            map: {mappings: ''}
        }); // TS2322: Type Promise<[...]> [...] is not assignable to type  TransformResult
    };
```

### Your Proposal for Changes

Either:

* Update the documentation to remove the "async" mention if the hook _is not_ asynchronous
* Update the type declaration to allow it to return a promise if the hook _is_ asynchronous

Note that the documentation recommends using asynchronous methods...but the implementation forbids it. Something is very strange here.

> Use asynchronous methods when it is possible, e.g. fs.readFile instead of fs.readFileSync.

https://rollupjs.org/plugin-development/#conventions

**Comment by TrickyPi** [comment]
Please see https://rollupjs.org/command-line-interface/#config-intellisense.

**Comment by ericmorand** [comment]
@TrickyPi I don't understand. This is not an IDE problem. The code can't compile - the Typescript compiler refuses to compile it because it is not valid.

**Comment by TrickyPi** [comment]
Because you are using the wrong type for the 'transform' function.

**Comment by TrickyPi** [comment]
Yeah, you are right, It is a documentation issue, reopened it.

**Comment by ericmorand** [comment]
Thanks 

I looked at the typings more closely. Is the legit type `MakeAsync<TransformHook>`?

**Comment by ericmorand** [comment]
Thank you.

**Comment by lukastaegert** [comment]
If you really need an explicit type instead of using the `Plugin` type, the correct type is `NonNullable<Plugin['transform']>`. While other types should be stable, I would not want to make absolute guarantees for this.

**Comment by ericmorand** [comment]
And actually, using it with a non-arrow function also works flawlessly and give us inferred argument and return types, as expected:

```ts
<Plugin["transform"]>function transform(this, code, id) { // this, code and id types are inferred
    return Promise.resolve(); // ...as is the return type
}
```

**Comment by ericmorand** [comment]
Actually, it does not work but it is not a Rollup issue:

https://github.com/microsoft/TypeScript/issues/56636

Anyway, I close if you are OK. I still think that the documentation is lacking about Typescript but if I have time, I'll try to propose something in the next few days.
