### ISSUE TITLE
Uses wrong import base and tries to load `ts` file from node_modules

### ISSUE THREAD

**Issue by domoritz** [rollup/rollup#529]
I already posted this issue at https://github.com/rollup/rollup-plugin-typescript/issues/30 but haven't gotten any responses. I suspect that this may be an issue with rollup itself rather than just the plugin. Feel free to close this issue it you think it's an issue with the plugin.

**Comment by Victorystick** [comment]
@domoritz Sorry about not having gotten back to you about that. I've been digging into it and (after some hacks) I've got it building. I'll get back to you once I've cleaned up said hacks.

**Comment by domoritz** [comment]
Thank you @Victorystick. I'll close the issue here.
