### ISSUE TITLE
Rollup hangs on unknown external modules

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#53]
When rollup tries to bundle an external module which doesn't exist. It gets stuck in an infinite loop in [defaultExternalResolver](https://github.com/rollup/rollup/blob/master/src/utils/resolveId.js#L55), where `dir` was modified like so

```js
'/home/user/repo' -> 
'/home/user' -> '/home' -> '' -> '.' -> '.' -> ...
```
never reaching the terminating condition `dir === '/'`.

The issue was mentioned in #52. Thanks for bringing it up @petulla!

**Comment by petulla** [comment]
My understanding is the need to explicitly reference the relative path is also an issue.
