### ISSUE TITLE
Rust panic on Mittwald servers

### ISSUE THREAD

**Issue by fabianwohlfart** [rollup/rollup#5304]
### Rollup Version

greater than 4.0.0

### Operating System (or Browser)

Linux

### Node Version (if applicable)

greater or equal than 18

### Description

With the rollup-swc update the Mittwald (german hosting service) server cannot deal.
When I use Rollup through Nitro(2.81) through Nuxt (3.8.2) Rust will panic:

```
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:416:13:
assertion `left == right` failed
  left: 2
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
error Command failed with signal "SIGABRT".
```

`/usr/local/` is not writeable by my user.
So I was thinking if this may be the error?
As Mittwald is super restrictive I cannot get more information from the service team than »Rollup is the cause«.

**Comment by lukastaegert** [comment]
I do not think it can have to do with file system issues because at the moment, our Rust code does not interact with the file system. And `stacker` is not a direct dependency we use but a dependency of SWC, which means the error throws somewhere deep in SWC code. I don't suppose you can set `RUST_BACKTRACE=1`, which might indeed add a little more information?

**Comment by lukastaegert** [comment]
Apparently, it is a function `guess_os_stack_limit` for Linux flavored operating systems. I must honestly say I have no idea what is happening inside that function, nor how to fix anything.
Can you try using `@rollup/wasm-node` instead of `rollup`? It is a drop-in replacement using WebAssembly.

**Comment by fabianwohlfart** [comment]
Here is the backtrace,.
Stack limit seems to be 8192 kb, checked with `ulimit -s`

```
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:416:13:
assertion `left == right` failed
  left: 2
 right: 0
stack backtrace:
   0:     0x7f1e3b607f8c - <unknown>
   1:     0x7f1e3b58da10 - <unknown>
   2:     0x7f1e3b609719 - <unknown>
   3:     0x7f1e3b6093dd - <unknown>
   4:     0x7f1e3b609df0 - <unknown>
   5:     0x7f1e3b60995c - <unknown>
   6:     0x7f1e3b6098b6 - <unknown>
   7:     0x7f1e3b6098a1 - <unknown>
   8:     0x7f1e3b579404 - <unknown>
   9:     0x7f1e3b5796eb - <unknown>
  10:     0x7f1e3b57efb7 - <unknown>
  11:     0x7f1e3b5dc509 - <unknown>
  12:     0x7f1e3b6a0e22 - <unknown>
  13:     0x7f1e3b69b50e - <unknown>
  14:     0x7f1e3b69883f - <unknown>
  15:     0x7f1e3b6971ea - <unknown>
  16:     0x7f1e3b696a73 - <unknown>
  17:     0x7f1e3b6ed50d - <unknown>
  18:     0x7f1e3b6e866c - <unknown>
  19:     0x7f1e3b6e6ead - <unknown>
  20:     0x7f1e3b6e56d1 - <unknown>
  21:     0x7f1e3b66b550 - <unknown>
  22:     0x7f1e3b667d3b - <unknown>
  23:     0x7f1e3b66280c - <unknown>
  24:     0x7f1e3b65d797 - <unknown>
  25:     0x7f1e3b690e50 - <unknown>
  26:     0x7f1e3b6904c1 - <unknown>
  27:     0x7f1e3b6e5986 - <unknown>
  28:     0x7f1e3b66b550 - <unknown>
  29:     0x7f1e3b667d3b - <unknown>
  30:     0x7f1e3b66280c - <unknown>
  31:     0x7f1e3b65d797 - <unknown>
  32:     0x7f1e3b6fbe30 - <unknown>
  33:     0x7f1e3b6a6142 - <unknown>
  34:     0x7f1e3b69b5e7 - <unknown>
  35:     0x7f1e3b6b35f2 - <unknown>
  36:     0x7f1e3b5ceead - <unknown>
  37:     0x7f1e3b5d4ce7 - <unknown>
  38:     0x7f1e3b5865ac - <unknown>
  39:           0xb28b69 - <unknown>
  40:           0xdc4e00 - <unknown>
  41:           0xdc633f - <unknown>
  42:     0x7f1e43f07b39 - <unknown>
fatal runtime error: failed to initiate panic, error 5
error Command failed with signal "SIGABRT".
```

I am using Rollup through Nuxt > Nitro, thus I cannot change to `wasm-node` directly, but added a resolution to my package.json where I am now locked to a specific version of Nitro that does not use native SWC-based parser.
Or is there a way to do so through the settings?

**Comment by lukastaegert** [comment]
I think you should be able to use package.json overrides to replace rollup with `@rollup/wasm-node` even for transitive dependencies. Let me know if this works!

**Comment by fabianwohlfart** [comment]
Unfortunatly other dependencies exist…

```
ERESOLVE overriding peer dependency
npm WARN While resolving: @miyaneee/rollup-plugin-json5@1.1.2
npm WARN Found: rollup@undefined
npm WARN node_modules/rollup
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer overridden rollup@"@rollup/wasm-node" (was "^1.20.0 || ^2.0.0 || ^3.0.0") from @miyaneee/rollup-plugin-json5@1.1.2
npm WARN node_modules/@miyaneee/rollup-plugin-json5
npm WARN   @miyaneee/rollup-plugin-json5@"^1.1.2" from @nuxtjs/i18n@8.0.0-rc.11
npm WARN   node_modules/@nuxtjs/i18n
npm ERR! Cannot read properties of null (reading 'name')
```

**Comment by fabianwohlfart** [comment]
I did a mistake with the override.
The correct way I should have done it is:

```
"resolutions": {
  "rollup": "npm:@rollup/wasm-node"
}
```
or
```
"overrides": {
  "rollup": "npm:@rollup/wasm-node"
}
```

Works :)

ps. Just got back from Mittwald service, they said I should switch to another server, no other solution or explanation provided ¯\\_(ツ)_/¯
