### ISSUE TITLE
I'm not sure if this is a bug.  When I set treeshake.moduleSideEffects to false in the configuration,  the functions doNothing and alpha, which should have been eliminated by treeshaking, still persist in the code.

### ISSUE THREAD

**Issue by zswanglyg** [rollup/rollup#5317]
### Rollup Version

v4.9.1

### Operating System (or Browser)

windows 11

### Node Version (if applicable)

v18.19.0

### Link To Reproduction

https://rollupjs.org/repl/?version=4.9.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGFscGhhJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZhbHBoYSU1QyUyMiU1Q24lNUNuY29uc3QlMjBtYWluJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwYWxwaGEoKSU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMG1haW4lMjAlN0QlMjAlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZG9Ob3RoaW5nJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlNUNuJTVDbmNvbnN0JTIwYWxwaGElMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBkb05vdGhpbmcoKSU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGFscGhhJTIwJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmFscGhhLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBJTdCJTIybW9kdWxlU2lkZUVmZmVjdHMlMjIlM0FmYWxzZSU3RCU3RCU3RA==

### Expected Behaviour

const main = () => {
};

export { main };

### Actual Behaviour

const doNothing = () => {};

const alpha = () => {
    doNothing();
};

const main = () => {
    alpha();
};

export { main };

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #5322
