### ISSUE TITLE
systemjs not updated for any string export name spec

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#5320]
### Rollup Version

4.9.1

### Operating System (or Browser)

repl

### Link To Reproduction

https://rollupjs.org/repl/?version=4.9.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMHglMjBhcyUyMCU1QyUyMid4JTVDJTIyJTIwJTdEJTIwZnJvbSUyMCd4JyUzQiU1Q24lNUNuZnVuY3Rpb24lMjBhJTIwKCklMjAlN0IlN0QlNUNuZnVuY3Rpb24lMjBiJTIwKCklMjAlN0IlN0QlNUNuZXhwb3J0JTIwJTdCJTIwYSUyMGFzJTIwJTVDJTIyJ2ElNUMlMjIlMkMlMjBiJTIwYXMlMjAlNUMlMjInYiU1QyUyMiUyMCU3RCUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnN5c3RlbSUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=

### Expected Behaviour

```js
export { x as "'x" } from 'x';

function a () {}
function b () {}
export { a as "'a", b as "'b" };
```

```js
System.register(['x'], (function (exports) {
	'use strict';
	return {
		setters: [function (module) {
			exports("'x", module.x);
		}],
		execute: (function () {

			exports({
				"'a": a,
				"'b": b
			});

			function a () {}
			function b () {}

		})
	};
}));
```

### Actual Behaviour

```js
System.register(['x'], (function (exports) {
	'use strict';
	return {
		setters: [function (module) {
			exports(''x', module.x);
		}],
		execute: (function () {

			exports({
				'a: a,
				'b: b
			});

			function a () {}
			function b () {}

		})
	};
}));
```

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #5321
