### ISSUE TITLE
babel pure annotation output with leading comments not supported

### ISSUE THREAD

**Issue by twk3** [rollup/rollup#5324]
### Rollup Version

4.5.0

### Operating System (or Browser)

REPL

### Link To Reproduction

https://rollupjs.org/repl/?version=4.5.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjBmb3VyJTIwJTNEJTIwJTJGKiUyMCUyM19fUFVSRV9fJTIwKiUyRiUyMCUyRiolMjBmb28lMjAqJTJGJTIwYWRkKDIlMkMlMjAyKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE

### Expected Behaviour

The PURE annotation is not stripped. Instead all comments are considered combined or whitespace. Matching behaviour of  UglifyJS starting in v3.1.0 and properly handling the output from `@babel/helper-annotate-as-pure` as documented here: https://babeljs.io/docs/babel-helper-annotate-as-pure

### Actual Behaviour

The following warning is thrown, and the PURE annotation is stripped.

```
Rollup completed with warnings:
A comment "/* #__PURE__ */" in "main.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues. [(link)](https://rollupjs.org/configuration-options/#pure)
/main.js (1:13)
1: const four = /* #__PURE__ */ /* foo */ add(2, 2);
```

Libraries like https://github.com/FormidableLabs/victory are currently triggering these warnings and having their annotations stripped when included in rollup projects due to this issue.

```
../../node_modules/victory-core/es/victory-primitives/rect.js (16:2) A comment

"/*#__PURE__*/"

in "../../node_modules/victory-core/es/victory-primitives/rect.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
../../node_modules/victory-core/es/victory-primitives/rect.js (21:2) A comment

"/*#__PURE__*/"

in "../../node_modules/victory-core/es/victory-primitives/rect.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.

```

**Comment by lukastaegert** [comment]
Thanks for the issue, fix at #5332.

**Comment by daomtthuan** [comment]
Is this related ?
https://github.com/dotnet/aspnetcore/issues/55286

I'm having same issue when use vite/rollup with signalr

**Comment by lukastaegert** [comment]
It would really help to provide a code example in the REPL instead of just the error messages.

**Comment by daomtthuan** [comment]
> It would really help to provide a code example in the REPL instead of just the error messages.

@lukastaegert 

https://stackblitz.com/edit/vitejs-vite-utvumq?file=src%2FApp.tsx

Sample script

```tsx
import { useEffect } from 'react';
import { HubConnectionBuilder, LogLevel } from '@microsoft/signalr';
import './App.css';

function App() {
  // Using sample https://learn.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-8.0&tabs=visual-studio
  // To test building with use @microsoft/signalr
  useEffect(() => {
    const instance = new HubConnectionBuilder()
      .withUrl('/chathub')
      .configureLogging(LogLevel.Information)
      .build();

    (async () => {
      await instance.start();
    })();

    return () => {
      (async () => {
        await instance.stop();
      })();
    };
  }, []);

  return <>Test using @microsoft/signalr</>;
}

export default App;
```

Run build

```cmd
~/projects/vitejs-vite-utvumq
❯ yarn build
yarn run v1.22.19
$ tsc && vite build
vite v5.2.10 building for production...
node_modules/@microsoft/signalr/dist/esm/Utils.js (189:0): A comment

"/*#__PURE__*/"

in "node_modules/@microsoft/signalr/dist/esm/Utils.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
node_modules/@microsoft/signalr/dist/esm/Utils.js (207:0): A comment

"/*#__PURE__*/"

in "node_modules/@microsoft/signalr/dist/esm/Utils.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
✓ 59 modules transformed.
dist/index.html                   0.46 kB │ gzip:  0.30 kB
dist/assets/index-DiwrgTda.css    1.39 kB │ gzip:  0.72 kB
dist/assets/index-BDlzFd_n.js   198.67 kB │ gzip: 60.10 kB
✓ built in 3.16s
✨  Done in 8.78s.
```

**Comment by DerZade** [comment]
I can confirm that this issue still exists. Can we get this issue reopened?

**Comment by dkillion-webstaurantstore** [comment]
I'm having this issue after migrating an app from create-react-app to vite

**Comment by drewkill32** [comment]
This appears to be an issue with the SignalR client using the pure annotation incorrectly [dotnet/aspnetcore/src/SignalR/clients/ts/signalr/src/Utils.ts](https://github.com/dotnet/aspnetcore/blob/a0652e0852f1dc9ea199a453efd421f6dfc04f1b/src/SignalR/clients/ts/signalr/src/Utils.ts#L240-L258)

**Comment by lukastaegert** [comment]
That is why I added this warning, that is definitely an incorrect usage. I hope someone can fix the usage upstream. The correct annotation here would be `__NO_SIDE_EFFECTS__`

**Comment by dkillion-webstaurantstore** [comment]
It is because the SignalR team at Microsoft uses Webpack where the  `/*#__PURE__#*/` annotation is supported in the function declaration. [Webpack Tree Shaking](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects). They are moving off of webpack in the next major version, so it won't be an issue then

**Comment by sweihub** [comment]
I have the same issue with latst npm & rollup installed

```
vite v5.2.11 building for production...
node_modules/mathjs/lib/esm/entry/configReadonly.js (6:20): A comment

"/* #__PURE__ */"

in "node_modules/mathjs/lib/esm/entry/configReadonly.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
node_modules/mathjs/lib/esm/type/unit/physicalConstants.js (47:0): A comment

"// export const createSpectralRadiance = /* #__PURE__ */ unitFactory('spectralRadiance', '1.1910429723971881e-16', 'W m^2 sr^-1') // TODO spectralRadiance"

in "node_modules/mathjs/lib/esm/type/unit/physicalConstants.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
node_modules/mathjs/lib/esm/utils/number.js (24:18): A comment

"/* #__PURE__ */"
...
```

**Comment by mo-martinwilson** [comment]
I'm experiencing similar: here's my rollup setup:

package.json versions:
```JavaScript
"devDependencies": {
    "@rollup/plugin-node-resolve": "^15.2.3",
    "@rollup/plugin-terser": "^0.4.4",
    "rollup": "^4.18.0"
  },
```

rollup.config.js
```JavaScript
import resolve from '@rollup/plugin-node-resolve';
import terser from '@rollup/plugin-terser';

export default {
  input: "index.js",
  output: { file: "./src/static/main.js", format: "es" },
  plugins: [
    resolve(),
    terser({
      ecma: 2021,
      module: true,
      warnings: true,
    })
  ]
}
```

When I run `$ npm run build` I see:
> my-app@0.0.1 build
> rollup -c
> 
> 
> index.js → ./src/static/main.js...
> (!) node_modules/three/build/three.module.js (6480:18): A comment
> 
> "/*@__PURE__*/"
> 
> in "node_modules/three/build/three.module.js" contains an annotation that Rollup cannot interpret due to the position of the > comment. The comment will be removed to avoid issues.
> https://rollupjs.org/https://rollupjs.org/configuration-options/#pure
> C:\dev\omitted\directory\path\node_modules\three\build\three.module.js:6480:18
> 6478: let _object3DId = 0;
> 6479:
> 6480: const _v1$4 = new /*@__PURE__*/ Vector3();
>                         ^
> 6481: const _q1 = new /*@__PURE__*/ Quaternion();
> 6482: const _m1$1 = new /*@__PURE__*/ Matrix4();
> (!) node_modules/three/build/three.module.js (6481:16): A comment

And nothing is built into my target file :(

**Comment by Firsh** [comment]
What puts those comments there? I didn't. Meaning that it's a build step that could be disabled.

**Comment by gweesin** [comment]
> This issue has been resolved via #5332 as part of rollup@4.9.4. You can test it via `npm install rollup`.

It still cannot work as expected in rollup@4.27.3.

**Comment by elektronik2k5** [comment]
This is definitely still an issue, using `rollup@4.30.1` (as part of `vite@6.0.7`).

**Comment by glittle** [comment]
Still going on...

![Image](https://github.com/user-attachments/assets/71215071-03f9-4dff-980f-bd2f5dca541c)

**Comment by nichita-pasecinic** [comment]
bump

**Comment by OscBacon** [comment]
bump +1

**Comment by fredrikcarlbom** [comment]
> It is because the SignalR team at Microsoft uses Webpack where the `/*#__PURE__#*/` annotation is supported in the function declaration. [Webpack Tree Shaking](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects). They are moving off of webpack in the next major version, so it won't be an issue then

It does not seem like they are moving off webpack, neither version 9 nor previews of 10 have switched from webpack.

**Comment by lukastaegert** [comment]
Just a note, reading their documentation I find no example where they hint that in Webpack `__PURE__` is supported for function declarations. On the linked page, the only similar example is actually a function expression wrapped in an IIFE, which is definitely fine. So unless I am overlooking something, this is not a Webpack problem but an incorrect usage problem.

It is, however, supported for constructors, just not with the comment nested between as is done [apparently in Three.js](https://github.com/rollup/rollup/issues/5324#issuecomment-2164729337). Created #5995 to track.

**Comment by kangwuyi** [comment]
terser +1 (rollup v4.53.3)
