### ISSUE TITLE
Cannot find module @rollup/rollup-win - nuxt 3 - npm install fail

### ISSUE THREAD

**Issue by JulienHenrotin** [rollup/rollup#5325]
### Rollup Version

4.9.2

### Operating System (or Browser)

Windows 11

### Node Version (if applicable)

20.10.0

### Link To Reproduction

https://github.com/JulienHenrotin/testNuxt3

### I can no longer launch my Nuxt 3 project due to **Rollup package**
I cloned my web project into a machine with a fresh Windows 11 installation but I'm unable to get past the **package installation step.**

Before this, I installed Node using NVM (Node Version Management).

After clone project I just have to install dependencies before run the project.

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      typescript, app, nitro, runtimeConfig, modules, htmlValidator
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @nuxtjs/google-fonts@3.1.3, @nuxtjs/html-validator@1.6.0, @vueuse/nuxt@10.7.0, @nuxtjs/i18n@8.0.0-beta.9, nuxt-icons@3.2.1, @nuxt/image@1.1.0, @nuxtjs/fontaine@0.4.1, nuxt-schema-org@3.2.1, nuxt-delay-hydration@1.3.3
-------------------------------

### Actual Behaviour

When I run `npm install`, I get the following error:

``` 
[15:25:31]  ERROR  Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i again after removing both package-lock.json and node_modules directory.

  at requireWithFriendlyError (node_modules\rollup\dist\native.js:87:9)
  at Object.<anonymous> (node_modules\rollup\dist\native.js:96:48)
  at Module._compile (node:internal/modules/cjs/loader:1376:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
  at Module.load (node:internal/modules/cjs/loader:1207:32)
  at Module._load (node:internal/modules/cjs/loader:1023:12)
  at cjsLoader (node:internal/modules/esm/translators:345:17)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
  at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)


[15:25:31]  ERROR  Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i again after removing both package-lock.json and node_modules directory.

npm ERR! code 1
npm ERR! path C:\Users\julie\Downloads\my_project
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c nuxt prepare
``` 

### What I tried:

- deleting the node_module folder, cache, and package.lock
- testing other versions of node (17.9.1, 18.19.0, 19.9, 20.10)
- installing Node in the traditional way without NVM
- changing the version of Rollup `"overrides": {"rollup": "4.6.1"}`
- change nuxt version to 3.9.0
- create new empty nuxt project

**Comment by JulienHenrotin** [comment]
> Could you try using 'npm i @rollup/rollup-win32-x64-msvc' to install this package?

Already try it but no apparent change.

**Comment by anthonysanlucas** [comment]
#### This issue is solved in a simple way, using pnpm. 😀

After several minutes trying to fix it I decided to use another package manager.

**Comment by mahsarajabpour** [comment]
I used the commands `npm cache clean --force` and `rm -rf node_modules package-lock.json`.
Then I realized that I could prevent the same error from occurring without needing to add the optional `rollup` dependency. It was just necessary to remove the `--no-optional` flag in the "Install Dependencies" section of my `ci.yml file`. 
I hope that helps!

**Comment by Moe03** [comment]
+1

**Comment by Bhavanesh22** [comment]
> necessary
 @mahsarajabpour 

I am facing the above issues on angular. I am able getting your point. Can you please elaborate this.

**Comment by DikshaAdhikari** [comment]
@Bhavanesh22 did you find the solution for this? I am facing the same issue in angular and I have tried almost everything mentioned above

**Comment by Bhavanesh22** [comment]
> @Bhavanesh22 did you find the solution for this? I am facing the same issue in angular and I have tried almost everything mentioned abov

**Comment by Bhavanesh22** [comment]
> > @DikshaAdhikari 

This issue happens because of jfrog configuration and npm is not installing properly.
I didn't find the permanent solution for this issue. 

But I have a temporary solution. 

Get a copy of nodemodules/@rollup file from your any previous working project or get it from your colleague and replace the file in your current project. 

Keep the working rollup file for future use .

**Comment by DikshaAdhikari** [comment]
Thank you @Bhavanesh22, it worked for me :)

**Comment by WaiRung** [comment]
Does anyone get any permanent solution? Getting stuck with it even when start with brand new Nuxt project

**Comment by sukalov** [comment]
> #### This issue is solved in a simple way, using pnpm. 😀
> 
> After several minutes trying to fix it I decided to use another package manager.

OH MY GOD FINALLY THIS WORKED after hour of trying everything. switched to pnpm from bun, page works
