### ISSUE TITLE
src/utils/path.js behavior on Windows

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#533]
Is there an architectural reason for src/utils/path.js to re-implement so many things that already exist in the node path module? At least for the non-browser build, it seems it would make sense to use node's path functions.

Node's path module also includes support for Windows paths. Today on Windows I noticed an issue where Rollup's resolved version of the path to a file contained forward slashes while one that I had generated myself in a plugin (using node's path module) contained backslashes - and this resulted in Rollup thinking these were two separate modules and it was included twice in the bundle.

It seems there are three options:

- Have users make sure paths to modules sent to Rollup always use forward slashes, regardless of the platform's real path separator (this is what I'm doing for now but it seems like a bit of a hack)
- Update the function `resolve()` in path.js. Right now the line `return resolvedParts.join( '/' ); // TODO windows...` is always assuming a `/` separator
- Do a larger-scale replacement of path.js implementations with the functions in node's path module

Options 1 is very easy because it's pretty much "do nothing". But option 2 doesn't seem very difficult at all. We could check whether the global `process` is defined and whether `process.platform === 'win32'` and if so, use the separator `\` and otherwise use `/`. This would keep the same behavior as exists now in browser environments, where `process` is not available.

Thoughts?

**Comment by TrySound** [comment]
Windows supports forward slash as well. By the way we use minimatch for filters which supports only unix separator.

**Comment by Conduitry** [comment]
I'm trying to figure out again what my initial issue was. I think it was that I had a module that was getting included twice, if one time it was referred to with forward slashes in the path and another time with backslashes. I had a module that I was both a) importing normally, using imports with relative paths in my code, and b) importing as the result of generated code from a transform. The former had forward slashes in its path, and the latter (generated using path.join) had backslashes. My solution at the time was to change the backslashes in the generated path to forward slashes. I haven't really revisited whether more recent rollup versions changed what I had to do here.
