### ISSUE TITLE
Tree-shaking incorrectly eliminates optional access to a shared array element 

### ISSUE THREAD

**Issue by gebsh** [rollup/rollup#5343]
### Rollup Version

4.9.5

### Operating System (or Browser)

macOS Sonoma 14.2.1 / Firefox 121.0.1

### Node Version (if applicable)

21.6.0

### Link To Reproduction

[REPL link](https://rollupjs.org/repl/?version=4.9.5&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwc3RhY2slMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBmb28lM0ElMjB1bmRlZmluZWQlMkMlNUNuJTIwJTIwJTdEJTNCJTVDbiU1Q24lMjAlMjBzdGFjay5wdXNoKHN0YXRlKSUzQiU1Q24lMjAlMjBzZXRGb28oKSUzQiU1Q24lMjAlMjBzdGF0ZS5mb28lM0YuKCklM0IlMjAlMkYlMkYlMjBUaGlzJTIwbGluZSUyMGlzJTIwZWxpbWluYXRlZC4lNUNuJTIwJTIwc3RhY2sucG9wKCklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHNldEZvbygpJTIwJTdCJTVDbiUyMCUyMGlmJTIwKHN0YWNrLmxlbmd0aCUyMCUzRSUyMDApJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHN0YWNrLmF0KC0xKS5mb28lMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygnZm9vKCklMjBjYWxsZWQnKSU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE)

### Expected Behaviour

`state.foo?.();` line should not be eliminated by tree-shaking.

### Actual Behaviour

`state.foo?.();` is not present in the bundle output.

I assume this is caused by the fact that the shared object is accessed via `state` not via `stack[0]` or `stack.at(-1)`. Changing to any of these two correctly preserves the line in the output.

**Comment by lukastaegert** [comment]
Thanks for spotting, fix at #5352
