### ISSUE TITLE
I accidentally was doing a back up on my laptop and all my files got grouped with json file tokens list I have copies of my receipts for purchase and need help now getting project out of archive!

### ISSUE THREAD

**Issue by Itzyboo1** [rollup/rollup#5356]
### Documentation is

- [X] Missing
- [ ] Needed
- [X] Confusing
- [X] Not sure?

### Please Explain in Detail...

![IMG_8632](https://github.com/rollup/rollup/assets/126123063/b4a7f9dd-afd8-4426-96fc-a883201626d3)

### Your Proposal for Changes

I was doing a back up of all my files and unfortunately my  files got put together with my json token files and then it ended up getting archived so now I’m going through and extracting only that file to download attached are my receipts that coenside with that json file 
![IMG_8628](https://github.com/rollup/rollup/assets/126123063/1001ee06-eb58-4568-9f7f-006f155aa5ad)
e
![IMG_8630](https://github.com/rollup/rollup/assets/126123063/1242615e-0ec3-49b5-a1bc-0ebde1b92b49)

![IMG_8631](https://github.com/rollup/rollup/assets/126123063
![IMG_8629](https://github.com/rollup/rollup/assets/126123063/7c70b2ee-c789-435b-ad77-7459401ef7bb)
/d3e78f75-3f1c-4912-bb4d-e877932a3f34)

**Comment by Itzyboo1** [comment]
If I understand you correct but not much said I had via GitHub communications yesterday and had indicated to me I would have to pull it out of archived because on top of all this I also started to created new and it automatically archived? Is that correct I would really like to clear this up
Sincerely,
Jennifer Caprio

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lukastaegert** [comment]
I am pretty sure you are confusing the [JavaScript bundler Rollup](https://rollupjs.org) with something else. We are not involved with any crypto scams or whatever the problem is.
