### ISSUE TITLE
Expose code in entryFileNames, chunkFileNames, and assetFileNames

### ISSUE THREAD

**Issue by relaxedleaf** [rollup/rollup#5362]
### Feature Use Case

Currently I am using Vite to build bundle for my React app. One of the features I need is to customize names of the output files. To be specific, I want to make all of my output names to be in `assets/[name]-[hash].[ext]` format, but in lowercase.

I don't think there is any way for me to get the hash generated by rollup directly, so I will have to create a custom hashing function to generate hash in lowercase

The following is my implementation
```typescript
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import { createHash } from "node:crypto";

export default defineConfig({
  plugins: [react()],
  build: {
    rollupOptions: {
      output: {
        chunkFileNames: (chunkInfo) => {
	  const uniqueToken = Date.now().toString();
          const hash = createHash("sha256")
            .update(JSON.stringify(chunkInfo) + uniqueToken)
            .digest("hex")
            .substring(0, 8);
          return `assets/${chunkInfo.name.toLowerCase()}-${hash}.js`;
        },
      },
    },
  },
});
```

My implementation is not ideal for cache busting as it appends `uniqueToken` to `chunkInfo`, which will generate new file names for every single file on each build.

An ideal situation is that I could generate custom hash based on the content of the file. This way the hash will remain the same if the source file is never changed

### Feature Proposal

- Expose the file content in `entryFileNames`, `chunkFileNames`, and `assetFileNames` so that we have a better way to generate hash based on the actual content of the file
- In my case, it would even be better if the default output hash is part of the callbacks

**Comment by lukastaegert** [comment]
Unfortunately, we do not have the chunk content available when this function is called because the chunks can reference other chunks, and hashes in file names cannot be resolved until all chunk name patterns and dependencies are known.
That being said, why is Rollup's hashing algorithm that is based on the file contents not suitable for you? Is it the character set used for hashes? That is something we could make configurable.

**Comment by relaxedleaf** [comment]
> Unfortunately, we do not have the chunk content available when this function is called because the chunks can reference other chunks, and hashes in file names cannot be resolved until all chunk name patterns and dependencies are known. That being said, why is Rollup's hashing algorithm that is based on the file contents not suitable for you? Is it the character set used for hashes? That is something we could make configurable.

Thanks for the reply. The issue I am having is that the default output file hash has both uppercase and lowercases. A hosting service I am using only allows file names to be in lowercase. I am not quite sure if hash I am getting is directly from rollup, or from Vite.

But yes, there is additional option where I can configure character sets to set it to a-z0-9, that would be awesome!

**Comment by lukastaegert** [comment]
I created #5371 as a potential way to address this. This lets you select the character set used for file hashes.

**Comment by relaxedleaf** [comment]
> I created #5371 as a potential way to address this. This lets you select the character set used for file hashes.

Thank you very much!

**Comment by rawnsley** [comment]
> Unfortunately, we do not have the chunk content available when this function is called because the chunks can reference other chunks, and hashes in file names cannot be resolved until all chunk name patterns and dependencies are known. That being said, why is Rollup's hashing algorithm that is based on the file contents not suitable for you? Is it the character set used for hashes? That is something we could make configurable.

@lukastaegert it would be very useful for us to hash the actual file content rather than the proxy content currently used for the hash. Could there be a way to defer calling this function until the final content is known? This would start with the files that don’t reference anything else and then work back up the tree as more filenames are resolved.

**Comment by lukastaegert** [comment]
As chunks can easily contain circular references when dynamic imports are used, this is just not possible. The current logic uses a placeholder for referenced hashes and then uses a dependency graph to calculate the final hashes.
