### ISSUE TITLE
Compare with webpack

### ISSUE THREAD

**Issue by katopz** [rollup/rollup#537]
I think some information [here](https://webpack.github.io/docs/comparison.html) is not up to date. And make rollup look not quite good there.
e.g. `uglify` is mark as **no** there which is not exactly true.

So the question is can someone that know 100% of rollup (I'm not) please [update](https://github.com/webpack/docs/wiki/comparison/_edit) that doc please?
I mean not just `uglify` but also some other feature too.

And would be nice if some **no** there appear here as **TODO** I think.

Cheers

**Comment by TrySound** [comment]
@katopz It's old info. You can update first look if you want.
Minimizing: [rollup-plugin-uglify](https://github.com/TrySound/rollup-plugin-uglify)
Node.js built-in libs require("path"): [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve)

**Comment by Victorystick** [comment]
@TrySound I've updated those parts of the comparison.

@katopz We'll try to keep contributing updates to it during Rollup development.
