### ISSUE TITLE
importing rollup from esm.sh doesn't work

### ISSUE THREAD

**Issue by phaux** [rollup/rollup#5375]
### Rollup Version

4.9.6

### Operating System (or Browser)

all

### Node Version (if applicable)

deno 1.40.3

### Link To Reproduction

just run `deno eval 'import "https://esm.sh/rollup"'`

### Expected Behaviour

[Docs](https://rollupjs.org/tools/#deno) say you can import rollup from esm.sh:

```js
import {rollup} from "https://esm.sh/rollup@2.61.1";
```

### Actual Behaviour

Version from the docs works but the latest version fails to build at esm.sh and others:

https://esm.sh/rollup@4.9.6 (error at https://esm.sh/v135/rollup@4.9.6/es2022/dist/native.js)
https://esm.run/rollup@4.9.6
https://cdn.skypack.dev/rollup@4.9.6

**Comment by TrickyPi** [comment]
Thanks for spotting. As a workaround, use `@rollup/browser` instead. I will update the docs later.
