### ISSUE TITLE
Replace glob.sync by globSync in code example

### ISSUE THREAD

**Issue by adazmy** [rollup/rollup#5376]
### Documentation is

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not sure?

### Please Explain in Detail...

On documentation section https://rollupjs.org/configuration-options/#input and in the provided configuration example, the `glob.sync` is no more supported by glob.

It's maybe the case in other sections too...

### Your Proposal for Changes

Use `globSync `instead of  `glob.sync` is broken since now it is `globSync `

**Comment by TrickyPi** [comment]
Is there any document where I can find information indicating that `glob.sync` is no longer supported by glob?

**Comment by adazmy** [comment]
https://github.com/isaacs/node-glob/issues/493#issuecomment-1447481501

I was having the same error:

```
...
TypeError: glob.sync is not a function
...
```

**Comment by TrickyPi** [comment]
It's weird. See https://stackblitz.com/edit/stackblitz-starters-7ggxfl?file=index.mjs. It works if using `import { glob } from 'glob'` instead. Anyway, the docs section is wrong.
