### ISSUE TITLE
NodeJS Core Dump on Specific Syntax Error (`Prop::Assign`)

### ISSUE THREAD

**Issue by curran** [rollup/rollup#5379]
### Rollup Version

4.9.6

### Operating System (or Browser)

Ubuntu Linux

### Node Version (if applicable)

v21.2.0

### Link To Reproduction

This repo contains a minimal reproduction for a Node environment:

https://github.com/curran/rollup-swc-crash-reproduction

The REPL reproduction fails to produce the exact same behavior that this issue is about, but may be of interest nevertheless to see how this error plays out in the WASM build:

https://rollupjs.org/repl/?version=4.9.6&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTdCJTVDbiUyMCUyMGJhciUyMCUzRCUyMGJheiUyQyU1Q24lN0QlM0IlNUNuY29uc29sZS5sb2coZm9vKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE

Here's another repro in the SWC Playground:

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVajmUlBISiwCspISq3S4aq25koGy%2BTmpejn56RpANZrWABhzMhQvAAAA&config=H4sIAAAAAAAAA1WPSQ7CMAxF9z1F5DVbWHCHHsIKbpUqk%2BJUIqp6d9JMwM7%2Bg598TELAxhKe4shjXjwGpjD2rHCyEd9ZAZIGWQblI9y6u%2FFlxbBTUc5qQMSwUiwlvrc0aOeYsragZmqaUVYt6ZcnnfGBmP%2BDVxTtqke%2F4qaGBONeezHbHzF5qvgHfEMdNg6D4rk3yxPnB%2BvJL0oTAQAA

### Expected Behaviour

When invoking Rollup in Node via the JS API with a source file that contains the following kind of syntax error:

```js
const foo = {
  bar = baz,
};
console.log(foo);
```

the call to this line:

```js
const bundle = await rollup(inputOptions);
```

should throw an error explaining that there is a syntax error.

### Actual Behaviour

Rollup surprisingly _does not throw_ the error, but rather seems to cause the entire Node process to crash (which ended up crashing my Web app server that invokes Rollup). This is the error that gets logged to the terminal:

```
thread '<unnamed>' panicked at parse_ast/src/convert_ast/converter.rs:848:26:
not implemented: Cannot convert Prop::Assign
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

Has anyone encountered this before? Anyone know of a way to prevent the process from crashing? Perhaps there's an option like `handleSWCError` or something? I wrapped the invication of Rollup in a try/catch, but this error is mysteriously never caught. Perhaps this is an upstream bug in SWC? Many thanks!

**Comment by curran** [comment]
## SWC Test

This repo also contains a minimal reproduction for a Node environment, invoking SWC directly with the same input:

https://github.com/curran/rollup-swc-crash-reproduction

```js
import swc from "@swc/core";

async function main() {
  const inputCode = `const foo = {
    bar = baz,
  };
  console.log(foo);`;

  try {
    const result = await swc.transform(inputCode, {
      jsc: {
        target: "es5",
      },
    });

    console.log(result.code);
  } catch (error) {
    console.log("Caught an error from SWC: ", error);
    console.error(error);
  }
}

main();
```

The output from that is:

```
$ npm run test-swc

> rollup-swc-crash-reproduction@1.0.0 test-swc
> node ./test-swc.js

thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_compat_es2015-0.4.0/src/duplicate_keys.rs:67:33:
internal error: entered unreachable code: assign property in object literal is invalid
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Caught an error from SWC:  [Error: failed to handle: internal error: entered unreachable code: assign property in object literal is invalid] {
  code: 'GenericFailure'
}
[Error: failed to handle: internal error: entered unreachable code: assign property in object literal is invalid] {
  code: 'GenericFailure'
}
```

**Comment by curran** [comment]
I'm evaluating alternatives for protecting the system in the mean time until this error gets resolved. I'm not sure what approach is best:

 * Spin up a separate process for the Rollup build and send messages to it, so that if that process crashes the app server will not go down
 * Put the app server behind a process manager like PM2, so that if this error occurs and the process goes down, the app server will automatically restart

**Comment by curran** [comment]
Happy to contribute here. I suppose the first step would be to add this file as a sample in one of the `test` directories? Not sure which one is best.

```js
const foo = {
  bar = baz,
};
console.log(foo);
```

**Comment by lukastaegert** [comment]
If SWC has the error, then there is likely nothing we can do in Rollup and the bug needs to fixed upstream in SWC.

**Comment by curran** [comment]
There is one key difference between the behavior of the [Rollup test](https://github.com/curran/rollup-swc-crash-reproduction/blob/main/test.js) and the [SWC test](https://github.com/curran/rollup-swc-crash-reproduction/blob/main/test-swc.js):

 * The SWC test has the expected behavior of throwing an error
 * The Rollup test has the unexpected behavior of not throwing an error, but instead crashing the Node process

Is there perhaps some place in the Rust side of Rollup where a try/catch or similar structure could be added, so that Rollup throws an error like the SWC Node library does?

**Comment by curran** [comment]
I've added a new test case here

https://github.com/rollup/rollup/pull/5381

**Comment by TrickyPi** [comment]
I guess the reason is that It triggers a panic in the Rust code.

https://github.com/rollup/rollup/blob/14425f92620beaf03d428dab12ca4424e35ad193/rust/parse_ast/src/convert_ast/converter.rs#L848

**Comment by curran** [comment]
Excellent! Thank you so much.
