### ISSUE TITLE
Rollup from a directory child to the rollup.config.js file

### ISSUE THREAD

**Issue by petulla** [rollup/rollup#538]
hey all

If I indicate in my rollup.config.js file that my entry is, say, `index.js`, how can I allow my projects to import a module from several directories towards root of that index file.

So let's say in `index.js` I import from `./../../modules/svg/text.js`

This throws: 

`Couldn't find preset "es2015-rollup" relative to directory "/Users/myusername/mydirectory/modules/svg"`

**Comment by Rich-Harris** [comment]
Looks like Babel is trying to resolve `babel-preset-es2015-rollup` relative to a directory *above* where it's installed. One possible fix:

```js
import babel from 'rollup-plugin-babel';
import es2015Rollup from 'babel-preset-es2015-rollup';

export default {
  entry: 'index.js',
  plugins: [
    // rather than passing a string, which must be resolved relative to
    // the file being transpiled, pass the preset itself
    babel({ presets: [ es2015Rollup ] })
  ],
  ...
};
```

Disclaimer: I haven't tried this!

**Comment by petulla** [comment]
This worked. Thanks Rich!
