### ISSUE TITLE
Missing known globals: WeakRef, FinalizationRegistry, AggregateError.

### ISSUE THREAD

**Issue by lichaozhy** [rollup/rollup#5387]
### Feature Use Case

`raw.js`,
```js
AggregateError;
WeakRef;
FinalizationRegistry;
```

A correct `bundle.js`,
```js
'use strict';
```

But current version,
```js
'use strict';
AggregateError;
WeakRef;
FinalizationRegistry;
```

### Feature Proposal

New global properties should be removed in bundle correctly.

**Comment by liuly0322** [comment]
Well, you need to set `treeshake.unknownGlobalSideEffects`, see [repl](https://rollupjs.org/repl/?version=4.16.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMkFnZ3JlZ2F0ZUVycm9yJTNCJTVDbldlYWtSZWYlM0IlNUNuRmluYWxpemF0aW9uUmVnaXN0cnklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQSU3QiUyMnVua25vd25HbG9iYWxTaWRlRWZmZWN0cyUyMiUzQWZhbHNlJTdEJTdEJTdE), you can toggle this option.

Refer to the [doc](https://rollupjs.org/configuration-options/#treeshake-unknownglobalsideeffects) for why this happens.

**Comment by lukastaegert** [comment]
True 😉 
But a PR to extend the list of known globals is also welcome: https://github.com/rollup/rollup/blob/5d8019b901e98cc8895751a23e5edfc9135b1a35/src/ast/nodes/shared/knownGlobals.ts#L148-L148
