### ISSUE TITLE
onLog documentation is lacking something

### ISSUE THREAD

**Issue by faniell** [rollup/rollup#5396]
### Documentation is

- [X] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not sure?

### Please Explain in Detail...

I am trying to use onLog with Rollup v3.23.0 and I use the example from the wiki:

```js
// rollup.config.js
export default {
	//...
	onLog(level, log, handler) {
		if (log.code === 'CIRCULAR_DEPENDENCY') {
			return; // Ignore circular dependency warnings
		}
		if (level === 'warn') {
			handler('error', log); // turn other warnings into errors
		} else {
			handler(level, log); // otherwise, just print the log
		}
	}
};
```

This has no effect.

I also have tried to use it like this. Something I found going through the code for Rollup on Github:

```js
// rollup.config.js
export default {
	input: "file.js",
	onLog: (level, log) => {
		if (log.code === 'CIRCULAR_DEPENDENCY') {
             		return; // Ignore circular dependency warnings
        	}
	},
	output: {...},
	plugins: [...]
}
```

Did not have success using onLog through a custom made plugin either.

### Your Proposal for Changes

I might be misunderstanding or something is missing from the onLog documentation. Can there be made changes to the documentation to clarify onLog and how to use it in more detail. I was not able to find any other uses of onLog while Googling.

**Comment by lukastaegert** [comment]
onLog was introduced in v3.25.0. I just wonder why you do not get a warning about an unknown option with v3.23.3
