### ISSUE TITLE
Mocking/Rewiring for Unit Tests

### ISSUE THREAD

**Issue by djskinner** [rollup/rollup#540]
Are there any established patterns for mocking imports when unit testing? With Webpack/Browserify I might have used Rewire. What's the Rollup way?

**Comment by Victorystick** [comment]
Rewiring dependencies like you describe would work a bit differently with Rollup than CommonJS-style bundlers. We haven't encountered this issue before, so we haven't investigated all the options yet.

One way would be to Rollup each individually, and use a plugin with some dependency rewriting feature to mock the dependencies you want. But it would probably be more convenient to use a package build with mocking in mind.

**Comment by eventualbuddha** [comment]
You could use [rollup-plugin-alias](https://www.npmjs.com/package/rollup-plugin-alias) for replacing entire modules, or [rollup-plugin-stub](https://github.com/eventualbuddha/rollup-plugin-stub) for manipulating just the named exports of a library. Note that the latter only really works with ES modules, not CJS.

**Comment by Victorystick** [comment]
@eventualbuddha I didn't know about those two plugins. I've added them to the Wiki.

**Comment by djskinner** [comment]
Yes thanks for pointing those out, I was thinking a plugin might be able to do the job but didn't see them on the list.
