### ISSUE TITLE
Tree shaking not being applied in some cases?

### ISSUE THREAD

**Issue by patrickarlt** [rollup/rollup#541]
I'm attempting to configure Rollup to generate a custom build of an existing library that includes a 'jsnext:main'. Everything is working but the resulting file include all output and isn't having its tree shaken.

Here is my config:

```js
import json from 'rollup-plugin-json';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'esri-leaflet-build.js',
  dest: 'esri-leaflet.js',
  moduleName: 'L.esri',
  format: 'umd',
  external: ['leaflet'],
  plugins: [
    nodeResolve({
      jsnext: true,
      main: false,
      browser: false,
      extensions: [ '.js', '.json' ]
    }),
    json()
  ],
  globals: {
    'leaflet': 'L'
  }
}
```

and my entry file

```js
import {
  FeatureManager,
  Task,
  Util,
  basemapLayer
} from 'esri-leaflet';

export default {
  FeatureManager: FeatureManager,
  Task: Task,
  Util: Util,
  basemapLayer: basemapLayer
}
```

[esri-leaflet](https://github.com/Esri/esri-leaflet/) has a `jsnext:main` in it's [package.json](https://github.com/Esri/esri-leaflet/blob/master/package.json#L52) that points to a [file that contains the exports statements](https://github.com/Esri/esri-leaflet/blob/master/src/EsriLeaflet.js):

```js
// export version
export {version as VERSION} from '../package.json';

// import base
export { Support } from './Support';
export { Util } from './Util';
export { get, post, request } from './Request';

// export tasks
export { Task, task } from './Tasks/Task';
export { Query, query } from './Tasks/Query';
export { Find, find } from './Tasks/Find';
export { Identify, identify } from './Tasks/Identify';
export { IdentifyFeatures, identifyFeatures } from './Tasks/IdentifyFeatures';
export { IdentifyImage, identifyImage } from './Tasks/IdentifyImage';

// export services
export { Service, service } from './Services/Service';
export { MapService, mapService } from './Services/MapService';
export { ImageService, imageService } from './Services/ImageService';
export { FeatureLayerService, featureLayerService } from './Services/FeatureLayerService';

// export layers
export { BasemapLayer, basemapLayer } from './Layers/BasemapLayer';
export { TiledMapLayer, tiledMapLayer } from './Layers/TiledMapLayer';
export { RasterLayer } from './Layers/RasterLayer';
export { ImageMapLayer, imageMapLayer } from './Layers/ImageMapLayer';
export { DynamicMapLayer, dynamicMapLayer } from './Layers/DynamicMapLayer';
export { FeatureManager } from './Layers/FeatureLayer/FeatureManager';
export { FeatureLayer, featureLayer } from './Layers/FeatureLayer/FeatureLayer';
```

I would expect that my output file `esri-leaflet.js` would only contain the code for `FeatureManager`, `Task`, `Util`, `basemapLayer` but instead it contains the entire library and only [exports the 4 things I want](https://gist.github.com/patrickarlt/97a2aa98766f325d2ae3#file-esri-leaflet-js-L3735-L3740). There are still things like `RasterLayer` in the output file https://gist.github.com/patrickarlt/97a2aa98766f325d2ae3#file-esri-leaflet-js-L1968 that shouldn't be.

----

I'm trying to think of reasons why this might be:

* Is the `export {thing, otherThing} from './thing.js'` not supported for some reason?
* Can modules resolved with `rollup-plugin-node-resolve` not be tree shaken?
* Something else?

**Comment by patrickarlt** [comment]
Just realized I didn't post my versions of everything:

* rollup version 0.25.4
* rollup-plugin-json ^2.0.0
* rollup-plugin-node-resolve 1.4.0

**Comment by Rich-Harris** [comment]
Rollup is conservative when it comes to statements that could have side-effects, since you might have a situation like this...

```js
// main.js
import { foo } from './foo.js';
foo();

// foo.js
alert( 'unexpected side-effect!' );

export function foo () {
  alert( 'expected side-effect!' );
}
```

...in which ignoring the first alert would be incorrect.

Code like `var RasterLayer = L.Layer.extend({...})` *might* have side-effects and might not – it's hard to know the value of `L.Layer.extend` without running the code, so Rollup has to assume that it might be a side-effect-inducing function. (Hard, but perhaps not impossible in all cases – filed under 'future research projects'.)

One possible workaround is to import directly from individual files rather than `jsnext:main`:

```js
import { FeatureManager } from 'esri-leaflet/src/Layers/FeatureLayer/FeatureManager.js';
import { Task } from 'esri-leaflet/src/Tasks/Task.js';
import { Util } from 'esri-leaflet/src/Util.js';
import { basemapLayer } from 'esri-leaflet/src/Layers/BasemapLayer.js';

export default {
  FeatureManager: FeatureManager,
  Task: Task,
  Util: Util,
  basemapLayer: basemapLayer
};
```

**Comment by patrickarlt** [comment]
Thanks for the very clear explanation @Rich-Harris. I'm going to close this now since my question has been answered.

Has an option like `assumeNoSideEffects` been discussed that would simply tell Rollup to assume that there are no side effects at all? That seems like a safe option that would cover some use cases.

**Comment by tymondesigns** [comment]
I'm also having a similar issue, would be great to be able to add an option to disable the assumption of side effects

**Comment by jgravois** [comment]
i tested post #902 refactor and Rollup still plays it conservative with regard to the specific possible side effects Rich describes above.
