### ISSUE TITLE
Expose module ids on error

### ISSUE THREAD

**Issue by joewalnes** [rollup/rollup#545]
I'm building a tool that adds a _watch_ wrapper to rollup.

It looks at the response to `rollup()` and pulls out the `module -> id` fields to see which files were used as source inputs. Each of these files are registered with a file watcher, so any updates can trigger a new rollup.

This works really well and has advantages over simply recursively watching an entire directory:
- users don't need to make decisions about which trees to watch as rollup knows all the exact files, even if they're loaded from other places (such as node_modules)
- only includes files that are actually relevant

However, if rollup fails with an error, it's currently not possible to know when to try again as the modules are never expose. It would be ideal if when the `rollup()` promise was rejected, the error would include all files that were loaded so far, and any file it expected to find but could not.

**Comment by joewalnes** [comment]
Any thoughts on this?

**Comment by Rich-Harris** [comment]
Sorry for the slow response. As of version 0.40, errors that are specific to a module will include a `loc: { file, line, column }` property as well as a `frame` property for locating errors.
