### ISSUE TITLE
Is it possible to build libraries that support IE8?

### ISSUE THREAD

**Issue by cbetta** [rollup/rollup#546]
I'm trying to figure out what the oldest IE is that I can support with libraries built with Rollup and Babel.

**Comment by Victorystick** [comment]
Rollup uses some ES5 features such as `getters` and `Object.freeze` to implement proper ES6 module semantics efficiently without resorting to [SystemJS-like overhead](https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained#how-it-works).

So long as you don't [export namespaces](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20*%20as%20module%20from%20'.%2Fmodule'%3B%5Cn%5Cnexport%20%7B%20module%20%7D%3B%22%7D%2C%7B%22name%22%3A%22module.js%22%2C%22code%22%3A%22export%20var%20count%20%3D%200%3B%5Cnexport%20function%20inc()%20%7B%20count%2B%2B%3B%20%7D%22%7D%5D%7D), Rollup should [generate IE8 compatible code](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20var%20count%20%3D%200%3B%5Cnexport%20function%20inc()%20%7B%20count%2B%2B%3B%20%7D%22%7D%5D%7D). Does that answer your question?

**Comment by cbetta** [comment]
Ok I think I need to start with a fresh project to test. Currently I'm using rollup and babel and I keep getting an `Expected identifier` error somewhere in the imported babel code (near `babelHelpers.typeof`).

I'll see if I can replicate in a smaller example and share.

**Comment by cbetta** [comment]
Ok so I managed to make an example app that throws an error: https://github.com/cbetta/rollup-ie8-test. I'd love some eyes on this to tell me if I'm doing something silly.

**Comment by eventualbuddha** [comment]
Babel expects an ES5 environment, so you'll probably need a polyfill if you plan to use Babel and want to target IE8. That's a Babel issue more than a rollup issue, so I suggest searching on babeljs.io etc.

**Comment by Victorystick** [comment]
Like @eventualbuddha says. Take a closer look at Babel. I'll close this issue in the mean time.

**Comment by cbetta** [comment]
Cheers, that helped a lot. Figured out the solution.


Add `babel-polyfill` and then add this to the browser:

```html
<script src="node_modules/babel-polyfill/dist/polyfill.min.js" charset="utf-8"></script>
```

**Comment by Jogiter** [comment]
mark i got an problem on ie8 2
