### ISSUE TITLE
rollup fails on non-transformed async functions

### ISSUE THREAD

**Issue by rustyedges** [rollup/rollup#548]
Without enabling babel plugin (and transpiling with regenerator runtime or transform-async-to-generators), the following simple code will fail to bundle with rollup, throwing unexpected token error...

```
const fn = async () => {
 return 'promise me this'
}

(async () => {
 const msg = await fn()
 console.log(msg)
})()
```

ran into this issue when trying to build app targeting chakracore.  my first step was to replace all import/export with require calls and strip client-side stuff and see it running successfully without bundling on node-chakra (which supports async/await as well)

Guess my understanding was that could use whatever your runtime supported and rollup could handle the bundling/tree shaking of ES6 modules without requiring babel transpilation?  Wonder how to track down full list of "next-generation" (ES6/7) language constructs that are supported without plugging in Babel?

**Comment by rustyedges** [comment]
Looking into this further, thinking comes down to limitation of acorn parser?
[](https://github.com/ternjs/acorn/issues/309)

so maybe need to include and enable this plugin?
[](https://github.com/MatAtBread/acorn-es7-plugin)

**Comment by Victorystick** [comment]
@rustyedges Rollup currently only targets ES6, although it'll likely get extended to ES7 shortly. For now, if you use >ES6 features, they'll need to be transpiled for Rollup to process them.

**Comment by rustyedges** [comment]
@Victorystick thanks for confirming and the work on rollup.  I realized I often conflate ES6 and ES7

**Comment by alippai** [comment]
FYI Chrome Canary and Edge Preview has async/await support now. Safari/Webkit will ship it in the next Technical Previews and Firefox is working on this as well.

**Comment by js-choi** [comment]
Mozilla Firefox, Microsoft Edge, Apple Safari (macOS and iOS), and the Blink platforms Google Chrome, Opera Browser, and Node have [all now shipped built-in async functions](http://kangax.github.io/compat-table/es2016plus/) to their stable releases. Async functions are now available without transpilation. This issue should be revisited.

**Comment by regou** [comment]
Any update about this? 
Some project that only running on modern browsers don't need transpile async functions

**Comment by bfred-it** [comment]
I don't think this is an issue in rollup 0.43. Rollup bundles the demo successfully:

```sh
$ cat a.js
const fn = async () => {
 return 'promise me this'
}

(async () => {
 const msg = await fn()
 console.log(msg)
})()                                                                               

$ rollup a.js --format iife
(function () {
'use strict';

const fn = async () => {
 return 'promise me this'
};

(async () => {
 const msg = await fn();
 console.log(msg);
})();

}());
```

Also shown in acorn's own tests: https://github.com/ternjs/acorn/blob/master/test/tests-asyncawait.js

@regou can you open a separate issue describing your problem, if any?

**Comment by kevinforrestconnors** [comment]
Installing `rollup-plugin-async` makes the external dependency warning go away, but I'm still getting `Uncaught ReferenceError: regeneratorRuntime is not defined`.  How to fix?

rollup.config.js:

```js
import babel from 'rollup-plugin-babel'
import resolve from 'rollup-plugin-node-resolve'
import pkg from "./package.json";
import async from 'rollup-plugin-async';

const external = [
    ...Object.keys(pkg.peerDependencies || {}),
    ...Object.keys(pkg.dependencies || {}),
];

const makeExternalPredicate = externalArr => {
    if (externalArr.length === 0) {
        return () => false;
    }
    const pattern = new RegExp(`^(${externalArr.join("|")})($|/)`);
    return id => pattern.test(id);
};

export default {
    input: 'src/cronreader.js',
    output: {
        file: 'dist/bundle.js',
        format: 'iife',
        globals: {
            "@babel/runtime/regenerator": "regeneratorRuntime",
            "@babel/runtime/helpers/asyncToGenerator": "asyncToGenerator"
        }
    },
    external: makeExternalPredicate(external),
    plugins: [
        async(),
        resolve({
            customResolveOptions: {
                moduleDirectory: 'src'
            }
        }),
        babel({
            runtimeHelpers: true,
            exclude: 'node_modules/**', // only transpile our source code
            presets: ["@babel/env"],
            plugins: [
                "@babel/transform-runtime",
                "@babel/transform-async-to-generator",
            ]
        })
    ]
}
```

I was referred to this page from here: https://stackoverflow.com/questions/39902076/babel-rollup-errors-transpiling-and-bundling-es2017/39936968#39936968
