### ISSUE TITLE
Using vinyl file as input

### ISSUE THREAD

**Issue by bedeoverend** [rollup/rollup#549]
Would it be possible to use a vinyl file as the entry point? I'm looking at using rollup on inline script tags in HTML - the only way to do this at the moment is with an intermediate temporary file that I give to rollup, it'd be great to be able to scrap this and feed rollup vinyl files. Cheers!

**Comment by eventualbuddha** [comment]
Yes, you can probably do this assuming vinyl can be converted to JavaScript with ES modules. See https://github.com/rollup/rollup-plugin-ractive for an example that may be similar or the list of other plugins on the wiki: https://github.com/rollup/rollup/wiki/Plugins

When you have something, post a link here and we'll be happy to give you feedback and add it to the wiki when it's ready.

**Comment by bedeoverend** [comment]
For future reference, the plugin I ended up making is [here](https://github.com/simplaio/rollup-plugin-file) would love to get feedback / contributions. Cheers!
