### ISSUE TITLE
Node 16 not supported any longer, can't run more modern Node's either

### ISSUE THREAD

**Issue by kungfooman** [rollup/rollup#5497]
### Rollup Version

HEAD

### Operating System (or Browser)

Linux ubuntu-2gb-nbg1-1 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Node Version (if applicable)

Node 16

### Expected Behaviour

Rollup should work like before.

### Actual Behaviour

I used Rollup for years and never had any problems with Node v16. Now Rollup's `package.json` suddenly demands v18. So I installed node v18, but now that doesn't work: https://stackoverflow.com/questions/72921215/getting-glibc-2-28-not-found

There are hundreds of people with the same problem as you can see by the upvotes and the solution is "install v16"... but now Rollup package.json declared that it requires node v18. Is there a technical reason behind it, a missing function in v16? It worked for years and I would like to continue using rollup on my servers that still only support node v16.

**Comment by TrickyPi** [comment]
Node 16 has reached EOL, So Node 18 is the minimum required version in the Rollup V4. Also, I see there are other workarounds in this link https://stackoverflow.com/a/74798469.

**Comment by kungfooman** [comment]
> Node 16 has reached EOL, So Node 18 is the minimum required version in the Rollup V4. Also, I see there are other workarounds in this link https://stackoverflow.com/a/74798469.

Your link links to https://www.digitalocean.com/community/questions/how-install-glibc-2-29-or-higher-in-ubuntu-18-04 which suggests:

1) Change OS
2) Build glibc from source

Both solutions seem rather tricky and non-trivial to me, so rollup pretty much killed all support for Ubuntu 18.04 LTS?

**Comment by TrickyPi** [comment]
Actually, RollupV4 can currently run on Node 16, but we don't guarantee that it will continue to do so.

**Comment by kungfooman** [comment]
> Actually, RollupV4 can currently run on Node 16, but we don't guarantee that it will continue to do so.

I know, but you will be spammed with dozens of warnings - that's the entire joke, there is no technical limitation justifying the deprecation...

**Comment by liuly0322** [comment]
I think the idea of "EOL" is, you can continue to use older version of **both old Node.js and npm packages**, or switch to newer version packages with newer Node.js version. Updating minimal Node.js version requirement can help reduce bugs in newer versions of packages.

So if you want to use newer version of packages, not only rollup, it is better upgrading Node.js. If you find upgrading OS hard, maybe try to use newer versions of Node.js in docker?
