### ISSUE TITLE
load hook is all or nothing

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup#550]
It would be nice to be able to intercept some of the load calls but not all, similar to how `resolveId` defers to other loaders or the default if you return undefined.

**Comment by Victorystick** [comment]
@calvinmetcalf `load()` should be able to return `null` to defer to another loader just like `resolveId()` can. See [this part of `rollup-plugin-typescript`](https://github.com/rollup/rollup-plugin-typescript/blob/master/src/index.ts#L65-L69) for an example.

**Comment by calvinmetcalf** [comment]
ah thanks, cleaned up the docs that had me confused https://github.com/rollup/rollup/wiki/Plugins/_compare/da85310a3b297163086d017bce548603f9506c82...8f9cfc89a75a617c49c1e0f9fba3bae454c85355

**Comment by Victorystick** [comment]
@calvinmetcalf Good idea. I'll clarify that the default is to load an id from the file system.
