### ISSUE TITLE
function parameter tracking does not handle spread syntax in arguments correctly

### ISSUE THREAD

**Issue by sapphi-red** [rollup/rollup#5502]
### Rollup Version

4.17.1

### Operating System (or Browser)

REPL

### Link To Reproduction

https://rollupjs.org/repl/?version=4.17.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm9vKGFyZzAlMkMlMjBhcmcxJTJDJTIwYXJnMiklMjAlN0IlNUNuJTIwJTIwaWYlMjAoYXJnMCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ2hhcyUyMGFyZzAnKSU1Q24lMjAlMjAlN0QlNUNuJTIwJTIwaWYlMjAoYXJnMSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ2hhcyUyMGFyZzEnKSU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25mb28oLi4uJTVCJ2FyZzAnJTJDJTIwJ2FyZzEnJTVEKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE

### Expected Behaviour

`has arg0` and `has arg1` is output when running the built file.

### Actual Behaviour

Only `has arg0` is output when running the built file.

**Comment by liuly0322** [comment]
Thanks, fix in #5503. According to [ecma262](https://tc39.es/ecma262/#prod-Arguments), The spread element can only be in the first-level of function call to change arguments length, so the fix should be enough.

**Comment by sapphi-red** [comment]
Thanks!
