### ISSUE TITLE
Allow exporting an Alias with iife / umd

### ISSUE THREAD

**Issue by paulfalgout** [rollup/rollup#553]
Libraries like jQuery, Ember and Marionette export their `moduleName` plus an additional alias `$`, `Em`, `Mn`.  I attempted to do this with Marionette in an admittedly hacky, but simple way by setting `moduleName` to `Marionette  = global.Mn`.
This worked until exporting with dot notation was added.  I can get around this by `Marionette = global['Mn']` but would this be something the library could support?

**Comment by Rich-Harris** [comment]
How about using the `footer` option?

```js
// rollup.config.js
export default {
  entry: 'src/main.js',
  format: 'iife',
  moduleName: 'Marionette',
  footer: 'window.Mn = window.Marionette;'
};
```

**Comment by Rich-Harris** [comment]
Will close this – using `footer` is the recommended solution to this issue
