### ISSUE TITLE
Node.JS 22.2.0 rollup 4.18.0 hits `[!] SyntaxError: Unexpected identifier 'assert'` error

### ISSUE THREAD

**Issue by khteh** [rollup/rollup#5531]
### Rollup Version

4.18.0

### Operating System (or Browser)

Ubuntu 24.04

### Node Version (if applicable)

22.2.0

### Link To Reproduction

https://github.com/khteh/Node.JSRestAPI

### Expected Behaviour

No build error

### Actual Behaviour

Running `rollup -c` hits the following error:
```
$ n run build_all

> node.jsrestapi@1.0.0 build_all
> npm-run-all clean build_core build_infra build_webapi build copy-assets


> node.jsrestapi@1.0.0 clean
> tsc --build --clean && rimraf build src/webapi.core/build src/infrastructure/build src/webapi/build


> node.jsrestapi@1.0.0 build_core
> npm run build --workspace=webapi.core


> webapi.core@1.0.0 build
> tsc --project tsconfig.json && npm run rollup


> webapi.core@1.0.0 rollup
> rollup -c

[!] SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:163:18)
    at callTranslator (node:internal/modules/esm/loader:430:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:436:30)
    at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)


npm error Lifecycle script `rollup` failed with error:
npm error code 1
npm error path /usr/src/Node.JSRestAPI/src/webapi.core
npm error workspace webapi.core@1.0.0
npm error location /usr/src/Node.JSRestAPI/src/webapi.core
npm error command failed
npm error command sh -c rollup -c
npm error Lifecycle script `build` failed with error:
npm error code 1
npm error path /usr/src/Node.JSRestAPI/src/webapi.core
npm error workspace webapi.core@1.0.0
npm error location /usr/src/Node.JSRestAPI/src/webapi.core
npm error command failed
npm error command sh -c tsc --project tsconfig.json && npm run rollup
ERROR: "build_core" exited with 1.
```

**Comment by TrickyPi** [comment]
https://github.com/khteh/Node.JSRestAPI/blob/1854f6de4641e7fd7e6e2a4fde03fda473652f74/src/webapi.core/rollup.config.js#L3
Import assertions (the `assert` keyword) have been removed from node starting in v22.0.0, please use `with` instead of.
See https://nodejs.org/en/blog/release/v22.0.0

**Comment by sibelius** [comment]
what is the fix ?

**Comment by theRatramnus** [comment]
Just replace `assert` with `with` 👍

**Comment by W3stside** [comment]
alternatively, for anyone coming here who cannot simply change `assert` to `with` and are maybe dealing with a transitive dependency can simply downgrade node (ie using `nvm` via `nvm i 20.9 && nvm use 20.9`) and trying again.

**Comment by Kegulf** [comment]
Hmm, we're still getting the same `assert` error message even when using `with`. 

```TS
import packageJson from "./package.json" with { type: "json" };
```

**Comment by Kegulf** [comment]
https://github.com/rollup/rollup/discussions/5299

**Comment by Kegulf** [comment]
Oooh, you know what it is? 😂 
We have `rollup.config.ts`, and to be able to use that config we have to build that file using `@rollupjs/plugin-typescript`.

I went back to a JS config file and it works perfectly.. 
So my issue is apparently different that the original issue here. But it does reveal what could be considered a bug in Rollup.
Rollup should not convert `with` to `assert` on build.

**Comment by TrickyPi** [comment]
> Rollup should not convert `with` to `assert` on build.

Please see https://rollupjs.org/configuration-options/#output-importattributeskey. You can choose different `importAttributesKey` values based on the Node runtime version.

**Comment by khteh** [comment]
> Did the simple change work for @khteh?

Yes it did

**Comment by tjdesigner** [comment]
> https://github.com/khteh/Node.JSRestAPI/blob/1854f6de4641e7fd7e6e2a4fde03fda473652f74/src/webapi.core/rollup.config.js#L3 Import assertions (the `assert` keyword) have been removed from node starting in v22.0.0, please use `with` instead of. See https://nodejs.org/en/blog/release/v22.0.0

Saved here brother! 🙌🏽 🤜🏽🤛🏽

**Comment by adriencaccia** [comment]
@Kegulf I had the same issue, made it work by using the [`--configImportAttributesKey with`](https://rollupjs.org/command-line-interface/#configimportattributeskey-with-assert) flag:

```bash
rollup --config rollup.config.ts --configPlugin typescript --configImportAttributesKey with
```

**Comment by KrisLau** [comment]
Getting `Parsing error: Unexpected token with` from eslint when I do that but the server runs fine. Not sure what I need to change to get rid of the error?
