### ISSUE TITLE
`@__NO_SIDE_EFFECTS__` annotation not working with imported function

### ISSUE THREAD

**Issue by TheDSCPL** [rollup/rollup#5557]
### Rollup Version

4.18.0

### Operating System (or Browser)

REPL

### Link To Reproduction

[REPL](https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZm9vJTIwZnJvbSUyMCdhJyUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGNhbGwlMjBpc24ndCUyMHJlbW92ZWQlMkMlMjBidXQlMjBpdCUyMHNob3VsZCUyQyUyMGJlY2F1c2UlMjAlNjBmb28lNjAlMjBpcyUyMGFubm90YXRlZCUyMHdpdGglMjAlNDBOT19TSURFX0VGRkVDVFMlMjBpbiUyMGl0cyUyMG1vZGlsZSU1Q25mb28oKSUzQiU1Q24lMkYqJTQwX19QVVJFX18lMjB0aGlzJTIwY2FsbCUyMGlzJTIwcmVtb3ZlZCUyMGJlY2F1c2UlMjBvZiUyMHRoZSUyMCU0MFBVUkUlMjBhbm5vdGF0aW9uKiUyRiU1Q25mb28oKSUzQiU1Q24lNUNuJTJGKiU0MF9fTk9fU0lERV9FRkZFQ1RTX18qJTJGJTVDbmZ1bmN0aW9uJTIwYmFyKCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIyQnllJTVDJTIyKSUzQiU1Q24lN0QlNUNuJTJGJTJGJTIwVGhpcyUyMGxvY2FsbHklMjBkZWNsYXJlZCUyMGZ1bmN0aW9uJ3MlMjBjYWxsJTIwaXMlMjByZW1vdmVkJTIwYXMlMjBleHBlY3RlZCU1Q25iYXIoKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjIlMkYqJTQwX19OT19TSURFX0VGRkVDVFNfXyolMkYlNUNuZnVuY3Rpb24lMjBmb28oKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJIZWxsbyU1QyUyMiklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZm9vJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0ElN0IlMjJhbm5vdGF0aW9ucyUyMiUzQXRydWUlN0QlN0QlN0Q=)

### Expected Behaviour

![imagem](https://github.com/rollup/rollup/assets/13943588/e28cc660-d783-4d22-af1b-81dc0cf6e1dc)

Take a function `foo` declared in a module with the `/*@__NO_SIDE_EFFECTS__*/` comment above its declaration. When `foo` is imported and called from another module, it should retain its no-side-effects attribute and be tree-shaken when used in such a way that would trigger tree-shaking.

### Actual Behaviour

![imagem](https://github.com/rollup/rollup/assets/13943588/740f4ae5-9322-40be-bc3a-22619e2eb060)

The call to the `foo` function doesn't get dropped even though `foo` is annotated as side-effect free in its module.

**Comment by lukastaegert** [comment]
The REPL requires imports to be written as relative imports, then it should work: https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZm9vJTIwZnJvbSUyMCcuJTJGYSclM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBjYWxsJTIwaXNuJ3QlMjByZW1vdmVkJTJDJTIwYnV0JTIwaXQlMjBzaG91bGQlMkMlMjBiZWNhdXNlJTIwJTYwZm9vJTYwJTIwaXMlMjBhbm5vdGF0ZWQlMjB3aXRoJTIwJTQwTk9fU0lERV9FRkZFQ1RTJTIwaW4lMjBpdHMlMjBtb2RpbGUlNUNuZm9vKCklM0IlNUNuJTJGKiU0MF9fUFVSRV9fJTIwdGhpcyUyMGNhbGwlMjBpcyUyMHJlbW92ZWQlMjBiZWNhdXNlJTIwb2YlMjB0aGUlMjAlNDBQVVJFJTIwYW5ub3RhdGlvbiolMkYlNUNuZm9vKCklM0IlNUNuJTVDbiUyRiolNDBfX05PX1NJREVfRUZGRUNUU19fKiUyRiU1Q25mdW5jdGlvbiUyMGJhcigpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMkJ5ZSU1QyUyMiklM0IlNUNuJTdEJTVDbiUyRiUyRiUyMFRoaXMlMjBsb2NhbGx5JTIwZGVjbGFyZWQlMjBmdW5jdGlvbidzJTIwY2FsbCUyMGlzJTIwcmVtb3ZlZCUyMGFzJTIwZXhwZWN0ZWQlNUNuYmFyKCklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyJTJGKiU0MF9fTk9fU0lERV9FRkZFQ1RTX18qJTJGJTVDbmZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIySGVsbG8lNUMlMjIpJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZvbyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBJTdCJTIyYW5ub3RhdGlvbnMlMjIlM0F0cnVlJTdEJTdEJTdE

**Comment by TheDSCPL** [comment]
:facepalm: You're right. Thank you
