### ISSUE TITLE
The compiled file fails with error during namespace mapping

### ISSUE THREAD

**Issue by vyshkov** [rollup/rollup#5559]
I am using Vite/Rollup for nest.js app bundling.

Here the config file:
```
import { defineConfig } from 'vite';
import { VitePluginNode } from 'vite-plugin-node';
import path from 'path';

export default defineConfig({
  build: {
    rollupOptions: {
      output: {
        format: 'cjs',
        entryFileNames: '[name].js' 
      }
    }
  },
  plugins: [
    ...VitePluginNode({
      adapter: 'nest',
      appPath: './src/index.ts',

      initAppOnBoot: false,
      tsCompiler: 'swc',

      swcOptions: {
        jsc: {
          parser: {
            syntax: 'typescript',
            dynamicImport: true,
            decorators: true
          },
          baseUrl: path.resolve('.'),
          paths: {
            '@libs/*': ['src/libs/*']
          },
          target: 'es2021',
          transform: {
            decoratorMetadata: true
          }
        }
      }
    })
  ],
  optimizeDeps: {
    exclude: ['@nestjs/microservices', '@nestjs/websockets']
  }
});
```

It compiles successfully.

However, when I execute the compiled file, the error is thrown:
```
Object.defineProperty(n, k, d.get ? d : {
                                      ^

TypeError: Cannot read properties of undefined (reading 'get')
    at _interopNamespaceDefault (pathToFile/index.js:34:39)
    at Module.<anonymous> (pathToFile/index.js:48:41)
    ...
```

I checked this part in the compiled code and it fails when it tries to access `setMaxListeners` from the `process`:
```
function _interopNamespaceDefault(e) {
  const n = Object.create(null, { [Symbol.toStringTag]: { value: 'Module' } });
  if (e) {
    for (const k in e) {
      if (k !== 'default') {
        const d = Object.getOwnPropertyDescriptor(e, k);
        Object.defineProperty(n, k, d.get ? d : { // <--- d is undefined, k is "setMaxListeners", e is process object
          enumerable: true,
          get: () => e[k]
        });
      }
    }
  }
  n.default = e;
  return Object.freeze(n);
}
```

The error is clear, `Object.getOwnPropertyDescriptor` will take the property of the object without iterating over its prototypes, and since `setMaxListeners` is a property of the `EventEmitter` it returns undefined.

it fails here during the process namespace mapping:
```
const AWS__namespace = /*#__PURE__*/_interopNamespaceDefault(AWS);
const dotenv__namespace = /*#__PURE__*/_interopNamespaceDefault(dotenv);
const fs__namespace = /*#__PURE__*/_interopNamespaceDefault(fs);
const process__namespace = /*#__PURE__*/_interopNamespaceDefault(process$1); // <--------------------------
const fastcsv__namespace = /*#__PURE__*/_interopNamespaceDefault(fastcsv);
```

However, this code is generated by rollup and I can't control it. 
How can I fix it?

**Comment by lukastaegert** [comment]
I see. So apparently some code is doing `import * as ... from 'process'`. It is really a pity that process supports named exports that come from the prototype chain as indeed, one assumption in Rollup's helpers is that all named exports are own properties of the namespace object even if it is required CommonJS. While I am not yet sure how to fix it in Rollup, here are several ways out for you:

1. If you can control the import, do not use a namespace import but named imports
2. Disable `output.externalLiveBindings`: This is something you usually do not need anyway, and it will use a simpler helper that iterates via `in` over the export. This would also pick up prototype chain properties: https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHglMjBmcm9tJTIwJ3Byb2Nlc3MnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyh4KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZXh0ZXJuYWxMaXZlQmluZGluZ3MlMjIlM0FmYWxzZSUyQyUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiU3RCU3RCU3RA==

**Comment by vyshkov** [comment]
I couldn't change the imports, but disabling `externalLiveBindings` helped. Thanks @lukastaegert!

**Comment by brunnerh** [comment]
While the given workarounds do work, I think this should be reopened & hopefully fixed.
I just ran into this with the code trying to resolve the key `'constructor'` as a property, which failed.

**Comment by xiaoxiyao** [comment]
I've also encountered this issue while using AMD modules. The `require` function's prototype was modified, causing the iteration to pick up properties from the prototype chain and fail. Helper functions generated by build tools should be defensive. I hope this can be fixed.

**Comment by tzahola** [comment]
Still broken. This should be documented somewhere other than a random closed GitHub issue.
