### ISSUE TITLE
Is it possible to lazy initialize modules?

### ISSUE THREAD

**Issue by philer** [rollup/rollup#557]
Is it possible to have rollup initialize a module only when it is actually needed on a particular page load?

Use case 1: **expensive side effects**

I'm writing a client-side standalone app (i.e. not a library). I have several modules that are only used on a few pages on certain occasions. Yet using my current simple rollup setup all modules in my monolithic output file are always initialized on every pageload.

Example: Let's consider a simple module that provides a modal (pop-up, overlay).
```JS
var $modal = $('<div id="modal">').appendTo('body');

export function show(content) {
  $modal.html(content).show();
}

export function hide() {
  $modal.hide().empty();
}
```
As you can see the first line initializes a DOM element. Of course this might be something bigger and more expensive. For that reason I only want to initialize it when it's actually needed:
```JS
// inside some other module…
if (somethingHappend)
  import * as modal from './modal.js';
  modal.show("things happened");
}
```
However this doesn't work; the contents of modal.js are hoisted to the top of the output file and are executed every time regardless of whether or not the module is actually needed.

Use case 2: **Lots of modules that are rarely needed**

This is a little more general. Basically I may have a project with lots of modules, maybe hundreds, and they each export their own set of functions. However many of these modules and functions may only be needed on a few pages. I'm not an expert on JS memory management but that seems like an awful lot of unneeded Function objects being created.

So my question is: Is it possible to achieve this kind of lazy loading and if so, how? I'm mostly interested in something elegant/native. I know I could add an `init()` function to my module and then check if it has already been called every time my module is accessed, but that's pretty ugly.

edit: It appears the behaviour I'm looking for already exists as a spec using `System.import` (as part of the ["ECMAScript 6 module loader API"](http://www.2ality.com/2014/09/es6-modules-final.html#the_ecmascript_6_module_loader_api)). Is this implemented in rollup? I can't find any documentation about it.

**Comment by Victorystick** [comment]
@philer `System.import` is indeed what you're looking for; have a look at [SystemJS](https://github.com/systemjs/systemjs) if you haven't already.

Implementing `System.import` is, however, out-of-scope for Rollup.
