### ISSUE TITLE
Handle absolute imports relative to `basedir`

### ISSUE THREAD

**Issue by sorgloomer** [rollup/rollup#558]
Hi there,

What is your opinion about supporting a `basedir` option, and resolving all the absolute imports relative to that basedir? Sometimes it's handy to just write `import '/constants';` instead of `import '../../../../../../constants';`.

Have a nice day!

**Comment by TrySound** [comment]
@sorgloomer Use custom resolver for that task.

**Comment by sorgloomer** [comment]
Thanks, works like a charm! I didn't know I can do that, didn't read the docs carefully.

For those who seek something similar, here is my resolver:

```
function resolveId(importee, importer) {
  if (isAbsolute(importee)) {
    const root = path.parse(importee).root;
    return ensureExt(path.resolve(basedir, path.relative(root, importee)));
  } else {
    const importer_dir = path.dirname(importer);
    return ensureExt(importer ? path.resolve(importer_dir, importee) : path.resolve(importee));
  }
   function isAbsolute(path) {
    return /^[\\\/]/.test(path);
  }
  function ensureExt(fn) {
    return /\.js$/.test(fn) ? fn : fn + '.js';
  }
}

...

rollup({
  plugins: [{ resovleId }]
}).then(...);
```

**Comment by TrySound** [comment]
You can try one of existed modules like [includepaths](https://github.com/dot-build/rollup-plugin-includepaths).

**Comment by luwes** [comment]
A variation on @sorgloomer's root import plugin which checks if the file exists.

```
const rootImport = (options) => ({
    resolveId: (importee, importer) => {
        if (importee[0] === '/') {
            const rootPath = `${options.root}${importee}.js`;
            const absPath = path.resolve(__dirname, rootPath);
            return fs.existsSync(absPath) ? absPath : null;
        }
        return null;
    }
});
```

```
    rootImport({
        root: 'static/js'
    }),
```

**Comment by RJahnavi** [comment]
Not sure if the below issue is related to this thread or not:
Rollup changes import of absolute path to relative path while bundling

I am importing a absolute path in some files of my repo and when I bundle it with rollup
My actual import where /api/ is absolute path looks like:
import * from '/api/myFile.js'

But when I bundle it, rollup changes it to relative path and it looks like:
import * from from '../../../../api/myFile.js'

And the above path doesn't exist in my app :(

My rollup config:
rollup src\input.js -o lib\bundle.js -f esm --inlineDynamicImports=true

I tried making '/api/' path as external, that didn't change anything. And i tried using few rollup plugins - includepaths, root-import,etc nothing worked
Is there any solution to this ?

**Comment by arcanis** [comment]
I also have this issue. My resolve returns absolute paths, but they are turned into relative one and it's not entirely clear which rules are used for this conversion (the `output.file` and `output.dir` settings seem to have no effect on it) 🤔

**Comment by piotr-cz** [comment]
I'm migrating from `snowpack^1` which stores dependencies in `/web_modules` directory and would like to replace import paths to packages from `node_modules`.

I was lucky with the [@rollup/plugin-alias](https://github.com/rollup/plugins/tree/master/packages/alias) plugin:

```js
import rollupPluginNodeResolve from '@rollup/plugin-node-resolve'
import rollupPluginCommonjs from '@rollup/plugin-commonjs'
import rollupPluginAlias from '@rollup/plugin-alias'

export default {
  // input,
  // output,
  plugins: [
    rollupPluginAlias({
      entries: [{
        find: /^\/web_modules\/(.*)\.js/,
        replacement: '$1',
      }]
    }),
    rollupPluginNodeResolve(),
    rollupPluginCommonjs(),
  ]
}
```

**Comment by eemeli** [comment]
I stumbled on this issue with the same problem, but then happily found the [output.paths](https://rollupjs.org/guide/en/#outputpaths) option, which solves it exactly.

**Comment by chowey** [comment]
As @eemeli points out, output.paths solves it. Here's the code that worked for me:

```js
export default {
  // ...
  output: {
    // ...
    paths: (id) => id,
  },
}
```

**Comment by mckravchyk** [comment]
If you use TypeScript you can easily set this up with `compilerOptions.baseUrl` 

tsconfig.json
```
{
  ...
  compilerOptions: {
    ...
    "baseUrl": "./"
  },
}
```

Then you can use:
```
import util from 'src/lib/util';
```

**Comment by mysuf** [comment]
I tried include-paths plugin, but it was pretty slow and it drops node-resolve capabilities. Then I've tried this solution and it works like a charm (probably due to 'default' resolver being first).

```
import { nodeResolve } from '@rollup/plugin-node-resolve'; // v13.0.6

{
  ...
  plugins: [
    nodeResolve({ moduleDirectories: ['src', 'node_modules'] }),
  ]
}
```

**Comment by ericmorand** [comment]
Please don't use @mckravchyk solution. It is clearly explained in TypeScript documentation that it only makes sense in conjuction with AMD module loaders:

> This feature was designed for use in conjunction with AMD module loaders in the browser, and is not recommended in any other context.

https://www.typescriptlang.org/tsconfig#baseUrl

**Comment by sorgloomer** [comment]
Multiple possible solutions were demonstrated here, there are probably even more after almost 8 years. I consider this issue solved. Many thanks to all commenters.
