### ISSUE TITLE
Invalid output code for ternary with nullish coalescing

### ISSUE THREAD

**Issue by bluwy** [rollup/rollup#5585]
### Rollup Version

4.19.0

### Operating System (or Browser)

macos

### Link To Reproduction

https://rollupjs.org/repl/?version=4.19.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjByZXN1bHQlMjAlM0QlMjAodHJ1ZSUyMCUzRiUyMCdhJyUyMCUzQSUyMCdiJyklMjAlM0YlM0YlMjAnYyclM0IlNUNuY29uc29sZS5sb2cocmVzdWx0KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlN0QlN0Q=

### Expected Behaviour

Given `const result = (true ? 'a' : 'b') ?? 'c';`, the output should be something like `const result = 'a'` if completely treeshaken.

### Actual Behaviour

Rollup outputs `const result = ('a' ;`, which is invalid. (Missing closing parentheses)

It happens only when treeshaking the code, so if `true` is replaced with a random global var like `foobar`, the output code is correct.

Found from https://github.com/withastro/astro/issues/11526

**Comment by TrickyPi** [comment]
closed same as #5583
