### ISSUE TITLE
Interactive sandbox freezes on `import '.x';`

### ISSUE THREAD

**Issue by sorgloomer** [rollup/rollup#559]
The interactive sandbox on rollupjs.org gets in an infinte loop if I try to import a module of which the name starts with a dot.

Steps to reproduce:

  * go to rollupjs.org (v0.25.4)
  * type: `import '.x';` in any source

**Comment by eventualbuddha** [comment]
Moved to the rollupjs.org tracker.

**Comment by eventualbuddha** [comment]
This is fixed now.
