### ISSUE TITLE
Wrong namespace property definition when namespaced `output.name` with first-level reserved key.

### ISSUE THREAD

**Issue by 7086cmd** [rollup/rollup#5603]
### Rollup Version

v4.20.0

### Operating System (or Browser)

macOS / Chrome

### Node Version (if applicable)

Does not apply

### Link To Reproduction

https://rollupjs.org/repl/?version=4.20.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAlN0IlMjBqb2luJTIwJTdEJTIwZnJvbSUyMCdub2RlJTNBcGF0aCclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGN1YmUoNSkpJTNCJTIwJTJGJTJGJTIwMTI1JTVDbmpvaW4oJ2EnJTJDJTIwJ2InKSU1Q25leHBvcnQlMjBkZWZhdWx0JTIwam9pbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZXhwb3J0cyUyMiUzQSUyMm5hbWVkJTIyJTJDJTIyZXh0ZW5kJTIyJTNBZmFsc2UlMkMlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiUyMm5vZGUlM0FwYXRoJTIyJTNBJTIyMSUyMiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJ0b1N0cmluZy52YWx1ZU9mLmhlbGxvJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

### Actual Behaviour

```js
this[undefined] = this[undefined] || {};
this[undefined].valueOf = this[undefined].valueOf || {};
this.toString.valueOf.hello = ...
```

### Expected Behaviour

```js
this.toString = this.toString || {};
this.toString.valueOf = this.toString.valueOf || {};
this.toString.valueOf.hello = ...
```

Or maybe throw an error 🤔 (?) It would be great to create a warning since it is an override to standard APIs, but it is not a illegal action.

These reserved keys include: `toString`, `valueOf`, etc.

**Comment by thirumurugan-git** [comment]
Hi @TrickyPi ,
I'm working to resolve this issue. Here's my [pull request](https://github.com/rollup/rollup/pull/5605). I'm happy to make any changes if needed. Thank you.
