### ISSUE TITLE
closeWatcher is not called on SIGINT (Ctrl + C)

### ISSUE THREAD

**Issue by m59peacemaker** [rollup/rollup#5615]
### Expected Behavior / Situation

It seems appropriate for `rollup -w` to add a SIGINT handler in which `watcher.close()` is called, triggering `closeWatcher` hooks, so that plugins that have need of `closeWatcher` can properly clean up.

### Actual Behavior / Situation

The `closeWatcher` hook is not called when the process from `rollup -w` is killed with SIGINT (e.g. via Ctrl + C).

### Modification Proposal

Simply add a `process.on('SIGINT', handler)` in the cli handler for `rollup -w` to gracefully close the watcher so that closeWatcher hooks are called.

I can likely prepare this PR if desirable.

**Comment by lukastaegert** [comment]
This should actually work already. We are using `signal-exit` to detect this and other signals and close the watcher here. I just noticed, though, that we are using it wrong, and `signal-exit` is synchronously killing the process before our async handler could trigger. Fix at #5619.
