### ISSUE TITLE
REPL not working if no `version` query provided

### ISSUE THREAD

**Issue by hyrious** [rollup/rollup#5617]
### Rollup Version

4.x

### Operating System (or Browser)

Chrome 127

### Link To Reproduction

https://rollupjs.org/repl/

### Expected Behaviour

The REPL should just work without `version` query in search params.

### Actual Behaviour

It just stops working, stuck in `Loading Rollup...`.

After digging into the devtools I found that when you [requests the rollup module without version field](https://github.com/rollup/rollup/blob/c4bb050/docs/repl/helpers/query.ts#L69), the wasm URL [was never constructed](https://github.com/rollup/rollup/blob/c4bb050/docs/repl/stores/rollup.ts#L40), thus it never tries to load rollup.

It seems simply deleting ` && version` would be enough to fix this issue.

**Comment by lukastaegert** [comment]
Thanks for spotting, should be fixed in a moment.
