### ISSUE TITLE
"import.meta.url" produced wrong code when output.compact is true and output.format is cjs or iife

### ISSUE THREAD

**Issue by eclosion** [rollup/rollup#5623]
### Rollup Version

4.21.0

### Operating System (or Browser)

windows11 edge

### Node Version (if applicable)

20.15.0

### Link To Reproduction

https://rollupjs.org/repl/?version=4.21.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKGltcG9ydC5tZXRhLnVybCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmNvbXBhY3QlMjIlM0F0cnVlJTJDJTIyZm9ybWF0JTIyJTNBJTIyaWlmZSUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=

### Expected Behaviour

```
console.log(import.meta.url);
```
should produce
```
(function(){'use strict';var _documentCurrentScript=typeof document!=='undefined'?document.currentScript:null;console.log((_documentCurrentScript && _documentCurrentScript.src || new URL('main.js', document.baseURI).href));})();
```

### Actual Behaviour

```
(function(){'use strict';var_documentCurrentScript=typeofdocument!=='undefined'?document.currentScript:null;console.log((_documentCurrentScript && _documentCurrentScript.src || new URL('main.js', document.baseURI).href));})();
```
so I got the error: ReferenceError: typeofdocument is not defined
it seems like that [the code at /src/utils/interopHelpers.ts#L74](https://github.com/rollup/rollup/blob/v4.21.0/src/utils/interopHelpers.ts#L74)
```
return `var${_}${DOCUMENT_CURRENT_SCRIPT}${_}=${_}typeof${_}document${_}!==${_}'undefined'${_}?${_}document.currentScript${_}:${_}null;${n}`;
```
should be
```
return `var ${DOCUMENT_CURRENT_SCRIPT}${_}=${_}typeof document${_}!==${_}'undefined'${_}?${_}document.currentScript${_}:${_}null;${n}`;
```

**Comment by TrickyPi** [comment]
Thanks for your spotting and nice resolution! filed a PR https://github.com/rollup/rollup/pull/5624 to close this issue.
