### ISSUE TITLE
plugin hook when dealing with circular deps

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup#563]
so a user can deal with it but it defaults to [this](https://github.com/rollup/rollup/blob/b50167646efe19297b40de49f19caebe2eb77018/src/Bundle.js#L352), the idea being that commonjs modules deal with cycles differently and for the commonjs plugin we might want to be able to do something like inline one module inside another.

**Comment by calvinmetcalf** [comment]
I suppose a globalTransform could be used for this, but it would still cause the warning to happen.

**Comment by bmeck** [comment]
I think this warning is valid, consider the following: 

Given:

```javascript
// a
import {export_b as import_b} from 'b';
export var export_a = 1;
console.log(import_b);
```

```javascript
// b
import {export_a as import_a} from 'a';
export var export_b = 2;
console.log(import_a);
```

All module resolution/binding is done *prior* to evaluation. So in the case of importing `a` according to ES spec:

1. `a` declares `export_a`
2. `a` grabs `b`
    1. `b` declares `export_b`
    2. `b` grabs `a`
    3. `b` shares `export_a` with `a` as `import_a`
3. `a` shares `export_b` with `b` as `import_b`
4. `b` executes
    1. `export_b` becomes `2`
    2. `console.log(import_a)` logs `undefined`
5. `a` executes
    1. `export_a` becomes `1`
    2. `console.log(import_b)` logs `2`

**Comment by calvinmetcalf** [comment]
so if we were actually in the ES6 module environment we'd be able to leverage the loader to deal with this issue, back when the loader spec was still in ES6 spec I was able to write a loader that handled almost all cjs stuff (only exception was requiring for side effects  in the middle of a module) and I assume that the current loader proposal is just as powerful.

I was more thinking in terms of the commonjs plugin which if we had

```js
// a
var b = require('b');
exports.foo = function () {
    b.baz();
};
exports.bar = function () {
   console.log('hello');
};

// b
var a = require('a'); 
exports.baz = function () {
   a.bar();
}
    
// main
var a = require('a');
a.foo();
```
This is contrived but valid commonjs, the best this can really be compiled to with the current hooks is something like 

```js
// a
var module$1 = {exports: {}};
var exports $1 = module$1.exports;
var b = module$2.exports;
exports.foo = function () {
    b.baz();
};
exports.bar = function () {
   console.log('hello');
};

// b
var module$2 = {exports: {}};
var exports $2 = module$1.exports;
var a$1 = module$1.exports;
exports$2.baz = function () {
   a$1.bar();
}
    
// main
var a$2 = module$1.exports;
a$2.foo();
```

but it really needs to be more like

```js
var module$1 = {exports: {}};
var exports $1 = module$1.exports;
var module$2 = {exports: {}};
var exports $2 = module$1.exports;
var a$1 = module$1.exports;
exports$2.baz = function () {
   a$1.bar();
}
var b = module$2.exports;
exports.foo = function () {
    b.baz();
};
exports.bar = function () {
   console.log('hello');
};

    
// main
var a$2 = module$1.exports;
a$2.foo();
```

**Comment by guybedford** [comment]
Tracking CommonJS execution ordering for cycles in https://github.com/rollup/rollup/issues/1507.
