### ISSUE TITLE
Unexpected error occurs using Rollup with rollup-plugin-serve and  start-server-and-test  since rollup@4.21.1

### ISSUE THREAD

**Issue by elchininet** [rollup/rollup#5641]
### Rollup Version

4.21.1 / 4.21.2

### Operating System (or Browser)

MacOS 14.5

### Node Version (if applicable)

20.17.0

### Link To Reproduction

https://github.com/elchininet/shadow-dom-selector

### Expected Behaviour

The expected behaviour is not having the issue described in the `Actual behaviour`.

### Actual Behaviour

I really don't know if this issue is coming from `rollup` or from another package (because I use `rollup-plugin-serve` and `start-server-and-test` to run my tests) but the issue is reproducible when I update `rollup` to a greater version than `4.21.0` and this has been working without issues for months. I have reviewed the commits in this version and I cannot identify any change that could cause this, so I would need your help to understand from which place this is coming.

Follow the nex steps to reproduce it:

1. Clone [the provided repo](https://github.com/elchininet/shadow-dom-selector)
2. Run `pnpm i`
3. Run `pnpm test:ci`
4. Tests will pass without issues
5. Update `rollup` in `package.json` to `4.21.1` (or to `4.21.2`)
6. Run `pnpm i`
7. Run `pnpm test:ci`
8. You will receive:

```bash
> shadow-dom-selector@4.1.2 test:ci /shadow-dom-selector
> pnpm clean && start-server-and-test 'pnpm demo' http://localhost:3000 'pnpm test:run'


> shadow-dom-selector@4.1.2 clean /shadow-dom-selector
> rm -rf dist .nyc_output coverage || true

1: starting server using command "pnpm demo"
and when url "[ 'http://localhost:3000' ]" is responding with HTTP status code 200
running tests using command "pnpm test:run"


> shadow-dom-selector@4.1.2 demo /shadow-dom-selector
> rollup --config rollup.test.config.js --bundleConfigAsCjs -w

Error: server closed unexpectedly
    at ChildProcess.onClose (/shadow-dom-selector/node_modules/.pnpm/start-server-and-test@2.0.5/node_modules/start-server-and-test/src/index.js:83:14)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
 ELIFECYCLE  Command failed with exit code 1.
```

[Here is a Workflow](https://github.com/elchininet/shadow-dom-selector/actions/runs/10757386433/job/29831361013?pr=79) in which Dependabot updated `rollup` and the issue can be seen in the `tests` job. I stopped Dependabot to upgrade `rollup` for now, but I would like to find a better solution.

>Note: If I execute `pnpm demo` the server starts without issues and I can visit the demo page in `http://localhost:3000`. That is why I am not really sure if the issue is coming from `rollup`, but it occurs when I update it.

**Comment by elchininet** [comment]
Hi @sunnylost,
Thanks for the detailed explanation, now I understand what is happening. I was looking at that commit but nothing called my attention, now I get it.
Thanks again 👍

**Comment by elchininet** [comment]
I think that this can be easily fixed from `start-server-and-test`. Previously it piped the main `stdin` to the server and the tests. [This pull request](https://github.com/bahmutov/start-server-and-test/pull/369) fixed that sending different `stdins` but for some reason the `stdin` for the server was set as `ignore`, I think that it makes sense to set the `stdin` for the server as `inherit` too, I have already tested it and it solves the issue completely and I can update to `4.21.2`.

I'll open an issue in `start-server-and-test` to se if it can be fixed, but for now I'll work with a patched version of that package, so I can allow @dependabot to update `rollup`.

**Comment by elchininet** [comment]
Well, even if it solved the issue on my local, it doesn't solve the issue during [a Github workflow](https://github.com/elchininet/shadow-dom-selector/pull/83). I think that on CI `isTTY` should return false, so it should not call close if the `stdin` reaches its end, isn't it?

**Comment by sunnylost** [comment]
I set up the same repository on GitHub, and its CI E2E tests work fine. You might want to consider avoiding a PR and updating directly instead.

**Comment by elchininet** [comment]
So, do you think that it is an issue with permissions?

**Comment by elchininet** [comment]
>I set up the same repository on GitHub, and its CI E2E tests work fine. You might want to consider avoiding a PR and updating directly instead.

That‘s weird, I merged it directly and this in `master`:

https://github.com/elchininet/shadow-dom-selector/actions/runs/10773736199/job/29874172254

Do you have something special on your side?

**Comment by sunnylost** [comment]
No, just cloned your repo, nothing else.

**Comment by elchininet** [comment]
And the end-to-end tests work with that change in your repo? Or do you mean in master before the change? Could you try to sync the repo and check with the latest master?

**Comment by sunnylost** [comment]
OK, finally I make it run. 

Reason:

https://github.com/nodejs/node/issues/43302

Solution:

https://github.com/sunnylost/shadow-dom-selector/blob/master/.github/workflows/tests.yaml#L3-L5

You have to setup a shell. Add these code at the top of `tests.yaml`:

```yaml
defaults:
  run:
    shell: 'script -q /dev/null bash -e {0}'
```

**Comment by elchininet** [comment]
>OK, finally I make it run.

Oh man, thanks for the debugging. Let me implement it.
Thanks!

**Comment by sunnylost** [comment]
I also changed the action's OS, and it ran successfully:

https://github.com/sunnylost/shadow-dom-selector/actions/runs/10776799117

```yaml
jobs:      
  tests:
    runs-on: macos-13
```

If you encounter any other problems, you may want to consider changing this.

**Comment by elchininet** [comment]
>I also changed the action's OS, and it ran successfully:

Yep, it seems that the issue is the Linux runner because with the script what happens is that [it hides everythinh from the output](https://github.com/elchininet/shadow-dom-selector/actions/runs/10777429936/job/29886552944) (I am not even sure that tests run because everything is executed in milliseconds) and the Coverage fails.

What happens with a MacOS runner is that [the minutes per month for my free acount are reduced by ten](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

I'll rever for now to keep `rollout` in version `4.21.0` for now :(

**Comment by elchininet** [comment]
Hi @sunnylost,
I solved the issue just removing `start-server-and-test` and replacing it by the builtin `webServer` `Playwright`'s feature. It seems that there is no issue with both libraries it is just an unfortunate coincidence of putting them to work in tandem.

https://github.com/elchininet/shadow-dom-selector/pull/86

Closing this issue 👍
