### ISSUE TITLE
Treeshaking react-dnd is too eager

### ISSUE THREAD

**Issue by skovhus** [rollup/rollup#5650]
### Rollup Version

4.9.2+

### Operating System (or Browser)

MacOS

### Link To Reproduction

[repl](https://rollupjs.org/repl/?version=4.21.3&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMGh0dHBzJTNBJTJGJTJGZ2l0aHViLmNvbSUyRnJlYWN0LWRuZCUyRnJlYWN0LWRuZCU1Q24lNUNuaW1wb3J0JTIwJTdCc3VwcG9ydHNQYXNzaXZlJTdEJTIwZnJvbSUyMCcuJTJGc3VwcG9ydHNQYXNzaXZlJyU1Q24lNUNuZnVuY3Rpb24lMjBhZGRFdmVudExpc3RlbmVyKHN1YmplY3QlMkMlMjBldmVudCUyQyUyMGhhbmRsZXIlMkMlMjBjYXB0dXJlJTIwJTNEJTIwZmFsc2UpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwb3B0aW9ucyUyMCUzRCUyMHN1cHBvcnRzUGFzc2l2ZSUyMCUzRiUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjYXB0dXJlJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHBhc3NpdmUlM0ElMjBmYWxzZSU1Q24lMjAlMjAlMjAlMjAlN0QlMjAlM0ElMjBjYXB0dXJlJTNCJTVDbiUyMCUyMCUyMCUyMHRoaXMubGlzdGVuZXJUeXBlcy5mb3JFYWNoKGZ1bmN0aW9uKGxpc3RlbmVyVHlwZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc3QlMjBldnQlMjAlM0QlMjBldmVudE5hbWVzJTVCbGlzdGVuZXJUeXBlJTVEJTVCZXZlbnQlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoZXZ0KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBzdWJqZWN0LmFkZEV2ZW50TGlzdGVuZXIoZXZ0JTJDJTIwaGFuZGxlciUyQyUyMG9wdGlvbnMpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiUyMCUyMCU3RCU1Q24lNUNuYWRkRXZlbnRMaXN0ZW5lcigpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBodHRwcyUzQSUyRiUyRmdpdGh1Yi5jb20lMkZyZWFjdC1kbmQlMkZyZWFjdC1kbmQlMkZibG9iJTJGbWFpbiUyRnBhY2thZ2VzJTJGYmFja2VuZC10b3VjaCUyRnNyYyUyRnV0aWxzJTJGc3VwcG9ydHNQYXNzaXZlLnRzJTIwJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMHN1cHBvcnRzUGFzc2l2ZSUyMCUzRCUyMCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBsZXQlMjBzdXBwb3J0ZWQlMjAlM0QlMjBmYWxzZSUzQiU1Q24lMjAlMjB0cnklMjAlN0IlNUNuJTIwJTIwJTIwJTIwYWRkRXZlbnRMaXN0ZW5lciglNUMlMjJ0ZXN0JTVDJTIyJTJDJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTIwT2JqZWN0LmRlZmluZVByb3BlcnR5KCU3QiU3RCUyQyUyMCU1QyUyMnBhc3NpdmUlNUMlMjIlMkMlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwZ2V0KCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwc3VwcG9ydGVkJTIwJTNEJTIwdHJ1ZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjB0cnVlJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QpKSUzQiU1Q24lMjAlMjAlN0QlMjBjYXRjaCUyMChlMyklMjAlN0IlNUNuJTIwJTIwJTdEJTVDbiUyMCUyMHJldHVybiUyMHN1cHBvcnRlZCUzQiU1Q24lN0QpKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyc3VwcG9ydHNQYXNzaXZlLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBJTIyc21hbGxlc3QlMjIlN0QlN0Q=)

### Expected Behaviour

`supportsPassive` from [react-dnd](https://github.com/react-dnd/react-dnd/blob/main/packages/backend-touch/src/utils/supportsPassive.ts) should not be tree-shaken – it depends on runtime side effects.

### Actual Behaviour

`supportsPassive` is just removed when Vite's default configuration. 

Note that the problem can't be reproduced in rollup@4.9.1, but is found in version 4.9.2+. The problem is naturally also present in downstream dependencies such as Vite from version 5.2.0 (that bumped rollup from 4.2.0 to 4.13.0).

**Comment by skovhus** [comment]
Might be a duplicate of https://github.com/rollup/rollup/issues/5408

But seems like a pretty severe bug.

**Comment by skovhus** [comment]
@lukastaegert created a PR to revert the faulty changes here: https://github.com/rollup/rollup/pull/5654

**Comment by lukastaegert** [comment]
The change is not faulty even if it caused these issues. It is just that the over-eager TDZ detection heuristic "saved" use before, but I would not like to rely on this to prevent these issues. I am preparing a more thorough solution.

**Comment by skovhus** [comment]
> I am preparing a more thorough solution.

That sounds great, thanks for looking into this. 

Regarding wording here, then my thinking is: anything that unexpectedly breaks applications functionality is faulty. And I would ideally prefer that those changes are rolled back, but I can manually do a pnpm patch until a proper fix has landed.

**Comment by lukastaegert** [comment]
Here is the fix: #5658

**Comment by skovhus** [comment]
Thanks for the fast turnaround!
