### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by jackfromeast** [rollup/rollup#5652]
### Documentation is

- [X] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not sure?

### Please Explain in Detail...

Hi, rollup maintainers!

Could we set up a security policy for this repository to support responsible reporting of security issues?

Thank you!

### Your Proposal for Changes

The following is just the default template from Github, please feel free to use it as a reference.

# Security Policy

## Supported Versions

Use this section to tell people about which versions of your project are
currently being supported with security updates.

| Version | Supported          |
| ------- | ------------------ |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :x:                |
| 4.0.x   | :white_check_mark: |
| < 4.0   | :x:                |

## Reporting a Vulnerability

Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.

**Comment by lukastaegert** [comment]
What kind of security issues are you thinking of in a CLI tool that has full hard drive access and executes arbitrary code provided by plugins?

**Comment by jackfromeast** [comment]
Hi @lukastaegert! 

In short, we have found a DOM Clobbering gadget that can lead to XSS in rollup bundled scripts. The following issue might be a good reference: https://github.com/webpack/webpack/security/advisories/GHSA-4vvj-4cpr-p986, which is the same similar problem we found in Webpack.

**Comment by lukastaegert** [comment]
I see. That makes sense, though I must admit this is our very first CVE ever, hence we do not really have a process for this, or a simple way to release updates for older versions. I guess the policy will be that only the latest version receives updates until someone finds time to set up something better.

**Comment by jackfromeast** [comment]
Hi @lukastaegert, do we have a plan to set up the security policy and private vulnerability reporting? This will help us report and safely patch the security issue.

**Comment by lukastaegert** [comment]
Sorry for the wait. I hope I set it up correctly now, can you check?

**Comment by jackfromeast** [comment]
Thanks! I just reported the problem privately and hope you can find time to check it :>
