### ISSUE TITLE
error building/running tensorflow-js (tfjs) with rollup v4.22.0 on Linux container

### ISSUE THREAD

**Issue by ryanxcharles** [rollup/rollup#5661]
### Rollup Version

4.22.0

### Operating System (or Browser)

Linux/all browsers

### Node Version (if applicable)

20.8.1

### Link To Reproduction

https://powvalidator-com.fly.dev/test

### Expected Behaviour

tfjs should load with no error.

### Actual Behaviour

There are mysterious errors that seem to have nothing to do with rollup, and tfjs does not work. I currently have a demo of the tfjs loading at the URL above - please check the browser console.

Here is a screen shot of the error:

![Screenshot 2024-09-19 at 9 13 47 AM](https://github.com/user-attachments/assets/419081d1-9ceb-4d69-b0cf-05f760094cfc)

Here is the place in tfjs where it is throwing an error:

![Screenshot 2024-09-19 at 9 14 07 AM](https://github.com/user-attachments/assets/04d5960a-bf81-454f-8155-b071d88c111c)

The error doesn't look like it has anything to do with rollup, but I have empirically verified that the only variable is when I upgrade from rollup v4.21.3 to v4.22.0, that is when the error occurs. I must run rollup v4.21.3 in production to prevent this error from occuring.

Note that I have not been able to reproduce this error on my macOS machine. The only time the error occurs is when I build and run for production inside a Linux container. I am using vite if that makes any difference. I have tried building/running for production on macOS with no ability to reproduce. Therefore, reproducing is a bit annoying as I can only reproduce the issue inside a container.

**Comment by lukastaegert** [comment]
Can you check if the error persists with 4.22.1? We rolled back part of the changes in 4.22.0 which we suspected to cause the issue, would be nice to get confirmation.

**Comment by ryanxcharles** [comment]
Unfortunately that didn't fix the issue, @lukastaegert . I tried upgrading to v4.22.1, and I get the same issue. I then downgraded back to v4.21.3, and the issue goes away.

Just to re-iterate:
- I am not able to reproduce on macOS. tfjs builds and runs fine.
- Only when tfjs is build/run inside a linux/amd64 container does the issue occur.
- This leads me to suspect that something has changed about the way rollup is building on linux/amd64, but not macOS, is causing tfjs to build wrongly, and it no longer runs in a browser.
- Both v4.22.0 and v4.22.1 have the issue.

I could probably produce a simple demonstration if that would help. I think simply building any front-end application with tfjs built on a linux/amd64 container would probably have the issue.

**Comment by lukastaegert** [comment]
> I am not able to reproduce on macOS

That is a good hint, will try in Docker.

**Comment by lukastaegert** [comment]
See #5669, please give `4.22.3-0` a spin to see if it fixes your issues as well.

**Comment by ryanxcharles** [comment]
Great job, @lukastaegert ! I believe that fixed the issue. I deployed with 4.22.3-0 and the issue seems to have vanished. Thank you!

**Comment by lukastaegert** [comment]
Thanks for checking!

**Comment by lukastaegert** [comment]
Closed via v4.22.3
