### ISSUE TITLE
Error from swc since version 4.22.1 - when the ៘ is used

### ISSUE THREAD

**Issue by kfirstri** [rollup/rollup#5672]
### Rollup Version

4.22.1

### Operating System (or Browser)

macos 14.6.1

### Node Version (if applicable)

18.16.0

### Link To Reproduction

https://rollupjs.org/repl/?version=4.22.4&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKCU1QyUyMiVFMSU5RiU5OCU1QyUyMiklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTdEJTdE

### Expected Behaviour

Rollup should work fine and run file that has this character: ៘ 

It worked fine in version 4.22.0 

Reproduce that works: 
https://rollupjs.org/repl/?version=4.22.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKCU1QyUyMiVFMSU5RiU5OCU1QyUyMiklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiU3RCU3RA==

### Actual Behaviour

Ever since version 4.22.1 (and later) - if we have this character (៘) in the file (code or comment) rollup crashes with this error:
```
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_common-0.39.0/src/syntax_pos.rs:702:18:
width 3 given for non-narrow character
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x11137fd58 - _napi_register_module_v1
   1:        0x11131d558 - <unknown>
   2:        0x11135d0c8 - _napi_register_module_v1
   3:        0x111380de0 - _napi_register_module_v1
   4:        0x111381f94 - _napi_register_module_v1
   5:        0x111381224 - _napi_register_module_v1
   6:        0x1113811c0 - _napi_register_module_v1
   7:        0x1113811b4 - _napi_register_module_v1
   8:        0x111495850 - _napi_register_module_v1
   9:        0x1114958ac - _napi_register_module_v1
  10:        0x111495864 - _napi_register_module_v1
  11:        0x111316b64 - <unknown>
thread caused non-unwinding panic. aborting.
error Command failed with signal "SIGABRT".
```

----

I wanted to add more context to the issue ->

We have a vite project that has a non-direct dependency to [fbjs](https://www.npmjs.com/package/fbjs).
One of the files that's being used is [UnicodeBidi.js](https://github.com/facebook/fbjs/blob/main/packages/fbjs/src/unicode/UnicodeBidi.js) which has the unicode representation of the "៘" character...

vite unescapes unicode to string ([security issue that was raised](https://github.com/vitejs/vite/issues/12676)) which eventually brings this character to rollup as a string which makes it crash.

I'm guessing it's related to swc version bump that happened in version 4.22.1 ([source](https://github.com/rollup/rollup/commit/c6f1e2775ed5f04e900479d3fb4052d8e55335a7#diff-451baee557d6e77c80c112f10d0d55f753ca56cdc987870a580a075f218b0600R10))

**Comment by rodericktech** [comment]
I was getting the same bug Friday, as a result of the same UnicodeBidi.js file.  It took a long time to troubleshoot and by the time I figured out I needed to revert `rollup` to 4.21.3 (maybe 4.22.0 would have worked?) it was about 2:00am where I live and I didn't raise the issue.  Thanks @kfirstri for raising it, it was on my list to do this morning.

**Comment by MaziyarMK** [comment]
yarn package.json workaround for the time being:

```
"resolutions": {
  "rollup": "4.22.0"
}
```

**Comment by Jinjiang** [comment]
Got the same error from last Friday on a project based on Vite:

```
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_common-0.39.0/src/syntax_pos.rs:702:18:
width 3 given for non-narrow character
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x122b13d58 - _napi_register_module_v1
   1:        0x122ab1558 - <unknown>
   2:        0x122af10c8 - _napi_register_module_v1
   3:        0x122b14de0 - _napi_register_module_v1
   4:        0x122b15f94 - _napi_register_module_v1
   5:        0x122b15224 - _napi_register_module_v1
   6:        0x122b151c0 - _napi_register_module_v1
   7:        0x122b151b4 - _napi_register_module_v1
   8:        0x122c29850 - _napi_register_module_v1
   9:        0x122c298ac - _napi_register_module_v1
  10:        0x122c29864 - _napi_register_module_v1
  11:        0x122aaab64 - <unknown>
thread caused non-unwinding panic. aborting.
```
