### ISSUE TITLE
@rollup/rollup-freebsd-arm64@4.24.1 is failing from the latest release for rollup

### ISSUE THREAD

**Issue by srinivasangurukannan** [rollup/rollup#5704]
error Couldn't find package **"@rollup/rollup-freebsd-arm64@4.24.1**" required by **"rollup@^4.2.0"** on the "npm" registry.

**Comment by CQuarterz** [comment]
I am having the same issue, never had this issue before the last hour

**Comment by talmalul-leap** [comment]
I'm having the same issue.
I'm using Vite and it looks like the latest version of rollup (4.24.1) is broken.
They just release this version about an hour ago.

**Comment by alije123** [comment]
i faced too and adding "resolutions": {
    "rollup": "4.24.0"
  } to package.json fixes it

**Comment by talmalul-leap** [comment]
@alije123 god bless you

**Comment by xxxhand** [comment]
I am having the same issue.

**Comment by mistlight** [comment]
the nodejs community, never change...

**Comment by NeViNez** [comment]
Actually this problem occurs when using `yarn` for installing `rollup` latest package - `yarn add -D rollup`

Using `npm` works fine on latest version.

**Comment by srinivasangurukannan** [comment]
Tried the build with npm and it works !!

Yarn build fails

**Comment by srinivasangurukannan** [comment]
> i faced too and adding
> 
> ```
> "resolutions": {
>     "rollup": "4.24.0"
>   }
> ```
> 
> to package.json fixes it
..
This will work only if we are using directly in our package.json.
The template like vite.js / vue.js has to wait for update

**Comment by CQuarterz** [comment]
> Tried the build with npm and it works !!
> 
> Yarn build fails

Yup seems to be a yarn issue not an npm though

**Comment by alije123** [comment]
@srinivasangurukannan, i only have vite in my dev dependencies and it works fine. Yarn 4.5.1

**Comment by kamdz** [comment]
I have the same issue, comes from tsup (has rollup as dep)

**Comment by tagattie** [comment]
It appears PR #5698 (which was created by me) broke an installation of rollup 4.24.1 using yarn. I opened another PR #5705 which should fix the error. I hope the proposed change will be merged shortly.

Sorry for the breakage.

**Comment by shiva-karthick** [comment]
Thanks for your help @tagattie, really appreciate it. :)

**Comment by garraflavatra** [comment]
For the record: I just noticed it also fails with Bun. 

Thank you for the quick fix @tagattie 👍

**Comment by lukastaegert** [comment]
Should be fixed now, sorry for the mess.
