### ISSUE TITLE
extract license info and do something with it

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#571]
Good idea from @ericf: https://medium.com/@ericf/rich-harris-it-would-be-interesting-if-rollup-help-build-a-license-file-based-on-the-packages-you-feeff46affd5#.vde6wss1x

**Comment by tikitu** [comment]
CocoaPods (iOS packaging system) does [something similar](https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements) -- might be worth a look for inspiration?

**Comment by bfred-it** [comment]
That's interesting, perhaps that belongs to something like [`rollup-plugin-license`](https://github.com/rollup/rollup/issues/490#issuecomment-178801064)?

**Comment by mjeanroy** [comment]
Hi @Rich-Harris,
For information, I created [a plugin](https://www.npmjs.com/package/rollup-plugin-license) that can do that. I use it on a small project and I would be happy to have feedbacks if someone use it.

**Comment by Rich-Harris** [comment]
@mjeanroy the plugin is an excellent idea! Thanks, have added it to the [wiki](https://github.com/rollup/rollup/wiki/Plugins)
