### ISSUE TITLE
Base16 character set used in hashes is incorrect

### ISSUE THREAD

**Issue by heftymouse** [rollup/rollup#5710]
### Expected Behavior / Situation

Using the `--hashCharacters hex` option should use the character set defined as Base16 in [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648.html#section-8) and the usual definition of hexadecimal.

### Actual Behavior / Situation

Rollup uses an unusual character set `abcdef0123456789` instead of `0123456789abcdef`, which, while documented as such, is not very obvious and can be a pitfall when the developer assumes the typical meaning of Base16.

### Modification Proposal

Make the Base16 hashing function output hexadecimal in its usual meaning.

**Comment by lukastaegert** [comment]
We can definitely do that, though I wonder how you stumbled upon this and especially where it caused an issue? After all, for most use cases, hashes should just be abstract strings satisfying certain uniqueness conditions.

**Comment by heftymouse** [comment]
My use case is definitely strange 😆 I came across this while trying to fix image links in my Astro website's RSS feed. Eventually, the approach I unfortunately settled on was trying to generate Rollup's asset filenames myself and fixing the `<img>` tags using rehype. This works fine once you realize the odd character set, but I was sent on a wild goose chase for quite a while trying to figure out why my hashes weren't matching.

**Comment by lukastaegert** [comment]
I see. Recreating the xxhash algorithm was apparently not a problem 😅

I think there is no problem changing that in a minor version. Before we do so: Do you also have an opinion on the correct order of characters in base36 and base64 😉?

https://github.com/rollup/rollup/blob/5d37496e50966deb1d9098b9e2dba3aa90341621/rust/xxhash/src/lib.rs#L4-L10

**Comment by heftymouse** [comment]
Seems fine to me :) Thank you!
