### ISSUE TITLE
Bundles should support explicit resource management

### ISSUE THREAD

**Issue by NotWoods** [rollup/rollup#5714]
### Feature Use Case

Avoid the need to wrap `bundle.generate` in a try-finally block by supporting the [Explicit Resource Management](https://github.com/tc39/proposal-explicit-resource-management) syntax with `using`:

```ts
await using bundle = await rollup(...);

await generateOutput(bundle);
// bundle.close is automatically called at the end of this block even if an error is thrown
```

### Feature Proposal

Add `Symbol.asyncDisposable` to `RollupBuild` so it works with the `async using` keyword.

See also: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management

**Comment by lukastaegert** [comment]
Good idea! PR welcome, or someone picks this up.
