### ISSUE TITLE
[@rollup/rollup-linux-arm64-musl@4.24.4] optional install error

### ISSUE THREAD

**Issue by Xtche** [rollup/rollup#5715]
### Rollup Version

4.24.4

### Operating System (or Browser)

window64

### Node Version (if applicable)

22

### Link To Reproduction

none

### Expected Behaviour

[@rollup/rollup-linux-arm64-musl@4.24.4] optional install error: Error: [vite@5.4.10 › rollup@4.24.4 › @rollup/rollup-linux-arm64-musl@4.24.4] Can't find package @rollup/rollup-linux-arm64-musl's version: 4.24.4
![image](https://github.com/user-attachments/assets/5b3199db-7b2a-4d83-965b-3d346850f6ca)

### Actual Behaviour

[@rollup/rollup-linux-arm64-musl@4.24.4] optional install error: Error: [vite@5.4.10 › rollup@4.24.4 › @rollup/rollup-linux-arm64-musl@4.24.4] Can't find package @rollup/rollup-linux-arm64-musl's version: 4.24.4
![image](https://github.com/user-attachments/assets/5b3199db-7b2a-4d83-965b-3d346850f6ca)

**Comment by lukastaegert** [comment]
Likely a caching issue with your package manager. `npm show @rollup/rollup-linux-arm64-musl versions` lists the version to exist.

**Comment by Xtche** [comment]
Nothing's changed, but it's working
