### ISSUE TITLE
In certain special cases, `[hash:22]` may not meet expectations

### ISSUE THREAD

**Issue by shulaoda** [rollup/rollup#5720]
Related to #5371

Due to the adoption of a new hash calculation method, the `hash` length is at most `21` in the following cases.

https://github.com/rollup/rollup/blob/b350d9ef1dac59d9358041d767661a23ecc47a26/rust/xxhash/src/lib.rs#L11-L13

```rust
#[test]
fn test() {
  assert_eq!(xxhash_base64_url(b"0000").len(), 21);
  assert_eq!(to_string(b"1111111111111111", 64, CHARACTERS_BASE64).unwrap().len(), 21);
}
```

**Comment by lukastaegert** [comment]
Good point, in the current logic, this may lead to misaligned source maps. We should probably change the limit either to 21 or pad to length 22.
