### ISSUE TITLE
Failed to build using version 4.27.0.

### ISSUE THREAD

**Issue by kiloc** [rollup/rollup#5734]
### Rollup Version

4.27.2

### Operating System (or Browser)

window/linux

### Node Version (if applicable)

v18

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-mgajrx?file=package.json

### Expected Behaviour

I use vite to build js code,  it's can't work.  i found the vite dependece rollup,  when i use rollup@4.26.0 can build success. but can't work on rollup@4.27.0.  Maybe there is some issue when import js worker.  

### Actual Behaviour

![image](https://github.com/user-attachments/assets/4dde778e-3259-4e46-a5ec-c1bbcc7a3e3d)

**Comment by lukastaegert** [comment]
Thanks! I noticed that you need to add `@rollup/plugin-node-resolve` to the reproduction as well as `monaco-editor`, but it is a legitimate bug.

**Comment by kiloc** [comment]
ok! thinks

**Comment by lukastaegert** [comment]
Can you verify that rollup@4.29.0-0 does not have this issue?
