### ISSUE TITLE
Why is `./` required for module paths?

### ISSUE THREAD

**Issue by maranomynet** [rollup/rollup#574]
OK, this may be a stupid question, but here goes:
As far as I can tell, the ES6 module syntax allows "bare" relative paths - so that

```js
import bar from 'foo';
```

...should be the equivalent of 

```js
import bar from './foo';
```

So, why does Rollup not allow this?
Why doesn't it attempt to resolve all non-prefixed paths as relative - before handing things over to plugins such as "node-resolve"?

**Comment by fskreuz** [comment]
import bar from 'foo';

As far as I know, unprefixed is used to indicate external dependencies. This would mean `bar` comes from a global `foo` but bundle just introduces the reference to `foo`, but doesn't include it in the bundle.

**Comment by maranomynet** [comment]
Is that according to the EcmaScript 2015 standard, or some custom Rollup/node-specific departure from the standard?

**Comment by bmeck** [comment]
@maranomynet The ES standard has no intention to ever set about including path resolution, it is only the syntax and semantics of modules, not the loader. This behavior is in both the [HTML](https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier) and [Node](https://nodejs.org/api/modules.html#modules_all_together)  resolution algorithms, `./` and `../` are so called "relative paths". Having a `/` is an "absolute path". Having neither is often called a "base path".

HTML currently does not allow base paths in their resolution algorithm, Node however does.

|Example|Type|Resolution Point|
|---|---|---|
|/foo.js|Absolute|"root" (base url in HTML, fs root in `node`)|
|./foo.js|Relative|"./" so directory of current file|
|../foo.js|Relative|"../" so parent directory of current file|
|foo.js|Base|`node_modules` viewable current package|

**Comment by maranomynet** [comment]
This was very informative. Thanks @bmeck!

**Comment by eventualbuddha** [comment]
I'm considering this answered, so I'm closing. Feel free to discuss further here if you like.
