### ISSUE TITLE
importAttributesKeyword doesnt work

### ISSUE THREAD

**Issue by titoBouzout** [rollup/rollup#5742]
### Rollup Version

4.27.2

### Operating System (or Browser)

windows

### Node Version (if applicable)

22

### Link To Reproduction

https://rollupjs.org/repl/?version=4.27.4&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnZlcnNpb24lN0QlMjBmcm9tJTIwJy4lMkZwYWNrYWdlMi5qc29uJyUyMHdpdGglMjAlN0J0eXBlJTNBJTVDJTIyanNvbiU1QyUyMiU3RCUyMCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyJTdCdmVyc2lvbiUzQSU1QyUyMjElNUMlMjIlN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIycGFja2FnZTIuanNvbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMmltcG9ydEF0dHJpYnV0ZXNLZXklMjIlM0ElMjJ3aXRoJTIyJTdEJTdEJTdE

### Expected Behaviour

The ability to import a json file

### Actual Behaviour

I get this error
```
You are using import attributes, without specifying the desired output syntax.
Please specify the "importAttributesKeyword" generator option, whose value can be one of:
 - "with"        : `import { a } from "b" with { type: "json" };`
 - "assert"      : `import { a } from "b" assert { type: "json" };`
 - "with-legacy" : `import { a } from "b" with type: "json";`

client/index.js

client/index.js (15:53): Unexpected token `:`. Expected identifier, string literal, numeric literal or [ for the computed key

13: render(() => <Layout />)*/
14:
15: export { version } from '../package.json' with { type: 'json' }
                                                         ^
```

There's something strange about that error, it tells about a `importAttributesKeyword` but that doesn't seem to exist, it should be `importAttributesKey`.  Anyway, I add `output.importAttributesKey = 'with'`  and the error doesn't go away, and still doesn't work. I am confused. 

It is supported to import like that or isn't?

**Comment by lukastaegert** [comment]
The error does not show in your reproduction, and I also did not see it before. My guess is that it is thrown by a plugin, maybe Babel?

**Comment by titoBouzout** [comment]
> The error does not show in your reproduction, and I also did not see it before. My guess is that it is thrown by a plugin, maybe Babel?

Thanks, that was it, adding the following to babel config solved it

````
{ generatorOpts: { "importAttributesKeyword": "with" } }
```
