### ISSUE TITLE
`conda-forge` build for 4.28.1 fails

### ISSUE THREAD

**Issue by MementoRC** [rollup/rollup#5758]
Hi, it would appear that this code makes the build on conda-forge fail:
```
const onwarn: WarningHandlerWithDefault = warning => {
	console.error(
		'Building Rollup produced warnings that need to be resolved. ' +
			'Please keep in mind that the browser build may never have external dependencies!'
	);

	throw Object.assign(new Error(), warning);
};
```
After adding a patch, the build completes. The question is whether this is the correct approach?

the conda version update build is under:
https://github.com/conda-forge/rollup-feedstock/pull/44#pullrequestreview-2486694354

**Comment by lukastaegert** [comment]
The warning is about a conflict with a module that has the same name as a builtin? Where does it come from? I do not think vanilla Rollup has this issue. Elevating warnings to errors in its own build has been a useful decision for Rollup so far.

**Comment by MementoRC** [comment]
The error was:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1102334&view=logs&j=ae18cb70-17c3-5a15-782b-9596d963d812&t=e865a0f7-73cb-587e-e7ab-2c56f005adfa&l=1037

Could you suggest a more practical way to resolve it? Or, is it acceptable to package `rollup` this way on conda-forge?

**Comment by lukastaegert** [comment]
The question is why there is something in your Rollup build that tries to import "events" in the first place, because there is nothing when I build Rollup from source. But it is probably fine to fix it this way.

**Comment by MementoRC** [comment]
It seems to originate from chokidar, unfortunately, my knowledge with node is very limited (i.e. nonexistent). It would be great if someone could help review/fix the conda build as a co-maintainer. For now, I should use the patch until I understand more about the issue. Thx
