### ISSUE TITLE
Do not wrap keys of objects in quotes when not necessary

### ISSUE THREAD

**Issue by floratmin** [rollup/rollup#5764]
### Feature Use Case

When I use characters which are allowed to use as variable names as keys rollup wraps them sometimes in unnecessary quotes.

```js
const ꁈꄼሕᣎᠳ勞 = {
    ꁈꄼሕᣎᠳ勞: 'test ',
    ฆ理ꃝꋹᕠ礼: 'bar'
};
```
this becomes:
```js
const r={"ꁈꄼሕᣎᠳ勞":"test ",ฆ理ꃝꋹᕠ礼:"bar"};
```

### Feature Proposal

Omitting unnecessary quotes allows for smaller bundle sizes.

**Comment by TrickyPi** [comment]
I wasn't able to reproduce this issue in the REPL https://rollupjs.org/repl/?version=4.28.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwJUVBJTgxJTg4JUVBJTg0JUJDJUUxJTg4JTk1JUUxJUEzJThFJUUxJUEwJUIzJUVGJUE0JUFGJTIwJTNEJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCVFQSU4MSU4OCVFQSU4NCVCQyVFMSU4OCU5NSVFMSVBMyU4RSVFMSVBMCVCMyVFRiVBNCVBRiUzQSUyMCd0ZXN0JTIwJyUyQyU1Q24lMjAlMjAlMjAlMjAlRTAlQjglODYlRUYlQTclQTQlRUElODMlOUQlRUElOEIlQjklRTElOTUlQTAlRUYlQTglOTglM0ElMjAnYmFyJyU1Q24lN0QlM0IlNUNuY29uc29sZS5sb2coJUVBJTgxJTg4JUVBJTg0JUJDJUUxJTg4JTk1JUUxJUEzJThFJUUxJUEwJUIzJUVGJUE0JUFGKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlN0QlN0Q=. Could you provide a minimal reproduction?

**Comment by floratmin** [comment]
Oh, sorry. This belongs to vite, not rollup.
