### ISSUE TITLE
Import module that uses `module.export` in rollup.config.js

### ISSUE THREAD

**Issue by rpominov** [rollup/rollup#578]
You can see what I'm trying to do here https://github.com/rpominov/lobot/blob/70c82ef058264bd5178194739a95e0189c7b8eab/bin/rollup.config.js

When I try to run rollup with this config, I get:

```
[Error: Module /Users/anon/projects/my/basic-signals/node_modules/lobot/bin/projectName.js does not export pascalCase (imported by /Users/anon/projects/my/basic-signals/node_modules/lobot/bin/rollup.config.js)]
```

Is this possible to import es5 file from the config? Or maybe it's should just work and it's me doing something wrong?

**Comment by rpominov** [comment]
Simply using `require()` for CommonJS modules works fine.

**Comment by Rich-Harris** [comment]
You should also be able to do this...

```js
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import nodeResolve from 'rollup-plugin-node-resolve'
import projectName from './projectName'

export default {
  entry: 'src/index.js',
  dest: `umd/${projectName.camelCase}.js`,
  plugins: [
    nodeResolve({jsnext: true}),
    commonjs(),
    babel(),
  ],
  format: 'umd',
  moduleName: projectName.pascalCase,
}
```

Lil' bit hacky but it transpiles to the same `require()` call.

**Comment by rpominov** [comment]
So it works if I don't use destruction? This explains why it worked at first, but the just stopped (I didn't noticed that I added destruction).

Anyway, good to know. Thanks!

**Comment by EliasHasle** [comment]
I had the same problem. In my case I had to apply Babel first, and commonjs afterwards. Otherwise I got a syntax error on cutting-edge ES features.
