### ISSUE TITLE
Question: Why do I see Module does not export Bloodhound (UMD module)?

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#579]
I'm having some troubles understanding why I see:

```bash
Error: Module /Users/kross/projects/af_core/node_modules/corejs-typeahead/dist/bloodhound.js does not export Bloodhound (imported by /Users/kross/projects/af_core/app/assets/javascripts/global_search_autocomplete.js)
```

As far as I can tell from the build, this is a UMD module, and I should be able to import without a problem using the `rollup-plugin-commonjs`:
https://github.com/corejavascript/typeahead.js/blob/212fe89300e4760f15df4dec4e447d1dee21e965/dist/bloodhound.js

Rollup options:
```javascript
let options = {
    entry: '/Users/kross/projects/af_core/app/assets/javascripts/index.js',
    sourceMap: true,
    format: 'cjs',
    plugins: [
        nodeResolve({
            jsnext: true,
            main: true,
            builtins: false,
            browser: true,
            extensions: ['.js', '.json']
        }),
        commonjs({
            include: '/Users/kross/projects/af_core/node_modules/**',
            extensions: [
                '.js'
            ],
            namedExports: {
                '/Users/kross/projects/af_core/node_modules/ua-parser-js/src/ua-parser.js': [
                    'UAParser'
                ]
            }
        }),
        babel({
            babelrc: false,
            presets: [
                'es2015-rollup'
            ]
        })
    ],
    dest: 'public/assets/debug/af_core.cjs-bundled.js',
    moduleName: 'application'
}
```

I had previously worked around this with a named import in my engine project, but since I'm using `npm link` for a dependency, it appears the named export doesn't match because the path differs.  But why do I need to name this export anyway?  It's a UMD module with a name, correct?

What am I missing?

**Comment by TrySound** [comment]
@rosskevin Hi!. Show `global_search_autocomplete.js`

**Comment by rosskevin** [comment]
Sorry!  I missed that.  Heres a snippet:

```javascript
import Base from './lib/base'
import {Bloodhound}  from 'corejs-typeahead/dist/bloodhound'
import 'corejs-typeahead/dist/typeahead.jquery'

const Default = {}

const GlobalSearchAutocomplete = class extends Base {
  constructor(config = {}) {
    super($.extend(true, {}, Default, config))
  }
  
  // ...
}

export default GlobalSearchAutocomplete
```

**Comment by rosskevin** [comment]
I just ran this with no complaints:

```javascript
import {default as Bloodhound}  from 'corejs-typeahead/dist/bloodhound'
```

Not sure it works, but it resolves.  Am I on the right track?

**Comment by TrySound** [comment]
@rosskevin `import {Bloodhound}` means check property of exports, not exports itself. 
`import { default as something } from 'path';` means the same as `import something from 'path';`
And as you can see
```js
module.exports = factory(require("jquery"));
```
it's default value and exports itself.

**Comment by rosskevin** [comment]
Thanks for the explanation, it definitely helps. 

I'm deep in a conversion of all our modules to ES2015 and went back to this, only to find out the standard `import Bloodhound from 'corejs-typeahead/dist/bloodhound'` now works.  I assume given the amount of refactoring I'm doing that I had some other quirk.  I'll follow up if I get everything cleaned up and this reappears.

**Comment by TrySound** [comment]
@rosskevin  Here's great guide about modules
http://www.2ality.com/2014/09/es6-modules-final.html
