### ISSUE TITLE
Add --internals CLI option to specify which npm modules to bundle

### ISSUE THREAD

**Issue by bfred-it** [rollup/rollup#581]
I looked at the wiki and at some issues but I couldn't find a way to specify which external modules to bundle with the cli. 

Could this option be added otherwise? It would be particularly useful for IIFE packages with nano dependencies like the fundamental [noop3](https://github.com/sindresorhus/noop3)

```sh
rollup --internal noop3 --format iife --name pandas src/main.js > dist/main.js
```

**Comment by TrySound** [comment]
@bfred-it You can use `globals` option or global variables for this cases.

**Comment by bfred-it** [comment]
I don't think that's it:

```sh
rollup --globals noop3:NAME --format iife --name pandas src/main.js > dist/main.js
```

Produces:

```js
var pandas = (function (noop3) {
	'use strict';
	noop3 = 'default' in noop3 ? noop3['default'] : noop3;
	noop3();
}(NAME));
```

But I'd like:

```js
var pandas = (function () {
	'use strict';
	function noop3 () {};
	noop3();
}());
```

**Comment by TrySound** [comment]
@bfred-it It's the problem of commonjs incompatibility with es2015 modules. Just es realizations for that. Or do you mean rollup-plugin-node-resolve? It works fine, but you can't define plugins in cli without rollup config file. 
https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file

**Comment by Rich-Harris** [comment]
Going to close this as it doesn't look like there's anything to do – using a config file is the right approach if you need to use a plugin like rollup-plugin-node-resolve.

**Comment by bfred-it** [comment]
Sorry I didn't reply sooner.
That worked! I wish [--plugin](https://github.com/rollup/rollup/issues/226) was added without config but an extra file is not a big deal. Thanks! :)
