### ISSUE TITLE
Module name with dash in UMD format produces invalid output

### ISSUE THREAD

**Issue by philer** [rollup/rollup#584]
It's probably not a big issue but the following config produces bad output:

``` js
export default config = {
  moduleName: "my-module-with-dashes",
  format:     "umd",
  // ...
}
```

Results in this line in the bundle's UMD head:

``` JS
// ...
  (factory((global.my-module-with-dashes = global.my-module-with-dashes || {})));
// ...
```

You should probably check the module name and use bracket syntax if necessary.

**Comment by zackthehuman** [comment]
Seems like a similar issue to #582.

**Comment by Victorystick** [comment]
I think you're mixing up `moduleId` with `moduleName`. The former is an AMD id and the latter a JS identifier.

```js
// AMD head
define( 'module-id', ... );

// UMD head
  (factory((global.moduleName = global.moduleName || {})));
// ...
```

You should try
```js
export default {
  moduleId: "my-module-with-dashes",
  moduleName: "myModuleWithoutDashes",
  format: "umd",
  // ...
}
```

But, if what you really want is dashes in your module Identifier, then yes that should be fixed.

**Comment by philer** [comment]
So what exactly is the difference between `moduleId` and `moduleName`? Or rather, why are they not the same thing? [The docs](https://github.com/rollup/rollup/wiki/JavaScript-API#moduleid) aren't very elaborate on the subject, they just tell me that the two things exist and UMD apparently uses both. I haven't used AMD before so I'm probably missing something.

Either way it'd probably be a good idea to allow generic moduleNames, regardless of whether or not it's a good idea to actually use them.

**Comment by Victorystick** [comment]
The difference is that `moduleId` is a _string used by the AMD format_ and `moduleName` is a _generic JavaScript identifier_.

For instance, `'1337.js'` could be a `moduleId`, but since it cannot be used as an identifier we'll need a different `moduleName`; like: `leetJS`.

```js
define([ '1337.js' ], function ( leetJS ) {
  // use leetJS...
});
```

> [...] probably be a good idea to allow generic moduleNames, [...]

@philer Agreed.

**Comment by Rich-Harris** [comment]
Is there really a case for allowing dashes in global names? I'd be in favour of throwing an error if an invalid identifier (or member expression, which probably makes things slightly trickier) is used, since it's almost certainly unintentional, and it's an opportunity to direct people towards the relevant documentation
