### ISSUE TITLE
Conflicts using destructuring assignment; "Cannot overwrite the same content twice"

### ISSUE THREAD

**Issue by zackthehuman** [rollup/rollup#585]
I often import a module and then use destructuring assignment to grab the things I need. This is causing a problem if I happen to grab the same thing in two different modules. For example:

```javascript
// index.js
import Immutable from 'immutable';
import foo from './foo';

const {
  List
} = Immutable;
```

```javascript
// foo.js
import Immutable from 'immutable';

const {
  List
} = Immutable;

new List();
```

When I run this through rollup I get the following error:

> Cannot overwrite the same content twice: 'List'

The version of rollup being used is 0.21.3. I am using rollup via `broccoli-rollup`, but I can see that this error is generated from within rollup itself and not the broccoli plugin.

**Comment by Victorystick** [comment]
Can you upgrade to a more recent version of Rollup; like 0.25.x?

**Comment by zackthehuman** [comment]
Upgrading to 0.25.x worked. The changes were reflected in `broccoli-rollup` here: https://github.com/chadhietala/broccoli-rollup/commit/1c5cc9b5fc0df1a5b3b85093d41a314be0170f35

I no longer encounter the error described in this issue. Thanks!
