### ISSUE TITLE
Plugins leak state between bundles

### ISSUE THREAD

**Issue by fatfisz** [rollup/rollup#589]
I use `grunt-rollup` with `rollup-plugin-babel` and I have a few different bundles declared. `grunt-rollup` just passes plugins to the `rollup` function, so each bundle inherits used helpers from the previous ones. For example if the first bundle uses classes and the second one doesn't, both bundles will receive the class helpers. In this simple case reordering the bundles can help, but there are some unsolvable cases too.

The gist of it is that the plugins leak state between bundles when using the JS API and it may be confusing. That's why I think that this is a problem with `rollup` and not `grunt-rollup`.

I suggest these solutions:

1. Provide a new hook for plugins that explicitly deals with resetting the state. I don't think that any of the existing hooks is an appropriate place for this.
2. Allow different means of plugin configuration: an array consisting of a plugin function and a configuration object. `rollup` would handle this by initializing the plugin by itself.
3. Or maybe at least some info for the users about this gotcha?

I don't know what's the best course of action here, I just hope no one else gets confused like I did :wink:

**Comment by Victorystick** [comment]
Since most, if not all, plugins are designed to be used once per bundle it's logical error to reuse the plugins for multiple bundles.

One course of action would be to pass `grunt-rollup` a function that when called returns a fresh Rollup config, instead of a config object itself. That way, we could prevent leakage of state.

```js
rollupConfig: () => ({ ... })
```

**Comment by fatfisz** [comment]
Now how did I come under an impression that instantiating plugins each time was a bad idea... You are right, this should be the way to go. I will take this to the people responsible for `grunt-rollup`.

I will close this issue because the problem is not with `rollup` after all, sorry for confusion.
