### ISSUE TITLE
Duplication caused from importing the same module with different casing

### ISSUE THREAD

**Issue by nhunzaker** [rollup/rollup#590]
**TL:DR:** What do you think about warning when code imports the same module with different casing?

When a module is mistakenly imported with different casing, on file systems that don't care, duplication occurs when importing the module. I've made a test case here:

https://gist.github.com/nhunzaker/2a36fa377a41f6d6b054196af299d909

In this case, both `green` and `orange` require `yellow`, however one requires it as `Yellow` (with a capital "Y"). Under the hood, Rollup appends `$1` to the second yellow, like so:

``` javascript
var blue = "blue"

var yellow = "yellow"

var green = [ yellow, blue ]

var red = "red"

var yellow$1 = "yellow"

var orange = [ yellow$1, red ]

export { green, orange };
```

What about warning these cases?

**Comment by Rich-Harris** [comment]
My feeling is that Rollup should fail altogether if incorrect casing is used. Implemented in #630

**Comment by Rich-Harris** [comment]
Closing, as Rollup now insists on the correct casing

**Comment by nhunzaker** [comment]
👍. Awesome. Even better!
