### ISSUE TITLE
Unused imports from external modules should be stripped from import statements in ES bundles

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#595]
The following code...

``` js
// main.js
import { unused } from 'external';

function alsoUnused () {
  unused();
}
```

...could result in the following ES bundle (i.e. it imports the external module in case it has side-effects, but doesn't need `unused` specifically)...

``` js
import 'external';
```

...but instead we get this...

``` js
import { unused } from 'external';
```

...which causes [confusion](http://stackoverflow.com/questions/36417779/rollup-including-unneeded-dependancies-and-missing-a-function-in-output).

**Comment by pakastin** [comment]
Would be great if Rollup could also notify about unused imports, so you'd know to clean up source files..
