### ISSUE TITLE
Browser page script referencing ES2015 class from a rollup-built module

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#596]
First, if there is a better place to ask this question, please let me know.

If my `iife` rollup file exports an ES2015 `Form` class, how do I reference it from a page script? i.e. `new Form()`?  

The bulk of the code is in the rollup package, and just a small script to trigger it is in the page script.  I'm not limited to `iife`, it can be any of the packages `umd`, `amd` or `cjs`, I'm just looking for the best way to do this.

Options:

```javascript
{
    entry: '/Users/kross/projects/af_core/spec/dummy/app/assets/javascripts/application.js',
    sourceMap: true,
    format: 'iife',
    plugins: [
        commonjs({
            include: '/Users/kross/projects/af_core/spec/dummy/node_modules/**',
            extensions: [
                '.js'
            ],
            namedExports: {}
        }),
        nodeResolve({
            jsnext: true,
            main: true,
            builtins: false,
            browser: true,
            extensions: [
                '.js',
                '.json'
            ]
        }),
        babel({
            babelrc: false,
            presets: [
                'es2015-rollup'
            ]
        }),
    ],

    dest: 'public/assets/debug/application.js',
    moduleName: 'application'
}
```

`application.js`:

```javascript
export {default as Form} from './lib/form/form'
```

Since the page script run in the browser is non-ES2015, I'm struggling to find the right way to reference the generated class from babel.

**Comment by rosskevin** [comment]
I should mention that I could use this in the browser from a `cjs` or `umd`, just not sure what the best route for browser use.

**Comment by rosskevin** [comment]
I'm currently left to think I have to use browserify instead of rollup so that my page script can access my object.  This would be a shame because I've put a lot of time and energy into rollup, and all of my libraries have been converted and work great.  I'd rather not have to use browserify only for the last jump to the browser when rollup has worked so well so far.

I'd appreciate any pointers.

**Comment by Conduitry** [comment]
http://rollupjs.org/#{%22options%22%3A{%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22Hello%22%2C%22globals%22%3A{}}%2C%22modules%22%3A[{%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20default%20class%20Hello%20{}%22}]}

If you export your class from a module, and output as iife, and set the moduleName option, you can control what global variable your class export is assigned to. Is this what you're looking for?

**Comment by Victorystick** [comment]
As you can see in [this example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22application%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20class%20A%20%7B%7D%22%7D%5D%7D), Rollup is defining the `application` global with an `A` property.

In your case, `application.Form` should do the trick.

**Comment by rosskevin** [comment]
Thanks @Victorystick - that led me in the right direction.

I have a rails engine with a dummy application entry point, but most of the code is in another file.  While I did the equivalent `export` from the engine, the _main_ entry point didn't export anything, it only imported.

So sticking with `iife` as you mentioned, my main entry point now does `export * from 'af_core/app/assets/javascripts/index'` and `application.A` is now available.

So ultimately, it was a failure on my part to `export` from the the _main_ entry point - which makes complete sense.

Thank you!
