### ISSUE TITLE
Tree shaking re-exported modules not exclude unused symbols

### ISSUE THREAD

**Issue by bjornharrtell** [rollup/rollup#597]
I'm trying to use re-exporting to essentially fold multiple modules in a bundle with namespaces.

Given the following modules:

Module `a`
```js
export const a = 1
```
Module `b`
```js
export const b = 1
```
Module `c`
```js
import * as a from './a'
import * as b from './b'
export { a, b }
```

And if I rollup the `c` module I get:
```js
const a = 1
var a$1 = Object.freeze({
	a: a
});
const b = 1
var b$1 = Object.freeze({
	b: b
});
export { a$1 as a, b$1 as b };
```

If I then use the above bundled module as follows:

```js
import { a } from './bundle'
console.log(a)
```

Rolling up the above will result in a new bundle that contains the unused module `b`.

I'm not sure what is possible in this case but should not rollup be able to at least remove `b` from the final bundle?

**Comment by Victorystick** [comment]
@bjornharrtell If you bundle the `c` module into `bundle` first, and then attempt to bundle some other module which uses the first bundle you're in for trouble.

When bundling `c`, Rollup doesn't know which parts will be used, so it must be pessimistic and include it all. When you try to bundle the second chunk of code the `Object.freeze` statements will _use_ the `a` and `b` variables marking them as _required for the bundle_.

If you want Rollup to tree-shake `b` away, you need to bundle everything in one go.

**Comment by bjornharrtell** [comment]
Thanks for the thorough explanation.

**Comment by Swatinem** [comment]
That’s why I advocate against third party libraries referencing a pre-bundled version via `jsnext:main`. This was discussed before, although I haven’t found where exactly…

**Comment by bjornharrtell** [comment]
Yes I see that now, took a fair bit of effort to understand though. At the same time, compiling an application plus every referenced library from source might become too slow for large projects. Then I guess tools can compile only changed modules hot reload. The tool chain of JavaScript is soon as large and cumbersome as C++. ;)
