### ISSUE TITLE
Cannot find module '../package'

### ISSUE THREAD

**Issue by gigavinyl** [rollup/rollup#602]
When running this config file:
```js
import babel from 'rollup-plugin-babel';
import json from 'rollup-plugin-json';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'server/server.js',
  format: 'umd',
  dest: 'bundelIndex.js',
  plugins: [
    babel({
      exclude: 'node_modules/**',
      babelrc: false,
      presets: ['react', 'es2015-rollup', 'stage-0'],
      plugins: ['transform-decorators-legacy'],
    }),
    json(),
    nodeResolve({ jsnext: true, main: true, skip: ['knex'] }),
    commonjs(),
  ],
};
```
I get the error: `Cannot find module '../package' from '/Users/gigavinyl/Projects/ceres/node_modules/fsevents/node_modules/node-pre-gyp/lib'`. Am I misunderstanding one of the node-related plugins?
Update: Removing "skip: ['knex']" produces the error `Cannot find module 'sqlite3' from '/Users/gigavinyl/Projects/ceres/node_modules/knex/lib/dialects/sqlite3'` which is odd because knex is set up for postgres.

**Comment by TrySound** [comment]
@gigavinyl You can't skip extension. Just specify `../package.json`.

**Comment by TrySound** [comment]
@gigavinyl And I don't think you should traverse all your modules on server side. Just put those packages in `external` rollup option.

**Comment by TrySound** [comment]
Maybe you even don't need node-resolve in this case.

**Comment by gigavinyl** [comment]
@TrySound Adding the troublesome modules as external seems to have resolved the isssue 😄 . Thanks!
