### ISSUE TITLE
Option to apply scope hoisting to require calls?

### ISSUE THREAD

**Issue by ashaffer** [rollup/rollup#604]
I'd like to be able to apply scope hoisting to static (i.e. string constant) calls to node's require that occur at the top of a module's scope, as 99.99% of all require calls do. Is this possible with rollup? It seems like it should be.

**Comment by Victorystick** [comment]
I assume the `commonjs` and `node-resolve` plugins found [here](https://github.com/rollup/rollup/wiki/Plugins)  don't do the trick. Have you given [esnext](https://github.com/esnext/esnext) a look?

**Comment by Rich-Harris** [comment]
Any code transformation can be implemented as a plugin – sounds like this is maybe a special case for [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) to handle?

I'll close this though as it isn't something that would be implemented in Rollup itself.
