### ISSUE TITLE
dies silently

### ISSUE THREAD

**Issue by himalayafan** [rollup/rollup#606]
Hi. I experienced a lot of times that Rollup dies silently without any error messages. E.g. if I bundle and have a wrong spelling so it can't import correct files. It refuse to bundle without warning or errors.
There are other identical use cases where this happened too.

Couldn't it be an idea to give a message back to end-dev about what is wrong? It would save hours of bug tracking if you have a large code base.

**Comment by eventualbuddha** [comment]
Can you provide an example? Ideally a minimal one?

**Comment by Rich-Harris** [comment]
Closing this until there's some information we can work with
