### ISSUE TITLE
What's the best way to override 'main' for a package that hasn't got a jsnext:main field?

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup#608]
I'm using react-redux and redux together. redux has a `jsnext:main` field, but react-redux does not, resulting in problems (because when react-redux's babel-built code tries to load redux using commonjs semantics, it fails because redux doesn't export a default). Or something.

I think  this issue is about this: https://github.com/reactjs/react-redux/issues/243

In the meantime, I need a way to hack it... What would be the best way for me to tell rollup to behave as if a given package (react-redux) had a `jsnext:main` field?

I'm guessing this is something I could configure in the commonjs or node-resolve plugin, but I'm not sure which or how...

**Comment by Rich-Harris** [comment]
With a combination of `load` and `resolveId` hooks you can make Rollup load whatever code you want:

```js
rollup.rollup({
  entry: 'src/index.js',
  plugins: [
    {
      resolveId ( importee, importer ) {
        if ( importee === 'react-redux' ) {
          return 'lol';
        }
        // if nothing gets returned, we fall through to other plugins
        // and eventually the default
      },
      load ( code, id ) {
        if ( id === 'lol' ) return '// code goes here';
      }
    },
    nodeResolve(...) // will now get bypassed for react-redux
  ]
}).then(...);
```

(Obviously the convention is for plugins to exist as functions, but all they do is return a POJO so you can do the same thing directly.)
