### ISSUE TITLE
Shorthand properties

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#61]
Unable to check right now, but I'd strongly expect [this Esperanto issue](https://github.com/esperantojs/esperanto/issues/183) to apply to Rollup as well:

```js
import foo from 'foo';

export default {
  // `foo` might be rewritten `_foo`, which means the
  // shorthand property no longer works
  foo 
}
```

**Comment by Victorystick** [comment]
This ought to apply to all object shorthands, right? Not just those with exports. We'll just have to expand the shorthands, if we rename the variables.
