### ISSUE TITLE
How to prevent from handling files with same extension by rest transformer.

### ISSUE THREAD

**Issue by differui** [rollup/rollup#612]
I wrote a transformer to create scoped template and stylesheet(`rollup-plugin-scoped`).

eg.

**btn.scss**

```scss
.btn {
    color: red;
}
```

**btn.tpl**

```
<button class="btn">Foo</button>
```

The transformer will yield:

```css
/* 'abcdef' is a hash sum */
.btn[abcdef] {
    color: red;
}
```

```html
<button class="btn" abcdef="">Foo</button>
```

I append `"scoped!"` before importee id to figure out scoped asset and unscoped asset.`rollup-plugin-scoped` handle scoped stuff and `rollup-plugin-sass`(which I wrote for compile sass code) handle unscoped stuff.

```js
const style form 'scoped!btn.scss'; // handle by rollup-plugin-scoped
const style2 from 'btn2.scss'; // handle by rollup-plugin-sass
```

```js
var rollup = require('rollup');
var scoped = require('rollup-plugin-scoped');
var sass = require('rollup-plugin-sass');

rollup.rollup({
    entry: 'app.js',
    plugins: [
        scoped(), // match *.scss
        sass() // match *.scss too
    ]
})
``` 

Because `rollup-plugin-scoped` and `rollup-plugin-sass` both matched `*.scss`.The result of rest one override the former's.Is there any way prevent from rest transform handing the result which output by former transformer?

**Comment by Victorystick** [comment]
Can't you just tell the `sass` plugin to exclude any `scoped!` module ids?

```js
sass({
  exclude: 'scoped!*'
})
```

**Comment by differui** [comment]
@Victorystick Thanks for replying.

`scoped!btn.scss` is not a valid importee id.So `rollup-plugin-scoped` will resolve id before tranform it.

***rollup-plugin-scoped*

```
return {
        resolveId: function (importee, importer) {
            var importeeId;

            if (!/^scoped!/.test(importee)) {
                return null;
            }

            importeeId = importee.substr(7);
            importeeId = path.resolve(path.parse(importer).dir, importeeId);

            return importeeId;
        },
};
```

So the reset `rollup-plugin-sass` can not get the original importee id anymore.

**Comment by Victorystick** [comment]
@differui You don't happen to place the scoped files in a separate directory from the unscoped ones? You could exclude based on that.

**Comment by differui** [comment]
@Victorystick I got it.I can place `rollup-plugin-sass` before `rollup-plugin-scoped` and use tell `sass` to exclude scoped files.

**Comment by differui** [comment]
> @Victorystick I got it.I can place rollup-plugin-sass before rollup-plugin-scoped and use tell sass to exclude scoped files.

Fail to do this.Because `resolveId` is public for every plugin that mached same importee and run before filter.`rollup-plugin-sass` gets the resolved id when it try to filter importee.
