### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by jonataswalker** [rollup/rollup#613]
I'm running a very basic setup (https://github.com/jonataswalker/es6-sample-project) &mdash; 4 simple files &mdash; and it takes up to 5s to finish. Is this what I should expect?

```
$ time make build-js
real    0m5.109s
user    0m5.020s
sys     0m0.320s
```

**Comment by Rich-Harris** [comment]
I'd be curious to see what happens if you use [rollup-plugin-buble](https://www.npmjs.com/package/rollup-plugin-buble) instead of Babel?

```js
import json from 'rollup-plugin-json';
import buble from 'rollup-plugin-buble';

var pkg = require('./package.json');

export default {
  format: 'umd',
  entry: pkg.rollup.entry,
  dest: pkg.rollup.dest,
  moduleName: pkg.rollup.moduleName,
  plugins: [
    json({
      exclude: [ 'node_modules/**' ]
    }),
    buble({
      exclude: ['node_modules/**', '*.json']
    })
  ]
}
```

Babel can be a little slow to start up, especially if you're using npm2.

**Comment by jonataswalker** [comment]
Wow, come on, what's this about? Using `rollup-plugin-buble`:

```
real    0m1.551s
user    0m1.628s
sys     0m0.044s
```

**Comment by Rich-Harris** [comment]
Yep, that's what I expected. [Bublé](https://buble.surge.sh) is a bit nimbler than Babel.

**Comment by jonataswalker** [comment]
@Rich-Harris that's awesome, changing right now.

**Comment by jsux** [comment]
Also if you run you're scripts in a long lived process you'll see huge performance improvements for building with babel if you find you need the additional features babel offers. I have a gulp daemon process that I use to build in and when I do usually rollup becomes the bottleneck not babel. Babel has a slow cold start time, but once its warm with the JIT kicking in it will mostly fly - probably not as fast as bublé but then is has severe limitations at present which are intentionally part of its design.

Problem is with build scripts kicking of a new node instance for every call (I notice you're using a make script) is that you're disposing all the hard work the JITs just done for you.

**Comment by jonataswalker** [comment]
@jsux thanks for your comments but I'm not sure how to avoid what you raised. I'm pretty happy with my swiss-army-knife Makefile and would like to see your suggestion.
