### ISSUE TITLE
Specifying enclosing bundle in IIFE via the CLI

### ISSUE THREAD

**Issue by backspaces** [rollup/rollup#615]
(This is a documentation question, not an issue)

How do I make the output of rollup be wrapped in an IIFE? Maybe I have to use a config file?

~/src/b6[560]: rollup src/main.js 
function sqrt(x) {
  return Math.sqrt(x);
}

function square(x) {
  return x * x;
}
function diag(x, y) {
  return sqrt(square(x) + square(y));
}

console.log(square(11)); // 121
console.log(diag(4, 3)); // 5

**Comment by Rich-Harris** [comment]
`rollup src/main.js -f iife` (the `-f` (or `--format`) options are `iife`, `amd`, `cjs`, `umd` or `es6`). If you export anything you'll also need to specify a `--name` (or `-n`) so it can create a global variable.

**Comment by backspaces** [comment]
So if I have an e6 set of modules, and I want the bundle rollup creates of them, using -f iife and -n myBundle will bundle the import/exports into a single file with an iife wrapper exporting "myBundle"?

My confusion was --format including es6 and iife both. Just tried it and it worked like a charm, YaY!!

Thanks .. this is going to seriously change how my team approaches es6 and modules.
