### ISSUE TITLE
rollup with babel-polyfill - TypeError: undefined is not an object! (test case included)

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#616]
With the polyfill removed, in phantomjs/Firefox I get a readable error: `Symbol is not defined` - which makes sense.  I've seen the Symbol error before and I've been able to use `import 'babel-polyfill/dist/polyfill'`.  But now in another project using the same build chain, I get this obscure `TypeError: undefined is not an object!` with my rollup generated file.  

Only by deleting this `import` do I get what I expect - which is the Symbol error.  So while that error is an annoyance, it is trivial. Now to the issue:

If I include the polyfill in the html directly as you can see in the [testrunner.html](https://github.com/alienfast/picker.js/blob/master/test/testrunner.html#L20), all tests work (`gulp js` using mocha).  The real problem with this is I want my `iife` with the polyfill that works cross browser, I don't want to include it as a separate script for all users, and I'm not sure why it is tree shaking (speculation) when [another project](https://github.com/FezVrasta/bootstrap-material-design/tree/v4-dev) I have doesn't do the same.

The [tests here are still very basic](https://github.com/alienfast/picker.js/blob/master/test/index.js) - just getting started - so it is a good test case.

https://github.com/alienfast/picker.js
```bash
clone  https://github.com/alienfast/picker.js.git

# Install the Gulp command line tools, gulp-cli, with 
npm install -g gulpjs/gulp-cli#4.0

cd picker.js
npm install

gulp js
```

Here is the rollup config used:

```javascript
let options = {
    entry: '/Users/kross/projects/picker.js/test/index.js',
    sourceMap: true,
    format: 'iife',
    plugins: [ // (count: 3)
        commonjs({
            include: 'node_modules/**',
            extensions: [
                '.js'
            ]
        }),
        nodeResolve({
            jsnext: true,
            main: true,
            builtins: false,
            browser: true,
            extensions: [
                '.js',
                '.json'
            ]
        }),
        babel({
            babelrc: false,
            presets: [
                'es2015-rollup'
            ]
        }),
    ],

    dest: 'dist/picker-tests.js.iife.js',
    moduleName: 'pickerTests',
}
```

Versions:
```
rollup@0.25.8
rollup-plugin-babel@2.4.0
rollup-plugin-commonjs@2.2.1
rollup-plugin-node-resolve@1.5.0
```

I have tried each of the following imports in `js/index.js` with the same results:
```javascript
//import 'babel-polyfill/dist/polyfill'
//import 'babel-polyfill'
//import 'core-js/es6/symbol'

// fail to rollup
//export * from 'babel-polyfill'
```

Is there an option I have used to cause the `babel-polyfill` to be manipulated?  Can I include it in a way without tree shaking?

**Comment by bsouthga** [comment]
my solution to this was to import the file directly as...

```javascript
import '../../../node_modules/babel-polyfill/dist/polyfill';
```

Feels pretty hacky, but rollup can now grab the file itself, and include it in the output.

**Comment by TrySound** [comment]
@bsouthga 
Why do you resolve node_modules by hands?
```js
import 'babel-polyfill/dist/polyfill';
```

**Comment by TrySound** [comment]
Oh, I see. It's weird. Maybe something wrong with resolver.

**Comment by Rich-Harris** [comment]
Just as an experiment, could you try this?

```js
let options = {
    ...
    plugins: [ // (count: 3)
        // ...
        babel({
            babelrc: false,
            presets: [ 'es2015-rollup' ],
            exclude: [ 'node_modules/babel-polyfill/** ] // or [ 'node_modules/**' ]
        }),
    ],
    ...
}
```

My hypothesis is that Babel is transforming its own polyfill, thereby summoning Zalgo.

**Comment by rosskevin** [comment]
@Rich-Harris - that seems totally plausible and makes sense to me.  It didn't work, so I tried a few different exclusions just to be sure: 

```
node_modules/babel-polyfill/**
./node_modules/babel-polyfill/**
node_modules/**
```

Same issue:

```javascript
TypeError: undefined is not an object!

   in exports at file:///Users/kross/projects/picker.js/dist/picker.js.iife.js:276
   in defineProperty at file:///Users/kross/projects/picker.js/dist/picker.js.iife.js:7529
   at file:///Users/kross/projects/picker.js/dist/picker.js.iife.js:308
   at file:///Users/kross/projects/picker.js/dist/picker.js.iife.js:7688
   in __commonjs at file:///Users/kross/projects/picker.js/dist/picker.js.iife.js:10
   at file:///Users/kross/projects/picker.js/dist/picker.js.iife.js:7451
```

**Comment by rosskevin** [comment]
So, this has popped into the other project that was working `bootstrap-material-design` ([repo](https://github.com/FezVrasta/bootstrap-material-design/tree/v4-dev) [starter template](http://rosskevin.github.io/bootstrap-material-design/examples/starter-template/)).  I keep the dependencies updated, so I'm guessing at some point rollup started mangling babel-polyfill.

We are nearing our first public release so [this](https://github.com/FezVrasta/bootstrap-material-design/issues/1003) is bad timing.

What do you need from me to better take a look?

**Comment by rosskevin** [comment]
Interesting, I added an external ref to babel-polyfill (without changing the messed up/bundled one) and it does see it as a second one:
http://codepen.io/rosskevin/pen/dMrMMm

![v4_bmd_template_-_external_polyfill_and_gulpfile_babel_js_-_bootstrap-material-design_-____projects_bootstrap-material-design_](https://cloud.githubusercontent.com/assets/136564/15154522/9096cf26-16a3-11e6-9508-be4aa98b4e57.png)

So it's not mangled too much to at least see that there is one registered.   Not sure this is helpful information...

**Comment by rosskevin** [comment]
Writing a repo/test-case now...

**Comment by rosskevin** [comment]
Ok, here's the test case: https://github.com/rosskevin/test-rollup-616-babel-polyfill

[Open this demo](http://rosskevin.github.io/test-rollup-616-babel-polyfill/) in Chrome (succeeds) vs Firefox (fails)

**Comment by rosskevin** [comment]
Is there a chance someone could look at the included test case? This used to work but now is not, it is a confirmed bug.

**Comment by Rich-Harris** [comment]
Sorry for the long delay. With the latest version of all the various plugins (I found and fixed a couple of bugs via your test case – thanks), and a rollup.config.js file, this *appears* to build and work correctly:

```js
// rollup.config.js
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
    entry: 'js/index.js',
    sourceMap: true,
    format: 'iife',
	plugins: [ // (count: 3)
        commonjs({
            include: 'node_modules/**',
            extensions: [
                '.js'
            ]
        }),
        nodeResolve({
            jsnext: true,
            main: true,
            // builtins: false,
            browser: true,
            extensions: [
                '.js',
                '.json'
            ]
        }),
        babel({
            babelrc: false,
            presets: [
                'es2015-rollup'
            ]
        }),
    ],

    moduleName: 'test',
    dest: 'site/dist/test.iife.js'
};
```

I just added a `"build": "rollup -c"` task to the `"scripts"` section.

It's still not working for me with Gulp, because the various dependencies aren't up to date. **I recommend against using Gulp** for precisely this reason – it adds extra layers of indirection and complexity, prevents you from controlling which versions of plugins are used (certainly if you use `gulp-pipeline`), makes everything harder to debug (it took me a long time to untangle stuff to understand what was going on – library authors like me much prefer getting straightforward test cases without having to understand all that extra gubbins!) and ultimately can only make the build slower.

I'll close this issue as I don't think there are any further changes required on our end, but let us know if you continue to have problems with it.

**Comment by rosskevin** [comment]
Thanks for your work on this @Rich-Harris.  I updated the test case specifically with what you have mentioned in your comment, though I receive the same exact error in Firefox.

Here is the branch with the pure test case:
https://github.com/rosskevin/test-rollup-616-babel-polyfill/tree/rich-changes

Will you reopen take a look?

**Comment by rosskevin** [comment]
I don't want this to fall off the radar and I'm anxious since this hasn't been reopened and I've put a lot of time into it. Should I open a new issue and reference the updated test case?
