### ISSUE TITLE
New hook for transforming ids

### ISSUE THREAD

**Issue by fatfisz** [rollup/rollup#621]
Now that #591 is merged, the internal paths marked as external are referenced by path fragments. It would be nice to allow transforming them (e.g. to remove extensions, "/index.js" bits, etc.).

Currently doing it is possible, but requires a very roundabout way: first `resolveId` would have to return an appropriate id (stripped of extensions, etc.), then `load` would have to handle it by more or less resolving the id again. Also `resolveId` would have to double check if the wanted file is `./x.js` or `./x/index.js`. I tinkered around with `rollup-plugin-node-resolve` to see what could be done, and it didn't turn out nice.

Is this sensible? Maybe there exists some other simple way to achieve that?

**Comment by fatfisz** [comment]
I had an afterthought: this could probably be achieved by a separate plugin that would do the stripping magic only for the internal-external deps. Will test that idea and post results.

**Comment by fatfisz** [comment]
Actually, because the results of `resolveId` are not passed from plugin to plugin, I'd have to first exclude the files from any plugins which are currently resolving ids (e.g. `rollup-plugin-node-resolve`) and then use another plugin for what I want to do. I'm going with this for now, but it is a tiny bit inconvenient, and a separate hook for transforming ids would make it easier.

I could do this if the idea is ok.

**Comment by fatfisz** [comment]
Ok, here's what I've come up with:

1. Save external deps in an array.
  ```js
  const external = [
    path.resolve('./lib/bag/index.js'),
    path.resolve('./lib/database/index.js'),
    path.resolve('./lib/config.js'),
  ];
  ```

2. Map this array using a function of your choice that will do the stripping.
  ```js
  const externalStripped = external.map(strip);
  ```

3. Attach `externalStripped` to the list of external files.

4. Use a custom resolver that will do the stripping for the chosen files (the `external` array is needed here).
  ```js
  {
    resolveId(importee, importer) {
      if (!importer) {
        return;
      }

      return new Promise((resolve, reject) => {
        nodeResolve(importee, { basedir: path.dirname(importer) }, (err, resolved) => {
          if (err) {
            return reject(err);
          }

          if (external.indexOf(resolved) === -1) {
            return resolve();
          }

          resolve(strip(resolved));
        });
      });
    },
  }
  ```

So I made this work somehow, but:
* The files passed to the `external` option have to be transformed beforehand.
* The transforming function needs to be available both in the plugin and in the config.
* The same files passed twice in two different ways.
* Most filenames will have to be resolved more than once.

If there was a hook for transforming ids, I could just pop in a plugin and be done.

**Comment by fatfisz** [comment]
If the idea is passable then I could do it.

**Comment by Rich-Harris** [comment]
Can you explain in a bit more detail what the use for this would be? I'm not sure I totally understand where this is necessary, though I assume I'm just missing something.

I did wonder more generally about transforming IDs, while we're here – e.g. if you had a compile-to-css plugin, subsequent CSS plugins such as rollup-plugin-postcss would ignore it. Perhaps the `transform` hook (which is currently expected to return a `{ code, map }` object – if a string is returned it's turned into that form) could return a `{ code, map, id }` object if appropriate.

**Comment by fatfisz** [comment]
I actually reached a conclusion that what I wanted to do wasn't that good, but here it is.

I have a directory containing a few files, let's say it's `./database/`. I want this to be a sub-module of sorts. So all of the files are either the interface (`index.js`) or utils used internally behind the interface. I want to avoid rolling everything up into `./database/index.js` or keeping the directory at all, because after packing it's rather redundant. So I'd like the target to be `./database.js` instead.

Other parts of the code are referencing this sub-module using the path `./database`. This means I could have both `./database/index.js` and `./database.js` recognized by the npm path resolver. There is a problem, however: because `./database` is set as an external dep (this is a requirement), at the resolving time it is saved as `./database/index.js`. So in the end I can't have `./database.js` target in a straightforward way.

Since then *everything* has changed and I don't need this anymore, but I'd happily create the patch anyway. Extending the existing `transform` hook is a nice idea. This id would be then used only for rendering?

**Comment by fatfisz** [comment]
As this is not an issue for me anymore, and it is quite old, I'm closing this. I wouldn't be able to invest any time into working on this currently anyway.
