### ISSUE TITLE
Can't include immutable.js in a bundle: "Module does not export Record"

### ISSUE THREAD

**Issue by alendit** [rollup/rollup#624]
Hi,

when I try to include `immutable.js` into my bundle, rollup complains about it not exporting any variables. I've created [an example project](https://github.com/alendit/rollup-immutable-issue) to demonstrate this issue.

I use the newest `rollup` (0.26) and `immutable.js`.

**Comment by alendit** [comment]
Missed the commonjs plugin, closing.

**Comment by sonicd300** [comment]
Can you please post your code, having the same issue, still googling it.

**Comment by Victorystick** [comment]
@sonicd300 Any success using the [`namedExports` option](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports)?
