### ISSUE TITLE
Invalid code "class exports.Foo" emitted for TypeScript's decorators

### ISSUE THREAD

**Issue by IgorMinar** [rollup/rollup#626]
Given this code with decorators:
```
@Injectable()
class Testability() {}
```

Typescript transpiles this into a more verbose version of this es6 code:
```
export let Testability = class Testability {};
Testability = __decorate([
    Injectable(),
], Testability);

function __decorate(decorators, target) {
  return target;
}

function Injectable() {}
```

If code like this is processed by rollup, rollup will emit invalid code that looks like:

```
(function (exports) {
  'use strict';

  exports.Testability = class exports.Testability {};
  exports.Testability = __decorate([
      Injectable(),
  ], exports.Testability);

  function __decorate(decorators, target) {
    return target;
  }

  function Injectable() {}

}((this.rollbug = this.rollbug || {})));
//# sourceMappingURL=rollbug.umd.js.map
```

Note the **`class exports.Testability`** part which is syntactically invalid es6 code.

I'd expect the class to be emitted as `exports.Testability = class Testability{ ...`

rollup config:
```
export default {
  entry: 'rollbug.js',
  dest: 'rollbug.umd.js',
  sourceMap: true,
  format: 'iife',
  moduleName: 'rollbug'
}
```

rollup version:  0.26.0

**Comment by Rich-Harris** [comment]
[Simpler repro](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20let%20Foo%20%3D%20class%20Foo%20%7B%7D%5CnFoo%20%3D%20lol(%20Foo%20)%3B%22%7D%5D%7D): 

```js
export let Foo = class Foo {}
Foo = lol( Foo );
```

Results in:

```js
'use strict';

exports.Foo = class exports.Foo {}
exports.Foo = lol( exports.Foo );
```

**Comment by Rich-Harris** [comment]
Thanks @IgorMinar – have opened #628 to address this
