### ISSUE TITLE
function invokation with side effects gets removed

### ISSUE THREAD

**Issue by thgreasi** [rollup/rollup#635]
Hi to all!
I'm currently using rollup v0.26.1 and had an issue with a function invocation that got removed, while it was modifying the prototype of an other variable. This might be related to #476 but I wasn't sure whether I should re-open it and post my findings there.
- [my original code](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20function%20extendPrototype%28localforage%29%20%7B%5Cn%20%20%20%20try%20%7B%5Cn%20%20%20%20%20%20%20%20var%20localforagePrototype%20%3D%20Object.getPrototypeOf%28localforage%29%3B%5Cn%20%20%20%20%20%20%20%20if%20%28localforagePrototype%20%26%26%20!localforagePrototype.newObservable%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20localforagePrototype.newObservable%20%3D%20localforageObservable%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20return%20true%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%20catch%20%28e%29%20%7B%20%2F*%20*%2F%20%7D%5Cn%20%20%20%20return%20false%3B%5Cn%7D%5Cn%5CnextendPrototype%28localforage%29%3B%22%7D%5D%7D)
- [a simplified version](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20function%20extendPrototype%28localforage%29%20%7B%5Cn%20%20%20%20try%20%7B%5Cn%20%20%20%20%20%20var%20localforagePrototype%20%3D%20Object.getPrototypeOf%28localforage%29%3B%5Cn%20%20%20%20%20%20localforagePrototype.newObservable%20%3D%20localforageObservable%3B%5Cn%20%20%20%20%7D%20catch%20%28e%29%20%7B%20%2F*%20*%2F%20%7D%5Cn%20%20%20%20return%20false%3B%5Cn%7D%5Cn%5CnextendPrototype%28localforage%29%3B%22%7D%5D%7D)
- [a working (not equivalent) variation](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20function%20extendPrototype%28localforage%29%20%7B%5Cn%20%20%20%20try%20%7B%5Cn%20%20%20%20%20%20Object.getPrototypeOf%28localforage%29.newObservable%20%3D%20localforageObservable%3B%5Cn%20%20%20%20%7D%20catch%20%28e%29%20%7B%20%2F*%20*%2F%20%7D%5Cn%20%20%20%20return%20false%3B%5Cn%7D%5Cn%5CnextendPrototype%28localforage%29%3B%22%7D%5D%7D)

An other way to make it work was to [export the result of the method](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20function%20extendPrototype%28localforage%29%20%7B%5Cn%20%20%20%20try%20%7B%5Cn%20%20%20%20%20%20%20%20var%20localforagePrototype%20%3D%20Object.getPrototypeOf%28localforage%29%3B%5Cn%20%20%20%20%20%20%20%20if%20%28localforagePrototype%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20localforagePrototype.newObservable%20%3D%20localforageObservable%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20return%20true%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%20catch%20%28e%29%20%7B%20%2F*%20*%2F%20%7D%5Cn%20%20%20%20return%20false%3B%5Cn%7D%5Cn%5Cnexport%20var%20extendPrototypeResult%20%3D%20extendPrototype%28localforage%29%3B%22%7D%5D%7D)

To summarize:

``` js
export function extendPrototype(localforage) {
    try {
        var localforagePrototype = Object.getPrototypeOf(localforage);
        if (localforagePrototype && !localforagePrototype.newObservable) {
            localforagePrototype.newObservable = localforageObservable;
            return true;
        }
    } catch (e) { /* */ }
    return false;
}

extendPrototype(localforage);
```

``` js
export function extendPrototype(localforage) {
    try {
        var localforagePrototype = Object.getPrototypeOf(localforage);
        localforagePrototype.newObservable = localforageObservable;
    } catch (e) { /* */ }
    return false;
}

extendPrototype(localforage);// also gets ommited
```

The only working variations I found are:

``` js
export function extendPrototype(localforage) {
    try {
        Object.getPrototypeOf(localforage).newObservable = localforageObservable;
    } catch (e) { /* */ }
    return false;
}

extendPrototype(localforage);
```

and

``` js
export function extendPrototype(localforage) {
    try {
        var localforagePrototype = Object.getPrototypeOf(localforage);
        if (localforagePrototype) {
            localforagePrototype.newObservable = localforageObservable;
            return true;
        }
    } catch (e) { /* */ }
    return false;
}

export var extendPrototypeResult = extendPrototype(localforage);
```

PS: Thanks in advance for this and :+1: for the great boilerplate example repo! It made adopting rollup really easy.

**Comment by Rich-Harris** [comment]
Apologies for the long lack of response. I'm having difficulty seeing the bug – it's possible that it was fixed in a more recent version? On 0.26.6 the [original example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20function%20extendPrototype(localforage)%20%7B%5Cn%20%20%20%20try%20%7B%5Cn%20%20%20%20%20%20%20%20var%20localforagePrototype%20%3D%20Object.getPrototypeOf(localforage)%3B%5Cn%20%20%20%20%20%20%20%20if%20(localforagePrototype%20%26%26%20!localforagePrototype.newObservable)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20localforagePrototype.newObservable%20%3D%20localforageObservable%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20return%20true%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%20catch%20(e)%20%7B%20%2F*%20*%2F%20%7D%5Cn%20%20%20%20return%20false%3B%5Cn%7D%5Cn%5CnextendPrototype(localforage)%3B%22%7D%5D%7D) appears to work correctly.

**Comment by thgreasi** [comment]
Hi there!
Using the example that you linked, I think that the `extendPrototype(localforage);` invocation is still being removed and the resulting code only defined and exports the method.
Is this the expected behaviour?

**Comment by Rich-Harris** [comment]
D'oh, you're totally right – whoops! Marking this as a bug

**Comment by Rich-Harris** [comment]
[Whittled the test case down a bit](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22function%20mutate(obj)%20%7B%5Cn%20%20%20%20var%20obj2%20%3D%20obj%3B%5Cn%20%20%20%20obj2.mutated%20%3D%20true%3B%5Cn%7D%5Cn%5Cnvar%20obj%20%3D%20%7B%7D%3B%5Cnmutate(%20obj%20)%3B%20%2F%2F%20should%20be%20included%5Cn%5Cnexport%20%7B%20obj%20%7D%3B%22%7D%5D%7D) – I think this is the same issue as #669

**Comment by Rich-Harris** [comment]
Looks like this was fixed, closing
