### ISSUE TITLE
Preprocess modules before running rollup in gulp

### ISSUE THREAD

**Issue by mindrones** [rollup/rollup#636]
I [read](https://github.com/rollup/rollup/wiki/Build-tools#gulp-usage) that using gulp/stream wrappers around rollup (like [`gulp-rollup`](https://github.com/mcasimir/gulp-rollup)) is discouraged, but how to preprocess modules and then use the result as input for rollup without saving temporary files? (I suspect the answer is writing a rollup plugin)

**`browserify` example**

Assuming the main file, `src/index.js`, contains code like:
```js
// @if PRODUCTION=false
var REALTIME_DATA = false
// @endif
// @if PRODUCTION=true
var REALTIME_DATA = true
// @endif
...
```
I can [gulp-preprocess](https://github.com/jas/gulp-preprocess) the bundle like this:
```js
// gulpfile.js, run with `gulp -p`

const gulp = require('gulp');
const browserify = require('browserify');
const source = require('vinyl-source-stream');
const buffer = require('vinyl-buffer');
const preprocess = require('gulp-preprocess');
const gulpif = require('gulp-if');
const uglify = require('gulp-uglify');

cliOptions = require('minimist')(process.argv.slice(2), {
    boolean: ['p'],
    default: {p: false}
});

gulp.task('default', function() {
    return browserify('./src/index.js')
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(buffer())
    .pipe(preprocess({
        context: {PRODUCTION: cliOptions.p}
    }))
    .pipe(gulp.dest('./build/dev'))
    .pipe(gulpif(cliOptions.p, uglify()))
    .pipe(gulp.dest('./build/dist'))
});
```
In this case all is fine because `browserify` is not supposed to change my source code and processing happens on a single file, the bundle.

**The problem with `rollup`**

Let's examine the rollup bundle if we use such `gulp-preprocess` directives:
```js
// gulpfile.js, run with `gulp -p`
...
gulp.task('default', function() {
    return rollup({
        entry: './src/index.js',
    }).then(function(bundle) {
        var code = bundle.generate({
            format: 'umd'
        }).code
        console.log(code)
    });
})
```
the conditional blocks get modified as `rollup` gets rid of the (apparently) unneeded `var REALTIME_DATA = false`:
```js
// build/dev/index.js
// @endif
// @if PRODUCTION=true
var REALTIME_DATA = true
// @endif
...
```
I then tried with the The [rollup-plugin-replace plugin](https://github.com/rollup/rollup-plugin-replace):

```js
// src/index.js
var REALTIME_DATA = __IS_PRODUCTION_BUILD__
```

```js
// gulpfile.js, run with `gulp -p`
...
gulp.task('default', function() {
    return rollup({
        entry: './src/index.js',
        plugins: [
            replace({
                values: {
                    __IS_PRODUCTION_BUILD__: cliOptions.p
                }
            }),
        ]
    }).then(function(bundle) {
        ...
    });
})
...
```
which works well 

```js
// build/dev/index.js
var REALTIME_DATA = true
...
```

but this only replaces strings, it can't conditionally eliminate entire blocks of code in the original code like `gulp-preprocess` can do.

Is this possible somehow without writing a rollup plugin? 

Thanks!

**Comment by Victorystick** [comment]
@mindrones The best course of action would probably be to write a `preprocess` plugin. It's actually pretty easy.

Rollup can and does eliminate unused conditional branches; see [this example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22amd%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20let%20foo%3B%5Cn%5Cnif%20(%20false%20)%20%7B%5Cn%20%20foo%20%3D%201%3B%5Cn%7D%20else%20%7B%5Cn%20%20foo%20%3D%202%3B%5Cn%7D%22%7D%5D%7D) (a minifier will remove the unused, empty if-block). So the `replace` plugin can be used to eliminate code that should not be executed.

Feel free to re-open this issue if it doesn't solve your problem.

**Comment by mindrones** [comment]
@Victorystick OK, time permitting I'll have a try at it: if successful I'll report back, thanks!

**Comment by yairEO** [comment]
what is I want to do the simplest preprocess? like replacing strings in the code. should I write a simple plugin just for that? seems like an overkill.

All i want to do it doing something like this `replace(/\[SERVERPATH]/g, config.serverPath)` before `return bundle.write({...`

**Comment by Rich-Harris** [comment]
@yairEO see https://github.com/rollup/rollup-plugin-replace

**Comment by yairEO** [comment]
Can't skip the whole `npm install` and requiring the plugin and so on, and just write the plugin as an inline function? 
Thanks Rich!

**Comment by Rich-Harris** [comment]
Using the plugin will be a lot easier if you want sourcemap support, but if you want a naive version then I guess you could do

```js
entry: 'src/main.js',
dest: 'bundle.js',
plugins: [{
  transform ( code, id ) {
    return code.replace(/\[SERVERPATH]/g, config.serverPath);
  }
}],
// other options
```
