### ISSUE TITLE
Namespace and default exports of the same import treated as the same binding

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#637]
See example - http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20fs%20from%20'fs'%3B%5Cnimport%20'.%2Fmaths.js'%3B%5Cnfs.p()%3B%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22import%20*%20as%20fs%20from%20'fs'%3B%5Cnfs.asdf()%3B%22%7D%5D%7D

In this case, the namespace and the default import are both being treated as the same binding, instead of having two separate bindings in this case.

**Comment by Rich-Harris** [comment]
thanks – fixed in 0.26.7
