### ISSUE TITLE
Strategy for momentjs locale inside/outside iife

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#641]
https://github.com/alienfast/picker.js/issues/13#issuecomment-216639514

So I've just put together a new datepicker for multiple different renderings called [picker.js](http://alienfast.github.io/picker.js/)

Inside the iife, I import/use `moment`.  The exposed configuration for `datepicker` allows for a `lang` to be passed in, and I'm expecting that given the desired language file, it will configure moment for use.  Here's a codepen demonstrated expected use with `lang: 'pl'`:

http://codepen.io/rosskevin/pen/PNxMoB?editors=0010

The issue here is that while everything is included as expected, the picker.js iife rollup doesn't expose `moment`, so the [additional lang file](https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/locale/pl.js) cannot find `moment` to define a new locale.

My goal is to have everything included (not all locales) so it is as easy to use as possible, but I suppose moment could be supplied from outside my module.

What is the strategy here?
1. Require it to be supplied externally (not desirable)?
2. Expose it in a way that is compatible with the external locale file (how?)? Export moment, set it as `var moment = window.picker.moment` then add the `<script>` tag for the additional locale?
3. Other?

Thanks for any thoughts/pointers.

**Comment by rosskevin** [comment]
I implemented strategy \#2 here: http://alienfast.github.io/picker.js/bmd4-locale.html

It seems a bit messy, but works.  I would prefer to do this the "best" way, I just need to know a better way to do it.

**Comment by Rich-Harris** [comment]
There isn't really a good way to handle things like plugins until everyone everywhere is using standard modules (I say this from bitter experience). I suspect the best route, if you don't want to extract `moment` from the bundle and keep it as an external dependency, would be to have a line in your [entry module](https://github.com/alienfast/picker.js/blob/master/js/index.js) that creates the global, like so:

```diff
- export {default as moment} from 'moment'
+ import moment from 'moment';
+
+ window.moment = moment;
+ export { moment };
```

That way you could lose the intermediate `<script>` tag:

```html
<script src="dist/picker.iife.js"></script>
<script src="https://cdn.rawgit.com/moment/moment/2.13.0/locale/pl.js"></script>
```

**Comment by rosskevin** [comment]
@Rich-Harris that works well, thank you.  

So `window.moment = moment` attaches to the global window, that makes sense.

I'm curious about `export {moment}`, since it isn't named, is it creating  _the_  global?

[rollup demo](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%22moment%22%3A%22moment%22%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20moment%20from%20'moment'%3B%5Cnwindow.moment%20%3D%20moment%3B%5Cnexport%20%7B%20moment%20%7D%3B%22%7D%2C%7B%22name%22%3A%22moment.js%22%2C%22code%22%3A%22export%20default%20function%20(%20x%20)%20%7B%5Cn%5Ctreturn%20x%20*%20x%3B%5Cn%7D%5Cn%22%7D%5D%7D)

**Comment by rosskevin** [comment]
Nevermind, the demo site even explains it...!

**Comment by Rich-Harris** [comment]
Yep, if you're creating an IIFE and `moment` is external, it's assumed to be `window.moment` – it's only if it's bundled (either a relative path, or you're using [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) that you'd need to assign it.
