### ISSUE TITLE
Babel plugin causes Rollup to fail silently with ES2015 class keyword

### ISSUE THREAD

**Issue by credwards27** [rollup/rollup#642]
References: rollup/rollup-plugin-babel#52

I'm not sure if this belongs here or at [rollup/rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel).

Rollup fails silently when using the **rollup-plugin-babel** plugin if any of the imported
(and used) modules contain the ES2015 `class` keyword.

My gulpfile.js:

```js
const gulp = require("gulp"),
    sourcemaps = require("gulp-sourcemaps"),
    rename = require("gulp-rename"),
    rollup = require("gulp-rollup"),
    babel = require("gulp-babel"),
    concat = require("gulp-concat"),
    uglify = require("gulp-uglify"),
    gUtil = require("gulp-util"),
    
    rollupBabel = require("rollup-plugin-babel"),
    rollupIncludePaths = require("rollup-plugin-includepaths");

/* Common error handler.
*/
function handleError() {
    gUtil.log.apply(this, arguments);
    this.emit("end");
}

gulp.task("js", function() {
    console.log("Compiling scripts...");
    
    return gulp.src("app/js/app.js")
        .pipe(rollup({
            entry: "app/js/app.js",
            format: "iife",
            sourceMap: true,
            plugins: [
                rollupIncludePaths({
                    paths: [ "app/js" ]
                }),
                rollupBabel({
                    presets: [ "es2015-rollup" ],
                    plugins: [
                        ["babel-root-import", {
                            rootPathSuffix: "app/js"
                        }]
                    ]
                })
            ]
        }))
        .on("error", handleError)
        .pipe(rename("app.min.js"))
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("dist/js"));
});
```

Running `gulp js` will complete successfully as long as none of the modules
included by `app/js/app.js` contain an ES2015 `class` keyword.

The task will fail silently, however, if any module contains `class`, such as:

### app/js/app.js

```js
import MyClass from "myClass";

var myClass = new MyClass();
```

### app/js/myClass.js

```js
export default class MyClass {
    constructor() {
        console.log("this is my class");
    }
}
```

With the above code, `gulp js` starts, prints "Compiling scripts...", then exits
without a "Finished 'js' after X ms" message. No pipes after the `rollup` pipe
run.

With the same babel options run in the `gulp-babel` module directly instead of
the rollup module, the task succeeds (using `"es2015"` instead of
`"es2015-rollup"`). So that rules out babel and babel-plugin-transform-es2015 as
the culprit.

### Environment Info

- Node version: 4.4.3
- NPM version: 3.3.8

#### Dev Dependencies:

```json
"devDependencies": {
    "babel-plugin-external-helpers": "^6.5.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-es2015-rollup": "^1.1.1",
    "babel-root-import": "^3.2.2",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-concat": "^2.6.0",
    "gulp-plumber": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-rollup": "^1.8.0",
    "gulp-sourcemaps": "^2.0.0-alpha",
    "gulp-uglify": "^1.5.3",
    "gulp-util": "^3.0.7",
    "rollup-plugin-babel": "^2.4.0",
    "rollup-plugin-includepaths": "^0.1.2"
  }
```

**Comment by credwards27** [comment]
rollup/rollup-plugin-babel#52

**Comment by Rich-Harris** [comment]
There's a lot of moving parts here – are you able to whittle it down to a more minimal example (*preferably* without Gulp, since it seems unlikely to be a factor). Here's a repo with the same code and a similar config, and it appears to be working fine: https://github.com/Rich-Harris/rollup-642. Thanks

**Comment by credwards27** [comment]
Thanks for the sample project, I was able to narrow it down to a `Bad Sourcemap` error being thrown, which was fixed in #619. The **rollup-plugin-babel** plugin uses `rollup@0.25.8`, before the fix was merged, so it should just be a matter of updating the dependencies in that project.

Thanks again, this is solved in this thread as far as I'm concerned.

**Comment by kazzkiq** [comment]
@credwards27 I'm hitting a similar error. What exactly you did to fix it? Can you please provide your `gulpfile.js`?

My `gulpfile.js` is as follows:

```js
'use strict';

const gulp = require('gulp');
const rollup = require('gulp-rollup');
const rename = require('gulp-rename');
const babel = require('rollup-plugin-babel');
const sourcemaps = require('gulp-sourcemaps');

gulp.task('compile:es6', () => {
   return gulp.src(`src/Main.js`)
          .pipe(rollup({
              plugins: [
                  babel({
                      exclude: 'node_modules/**',
                  })
              ]
          }))
          .pipe(rename('bundle.js'))
          .pipe(gulp.dest('dist/'));
});
```

It runs the `compile:es6` task without any errors firing, but when you look at the bundle, there is no Babel transpilation (classes remain classes, etc).

**Comment by credwards27** [comment]
@kazzkiq That sounds like a different issue, mine wasn't even generating any output files. The gulpfile at the beginning of this issue is essentially what I was using, but the issue was that I was using `gulp-rollup~1.8.0`, which used an outdated version of Rollup. To start, make sure you are using `gulp-rollup~1.9.0`, which has up-to-date dependencies (`rollup@0.26.0`).

For your issue though, it looks like you need a preset for Babel.

Install `babel-preset-es2015-rollup`, and use it with:

```js
.pipe(rollup({
    plugins: [
        babel({
            exclude: 'node_modules/**',
            presets: [ 'es2015-rollup' ]
        })
    ]
}))
```

`babel-preset-es2015-rollup` doesn't need to be `require`'d in the gulpfile itself, Babel will just find it. Check out the [docs](https://babeljs.io/docs/usage/options/) for more Babel information, the object passed into babel() is exactly the same as using Babel directly without Rollup.

You also might check out [rollup-stream](https://www.npmjs.com/package/rollup-stream), which works like `gulp-rollup` but isn't blacklisted on NPM. It's setup is a little different, the readme does a good job explaining it. That project seems to be a bit more on top of keeping up with Rollup releases, and ultimately I switched over to it when I isolated the problem I was having.

Hope this helps.

**Comment by kazzkiq** [comment]
Thanks, @credwards27!

I had installed `babel-preset-es2015` instead of `babel-preset-es2015-rollup`. Simply running `npm install babel-preset-es2015-rollup` did the trick for me.

**Comment by credwards27** [comment]
Awesome, glad you got it working!
