### ISSUE TITLE
Run Node with Rollup module resolution

### ISSUE THREAD

**Issue by steadicat** [rollup/rollup#643]
Is there a way to run Node using Rollup to handle ES6 module imports? Similar to what [`babel-node`](https://babeljs.io/docs/usage/cli/#babel-node) does?

Node 6 supports most of ES6 natively, except for modules. Rollup feels like the perfect fit for providing that support. Especially for quick non-production scripts. Babel feels overkill.

I'd like to avoid an explicit precompilation/bundling step if possible.

**Comment by Rich-Harris** [comment]
Not really, that would be a different tool – though I kind of like the idea of a lean package that rewrites `import` statements on the fly to the CommonJS equivalent and disregards everything else. I maintain a library called [tippex](https://github.com/rich-harris/tippex) which ought to be able to do so fairly reliably...

**Comment by Rich-Harris** [comment]
I got curious and made [es-module-loader](https://gitlab.com/Rich-Harris/es-module-loader):

```bash
npm install -g es-module-loader
esml-node some-es-module.js
```

YMMV!

**Comment by Rich-Harris** [comment]
In case anyone else discovers this issue and has similar needs, @benjamn may have what you're looking for: https://github.com/benjamn/reify
