### ISSUE TITLE
Any doc about the format option?

### ISSUE THREAD

**Issue by lili21** [rollup/rollup#647]
What value dose this option accept? 

`cjs` , `es6`,  and ?

**Comment by Rich-Harris** [comment]
The docs are [here](https://github.com/rollup/rollup/wiki/JavaScript-API#format) – you can use `amd`, `cjs`, `es6` (though we'll eventually rename that to `es`), `iife` or `umd`. Visit [rollupjs.org](http://rollupjs.org/) to try each of them out
