### ISSUE TITLE
export default should use const/let, not var.

### ISSUE THREAD

**Issue by zbraniecki** [rollup/rollup#653]
Currently, when exporting a default object, it assigns it using `var` which is unnecessary.

Example:
```
export default {
  foo: 1
};
```

`rollup ./test.js`

```
var test = {
  foo: 1
};
```

Instead, it should use `const`.

**Comment by eventualbuddha** [comment]
This should be opt-in, if such and option existed. Rollup is most commonly used as the final step in bundling JavaScript libraries, so using `const` would render the output dependent on ES2015 features.

**Comment by zbraniecki** [comment]
agree. I think we're at the point where we see projects that are targeting es6-compatible targets and rollup is used as a module bundler. I'd like to see this feature mostly for those scenarios so that using rollup doesn't mean regressing to es2015.

**Comment by NicolasParada** [comment]
Agree. Now I'm using:
```js
const myModule = {
    foo: 'bar'
}

export default myModule
```

**Comment by Rich-Harris** [comment]
Have raised #684

**Comment by Rich-Harris** [comment]
As of 0.26.6, you can use `preferConst: true` to use `const` instead of `var` in these situations

**Comment by zbraniecki** [comment]
that works great! Thank you :)
