### ISSUE TITLE
Support multiple configurations in a single rollup.config.js

### ISSUE THREAD

**Issue by tkissing** [rollup/rollup#655]
With the current way config files work, creating different bundles from a single code base involves creating a lot of config files with a lot of duplicated configuration in them. I can somehow work around the duplication by importing a base config and overriding properties as needed, but I still end up with all these files and `import base from './rollup.base.js';` at the top of each.

It would be much nicer if I could put all my configurations into a single file, e.g. `targets:  [ {entry: 'src/index.js', format: 'amd', dest: 'dist/amd.js'}, ...]`

**Comment by eventualbuddha** [comment]
I agree. There's also the issue of duplicating the work that this would solve.

**Comment by eventualbuddha** [comment]
Here's my proposed API:

```js
// rollup.config.js
export default {
  entry: 'src/index.js',
  plugins: […],
  targets: [
    {
      format: 'umd',
      moduleName: 'thing',
      dest: 'dist/thing.js'
    },
    {
      format: 'es6',
      dest: 'dist/thing.mjs'
    }
  ]
};
```

This does not allow different plugins, entry, or any of the "input" options, so it may not work for you @tkissing. This would meet my needs, though. Perhaps we could allow all the options in the targets, but if you specified only differing output then rollup would only have to build the bundle once as an optimization?

**Comment by Rich-Harris** [comment]
👍  I like that proposal, and agree that it makes sense to limit the target options to those you'd use with `bundle.write(options)` (see [here](https://github.com/rollup/rollup/wiki/JavaScript-API#bundlewrite-options-) – includes all the `bundle.generate` options [here](https://github.com/rollup/rollup/wiki/JavaScript-API#bundlegenerate-options-))

**Comment by eventualbuddha** [comment]
@Rich-Harris I can look into this, but I'm not sure how to handle the tests. At the moment I'm thinking I'd add the tests in the `cli` folder and allow an `_expected` folder instead of `_expected.js`, and the targets would have `dest` entries like `_expected/cjs.js` or something. Sound reasonable, or would you do a different approach?

**Comment by tkissing** [comment]
That would work for me 👍

**Comment by Rich-Harris** [comment]
@eventualbuddha that sounds like a good approach to me, yep
