### ISSUE TITLE
Non-exported members included in top-level scope of bundle

### ISSUE THREAD

**Issue by ty1824** [rollup/rollup#656]
I've tried to do my due diligence to see if this has been reported before, but I've been unable to find anything.

When writing a module, I include utility functions/let statements that can be used by that module (and only that module) that are not exported. When a bundle is created, all of these are visible in the resulting scope. I would expect them to only be visible to the module where they are defined.

```
// test.js
let test = 5;
export function testFunction() { return test; }
}
```

```
// main.js
import { testFunction } from './test.js';
console.log( testFunction() );
```

Result:
```
let test = 5;
function testFunction() { return test; }

console.log( testFunction() );
```

I would think that `test` should not be available in the scope where testFunction is imported. Instead should only be visible to `testFunction`. I'm curious if this behavior was intended, or if it is less of a concern due to the intended uses of Rollup. Or maybe I am misunderstanding the module spec? :)

Possible valid result:
```
let testFunction = {
  let test = 5;
  function testFunction() { return test; }
  return testFunction;
}
console.log(testFunction());
```

Possible valid result for multiple exports:
```
let { testFunction1, testFunction2 } = {
  let test = 5;
  function testFunction1() { return test; }
  function testFunction2() { return test * 2; }
  return { testFunction1, testFunction2 };
}
console.log(testFunction1());
console.log(testFunction2());
```

**Comment by fskreuz** [comment]
[It won't actually matter](http://bit.ly/1WEGDeN). Rollup just rolls up everything into one level and "namespaces" like-named variables:

```js
// main.js
import { testFunction } from './test.js';
import { anotherTestFunction } from './another-test.js';
console.log( testFunction() );
console.log( anotherTestFunction() );

// test.js
let test = 5;
export function testFunction() { return test; }

//another-test.js
let test = 5;
export function anotherTestFunction() { return test; }

// result
'use strict';

let test = 5;
function testFunction() { return test; }

let test$1 = 5;
function anotherTestFunction() { return test$1; }

console.log( testFunction() );
console.log( anotherTestFunction() );
```

Besides, your suggestions fundamentally change how the function works. It changes the scope of the variable from outside to the inside. Also, Rollup was designed to compile with everything in the top level so that ES6 module bindings work as expected without overly complicated helper functions and constructs.

**Comment by Victorystick** [comment]
@ty1824 The behavior is correct and by design, just as @fskreuz says. Rollup ensures that non-exported names are not available outside of the bundle.

**Comment by ty1824** [comment]
The way I noticed it was via dev console. Once a bundle is loaded into a page, it is possible to access those "private" members via global scope despite them not being exported.

I understand if it's by design, however -- it definitely would add additional cruft to bundles.

**Comment by Victorystick** [comment]
@ty1824 I think you've forgotten to specify a module format. Rollup will generate ES modules by default. Attempting to run an ES module _ like a script_ in a browser may give the impression of private variables being public, but actually it's a logical error.

If you want to execute a bundle in a current browser, please use the IIFE format.
