### ISSUE TITLE
How to do unit testing with rollup+buble?

### ISSUE THREAD

**Issue by josdejong** [rollup/rollup#657]
I just heard about buble and I'm really excited about the combination of rollup and buble! It's so lightweight and easy to use compared with for example webpack+babel. Thanks for all the effort :)

I have a project with ES6 code and ES6 modules. My question is: how to do unit testing? I'm familiar with ava, mocha, tape, etc. I don't have a strong opinion on which one to use as long as it allows me to do lightweight unit testing with ES6 code and tests powered by rollup and buble.

**Comment by fskreuz** [comment]
> How to do unit testing with rollup+buble?

Just like you would do it in any other library, write tests against the public API of the bundled, transpiled output.

**Comment by josdejong** [comment]
My unit tests themselves are also written in ES6 + ES6 modules, so need to be transpiled and bundled too. I mostly test in node.js, sometimes also in the browser. 

[Ava](https://github.com/avajs/ava) solves this perfectly fine, though it's using babel and I would love to use rollup here. Just curious to how others have tackled unit testing with rollup+buble.

**Comment by Rich-Harris** [comment]
FWIW, my own approach is to use `buble/register` with Mocha (in fact, Bublé's own tests use this pattern):

```js
// package.json
{
  ...,
  "scripts": {
    "test": "mocha test/test.js --compilers js:buble/register",
    ...
  }
}
```

The downside is that `test/test.js` and any files that it depends on have to be `require`d, because Bublé doesn't attempt to convert `import` and `export` syntax. So you're testing the CJS/UMD build Rollup generates, rather than the ES build. In practice I haven't found this to be much of an inconvenience.

**Comment by eventualbuddha** [comment]
My typical approach is to use something similar to what @Rich-Harris has said, only with `babel-register` instead of `buble/register`.

Also, I've started putting the options into `test/mocha.opts` instead of in `package.json` so that running tests from WebStorm or Sublime Text or whatever doesn't have to duplicate the options and `package.json` just has this: `"test": "mocha"`.

While from a purity standpoint I agree testing the generated bundle is best, that usually means you can't unit test the internal parts. To address this, you could do a hybrid approach.

**Comment by josdejong** [comment]
Thanks for your suggestions. Good to know about `buble/register`, that helps a lot!

Testing the generated bundle will indeed work and is nice for integration tests. I would be really interested though in a way to "just" be able to use all ES6 goodness including modules in both my code and tests without having to jump though hoops. 

I will keep looking and poking around to see if I can find a solution to use ES6 modules. Maybe find/create some minimalist transform tool which turns ES6 modules into CJS (sort of the inverse of [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs)), and use that in combination with `mocha` and `buble/register`.

**Comment by Rich-Harris** [comment]
You could take a look at [reify](https://github.com/benjamn/reify) which is designed to enable `import` and `export` with any version of Node. In theory it should work alongside `buble/register`.

**Comment by josdejong** [comment]
Ah, reify could do the trick, going to play around with it!

**Comment by josdejong** [comment]
Awesome, reify works like a charm! I figured that for on-the-fly unit tests I use the latest version of node.js anyways which supports almost 100% ES6 so I don't need to convert to ES5. I can simply run:

```
mocha --require reify test
mocha --require reify test/justThisFile.test.js
```

(and similar when using tape via an npm script like
 `node --require reify test/**.test.js test/**/*test.js`)

Still struggling with getting all my tests bundled to run them in the browser and in old versions of node.js. Rollup doesn't support multiple entries, and to use mocha + chai (or assert) you need rollup-plugin-commonjs and rollup-plugin-node-resolve but I run into all sorts of issues trying to get that working. To be continued.

**Comment by eventualbuddha** [comment]
You can use rollup-plugin-multi-entry to get multiple entries with rollup.

**Comment by Rich-Harris** [comment]
Closing this as it looks like reify and rollup-plugin-multi-entry do the trick

**Comment by josdejong** [comment]
Yes, thanks. Still have to figure out some details but this should work.

**Comment by meszaros-lajos-gyorgy** [comment]
Reify gives an error, if you add default arguments to a function inside your unit tests and it also doesn't support the destructing assignment:
```javascript
const test = (name = 'Jim') => {
  console.log(`hello ${name}`)
}
test()

const test2 = ([x, y]) => {
  console.log(`the points are ${x} and ${y}`)
}
test2([100, 120])
```

On the other hand, bublé says, that it doesn't support import.

What now?
