### ISSUE TITLE
Alias & external dependencies

### ISSUE THREAD

**Issue by mjeanroy** [rollup/rollup#660]
Hi,
Suppose this build configuration (I use gulp-rollup, but it does not matter):

```javascript
gulp.task('bundle', () => {
  return gulp.src(path.join(__dirname, 'src/index.js'))
    .pipe(rollup({
      external: ['underscore'],
      plugins: [
        alias({
          lodash: 'underscore'
        })
      ]
    }))
    .pipe(gulp.dest(path.join(__dirname, 'dist')));
});
```

What I want to do:
- Replace `lodash` imports with `underscore` imports.
- Treat underscore as an external dependency.

Here is the following output:

```javascript
import _ from '../../../../../underscore';
```

It seems that the alias is replace with a relative path (please, check out [this repository](https://github.com/mjeanroy/test-rollup-alias) to test by yourself).

I tried to debug what happens in rollup and it seems that [this line](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L209) is responsible. Not sure if it could be a fix, but maybe rollup can check if the `resolvedId` value is a relative path ?

What do you think about this patch:

```diff
- } else if ( resolvedId ) {
+ } else if ( resolvedId && resolvedId.charAt(0) === '.' ) {
    normalizedExternal = this.getPathRelativeToEntryDirname( resolvedId );
}
```

If that sounds good to you, I can try to send you a PR.

Not sure, but it may be related to #633.

**Comment by Rich-Harris** [comment]
Fixed in 0.26.4 👍
