### ISSUE TITLE
Strange output indentation

### ISSUE THREAD

**Issue by GianlucaGuarini** [rollup/rollup#666]
Hi @Rich-Harris thanks for this piece of software! I am using rollup to build riot.js but I have noticed that the output code loses its indentation also when the `indent` option is set to false.

This is my config file:
```js
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import babel from 'rollup-plugin-babel'

export default {
  format: 'umd',
  moduleName: 'riot',
  banner: '/* Riot WIP, @license MIT */',
  indent: false,
  plugins: [
    nodeResolve({ jsnext: true, main: true }),
    commonjs({ include: 'node_modules/**' }),
    babel({
      exclude: 'node_modules/riot-tmpl/**'
    })
  ]
}
```
This is an example of input:

<img width="649" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/879612/15535205/a182b26c-226c-11e6-81dc-6bd76323e6ee.png">

that gets transformed by rollup into:

<img width="756" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/879612/15535223/b1f2653e-226c-11e6-8ab0-54e356c0f685.png">

any help is really appreciated thanks

**Comment by yairEO** [comment]
why would you care about the output code indentation? it's an auto-generated code which isn't interesting 99% of the time, unless you are curious about the result of a certain import

**Comment by GianlucaGuarini** [comment]
@yairEO yes and no..
Many pull request come from users debugging directly on the [output code](https://github.com/riot/riot/blob/master/riot.js) because it's clean and simple. Having an unminified version of our bundle so unreadable might be a problem for many users.
The question is why gets this code even changed?

**Comment by yairEO** [comment]
In what way users use the output code to submit pull requests? what is the flow? I'm trying to understand since this is the first time I hear about this. curious

**Comment by GianlucaGuarini** [comment]
[in](https://github.com/riot/riot/pull/1805) [this](https://github.com/riot/riot/pull/1731/commits/d77e72c33997c767b552e4652cbda9cbfa3cfefe) [way](https://github.com/riot/riot/pull/1289) - we can't control our users but sometimes in these wrong pull requests there are "real" bug that must be fixed. And secondly, if anyone has a problem in riot.js he/she can quickly debug it by digging the output code without being forced to pull the repo and compile riot by them self to add a `console.log`

**Comment by GianlucaGuarini** [comment]
Ok I've found out that removing the babel plugin the problem disappears. Closing this issue

**Comment by GianlucaGuarini** [comment]
for anyone landing on this issue: the option `compact: 'auto'` was the reason of the issue in babel. Setting it to `false` solved the problem
