### ISSUE TITLE
import all, object keys and the 'this' keyword

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#667]
Consider this simple scenario:

### A.js:

    export var get = function( name ){
        return this[name];
    }
    export var foo = 1;
    export var bar = 2;

### B.js:

    import * as obj from 'A';

    var foo = obj.get('foo');

---------------

### Expected bundle:

    var obj = {
        get : function( name ){
            return this[name];
        },
        foo : 1,
        bar : 2
    }

    var foo = obj.get('foo');

### Current bundle:

    var get = function get(name) {
        return this[name];
    };
    var foo = 1;
    var bar = 2;

    lates = Object.freeze({
        get: get,
        foo: foo,
        bar : bar
    }

    var foo = obj.get('foo');

-------------
The problem is the `this` keyword in `A.js` function `get` is not referencing the object (I really wish it did)

In reality I have a very big object of simple string, and a `get` method, which its purpose is to get the string and wrap it with something and return it (used for compiling template strings), so I'm trying to import all the templates, then using the `get` method pretty much everywhere to fetch the right template and return its compiled function.

Yes, I could use `call` to pass the reference, but that is ugly (resulting more code for me to write each time), and anyway, I don't get the point of bloating the code with variables, when what I wanted was to import those variable as an object..not as an object which only has keys as pointers to variables.

Also, I intentionally don't write `A.js` is an exported Object by itself, to have the option to import individual variables without importing them all.

**Comment by Victorystick** [comment]
Actually, [your example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20*%20as%20obj%20from%20'.%2FA.js'%3B%5Cn%5Cnvar%20foo%20%3D%20obj.get('foo')%3B%22%7D%2C%7B%22name%22%3A%22A.js%22%2C%22code%22%3A%22export%20var%20get%20%3D%20function(%20name%20)%7B%5Cn%20%20%20%20return%20this%5Bname%5D%3B%5Cn%7D%5Cnexport%20var%20foo%20%3D%201%3B%5Cnexport%20var%20bar%20%3D%202%3B%22%7D%5D%7D) results in the following code, which is exactly what I'd expect.

```js
var get = function( name ){
    return this[name];
}

var foo = get('foo');
```

If you just want to dynamically index exports of `A` you can do that without some freaky `get` function; [like so](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%5Cnimport%20*%20as%20obj%20from%20'.%2FA.js'%3B%5Cn%5Cnconsole.log(%20obj%5B'foo'%5D%20)%3B%22%7D%2C%7B%22name%22%3A%22A.js%22%2C%22code%22%3A%22export%20var%20get%20%3D%20function(%20name%20)%7B%5Cn%20%20%20%20return%20this%5Bname%5D%3B%5Cn%7D%5Cnexport%20var%20foo%20%3D%201%3B%5Cnexport%20var%20bar%20%3D%202%3B%22%7D%5D%7D).

```js
// B.js
import * as obj from './A.js';

console.log( obj['foo'] );
```

**Comment by yairEO** [comment]
Regarding the `get` function, I've made it very simple in the example code, but it is much more complex for me in reality (it does some transformation to the result), and that complicity is written once instead of accessing a property manually I access it via the `get` method.

I now get it, that it's impossible for Rollup to include `foo` (from the first example) in the bundle, because It doesn't know that the code asked to use `foo`.

`obj.get('foo');` doesn't let Rollup know that `foo` is needed and therefor include it, unless it knows from within `A.js`, but then there's the reference problem if what's `this`... because the bundle doesn't create an object (why? since `import X as Y` seems to me like I want an object to be generated..which will solve the issue)
