### ISSUE TITLE
Sourcemaps broken when Object.freeze generated

### ISSUE THREAD

**Issue by misea** [rollup/rollup#668]
Object.freeze statements appear to be generated when imported objects are exported out of rollup-known scope. However they do not seem to be accounted for in the source map, which breaks debugging.

Here's a repro

a.js
```
export var items = [];
export var one = 1;
export var two = 2;
export var three = 3;
export function hello() {
  console.log('hello');
}
export function world() {
  console.log('world');
}
```

b.js
````
import * as obj from './a.js';

window.test=obj;

obj.hello();
obj.world();
````

Using Chrome, breakpoints set in b.js are not mapped to the correct line, though they are if the window.test=obj line is removed. I'm assuming it's the Object.freeze statement that is causing the problem, but it could be something else.

**Comment by Victorystick** [comment]
Indeed. Curious.

**Comment by Rich-Harris** [comment]
Finally got round to fixing this, in 0.32.3. Thanks!
