### ISSUE TITLE
Great approach - PUSH!

### ISSUE THREAD

**Issue by clintwood** [rollup/rollup#67]
Just to say that as more and more projects/modules are switching to ES6+ using modules this concept ([as you describe here](https://github.com/rollup/rollup#a-better-approach)) and a guide on how to optimally structure module libraries should be pushed FAR and WIDE!  I know you working with Guy from `jspm` and others, which is great but this really needs big publicity/visibility!

Just saying ;)

**Comment by stefanullinger** [comment]
+1 ... awesome work!

**Comment by clintwood** [comment]
See [here](https://github.com/facebook/immutable-js/pull/547)!

**Comment by Rich-Harris** [comment]
Thanks! You're right, we should be a bit more vocal about all this – I want Rollup to succeed, but more than that I want its *ideas* to succeed, and that means educating people about the difference ES6 modules can make and what people can do to help move the ecosystem along. I've made a start on a website with an interactive demo, finding time to finish it alongside a gazillion other things is the fun part... hopefully soon though

**Comment by Victorystick** [comment]
@Rich-Harris Let me know what you're preparing something for GitHub pages. Would love to help if I can.

**Comment by Rich-Harris** [comment]
@Victorystick right now I can't even get the damn site to build – I broke something, will try and fix it – but the (extremely WIP) repo is https://github.com/rollup/rollupjs.org. I was thinking along these lines initially: http://esnext.github.io/es6-module-transpiler/editor

**Comment by Victorystick** [comment]
@Rich-Harris Can we considered this closed? The number of stargazers have grown a lot since this issue was opened. With http://rollupjs.org up and running and our [feature in JavaScript Weekly](http://javascriptweekly.com/issues/255) we've got more eyes on us than ever. :smile:

**Comment by Rich-Harris** [comment]
yep, I think so :beers:
