### ISSUE TITLE
Cannot call a namespace ('express')

### ISSUE THREAD

**Issue by j-oliveras** [rollup/rollup#670]
I'm trying to bundle a node app that uses express, but rollup fails with:
> Cannot call a namespace ('express')

Callstack:
> Error: Cannot call a namespace ('express')
>     at error (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\src\utils\error.js:2:14)
>     at call (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\src\utils\run.js:18:5)
>     at Object.enter (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\src\utils\run.js:85:10)
>     at visit (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\node_modules\estree-walker\dist\estree-walker.e
> s6.js:27:9)
>     at visit (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\node_modules\estree-walker\dist\estree-walker.e
> s6.js:51:4)
>     at visit (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\node_modules\estree-walker\dist\estree-walker.e
> s6.js:48:5)
>     at walk (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\node_modules\estree-walker\dist\estree-walker.es
> 6.js:5:2)
>     at run (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\src\utils\run.js:56:2)
>     at Statement.run$1 [as run] (C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\src\Statement.js:141:8)
>     at C:\Users\joliveras\AppData\Roaming\npm\node_modules\rollup\src\Module.js:619:23

That app are builded with typescript and exported with es6 modules and, with rollup, I want to generate a commonjs bundle.

I generate bundles with app that not use express without issues.

I made a sample project with same issue in pure javascript: https://github.com/j-oliveras/express-rollup-issue Only need `npm install` and `npm run rollup`.

I expect that Rollup generate a bundle with commonjs modules without issues.

I use node 4.4.0 (32 bits), npm 3.9.4 into Windows 7 Pro.

**Comment by Victorystick** [comment]
When importing a module's _namespace_ using `* as foo` you get a _namespace object_ which isn't callable. You should import express' default export instead.

```js
import express from 'express';

const app = express();
```

**Comment by j-oliveras** [comment]
Thanks.

Now works.

**Comment by tatemz** [comment]
I am having the same issue. When I used the suggested fix above, I get this error:

`Error: Module node_modules/express/index.js does not export default`

**Comment by Victorystick** [comment]
@tatemz Are you trying to bundle `express` along with your app? If you're not, I suggest marking it [external](https://github.com/rollup/rollup/wiki/JavaScript-API#external).

**Comment by tatemz** [comment]
Here is what I did to fix my error. Not sure if this is a good fix:

```
import * as express from 'express';

const e = require("express");

var app = e();
app.get('/', function (req: express.Request, res: express.Response) {
  res.status(200).send('ok');
});
```

**Comment by keithotto** [comment]
@Victorystick How do you mark express to be external? Based on the link you posted I tried:
`external: [ 'express' ]`

But still get the same Cannot call a namespace ('express'). Doesn't seem to be skipping over it.

**Comment by j-oliveras** [comment]
@keithotto to use @Victorystick solution with typescript you must enable ```allowSyntheticDefaultImports``` compiler option.

Tatemz solution should work, too.

**Comment by Blackbaud-PatrickOFriel** [comment]
@Victorystick  I'm having a similar problem when trying to use `import * as moment from 'moment';`. Considering that moment itself recommends that you use it this way (see: http://momentjs.com/docs/#/use-it/typescript/) this seems like something that should be supported by rollup.

**Comment by Rich-Harris** [comment]
@Blackbaud-PatrickOFriel That's crazy — not sure what TypeScript were thinking, but calling a namespace is straightforwardly impossible with ES modules, and it's not something Rollup will ever support. Moment's UMD file exposes a default export that should be used like this:

```js
import moment from 'moment';
var date = moment();
```

**Comment by Blackbaud-PatrickOFriel** [comment]
Thanks for the quick response @Rich-Harris, do you mind pointing out where can I access moment's UMD file?

**Comment by Rich-Harris** [comment]
If you go to unpkg.com/[packagename] you'll see the latest version of a package — or rather, the file that its `main` entry points to, which is often a UMD build:

https://unpkg.com/moment

Adding a `/` character to the end lets you browse the package contents (useful for cases when `main` isn't a bundle, as a lot of packages have a bundle in a `dist` or `build` folder):

https://unpkg.com/moment/

**Comment by jkuri** [comment]
encountered similar error. in TypeScript you can also do
```ts
import * as express_ from 'express';

let express: any = (<any>express_).default || express_;
```

**Comment by DrecDroid** [comment]
Hi, I had the same problem, each of the solutions described here works but It throws away VSCode Intellisense.

I've found a workaround that preserves the Intellisense and the import in the code.

```
import * as express_ from 'express'

let express = express_  // *-* MaGiC Happens Here *-*
let app = express()
```
I don't know why It works but It does.

My config looks like this:

```
export default {
  entry: 'express_server/main.ts',
  format: 'cjs',
  dest: 'express_server/bin/server.js',
  plugins: [
    typescript({
      typescript : require('typescript'),
      tsconfig : false,
      baseUrl: '.',
      moduleResolution: 'node',
    })
  ],
  external : ['express'] //Just to remove the warnings, still works without It.
};
```

Hopefully somebody find this helpful.

**Comment by Ismaestro** [comment]
I've made the same for moment:

```
import * as moment_ from 'moment';

const moment = moment_;
```

:)

**Comment by ne1410s** [comment]
> @keithotto to use @Victorystick solution with typescript you must enable `allowSyntheticDefaultImports` compiler option...
> 

Also seems that `esModuleInterop` compiler option needs to be enabled for the above to be effective.

**Comment by joshuakb2** [comment]
None of the above suggestions worked for me, trying to:
1. `import * as express from 'express'`, for access to types and other exports.
2. Call `express` as a function.
3. Keep intellisense working correctly in VS Code

This works though:
```ts
import * as express from 'express';
let app = express.call(null);
```
