### ISSUE TITLE
Namespace object methods and this

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#672]
Consider [this example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20*%20as%20ns%20from%20'.%2Ffoo.js'%3B%5Cn%5Cnconsole.log%28%20ns.self%28%29%20%29%3B%5Cnconsole.log%28%20ns%5B'self'%5D%28%29%20%29%3B%22%7D%2C%7B%22name%22%3A%22foo.js%22%2C%22code%22%3A%22export%20function%20self%20%28%29%20%7B%5Cn%20%20%20%20return%20this%3B%5Cn%7D%22%7D%5D%7D). If a function is accessed through the namespace object in such a way that Rollup cannot statically determine which function it is, and subsequently invoked, `this` will be bound to the namespace object. I do not think that is supposed to happen.

If people start relying on this behaviour, their code will break once modules are natively supported. Can we prevent it, and how? 

``` js
// main.js
import * as ns from './foo.js';

console.log( ns.self() );     // => window or undefined
console.log( ns['self']() );  // => ns

// foo.js
export function self () {
    return this;
}
```

**Comment by Rich-Harris** [comment]
I assume the spec is unambiguous on this point – that the namespace object is *not* the context in which the function is called? (Had a quick look but I'm bad at reading spec documents.)

**Comment by eventualbuddha** [comment]
Yeah, we should change the way we're calling them. I recommend following babel's approach when we have to use a member expression:

```js
function self () {
    return this;
}

var ns = Object.freeze({
    self: self
});

console.log( self() );
console.log( (0, ns['self'])() );
```

**Comment by Victorystick** [comment]
@eventualbuddha That'll work for dynamic access like in my example, but what about when were passing the namespace object to for example an external function?

```js
import * as ns from '...';

externalFunction(ns);
```

It still needs to be able to dynamically look up properties and call methods of the object. How should such scenarios be handled?

**Comment by bfred-it** [comment]
@Rich-Harris if `wontfix` then should we close thi and #728?

**Comment by guybedford** [comment]
It seems unlikely a new approach for handling this will be happening anytime soon. If there are new suggestions though, happy to reopen discussion.
