### ISSUE TITLE
Recognize pure instance methods

### ISSUE THREAD

**Issue by mhevery** [rollup/rollup#673]
Given:

```
var names = 'a,b,c'.split(',');
```

I would expect that to be tree shaken, unless `names` is used, but it is preserved (regardless if `names` is used.). The reason is that Rollup does not track types, and so it can't be sure that `split` is a function on `string`. 

I would like to propose a work around like this:

```
var names = String.prototype.split.call('a,b,c', ',');
```

Now rollup can be sure that `split` is called on a `string` and it should know that it is pure. It seems that [pureFunctions.js](https://github.com/rollup/rollup/blob/master/src/utils/pureFunctions.js) should be updated with `String.prototype.split` and both `apply` and `call` methods.

//cc @robwormald

**Comment by guybedford** [comment]
The original scenario here is now correctly treeshaken by Rollup, although the work-around case is still not supported!
