### ISSUE TITLE
new vs Object.create() tree shaking issue

### ISSUE THREAD

**Issue by robwormald** [rollup/rollup#674]
Given:

``` javascript
//test.ts
export class SomeThing {}

export class Identifier {
  constructor() {}
};
Identifier.foo = new SomeThing();
//Identifier.bar = Object.create(Identifier);

export class SomeOtherIdentifier {}
```

``` javascript
//main.js
import {SomeOtherIdentifier} from './test'

console.log(new SomeOtherIdentifier());
```

Output:

``` javascript
(function () {
  'use strict';

  class SomeThing {}

  class Identifier {
    constructor() {}
  };
  Identifier.foo = new SomeThing();

  class SomeOtherIdentifier {}

  console.log(new SomeOtherIdentifier());

}());
//# sourceMappingURL=rollup-out.js.map
```

Note the extraneously included SomeThing and Identifier classes

Interestingly, given a slightly changed file, using `Object.create(SomeThing)` instead of `new SomeThing()`:

``` javascript
export class SomeThing {}

export class Identifier {
  constructor() {}
};
Identifier.bar = Object.create(Identifier);

export class SomeOtherIdentifier {}
```

The extraneous classes are appropriately dropped:

``` javascript
(function () {
  'use strict';

  class SomeOtherIdentifier {}

  console.log(new SomeOtherIdentifier());

}());
//# sourceMappingURL=rollup-out.js.map
```

Test cases [new](http://tinyurl.com/hzbrklh) vs [Object.create](http://tinyurl.com/glrxmpk)

cc @mhevery @eventualbuddha

**Comment by IgorMinar** [comment]
fyi: Object.create is a red herring because it doesn't cause the constructor to be called.

**Comment by mhevery** [comment]
Yes, it can only be used in cases where the constructor args and shape of
the object match. (ie no work other then assignment is done in the
constructor.)

**Comment by Rich-Harris** [comment]
Rollup understands whether or not a constructor function has side-effects, and [can remove `new` expressions if there are none](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22function%20Foo%20()%20%7B%5Cn%20%20%2F%2F%20comment%20out%20the%20next%20line%20%E2%80%93%20everything%20will%20be%20removed%5Cn%20%20alert(%20'side-effect!'%20)%3B%5Cn%7D%5Cnvar%20foo%20%3D%20new%20Foo()%3B%22%7D%5D%7D):

```js
function Foo () {
  // comment out the next line – everything will be removed
  alert( 'side-effect!' );
}
var foo = new Foo();
```

But it [doesn't know about classes and constructors](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22class%20Foo%20%7B%5Cn%20%20constructor%20()%20%7B%5Cn%20%20%20%20%2F%2F%20comment%20out%20the%20next%20line%20%E2%80%93%20has%20no%20effect%5Cn%20%20%20%20alert(%20'side-effect!'%20)%3B%5Cn%20%20%7D%5Cn%7D%5Cnvar%20foo%20%3D%20new%20Foo()%3B%22%7D%5D%7D). I think that's something we could probably fix 👍

**Comment by hettiger** [comment]
@Rich-Harris +1 I really think that it needs to be fixed. Any plans on this?
