### ISSUE TITLE
Potential vulnerability from scope merging

### ISSUE THREAD

**Issue by tolmasky** [rollup/rollup#675]
Rollup appears to effectively merge scopes during its concatenation process. A malicious module could hide somewhere in their code something like:

```javascript
try { x = eval("MY_SECRETER"); http_send(x); } 
```

Later, your code:

```javascript
var MY_SECRETER = .... // only this file has access to this.
```

However, once you rollup, the malicious module will have access to this.

**Comment by tolmasky** [comment]
I see that this is already address in the wiki, I can go ahead and close this.

**Comment by tolmasky** [comment]
Upon a second reading, I guess it doesn't really deal with the security aspects, so maybe that is at least worth warning about.

**Comment by Rich-Harris** [comment]
Thanks! 0.26.4 beefs up the warning to mention the vulnerability, and I've also updated the wiki
