### ISSUE TITLE
wrong ES6 format / bundle

### ISSUE THREAD

**Issue by himalayafan** [rollup/rollup#678]
Arrow, class etc are all part of the ES2015. 
If you use arrow functions, and bundle to ES6 format, it get transpiled. The arrow functions are gone even it's part of the ES2015 specs.

I also experienced that Class got transformed to prototype. There are also other examples.

Repro? Simply try it out!

**Comment by aeosynth** [comment]
you probably have a `.babelrc` with those options enabled

**Comment by himalayafan** [comment]
Tested with babelrc set to false in the config. Also tested with buble.

**Comment by Rich-Harris** [comment]
ES6 format just means that the bundle uses `import` and `export`, not that it somehow disables the transpilation that Babel or Bublé do. You need to explicitly disable those transforms.
