### ISSUE TITLE
Trying to looking up named import from external module

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup#68]
We have a quite big (400K source) project that I would like to bundle with rollup, but it it currently fails when I use a named import from an external dependency.

The problem is here:
https://github.com/rollup/rollup/blob/master/src/Bundle.js#L238
`TypeError: Cannot read property 'mat4' of undefined`

I will try to reduce this to a smaller testcase and fix it in the process, but it might take me some time…

**Comment by Rich-Harris** [comment]
Closed via #70
