### ISSUE TITLE
Flow to help eliminate dead code

### ISSUE THREAD

**Issue by sheerun** [rollup/rollup#687]
Your project has been mentioned at the end of Flow presentation, I thought I'd ping you:
https://www.youtube.com/watch?v=VEaDsKyDxkY

Flow could aid to perform more comprehensive dead code elimination.

**Comment by Rich-Harris** [comment]
Thanks for sharing! Yep, there's a lot of work to do to get some sort of value tracking in Rollup to enable better static analysis, and the extra information Flow provides could be extremely useful in that context. Probably out of scope in the near future but definitely something to bear in mind. 👍 

Relevant section of the talk is at [26m5](https://youtu.be/VEaDsKyDxkY?t=26m5s), for anyone interested. Jeff hits on one of the frustrations that frequently comes up – people are often confused about why unused object properties and class methods (etc) aren't removed. My hunch is that we could get pretty far within JavaScript by tracking values (and types, by extension), but it certainly wouldn't be easy...
