### ISSUE TITLE
README information on the CLI

### ISSUE THREAD

**Issue by iamJoeTaylor** [rollup/rollup#69]
It would be awesome if there was a way to get a bit of information on the CLI in the README.

**Comment by tdumitrescu** [comment]
if esperanto is being phased out in favor of rollup (https://github.com/esperantojs/esperanto/pull/191) it would be nice to have _something_ in the README that gives actual (non-"aspirational") usage examples...

**Comment by Rich-Harris** [comment]
Agree! @Victorystick has added some usage info, and I plan to rewrite the README to better reflect the fact that Rollup is now much less of an experiment. I don't plan to merge https://github.com/esperantojs/esperanto/pull/191 until that's done
