### ISSUE TITLE
Lodash tree-shaking issue

### ISSUE THREAD

**Issue by efender** [rollup/rollup#691]
There is a simple `app.js` file that has one import from [lodash-es](https://github.com/lodash/lodash/tree/es) (v4.13.1):

1) import template module from `template.js` file
```js
import { default as _template } from './libs/lodash-es/template';
const compiled = _template( '<h1 class="<%-className%>"><%=title%></h1>' );
```
**RESULT 1:** bundle.js size **_50.93 Kb_**
   
   
2) import template module from `lodash.js` re-export file
```js
import { template as _template } from './libs/lodash-es/lodash';
const compiled = _template( '<h1 class="<%-className%>"><%=title%></h1>' );
```
**RESULT 2:** bundle.js size **_547.58 Kb_**

rollup config:
```js
rollup( {
    entry: 'app.js',
} ).then(...);
```

**Comment by Rich-Harris** [comment]
Yep, this is a known issue. Rollup tracks all imported files to see what side-effects they have – not doing so frequently results in incorrect programs. Unfortunately lodash has a lot of what *look* like side-effecty statements, so a lot of unused code gets included.

Eventually we plan to make the static analysis a bit smarter to reduce the number of false positives in the tree-shaking algorithm, but the advice for lodash is to import modules from individual files, as per your first example.

**Comment by jdalton** [comment]
In the meantime there's always [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to assist.
It's also great combo'ed with [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

**Comment by goliney** [comment]
I've just met rollup, and was extreamly exited, but I have to give up with it already, because I can not make it work with `import {defaults} from 'lodash';`, which I use with `babel-plugin-lodash`.

**Comment by jdalton** [comment]
@goliney Rollup has a way to work with babel plugins. See [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel).

**Comment by curran** [comment]
Related to https://github.com/d3/d3/issues/3076

**Comment by yairEO** [comment]
@jdalton - Hi, I've tried using `babel-plugin-lodash` within `rollup-plugin-babel` but still I cannot import:

   import { template } from 'lodash.template'

## This is my configuration for the *babel* *rollup* plugin:

    {
        "plugins": [["lodash", { "id": ["lodash-template"] }]],
        "presets": [["@babel/env", { "targets": { "node": 6 } }]]
    }

**Comment by TrySound** [comment]
@yairEO Just import from normal lodash.
```
import {template} from 'lodash';
```

**Comment by yairEO** [comment]
@TrySound - I've also tried it but got this error:

>  Error: 'default' is not exported by node_modules\lodash\template.js

**Comment by TrySound** [comment]
Because lodash is cjs. Try `lodash-es` or transpile cjs to esm with plugin.

**Comment by yairEO** [comment]
@TrySound - Thanks Bogdan. Now it did work :)

But, unfortunately I get this error:

> Lodash chain sequences are not supported by babel-plugin-lodash.

For this simple code example:

    import template from 'lodash'

    template();  // <-- for this. In reality I'm passing some basic HTML string here

**Comment by leodr** [comment]
If you're having trouble with similar problems you can always use the individual lodash function packages like [`lodash.template`](https://www.npmjs.com/package/lodash.template).

**Comment by TrySound** [comment]
@leodr They are deprecated and will be removed in lodash v5.

**Comment by leodr** [comment]
> @leodr They are deprecated and will be removed in lodash v5.

You're right, I added it to my comment.
