### ISSUE TITLE
Option to disable __esModule?

### ISSUE THREAD

**Issue by developit** [rollup/rollup#708]
Thought I'd properly submit this as an issue rather than commenting on a closed PR:  would it be possible to provide an option (or piggyback off of `strictMode:false`) to disable the `__esModule` property from being defined on UMD/AMD bundles?

Context:
- [original comment](https://github.com/rollup/rollup/pull/685#issuecomment-224463889)
- [my current hacky solution via uglify `--pure-funcs`](https://github.com/developit/preact/blob/master/package.json#L14)

**Comment by eventualbuddha** [comment]
An option for this might be fine. I don't think I'd want to conflate it with `strictMode`. Out of curiosity, how do you handle interop with e.g. babel when you don't have `__esModule`?

**Comment by developit** [comment]
In my case, my default export is always an object that matches the named exports.
Since filing this issue, I've actually switched to only producing a default export, which actually skips `__esModule`.  Maybe that's enough of a solution?  I just proxy the entry file using `rollup-plugin-memory`.

**Comment by eventualbuddha** [comment]
> Maybe that's enough of a solution?

Sounds like that might be enough. I'll let you close if you like.

**Comment by developit** [comment]
Will do! :)

**Comment by futurist** [comment]
The `cjs` code generated with `exports: named` cannot work under ES3 (IE8), due to:
```js
Object.defineProperty(exports, '__esModule', { value: true })
```

That's a problem when we want more compatible, recommand have an option to disable it.

**Comment by eventualbuddha** [comment]
@futurist you could snip out that line in a post-processing step, or you could include a polyfill for `Object.defineProperty`.

IE 8 seems to have roughly 2-5% global market share. I realize there are still places that require supporting it, but I question whether it's worth bringing that legacy into a tool like rollup.

**Comment by Rich-Harris** [comment]
My vote would be for adding a polyfill – you could do it with the `intro` option:

```js
// rollup.config.js
export default {
  entry: 'src/index.js',
  dest: 'bundle.js',
  format: 'cjs',
  intro: `if (!Object.defineProperty) Object.defineProperty = function(obj, prop, descriptor) {obj[prop] = descriptor.value;};`
};
```

(Obviously that's not a complete polyfill, but either a) you've already got one or b) you only need it for the `__esModule` stuff)

**Comment by futurist** [comment]
I've made this plugin to remove `__esModule` line, when want to compatible with ES3:

https://github.com/futurist/rollup-plugin-es3

**Comment by TrySound** [comment]
This is required to move react to named exports with smoother interop. Can we go with `esModule: false` option?

/cc @guybedford

**Comment by GrosSacASac** [comment]
Issue can be closed
output.esModule to false to disable it
