### ISSUE TITLE
Environment variabels doesn't work correctly

### ISSUE THREAD

**Issue by Kflash** [rollup/rollup#719]
I'm trying to use the environment variabel feature provided by Rollup, but doesn't work correctly. It seems like the variabels are not set at the beginning?
My original code is this:
`cross-env NODE_ENV=production rollup -c rollup.config.js`

if I change this to 

`rollup -c --environment NODE_ENV:production rollup.config.js`

Things will not work out if I in the bundle process checks if I e.g. check like this:

` debugger: PRODUCTION ? true : false, `
Or if I have a check like this

```
if (!PRODUCTION) { 
   ...
}
```
the code will run even if there is a production build I'm bundling. I know the production variable is set. I see it's "true" value in the console log. But the check isn't working. For this do I maybe need to unset development variable to falsy first?

For cross-env it seems like all environment variabels are set first before Rollup starts to roll-up. With Rollup it seems like the variabels is set in the middle of the process?

Hard to say what's causing this, but I tried different solutions and ended up with nodeResolve plugin errors, uglify plugin errors etc.

It's not a big issue for me, I can contiue using cross-env 

**Rollup version: 0.31.2**

Sources I used is the Rollup documentation, and also the Rollup config file for Buble on the GitLab repo.

**Comment by eventualbuddha** [comment]
It's unclear how the `PRODUCTION` constant in your code is related to the `NODE_ENV` variable. Can you share your config? Maybe a repo that illustrates the problem?

**Comment by Kflash** [comment]
`const PRODUCTION = process.env.NODE_ENV === 'production';`

This is the constant. As mentioned earlier this is set in package.json as illustrated. I then in the configuration check if PRODUCTION. If so I minify the source with uglify.

This is not working with rollup environment variables. 

It's not an issue with my configuration it seems.

` cross-env ` works.  And if I do `set NODE_ENV= ` manually it also works.

**Comment by Rich-Harris** [comment]
The `--environment` flag affects `process.env` *inside your config file*, not inside the generated bundle. You can use [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) to rewrite code:

```js
import replace from 'rollup-plugin-replace';

export default {
  entry: 'main.js',
  plugins: [
    replace({
      PRODUCTION: process.env.PRODUCTION ? 'true' : 'false'
    })
  ]
}
```

**Comment by Guria** [comment]
https://github.com/rollup/rollup/issues/487#issuecomment-485660918 works like a charm for me
