### ISSUE TITLE
TypeScript & Templates 

### ISSUE THREAD

**Issue by daslicht** [rollup/rollup#720]
Hi,
is there e a way to use Rollup with TypeScript ?
How about bundling Templates and send them to the client ?

**Comment by eventualbuddha** [comment]
You can use [rollup-plugin-typescript](https://github.com/rollup/rollup-plugin-typescript) in your `rollup.config.js` file.

As for templates, it depends on what template system you're using. There are [quite a few plugins](https://www.npmjs.com/browse/keyword/rollup-plugin) that support a variety of formats. If the format you're looking for is not available you should check out the [plugin info wiki page](https://github.com/rollup/rollup/wiki/Plugins) for information on writing your own plugin.

**Comment by daslicht** [comment]
Thank you !
