### ISSUE TITLE
diamond import/export structure

### ISSUE THREAD

**Issue by thepian** [rollup/rollup#729]
I'm not sure if this is a core rollup issue or with the includes plugin. I saw it after adding a common package index.js

Given

```
flow.js
/m/index.js
/m/a.js
/m/b.js
/m/common.js
```

flow imports `./m`
a imports `./common`
b imports `./common`
common has no imports

When I refer to a common export in the index file it cannot find it as it doesn't have the $1 postfix.

**Comment by TrySound** [comment]
@thepian Provide please full error stack and code examples

**Comment by thepian** [comment]
I changed the structure, I cannot reproduce it
