### ISSUE TITLE
uglify performance on rollup build

### ISSUE THREAD

**Issue by sod** [rollup/rollup#734]
Don't know why, but uglify on a rollup build was a magnitude faster if the var statements weren't combined but on first occurance of a variable instead. 

#### `var` on occurance (looks like https://gist.github.com/sod/8a86e1a5448740a25e64c7f5746fd221)
```sh
# command
for test in 1000 2000 3000 4000; do; echo "$test Variables:"; node create-uglify-data.js $test > x.js; time uglifyjs --compress --mangle -- x.js > x.min.js; done;
# output:
1000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  0,25s user 0,03s system 117% cpu 0,242 total
2000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  0,33s user 0,03s system 115% cpu 0,315 total
3000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  0,43s user 0,04s system 112% cpu 0,419 total
4000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  0,45s user 0,04s system 113% cpu 0,435 total
```

#### `var` in head (looks like https://gist.github.com/sod/60834139bf84298bb10af86069968d62)
```sh
# command
for test in 1000 2000 3000 4000; do; echo "$test Variables:"; node create-uglify-data.js $test --include-head > x.js; time uglifyjs --compress --mangle -- x.js > x.min.js; done;
# output:
1000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  1,98s user 0,04s system 103% cpu 1,959 total
2000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  6,70s user 0,05s system 100% cpu 6,686 total
3000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  8,58s user 0,06s system 100% cpu 8,595 total
4000 Variables:
uglifyjs --compress --mangle -- x.js > x.min.js  14,74s user 0,09s system 100% cpu 14,786 total
```

the test script: https://gist.github.com/sod/667821065fb37d6d406c07cca07f9e54

**Comment by Rich-Harris** [comment]
That's really fascinating, I had no idea. I wonder why? Might be worth raising an issue with the UglifyJS folks.

I'm not sure if there's anything Rollup can do though – it's not hoisting variables unnecessarily, so there isn't really any behaviour that could change (that I'm aware of?) to make it more Uglify-friendly.

Furthermore I'm not sure if Rollup *should* modify its output for a particular minifier. I got a similar result – with 1000 variables, `time uglify input.js -cm` took **1.87s** for combined vars, **0.24s** for separate ones. But with [Prosecco](http://prosecco.surge.sh/) (an ES6-friendly minifier I haven't quite finished writing) I get **0.18s** and **0.15s** respectively – a negligible difference. So it seems that Uglify is just doing something odd and preventable and therefore likely to change in future.

**Comment by sod** [comment]
You also write a minifier? lol, how many hours has your day?

I made a ticket and got an answer here https://github.com/mishoo/UglifyJS2/issues/1145#issuecomment-227335465

**Comment by jonataswalker** [comment]
@Rich-Harris https://gitlab.com/Rich-Harris/prosecco - 404

I'm curious about it.

**Comment by Rich-Harris** [comment]
@jonataswalker yeah, I've been meaning to open source it, haven't had a chance to tidy up the codebase a bit (my day has fewer hours than I'd like, to answer @sod's question!). Soon hopefully.

That's good to know about Uglify's performance with sequences – sounds like it should be possible to improve it by using iteration instead of recursion. I'm going to close this issue as I don't think there's anything for Rollup to do here – thanks
