### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#743]
I just upgraded to 0.32, and now I get a TypeError. My command-line is:

```
rollup --banner "$(preamble)" -f umd -g d3-time:d3 -n d3 -o build/d3-time-format.js -- index.js
```

(See [d3-time-format](https://github.com/d3/d3-time-format/blob/master/package.json#L26).)

It’s trying to do this:

```js
// Add missing Module IDs to external.
if ( external.indexOf( names[0] ) === -1 ) {
  external.push( names[0] );
}
```

And `external` is undefined. This appears related to 9461ed325eb43059e4f26caea3a67396acac99ef.

**Comment by Rich-Harris** [comment]
Whoops! Fixed in 0.32.2, thanks
