### ISSUE TITLE
Weird sourcemaps

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#745]
Threw out thousands lines of my project code and got this minimal structure which logs in wrong line and file.
[rollup-sourcemaps.zip](https://github.com/rollup/rollup/files/329644/rollup-sourcemaps.zip)

**Comment by Rich-Harris** [comment]
Looks like a dupe of #668 – looking into it now

**Comment by Rich-Harris** [comment]
fixed in 0.32.3

**Comment by TrySound** [comment]
Thanks!

**Comment by TrySound** [comment]
Yay! It works!:)
