### ISSUE TITLE
Sourcemap error is imprecise

### ISSUE THREAD

**Issue by patlillis** [rollup/rollup#746]
When running rollup from the command line, with a config file, and passing in the --sourcemap option, I get the following error:

![image](https://cloud.githubusercontent.com/assets/2921735/16301194/053191c8-3912-11e6-95d9-32d024c067fd.png)

**Cannot generate a sourcemap if non-sourcemap-generating transformers are used**

I finally figured out it was because I was passing `sourceMap: false` into the config for rollup-plugin-commonjs, but it would be really helpful if the error message told me which plugin/transformer is non-sourcemap-generating.

**Comment by TrySound** [comment]
@patlillis Do you use `rollup-plugin-string`?

**Comment by Rich-Harris** [comment]
Rollup doesn't actually have a way of *knowing* which plugin caused the error. Perhaps if there was a convention of plugins returning an object with an ID property we could gradually work around that – so something like rollup-plugin-string could look like this:

```js
import { createFilter } from 'rollup-pluginutils';

export default function string(opts = {}) {
  if (!opts.include) {
    throw Error('include option should be specified');
  }

  const filter = createFilter(opts.include, opts.exclude);

  return {
    name: 'string',

    transform(code, id) {
      if (filter(id)) {
        return `export default ${JSON.stringify(code)};`;
      }
    }
  };
}
```

That way we could print an error like 'Sourcemap generation failed because the 'string' plugin did not return a valid { code, map } object. See TKTK for more information'

**Comment by TrySound** [comment]
Let's follow this.

**Comment by TrySound** [comment]
Also why rollup doesn't add empty map by default?

**Comment by TrySound** [comment]
@patlillis [string 2.0.1](https://github.com/TrySound/rollup-plugin-string/releases/tag/v2.0.1) was fixed and released.

**Comment by Rich-Harris** [comment]
As of 0.33, this results in a warning rather than an error, and where possible Rollup will identify the offending plugin (i.e. as long as it returns a `name`)

**Comment by patlillis** [comment]
Awesome! Good stuff, thanks.
