### ISSUE TITLE
simple re-export fails with `TypeError: Cannot read property 'isExternal' of undefined`

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup#75]
I have a very simple straightforward re-export like this:
```js
export {json} from "./xhr"
```

That fails with the following error:

```
TypeError: Cannot read property 'isExternal' of undefined
    at Module.getCanonicalName (.gobble-build/01-rollup/1/rollup.js:1238:17)
    at .gobble-build/01-rollup/1/rollup.js:2055:76
```

Renaming it like `export {json as json2} from "./xhr"` solves the problem however. So I would guess it some kind of naming conflict. Hopefully it will be solved by #71 or similar.
I haven’t been able to create a reduced testcase so far :-(

**Comment by Victorystick** [comment]
@Swatinem Thank you for reporting all these bugs. The primary reason for #71 is to gather all names in one place for easier maintenance. It'll hopefully help to address a bunch of these issues.

**Comment by Rich-Harris** [comment]
Am a little stumped by this one... it *looks* the same as [this test case](https://github.com/rollup/rollup/tree/master/test/function/export-from-internal-module) which already passes. Hopefully it'll be just as mysteriously resolved by #71 or #78

**Comment by Rich-Harris** [comment]
@Swatinem can you try this out with 0.14.0 and see if it's fixed please? Thanks

**Comment by Swatinem** [comment]
Yes, this particular case is fixed, I still do have two failures with my code, I’m trying to reduce them to testcases right now.
