### ISSUE TITLE
`paths` option

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#754]
Scenario: your bundle depends on an external library, but you don't want to do this sort of thing:

```js
import react from 'https://npmcdn.com/react@15.0.1/dist/react.min.js';

// or, e.g. in /bin/my-lib
import myLib from '../dist/my-lib.js'
```

In the second case, you can end up in [all sorts of contortions](https://github.com/Rich-Harris/acorn/blob/02dc124b80ed12a9b71a74b0f809f078333afc09/rollup/config.bin.js#L4-L7) if the relative path from the bundle isn't the same as the relative path from the source file.

Proposed solution: use an external module ID, as normal, but then:

```js
// rollup.config.js
export default {
  entry: 'src/main.js',
  dest: 'bundle.js',
  paths: {
    'react': 'https://npmcdn.com/react@15.0.1/dist/react.min.js',
    'my-lib': '../dist/my-lib.js' // relative to bundle
  },
  // ...
};
```

**Comment by TrySound** [comment]
Isn't [rollup-plugin-alias](https://github.com/frostney/rollup-plugin-alias) the same?

**Comment by Rich-Harris** [comment]
Not unless I've misunderstood rollup-plugin-alias – this is about *external* dependencies. (By extension, `paths` keys should probably be added to `external`, in the same way that `globals` keys are)
