### ISSUE TITLE
Tree-shaking issues when importing rolled-up bundle

### ISSUE THREAD

**Issue by maxdavidson** [rollup/rollup#757]
When importing a bundle that has been exported as an ES module with Rollup, it does not apply tree-shaking as aggressively. 

Examples: [conditional exports](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2Finline%20exports%20-%20WORKS%5Cn%2F%2F%20export%20%7B%20readU16LE%20%7D%20from%20'.%2Fa'%5Cn%5Cn%2F%2F%20separate%20exports%20-%20DOESN'T%20WORK%5Cnexport%20%7B%20readU16LE%20%7D%20from%20'.%2Fb'%22%7D%2C%7B%22name%22%3A%22a.js%22%2C%22code%22%3A%22const%20isLE%20%3D%20new%20Uint8Array%28new%20Uint16Array%28%5B0xFF00%5D%29.buffer%29%5B0%5D%20%3D%3D%3D%200x00%3B%5Cn%5Cnexport%20function%20readU16LE%28dv%2C%20i%29%20%7B%5Cn%20%20return%20dv.getUint16%28i%2C%20true%29%3B%5Cn%7D%5Cn%5Cnexport%20function%20readU16BE%28dv%2C%20i%29%20%7B%5Cn%20%20return%20dv.getUint16%28i%2C%20false%29%3B%5Cn%7D%5Cn%5Cnexport%20const%20readU16%20%3D%20isLE%20%3F%20readU16LE%20%3A%20readU16BE%3B%22%7D%2C%7B%22name%22%3A%22b.js%22%2C%22code%22%3A%22const%20isLE%20%3D%20new%20Uint8Array%28new%20Uint16Array%28%5B0xFF00%5D%29.buffer%29%5B0%5D%20%3D%3D%3D%200x00%3B%5Cn%5Cnfunction%20readU16LE%28dv%2C%20i%29%20%7B%5Cn%20%20return%20dv.getUint16%28i%2C%20true%29%3B%5Cn%7D%5Cn%5Cnfunction%20readU16BE%28dv%2C%20i%29%20%7B%5Cn%20%20return%20dv.getUint16%28i%2C%20false%29%3B%5Cn%7D%5Cn%5Cnconst%20readU16%20%3D%20isLE%20%3F%20readU16LE%20%3A%20readU16BE%3B%5Cn%5Cnexport%20%7B%20readU16LE%2C%20readU16BE%2C%20readU16%20%7D%22%7D%5D%7D), [evaluated functions](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20Inline%20exports%20-%20WORKS%5Cn%2F%2F%20export%20%7B%20foo%20%7D%C2%A0from%20'.%2Fa'%5Cn%5Cn%2F%2F%20Separate%20exports%20-%20DOESN'T%20WORK%5Cnexport%20%7B%20foo%20%7D%C2%A0from%20'.%2Fb'%22%7D%2C%7B%22name%22%3A%22a.js%22%2C%22code%22%3A%22const%20hello%20%3D%205%5Cn%5Cnfunction%20getHello%28%29%20%7B%5Cn%20%20return%20hello%3B%5Cn%7D%5Cn%5Cnexport%20const%20foo%20%3D%20getHello%28%29%3B%5Cnexport%20const%20bar%20%3D%20getHello%28%29%3B%22%7D%2C%7B%22name%22%3A%22b.js%22%2C%22code%22%3A%22const%20hello%20%3D%205%3B%5Cn%5Cnfunction%20getHello%28%29%20%7B%5Cn%20%20return%20hello%3B%5Cn%7D%5Cn%5Cnconst%20foo%20%3D%20getHello%28%29%3B%5Cnconst%20bar%20%3D%20getHello%28%29%3B%5Cn%5Cnexport%20%7B%20foo%2C%20bar%C2%A0%7D%22%7D%5D%7D)

The cause of this seems to be that directly evaluated expressions that depend on other variables cannot be tree-shaken unless their declarations are prefixed with `export`. Since Rollup's ES bundling always places the exports at the end of the file, no tree-shaking is applied.

**Comment by Rich-Harris** [comment]
Sorry for the non-response. This looks to have been fixed in recent versions — closing
