### ISSUE TITLE
"this" converted to "undefined"

### ISSUE THREAD

**Issue by dbrgn** [rollup/rollup#759]
I'm having a problem with `this` in a function since rollup 0.31.

Is this invalid code or is it a rollup bug?

Input file:

```javascript
// testcase.spec.js
export default () => {
    describe('Simple Testcase', () => {
        beforeEach(() => {
            this.date = new Date();
        });
        it('is not undefined', () => {
            expect(this.date).not.toBeUndefined();
        });
    });
}
```

Rollup 0.30:

```javascript
var testcase_spec = () => {
    describe('Simple Testcase', () => {
        beforeEach(() => {
            this.date = new Date();
        });
        it('is not undefined', () => {
            expect(this.date).not.toBeUndefined();
        });
    });
}

export default testcase_spec;
```

Rollup 0.31:

```javascript
var testcase_spec = () => {
    describe('Simple Testcase', () => {
        beforeEach(() => {
            undefined.date = new Date();
        });
        it('is not undefined', () => {
            expect(undefined.date).not.toBeUndefined();
        });
    });
}

export default testcase_spec;
```

**Comment by Rich-Harris** [comment]
It's invalid code I'm afraid. The previous (0.30) behaviour was incorrect – at the top level of an ES2015 module (which includes the bodies of arrow functions), `this` is `undefined`. You can't use it to mean the global namespace as in scripts or CommonJS modules.

**Comment by dbrgn** [comment]
So the correct way would probably be to use real functions instead of function expressions, so that a namespace is created?

```
export default () => {
    describe('Simple Testcase', function() {
        beforeEach(() => {
            this.date = new Date();
        });
        it('is not undefined', () => {
            expect(this.date).not.toBeUndefined();
        });
    });
}
```

**Comment by dbrgn** [comment]
Also, should this trigger a warning, instead of creating attributes on `undefined` in the resulting code?

**Comment by Rich-Harris** [comment]
Since ES2015 modules are always in strict mode (i.e. the bundled result always has a 'use strict' pragma at the top), the `this` inside the function is *also* `undefined`, so that isn't a workaround. If you really, *really* have to modify the global namespace the way to do it would be something like this:

```js
var root = typeof window !== 'undefined' ? window :
           typeof global !== 'undefined' ? global :
           Function('return this')();

root.date = new Date();
```

> Also, should this trigger a warning, instead of creating attributes on `undefined` in the resulting code?

Triggering a warning is a good idea since it's probably unintentional. But we do need to change the code – otherwise, when modules are natively supported in browsers and people are able to stop using Rollup, they'll have to spend painful hours tracking down bugs that we hid from them. In the long run, we're not helping anybody by violating the spec.

**TODO**

* [ ] trigger warning when `this` is rewritten as `undefined`

**Comment by dbrgn** [comment]
> If you really, really have to modify the global namespace the way to do it would be something like this

The code in question is run by a testing framework and I just want to change the function scope, not the global scope :)

> In the long run, we're not helping anybody by violating the spec.

Yes of course :) Stick to the spec. Warnings would probably help.

**Comment by eventualbuddha** [comment]
> The code in question is run by a testing framework and I just want to change the function scope, not the global scope :)

Yes, for mocha you just use regular functions if you need there framework-provided context.

**Comment by Victorystick** [comment]
@dbrgn Why not just define a variable instead of assigning properties to `this`?

```js
// testcase.spec.js
export default () => {
    describe('Simple Testcase', () => {
        let date;
        beforeEach(() => {
            date = new Date();
        });
        it('is not undefined', () => {
            expect(date).not.toBeUndefined();
        });
    });
}
```

**Comment by eventualbuddha** [comment]
Closing as there's nothing for rollup to do here.

**Comment by dbrgn** [comment]
What about this?

`TODO: trigger warning when this is rewritten as undefined`

**Comment by Rich-Harris** [comment]
@dbrgn I've opened #770 to track that

**Comment by pornel** [comment]
We've been told that this also affects [code in Superagent](https://github.com/visionmedia/superagent/pull/1076) which I think is perfectly valid from CommonJS perspective. It'd be nice if you could find solution to support `this` in exported function expressions in CommonJS modules.

**Comment by ntilwalli** [comment]
@pornel I submitted an issue for this earlier today to get comment: https://github.com/rollup/rollup/issues/1007
