### ISSUE TITLE
Doesn't support an export-from form.

### ISSUE THREAD

**Issue by ericf** [rollup/rollup#76]
I ran into an error when trying to rollup a module that uses the following export-from form:

```js
export {default as Foo} from 'foo';
```

**Comment by Victorystick** [comment]
I see. What was the error? Can you include a stack trace?

I'm working on a possible solution in #71. Hang on.

**Comment by Swatinem** [comment]
I already submitted a failing test in #73 . A also use this pattern a lot…

**Comment by Rich-Harris** [comment]
I'll close this in favour of #73/#74, which ought to be fixed by #71/#78...
