### ISSUE TITLE
Use a stream as rollup input

### ISSUE THREAD

**Issue by Spy-Seth** [rollup/rollup#762]
I've look into the rollup codebase and the [rollup Javascript API](https://github.com/rollup/rollup/wiki/JavaScript-API) `rollup({ entry: 'src/js/main.js', ... })` do not support a node stream as input. 

Accepting stream could make easy to work with rollup in complex build process: we want to avoid read and write on the filesystem. Did you think it could be implemented? If yes I could git it a try.

I've seen seen the issue https://github.com/rollup/rollup/issues/508, I'm not talking about gulp/vinyl stream but native stream implementation (that implement [the node `Stream` interface](https://nodejs.org/api/stream.htm)).

**Comment by shouze** [comment]
Should be a cool feature indeed.

**Comment by Rich-Harris** [comment]
Rollup itself will almost certainly never support streams directly – there's no point – but it's easy to load modules from a stream instead of from the filesystem. Any plugins that return a `load` function will be tried before Rollup falls back to the filesystem, so you can do this sort of thing:

```js
// rollup.config.js
export default {
  entry: 'src/js/main.js',
  plugins: [ streams() ],
  // ...
};

function streams () {
  return {
    load ( id ) {
      return new Promise( ( fulfil, reject ) => {
        var stream = getStreamSomehow( id );
        var body = '';

        stream.on( 'data', chunk => body += chunk );
        stream.on( 'error', reject );
        stream.on( 'end', () => fulfil( body ) );
      });
    }
  };
}
```

**Comment by Spy-Seth** [comment]
Ok I like the idea to extract the stream data in the plugging. But I suppose the entry path `src/js/main.js` should exist (some plugging could use it)?

**Comment by eventualbuddha** [comment]
The main file doesn't have to exist if you use the options hook in your plugin. In fact, it doesn't have to be a string. See rollup-plugin-multi-entry for an example.

**Comment by Spy-Seth** [comment]
So with your help I succeed to use a stream. Not has entry point but it's works 😄  https://gist.github.com/Spy-Seth/f09120e6609c40a198f3bff56984a211

I will split and clean up this and it will be good. Thanks for you're help!

**Comment by eventualbuddha** [comment]
From your gist:

> TODO: Import the global babelrc configuration instead of duplicate it.

I created [babelrc-rollup](https://github.com/eventualbuddha/babelrc-rollup) for exactly this functionality.

**Comment by raphaelokon** [comment]
@Rich-Harris I would find this useful for piping into tests …

```bash
rollup --c config/rollup.config.test.js | tape-run
```
