### ISSUE TITLE
Treating relative paths as externals via resolveId does not work

### ISSUE THREAD

**Issue by kaste** [rollup/rollup#763]
Hi!

For a specific build I want to treat a (normal) (relative) import as an external resource. Given::

```
import {throttle} from './Lib/decorators'

throttle(/* function */)...
```

I want a build roughly as follows::

```
(function(Lib_decorators){ ... }(Lib.decorators))
```

I first tried `resolveId` with something maybe naive like `if (importee.endsWith('Lib/decorators')) return false` b/c you say that returning a "falsy value signals that importee should be treated as an external module and not included in the bundle" (https://github.com/rollup/rollup/wiki/Plugins).

But that doesn't work at all; it throws `Could not resolve...` and aborts. Reading the source code https://github.com/rollup/rollup/blob/master/src/Bundle.js#L228-L254 hints me that I have to use `options.external` which is otherwise not pluggable instead. But then rollup treats `'./Lib/decorators'` and `../Lib/decorators` (and so on) as different modules. Output::

```
(function (__Lib_decorators,___Lib_decorators) {
        'use strict';

}(__Lib_decorators,___Lib_decorators));
```

From my perspective the codepath I linked to is already too complex and just open for bugs.

The best workaround I found is letting `resolveId` return a name e.g. `Lib.decorators`, then treating this name as external via `options.external`, lastly rename the wrongly normalized name `Lib_decorators` back to `Lib.decorators` via `options.globals`::

```
const plugin = function() {
  return {
    resolveId(importee, importer) {
      if (importee.endsWith('Lib/decorators')) return 'Lib.decorators'
    }
  }
}

export default {
  format: 'iife',
  external: function(id) {
    if (id === 'Lib.decorators') return true
  },
  globals: function(id) {
    if (id === 'Lib.decorators') return 'Lib.decorators'
  },
  plugins: [ plugin() ]
}
```

**Comment by Rich-Harris** [comment]
You *should* be able to get this to work like so:

```js
// rollup.config.js
import { resolve } from 'path';

const resolved = resolve( 'Lib.decorators' );

export default {
  format: 'iife',
  external: [ resolved ],
  globals: function(id) {
    if (id === resolved) return 'Lib.decorators'
  }
};
```

In other words, if (having followed the normal resolution process) an ID matches an absolute path that's included in `external`, it gets treated as external, regardless of where it's imported from. Let us know if this works!

**Comment by kaste** [comment]
No that doesn't work. `globals` is called with the relative path. Also the `.js` extension must be appended. So this works: 

```
import {resolve} from 'path'

export default {
  format: 'iife',
  external: [
    resolve('Lib/index.js')
  ],
  globals: {
    './Lib/index.js': 'MyLib'
  }
}
```
But you use it like::

```
import {foo} from './Lib/index'
```

**Comment by Rich-Harris** [comment]
Yep, you found a bug 😀 As of the next release (shortly), `globals` will work with the resolved module ID rather than a relative one.

**Comment by Narretz** [comment]
Is it just me or does this totally break such imports:
(from the entry file)
`import services from './services'`
where services is a .ts file.

results in

> Could not resolve ./services from C:\Users\..\src\app.ts

**Comment by Rich-Harris** [comment]
@Narretz always use the file extension – `import services from './services.ts'`. In future we'll disallow extension-less imports. I don't know if that helps? Seems unrelated to this issue

**Comment by Narretz** [comment]
Ok, thanks.
This happened starting with version 0.34.0 and this issue seemed to be the most likely candidate for causing it. The other two mentioned in the CL are #755 and #756

**Comment by mebibou** [comment]
I'm trying to use the `globals` with relative path but I am confused on what is the solution now. I have
```
import { foo } from './lib/bar';
```
Trying the last solution provided here:
```
import {resolve} from 'path'

export default {
  format: 'iife',
  external: [
    resolve('lib/bar.js')
  ],
  globals: {
    './lib/bar.js': 'Bar'
  }
}
```
Still gives the error
```
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
```
I've tried many combination of relative/non-relative paths but always the same result.
Also on the official docs there is only an example for `jquery`, it would be nice to have one for relative paths as well

**Comment by lukastaegert** [comment]
Hi @mebibou,
this is how it works for me:

1. `external` compares imports exactly the way they are written. This means if `bar.js` is in one place imported as `./bar.js` and in another as `../bar.js`, then this is what your `external` option needs to look like:

```js
external: ['./bar.js', '../bar.js']
```

2. `globals`, on the other hand, resolves relative paths to absolute ones. This feels a little weird i.e. because the file in question is no part of the bundle, but the result is that in the above situation, both imports can be replaced with the same global. This is what worked for me (assuming `bar.js` resides in `./lib/bar.js`):

```js
import {resolve} from 'path';

export default {
  format: 'iife',
  external: ['./bar.js', '../bar.js'],
  globals: {
    [resolve(__dirname, 'lib/bar.js')]: 'Bar'
  }
}
```

**Comment by lukastaegert** [comment]
Ah, I retract my first point, using the absolute path for the `external` option works perfectly as well:

```js
import {resolve} from 'path';

const barId = resolve(__dirname, 'lib/bar.js');

export default {
  format: 'iife',
  external: [barId],
  globals: {
    [barId]: 'Bar'
  }
}
```

**Comment by lukastaegert** [comment]
Prepared a PR to update the docs, please have a look: rollup/rollupjs.org#151

**Comment by mebibou** [comment]
@lukastaegert yes thanks `resolve(__dirname, 'lib/bar.js');` worked, perfect
