### ISSUE TITLE
d3-scale tree shaking

### ISSUE THREAD

**Issue by davecranwell** [rollup/rollup#764]
I'm trying to write a standalone browser module which depends on code from a third party es6 lib, namely d3, specifically `d3-scale`.

So `d3-scale` is set as a dependency in my `package.json` and gets installed in `node_modules`. I want to include this third party code in my own when my own module gets bundled i.e I want there to be no external dependencies for my code to work.

I was previously doing `import scaleLinear from 'd3-scale'` at the top of my script but that gets ignored because it isn't local (beginning with a dot). I tried instead doing `import scaleLinear from '../node_modules/d3-scale/linear';` but now while scaleLinear is correctly included in my bundle none of _its own_ imports are. 

I can't very well rewrite the third party lib to use relative imports, and I don't want to import those deeper dependencies myself.

I feel like I'm missing something obvious here, or perhaps I've just misunderstood something vital.

**Comment by davecranwell** [comment]
To answer my own question: I need to be using https://github.com/rollup/rollup-plugin-node-resolve it seems. Annoying this seems to result in some genuinely dead code being added to my bundle.

**Comment by TrySound** [comment]
@davecranwell `nodeResolve({ jsmain: true })`

**Comment by eventualbuddha** [comment]
> Annoying this seems to result in some genuinely dead code being added to my bundle.

I completely agree. Unfortunately, I don't know of a way to statically analyze all the wierd forms of CommonJS out there. If you have suggestions on this score we'd be happy to hear them.

One suggestion I've seen is to look specifically for the structure that popular tools like babel (and rollup itself, perhaps), create.

**Comment by davecranwell** [comment]
I'm not sure that it's Rollup's fault at all, actually. 

My only use of `d3-scale` in my entire project, is just two calls to`scaleLinear.range(x,y)`. Unfortunately this is - through a dependency tree I don't have the patience to analyse - including all of https://github.com/d3/d3-scale/blob/master/src/viridis.js and all of https://github.com/d3/d3-color/blob/master/src/color.js (to name just two of many) despite my code never actually _using_ any of these vars or the functions that use them.

I thought it was Rollup's unique skill to identify this dead code, and it's certainly doing a good job elsewhere, but it just doesn't seem to be working here. I don't hold it against Rollup though. There's only so much introspection I can expect Rollup to perform!

**Comment by lukekentwell** [comment]
I am also having a problem with d3-** tree shaking, 
I am using `import { max, min } from 'd3-array';`

as a result in my bundle there is some dead code being added from the d3-array:

`function ascending(a, b) {
      return a < b ? -1 : a > b ? 1 : a >= b ? 0 : NaN;
    }

    function bisector(compare) {
      if (compare.length === 1) compare = ascendingComparator(compare);
      return {
        left: function(a, x, lo, hi) {
          if (lo == null) lo = 0;
          if (hi == null) hi = a.length;
          while (lo < hi) {
            var mid = lo + hi >>> 1;
            if (compare(a[mid], x) < 0) lo = mid + 1;
            else hi = mid;
          }
          return lo;
        },
        right: function(a, x, lo, hi) {
          if (lo == null) lo = 0;
          if (hi == null) hi = a.length;
          while (lo < hi) {
            var mid = lo + hi >>> 1;
            if (compare(a[mid], x) > 0) hi = mid;
            else lo = mid + 1;
          }
          return lo;
        }
      };
    }

    function ascendingComparator(f) {
      return function(d, x) {
        return ascending(f(d), x);
      };
    }

    var ascendingBisect = bisector(ascending);`

I dont ever use these, I am assuming because the var assignment is a function that's the start of the tree??

**Comment by Rich-Harris** [comment]
Reduced test case demonstrating the issue in the previous example: https://github.com/rollup/rollup/issues/1208. I'll close this in favour of that issue.
