### ISSUE TITLE
Warn on top-level `this`

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#770]
See https://github.com/rollup/rollup/issues/759#issuecomment-229643331

**Comment by timdp** [comment]
I like this feature but without context, it's a bit scary. Maybe it could also log `module.id`, `node.start`, `node.end`, etc.?

**Comment by dustindowell22** [comment]
I'm getting this warning when I'm importing certain modules from `lodash-es` could this be a false positive? `map`, `sortBy`, `filter`, `clone` are the ones triggering this for me in my project. Everything seems to be working fine though. Is this normal?

**Comment by jdalton** [comment]
From [lodash/_root](https://github.com/lodash/lodash/blob/4.13.1-npm/_root.js):
>
```js
/** Detect `this` as the global object. */
var thisGlobal = checkGlobal(typeof this == 'object' && this);
```

**Comment by AgronKabashi** [comment]
I'm receiving a lot of these warnings (~20-30 times) when importing Angular 2 packages. I could suppress these messages by supplying the rollup config with my own `onwarn`callback but would that be considered good practice?

**Comment by TrySound** [comment]
@AgronKabashi There's `context` option.

**Comment by code-tree** [comment]
@TrySound Could you please elaborate in the case of Angular2, as I don't yet fully understand what's going on.

Is Angular2 doing something wrong here? If I set `context: 'window'` is the problem solved?

(`ngc` is generating the code that causes this warning, so I don't know what is going on under the hood)

**Comment by AgronKabashi** [comment]
@code-tree Yes, setting context: 'window' or context: 'this' will hide those messages.
