### ISSUE TITLE
`this` from an imported UMD module converted to `undefined`

### ISSUE THREAD

**Issue by mattzuba** [rollup/rollup#771]
First off, I apologize if this is the wrong project to file this issue, but I'm not quite sure if it's a bug in rollup, or an issue with the UMD definition in the other project, so I'm starting here.

I'm attempting to use [URI.js](https://github.com/medialize/URI.js) in a project which is defined via UMD.  It seems that URI.js is using `this`, rather than `window` or [some other method to determine the global object](https://github.com/rollup/rollup/issues/759#issuecomment-229643331).

Is this a bug in rollup where it should be handling `this` as it imports non-ES6 modules, or is this a design flaw in URI.js that should be addressed there to make it bundleable?

I haven't tested this with other bundlers so I'm not sure how others handle it.

**Comment by Rich-Harris** [comment]
Are you using rollup-plugin-commonjs to import the UMD module? I suspect we need to update that plugin so that top-level `this` is treated the same as `global` – that *should* fix it.

**Comment by mattzuba** [comment]
I am indeed using the commonjs plugin.

On Thu, Jul 7, 2016, 5:38 AM Rich Harris <notifications@github.com> wrote:

> Are you using rollup-plugin-commonjs to import the UMD module? I suspect
> we need to update that plugin so that top-level this is treated the same
> as global – that *should* fix it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rollup/rollup/issues/771#issuecomment-231065433>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABbOuST1Zryd15Y6aLuM2dy9_WYJUaD7ks5qTPNNgaJpZM4JGxYK>
> .
>
-- 

Thanks,
Matt Zuba
Sent from my mobile telecommunication device, please excuse any tpyos.

**Comment by mattzuba** [comment]
I fear this may be an issue on my part and this issue can be closed (and if there is a bug based on my explanation below, I can open it against the plugin repo).  It seems I was improperly using the commonjs plugin and a few tweaks to it's options is making it work properly.

Originally my plugin init looked like `commonjs({include: 'app/js'})`.  Using this config, `this` was transformed into `undefined` in the URI.js module.  When I remove the include config option, `this` is transformed into `commonjsGlobal` as desired.  Optionally, if I use the ignoreGlobal option, `this` remains as is and doesn't change.  Either of the latter two options fit my bill.  Though I'm not sure if including the the include option is supposed to have that side effect.

**Comment by Rich-Harris** [comment]
The `include` option should be a glob – so to run all the files in `app/js` through the plugin, you'd use `app/js/**`. *Not* including the `include` option is equivalent to 'include everything', which is presumably by removing it fixed the problem. The reason `ignoreGlobal` has that effect is that once URI.js is wrapped by rollup-plugin-commonjs, the `this` is no longer at the top level by the time Rollup itself sees it.

So I'll close this, it looks like everything is working as expected – but shout if not!

**Comment by mattzuba** [comment]
Thanks for the explanation!  That makes a lot of sense now and I'd agree, everything seems to be working as it should.  Thanks again for your help and for a great tool!
