### ISSUE TITLE
"filepath" does not exist in the hypothetical file system!

### ISSUE THREAD

**Issue by rogervila** [rollup/rollup#772]
Hello, I have made a little app in order to test rollup with babel, but I can't import modules. 

I get this message: `"filepath" does not exist in the hypothetical file system!` **but "filepath" does exist**.

This is my `gulpfile.js`

```js
let gulp = require('gulp'),
	runSequence = require('run-sequence'),
	rollup = require('gulp-rollup'),
	rollupIncludePaths = require('rollup-plugin-includepaths'),
	babel = require('rollup-plugin-babel');

gulp.task('default', () => {

	const includePathOptions = {  
		paths: ['src']
	};

	return gulp.src('src/app.js')
		.pipe(rollup({
			entry: './src/app.js',
			sourceMap: 'inline',
			plugins: [
				rollupIncludePaths(includePathOptions),
				babel({
					presets: ['es2015-rollup'],
					babelrc: false
				})
			],
			format: 'umd',
			moduleName: 'testing'
		}))
		.pipe(gulp.dest('dist'));
});
```

What am I missing?

Thank you.

**Comment by TrySound** [comment]
@rogervila Something wrong in implicitly added plugin to process streams. Use rollup directly without any wrappers. Just return rollup promise like here https://github.com/rollup/rollup/wiki/Build-tools.

**Comment by Rich-Harris** [comment]
I'd second @TrySound's remarks – Gulp adds an extra layer of complexity and makes it hard to debug problems. Have you tried raising an issue with gulp-rollup?

**Comment by rogervila** [comment]
@Rich-Harris @TrySound Hello, the idea is to manage all the assets of the project with just running a `gulp` command, this is why we don't use rollup-cli.

I have referenced the issue in gulp-rollup, let's see if they know what happens.

**Comment by TrySound** [comment]
@rogervila We don't suggest you to use rollup-cli. You can use rollup API directly in gulp task as I mentioned in [this example](https://github.com/rollup/rollup/wiki/Build-tools).

**Comment by rogervila** [comment]
I Solved it!

**I had to add [this attribute](https://www.npmjs.com/package/rollup-plugin-hypothetical#optionsallowrealfiles) from `rollup-plugin-hypothetical` into the `.pipe(rollup())` function** (They should add this on the docs).

You are right, Gulp adds an extra layer of complexity and makes it hard to debug problems.
Thank you very much @TrySound for the example, I will implement it in order to avoid gulp plugins.

This is the current file.

```js
let gulp = require('gulp'),
	runSequence = require('run-sequence'),
	rollup = require('gulp-rollup'),
	babel = require('rollup-plugin-babel'),
	uglify = require('gulp-uglify'),
	sourcemaps = require('gulp-sourcemaps');

	
	gulp.task('default', () => {

		return gulp.src('src/app.js')
			.pipe(sourcemaps.init())
			.pipe(rollup({
				allowRealFiles: true, // !IMPORTANT, it avoids the hypothetical file system error
				entry: './src/app.js',
				plugins: [
					babel({
						presets: ['es2015-rollup'],
						babelrc: false
					})
				],
				format: 'umd',
				moduleName: 'testing'
			}))
			.pipe(uglify())
			.pipe(sourcemaps.write())
			.pipe(gulp.dest('dist'));
	});
```

**Comment by Permutatrix** [comment]
[That usage of gulp-rollup is strongly discouraged.](https://github.com/mcasimir/gulp-rollup/issues/38#issuecomment-231350537) Just want to make sure there's a link to that here so people don't stumble across this issue and get the wrong idea.

**Comment by btipling** [comment]
To anyone reading this the correct solution is to fix the gulp source paths used for the gulp rollup task so that it includes the file it says it's missing. 

**Do not use `allowRealFiles: true`.** 

This issue has nothing to do with rollup and stems from incorrect usage of gulp.
