### ISSUE TITLE
Better way of working with Rollup and browser ES6 scripts

### ISSUE THREAD

**Issue by YuryStrozhevsky** [rollup/rollup#776]
I would like to use Rollup making a "browser scripts". I mean that your tool would produce a scripts which will be used by HTML page (from script tag). Yes, it would be HTML pages using pure ES6 code, with no transpilation.

I can produce pure ES6 files with "format = es". But after that I have a "little" problem: in such "browser scripts" there are functions which would be used from UI elements and thus I have no direct calls to such functions. And thus Rollup just removed all "unnecessary" function bodies.

I can make a hacks with additional scripts, but is there any better way to configure Rollup to "fix" particular function in result code?

**Comment by TrySound** [comment]
@YuryStrozhevsky You are able to export functions which you want to be used outside of the bundle. Look at [this example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20There%20are%20many%20ways%20to%20export%20bindings%5Cn%2F%2F%20from%20an%20ES2015%20module%5Cnexport%20var%20foo%20%3D%201%3B%5Cn%5Cnexport%20function%20bar%20()%20%7B%5Cn%5Ctreturn%20foo%3B%20%2F%2F%20try%20changing%20this%20to%20%60foo%2B%2B%60%5Cn%7D%5Cn%5Cnfunction%20baz%20()%20%7B%5Cn%5Ctreturn%20bar()%3B%5Cn%7D%5Cn%5Cnexport%20%7B%20baz%20%7D%3B%5Cnexport%20*%20from%20'.%2Fqux'%3B%22%7D%2C%7B%22name%22%3A%22qux.js%22%2C%22code%22%3A%22export%20var%20qux%20%3D%20'QUX'%3B%22%7D%5D%7D). Also you need to use `iife` format, cas `es` is not supported yet. `es` do not transpiles your es6 code, just outputs modules format.

**Comment by YuryStrozhevsky** [comment]
Is it possible to export functions directly to "window" class? I mean is it possible to put "window" as "options.moduleName"?

**Comment by TrySound** [comment]
@YuryStrozhevsky Nope. But you can assign something to `window` property and it won't be tree shaked.

**Comment by YuryStrozhevsky** [comment]
@TrySound Thanks for the quick answers!
