### ISSUE TITLE
May i disable tree-shaking?

### ISSUE THREAD

**Issue by pabdon** [rollup/rollup#784]
Is it possible to inhibit the tree-shaking for a given function? Or how can I force an import is in the bundle even if it is not used. I am creating elements in the DOM and assigning methods imported from another module to some events. I am using a tagged template function and so these methods will only be executed when the page loads and the event is triggered.

**Comment by Rich-Harris** [comment]
Can you elaborate a bit? Anything that is `export`ed from your entry module, or that has side-effects, will be preserved – the only stuff that should be treeshaken is stuff that's genuinely not being used.

It *is* possible to disable treeshaking (with `treehake: false` – [docs](https://github.com/rollup/rollup/wiki/JavaScript-API#treeshake)), but it's a last resort intended to work around any bugs that crop up.

**Comment by pabdon** [comment]
I think that whenever we have a method in a string that will be evaluated at run time (html, Function, Eval) the tree-shaking does not have to consider as a necessary method in the bundle. For example:

`<Input  autofocus  onblur =" htmlRemove (this) " type =" text " id =" sample1 ">`

Then I realized that just mention the method in the importing module to solve the problem:

`methods: {htmlRemove, otherMethod}`

Thank you and I think that this issue can be closed!

**Comment by Victorystick** [comment]
Great! Good luck with your project! Let us know if you run into any other issues.
