### ISSUE TITLE
Cannot use external modules that do not expose in default

### ISSUE THREAD

**Issue by d3x7r0** [rollup/rollup#790]
I was just upgrading my version of rollup and hit a brick wall with some new behaviour.

Apparently rollup now errors out when you try to directly call the resulting namespace. 

Previous I used:

``` javascript
import * from Promise from 'bluebird';

let a = new Promise(resolve => ...);
```

Sadly I cannot seem to work around the issue by doing:

``` javascript
import Promise from 'bluebird';

let a = new Promise(resolve => ...);
```

since that results in something like:

``` javascript
Promise$1__default = Promise$1['default'];
```

instead of the former behaviour:

``` javascript
Promise$1 = 'default' in Promise$1 ? Promise$1['default'] : Promise$1;
```

[Here's the issue](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22umd%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%22bluebird%22%3A%22bluebird%22%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20*%20as%20Promise%20from%20%27bluebird%27%3B%5Cn%5Cnlet%20a%20%3D%20Promise.resolve%28%29%3B%5Cn%5Cnlet%20b%20%22%7D%5D%7D)

Maybe I'm missing something but I don't seem to find a way to work around this new behavior and continue using older libraries that are unaware of the need to export to default.

**Comment by TrySound** [comment]
@d3x7r0 The problem is that bluebird is commonjs lib. Rollup works only with es-modules. To load commonjs you should use plugin converter https://github.com/rollup/rollup-plugin-commonjs.

**Comment by d3x7r0** [comment]
@TrySound This was actually for a library that we plan to re-use on several other projects so I was avoiding bundling in bluebird.

**Comment by Rich-Harris** [comment]
Apologies for the non-response. This seems to be [working](http://rollupjs.org/?version=0.39.2&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnVtZCUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlMjJibHVlYmlyZCUyMiUzQSUyMmJsdWViaXJkJTIyJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwUHJvbWlzZSUyMGZyb20lMjAnYmx1ZWJpcmQnJTNCJTVDbiU1Q25sZXQlMjByZXNvbHZlZCUyMCUzRCUyMFByb21pc2UucmVzb2x2ZSgpJTNCJTVDbiU1Q25sZXQlMjBwcm9taXNlJTIwJTNEJTIwbmV3JTIwUHJvbWlzZSglMjAoJTIwZnVsZmlsJTJDJTIwcmVqZWN0JTIwKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0c2V0VGltZW91dCglMjBmdWxmaWwlMkMlMjA1MDAwJTIwKSUzQiU1Q24lN0QpJTNCJTIyJTdEJTVEJTdE) in current versions, as it's checking for the existence of `default`. Can this issue be closed? Thanks

**Comment by d3x7r0** [comment]
We had to stop using rollup in that particular project because of this issue, maybe we can re-evaluate that decision but it looks like it's working now. 👍
