### ISSUE TITLE
Cannot export * from external module.

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#791]
Say I’ve npm install’d d3-array and d3-color, and now I have an index.js (an entry file) that looks like this:

``` js
export * from "d3-array";
export * from "d3-color";
```

When running rollup, I get the following error:

```
$ node_modules/.bin/rollup -f cjs index.js 
Treating 'd3-array' as external dependency
Treating 'd3-color' as external dependency
module.getExports is not a function
TypeError: module.getExports is not a function
    at /Users/mbostock/Development/d3/node_modules/rollup/src/Module.js:288:11
    at Array.forEach (native)
    at Module.getExports (/Users/mbostock/Development/d3/node_modules/rollup/src/Module.js:287:25)
    at /Users/mbostock/Development/d3/node_modules/rollup/src/Bundle.js:107:17
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

However, if I resolve it so that it’s not an external dependency, like so:

``` js
export * from "./node_modules/d3-array/index";
export * from "./node_modules/d3-color/index";
```

It works, except now the code gets inlined, rather than require’d. So I end up needing to do this:

``` js
export {
  bisect,
  bisectRight,
  bisectLeft,
  ascending,
  bisector,
  descending,
  deviation,
  extent,
  histogram,
  thresholdFreedmanDiaconis,
  thresholdScott,
  thresholdSturges,
  max,
  mean,
  median,
  merge,
  min,
  pairs,
  permute,
  quantile,
  range,
  scan,
  shuffle,
  sum,
  ticks,
  tickStep,
  transpose,
  variance,
  zip
} from "d3-array";

export {
  color,
  rgb,
  hsl,
  lab,
  hcl,
  cubehelix
} from "d3-color";
```

Should `export * from "d3-color"` work? Or am I doing something wrong? Let me know if you want an isolated repo to reproduce this issue. Thank you!!

**Comment by TrySound** [comment]
@mbostock `export *` should gets somewhere information what exactly it need to export. It's the restriction for now.

@Rich-Harris If such deps are not resolved we can convert it to `export * as module from 'module';` and then assign to `exports` in `cjs`. For `es` we can just leave it untouched.

**Comment by TrySound** [comment]
@mbostock Now `export *` can be used only internally like here https://github.com/rollup/rollup/blob/master/src/utils/path.js
https://github.com/rollup/rollup/commit/1e98a69e2ec80bd4f99ae363f96a04d9752464f0
