### ISSUE TITLE
import of Buble throws errors

### ISSUE THREAD

**Issue by Kflash** [rollup/rollup#793]
Not sure if this is an Buble or Rollup issue, but I tried to import Buble and ended up with various vague messages.  

Just to make it clear. 

In the `rollup-plugin-buble` plugin `buble` are imported like this:

`import { transform } from 'buble';`

so when I tried that, and also this 

`import buble from 'buble';`

I ended up with this messages / errors

```js
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
```
No idea where this 'this' keyword are coming from, but maybe related to this error message:

```js
Module node_modules\acorn\dist\acorn.js does not export default (imported by \node_modules\buble\dist\buble.es.js)
```
So the only possible solution is to use the commonjs plugin, but I don't need 3422 extra lines of code in my  bundle when the source code itself is around 43 lines.

Any solution?

**Comment by Kflash** [comment]
@TrySound  any solution on this issue?

**Comment by TrySound** [comment]
@Kflash Give me minimal code example please.

**Comment by Kflash** [comment]
Use TypeScript and do this with buble as dependency;

`import buble from `buble`

Try to compile the code with tsc. It will throw.

Don't use rollup ts plugin. That plugin swallows the errors.

You also get the same error in vscode without compiling.

On Aug 2, 2016 2:58 PM, "Bogdan Chadkin" <notifications@github.com> wrote:

@Kflash <https://github.com/Kflash> Give me minimal code example please.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rollup/rollup/issues/793#issuecomment-236817948>, or mute
the thread

**Comment by Kflash** [comment]
@TrySound Did you find a solution on this issue? I still can't import Buble as ES module.

**Comment by TrySound** [comment]
@Kflash Did you try commonjs plugin?

**Comment by Kflash** [comment]
@TrySound I did. But it gave me 3422 extra lines of code. And I saw that Buble supports ES modules, so I thought it should work.

**Comment by TrySound** [comment]
Hm.. weird. there should be `dist/acorn.es.js`.

**Comment by Kflash** [comment]
```js
Module node_modules\acorn\dist\acorn.js does not export default (imported by \node_modules\buble\dist\buble.es.js)
```

**Comment by TrySound** [comment]
I saw.

**Comment by TrySound** [comment]
I found. Acorn added jsnext since one if the latest versions. Try to clean npm cache or just run npm update or install acorn3.3

**Comment by Kflash** [comment]
I think there is issues with Acorn dependencies.

```js
npm i @3.3.0 // from CLI

// output
+-- acorn@3.3.0
  +-- acorn@2.7.0
  `-- acorn-globals@1.0.9
    `-- acorn@2.7.0
```
In my end I'm using acorn@2.7.0 because the newest is overwritten

**Comment by Kflash** [comment]
This get weird. I quick look at this link: https://github.com/ForbesLindesay/acorn-globals/blob/master/package.json#L20

 acorn@3.1.0 is the dependency. And the last to be installed.

**Comment by TrySound** [comment]
Heh. The problem with npm :)

**Comment by TrySound** [comment]
Acorn3.3 doesn't have any dependencies.
