### ISSUE TITLE
'this' issues with ES6 class

### ISSUE THREAD

**Issue by ghost** [rollup/rollup#794]
Seems like I randomly get this error message 

`The`this`keyword is equivalent to`undefined`at the top level of an ES module, and has been rewritten`

without any reason? Spent some time debugging it, but can't say for sure why it got triggered. Most of the time I get it when I do this (_bad example_):

``` js
class A {}
class B extends A {
constructor() { super(); }
}
```

It can be reproduced if you do

``` js
import { EventEmitter } from 'events'; // also import * as E from 'events' fails

class A extends EventEmitter {
constructor() { super(); }
}
```

In the last example you also get some other random errors if you compile. E.g. domain() doesn't exist or is deprecated or isn't existing etc.

**Comment by Kflash** [comment]
Ran into new issues regarding this. Simple class like this:

```js
// outside of this Class I have a each function

class Foo {
this.container = [];
constructor() {...}
execute (callback: Function): void {

// NOTE! use of 'this' here throws this:  the "this" keyword is disallowed outside of a class body
each(this.container, callback);
}
}
```
I can't figure out how it can be outside the class body? It's inside it!

**Comment by TrySound** [comment]
@Kflash What is the result of typescript before rollup?

**Comment by Kflash** [comment]
@TrySound I updated the prev message. The TypeScript message is fixed, but not the issue that Rollup rename to undefined message. When I look at the source code. Nothing is set to undefined...

**Comment by TrySound** [comment]
Use or not, what rollup gets from you? Can you post that compiled code, not your ts sources?

**Comment by TrySound** [comment]
And I'm not sure `this.container = [];` is correct.

**Comment by Kflash** [comment]
Rollup output: `Thethiskeyword is equivalent toundefinedat the top level of an ES module, and has been rewritten`

You are right this.container = []; is wrong. A typo when I quickly tried to write it into JS code.
Updated the example code.

**Comment by TrySound** [comment]
@Kflash Did you try to disable tree shaking?

**Comment by Kflash** [comment]
nope.

**Comment by krze-han** [comment]
Is there a way to suppress this warning? I'm working on an angular 2 / typescript project and I'm receiving over  100 of these warnings.  This makes it very difficult to see actual errors, especially when all the warnings rolls-over the standard output.

**Comment by krze-han** [comment]
import rollup      from 'rollup';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify';

export default {
    entry: 'ng2-App/Bootstrapper/Components/main-aot.js',
    dest: 'tmp/aot/build.js', // output a single application bundle
    sourceMap: false,
    format: 'iife',
    onwarn: function (message) {
        // Suppress this error message... there are hundreds of them. Angular team says to ignore it.
        // https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
        if (/The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten./.test(message)) {
            return;
        }
        console.error(message);
    },
    plugins: [
        nodeResolve({
            jsnext: true,
            module: true,
            main: true,  // for commonjs modules that have an index.js
            browser: true
        }),
        commonjs({
            include: 
                'node_modules/**',
            }
        }),
        uglify()
    ]
};

**Comment by TristanVALCKE** [comment]
@krze-han Please use code tag ! the button look like: **<>**

**Comment by laurence-myers** [comment]
The actual generated code that causes the problem is a function "__extends()", seemingly created by TypeScript to apply traditional OO inheritance.

`var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};`

It checks if "this" exists, then if "__extends" has been defined, and uses that. Otherwise it defines its own implementation. I guess Rollup is being too helpful in checking for use of "this" at the top level; maybe it shouldn't emit a warning if "this" is first checked for existence/undefined.

@krze-han this solution with the "onwarn" setting works for me, thanks! 👍

**Comment by Rich-Harris** [comment]
As of 0.39, warnings are objects with a `code` property, meaning the custom `onwarn` function will need to be slightly different:

``` diff
export default {
    entry: 'ng2-App/Bootstrapper/Components/main-aot.js',
    dest: 'tmp/aot/build.js', // output a single application bundle
    sourceMap: false,
    format: 'iife',
-    onwarn: function (message) {
+    onwarn: function (warning) {
        // Suppress this error message... there are hundreds of them. Angular team says to ignore it.
        // https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
-        if (/The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten./.test(message)) {
+        if (warning.code === 'THIS_IS_UNDEFINED')
            return;
        }
-        console.error(message);
+        console.error(warning.message);
    },
```
