### ISSUE TITLE
Feature: Import folder of JavaScript pages.

### ISSUE THREAD

**Issue by halfnibble** [rollup/rollup#798]
## Feature Request
My understanding is that es6 doesn't specify _exactly_ how module importing should work.

Since we can already import all the modules of a single page using:
`import 'pages';`

I suggest adding a feature to import all the modules of folder, with the following syntax:
`import 'pages/*';`

Thanks for the excellent tool.

**Comment by eventualbuddha** [comment]
This can be implemented using a plugin. Check out https://github.com/rollup/rollup/wiki/Plugins for a list of plugins which can serve as examples. Feel free to comment again here or on [Gitter](https://gitter.im/rollup/rollup?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) with questions. Let us know when you've got something to share on the wiki!
