### ISSUE TITLE
Option to preserve comments above the import statements

### ISSUE THREAD

**Issue by rberner** [rollup/rollup#801]
I would like to be able to keep any comments that I write at the top of my files, even after they are bundled. For example:

```
//file a
import {b} from './b'
alert('b is equal to ' + b);
```

```
//file b
// Here is my special comment i want to keep
export const b = 10;
```

Bundling these would produce the following:

```
//file a
const b = 10;
alert('b is equal to ' + b);
```

My comments at the top of file b are removed though. I would like rollup to produce this file instead:

```
//file a
//file b
// Here is my special comment i want to keep
const b = 10;
alert('b is equal to ' + b);
```

**Comment by horosgrisa** [comment]
@Rich-Harris  What you think about this?

**Comment by ksvitkovsky** [comment]
@rberner checked at current version, is that the expected result?

![2017-06-15 21 19 04](https://user-images.githubusercontent.com/15626295/27193606-802e8008-5210-11e7-842b-382e46963a40.png)

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by insertmike** [comment]
@shellscape I would request a re-open. Rollup can expose a violation of licenses when they are at the top of the file.

**Comment by lukastaegert** [comment]
For that reason, the first comment in every file that is not tree-shaken is retained: https://rollupjs.org/repl/?version=2.59.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRoaXMlMjBpcyUyMGElMjBsaWNlbnNlJTIwY29tbWVudCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGlzJTIwc29tZXRoaW5nJTIwZWxzZSU1Q25pbXBvcnQlMjAnLiUyRmRlcC5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKCdtYWluJyklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJkZXAuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJ2RlcCcpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=
