### ISSUE TITLE
Rollup + Vuejs - the right way?

### ISSUE THREAD

**Issue by lukasjuhas** [rollup/rollup#805]
Hey

Anyone tried using rollup with vue? I found #464 - but I think I have slightly different issue. Basically when I try to pull in Vue, and initialise it I get following message:

`Uncaught ReferenceError: process is not defined(anonymous function) @ vue.common.js:944`

I assume it has something to do with my setup, so here it is:

```
gulp.task('scripts', ['clean-scripts'], () => {
  rollup({
    // BUG: https://github.com/rollup/rollup-plugin-node-resolve/issues/43
    entry: 'resources/assets/scripts/app.js',
    plugins: [
      nodeResolve({
        jsnext: true,
      }),
      commonjs(),
      vue(),
      babel({
        babelrc: false, // rollup needs it's own preset.
        presets: ['es2015-rollup'],
        exclude: 'node_modules/**',
      }),
    ],
  }).then(bundle => {
    bundle.write({
      format: 'iife',
      sourceMap: gulpif(!production, true, false),
      dest: `${config.public}/scripts/scripts.min.js`,
    });
  }).catch(err => console.log(err.stack));
});
```

Any ideas?

Thank you!

Lukas

**Comment by NicolasParada** [comment]
```js
import replace from 'rollup-plugin-replace'

/*...*/
rollup({
  /*...*/
  plugins: [
    replace: {
      'process.env.NODE_ENV': JSON.stringify('development'),
      'process.env.VUE_ENV': JSON.stringify('browser')
    }
  ],
  /*...*/
})
```

**Comment by lukasjuhas** [comment]
Thanks @NicolasParada !!

That worked perfectly.

Cheers.

**Comment by jonaskuske** [comment]
For anyone getting here in the future, you don't need the replace plugin anymore!

Simply import **`'vue/dist/vue.esm.browser'`** and you'll get a Vue version that does not reference `process` (because its meant to run in the browser) but still is a proper module and does not expose itself globally on `window`.  ✌🏻

**Comment by viT-1** [comment]
@jonaskuske Your solution is ok only for "ES6 ready" browsers with support of `<script type="module">`

**Comment by kudorgyozo** [comment]
> ```js
> import replace from 'rollup-plugin-replace'
> 
> /*...*/
> rollup({
>   /*...*/
>   plugins: [
>     replace: {
>       'process.env.NODE_ENV': JSON.stringify('development'),
>       'process.env.VUE_ENV': JSON.stringify('browser')
>     }
>   ],
>   /*...*/
> })
> ```



> ```js
>       'process.env.NODE_ENV': JSON.stringify('development'),
>       'process.env.VUE_ENV': JSON.stringify('browser')
> ```

where do you put this in the list of plugins

**Comment by Flamenco** [comment]
Another option i used to use was to create a file called vue-env.js and include it before the first vue import.

vue-env.js
```
if (!('process' in window)) {
  // @ts-ignore
  window.process = {
    env: {
      NODE_ENV: 'production'
    }
  }
}
```
