### ISSUE TITLE
Proposal: plugins 'state'

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#806]
- state should be common between per file plugins
- It should be a plain object to be cachable
- ongenerate method gets map of states

This will let to use typescript and css-module in more flexible way.

``` js
{
  resolveId(importer, importee, state) {},
  load(id, state) {},
  transform(code, id, state) {},
  ongenerate(bundle, rendered) {
    const states = bundle.modules.map(module => module.state);
    console.log(states);
  }
}
```

**Comment by TrySound** [comment]
New hooks `buildstart` and `buildend`.

In context `css-modules`

`buildstart(states:Array<Object>)` will invalidate every item and create empty array

`transform(code, id, state:Object)` will validate existing items or compile new.

`buildend(states:Array<Object>)` will filter valid items and write on disk.

`buildend` can be placed after all transformations but before generating, so can be async and accept promise.

**Comment by tivac** [comment]
```js
export default function(opts) {
    var processor = new Processor();
    
    return {
        buildstart : (state) => {
            state.seen = [];
        },
        
        transform : (code, id, state) => {
            state.seen.push(id);
            
            return processor.add(id, code);
        },
        
        buildend : (state) => {
            state.seen.forEach(processor.remove);
        },

        ongenerate : (bundle, result) => {
            result.css = processor.output();
        },

        onwrite : (bundle, result) => {
            result.css.then((css) => css.writeToDisk());
        }
    };
};
```

Is a pseudocode version of what I think you're proposing, but I'm not feeling terribly sure about my interpretation. Is this correct?

Assuming it is correct, I don't yet see how building it like this would solve my [remaining rollup problem](https://github.com/tivac/modular-css/issues/158). Based on my current understanding I think my plugin needs to know that a file has been modified **before** the `transform` step is run so any new output/dependencies are reflected in the the bundle.

**Comment by snuggs** [comment]
A humble refactor @tivac :-) Or one of my favorite features, Object property function declarations. Trying to ramp up on this project myself.

``` javascript
export default function(opts) {
    let processor = new Processor();

    return {
        buildstart(state) {
            state.seen = [];
        },

        transform(code, id, state) {
            state.seen.push(id);

            return processor.add(id, code);
        },

        buildend(state) {
            state.seen.forEach(processor.remove);
        },

        ongenerate(bundle, result) {
            result.css = processor.output();
        },

        onwrite(bundle, result) {
            result.css.then((css) => css.writeToDisk());
        }
    };
};
```

@tivac I believe `onbuildend()` would also provide the hook you mentioned in a previous issue yes?

**Comment by snuggs** [comment]
Also @TrySound `buildstart()` and `buildend()` should perhaps take a collection of `seen`s in? Seems like the two `func`s know a bit too much about the state.

```javascript
{
  buildstart(states) { // should have no side effects
     states = [];
    // Seen states should be  initialized outside of the scope of this operation
    // this tightly couples the state to this object.
    // states merely need to be injected into transform(), & buildend()
  },

    // also state.seen.push << this scope knows too much about the state object.
    // whether the states are "seen" is irrelevant and should be passed in wholely.
    // Method signature should change state to plural
  transform(code, id, states) {
    // since the operations push & add are done in sync
    // this makes processor the state machine. state is merely a shadow at this point.
    // rule of thumb "If things change at the same time they should be in the same place.
    // Not smelly but a bit pungent.

    states.push(id);

     return processor.add(id, code); // is the processor returned or the added transform? Just to be clear.
  },

// buildstart / buildend need not know about states only transform
  buildend(states) {
    states.forEach(processor.remove);
    // AH I get it now. state has feature envy of the processor. 

    // https://sourcemaking.com/refactoring/smells/feature-envy

    // perhaps .addTransform(id, code), .removeTransforms() is a better API for the Processor.
  }
}
```

/cc @tivac

**Comment by tivac** [comment]
@snuggs fwiw the `processor` bits are specific to my `modular-css` project, I was just trying to make sure I understood what @TrySound was proposing. I'm still not 100% sure I grok the proposed implementation yet though.

Yes, `buildend` would solve my issue in #372 where there's no hook for plugins before `ongenerate` atm, so there's no ability to modify the `Bundle` instance before output is generated.

**Comment by snuggs** [comment]
I like where this is going. Just thinking out loud myself. I'm a really good programmer but fresh on this tool. Following in your footsteps @tivac

**Comment by tivac** [comment]
@TrySound @Rich-Harris any progress on this? `modular-css` still suffers from not knowing when files have been changed out from underneath it using `rollup-watch`.

**Comment by guybedford** [comment]
Note `buildStart` and `buildEnd` are now supported, where adding to `this` of the plugin context can be relied on for storing build-specific state (although we're not currently encouraging this I believe it will work).
