### ISSUE TITLE
Improve bundle reuse/cache for unchanged imports

### ISSUE THREAD

**Issue by skeggse** [rollup/rollup#808]
If I change a file, but don't modify the imports, I'd like rollup to avoid rebuilding all the imported modules as well. I realize this might not always be possible, but it would speed up builds, which even when aggressively cached take half a minute.

**EDIT**: I may be misinformed - it looks like this should already be happening.

**Comment by TrySound** [comment]
@skeggse Yep. We already introduced `cache` option and trying now to improve some things. Ref https://github.com/rollup/rollup/issues/723
