### ISSUE TITLE
Update wiki mention about jsnext and module

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#818]
https://github.com/rollup/rollup/wiki/jsnext:main
https://github.com/rollup/rollup-plugin-node-resolve/commit/3befb3ba9856a375881708258e39c7c7a7d63e86

**Comment by tnga** [comment]
considering this https://github.com/nodejs/node/wiki/ES6-Module-Detection-in-Node#option-4a-single-module-entry-point-rejected

**Comment by tivac** [comment]
@tnga But that page is outdated and links to a page which specifically says "node will use `module` in package.json".

![image](https://cloud.githubusercontent.com/assets/49545/17385529/2500b604-5998-11e6-8cef-1e7871fadea6.png)

Here's the updated doc: https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md
