### ISSUE TITLE
Remove depots to increase stability 

### ISSUE THREAD

**Issue by ghost** [rollup/rollup#819]
There are various deopts in the source code. Affected browser is mostly chrome.  
Just to mention one obvioius. `for in  ` statements gives a deopt.  Workaround is to use `object.keys`

**Comment by Kflash** [comment]
This  mentioned deopt and others is something I discovered after working on the Inferno library. There are also possible to increase Rollup performance with around 7%

**Comment by TrySound** [comment]
PR welcome

**Comment by TimothyGu** [comment]
> `for in` statements gives a deopt. Workaround is to use `object.keys`

Despite deopts etc., `for-in` is still faster though. Check http://jsbench.github.io/#5905cad9488ab4d470ad7a5818aebc2f.
