### ISSUE TITLE
ES7 module syntax

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#82]
Via https://github.com/esperantojs/esperanto/issues/123. Currently at stage 1: https://github.com/leebyron/ecmascript-more-export-from. Probably worth considering if/when it reaches stage 2, once Acorn (or another ESTree-generating parser) handles it.

**Comment by Victorystick** [comment]
Agreed. This would be a great addition.

**Comment by snuggs** [comment]
I believe we can close this issue now @Rich-Harris @Victorystick

**Comment by Rich-Harris** [comment]
yeah, we can reopen if it ever gets beyond stage 2

**Comment by 2beers** [comment]
Sorry for opening this , but I came here from mozilla doc site https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

> "This feature is not implemented in any browsers natively at this time. It is implemented in many transpilers, such as the Traceur Compiler, Babel or Rollup."

Maybe someone should tell Mozilla to remove Rollup from list to avoid confusions.

**Comment by Rich-Harris** [comment]
Didn't realise it had advanced, nice. Reopening
