### ISSUE TITLE
Tree shaker too aggressive with successive 'var' statements

### ISSUE THREAD

**Issue by paul-go** [rollup/rollup#820]
Examine the following case:

```
// main.js
import { func } from './func.js';

// func.js
export function func ( ) {
}

export var func;
```

The compiled output is:
```
'use strict';

var func;

func();
```

However, this is incorrect because a `var` statement without an assignment, defining a pre-existing identifier is essentially a no-op. The correct behavior should shake the successive null var statements, but leave in the function definition.

This is concrete problem because when using TypeScript's module merging feature (i.e. merging a function with a module), a `var` statement is emitted before the module which causes the preceding function to be shaken off.

**Comment by TimothyGu** [comment]
Your `func.js` doesn't work in Babel either, which returns the following:

```js
exports.func = func;
function func() {}

var func = exports.func = undefined;
```

Traceur throws an error for the same file

```
Duplicate export. 'func' was previously exported at func.js:1:8
```

Do you have any evidence that the TypeScript feature actually works?

**Comment by Rich-Harris** [comment]
Pretty sure that the duplicate export of `func` is invalid JavaScript. Acorn rejects it, Babel rejects it, Traceur rejects it, and V8 rejects it according to the linked issue.

Going to put this ball back in TypeScript's court, sorry.

**Comment by Rich-Harris** [comment]
By the way – this might be semi-related to #716, which is now fixed. So the workaround in the linked issue *might* now work again.
