### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by thepian** [rollup/rollup#822]
I find it hard to get beyond a demo example to something that can be reliably debugged.

I configured a Gulp task running riot+buble but it seems I end up with broken source maps. So I figured Buble is fairly new and not fully supported yet so I tried to use Babel. However with Babel you need to change the .bablerc to use a special preset. However that preset will not work with Gulp when it uses Babel as well.

[ ] Example for a way to build with ES6 and source maps that works reliably so you can have debugging breakpoints and see the variables and correct lines.
[ ] Perhaps gulp example with working source maps as well.

**Comment by TrySound** [comment]
@thepian There is an option `babelrc: false`. You may pass it in babel() plugin call. Configuration with preset may be passed in the same way. This will let you to keep different presets safely.

**Comment by TrySound** [comment]
@thepian Also can you create small reproducing repository with broken source map?

**Comment by snuggs** [comment]
@TrySound you are correct. Here is an example using sourcemaps directly from `gulp-babel` https://github.com/babel/gulp-babel#user-content-source-maps

However, what's unfortunate @thepian is the `.babelrc` file should ALSO work with `gulp-babel`

https://github.com/babel/gulp-babel/issues/48

Hope that helps.

**Comment by aMarCruz** [comment]
@thepian , currently, riot does not supports sourcemaps, it is WIP for v3.

**Comment by thepian** [comment]
I can't stress enough how much working examples help though. Even if it's a link to a repo that does things well.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
