### ISSUE TITLE
Getting import statements in output code

### ISSUE THREAD

**Issue by futuraprime** [rollup/rollup#824]
I'm trying to replace my webpack workflow with rollup. I think I've got everything configured correctly—I'm using `grunt-rollup` like so:

    rollup : {
      options : {
        sourceMap : true,
        plugins : function() {
          return [
            bundleWorker(),
            babel({
              presets: [ 'es2015-rollup', 'react', ],
            }),
          ];
        },
      },
      files : {
        dest : 'built/dist.js',
        src : 'js/init.js',
      },
    },

Which seems fine, except I end up with a pile of import statements at the top of my output file:

    import { json, timer, interpolate } from 'd3';
    import React from 'react';
    import ReactDOM from 'react-dom';
    (etc.)

etc. This file obviously does not run. It also gives me a bunch of errors:

    Running "rollup:files" (rollup) task
    Treating 'd3' as external dependency
    Treating 'react' as external dependency
    Treating 'react-dom' as external dependency
    (etc.)

I don't want these treated as external dependencies, but have no idea how to prevent them (specifiying `external: function() { return false; }` does not do it).

**Comment by Rich-Harris** [comment]
You'll need to specify an output format, like so:

```js
rollup : {
  options : {
    format: 'amd', // or 'iife', 'umd', 'cjs'
    sourceMap : true,
    plugins : function() {
      return [
        bundleWorker(),
        babel({
          presets: [ 'es2015-rollup', 'react', ],
        }),
      ];
    },
  },
  files : {
    dest : 'built/dist.js',
    src : 'js/init.js',
  },
}
```

The format defaults to `es`, i.e. merge the files into one but otherwise don't change anything. Which is probably unhelpful – I think we should print a warning if `options.format` isn't specified.

**Comment by futuraprime** [comment]
Aha! Thanks—that does solve the imports issue, but I still have a bunch of "external dependencies" that aren't being rolled up.

**Comment by Rich-Harris** [comment]
Ah – for that you'll need to add another couple of plugins:

* https://github.com/rollup/rollup-plugin-node-resolve – locates dependencies in your node_modules folder
* https://github.com/rollup/rollup-plugin-commonjs – converts CommonJS files to ES modules

**Comment by futuraprime** [comment]
Marvelous. It does still have some problems (the worker is throwing up some babel errors `'import' and 'export' may only appear at the top level (4:0)`, which are possibly specific to that worker plugin. More to the point, however, it's having trouble finding functions out of lodash (says 'lodash does not export). Is that down to the node-resolve plugin?

**Comment by TrySound** [comment]
@futuraprime Did you enable `{ jsnext: true }` option of `node-resolve`?

**Comment by TrySound** [comment]
Also did you tried lodash-es?

**Comment by futuraprime** [comment]
I am using `{ jsnext: true }`.

I tried using `lodash-es` but it fails with `Warning: 'import' and 'export' may only appear at the top level (7:0) in node_modules/lodash-es/_freeGlobal.js`. (I've added `./node_modules/lodash-es/**` to the commonjs plugin's exclude list but this makes no difference.)

**Comment by futuraprime** [comment]
Of course, I used `excludes` instead of `exclude`. This bit seems to be working now.
