### ISSUE TITLE
Direct eval - an option to ignore

### ISSUE THREAD

**Issue by boopathi** [rollup/rollup#825]
For example, 

https://github.com/sindresorhus/to-fast-properties/blob/master/index.js 

Here eval is present on purpose for that particular function to be not optimized. But when using rollup with this module, it exits. It will be good to have an option telling rollup not to worry about Direct Eval, similar to uglifyJS - https://github.com/mishoo/UglifyJS2#mangle `mangle.eval = true`

And it is not possible to use Indirect eval in the above code too.

**Comment by Rich-Harris** [comment]
It exits? That shouldn't happen – you should just get a warning like this:

> Use of `eval` (in path/to/file.js) is strongly discouraged, as it poses security risks and may cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details

See e.g. [this gist](https://gist.github.com/Rich-Harris/9d2ee49408d0e18b29383404e6813c49) – the bundle is generated, just with the warning (which you can suppress by supplying a noop `onwarn` function). Are you experiencing something different?

**Comment by boopathi** [comment]
Oops. This was the last warning before it exited. The problem was that I didn't handle using the `catch` statement. It was just a coincidence that this warning was displayed before it exited. 

Uncaught promise errors should be thrown IMO. 

Closing this issue. Thanks.

**Comment by intervalia** [comment]
I would like a comment like this one: `// eslint-disable-line no-eval` that would ignore the fact that I did an `eval` on this line. or `// eslint-disable-next-line no-eval` that would ignore the `eval` on the next line.

If I know what I am doing and wanted/needed to use `eval` in my file I don't want rollup to complain about it.

Can this be done? Can this be added?
