### ISSUE TITLE
SystemJS output

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#83]
See https://github.com/esperantojs/esperanto/issues/53

**Comment by kylecordes** [comment]
rollup/rollup#83 ends with a pointer back to this issue, by the way.

**Comment by Victorystick** [comment]
@kylecordes This _is_ rollup/rollup#83. :stuck_out_tongue_winking_eye:

**Comment by Dutchboy** [comment]
@Victorystick Any solutions?

**Comment by guybedford** [comment]
PR at #1897.

**Comment by guybedford** [comment]
`system` format is now supported :)
