### ISSUE TITLE
Can't bundle a CLI project

### ISSUE THREAD

**Issue by screendriver** [rollup/rollup#831]
I am writing a CLI application at the moment and my entry script has to declare a shebang so that it can run on a CLI:

```js
#!/usr/bin/env node
```

Unfortunately rollup can't build this file. I get following error: `Unexpected character '#'`

**Comment by screendriver** [comment]
The solution was to add the `banner` option to my `rollup.config.js`

https://github.com/screendriver/dater-cli/commit/01621e2d2e1f7831220da77baf9a8347ea4cc976#commitcomment-18547437

**Comment by RichieChoo** [comment]
> The solution was to add the `banner` option to my `rollup.config.js`
> 
> [screendriver/redater@01621e2#commitcomment-18547437](https://github.com/screendriver/redater/commit/01621e2d2e1f7831220da77baf9a8347ea4cc976#commitcomment-18547437)
Can not find your `rollup.config.js`
