### ISSUE TITLE
Fail to build project with babel-preset-rollup-2015.

### ISSUE THREAD

**Issue by differui** [rollup/rollup#832]
I was using rollup.js to build [my project](https://github.com/differui/knockout.register) and encountered below error:

```bash
{
    [Error: Error loading ./src/index.js: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information]
    id: 'C:/Users/binrui/Workspace/knockout.filter/src/index.js'
}
 ```

There is only one `.babelrc` in `/src`.

Use below command to build:

```bash
npm run build
```

**Comment by TrySound** [comment]
It's not rollup itself issue. Please reopen it in https://github.com/rollup/rollup-plugin-babel

**Comment by differui** [comment]
@TrySound  Thanks for replying.

Same issue exist  https://github.com/rollup/rollup-plugin-babel/issues/71.
