### ISSUE TITLE
export * from swallows defaults

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#836]
http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20*%20from%20'.%2Fmaths.js'%3B%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22export%20default%205%3B%22%7D%5D%7D

**Comment by TrySound** [comment]
Ref https://github.com/rollup/rollup-plugin-multi-entry/issues/12

**Comment by eventualbuddha** [comment]
I accidentally duplicated this ticket but I'm keeping the duplicate because the description has more information (https://github.com/rollup/rollup/issues/840).

**Comment by TrySound** [comment]
It's fine. Thanks.
