### ISSUE TITLE
`mappings: ''` breaks sourcemaps

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#838]
`flow-remove-types` does not generate sourcemaps but just replaces all invalid for acorn characters with spaces. This is 1:1 mapping. But current `{ mappings: '' }` just breaks sourcemap in every source where it's used. How can it be handled automatically?

/cc @Rich-Harris

**Comment by Rich-Harris** [comment]
I wonder if we need to have a way of signalling that a transformer hasn't moved any code around. Probably a bit of a niche scenario but I'd quite like to play around with flow-remove-types myself...

How about

```js
return { code, mappings: null };
```

?

**Comment by aMarCruz** [comment]
It is `{ code, mappings: null }` preserving sourcemap now (for these cases)?.

**Comment by tehvgg** [comment]
@TrySound I believe this can be closed, solved by #1797

**Comment by TrySound** [comment]
@tehvgg Thanks.
