### ISSUE TITLE
node v0.10 broken

### ISSUE THREAD

**Issue by hjdivad** [rollup/rollup#839]
Is node v0.10 supported?  I wasn't able to find out what versions of node are supported in the README, website or guide and there isn't an `engines` entry in `package.json`.  Testing on v0.10 stopped [a while ago](https://github.com/rollup/rollup/commit/82bac613fca78f76855fb2503c4166ae50c9724d#diff-354f30a63fb0907d4ad57269548329e3) but the commit message doesn't make it clear that support has ceased.

In any case, rollup seems to fail in v0.10 with `Map is undefined`.

```
/home/travis/build/heimdalljs/heimdalljs-lib/node_modules/rollup/src/Bundle.js:23
		this.cachedModules = new Map();
                           ^
ReferenceError: Map is not defined
    at new Bundle (/home/travis/build/heimdalljs/heimdalljs-lib/node_modules/rollup/src/Bundle.js:23:28)
```
(see the [full build](https://travis-ci.org/heimdalljs/heimdalljs-lib/jobs/150723985))

Is this a bug or is this version of node intentionally unsupported?

**Comment by TrySound** [comment]
@hjdivad We don't support node0.10 and will stop support node0.12 in december.

**Comment by hjdivad** [comment]
@TrySound thanks!
