### ISSUE TITLE
default exports are ignored by `export *`

### ISSUE THREAD

**Issue by eventualbuddha** [rollup/rollup#840]
I'd expect that default exports in a module re-exported with `export *` would be present in the exporting module, but they are not.

([repl](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20*%20from%20'.%2Fmaths.js'%3B%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22export%20default%200%3B%22%7D%5D%7D))

**main.js**

```js
export * from './maths.js';
```

**maths.js**

```js
export default 0;
```

Originally reported at https://github.com/rollup/rollup-plugin-multi-entry/issues/12.

**Comment by eventualbuddha** [comment]
This is a duplicate of #836, but I'm keeping this one because it's more descriptive.

**Comment by Rich-Harris** [comment]
Can't find the link right now, but I think this came up once before and the conclusion was that  default exports weren't included in `[im|ex]port *` – does that sound right?

**Comment by eventualbuddha** [comment]
[ES2015 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-getexportednames) says:

```
For each element n of starNames, do
  If SameValue(n, "default") is false, then
    If n is not an element of exportedNames, then
      Append n to exportedNames.
```

So you're right about `export *`, @Rich-Harris. Additional evidence from [babel](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=import%20*%20as%20foo%20from%20'foo'%3B).

I'm having trouble parsing the spec to figure out the `import *` case, but babel includes `default` for ES modules since it just uses whatever it gets from `require` as-is:

```js
function _interopRequireWildcard(obj) {
    if (obj && obj.__esModule) {
        return obj;
    } else {
        var newObj = {};
        if (obj != null) {
            for (var key in obj) {
                if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key];
            }
        }
        newObj.default = obj;
        return newObj;
    }
}
```
