### ISSUE TITLE
Enabling Entry to Accept A String

### ISSUE THREAD

**Issue by AlexanderElias** [rollup/rollup#843]
### Enabling Entry to Accept A String

Roll is really cool but I hoping for a feature to be added. I don't mind contributing but I would like to propose it first and get your input. It would be more efficient for my usage of rollup to programmatically give it a string rather than providing it a file path. In my instance I already have the files loaded in memory. Would something like this be possible?

Let me know your thoughts.

**Comment by eventualbuddha** [comment]
This is exactly what [rollup-plugin-memory](https://github.com/TrySound/rollup-plugin-memory) is for!

**Comment by eventualbuddha** [comment]
You may find this list of plugins useful: https://github.com/rollup/rollup/wiki/Plugins

**Comment by eventualbuddha** [comment]
Also, searching on npm: https://www.npmjs.com/search?q=rollup-plugin

**Comment by AlexanderElias** [comment]
Not what I am talking about but cool plugin. I am referring to the `entry:`

**Comment by AlexanderElias** [comment]
`entry:` should have the ability to be a string not just a file path. That is what I was suggesting.

**Comment by AlexanderElias** [comment]
Or adding an additional value that can be used instead of `entry` like `text:`that will allow a  js string.

**Comment by eventualbuddha** [comment]
Hmm. Perhaps that's not what rollup-plugin-memory is for. Anyway, this can be done using a plugin. You essentially want a simpler version of what [rollup-plugin-multi-entry](https://github.com/rollup/rollup-plugin-multi-entry/blob/master/index.js) does.

I'm not sure whether such a plugin exists, but you can pretty easily write it yourself. The easiest way to do that is to include the plugin in your `rollup.config.js` file inline first:

```
const entryModule = '\0entry-in-memory-module`;

function entryInMemory(code) {
  return {
    options(options) {
      return Object.assign({}, options, { entry: entryModule });
    },

    resolveId(id) {
      if (id === entryModule) {
        return entryModule;
      }
    },

    load(id) {
      if (id === entryModule) {
        return code;
      }
    }
  };
}

export default {
  plugins: [entryInMemory('export * from "foo"')]
};
```

**Comment by TrySound** [comment]
What is the use case? It won't work for relative modules.
