### ISSUE TITLE
unexpected result after a rollup task: `this` keyword  has been rewritten to `undefined`

### ISSUE THREAD

**Issue by tnga** [rollup/rollup#847]
```js
// Extracts the result from a wrapped and chained object.
_.prototype.value = () => this._wrapped;
```

**rollup output**
```js
var _this = undefined;
// Extracts the result from a wrapped and chained object.
_.prototype.value = function () {
	return _this._wrapped;
};
```
*log:*
`The this keyword is equivalent to undefined at the top level of an ES module, and has been rewritten`

**Comment by tnga** [comment]
if   `this` keyword is equivalent to `undefined` at the top level of an ES module, why rewrite it in the bundle ? I think it shall be generated as it, so that it will be `undefined` for ES module and will take it meaning as developer expected for other usage *(cjs, amd, iife)*.

**Comment by TrySound** [comment]
All is correct here. `this` is undefined in the top of module. Babel output is
```
var _this = this;
_.prototype.value = function () {
    return _this._wrapped;
};
```
which is invalid for rollup. It's part of module linting.

**Comment by tnga** [comment]
Therefore, how to overcome to that ? Considering the `this` in the example is for the associated object *(not `undefined`)* and the fact that the usage of `this` at the top level of a code is sometime for referring global object in some VM.

**Comment by TrySound** [comment]
@tnga Access them directly. Don't use implicit behaviour.

**Comment by tnga** [comment]
@TrySound, it can be okay for knowing global object *(ex: `window` in browser, `global` in the server)*, but how about this definition:
```js
// Extracts the result from a wrapped and chained object.
_.prototype.value = () => this._wrapped;
```
considering object will be created later through `_` !

**Comment by tnga** [comment]
That said, the behavior don't happen with an explicit definition:
```js
// Extracts the result from a wrapped and chained object.
_.prototype.value = function () { return this._wrapped; }
```

* @TrySound as you previously explain with babel result, maybe this can be referring to issue #848 *

**Comment by TrySound** [comment]
Do you know arrow functions doesn't have own context? That means it can't use `this` as an instance of `_`.

**Comment by tnga** [comment]
I didn't understand it like that with es6 spec and some authors blog/article about it. Maybe i misunderstood but considering this example taking from https://github.com/getify/You-Dont-Know-JS in `es6 & beyond/ch2.md`
```js
var controller = {
    makeRequest: function(..){
        btn.addEventListener( "click", () => {
            // ..
            this.makeRequest(..);
        }, false );
    }
};
```
the `this` will referred to `btn` which is an instance of a `HTMLElement` *(ex `HTMLButtonElement`)*.

**Comment by TrySound** [comment]
Just run this code in browser and log this.

**Comment by TrySound** [comment]
And addEventListener does not apply context.

**Comment by tnga** [comment]
> Do you know arrow functions don't have own context?

Thinking about it, i didn't read the spec as i had to do. I just got an overview. After this discussion, i take a time to really get into it ; now it's okay for me. 

Thank for the review @TrySound, i really appreciate it !
