### ISSUE TITLE
unexpected result after a rollup task: native arguments variable is "overscoped"

### ISSUE THREAD

**Issue by tnga** [rollup/rollup#848]
using rollup + babel-plugin, this issue happen when use arrow function syntax:

**normal function**
```js
export function cbze (func, context, argCount) {
	if (context === void 0) return func;
	if (argCount === void 0) return function (value) {
               return func.call(context, value);
        };
	return function () {
		return func.apply(context, arguments);
	};
}
```
*(es5) expected result: __ok__*
```js
function cbze (func, context, argCount) {
	if (context === void 0) return func;
	if (argCount === void 0) return function (value) {
               return func.call(context, value);
        };
	return function () {
		return func.apply(context, arguments);
	};
}
```

**arrow function**
```js
export function cbze (func, context, argCount) {
	if (context === void 0) return func;
	if (argCount === void 0) return (value) => func.call(context, value);
	return () => func.apply(context, arguments);
}
```
*(es5) expected result: __not ok__*
```js
function cbze (func, context, argCount) {
        var _arguments = arguments; // ???

	if (context === void 0) return func;
	if (argCount === void 0) return function (value) {
               return func.call(context, value);
        };
	return function () {
		return func.apply(context, _arguments); // cbze arguments overwrite expected arguments
	};
}
```
normally, the arguments variable use on `func.apply` is arguments of the returned function; but it's overwritten in the second case; therefore scope isn't respected with this bundle for arrow function usage

**Comment by TrySound** [comment]
Show full stacktrace please

**Comment by tnga** [comment]
the task end without log, like everything is ok ! above, you have the different results. I just add few comment to explain behavior. That said, that behavior only happen when use rollup's babel plugin ; without it, everything is ok, except the fact that the result isn't favorable for ES5 usage case.

**Comment by TrySound** [comment]
@tnga Then write this issue in babel plugin repo.
