### ISSUE TITLE
Tree-shaking not working?

### ISSUE THREAD

**Issue by futuraprime** [rollup/rollup#849]
I'm trying to set up rollup, but I'm not getting the benefits of (or perhaps am not properly understanding) tree-shaking. When I do something like:

    import extend from 'lodash-es/extend';

it brings in the entirety of extend, even if I haven't called extend in my code; more troublingly, if I

    import { extend } from 'lodash-es';

it imports the entirety of lodash. I had thought Rollup's tree-shaking would limit this import to necessary functions. Is this a peculiarity of `lodash-es`.

My config (using grunt-rollup) is like so:

      options : {
        format : 'iife',
        sourceMap : true,
        plugins : function() {
          return [
            babel({
              presets : [ 'es2015-rollup', 'react', ],
              exclude : './node_modules/**',
            }),
            nodeResolve({
              module: true,
              jsnext : true,
              main : true,
              browser: true,
            }),
            commonjs({
              include : 'node_modules/**',
              exclude : [ './node_modules/lodash-es/**' ],
            }),
          ];
        },

Is there something I'm doing wrong? Is this working as intended?

Thanks so much for looking into this.

**Comment by tnga** [comment]
for the first case, i thing is normal that rollup brings in the entirety of extend and all it associated/expected call (external variables, functions, ...) determined through the **tree shacking stuff** ; even if you don't use it in your code, considering that the `import` instruction is sufficient for that. 

_with  **tree shacking stuff**, rollup brings what it will seems to be necessary; not what you don't use._

for the second case, it's unexpected, maybe a *lodash* behavior ?

**Comment by TrySound** [comment]
Yeah lodash has some problems with tree shaking which will be fixed in lodash5 I hope. The only case is using paths like `import map from 'lodash-es/map';`

**Comment by tnga** [comment]
@TrySound, or a rollup's tree shaking behavior ? That said, it's troubling, i have the same behavior with https://github.com/tnga/underscore-es. For example focusing this code,
```js
import {_template} from 'underscore-es'; //or underscore-es/src/tools

var basicTemplate = _template("Ok, i use <%= builder %> for my es6 and beyond stuff !");
var result = basicTemplate({builder: 'rollup'});
console.log( result ); 
```
rollup brings in the entirety of the *underscore-es* or many unnecessary functions and variables from *tools*; which some of them are suffixed with *$* if there aren't imported, but are called (so that they can't be used). Formally, i don't thing that is my code or how *underscore-es* is written the problem !

**Comment by Rich-Harris** [comment]
This comes up a lot so I've just added a section to the wiki: https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working

**Comment by hollowdoor** [comment]
From the wiki it says "rollup plays it safe and includes those side-effects." But I have a module that is es6 modules with no side-effects. Unless I'm not understanding what side-effects are.

The module being imported is here https://github.com/hollowdoor/type_func

Importing one function from type-func imports the whole thing.

Like `import {boolean} from 'type-func'` makes output contain all the other functions.

Ignore the bad example in the readme at https://github.com/hollowdoor/type_func, for the import. I wrote that incorrectly, and haven't updated that yet. :)

**Comment by B-Esmaili** [comment]
@Rich-Harris i followed troubleshooter tip but no chance. I use `create-react-library`  and i do `import Button from 'antd/es/button'` and end up with 900 kb bundle. Am i the first one in the planet using rollup & antd together? this is realy disappointing that antd guys answer this [question](https://github.com/ant-design/antd-mobile-samples/issues/46) that way.

**Comment by B-Esmaili** [comment]
Is this project active at all? 5 days without any response! At least somebody tell me it's not possible using rollup so that i don't wast my time on it anymore.

**Comment by peterslavov** [comment]
@B-Esmaili for antd and other libraries (I've used it for material-ui), you should use the [babel-plugin-import](https://github.com/ant-design/babel-plugin-import) plugin to make tree shaking work.
