### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ghost** [rollup/rollup#850]
@Rich-Harris You asked for a separate issue ticket regarding performance improvements.

In most cases when you are doing a low level library which `Rollup` is, then I don't think extreme optimization is necessary, but you are doing `CRUD`. 

First thing I would have looked at is the use of native functions, but also what you want to achieve, and which parts of the code you need to optimize.

Example `Try/ catch` is a very expensive operation. The issue here is that `V8` doesn't support the never throwing try-catch block  in their optimizing compiler so the entire containing function that syntactically contains a try catch will not be optimized.  *You can easily work around this though, by creating a helper function*.

`V8 TurboFan` will however support try-catch optimizing in the compiler, but we are not there yet: https://codereview.chromium.org/1996373002.   

`Bluebird` as a reference also have a ok try/catch solution.

Native `map`, `forEach`, `reduce` etc also have a horrible performance most of the time. 

That's why libraries such as `Lodash` exist. 

I'm not providing any benchmarks here because benchmarks depends on the user case, and is not always reliable.

This things could also be optimized. Example if you choose not to rely on any dependencies you could make your own `ArrayMap` and `ObjectMap` function to faster iterate through array and objects.

That said, mostly all native implementations always do more in terms of error handling and features than the simple self-implementations.  You can see it here: http://www.ecma-international.org/publications/standards/Ecma-262.htm

So making your own functions for this will make Rollup perform better. But how good it perform will in the end rely on the end-user and how he / she is using your library.

You can take it even a step further and look at micro optimizations, but in the long run I don't think that is needed for a library such as Rollup. Example on micro optimization is 

* don't cache the length in loops
* for loops are faster then while loops - except in Firefox (*with a few exceptions*)

Other things to look into is what is causing `DEOPT`. I'm not an expert on that, but I know that use of `instanceOf` among other things  in V8 gives a DEOPT in latest Chrome version. If I'm not mistaken I think it occured from v. 48. Anyway. How important this is for `Rollup`, I don't know.

Also caching  is important, but also sometimes it can become a bottleneck.  

So maybe the way to go would be to create your own functions that do only the things you expectwithout heavy error checking and tons of features you don't need.

This is just for the internal code of Rollup, and such optimizations will also have impact on the `watch` task performance. For Rollup watch I suggest use `setImmediate` for newer versions of NodeJS. 
https://nodejs.org/api/timers.html with fallback for legacy NodejS. I opened a ticket in that repo regarding this.

**Comment by Rich-Harris** [comment]
Thanks for this @Kflash. My sense is that we should probably add a performance test that creates a large bundle so that we can gather some real data when assessing whether to replace native array methods (for example).

Surprised to learn `instanceof` causes deopt. Luckily we're not affected by that anyway, we don't use it anywhere.

rollup-watch currently uses `setTimeout(..., 50)` so that multiple file changes (e.g. following a `git checkout` or whatever) only trigger one rebuild, though I'm interested to learn about `setImmediate` – I actually thought that had been dropped for some reason. That's great news.

**Comment by Kflash** [comment]
@Rich-Harris Regarding `rollup-watch` you could consider to use `chokidar`. Just note that it uses anymatch under the hood, which supports negation patterns. Maybe not a big deal for Rollup, but it solves some issues and bottlenecks found in the native `fs.watch` implementation.

Agree that creating a performance test that creates a large bundle is the way to go, but as a start you could think as a end-user not as an author of the library and do a deep analyze on the part of the code that are most used. E.g. CLI I guess is most used, so start to see if CLI can be optimized, then follow the qlues you get from the issue tickets regarding witch feature people are using. And optimize it from there.

Regarding 'setImmediate'. A good but old explanation are given here: http://stackoverflow.com/questions/17502948/nexttick-vs-setimmediate-visual-explanation
It's been used by some other large libraries that has a watch task.
