### ISSUE TITLE
Add an option to turn off top level this->undefined

### ISSUE THREAD

**Issue by zbraniecki** [rollup/rollup#851]
I'm working on a project that has as one of the targets an `XPCOM Module` which is an internal module in Gecko (Mozilla's engine).

XPCOM modules require you to specify `this.EXPORTED_SYMBOLS` and assign any exported functions on `this`.
The result looks like this: https://github.com/l20n/l20n.js/blob/master/src/runtime/gecko/l20n-chrome-xbl.js

rollup works perfectly, but starting from 0.31 it started rewriting top-level `this` to `undefined` which prevents us from upgrading.

Can we get an option to turn the conversion off?

**Comment by TrySound** [comment]
Bad APIs are against spec. :)

**Comment by zbraniecki** [comment]
Correct, unfortunately, changing an API that has been around for 15 years and is at the core of a major open source project is rather hard.

**Comment by cognitom** [comment]
@zbraniecki does it help you? Not clean, but works.
https://github.com/rollup/rollup/pull/707#issuecomment-234757367

**Comment by Rich-Harris** [comment]
Have opened #858 – feedback on the API welcome

**Comment by Rich-Harris** [comment]
As of 0.34.10 you can override the context with `options.context`
