### ISSUE TITLE
Unexpected token = error using default destructuring value

### ISSUE THREAD

**Issue by cif** [rollup/rollup#853]
Searched thoroughly as I could on this one but apologies if this has been reported already

I'm getting `Parse Error: Line 100: Unexpected token = ` during transform. Line 100 is the first line of the first attempt to assign default value to a destructured object variables like so:

```
const {
    isColorized = false,
    isDefaultHidden = false
  } = properties;
```

Perhaps there is a plugin out there somewhere which solves this problem?

**Comment by cif** [comment]
Indeed, babel is still required for the sugar. Closing the issue.

**Comment by cif** [comment]
Re-opened. This error is still being thrown I just didn't see it until after I solved the various babel configuration warnings / issues.

**Comment by Rich-Harris** [comment]
Odd – can you provide a reproducible test case please? [Rollup is fine with assignment patterns in declarations](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22const%20%7B%5Cn%20%20isColorized%20%3D%20false%2C%5Cn%20%20isDefaultHidden%20%3D%20false%5Cn%7D%20%3D%20properties%3B%5Cn%5Cnconsole.log(%20isColorized%2C%20isDefaultHidden%20)%3B%22%7D%5D%7D) (it's happy with anything that Acorn is happy with in ES6 mode), so it's not clear what's going wrong here. Maybe there's a transform before the Babel transform that doesn't know what to do with ES6 code? (In which case just flip the order)

**Comment by cif** [comment]
Bingo on fixing the syntax order. There was a JSX transform plugin happening prior to babel. Thanks!
