### ISSUE TITLE
Update 0.34.1 -> 0.34.8: broken bundle (var   var)

### ISSUE THREAD

**Issue by efender** [rollup/rollup#854]
And lodash (4.14.1) again )
With Rollup 0.34.1 - bundle is OK.

`app.js`
```js
import baseKeysIn from './lodash-es/_baseKeysIn.js';
```
` bundle.js`
```js
...
    /** Built-in value references. */
  var   var enumerate = Reflect ? Reflect.enumerate : undefined;;
  var   var propertyIsEnumerable = objectProto.propertyIsEnumerable;;
...
```
`config default, no plugins`
```js
rollup( {
  entry: appFile
}.then(...
```
Tnahks uglifyjs! :)
![1471290484190](https://cloud.githubusercontent.com/assets/6908417/17677198/c16da066-6342-11e6-8128-6720572d612c.png)

**Comment by Rich-Harris** [comment]
That's very odd, and I can't seem to reproduce it (attempted [here](https://github.com/Rich-Harris/rollup-issue-854)) – could you create a repo (or fork mine) to show the problem, or better yet reproduce it on [rollupjs.org](http://rollupjs.org/)? Thanks

**Comment by efender** [comment]
Yes, you are right, your test is OK for me too.
I'll test my project later.
Thanks!
