### ISSUE TITLE
Rollup Uglify of lodash-es fails

### ISSUE THREAD

**Issue by lukekentwell** [rollup/rollup#856]
I am attempting to write a small library and use the lodash as a dependency. 
I have:
- installed lodash-es (via npm)
- imported lodash in my file using `import _ from 'lodash-es';`
- using rollup-plugin-uglify

When rollup is run I get an error : `Error at new JS_Parse_Error`.

I attempted to use the harmony minifier instead (in a desperate, I dont know what is going on attempt) however that did not work resulting in the same error.

Can anyone here tell me what I am doing wrong??

Thanks in advance.

**Comment by TrySound** [comment]
@lukekentwell Which `format` do you use? If `es` uglify won't parse it.

**Comment by lukekentwell** [comment]
@TrySound  The format I am using is `umd`

**Comment by lukekentwell** [comment]
@Try Sound
Im sorry, I was screwing up the import line.. what I needed was
`import forEach from 'lodash-es/forEach'`

Sorry to have wasted your time.

_L

**Comment by TrySound** [comment]
It's okay.
