### ISSUE TITLE
`export {foo as default}` results in a live binding

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#860]
[See demo](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20foo%20from%20'.%2Ffoo.js'%3B%5Cnconsole.log(%20foo%20)%3B%20%2F%2F%20expected%201%2C%20got%202%22%7D%2C%7B%22name%22%3A%22foo.js%22%2C%22code%22%3A%22let%20foo%20%3D%201%3B%5Cnexport%20%7B%20foo%20as%20default%20%7D%3B%20%2F%2F%20%60export%20default%20foo%60%20works%20correctly%5Cnfoo%20%3D%202%3B%22%7D%5D%7D):

```js
// main.js
import foo from './foo.js';
console.log( foo ); // expected 1, got 2

// foo.js
let foo = 1;
export { foo as default }; // `export default foo` works correctly
foo = 2;
```

This should log 1 but logs 2. Via #845

**Comment by guybedford** [comment]
@Rich-Harris I don't think this is correct actually. It is only `export default asdf` that is not live as that is an expression form, but `export { x as default }` should be live like any other binding.
