### ISSUE TITLE
Add API function for loading config file

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#865]
As per a Gitter suggestion, we could move the logic to load a`rollup.config.js` file out of the Rollup CLI code and into the library itself. That would make it easier for other people to use, and would decrease the amount of CLI-unique code by quite a bit. It may also make the code easier to test since we're only concerned with loading a set of options, and not actually bundling anything.

**Comment by TrySound** [comment]
Ref https://github.com/rollup/rollup/issues/828

**Comment by snuggs** [comment]
I concur. MUCH easier solution. Does this create a dependency PR with the cli? Curious to see how this plays out so I can begin contributing as much as I can ;-)

**Comment by bfred-it** [comment]
Duplicate of https://github.com/rollup/rollup/issues/761?
