### ISSUE TITLE
How do you bundle a library and leave node_modules external?

### ISSUE THREAD

**Issue by jsg2021** [rollup/rollup#872]
I'm trying to play with rollup and starting with a library. (not a whole app)  I want to bundle the library into one file, but leave the library's dependencies (es6 or cjs) as external. Is there a way to do that?

**Comment by bfred-it** [comment]
rollup does not bundle external modules by default like browserify does. You have to manually enable that behavior with the plugin [https://github.com/rollup/rollup-plugin-node-resolve](rollup-plugin-node-resolve)

Additionally there's an `external` and `--external` option to exclude any specific files: https://github.com/rollup/rollup/wiki/JavaScript-API#external

**Comment by jsg2021** [comment]
Ah, is there a plugin / config that only enables resolving directories as modules with index.js files?

ex: `import {foo} from './bar'` where `./bar` is a directory and has an `index.js`
