### ISSUE TITLE
Suggestion to add to Plugin wiki

### ISSUE THREAD

**Issue by thgh** [rollup/rollup#876]
### Plugin hooks

Here is an chronological overview of the hooks that plugins can use.
#### Phase 1: plugin initialization

The pluginObject is created before rollup does anything. It may contain any of the hooks mentioned below.
`export default function (pluginOptions) => pluginObject`
#### Phase 2: rollup.rollup()

`options (bundleOptions) => bundleOptions` is called once in the very beginning
#### Phase 3: bundle.build()

First comes the entry file, then the modules it imports and so fourth recursively.
`For every module {`
&nbsp;&nbsp;&nbsp;&nbsp;`resolveId (importId, importer) => moduleId`
&nbsp;&nbsp;&nbsp;&nbsp;`load (moduleId) => moduleSource`
&nbsp;&nbsp;&nbsp;&nbsp;`transform (moduleSource, moduleId) => { code, ast, map}`
`}`
Note: transform is only called if moduleSource was changed since last time
#### Phase 4: bundle.render()

The bundleOptions in ongenerate also contain the bundle result.
`intro () => introText`
`banner () => bannerText`
`footer () => footerText`
`transformBundle (bundleRendered) => {code, map}`
`ongenerate (bundleOptions, bundleRendered)`

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
