### ISSUE TITLE
bundle.generate result returns null for map

### ISSUE THREAD

**Issue by damountie** [rollup/rollup#877]
If I run `rollup -c -m` then I get a correct source-map :+1: Likewise, if I use `bundle.write` from the API, then I get the code and the map both written out all OK.

But, I find that the `map` in the result of `bundle.generate`, is only ever returned to me as `null`.

I first noticed this behaviour whilst using `rollup-stream` with `gulp` and `browserify`. However I quickly realised that this behaviour is within `rollup`. I created the following quickie script to test this out, following the example in the Wiki:

```js
const fs = require( 'fs' );
const readFileSync = fs.readFileSync;
const rollup = require('rollup');
const config = require('./rollup.config.js');

rollup.rollup(config).then(bundle => {
    const result = bundle.generate({
        format: 'iife',
    });

    // result.code is as expected
    fs.writeFileSync( 'rollup-generate.js', result.code );
    
    // result.map is null
    fs.writeFileSync( 'rollup-generate.js.map', result.map );

    // rollup-write.js and rollup-write.js.map are correct.
    bundle.write({
        format: 'iife',
        dest: 'rollup-write.js',
        sourceMap: true,
    })
});
```

Every time, the product of using `bundle.write` or the CLI is correct. But consistently I get only `null` when using `bundle.generate`.

**Comment by TrySound** [comment]
```js
const result = bundle.generate({
    format: 'iife',
    sourceMap: true
});
```

**Comment by damountie** [comment]
^ True story. I am getting an issue still with this, but it's not `rollup`s issue -- thanks.
