### ISSUE TITLE
No plugin for 2016 and 2017 presets?

### ISSUE THREAD

**Issue by davegomez** [rollup/rollup#888]
I want to use Rollup for my project while I'm using the new Async/Await JS feature but I can't find any Rollup plugin for the 2016 or 2017 Babel presets.

Is there a way to use this presets and allow Rollup do "his thing"?

**Comment by NicolasParada** [comment]
https://github.com/leebyron/rollup-plugin-async ;D

**Comment by Rich-Harris** [comment]
Also, more recent versions of Babel allow you to use `modules: false`, which means bundler-specific presets are no longer necessary:

```js
// .babelrc
{
  "presets": [
    [
      "es2015", // or es2016, etc...
      {
        "modules": false
      }
    ]
  ]
}
```

**Comment by GGAlanSmithee** [comment]
@Rich-Harris is this the prefered way over [the rollup-babel preset](https://github.com/rollup/babel-preset-es2015-rollup) ?

> This is babel-preset-es2015, minus modules-commonjs, plus external-helpers. Use it with rollup-plugin-babel.

Seems to do a bit more than just - modules?

**Comment by Rich-Harris** [comment]
@GGAlanSmithee ah, yeah, I guess you would also need to add the `external-helpers` plugin if you did it that way. (Had forgotten about that – I don't use this plugin any more, I use [rollup-plugin-buble](https://gitlab.com/Rich-Harris/rollup-plugin-buble) 😀 )

**Comment by eventualbuddha** [comment]
You can also use [babelrc-rollup](https://github.com/eventualbuddha/babelrc-rollup), which takes care of the details for you.
