### ISSUE TITLE
Multiple bundles, interdependencies

### ISSUE THREAD

**Issue by ozra** [rollup/rollup#891]
Is it possible to generate a bundle "critical-scripts" that is used on every page, and a few bundles "special-stuff", "special-stuff-two", for use on certain pages, that _depend_ on "critical-scripts", without shaking those parts out of "critical", or re-including deps in the "specials"? Is it just a matter of what is imported, or what is used in the file too?

I hope I explained it comprehensibly.

**Comment by GGAlanSmithee** [comment]
there is discussion regarding code splitting in #372

**Comment by ozra** [comment]
Ah, I was too bad at searching the issues. Closes since this is a dupe.
