### ISSUE TITLE
Observable$1 generated without proper operator with Angular 2 Http

### ISSUE THREAD

**Issue by Zhuoqing** [rollup/rollup#895]
when trying to use rollup to bundle angular 2 RC6 Http and rxjs , the generated code contain both Observable and Observable$1, while the imported operator only exist for Observable, but angular 2 Http is using Observable$1, thus exception is thrown. 

```
class Observable {
}
Observable.prototype.map = map;
class Observable$1 {
}
//but no Observable$1.prototype.map = map;
//angular 2 http code
var JSONPConnection_ = (function (_super) {
        this.response = new Observable$1(function (responseObserver) {
```

Not sure what I did wrong. I am using the rxjs->rxjs-es hack. Help appreciated.
I end up import map function and use map.call(Obs, (res: Response, index) => {}, Obs) as workaround.

app/testEntry.ts

```
import {Http, Response} from '@angular/http';
import 'rxjs/add/operator/map';
import {Injectable } from '@angular/core';

@Injectable()
export class UtilService {
  constructor(private _http: Http) {
    _http.get('./_locales/zh/messages.json')
      .map(res => {
        console.log(res);
        return res.json();
      })
  }
}
```

```
Angular 2 RC6, 
"rollup": "0.34.13",
"rollup-plugin-node-resolve": "2.0.0",
"rollup-plugin-typescript": "0.8.1",
"rxjs": "5.0.0-beta.11", 
"rxjs-es": "5.0.0-beta.11",

```

rollup.config.js

```
import typescript from 'rollup-plugin-typescript';
import nodeResolve from 'rollup-plugin-node-resolve';

class RollupNG2 {
  constructor(options){
    this.options = options;
  }
  resolveId(id, from){
    if (id.indexOf('rxjs/') >= 0){
        console.log(id, from);
    }
    if (id.startsWith('rxjs/')){
      return `${__dirname}/node_modules/rxjs-es/${id.replace('rxjs/', '')}.js`;
    }
  }
}

const rollupNG2 = (config) => new RollupNG2(config);

export default {
  entry: 'app/testEntry.ts',
  sourceMap: true,
  moduleName: 'popup',
  plugins: [
    typescript(),
    rollupNG2(),
    nodeResolve({
      jsnext: true, main: true
    })
  ]
}
```

**Comment by AlexGolubnychyi** [comment]
I had the same issue. Looks like it is specific to Windows because of its "\" path delimiter.
When rollup resolves full path it gets different results for "./Observable" coming from inside angular and "rxjs/Observable" coming from your code. Full path is used as Id which means different ids which results in Observable being rolled up twice.

As a workaround I use this code:
`resolveId: id => {
     if (id.startsWith("rxjs/")) {
         let result = `${__dirname}/node_modules/rxjs-es/${id.replace("rxjs/", "")}.js`;

         if (!__dirname.startsWith("/")) { 
             return result.replace(/\//g, "\\");
         }
         return result;
    }
}`

Another option is to use Bash on Windows 10

**Comment by Zhuoqing** [comment]
@AlexGolubnychyi thanks for the workaround, it works for me.

**Comment by Rich-Harris** [comment]
Apologies for the non-response, is this still an issue? If so, is it possible to create a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by rdfriedl** [comment]
I have been having the same issue with modules being rolled up twice on windows systems.
I previously opened an [issue](https://github.com/rollup/rollup/issues/1367) that i believe is closely related to this one.
it also has a repro attached to it.

Also as @AlexGolubnychyi mentioned, using bash on windows dose solve this problem.

**Comment by bfred-it** [comment]
Closing since this one is stale and https://github.com/rollup/rollup/issues/1367 has a repro. 👍
