### ISSUE TITLE
Node `fs` module etc.

### ISSUE THREAD

**Issue by Benjamin-Dobell** [rollup/rollup#897]
I can't seem to import from Node's `fs` module (or several other built-in modules). The moduie is treated as an external dependency, even if I use the https://github.com/calvinmetcalf/rollup-plugin-node-builtins. Looking at that plugin, it doesn't actually seem to handle `fs`.

However, rollup config files are themselves able to import from `fs` just fine. How does this work?

**Comment by TrySound** [comment]
@Benjamin-Dobell Why you need to bundle fs? Use browserify for this case.

**Comment by Benjamin-Dobell** [comment]
@TrySound I'm using a bunch of ES6 modules (almost all of which support `jsmain:next`), built with Rollup (because they're run in the browser) e.g. three.js. Typically these modules are bundled up with Rollup so they can run in a browser (which is working great).

However, I'd now like to build some automation (tests etc.) depending on these exact modules, but running them inside of Node.js, so I can do thing like read and write files.

Technically I guess I could use Babel etc. but it seems like overkill seems as they're all `jsmain:next` compatible modules with no ES6 syntax besides the module syntax itself.

**Comment by TrySound** [comment]
@Benjamin-Dobell Do you want to bundle reading process or just raw data?

**Comment by TrySound** [comment]
Ah, okay. Just don't bundle fs itself. It's system module. All you can is inline read data. But it's overkill too. You can add `external: ['fs']` option to prevent that warning.

**Comment by Benjamin-Dobell** [comment]
@TrySound Thanks, I've actually tried that already:

`external: ['fs']`

The issue is that when I run I get `fs` is undefined. Regardless of whether I try:

`import * as fs from 'fs';`

`import fs from `fs`;`

`import {default as fs} from `fs`;`

Perhaps I'm simply building with the wrong target format:

```
export default {
    entry: 'index.js',
    plugins: [
        nodeResolve({
            jsnext: true,
            main: true,
            browser: false
        }),
        json(),
        someCustomTransforms()
    ],
    external: [
        'fs'
    ],
    targets: [
        {
            dest: 'build/testing.js',
            format: 'iife',
            moduleName: 'testing',
            sourceMap: true
        }
    ]
}
```

It seems the output IIFE expects `fs` to be passed as a parameter? Should I use regular `require` syntax, then require the file with my IIFE? I was kind of hoping Rollup would spit out something that "just worked" with Node - although, I fully understand that's not its primary purpose.

**Comment by TrySound** [comment]
@Benjamin-Dobell iife format is for browser. Use cjs

**Comment by Benjamin-Dobell** [comment]
Derp! Thank you!

**Comment by vinnyoodles** [comment]
I'm getting a similar issue with loading `fs`

```
Uncaught ReferenceError: require is not defined
```

It's due to the bundle including this line
```javascript
var fs = _interopDefault(require('fs')); 
```

Any ideas?

**Comment by Rich-Harris** [comment]
@vinnyoodles where are you trying to run the bundle? It sounds like you're creating `cjs` output then running it in a browser, which won't work.

**Comment by srepollock** [comment]
I'm having a similar issue in my project. I'm writing my project in ESNEXT, transpiling in Babel, and using Rollup to bundle it all into cjs, es5 and umd. In my src/**/*.ts modules I'm using a fs.writeFileSync()/fs.readFileSync() in a helper function of the library and Rollup is yelling at me that:
```
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
fs (guessing 'fs')
```
Rollup.config.js
```js
import typescript from 'rollup-plugin-typescript2';
import babel from 'rollup-plugin-babel';
import globals from 'rollup-plugin-node-globals';
import builtins from 'rollup-plugin-node-builtins';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import pkg from "./package.json";

export default {
    input: './src/index.ts',
    output: [
        {
            file: pkg.main,
            format: 'umd',
            name: 'Divine'
        },
        {
            file: "./lib/divine.cjs.js",
            format: 'cjs',
            name: 'Divine'
        },
        {
            file: pkg.module,
            format: 'es',
            name: 'Divine'
        },
    ],
    external: [
        "fs"
    ],
    plugins: [
        globals(),
        resolve(),
        builtins(),
        typescript(),
        commonjs(),
        babel({
            babelrc: false,
            presets: [["@babel/preset-env", {"modules": false}]],
            runtimeHelpers: true
        })
    ],
    watch: {
        include: 'src/**'
    }
}
```

Any help with this would be greatly appreciated 😄

**Comment by codenakama** [comment]
Why this issue was closed if there isn't any resolution? I have the same issue as explained above. I've been investigating but can't tell why `var fs = _interopDefault(require('fs')); ` is being added to my bundle. even when making it external

**Comment by TrySound** [comment]
@codenakama because it's resolved for author of this issue.
Do you have any `import fs from 'fs'` in your code or your dependencies?

**Comment by codenakama** [comment]
@TrySound sorry, wrong assumption, the issue is occurring as well using webpack, so I assume its a problem with our UI lib or with nextjs.

**Comment by codenakama** [comment]
@TrySound I can see this on my `main.es.js` though. are these supposed to be here? - any pointers would be helpful. thanks

```
import util from 'util';
import tty from 'tty';
import fs from 'fs';
import net from 'net';
import os from 'os';
import stream from 'stream';
```

**Comment by codenakama** [comment]
It seems adding `preferBuiltins:true` solves the problem, I just don't know exactly why.

**Comment by TrySound** [comment]
You did not describe your problem well, so I'm not sure what you tried to solve.

**Comment by codenakama** [comment]
@TrySound I am using rollup to create a bundled package for a UI library written with React.

after running `rollup -c` with below config, I was getting errors when importing components from the package and I could see 
```
import util from 'util';
import tty from 'tty';
import fs from 'fs';
import net from 'net';
import os from 'os';
import stream from 'stream';
```

in the output file for `main.esm.js` 

The error has been resolved by adding `preferBuiltins:true` to the config but as I mentioned above, I do not know why it works now, although I'm happy it does.

```
import autoprefixer from "autoprefixer";
import babel from "rollup-plugin-babel";
import commonjs from "rollup-plugin-commonjs";
import filesize from "rollup-plugin-filesize";
import localResolve from "rollup-plugin-local-resolve";
import builtins from "rollup-plugin-node-builtins";
import resolve from "rollup-plugin-node-resolve";
import peerDepsExternal from "rollup-plugin-peer-deps-external";
import postcss from "rollup-plugin-postcss";
import pkg from "./package.json";

const config = {
  preferBuiltins: true,
  input: "src/index.js",
  output: [
    {
      file: pkg.browser,
      format: "umd",
      name: "@lushdigital/ui"
    },
    {
      file: pkg.main,
      format: "cjs",
      name: "@lushdigital/ui"
    },
    {
      file: pkg.module,
      format: "esm"
    }
  ],
  external: ["react", "react-dom"],
  plugins: [
    peerDepsExternal(),
    postcss({ extract: true, plugins: [autoprefixer] }),
    babel({ exclude: "node_modules/**" }),
    localResolve(),
    resolve(),
    commonjs({
      namedExports: {
        "react-dom/server": ["renderToStaticMarkup"],
        react: ["Component", "createElement"],
        "react-immutable-proptypes": ["Set"],
        esrever: ["reverse"],
        immutable: [
          "Set",
          "Record",
          "Map",
          "List",
          "OrderedSet",
          "Stack",
          "is"
        ],
        "slate-plain-serializer": ["immutable"],
        "prop-types": [
          "bool",
          "func",
          "object",
          "shape",
          "number",
          "string",
          "array",
          "oneOf",
          "PropTypes"
        ]
      }
      // include: 'node_modules/**'
    }),
    filesize(),
    builtins()
  ]
};

export default config;
```

**Comment by TrySound** [comment]
I'm sure rollup does not have `preferBuiltins` option. `rollup-plugin-node-resolve` has one. Also you do not need `rollup-plugin-local-resolve` as you already use `rollup-plugin-node-resolve`.

`rollup-plugin-node-builtins` is probably the source of your problem. I would recommend you to not use it as it's not maintained this days. If you have problems with modules without shimming builtins you should probably replace these modules to browser compatible.

**Comment by codenakama** [comment]
@TrySound thanks, cleaned up a bit, but removing `rollup-plugin-node-builtins` I get the errors above.

**Comment by TrySound** [comment]
Then add `preferBuiltins:true` to node resolve plugin and check which of your dependencies has these imports.

**Comment by codenakama** [comment]
@TrySound doing so and remove builtins() plugin, I get errors and this output from rollup

```
util (imported by node_modules/inherits/inherits.js, commonjs-external-util, node_modules/slate-react/node_modules/debug/src/node.js, node_modules/debug/src/node.js)
tty (imported by node_modules/debug/src/node.js, node_modules/slate-react/node_modules/debug/src/node.js, commonjs-external-tty)
net (imported by node_modules/debug/src/node.js, commonjs-external-net)
fs (imported by node_modules/debug/src/node.js, commonjs-external-fs)
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
styled-components (guessing 'styled')
react (guessing 'React')
react-dom (guessing 'ReactDOM')
util (guessing 'util')
tty (guessing 'tty')
fs (guessing 'fs')
net (guessing 'net')
react-dom/server (guessing 'server')
created dist/main.js, dist/main.cjs.js, dist/main.esm.js in 43.9s
```

**Comment by sync3ds** [comment]
I solved this issue by installing [rollup-plugin-node-polyfills](https://github.com/ionic-team/rollup-plugin-node-polyfills).

`import nodePolyfills from 'rollup-plugin-node-polyfills';`

`
rollup({
  entry: 'main.js',
  plugins: [
    nodePolyfills()
  ]
})`
