### ISSUE TITLE
Bundle library with rollup

### ISSUE THREAD

**Issue by pepone** [rollup/rollup#900]
I trying to create a library bundle from multiple JS files using rollup, so far seems that I need to create a main.js where I export all public bits. 

```
// main.js
const Ice = {}
import Ice_ACMConfig from "./Ice/ACMConfig.js"
....
import Ice_Current from "./Ice/Current.js"

Ice.ACMConfig = Ice_ACMConfig;
...
Ice.Current = Ice_Current;

export {Ice as default }
```

Is this the recommended approach to create libraries bundles? or is better to avoid the single exports?

```
import ACMConfig from "./Ice/ACMConfig.js"
....
import Current from "./Ice/Current.js"

export { ACMConfig, Current }
```

**Comment by GGAlanSmithee** [comment]
I would say that the correct way from an API perspective is to think of it as a namespace (which is your second option). This is cleanest IMO, since you can then do `import {AMConfig} from 'ice'`. 

I also belive that your first option would prevent tree shaking. (someone please correct me if I'm wrong)

**Comment by hzlmn** [comment]
If you have isolated methods in your API, its better to export them separately. It will allow other people that will use rollup to get benefits from tree-shaking

**Comment by snuggs** [comment]
@pepone have been using https://github.com/rollup/rollup-plugin-multi-entry
to solve this problem. Let me know if you need any help configuring. /cc @GGAlanSmithee @hzlmn

**Comment by Rich-Harris** [comment]
Closing, as there's nothing to do here – the second example in the original post is the recommended approach 👍
