### ISSUE TITLE
Module Tree output

### ISSUE THREAD

**Issue by adamdbradley** [rollup/rollup#903]
Would it be possible for rollup to print out a tree of all the modules used and how they are related? Reason for the request is that I have a project where certain dependencies are still getting included, but having difficulty tracking down "why", and thought a module graph or tree would help pinpoint the culprit. Thanks

**Comment by Rich-Harris** [comment]
👍, we should do this – would just be a case of adding a `dependencies` property [here](https://github.com/rollup/rollup/blob/1d7c853ce6fabec207401a53d8210ea25f08d72e/src/Module.js#L660-L669) which contained a list of module IDs:

```js
rollup.rollup( options ).then( bundle => {
  bundle.modules.forEach( ({ id, dependencies }) => {
    console.log( `${id} has ${dependencies.length} dependencies:`, dependencies );
  });
});
```

This would only work via the JavaScript API, unless we added more logging to the CLI – #651.

**Comment by Rich-Harris** [comment]
Released in 0.35

**Comment by jharris4** [comment]
In case it helps anyone, it looks like `bundle.modules` got replaced with `bundle.cache.modules` in version 1.x.

**Comment by DesignByOnyx** [comment]
For anybody who comes here for the same reason I did, here's a handy little function for listing all of the modules which depend on another module:

```js
async function build() {
	const bundle = await rollup.rollup(config);
	const { modules } = bundle.cache;
	printModulesWhichDependOn(modules, 'lodash');
}

/**
 * Prints a list of modules which depend on `moduleName`, excluding the module itself.
 * This is useful if you need to see every module which depends on eg. "lodash".
 * 
 * @param {*} modules - a list of modules from the build (build.modules or build.cache.modules)
 * @param {*} moduleName 
 */
function printModulesWhichDependOn(modules, moduleName) {
	console.log(`MODULES WHICH DEPEND ON "${moduleName}":`);
	modules.forEach(({ id, dependencies }) => {
		if (
			id.indexOf(moduleName) === -1 &&
			dependencies.find(d => d.indexOf(moduleName) > -1)
		) {
			console.log(`  - ${id}`);
		}
	});
}
```
