### ISSUE TITLE
How to import scripts that create globals or manipulate them

### ISSUE THREAD

**Issue by moglars** [rollup/rollup#907]
I tried to bundle a custom script with d3, d3-tip and socket.io.

`import * as d3 from 'd3';`

works great because d3 is written in ES6 modules syntax.
d3-tip has the UMD syntax. It adds the function tip to the d3 object. 
Of course, d3 doesn't export the tip function and the build fails:

`Export 'tip' is not defined by`

So this leads to three questions: 
- How do I tell rollup that d3.tip() is introduced by d3-tip?
- How do I tell rollup that the d3-tip script should be included after d3?
- Are these even the right questions?

I have seen that rollup can determine which functions of d3 are used in my custom script and only adds the code that is needed for those functions to run. 
What I want to do now is

```
import 'd3-tip';
import 'socket.io-client/socket.io.js';
```

And rollup should replace the lines with the corresponding file contents. There is no need to modify these scripts somehow. I tried the CommonJS plugin to import d3-tip and socket.io but got different errors that I think are not worth tackling because these libraries are just not fully compatible with rollup.
I probably totally misunderstood the purpose of rollup because it would be so easy to write a replacement script that does what I described above.

**Comment by snuggs** [comment]
If i'm not mistaken one must use requires on UMD formats. Rollup needs corresponding  `import`/`export` statements. Unfortunately  DCE is not available to UMD / CJS modules. The traditional `require` will be used untampered.

perhaps the `options.external` collection? Doing some tests now.

**Comment by moglars** [comment]
This is the UMD of d3-tip.js
```
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module with d3 as a dependency.
    define(['d3'], factory)
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS
    module.exports = function(d3) {
      d3.tip = factory(d3)
      return d3.tip
    }
  } else {
    // Browser global.
    root.d3.tip = factory(root.d3)
  }
}(this, function (d3) {
```
if I do
`import d3Tip from 'd3-tip';` (assuming the node-resolve and commonJs plugins are installed)
`d3Tip(d3)` would extend d3 and return the tip function I need. But after bundling with rollup, d3 will not be available as a global. That gives me 
`TypeError: can't define property "tip": Object is not extensible` at line `d3.tip = factory(d3)`
I haven't tried options.external or options.globals yet and will play around with them to see if it helps. I know that the author of d3-tip probably didn't expect people to try bundle the module with rollup. Many scripts probably don't work with rollup out of the box. That's why I try to figure out what the approach with the most interoperability would be: maybe bundling d3 exclusively and concat the other files with a tool that can guess the order for the scripts with JSON files that define the dependencies.

**Comment by moglars** [comment]
I added a pull request to d3-tip library: https://github.com/Caged/d3-tip/pull/166
The UMD code I posted above was not from the main d3-tip version. There was some confusion. The bundling works fine with the modified d3-tip version with the ES2015 modules syntax. 

I will try later to bundle in socket.io.js too.

**Comment by arxpoetica** [comment]
Any luck with this @moglars?

**Comment by Rich-Harris** [comment]
Since `d3-tip` exposes itself as a UMD module, you could use [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs).

However, some older scripts don't use UMD, and just declare global variables. For those, I've just created a new plugin – [rollup-plugin-legacy](https://github.com/rollup/rollup-plugin-legacy).

So for `d3-tip`, for example, you could use it like this:

```js
// rollup.config.js
import legacy from 'rollup-plugin-legacy';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'src/index.js',
  dest: 'bundle.js',
  format: 'iife',
  moduleName: 'myBundle',
  plugins: [
    nodeResolve(),
    legacy({
      'node_modules/d3-tip/index.js': 'd3.tip'
    })
  ]
};
```

Then, in your app, you could do

```js
import tip from 'd3-tip';
var myTip = tip().attr('class', 'd3-tip').html(function(d) { return d; });
```

Alternatively, you could use named imports (useful if a script declares several things):

```js
// in config
legacy({
  'node_modules/d3-tip/index.js': { tip: 'd3.tip' }
}),

// in app
import { tip } from 'd3-tip';
```

**Comment by arxpoetica** [comment]
This is fantastic and solves many a 3rd party lib. problem. 🍔

**Comment by PlkMarudny** [comment]
But still I cannot import socket.io-client, obtaining: 

` Cannot access 'XMLHttpRequest' before initialization`, using a simple setup coming from 

`npx degit sveltejs/template min-svelte`

using the latest Rollup, and the import:

`import { io } from 'socket.io-client';` followed by:

`const socket = io();`

**Comment by PlkMarudny** [comment]
Actually, the above appears while using socket.io from the 3.x.x line only
