### ISSUE TITLE
Comments and whitespace preserved unnecessarily

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#911]
Me being anal about the quality of generated code:
### Comments of removed nodes are sometimes kept

This happens on the [Tree-shaking](http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY3ViZSUyMCU3RCUyMGZyb20lMjAnLiUyRm1hdGhzLmpzJyUzQiU1Q25jb25zb2xlLmxvZyglMjBjdWJlKCUyMDUlMjApJTIwKSUzQiUyMCUyRiUyRiUyMDEyNSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBnZXRzJTIwaW5jbHVkZWQlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3QlMkYlMkYlMjByZXdyaXRlJTIwdGhpcyUyMGFzJTIwJTYwc3F1YXJlKCUyMHglMjApJTIwKiUyMHglNjAlNUNuJTVDdCUyRiUyRiUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zISU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTVEJTdE) example:

``` js
// 0.34
'use strict';

// This function gets included
function cube ( x ) {
    // rewrite this as `square( x ) * x`
    // and see what happens!
    return x * x * x;
}

console.log( cube( 5 ) ); // 125
```

``` js
// 0.35
'use strict';

// This function isn't used anywhere, so
// Rollup excludes it from the bundle...


// This function gets included
function cube ( x ) {
    // rewrite this as `square( x ) * x`
    // and see what happens!
    return x * x * x;
}

console.log( cube( 5 ) ); // 125
```
### Extra spaces between function declarations

On the [Static namespaces](http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwRVM2JTIwbW9kdWxlcyUyMGxldCUyMHlvdSUyMGltcG9ydCUyMGFsbCUyMG9mJTIwYW5vdGhlciUyMG1vZHVsZSdzJTVDbiUyRiUyRiUyMGV4cG9ydHMlMjBhcyUyMGElMjBuYW1lc3BhY2UuLi4lNUNuaW1wb3J0JTIwKiUyMGFzJTIwYXNzZXJ0JTIwZnJvbSUyMCcuJTJGYXNzZXJ0JyUzQiU1Q24lNUNuJTJGJTJGJTIwLi4uYnV0JTIwd2UlMjBjYW4lMjBzdGF0aWNhbGx5JTIwcmVzb2x2ZSUyMHRoaXMlMjB0byUyMHRoZSU1Q24lMkYlMkYlMjBvcmlnaW5hbCUyMGZ1bmN0aW9uJTIwZGVmaW5pdGlvbiU1Q25hc3NlcnQuZXF1YWwoJTIwMSUyMCUyQiUyMDElMkMlMjAyJTIwKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhc3NlcnQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBlcXVhbCUyMCglMjBhJTJDJTIwYiUyQyUyMG1zZyUyMCklMjAlN0IlNUNuJTVDdGlmJTIwKCUyMCFtc2clMjApJTIwbXNnJTIwJTNEJTIwZm9ybWF0KCUyMCclMjVzJTIwZG9lcyUyMG5vdCUyMGVxdWFsJTIwJTI1cyclMkMlMjBhJTJDJTIwYiUyMCklM0IlNUNuJTVDdGlmJTIwKCUyMGElMjAhJTNEJTIwYiUyMCklMjB0aHJvdyUyMG5ldyUyMEVycm9yKCUyMG1zZyUyMCklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMG9rJTIwKCUyMHZhbHVlJTJDJTIwbXNnJTIwKSUyMCU3QiU1Q24lNUN0aWYlMjAoJTIwIW1zZyUyMCklMjBtc2clMjAlM0QlMjBmb3JtYXQoJTIwJyUyNXMlMjBpcyUyMG5vdCUyMHRydXRoeSclMkMlMjB2YWx1ZSUyMCklM0IlNUNuJTVDdGlmJTIwKCUyMCF2YWx1ZSUyMCklMjB0aHJvdyUyMG5ldyUyMEVycm9yKCUyMG1zZyUyMCklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGZvcm1hdCUyMCglMjBzdHIlMkMlMjAuLi5hcmdzJTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwc3RyLnJlcGxhY2UoJTIwJTJGJTI1cyUyRmclMkMlMjAoKSUyMCUzRCUzRSUyMGFyZ3Muc2hpZnQoKSUyMCklM0IlNUNuJTdEJTIyJTdEJTVEJTdE) example:

``` js
// 0.34
'use strict';

function equal ( a, b, msg ) {
    if ( !msg ) msg = format( '%s does not equal %s', a, b );
    if ( a != b ) throw new Error( msg );
}

function format ( str, ...args ) {
    return str.replace( /%s/g, () => args.shift() );
}

// ES6 modules let you import all of another module's
// exports as a namespace...
// ...but we can statically resolve this to the
// original function definition
equal( 1 + 1, 2 );
```

``` js
// 0.35
'use strict';

function equal ( a, b, msg ) {
    if ( !msg ) msg = format( '%s does not equal %s', a, b );
    if ( a != b ) throw new Error( msg );
}



function format ( str, ...args ) {
    return str.replace( /%s/g, () => args.shift() );
}

// ES6 modules let you import all of another module's
// exports as a namespace...
// ...but we can statically resolve this to the
// original function definition
equal( 1 + 1, 2 );
```

Low priority but worth dealing with eventually.

**Comment by aMarCruz** [comment]
@Rich-Harris hi,
agree on this. I published a [plugin](https://github.com/aMarCruz/rollup-plugin-cleanup) to clean the output of rollup, written to generate the next non-minified versions of [Riot](http://riotjs.com), since these comments make debugging confusing; if someone want to study the code, these are in the original sources.

Because the plugin only supports JavaScript, users should put the plugin after any transpiler, so I was thinking to implement it in `transformBundle`. Is this recommended?

**Comment by TrySound** [comment]
@aMarCruz Correct.

**Comment by aMarCruz** [comment]
@TrySound thanks, I have a few days using rollup. Thanks for your great work too!

**Comment by snuggs** [comment]
@Rich-Harris is that what's causing this? 

http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGbGV0JTIwY29tbWVudGVkJTIwJTNEJTIwXyUyMCUzRCUzRSUyMCU3QiU3RCU1Q25sZXQlMjBub29wJTIwJTNEJTIwXyUyMCUzRCUzRSUyMCU3QiU3RCU1Q24lMkYlMkZsZXQlMjBjb21tZW50ZWQyJTIwJTNEJTIwXyUyMCUzRCUzRSUyMCU3QiU3RCU1Q24lMkYlMkYlNUNuJTVDbiU1Q25sZXQlMjBoaWRkZW4lMjAlM0QlMjBfJTIwJTNEJTNFJTIwJTdCJTdEJTVDbiU1Q25jb25zb2xlLmxvZyglNjBob29yYWglM0ElMjAlMjQlN0Jmb28lN0QuanMlMkNub29wJTNBJTIwJTI0JTdCbm9vcCU3RCU2MCUyQyUyMHJlcXVpcmUpJTIyJTdEJTVEJTdE
