### ISSUE TITLE
TypeError: Cannot read property 'getName' of undefined

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#928]
I get this error after updating to version `v0.35.9` and no bundle is generated.

`0.34.13` works fine.

-------------
I'm on windows 7, Node `v6.3.0`

**Comment by TrySound** [comment]
@yairEO Can you report full stack trace?

**Comment by yairEO** [comment]
@TrySound - How can I do that? I use GULP to run a rollup task, and it looks like this:

```
gulp.task('bundleJS', function(callback) {
    var outputFileName = config.namespace + '.js',
        cache;

    rollup({
        entry   : 'js/dist/app.js',
        plugins : rollupPlugins,
        cache   : cache
    })
    .then(function (bundle) {
        var bundleSettings = {
                format    : 'umd',
            //  sourceMap : true,
                banner    : config.banner
            },
            result = bundle.generate(bundleSettings),
            mapFileName = outputFileName + '.map',
            sourceMappingURL = '\n//# sourceMappingURL='+ mapFileName;

        cache = bundle;

        // bundle file
        fs.writeFile( '../js/' + outputFileName, result.code + (bundleSettings.sourceMap ? sourceMappingURL : ''), function(){
            callback();
        });

        // map file
        if( bundleSettings.sourceMap )
            fs.writeFile( '../js/' + mapFileName, result.map.toString());
    })
    .catch(function(err){
        gutil.log( gutil.colors.white.bgRed('Rollup [catch]: ', err) );
        callback();
    })
});
```

the error message is generated from the `catch(function(err){` function

**Comment by TrySound** [comment]
```
console.log(err.stack);
```

**Comment by yairEO** [comment]
```
C:\www\UI\BUILD>gulp bundleJS
(node:41256) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please u
pdate it to a more recent version.
(node:41256) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please u
pdate it to a more recent version.
[13:17:18] Using gulpfile C:\www\UI\BUILD\gulpfile.js
[13:17:18] Starting 'bundleJS'...
[13:17:21] Rollup [catch]:  TypeError: Cannot read property 'getName' of undefined
    at C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:7219:27
    at C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:134:57
    at Array.forEach (native)
    at forOwn (C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:134:24)
    at ModuleScope.deshadow (C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:7211:3)
    at C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:5346:57
    at Array.forEach (native)
    at BundleScope.deshadow (C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:5346:16)
    at Bundle.deconflict (C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:8645:13)
    at C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:8598:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
[13:17:21] Finished 'bundleJS' after 2.21 s
```

**Comment by Havunen** [comment]
I see the same issue with following setup: https://github.com/trueadm/inferno/blob/dev/config/rollup.config.js
(inferno - dev branch) 

Updating rollup ("rollup": "^0.34.13", => "rollup": "^0.35.9") gives the same exception with OP. 
```
Treating 'stream' as external dependency
TypeError: Cannot read property 'getName' of undefined
    at /media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:7219:27
    at /media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:134:57
    at Array.forEach (native)
    at forOwn (/media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:134:24)
    at ModuleScope.deshadow (/media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:7211:3)
    at /media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:5346:57
    at Array.forEach (native)
    at BundleScope.deshadow (/media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:5346:16)
    at Bundle.deconflict (/media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:8645:13)
    at /media/sk/ssd-data/GIT/inferno/node_modules/rollup/dist/rollup.js:8598:11

> inferno-src@1.0.0-alpha8 build:prod /media/sk/ssd-data/GIT/inferno
> cross-env NODE_ENV=production babel-node --presets es2015 config/rollup.config.js
```

**Comment by TrySound** [comment]
@yairEO By the way you may return promise in gulp tasks to keep them in sync.

**Comment by yairEO** [comment]
Thanks Bogdan, I didn't know that. I use [runSequence](https://www.npmjs.com/package/run-sequence)..

**Comment by TrySound** [comment]
I meant returning promise like stream instead of calling callback.
Also can you produce some failed code?

**Comment by yairEO** [comment]
Yes I understood you meant that..
but what do you mean about failed code? you want me to paste the stack trace of a bad source files for rollup build?

**Comment by TrySound** [comment]
@yairEO Just something minimal which causes this error.

**Comment by yairEO** [comment]
Ok, I will do it tomorrow. did you test it on windows / linux yourself? maybe it will show it also with an empty entry file..

**Comment by TrySound** [comment]
We have tones of tests. This is a specific case.

**Comment by yairEO** [comment]
but tests done on one kind of OS and with the the latest Node version or different versions?
there are so many scenarios of setups out there, tests can only expose some of the issues I guess..

**Comment by TrySound** [comment]
Our code in most cases is not os specific. The problem could be only with paths. But they was fixed some time ago.

**Comment by aubergene** [comment]
I'm getting what looks like the same error with on OSX, rollup version 0.35.10

```
Cannot read property 'getName' of undefined
TypeError: Cannot read property 'getName' of undefined
    at /usr/local/lib/node_modules/rollup/src/ast/scopes/ModuleScope.js:27:29
    at /usr/local/lib/node_modules/rollup/src/utils/object.js:8:40
    at Array.forEach (native)
    at forOwn (/usr/local/lib/node_modules/rollup/src/utils/object.js:8:24)
    at ModuleScope.deshadow (/usr/local/lib/node_modules/rollup/src/ast/scopes/ModuleScope.js:19:3)
    at /usr/local/lib/node_modules/rollup/src/ast/scopes/Scope.js:87:41
    at Array.forEach (native)
    at BundleScope.deshadow (/usr/local/lib/node_modules/rollup/src/ast/scopes/Scope.js:87:17)
    at Bundle.deconflict (/usr/local/lib/node_modules/rollup/src/Bundle.js:213:14)
    at /usr/local/lib/node_modules/rollup/src/Bundle.js:166:10
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

here's my config

```js
import node from 'rollup-plugin-node-resolve';
import uglify from 'rollup-plugin-uglify';

export default {
  entry: 'src/js/simple/index.js',
  plugins: [
    node({
      jsnext: true,
      // skip: [ 'd3' ],
    }),
    // uglify()
  ],
  // external: [
  //   'd3'
  // ],
  // globals: {
  //   d3: 'd3'
  // },
  moduleName: 'simpleCharts',
  sourceMap: true,
  targets: [
    { dest: 'public/js/simpleCharts.js', format: 'iife' }
  ]
}
```

**Comment by larrybotha** [comment]
I thought I was going crazy... how can Rollup just work for everyone else and not me?!

`v0.35.12` throws the `getName` reference error, `0.34.13` works fine.

Minimal test case:

```javascript
// gulp task
gulp.task('scripts', () => {
  return rollup({
    entry: 'src/index.js',
    plugins: [
      buble(), // or babel...
      // babel({
      //   babelrc: false,
      //   exclude: 'node_modules/**',
      //   presets: [ 'es2015-rollup', 'stage-0', 'react' ]
      // }),
      commonJs({
        include: [ 'node_modules/**' ]
      }),
      resolve()
    ],
  }).then(bundle => {
    return bundle.write({
      format: 'iife',
      dest: 'dist/app.bundle.js',
    });
  })
});
```

```javascript
// src/index.js
import React from 'react';
import { render } from 'react-dom';
```

**Comment by yairEO** [comment]
Should this big bug be assigned to anyone? 
should it be labeled?

**Comment by Rich-Harris** [comment]
Looks like this is caused by `import { nonexistent } from './whatever.js'` – since there's no declaration corresponding with `nonexistent`, `declaration.getName` is an error.

Folks, some friendly advice on filing bugs: you will get a response **much quicker** if you can supply a minimal reproduction that we can investigate. Piecing things together from the scraps of evidence in this thread is very hard. 'Minimal' means no plugins (unless they're the source of the bug), and no Gulp nonsense. It's one thing for me to spend my free weekend time on this stuff, but when it turns out to be essentially user error I hope you can understand why I'm a little frustrated!

#962 fixes this error and gives you a helpful warning.

@Havunen I get the following warning with Inferno:

> Non-existent export 'hookTypes' is imported from /path/to/inferno/src/DOM/addAttributes.js by /path/to/inferno/src/DOM/shapes/rootNodeWithComponent.js

I can't find the corresponding files in the repo (some TypeScript thing I don't understand?) but if you remove `hookTypes`, you're golden.

@larrybotha You'll need to manually tell rollup-plugin-commonjs that `react-dom` exports `render` using the `namedExports` option – it can't automatically infer it from the code (because it's just re-exporting another module). See [here](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports) for more info.

@aubergene, @yairEO, afraid I can't know how to fix your cases from here, but if you use the version of Rollup I'm about to release, it will tell you.

**Comment by Havunen** [comment]
@rich-harris thanks from your input and hard work. Maybe you can change this exception to something more user friendly? This exception just looks like something related to rollup and googling it shows up this thread. Just thought its related. Thanks for help :)

**Comment by Rich-Harris** [comment]
@Havunen As of 0.35.15 (just released) you'll get the warning message above, identifying the non-existent export – no error

**Comment by hzlmn** [comment]
@Rich-Harris Hi, I get same issue with latest rollup, when  `import { Whatever } from './lib'` is not defined.
