### ISSUE TITLE
Missing Internal Base Class Dependency

### ISSUE THREAD

**Issue by deckar01** [rollup/rollup#932]
Classes that are extended, but not exported are not included in the output.

```js
// base.js

export class Base {
  foo() {
    return true;
  }
}
```

```js
// thing.js

import { Base } from './base'

export class Thing extends Base {
  bar() {
    return true;
  }
}
```

```js
// main.js

export { Thing } from './thing'
```

\> rollup main.js

```
class Thing extends Base {
  bar() {
    return true;
  }
}

export { Thing };
```

> Uncaught ReferenceError: Base is not defined

My current work around is to explicitly export the base class in the main module. 

I just want es6 module aware concatenation, but this tree shaking is spooking me. 👻  😦

**Comment by TrySound** [comment]
@deckar01 Try to pass `treeshake: false` option

**Comment by deckar01** [comment]
@TrySound Using `--no-treeshake` produces the same invalid output.

It does modify the output if I add more code to the base file:

---

**Extra code in the base with tree shaking:**

```js
// base.js

export class Base {
  foo() {
    return true;
  }
}

Base.static = true;
```

\> rollup main.js

```js
class Thing extends Base {
  bar() {
    return true;
  }
}

export { Thing };
```

> Uncaught ReferenceError: Base is not defined

---

**Extra code in the base without tree shaking:**

```js
// base.js

export class Base {
  foo() {
    return true;
  }
}

Base.static = true;
```

\> rollup --no-treeshake main.js

```js
Base.static = true;

class Thing extends Base {
  bar() {
    return true;
  }
}

export { Thing };
```

> Uncaught ReferenceError: Base is not defined

Strangely, the class declaration is removed, even though tree shaking is disabled.

**Comment by TrySound** [comment]
@deckar01 There's no such flag in rollup cli. Specify this option in config please.

**Comment by deckar01** [comment]
@TrySound I went ahead and repeated the 2 test cases from https://github.com/rollup/rollup/issues/932#issuecomment-246744860 using a config file, but the results were exactly the same.

The option for disabling tree shaking was add in #625 with tests for the command line, but it is for "debugging" purposes so it never got documented. Boolean CLI flags automatically get a corresponding `--no-*` counterpart (see the conflict, indent, and strict options).

> ## [:link: 0.26.1](https://github.com/rollup/rollup/blob/5b68b14052806364878975dc976eda1b7ea35cab/CHANGELOG.md#0261)
> 
> - Add `treeshake: false`/`--no-treeshake` option for debugging (#505)

**Comment by TrySound** [comment]
Documented
https://github.com/rollup/rollup/wiki/JavaScript-API#treeshake

**Comment by deckar01** [comment]
Should the corresponding CLI flag be added to the CLI wiki?

Either way, turning off tree shaking did not resolve the issue, so I will update the title to reflect that the bug might not be occurring in the tree shaking phase.

**Comment by deckar01** [comment]
@blobor Is this issue present in `rollup-stream 1.13.0` (`rollup ^0.35.4`), but not `rollup-stream@1.12.0` (`rollup ^0.34.10`)?

**Comment by mairatma** [comment]
@deckar01 I can confirm that, I downgraded rollup to `^0.34.0` yesterday because of this issue, and the problem disappeared.

**Comment by deckar01** [comment]
Thanks @mairatma. That means the regression is somewhere in https://github.com/rollup/rollup/compare/7ad9f69...5d5eb24. Still a lot of ground to cover, but it's nice to have some leads to follow.

**Comment by Rich-Harris** [comment]
Thanks! This is fixed in 0.35.13

**Comment by deckar01** [comment]
@Rich-Harris Thank you!

**Comment by ondras** [comment]
@Rich-Harris this very bug just happend to me with 0.36.0. Am I doing something wrong, is it a regression, a different issue or expected behavior?

**Comment by ondras** [comment]
@Rich-Harris aargh, my bad, wrong global/local rollup version. Sorry for confusion.
