### ISSUE TITLE
CloudFlare blacklisting on unpkg.com breaks rollupjs.org

### ISSUE THREAD

**Issue by bfred-it** [rollup/rollup#935]
http://rollupjs.org/ wasn't loading fully for me, `rollup.browser.js` couldn't be loaded... because I hit the [infamous CloudFlare wall](http://i.imgur.com/jIgS3uF.png) from my new condo.

I understand that this is more of a problem of mine than rollup's, but I thought I'd let you know.

**Comment by jgravois** [comment]
given that CloudFare sponsors unpkg.com, i'm scratching my head as to why they'd simultaneously blacklist it.

perhaps @mjackson just needs to change the site settings to "Essentially Off"?
https://support.cloudflare.com/hc/en-us/articles/200170096-How-do-I-turn-the-CloudFlare-captcha-challenge-page-off-

**Comment by bfred-it** [comment]
No no CloudFlare is not blacklisting that site but my ip, for whatever reason. It's part of their spam-prevention setting

**Comment by mjackson** [comment]
Oof, sorry about that. I turned the Firewall settings to Essentially Off, as @jgravois suggested. Hopefully that'll fix the issue.

**Comment by bfred-it** [comment]
Thank you! I can't check for myself since I visited the site and already did the captcha, but hopefully it will help the next person :)
