### ISSUE TITLE
omit getInteropBlock

### ISSUE THREAD

**Issue by emilos** [rollup/rollup#939]
Hey,

thanks for the great tool. I'm trying to include rollup in a bigger app and I'd like to rewrite the files to es6 step by step. I'd like to start with views first, to transpile the files one by one, and later migrate more files to finally end up with a bundle. I was wondering if the following would make sense:

Here's a simplified case, given this input:
```javascript
import View from 'core/view';
export default View.extend({});
```
I'd expect to have the following result:

```javascript
define(['core/view'], function (View) {
      'use strict';

      return View.extend({});
});
```
however the result I'm getting right now is:
```javascript
define(['core/view'], function (View) { 'use strict';
    View = 'default' in View ? View['default'] : View;
    var main = View.extend({});
    return main;
});
````

I'd like to omit the `getInteropBlock` step, to generate the code from the example 1 if possible for now. Would that make any sense or does that have some downsides? I'll happily create a PR if it makes sense.

**Comment by Rich-Harris** [comment]
I could get behind an `interop: false` option. A PR would be great, thank you!

There's a separate issue for the second part (avoiding the `return main` thing): https://github.com/rollup/rollup/issues/826
