### ISSUE TITLE
Silent output from rollup's cli

### ISSUE THREAD

**Issue by hzlmn** [rollup/rollup#940]
When using `rollup` from cli it's output nothing on finished bundle. It would be great if it produce some information about time to complete bundle and bundle's size.

 Also I would like to have `option` from cli to see what functions was eliminated from bundle.

![2016-09-14 17 04 16](https://cloud.githubusercontent.com/assets/8246283/18515311/96c894e8-7a9d-11e6-965a-9948ba6603c3.png)

**Comment by TrySound** [comment]
Tree shaking is not dead code eliminated first of all. Rollup does not add also truely conditions and some more things. So loggin every stuff is not the case. It's also useless. Don't you think so?

**Comment by hzlmn** [comment]
It could be useful for debugging purposes. It's kinda related to #903 #651

**Comment by Rich-Harris** [comment]
Yeah, I think it would be useful if Rollup printed some information to `stderr`, even if only with a `--verbose`/`-v` flag. It's covered by #651 though (we'll get round to it eventually :) so I'll close this.
