### ISSUE TITLE
"empty" variable conflict

### ISSUE THREAD

**Issue by droooney** [rollup/rollup#941]
I have a ES6 module which has a private variable "empty". I also use "socket.io-client" library which I require using CommonJS. However, rollup creates a variable with the same name in the shared namespace resulting in overriding my own one. This "empty" variable (from rollup) is used in the module [engine.io-client](https://www.npmjs.com/package/engine.io-client) in the file `engine.io.js` (which was created using [derequire](https://www.npmjs.com/package/derequire)), I suppose. The usage in the file is line 1893 `WebSocket = _dereq_('ws');`. And the "engine.io-client" module has "browser" field set to

``` javascript
{
  "ws": false,
  "xmlhttprequest-ssl": "./lib/xmlhttprequest.js"
}
```

Exactly this `_dereq_('ws')`, I suppose, causes the rollup "empty" variable appearance.
This is my rollup config:

``` javascript
const npm = require('rollup-plugin-node-resolve');
const babel = require('rollup-plugin-babel');
const builtins = require('rollup-plugin-node-builtins');
const cjs = require('rollup-plugin-commonjs');
const multi = require('rollup-plugin-multi-entry');

module.exports = {
  entry: './browser.js',
  dest: './test.js',
  format: 'iife',
  moduleName: 'D',
  sourceMap: true,
  plugins: [
    multi(),
    builtins(),
    npm({
      browser: true,
      preferBuiltins: false
    }),
    cjs({
      include: 'node_modules/**',
      exclude: 'node_modules/rollup-plugin-node-builtins/**',
      namedExports: {
        'node_modules/assert/assert.js': [
          'deepEqual',
          'deepStrictEqual',
          'notDeepEqual',
          'notEqual',
          'strictEqual'
        ]
      }
    }),
    babel({
      presets: ['es2015-rollup'],
      exclude: 'node_modules/**',
      babelrc: false
    })
  ]
};

```

Hope, I've helped you to resolve another issue, you tremendously awesome Rollup :)

PS: probably, this is related to node-resolve or CommonJS plugins but I'm not sure, that's why it's here.

**Comment by Rich-Harris** [comment]
Hi – any chance you would be able to share that repo? Would make investigation much easier if we have clear steps to reproduce 😀  thanks

**Comment by droooney** [comment]
Well. It's funny. I'm working on another machine now and for some unexpected reason I cannot reproduce the issue :). Tomorrow will have access to the computer this issue appeared on.

**Comment by droooney** [comment]
If it helps somehow: here is required simplified piece of code: 

```javascript 
// helpers.js 
const empty = document.createElement('div'); 

export function find(selector) { 
  return document.querySelector(selector) || empty; 
} 

// main.js 
import { find } from './helpers'; 
import io from 'socket.io-client'; 

console.log(find('.some-non-existent-selector')); // { default: {} } 
``
Maybe you need to change the import order, i'm not already sure. I've modified some of the code since then, didn't think I wouldn't be able to reproduce the issue :)

**Comment by Rich-Harris** [comment]
Hi, afraid I'm going to need more to work with than that – I've been trying to create a reproduction from that information for a while now and it's not going anywhere! Can you put up a repo? Thanks
