### ISSUE TITLE
Error transforming with 'babel' plugin

### ISSUE THREAD

**Issue by photonstorm** [rollup/rollup#946]
Happily using rollup on a project at home on OS X. Pulled down the same project, and set it up on Windows 10, and get the following error when issuing `rollup -c`:

```
Error transforming g:\www\beam\src\Beam.js with `babel` plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" present, consider using "es2015-rollup" instead.
```

Which I could understand if that was the case. My `rollup.config.js`:

```
import babel from 'rollup-plugin-babel';
import json from 'rollup-plugin-json';

let pkg = require('./package.json');
let external = Object.keys(pkg.dependencies);

export default {
    entry: 'src/Beam.js',
    external: external,
    plugins: [
        json(),
        babel()
    ],
    targets: [
        {
            dest: pkg['main'],
            format: 'umd',
            moduleName: 'Beam',
            sourceMap: true
        },
        {
            dest: pkg['jsnext:main'],
            format: 'es',
            sourceMap: true
        }
    ]
};
```

and my .babelrc:

```
{
    "presets": [ "es2015-rollup" ]
}
```

Running node v6.4.0. Rollup is installed globally, all of the various packages are installed locally. Using rollup 0.35.11.

**Comment by photonstorm** [comment]
For what it's worth, swapping from babel to buble works perfectly, and builds locally with no issues (in case that sheds any light on this?).

Which I guess is at least a solution for now :)

**Comment by hzlmn** [comment]
@photonstorm I guess it's an issue with `es2015-rollup`. Should be fixed with preset `es2015` and `modules:false`

related: 
   [#11](https://github.com/rollup/babel-preset-es2015-rollup/issues/11)
   [#842](https://github.com/rollup/rollup/issues/842)

**Comment by yairEO** [comment]
also related:
#993

**Comment by terkelg** [comment]
I had this problem too but only with my Travis-CI build - not on my local machine. However, the switch from ```es2015-rollup``` to ```es2015``` fixed it. Thanks!

**Comment by Rich-Harris** [comment]
There have been a few changes to rollup-plugin-babel since this issue was opened, any chance this issue is fixed already? (I don't have access to Windows right now.) If not, would you mind opening an issue on that repo, with a reproduction? Thanks

**Comment by photonstorm** [comment]
Honestly not sure, sorry, will close this for now and re-open if it manifests again.
