### ISSUE TITLE
the option 'external ' did not respect what i set

### ISSUE THREAD

**Issue by xingyuzhe** [rollup/rollup#948]
i set the option 'external ' like this:
`let external = type=== 'min' ? function () { return false } : Object.keys(pkg.dependencies)`

a.js
`import global from 'global'`
`export default { a: global.xx }`

index.js
`import a from './a'`
`export default { b: a.xx }`

i expect all modules can be merged to a single file( include  module 'global'  from npm ),  but the final bundled file always treate  the modules from npm as external  modules  and did not merge them. Am i mistaken the meaning of   ‘external’?  How do i tell rollup that i want merge all modules  to a  single file?

**Comment by Rich-Harris** [comment]
If you want to bundle dependencies from npm you need to use https://github.com/rollup/rollup-plugin-node-resolve, otherwise Rollup doesn't know how to find them.

**Comment by xingyuzhe** [comment]
@Rich-Harris thanks, it works!
