### ISSUE TITLE
Support for Google Closure format

### ISSUE THREAD

**Issue by plexus** [rollup/rollup#949]
The [Google Closure Compiler](https://developers.google.com/closure/) is an optimizing JS-to-JS compiler that's used extensively within Google, and that also forms the basis for the ClojureScript compiler.

It has its own conventions for specifying modules

``` javascript
goog.provide('goog.dom.NodeType');
goog.require('foo.bar');

goog.dom.NodeType = {... foo.bar.something() ... }
```

Would Rollup be interested in a "finalizer" to target this format? This would greatly help ClojureScript to consume 3rd party JS libraries (at least the ones using ES2015/rollup).

I have a [working prototype](https://gist.github.com/plexus/e3971543bce8840f2e076bbefeec5016) that worked to compile D3 and import it from ClojureScript. There are several things about this that need to be discussed and probably could be a lot better, and it needs tests, but I'd like to first gauge wether a PR would be welcomed here.

Thanks!

**Comment by eventualbuddha** [comment]
I don't want to speak for @Rich-Harris, but my guess is that he'd say this should be a plugin. Granted, the plugin API doesn't yet support different finalizers/output formats, but this might be a good test case for getting there.

**Comment by plexus** [comment]
Thanks for the response. If the plugin API supported this it would be just as good for us.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
