### ISSUE TITLE
Treat intro/outro/header/footer as templates

### ISSUE THREAD

**Issue by brianmhunt** [rollup/rollup#951]
... and pass useful information to them like the module name, or the current file.

The idea is to e.g. print out the name of the file where a bit of source came from with e.g.

```javascript
bundle({ intro: "// --- ${file} --- ", outro: "// ^^^ ${file} ^^^" })
```

and the output would look like e.g.

```javascript
// --- a.js ---
function a_function() { /*... */ }
// ^^^ a.js ^^^

// --- b.js ---
var b = /**/
// ^^^ b.js ^^^
```

... which turns out to be arguably necessary when you are debugging hundreds of files.

Sorry if I missed another or better way to do this, but making `intro`/`outro` (and `header`/`footer`) into templates seems the most sensible and straightforward way to do this.  That or a plugin - but that seems like it might be overkill. :)

**Comment by Rich-Harris** [comment]
I'd argue that a plugin would actually be perfect for this – the necessary APIs are already there, and it avoids adding more stuff to the core (there's always a temptation to add small innocent features, but they have a habit of breeding...). It could be done *slightly* more performantly in core, but I'm not sure it's a common enough requirement to justify the extra code.

Something like this should do the trick (with the caveat that I haven't tried it!):

```js
// rollup-plugin-wrap
import { createFilter } from 'rollup-pluginutils';
import MagicString from 'magic-string';

export default function wrap ( options ) {
  const filter = createFilter( options.include, options.exclude );

  return {
    name: 'wrap',
    transform ( code, id ) {
      if ( !filter( id ) ) return null;

      const magicString = new MagicString( code )
        .prepend( options.intro( id, code ) )
        .append( options.outro( id, code ) );

      return {
        code: magicString.toString(),
        map: magicString.generateMap({ hires: true })
      };
    }
  };
}
```

**Comment by brianmhunt** [comment]
I'll take that. :)  Closing - but feel free to re-open if you think there's something to be done here in the core.
