### ISSUE TITLE
Does closure-compiler-js source map compatible with rollup?

### ISSUE THREAD

**Issue by camelaissani** [rollup/rollup#961]
I wrote a rollup plugin for using closure-compiler-js: [rollup-plugin-closure-compiler-js](https://github.com/camelaissani/rollup-plugin-closure-compiler-js)

The unit test that checking source map worflow fails and prints this stack trace:

```
 TypeError: Cannot read property 'traceSegment' of undefined
      at node_modules/rollup/dist/rollup.js:8272:23
      at Array.forEach (native)
      at node_modules/rollup/dist/rollup.js:8270:8
      at Array.map (native)
      at Link.traceMappings (node_modules/rollup/dist/rollup.js:8267:31)
      at collapseSourcemaps (node_modules/rollup/dist/rollup.js:8390:19)
      at Bundle.render (node_modules/rollup/dist/rollup.js:8875:10)
      at Object.generate (node_modules/rollup/dist/rollup.js:9032:26)
      at test/test.js:47:36
```

Here the link to the ci build: https://travis-ci.org/camelaissani/rollup-plugin-closure-compiler-js#L168

Therefore, after many hours of investigation I am wondering if the source map is compatible with Rollup.
Could you have a look to this please?

**Comment by Victorystick** [comment]
It should be. Regardless, we shouldn't throw an error like that.

**Comment by camelaissani** [comment]
Okay let's close this issue. It seems that closure-compile-js doesn't compose source maps https://github.com/google/closure-compiler-js/issues/25

**Comment by camelaissani** [comment]
I have more details now.
The method transformBundle from my plugin implementation receives this code in input:
```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

class Route {
    constructor(uriPart) {
        this.uriPart = uriPart;
    }

    get uri() {
        return this.uriPart;
    }
}

class Router {}

exports.Route = Route;
exports.Router = Router;
```
I pass this code to closure-compile-js and it returns this compiled code:
```js
var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}};$jscomp.global=$jscomp.getGlobal(this);var module$Input_0={};Object.defineProperty(module$Input_0,"__esModule",{value:!0});var Route$$module$Input_0=function(a){this.uriPart=a};$jscomp.global.Object.defineProperties(Route$$module$Input_0.prototype,{uri:{configurable:!0,enumerable:!0,get:function(){return this.uriPart}}});var Router$$module$Input_0=function(){};
module$Input_0.Route=Route$$module$Input_0;module$Input_0.Router=Router$$module$Input_0;
```
and this source map:
```json
{
"version":3,
"file":"",
"lineCount":2,
"mappings":"AAyBA,IAAI,QAAU,CAGN,MAAQ,EAHF,CCIN,UAAY,QAAQ,CAAC,CAAD,CAAc,CACxC,MAAyB,WAAlB,EAAC,MAAO,OAAR,EAAiC,MAAjC,GAA4C,CAA5C,CACH,CADG,CAEe,WAAlB,EAAC,MAAO,OAAR,EAA2C,IAA3C,EAAiC,MAAjC,CAAmD,MAAnD,CAA4D,CAHxB,CDJ5B,CCkBd,QAAA,OAAA,CAAiB,OAAA,UAAA,CAAkB,IAAlB,CC3ChB,KAAA,eAAA,EAEDA,OAAAC,eAAA,CAAsBC,cAAtB,CAA+B,YAA/B,CAA6C,CAAEC,MAAO,CAAA,CAAT,CAA7C,CAEA,KAAMC,sBACFC,QAAW,CAACC,CAAD,CAAU,CACjB,IAAAA,QAAA,CAAeA,CADE,CADzB,QAAA,OAAA,OAAA,iBAAA,CAAA,qBAAA,UAAA,CAAA,CAAA,IAKQ,CAAA,aAAA,CAAA,CAAA,CAAA,WAAA,CAAA,CAAA,CAAA,IAAMC,QAAN,EAAM,CACN,MAAO,KAAAD,QADD,CAAN,CALR,CAAA,CAUA,KAAME,uBAAN,QAAA,EAAA,EAEAJ;cAAAA,MAAA,CAAgBA,qBAChBI,eAAAA,OAAA,CAAiBA;",
"sources":[" [synthetic:base] "," [synthetic:util/global] ","Input_0"],
"names":["Object","defineProperty","module$Input_0","value","Route","constructor","uriPart","uri","Router"]
}
```
Finally I return this compiled source and the source map to Rollup which fails with this stack:
```shell
TypeError: Cannot read property 'traceSegment' of undefined
      at node_modules/rollup/dist/rollup.js:8279:23
      at Array.forEach (native)
      at node_modules/rollup/dist/rollup.js:8277:8
      at Array.map (native)
      at Link.traceMappings (node_modules/rollup/dist/rollup.js:8274:31)
      at collapseSourcemaps (node_modules/rollup/dist/rollup.js:8397:19)
      at Bundle.render (node_modules/rollup/dist/rollup.js:8882:10)
      at Object.generate (node_modules/rollup/dist/rollup.js:9040:26)
      at test/test.js:65:42
```

**Comment by GGG-KILLER** [comment]
I dug into the rollup source and found out that when rendering a bundle, rollup [calls `transformBundle` (src/Bundle.js:422)](https://github.com/rollup/rollup/blob/fca14dbab102a9fa8efc7249287e2145583712ea/src/Bundle.js#L422), which consumes the sourceMap generated by the closure compiler.

Then, when it [calls `collapseSourcemaps` (src/Bundle.js:436)](https://github.com/rollup/rollup/blob/fca14dbab102a9fa8efc7249287e2145583712ea/src/Bundle.js#L436), the result from the `transformBundle` is passed as the parameter called [`bundleSourcemapChain` (src/utils/collapseSourcemaps.js:101)](https://github.com/rollup/rollup/blob/fca14dbab102a9fa8efc7249287e2145583712ea/src/utils/collapseSourcemaps.js#L101).
Inside `collapseSourcemaps`, [it iterates over each entry residing inside the array and then nests the current `source` entry inside a `Link` (src/utils/collapseSourcemaps.js:146-148)](https://github.com/rollup/rollup/blob/fca14dbab102a9fa8efc7249287e2145583712ea/src/utils/collapseSourcemaps.js#L146-L148) with the sourcemap set as the current entry of the iteration.

By doing that, it confuses the [`Link.prototype.traceMappings`(src/utils/collapseSourcemaps.js:23)](https://github.com/rollup/rollup/blob/fca14dbab102a9fa8efc7249287e2145583712ea/src/utils/collapseSourcemaps.js#L23) which [expects `this$1.sources[ segment[1] ]` to be the same source present before the `bundleSourcemapChain` nesting. (src/utils/collapseSourcemaps.js:32)](https://github.com/rollup/rollup/blob/fca14dbab102a9fa8efc7249287e2145583712ea/src/utils/collapseSourcemaps.js#L32).

**Comment by PaulBGD** [comment]
Any update on this? Would love to have support for closure compiler.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
