### ISSUE TITLE
Rollup not including html / css with jspm and angular2

### ISSUE THREAD

**Issue by born2net** [rollup/rollup#965]
I am trying to roll everything up using angular 2 project via:

```
jspm build src/App.js " + paths.dist + "/" + paths.targetJS + ' --format global --skip-source-maps
```

and getting the following errors:
![capture](https://cloud.githubusercontent.com/assets/5090936/18638690/f45df5ca-7e45-11e6-8f0f-ee14bef1c427.PNG)

I am wondering how do I get rollup to embed all my resources?

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by Victorystick** [comment]
@born2net Have you run this by the JSPM folks? You're running `jspm build` and not `rollup -c` after all.

**Comment by born2net** [comment]
I ended up with a diff solution.
I am using jspm bundle with !text raw plugin.

```
import AdnetNetworkPackageViewerTemplate from "./AdnetNetworkPackageViewer.html!text"; 
@Component({
    template: AdnetNetworkPackageViewerTemplate, /*prod*/
    selector: 'AdnetNetworkPackageViewer',
    moduleId: __moduleName    
})
```

tx for checking in,

Sean
