### ISSUE TITLE
0.35.x breaking Angular 1.x dependency injection?

### ISSUE THREAD

**Issue by scotttrinh** [rollup/rollup#968]
[rollup.org repro](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBhbmd1bGFyJTIwZnJvbSUyMCdhbmd1bGFyJyUzQiU1Q24lNUNuaW1wb3J0JTIwd2lkZ2V0JTIwZnJvbSUyMCcuJTJGd2lkZ2V0Lm1vZHVsZSclM0IlNUNuJTVDbmFuZ3VsYXIubW9kdWxlKCdteUFwcCclMkMlMjAlNUIlNUNuJTIwJTIwJTIwJTIwd2lkZ2V0JTVDbiUyMCUyMCU1RCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyd2lkZ2V0Lm1vZHVsZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBhbmd1bGFyJTIwZnJvbSUyMCdhbmd1bGFyJyUzQiU1Q25pbXBvcnQlMjBlbGVjdHJvbiUyMGZyb20lMjAnZWxlY3Ryb24nJTNCJTVDbiU1Q25pbXBvcnQlMjB3aWRnZXQlMjBmcm9tJTIwJy4lMkZ3aWRnZXQuY29tcG9uZW50JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGFuZ3VsYXIubW9kdWxlKCd3aWRnZXQnJTJDJTIwJTVCJTVEKSU1Q24lMjAlMjAudmFsdWUoJ2VsZWN0cm9uJyUyQyUyMGVsZWN0cm9uKSU1Q24lMjAlMjAuY29tcG9uZW50KCd3aWRnZXQnJTJDJTIwd2lkZ2V0KSU1Q24lMjAlMjAubmFtZSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ3aWRnZXQuY29tcG9uZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTIwJTIwdGVtcGxhdGUlM0ElMjAlNjBpJ20lMjBhJTIwd2lkZ2V0ISU2MCUyQyU1Q24lMjAlMjBjb250cm9sbGVyJTNBJTIwV2lkZ2V0Q29udHJvbGxlciU1Q24lN0QlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwV2lkZ2V0Q29udHJvbGxlcihlbGVjdHJvbiklMjAlN0IlNUNuJTIwJTIwZWxlY3Ryb24uZnVuYygpJTNCJTVDbiU3RCUyMiU3RCU1RCU3RA==)

Something in the tree shaking rewrite broke using Rollup with Angular 1.x in a common pattern. In the repro, you can see that we're registering the `electron` dependency in the `widget.module.js` module declaration, which gets injected by Angular's dependency injector based on its name, but since Rollup is trying to avoid the collision with the `electron` variable, it renames the function parameter in the controller to `electron$$1` which breaks Angular's injector.

There is a way around this ([don't use implicit injection](https://docs.angularjs.org/guide/di)), but this is a breaking change for us Angular users. Not sure if there is anything `rollup` can or should do about it, but I wanted to raise the issue to see if it warrants discussion and to give other Angular 1.x developers a head-start on this problem.

**Comment by Victorystick** [comment]
Rollup doesn't guarantee that variables/parameter names remain the same when bundled. As far as I know, implicit injection is not an encouraged practice.

Why not add the `$inject` property? Or get a pre-processor to do it for you. I think there are tools (e.g. Closure Compiler) that does it given an `@ngInject` JSDoc annotation.

```js
/** @ngInject */
function foo($http, bar) {
  ...
}
```

**Comment by scotttrinh** [comment]
Understood and agreed. I mostly meant to bring this up as it was unexpected and seemed like perhaps worth mentioning somewhere. Maybe talking about the lack of guarantee somewhere in the documentation?

I've used ng-annotate before, so I appreciate your suggestion about making a plugin for it! I'll put it in my todo list and link to this issue if/when I get it done so anyone searching for this issue can benefit from it.

Thanks!

**Comment by scotttrinh** [comment]
Just a heads up here that [I attempted to make a plugin](https://gitlab.com/scotttrinh/rollup-plugin-ng-annotate), but `ng-annotate` throws an error if fed an ES6 module, and it won't work if you feed it the bundle since the argument names have already been mutated.

Is there a way to get the contents of each file without the `import`/`export` statements somewhere in the plugin architecture? If not, this might be an issue that I bring up with the ng-annotate folks.

**Comment by Victorystick** [comment]
The `import`/`export` statements have to be in the code _after any plugin transforms_ at which time they're passed to Rollup itself. Without those statements, Rollup can't work its magic.

Bringing it up with the people behind ng-annotate sounds like a great idea.
