### ISSUE TITLE
Visualising dependency graph

### ISSUE THREAD

**Issue by ondras** [rollup/rollup#971]
This is just a question, not a bug.

Is it somehow possible (ideally without writing a new plugin) to make rollup output the dependency graph it collects when traversing source files? The DOT (graphviz) language comes to mind, but any other format would be feasible as well.

**Comment by hzlmn** [comment]
If I understand you right, you can use `dependencies` property via API. See here #903.
And then plug data to some plotting library.

**Comment by ondras** [comment]
@hzlmn I see, this should do the trick. Will try tomorrow and see how this works out.

**Comment by Victorystick** [comment]
@ondras Closing as resolved. :smile:

**Comment by ondras** [comment]
Yes, please :)
