### ISSUE TITLE
else if branches with false condition dropped incorrectly in generated code

### ISSUE THREAD

**Issue by yyx990803** [rollup/rollup#973]
[repro](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJtb2R1bGUuZXhwb3J0cyUyMCUzRCUyMGZ1bmN0aW9uJTIwdGVzdCUyMCgpJTIwJTdCJTVDbiUyMCUyMGlmJTIwKGElMjAlM0UlMjAwKSUyMCU3QiU3RCUyMGVsc2UlMjBpZiUyMChmYWxzZSklMjAlN0IlN0QlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmFuc3dlci5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwNDIlM0IlMjIlN0QlNUQlN0Q=)

It seems when the condition for an `else if` branch is deterministically false (`false`, or something like `'production' === 'production'`), rollup is being smart and trying to drop the branch, however outputting incorrect code.

This happens with all versions `>=0.35.0`.

**Comment by Victorystick** [comment]
Nice catch! Thanks.

**Comment by Victorystick** [comment]
@yyx990803 Got a patch on its way. You can expect it in 10 hours, after I've gotten some sleep. :sleeping:

**Comment by Rich-Harris** [comment]
Released 0.36.1 with the fix – thanks
