### ISSUE TITLE
index.js is not implied when importing directory

### ISSUE THREAD

**Issue by httpdigest** [rollup/rollup#974]
It is a common case to encounter imports like this:
```JavaScript
import { MyComponent } from './app/components';
```
where app/components is a directory containing various JavaScript files, including a `index.js` file.
When bundling the application with Webpack 2, Webpack 2 seems to correctly? imply that `index.js` is meant.
But rollup 0.36.0 does not do this.

Instead it outputs:
`Could not resolve './app/components' from d:\...\main.js`

**Comment by TrySound** [comment]
@httpdigest It's node resolve responsibility. You can try https://github.com/rollup/rollup-plugin-node-resolve

**Comment by httpdigest** [comment]
Thanks for mentioning this resolve plugin.
Does this mean that rollup standalone cannot resolve node modules and also not ES modules that you import via the directory name (for implied index.js)?

**Comment by TrySound** [comment]
@httpdigest It means imports are not found and not inlined. `imports` will be comverted in `requires` when used commonjs format or in global variables for umd/iife.

`index.js` is commonjs thing too. 

Out of the box rollup don't do anything with not relative paths.
