### ISSUE TITLE
[bug] Not all statements are outputted.

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#980]
I have the following example: https://goo.gl/aFy6no

Notice in the resulting output that the `new C` line is nowhere to be found.

**Comment by trusktr** [comment]
If I wrap the `new C` line with something, it will show up: https://goo.gl/cklUVj

**Comment by Victorystick** [comment]
Side-effects in super constructors don't appear to be tracked.

**Comment by Rich-Harris** [comment]
This is [fixed](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQyUyMGZyb20lMjAnLiUyRkMnJTVDbm5ldyUyMEMlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMkEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQyUyMGZyb20lMjAnLiUyRkMnJTVDbiU1Q252YXIlMjBBJTVDbiU1Q25pbml0QSgpJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwaW5pdEEoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpZiUyMChBKSUyMHJldHVybiU1Q24lNUNuJTIwJTIwJTIwJTIwQSUyMCUzRCUyMGNsYXNzJTIwQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zdHJ1Y3RvcigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKEMpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjAlN0JBJTIwYXMlMjBkZWZhdWx0JTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJDLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEElMkMlMjAlN0Jpbml0QSU3RCUyMGZyb20lMjAnLiUyRkEnJTVDbiU1Q25pbml0QSgpJTVDbiU1Q25jbGFzcyUyMEMlMjBleHRlbmRzJTIwQSUyMCU3QiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCQyUyMGFzJTIwZGVmYXVsdCU3RCUyMiU3RCU1RCU3RA==), finally, via #1234. Thanks
