### ISSUE TITLE
[bug] Truthy if statement body missing in output

### ISSUE THREAD

**Issue by btd** [rollup/rollup#981]
Hello. I noticed regression when building react with NODE_ENV != production. [Example](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTVDbiUyRioqJTVDbiUyMColMjBDb3B5cmlnaHQlMjAyMDE2LXByZXNlbnQlMkMlMjBGYWNlYm9vayUyQyUyMEluYy4lNUNuJTIwKiUyMEFsbCUyMHJpZ2h0cyUyMHJlc2VydmVkLiU1Q24lMjAqJTVDbiUyMColMjBUaGlzJTIwc291cmNlJTIwY29kZSUyMGlzJTIwbGljZW5zZWQlMjB1bmRlciUyMHRoZSUyMEJTRC1zdHlsZSUyMGxpY2Vuc2UlMjBmb3VuZCUyMGluJTIwdGhlJTVDbiUyMColMjBMSUNFTlNFJTIwZmlsZSUyMGluJTIwdGhlJTIwcm9vdCUyMGRpcmVjdG9yeSUyMG9mJTIwdGhpcyUyMHNvdXJjZSUyMHRyZWUuJTIwQW4lMjBhZGRpdGlvbmFsJTIwZ3JhbnQlNUNuJTIwKiUyMG9mJTIwcGF0ZW50JTIwcmlnaHRzJTIwY2FuJTIwYmUlMjBmb3VuZCUyMGluJTIwdGhlJTIwUEFURU5UUyUyMGZpbGUlMjBpbiUyMHRoZSUyMHNhbWUlMjBkaXJlY3RvcnkuJTVDbiUyMColNUNuJTIwKiUyMCU0MHByb3ZpZGVzTW9kdWxlJTIwUmVhY3RJbnZhbGlkU2V0U3RhdGVXYXJuaW5nSG9vayU1Q24lMjAqJTJGJTVDbiU1Q24ndXNlJTIwc3RyaWN0JyUzQiU1Q24lNUNudmFyJTIwd2FybmluZyUyMCUzRCUyMGZ1bmN0aW9uKCklN0IlN0QlM0IlNUNuJTVDbmlmJTIwKCU1QyUyMmRldmVsb3BtZW50JTVDJTIyJTIwISUzRCUzRCUyMCdwcm9kdWN0aW9uJyklMjAlN0IlNUNuJTIwJTIwdmFyJTIwcHJvY2Vzc2luZ0NoaWxkQ29udGV4dCUyMCUzRCUyMGZhbHNlJTNCJTVDbiU1Q24lMjAlMjB2YXIlMjB3YXJuSW52YWxpZFNldFN0YXRlJTIwJTNEJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlNUMlMjJkZXZlbG9wbWVudCU1QyUyMiUyMCElM0QlM0QlMjAncHJvZHVjdGlvbiclMjAlM0YlMjB3YXJuaW5nKCFwcm9jZXNzaW5nQ2hpbGRDb250ZXh0JTJDJTIwJ3NldFN0YXRlKC4uLiklM0ElMjBDYW5ub3QlMjBjYWxsJTIwc2V0U3RhdGUoKSUyMGluc2lkZSUyMGdldENoaWxkQ29udGV4dCgpJyklMjAlM0ElMjB2b2lkJTIwMCUzQiU1Q24lMjAlMjAlN0QlM0IlNUNuJTdEJTVDbiU1Q252YXIlMjBSZWFjdEludmFsaWRTZXRTdGF0ZVdhcm5pbmdIb29rJTIwJTNEJTIwJTdCJTVDbiUyMCUyMG9uQmVnaW5Qcm9jZXNzaW5nQ2hpbGRDb250ZXh0JTNBJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBwcm9jZXNzaW5nQ2hpbGRDb250ZXh0JTIwJTNEJTIwdHJ1ZSUzQiU1Q24lMjAlMjAlN0QlMkMlNUNuJTIwJTIwb25FbmRQcm9jZXNzaW5nQ2hpbGRDb250ZXh0JTNBJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBwcm9jZXNzaW5nQ2hpbGRDb250ZXh0JTIwJTNEJTIwZmFsc2UlM0IlNUNuJTIwJTIwJTdEJTJDJTVDbiUyMCUyMG9uU2V0U3RhdGUlM0ElMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHdhcm5JbnZhbGlkU2V0U3RhdGUoKSUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTNCJTVDbiU1Q252YXIlMjBSZWFjdEludmFsaWRTZXRTdGF0ZVdhcm5pbmdIb29rXzElMjAlM0QlMjBSZWFjdEludmFsaWRTZXRTdGF0ZVdhcm5pbmdIb29rJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwUmVhY3RJbnZhbGlkU2V0U3RhdGVXYXJuaW5nSG9va18xJTNCJTVDbmV4cG9ydCUyMCU3QiUyMFJlYWN0SW52YWxpZFNldFN0YXRlV2FybmluZ0hvb2tfMSUyMGFzJTIwX19tb2R1bGVFeHBvcnRzJTIwJTdEJTNCJTVDbiUyMiU3RCU1RCU3RA==)

**Comment by btd** [comment]
Maybe this would help. I tried to investigate this issue.
Such if:
```js
if ("development" !== 'production') {
  var processingChildContext = false;

  var warnInvalidSetState = function () {
    "development" !== 'production' ? warning(!processingChildContext, 'setState(...): Cannot call setState() inside getChildContext()') : void 0;
  };
}
```
First correctly replaced with just block in IfStatement .render:
```js
{
  var processingChildContext = false;

  var warnInvalidSetState = function () {
    "development" !== 'production' ? warning(!processingChildContext, 'setState(...): Cannot call setState() inside getChildContext()') : void 0;
  };
}
```
In the same .render it call .consiquent.render -> which is BlockStatement -> which call Statement.prototype.render which just remove block. I honestly not such how correct fix should look.

**Comment by Victorystick** [comment]
Probably related to #985.

**Comment by btd** [comment]
Yep. Sorry I missed that issue.

**Comment by btd** [comment]
Ahh, that appeared after mine. Will stop to create noise.
