### ISSUE TITLE
source map generated by rollup miss 'file' property

### ISSUE THREAD

**Issue by ash0080** [rollup/rollup#986]
I do not know if it's a bug, because it's too trivial...
The source map generated by rollup miss 'file' property like this

`
{"version":3,"file":null,"sources":["..
`

but, without the file name,  WebStorm will ignore the source map, so you can't debug in it.
thought it's easy to be fixed manually, but with --watch, means very annoying.

rollup version 0.36.0 with rollup-plugin-typescript

**Comment by marvinhagemeister** [comment]
I'm running into a similar problem in the chrome debug extension for vscode which complains about not finding the correct file names.

**Comment by ash0080** [comment]
@marvinhagemeister Yes, file property is optional, so you can debug it in Chrome, but seems the IDEs need the anchor to map the right files in source

**Comment by Rich-Harris** [comment]
I can't reproduce this, is it still happening with the current version? If so, [please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) – thanks

**Comment by gnomesley** [comment]
This only happens when using plugins.
Here is a repro: https://github.com/gnomesley/rollup-sourcemap-file

**Comment by Rich-Harris** [comment]
Thanks — fixed in 0.40.2
