### ISSUE TITLE
string '//# sourceMappingURL=' gets removed

### ISSUE THREAD

**Issue by thisconnect** [rollup/rollup#988]
http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYWRkTWFwcGluZyUyMGZyb20lMjAnLiUyRnRlc3QuanMnJTNCJTVDbmNvbnNvbGUubG9nKCUyMGFkZE1hcHBpbmcoJTIwJ3Rlc3QnJTIwKSUyMCklM0IlNUNuY29uc29sZS5sb2coJyU1QyU1Q24lMkYlMkYlMjMlMjBzb3VyY2VNYXBwaW5nVVJMJTNEJyklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydGVzdC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBhZGRNYXBwaW5nJTIwKCUyMG9yZyUyMCklMjAlN0IlNUNuJTVDdHJldHVybiUyMG9yZyUyMCUyQiUyMCclNUMlNUNuJTJGJTJGJTIzJTIwc291cmNlTWFwcGluZ1VSTCUzRCclNUNuJTdEJTIyJTdEJTVEJTdE

**Comment by Victorystick** [comment]
See [this source file](https://github.com/rollup/rollup/blob/master/src/utils/sourceMappingURL.js) for how Rollup circumvents this issue; and where it [introduces it](https://github.com/rollup/rollup/blob/master/src/Module.js#L71-L76).

**Comment by thisconnect** [comment]
Do you consider this a bug?

**Comment by Victorystick** [comment]
I think it is, and the same applies to any other tools that indiscriminately remove all occurrences of that string.

**Comment by Permutatrix** [comment]
[Check this out.](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIzJTVDbnNvdXJjZU1hcHBpbmdVUkwlM0Qnc29tZXRoaW5nJyUzQiUyMiU3RCU1RCU3RA==) Even if it's really a comment, the regular expression has a `\s` in the middle of it, which will match the end of a multiline string.

**Comment by thisconnect** [comment]
thank you!

**Comment by Rich-Harris** [comment]
Released 0.38 with the fix

**Comment by Permutatrix** [comment]
@Rich-Harris It's a lot better but still isn't entirely fixed. [For instance, @thisconnect's original example could be rewritten like this.](http://rollupjs.org/?version=0.38.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYWRkTWFwcGluZyUyMGZyb20lMjAnLiUyRnRlc3QuanMnJTNCJTVDbmNvbnNvbGUubG9nKCUyMGFkZE1hcHBpbmcoJTIwJ3Rlc3QnJTIwKSUyMCklM0IlNUNuY29uc29sZS5sb2coJTYwJTVDbiUyRiUyRiUyMyUyMHNvdXJjZU1hcHBpbmdVUkwlM0QlNjApJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRlc3QuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwYWRkTWFwcGluZyUyMCglMjBvcmclMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjBvcmclMjAlMkIlMjAlNjAlNUNuJTJGJTJGJTIzJTIwc291cmNlTWFwcGluZ1VSTCUzRCU2MCU1Q24lN0QlMjIlN0QlNUQlN0Q=) I'll leave it up to you whether this edge case is worth worrying about.

**Comment by Rich-Harris** [comment]
@Permutatrix yeah, I missed that – fixed by https://github.com/rollup/rollup/pull/1171
