### ISSUE TITLE
tree-shaking broken with same variable names?

### ISSUE THREAD

**Issue by mrtnbroder** [rollup/rollup#992]
[Broken](http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBvbmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZhbGwuanMnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhvbmUpJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm9uZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMG9uZSUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCglN0IlNUNuJTIwJTIwb25lJTNBJTIweCU1Q24lN0QpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmFsbC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBvbmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZvbmUuanMnJTVDbmltcG9ydCUyMCU3QiUyMHR3byUyMCU3RCUyMGZyb20lMjAnLiUyRnR3by5qcyclNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwb25lJTIwJTNEJTIwb25lKDEpJTVDbmV4cG9ydCUyMGNvbnN0JTIwdHdvJTIwJTNEJTIwdHdvKDIpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnR3by5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHR3byUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMCglN0IlNUNuJTIwJTIwdHdvJTNBJTIweCU1Q24lN0QpJTIyJTdEJTVEJTdE) vs [Expected](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBvbmVzJTIwJTdEJTIwZnJvbSUyMCcuJTJGYWxsLmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2cob25lcyklM0IlMjAlMkYlMkYlMjAxMjUlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyb25lLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwb25lJTIwJTNEJTIwKHgpJTIwJTNEJTNFJTIwKCU3QiU1Q24lMjAlMjBvbmUlM0ElMjB4JTVDbiU3RCklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYWxsLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG9uZSUyMCU3RCUyMGZyb20lMjAnLiUyRm9uZS5qcyclNUNuaW1wb3J0JTIwJTdCJTIwdHdvJTIwJTdEJTIwZnJvbSUyMCcuJTJGdHdvLmpzJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBvbmVzJTIwJTNEJTIwb25lKDEpJTVDbmV4cG9ydCUyMGNvbnN0JTIwdHdvcyUyMCUzRCUyMHR3bygyKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0d28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjB0d28lMjAlM0QlMjAoeCklMjAlM0QlM0UlMjAoJTdCJTVDbiUyMCUyMHR3byUzQSUyMHglNUNuJTdEKSUyMiU3RCU1RCU3RA==)

I actually expected the outcome to be something like this for the first version:

``` js
'use strict';

const one$ = (x) => ({
  one: x
})

const one = one$(1)

console.log(one);
```

if you change the variable names within `all.js` to something else than `one` and `two`, and import the now renamed variable within the `main.js` module, it works.

**Comment by nuintun** [comment]
also broken names at like this:

>is.js
```js
export function fn(value){
  return Object.prototype.toString(value) === '[object Function]';
}
```
>main.js
```js
import * as Is from './is.js';

export function apply(fn, context, args) { 
  switch (args.length) {
    // faster
    case 0:
      return fn.call(context);
    case 1:
      return fn.call(context, args[0]);
    case 2:
      return fn.call(context, args[0], args[1]);
    case 3:
      return fn.call(context, args[0], args[1], args[2]);
    default:
      // slower
      return fn.apply(context, args);
  }
}

export function bind(callback, context) {
  var fn = function(){
    return apply(callback, context, argument);
  }
  
  // // or
  // function fn(){
  //   return apply(callback, context, argument);
  // }
  
  return fn;
}

Is.fn(isNaN);
apply(isNaN);
bind(isNaN);
```
after:
>bundle.js
```js
(function (exports) {
  'use strict';

  function fn(value){
    return Object.prototype.toString(value) === '[object Function]';
  }

  function apply(fn$$1, context, args) { 
    switch (args.length) {
      // faster
      case 0:
        return fn$$1.call(context);
      case 1:
        return fn$$1.call(context, args[0]);
      case 2:
        return fn$$1.call(context, args[0], args[1]);
      case 3:
        return fn$$1.call(context, args[0], args[1], args[2]);
      default:
        // slower
        return fn$$1.apply(context, args);
    }
}

function bind(callback, context) {
  var fn$$1 = function(){
    return apply(callback, context, argument);
  };
  
  // // or
  // function fn(){
  //   return apply(callback, context, argument);
  // }
  
  return fn$$1;
}

fn(isNaN);
apply(isNaN);

exports.apply = apply;
exports.bind = bind;
}((this.bundle = this.bundle || {})));
```

**Comment by Victorystick** [comment]
@nuintun `bind(isNaN)` does not have any side-effects and is therefore safe to eliminate from the bundle. :+1:

**Comment by Victorystick** [comment]
@mrtnbroder Looking at your broken example again, I see the real the issue. You're redeclaring `one`!
```js
import { one } from './one.js';
//        ^ is unused, and therefore removed from the bundle.

export const one = one(1);
//            ^-----^
//               These are the same variable.
```

Which is why your bundle ends up like this:
```js
const one$$1 = one$$1(1);

exports.one = one$$1;
```

So no tree-shaking bug. Although, Rollup should inform the user when you're shadowing an import. #1137

**Comment by nuintun** [comment]
@Victorystick Yes, variables and functions being renamed is expected behaviour in some case. but In ```bind``` and ```apply``` function ```fn``` a block scope local variable, so it no necessary change name.
