### ISSUE TITLE
plugins order of excecution 

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup#996]
Hi, is the order of plugins execution nontenured?
I have a transform plugin which **must** run before the `babel` plugin, and it seems to not be running at the order the Array of plugins was set to be.

I have lines of code with things like `[SERVERPATH]` which make no sense for Babel and throws an error for them, unless those are replaced with a real meaningful string via basic rollup transform:

    // .. rollup plugins Array creation
    rollupPlugins = [];

    var rollupPlugins__transform = {
            transform( code, id ){
                return code
                    .replace(/\[SERVERPATH]/g, config.serverPath)
                    .replace(/\[prodUrl]/g, config.prodUrl)
                    .replace(/mocks\//g, config.serverPath + '/BUILD/mocks/');
            }
        },
        rollupPlugins__babel = {
            presets        : [['es2015', {"modules": false}]], //['es2015-rollup'],
            runtimeHelpers : true,
            exclude        : 'node_modules/**',
            plugins        : ["external-helpers"]
        },
        rollupPlugins__uglify = uglifyRollup(uglify_settings);

    rollupPlugins.push(rollupPlugins__transform);
    rollupPlugins.push(eslintRollup(eslint_settings));
    rollupPlugins.push(babelRollup(rollupPlugins__babel));

    // .. later
    rollup({
            entry   : 'app.js',
            plugins : rollupPlugins
        })
        .then(function (bundle) {
            // ... irrelevant code
        });

**Comment by Victorystick** [comment]
Plugins are executed in order. What behaviour are you having, and what do you want?

**Comment by yairEO** [comment]
Create an entry file with some ES2015 (for babel) and some "variable" (`FOO`) which will be transformed:

    (()=>{
        'test me string'.replace([FOO]/, 1);
    })()


setup Rollup with plugins:

    // Define rollup plugins
    var rollupPlugins = [],
        rollupPlugins__transform = {
            transform( code, id ){
                return code.replace(/\[FOO]/g, '/test')
            }
        },
        rollupPlugins__babel = {
            presets        : [['es2015', {"modules": false}]], //['es2015-rollup'],
            runtimeHelpers : true,
            exclude        : 'node_modules/**',
            plugins        : ["external-helpers"]
        };

    rollupPlugins.push(rollupPlugins__transform);
    rollupPlugins.push(rollupPlugins__babel);

    // create the bundle
    rollup({
        entry   : 'foo.js',
        plugins : rollupPlugins
    })
    .then(function (bundle) {
        var result = bundle.generate();

        // bundle file
        fs.writeFile( 'foo.js', result.code);
    })
    .catch(function(err){
        gutil.log( gutil.colors.white.bgRed('Rollup [catch]: ', err.stack) );
    })

**Comment by yairEO** [comment]
Wait I am investigating more, seems like it works in another setup

**Comment by yairEO** [comment]
Sorry for have wasted your time, it was a mistake of my part which had led me to the wrong conclusion. I'm very deeply sorry! please continue your nice day and have no memory of this ticket.
