### ISSUE TITLE
Rollup es6 modules not playing well with others

### ISSUE THREAD

**Issue by fheidrich** [rollup/rollup#998]
I have a problem integrating my application, which uses requireJS+babel+transform-es2015-modules-amd with D3, which uses rollup.

Apparently both rollup and babel will Object.defineProperty(exports, '__esModule', { value: true }); on its module. But babel, on the transpiled code, the format of the module is different.

Here is an example for babel transpiled code:
````
define(['exports', 'd3', 'leaflet'], function (exports, _d, _leaflet) {
    'use strict';

    Object.defineProperty(exports, "__esModule", {
        value: true
    });

    var _d2 = _interopRequireDefault(_d);

    var _leaflet2 = _interopRequireDefault(_leaflet);

    function _interopRequireDefault(obj) {
        return obj && obj.__esModule ? obj : {
            default: obj
        };
    }

````
Note the _interopRequireDefault, it makes 
_leaflet2 = {default: _leaflet}
But it doesn't do the same for _d2, as _d has __esModule set (so babel thinks _d already is an esModule), but it is from a different system (rollup), which doesn't need the {default: value} format.

I did suggest a possible fix in https://github.com/d3/d3/issues/2985
The idea is for the rollup generated code to only set __esModule in the case
if (typeof exports === 'object' && typeof module !== 'undefined') {
 Object.defineProperty(exports, '__esModule', { value: true });
}

https://github.com/d3/d3/issues/2985 has more details there.

**Comment by mbostock** [comment]
If you’re using Babel, you probably want to configure it to pull in the ES2015 source (the [module field](https://github.com/d3/d3/blob/master/package.json#L20) in the package.json, or the older jsnext:main field). It’s possible that the default behavior is to pull in the UMD bundle, which is probably a bad idea given that you’re running it through Babel anyway. Have you configured Babel accordingly?

**Comment by fheidrich** [comment]
Hi Mike, not sure I follow, D3 for me is a bower dependency (not at all mentioned in my build or package.json). Babel transpiles my es6 code to requireJS/AMD, and it will work nicely with 3rd-party UMD bundles, as these will be loaded as AMD as well.

I'm not expert in neither, but I do fell it is the __esModule that is burning me, as both frameworks use the same flag, but the schema of the es6 modules in each is slightly different.

 I added a bit hacky work around for my problem, during my app bootstrapping I use:
````
require(['ojs/ojcore', 'knockout', 'router', 'jquery', 'moment', 'd3', 'leaflet', 'ojs/ojrouter'],
function(oj, ko, router, $, moment, d3) {

    // D3.js version 4 uses rollup es6 module
    // which do work with transform-es2015-modules-amd.
    // See https://github.com/d3/d3/issues/2985
    // See https://github.com/rollup/rollup/issues/998
    // The following lines work as a work around.
    if (d3.__esModule && !d3.default) {
        d3.default = d3;
    }
````

**Comment by mbostock** [comment]
I don’t recommend using Bower to install D3. D3’s support for Bower was deprecated in 4.0 and will be going away in 5.0, and if you use Bower to install D3 you will *only* get the precompiled UMD bundle and not the ES2015 source you will need for compatibility with Babel and other modern (ES2015+) toolchains.

**Comment by fheidrich** [comment]
Understood, thanks for letting me now.

**Comment by RossRogers** [comment]
Breadcrumbs for future google searches:

I was hitting a similar issue to this one, where using es6 with code like:

    import foo from './util/bar.jsx';

Would have this same issue as @fheidrich.  Whereas doing

    import * as bar from './util/bar.jsx';

and referencing `bar.foo` would work and have the `default` field in the module import.

However, you can make this work:

    import foo from './util/bar.jsx';

If you define `foo` using the `default` keyword like:

    export default function foo() { /*...*/  }

**Comment by fheidrich** [comment]
In my code I use
````
import d3 from 'd3'
````
the way d3 is exported I cannot change.

**Comment by mbostock** [comment]
D3 has no default export, so that’s an invalid import. As noted in the README, you need to

```js
import * as d3 from "d3";
```

if you want to import everything.

**Comment by fheidrich** [comment]
Thanks @mbostock, that worked!
I totally missed the note on the README, my bad.

**Comment by fheidrich** [comment]
Thanks everyone for helping me out here!
As far as my testing goes d3 es2015 modules are working fine with my babel es2015 modules.
